### ISSUE TITLE
knex.raw identifier binding ?? does not quote Table/Column name correctly

### ISSUE THREAD

**Issue by elhigu** [tgriesser/knex#1003]
When I try to use knex.raw to convert case sensitive table / column names to quoted sql identifiers, it does not seem to work as expected:

```js
knex('myTable').where('MyTable.myColumn', '=', knex.raw('??', ['OtherTable.myColumn']) ).toString()
```
outputs:
```sql
select * from "myTable" where "MyTable"."myColumn" = "OtherTable.myColumn"
```

when last column reference should be quoted `"OtherTable"."myColumn"`. Should this work or am I just trying to do it wrong? 

ps. I know I can use knex client internal functions for quoting this, but that is not exposed official API...

**Comment by rhys-vdw** [comment]
What is `??`? It doesn't seem to be documented.

**Comment by chrisbroome** [comment]
@rhys-vdw It's for quoting things that should be identifiers like table names, column names, etc.

For what it's worth, I've also experienced this issue, and I've had to work around it by creating `knex.raw('??.??', [tableName, columnName])` objects and passing them around while `toString`ing in strategic places to make it work. It's definitely not the most ideal situation, but I haven't had to parameterize table/view/column names enough in daily usage for it to be a big deal.

**Comment by rhys-vdw** [comment]
Thanks @chrisbroome. I see there is a test [here](https://github.com/tgriesser/knex/blob/775d6c2af7106b38d53083bd5185c189f2fcd01f/test/tape/raw.js#L12-L18).

We can't automatically split on the `.` because it's possible to have period in a table name, no?

To close this issue, the knew.raw documentation should be updated to include this operator. Probably should include an example of the `??.??` usage.

**Comment by elhigu** [comment]
@chrisbroome nice work around, hadn't thought of that :)

@rhys-vdw I still think that this is a real bug instead of just missing documentation. Even the basic usage of `knex` does not work well if one has `.` in table names. If you have them you can't do any complex queries e.g. having joins and having to refer multiple tables in query.

For example this is how you do simple join:
```js
knex('MyTable').join('OtherTable', 'MyTable.otherId', '=', 'OtherTable.id').toString();
```
which renders to following SQL (dots separate table and column):
```sql
select * from "MyTable" inner join "OtherTable" on "MyTable"."otherId" = "OtherTable"."id"
```

With `Dotty.Table` query above outputs totally invalid output:
```js
knex('MyTable').join('Dotty.Table', 'MyTable.otherId', '=', 'Dotty,Table.id').toString()
```
SQL:
```sql
select * from "MyTable" inner join "Dotty"."Table" on "MyTable"."otherId" = "Dotty"."Table"."id"
```

Looks like testcase mentioned does not have dot in table name, but it does not have column reference either, so according to that it still seems to be undefined behaviour how to handle dots in case of `??`.

I would prefer to handle it the way that is the most common use case in `knex`, which expects that there is no dots used in table names and that dot is used to separate table and column. There are many examples in documentation about that functionality e.g. in chapter http://knexjs.org/#Builder-join

**Comment by rhys-vdw** [comment]
@elhigu Well argued, I concede the point.

In that case we need to fix the bug and document the feature.

**Comment by elhigu** [comment]
To give pointers, if someone starts working on this: Internal `knex` function to do converting `'Table.Column'` to `"Table"."Column"` format if found from formatter `knex.client.formatter().columnize('Table.Column')`.

**Comment by chrisbroome** [comment]
I think the most common use case is where tables do not have a `.` character in the name, so for `knex.raw`, maybe splitting on the `.` is OK.

I *would* like to have a pair of new functions, `quotedIdentifier` and `quotedIdentifierPath`.

* `quotedIdentifier` should quote a single identifier without interpolation of `.` characters.
* `quotedIdentifierPath` should take an arbitrary number of path parts, quote each part individually using `quotedIdentifier` and then join the parts using the `.` character.

A simple implementation (harmony syntax):

```JavaScript
function quotedIdentifier(name) {
  // implementation-specific code that quotes a single path part without interpolating . characters
  // so identifier('table.with.dots') yields the quoted identifier "table.with.dots"
}

function quotedIdentifierPath(...args) {
  return args.map(quotedIdentifier).join('.');
}

console.log(quotedIdentifierPath('table'))
// "table"

console.log(quotedIdentifierPath('table_name', 'column_name'))
// "table_name"."column_name"

console.log(quotedIdentifierPath('schema_name', 'table_name', 'column_name'))
// "schema_name"."table_name"."column_name"

console.log(quotedIdentifierPath('schema_name', 'table_name.with.dots', 'column_name'))
// "schema_name"."table_name.with.dots"."column_name"
```

**Comment by elhigu** [comment]
@chrisbroome as far as I know currently there is no escaping / identifier wrapping functions in public API of `knex`, I'm not sure why @tgriesser has not exposed functions public, but only to be called through `knex.raw`. Maybe you could open separate feature request issue for those and link to this issue?

**Comment by wubzz** [comment]
@elhigu Is this merged and can be closed? (I'm guessing it is, just double-checking)

**Comment by elhigu** [comment]
Yep, thanks for reminder

**Comment by rpavez** [comment]
There are still issues with this.

```
.fullOuterJoin('custom_field_value', function() {
    this.on('custom_field.id', '=', 'custom_field_value.custom_field_id').andOn('custom_field_value.objectId', 216015);
})
```

is generating

`select "access_control"."objectId", "custom_field".*, "custom_field_value".* from "custom_field" full outer join "custom_field_value" on "custom_field"."id" = "custom_field_value"."custom_field_id" and "custom_field_value"."objectId" = "216015"`

216015 should not be in quotes

**Comment by elhigu** [comment]
@rpavez this is completely different issue. The one you added is actually correct functionality because in joins function on function signature is `.on(columnRef, columnRef)` which is different to for example `where` `.where(colRef, value)` .  You actually are using it correctly in `.on('custom_field.id', '=', 'custom_field_value.custom_field_id')` and then expect it to work differently with `.andOn('custom_field_value.objectId', 216015)`.

correct way to use literals in join is:

```js
.andOn('custom_field_value.objectId',  knex.raw('?', [216015]))
```

(I know its not the best part of knex API...)

**Comment by rpavez** [comment]
That worked, thanks a lot!
