### ISSUE TITLE
postgres json root array values serialized wrong

### ISSUE THREAD

**Issue by zacronos** [tgriesser/knex#1004]
`console.log(knex.table('example').insert({blob: [1,2,3]}).toString());`
yields the following:
`insert into "example" ("blob") values ('{\"1\",\"2\",\"3\"}')`

If actually executed against a postgres db, for example with a table created by:
```javascript
knex.schema.createTable('example', function (table) {
  table.increments('id');
  table.json('blob');
});
```
then I get the following error: `invalid input syntax for type json`.  And of course that error is correct.

I looked into the code to see if I could create a PR to handle this, but it looks like an "ideal" solution would require some significant refactoring.  The problem is that at the time knex knows it is serializing an array, it has no way of knowing whether the target value is a PG native array or a JSON array, and they have very different syntax.

My workaround is to do something like:
`knex.table('example').insert({blob: knex.raw('?', JSON.stringify([1,2,3]))});`
in order to force JSON-style serialization of the array.  Perhaps that's the best that can be done, but I wanted to make sure folks are aware of the issue -- if nothing else, this issue documents the problem and workaround for others who might run into it.

**Comment by rhys-vdw** [comment]
Thanks for the report. This is a tough one because Knex has no knowledge of column types. Nothing to add really, except perhaps a shorter form is possible?

```js
knex.table('example').insert({blob: JSON.stringify([1,2,3])});
```

**Comment by zacronos** [comment]
Ah, true, thanks for that suggestion.  That feels a little less hackish.

**Comment by rhys-vdw** [comment]
> if nothing else, this issue documents the problem and workaround for others who might run into it.

It would be good to get this workaround into the actual docs. Perhaps under `schema.json`.

**Comment by zacronos** [comment]
Roger, I'll make a PR for it.  Is this a postgres-only issue?  Or to put it another way, do any other dialects have a native array syntax which knex uses?

E.g. you wouldn't want `[1,2,3]` to be serialized as `{1, 2, 3}` whether the column is JSON (in newer postgres) or text (anything else).

**Comment by zacronos** [comment]
Documentation PR is up, https://github.com/tgriesser/knex/pull/1005

**Comment by zacronos** [comment]
I believe this is handled as well as it can be now, so I'm closing the issue.

**Comment by rhys-vdw** [comment]
@zacronos Agreed, thank you.
