### ISSUE TITLE
Setting up question

### ISSUE THREAD

**Issue by maxnathaniel** [tgriesser/knex#1012]
Hi all,

I've just started learning node js recently. So far, I had gone through several tutorials on mongodb and mongoose for node. However, I've been pointed to Knex (more specifically postgreSQL) for DB with node. However, I'm not sure how to get started. I've tried to insert createTable in my main app.js file, but the table doesn't seem to be created when I check my pgAdmin III interface. Maybe people who use this knex package are assumed to be high level programmers.

My main app.js file
```
var knex = require('knex')( {
  client: 'pg',
  connection: {
    host: '127.0.0.1',
    port: '5433',
    user: 'superadmin',
    password: 'xxx',
    database: 'wine'
  },
  debug:'true';
});

knex.schema.createTable('users', function (table) {
  table.increments();
  table.string('name');
  table.timestamps();
})

knex.schema.createTable('comments', function (table) {
  table.increments();
  table.string('name');
  table.timestamps();
})

```

Looking forward to any possible help. Thank you!

**Comment by blah238** [comment]
See here: https://github.com/tgriesser/knex/issues/325#issuecomment-46150185

**Comment by maxnathaniel** [comment]
Hi blah238,

Thanks for the pointer.

Once I create the two objects in the module.exports object, how do I initiate the creation of table? Is it via migration as seen here - http://knexjs.org/#Migrations

**Comment by blah238** [comment]
You don't have to use migrations, I was only referring to the explanation of how to use `createTable` on its own.

Here is an example (note I changed it to use SQLite3 to test it).

```js
var knex = require('knex')({
  client: 'sqlite3',
  connection: {
    filename: './test.db'
  },
  debug: true
});

return knex.schema.createTable('users', function (table) {
  table.increments();
  table.string('name');
  table.timestamps();
})
.createTable('comments', function (table) {
  table.increments();
  table.string('name');
  table.timestamps();
})
.then(function () {
  console.log('tables created successfully');
})
.catch(function (err) {
  console.error(err);
})
.finally(function () {
  process.exit(); // Not sure why this is needed to get the app to exit, but this takes care of it
});
```

**Comment by maxnathaniel** [comment]
Thanks for that.

Just one more question - Where exactly should it go? 

1. I tried putting it in the app.js file but it threw an error that app is 'undefined' in another file where I set 

```
app.set('port', port);

```
2. Or should I put the createTable code in a separate controller folder?

**Comment by maxnathaniel** [comment]
Oh interestingly, I inserted the code after everything in app.js and the tables are created! Any idea why that is the case?

**Comment by blah238** [comment]
I'm not sure what you're asking, but it doesn't sound Knex-related. If you think it is, post the code in question.

**Comment by maxnathaniel** [comment]
No problem, thanks for all your help!
