### ISSUE TITLE
Creating user model with Passport 

### ISSUE THREAD

**Issue by maxnathaniel** [tgriesser/knex#1013]
Hi all,

Being relatively new to node and knex, I'm wondering how I can integrate a user model with Passport JS. I found tonnes of resources on Passport and Mongoose, but very little about knex(postgres). 

Would appreciate it if someone can point me to a direction. Thank you!

**Comment by rhys-vdw** [comment]
Knex has no concept of 'models' as such, it can just help you build SQL and normalizes database responses. Which part specifically were you looking for help with?

**Comment by maxnathaniel** [comment]
Thanks for your reply. In this case, I wouldn't be able to create a knex model for users?  Hence, for creating new users, I create a new 'insert' into my 'users' table, and for users login, I query my 'user' table to check for existing user. 

Am not particularly sure what is the best way to go about it with knex.

**Comment by rhys-vdw** [comment]
You might want to look into [Bookshelf.js](http://bookshelfjs.org). It adds an ORM layer around Knex.

**Comment by maxnathaniel** [comment]
Thank you!

**Comment by rhys-vdw** [comment]
> Hence, for creating new users, I create a new 'insert' into my 'users' table, and for users login, I query my 'user' table to check for existing user.

But yes, essentially that sounds perfect. It should be easy to use knex to replace to query part of any Passport.js tutorial.

**Comment by maxnathaniel** [comment]
Sounds fantastic! Just have to figure how to do hashing of passwords!

**Comment by rhys-vdw** [comment]
Look into the virtuals plug-in if you're using bookshelf.
