### ISSUE TITLE
Append raw to select?

### ISSUE THREAD

**Issue by 58bits** [tgriesser/knex#1016]
Is it possible to append a raw sql statement, to the end of of a Knex select query?

For example, I'd like to add the following postgres window function to the end of a select query...

`count(*) OVER() AS total`

Or can this be done another way?

Here's what the current select query looks like... (without the following where and join clauses).

```
knex.select(knex.raw('s.id as story_id, s.lr_id, s.name as title, s.published_title, s.url, s.date, \
                s.description, s.copyright, s.keywords, si.image_id, s.is_published, s.is_hidden, \
                count(*) OVER() AS total'))
```

**Comment by rhys-vdw** [comment]
Like this?

```js
knex.select(
  's.id as story_id',
  's.lr_id',
  's.name as title',
  's.published_title',
  's.url',
  's.date',
  's.description',
  's.copyright',
  's.keywords',
  'si.image_id',
  's.is_published',
  's.is_hidden'
).select(knex.raw('count(*) OVER() as total'))
```

`select` statements are additive.

**Comment by 58bits** [comment]
Thank you! It worked. I think I love Knex.js ;-)
