### ISSUE TITLE
QueryBuilder Json type stringify problem

### ISSUE THREAD

**Issue by pyros2097** [tgriesser/knex#1021]
I'm using knex only for building queries only and then use these directly with the postgres client. But with JSON data it inserts a backslash for characters for quotes like this,

```
ERROR:  invalid input syntax for type json at character 74
DETAIL:  Token "\" is invalid.
CONTEXT:  JSON data, line 1: {\...
STATEMENT:  insert into "activity" ("data") values ('{\"id\":\"player1\"}')
ERROR:  current transaction is aborted, commands ignored until end of transaction block
```

The postgres client requires only the normal text without backslashes.
It is possible to overcome this?

**Comment by zacronos** [comment]
I've seen this myself -- I would definitely consider this a bug.

**Comment by FrankZZ** [comment]
+1

**Comment by matus123** [comment]
+1

**Comment by jamesdixon** [comment]
Has anyone succeeded in solving this? I'm also running into this issue when attempting to store stringified JSON in a Postgres JSONB column. I did notice that it seems to only fail when doing an `update`, but succeeds on `insert`.

**Comment by jamesdixon** [comment]
Tracked the issue down to [this line](https://github.com/tgriesser/knex/blob/master/src/dialects/postgres/utils.js#L80).

**Comment by wubzz** [comment]
Cannot reproduce in latest knex, closing. Reopen if it's still an issue.
