### ISSUE TITLE
How do I use the Environment configuration?

### ISSUE THREAD

**Issue by LordWingZero** [tgriesser/knex#1025]
I see here http://knexjs.org/#knexfile I can create a "Environment configuration" which is basically a module that exports a configuration object.

```javascript
var mysqlConfig = {    
    production: {
        client: 'mysql2',
        connection: {
            host: 'some.domain.org',
            user: 'root',
            password: 'hello',
            database: 'world',
            timezone: 'CDT'
        }
    },
    development: {
        client: 'sqlite3',
        connection: {
            filename: "./irc.sqlite"
        }
    }
};
module.exports = mysqlConfig;
```

However, when I try and pass the object into my `var knex = require('knex')(mysqlConfig); ` I get:

Unhandled rejection Error: There is no pool defined on the current client

It does not like that object. I know its as easy as checking 'process.env.NODE_ENV' for 'production' or 'development' and then passing in mysqlConfig.development but the documentation here for knex is confusing. Im not trying to use knex in a CLI.

**Comment by chrisbroome** [comment]
As far as I know, you need to pass a specific config to initialize knex. Something like

```JavaScript
// get a knex configuration, defaulting to development
var knexConfig = mysqlConfig[process.env.NODE_ENV || 'development'];

// initialize knex with the configuration for the environment
var knex = require('knex')(knexConfig);

// export the initialized knex object
module.exports = knex;
```

I usually put the initialized knex object in a module (as in the example) and then require that where I need it in the app.

Also note that when running any `knex migrate` command, it will use `NODE_ENV` implicitly. I do recommend using a different environment variable for anything other than migrations. `NODE_ENV` just affects way too many modules, and for express in particular, it has a serious performance impact when not set to `production`.

**Comment by LordWingZero** [comment]
Thanks this helps a ton! I really should be taking advantage of modules more. I was just afraid to stash too much stuff off to a module and then have a weird dependency layout where everything depended on each other.
