### ISSUE TITLE
Best way to set up tables if they dont yet exist?

### ISSUE THREAD

**Issue by LordWingZero** [tgriesser/knex#1026]
I have my app mostly done and was considering open sourcing it, for dev it uses sqlite3 and for production it uses mysql2 but it occurred to me a new user that had just downloaded my app wont have any tables set up.

What is a smart way to handle this? At the very least I could build a function that checks for the tables and creates them if they dont exist. Is that appropriate?

**Comment by sombriks** [comment]
Hello @LordWingZero,

knex already have a way to help you with it, you can create migrade and seed scripts.

see it in the main documentation: http://knexjs.org/#Migrations

for example, i create migrate files and seed files as described in the docs and inside my app i have this hook to make sure i have the latest database schema and seed population:

```javascript
console.log("(1/3) running [knex.migrate.latest()]");
knex.migrate.latest().then(function(){
  console.log("(2/3) running [knex.seed.run()]");
  return knex.seed.run();
}).then(function(){
  console.log("(3/3) app ready. Listening port: "+port+", addr: "+(addr ? addr : "0.0.0.0"));
  app.listen(port,addr);
});
```

hope it helps

**Comment by LordWingZero** [comment]
This does help a bit, it gives me understanding of how a migration and seed are kicked off. Can you share a few more things so I can have some code examples to go off:

What does your knexfile file look like?

What do your migration files look like?

Lastly, how are you initializing knex?

**Comment by sombriks** [comment]
let's say you are starting from scratch. first thing is to install knex system-wide:

***sudo npm -g install knex***

afer that, you'll have the knex command available from command line.

second step, install the desired database support (ex. ***sudo npm -g install pg***).

third: inside your project folder, type '***knex init***'. it will create the ***knexfile.js*** for you, then you will be able to modify it with the specific options for your database, exactly as seen in the manual.

once you have a knex file, the ***knex:migrate latest*** and ***knex seed:run*** migrations and seeds made with ***knex migrate:make*** and ***knex seed:make***.

Everything is written in the manual. yet, if you are wondering how a migrate file looks like, see this sample:

```javascript
// knex migrate:make nova_tabela_complemento
// 20150930202856_nova_tabela_complemento.js
exports.up = function(knex, Promise) {
  return knex.schema.createTable("endcomplemento",function(table){
    table.increments("idendcomplemento");
    table.integer("idcomunidade").notNullable().references("idcomunidade").inTable("comunidade");
    table.integer("idcondomino").notNullable().references("idcondomino").inTable("condomino");
    table.integer("nivelcomplemento").notNullable();
    table.boolean("mastercondomino").defaultTo(false);
    table.string("labelcomplemento").defaultTo("");
    table.string("valorcomplemento").defaultTo("S/N");
    // table.primary(["idcomunidade","idcondomino","nivelcomplemento"]);
    table.dateTime("dtcadendcomplemento").defaultTo(knex.raw("now()"));
  });
};

exports.down = function(knex, Promise) {
  return knex.schema.dropTableIfExists("endcomplemento");
};
```

I've seen a few data mappers and migrate strategies, but knex provided us a quite nice one. 

All you need to know is in http://knexjs.org/ , read it with no rush, nearly all answers to my questions i've found there.

**Comment by LordWingZero** [comment]
I have read most of the documentation, and all of the knex migrate stuff but im still struggling. For example, I have done knex init and installed database support. But in my app.js I dont know how to load knex.js and have it automatically initialize with the details in kennex.js.

Also what I dont understand is why theres a migrations: { tableName: 'migrations' } inside the konnect.js production/staging objects because I dont understand what migrations have to do with individual tables.

**Comment by LordWingZero** [comment]
Or am incorrect in thinking the the knexfile.js is supposed to be used to init knex inside of my application code? Should I be doing:
```javascript
var knexfile = require('./knexfile.js');

// Set up Knex
var knexObj = {};
if(isDev)
{
    knexObj = knexfile.development;
} else {
    knexObj = knexfile.production;
}
var knex = require('knex')(knexObj);
```
