### ISSUE TITLE
How to do `count(distinct)` ?

### ISSUE THREAD

**Issue by ErisDS** [tgriesser/knex#1028]
I have been unable to find a way with the knex API to perform a count distinct, E.g. `select count(distinct things.id) as aggregate from things...`

`select distinct count(things.id)` is very different to `select count(distinct things.id)`

`.distinct().count()` makes the former, and putting `.count('distinct things.id')` results in an incorrectly quoted query: `select count("distinct things"."id")`

I get the feeling I'm going to have to structure the query as `select count(*) 
from (select distinct things.id from things....`, I'm just hoping there is a way to do it without using subqueries.

Any ideas at all would be very greatly appreciated.

**Comment by johanneslumpe** [comment]
@rhys-vdw would it make sense for `count` to accept `knex.raw` as a value? Then the above would be as simple as `knex('things').count(knex.raw('distinct things.id'))`. Currently that fails with `Uncaught TypeError: val.toLowerCase is not a function`.

**Comment by ErisDS** [comment]
Just after posting this (you know, as is always the way), I found this: https://github.com/tgriesser/knex/issues/238

After *much* fiddling, I managed to get this working.

Context is I'm inside a custom bookshelf plugin that's dynamically creating counts for a query for paginating responses... so my final code looks like this:

`this.query().clone().select(bookshelf.knex.raw('count(distinct "' + tableName + '"."' + idAttribute +'") as "aggregate"'));`

I can close this now, as I've solved it, and #328 is already tracking the `toLowerCase` error, however I'd propose that supporting this without doing a raw query would be nice, something like accepting this:

`this.query().clone().count('distinct "' + tableName + '"."' + idAttribute +'")` 

or an option

`this.query().clone().count(tableName + '.' + idAttribute, {distinct: true})`

or even easier

`this.query().clone().countDistinct(tableName + '.' + idAttribute)`

would save quite a lot of fiddly quoting of code in this case

**Comment by rhys-vdw** [comment]
Hi @ErisDS, I agree that that's too complex. Leave this open for a PR.

`QueryBuilder#countDistinct` looks like a good solution to me.

**Comment by elhigu** [comment]
Count distinct sounds like a good idea :+1: 

@ErisDS As a workaround have you tried `count(knex.raw('distinct ??', 'tableName.idAttribute'))`. I think that identifier escaping feature did came around knex 0.8, but it has been buggy / not documented yet. 

There is discussion about it in #1003 and it should be fixed / working after #1050 is merged. Pull request contains fixes to knex.raw identifier escaping + documentation of the new style of knex.raw parameter replacements.

**Comment by ErisDS** [comment]
You can see the workaround I am using here: https://github.com/TryGhost/Ghost/blob/master/core/server/models/base/pagination.js#L152 and as you've seen I've got an open PR #1046 which adds `countDistinct`, `avgDistinct` and `sumDistinct`.

**Comment by ariden83** [comment]
Do you know how to do countDistinct(...).as(...)

as :  countDistinct(this.prototype.tableName + '.' + this.prototype.idAttribute).as('count')

Actually, SQL generated : 

select count(distinct "table"."id"), "nrb" FROM ...

and i want 

select count(distinct "table"."id") as "nrb" FROM ...

**Comment by absolux** [comment]
@ariden83 
Have you tried
```js
knex('table').countDistinct('table.id as nrb')
```

**Comment by jorgemejia** [comment]
Is it possible to use max() for get max value fora column?

**Comment by elhigu** [comment]
@jorgemejia `.select(knex.raw('max(??)', ['colName']))`

**Comment by cahhvoy** [comment]
this seems to work correctly  and is a bit simpler 
```
knex('Quotes').count('quoteBody')
    .then((res)=>{
        //console.log("rows "+JSON.stringify(res))        
        console.log("rowspl2 "+res[0]['count(`quoteBody`)'])
    })
    .catch((err)=>{
        console.log("err "+err)
    })
```

**or try it like this**
```

knex('Quotes').count('quoteBody', {as: 'rows'})
    .then((res)=>{
       // console.log("rows "+JSON.stringify(res))
        console.log("rowsp "+res[0]['rows'])
    })
    .catch((err)=>{
        console.log("err "+err)
    })
```
