### ISSUE TITLE
Connection pools - retry other server on fail?

### ISSUE THREAD

**Issue by avimar** [tgriesser/knex#1030]
Hi - I'm trying to figure out how to do maintenance on my mysql/mariadb server without downtime.

Is there a way for knex to automatically try a second server if the connection ends? Or to drain one of the SQL servers (just a few seconds at most) to switch to a backup server?

**Comment by avimar** [comment]
So, it looks like `pool2` even has a clustering ability: https://github.com/myndzi/pool2#clustering
It won't retry queries, but seemingly you can routes reads separately from writes. That should be easy to integrate -- a select is a read, nearly everything else is a write... specify which servers are slaves for just reads.

If you couple that with the ping option - and maybe a manual way to remove a server? -- that should give you no-downtime ability to interact with a master-master setup.

What I'm trying to solve: avoiding downtime. I'll have a master-master setup (or galera cluster? but that seems overkill and more complicated) but I know I'll have to do maintenance on one of them at some point...

**Comment by elhigu** [comment]
> Is there a way for knex to automatically try a second server if the connection ends? Or to drain one of the SQL servers (just a few seconds at most) to switch to a backup server?

I'm not sure what you mean by this... As far as I know there is no way to do automatic retrying is pretty much impossible because of connection failures in middle of transaction.
