### ISSUE TITLE
"No pool defined on current client"

### ISSUE THREAD

**Issue by ononotofu** [tgriesser/knex#1031]
Currently trying to deploy to heroku -- receiving this error whenever I make a post or get request to an endpoint: "There is no pool defined on the current client"

I've tried setting pool to a variety of min/max values but the same error persists. Running knex migrate:latest does persist the schema into the database, so I do not think it's a connection issue. I've also tried passing a URL instead of an object to connection, but same issue. No other errors that I can see.

This is a problem with both the development and production environments, so it is not related to heroku deployment.

```
//package.json

"dependencies": {
"bluebird": "^2.9.13",
"body-parser": "^1.10.0",
"bookshelf": "^0.7.9",
"cli-table": "^0.3.1",
"cors": "^2.5.2",
"endpoints": "^0.9.0",
"express": "^4.10.6",
"express-routebuilder": "^2.1.0",
"knex": "0.8.6",
"pg": "^4.4.3",
"sqlite3": "^3.0.4"
}

```

```
// knexfile.js
module.exports = {
	development: {
	 client: 'pg',
	 debug: true,
	 connection: {
	  user: 	'xxxxx',
	  database: 	'xxxxx'
  }
	},
	production: {
		client: 'pg',
		connection: {
			host: "xxxx.amazonaws.com",
			port: "xxxxx",
			user: "xxxxx",
			password: "xxxxx",
			database: "xxxxx",
			ssl: true
	},
	pool: {
		min: 0,
		max: 1 
	}
	}
};
```

Any help would be greatly appreciated!

**Comment by chrisbroome** [comment]
How are you initializing knex?

**Comment by ononotofu** [comment]
@chrisbroome thanks for the quick reply, I'm using a framework called endpoints which emits json-api -- I believe the initializing hook is this:

```
const config = require('../../knexfile');
const Knex = require('knex')(config);
const Bookshelf = require('bookshelf')(Knex);

module.exports = Bookshelf;
```

if I change my database to sqlite, it works fine.

**Comment by blah238** [comment]
@ononotofu I do not believe the `development` and `production` environments are respected outside of the CLI, which would explain why the migration worked but the application doesn't. I think you'll have to handle that logic yourself and pass in the applicable connection properties to Knex in your initialization logic.

**Comment by blah238** [comment]
See also: https://github.com/tgriesser/knex/issues/1025

**Comment by ononotofu** [comment]
@blah238  I don't want to admit to how much time I spent trying to debug this -- you completely unblocked me on this -- it works!

updated config, for anyone in the future: 

```
module.exports = {
		client: 'pg',
		connection: {
			host: "xxxx.amazonaws.com",
			port: "xxxxx",
			user: "xxxxx",
			password: "xxxxx",
			database: "xxxxx",
			ssl: true
	},
		pool: {
			min: 1,
			max: 7
		}
};
```

Thank you so much!~
