### ISSUE TITLE
Proposed select syntax: select({ alias: 'column' })

### ISSUE THREAD

**Issue by fengb** [tgriesser/knex#1034]
Can we extend select to do this:

``` sql
> knex.select({ by: 'author' }).from('book')
select `author` as `by` from `book`
```

I've been using aggregation queries a lot and doing `select('sum(foo)/count(foo) as bar')` tends to hide the aliases, while `select({ bar: 'sum(foo)/count(foo)' })` would make them much more prominent.

**Comment by chrisbroome** [comment]
I'd like to add that multiple columns could be supported by adding additional key/value pairs:

```JavaScript
knex.select({by: 'author', publishedBy: 'publisher'}).from('book');
// select `author` as `by`, `publisher` as `publishedBy` from `book`
```

**Comment by rhys-vdw** [comment]
Looks nice to me. Note that we'd also need to support this:

```js
knex.select('thing', 'other', { aliasName: 'column_name' })
```

**Comment by ivanslf** [comment]
Sorry for bringing up such an old issue, but it would integrate nicely with the new ES6 property-value shorthand:

`knex.select({title, description, createdTime: 'created_time'})`

**Comment by wubzz** [comment]
This feature has been merged, closing.
