### ISSUE TITLE
JSON Data Type support in MySQL v5.7.x and SQlite 3.9

### ISSUE THREAD

**Issue by lanceschi** [tgriesser/knex#1036]
Hi,

I was just wondering if the new [JSON data type](https://dev.mysql.com/doc/refman/5.7/en/json.html) present in MySQL v5.7.x is supported?

Thanks

**Comment by elhigu** [comment]
There is no support yet. Using `json` column type in schema actually creates `text` column.

**Comment by elhigu** [comment]
Support should be brought to the same level with postgres jsonb type.

**Comment by andyfleming** [comment]
This would be great. If it doesn't already behave this way with JSON columns it would be great to have automatic parsing/stringifying. If we don't think it is a good default, we should consider adding it as an option to enable (possibly for postgres json columns too).

**Comment by leebenson** [comment]
does anyone know if there's been any movement on this feature?

**Comment by HaNdTriX** [comment]
> As of MySQL 5.7.8, MySQL supports a native JSON 
https://dev.mysql.com/doc/refman/5.7/en/json.html

**Comment by elhigu** [comment]
Also SQlite, oracle and mssql supports json nowadays https://www.infoq.com/news/2015/10/sqlite-39-released 

So we should check all that all dialects creates correct column type for json column.

**Comment by knobandre** [comment]
What is the status for adding support for JSON Data Type for SQLite?

**Comment by kibertoad** [comment]
@knobandre You are welcome :-P

**Comment by kibertoad** [comment]
@elhigu Do we only close issues after non-next version with new functionality is released?

**Comment by wubzz** [comment]
It should auto close if issue is mentioned in commit / PR and PR is merged. I can see support for SQLite was added which is great, but I don't think it concludes the original issue? (MySQL)

**Comment by wubzz** [comment]
Hm, wasn't referenced here, that's why I missed it. I'll close this then.
