### ISSUE TITLE
is it possible to delete a constraint/index in knex?

### ISSUE THREAD

**Issue by gfarrell** [tgriesser/knex#1037]
In my migrations I'm creating a uniqueness constraint on three columns:

    table.unique(["one", "two", "three"]);

is it possible to do the reverse on rollback?

**Comment by blah238** [comment]
Yes, the signature is `table.dropUnique(columns, indexName)` and should be similar to `table.dropIndex` which is now documented: https://github.com/tgriesser/knex/blob/05ffb457a885c9a2d27a0684b57cbcf45cbb0456/index.html#L1908

There are a couple of open issues (PRs welcome) to document `dropUnique`, among others: https://github.com/tgriesser/knex/issues/483 https://github.com/tgriesser/knex/issues/918

**Comment by gfarrell** [comment]
Thanks.

**Comment by himharsh1997** [comment]
Just to add on this answer "Try to avoid composite index and use index with single column if possible"
