### ISSUE TITLE
New release for multiple changes

### ISSUE THREAD

**Issue by jadengore** [tgriesser/knex#1039]
I just took a look and it seems that there hasn't been an update to Knex on `npm` since May. In addition, there have been almost 100 commits since this last release.

It would be good for these changes to make it into an official release so people can get the updates that have been merged.

Edit: The exact count of commits from 0.8.6 is 97!

**Comment by blah238** [comment]
I agree, but it sounds like a [0.9.0](https://github.com/tgriesser/knex/pull/969) release is forthcoming? I don't know how to do a proper release yet myself, so I think @rhys-vdw or @tgriesser would need to do it.

For anyone who really needs the latest changes now, you can always either clone the repo and [`npm link`](https://docs.npmjs.com/cli/link) it or use the [GitHub URL in your `package.json`](https://docs.npmjs.com/files/package.json#github-urls).

**Comment by jadengore** [comment]
@blah238 :+1: 

@rhys-vdw Can we possibly prep a release for this?

**Comment by rhys-vdw** [comment]
> I just took a look and it seems that there hasn't been an update to Knex on npm since May. In addition, there have been almost 100 commits since this last release.

Yes, I'm aware of this. I was hoping Tim would get a chance to go through it all, but a release is well overdue now.

> I don't know how to do a proper release yet myself, so I think @rhys-vdw or @tgriesser would need to do it.

Yep, Tim and I the only ones with npm rights presently. I personally have not done a knex release, but I've done a release for bookshelf so I know the procedure.

> You might need some updates to that changelog.

Definitely. If either of you guys have time it'd be great to get a PR against my changelog to add the missing changes. I'll try to cut a release on Sunday (was hoping to do another Bookshelf release then too).

**Comment by ArdentZeal** [comment]
Please also include the batchInsert feature properly. We are using a side branch for months now! https://github.com/tgriesser/knex/issues/757

Kind Regards,
ArdentZeal

**Comment by rhys-vdw** [comment]
@ArdentZeal I've responded on #757. There's more work to be done there than a simple merge, but I'm happy to help get this into master.

**Comment by rhys-vdw** [comment]
Well I've just made a release. There are a lot of changes (as @jadengore mentioned), so probably a few new issues coming up soon.

**Comment by jadengore** [comment]
Thanks @rhys-vdw!
