### ISSUE TITLE
Create table hangs

### ISSUE THREAD

**Issue by Sendoushi** [tgriesser/knex#1041]
So, made a little script and it hangs.

I'm using knex 0.8.6.
If I change the connection data, it will error so I guess postgresql connection is working.
The console.log doesn't happen. Nothing happens, just hangs.

```js
var knex = require('knex')({
    client: 'pg',
    debug: true,
    connection: {
        'host': 'localhost',
        'database': 'test',
        'user': 'admin',
        'password': 'admin',
        'charset': 'utf8'
    }
});

knex.schema.createTable('test', function (table) {
    table.increments('id').primary();
    console.log('created', 'test');
});
```

**Comment by chrisbroome** [comment]
Try starting the script with `DEBUG=knex:* node your-script-name.js` and post the output here.

**Comment by Sendoushi** [comment]
No output...

**Comment by Sendoushi** [comment]
So with the line you provided I don't get an output. But... changed the code to:

```js
var knex = require('knex')({
    client: 'postgres',
    debug: true,
    connection: {
        'host': 'localhost',
        'user': 'admin',
        'password': 'admin',
        'database': 'test'
    }
});

knex.schema.hasTable('test_table')
.then(exists => {
    console.log('exists?', exists);
});

knex.schema.createTable('test_table', function (table) {
    table.increments('id').primary();
    console.log('created', 'test');
});
```
And now it spits some stuff and logs the exists. Hangs on create table though and no log for it.

**Comment by chrisbroome** [comment]
That means `createTable` probably failed. `createTable` returns a `Promise`, and since you don't have a handler for either success or failure, there's no way to determine what happened. Try this:

```JavaScript
knex.schema
  .createTable('test_table', function (table) {
    table.increments('id').primary();
  })
  .then(function() {
    console.log('created test');
  })
  .catch(function(err) {
    console.error(err);
  });
```

**Comment by Sendoushi** [comment]
Oh it returns a promise? Cool!
It worked. Thanks.

I think I already tried this but... oh well it is working thanks!
