### ISSUE TITLE
Unique index issue.

### ISSUE THREAD

**Issue by srksag** [tgriesser/knex#1049]
I'm trying to create an unique index on a pg table using knex and if I'm chaining the statements, the uniqueness is being defined as unique constraint, I understand that it solves the purpose of maintaining DB constraints, but I prefer to have this defined on the index level, so that I can drop the index if I don't need it.

Do you think that we can extend index methods support by adding "uniqueIndex"  to the list.

**Comment by rhys-vdw** [comment]
Could you clarify with some code examples?

**Comment by srksag** [comment]
@rhys-vdw - thnx for the response, no need to consider this request as pg creates index internally for the unique constraint.

-Ravi
