### ISSUE TITLE
Is there a way to do INSERT INTO ... SELECT?

### ISSUE THREAD

**Issue by nareshbhatia** [tgriesser/knex#1056]
INSERT INTO orders (user_id, email)
    SELECT user_id, 'jdoe@gmail.com'
    FROM   users as u
    WHERE  u.username = 'jdoe'

**Comment by chrisbroome** [comment]
This works, though it's not _exactly_ the sql above:

```JavaScript
const qb = knex.from('orders')
  .insert(function() {
    this.from('users as u')
      .where('u.username', 'jdoe')
      .select('user_id', 'jdoe@gmail.com AS email')
      .select('user_id', knex.raw('? AS ??', ['jdoe@gmail.com', 'email']))
  });
console.log(qb..toString()
```

Produces the following (newlines added for clarity, MySQL Dialect):
``` SQL
insert into `orders`
select `user_id`, 'jdoe@gmail.com' AS `email`
  from `users` as `u`
 where `u`.`username` = 'jdoe'
```

**Comment by nareshbhatia** [comment]
Wow! Is that officially supported? I could find it in the docs anywhere (that I could send a function into `insert()`).

In any case, it's not quite working for me. I am using postgres, and if I don't specify the column names in the `INSERT` lines, then postgres expects me to send ALL columns in the SELECT clause - in the correct sequence.  Just using the `AS` to name the column does not cut it :-(. My table has many nullable columns that I don't want to specify at the time of insertion.

**Comment by chrisbroome** [comment]
The best I could come up with for explicitly putting columns is using `knex.raw` in the top level `from` clause:

``` JavaScript
const qb = knex.from(knex.raw('?? (??, ??)', ['orders', 'user_id', 'email']))
  .insert(function() {
    this.from('users AS u')
      .where('u.username', 'jdoe')
      .select('user_id', knex.raw('? AS ??', ['jdoe@gmail.com', 'email']))
   });
console.log(qb.toString());
```

Output (this time, Postgres)
``` SQL
insert into "orders" ("user_id", "email")
select "user_id", 'jdoe@gmail.com' AS "email"
  from "users" as "u"
 where "u"."username" = 'jdoe'
```

**Comment by nareshbhatia** [comment]
Thanks, @chrisbroome. While this works, it's becoming practically unreadable. At this point, I am going with a raw query using `knex.raw()`. This would be a good enhancement to consider for the future.

I am closing this issue for now, but feel free to comment if you have a better solution.

**Comment by LRagji** [comment]
Still have 2 questions 

- Where is this documented `knex.insert(function() {}` shouldn't this be async?
- The solution offered is readability nightmare :( whole point of me using knex was to make things readable..
