### ISSUE TITLE
Text Types?

### ISSUE THREAD

**Issue by ScottRandallWay** [tgriesser/knex#1064]
For the text schema command:  table.text(name, [textType]) 

What is the meaning of the tinytext, mediumtext, and longtext selections?
How do I pass these textType values?  as strings? should they be capitalized? like this?

table.text('myColumnName', 'LONGTEXT');

The documentation does not provide this information.  Your input is appreciated.

Scott

**Comment by hadyrashwan** [comment]
table.text('myColumnName','longtext')
its over one year old but here you go

**Comment by kempsteven** [comment]
Source: https://chartio.com/resources/tutorials/understanding-strorage-sizes-for-mysql-text-data-types/

TINYTEXT: 255 characters - 255 B
The TINYTEXT data object is the smallest of the TEXT family and is built to efficiently store short information strings. This type can store up to 255 bytes (expressed as 2^8 -1) or 255 characters and requires a 1 byte overhead. This object can be used to store things like short summaries, URL links, and other shorter objects. TINYTEXT shines over VARCHAR when storing data that’s under 255 characters with an inconsistent length and no need to be used for sorting criteria.

TEXT: 65,535 characters - 64 KB
The standard TEXT data object is sufficiently capable of handling typical long-form text content. TEXT data objects top out at 64 KB (expressed as 2^16 -1) or 65,535 characters and requires a 2 byte overhead. It is sufficiently large enough to hold text for something like an article, but would not be sufficient for holding the text of an entire book.

MEDIUMTEXT: 16,777,215 - 16 MB
The MEDIUMTEXT data object is useful for storing larger text strings like white papers, books, and code backup. These data objects can be as large as 16 MB (expressed as 2^24 -1) or 16,777,215 characters and require 3 bytes of overhead storage.

LONGTEXT: 4,294,967,295 characters - 4 GB
The LONGTEXT data object is for use in extreme text string storage use cases. It is a viable option when the MEDIUMTEXT object is not big enough. Computer programs and applications often reach text lengths in the LONGTEXT range. These data objects can be as large as 4 GB (expressed as 2^32 -1) and store up to 4,294,967,295 characters with 4 bytes of overhead storage,

**Comment by haidarabdillah** [comment]
> longtext

save my day
