### ISSUE TITLE
Conditional queries

### ISSUE THREAD

**Issue by fsebbah** [tgriesser/knex#1068]
Hi,
I don't know if this request exists. But I search a way to build a select query with conditional arguments.
Sample:

```js
knex('mytable')
.select('champ1','champ2','champ3')
.where ('champ1','=',val1)
.andWhere ('champ2','=',val2)
.then{function(rows,err){
})
```
etc...

But if champ2 is empty or don't fill the condition
I must duplicate the code without the andWhere 

```js
knex('mytable')
.select('champ1','champ2','champ3')
.where ('champ1','=',val1)
.then{function(rows,err){
etc...
})
```

If i give as value2 :'*', the query turn off.
If you a reference, thanks.
Franck

**Comment by rhys-vdw** [comment]
[`QueryBuilder#modify`](http://knexjs.org/#Builder-modify)

```js
knex('table').select('col_a').modify(function (qb) {
  if (bValue) {
    qb.where('col_b', bValue);
  }
}).then(...
```
```

**Comment by fsebbah** [comment]
it's perfect for me. Is there a forum ?
Thanks, 
Franck

**Comment by elhigu** [comment]
As far as I know github issues is the only forum for knex.
