### ISSUE TITLE
Knex Insert command not working with oracle

### ISSUE THREAD

**Issue by SJ-SivaSubrahmaniam** [tgriesser/knex#1074]
Insert command which I used

knex('MS_GROUP').insert({COLUMN1: 'SlaughterhouseFive'}).then(console.log);

output : 
{ method: 'insert',
  options: {},
  bindings: [ 'SlaughterhouseFive' ],
  sql: 'insert into "MS_GROUP" ("COLUMN1") values (?)' }
1

But the records are not inserted. Is there anything wrong with this query ?

**Comment by wubzz** [comment]
Reopen if this is still an issue.

From example, this should work.

**Comment by r4kh4t** [comment]
Facing same issue
