### ISSUE TITLE
Query Batch

### ISSUE THREAD

**Issue by ericrini** [tgriesser/knex#1075]
Hello,

I have a use case involving bulk loading hundreds of thousands (eventually millions) of rows into a data warehouse each night. To make sure this is as efficient as possible, I'm trying to follow the suggestions outlined in this document http://dev.mysql.com/doc/refman/5.5/en/optimizing-innodb-bulk-data-loading.html.

Is it possible to get something like this loaded through Knex? Here's is what I've come up with so far.

```javascript
var sql = util.format(
    'SET autocommit=0; SET unique_checks=0; set foreign_key_checks=0; %s; SET unique_checks=1; SET foreign_key_checks=1; COMMIT;',
    query.toString()
);

return knex.raw(sql)
```

I believe the SQL is correct, but Knex.raw tries to execute as a parameterized query which is limited to a single statement. While there's good reasons for this in most use cases, they aren't applicable to this bulk loading scenario.

Is there maybe some undocumented way to run a raw query batch in Knex?

**Comment by ericrini** [comment]
SOLVED... this is not a problem with Knex, but rather the options passed to the MySQL client library.

```
	"olap": {
		"client": "mysql",
		"connection": {
			"multipleStatements": true
		}
	}
```

Reference: https://github.com/felixge/node-mysql

**Comment by wubzz** [comment]
Seems to be solved, closing this.
