### ISSUE TITLE
knex CLI command not working

### ISSUE THREAD

**Issue by feesjah** [tgriesser/knex#1077]
I did install it globally, but this is what I get : 
rob@rmint ~/dev/fix $ knex init
No command 'knex' found, did you mean:
 Command 'nex' from package 'nvi' (universe)
knex: command not found

**Comment by elhigu** [comment]
You probably did something wrong... added example how to install it locally to directory and globally. try again:

```sh
Mikaels-MBP:temp mikaelle$ npm install knex
/Users/mikaelle/Projects/Vincit/temp
└─┬ knex@0.9.0 
  ├── bluebird@2.10.2 
  ├─┬ chalk@1.1.1 
  │ ├── ansi-styles@2.1.0 
  │ ├── escape-string-regexp@1.0.3 
  │ ├─┬ has-ansi@2.0.0 
  │ │ └── ansi-regex@2.0.0 
  │ ├── strip-ansi@3.0.0 
  │ └── supports-color@2.0.0 
  ├─┬ commander@2.9.0 
  │ └── graceful-readlink@1.0.1 
  ├─┬ debug@2.2.0 
  │ └── ms@0.7.1 
  ├── inherits@2.0.1 
  ├── interpret@0.6.6 
  ├─┬ liftoff@2.0.3 
  │ ├── extend@2.0.1 
  │ ├─┬ findup-sync@0.2.1 
  │ │ └─┬ glob@4.3.5 
  │ │   ├─┬ inflight@1.0.4 
  │ │   │ └── wrappy@1.0.1 
  │ │   ├─┬ minimatch@2.0.10 
  │ │   │ └─┬ brace-expansion@1.1.1 
  │ │   │   ├── balanced-match@0.2.1 
  │ │   │   └── concat-map@0.0.1 
  │ │   └── once@1.3.3 
  │ ├── flagged-respawn@0.3.1 
  │ └── resolve@1.1.6 
  ├── lodash@3.10.1 
  ├── minimist@1.1.3 
  ├─┬ mkdirp@0.5.1 
  │ └── minimist@0.0.8 
  ├── pg-connection-string@0.1.3 
  ├─┬ pool2@1.3.0 
  │ ├── double-ended-queue@2.1.0-0 
  │ ├── hashmap@2.0.4 
  │ └── simple-backoff@1.0.0 
  ├─┬ readable-stream@1.1.13 
  │ ├── core-util-is@1.0.2 
  │ ├── isarray@0.0.1 
  │ └── string_decoder@0.10.31 
  ├─┬ tildify@1.0.0 
  │ └── user-home@1.1.1 
  └── v8flags@2.0.10 

npm WARN ENOENT ENOENT: no such file or directory, open '/Users/mikaelle/Projects/Vincit/temp/package.json'
npm WARN EPACKAGEJSON temp No description
npm WARN EPACKAGEJSON temp No repository field.
npm WARN EPACKAGEJSON temp No README data
npm WARN EPACKAGEJSON temp No license field.
Mikaels-MBP:temp mikaelle$ knex
-bash: knex: command not found
Mikaels-MBP:temp mikaelle$ node_modules/.bin/knex

  Usage: knex [options] [command]


  Commands:

    init [options]                         Create a fresh knexfile.
    migrate:make [options] <name>         Create a named migration file.
    migrate:latest                         Run all migrations that have not yet been run.
    migrate:rollback                       Rollback the last set of migrations performed.
    migrate:currentVersion                View the current version for the migration.
    seed:make [options] <name>            Create a named seed file.
    seed:run                              Run seed files.

  Options:

    -h, --help         output usage information
    -V, --version      output the version number
    --debug            Run with debugging.
    --knexfile [path]  Specify the knexfile path.
    --cwd [path]       Specify the working directory.
    --env [name]       environment, default: process.env.NODE_ENV || development

Mikaels-MBP:temp mikaelle$ npm install -g knex
/usr/local/bin/knex -> /usr/local/lib/node_modules/knex/lib/bin/cli.js
/usr/local/lib
└─┬ knex@0.9.0 
  ├── bluebird@2.10.2 
  ├─┬ chalk@1.1.1 
  │ ├── ansi-styles@2.1.0 
  │ ├── escape-string-regexp@1.0.3 
  │ ├─┬ has-ansi@2.0.0 
  │ │ └── ansi-regex@2.0.0 
  │ ├── strip-ansi@3.0.0 
  │ └── supports-color@2.0.0 
  ├─┬ commander@2.9.0 
  │ └── graceful-readlink@1.0.1 
  ├─┬ debug@2.2.0 
  │ └── ms@0.7.1 
  ├── inherits@2.0.1 
  ├── interpret@0.6.6 
  ├─┬ liftoff@2.0.3 
  │ ├── extend@2.0.1 
  │ ├─┬ findup-sync@0.2.1 
  │ │ └─┬ glob@4.3.5 
  │ │   ├─┬ inflight@1.0.4 
  │ │   │ └── wrappy@1.0.1 
  │ │   ├─┬ minimatch@2.0.10 
  │ │   │ └─┬ brace-expansion@1.1.1 
  │ │   │   ├── balanced-match@0.2.1 
  │ │   │   └── concat-map@0.0.1 
  │ │   └── once@1.3.3 
  │ ├── flagged-respawn@0.3.1 
  │ └── resolve@1.1.6 
  ├── lodash@3.10.1 
  ├── minimist@1.1.3 
  ├─┬ mkdirp@0.5.1 
  │ └── minimist@0.0.8 
  ├── pg-connection-string@0.1.3 
  ├─┬ pool2@1.3.0 
  │ ├── double-ended-queue@2.1.0-0 
  │ ├── hashmap@2.0.4 
  │ └── simple-backoff@1.0.0 
  ├─┬ readable-stream@1.1.13 
  │ ├── core-util-is@1.0.2 
  │ ├── isarray@0.0.1 
  │ └── string_decoder@0.10.31 
  ├─┬ tildify@1.0.0 
  │ └── user-home@1.1.1 
  └── v8flags@2.0.10 

Mikaels-MBP:temp mikaelle$ knex

  Usage: knex [options] [command]


  Commands:

    init [options]                         Create a fresh knexfile.
    migrate:make [options] <name>         Create a named migration file.
    migrate:latest                         Run all migrations that have not yet been run.
    migrate:rollback                       Rollback the last set of migrations performed.
    migrate:currentVersion                View the current version for the migration.
    seed:make [options] <name>            Create a named seed file.
    seed:run                              Run seed files.

  Options:

    -h, --help         output usage information
    -V, --version      output the version number
    --debug            Run with debugging.
    --knexfile [path]  Specify the knexfile path.
    --cwd [path]       Specify the working directory.
    --env [name]       environment, default: process.env.NODE_ENV || development

Mikaels-MBP:temp mikaelle$ 
```

**Comment by feesjah** [comment]
rob@rmint ~/dev/fix $ npm install -g knex
/usr/local/bin/bin/knex -> /usr/local/bin/lib/node_modules/knex/lib/bin/cli.js
knex@0.9.0 /usr/local/bin/lib/node_modules/knex
├── interpret@0.6.6
├── inherits@2.0.1
├── pg-connection-string@0.1.3
├── minimist@1.1.3
├── tildify@1.0.0 (user-home@1.1.1)
├── v8flags@2.0.10 (user-home@1.1.1)
├── commander@2.9.0 (graceful-readlink@1.0.1)
├── debug@2.2.0 (ms@0.7.1)
├── readable-stream@1.1.13 (string_decoder@0.10.31, isarray@0.0.1, core-util-is@1.0.2)
├── mkdirp@0.5.1 (minimist@0.0.8)
├── bluebird@2.10.2
├── chalk@1.1.1 (escape-string-regexp@1.0.3, supports-color@2.0.0, ansi-styles@2.1.0, strip-ansi@3.0.0, has-ansi@2.0.0)
├── lodash@3.10.1
├── pool2@1.3.0 (simple-backoff@1.0.0, hashmap@2.0.4, double-ended-queue@2.1.0-0)
└── liftoff@2.0.3 (extend@2.0.1, flagged-respawn@0.3.1, resolve@1.1.6, findup-sync@0.2.1)
rob@rmint ~/dev/fix $ npm install --save knex
knex@0.9.0 node_modules/knex
├── interpret@0.6.6
├── inherits@2.0.1
├── pg-connection-string@0.1.3
├── minimist@1.1.3
├── v8flags@2.0.10 (user-home@1.1.1)
├── tildify@1.0.0 (user-home@1.1.1)
├── commander@2.9.0 (graceful-readlink@1.0.1)
├── debug@2.2.0 (ms@0.7.1)
├── pool2@1.3.0 (simple-backoff@1.0.0, hashmap@2.0.4, double-ended-queue@2.1.0-0)
├── readable-stream@1.1.13 (string_decoder@0.10.31, isarray@0.0.1, core-util-is@1.0.2)
├── chalk@1.1.1 (escape-string-regexp@1.0.3, supports-color@2.0.0, ansi-styles@2.1.0, strip-ansi@3.0.0, has-ansi@2.0.0)
├── mkdirp@0.5.1 (minimist@0.0.8)
├── bluebird@2.10.2
├── lodash@3.10.1
└── liftoff@2.0.3 (extend@2.0.1, flagged-respawn@0.3.1, resolve@1.1.6, findup-sync@0.2.1)
rob@rmint ~/dev/fix $ knex
No command 'knex' found, did you mean:
 Command 'nex' from package 'nvi' (universe)
knex: command not found
rob@rmint ~/dev/fix $ 

So strange, all my other cli commands work , but this one just wont. Do you have any idea if some external thing might be causing a problem ?
'node_modules/.bin/knex' works though, so i can get by

**Comment by elhigu** [comment]
Maybe your PATH variable is set strangely... which distro are you running? 

Also you could try `sudo npm install -g knex`. Strange that there is no errors, but still it doesn't work.

**Comment by feesjah** [comment]
something was wrong indeed, prefix wasnt right.
this is what fixed it in case someone stumbles onto the same problem:
npm config set prefix /usr/local

**Comment by ayunas** [comment]
![image](https://user-images.githubusercontent.com/30554629/63537120-a1530d00-c4da-11e9-99d8-004a615f5c11.png)
I still get the same error.  I globally installed knex, then I installed it locally in my project.  then I deleted my node modules and did npm install again

**Comment by ZRELOLERZ** [comment]
I had the same the same problem in WSL. What worked for me was using `sudo`
