### ISSUE TITLE
Syntax for setting transaction isolation level

### ISSUE THREAD

**Issue by vieks** [tgriesser/knex#1078]
I don't see it in the doc how to set isolation level for transactions ?

Thx.

**Comment by vieks** [comment]
up

**Comment by elhigu** [comment]
As far as I know there is no way to do it without `knex.raw()`.

**Comment by vieks** [comment]
hum, why not implement it as parameter for transaction method ? I will be quick and more elegant way than doing a raw call.

Like Sequalize do: [http://docs.sequelizejs.com/en/latest/docs/transactions/#isolation-levels](http://docs.sequelizejs.com/en/latest/docs/transactions/#isolation-levels)

**Comment by elhigu** [comment]
Something like that sounds reasonable, exact syntax needs to be discussed though. When it is clear that is wanted, someone might implement it too :) Do you have some clear vision how it would exactly work with knex syntax to get discussion started?

**Comment by carera** [comment]
+1 for this
For now, can someone tell me how would i approach this with knex.raw(), please?

**Comment by jmurzy** [comment]
This is a dupe of #581. 

@carera You must have figured it by now but the current "workaround" for Posgres is in #581. A bit more hackier but I believe you could do the same for MySQL as well.

**Comment by elhigu** [comment]
@jmurzy thanks! Closing this one...
