### ISSUE TITLE
Schema table builder avoid callback

### ISSUE THREAD

**Issue by Roam-Cooper** [tgriesser/knex#1082]
To get a table builder I have to call `knex.schema.table(tableName, callback Fn);` but the problem is that I get the table builder only inside the standard callback function. The promise returned is a void promise, I would've expected to be able to attach a then handler and receive the table builder this way.

What it means is that I have to use a conventional callback to get the table builder, and a promise catch handler to receive any errors. It seems really backwards?

I also can't seem to promisify this as the standard error, data callback function arguments pattern is not being used.

It would just have been nice to be able to use it like: `knex.schema.table(tableName, function(tableBuilder){}).then(function(tableBuilder){});` where the callback function is optional...

**Comment by wubzz** [comment]
This is quite the major API-redesign for the schema scheduler which I don't see likely changing anytime soon unless some strong arguments are put on the table.

Please reopen if this is still an active issue.

**Comment by elhigu** [comment]
Current schema API is so problematic, that it will need completely new version of it (people has already started working on this couple of times) and old one needs to be kept around for a quite long time to provide backwards compatibility.

I will start issue for API design + base principles on which it will be designed for the new migration API at some point during this year.
