### ISSUE TITLE
Migrations & Transactions - Source Code Question

### ISSUE THREAD

**Issue by JoaoCnh** [tgriesser/knex#1084]
Hey

Lately I've been deep in knex trying to make SQL Server to work. It came out has a need and why not give it a shot. It has been going well, I've been re-using a lot of tests and adapting to the correct SQL Server syntax and adjusting the dialect to fulfill those needs. 
The integrations tests have passed until the migrate ones.

I believe it's because of Transactions (Haven't touched that part yet) so I went on ahead trying to figure out what the code does. But....... I'm kinda stuck.

I don't understand how the migrations and transactions interact.

from the _waterfallBatch method forward it's all blurry to me. 

I'm don't even consider myself an intermediate javascript coder so go easy on me :D 

My main struggles are: the Transaction class with the transactor, the _useTransaction method and _transaction method and specially the warnPromise method.

If an explanation is possible on how thinks work in this level I would be eternally grateful.

**Comment by JoaoCnh** [comment]
There seems to be no answer to the Transactions problem in knex with the mssql driver. I tried and tried and tried but I just can't get it to work. 

Shame though, the query building and schema building were going really well.

**Comment by Grimace1975** [comment]
@JoaoCnh 
i am the writer of the mssql driver. not sure how the migrations work tho. All tests where passed, but don t really do much with migrations.

**Comment by JoaoCnh** [comment]
When I was making my version the integration tests failed on transactions with mssql driver. Basically the problem was engineering the mssql driver Transaction object correctly into the existing Knex

**Comment by rhys-vdw** [comment]
@JoaoCnh Why did you close the issue? We need to leave this open until it's resolved.

Would you be able to give more information about what's going wrong with Transactions? Is it possible the the problem is actually not in the MSSQL adapter, but in the transaction Promise logic? It might be worth trying [this PR](https://github.com/tgriesser/knex/pull/1114) which is soon to be merged into master.

**Comment by JoaoCnh** [comment]
Basically in this issue I wasn't capable of integrating the mssql driver transactions into the mssql dialect. The problem weren't promises.

I tried the recent mssql dialect developed by @Grimace1975 and although it migrates the knex_migrations table it doesn't migrate my table when doing knex migrate:latest

the stack trace:

`TypeError: expecting an array, a promise or a thenable

    See http://goo.gl/s8MMhc

    at PromiseArray.init [as _init] (c:\dir\node_modules\knex\node_modules\bluebird\js\main\promise_array.js:42:27)
    at Promise._settlePromiseAt (c:\dir\node_modules\knex\node_modules\bluebird\js\main\promise.js:579:21)
    at Promise._settlePromises (c:\dir\node_modules\knex\node_modules\bluebird\js\main\promise.js:697:14)
    at Async._drainQueue (c:\dir\node_modules\knex\node_modules\bluebird\js\main\async.js:123:16)
    at Async._drainQueues (c:\dir\node_modules\knex\node_modules\bluebird\js\main\async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (c:\dir\node_modules\knex\node_modules\bluebird\js\main\async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)`
