### ISSUE TITLE
Subselect support for update

### ISSUE THREAD

**Issue by katherine-barn2door** [tgriesser/knex#1087]
Looking at the docs for "update", it appears to only take straight values, if I understand correctly. Which then means there isn't a good way to do this:

```
UPDATE shipping s
SET s.offer_id =
  (SELECT o.id
   FROM offers o
   WHERE o.shipping_id = s.id);
```

I would guess I'd be looking for an API something like this:

```
knex.('shipping')
  .update('offer_id', function(offerId) {
    knex.select('id').from('offers').where('shipping_id', offerId);
  });
```

Postgres: http://www.postgresql.org/docs/9.1/static/sql-update.html

So is raw the only way I can go?

**Comment by chrisbroome** [comment]
Have you tried using a join for the update?

``` JavaScript
const query = knex.from('shipping AS s')
  .join('offers AS o', 'o.shipping_id', '=', 's.id')
  .update('s.offer_id', knex.raw('??.??', ['o', 'id']));

console.log(query.toString())
```
Output (newlines added for clarity):
``` SQL
    update "shipping" as "s"
inner join "offers" as "o"
        on "o"."shipping_id" = "s"."id"
       set "s"."offer_id" = "o"."id"
```

**Comment by katherine-barn2door** [comment]
No I haven't but I will if my version will support it. I've never seen this "??.??" documented anywhere. How did you learn about that syntax?

**Comment by chrisbroome** [comment]
That's a really good question. I'm sure it was in the documentation at some point, but it appears that it is not now.

**Comment by chrisbroome** [comment]
So it's not in the docs that are live at http://knexjs.org. It *is* documented in the master branch docs that I'm assuming will be published with the release of the next version. Take a look here for the info: https://github.com/tgriesser/knex/blob/master/index.html#L2093-L2096

**Comment by whitelynx** [comment]
Looks like that documentation was added 5 days after the last release (v0.9.0); I hope they release a new version soon so the documentation mentions this.

**Comment by wubzz** [comment]
This is possible via for example
```javascript
knex
.from('shipping')
.update({
    'offer_id': knex.from('offers').select('id').where('shipping_id', knex.raw('??', 'shipping.id')),
})
.toString();
//update `shipping` set `offer_id` = (select `id` from `offers` where `shipping_id` = `shipping`.`id`)
```
