### ISSUE TITLE
`knex.raw()` doesn't print queries when debugging

### ISSUE THREAD

**Issue by brianseitel** [tgriesser/knex#1088]
If I use a `knex.raw()` statement with a config like: `require(knex)({ client: 'pg', debug: true })`, then nothing shows up. But if I use the query builder, it shows up. Am I doing something wrong?

```js

var knex = require('knex')({ client: 'pg', debug: true });

return knex.raw('SELECT id FROM users');
```

Debugging doesn't print anything. However, if I use the builder..

```js

var knex = require('knex')({ client: 'pg', debug: true });

return knex('users').select('id');
```

I get the expected output in the console.

**Comment by blah238** [comment]
The only place that SQL queries are debug-logged is here: https://github.com/tgriesser/knex/blob/51ef27bd4fcb538abaa8ecfd001d1d1659aa398f/src/runner.js#L37

It would seem to be a bug that `runner.builder._debug` is undefined when it's a raw query.

**Comment by blah238** [comment]
Culprit seems to be here: https://github.com/tgriesser/knex/blob/51ef27bd4fcb538abaa8ecfd001d1d1659aa398f/src/raw.js#L20

Should be `client.config.debug` instead of `client.options.debug`.
