### ISSUE TITLE
'dropColumn' within 'hasColumn' does not work

### ISSUE THREAD

**Issue by techniq** [tgriesser/knex#1091]
I was attempting to make my rollback's more resilient when a column does not exist when being dropped (happens on a failed migration on occasion), and since there is not a `dropColumnIfNotExists`, I attempted to use `knex.schema.hasColumn` and then perform the `table.dropColumn` if exists.  Oddly, `table.dropColumn` is not ran if performed within the `hasColumn`, but works just fine outside of the check.

``` js
exports.down = function(knex, Promise) {
  return knex.schema.table('address', function (table) {

    // Doesn't work
    knex.schema.hasColumn('address', 'geocode_source').then(function (exists) {
      if (exists) {
        table.dropColumn('geocode_source');
      }
    });

    knex.schema.hasColumn('address', 'geocode_quality').then(function (exists) {
      if (exists) {
        table.dropColumn('geocode_quality');
      }
    });

    // Works
    //table.dropColumn('geocode_source');
    //table.dropColumn('geocode_quality');
});
```

**Comment by chrisbroome** [comment]
So, this isn't exactly how I'd like to do it either, but it works:

``` JavaScript
const tableName = 'address';

exports.down = (knex, bluebird) => {
  // array of columns to drop
  const columnsToDrop = [
    'geocode_source',
    'geocode_quality'
  ];

  return bluebird
    // filter the columns based on whether or not they exist
    .filter(columnsToDrop, columnName => knex.schema.hasColumn(tableName, columnName))
    .then(existingColumns =>
      knex.schema.table(tableName, t => {
        // for each existing column, drop it
        existingColumns.forEach(columnName => t.dropColumn(columnName));
      })
    )
};
```

If you're not using arrow functions (`=>`), then be *sure* to return the promise from each function.

**Comment by techniq** [comment]
Thanks @chrisbroome, that worked.

I experimented a little more, using arrow functions and not reusing the same `table` instance but using `knex.schema.table` each time I needed an instance, but surprisingly this doesn't work as well: 

```js
exports.down = function(knex, Promise) {
  const tableName = 'address';
  return knex.schema.table(tableName, table => {
    return Promise.all([
      knex.schema.hasColumn(tableName, 'geocode_source').then(exists => {
        knex.schema.table(tableName, t => t.dropColumn('geocode_source'));
      }),
      knex.schema.hasColumn(tableName, 'geocode_quality').then(exists => {
        knex.schema.table(tableName, t => t.dropColumn('geocode_quality'));
      })
    ])
  });
};
```

Any idea as to what the root issue is?  It would be nice to maybe add `dropColumnIfNotExists` to `knex.schema`.

**Comment by elhigu** [comment]
Use case of OP is not supported. One cannot use async functions inside alterTable handler function.

**Comment by MyElectricSheep** [comment]
Ok, quite late as well for @techniq 's question, but for people needing a `dropColumnIfExists` alternative (yes, it does happen we don't know for sure which column will actually exist); I did the following that worked well:

First I defined my target tables in an array, then mapped through it with an index, and for each table, mapped through the columns I needed to remove. It went like this:

`const tables = ['accounts', 'users', 'invitations', 'requests'];

const columnsToDrop = [
  ['budget', 'authorized', 'ratio', 'limit'],
  [
    'limit',
    'monthlyBudget',
    'teamMonthlyBudget',
    'teamMonthExpenses',
  ],
  ['monthlyBudget', 'limit'],
  ['budget', 'amount'],
];

exports.down = async function (knex) {
  return (clean = await Promise.all(
    tables.map(async (table, index) =>
      knex.schema.hasTable(table).then(async (exists) => {
        if (!exists) return null;
        return (accounts = await Promise.all(
          columnsToDrop[index].map(column =>
            knex.schema.hasColumn(table, column).then((hasColumn) => {
              if (hasColumn)
                return knex.schema.table(table, async (table) => {
                  table.dropColumn(column);
                });
            }))
        ));
      }))
  ));
};`

Not sure if it's an elegant solution, but hey, it worked :P

**Comment by donnfelker** [comment]
I put this into a `dbHelper.js` file and use it anywhere I need to rollback a column/etc. 

```javascript

const dropColumn = (knex, tableName, columnName) => {
    // knex does not have a dropColumnIfExists :\
    return knex.schema.hasColumn(tableName, columnName).then((hasColumn) => {
        if(hasColumn) {
            return knex.schema.alterTable(tableName, table => {
                table.dropColumn(columnName)    
            })
        } else {
            return null
        }
    })
}

module.exports = { dropColumn }
```

Usage in a migration:

```javascript
const { dropColumn } = require('../dbHelpers')

exports.up = knex => {
  return knex.schema
      .alterTable('myTableName', table => {
          table.string('myColumnName')
      })
} 

exports.down = knex => {
  return dropColumn(knex, 'myTableName', 'myColumnName')
};
 
```

**Comment by kjkent** [comment]
Thanks @donnfelker! Definitely saved me a job there.

I amended this very slightly as my use-case involves multiple schemas.

Of course, if using something other than the default `public` schema, amend the default parameter as necessary.

```JavaScript
const dropColumn = (knex, tableName, columnName, schemaName = "public") => {
    return knex.schema
        .withSchema(schemaName)
        .hasColumn(tableName, columnName)
        .then((hasColumn) => {
            if (hasColumn) {
                return knex.schema.alterTable(tableName, table => {
                    table.dropColumn(columnName);
                });
            } else {
                return null;
            }
        });
};

module.exports = { dropColumn };
```

**Comment by zgldh** [comment]
Here is what I do and it works for me.
`node v16.17.1`
`knex 0.21.18`


``` typescript
import Knex from 'knex'

exports.up = async (knex: Knex) => {
  if (false === await knex.schema.hasColumn('orders', 'extra_text')) {
    await knex.schema.alterTable('orders', table => {
      table.text('extra_text').defaultTo('').comment('Extra text shows on receipt page')
    })
  }
}

exports.down = async (knex: Knex) => {
  if (true === await knex.schema.hasColumn('orders', 'extra_text')) {
    await knex.schema.alterTable('orders', table => {
      table.dropColumn('extra_text')
    })
  }
}
```
