### ISSUE TITLE
Knex does not try to recover from terminated PG connections

### ISSUE THREAD

**Issue by mgartner** [tgriesser/knex#1111]
Using Knex 0.7.6, if Postgres terminates a connection, Knex does not try to create a new one. Eventually my app stops working once all connections have been terminated. I get this error when PG terminates a connection:

```
error: terminating connection due to administrator command
```

Ideally Knex would try to create a new connection when it receives this error. I don't see anywhere in the changelog referencing this issue, but has this been fixed in a more recent version of Knex?

**Comment by rhys-vdw** [comment]
@mgartner Are you able to update and test if this works with a newer version? I'm not personally aware of this error, but I haven't searched for it.

**Comment by mgartner** [comment]
I've only seen this error on very rare cases in production, so I'll try to reproduce this error first.

**Comment by mgartner** [comment]
I'm able to reproduce in 0.7.6 by manually terminating connections in PG:

```sql
SELECT pg_terminate_backend(pid) as killed from pg_stat_activity WHERE state LIKE 'idle';
```

I'll attempt to upgrade Knex and do the same.

**Comment by mgartner** [comment]
@rhys-vdw upgrading to knex 0.9.0 and bookshelf 0.9.1 seems to have solved the issue! I can terminate connections in PG manually, and they both reestablish connections automatically.

Thanks for your help.

**Comment by rhys-vdw** [comment]
Thanks, that would be awesome.

**Comment by rhys-vdw** [comment]
Whoops, hadn't read your most recent response. Great to hear it's been fixed. Thanks.
