### ISSUE TITLE
recuperate a date from Mysql

### ISSUE THREAD

**Issue by fsebbah** [tgriesser/knex#1116]
Hi,
My db turn on Mysql. The dates are stored in the format 'YYYY-MM-DD HH:mm:ss".
Whit a simple query via Knex, I recuperate the date with a difference of 1 day.
Sample: In mysql : "2015-09-08 00:00:00"
The data : "2015-09-07T22:00:00.000Z"
The config of knex is classic:
    connection: {
        host: 'host',
        user: 'user',
        password: 'password',
        database: 'database',
        debug: true
    }
If you have ideas,
Thanks,
Franck

**Comment by rhys-vdw** [comment]
What does "recuperate" mean in this context?

**Comment by fsebbah** [comment]
Hi,
In mysql, a date is storaged as this: "2015-09-08 00:00:00".
If I read the return of datas with moment.js the date is correct.
Sample: moment.(data.date).format("YYYY-MM-DD"), --> "2015-09-08" : Correct
To track the datas, i stock the global return in a json file and here the date is Incorrect with a difference of one day.: "2015-09-07T22:00:00.000Z"  
Thanks,
Franck

**Comment by elhigu** [comment]
duplicate  https://github.com/tgriesser/knex/issues/1461
