### ISSUE TITLE
postgres dropPrimary() ignores case, resulting error.

### ISSUE THREAD

**Issue by scarlet9** [tgriesser/knex#1120]
If a table has a name with uppercase letter (like `User`), `dropPrimary()` does not work for those tables since postgres folds their names into lower case without double quotes. 
Fixing [this line](https://github.com/tgriesser/knex/blob/775d6c2af7106b38d53083bd5185c189f2fcd01f/lib/dialects/postgres/schema/tablecompiler.js#L62) with double quotes like below might fix this problem.
```js
this.pushQuery('alter table ' + this.tableName() + ' drop constraint "' + this.tableNameRaw + '_pkey"');
```

**Comment by wubzz** [comment]
@scarlet9 Thanks for the report. A fix has been merged and is present in knex 0.10. See #1167
