### ISSUE TITLE
AWS Aurora

### ISSUE THREAD

**Issue by ghost** [tgriesser/knex#1122]
Hello there! Sorry if it isn't the correct place to ask such question, but I'd try. Amazon provides us their own implementation of RDBMS [Aurora](https://aws.amazon.com/rds/aurora/), that compatible with mysql. Question is: How can I use knex with it, if I can use it at all!?

Thanks,
Romain

**Comment by vanesyan** [comment]
Oh and HAPPY NEW YEAR :santa:

**Comment by shane-walker** [comment]
@vanesyan You should just be able to use the MySQL driver. According to the Aurora documentation it is fully compatible with MySQL APIs.

**Comment by willfarrell** [comment]
I'm using it with the mysql driver. Works like a charm. This issues can be closed. If you like you can add a PR for the docs letting others know to use the mysql driver.

**Comment by jpike88** [comment]
how on earth is this issue still open....

**Comment by jpike88** [comment]
I think some spring cleaning is in order guys XD

**Comment by elhigu** [comment]
Thanks! @jpike88 would be great help if you can go more issues through and spot some other obviously closable ones 👍
