### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by rstacruz** [tgriesser/knex#1125]
Editing index.html is a pain.

Would you like something based on gitbooks.com or docpress.github.io, where you'd just have Markdown files?

**Comment by thebearingedge** [comment]
Would love to help with docs, very interested to see what the maintainers think.

**Comment by rhys-vdw** [comment]
Without having yet looked into @rstacruz's suggestions, I'd prefer to use JSDoc. Inlining documentation makes it easy to read the code and keeps everything synchronised naturally. I've already used this approach for bookshelf, and [the theme](https://github.com/bookshelf/bookshelf-jsdoc-theme/) could be forked and reused for Knex.

JSDoc also provides a 'tutorials' feature which allows for Markdown files to be added to the documentation.

Transcribing all the information from HTML to JSDoc comments was an absolutely monumental task, but I think all in all it improved the docs pretty dramatically and would love to see this approach taken for knexjs.org.

**Comment by tgriesser** [comment]
I was actually thinking about gitbook for knex - just because I'm planning on splitting a lot of the pieces of  knex into individual components and so it might make it easier to split things up into "chapters"

https://github.com/GitbookIO/gitbook

**Comment by blah238** [comment]
:+1: This is an important issue. IMO JSDoc makes more sense for documenting an API, but either would be a welcome improvement over editing HTML by hand. Perhaps use both -- Gitbook for the concepts and examples and JSDoc for the API reference. We could probably even [generate Markdown from JSDoc](https://github.com/jsdoc2md/jsdoc-to-markdown).

**Comment by rstacruz** [comment]
yes, that is a sane way to go about with it IMHO. I use a similar setup for my own projects.

**Comment by johanneslumpe** [comment]
How do you all feel about using standard doc blocks in code, for every single method, and then generate documentation based on file name/directory structure and said doc blocks?

**Comment by wubzz** [comment]
https://github.com/knex/documentation
