### ISSUE TITLE
Knex won't release script execution unless destroy is called

### ISSUE THREAD

**Issue by rodrigogoncalves** [tgriesser/knex#1127]
I am trying to understand why do I have to explicitly call `knex.destroy()` in order to release the script execution when the Knex instance is created with an active connection (this behavior doesn't happen when Knex is initialised with `const knex = require('knex')({});`.

I've put a simple example that illustrates this. If the script below is saved as `script.js`, calling `$ node script.js` will only return to the console if `destroy()` is called explicitly.

Thank you

``` javascript
'use strict';
const Promise = require('bluebird');
const knex = require('knex')({
    client: 'sqlite',
    connection: {
        filename: ':memory:'
    }
});

console.log('> BEGIN');
return Promise.all([
]).then(function () {
    return knex.destroy();
}).finally(function () {
    console.log('> END');
    return;
});
```

**Comment by kibertoad** [comment]
Closing this down as a stale issue. Please open a new one if it is still relevant.
