### ISSUE TITLE
How get table schema from existing database using knex.js?

### ISSUE THREAD

**Issue by mistyharsh** [tgriesser/knex#1135]
I am trying to retrieve schema of an existing table (table description) in a **postgres** using **knex.js**. If my table is `users`, then using `postgres console`, I can do `\d+ users`, Is there anything equivalent for this in **knex**?

I am trying to build my custom automated migration framework on top of knex. If there is some existing solution, then that would work as well.

**Comment by mistyharsh** [comment]
After digging it more, I realize that it has to do with different SQL databases. For example, I will need to use `information_schema` to get schema details if I am using **postgres**. `Knex` itself won't do that. It is query builder and that's all. I must make queries using `Knex` to get my data (in my case schema - data about data)

Closing the issue.

**Comment by WilliamSWoodruff** [comment]
@mistyharsh Best idea I have right now is to save table column / type info on each model when it gets created in the DB. Does anyone else have a good solution for this?

**Comment by dashmug** [comment]
@wswoodruff There is no need for that since the DB already saves it.

For example in PostgreSQL,

```sql
SELECT * FROM information_schema.columns;
```

**Comment by wswoodruff** [comment]
Thank you @dashmug I was hoping nobody would respond to that hahaha. I've since learned about `knex.table(model.tableName).columnInfo()` -- and I'm using that on a migration lib right now! Soon to come out =)

**Comment by bennyn** [comment]
Hey @wswoodruff, is your migration lib already out by now? :)

**Comment by wswoodruff** [comment]
@bennyn Still working on it, and it still needs testing. Here it is if you wanna check the progress or try it out: [schwifty-migration](https://github.com/BigRoomStudios/schwifty-migration)

I've gotten `schwifty-migration` to spit out a knex migration file with MySQL and Postgres dbs, using [hapi](https://github.com/hapijs/hapi) and [schwifty](https://github.com/BigRoomStudios/schwifty) only right now.

I plan on eventually being able to use it to generate knex migration files without relying on `schwifty`.

**Comment by bennyn** [comment]
That's a good start! 

Can you give a sample on how a migration file (like `20170817143549_schwifty-migration.js`) looks like? Is it (when generated) independent of [schwifty](https://github.com/BigRoomStudios/schwifty)?

**Comment by haywirez** [comment]
Also interested in this, especially for creating a ephemeral DB for tests - is it possible to generate a seed file somehow from an existing PG database?

**Comment by farnetani** [comment]
I see in: https://github.com/niradler/rve-knex-migration, but it's not complete!

I'd like to have it too!

**Comment by kibertoad** [comment]
I don't think anyone from the core knex team is working on anything similar, but if anyone would consider contributing such functionality, that would be cool :)
