### ISSUE TITLE
Multiple postgres schemas in migrations

### ISSUE THREAD

**Issue by richardsimko** [tgriesser/knex#1138]
I'm trying to perform migrations on multiple postgres schemas (They all have the same schema and are only used to separate tenants) but I can't find a reasonable way to do this.

I know you can do `knex.migrate()` with a different `tableName`, however this just creates the tables in the "root" schema. I've also tried to implement my migrations to actually perform the tasks on each schema, however this will mean that all migrations are stored in a single table which might not be good, considering that a new schema can be created at any time a customer signs up. In that case I need some way for that schema to "catch up" with the current state, which can't be done by running all migrations since knex will register these as having been ran already.

What's the best approach here? And is it even doable?

**Comment by luthv** [comment]
+1

It would be great if we can have something like knex.migrate.withSchema('schema-name').latest()

**Comment by albertovasquez** [comment]
Any ideas for this request.  I'm in the same boat.  I wish to use migrations for tenant schemas.

**Comment by RichardSimko** [comment]
I ended up dropping the idea completely and going for a single schema. I'll revisit the issue once performance becomes a problem.

**Comment by albertovasquez** [comment]
@RichardSimko What I ended up doing in knexfile.js is allow for command line args.
Something like this should work.  Just started with this approach so haven't found any gotchas just yet.

const argv = require('minimist')(process.argv.slice(1));
let migrations;

```
if (!argv._[2]) {
  migrations = {
    directory: __dirname + '/migrations/public',
    tableName: 'public.migrations'
  };
} else {
  const schema = argv._[2];
  migrations = {
    directory: __dirname + '/migrations/tenant',
    tableName: `${schema}.migrations`
  };
}
```

Then for use that migrations object for your initialization configuration.  Then add a script in your package.json `migrate-latest` 

So for public migrations run
`npm migrate-latest`
and for tenant migrations run
`npm migrate-latest tenantname`

**Comment by elhigu** [comment]
closing old issue
