### ISSUE TITLE
a subquery 

### ISSUE THREAD

**Issue by fsebbah** [tgriesser/knex#1141]
Hi,
I don't know if the title is correct.
I have this query:

SELECT employee_id,compensatory_leave_category_id,paid_leave_category_id,presence_category_id,
nb_days_closed_category_id,extra_hours_category_id,days_not_working_category_id,hours_by_day
FROM jos_joomrh_event_working_time_parameters_year_profile jyp,
jos_joomrh_event_working_time_parameters jtp,
jos_joomrh_event_working_time_employees jte,
jos_joomrh_event_working_time_parameters_years jyear
where jyp.working_time_parameter_year_id=jyear.id
and jtp.id=jyp.working_time_parameter_id
and jte.working_time_parameter_id=jtp.id
and jyear.name_year=(select max(j1.name_year) from jos_joomrh_event_working_time_parameters_years j1)
order by employee_id;

The begining of my query in knex is:
    k('jos_joomrh_event_working_time_parameters_year_profile')
    .select(['employee_id','compensatory_leave_category_id','paid_leave_category_id','presence_category_id',
            'nb_days_closed_category_id','extra_hours_category_id','days_not_working_category_id','hours_by_day'])
        .innerJoin('jos_joomrh_event_working_time_parameters', 'jos_joomrh_event_working_time_parameters_year_profile.id', 'jos_joomrh_event_working_time_parameters.working_time_parameter_id')
        .innerJoin('jos_joomrh_event_working_time_parameters_years', 'jos_joomrh_event_working_time_parameters_years.id', 'jos_joomrh_event_working_time_parameters.working_time_parameter_year_id')
        .innerJoin('jos_joomrh_event_working_time_employees', 'jos_joomrh_event_working_time_employees.working_time_parameter_id', 'jos_joomrh_event_working_time_parameters.id')
        .where('employee.id', e.employee_id)
        .orderBy('name_year', 'desc')

How "translate" in knex the last line ?
and jyear.name_year=(select max(j1.name_year) from jos_joomrh_event_working_time_parameters_years j1)

Thanks,
Happy new year for knex and this team,
Franck

**Comment by carera** [comment]
You can use subqueries: http://knexjs.org/#Builder-where
```
...
.andWhere(
  'jyear.name_year', 
  knex('jos_joomrh_event_working_time_parameters_years j1').max('name_year')
)
...
```

**Comment by fsebbah** [comment]
it's very straightforward ;-)
Thks,
Franck
