### ISSUE TITLE
`references` function taking <table>.<column> syntax is undocumented

### ISSUE THREAD

**Issue by lourd** [tgriesser/knex#1148]
It's used in the [Bookshelf docs](http://bookshelfjs.org/#associations) but not shown in the Knex docs. It needs to be documented that this can be used instead of saying the slightly longer `references(<column>).inTable(<table>)`

**Comment by elhigu** [comment]
In many examples that syntax is used. e.g. in join documentation. If someone finds nice place to explain the table.column reference syntax please share and maybe send a pull request :+1:

**Comment by lourd** [comment]
I'm happy to make a PR but aren't clear where the docs are made. Is the entire knex.js site manually put together in the repo's [index.html](https://github.com/tgriesser/knex/blob/master/index.html)?

**Comment by elhigu** [comment]
Yep that is correct. All documentation is written directly to index.html.

**Comment by lourd** [comment]
Cool, just made a PR. Let me know how you think that looks
