### ISSUE TITLE
onUpdate Postgresql

### ISSUE THREAD

**Issue by stongo** [tgriesser/knex#1151]
Having a problem trying to chain the `onUpdate` method.
`table.timestamp('updated_at').defaultTo(knex.fn.now()).onUpdate('SET DEFAULT');`
results in 
`Knex:warning - migrations failed with error: table.timestamp(...).onUpdate is not a function`

**Comment by stongo** [comment]
Realized on update is only available on reference columns. so it was user error, but also uncaught :)

**Comment by elhigu** [comment]
"is not an function" errors are pretty hard to catch with js :)
