### ISSUE TITLE
How to read table with huge number of rows?

### ISSUE THREAD

**Issue by ashwanikumar04** [tgriesser/knex#1152]
Hello:

This is more of a question than an issue.
I have a table user which has say 1M rows. How can I read all the rows to do some processing on the data? Say send some emails using any message queue (RabbitMQ etc)

Thanks.

**Comment by vschoettke** [comment]
Take a look the .stream() (http://knexjs.org/#Streams-stream ) method. If dialect/driver supports it (e.g. Postgres) rows are read progressively.

**Comment by ashwanikumar04** [comment]
Hi,
I did see that link. However I was not able to get it working to read every row and process it.

This is what I am trying
```
  var stream = query.stream();
                    stream.on('error', function (err) {
                        // Handle error, an 'end' event will be emitted after this as well
                    })
                        .on('fields', function (fields) {
                            // the field packets for the rows to follow
                        })
                        .on('result', function (row) {
                            // Pausing the connnection is useful if your processing involves I/O

                            processRow(row);
                        })
                        .on('end', function () {
                            // all rows have been received
                        });
```
Not sure how to get it working. Any pointers?

**Comment by vschoettke** [comment]
Have you tried using just the normal `data` event?

**Comment by ashwanikumar04** [comment]
Hi, yes it is working :)
