### ISSUE TITLE
escape single quote incorrectly

### ISSUE THREAD

**Issue by snowcxt** [tgriesser/knex#1153]
escape ` '` (single quote) to ` \'` instead of `''` (two quotes) for postgres. For example:

```javascript
knex('table').insert({a: "tom's test"}).toString()
```

returns `insert into "table" ("a") values ('tom\'s test')` but should be `insert into "table" ("a") values ('tom''s test')`

**Comment by elhigu** [comment]
There is pull request in process https://github.com/tgriesser/knex/pull/1095 for fixing this. Closing as this is duplicate issue.
