### ISSUE TITLE
Extending knex

### ISSUE THREAD

**Issue by thetutlage** [tgriesser/knex#1158]
Is there any way to extend knex ( have not found one ) to add my own methods.

Below will not work because after the first method call knex returns an instance of queryBuilder.

``` javascript
var knex = require('knex')(config)
knex.paginate = function () {}
```

I also have an idea to have an `extend` method, which can be used to add/extend new methods, but before working on it, i want to know are you guys even interested in something like this or not.

**Comment by wubzz** [comment]
+1 For extend support

**Comment by elhigu** [comment]
I think there is no official way to extend query builder, I recall that there has been some talk about it for 1.0 stable version. Anyways maybe something really hacky like this could work for your case?

```js
var knex = require('knex')({client: 'pg'})
knex.client.QueryBuilder.prototype.newFunc = function () { 
  console.log("New query builder function"); return this; 
}
knex('table').newFunc().toString();
// outputs: 
// New query builder function
// 'select * from "table"'
```

**Comment by thetutlage** [comment]
how about having a `extend` method on knex instance to add new methods.

```javascript
knex.extend('paginate', function () {
   // this will be the current query chain
})
```

i did something like this and can submit a PR

**Comment by elhigu** [comment]
@rhys-vdw has there been discussion about knex extending interfaces for 1.0? If 0.x is getting that feature would be probably good to try to do it pretty much the same way. @tgriesser do you have an idea if there are some less obvious problems that this kind of feature could cause? 

I don't know knex codebase / use cases enough to be able to say if this feature would be ok to add :8ball:  

Would that extended method be available also in all subquerybuilders?

**Comment by wubzz** [comment]
@thetutlage  Sugar syntax suggestion:

```javascript
knex.extend({
	myNewFunction: function() {
		/**Do something**/
		return this;
	},

	myNewFunctionTwo: function() {
		/**Do something**/
		return this;
	}
});
```

```javascript
knex.QueryBuilder.extend({
	myNewFunction: function() {
		/**Do something**/
		return this;
	},

	myNewFunctionTwo: function() {
		/**Do something**/
		return this;
	}
});
```

Since knex and the QB are two different 'classes', this makes more sense. My two cents..

**Comment by thetutlage** [comment]
@wubzz i am planning to have a single method on the `knex` instance, not on the query builder and then that method will take care on how to add it lazily adding to the queryBuilder ( this will happen when an instance of queryBuilder is returned by the knex internally ).

Yes we have support for an object to have multiple methods, or a single key/value pair

**Comment by thetutlage** [comment]
Also submitted a PR. I am open to make changes for the good. Also want to know how interested the core contributors are in having the support for extending knex.

**Comment by rhys-vdw** [comment]
I'm on the fence about `extend`. Yes, I agree this would be a simple and useful way of modifying the `knex` instance. However, I'd like to rule out using the new OO language features as a possibility for this first. Certainly it would take a lot of work, but it might be worth seeing what it would take to use ES syntax to achieve the same end.

Due to knex's interface being a function, it might end up looking like this, which is not ideal:

```js
import QueryBuilder from 'knex/QueryBuilder';
import makeKnex from 'knex/makeKnex';

class CustomQueryBuilder extends QueryBuilder {
  // ...
}

export default makeKnex({ QueryBuilder: CustomQueryBuilder });
```

But maybe there is a nicer way?

Also @tgriesser, can you weigh in?

**Comment by timruffles** [comment]
I'd be up for working on this. A lot of the outstanding issues could be mitigated with some way to extend.

**Comment by thetutlage** [comment]
@timruffles I am not sure, haven't heard from anyone of them apart from @rhys-vdw

**Comment by RWOverdijk** [comment]
👍 I could really use this. I'd even be willing to help implement this. Can we reopen the issue? It looks relatively simple to implement. A QueryBuilder class that's then used in stead of a function.

**Comment by elhigu** [comment]
@RWOverdijk if you are able to implement extension stuff in a way that it is tested to works also in subquery builder and with initialized transaction, I think it would be ok with merging the feature. @rhys-vdw @tgriesser @wubzz any objections?

**Comment by nicholaswmin** [comment]
+1

**Comment by rickyk586** [comment]
Here's how I was able to monkey patch it for v0.12.7

```
var Knex = require('Knex');
var KnexQueryBuilder = require('knex/lib/query/builder');

var knexClient = Knex(config);

KnexQueryBuilder.prototype.newMethod = function(){
	console.log('in new method');
	return this;
};
knexClient.queryBuilder = function(){
	return new KnexQueryBuilder(knexClient.client);
};
```

**Comment by timhuff** [comment]
@rickyk586 Thanks for the tip. I figured I'd share likewise. I don't believe your last statement is necessary. Isn't it equivalent to [what already exists in the codebase](https://github.com/tgriesser/knex/blob/master/src/client.js#L69)?

Here's a full example, where I add a new method to support Postgres's `?|` (json contains any) operator:
```
const KnexQueryBuilder = require('knex/lib/query/builder')

KnexQueryBuilder.prototype.whereJsonbContainsAny = function (field, array) {
  const questionMarks = new Array(array.length).fill('?').join(',')
  return this.whereRaw(`?? \\?| array[${questionMarks}]`, [field].concat(array))
}
```

**Comment by nickell** [comment]
@rickyk586 Thanks for showing how you monkey patched it. I used your example for a while and just noticed [modify](http://knexjs.org/#Builder-modify) in the docs. It may not help with your use-case but for mine it goes like this:

```javascript
// Regular function
function throwIfNone(queryBuilder, errMsg = 'Entity not found') {
    queryBuilder._throwIfNone = errMsg
}

function checkThrowIfNone(response, obj, builder) {
    if (
        builder._throwIfNone &&
        obj.response &&
        obj.response.rowCount === 0
    ) {
        const err = new Error(builder._throwIfNone)
        throw err
    }
}

db.client.on('query-response', checkThrowIfNone)

// Inside some async method
const { first_name } = await db('user_table')
    .first('first_name')
    .modify(throwIfNone, 'User not found')
```

This particular method has come in handy when we're destructuring a response. It may not be as pretty in usage as adding a method to the query builder prototype but it's nice to avoid messing with knex internals.

**Comment by Cmacu** [comment]
+1
