### ISSUE TITLE
trx.commit, trx.rollback give eslint violations

### ISSUE THREAD

**Issue by feesjah** [tgriesser/knex#1166]
Hi, it's not really an important issue, knex works fine (thanks ! :) ) 
but eslint gives this error: "expected an assignment or function call and instead saw an expression."
whenever I use trx.commit; or trx.rollback;  Is there a way to avoid this ? 

Thanks in advance,

Rob

**Comment by timruffles** [comment]
I don't think this is an issue for the library authors :) Sounds like you need to either change your coding style, or your `.eslintrc` settings!

A code example would definitely help clear it up either way.

**Comment by feesjah** [comment]
yeah I know nothing is wrong with knex, I figured I might be doing something wrong
```
...
.catch(err => {
            console.log('error saving account, rolling back');
            console.error(err);
           ** trx.rollback;** 
          })

```
So, am I using this the wrong way, if so, how should I use it ? should i just do ?

**Comment by elhigu** [comment]
`trx.rollback`is function, try calling `trx.rollback()`. Please reopen the issue is problems continue.

**Comment by feesjah** [comment]
if I call trx.commit(), i get  "Transaction query already complete, run with DEBUG=knex:tx for more info" Even though I'm just calling it once. When I use trx.commit; or trx.rollback; withouth the () it works fine, same goes for rollback. And I am just calling it once, strange...

**Comment by tgriesser** [comment]
You're likely returning a promise to the transaction function which then automatically commits or rolls back the transaction, in which case you don't need to use `trx.commit` or `trx.rollback`

**Comment by feesjah** [comment]
Yep, works fine without it :o Thanks!
