### ISSUE TITLE
Knex object hangs program inside transactions

### ISSUE THREAD

**Issue by LyonesGamer** [tgriesser/knex#1171]
In the case of a code sample like this:

    const knex = require('knex')({...});

    knex.transaction(function(trx) {
        knex('table).select('id').first().then(function(id) {
            trx.update({'foo': 4}).where({'id': id}).then(function() {
            }
        }
    }

The call to knex() causes the application to hang indefinitely. While I can understand wanting the user to use trx inside a transaction, it would be better for it to return an error than hang.

**Comment by elhigu** [comment]
It shouldn't hang if you have DB connections available to do other request outside of the transaction inside a transaction... This might be related to this issue https://github.com/tgriesser/knex/issues/1040

**Comment by elhigu** [comment]
How is your connection pool settings? Could you try to make pool bigger to test if it still hangs to verify if the error is because of not having enough available connections to complete transaction?

**Comment by LyonesGamer** [comment]
I don't define connection pool settings, but that did encourage me to look at those settings, and noticed this:

"This connection pool has a default setting of a min: 2, max: 10 for the MySQL and PG libraries, and a single connection for sqlite3 (due to issues with utilizing multiple connections on a single file)."

I am using SQLite, so this would appear to be the issue.

**Comment by elhigu** [comment]
@LyonesGamer next release should throw an error after certain timeout if there are no available connections
