### ISSUE TITLE
Multi-column foreign keys

### ISSUE THREAD

**Issue by polkovnikov-ph** [tgriesser/knex#1179]
How to create a foreign key in the following db schema?

	CREATE TABLE `table1` (
		`id1` INT(11) NOT NULL,
		`id2` INT(11) NOT NULL,
		PRIMARY KEY (`id1`, `id2`)
	);
	CREATE TABLE `table2` (
		`id` INT(11) NOT NULL,
		`id1` INT(11) NOT NULL,
		`id2` INT(11) NOT NULL,
		PRIMARY KEY (`id`),
		INDEX `FK__table1` (`id1`, `id2`),
		CONSTRAINT `FK__table1` FOREIGN KEY (`id1`, `id2`) REFERENCES `table1` (`id1`, `id2`)
	);

**Comment by polkovnikov-ph** [comment]
Does anybody even care? :)

**Comment by polkovnikov-ph** [comment]
Does anybody even care? :)

@tgriesser

**Comment by polkovnikov-ph** [comment]
@elhigu That doesn't seem like a question. There's just no such API, yet I didn't want to say it that way.

A month have passed. Do we have any developers to comment on this?

**Comment by elhigu** [comment]
@polkovnikov-ph I added `question` tag to mark this issue as a question. That should indicate for people that they if they know or has time to look into this they may give an answer. 

You should be able to create composite primary key with:

```js
table.primary(['id1', 'id2'])
```

If you have first created those columns. For foreign key references my guess is that you need to use `knex.raw`. 

Have you tried any solution yourself?

**Comment by polkovnikov-ph** [comment]
@elhigu The problem was with foreign keys, the double primary key was needed to explain why this is an interesting case at all.

Yes, I did it with `knex.raw`. Yet this is a feature from SQL standard and is supported well in most DBs. I don't see why we have to use `knex.raw` to circumvent this issue. Such thing should have some built-in syntax in `knex`.

**Comment by raijinsetsu** [comment]
You can, though it's not in the documentation. You need to use the table builder:
```
table.foreign(['colA','colB'])
    .references(['colA','colB'])
    .on('tableB');
```

**Comment by elhigu** [comment]
@raijinsetsu  @polkovnikov-ph If that works, pull request for documentation update would be great :+1: And if it doesn't pull request for that feature would be nice to have too :)

**Comment by raijinsetsu** [comment]
It worked for me using v0.10.
I'll see about putting together a pull request sometime today.

**Comment by bin1357** [comment]
@polkovnikov-ph , it works, but i can't set name for foreign:
`knex.schema.createTable('table1', (table) => {
    table.integer('id1').notNullable();
    table.integer('id2').notNullable();
    table.primary(['id1', 'id2']);
}).then();

knex.schema.createTable('table2',(table)=>{
    table.integer('id').notNullable().primary();
    table.integer('id1').notNullable();
    table.integer('id2').notNullable();
    table.foreign(['id1','id2'])
        .references(['id1','id2'])
        .on('table1');
}).then();`

**Comment by raijinsetsu** [comment]
Created a pull request: https://github.com/tgriesser/knex/pull/1261

**Comment by icelic** [comment]
How would you do this but for the case where are foreign keys both from different tables.

For example something like this: 
`table.foreign(['id1','id2'])
        .references(['id1','id2'])
        .on(['table1', 'table2']);`

This ofcorse throws an error: 
`Unhandled rejection TypeError: Expected tableName to be a string, got: object`

**Comment by raijinsetsu** [comment]
I think you need to split the calls. Try something like this:

table.foreign(['id1']).on(['table1']);
table.foreign(['id2']).on(['table2']);
