### ISSUE TITLE
Unable to use transactions for Postgresql

### ISSUE THREAD

**Issue by ajay-shenoy** [tgriesser/knex#1183]
Am using node version v5.2.0, knex version ^0.7.3, bookshelf version ^0.7.9.

Not able to use transactions with knex object as well as with raw queries for asynchronous queries.
Eg: 
var knex = require('knex')({
		client: 'pg',
		connection: dbjson.postgres.slave,
		pool: {
			min: 0,
			max: 7
		}
	});
var dbObj = require('bookshelf')(knex);
var rawQry = 'Select ....'
dbObj.knex.transaction(function(trx) {
   dbObj.knex.transacting(trx).raw(rawQry)
   .then(function(res){
   })
   .catch(e) {}
.then(function(resp) {
  console.log('Transaction complete.');
}).catch(function(err) {
  console.error(err);
});

[TypeError: dbObj.knex.transacting(...).raw is not a function]

Please provide an appropriate solution.

**Comment by elhigu** [comment]
Try to change `dbObj.knex.transacting(trx).raw(rawQry).then(..)` -> `dbObj.knex.raw(rawQry).transacting(trx).then(...)`.

**Comment by wubzz** [comment]
I'm surprised if calling `.transacting` directly on the main knex object does not throw a TypeError.

`.transacting` is available only for an instance of raw or the querybuilder. (`knex.raw().transacting` or `knex(tablename).transacting`)

**Comment by ajay-shenoy** [comment]
Thanks. That worked.
