### ISSUE TITLE
Migration Promise.all() not executing in order

### ISSUE THREAD

**Issue by jlmakes** [tgriesser/knex#1187]
Turns out the pooling had nothing to do with it. The solution came from [this comment](https://github.com/tgriesser/knex/issues/993#issuecomment-143480048) in issue #993 

The problem was solved by forcing the query order with `.then`, for example:
```js
exports.up = function (knex, Promise) {
    return Promise.all([
        knex.raw("some query")
    ]).then(function () {
        return Promise.all([
            knex.raw("another query")
        ]);
    });
};
```

**Comment by elhigu** [comment]
@jlmakes Is there some issue with `knex` in this? It is `Promise.all` specs  which doesn't guarantee in-order execution of items... Actually it is pretty much the point why to use `Promise.all` to run many queries in parallel and wait that all are resolved before continue.

**Comment by jlmakes** [comment]
@elhigu I was running into odd behavior using `Promise.all` that `pool.max = 1` seemed to help with, but I think it was a fluke.

My problem was that my triggers were executing before the appropriate tables were created, and I saw no mention of using `.then()` in the Knex documentation, but I guess it’s the Bluebird documentation that applies here.

Everything is all good, now that I’m putting the dependent queries inside the `.then()`

**Comment by elhigu** [comment]
@jlmakes It did help because it forces all queries to use the same connection, so they couldn't be ran in parallel. Also wrapping all those requests to same transaction would have the same effect, since all queries of the same transaction must use the same connection for their execution.
