### ISSUE TITLE
Necessary whitespace trimmed from where condition parameters

### ISSUE THREAD

**Issue by raddevon** [tgriesser/knex#1189]
I want to query for a value that contains trailing whitespace, but it seems Knex is trimming the whitespace causing the query to return no results. Is this the intended behavior?

**Comment by rhys-vdw** [comment]
Do you mean a string value with trailing whitespace?

Please share code that can reproduce the example. Chain `.debug()` to have knex log out the query as it's executed.

**Comment by elhigu** [comment]
I just tried following, which seem to work fine

```js
knex = require('knex')({client:'pg'});
knex('table').where('str', 'wat ').toString();
// select * from "table" where "str" = 'wat '
```

**Comment by raddevon** [comment]
@rhys-vdw Yes, that's my meaning. It seems to be trimming trailing whitespace from a string value.

Here's the `.debug()` output. It appears to have the whitespace intact: 

```
{ method: 'select',
      options: {},
      bindings: [ 'BTWL4263059Y080KGN  ' ],
      sql: 'select "modemtimeout", "ipaddress" from "processors" where "hardwareid" = ?' }
```

Here's the code that produces the output:

```
knex
    .select('modemtimeout', 'ipaddress')
    .from('processors')
    .where({
      hardwareid: hardwareid
    }).debug()
    .then(function(rows) {
      if(rows.length > 0) {
        res.send(rows[0]);
      } else {
        res.status(404).end();
      }
    });
```

I can run the SQL against my database manually to get a single result as expected. Here's the SQL:

```
select "modemtimeout", "ipaddress" from "processors" where "hardwareid" = 'BTWL4263059Y080KGN  '
```

The Knex query returns an empty result array.

**Comment by elhigu** [comment]
@raddevon Are you using postgres dialect? If so I'll check if the positional binding preprocessing phase works correctly... toSQL() / toString() wouldn't reveal if the problem is in that.

**Comment by raddevon** [comment]
@elhigu Yes, I am using postgres. Thank you for your help!

**Comment by elhigu** [comment]
@raddevon I just went through the whole code how query is sent to node-postgres driver for execution and everything did seem to work correctly. 

Parameters passed to node-postgres were: 
```js
connection.query({ 
    text: 'select "modemtimeout", "ipaddress" from "processors" where "hardwareid" = $1' 
  }, [ 'BTWL4263059Y080KGN  ' ], 
  function (err, result) { ... });
``` 

and I tried out with my local DB that node-postgres didn't trim the string value either.

Your problem seems to be somewhere else than in knex / node-postgres.

Related code how `knex` send queries to node-postgres driver is here
https://github.com/tgriesser/knex/blob/master/src/dialects/postgres/index.js#L145

You may want to add some debug prints there in your `node_modules/knex` to dig in further what is wrong.

**Comment by raddevon** [comment]
@elhigu Thanks for checking into it. I tried commenting out everything up to my `then` and replacing the knex query it with a query run through node-postgres (Bluebird promisified) with the same `hardwareid` value. After doing that, the query returns a single row as I would expect.

I have also inspected the value at the line you reference, and I can see the spaces are still present. Not sure at this point what to attribute the problem to, but I'll continue to investigate and report back if I can figure it out.

**Comment by raddevon** [comment]
Found the issue. I thought I was using an environment variable to set the database config option in Knex, but that was only being used for node-postgres. (We use both now as we're in the process of transitioning our queries from node-postgres to Knex.) 

Sorry to have wasted your time, @elhigu & @rhys-vdw. Thanks for the excellent support!
