### ISSUE TITLE
When and how does knex escape queries?

### ISSUE THREAD

**Issue by bendulum** [tgriesser/knex#1190]
I have already posted to Stackoverflow [here](http://stackoverflow.com/questions/35257773/escaping-knex-mysql-query-statements) but without success so far.
Maybe someone here can help me out, below is the copy pasted question.

---

I'm fairly new to knex and databases in general, so this is a beginner question.
I found no clear mention in the [knex docs](http://knexjs.org/) about this.
Are non-raw knex queries automatically "safe"?

Secondly, for raw queries, I have several raw statements similar to this:

    var condition = _.map(ids, function(id) {
        return '`id`=' + id;
    }).join(' OR ');
    
    knex('categories')
        .whereRaw(condition)
        .select('*')
        .catch(_error.bind(null, cb))
        .then(function(res) { ... });

Would escaping the `id` in the condition with a function described [here](http://stackoverflow.com/a/7760578/3248285) be sufficient to escape that query? What else to look out fo in such a scenario?

**Comment by elhigu** [comment]
I added short answer to stackoverflow. tldr;  you should use raw bindings to escape column references / values in knex raw queries.
