### ISSUE TITLE
bind message supplies 1 parameters, but prepared statement "" requires 0 

### ISSUE THREAD

**Issue by NerdPad** [tgriesser/knex#1207]
I am trying to filter rows based on the `name` property in a `jsonb` column named `body`

`qb.select('id', 'body').from('persons').whereRaw("body ->> 'name' ILIKE '%?%'", [params.name])`

and I am getting the following error.

> select "id", "body" from "persons" where body ->> 'name' ILIKE '%$1%' - bind message supplies 1 parameters, but prepared statement "" requires 0 

Can you please point out the issue here? I am very new to Postgres & Knex

**Comment by elhigu** [comment]
My best guess is that postgres prepared statement `$1` parameter binding cannot be used in that kind of string literal. I have came across some other places too where postgre says that bindings are not allowed. 

One way to work around this should be use string concatenation: 
```js
qb.select('id', 'body').from('persons').whereRaw("body ->> 'name' ILIKE '%'||?||'%'", [params.name])
```

Pretty ugly though :(

**Comment by NerdPad** [comment]
This works, but it's seriously ugly.

Is concatenation (||) documented? I might have missed it.

**Comment by elhigu** [comment]
Yeah `||` operator is documented in PostgreSQL. I think MSSQL uses `+` and MySQL has function called `CONCAT()` for that.

The problem above seem to be that postgres positional bindings e.g. `$1` cannot be used inside string literal. 

Another way to fix this in knex side would be to add `%` marks to string which is going to be bound.

```js
qb.select('id', 'body').from('persons').whereRaw("body ->> 'name' ILIKE ?", [`%${params.name}%`])
```

Another undocumented way which might work:

```js
qb.select('id', 'body').from('persons').whereRaw("body ->> 'name' ILIKE '%?%'", [knex.raw(params.name)])
```

If I remember correctly in this case `knex` evaluate inner `knex.raw` before sending query to postgres driver... however that is undocumented implementation detail which might change in future.
