### ISSUE TITLE
Using .where({col: Array}) results in strange sql

### ISSUE THREAD

**Issue by wubzz** [tgriesser/knex#1212]
Noticed this while trying to run an `IN(val, val, val)` clause using only `.where`..

```javascript
var QueryBuilder = knex('table')
  .where({
      year: ['2015', '2016'],
      id: 2201
  });

console.log(QueryBuilder.toString());
select * from "table" where "year" = '{\"2015\",\"2016\"}' and "id" = '2201'
```

Is this the expected behavior? I was very surprised. For an Array I would have expected it to be treated as an IN, not to get stringified. Making an issue before a PR because I'm not sure if this is supposed to be this way or not.

**Comment by tuhoojabotti** [comment]
In PostgreSQL arrays are a valid type: [See the docs](http://www.postgresql.org/docs/current/static/functions-array.html#FUNCTIONS-ARRAY)

**Comment by wubzz** [comment]
That I know, but still struck me as pretty strange.. The workaround was to simply pass an instance of another querybuilder. Bound to strike again.
