### ISSUE TITLE
Update bluebird to 3.x

### ISSUE THREAD

**Issue by Rush** [tgriesser/knex#1216]
Bookshelf has bluebird 2.x and promises produced by it don't provide bluebird features, such as: 

`.catch() now supports an object predicate as a filter: .catch({code: 'ENOENT'}, e => ...).`
http://bluebirdjs.com/docs/new-in-bluebird-3.html

ref. tgriesser/bookshelf#1137

**Comment by elhigu** [comment]
@wubzz updated bluebird
