### ISSUE TITLE
inTable(undefined) fails silently

### ISSUE THREAD

**Issue by skleeschulte** [tgriesser/knex#1220]
table.foreign('foreignId').references('id').inTable(undefined);

fails silently whereas

    table.foreign('foreignId').references('id').inTable('nonExistentTable');

throws an error (env: knex 0.10.0, pg: 4.4.6, postgresql: 9.5, node: 5.6.0). Is that expected behaviour or is it a bug? I had a hard time to figure out why my foreign key wasn't created...

**Comment by rhys-vdw** [comment]
Thanks for the report. This should throw a `TypeError` on any non-string value.
