### ISSUE TITLE
Cannot seem to use named bindings for arrays

### ISSUE THREAD

**Issue by keithrz** [tgriesser/knex#1228]
```
var knex = require('knex');
var postgresConn = 'postgresql://user:pw@host:port/db?tcpKeepAlive=true';

var redshift = knex({
    client: 'pg',
    connection: postgresConn
});


var sql = redshift.raw('select * from schema.table where col_1 in (:col_1_values) and col_2 = :col_2_value',
    {col_1_values: [[1, 2, 3]], col_2_value: 99}).toString();

console.log(sql);
```

Expected output:
select * from schema.table where col_1 in (1,2,3) and col_2 = '99'

Actual output:
select * from schema.table where col_1 in (:col_1_values) and col_2 = '99'

knex version: 0.10.0
pg version: 3.6.2

**Comment by keithrz** [comment]
Since this is postgres, I also tried
where col_1 = ANY (:col_1_values)

**Comment by keithrz** [comment]
Fixed this by adding a space before the (

```
var knex = require('knex');
var postgresConn = 'postgresql://user:pw@host:port/db?tcpKeepAlive=true';

var redshift = knex({
    client: 'pg',
    connection: postgresConn
});


var sql = redshift.raw('select * from schema.table where col_1 in ( :col_1_values) and col_2 = :col_2_value',
    {col_1_values: [[1, 2, 3]], col_2_value: 99}).toString();

console.log(sql);
```

Could this be added to the documentation, please?

**Comment by keithrz** [comment]
Hmmm... spoke too soon, perhaps.  Now I'm wondering why my array of Numbers turns into an array of Strings.

Output:
select * from schema.table where col_1 in ( '{{"1","2","3"}}') and col_2 = '99'

invalid input syntax for integer: "{{"1","2","3"}}"

I tried updating to latest version of pg (4.5.1), and this did not make a difference.

**Comment by wubzz** [comment]
@keithrz Definitely should not require a space within parenthesis to make `(:col_1_values)` work, that must be a bug. @rhys-vdw Right?

However, in your latest example, you are using PG and specifying an Array as a binding. Since arrays are supported by postgres, they are not joined by a delimiter when using them as bindings. _(Last I checked, at least)_ With the exception of API functions such as `.whereIn(field, array)`.

**Comment by keithrz** [comment]
@wubzz thanks for replying.  I thought that if I used a 2-dimensional array, it would treat the array properly, regardless of whether or not the database supported arrays natively.  I'm following this part of the docs:

```
Note that due to ambiguity, arrays must be passed as arguments within a containing array.

knex.raw('select * from users where id in (?)', [1, 2, 3]);
// Error: Expected 3 bindings, saw 1

knex.raw('select * from users where id in (?)', [[1, 2, 3]])


Outputs:
select * from users where id in (1, 2, 3)
```

**Comment by keithrz** [comment]
My query works if I format it like this:

```
var sql = redshift.raw('select * from schema.table where col_1 = ANY ( :col_1_values::integer[]) and col_2 = :col_2_value',
    {col_1_values: [[1, 2, 3]], col_2_value: 99}).toString();
```

**Comment by wubzz** [comment]
@keithrz I see what you're saying, the example from the docs will work with `ANY` for postgres, but not for `IN`. _(Which is to be expected)_ Your latest example makes sense.

So to sum up this issue the bug currently in play is that using named bindings within parenthesis does not work unless a space is added after the `(`.

```javascript
let schemaBuilder = knex.raw('select * from users where id in (:test)', {test: [1, 2, 3]});
console.log(schemaBuilder.toString());
//select * from users where id in (:test)

let schemaBuilder = knex.raw('select * from users where id in ( :test)', {test: [1, 2, 3]});
console.log(schemaBuilder.toString());
//select * from users where id in ( '{"1","2","3"}')
```

The cause seems to be the regular expression run in `replaceKeyBindings`:
```javascript
  var regex = new RegExp('(^|\\s)(\\:\\w+\\:?)', 'g')
```

I'll see if I can get time this weekend for further investigation.

**Comment by wubzz** [comment]
@elhigu Based on https://github.com/tgriesser/knex/commit/ca3c1d0a2277f00d6e99ef6bfce7c692cd029af5 I'm guessing you'll know more about this than anyone. What's your take on this?

**Comment by keithrz** [comment]
I was wrong; this query does not work:

```
var sql = redshift.raw('select * from schema.table where col_1 = ANY ( :col_1_values::integer[]) and col_2 = :col_2_value',
    {col_1_values: [[1, 2, 3]], col_2_value: 99}).toString();
```

it returns this:
```
select * from schema.table where col_1 = ANY ( "1,2,3":integer[]) and col_2 = '99'
```

so one of the two semicolons is removed from ::integer[].  And the value is not converted to an array at this point.  It is "1,2,3" instead of  '{{"1","2","3"}}'

If I put the ::integer outside of the parens, it seems to convert the text correctly, but postgres complains about converting a boolean to integer[] (I assume the boolean is the result of the = ANY () expression)

**Comment by keithrz** [comment]
@elhigu , @wubzz , would it help to incorporate some of the logic that sequelize is using?

https://github.com/sequelize/sequelize/blob/master/lib/sql-string.js#L90

I'm going to try applying a similar regex on my local copy of knex.

**Comment by keithrz** [comment]
If I change raw.js to use a different regex, and skip double semicolons:

```
  var sql = raw.sql,
      bindings = [];

  sql = raw.sql.replace(/\:+(?!\d)(\w+)/g, function (full) {
    if ('::' === full.slice(0, 2)) {
      return full;
    }
    var key = full.trim();
    var isIdentifier = key[key.length - 1] === ':';
```

And my sql is this:
```
var sql = redshift.raw('select * from schema.table where col_1 = ANY (:col_1_values::integer[]) and col_2 = :col_2_value',
    {col_1_values: [[1, 2, 3]], col_2_value: 99}).toString();
```

I get this:

```
select * from schema.table where col_1 = ANY ('{{"1","2","3"}}'::integer[]) and col_2 = '99'
```

this may work in newer versions of postgres, but I'm using Redshift which is based on Postgres 8.0.

I really shouldn't have to do an explicit cast, since my bind variable contains numbers.  What should happen is that this code:
```
var sql = redshift.raw('select * from schema.table where col_1 = ANY (:col_1_values) and col_2 = :col_2_value',
    {col_1_values: [[1, 2, 3]], col_2_value: 99}).toString();
```
should translate to this:
```
select * from schema.table where col_1 = ANY ('{{1,2,3}}') and col_2 = '99'
```
that is, it should not have the double-quotes around each value. 

I'm still a little confused about when I should use a 1-dim vs. 2-dim array.  If I use a 1-dim array:
```
var sql = redshift.raw('select * from schema.table where col_1 = ANY (:col_1_values) and col_2 = :col_2_value',
    {col_1_values: [1, 2, 3], col_2_value: 99}).toString();
```
it should translate to this:
```
select * from schema.table where col_1 = ANY ('{1,2,3}') and col_2 = '99'
```

**Comment by keithrz** [comment]
It looks like the underlying binding issue is an issue with the pg library.  I was going to try pg-native
https://github.com/tgriesser/knex/commit/92c9653b546577cb59a69b584730e3b53c694a03

but I ran into other issues trying that.
TypeError: Cannot read property 'on' of undefined,
     at {obfuscated_project_root}/node_modules/knex/lib/dialects/postgres/index.js:79:19,

Looks like it's back to sequelize for me.  I don't get these issues with sequelize, even though I'm pretty sure it uses pg client, too.

The original regex issue,
: binding does not work unless there is a space between ( and : 
still needs to be addressed.  My binding issues, specific to Postgres, may be fixed if knex can handle pg-native.

**Comment by vcasadei** [comment]
Any news on this? I really could use WHERE IN in my code, but I cannot get arrays to work

**Comment by keithrz** [comment]
@vcasadei if you're using Redshift and running into array problems, there is a separate conversation here:
https://github.com/brianc/node-postgres/issues/1186

the issue with parsing bind variables for IN clauses has been fixed in knex.  The latest version should have the fix.

**Comment by vcasadei** [comment]
@keithrz I'm not using Redshift. I'll try the latest version.
