### ISSUE TITLE
expanding contributor base

### ISSUE THREAD

**Issue by timruffles** [tgriesser/knex#1230]
@tgriesser would you be open to bringing in more contributors? There's a lot of features/issues etc that would benefit.

e.g Postgres JSON support would be a fantastic feature, as would some way of extending the query builder via plugins.

I see a lot of people with good ideas for building the library out, making them contributors would move the library forward! :)

**Comment by nitetrik** [comment]
I totally agree!

**Comment by rhys-vdw** [comment]
Hey guys. I'm looking out for new contributors. Tim's pretty busy at the
moment, but I occasionally email him and ask him to add another
contributor. Send me an email at rhys.vdw@gmail.com telling me who you are
and what tasks you'd like to tackle.

**Comment by elhigu** [comment]
@timruffles Btw. I wrote JSON support for our ORM which is built on top of knex... Maybe the biggest challenge in it is to define syntax how to refer fields inside jsonb columns etc... I'm happy to participate if someone likes to implement that directly to knex.

**Comment by ngoctranfire** [comment]
When you mention postgresql json support, do you mean the functions and operations on json in postgresql?? http://www.postgresql.org/docs/9.3/static/functions-json.html

**Comment by elhigu** [comment]
@ngoctranfire Yes, our implementation was Postgres 9.4 JSONB specific... would be awesome to have some abstraction which would work with MySQL and PostgreSQL.

**Comment by timruffles** [comment]
@elhigu awesome, would be a fantastic feature to have!

**Comment by kibertoad** [comment]
I think knex is pretty active lately and also plenty of people are actively contributing, so I would consider this resolved.
