### ISSUE TITLE
MSSQL Config option, 'host'

### ISSUE THREAD

**Issue by wubzz** [tgriesser/knex#1235]
Spontaneously found myself having to use mssql this evening _(oh god..)_, and figured I'd try knex for this. At first, I was stumbled by the following:

```javascript
knex({
client: 'mssql',
connection: {
host: 'IP Here',
...
...
}
});
```

Generating a connection string of `undefined:1433`. This is because the mssql module expects `server`, not `host`. This should either be clarified in the documentation, or knex could make `server` = `host` prior to sending the options object down to the `mssql` module. _(I know mssql is new for knex)_

**Comment by rhys-vdw** [comment]
All the clients should take a similar config object. Any variation is confusing.
