### ISSUE TITLE
Seeding multiple tables fail

### ISSUE THREAD

**Issue by kahwooi** [tgriesser/knex#1243]
I am trying to seed data for 2 tables, first is to insert into users, return the user id, and insert into account table, but no data is inserted into both tables:

```
exports.seed = function(knex, Promise) {
  return Promise.join(
    // Deletes ALL existing entries
    knex('users').del(), 
    knex('accounts').del(),

    // Inserts seed entries
    knex('users').insert({
        uerId: '1231231',
        email: 'kel@kel.com'
    }).then(function(result){
      knex('accounts').insert({
        accountId: '123',
        userId: result[0].userId
      });
    })
  );
};
```

**Comment by rhys-vdw** [comment]
Promise.join does not guarantee order of execution. I've seen this pattern suggested a number of times - it is wrong. Chain promises together with `.then` so they are executed sequentially.

Look at the debugging section of the docs to see how to get query traces and check what's actually going on.

We can reopen this issue if that does not solve your problem.

**Comment by SlashmanX** [comment]
> I've seen this pattern suggested a number of times - it is wrong.

_sorry for bumping an old issue_ but the reason this is suggested is because when you create a seed using the CLI, the file is prefilled with this:

```

exports.seed = function(knex, Promise) {
  return Promise.join(
    // Deletes ALL existing entries
    knex('table_name').del(), 

    // Inserts seed entries
    knex('table_name').insert({id: 1, colName: 'rowValue'}),
    knex('table_name').insert({id: 2, colName: 'rowValue2'}),
    knex('table_name').insert({id: 3, colName: 'rowValue3'})
  );
};
```

Which seems to be very wrong if they're not run in order...

**Comment by elhigu** [comment]
@SlashmanX Huh, you are right https://github.com/tgriesser/knex/blob/master/src/seed/stub/js.stub that is bug, that seed file is done horribly wrong :) I'll open an issue about it.

**Comment by KhalifaGad** [comment]
any updates?
