### ISSUE TITLE
How to do casting?

### ISSUE THREAD

**Issue by zettam** [tgriesser/knex#1244]
`select count(*)::integer from mytable`
How to do this properly with knexjs?

**Comment by rhys-vdw** [comment]
```js
knex('mytable').select(knex.raw('count(*)::integer'))
```

A more elegant solution to the big integer as string issue is detailed in #387.

**Comment by sagidM** [comment]
@rhys-vdw `global Knex.raw is deprecated, use knex.raw (chain off an initialized knex object)` (https://github.com/jfgodoy/knex-postgis/issues/20)

I updated it accordingly, using `knex-postgis` https://github.com/jfgodoy/knex-postgis/issues/20#issuecomment-312404336

Now the query: `.select(st.asText('count(*)::integer'))`
shows: `column "count(*)::integer" does not exist`

**Comment by elhigu** [comment]
@sagidM `knex.raw` definitely exists. You just need to call it from configured knex instance, not from `require('knex').raw`. And about `knex-postgis` you should ask elsewhere.
