### ISSUE TITLE
Unable to return multiple fields on update

### ISSUE THREAD

**Issue by caelon** [tgriesser/knex#1245]
I'm trying to use `.returning` as explained in #132 but I'm not having any success. Here's the snippet:

    db('challenges').where('challenged', '=', challengedName)
      .returning(['id','challenger', 'challenged'])
      .update( {
        userA: chal[0].challenged,
        userB: chal[0].challenger
      })
      .then(function(dosomething) {
        console.log("You can do a then after an update");
        console.dir(dosomething);
      })
      .catch(function(error) {
        console.error(error)
      })

If `.returning` has any of those fields by itself, the `.then` fires just fine and the query showing up in debug looks correct. If I try the above, I get:

    { method: 'update', 
      options: {}, 
      bindings: [ 'Don2', 'Don', 'Don' ], 
      sql: 'update "challenges" set "userA" = ?, "userB" = ? where "challenged" = ?', 
      returning: undefined }

Either I've implemented `.returning` improperly or it's not working for `.update`. Any thoughts?

**Comment by caelon** [comment]
Sorry, not positive why the carriage returns aren't working in the code. I'll keep fiddling with it.

**Comment by wubzz** [comment]
@caelon What version of knex are you using? And what is the output of `dosomething` when you run the query with multiple returning columns?

Testing this locally in 0.10 I get the following:

```javascript
console.log(
	test('challenges').where('challenged', '=', 'test')
	.returning(['id','challenger', 'challenged'])
	.update( {
		userA: 'test',
		userB: 'test2'
	}).toSQL()
);
{
  method: 'update',
  options: {},
  bindings: [ 'test', 'test2', 'test' ],
  sql: 'update "challenges" set "userA" = ?, "userB" = ? where "challenged" = ? returning "id", "challenger", "challenged"',
  returning: [ 'id', 'challenger', 'challenged' ] 
}
```

**Comment by caelon** [comment]
Ugh, I'm using 0.10 as well. `dosomething` doesn't returning anything - neither the `console.log` nor the `console.dir` fire. I've assumed it's because the `.returning` is undefined and therefore not doing anything.

If it's working for you, I'm completely stumped.

**Comment by caelon** [comment]
Adding code that surrounds the above in case it's messing it up:
```
db.select().from('challenges').where('challenged', '=', challengedName)
    .then(function(chal) {
        db('challenges').where('challenged', '=', challengedName)
            .returning(['id','challenger', 'challenged'])
            .update( {
                userA: chal[0].challenged,
                userB: chal[0].challenger
            })
            .then(function(dosomething) {
                console.log("You can do a then after an update");
                console.dir(dosomething);
            })
            .catch(function(error) {
                console.error(error)
            })
    .then(function(chal2) {
        res.send('<Response><Sms>The duel is on! You will be notified when the result is determined.</Sms></Response>');
    })
    .catch(function(error) {
        console.error(error)
    })
})

```

**Comment by wubzz** [comment]
@caelon That *should* be throwing `.then of undefined` or `.catch of undefined` errors because of the last `.then` and `.catch` not being called on a promise or a querybuilder. Which in turn would mean the code is not being executed. The indentation in your post doesn't make this too obvious, but placing your code in my IDE fixes the indentation:

```javascript
db.select().from('challenges').where('challenged', '=', challengedName)
	.then(function(chal) {
		db('challenges').where('challenged', '=', challengedName)
			.returning(['id','challenger', 'challenged'])
			.update( {
				userA: chal[0].challenged,
				userB: chal[0].challenger
			})
			.then(function(dosomething) {
				console.log("You can do a then after an update");
				console.dir(dosomething);
			})
			.catch(function(error) {
				console.error(error)
			})
			.then(function(chal2) {
				res.send('<Response><Sms>The duel is on! You will be notified when the result is determined.</Sms></Response>');
			})
			.catch(function(error) {
				console.error(error)
			})
	})
```

Try this instead:

```javascript
db.select().from('challenges').where('challenged', '=', challengedName)
	.then(function(chal) {
		return db('challenges').where('challenged', '=', challengedName)
			.returning(['id', 'challenger', 'challenged'])
			.update({
				userA: chal[0].challenged,
				userB: chal[0].challenger
			})
	})
	.then(function(returningRows) {
		console.log("You can do a then after an update");
		console.dir(returningRows);
		res.send('<Response><Sms>The duel is on! You will be notified when the result is determined.</Sms></Response>');
	})
	.catch(function(error) {
		console.error(error);
	});
```


I see you are selecting a row and using index 0 without checking if a row was found too. This can cause application errors if no rows could be found. I would suggest running only the update query with a returning statement, not the select query. Something like this:

```javascript
db('challenges').where('challenged', challengedName)
	.update({
		userA: knex.raw('challenged'),
		userB: knex.raw('challenger')
	})
	.returning(['id', 'challenger', 'challenged'])
	.then(function(returningRows) {
		if(returningRows.length > 0) {
			res.send('<Response><Sms>The duel is on! You will be notified when the result is determined.</Sms></Response>');
		} else {
			//No rows matched/updated, no duel started
		}
	})
	.catch(function(error) {
		
	});
```
```javascript
update "challenges" set "userA" = challenged, "userB" = challenger where "challenged" = ? returning "id", "challenger", "challenged"
```

That way you can avoid potential errors in your current code, while also checking to see if a duel is started or not depending on amount of updated rows in the query.

**Comment by caelon** [comment]
@wubzz Thank you very much for the refactor. Your first suggestion works fine while the second one still has `.returning` of undefined. I'll work to figure out why. I appreciate the time and effort you put into what ended up being my ignorance, not any fault of the code. I'll close the issue.

On a side note, are the docs from knexjs.org in this repo? I'm willing to write a pull request to update the `.returning` docs to include multiple fields if so. I couldn't find them.

**Comment by wubzz** [comment]
@caelon Yes, see `index.html`. I'll gladly merge an update to `returning` as it does in fact support `[columns]` not just `column`.
