### ISSUE TITLE
Increments is Primary by default?

### ISSUE THREAD

**Issue by NerdPad** [tgriesser/knex#1248]
Does ```table.increments()``` automatically sets the column as primary key, or do we have to do something like this ```table.increments().primary()```

**Comment by wubzz** [comment]
@NerdPad as specified in the documentation:

> Adds an auto incrementing column, in PostgreSQL this is a serial. This will be used as the **primary key** for the column.

So you should not have to manually call `.primary()` after `.increments()`, however if you *do* call it after `.increments()`, nothing will happen as it's already a primary.

**Comment by NerdPad** [comment]
Thank you.
