### ISSUE TITLE
Oracle update method not adding 'returning' to query

### ISSUE THREAD

**Issue by AiNoKame** [tgriesser/knex#1249]
Oracle inserts are working great, but whenever knex builds an Oracle update query where I specify `*` (or any column) as returning, it doesn't show up in the built query:

```
return db('access_tokens').update({
    valid: false,
    updated_at: db.fn.now()
  }, '*')
  .where({
    token_hash: '916831e2ca46a4770cc334b4875cd483116005e71321c460d180951e118026a670cf8cb6dd7b856a5f4098ebf77d7291c18c908ae1c00a54ca64a35b8151005d'
  });
```

```
{ method: 'update',
  options: {},
  bindings:
   [ 0,
     '916831e2ca46a4770cc334b4875cd483116005e71321c460d180951e118026a670cf8cb6dd7b856a5f4098ebf77d7291c18c908ae1c00a54ca64a35b8151005d' ],
  sql: 'update "access_tokens" set "updated_at" = CURRENT_TIMESTAMP, "valid" = ? where "token_hash" = ?' }
```

The update return value is always the rowid (I think). Should `returning` and/or `returningSql` be working with Oracle's update implementation?

**Comment by rhys-vdw** [comment]
Thanks for the retort. As far as I know, only the MySQL and PostgreSQL
adapters support returning. It is ignored by other dialects. It seems
Oracle supports the syntax, so there's no reason the adapter doesn't. We'll
take a PR for this.
