### ISSUE TITLE
How to upload Blobs to Mysql

### ISSUE THREAD

**Issue by Hectorhammett** [tgriesser/knex#1259]
Hi guys! I'm usually a php guy, and i do know that it's preferable to store the file in a server and storing the url on the database.

But now, i'm creating a desktop app with NWJS, and using knex and bookshelf for the proyect. The thing is that because it's a desktop app, but with a centrilzed DB, im not using the DB as a server as a whole, just as a Mysql server. So, i can't upload the file directly into the computer, i mean, probably could, but have to try to look for any protocols, and that has to be available on every OS (That's one of the reaons of using NWJS, because it's portable).

So, i need the user to upload a file, and then store it in the DB. So i  have to use a blob. I try a direct insert:

```
Fs.readFile(path, function(err, buffer) {
        if (err) {
          console.error(err);
          return;
        }
        console.log("readed the file");
        Knex('pdf').insert({
          string: buffer,
          fileType: "pdf",
          idManifiesto: idManifest
        }).then(function(){
          notify("pe-7s-check","Se ha guardado el manifiesto correctamente","success");
        }).catch(function(err){
          console.error(err);
          notify("pe-7s-close-circle","Hubo un error con la base de datos. Favor de revisar que el servidor se encuentre encendido.","danger");
        });
```

This gives me an ECONRESSET error. Any ideas?

Thanks guys!

**Comment by wubzz** [comment]
@Hectorhammett Could you paste the entire contents of `err` including the stack?

Also, out of curiosity, any particular reason why you wouldn't just Base64 the buffer for simplicity?

**Comment by Hectorhammett** [comment]
Ohh thanks, unfurtinatelly, right now i can't post the stack, i'm at work, and this proyect is a freelance proyect for a client.

How would i convert it to Base64?
```
Fs.readFile(path, "base64",function(err, buffer)) 
```
?

**Comment by wubzz** [comment]
@Hectorhammett Just call toString with `base64` as argument on the buffer itself.

```javascript
Fs.readFile(path, function(err, buffer) {
var base64 = buffer.toString('base64');
});
```

And when you load from the database, to create the buffer again:

```javascript
var buffer = new Buffer(base64string, 'base64');
```

**Comment by Hectorhammett** [comment]
All righty then, in a few hours i'll be posting the results. Thanks!

**Comment by Hectorhammett** [comment]
@wubzz Finally had some time to test it out! I worked man! Putting into a Base64 encoding works! I have it in my DB now.

But how do i open the file with the buffer? Do i have to save it as a file and then FS? Or how could i write the file back into a folder?

Thanks again man!

**Comment by Hectorhammett** [comment]
I tried this but it's giving me a corrupted file:
```
var buffer = new Buffer(archivo.string,'base64');
  Fs.writeFile('gotBack.pdf',buffer,'base64',function(){
    console.log("ready");
  })
```

**Comment by Hectorhammett** [comment]
YEAH BABY! Done it! I was using the blob type in Mysql, changed to text, and now it's working! Thanks man! You really REALLY helped me a lot!

**Comment by wubzz** [comment]
No problem!

**Comment by Hectorhammett** [comment]
Hello guys! I'm back, do i have to open another thread? I'm having one problem with this exact question tho:
I'm having an econreset on uploading Large Files. Any ideas how to fix this?
