### ISSUE TITLE
Error:Timeout acquiring a connection. The pool is probably full. 

### ISSUE THREAD

**Issue by kozer** [tgriesser/knex#1264]
Hello to everyone!
I have a problem and i want to find a solution.
I need to scrap a site and get some data from it.
There are a lot of data, worst case scenario is about 40.000.
Because of high cpu and memory usage i get the following error:

`Unhandled rejection Error: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?`

and as you guess everything blows up.

I use bookshelf with knex, and I try to make chunk save the data, all eficiense as possible.
Because i dont know if the data are already in my db, i came to something like this:

```
function sequence(products, vendor) {
  function chain(products, vendor) {
    if (!products.length) {
      return Promise.resolve();
    }
    return Promise.map(products.splice(0, 100), (product) =>  {
     /* Some validations to product */
      return bookshelf.knex('my_table')
        .where('someId', vendor.id)
        .andWhere('productCode', product.code)
        .update(product)
        .then((affected) => {
          if (!affected) {
            return tableModel.forge(product)
              .save()
              .then()
              .catch(function ignore() {});
          }
        });
    }).then(() => {
      return chain(products, vendor);
    });
  }
  return chain(products, vendor);
}
```

I want to accomplish something like `bulkInsert` function in knex to make it more efficient or to use `.toString` method on my chuck as i read this is more efficient for large amount of rows.
Any suggestions?

**Comment by wubzz** [comment]
@kozer You can adjust the timeout before this error is thrown, see [this](http://knexjs.org/#Installation-acquireConnectionTimeout).

I don't know if this is a pool config issue or if it's due to running this in parallel with 400,000 objects, but at some point the timeout of 10sec is reached on acquiring a new connection.

**Comment by kozer** [comment]
I thought that this might be a solution too, but I haven't try it yet.
But Im also intersted in a cleaner solution.
Did you find any?
How i can do better? I ll try the timeout thing and i ll update.

**Comment by wubzz** [comment]
@kozer Assuming I'm reading your code correctly, something like this should do I suppose. I haven't worked with bookshelf so I left that part out.

```javascript
let Promise = require('bluebird');
function processData(products) {
	var db = require('knex')({...});
	return Promise.mapSeries(products, (product) => {
		return db('my_table')
		.where({
				someId: vendor.id,
				productCode: product.code
			})
		.update(product)
		.then((affectedRowCount) => {
				if(affectedRowCount > 0) {
					return Promise.resolve();
				}
				return db('my_table')
				.insert(product);
			})
	})
}
```

Called by

```javascript
processData(products)
.then(() => {})
.catch((error) => {});
```

It's essentially what you already wrote yourself. They're both a variant of an *UPSERT*. If you are using postgres 9.5+ you could take a look at their new *UPSERT* support and run `.raw` queries instead. *(As UPSERT is not yet directly supported via knex API afaik)*
