### ISSUE TITLE
A raw query that runs in Windows but not on Ubuntu?

### ISSUE THREAD

**Issue by skywickenden** [tgriesser/knex#1266]
This query is never returning on ubuntu:

    const query = knex.raw(`
        INSERT INTO design_aperture
        (designId, id, x, y, width, height)
        SELECT ?, id, x, y, width, height
        FROM product_aperture
        WHERE productId = ?
      `, [
        designId,
        productId,
      ])
      .debug()
      .then((result) => {
        console.log('then running', result);
        resolve(true);
      })
      .catch( (error) => {
        console.error('\nsql error: \n',__filename, '\n', error, '\n');
        resolve({ error: true });
      });

Works fine on windows. On ubuntu .debug never runs, neither does .then or .catch

designId and productId are both correct.

Column name casing is correct.

**Comment by elhigu** [comment]
Which database are you using? e.g. with postgres case sensitive column names should be wrapped to ""...

Does this work any better? 
```js
const query = knex.raw(`
    INSERT INTO design_aperture
    (??, id, x, y, width, height)
    SELECT ?, id, x, y, width, height
    FROM product_aperture
    WHERE ?? = ?
  `, ['designId', designId, 'productId', productId])
  .debug()
  .then((result) => {
    console.log('then running', result);
    resolve(true);
  })
  .catch( (error) => {
    console.error('\nsql error: \n',__filename, '\n', error, '\n');
    resolve({ error: true });
  });
```

Does ubuntu work without `.debug()` added?

**Comment by skywickenden** [comment]
Thanks for responding @elhigu. It's MySql and the problem is not to do with case. I have a new idea about what is causing it, but am not sure how to investigate. I have isolated this code and it actually runs fine on its own. Yet the execution definitely reaches this query, it just never completes. This query is running inside a nested promise. It runs two levels down in the .then of previous knex queries. Could it be that there are no available connections due to them still being tied up? How could I ascertain that this is the problem?

When it runs on Windows there are 7 connections available in the pool. However on Ubuntu there is only one. Which could explain why it is a problem.

To be clear, the code is in several different files, but If I compress it into one it looks like this.

    knex.('query one')
      .then(() => {
        knex.('query two')
          .then(() => {
            promise.all([
])
           });
         });

**Comment by skywickenden** [comment]
As I suspected, this was caused by the limited connection pool. The bug was in the transaction code. Which was resulting in the query requiring two connections which worked fine on Windows as it had 7 available but failed on Ubuntu as it only had one.

**Comment by wubzz** [comment]
@skywickenden Having a hard time understanding that code, but it doesn't look like to me that you're running the queries in the actual transactions. You're creating a transaction, but then you are not using the `transaction` object to run queries, and you are not calling `.transacting(transaction)`.

I realize you marked this as closed/solved, but thought I should mention it.

**Comment by skywickenden** [comment]
@wubzz Yes, that was part of the problem.
