### ISSUE TITLE
Select * hangs forever if time is mocked with sinon

### ISSUE THREAD

**Issue by ejlangev** [tgriesser/knex#1267]
Node version: 4.3.2
Knex version: 0.9.0
Pg version: 4.5.1
Sinon version: 1.17.3

Commenting out the `sinon.useFakeTimers(Number(date))` causes this to run just fine.  Otherwise it seems to hang forever.

``` js
var knex = require('knex');
var sinon = require('sinon');

var pg = knex({
    debug: true,
    client: 'pg',
    connection: {
        host: 'localhost',
        user: 'postgres',
        password: 'password',
        database: 'test_db'
    }
});

var date = new Date();
date.setDate(25);
date.setMonth(1);
clock = sinon.useFakeTimers(Number(date));

var table = pg('test_table');

table().select('*')
    .then(function(result) {
        console.log('NEVER REACHED');
    })
    .catch(function(err) {
        console.log('NEVER REACHED');
    })
```

Not sure if this is a problem with knex or with pg underneath though.

**Comment by ejlangev** [comment]
Seems to be because `pool2` relies on behavior of `setTimeout`.  Using `sinon.useFakeTimers(...)` replaces several methods including `setTimeout` with synchronous versions which breaks it.  Can fix by replacing with: `clock = sinon.useFakeTimers(Number(date), 'Date');`

**Comment by robwilkerson** [comment]
I see the same Knex/Sinon conflict using MySQL. I was re-deploying some old integration tests from less than a year ago with updated dependencies and was having a hell of a time figuring out why the code didn't work.

After lots of trial, even more error, restoring module state of the old app and working forward, it looks like something changed in v0.8.0 of Knex. If I roll Knex all the way back to `0.7.6`, my existing code works fine. I can also verify that @ejlangev's workaround works. Here's my code with his changes:

```javascript
beforeEach(function() {
    return fixtures.load(data)
        .then(function() {
            let date = new Date().getTime();
            clock = sinon.useFakeTimers(date, 'Date');
            return;
        });
});
afterEach(function() {
    return fixtures.clear(data)
        .then(function() {
            return clock.restore();
        });
});
```
Note that my `fixtures` methods return a Knex promise.

**Comment by w4-hojin** [comment]
API was updated 
```
fakeClock = sinon.useFakeTimers({
        now: new Date().getTime(),
        toFake: ['Date'],
      });
```

**Comment by elhigu** [comment]
I don't think this is knex's problem.

**Comment by meelash** [comment]
For posterity, you can use the shouldAdvanceTimers option on sinon.useFakeTimers or call clock.runAll to have this work correctly while stubbing setTimeout and other functions besides Date.
