### ISSUE TITLE
Adding support for array values in object passed to 'where' functions

### ISSUE THREAD

**Issue by elhigu** [tgriesser/knex#1281]
There was initial PR https://github.com/tgriesser/knex/pull/1024 to add support for passing objects containing array values to the `where` function. This allows for shorter and more concise syntax when querying for anything else than `=`. Example:

Previously:

`Player.where('team', 'foo').andWhere('score_record', '>=', 500).fetchAll();`

Now with this change:

`Player.where({
  team: 'foo',
  score_record: ['>=', 500]
}).fetchAll();
`

Discussion about the feature may be continued here.

**Comment by wubzz** [comment]
To kick of a discussion here again:

I agree something like this is useful to prevent endless chaining, but I really do not like the syntax. Not to mention this would inevitably collide with the existing support of arrays in (amongst others?) postgres.

I would say make a new class `Operators` with functions that when called would generate an instance of Raw for the specified parameter. `Operators` would then be exposed onto Knex just like `Raw` So for example:

```javascript
Player.where({ team: 'foo', score_record: knex.operators.greaterThan(500)] }).fetchAll();
```

```javascript
greaterThan: function(value) {
     return raw('>= ?', value);
}
```

This way you:
- Don't have to work with strings
- No collision with existing arrays support

**Comment by rhys-vdw** [comment]
> this would inevitably collide with the existing support of arrays

Not necessarily. At least not as of the current version of PostgreSQL, which does not support array equality.

You cannot, for instance, do:

```sql
select * from records where some_array_column = '{0, 1, 2}';
-- error because `=` is not defined for array types
```

> I would say make a new class `Operators`

This is a neat idea. But we should think about use cases for these objects. One disadvantage of using this approach over the proposed array syntax is lack of JSON support. If we allow all operations with JSON supported types then it is possible to pass the object as query parameters:

```js
router.get('/records', (req, res) => {
  knex('records')
    .where(req.params.where || {})
    .then(records => req.json(records));
});
```

**Comment by elhigu** [comment]
I don't like this anymore, closing :)
