### ISSUE TITLE
Wrap index names

### ISSUE THREAD

**Issue by elhigu** [tgriesser/knex#1283]
maxcnunes commented on Jul 16, 2015
The current implementation I have been using at work for multi tenants is based in different tables for each client (tenant). To distinguish each table for each client we use the client id (number) as prefix name. For example I have these tables for client 1 (1_authorization, 1_user) and these tables for client 2 (2_authorization, 2_user).

Due that I have tables starting with number values. And this pull request fixes the problem of executing queries with index names starting with number values. Since I have been working only with Mysql and Postgres I have applied the changes only in those databases types.

There is almost ready pull request for this in https://github.com/tgriesser/knex/pull/899

**Comment by maxcnunes** [comment]
Hi @elhigu,

I guess you can close this issue already. Since that pull request has already been merged into master.

**Comment by rhys-vdw** [comment]
Closed by #1289. Thanks @maxcnunes.
