### ISSUE TITLE
Update dependencies for latest stable versions

### ISSUE THREAD

**Issue by nkrass** [tgriesser/knex#1285]
Dear sirs,
While knex is moving towards the stable version of 1.0 it may be helpful to consider updating the underlying list of dependencies to the their respective latest stable version alongside recent updating to lodash 4.6.1:
1. bluebird : ">=3.3.4"   -> the change needed is about the Promisify with the 2nd argument being obj.
2. pool2 : ">=1.3.2",
3. interpret :  ">=1.0.0",
4. liftoff  : ">=2.2.0",
5. minimist :">=1.2.0",
6. readable-stream :">=2.0.6",
7. tildify :">=1.1.2"

**Comment by wubzz** [comment]
Closing as current dependeicies either match or have passed the above list.
