### ISSUE TITLE
.toSQL() does not position bindings correctly

### ISSUE THREAD

**Issue by 790** [tgriesser/knex#1286]
Version 0.10.0

`> var knex = require('knex')({client:'pg'});`
`> knex.select().from('foo').where('bar', '=', '123').toSQL()`
`{ method: 'select',
  options: {},
  bindings: [ '123' ],
  sql: 'select * from "foo" where "bar" = ?' }`

I would expect the result when using postgres dialect to be `select * from "foo" where "bar" = $1`
knex seems to only perform the binding positioning when it's actually running the queries itself rather than just generating them.

I'd can submit a PR to fix this for pg, assuming it's not intentional, but I'm not familiar with other dialects  and it probably affects them also.

**Comment by wubzz** [comment]
@elhigu Sounds like the same issue as `prepBindings` in #1269 . Maybe we should move `positionBindings` calls to `toSQL()` as well.

[Reference](https://github.com/tgriesser/knex/blob/master/src/dialects/postgres/index.js#L145)

**Comment by elhigu** [comment]
@wubzz I'm not sure if this is an issue... knex has always worked that way that position bindings are replaced just before sending the query. If that is going to be changed the consequences must be investigated throughly...

**Comment by 790** [comment]
If it's always worked that way then I'd posit that it's always been broken. A toSQL() method that returns SQL that you can't actually run (at least in postgres) certainly seems broken.

The docs mention that "you can even use knex without a connection, just for its query building features", which is how I'm using it. If this is a supported way of using it then presumably it should produce valid queries whether having a connection or not.

I wouldn't be averse to a new method if compatibility with existing uses of toSQL() is a problem, but I can't see many cases where fixing it would cause a problem. The tests might fail, but they would have been wrong in the first place.

**Comment by elhigu** [comment]
@790 If you like to form query which has all bindings replaced / escaped correctly etc. you can already call `.toQuery()` which returns SQL string where bindings are replaced with values. 

I understand that e.g. if you use `pg` driver you might like to have bindings and postgres compatible SQL separately in hand and I'm not saying that it would be bad thing at all if `.toSQL()` would already give you client specific SQL with in clients SQL binding format... it makes sense.

That being said it is so fundamental change to earlier functionality of `knex` that I don't feel being correct person to make that big decision by myself. 

Probably @tgriesser is the only one who could approve this.

**Comment by 790** [comment]
@elhigu Yeah, I have been using toString/toQuery but ideally I want the proper paramaterized queries to pass to pg.

I'm not sure it has to be a big fundamental change, I've fixed it in my local copy by simply adding a `.toSQL()` method onto the postgres dialect's QueryCompiler that calls the main `.toSQL()` function and passes the result through positionBindings before returning. I'm not familiar enough with the codebase to say if this is the correct/optimal way of doing it, but if pg is the only dialect affected by it, it could be worth implementing. I'd have thought anyone using the pg dialect has avoided using toSQL due to it being broken, or, they are doing the replacement themselves in which case I wouldn't expect functionality to change as the things they're trying to replace (the question marks) have already been replaced.

If several dialects are affected by this then it may be better to rethink how it works fundamentally rather than patching each dialect individually.

**Comment by elhigu** [comment]
The implementation shouldn't be a problem.

Change is fundamental in that sense that `toSQL()` is part of public API and all the people who has been using that part of `knex` with current functionality will need to fix their code / tests all over the world. This hasn't been bug or undefined behavior. It has been made that way by design (no idea why, so we'll need to wait Tim's input). 

To maintain backwards compatibility it could be implemented with an extra parameter or just by adding `.toDialectSQL()` or something like that as you suggested...

**Comment by nkrass** [comment]
+1 @elhigu it would be great if we introduce something like `.toDialectSQL()` and not change current `.toSQL()`. Currently if you are using `.toQuery() or .toString()` it looks like SQL injection is possible so we can't use it directly. Would be great to see this feature coming next release.

**Comment by elhigu** [comment]
@nkrass how `.toQuery` allows sql injection? It should escape everything properly to values or to identifiers. If it doesn't it is a bug. Would be good to write some tests for sql injection attacks and make sure they won't work.

**Comment by nkrass** [comment]
@elhigu as far as I saw `.toQuery` is similar with `.toString`. The problem with `.toQuery` is that it is not in the official documentation so we need to use `.toString`.

**Comment by rhys-vdw** [comment]
> The docs mention that "you can even use knex without a connection, just for its query building features", which is how I'm using it. If this is a supported way of using it then presumably it should produce valid queries whether having a connection or not.

I would have to agree. `toSQL` should be as usable as possible. Currently this is an obvious application that is unsupported, but advertise as such.

> To maintain backwards compatibility it could be implemented with an extra parameter or just by adding .toDialectSQL() or something like that as you suggested...

`toSQL()` already performs some dialect specific operations, so I think adding a function called `toDialectSQL` would be confusing.

> Change is fundamental in that sense that toSQL() is part of public API and all the people who has been using that part of knex with current functionality will need to fix their code / tests all over the world.

I've always done my unit testing using `toString()`, but I assume this has potential to break test frameworks. I think we might be able to mitigate this by offering a configuration option such as `legacyToSQLBindings` (defaulting to `false`).

It's not pretty, but if the "breaking change" here is just a matter of requiring different strings in your test assertions, it should only be required by a few projects, and only in the test config.

**Comment by elhigu** [comment]
@rhys-vdw That would be fine for me. The configuration option could even have deprecation warning already so that it can be removed at some point in future. Would be just helper to migrate for people fast and fix that later...

I'm not even sure if it is worth it to add backwards compatibility option since people can just delay updating to next version of 'knex' until they have fixed their stuff properly. As you said, there shouldn't be many people using this.

Though I still would like to know if there was a specific reason why `.toSQL` is implemented the current way.

**Comment by elhigu** [comment]
Closing this on favor of newer issue https://github.com/tgriesser/knex/issues/1286
