### ISSUE TITLE
Sqlite read-only mode?

### ISSUE THREAD

**Issue by npow** [tgriesser/knex#1287]
Is there a way to open an sqlite database in read-only mode using knex? Using `node-sqlite3` I can do:
`new sqlite3.Database('tmp/test_readonly.db', sqlite3.OPEN_READONLY, function (err) ...`

**Comment by ducaale** [comment]
You can use File uri like `file:/pathto/mydb?mode=ro`

**Comment by elhigu** [comment]
Thanks ducaale
