### ISSUE TITLE
Adding like clause conditionally

### ISSUE THREAD

**Issue by nareshbhatia** [tgriesser/knex#1295]
I have been using the following pattern to conditionally add where clauses to my select statements:

    if (companyId) {
        whereClause['company.id'] = companyId;
    }
    if (searchtext) {
        whereClause['p.first_name'] = searchtext;
    }

    return knex
        .select(...)
        .from('people as p')
        .leftOuterJoin( 'companies as company', 'company.pk', 'p.company_pk' )
        .where( whereClause );

Now I need to change the `searchtext` conditional above from equality to `like`. Any clues on how I can achieve that?

**Comment by wubzz** [comment]
Don't think there's any way to do a LIKE using the object syntax, someone please correct me if I'm wrong. You could however assign the `queryBuilder` as a variable and do conditional statements from that instead.

```javascript
var queryBuilder = knex.select(...).from(..).leftOuterJoin(..);

if(companyId) {
     queryBuilder.where('company.id', companyId);
}

if(searchtext) {
     queryBuilder.where('p.firstname', 'LIKE', searchtext);
}

return queryBuilder;
```

Alternatively you could use the function argument in `.where`. _(Note that this wraps the where clause)_

```javascript
queryBuilder.where(function() {
if(companyId) {
     this.where('company.id', companyId);
}
if(searchtext) {
     this.where('p.first_name', 'LIKE', searchtext);
}
});
```

**Comment by nareshbhatia** [comment]
Works like a charm! Thanks @wubzz.

I do have a followup question. I wanted to extend the like clause to match first_name **OR** last_name. So I modified the code as follows:

    var queryBuilder = knex.select(...).from(..).leftOuterJoin(..);

    if(companyId) {
         queryBuilder.where('company.id', companyId);
    }

    if(searchtext) {
         queryBuilder
            .where('p.first_name', 'ilike', searchtext + '%')
            .orWhere('p.last_name', 'ilike', searchtext + '%');
    }

Obviously I would like to force the precedence of the OR operator to be higher than that of the AND operator. Is there a way to introduce parenthesis in the generated expression? Currently Knex is generating no parenthesis, so the AND is taking precedence over OR.

**Comment by wubzz** [comment]
@nareshbhatia Yes, everytime you use a function argument to the any "where clause" function in the API, it will wrap the statement. So something like this I guess should work

```javascript
if(searchtext) {
     queryBuilder.where(function() {
          this.where('p.first_name', 'ilike', searchtext + '%')
               .orWhere('p.last_name', 'ilike', searchtext + '%');
     });
}
```

Should generate something like this. (I used some random params)

```sql
select * from "tableName" left outer join "companies" as "company" on "company"."pk" = "p"."company_pk" where "company"."id" = '1' and ("p"."first_name" ilike 'test%' or "p"."last_name" ilike 'test%')
```

**Comment by nareshbhatia** [comment]
Awesome! That works. Thanks @wubzz for all your help.

**Comment by novito** [comment]
@wubzz something I'm seeing when doing the function approach is that if the query is not modified, the query gets an extra `and (1=0)`. Is that expected, and any way to avoid it?

**Comment by wubzz** [comment]
@novito Do you have example code?

**Comment by novito** [comment]
@wubzz my bad. I jumped into that conclussion too quickly. However, I can confirm that if you have something like:

```
const query = knex.from('users').wherein('value', [])
```

It will do the ```1=0```. I'm not sure if that's expected or it should allow to do `IN ()`

**Comment by wubzz** [comment]
@novito Yes, that is intentional. Calling `whereIn` with an empty array will result in an empty resultset from the query. Using `IN ()` generates invalid sql syntax.

When `.whereIn` is called it is assumed the intent is to use it for filtering as part of the where clause. Thus, when omitted or set as empty, the resultset is also empty.

**Comment by novito** [comment]
@wubzz fantastic, that makes sense. Congrats on this library, I'm enjoying it a lot. Something that out of context on this thread, but worth mentioning now that I'm talking to you: It would be useful to add documentation on `andWhere` here http://knexjs.org/#Builder-where and perhaps a section on how conditionally chain queries.
