### ISSUE TITLE
mssql dialect tablecompiler.js Create Table logic incorrect

### ISSUE THREAD

**Issue by MEggersZA** [tgriesser/knex#1297]
mssql dialect tablecompiler.js logic tries to Create Table If It Exists (Should be not exists)
Line 24 generates if object_id(\'[knex_migrations]\', \'U\') is not null CREATE TABLE
This should be 'is null'

**Comment by nickwhiteley** [comment]
I came across this too.  It's currently line 23 (rather than 24 as mentioned above, which is as it is on NPM) in the master branch on Github.

**Comment by wolfgang42** [comment]
This is fixed by #1362.
