### ISSUE TITLE
DateTimes in MySQL

### ISSUE THREAD

**Issue by toiye** [tgriesser/knex#1298]
Is there any way to set a MySQL datetime column as datetime(3) or datetime(6), or better yet set a default for all datetime columns including .timestamps?  Right now it looks like I'm getting the milliseconds truncated when I insert into the DB and then retrieve.  

Thanks.

**Comment by timruffles** [comment]
Hi Toiye - thanks for using Knex!

For questions that aren't issues, rather queries about how to use Knex, it'd be great if you could ask them over at [StackOverflow](http://stackoverflow.com/search?q=knex). That way the maintainers have more time to fix issues :)
