### ISSUE TITLE
Converting multiple rows into an array for a many to many query

### ISSUE THREAD

**Issue by Kannaj** [tgriesser/knex#1300]
Hello,

querying a many to many table given an id pulls up multiple rows for the id. Would it be possible to convert the multiple rows into an array?

In short knex returns the following output for a query. Assuming two tables with a many to many relation
1. A post table
2. A tag table with an m2m relation with Post

`{
    post_id: 1,
    tag_id: 1
},
{post_id: 1,
tag_id: 2
} 
`

Is there something i could do to get an output like this?

`{
post_id:1,
tag_id:[1,2]
}`

**Comment by rhys-vdw** [comment]
If you're using PostgreSQL, you can do the following:

```sql
select post_id, array_agg(tag_id) as tag_ids from post_tags;
```

```js
knex('post_tags').select('post_id', knex.raw('array_agg(tag_id) as tag_ids'))
```

**Comment by bschwind** [comment]
My solution to this was to use [treeize](https://www.npmjs.com/package/treeize)

If anyone has a better/alternate solution, I'd love to hear how you do it!

**Comment by vforvalerio87** [comment]
I'm using GROUP_CONCAT (...) AS ... for each of the arrays I want (example: postIds, postNames, postBodies for each author), then I'm going through one of the arrays and creating a new array of objects where each property's value for that object is the value at each array's index.

See this repo for an example:
https://github.com/vforvalerio87/hypermedia
