### ISSUE TITLE
Knex returning ECONNRESET on uploading a large fil

### ISSUE THREAD

**Issue by Hectorhammett** [tgriesser/knex#1304]
Hi guys, i made this question a few days ago, and it was working pretty good:
#1259 
But, i had an oversight:
My app is now in a beta phase, but the day that we went on testing, i found the first oversight:
Knex it's returning me a "Econnreset" on large files.

I already described what i did on the reference but i'm gonna put it in here anyways:
I have an upload section on my app, which connects to a centrilized MYSQL database, so when i'm gonna upload the file, i transform it into a Base64 encoded file:

```
  Fs.readFile(path, function(err, buffer) {
        if (err) {
          console.error(err);
          return;
        }
        Knex('pdf').insert({
            string: buffer.toString("base64"),
            fileType: "pdf",
            idManifiesto: idManifest
          })
       ...
```

It works, but if i try to upload a large file, it gives me a Econnreset. (It failed with a 2.5 mb file). Any ideas on what to do? I think it has to do with Pool2, and i changed the min and max values with no success. Any ideas? Thanks guys!

**Comment by elhigu** [comment]
Is your mysql server on the same machine with the node.js code? Also stacktrace would be nice... check all the timeouts from your DB. 

Even better if you can give testcase of failing code it would help. e.g. one liner which generates long base64 string and tries to upload it mysql test table and which allows us to check out what is really happening.

**Comment by Hectorhammett** [comment]
Yes, i have a NWJS app (Node Js - node webkit) and a mysql sever (Xampp) installed for development purposes. 

I changed the my.ini for this:
```
max_allowed_packet = 5M
```

And now it's giving me this error:
![image](https://cloud.githubusercontent.com/assets/9062626/13944472/d1d797de-efc2-11e5-8f14-0ee0ec7c6c44.png)

Does it  help?

**Comment by Hectorhammett** [comment]
Also:
"Error: ER_TOO_BIG_ROWSIZE: The size of BLOB/TEXT data inserted in one transaction is greater than 10% of redo log size. Increase the redo log size using innodb_log_file_size. at Query.Sequence._packetToError (C:\xampp\htdocs\Residuos\node_modules\mysql\lib\protocol\sequences\Sequence.js:48:14) at Query.ErrorPacket (C:\xampp\htdocs\Residuos\node_modules\mysql\lib\protocol\sequences\Query.js:83:18) at Protocol._parsePacket (C:\xampp\htdocs\Residuos\node_modules\mysql\lib\protocol\Protocol.js:280:23) at Parser.write (C:\xampp\htdocs\Residuos\node_modules\mysql\lib\protocol\Parser.js:73:12) at Protocol.write (C:\xampp\htdocs\Residuos\node_modules\mysql\lib\protocol\Protocol.js:39:16) at Socket.<anonymous> (C:\xampp\htdocs\Residuos\node_modules\mysql\lib\Connection.js:96:28) at emitOne (events.js:90:13) at Socket.emit (events.js:182:7) at readableAddChunk (_stream_readable.js:153:18) at Socket.Readable.push (_stream_readable.js:111:10) at TCP.onread (net.js:529:20) -------------------- at Protocol._enqueue (C:\xampp\htdocs\Residuos\node_modules\mysql\lib\protocol\Protocol.js:141:48) at Connection.query (C:\xampp\htdocs\Residuos\node_modules\mysql\lib\Connection.js:201:25) at C:\xampp\htdocs\Residuos\node_modules\knex\lib\dialects\mysql\index.js:92:18 at tryCatcher (C:\xampp\htdocs\Residuos\node_modules\bluebird\js\main\util.js:26:23) at Promise._resolveFromResolver (C:\xampp\htdocs\Residuos\node_modules\bluebird\js\main\promise.js:480:31) at new Promise (C:\xampp\htdocs\Residuos\node_modules\bluebird\js\main\promise.js:70:37) at Client._query (C:\xampp\htdocs\Residuos\node_modules\knex\lib\dialects\mysql\index.js:88:12) at Client.query (C:\xampp\htdocs\Residuos\node_modules\knex\lib\client.js:127:24) at Runner.<anonymous> (C:\xampp\htdocs\Residuos\node_modules\knex\lib\runner.js:116:24) at Runner.tryCatcher (C:\xampp\htdocs\Residuos\node_modules\bluebird\js\main\util.js:26:23) at Runner.query (C:\xampp\htdocs\Residuos\node_modules\bluebird\js\main\method.js:15:34) at C:\xampp\htdocs\Residuos\node_modules\knex\lib\runner.js:44:21 at C:\xampp\htdocs\Residuos\node_modules\bluebird\js\main\using.js:176:30 at tryCatcher (C:\xampp\htdocs\Residuos\node_modules\bluebird\js\main\util.js:26:23) at Promise._settlePromiseFromHandler (C:\xampp\htdocs\Residuos\node_modules\bluebird\js\main\promise.js:507:31) at Promise._settlePromiseAt (C:\xampp\htdocs\Residuos\node_modules\bluebird\js\main\promise.js:581:18) at Promise._settlePromises (C:\xampp\htdocs\Residuos\node_modules\bluebird\js\main\promise.js:697:14) at Async._drainQueue (C:\xampp\htdocs\Residuos\node_modules\bluebird\js\main\async.js:123:16) at Async._drainQueues (C:\xampp\htdocs\Residuos\node_modules\bluebird\js\main\async.js:133:10) at Async.drainQueues [as _onTimeout] (C:\xampp\htdocs\Residuos\node_modules\bluebird\js\main\async.js:15:14) at Timer.listOnTimeout (timers.js:92:15)"

**Comment by Hectorhammett** [comment]
YES! Found the error. Was a missconfiguration on the MYSQL side, not Knex! Thank you for your help man!

**Comment by Hectorhammett** [comment]
Solution:
Changed the configuration on the my.ini:
`innodb_log_file_size = 32M`
