### ISSUE TITLE
put query in error

### ISSUE THREAD

**Issue by snowcxt** [tgriesser/knex#1305]
I'd like to get the query string from the error for debugging. e.g.:

``` javascript
knex.select('name').from('users')
  .where('id', '>', 20)
  .asCallback(function(err, rows) {
    if (err) console.log(err.query);
  });
```

If something wrong, you will see it

```
select "name" from "users" where "id" > 20
```

**Comment by wubzz** [comment]
@snowcxt Is the `query-error` event not enough here if this is solely for debugging purposes?

Or are you saying you want production code where you can access the SQL via the error object?

**Comment by snowcxt** [comment]
Looks like `query-error` is not exactly what I want. I misspell a column name in the query. I get an "errorMissingColumn" error. But it doesn't trigger the `query-error` event.

**Comment by wubzz** [comment]
Yep you're absolutely right. Looks like the events are not being triggered on the builder, only on the client.. I'll fix this.

**Comment by snowcxt** [comment]
Thank you. Could you just add the query string into the error as well. That will make my live much easier.
