### ISSUE TITLE
Having problems with a subquery

### ISSUE THREAD

**Issue by Surreal9** [tgriesser/knex#1312]
Any ideas how I could generate this SQL with knex?

```
select companies.guid,
    (select max(creation_date) from messages
        where company_guid = companies.guid)
from companies
```

so far I've come up with 

```
knex('companies').select('companies.guid', function(){
    this.table('messages').where('company_guid', 'companies.guid')
    .max('creation_date').as('latest_message')
}).toString()
```

which resuts in this SQL:

```
select "companies"."guid",
    (select max("creation_date") from "messages"
        where "company_guid" = 'companies.guid') as "latest_message"
from "companies"
```

which seems close, but this fails for some reason complaining about the quotes.. if I remove enough of them until I get to this:

```
select companies.guid,
    (select max("creation_date") from messages
        where company_guid = companies.guid) as "latest_message"
from companies
```

then it works. Any suggestions on what I could be doing wrong here?

**Comment by Surreal9** [comment]
Perhaps toString is just using double quotes whereas internally it would use backticks, which would work for these quoted identifiers (such as table names)

**Comment by Surreal9** [comment]
Ah, found the section of the docs that suggests using raw for identifiers which need periods, or in this case whereRaw was the answer.

**Comment by wubzz** [comment]
I would recommend
```javascript
.where('company_guid', knex.raw('??', 'companies.guid'))
```
instead of
```javascript
.whereRaw('company_guid = ??', 'companies.guid');
```

Since `.whereRaw` would generate `company_guid = "companies"."guid"` rather than `"company_guid" = "companies"."guid"`. May not matter in this case, but if the column was mixed-case, it would matter.

**Comment by Surreal9** [comment]
Thanks for your response! I ended up with `.whereRaw('company_guid = companies.guid')` which seems to work ok.
