### ISSUE TITLE
Can connect via psql but not via knex

### ISSUE THREAD

**Issue by adnelson** [tgriesser/knex#1314]
I have a database `test` that I've created locally. I can connect to this database via the `psql` command-line utility without problems:

```bash
$ createdb test
$ psql test
psql (9.4.6)
Type "help" for help.

test=> \q
```

However, I'm not able to connect to this same database via knex:

```
$ node
> require('knex')({client:'pg', debug: true, pool: {max: 1, min: 1},  connection: {host: 'localhost', database: 'test'}})
Knex:Error Pool2 - error: Ident authentication failed for user "<my username>"
```

Searching around for errors similar to this has yielded no results. I don't have any postgres-specific environment variables set that might be overriding the password. In addition, explicitly passing in `password: '', user: ''` to the `connection` object has no effect. No matter what I do, I'm getting authentication errors. What could be happening here?

**Comment by elhigu** [comment]
@adnelson With `psql` you are using unix socket to connect DB and with `knex` you are trying to use TCP connection... 

You should encounter the same problem if you try to connect the same way to your DB with `psql -U <myusername> -d test -h localhost`

Searching with error message http://lmgtfy.com/?q=Ident+authentication+failed+for+user 
And click the first stackoverflow link: http://stackoverflow.com/questions/2942485/psql-fatal-ident-authentication-failed-for-user-postgres

This might also be helpful to get your postgres setup to allow remote connections http://www.cyberciti.biz/tips/postgres-allow-remote-access-tcp-connection.html

Let me know if there are more problems with this.
