### ISSUE TITLE
.returning() not working

### ISSUE THREAD

**Issue by peteallen** [tgriesser/knex#1317]
I'm using the following code to try to create a `user` record and an associated `post` record. The database is postgresql 9.4. Both tables have a column called `id` of type `serial`.

```
return knex.insert({
    firstName: 'Bob',
    lastName: 'Jones'
  })
  .returning('id')
  .into('user')
  .then(function (response) {
    return knex.insert({
      title: 'Test post',
      text: 'This is a test post',
      user_id: response[0]
    })
    .into('post')
  })
  .then(function () {
     console.log('Success');
  });
```

When it reaches the second insert operation, `response` is undefined. What am I doing wrong?

**Comment by rhys-vdw** [comment]
Does this fail if you use `knex('user')` instead of `into`?

**Comment by peteallen** [comment]
Yes, I get the same result with this code:

```
return knex('user').insert({
    firstName: 'Bob',
    lastName: 'Jones'
  })
  .returning('id')
  .then(function (response) {
    return knex('post').insert({
      title: 'Test post',
      text: 'This is a test post',
      user_id: response[0]
    });
  })
  .then(function () {
     console.log('Success');
  });
```

**Comment by peteallen** [comment]
I have also verified that the following query works and correctly returns the row id:

`INSERT INTO "user" VALUES ('Bob', 'Jones') RETURNING "id";`

**Comment by elhigu** [comment]
@peteallen That first knex query generates 

```sql
insert into "user" ("firstName", "lastName") values ('Bob', 'Jones') returning "id"
```

It seems to be correct, try to add `console.log(require('util').inspect(response, {depth: null}))` to inside first then and run the query again. Could it be that `response[0]` is `undefined`, but `response` not?

**Comment by peteallen** [comment]
Hi @elhigu,

Thanks for the suggestion. I tried it, but it just logs `[ undefined ]` to the console.

**Comment by peteallen** [comment]
I also turned on the debug log and verified that it's construction the query correctly:

`insert into "user" ("firstName", "lastName") values ('Bob', 'Jones') returning "id"`

**Comment by wubzz** [comment]
Could you drop your table structure in here so we're 100% testing the same things? Alternatively put a breakpoint  [here](https://github.com/tgriesser/knex/blob/master/src/dialects/postgres/index.js#L174) and see what `row` is in that context.

From your `console.log` it looks like [this](https://github.com/tgriesser/knex/blob/master/src/dialects/postgres/index.js#L174) code got rows returned, but can't find `id` on the rows. This conclusion comes from your log being an Array(1) with index 0 being explicitly undefined. *("row" not having "id", `row[returning]`)*. Unsure why this is or how it could ever occur.

**Comment by peteallen** [comment]
I believe it was a problem with the schema. I've since made some schema changes and upon returning to this issue, the problem is no longer occurring. I wish I knew what the cause was, but it was something on my end. Thanks for your help and sorry for the trouble.

**Comment by nitinsharmacs** [comment]
Can someone tell me how to make returning() working with mysql

**Comment by elhigu** [comment]
> Can someone tell me how to make returning() working with mysql ?

For example by changing your database to postgresql, mssql or to oracle or by implementing support for returning statements to mysql db engine.
