### ISSUE TITLE
Set custom template for knex migrate:make

### ISSUE THREAD

**Issue by Charrondev** [tgriesser/knex#1319]
I don't if I just missed it, but it would be nice to be able to specify migration templates for use with the command `knex migrate:make`.

**Comment by jc21** [comment]
I was going to fork and implement this, but I see in the code it's already implemented, just no documented.

You can set your template file by using this config in your knexfile.js:

```javascript
module.exports = {
    development: {
        migrations: {
            tableName: 'migrations',
            stub: 'migrations/template.js'
        }
    }
}
```

where `stub` is the absolute or relative path to your migration template.

**Comment by rhys-vdw** [comment]
Good one @jc21. Would you be interested in opening a PR to add this feature to the docs?

**Comment by mdrmuhaimin** [comment]
If not I don't mind sending a PR. I can also include my learnings from here #1333

**Comment by jc21** [comment]
Sure if you're putting your hand up @mdrmuhaimin :)
