### ISSUE TITLE
`createTable` of in-memory sqlite3 doesn't create tables

### ISSUE THREAD

**Issue by ilyaigpetrov** [tgriesser/knex#1320]
I want to use in-memory sqlite3 for testing.
For DB initialization I call `knex.migrate.latest()` which applies the only migration correctly according to logs.
But running tests throws _'table doesn't exist'_ error unless I switch to newly created _'test.sqlite3'_.
I think it's a bug.

Config:
```javascript
{
    client: 'sqlite3',
    connection: {
      filename: ':memory:' // __dirname + '/../test.sqlite3'
    },
    migrations: {
      directory: __dirname + '/../migrations'
    },
    useNullAsDefault: true
}
```
The only migration:
```javascript
exports.up = function(knex, Promise) {
  return knex.schema.createTable('users', function(table) {
    console.log('CREATE TABLE'); // Always called.
    table.increments('uid').primary();
    table.string('username').unique();
    table.string('email').notNullable();
    table.string('hash').notNullable();
    table.string('role').defaultTo('President of Georgia');
    table.timestamps();
  })
};
...
```

## Update

Also `knex.destroy( () =>  require('fs').unlinkSync('path_to_test.sqlite3') )` throws _"Error: EBUSY: resource busy or locked, unlink..."_.

**Comment by elhigu** [comment]
Could you provide as simple complete code as possible to reproduce the problem? 

I believe that your migrations and rest of the code are run in different connection/configuration or something like that which causes the behavior...

**Comment by ilyaigpetrov** [comment]
@elhigu, you were right, I was creating two connections.
Minimal test case took only a few lines of code -- overconfident me should have written it from the beginning.
Fixing myself, thank you.
