### ISSUE TITLE
No rows return

### ISSUE THREAD

**Issue by fsebbah** [tgriesser/knex#1321]
I know it is a basic question but I don't found the solution.
I have a simple query

```js
knex
.select('name')
.from('users')
.where(id,1)
.then(function(rows){
})
.catch(function(err){})
.finally(function(){
knex.destroy
})
```

It 's a sample. But If there is no row How can I handle the event ?
I know It's a basic question and any help is good for me.
Thanks,
Franck

**Comment by rhys-vdw** [comment]
Hi @fsebbah - I can't teach you JavaScript.

```js
knex
  .select('name')
  .from('users')
  .where('id',1) // pass a string as the first argument
  .debug() // include this line to log out the generated query
  .then(function(rows) {
    console.log('this is the result:', rows)
  })
  .catch(function(error) {
    console.error('this is what went wrong:', error)
  })
  .finally(function() {
    knex.destroy(); // use parentheses to invoke function
  });
```

See the [FAQ](http://knexjs.org/#faq) section on debugging. In the meantime you'd do better asking questions like these on StackOverflow.
