### ISSUE TITLE
Creating an insert with nested select

### ISSUE THREAD

**Issue by nareshbhatia** [tgriesser/knex#1323]
I have the following JavaScript object:

```
var person = {
    username: 'jdoe',
    first_name: 'John',
    last_name: 'Doe',
    title: null,
    company_name: 'Apple'
};
```

Using this object, I want the generate the following insert statement:

```
INSERT INTO people
(username, first_name, last_name, title, company_id)
SELECT 'jdoe', 'John', 'Doe', null, company.id
FROM companies as company
WHERE company.name = $1
RETURNING id;
```

It is not clear how I can generate the column names in line 2 above. Also handling of the string values `'jdoe'` etc. seems to be very awkward. I had to use `knex.raw()` to handle special characters (like '@') in strings. Here's my best attempt:

```
var selectStatement = knex.select(
    knex.raw("'" + person.username + "'"),
    knex.raw("'" + person.first_name + "'"),
    knex.raw("'" + person.last_name + "'"),
    knex.raw("'" + person.title + "'"),
    'company.id'
)
.from('companies as company')
.where('company.name', person.company_name);

return knex('people')
    .returning('id')
    .insert(selectStatement)
    .then(function(id) {
        return id;
    });
```

This produces:

```
insert into "people"
select 'jdoe', 'John', 'Doe', 'null', "company"."id"
from "companies" as "company"
where "company"."name" = $1
returning "id"
```

Note the absence of column names in the insert statement and also the quoted `null` in the select. Is there a better way?

**Comment by rhys-vdw** [comment]
Yep, I could imagine a nicer API, but this is the best way I'm aware of:

```js
var selectStatement = knex.select(
  knex.raw('?, ?, ?, ?', [
    person.username,
    person.first_name,
    person.last_name,
    person.title
  ]),
  'company_id'
)
.from('companies as company')
.where('company.name', person.company_name);
```

yields:

```sql
"insert into "people" select 'jdoe', 'John', 'Doe', NULL, "company_id" from "companies" as "company" where "company"."name" = 'Apple'"
```

You could write a helper function:

```js
// values.js
var _ = require('lodash'); // lodash 4.7

// Shorthand for supplying value literals to `knex.raw`
module.exports = function values() {
  return knex.raw(
    _.times(arguments.length, _.constant('?')).join(', '),
    _.toArray(arguments)
  );
}
```

```js
knex.select(
  values(person.username, person.first_name, person.last_name, person.title),
  'company_id'
)
```

**Comment by nareshbhatia** [comment]
Thanks. @rhys-vdw. That solves my problem partially. I am still not seeing the column names being generated (line 2 below):

```
INSERT INTO people
(username, first_name, last_name, title, company_id)
SELECT ...
```

Without that line the database wants all the table fields in the correct order. While I can supply the fields in the correct order, I cannot supply the very first field which is the id (primary key). The DB is expected to generate it automatically and return it.

**Comment by rhys-vdw** [comment]
Okay, yeah. Looks like this is not supported properly. Looks like `insert` will have to read the columns from the nested `select` statement to generate the `VALUES` clause.

**Comment by rhys-vdw** [comment]
This is possible [via `knex.raw`](https://github.com/tgriesser/knex/commit/e74f43cfe57ab27b02250948f8706d16c5d821b8#diff-cb48f4af7c014ca6a7a2008c9d280573R608) in the meantime.

**Comment by nareshbhatia** [comment]
Can you please show me how? How would I augment your earlier solution using `kenx.raw` to insert column names? Brute force is fine with me.

```
var selectStatement = knex.select(
  knex.raw('?, ?, ?, ?', [
    person.username,
    person.first_name,
    person.last_name,
    person.title
  ]),
  'company_id'
)
.from('companies as company')
.where('company.name', person.company_name);
```

**Comment by rhys-vdw** [comment]
Sorry, I'm not at the computer any more. Look at the test I linked. The
basic idea is just to build up the entire query in a raw passed to insert.
If you can't get it I'll try to take a look tomorrow.

**Comment by nareshbhatia** [comment]
Ah ok, didn't realize that that was a link. I will take it from here. Thanks for your help.

**Comment by rhys-vdw** [comment]
**This issue should remain open until the feature is implemented. `knex.raw` is a workaround.**

**Comment by chenweiyj** [comment]
Yes, I meet the same problem. I think the specified columns in insert should be able to point out.

**Comment by jhnferraris** [comment]
How did you guys address this?

**Comment by bestan** [comment]
Something like this has worked for me:

```javascript
const insertValueNamesRaw = '(column1, column2, column3)';
const insertValues = ['value1', 'value2', 'value3'];
const insertValuesWrapped = [...insertValues.map(value => knex.raw(`'${value}'`))];

const whereNotExistsQuery = knex.select(...insertValuesWrapped).whereNotExists(function () {
  this.select(1).from('table').where('column1', 'value1');
}).toSQL();
knex.table('table').insert(knex.raw(`${insertValueNamesRaw} ${whereNotExistsQuery.sql}`, whereNotExistsQuery.bindings)).toString();
```

Output:
```sql
insert into "table" (column1, column2, column3) select 'value1', 'value2', 'value3' where not exists (select 1 from "table" where "column1" = 'value1')
```

**Comment by elhigu** [comment]
Is this what @nareshbhatia tried to do?

```
knex('people').insert({
  username: 'jdoe',
  first_name: 'jdoe',
  last_name: 'jdoe',
  title: null,
  company_id: knex('companies').select('id').where('company_name', companyName)
});
```

https://runkit.com/embed/og0udjmyu11b

**Comment by elhigu** [comment]
I think this can be closed, implementing FROM for inserts and updates is a separate issues.

**Comment by jeff-kilbride** [comment]
Just for the sake of anyone stumbling on this in the future, like I did, I solved this by combining the suggestions here with some `knex.raw()` tricks from #1056.
```
selectStatement = knex.select(
  knex.raw('?, ?, ?, ?', [
    person.username,
    person.first_name,
    person.last_name,
    person.title
  ]),
  'company_id'
)
.from('companies as company')
.where('company.name', person.company_name);

knex(
  knex.raw(
    '?? (??, ??, ??, ??, ??)',
     ['people', 'username', 'first_name', 'last_name', 'title', 'company_id']
  )
)
.insert(selectStatement);
```
This yields:
```
insert into `people` (`username`, `first_name`, `last_name`, `title`, `company_id`)
select 'jdoe', 'John', 'Doe', null, `company`.`id`
from `companies` as `company`
WHERE `company`.`name` = 'Apple'
```
Caveat -- I didn't run this on the OP's select criteria. I used this in my own code and translated the results back to the OP's question. However, it should be correct. Using `knex.raw` is the easiest way I have found to setup the table and column names in the INSERT portion of the statement.

Hope this helps someone else!

**Comment by lilsweetcaligula** [comment]
@jeff-kilbride

Thank you! Your solution helped me find mine.

**Comment by TSiege** [comment]
If anyone else has stumbled here trying to do this with a `whereNotExists` clause here's an example I have working with my own code.
```js
knex(
  // insert values clause
  knex.raw('?? (??, ??, ??)', ['posts_authors', 'author_id', 'post_id', 'sort_order'])
).insert(
  // select where not exists clause
  knex.select(
    knex.raw('?, ?, ?', [author_id, post_id, sort_order])
  ).whereNotExists(
    knex('posts_authors').select('id').where({ author_id, post_id: id })
  )
)
```

**Comment by rhys-vdw** [comment]
@TSiege you should create a new issue for this.
