### ISSUE TITLE
Documentation on how to use pg date() type functions

### ISSUE THREAD

**Issue by kuanb** [tgriesser/knex#1325]
There seems to be little online (only found this: http://stackoverflow.com/questions/36013605/how-to-use-postgres-date-with-knex-js) asking, and little in the documentation explaining how one might utilize datetime functions in queries.

For example, say I want to pull only the "MM-DD-YYYY" from a datetime column and `GROUP BY` by it. How would I go about doing so?

**Comment by rhys-vdw** [comment]
Added an [answer](http://stackoverflow.com/a/36374328/317135). You can just write arbitrary SQL into `knex.raw`.
