### ISSUE TITLE
Right way of writing knex migration

### ISSUE THREAD

**Issue by mdrmuhaimin** [tgriesser/knex#1333]
I find out there is two way we can write knex migration in the migration file. 

    exports.up = function (knex) {
        return knex.schema
          .createTableIfNotExists('foo', function (table) {
            table.increments('id').unique();
            table.string('foo1');
            table.string('foo2');
          })
         .createTableIfNotExists('bar', function (table) {
            table.increments('bar1');
            table.string('bar2').index();
          });

Or 

    exports.up = function (knex) {
        return Promise.all([
          knex.schema.createTableIfNotExists('foo', function (table) {
            table.increments('id').unique();
            table.string('foo1');
            table.string('foo2');
          }),
          knex.schema.createTableIfNotExists('bar', function (table) {
            table.increments('bar1');
            table.string('bar2').index();
          })
        ]);
    }

Which one is the right way of doing it?

**Comment by ricardograca** [comment]
In that case it doesn't make a difference.

You would only use the Promise based one if you require some change in a table before doing another change in another table. For example, if you needed to reference a certain table from another table and none of those tables exist yet, you would create the first table (the one that doesn't depend on anything) in a promise and then when that promise resolved you would create the second table. That way you ensure that dependencies are met.
