### ISSUE TITLE
Implementation specific create/alter table extensions

### ISSUE THREAD

**Issue by raijinsetsu** [tgriesser/knex#1335]
I see no way to add extra RAW pieces to the end of the create/alter table statement, so I cannot add options like MySQL's "ROW_FORMAT=COMPRESSED" to enable row compression. I poked around in the code and could find no undocumented way to accomplish this using existing functionality of the table or schema builders.

I can get around this by using the builder's toString function, modifying the SQL, and then wrapping it in knex.raw, but that seems like a kludge.

I see three possible solutions:
1. extend the knex schema builder to allow RAW statements to be appended to the end of the CREATE/ALTER statements
2. extend the table builder to expose the implementation specific extensions (like was done for MySQL's ENGINE and COLLATION options)
3. both

I can code this and submit a PR, but I wanted to get input from the knex maintainers before doing so - I do not want to waste my efforts.

**Comment by wubzz** [comment]
Can't you just run a seperate `.raw` after the create/alter table?

```javascript
knex.schema.table('table', (table) => {
//Do stuff
})
.then(() => knex.raw('ALTER TABLE table ROW_FORMAT=compressed'))
```

Not very familiar with mysql but I think that should work. As for API support for this I feel that I lack understanding of this to make that call. But if implementation is imminent, then I would say go for option 2 over the others.

**Comment by raijinsetsu** [comment]
It didn't occur to me to run an alter on the table after the fact. That should work.
