### ISSUE TITLE
Connection hanging after .destroy()?

### ISSUE THREAD

**Issue by pilks** [tgriesser/knex#1338]
I just started playing around with Knex tonight and it seems like it is hanging when run in my Tape test.

I could be off on this one, but here is the relevant code:

```javascript
const test = require('tape');
const Chat = require('../database/chat');

const db_config = require('../../knexfile.js');
const db = require('knex')(db_config);

test('Chat can be saved to the database.', (t) => {

  const postedChat = {
    title: `test-chat-${randomInteger()}`
  };

  Chat.saveToDatabase(postedChat).then((rows) => {
    t.equal(rows.length, 1, "Only one Chat should have been created.");
    t.ok(Number.isInteger(rows[0].id), "Retrieved Chat should have a numerical id.");
    return rows[0].id;
  })
  .then(removeRowWithId)
  .then(db.destroy)
  .then(t.end);

});
```

**Comment by rhys-vdw** [comment]
You don't have an error handler in that promise chain. Is `t.end` being called?

**Comment by mikeerickson** [comment]
A

**Comment by tjwebb** [comment]
@mikeerickson ?

**Comment by pilks** [comment]
@rhys-vdw Yeah, I placed some logs in both knex's destroy and tape's t.end to make sure they're being called.  Here's a more explicit promise chain that is still hanging:

```javascript
Chat.saveToDatabase(postedChat).then((rows) => {
  t.equal(rows.length, 1, "Only one Chat should have been created.");
  t.ok(Number.isInteger(rows[0].id), "Retrieved Chat should have a numerical id.");
  return rows[0].id;
})
.then((id) => {
  return db('chats').where('id', id).del()
})
.then(() => {
  return db.destroy();
})
.then(() => {
  t.end();
});
```

**Comment by elhigu** [comment]
@pilks try to write minimal test case to reproduce the problem... problem doesn't seem to be in part of the code you have included here. If you can reproduce the problem with simpler code, you probably will find the problem too.

**Comment by pilks** [comment]
@elhigu Thanks for the response.  I just got some time to look at this a little closer.  I checked my pg db and multiple connections were being made.
