### ISSUE TITLE
Should I use trx.commit and trx.rollback within knex.transaction?

### ISSUE THREAD

**Issue by wsieroci** [tgriesser/knex#1346]
Hello,

According to documentation I should add trx.commit and trx.rollback to the end of chain of operations within transaction. Something like that:

```
knex.transaction(function(trx) {
        return knex('sometable')
        .transacting(trx)
        <someoperations>
        .then(trx.commit)
        .catch(trx.rollback);
})
```

But when I do that then it somehow works, but I get error like that:

> Fri, 15 Apr 2016 11:10:43 GMT knex:tx undefined: Transaction completed: COMMIT;
> Fri, 15 Apr 2016 11:24:32 GMT knex:tx trx3 error running transaction query

But when I do not put "trx.commit and trx.rollback" at the end of the chain then I do not get such errors, and transaction just works.

So what should I do?

**Comment by elhigu** [comment]
Hi @wsieroci if you return promise from transaction, then `trx.rollback` / `tx.commit` is called automatically, so no need to call them explicitly. 

If you look http://knexjs.org/#Transactions the first example returns promise and doesn't call them and the second one doesn't return promise and `commit / rollback` are called explicitly.

**Comment by wsieroci** [comment]
@elhigu I see! Thanks for answer!
