### ISSUE TITLE
Cassandra (CQL) Support?

### ISSUE THREAD

**Issue by AGhost-7** [tgriesser/knex#1347]
I was wondering, is there any possibility of adding support for Cassandra? I'd be willing to contribute.

**Comment by kibertoad** [comment]
New dialects will not be implemented within the scope of knex, they should be created as separate npm packages.

See https://github.com/tgriesser/knex/blob/master/CONTRIBUTING.md -> "I would like to add support for new dialect to knex, is it possible?"

If you implement a new dialect, though, please let us know, we'll link to it from our documentation.
