### ISSUE TITLE
Postgres json(b) insert problem

### ISSUE THREAD

**Issue by melkior** [tgriesser/knex#1349]
Hi,

can you please tell me what I'm doing wrong here:

    var query = Knex.insert('messages').insert({key: 12345, references: ["abc","def","ghi"],data: {a:1,b:2}}).toString();
    console.log('Query:'+query);

    # node k.js 
    Query:insert into  ("data", "key", "references") values ('{"a":1,"b":2}', '12345', '{"abc","def","ghi"}')

'references' is jsonb and it shouldn't be '{"abc","def","ghi"}' but '["abc","def","ghi"]'
Is this a bug or?

Also, looks like table name is missing, but when I look at packet sent (tcpdump), table name in query is 'messages' as expected, so it's ok. But 'references' column is still wrong.

**Comment by wubzz** [comment]
@melkior You wrote `.insert('messages')` instead of `.into('messages')` / `Knex('messages')` so there's no tablename set.

As for the "references" issue, it's explained vaguely in the documentation, although under the json column section. *(Not the best place to put this, I'd say)*

Basically it states that for json/jsonb columns you need to stringify your data first. So try the following:

```javascript
var query = knex('messages').insert({key: 12345, references: JSON.stringify(["abc","def","ghi"]),data: {a:1,b:2}}).toString();
console.log(query);
//insert into "messages" ("data", "key", "references") values ('{"a":1,"b":2}', '12345', '["abc","def","ghi"]')
```

**Comment by melkior** [comment]
Thanks on fast response ;-)

Found it. Here's quote from docs:

> Note that when setting an array (or a value that could be an array) as the value of a json or jsonb column, you should use JSON.stringify() to convert your value to a string prior to passing it to the query builder, e.g.

Problem solved, thank you

**Comment by craigcosmo** [comment]
knex use pg package, shouldn't knex automatically stringify ?

![CleanShot 2024-05-24 at 16 11 53](https://github.com/knex/knex/assets/538657/9379d56b-1a8f-4794-8333-68b106dc6af8)
