### ISSUE TITLE
Query Builder MERGE aka UPSERT

### ISSUE THREAD

**Issue by willfarrell** [tgriesser/knex#1351]
The ability to uniformly apply and UPSERT to multiple languages.

Great summary of the different SQL implementations: https://en.wikipedia.org/wiki/Merge_(SQL)

Possible Syntax: `knex().insert({...}).upsert([keys]).update({...})`

**Comment by rhys-vdw** [comment]
I'd like to see a discussion of the API, but `upsert` support would be great.

**Comment by rhys-vdw** [comment]
Duplicate of #54
