### ISSUE TITLE
What is the correct way to return a single value from select query?

### ISSUE THREAD

**Issue by Arch-Mage** [tgriesser/knex#1355]
The simple way to do select query in knex is like this:

```javascript
db('table_name').where({ id: 1 }).select();
```

But, it return an array. Since `id` is a unique field, it's clear that I
expect a single result. And then, I have to do something like this:

```javascript
db('table_name').where({ id: 1 }).select().then(result => result[0]);
```

Is there any _official_ way to return a single value?

**Comment by wubzz** [comment]
`db('table_name').where({id: 1}).first().then((row) => row)`

Should work

**Comment by Arch-Mage** [comment]
Oh, it's actually `first`  and I keep looking for `one`, `selectOne`, etc. Thanks

**Comment by haroonKhan-10p** [comment]
db('table_name').where({id: 1}).first(); this would work the same. no?

**Comment by iki** [comment]
@arch-mage If there should be only single matching result, then it's a best practice to ensure it, common `single` implementations do it using `limit 2`. Here's how to add it to Knex. 

```ts
import Knex from 'knex'

declare module 'knex' {
  interface QueryInterface {
    _method: string
    _isSelectQuery: () => boolean
    single: (columns?: string | string[], notFoundMessage?: string, notSingleMessage?: string) => Promise<any>
  }
}

Knex.QueryBuilder.extend('single', function single(
  this: Knex.QueryBuilder,
  columns: string | string[] = '*',
  notFoundMessage?: string,
  notSingleMessage?: string,
): any {
  // eslint-disable-next-line no-underscore-dangle
  if (!this._isSelectQuery() || this._method === 'first')
    // eslint-disable-next-line no-underscore-dangle
    throw new Error(`Cannot chain .single() on "${this._method}" query!`)
  // eslint-disable-next-line no-param-reassign
  if (typeof columns === 'string') columns = [columns]
  const allColumns = columns.includes('*')
  const singleColumn = !allColumns && columns.length === 1 ? columns[0] : false
  if (!allColumns) this.select(...columns)
  this.limit(2)
  return this.then((results: any[]) =>
    (console.log(results) as any) || results.length === 1
      ? singleColumn
        ? results[0][singleColumn]
        : results[0]
      : results.length
      ? Promise.reject(notSingleMessage || `Query has more than one result: "${this.toSQL().sql}"`)
      : Promise.reject(notFoundMessage || `Query has no results: "${this.toSQL().sql}"`),
  )
} as any)
```

@wubzz would you be interested in a PR adding the `single` method to `QueryInterface`?

**Comment by trojancode** [comment]
> `db('table_name').where({id: 1}).first().then((row) => row)`
> 
> Should work

worked for me

**Comment by jkalandarov** [comment]
> `db('table_name').where({id: 1}).first().then((row) => row)`
> 
> Should work

Returned `Promise { **pending** }`
Used following method to resolve: `variable.then(function(result) {
   console.log(result)
})`

**Comment by ssshammi** [comment]
Funny i wanted to return all matching the ID. as my id filed is not unique. But even then i get only one row returned. Is there a way to return all matching rows

**Comment by jkalandarov** [comment]
@sshammi how many rows are there in your table with the same `id`? If `id` is declared as `primary key` and `auto_increment`, then only one unique `id` will be given to each row. Therefore, you can't return all matching rows by `id`.

**Comment by ssshammi** [comment]
So basically my table had multiple rows for StudentID but it;s not a primary key. When I do this i get multiple row. However the moment I add .groupBy('SessionIdentifer') it returns just 1 row. and SessionIdentifer is also not the primaty key. ActivityID is they primaty key but i don;t want that in response. Thanks again for the response @jkalandarov  ` const rows = await Database("UserActivityData").select(
        "SessionIdentifer",
        "TaskName",
        "TimeTaken",
        "Score",
        "Status"
    ).where({
        StudentID,
        CourseID: 'SOPEP_1'
    });`
