### ISSUE TITLE
Postgres ORDER BY not working with bindings

### ISSUE THREAD

**Issue by pvsrivathsa** [tgriesser/knex#1357]
I am trying to order results from a table based on user input. So I thought using named bindings would be better to avoid SQL injection. I try the following code snippet
```
function getUsers() {
  var query = "select * from users order by :sortClause";
  var sortClause = "name desc";
  return knex.raw(query, { sortClause: sortClause });
}
```

I see that the results are not ordered as per the `order by` clause. Whereas the following code works

```
function getUsers() {
  var sortClause = "name desc";
  var query = "select * from users order by " + sortClause;
  return knex.raw(query);
}
```

**Comment by elhigu** [comment]
SQL generated by your knex.raw() is something like 

```
select * from users order by 'name desc'
```

try:

```
knex.raw("select * from :tableName: order by :sortColumn: desc", { sortColumn: 'name', tableName: 'users' })
```

And check from docs what is the difference between `:bindingName` and `:bindingName:`

**Comment by pvsrivathsa** [comment]
@elhigu The method you suggested works fine but what if I have to parametrize *asc* or *desc* itself?

**Comment by elhigu** [comment]
I'm not sure why are you using knex raw in this case... but query above doesn't require knex raw at all
```
knex('users').orderBy('name', 'asc');
```

With using knex raw there are many ways to achieve it e.g.
```
knex.raw("select * from :tableName: order by :sortColumn: :direction", { sortColumn: 'name', tableName: 'users' , direction: knex.raw('asc')})
```

or
```
var direction = shouldAscend ? 'asc' : 'desc';
knex.raw("select * from :tableName: order by :sortColumn: " + direction , { sortColumn: 'name', tableName: 'users' })
```
