### ISSUE TITLE
QueryBuilder forcing `limit 1` on generated query

### ISSUE THREAD

**Issue by JordanForeman** [tgriesser/knex#1358]
I asked a [SO question](http://stackoverflow.com/questions/36704318/knexjs-querybuilder-forcing-limit-1-on-generated-query) yesterday that didn't pick up any traction, so I suppose I'll ask it here - I'm skeptical, but I might've uncovered a bug with the library (I hope its just something I'm doing wrong).

As the title says I'm using the QueryBuilder to generate a query against my database, and for some reason am only being returned one result when I expect several. Going a step further and enabling debugging using a debug config flag, I see that the query generated has a `limit 1` appended to it, even though I do **not** specify that. 

I actually do some dynamic limiting and offsetting to create a sort of _"paging"_, but _my_ limit is set to 10 (per page), and even if I remove my paging logic, I still end up with that pesky `limit 1`!!!!! 

Here is my code, adjusted for out-of-context clarity:

```js
module.exports = bookshelf.Model.extend({
    tableName: 'my_table' }, {
    
  getAllMostRecentByUserId: promise.method(function(embed, page, pageSize) {
    var page = parseInt(page), // 1
        size = parseInt(pageSize); // 10

    return this.query(function (qb) {
      qb.whereIn('id', function(){
        this.max('id').from('my_table').where('some_other_key', '!=', 1).groupBy('user_id');
      });
      qb.limit(size).offset((page - 1) * size); // Happens with or without this line
    })
    .fetch({ withRelated : embed });
  })
});
```

And here is the query being printed out to my console:

```bash
sql: 'select `my_table`.* from `my_table` where `id` in (select max(`id`) from `my_table` where `some_other_key` != 1 group by `user_id`) limit 1'
```

My only guess is that maybe somehow the logic behind `max` assumes there should be a singular result (since its looking for **the** max ID), but that logic is being propagated up to my main query from my subquery - hence me raising this issue. I took a look at the `max` function in the src, and that didn't raise any red flags for me though...so...I'm kinda stumped! Feel free to close this if its not actually a bug - just trying to find some clarity.

**Comment by elhigu** [comment]
I really don't know much about bookshelf, but could the problem be that you are calling .fetch which according to docs is method for fetching just one model instance?

**Comment by JordanForeman** [comment]
@elhigu oh jeez...that's exactly it. Thanks for taking a look! Closing this.
