### ISSUE TITLE
Transaction was implicitly committed, do not mix transactions and DDL with MySQL

### ISSUE THREAD

**Issue by kousha-icracked** [tgriesser/knex#1359]
I'm trying to chain some transactions:

``` js
return knex.transaction(function(trx) {
    let promises = [
        trx.raw(someQuery),
        trx.raw(someOtherQuery)
    ];

    Promise
        .all(promises)
        .then(trx.commit)
        .then(trx.rollback);
});
```

When I run, the process works fine; if I have a problem in wither queries, then I get a rollback. However, I also get this warning:

> Knex:warning - Transaction was implicitly committed, do not mix transactions and DDL with MySQL (#805)

**Comment by rhys-vdw** [comment]
I'm not familiar with that specific DDL issue, but it seems there is some information on #805. However, your code is wrong:

```js
    Promise
        .all(promises)
        .then(trx.commit)
        .then(trx.rollback);
```

Should be:
```js
    Promise
        .all(promises)
        .then(trx.commit)
        .catch(trx.rollback); // <-- Rollback on error!
```

You were committing and then attempting to roll back. If this is the case then an incorrect error message is being displayed. Would you be able to confirm this?

FYI you can return a `Promise` from the tranasaction callbakc, so you could so something like this:

```js
return knex.transaction(function(trx) {
    return Promise.all([
        trx.raw(someQuery),
        trx.raw(someOtherQuery)
    ]);
});
```

Knex determines whether to commit or rollback based on the returned Promise.

**Comment by wubzz** [comment]
Closing old issue with no response.
