### ISSUE TITLE
`npm install` fails on Windows

### ISSUE THREAD

**Issue by wolfgang42** [tgriesser/knex#1361]
Windows interprets `./scripts/build.sh` as a call to command `.` with the arguments `/scripts` and `/build.sh`:

```
> knex@0.10.0 build C:\Users\wfaust\Documents\Development\knex
> ./scripts/build.sh

'.' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by rhys-vdw** [comment]
Can you think of a workaround for this?

**Comment by wolfgang42** [comment]
On second thought, the underlying problem is that this is a UNIX shell script, so the Windows CLI wouldn't understand it anyway. I suppose you could require mingw to be installed, and run it under bash; however that's another dependency.

The least hacky way I can think of to fix the problem is to convert it into `build.js` and run it under Node. Does that sound like a good solution to you?

**Comment by elhigu** [comment]
@wolfgang42 sounds like a good idea. I've been using `shelljs` for that kind of stuff and been pretty happy with it 👍

**Comment by wolfgang42** [comment]
I've done the change [in wolfgang42/knex](https://github.com/wolfgang42/knex/tree/issue-1361-replace-buildsh); however I think I'm going to wait for #1416 to land before submitting a PR.
