### ISSUE TITLE
How to select bson/json in postgres?

### ISSUE THREAD

**Issue by zettam** [tgriesser/knex#1363]
New to knex, new to postgres. I'm trying to select a bson/json nested key from my db.
My structure is as follows:
info:{name:.. , id:.. , details: {price:.., somethinglse:.., ..} .. }

so what I like to do is to select info.details.price only --- how is this possible?

**Comment by elhigu** [comment]
There are no specific APIs in knex to do this, but with knex raw this should do:

```js
knex('tableName').select(knex.raw("??#>'{info,details,price}'", ['jsonbColumnName']))
```

I also wrote while ago blog post about PostgreSQL jsonb features, it might be helpful:
https://www.vincit.fi/en/blog/by-the-power-of-json-queries/

**Comment by zettam** [comment]
THanks for the response, how can I do the same thing with multiple selects? such as, price, and somethingElse?

Alsı, the results appear as "?column?" - what should I do to name them properly ?

**Comment by elhigu** [comment]
I'm not 100% sure but I suppose the normal `as columnName` works e.g.

```
knex('tableName').select(knex.raw("??#>'{info,details,price}' as ??", ['jsonbColumnName', 'price']))
```

**Comment by zettam** [comment]
oh very nice, thank you very much!
