### ISSUE TITLE
"Connection successful" callback?

### ISSUE THREAD

**Issue by zettam** [tgriesser/knex#1364]
How/when do we know that the connection with the db is successful ? 

var pg = require('knex')({
    client: 'pg',
    connection: {
        user: 'myuser',
        password: '123456789',
        database: "mydb"
    },
    debug: false
})

above part sends a connection request as far as I understand, but when is it a success ?

**Comment by NerdPad** [comment]
#1341 I m having the same issue.

**Comment by zettam** [comment]
Could you find a solution @NerdPad

**Comment by NerdPad** [comment]
@zettam Not yet. However the discussion in that thread could help you.

**Comment by elhigu** [comment]
Could it be enough to use afterCreate callback which is executed when pool creates new connection to DB.

e.g.
```js
        knex: {
          client: 'postgres',
          debug: false,
          connection: {
            host: process.env.POSTGRES_HOST || 'localhost',
            port: process.env.POSTGRES_PORT || 5432,
            user: process.env.POSTGRES_USER || 'postgres',
            password: process.env.POSTGRES_USER_PW || undefined
          },
          pool: {
            min: 0,
            max: 10,
            afterCreate: function (conn, cb) {
              conn.query('SET timezone="UTC";', function (err) {
                cb(err, conn);
              });
              // set trigram search match similarity limit
              conn.query('SELECT set_limit(0.01);', function (err) {
                cb(err, conn);
              });
            }
          },
          migrations: {
            tableName: 'migrations'
          }
        }
```

**Comment by rmharrison** [comment]
Running into the same issue. I want a way (ideally a callback) of verifying that a connection was successful. Otherwise, I'll get timeout failures due to initial connection issues. Difficult to debug.

**Comment by rmharrison** [comment]
My issue with @elhigu 's solution was that even when setting `pool min: 1`, the `afterCreate()` hook isn't triggered until a query actually happens.

**Comment by ferrao** [comment]
👍 for this

**Comment by thanpolas** [comment]
I think there still is a problem of signaling that a good connection has been established. The `afterCreate` callback is consumed by knex itself and doesn't propagate in any way...

The only way I can think of, to propagate a successful (or not) connection to the database is to double invoke callbacks to that end:

```js
// Initialize and connect to the database
const initDb = new Promise(function (resolve, reject) {
  knex({
    client: 'pg',
    /* .... */
    pool: {
      afterCreate: function (conn, done) {
        // in this example we use pg driver's connection API
        conn.query('SET timezone="UTC";', function (err) {
          if (err) {
            // first query failed, return error
            done(err, conn);
            reject(err);
          } else {
            done(err, conn);
            resolve(conn);
          }
        }
      }
    },
  });
});
```

please correct me if I'm wrong or discuss how else this can be resolved @elhigu

**Comment by elhigu** [comment]
@thanpolas that is not a good way to do it. Pool is not automatically filled when knex instance is created. You can just launch a query to DB to check that you have working connection:

```js
const knex require('knex')({... confeticonfeticonfs ...});

await knex.select(knex.raw('1')); // if this doesn't throw then you have working db connection
```

**Comment by thanpolas** [comment]
As part of application boot I want to ensure that the DB connection is live and operating before proceeding to boot the rest of the app, I can do it the way you suggest too I guess

**Comment by rmharrison** [comment]
@thanpolas: Indeed, waiting for the `select` query to finish before loading the rest of the app and aborting in the case of timeout, will work.

**Comment by fiznool** [comment]
Just to weigh in with my own 2c: I've also been searching for a way to validate that the DB is up and accepting connections during app boot. I've opted to go for `SELECT 1` as the 'validation query' as this [appears to be well supported across various different databases](https://stackoverflow.com/questions/3668506/efficient-sql-test-query-or-validation-query-that-will-work-across-all-or-most).
