### ISSUE TITLE
How to log knex error (The one printed to console)

### ISSUE THREAD

**Issue by NerdPad** [tgriesser/knex#1365]
In a scenario when knex/pool2 fails to acquire connection on bootstrap, it prints out ```Knex:Error``` to stdout. Same when the ```DEBUG=...``` flag is on.

How can I log all these using my logging library? (We use node-bunyan).

**Comment by diversario** [comment]
I get this dumped into our JSON logs:

```
Knex:warning - Pool2 - Error: read ECONNRESET
Knex:Error Pool2 - Error: Pool.remove() called on non-member
Knex:warning - Pool2 - Error: Cannot enqueue Quit after fatal error.
Knex:warning - Pool2 - Error: read ECONNRESET
Knex:Error Pool2 - Error: Pool.remove() called on non-member
Knex:warning - Pool2 - Error: Cannot enqueue Quit after fatal error.
Knex:warning - Pool2 - Error: read ECONNRESET
Knex:Error Pool2 - Error: Pool.remove() called on non-member
Knex:warning - Pool2 - Error: Cannot enqueue Quit after fatal error.
```

I'm using `knex` in `bookshelf` models..

I would very much like to have something that captures this and allows me to handle whether or not to print it out.

**Comment by nixgadget** [comment]
Any update on this question ? Id like to suppress these errors and redirect them to a bunyan logger.

**Comment by c0b** [comment]
:+1: for same question, hopefully bump up priority to get some developer's attention here

**Comment by elhigu** [comment]
You can monkeypatch console.log for now or use DEBUG=knex:* and pipe logs to logging library program. I know, both are horrible options. I'll close this issue since there are more discusion about it here: https://github.com/tgriesser/knex/issues/1483
