### ISSUE TITLE
My forked knex breaks

### ISSUE THREAD

**Issue by krainboltgreene** [tgriesser/knex#1366]
I forked knex until #1263 was finished, but it breaks due to this:

```
function checkLocalModule(env) {
  if (!env.modulePath) {
    console.log(chalk.red('No local knex install found in:'), chalk.magenta(tildify(env.cwd)));
    exit('Try running: npm install knex.');
  }
}
```

How am I supposed to work around this?

**Comment by wolfgang42** [comment]
I ran into a similar problem and wound up publishing a custom version to a local npm server. If you only need this on one computer, though, you could do it with [npm link](https://docs.npmjs.com/cli/link). I believe this should work:
```bash
cd /path/to/knex
npm link
cd /path/to/project
npm link knex
knex migrate:latest
```

**Comment by rhys-vdw** [comment]
Hm. So if we removed [the check](https://github.com/tgriesser/knex/blob/32fec2bfc1da475906b33c4a9702b98b5090d149/src/bin/cli.js#L38) would it work? It looks like it then [`require`s that string](https://github.com/tgriesser/knex/blob/32fec2bfc1da475906b33c4a9702b98b5090d149/src/bin/cli.js#L69) and would fail regardless.

I'm not entirely clear on the scenario here. Are you saying that you can't use a forked repo as a project dependency and still use the CLI?

**Comment by nixgadget** [comment]
@krainboltgreene This is happening due to [Liftoff requirement](https://github.com/tgriesser/knex/blob/32fec2bfc1da475906b33c4a9702b98b5090d149/src/bin/cli.js#L186). My guess you must have renamed the package to something else. Hope this helps.

**Comment by krainboltgreene** [comment]
Yeah, I don't see any reasonable way to solve it sadly. I don't really want to maintain a fork, I just feel like putting much effort beyond what I did in #1255
