### ISSUE TITLE
Pass JSON as a select parameter.

### ISSUE THREAD

**Issue by mdrmuhaimin** [tgriesser/knex#1367]
Currently the only way to retrieve a variable using json inside where was described here #104. 

> I want to get the data by an attribute in a json. My example set looks like:
> 
> ```
> {
>     id: 6,
>     userid: 23,
>     info: {
>         provider: 'paypal
>     },
>     date: 1384782229
> }
> ```
> By using the wgAdmin I can run this query to get the result:
> 
> ```
> SELECT *
> FROM payment logs
> WHERE info->>'provider' = 'paypal'
> ```
> But there is no way to create a query like this with knex isn't it?

The answer that was given

> The closest you could currently get is:
> 
> `knex('paymentlogs').whereRaw("info->>'provider' = ?", ['paypal']).select().then(...
> `

The post was from 2013, is there a better way now?

**Comment by elhigu** [comment]
Still the same, knex.raw is needed.

**Comment by mdrmuhaimin** [comment]
I think I found a better way though. For example for the above query, we can write like 
` knex('paymentlogs').where('info' , '@>' , '{"provider": "paypal"}')` ? 

Can we not?

**Comment by elhigu** [comment]
@mdrmuhaimin  Yes you should be able to use @>, <@, =, ?, ?|, ?& operators like that if you are going to apply them to whole jsonb column and not to just part inside column. 

But if you like to do e.g. json.attribute LIKE '%john%'  which requires extracting attributes inside of json column those references to fields inside JSON require knex.raw. 

e.g. 
```js
knex('paymentlogs').where(knex.raw("info#>>'{owner,firstName}'"),'LIKE','%john%')
```

So you can actually write just reference to json field with knex.raw when needed.
