### ISSUE TITLE
Postgres authentication failing on node version 6.0

### ISSUE THREAD

**Issue by stv8** [tgriesser/knex#1371]
After upgrading node version 6.0, authentication to my Postgres database fails when instantiating the knex client. Downgrading to 5.11 made it work. 

Here is the error message I was getting.

`Knex:Error Pool2 - error: password authentication failed for user "$user"`

**Comment by ivarconr** [comment]
Verified that it fails on linux (but seems to work fine under OSX).

**Comment by ivarconr** [comment]
Seems to be a problem in pg: https://github.com/brianc/node-postgres/issues/1000

**Comment by tayden-hakai** [comment]
I'm having issues with this on OSX 10.11.4

**Comment by egalpin** [comment]
For what it's worth, I had success updating to `pg@4.5.5`

**Comment by mdrmuhaimin** [comment]
This is latest update from https://github.com/brianc/node-postgres/releases/tag/v4.5.5 installing it will fix the issue.

**Comment by Pro-YY** [comment]
Solved my problem! Thank you!

**Comment by spamguy** [comment]
FWIW, I'm still having this problem. Fine on OSX, fails on Ubuntu. pg and knex are up-to-date. I filed a ticket at brianc/node-postgres#1080.

**Comment by elhigu** [comment]
@spamguy did you try to `rm -fr` node_modules and re-install?

**Comment by demisx** [comment]
I am on node 6.4.0 and the issue was resolved 👍  by upgrading these packages to the latest and then reinstalling them:

```sh
├── bookshelf@0.10.0 # <- no need for this one if you are not using bookshelfjs
├── knex@0.11.10
├── pg@6.1.0
```

**Comment by alanbueno** [comment]
@egalpin suggestion solved the problem for me! Tks!
