### ISSUE TITLE
Question: db.runSql is not a function

### ISSUE THREAD

**Issue by reggi** [tgriesser/knex#1374]
Seeking some help: 

> http://stackoverflow.com/questions/36926147/knex-issue-db-runsql-is-not-a-function

I'm getting this issue when I try and run some knex code within a test.

    1) database functions insert "before each" hook:
       Uncaught TypeError: db.runSql is not a function
       at 20160226153911-table.js:13:8

I have this config that sets up knex.

    var config = {
      database: {
        client: 'pg',
        connection: {
          host,
          user,
          password,
          database,
          charset: 'utf8'
        }
      },
      directory: pathJoin(__dirname, '../migrations'),
      tableName: TABLE
    }

    var knex = Knex.initialize(config.database)

Here's the code

    describe('database functions', () => {

      describe('insert', () => {

        before(() => knex.migrate.rollback(config))
        beforeEach(() => knex.migrate.latest(config))

        it('should work', async () => {
          let result = await insert({knex, table: TABLE}, { data: { name: 'thomas' } })
          console.log(result)
        })

      })

    })

In the migration when I `console.log(db)` it logs something just does not have the `.runsql` method.

**Comment by elhigu** [comment]
Your migration file is trying to call `db.runSql` which is not a function. I have no idea what you are trying to do, but there is a problem in your migration file `20160226153911-table.js:13:8`.

Looks like you are trying to run some migration which is written from `db-migrate` library instead of `knex` migration.
