### ISSUE TITLE
knex transaction not rollback in `up` when doing data migration

### ISSUE THREAD

**Issue by chenweiyj** [tgriesser/knex#1376]
When I run `migrate` in `sails-migrations` which adopts knex to achieve the goal, even if I use  `knex.transaction(trx) {}` to wrap the whole migration, it still does not rollback upon the error in data insertion via `trx.insert(...).into(...)`.

I would like to know what is wrong. And how to make the whole migration in one transaction?

**Comment by rhys-vdw** [comment]
@chenweiyj Which version of Knex are you using? Migrations should be enabled by default in newer versions.

**Comment by albertkim** [comment]
I am personally using 0.12.9 and encountering the same issue using MySQL. I am not using Sails, however, just using Knex directly.

To give some examples:

```js
exports.up = function(knex, Promise) {
  return knex.transaction((transaction) => {
    return transaction.schema.raw(`
      alter table customers add column credit int not null default 0;
    `).then(() => {
      return transaction.schema.raw(`
        alter table asdf add column pointsPerCredit int;
      `)
    })
  })
}
```

I have also tried

```js
exports.up = function(knex, Promise) {
    return knex.schema.raw(`
      alter table customers add column credit int not null default 0;
    `).then(() => {
      return knex.schema.raw(`
        alter table asdf add column pointsPerCredit int;
      `)
    })
}
```

There is clearly no table named `asdf`, I just tried it to test that a bad migration would be rolled back. However, the `credit` column is always created on the `customers` table after the failed migration, and I can't get it to roll back. I have tried every knex migration/transaction suggestion to no avail.

I do not want to be fixing up bad migrations manually. I was under the impression that Knex migrations always ran under a transaction, but I'm not seeing it be applied in my case. What am I doing wrong here?

**Comment by elhigu** [comment]
@albertkim the problem here is not `knex`, its `mysql` and `oracle`. Unlike postgres/mssql they do implicit commit after most of the schema changing statements https://dev.mysql.com/doc/refman/5.7/en/implicit-commit.html http://www.sqlines.com/oracle/implicit_commit.

So with those databases to rollback changes on error after schema changing statements you need to catch if code inside migration `up` throws an error and do explicit cleanup when migration fails.

**Comment by elhigu** [comment]
I'm adding an issue to documentation branch to add mention about this to doc pages.

**Comment by albertkim** [comment]
Thanks for the clarification. I was not aware that schema changes were not done as part of a migration in MySQL and Oracle.
