### ISSUE TITLE
MSSQL: `SELECT top (@p0)` doesn't work before SQL Server 2005

### ISSUE THREAD

**Issue by wolfgang42** [tgriesser/knex#1378]
I'm using a database server which still runs SQL Server 2000. In this version, [`top (@p0)` doesn't work](http://stackoverflow.com/a/175978/1979340). Instead, the standard solution is [`SET ROWCOUNT`](https://msdn.microsoft.com/en-us/library/ms188774.aspx), like so:

```sql
set rowcount @p0
select * from sometable
set rowcount 0
```

However, `SET ROWCOUNT` is going to be removed in a future version of SQL Server.

I'm not really sure what to do in this scenario. I suppose I could add an option which specifies whether `TOP` or `SET ROWCOUNT` should be used, but that seems cumbersome.

**Comment by nickwhiteley** [comment]
Microsoft ended support for SQL 2000 three years ago (and SQL 2005 last month) so I suggest Knex shouldn't try to support it either.  Getting full support for the current versions is a better use of dev time.

**Comment by wolfgang42** [comment]
That's reasonable. Less than a week after I opened this ticket the tables I was trying to get at got moved to a 2008 server anyway, so this is no longer a problem for me. Should I close this issue?

**Comment by nickwhiteley** [comment]
IMHO, yes.
