### ISSUE TITLE
Replication - Master/Slave

### ISSUE THREAD

**Issue by whito** [tgriesser/knex#138]
Question or Feature Request: 

Is it currently possible to utilize replication (master/slave) with knex connections? Perhaps be able to pass an array of different connections during initialize and define their capabilities (read only, read write, write)

This way you can set up multiple databases on different boxes for scaling, redundancy, performance etc.

**Comment by jonathandelgado** [comment]
@tgriesser Are you still interested in implementing this? I'm not familiar enough with Postgres, but I can throw in a PR for the MySQL poolCluster solution I mentioned earlier in the issue.

**Comment by daviddutch** [comment]
@tgriesser any news on this? I would need this on Postgres.

**Comment by rvlander** [comment]
+1

**Comment by rvlander** [comment]
Any news on this? If nothing have been done I will have to do something myself. Did you have any plan, ideas, vision on how to implement it?

**Comment by rhys-vdw** [comment]
@rvlander It doesn't sound like it. You're encouraged to try this as it seems like a popular feature. I'm not sure what Tim's status is at the moment but he's been busy. He's requested above that somebody implements it, so go for it. I can't provide much guidance but can merge when you're done.

**Comment by jonathandelgado** [comment]
@rvlander If you need this now, just create a pool of knex instances and round-robin between them. That is what I am doing currently and it works great. You might need some kind of health monitoring depending on your application.

**Comment by avimar** [comment]
I plan to have a mysql master-master, and for maintenance purposes would shut one down for 3-30 minutes. Is there a way to do that without downtime?

If a query times out to mysql, will it try the next connection?

Is there a way get mysql to stop responding to pings but finish the current query, so it times out from the pool? Would it keep trying and add itself back later?

**Comment by codematix** [comment]
+10

**Comment by Eli-Goldberg** [comment]
+10

**Comment by ewdave** [comment]
Hi, any update on this feature on knex yet?

**Comment by elhigu** [comment]
Moving discussion to https://github.com/tgriesser/knex/issues/2253 where has been collected links to many related issues.
