### ISSUE TITLE
How to do where('column1','column2')?

### ISSUE THREAD

**Issue by mnpenner** [tgriesser/knex#1387]
If I try doing `.where('col1','col2')` I'll get back

```sql
`col1`='col2'
```

But I want

```sql
`col1`=`col2`
```

I suppose I can do

```js
.whereRaw('??=??',['ecp_client_id','emr_client_id'])
```

But surely there must be something a little more clean and concise?

**Comment by chrisbroome** [comment]
You can just use `.raw` for the column name instead of using a `.whereRaw` for the whole query:

```JavaScript
.where('col1', knex.raw('??', 'col2'))
```

**Comment by ozum** [comment]
Hi,

Not to reopen another ticket and cause ticket pollution I continue this closed one.

My function is only passed `queryBuilder`. See .modify(fn, *arguments) on knex documents. So is there a way to access knex.raw through queryBuilder?
