### ISSUE TITLE
create migration in subdirectory

### ISSUE THREAD

**Issue by khomyakov42** [tgriesser/knex#1395]
I would use the following file structure for migration
```
<root>
   /migrations
     /v1.0.0
       20160510103943_users-table.js
       20160510104944_session-table.js
    /v1.0.1
       20160510111002_posts-table.js
       20160510189377_comments-table.js
```

**Comment by rhys-vdw** [comment]
Why?

**Comment by khomyakov42** [comment]
I have about 100 migrations, store them as a flat list is not convenient.

**Comment by rhys-vdw** [comment]
Currently Knex requires all migrations to be added to [a single directory](https://github.com/tgriesser/knex/blob/6bcceb4f49bbab26bd1828b0c30120fd775fab46/src/migrate/index.js#L314-L319).

**Comment by khomyakov42** [comment]
https://github.com/tgriesser/knex/blob/6bcceb4f49bbab26bd1828b0c30120fd775fab46/src/migrate/index.js#L104
If you are reading to use a recursive directory, then it will solve my problem

**Comment by rhys-vdw** [comment]
Well I'm not sure about the general use case, but I typically have a folder in my migrations called `helpers` or similar, which contains custom functionality shared between my migrations.

This would break any existing projects using this file structure.

**Comment by khomyakov42** [comment]
The fact is that I have too much migration files
