### ISSUE TITLE
knex.raw in whereNot

### ISSUE THREAD

**Issue by ozum** [tgriesser/knex#1402]
Hi,

`knex.raw()` in `whereNot()` function swallows `not` keyword.

```js
// Generates: select * from "table" where "is_active"
// Expected: select * from "table" where not "is_active"

knex
    .select('*')
    .from('table')
    .whereNot( knex.raw('??', 'is_active') );
```

Although I can make another query by hand easily, my code works on an AST generated by a RQL parser. As a result both `a=1&is_active` and `a=1&not(is_active)` RQL queries generates same SQL.

Is this behavior by design or a bug?

Best Regards,

**Comment by elhigu** [comment]
As far as I know sounds like a bug.

**Comment by elhigu** [comment]
This could be also one workaround: 
```js
knex.select('*').from('table').whereNot(function () { this.where(knex.raw('??', ['is_active'])) }).toQuery();
// select * from "table" where not ("is_active")
```

But yep this really should be fixed...

**Comment by ozum** [comment]
@elhigu Thank you for your response. Since my query is generated by AST, unfortunately I can't use workarounds.
