### ISSUE TITLE
Index timestamps by default?

### ISSUE THREAD

**Issue by olalonde** [tgriesser/knex#1405]
It seems that since timestamps are often used for sorting it would be a good default to have them indexed.

**Comment by rhys-vdw** [comment]
@olalonde I don't think this should be a default, but it would be nice if you could do:

```js
table.timestamps().notNull().default(knex.fn.now()).index();
```

**Comment by rmharrison** [comment]
I also wouldn't default the `index()`, but defaulting to `now()` would be useful.

**Comment by kibertoad** [comment]
Original suggestion is too opinionated and shouldn't be implemented in knex, so I'm closing this issue.
