### ISSUE TITLE
The operator "lkie" is not permitted

### ISSUE THREAD

**Issue by zhouxinyong** [tgriesser/knex#1406]
I used knex to select the datas,but I got error: The operator "like" is not permitted. How to solve it?

here is my code:

```
 const devices = await myKnex('device_with_tags_sensors')
                       .where('tags', 'lkie', `%${tags}%`)
```

The document [http://knexjs.org/#Builder-whereNotIn](http://knexjs.org/#Builder-whereNotIn) said we can  use this:

```
knex('users').where('name', 'like', '%Test%').orWhereNotIn('id', [1, 2, 3])
// select * from `users` where `name` like '%Test%' or `id` not in (1, 2, 3)
```

but when I run my code,why get an error:  The operator "like" is not permitted

**Comment by wubzz** [comment]
@zhouxinyong It's `like` not `lkie`, you got a typo.

**Comment by zhouxinyong** [comment]
@wubzz yes,I got it.it's my mistake.
