### ISSUE TITLE
SSH Tunnling Support

### ISSUE THREAD

**Issue by reggi** [tgriesser/knex#1414]
I'd love to be able to run migrations from my local machine using SSH. Is this something that knex could support?

**Comment by wubzz** [comment]
To me this sounds like something that should be on the driver level, not in knex. Just my two cents.

**Comment by elhigu** [comment]
That would be completely out of scope of knex. Btw. having similar capability out of the box with knex you can run migrations from your local machine using remote connection to your DB.

**Comment by ignasbernotas** [comment]
@reggi how did you solve this?

**Comment by reggi** [comment]
@ignasbernotas If you ssh / tunnel in terminal you can use knex to connect to the tunneled localhost.

**Comment by ignasbernotas** [comment]
@reggi I'm building an app that needs to be able to connect via user defined connection which in some cases is through an ssh tunnel on a remote server.

**Comment by PierBover** [comment]
Anyone solved this?

**Comment by m00dy** [comment]
I think this shouldn't be completely out of scope of knex. Knex is a query builder and therefore connect's to databases. Using ssh-tunnel is one of the common security practices today in database world.

**Comment by kibertoad** [comment]
@m00dy And what is the problem with just using tunneling on an OS level?..

**Comment by elhigu** [comment]
@m00dy that is completely out of scope of knex. Tunneling is handled OS level or database driver level, but definitely not knex level.

**Comment by PierBover** [comment]
For what it's worth, I used `mysql-ssh` to solve this, although I ended up using raw queries because I couldn't figure out how to use it with Knex.

**Comment by elhigu** [comment]
> Spawning instances on cloud is getting very very cheap these days. So, using a ssh-tunnel is becoming more like a mainstream thing /or at least this is where it is going.

Disagreed (even that these speculations are not relevant to this issue) people are using more and more each clouds own database services (RDS / Cloud SQL mostly) and each of them has their own support how to connect them securely remotely. Cloud SQL has their own local proxy thing and RDS uses AWS security groups. I haven't spawned my own database servers years (except for local testing of course). I believe that less people are requiring support for tunnels in future, when ad-hoc DB installations in cloud are getting fewer and people use readymade services, which offers ready made replication, support and updates.

>  It would be great If I passed a parameter to knex and see that all the way down to the driver.

`connection: {...}` part of knex configuration is passed directly to database driver.

@PierBover if there is some specific problem with that I suggest trying stackoverflow for support how to set it up.

**Comment by morgler** [comment]
Though this might be out of scope for knex, it would be great to see an example mentioned in the docs. As others have said, SSH is a common way to connect to a DB and thus a common stumbling block for getting started with knex.

**Comment by elhigu** [comment]
Feel free to add an example for it to github wiki.

**Comment by vitordeco** [comment]
Does anyone have an example of how to use the connection via tunnel in knex?

**Comment by picosam** [comment]
I think this may help: https://blog.pyrospect.com/2019/01/how-to-manage-remote-servers-and.html
