### ISSUE TITLE
Adding a binary column in mssql fails

### ISSUE THREAD

**Issue by statyan** [tgriesser/knex#1422]
There is a bug in **mssql/schema/columncompiler.js** for type "binary". 
```
binary: function binary(length) {
    return length ? 'varbinary(' + this._num(length) + ')' : 'blob';
},
```

If length wasn't passed, the type 'blob' is set to column and altering table query fails cause there is no 'blob' type for MS SQL. My proposal is to replace 'blob' with 'varbinary(max)'.

**Comment by rhys-vdw** [comment]
Yep. `varbinary(max)` sounds like the correct action.
