### ISSUE TITLE
AUTO_INCREMENT a big integer

### ISSUE THREAD

**Issue by NikolaBorislavovHristov** [tgriesser/knex#1438]
I have the following line of code in my app:

`
table.bigInteger("parsonId").notNullable().primary();
`

How to make this auto increment?
`table.increments()` is not a suitable method for me.

**Comment by jurko-gospodnetic** [comment]
A quick search through the sources turned up the `bigincrements` column type. Perhaps that can help?

**Comment by NikolaBorislavovHristov** [comment]
Perfect!

**Comment by rhys-vdw** [comment]
Note: This is mentioned in `increments` docs, so we can leave this issue closed.

**Comment by ankush981** [comment]
Perhaps the `bigIncrements` word can be put in bold? When scanning through the documentation, one sees the `increments` heading and assumes that `bigIncrement` perhaps doesn't exist.
