### ISSUE TITLE
Pool Destroyed w/ Child Processes

### ISSUE THREAD

**Issue by funnylookinhat** [tgriesser/knex#1449]
I have a fairly straightforward knex configuration:

```
{ client: 'mysql',
  pool: { min: '2', max: '10' },
  connection:
   { host: '127.0.0.1',
     port: '3306',
     user: 'username',
     password: 'password',
     database: 'mydb' } }
```

And I'm using node's `cluster` module to create child processes that each invoke a new Knex object.  All of a sudden with the latest `0.10.x` and `0.11.x` branches I've gotten the following for EACH process:

```
Knex:Error Pool2 - Error: connect ETIMEDOUT
Knex:Error Pool2 - Error: connect ETIMEDOUT
```

And any attempt to access the knex object results in a "Pool is destroyed" error.

I downgraded to `0.9.x` and all of a sudden it works again.  It looks like all installed versions are using the same version of `pool2@1.3.4` - so I don't think that's the problem.  Any thoughts / ideas?

If I load this configuration WITHOUT node clustering (e.g. on the master process) then it works perfectly fine.

```
vagrant@vagrant:/vagrant$ node --version
v4.4.3
vagrant@vagrant:/vagrant$ npm --version
2.15.1
```

**Comment by funnylookinhat** [comment]
One thing I've noticed is that setting the following fixes the issue - at least as far as I can tell:

```
pool: {
  min: 0,
  max: 2
}
```

**Comment by Chyzwar** [comment]
I had similar issues but with memory. knex 0.11.1 work ok but 0.11.5 have memory leak. 
It is something with knex or pool2. pool2 upgraded simple-backoff versions. 

```
└─┬ knex@0.11.5 
  ├─┬ liftoff@2.2.1 
  │ ├── extend@2.0.1 
  │ ├─┬ findup-sync@0.3.0 
  │ │ └── glob@5.0.15 
  │ ├── flagged-respawn@0.3.2 
  │ └── rechoir@0.6.2 
  ├── minimist@1.1.3 
  ├── pg-connection-string@0.1.3 
  ├─┬ pool2@1.3.4 
  │ ├── hashmap@2.0.6 
  │ └── simple-backoff@1.0.0 
  ├─┬ readable-stream@1.1.14 
  │ └── isarray@0.0.1 
  └── tildify@1.0.0 
```

```
└─┬ knex@0.11.1 
  ├─┬ liftoff@2.2.1 
  │ ├── extend@2.0.1 
  │ ├─┬ findup-sync@0.3.0 
  │ │ └── glob@5.0.15 
  │ ├── flagged-respawn@0.3.2 
  │ └── rechoir@0.6.2 
  ├── minimist@1.1.3 
  ├── pg-connection-string@0.1.3 
  ├─┬ pool2@1.3.4 
  │ ├── hashmap@2.0.6 
  │ └── simple-backoff@1.0.0 
  ├─┬ readable-stream@1.1.14 
  │ └── isarray@0.0.1 
  └── tildify@1.0.0 
```

**Comment by cbrunnkvist** [comment]
It sounds like perhaps you are opening the connections before cluster forks: the sockets/file descriptors for the original connections are not supposed to be shared across separate processes... Setting pool minimum to 0 means you just happen to make it work by not opening any connections before the forking happens. If my assumption is valid then the correct thing to do for you ensure you instantiate your knex clients _after_ cluster.fork().

But then again, you said it used to work under 0.10.x ...? 😕

**Comment by Chyzwar** [comment]
Sorry, it is not pool related, memory leak is possible in knex from 0.11.2. In my case it is during long seeding node peak up 1.4gb and crash. I will create separate issue when I get reproduction case possible.

**Comment by funnylookinhat** [comment]
@cbrunnkvist Right - it works fine under `0.9.x` - but not `0.10.x` or `0.11.x`

I also tried making sure the cluster master does not connect to knex at all, only the forked processes, and that did not fix it.

As it is, with `min: '2'` set, in `0.9.x` my master process connects to the server along with each child process and it works fine.  In `0.10.x` and `0.11.x`, my master process connects to the server but only the child processes cannot.

**Comment by elhigu** [comment]
@funnylookinhat could  you give runnable example how to reproduce this problem? this will be pretty impossible to resolve without it.

**Comment by funnylookinhat** [comment]
@elhigu I'm going to try to pull together a working example.  I'm having trouble replicating it outside of my application with a more barebones setup - so I'm wondering if something else might be involved.  I will let you know.

**Comment by funnylookinhat** [comment]
I can't get this to replicate on anything except the codebase I'm using for my employer - and that isn't open source.  I'm going to close this until I can come up with a scenario that easily repeats it.
