### ISSUE TITLE
Transactions appear to be committed before the end of promise chain

### ISSUE THREAD

**Issue by egalpin** [tgriesser/knex#1453]
Hi there,

Been using knex for a bit and thoroughly appreciate the efforts of everyone involved; it's a great tool.  Recently, an issue was illuminated by an automated test, revealing a race condition.  We tracked the issue down to a transaction. Here's a code sample:

```javascript
return knex.transaction(function (trx) {
    return functionThatSelectsForUpdate(trx)
        .then(function (dbRows) {
            return functionThatUpdatesRows(dbRows, trx);
        });
});
```

The above transaction would not necessarily wait for `functionThatUpdatesRows` to finish before committing the transaction.  Adding an empty `.then` at the end of the promise chain fixes the issue we were seeing:

```javascript
return knex.transaction(function (trx) {
    return functionThatSelectsForUpdate(trx)
        .then(function (dbRows) {
            return functionThatUpdatesRows(dbRows, trx);
        })
        .then();
});
```

I can only assume then that indicating to `knex` that further work is to be done, and that the further work depends on `functionThatUpdatesRows` being finished, ensures that the transaction is committed at the proper time.

Please note that I tried using `.then(trx.commit)` as per the [knex documentation](http://knexjs.org/#Transactions), but this presented further issues ("error: transaction already completed") since the trx is implicitly committed by `knex`.

Please let me know if this is user error on my part, or if you require any further information to help resolve this.  Thanks!

**Comment by jurko-gospodnetic** [comment]
If `functionThatUpdatesRows()` returns a promise that will get resolved once the DB operation implemented in that function has been completed, then there should be no need for the extra `.then()` call.

And even if you are returning a knex object representing an SQL query, but not actually running it, it should get run by `knex` by hooking its own `.then()` handler to it.

So I can't really see what could be causing it from your description. Can you prepare a simple example reproducing the behaviour you're describing?

**Comment by egalpin** [comment]
I can certainly try.  I'll work on putting something together that reproduces the issue. May take some time. Thanks!

**Comment by egalpin** [comment]
This was actually an alternate issue in the implementation, **not** the fault of `knex` whatsoever.  The [knex documentation](http://knexjs.org/#Transactions) is outdated regarding implicit `trx.commit`, but that's a separate issue.

Thanks!

**Comment by elhigu** [comment]
@egalpin actually there are two separate examples, where other requires explicit commit and another one relays on implicit commit depending on promise result... I don't know what you mean by document being outdated?

**Comment by egalpin** [comment]
@elhigu Thanks, read the doc wrong.  Your comment prompted me to re-read, during which I found that "... **if a promise is not returned** within the handler, it is up to you to ensure trx.commit, or trx.rollback are called..." (emphasis mine)
