### ISSUE TITLE
knex memory leak from 0.11.2

### ISSUE THREAD

**Issue by chyzwar** [tgriesser/knex#1457]
Hi, 

When using seed API I have memory leak for knex 0.11.2 and above.

30 sec after starting seed:
![knex-1](https://cloud.githubusercontent.com/assets/5990767/15627352/47f00d7a-24d9-11e6-8f6b-8d94ad46251e.png)

around 10 min later:
![knex-2](https://cloud.githubusercontent.com/assets/5990767/15627382/e62e78a0-24d9-11e6-9f96-c2e674a33b52.png)

and its crash in around 30 min (gradually slow down as well):
![knex-3](https://cloud.githubusercontent.com/assets/5990767/15627488/a8e05046-24dd-11e6-839b-96deb1c07ece.png)

Code to reproduce:

``` js
import faker from 'faker';

/* eslint no-console: "allow" */
function generate(iterations, perIteration, knex, tableName, generator) {
  console.log(tableName, iterations * perIteration);

  return knex
    .batchInsert(tableName, generator(perIteration))
    .then(() => {

      if (iterations) {
        return generate(iterations - 1, perIteration, knex, tableName, generator);
      }
    });
}

function usersGen(number) {
  const newUsers = [];

  for (let i = 0; i <= number; i++) {
    newUsers.push({
      firstName: faker.name.lastName(),
      lastName: faker.name.firstName(),
      userName: faker.internet.userName(),
      password: faker.internet.password(),
      avatar: faker.image.avatar(),
      email: faker.internet.email(),
      createdAt: faker.date.past(),
      groupId: 3,
    });
  }
  return newUsers;
}

exports.seed = (knex, Promise) => {
  console.log('User seeder, starting');

  return Promise.join(
    knex('users').truncate(),

    /**
     * Generate 10 milions of users,
     * 10000 iterations and 1000 each
     */
    generate(10000, 1000, knex, 'users', usersGen)
  );
};

```

I was reading knex code but there was huge refactoring when moving to es6. For version 0.11.1 memory usage is stable around 100mb.

**Comment by rhys-vdw** [comment]
@Chyzwar Okay, this is worrying.

> there was huge refactoring when moving to es6. For version 0.11.1 memory usage is stable around 100mb.

The move to ES6 happened before version 0.11, so that break (`/lib` -> `/src`) shouldn't be too difficult. Have you pinned down which release caused this?

And is this only a problem with `batchInsert`?

**Comment by Chyzwar** [comment]
Leak happen 0.11.2 and above. 0.11.1 is safe. When I was was looking into source in version 0.11.2 there was a lot commits related to es6. 

I am using MariaDB, maybe below is related, 
https://github.com/mscdex/node-mariasql/issues/144

**Comment by kibertoad** [comment]
Known memory leaks were resolved after changes in connection pooling. If problem is still observed in 0.15+ versions, please raise a new issue.
