### ISSUE TITLE
knex.batchInsert(...).returning is not a function

### ISSUE THREAD

**Issue by ashah023** [tgriesser/knex#1462]
According to the documentation, `batchInsert` is able to return values.

> BatchInsert also allows for returning values and supplying transactions using transacting.

An example is also provided by the documentation:

```javascript
  var rows = [{...}, {...}];
  var chunkSize = 30;
  knex.batchInsert('TableName', rows, chunkSize)
  .returning('id')
  .then(function(ids) {
    ...
  })
  .catch(function(error) {
    ...
  });
```

However, whenever I attempt to use the above code, I receive the following error: 
`TypeError: knex.batchInsert(...).returning is not a function`

I have updated to the latest version of Knex. Perhaps there is something I am missing?

Thank you in advance.

**Comment by rhys-vdw** [comment]
> I have updated to the latest version of Knex. Perhaps there is something I am missing?

Did this work before the update?

**Comment by ashah023** [comment]
No. I actually updated for this reason, but updating did not help.

**Comment by wubzz** [comment]
This doesn't make any sense, considering [this](https://github.com/tgriesser/knex/blob/master/test/integration/builder/inserts.js#L676) is still passing CI builds.

Are you sure the update was successful?

**Comment by ashah023** [comment]
My apologies! Looks like the update was indeed unsuccessful. _Actually_ updated today, and everything is fine.

Thank you for pointing me to the test cases. Sorry, again!
