### ISSUE TITLE
Method columnInfo for mssql fails

### ISSUE THREAD

**Issue by statyan** [tgriesser/knex#1463]
Tried on knex 0.11.5 with MS SQL connection.
Knex library lib/dialects/mssql/query/compiler produces incorrect query for columnInfo method.
Now it concatenates two strings:
` var sql = 'select * from information_schema.columns' + 'where table_name = ? and table_schema = \'dbo\'';`
And there is no space between  **information_schema.columns** and **where**.
Should be: 
` var sql = 'select * from information_schema.columns where table_name = ? and table_schema = \'dbo\'';`

**Comment by rhys-vdw** [comment]
Thanks. Could you open a PR please?

**Comment by statyan** [comment]
Yep, done!
