### ISSUE TITLE
How to do count in having clause using knex js ? 

### ISSUE THREAD

**Issue by monera23** [tgriesser/knex#1468]
I  am performing a double join using 2 tables and after that I am grouping the rows by an id column after that I want to count the number of particular projects for each id using the having clause. So how to use the having clause here. Basically I need to use count(project_Id) inside the having.

**Comment by rhys-vdw** [comment]
Have you tried using `knex.raw`?

**Comment by monera23** [comment]
To include the having clause in knex.raw ? Can you give an example, if that is the case ?

**Comment by elhigu** [comment]
@monera23 how is the query that you are trying to create written in plain sql without knex?

**Comment by monera23** [comment]
select * from table1 join tabl2 on table1.pk and table2.pk 
table2 join table3 on table2.pk and table3.pk 
where <condition>
group by table1.id
having(count > 0)
order by table1.id

Now the count that I want in having() is counting the number of projects in table3
Any suggestions ?

**Comment by rhys-vdw** [comment]
`join on {column} and {column}` is not valid SQL. And the column `count` you've used in the `having` clause is not defined. So I wont bother writing out that *exact* query

But the general idea is:

```js
knex('table1').groupBy('table1.id').having(knex.raw('count(*) > 0'));
```
