### ISSUE TITLE
Show warning when query inside transaction block is not using trx

### ISSUE THREAD

**Issue by kimmobrunfeldt** [tgriesser/knex#1469]
I have had quite a few occasions where I've created a transaction block but I forget to use the `trx`object and it causes errors in my app logic. For example, 

``` js
function insertAndReturnUsers(userObj) {
  return knex.transaction(trx => {
    return trx.insert(userObj).into('table_a')
      .then(() => getUsers())
  })
  .catch(err => {
    // Transaction failed.. do something
  });
}


function getUsers() {
  return knex('users').select('*');
}
```

In this case `insertAndReturnUsers` function has a bug. It doesn't return the newly created user when listing all users. I tend to do this mistake a lot and almost never my intention is to do a query **outside** the transaction.

Could it be possible to add a developer warning when accidentally doing this ?

**Comment by elhigu** [comment]
True, this is very common failure. 

Sadly as far as I know it is impossible to implement, kind of check you are describing. If that check could be implemented, in that case we could also bind query automatically to correct transaction...

Any ideas how to implement this?

**Comment by tgriesser** [comment]
I've thought about this (and I'm interested to hear any other ideas here). There isn't really a simple way to do this, since it's possible to lift the transaction object out of the transaction block. 

Instead I'm working on adding a new path for transactions, keeping but likely eventually deprecating the current syntax, where you'd instead call as a function and receive a transaction object:

```js
const trx = knex.transaction(/* optional config */)

trx.insert(userObj).into('table_a')
  .then(() => trx.select('*').from('users'))
  .then(trx.commit)
  .catch(trx.rollback)
```

this would make it simpler to create a transaction which properly works across an entire request / response cycle:

```js
app.use((req, res, next) => {
  req.knex = knex.transaction()
  onHeaders(req, () => {
    if (!req.knex.complete) {
      console.warn('Transaction was not committed or rolled back')
      req.knex.commit()
    }
  })
  next()
})
app.use((err, req, res, next) => {
  if (req.knex && !req.knex.complete) {
    req.knex.rollback(err)
  }
  //...
})
```

Then you'd just be sure to use `req.knex` and every query would always be on the same connection / transaction. It would also be possible to limit this behavior to post requests if you want.

```js
app.use((req, res, next) => {
  if (req.method === 'POST' || req.method === 'PUT' || req.method === 'DELETE') {
    req.knex = knex.transaction()
    onHeaders(req, () => {
      if (!req.knex.complete) {
        console.warn('Transaction was not committed or rolled back')
        req.knex.commit()
      }
    })
  } else {
    req.knex = knex
  }
  next()
})
```

Finally, these transaction objects would be lazy / inexpensive, there wouldn't actually be any connection checked out of the pool and no queries would be sent to the database until the first query is executed.

**Comment by wubzz** [comment]
Closing as this is not something we can do due to technical limitations, but there are other issues open relating to Tims example above.

**Comment by timbrownsf** [comment]
Was something like this ever implemented @tgriesser

**Comment by kibertoad** [comment]
@timbrownsf Can you provide an example of a wrong usage? I might try to cook something up.

**Comment by timbrownsf** [comment]
Sure, a common usage pattern:
```
updateUser: async ({id, newEmail}, {gqlContextDataloaders}) {
  const trx = await UserModel.knex().transaction();
  // Update user
  await UserModel.query(trx).patch({email: newEmail}).where({id});

  // Get some other record that we need to update, but use the dataloaders (our per-request cache)
  const otherRecords: Model[] = await dataLoaders.someOtherModel.byUserId.load(id);
  
  // Maybe do other stuff, doesn't matter at this point, the above line was the one that did a query without using the transaction.

  trx.commit()
}

```

**Comment by timbrownsf** [comment]
Perhaps I could set a `currentTransaction` property on our dataLoaders object, but without being able to check if it's open it could lead to errors. I could build my own `commitTrx(trx: Transaction)` method and use eslint to prevent devs from calling trx.commit() I guess...

**Comment by kibertoad** [comment]
@timbrownsf Wait, so how can dataLoader be aware of transaction existing elsewhere, if it is operating on its own clone of query builder?

**Comment by timbrownsf** [comment]
It isn't - thus the problem we often stumble into. Trying to figure out the best way to make dataloaders aware of current transaction.

**Comment by kibertoad** [comment]
@timbrownsf you can make a transaction parameter mandatory for dataloaders to force developers explicitly pass e. g. NO_TRANSACTION Symbol in cases you don't need one.

**Comment by timbrownsf** [comment]
I could, but trying to see if there's an easier way to do this that doesn't
require passing trx everywhere. Having a global transaction could work, but
not if I can't identify whether it's open or not.

**Comment by kibertoad** [comment]
@timbrownsf I think `transactionProvider` might be a helpful solution for you. Check out this example from documentation:

```
// Does not start a transaction yet
const trxProvider = knex.transactionProvider();

const books = [
  {title: 'Canterbury Tales'},
  {title: 'Moby Dick'},
  {title: 'Hamlet'}
];

// Starts a transaction
const trx = await trxProvider();
const ids = await trx('catalogues')
  .insert({name: 'Old Books'}, 'id')
books.forEach((book) => book.catalogue_id = ids[0]);
await  trx('books').insert(books);

// Reuses same transaction
const sameTrx = await trxProvider();
const ids2 = await sameTrx('catalogues')
  .insert({name: 'New Books'}, 'id')
books.forEach((book) => book.catalogue_id = ids2[0]);
await sameTrx('books').insert(books);
```
