### ISSUE TITLE
postgres: array column of uuids (or integers) and references

### ISSUE THREAD

**Issue by rkoberg** [tgriesser/knex#1471]
Is there some way to create references with a column that has an array of UUIDs? Or if not for UUIDs, then for integers?

First, I added this: https://coderwall.com/p/1b5eyq/index-for-uuid-array-data-type which provides a UUID type for arrays.

Is there some way to add a references() to this array?
```
    knex.schema.createTable('products', function(table){
...
//      table.jsonb('regions')
      table.specificType('regions', 'uuid[]')
        .defaultTo(knex.raw('ARRAY[]::uuid[]'))
        .references('id')
        .inTable('regions');
...
    })
```

**Comment by elhigu** [comment]
Could you add the SQL query here that you are trying to build... If it can be done with SQL I'm pretty sure that knex can generate correct query with knex.raw() if there is no better option.

**Comment by rkoberg** [comment]
I went a different route (you can close if you want), but basically something like:
```
CREATE TABLE regions (
   id integer PRIMARY KEY,
   name text,
   ...
);
 
CREATE TABLE wines (
   id integer PRIMARY KEY,
   regions integer[] ELEMENT REFERENCES regions,
);
```
where the regions on wines is an ordered list of regions, like IDs for [France, Bordeaux, Pomerol].

**Comment by elhigu** [comment]
Nice I hadn't seen an array of foreign keys before 😊 Closing the issue

**Comment by rkoberg** [comment]
Related to: https://github.com/tgriesser/bookshelf/issues/363

**Comment by SuyunovJasurbek** [comment]
onasini emsin bila . Odam zzz bub ketii

**Comment by SuyunovJasurbek** [comment]
Ertalabdan beri shu Bug ni deb
