### ISSUE TITLE
TypeError: Cannot read property '1' of null

### ISSUE THREAD

**Issue by Snugug** [tgriesser/knex#1477]
Trying to bootstrap my Node application, getting the following error, don't know how to proceed:

```bash
TypeError: Cannot read property '1' of null
/home/vcap/app/node_modules/knex/lib/dialects/postgres/index.js:128
 at emitOne (events.js:95:20)
 at Socket.<anonymous> (/home/vcap/app/node_modules/pg/lib/connection.js:109:12)
 at emitOne (events.js:90:13)
 resolver(/^PostgreSQL (.*?)( |$)/.exec(resp.rows[0].version)[1]);
 ^
 at Socket.emit (events.js:182:7)
 at readableAddChunk (_stream_readable.js:153:18)
 at Socket.Readable.push (_stream_readable.js:111:10)
 at TCP.onread (net.js:534:20)
 at null.<anonymous> (/home/vcap/app/node_modules/pg/lib/client.js:163:19)
 at Query.handleReadyForQuery (/home/vcap/app/node_modules/pg/lib/query.js:89:10)
 at null.callback (/home/vcap/app/node_modules/knex/lib/dialects/postgres/index.js:128:69)
 at emit (events.js:182:7)
npm ERR! Linux 3.19.0-33-generic
npm ERR! argv "/home/vcap/app/vendor/node/bin/node" "/home/vcap/app/vendor/node/bin/npm" "start"
```

**Comment by elhigu** [comment]
Could it be because your DB returns null as a version and then is trying to read its property 1?  

```js
resolver(/^PostgreSQL (.*?)( |$)/.exec(resp.rows[0].version)[1]);
```

More information would be necessary to resolve this any further. What is your DB, knex configuration and please add minimal example code (single file) which allows us to reproduce the problem. Also, which knex version are you using?

**Comment by Snugug** [comment]
This can be closed. It turns out no one I've talked to has been able to successfully get any database from the provider I was using to work. Switched providers and all is fine now. Thanks for the reply.

**Comment by phamdt** [comment]
I am also seeing this using GCP CloudSQL postgres with knex version 0.10.0. In my case it happened when i had to restart an application in production after some connection timeout issues.

**Comment by ThanhHuuTran** [comment]
I encounter this issue while using enterpriseDB: https://www.enterprisedb.com/
query "select versions()" return 
**"EnterpriseDB 9.6.18.25 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-36), 64-bit"**
therefore the regex `"/^PostgreSQL (.*?)( |$)/.exec(resp.rows[0].version)"` return null in this case

**Comment by phamdt** [comment]
i ended up just upgrading knex@0.21.2 which for me was far enough to fix the problem without having to deal with breaking changes in my consuming app.

**Comment by lancejpollard** [comment]
I am getting this when trying to connect to CockroachDB.

I have this:

```js
module.exports = {
  client: 'pg',
  connection: {
    connectionString: process.env.DATABASE_URL,
  },
  migrations: {
    directory: __dirname + '/../migrations',
  },
  seeds: {
    directory: __dirname + '/../seeds'
  }
};
```

The database URL is like:

postgresql://<user>:<pass>@free-tier9.gcp-us-west2.cockroachlabs.cloud:<port>/defaultdb?sslmode=verify-full&options=--cluster%3D<name>

However, I am getting:

```
/thecode/node_modules/knex/lib/dialects/postgres/index.js:135
    return /^PostgreSQL (.*?)( |$)/.exec(versionString)[1];
                                                       ^
TypeError: Cannot read properties of null (reading '1')
    at Client_PG._parseVersion (/thecode/node_modules/knex/lib/dialects/postgres/index.js:135:56)
```

Any ideas how to get this working? I added the postgres root.crt to home folder as well like the CockroachDB docs said.

```
$ npx knex --version
Knex CLI version: 2.0.0
Knex Local version: 2.0.0
```

Node version 17.

**Comment by lancejpollard** [comment]
Fixed it as seen in the linked post.

**Comment by rajsenthil** [comment]
> I am getting this when trying to connect to CockroachDB.
> 
> I have this:
> 
> ```js
> module.exports = {
>   client: 'pg',
>   connection: {
>     connectionString: process.env.DATABASE_URL,
>   },
>   migrations: {
>     directory: __dirname + '/../migrations',
>   },
>   seeds: {
>     directory: __dirname + '/../seeds'
>   }
> };
> ```
> 
> The database URL is like:
> 
> ```
> postgresql://<user>:<pass>@free-tier9.gcp-us-west2.cockroachlabs.cloud:<port>/defaultdb?sslmode=verify-full&options=--cluster%3D<name>
> ```
> 
> However, I am getting:
> 
> ```
> /thecode/node_modules/knex/lib/dialects/postgres/index.js:135
>     return /^PostgreSQL (.*?)( |$)/.exec(versionString)[1];
>                                                        ^
> TypeError: Cannot read properties of null (reading '1')
>     at Client_PG._parseVersion (/thecode/node_modules/knex/lib/dialects/postgres/index.js:135:56)
> ```
> 
> Any ideas how to get this working? I added the postgres root.crt to home folder as well like the CockroachDB docs said.
> 
> ```
> $ npx knex --version
> Knex CLI version: 2.0.0
> Knex Local version: 2.0.0
> ```
> 
> Node version 17.

Hello, I am facing the same problem connecting with cockroachdb. Is there any solution/workaround available?

**Comment by thesunny** [comment]
The fix is to change `client: 'pg'` to `client: 'cockroachdb'` and it doesn't feel like it should work because you haven't installed a cockroachdb specific driver (just the `pg` one), but it does work.

I just tried it out and it worked.

**Comment by jeffery526** [comment]
The database version can be added in knex configuration, when you use the PostgreSQL adapter to connect a non-standard database.

**Comment by jeffery526** [comment]
const knex = require('knex')({
  client: 'pg',
  **_version: '7.2',_**
  connection: {
    host: '127.0.0.1',
    port: 5432,
    user: 'your_database_user',
    password: 'your_database_password',
    database: 'myapp_test',
  },
});
