### ISSUE TITLE
Can't find the 2016 or v1.0 roadmap. Is there any?

### ISSUE THREAD

**Issue by rickmed** [tgriesser/knex#1478]

**Comment by rhys-vdw** [comment]
@tgriesser?

**Comment by rhys-vdw** [comment]
@rickmed The answer is no, presently. But I believe Tim might be working on something.

**Comment by tgriesser** [comment]
Yep been working on this, tentatively planning on sharing plans on what I've been working on around this early next week.

**Comment by tgriesser** [comment]
Haven't forgotten about this by the way, will be addressing with something soon

**Comment by tgriesser** [comment]
Took awhile but checkout https://github.com/tgriesser/knex/pull/1659 for the plan. Have gotten quite a bit of it done on a local fork, but I'm now planning on fixing thing incrementally on this branch since a big-bang rewrite will be difficult for upgrading
