### ISSUE TITLE
Returning ID after insert with sqlite using string primary key?

### ISSUE THREAD

**Issue by rapodaca** [tgriesser/knex#1479]
A sqlite3 table `foos` is defined with the knex (0.11.3) migration:

````javascript
exports.up = function (knex) {
  return knex.schema.createTable('foos', function (table) {
    table.string('id').primary();
  };
};
````

I'd like to get the primary key when I insert a new record. This works when using an integer primary key, but not string:

````javascript
db('foos').insert({ id: 'abc' }).then((ids) => {
  console.log('ids', ids); // prints [1], not ['abc'] as expected
});
````

Adding a `returning` clause does not change the return value.

In other words, rather than resolving to an array containing the IDs that were added, the insert statement apparently resolves to an array containing the number of created rows.

How can I have an insert resolve to an array containing string primary IDs?

**Comment by jurko-gospodnetic** [comment]
With Postgres you can use the `RETURNING` clause for this, accessible via knex's `.returning(...)` method. But I don't think sqlite3 supports such a clause and there I think you can not achieve the same effect directly.

However, if your code is sqlite3 specific, you could call its `last_insert_rowid()` function (possibly needs to be done using the same DB connection as used for the original INSERT, though I'm not certain of that) to get a similar effect. But that solution is completely out of scope for knex, unless knex decides to implement a sqlite3 specific method for accessing the `last_insert_rowid()` function.

**Comment by rapodaca** [comment]
Thanks for the ideas, but the main problem I see is undocumented inconsistent behavior.

Using an integer primary key gives the expected result (id returned after `insert`). Using a string primary key gives something else (row count returned after `insert`).

As I mentioned previously, `returning` did not change the outcome, which is consistent with the documentation that implies that this function does not work with sqlite:

> Utilized by PostgreSQL, MSSQL, and Oracle databases, the returning method specifies which column should be returned by the insert and update methods. 

http://knexjs.org/#Builder-returning

**Comment by elhigu** [comment]
@rapodaca Do you know if it is possible to implement the thing you are trying to do with sqlite3 database? Is there still something you need to get resolved for this issue? 

If you can specify what do you mean by "undocumented inconsistent behavior" and open new issue for that if there is need to update documentation.

**Comment by rapodaca** [comment]
@elhigu, I'm not sure. Poking around the sqlite documentation, I found references to `last_insert_rowid()`, but nothing about the expected return value of an insert.

"Undocumented inconsistent behavior" refers to getting back an [ID] after `insert` when the primary key type is integer, but [1] when the primary key type is  a string. From the `insert` documentation:

> // Returns [1] in "mysql", "sqlite", "oracle"; [] in "postgresql" unless the 'returning' parameter is set.
> knex('books').insert({title: 'Slaughterhouse Five'})

http://knexjs.org/#Builder-insert

My preference would be for the `insert` documentation to clarify this point, but I'm not even sure whether what I'm seeing is how things should work normally. So before that, I'd just like to get feedback as to whether what I'm seeing is expected behavior.

**Comment by elhigu** [comment]
@rapodaca I checked the code generated by knex and it doesn't do any magic for the insert return values. So it returns what ever sqlite3 driver returns. I'm closing this for now and this may be reopened if there is a bug. 

If there is need to update documentation, please open another issue for that and would be really helpful if you are able to verify  what exactly is returned.
