### ISSUE TITLE
SQL Azure connection?

### ISSUE THREAD

**Issue by jeffijoe** [tgriesser/knex#1480]
I am trying to connect to SQL Azure:

```
knex({
  client : 'mssql',
  connection: {
    server : 'myserver.database.windows.net',
    port: 1433,
    user : 'myuser',
    password : 'mypass',
    database : 'mydatabase',
    encrypt: true
  }
});
```

I am getting `Knex:Error Pool2 - Error: Timed out acquiring resource`

Is it not supported or am I doing something wrong?

**Comment by rhys-vdw** [comment]
@jeffijoe reported on gitter that `acquireRawConnection` is never being called. Could somebody using MSSQL investigate/fix?

**Comment by jeffijoe** [comment]
@rhys-vdw sorry, I realized I was adding my debug logs to `src` rather than `lib`, so it is called indeed.

**Comment by edzis** [comment]
@jeffijoe what was the issue? I am connecting to an Azure and get timeouts. Firewall rule is there.

**Comment by jeffijoe** [comment]
@edzis never got it working, sadly

**Comment by edzis** [comment]
@jeffijoe this worked for me:
```
knex({
  client : 'mssql',
  connection: {
    server : 'myserver.database.windows.net',
    user : 'myuser',
    password : 'mypass',
    options: {
        port: 1433,
        database : 'mydatabase',
        encrypt: true
    }
  }
});
```
Had to try out `tedious` directly and compare it to the config manipulations applied by `knex` and `mssql.

**Comment by jeffijoe** [comment]
Nice - not on the project anymore so cant try it out, but thanks for sharing!

**Comment by nev3rm0re** [comment]
@edzis Your example is slightly wrong, `database` should be outside of the `options`. If the user connecting is not permitted to access default database server will report "Login failed for user" message. Supplying correct database name as `connection.database` property resolves this error

**Comment by willmorgan** [comment]
`node-mssql` user/maintainer here.

Yes, you'll need to add `encrypt: true` under `options` otherwise it won't work on SQL Azure.

This can probably be closed.

**Comment by kibertoad** [comment]
@willmorgan I've started Recipes wiki for things like this, could you please review first entry of https://github.com/tgriesser/knex/wiki/Recipes for correctness?

**Comment by willmorgan** [comment]
@kibertoad Reviewed!

**Comment by kibertoad** [comment]
@willmorgan Thanks a lot!

**Comment by rkmunusamy** [comment]
> @jeffijoe this worked for me:
> 
> ```
> knex({
>   client : 'mssql',
>   connection: {
>     server : 'myserver.database.windows.net',
>     user : 'myuser',
>     password : 'mypass',
>     options: {
>         port: 1433,
>         database : 'mydatabase',
>         encrypt: true
>     }
>   }
> });
> ```
> 
> Had to try out `tedious` directly and compare it to the config manipulations applied by `knex` and `mssql.

Great @kibertoad
