### ISSUE TITLE
Knex calling the global console (use of console.log internally)

### ISSUE THREAD

**Issue by spaghetti-** [tgriesser/knex#1483]
While a very useful library, I see several uses of `console.log`, `console.error` etc internally, which I cannot catch without overriding the global object. Is there any way to specify my own logging mechanism within knex (for example: winston loggers)?

Please see specific examples [here](https://github.com/tgriesser/knex/blob/dfca38da339922f8ad8f52087ca5e6c0dcdab081/src/helpers.js#L25) and [here](https://github.com/tgriesser/knex/blob/dfca38da339922f8ad8f52087ca5e6c0dcdab081/src/helpers.js#L43).

**Comment by rhys-vdw** [comment]
Hm. So the two things you're pointing to are the query logger (enabled with `debug()`) and the 'exit' function which is called when you haven't installed the correct SQL library for your dialect. (I'm guessing you don't really need that second event.)

If you want to forwrad your query traces to a custom logger you could you could set [environment variable DEBUG](http://knexjs.org/#faq-debug) and then filter stdout for lines starting with `knex:`.

What are you trying to achieve?

**Comment by rhys-vdw** [comment]
@nixgadget has also asked after this feature in #1495. Sounds like a worthwhile feature.

Please use this thread to enumerate the kind of events you'd like to log. I don't expect this to be a big change.

**Comment by nixgadget** [comment]
Im mostly interested in the critical ones such as connection errors.

**Comment by nixgadget** [comment]
Or even better if you can implement a mechanism to inject a logger

**Comment by oiime** [comment]
Yeah, the most reasonable thing to do would be to inject an alternative logger when building a knex instance

eg:
`
const logger = require('bunyan').createLogger({})
const knex = Knex({client: 'x', connection: {}, logger: logger)
`

where logger defaults to console, if a logger is assigned I think the default behavior should be to log all events and let the logger figure out the log level. it'll be quite messy if it'll requires passing .debug(true) to every query. I can write a patch for that if you'd like.

**Comment by moll** [comment]
Stumbled upon the same issue that connection/pool errors are printed to the console at https://github.com/tgriesser/knex/blob/751ab2a4231bf4390ed128b314dc120589c34b7c/src/client.js#L161.

I personally don't think Knex should bother itself with logging at all, so I'd vote against any logger interface, and instead document where and how one should get to the errors if one wishes to send them to their own exception notifier, logger or do something different.

**Comment by moll** [comment]
As an workaround until the logging is removed:
```js
var knex = Knex({...})
knex.client.pool.removeAllListeners("error")
knex.client.pool.removeAllListeners("warn")
```

**Comment by avimar** [comment]
-Pool/connection error, e.g the entire DB goes down
-All debugging to my logger function, so that I can do what I want with it.

**Comment by tgriesser** [comment]
Yep, this is definitely something we should have configurable. I'm looking at adding some features in the coming weeks and I'll keep this in mind as I go through the priority list.

**Comment by msikma** [comment]
Sorry for making a duplicate issue. In case anyone is interested in a (partial?) workaround, I ended up doing this, which works for me:

```
knex.on('query', (query) => myCustomLogger(knex.raw(query.sql, query.bindings).toString()))
```

I'm not sure what else `debug:true` does, but I really just wanted to catch all queries that were being sent, and this allows me to do that.

**Comment by elhigu** [comment]
@msikma I'm also doing all query duration / transaction duration logging in these events. Also you can get even more detailed debug info to console by using environment variable `DEBUG=knex:*`

**Comment by ikari-pl** [comment]
@elhigu But the issue was to log them **not** to console, but to the custom logger. 
I am having the same issue with warnings and errors that Knex logged, but because I want to TCP-stream winston to a logging service, nothing that goes to console will be available in my log collectors. So, basically, if I can't force Knex to use *my* logger for *everything*, I'll never know things failed.

**Comment by msikma** [comment]
Yes, that's important. In my case it only logs the SQL queries. Knex should have an easy way to redirect all its output to a custom function, if you're going to run this in production.

**Comment by elhigu** [comment]
@ikari-pl I know. Discussion above was related to other issue which was closed as duplicate. This feature should still be implemented.

**Comment by Whoaa512** [comment]
Any news on when `Knex.setLogger` will be released?

**Comment by dbettini** [comment]
@tgriesser I see you made a commit which adds `setLogger`, will it be merged soon or is there something blocking it?

**Comment by DanrwAU** [comment]
Was this ever released and if not is it ever projected to be? 

Thanks!

**Comment by elhigu** [comment]
setting own loggers has been supported already maybe a year or so.

**Comment by elhigu** [comment]
https://knexjs.org/#Installation-log
