### ISSUE TITLE
Is Knex ready for production use?

### ISSUE THREAD

**Issue by RichardJECooke** [tgriesser/knex#1484]
I see Knex is not yet even version 1, but seems to have a lot of users.

Is it still unstable?  When will it be version 1?

**Comment by wubzz** [comment]
Personally using knex actively in production for 1 big application and several small-medium sized apps, and we rarely have any issues caused directly by the library itself.

Versioning 1+ for 'stable' was made a standard in npm long after knex had already been a module for a long time, so the current versioning may seem odd. A reference issue for this: #1331 . Knex has been around for around 3 years if I recall.
