### ISSUE TITLE
Build on docs site is broken

### ISSUE THREAD

**Issue by billyjanitsch** [tgriesser/knex#1487]
I just wanted to let you know that the build loaded on the docs site is currently broken due to the webpack error introduced in 1544fcd75f2353e92a06516c6b287c04532aae43 and fixed in 2fd63a7868a4d5f229d37cdd20f5816c9f442b7a. It would be great if you could cut a patch release and merge it into the `gh-pages` branch so that console tinkering (and query previews) work again.

<img width="350" alt="screen shot 2016-06-12 at 2 55 44 am" src="https://cloud.githubusercontent.com/assets/1158733/15989608/3c5b5566-3049-11e6-8d99-a2a750c6cdf0.png">

Thanks for your work on this library!

**Comment by elhigu** [comment]
This is already fixed in master. Will be updated in next release. Problem was webpack build failing, now we have test which checks that build is working when CI is ran, so this shouldnt happen again.
