### ISSUE TITLE
UUID and MD5 generated

### ISSUE THREAD

**Issue by anzileiro** [tgriesser/knex#1488]
how to generate a new uuid or md5 random to save on postgresql, for example:

<img width="743" alt="screen shot 2016-06-12 at 5 10 36 pm" src="https://cloud.githubusercontent.com/assets/3415671/15993581/e6ecadd2-30c0-11e6-8aca-4577ddba9de3.png">

But the 'knex.raw('uuid_generate_v4()')' does not work, I wonder how can I do to generate a random hash and save automatic when creating a new record?

and it also seems that uuid-v4 can not generate random because of migration that is static and unchanged for each request.

<img width="596" alt="screen shot 2016-06-12 at 5 23 16 pm" src="https://cloud.githubusercontent.com/assets/3415671/15993632/bf389aba-30c2-11e6-9555-ce4e011188ed.png">

Sorry I'm studying node due to own and my only help is google and github, I thank you for your help.

**Comment by elhigu** [comment]
What is the reason why 

> But the 'knex.raw('uuid_generate_v4()')'

Doesn't work? Does that work with postgrsql when you try to use it with plain sql wirhout knex? 

Try also running your code with DEBUG=knex:* evironment variable set to get more info whats going on with your queries.

**Comment by absolux** [comment]
@anzileiro, you should not use `uuis-v4` package in migrations, but in your models, for example before saving a new model, set its property `hash` to the value of `uuid()` and then save it

**Comment by fl0w** [comment]
You need to make sure the extension is available:
```js
knex.raw('create extension if not exists "uuid-ossp"')
```
then you can do
```js
t.string('hash').defaultTo(knex.raw('uuid_generate_v4()'))
```

**Comment by elhigu** [comment]
Thanks @fl0w, case closed ☺️

**Comment by rhazegh** [comment]
If you are using PostgreSQL 13 and want to use UUID V4, you no longer need to use `uuid-ossp` extension. 

So you could write:

```javascript
await knex.schema.createTable('Users', t => {
  t.uuid('id').defaultTo(knex.raw('gen_random_uuid()'));
  // ...
});
```

`gen_random_uuid()` function returns a version 4 (random) UUID.

**Comment by MatthewVaccaro** [comment]
@rhazegh Ayy thank you for this! The only thing you need to add is a `.unique()` if the table is going to be referenced elsewhere.

If you don't add the `.unique();` you'll end up getting this error like this.

> "There is no unique constraint matching given keys for referenced table < TABLE NAME >"

**Comment by robcresswell** [comment]
On the off chance anyone else stumbles across this thread, as of Knex `2.5.0` (08 July 2023) you can do

```javascript
await knex.schema.createTable('Users', (tableBuilder) => {
  tableBuilder.uuid('id').defaultTo(knex.fn.uuid());
  // ...
});
```

and you can add things like `primary()` for primary keys
