### ISSUE TITLE
columnInfo schema detection from table parameter

### ISSUE THREAD

**Issue by ghost** [tgriesser/knex#1490]
When using with Postgres, most Knex methods will correctly parse the schema name when building a query to the database like so: `knex('someSchema.myTable').select('someCol');`

However, the columnInfo method does not understand this and will instead return an empty object when the schema name is passed as a parameter with the table name to knex. That is,  `knex('someSchema.myTable').columnInfo()` does not work as expected and returns an empty object `{}`.

`knex('myTable').withSchema('someSchema').columnInfo()` does work, but it would be great if there was more consistency here.

**Comment by musicm122** [comment]
Thanks for posting. I've been stuck on this for the last hour or so.

**Comment by elhigu** [comment]
IMO identifier syntax is already ambiguous enough with table.column format, that using schema ref it shouldn't be allowed at all. 

If someone likes to make some feature request issue about this, where desired behaviour is well defined.
