### ISSUE TITLE
When the connection pool is at capacity

### ISSUE THREAD

**Issue by nmagerko** [tgriesser/knex#1492]
I was just wondering if there is a way to determine whether or not the connection pool for a `knex` instance is nearing/is at capacity. I have an application that varies a lot in how many connections it might have at any one time, and I was hoping to be able to explicitly create a few singular connections whenever the pool runs over capacity.

I saw a comment on a `bookshelf` issue [here](https://github.com/tgriesser/bookshelf/issues/175#issuecomment-32422348) saying that this would be a good feature to have, but I'm not sure if it was ever implemented.

Apologies if I missed it in the documentation! If it matters, I'm using `knex` with `bookshelf`.

**Comment by elhigu** [comment]
There is no official way to do this.

As a workaround if you can get hold of pool instance you could maybe add call to pool.stats() call to knex global `query` event or something like that to find out if you need more connections.

```
pool.stats();
/* {
    min: 0,
    max: 10,
    allocated: 0,
    available: 0,
    queued: 0,
    maxRequests: Infinity
} */
```

As far as I know you cannot change pool parameters dynamically, so those few extra connections would require initializing new knex instance with other pool I suppose.

I don't know your use case, but creating new connection if connection limit is reached doesn't sound like a good option. It is the database server which ultimately says how many connections it accepts and that limit cannot be changed in knex side.
