### ISSUE TITLE
Create database as a step of migration.

### ISSUE THREAD

**Issue by mbury** [tgriesser/knex#1497]
Is exists any way to run migration with not specify `database` parameter in`knexfile.js`? I want to create many databases as a step of migration and then load schema using `withSchema` but don't know how to do it. All examples use single database as schema builder target.

**Comment by vincent178** [comment]
＋1

**Comment by elhigu** [comment]
@mbury there is always some database that you connect (at least in postgresql), even when you connect to server to create more databases. 

So you should connect to e.g. db called template1 or postgres for the behavior that you are talking about. I suggest that you create one master db for your app to which you always connect initially.
