### ISSUE TITLE
Request: unique hash on query objects for logging

### ISSUE THREAD

**Issue by funnylookinhat** [tgriesser/knex#1502]
I'm trying to write a simple metrics tool to measure which queries are performing slowly so that I can evaluate my codebase over time.  As a simplified example:

```
var knex = require('knex')({myConfig});

var runningQueries = {};

knex.on('query', function (data) {
  // Generates a unique has using hash using keys like:
  // ['__knexUid', 'method', 'sql', 'bindings', 'options']
  var queryHash = generateHash(data);
  runningQueries[queryHash] = {
    sql: data.sql,
    start: Date.now()
  };
});

knex.on('query-response', function (response, obj, builder) {
  // This hash should match the one in the function above.
  var queryHash = generateHash(obj);
  var runTime = Date.now() - runningQueries[queryHash].start;
  // etc. etc.
  delete runningQueries[queryHash];
});
```

The problem I'm encountering is that multiple queries with the same properties will get jumbled together - and could potentially screw up my timings or cause me to miss queries.  It would be ideal if each query object had a unique hash attached to it (or the Date.now() timestamp it was created at) to identify them uniquely.

I can add the code, but before I submit a PR I'd like your input and to make sure I'm not wasting your time.  :)

**Comment by elhigu** [comment]
Hmm.. isn't __knexUid set for each connection and is unique in that way? Each connection can be running only one query at the time. 

So it should be always that when `query` event comes for certain __knexUid you can attach your own UUID for query in 'query' event and then when next `query-response` or `query-error` event comes you know that it came for the query which was executed last?

My implementation for timing queries was like this:

```js
'use strict';

var timers = {};

function showTime(timerId, opts) {
  var failed = opts && opts.failed;
  var precision = 3;
  var timer = timers[timerId];
  if (!timer) { 
    return; 
  }
  var elapsedHrtime = process.hrtime(timer.start);
  var elapsed = elapsedHrtime[1] / 1000000;
  var milliseconds = elapsedHrtime[0]*1000 + elapsed;
  if (milliseconds > opts.threshold) {
    console.log(failed ? "Slow query FAIL" : "Slow query SUCCESS", milliseconds.toFixed(precision) + " ms - " + timer.query);
  }
  delete timers[timerId];
}

module.exports = function (app, config) {
  app.knex().on('query', function (toSql) {
    var queryString = `${toSql.sql} ${JSON.stringify(toSql.bindings)}`;
    timers[toSql.__knexUid] = {
      start: process.hrtime(),
      query: queryString
    };
  });

  app.knex().on('query-error', function (err, toSql) {
    showTime(toSql.__knexUid, { failed: true, threshold: config.threshold });
  });

  app.knex().on('query-response', function (result, toSql) {
    showTime(toSql.__knexUid, { failed: false, threshold: config.threshold });
  });
};
```

But now that I think of it again maybe the best solution would be just to add uuid for query in 'query' event and attach it to query object. So something like this should work better:

```js
knex.on('query', function (toSql) {
  toSql.__queryUuid = my_favorite_uuid();
  // add uuid to bookkeeping with start time etc.
});

knex.on('query-error', function (err, toSql) {
  // get your unique hash from toSql.__queryUuid
});

knex.on('query-response', function (result, toSql) {
  // get your unique hash from toSql.__queryUuid
});
```

**Comment by funnylookinhat** [comment]
@elhigu Ah yes, I think your second solution is much more elegant, but I think that the data passed to the `query` event is cloned - so trying to add an attribute to it doesn't show up in the `query-response`.

I didn't know that only one unique query per `__knexUid` could be set at a time - so maybe I will pursue something like your first solution.  I still think that it's a valid feature request to add a uuid to each `toSql` for the sake of those events.

**Comment by funnylookinhat** [comment]
After a bit of grepping through the source, it looks like I could add that unique ID here:
https://github.com/tgriesser/knex/blob/master/src/query/compiler.js#L43

So it would be pretty straightforward.  I'm just not sure if anyone else would find it useful - I think it would make debugging much easier.

**Comment by elhigu** [comment]
I'm not confident that uuid generated in `toSQL` will remain the same between `query` and `query-response` events if there is no additional cloning code added somewhere.

I would rather figure out why stuff stored in `query`event doesn't show up in `query-response` that sounds strange. 

Anyways to me having uuid created in `toSQL` is not a problem, I don't see it hurting anyone there.

**Comment by funnylookinhat** [comment]
@elhigu Yeah, you are correct - shoving it into `toSQL` did not work.

However, I've confirmed that you can have multiple duplicate queries per `__knexUid` at once - so hashing based on that and the other parameters isn't a sufficient solution.

**Comment by wubzz** [comment]
You'd also need to add it [here](https://github.com/tgriesser/knex/blob/master/src/raw.js#L62) so that Raw queries are treated the same.

It does indeed sound weird if `query` and `query-response` do not have the same `__knexUid` given the code [here](https://github.com/tgriesser/knex/blob/master/src/runner.js#L121). It's picked up from the same connection in both emits.

**Comment by funnylookinhat** [comment]
@wubzz Oh - they do have the same `__knexUid` - the problem is that the same `__knexUid` can have multiple identical queries at once - which means hashing them uniquely with the data passed to `query` and `query-response` is impossible.

I've got code that is tested and working for both the query builder and raw queries.  Thanks for the suggestion on the Raw query placement!

https://github.com/tgriesser/knex/compare/master...funnylookinhat:query-uuid?expand=1

Should I open a PR?

**Comment by wubzz** [comment]
@funnylookinhat Ah, yes, since the knexUid comes from the connection and not the query, they would be the same if the same connection was used for both queries.

I'm agreeing with @elhigu there's no harm in adding this, so go for it! I'd recommend something more definitive instead of just `uuid` tho, such as `__knexQueryId` or something, but that's just me being picky.

**Comment by funnylookinhat** [comment]
@wubzz That's a good idea.  I've gone ahead and updated it to `__knexQueryUid` to fit the `__knexUid` pattern.

**Comment by E-Kuerschner** [comment]
I've noticed that some queries don't receive a __knexQueryUid. Any idea why that might be? It appears that anything using the `schema` api is missing this, for example:

```typescript
await connection.schema.dropTableIfExists(tableName)
```
this type of code is resulting in query event data looking like:
```
{
  __knexUid: '__knexUid3',
  __knexTxId: undefined,
  sql: "if object_id('***', 'U') is not null DROP TABLE ***",
  bindings: []
}
```
