### ISSUE TITLE
query where('field', '=', null) does return anything

### ISSUE THREAD

**Issue by capaj** [tgriesser/knex#1507]
My coworker @thunderball1 stumbled upon this problem, where calling where method like this:

```
where('field', '=', null)
```

doesn't return any results, even though the DB has such fields.

This works as expected:
```
where('field', null)
```

**Comment by elhigu** [comment]
For example with postgres you should do null comparison with 'IS' operator instead of equality '='.

**Comment by capaj** [comment]
@elhigu thanks, I always preferred '=', not sure why

**Comment by kerolosFawzy** [comment]
there method called whereNull use it instead
