### ISSUE TITLE
How to perform multiple where conditions using knex ? 

### ISSUE THREAD

**Issue by monera23** [tgriesser/knex#1508]
The query is something like this 

select id from table 
where id1 = 2 and 
where id3 in array and 
where id4 in array1
from table ;

Here array and array1 are the arrays in which I have to look for using IN. How to write the knex equivalent of it ?  I have written something like this 

Bookshelf.knex
		 		.select('id')
		 		.from('table')
		 		.where('table.id1',2)
		 		.whereIn('table.id2',array)
				.whereIn('table.id3',array3)
                                .then()

**Comment by sombriks** [comment]
Hello, you'll need to pass a callback to query your array if you doesn't have it: http://knexjs.org/#Builder-whereIn

see the subquery approach.
