### ISSUE TITLE
hasTable() doesn't resolve with a boolean

### ISSUE THREAD

**Issue by absolux** [tgriesser/knex#1509]
Hi, I am using knex schema builder to create the database tables

``` js
// create categories table
db.hasTable('categories').then(function (exists) {
  debug(exists)
  if ( exists ) return

  return db.createTable('categories', function (table) {
    table.increments('id')
    table.string('name').notNullable()
    table.string('slug').notNullable().index()
  })
}).then(function () { debug("Table `categories` created") })

// create tags table
db.hasTable('tags').then(function (exists) {
  debug(exists)
  if ( exists ) return

  return db.createTable('tags', function (table) {
    table.increments('id')
    table.string('name').notNullable()
    table.string('slug').notNullable().index()
  })
}).then(function () { debug("Table `tags` created") })
```

after debugging, `exists` is an array instead of a boolean, below the output of the console

```
database [ true, false ] +0ms      <= 
database [ true, false ] +4ms
database Table `categories` created +2ms
database Table `tags` created +0ms
```

true means that the table categories already exist, tags does not.

**Comment by tgriesser** [comment]
Hmm, that sounds like a bug.

**Comment by jurko-gospodnetic** [comment]
Well if it's an array when the table already exists and something falsy otherwise, then I'd not exactly consider it a bug, as the truthy/falsy value check still works correctly.

**Comment by tgriesser** [comment]
Yes, but if that's the case it's both not the documented behavior and is indicating something else has changed we're not testing for.

**Comment by jurko-gospodnetic** [comment]
Ok, just tested this with Postgres, and it does not seem to be the case.

My test code:

```
function testTable(tableName) {
    return knex.schema.hasTable(tableName)
        .then(function (res) {
            console.log('zzz: result:', res);
        })
        .catch(function (err) {
            console.log('zzz: error:', err);
        })
    ;
}

it('xxx - table does not exist', function () {
    return testTable('rumpelstiltskin');
});

it('xxx - table exists', function () {
    return testTable('programItem');
});
```

with `knex` connected to a Postgres 9.4 database containing a `programItem` database table and not containing a `rumpelstiltskin` one.

The output was as expected:

```
zzz: result: false
    ✓ xxx - table does not exist
zzz: result: true
    ✓ xxx - table exists

  2 passing (1s)
```

So we're missing some details here. Is this perhaps a database type specific issue?

**Comment by absolux** [comment]
@tgriesser, for information, I am using MySQL 5.5.47 and I'm not using migrations.

@jurko-gospodnetic, if you chain more than one call to `hasTable`, all promises will resolve with an array of booleans instead of a simple boolean. 

Also `exists` parameter is always truthy, and the creation of tables is skipped

**Comment by gimenete** [comment]
I'm having the same problem with `hasTable` and `hasColumn`. I'm using PostgreSQL. 9.6.2 and knex 0.12.7

```javascript
  schema.hasTable('auth_users')
    .then(result => console.log(result))
    .then(() => schema.hasColumn('auth_users', 'name'))
    .then(result => console.log(result))
```

prints

```
true
[true, false]
```

My workaround is using a function like this:

```javascript
  const last = result => Array.isArray(result) ? result[result.length - 1] : result

  return schema.hasTable('auth_users')
    .then(last)
    .then(result => console.log(result))
    .then(() => schema.hasColumn('auth_users', 'name'))
    .then(last)
    .then(result => console.log(result))
```

Now the output is:

```
true
false
```

Which is what I was expecting.

**Comment by wubzz** [comment]
I'm pretty sure this is caused by reusing the `schema` reference rather than instantianting a new reference each time.

For example this:
```javascript
const schema = knex.schema;

return schema.hasTable('test') //Runs hasTable test
.then(console.log)// true
.then(() => schema.hasTable('test2')) //Runs hasTable test AND hasTable test2
.then(console.log); //[true, false] -- Since two queries run
```

The schema reference is still just a query builder. So everytime `.then` is called, it will run the queries from the builder chain.

Doing this should solve the 'strangeness':

```javascript
return knex.schema.hasTable('test') //Runs hasTable test
.then(console.log)// true
.then(() => knex.schema.hasTable('test2')) //Runs hasTable test2
.then(console.log); //false
```

Or even better:

```javascript
const schema = knex.schema;

return schema.hasTable('test')
.then(() => schema.hasTable('test2'))
.spread((hasTableTest, hasTableTest2) => {...})
```

I wouldn't consider this a bug. @elhigu What do you think?

**Comment by elhigu** [comment]
@wubzz I think that the schema API is really misleading in this case, but you are probably right about the reason.

I would like to see it behaving differently that hasTable wouldn't store the calls to the builder because hasTable is used just to check how the DB looks like and is not really adding anything to schema.

**Comment by gimenete** [comment]
Thanks @wubzz Not reusing `schema` worked for me :) Now I always get booleans and not arrays.

**Comment by absolux** [comment]
Closing this.
Thanks @wubzz

**Comment by piranna** [comment]
I stumbled with the same issue during the last 2 hours, I find It good as an optimización but should be shown in the docs. Better, has two methods, hasTable() that always returns a Booleana, and hasTables() that always returns an Array of Booleana
