### ISSUE TITLE
"Show example query" functionality not working on docs page

### ISSUE THREAD

**Issue by robertd** [tgriesser/knex#1511]
I noticed that "Show example query" is not working in docs page

Chrome console looks like this:
```
transaction.js:48 Uncaught Error: Cannot find module "../index"
(index):3896 Uncaught ReferenceError: Knex is not defined
```

**Comment by robertd** [comment]
Possibly same issue that's causing #1518

**Comment by elhigu** [comment]
I cannot reproduce this one... I'm getting different kind of exceptions. @robertd could you give me some steps how to reproduce this particular error? I'm also using Chrome.

**Comment by robertd** [comment]
Hmm... It started working again... I was getting following errors on Friday
```
transaction.js:48 Uncaught Error: Cannot find module "../index"
(index):3896 Uncaught ReferenceError: Knex is not defined
```

Closing...
