### ISSUE TITLE
How to orderBy a collection according to a column ? 

### ISSUE THREAD

**Issue by monera23** [tgriesser/knex#1514]
I have a collection projects that I want to order by according to the number of likes in desc order ? Any way to do it. I am using _.orderBy but it is not giving the correct output. This is the current code I am using. 

_.orderBy(proj_coll, [function (proj) {
                 proj.get('likes');
            }], ['asc']);

**Comment by elhigu** [comment]
This question has nothing that is specific to knex. Check lodash documentation or try StackOverflow.
