### ISSUE TITLE
schema.table does not trigger its callback

### ISSUE THREAD

**Issue by timwis** [tgriesser/knex#1517]
There appears to be an issue with `knex.schema.table` where the callback is not being called. Per [the documentation](http://knexjs.org/#Schema-table), I've written up a test case:

```javascript
const knex = require('knex')({})

console.log('accessing table')
knex.schema.table('users', function (table) {
  console.log('inside') // this is never called
})
```
As a result, the [schema building](http://knexjs.org/#Schema-Building) methods are not possible. Here's a [demonstration](http://requirebin.com/?gist=1836fab2947ca656ccfafc2937700023) - open your console to see the results.

**Comment by wubzz** [comment]
@timwis You need to call either `.toString()`, `.toSQL()`, `.then(fn)` or `.asCallback(callback)` to trigger the compiler.

Knex won't start compiling until one of these functions are called, because you're still using the knex API to build up a query/procedure.

**Comment by timwis** [comment]
Oh, wow.. thanks @wubzz. Do you think it would be helpful for the documentation to mention that? The [example for `.table`](http://knexjs.org/#Schema-table) says "Outputs" underneath it as if the code listed there actually outputs that.

If so, I'm happy to submit a PR for it.
