### ISSUE TITLE
Properly unit testing the failure

### ISSUE THREAD

**Issue by Caligone** [tgriesser/knex#1519]
I am trying to test my catch handler in a piece of code :
```js
class User {
  actionsOnDB () {
    this.knex('users')
      .create()
      .then( () => {
        console.log('Done');
      })
      .catch( (err) => {
        console.log('Error');
      })
  }
}
```

I am using Sinon with something like :
```js
Sinon.stub(user.knex, 'create').returns(Promise.reject('Test Error'));
```

But I never get into my `catch`.

Is there a proper way to test that kind of things?
Thanks

**Comment by afgallo** [comment]
@Caligone I've got the same problem and was wondering if you ever resolved it? Not sure how to test the catch statement either ...

**Comment by Caligone** [comment]
@afgallo Sorry, I don't

**Comment by afgallo** [comment]
@Caligone I actually got that to work:

`const stub = Sinon.stub(User, 'fetchAll').returns(Promise.reject(new Error()));`

Not sure why the "create" function can't be stubbed. @tgriesser could you shed some light?

**Comment by tgriesser** [comment]
`create` isn't a knex method, not sure what you're trying to stub here

**Comment by afgallo** [comment]
Thanks @tgriesser, this should answer @Caligone's question.
