### ISSUE TITLE
TypeError: Converting Circular structure to JSON

### ISSUE THREAD

**Issue by eslachance** [tgriesser/knex#1523]
So I'm attempting to delete a row inside my psql database, a very simple structure with 4 rows + the auto ID: 

```sql
CREATE TABLE public.tags
(
  id bigint NOT NULL DEFAULT nextval('tags_id_seq'::regclass),
  tag character varying(32) NOT NULL,
  description character varying(256) NOT NULL,
  server character(18) NOT NULL,
  added_by character(18) NOT NULL,
  CONSTRAINT tags_pkey PRIMARY KEY (id)
)
```

Attempting to reproduce the `.del()` example, I have the following code:  `knex('tags').where('tag', 'test').del();`

I get the following error output to me: `TypeError: Converting circular structure to JSON`

I'm unsure what could cause this, and how to resolve it. Any ideas?

**Comment by elhigu** [comment]
Which knex version are you using? I'm not able to reproduce your problem.

```js
knex = require('knex')({client: 'pg'})
knex('tags').where('tag', 'test').del().toSQL()
{ method: 'del',
  options: {},
  timeout: false,
  bindings: [ 'test' ],
  sql: 'delete from "tags" where "tag" = ?',
  returning: undefined }
```

I don't see any reason why that would throw json circular dependency problem. Can you provide more complete example how to reproduce?

**Comment by eslachance** [comment]
I've tried this on 3 different systems with the same results: 

System 1: c9.io node.js instance (Dev environment)

- node 4.4.7
- PostgreSQL 9.3
- knex@0.11.7

System 2: Windows 10

- node 4.2.6
- PostgreSQL 9.5
- knex@0.11.7

System 3: OVH VPS

- Ubuntu Server 16.04
- node 6.2.1
- PostgreSQL 9.5.3
- knex@0.11.5

The only "oddity" I can find, really, is that my "other" queries work fine and when I turn on debug, I can see them all output in my console.... but specifically this command, when I run it, does not. I normally run this through eval()  (don't hate me - this is a bot on Discord with no console per se) and what I get returned is the error I mention. Adding on .toSQL() to the end returns exactly this (it's stringified, for output to chat): 

`{"method":"del","options":{},"timeout":false,"bindings":["test"],"sql":"delete from \"tags\" where \"tag\" = ?"}`

When I just put the command in my main script, along with the rest of the commands that work, I still get nothing. No output (assuming this is because of circular reference?).

My connection string in all cases (It's all the same code, really): 
```js
{
	  "client": "pg",
	  "debug": true,
	  "connection": {
	    "host"     : "localhost",
	    "user"     : "ubuntu",
	    "password" : "mypassword",
	    "database" : "omnic",
	    "charset"  : "utf8"
	  }
	}
```

The database literally has 3 tables (and their sequences), nothing else, and they're all 100% fresh installs of pgsql used only for this project. 

The output of `select * from tags;` on psql console is: 
```
 id |  tag  |                description                |       server       |      added_by      
----+-------+-------------------------------------------+--------------------+--------------------
  1 | test  | "This is the contents of the tag 'test'." | 185776869398806529 | 139412744439988224
  3 | new   | this is a new tag                         | 185776869398806529 | 139412744439988224
  4 | new2  | still a new tag                           | 185776869398806529 | 139412744439988224
  5 | bleh  | hahhaha fuck                              | 185776869398806529 | 186267615566495744
  6 | blah2 | blablabla                                 | 185776869398806529 | 186267615566495744
```

To prevent *any* interference from any of my code, I used the following script, exactly, all alone with nothing else (and the rest was shutdown): 
```
const knex = require('knex')({
	  "client": "pg",
	  "debug": true,
	  "connection": {
	    "host"     : "localhost",
	    "user"     : "ubuntu",
	    "password" : "mypassword",
	    "database" : "omnic",
	    "charset"  : "utf8"
	  }
	});
knex('tags').where('tag', 'test').del();
```

Console outputs nothing. 

If I need to, I will share my c9.io workbench, so you can troubleshoot this. It's just as mysterious to me, I have no idea what else I can try.

**Comment by tgriesser** [comment]
So this is what I'm guessing might be a similar problem to #1522, the async behavior isn't kicked off unless the query is executed w/ `then` or similar. 

If you put `.then()` on the end of the `.del()` it will executed the promise:

```js
knex('tags').where('tag', 'test').del().then(data => {
  console.log(data)
}).catch(e => {
  console.error(e)
});
```

The `TypeError: Converting circular structure to JSON` shows up when you trying to `JSON.stringify` something which has a reference to itsself, which is probably happening when `JSON.stringify` a query building chain that hasn't been executed, rather than its return result from the promise or callback.

**Comment by eslachance** [comment]
I'd say that is most definitely something that should be made 100% obvious. It's true that all my other queries actually have a callback, but I didn't need it in this case, it wasn't in the documentation examples, and even elhigu didn't seem to have this issue... unless he just added on the .then() automatically and never thought about it? Hey I get the feeling. 

Well, this actually worked, so mystery solved! Hopefully you guys can document this quickly somewhere :P

**Comment by elhigu** [comment]
@eslachance I didn't have that issue, because I didn't ran the query, just checked what kind of SQL generates from it. 

I still have no idea where in the code you are trying to convert object with circular dependencies to json string :) Great that you got your problem solved!

Functionality how queries are triggered is described in:

http://knexjs.org/#Builder
http://knexjs.org/#Interfaces-Promises
http://knexjs.org/#Interfaces-Callbacks
http://knexjs.org/#Interfaces-Streams

pull requests to improve documentation are always welcome!
