### ISSUE TITLE
Cannot insert 'point' values to Postgres

### ISSUE THREAD

**Issue by edgy360** [tgriesser/knex#1525]
I have a database in Postgres, and one of the columns is of type `point`. In an SQL query, I would write `point(1.23456, 1.23456)`, however if I do the same in Knex it will be escaped (for good reason).

Would it be possible to support inserting `point` values?

I am using the latest version of Node, Knex and pg.

**Comment by wubzz** [comment]
In conjunction with `insert` you would probably have to use something like

```javascript
var data = {
somecolumn: 'somevalue',
point: knex.raw('point(1.23456, 1.23456)')
};
knex(table).insert(data).then(...)
```

**Comment by edgy360** [comment]
Thanks, I didn't realise that `knex.raw` could be used with values. I was originally thinking that I could only use either `.insert` or `.raw`.
