### ISSUE TITLE
DefaultTo postgres functions

### ISSUE THREAD

**Issue by avinoth** [tgriesser/knex#1533]
Is there a way to set a `defaultTo` to a column a postgresql function? For example If I want to have an uuid column auto generate using `uuid_generate_v4()`.

 I'm currently running this as a separate migration setting the default using raw sql. Is there any way to do it as part of the migration itself?

For example

```
t.uuid('transact_id').defaultTo(default.uuid_generate_v4());
```

**Comment by rhys-vdw** [comment]
Have you tried:

```js
t.uuid('transact_id').defaultTo(knex.raw('uuid_generate_v4()');
```

**Comment by elhigu** [comment]
This could be added to FAQ maybe... at least #146 #158 #271 and #643 issues has been asking effectively the same thing.

**Comment by avinoth** [comment]
@rhys-vdw Thanks. As @elhigu suggested, might make sense to add it to the docs. Wasn't obvious at first.

**Comment by paulbjensen** [comment]
Note to add, for Postgres 9 and greater, you will need to run this SQL on the database to enable using uuid_generate_v4() functions:

```sql
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
```

This resolves an issue where running a migration on a PostgreSQL DB errors on a message like "function uuid_generate_v4() does not exist".

**Comment by wubzz** [comment]
Closing, created https://github.com/knex/documentation/issues/84
