### ISSUE TITLE
How to do an update on a model using join ? 

### ISSUE THREAD

**Issue by monera23** [tgriesser/knex#1534]
I have 2 tables A,B now I want to update the fields in A having some relation in a filed of table B. 
Does knex support update on join ? The database is postgres. The query is something like this: 

UPDATE A AS a
SET a.price = true
FROM B AS b
WHERE a.id = b.id ;

**Comment by avinoth** [comment]
You could use the query using `knex.raw` 

http://knexjs.org/#Raw-Queries

**Comment by monera23** [comment]
Any option other than that ?

**Comment by elhigu** [comment]
`.update` and `.join` doesn't seem to work well together. I would recommend using subquery instead... Maybe this is what you are trying to do?

```js
knex('A').update({price: true}).whereIn('id', function () { this.select('id').from('B'); });
```

**Comment by monera23** [comment]
Thanks it helped. :)

**Comment by aadilraza339** [comment]
This is how you can use the join with the update method in knex.
```
knex("organizationCardDetail AS orgCard")
				.update("orgCard.isCardDefault",0)
				.join('productscard AS prodCard','prodCard.cardId','=','orgCard.cardId')
				.where({"prodCard.organizationId":organizationId,"prodCard.productId":productId})``
```

**Comment by joelanman** [comment]
@aadilraza339 I'm confused, given #2796, are you sure your solution works?

**Comment by FKPSC** [comment]
> This is how you can use the join with the update method in knex.
> 
> ```
> knex("organizationCardDetail AS orgCard")
> .update("orgCard.isCardDefault",0)
> .join('productscard AS prodCard','prodCard.cardId','=','orgCard.cardId')
> .where({"prodCard.organizationId":organizationId,"prodCard.productId":productId})``
> ```

If you check the generated query, the additional table from the joins are completely missing.
