### ISSUE TITLE
Styling issue with method docs

### ISSUE THREAD

**Issue by jmm** [tgriesser/knex#1535]
Looks like https://github.com/tgriesser/knex/pull/1504 also resulted in some weird styling of the method name / signature documentation. Pretty sure it used to be styled something like:

**del / delete**&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.del()  

And now it's like:

**del / delete**.del() 

Should probably apply / reference a class name for one or both kinds of code content to style each appropriately.

**Comment by tgriesser** [comment]
Fixed in https://github.com/knex/documentation

**Comment by jmm** [comment]
@tgriesser Awesome, thanks! FYI, I noticed that for methods with an alias (like `del|delete`) there are invalid (space-containing) `id` attr vals in the output, making for broken links.
