### ISSUE TITLE
How do I use knex.raw() with  `where in`

### ISSUE THREAD

**Issue by rogerschlachter** [tgriesser/knex#1537]
This may be a silly, easy question but I've been poking around and haven't been able to find the answer. 
I have this query with a sub query

``` js
    return knex.raw(`
                update gps_message gm
                set status = 'PROCESSING'
                from (
                    select id
                    from gps_message
                    where status = 'MATCHED'
                    order by id
                    limit ?
                    ) sub
                where gm.id = sub.id
                returning *
            `, [limit])
```

But when I try to add in the `and id in (?)` like this, 

``` js
    return knex.raw(`
                update gps_message gm
                set status = 'PROCESSING'
                from (
                    select id
                    from gps_message
                    where status = 'MATCHED'
                                        and id in (?)
                    order by id
                    limit ?
                    ) sub
                where gm.id = sub.id
                returning *
            `, [[1,2,3],limit])
```

I get this
`invalid input syntax for integer: "{"1","2","3"}"`

Am I missing something here?

**Comment by emertechie** [comment]
Running into similar issue. Did you ever find a solution @rogerschlachter ?

**Comment by elhigu** [comment]
This seems to work... I suppose this is one more case of undefined behaviour which might change in future:

```js
> knex.raw(`select 1 where id in (??) order by id limit ? )`, [[1,2,3],1]).toSQL()

{ method: 'raw',
  sql: 'select 1 where id in (1, 2, 3) order by id limit ? )',
  bindings: [ '1' ],
  options: {},
  __knexQueryUid: '0634182d-0282-401d-9da0-83b0fb7547d8' }
```

**Comment by chrisbroome** [comment]
The original raw query works as it should for the other drivers: `mysql`, `sqlite`, `oracle`, `mssql`. This is definitely a `pg`-specific issue. It's also converting numbers to strings - which doesn't happen in the other drivers. So `limit 10` ends up being `limit '10'` (see #1001).

If the inner query is built using knex, it mostly works - again with the caveat that numbers are turned into strings. Here's a quick demo of each along with the output:

``` JavaScript
const limit = 10;

const raw = knex.raw(`update gps_message gm
set status = 'PROCESSING'
from (
    select id
      from gps_message
     where status = 'MATCHED'
       and id in (?)
  order by id
     limit ?
  ) sub
where gm.id = sub.id
returning *
`, [[1,2,3],limit]);

console.log('--raw:\n', raw.toString());

const inner = knex.from('gps_message')
  .where('status', 'MATCHED')
  .whereIn('id', [1, 2, 3])
  .orderBy('id')
  .limit(limit);

console.log('--inner:\n', inner.toString());
console.log();

const rawWithInner = knex.raw(`update gps_message gm
set status = 'PROCESSING'
from (?) sub
where gm.id = sub.id
returning *
`, [knex.raw(inner.toString())]);

console.log('--rawWithInner:\n', rawWithInner.toString());
```

And the output:

``` SQL
--raw:
 update gps_message gm
set status = 'PROCESSING'
from (
    select id
      from gps_message
     where status = 'MATCHED'
       and id in ('{"1","2","3"}')
  order by id
     limit '10'
  ) sub
where gm.id = sub.id
returning *

--inner:
 select * from "gps_message" where "status" = 'MATCHED' and "id" in ('1', '2', '3') order by "id" asc limit '10'

--rawWithInner:
 update gps_message gm
set status = 'PROCESSING'
from (select * from "gps_message" where "status" = 'MATCHED' and "id" in ('1', '2', '3') order by "id" asc limit '10') sub
where gm.id = sub.id
returning *
```

**Comment by rickyk586** [comment]
In the meantime, you can use ANY() instead:

> knex.raw(`select 1 where id = ANY(?)`, [[1, 2, 3, 'strings too']])

in many cases they are equivalent:
http://stackoverflow.com/questions/30263671/postgresql-in-vs-any
http://stackoverflow.com/questions/34627026/in-vs-any-operator-in-postgresql

**Comment by jahudka** [comment]
I think that first and foremost stuff should be consistent - `WHERE foo IN (?)` should be expanded the same way no matter what platform is used. Arrays aren't a basic datatype supported by all platforms - they're a specific feature of Postgres - so if you end up needing the user to inform knex of their intention when an array is passed, the default behaviour should be the one that works on all platforms, and the user should wrap the array using something like `knex.array(foo)` when they want to use the array _type_.

**Comment by elhigu** [comment]
I'll close this as current state how this is supported is already answered. Next thing would be to open proper feature request for extending `?` parameter expansion to support arrays better, with API proposal and  investigation what kind of support is necessary for different databases.

@jahudka default could probably be just comma separated list without parenthesis like one that could work with `where in (?)`... but I'm not sure if even that is valid for every dialect so it could be even dialect specific as long as it just works. Anyways as I said, proper feature request would be next step for implementing this.

**Comment by xiyoung** [comment]
this is my solution 

`const queryAll = _db
      .table('group_org_device')
      .leftJoin('group_org', function() {
        this.on('group_org.org_id_str', 'group_org_device.org_id_str').on(
          'group_org.ldap_id',
          'group_org_device.ldap_id'
        );
      })
      .select('group_org_device.device_mark')
    if(!toAll) {
      queryAll.whereRaw('group_org.group_id in (' + allGroupIds.map(_ => '?').join(',') + ')', [...allGroupIds])
    }`

**Comment by xiyoung** [comment]
this is my solution
`
const queryAll = _db .table('group_org_device') .leftJoin('group_org', function() { 
  this.on(
  'group_org.org_id_str', 'group_org_device.org_id_str').on( 
  'group_org.ldap_id', 
  'group_org_device.ldap_id' ); 
}) .select('group_org_device.device_mark') if(!toAll) { queryAll.whereRaw('group_org.group_id in (' + allGroupIds.map(_ => '?').join(',') + ')', [...allGroupIds]) }
`

**Comment by laratutodotcom** [comment]
[solved] --->https://laratuto.com/i-get-the-query-builder-to-output-in-raw-as-string/
