### ISSUE TITLE
Knex can't stay connected to MySQL database

### ISSUE THREAD

**Issue by tgmcguire** [tgriesser/knex#1539]
When I open a simple MySQL connection (using `mysql`, not `mysql2`) using Knex, it seems to drop the connection after a minute or so of inactivity. Attempts to keep the connection alive are fruitless, and I've tried several combinations of pooling configurations (including having pooling turned off altogether) with no results. I can replicate this on two separate MySQL remote DBs – one hosted at ClearDB and the other on a vanilla HostGator package – but they both have the same behavior.

On the other hand, when I use the `mysql` Node package, I can do virtually the same thing virtually infinitely with no errors.

**Using `knex`:**

```javascript
var local = require('knex')({
    client: 'mysql',
    connection: config.db, // connection string
    debug: true
});

setInterval(function () {
    console.log("PING");
    local.raw('SELECT 1').then(function() {
        console.log("pong");
    });
}, 3000);
```

**Result:**

```
PING
pong
PING
pong
[for what appears to be ~60 seconds]

events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: Connection lost: The server closed the connection.
    at Protocol.end ([trimmed]/node_modules/mysql/lib/protocol/Protocol.js:109:13)
    at Socket.<anonymous> ([trimmed]/node_modules/mysql/lib/Connection.js:102:28)
    at emitNone (events.js:72:20)
    at Socket.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:903:12)
    at doNTCallback2 (node.js:439:9)
    at process._tickDomainCallback (node.js:394:17)
```

------

**Using `mysql` alone:**

```javascript
var mysql = require('mysql');

var cnx = mysql.createConnection(config.db);

cnx.connect();

setInterval(function(){
    // off-the-shelf example code from mysql's readme
    cnx.query('SELECT 1 + 1 AS solution', function(err, rows, fields) {
      if (err) throw err;
     
      console.log('The solution is: ', rows[0].solution);
    });
},3000);
```

------

In a perfect world I wouldn't have to ping a connection every three seconds, but this should communicate my point. ;) Again, the `mysql` example runs seemingly infinitely, with no errors, no crashing, and no connection loss.

Am I doing something silly here, with the `knex` version of this, or is this a real problem? Any help is appreciated. Thanks!

**Comment by elhigu** [comment]
Could you run knex code with environment variable DEBUG=knex:* to see if it shows something interesting?

I just tried your code against locally installed mariadb running default configuration, but it doesn't seem to be cutting the connection. 

Also you shouldn't need to ping connection manually, knex should do it automatically when pool is checking if the connection is still alive.

**Comment by tgmcguire** [comment]
Thanks for the insight on the `debug` environment variable, and for looking into this. I have another process running in the same script that exports the database on occasion, and I think that was somehow interfering with knex – when I remove that process from my script, the server maintains connection. My apologies!

Thanks again!
