### ISSUE TITLE
Can we use postgres array with knex ? 

### ISSUE THREAD

**Issue by monera23** [tgriesser/knex#1540]
I want a column that stores an array as value. Now I would need 2 things to be done -
1) Insert query using knex.
2) Update any row with  array column using knex,

Also is there any support with bookshelf.js, for these 2 things ?

**Comment by elhigu** [comment]
Seems to be duplicate https://github.com/tgriesser/knex/issues/879 and https://github.com/tgriesser/knex/issues/569
