### ISSUE TITLE
How to catch connection errors?

### ISSUE THREAD

**Issue by timwis** [tgriesser/knex#1542]
Hey folks, I can’t seem to catch connection errors so I can display an error message to the user. When I initialize knex, if my DB is down, for example, I get an uncaught exception. try … catch doesn’t work, and knex({client…}) doesn’t have a catch method. Any ideas?

**Comment by absolux** [comment]
Have you tried with the event `query-error` see [here](http://knexjs.org/#Events-query-error)

**Comment by timwis** [comment]
Perhaps there's a way to test the resulting client to see if it's connected? ie:

```javascript
const knex = require('knex')({client: 'pg', connection: ...})
if (!knex.pool) throw new Error('Not connected')
```

Any advice?

**Comment by timwis** [comment]
The error is being thrown from [client.js](https://github.com/tgriesser/knex/blob/27d828273dd6a96b0a6b5b669ad02d0ec9825fd3/src/client.js#L164-L169) `helpers.warn` and `helpers.error`

**Comment by timwis** [comment]
@slathrop suggested calling `EventEmitter` at the same location where the console message is logged, though I don't imagine I'd be able to listen to that event, because I'd have to use:

```javascript
const knex = require('knex')({client: 'pg', connection ...}).on('connection-error', ...)
```
In this case, the Event Emitter is called _before_ the listener is attached.

Alternatively, an `Error()` could be thrown, but then I think that would make [these tests fail](https://github.com/tgriesser/knex/blob/master/test/tape/knex.js).

I'm happy to put the work into a PR, but I could really use a direction if anyone has a moment.

**Comment by tgriesser** [comment]
Connection errors should be handled a bit nicer in 0.12. Connection errors on valid connections (timeouts, etc) should automatically lead to the removal of the resource from the pool, and the error from being unable to connect to a DB at all should be reflected by rejecting the calling promise. Let me know if you're still having issues

**Comment by jerrychong25** [comment]
> Perhaps there's a way to test the resulting client to see if it's connected? ie:
> 
> ```js
> const knex = require('knex')({client: 'pg', connection: ...})
> if (!knex.pool) throw new Error('Not connected')
> ```
> 
> Any advice?

Thanks for the solution.

`if (!knex.pool) throw new Error('Not connected')`

This line solved my issue.

**Comment by elhigu** [comment]
Only way to catch connection errors is to try to make a query and see if the connection error is thrown. When pool is created no connections are created by knex (pool is not prefilled on startup).
