### ISSUE TITLE
Updating from node 5.10 to 6.2.2 -- many pool related errors

### ISSUE THREAD

**Issue by zettam** [tgriesser/knex#1543]
Is there any known issues with this update?
Everything works fine with knex 0.10 under nodejs 5.10 and when I update my core to 6.2.2 none of my postgres-knex work, I get many "pool2" errors about bad passwords.

 Knex:Error Pool2 - error: password authentication failed for user "myuser"

**Comment by tgriesser** [comment]
Did you do a fresh removal of `node_modules` and `npm install` after upgrading?

**Comment by zettam** [comment]
not really? should I?
I never needed that so far in my life. I use node for the last 3 years or so.

**Comment by tgriesser** [comment]
Yeah, if there are compiled native modules they're often dependent on the node version used.

**Comment by elhigu** [comment]
@zettam did it work? I'm using `nvm` to change node version which I'm using... I have to delete node_modules every time when I'm changing between major node versions.

**Comment by zettam** [comment]
I will try it later, now I am far away from home maybe it's not a good ite to make these important updates over mobile. I had to revert all changes but I will have to update anyway, and I will try when I do.

**Comment by zettam** [comment]
Checked. Worked. Thank you!
