### ISSUE TITLE
Insert not being called

### ISSUE THREAD

**Issue by drekka** [tgriesser/knex#1544]
Hi, not really a bug report but I'm stuck trying to figure this out. I have the following code which I posted on StackOverFlow:

    return Knex.transaction(function (tx) {
            debug("Inserting new story record");
            return tx.insert({
                'projectId':projectId,
                'title': title,
                'story': text,
                'points': 0,
                'storyNumber': Knex('story').max('storyNumber').where('projectId', projectId)
            }, 'id')
                .into('story')
                .then(function (id) {
                    debug("Returning story for %s", id);
                    return getStory(id);
                })
        })

The problem is that the 'then()' function is never called.

I've been reading all the knex doco and it appears that I've done everything right. The debug for the command looked like this:

    crux:db Inserting new story record +4ms
    { method: 'insert',
      options: {},
      timeout: false,
      cancelOnTimeout: false,
      bindings: [ 0, 2, 'test', 2, 'title' ],
      __knexQueryUid: 'aa5ff1d3-eff0-4687-864b-772c26e1aebd',
      sql: 'insert into `story` (`points`, `projectId`, `story`, `storyNumber`, `title`) values (?, ?, ?, (select max(`storyNumber`) from `story` where `projectId` = ?), ?)' }

So it all looks good to me. Just never executes.

any ideas?

**Comment by wubzz** [comment]
@drekka Are you calling `.then` on the initial return statement of `return Knext.transaction` ? If not, that's probably it. If I recall, transactions also require `.then` being called before it will execute.

**Comment by elhigu** [comment]
@drekka more information is needed... It is probably what @wubzz  said, though other possibility is that insert throws an error and everything is rolled back and `.then` will be never called.

Try this one which handles some error cases and might help you to find out real reason:

```js
return Knex.transaction(function (tx) {
  debug("Inserting new story record");
  return tx.insert({
    'projectId':projectId,
    'title': title,
    'story': text,
    'points': 0,
    'storyNumber': Knex('story').max('storyNumber').where('projectId', projectId)
  })
  .into('story')
  .then(function (id) {
    debug("Returning story for %s", id);
    return getStory(id);
  })
  .catch(function (err) {
    debug("Insert failed", err);
    throw err;
  })
})
// just to make sure that transaction is triggered (in your code caller is responsible of that)
.then(function (blah) { return blah; }); 
.catch(function (err) { debug("Huh! Transaction failed!", err); throw err; });
```

Also in `.insert({...}, returning)` you seem to use mysql which doesn't support passing returning argument. So I dropped it from my suggestion...

**Comment by drekka** [comment]
Thanks guys, I realised after some fiddling round that it would not work anyway because MySQL won't allow you to sub query the table you are inserting into. So I've been re-writing it using the raw function because it's doesn't appear that knex caters to a `insert into x (...) select from x`. 

I'll keep you posted.

**Comment by kamronbatman** [comment]
It would be nice to see what you came up with!

**Comment by drekka** [comment]
Hi, after some fiddling around I did this:

    return Knex.transaction(function (tx) {
            return tx('story').insert(
                Knex.raw(
                    '(projectId, storyNumber, title, story, points) select ?, max(storyNumber) + 1, ?, ?, 0 from story where projectId = ?',
                    [projectId, title, text, projectId]
                ), 'id')
        })
            .then(getStory);
    }

**Comment by elhigu** [comment]
I'm closing this, since the original issue seems to be solved.
