### ISSUE TITLE
Update jsonb column with array of strings

### ISSUE THREAD

**Issue by voidxnull** [tgriesser/knex#1546]
Is there a way to use json arrays of strings in `update`? For example, I want something like this:
```js
knex("something").update({field: ['"1"']});
```
Where `field` is jsonb.
It didn't work for me: `update "something" set "test" = '{"\\\\"1\\\\""}'`.

Then I tried this:
```js
knex("something").update({field: JSON.stringify(['"1"'])});
```
and got: `update "something" set "test" = '["\\\\"1\\\\""]'`.

As you can see, there are a few extra backslashes which cause `invalid input syntax for type json` error in postgres (should be `'["\\"1\\""]'`). It seems like `SqlString.escape` escapes backslashes placed by `JSON.stringify`.

**Comment by elhigu** [comment]
Which knex version are you using? I tried with 0.11.7 and 

```js
var knex = require('knex')({client: 'pg'});

knex("something").update({field: JSON.stringify(['"1"'])}).toSQL();
{ method: 'update',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [ '["\\"1\\""]' ],
  __knexQueryUid: 'aee59acf-5c74-4791-9ece-dc37e393f406',
  sql: 'update "something" set "field" = ?',
  returning: undefined }

console.log(knex("something").update({field: JSON.stringify(['"1"'])}).toSQL().bindings[0])
["\"1\""]

```

Which seems correct...

**Comment by elhigu** [comment]
@voidxnull which version were you using? I couldn't reproduce your problem.
