### ISSUE TITLE
Documentation Fix, Proper use of returning() in insert

### ISSUE THREAD

**Issue by refactorized** [tgriesser/knex#1547]
http://knexjs.org/#Builder-insert is misleading, or confusing - That one is supposed to use returning to work with the resulting dataset could be made much clearer. 

The example from [issue 732](https://github.com/tgriesser/knex/issues/732) outlines a working, and seemingly very idiomatic way to do it.

**Comment by elhigu** [comment]
Maybe one could add to documentation of `.insert` that passing `.insert({...}, ['id', 'name'])` is just a shortcut for `.insert({...}).returning(['id','name'])`

**Comment by refactorized** [comment]
@elhigu (if you know) - I can't find any origin / build process for the index.html file ( the docs ), do I just add changes manually, or are them some source files I am missing somewhere? 

Thanks!

**Comment by elhigu** [comment]
It is hand written html. No build process at all. It is pushed to gh-pages on every release.
