### ISSUE TITLE
How to make transactional inserts?

### ISSUE THREAD

**Issue by keevitaja** [tgriesser/knex#1549]
Hello!

I have been trying this for a while, i cannot do it. 

I have a 90k+ rows which need to be inserted into sqlite database. row is just increment and 3 strings. 

Can somebody help me with this? All the examples are for inserting 2 rows or something like that.

Thank you very much!

This is the table i am working with:

```
exports.up = function(knex, Promise) {
    return knex.schema.createTable('rooms', (table)=> {
        table.increments();
        table.string('num');
        table.string('name');
        table.string('zone');
    });
};
```

edit: this is what i need to do. the example below is working!

```
    var sqlite3 = require('sqlite3').verbose();
    var sql = new sqlite3.Database('./db.sqlite3');

    sql.serialize(function() {
      sql.run("BEGIN TRANSACTION");

      var stmt = sql.prepare("INSERT INTO rooms(num, name, zone) VALUES (?, ?, ?)");
      for (let i in rooms) {
          let room = rooms[i];
          stmt.run(room.uid, room.name, room.area);
      }
      stmt.finalize();

      sql.run("END TRANSACTION");      
    });

    sql.close();
```

**Comment by elhigu** [comment]
This may work for you http://knexjs.org/#Utility-BatchInsert

**Comment by keevitaja** [comment]
@elhigu sorry, batch is max ~5000 rows, i have more. 90000 rows.

**Comment by elhigu** [comment]
@keevitaja BatchSize means only that how many rows is inserted with single INSERT statement. There is no limitation to batchSize, except the one that is coming from SQLite, which has pretty small maximum statement length. So you cannot make very big batches with sqlite.

So if you try to add for example 90k rows, you should set batch size to be somewhere between 100-1000... depending on your data to keep individual INSERT statements small enough. For example if you set batchSize to 500 batchInsert will generate 180 INSERT statements, which each one of them inserts 500 rows and all those inserts are added inside the same transaction.

If you set batch size to 1 then it should work the same way that your raw sqlite example, which adds every row in separate insert statement in one transaction.

**Comment by keevitaja** [comment]
Oh, i'll try that. Thank you. Will report back!

**Comment by elhigu** [comment]
Well... in theory with sqlite you should be able to use raw sql for transaction, because sqlite allows only one database connection, so all statements are sent to that one connection. However its not recommended in any way. You can just use kenx's transaction APIs there are examples of it.

If you like to see what kind of queries are sent you can start your app with DEBUG=knex:* environment variable to see what knex is doing.

I'll close this issue already, but you can still leave comments if there are problems.
