### ISSUE TITLE
On methods like Where methods

### ISSUE THREAD

**Issue by atiertant** [tgriesser/knex#1552]
i suggest to implement all where methods in "on" to allow all join possibility like onIn, onNull ...
whould you be interrested by a PR?

**Comment by pmalouin** [comment]
Looks like it was implemented in: #1674 
Though, I don't see these methods documented at http://knexjs.org and they do not appear in the changelog.

**Comment by elhigu** [comment]
In issue was linked documentation update knex/documentation#2 . Looks like @tgriesser commented them out until the release, but then forgot to uncomment and update changelog when release was done https://github.com/knex/documentation/blob/gh-pages/sections/builder.js#L982.

**Comment by elhigu** [comment]
I uncommented the documentation
