### ISSUE TITLE
How to specify schema search path using knex.raw to call pl/pgsql in postgres

### ISSUE THREAD

**Issue by digualu** [tgriesser/knex#1556]
Hi,

   I have a pl/pgsql created in the public schema public.foo() which references a table "bar" based on the current schema context (e.g. the table could be schema1.bar or schema2.bar):

CREATE OR REPLACE FUNCTION public.foo() RETURNS TEXT AS
$$
# print_strict_params on

DECLARE
    user_uuid TEXT;
BEGIN
    SELECT uuid INTO user_uuid FROM bar;
    RETURN user_uuid;
END
$$
;

   Because I uses pl/pgsql, I need use "SELECT public.foo();" to call it. I can't use knex.withSchema().select().from() construct as the query doesn't have a FROM clause, so I resort to use knex.raw(), the only way I can think of is to call "SET SCHEMA xxx" before and reset it after the query. I am wondering if there is better way to do it.

   Appreciate any help.

Thanks

**Comment by wubzz** [comment]
This should work..

```javascript
knex.select(knex.raw('??.foo();', 'public'))
//select "public".foo();
```
