### ISSUE TITLE
acquireConnectionTimeout does not seem to be respected

### ISSUE THREAD

**Issue by rogerschlachter** [tgriesser/knex#1559]
I'm on a rural internet connection.  I have an SSH tunnel set up to hit my development postgres database.  I'm expecting to need a bit more time to connect so I'm setting the acquireConnectionTimeout to 2 minutes.  I bumped it up to 5 minutes, but it doesn't seem to be respecting that timeout.

I turned on the debugging, and looking at the times, it feels as though it's not really giving it any more time to connect.  Here's how I'm setting up the connection:

`const dbConfig = {
    client: 'pg',
    connection: {
        host: process.env.OPENSHIFT_INTELIFI_DB_URL,
        user: process.env.OPENSHIFT_INTELIFI_DB_USER,
        password: process.env.OPENSHIFT_INTELIFI_DB_PASSWORD,
        database: process.env.OPENSHIFT_INTELIFI_DB_DATABASE,
        port: process.env.OPENSHIFT_INTELIFI_DB_PORT
    },
    acquireConnectionTimeout: 60000 \* 3,
    debug: true
};

var knex = require('knex')(dbConfig);
var bookshelf = require('bookshelf')(knex);
bookshelf.plugin(['registry', 'bookshelf-camelcase', 'visibility']);

module.exports = bookshelf;`

and here's what I'm seeing in the logs
`info: We have started our server on port 3000
info: And environment is: local
  pool2 Attempting to acquire minimum resources (cur=0, min=2) +0ms
  pool2 Attempting to acquire resource (cur=0, ac=0) +1ms
  pool2 Attempting to acquire resource (cur=0, ac=1) +5ms
  pool2 reap (cur=0, av=0) +9s
  pool2 reap (cur=0, av=0) +10s
  pool2 reap (cur=0, av=0) +10s
  pool2 Timed out acquiring resource +505ms
  pool2 Couldn't allocate new resource: Timed out acquiring resource +1ms
  pool2 Destroying pool: unable to aquire a resource within 0s +0ms
Knex:Error Pool2 - Error: Timed out acquiring resource
  pool2 Timed out acquiring resource +1ms
  pool2 Couldn't allocate new resource: Timed out acquiring resource +1ms
  pool2 Destroying pool: unable to aquire a resource within 0s +0ms
Knex:Error Pool2 - Error: Timed out acquiring resource
  pool2 Couldn't allocate new resource: read ECONNRESET +13s
  pool2 Destroying pool: unable to aquire a resource within 0s +0ms
Knex:Error Pool2 - Error: read ECONNRESET
  pool2 Couldn't allocate new resource: read ECONNRESET +916ms
  pool2 Destroying pool: unable to aquire a resource within 0s +0ms
Knex:Error Pool2 - Error: read ECONNRESET
`

Maybe I'm misunderstanding acquireConnectionTimeout and what it does?  Maybe I need to be changing something else?  Any help is greatly appreciated.

**Comment by elhigu** [comment]
This seems to be fixed, at least test case is passing for every dialect, except oracle and sqlite.
