### ISSUE TITLE
MySQl DATE type select

### ISSUE THREAD

**Issue by XiaodiKong** [tgriesser/knex#1562]
Hi

when i select column ‘date’ from my mysql db, the type of this column is "DATE" eg, 2016-07-03, 

but return '2016-07-03T00:00:00.000Z' 

what can i do for it ?

**Comment by tayden-hakai** [comment]
Having the same issue with postgres. It would be great if the time information was omitted from the output.

**Comment by niczak** [comment]
I too have a MySQL database (using MySQL driver) and whenever I select from a 'date' column the return adds 'T06:00:00.000Z' to the dates.  @tgriesser - any idea why this happens or if there is a way to prevent it from doing so? 

I hate to even admit it but I have had to do string manipulation to remove these from results before they are sent back to our app.

Any insight would be most appreciated!

**Comment by abhyuditjain** [comment]
I am also having the same issue with postgresql. It's really annoying. Any way to bypass this would be really helpful.

**Comment by wubzz** [comment]
These types of issues are driver-level, and as far as I know Knex does not process any response other than for utility functions such as `.first` or `.map`. For this reason I kindly ask you to take your concerns to the corresponding dialect repository. Thank you.

For postgres users, a tip is to check out the module `pg-types`.

**Comment by elhigu** [comment]
@abhyuditjain this has been discussed many times in issues and in stackoverflow check for example this https://stackoverflow.com/questions/45103788/knexjs-returning-mysql-timestamp-datetime-columns-as-javascript-date-object

**Comment by roytz** [comment]
In my case, the connection was a string so I had to find the date OID and use
`pg.types.setTypeParser(DATE_OID, d => moment(d));`
