### ISSUE TITLE
Saving json with undefined values no longer possible

### ISSUE THREAD

**Issue by goloroden** [tgriesser/knex#1563]
### Bug description

I have some code that tries to write a record to PostgreSQL, where the record consists of two columns: `id` and `data`. The columns are from the following types:
- `id`: `integer`
- `data`: `jsonb`

The code I am using for writing things is:

``` javascript
  this.knex.
    raw(`
      INSERT INTO myTable (
        id, data
      ) VALUES (?, ?)
      ON CONFLICT DO NOTHING;
    `, [ options.id, options.data ]).
    then(() => {
      process.nextTick(() => callback(null));
    }).
    catch(err => {
      process.nextTick(() => callback(err));
    });
```
### Expected result

When I try to run this code with values for `id` and `data` such as `23` and `{ foo: 'bar' }`, everything works fine. I would expect this code also to work with JSON objects that contain `undefined`, e.g.:

``` javascript
{
  foo: 'bar',
  baz: {
    bas: 42,
    bar: undefined
  }
}
```

Before [this pull request](https://github.com/tgriesser/knex/pull/1459) got merged, this worked perfectly. So apparently PostgreSQL supports this.
### Actual result

Since the pull request was merged, I now get an exception telling me:

> Undefined binding(s) detected when compiling RAW query.

Is this by intention? If so, what is the correct way to deal with this situation? Or is this a bug?

**Comment by elhigu** [comment]
Are you expecting that undefined value is just ignored from json or what was the older functionality?

Since `undefined` is not valid json value I'm inclined to say that the error here is feature instead of bug. 

One could argue that `undefined` should be ignored from since fetching missing key and fetcing key which returns `undefined` look the same, but that will also be a bit strange behavior, especially when there is `undefined` inside an array...

```js
{ value: undefined, id: 1 } => { id: 1 } // kind of ok and reasonable
{ value: [1, undefined, 3] } => { value: [1, 3] } // this would be pretty confusing
```

And automatically converting `undefined` to `null` would be just plain wrong and dangerous.

If this error becomes as desired behavior it probably should be written down somewhere in docs.

**Comment by wubzz** [comment]
**Knex 0.10**
```javascript
var options = {
	id: '23',
	data: {
		bas: 42,
		bar: void 0
	}
};
var queryBuilder = knex.
	raw(`
      INSERT INTO myTable (
        id, data
      ) VALUES (?, ?)
      ON CONFLICT DO NOTHING;
    `, [ options.id, options.data ])

return console.log(queryBuilder.toString());

//     INSERT INTO myTable (
//        id, data
//      ) VALUES ('23', '{"bas":42}')
//      ON CONFLICT DO NOTHING;

```

In 0.10 you would reach [this](https://github.com/tgriesser/knex/blob/master/src/dialects/postgres/utils.js#L66) point in the compiler for Raw which would remove undefined values in itself.


Given that the rule introduced in the PR is global across all the compilers, I personally feel that if we start making exceptions all around the code, we'd eventually have code that is too obnoxious to maintain. In this particular case it's also something that, in my opinion, should have been cleaned up prior to calling knex.

We should make it clear in the documentation that undefined values **simply do not work** with knex.

**Comment by goloroden** [comment]
Originally I would have expected that the new version works in the same way as the old one does, but I'm fine with the suggestion by @wubzz. Sounds reasonable :-)

**Comment by elhigu** [comment]
@goloroden We try to keep behavior unchanged between 0.0.x changes, 0.x are currently having backwards incompatible changes, especially when it comes to undocumented behavior. After 1.0 there shouldn't be any backwards incompatible changes until 2.0.

**Comment by wubzz** [comment]
Documentation and Knex source has been updated and afaik currently reflects comments in this issue, so I'll be closing this now.
