### ISSUE TITLE
raw query with arguments not working

### ISSUE THREAD

**Issue by farzher** [tgriesser/knex#1565]
This works
`db.raw("NOTIFY channel, 'sup'").asCallback(function(){});`

This doesn't work
`db.raw("NOTIFY channel, ?", ["sup"]).asCallback(function(){});`

When I run toString() on each, they're equal to eachother

**Comment by elhigu** [comment]
If there is database error coming, it means that one is not allowed to use positional bindings to pass value to that query. I've encountered that few times... What kind of error are you getting?

**Comment by farzher** [comment]
Sorry for not including that

```
{ [error: NOTIFY channel, $1 - syntax error at or near "$1"]
     name: 'error',
     length: 84,
     severity: 'ERROR',
     code: '42601',
     detail: undefined,
     hint: undefined,
     position: '17',
     internalPosition: undefined,
     internalQuery: undefined,
     where: undefined,
     schema: undefined,
     table: undefined,
     column: undefined,
     dataType: undefined,
     constraint: undefined,
     file: 'scan.l',
     line: '1082',
     routine: 'scanner_yyerror' }
```

**Comment by elhigu** [comment]
Yep, one cannot use parameter binding in that position with postgresql. There is nothing that knex can do to make it work easily. As far as I know you just have to concat your query and add literal quoting manually.

**Comment by farzher** [comment]
I didn't know parameterized bindings was a DB concept, I thought knex did javascript logic to make a safe string to send to the DB

So there's no `knex.escape` function I could call?

**Comment by elhigu** [comment]
There is an escape function in internal API, but if you like to be future compatible this should work:

```js
knex.raw('NOTIFY channel, ' + knex.raw('?', ['sup']).toString())
```

Pretty ugly but works :)

**Comment by farzher** [comment]
Oh, toString, of course

```db.raw(db.raw("NOTIFY channel, ?", ["sup"]).toString())```

That's pretty silly, but not bad
