### ISSUE TITLE
sqlite3 - non existent columns in select or where not throwing error

### ISSUE THREAD

**Issue by esalter** [tgriesser/knex#1567]
This might be two issues.  Using sqlite3, if I select from a non existent column, or add a non existent column in the where clause, no error is thrown.  The query is being generated correctly.  If I run this same query using mysql then an error is correctly thrown.  Therein lies the use case here - I'd like to use sqlite3 for unit testing failure conditions, but since the behavior is different from the real db I cannot do this currently.

Of note, if the table doesn't exist, that DOES throw an error.  So it's just limited to selecting/filtering by a non existent column.

If this is just a setting flag somewhere I missed, that's great, please just let me know what I need to flip!

````node
          return knex.select(['NonExistentColumn'])
            .from('clients')
            .where('nonexistant', 1)
            .on('query-error', function(error, obj) {
                console.log(error); // never reached
            }).on('query-response', function(response, obj, builder) {
                console.log(obj); // some data including results = []
            })
            .then(function(results) {
                console.log(results); // []
            }).catch(function(err) {
                console.log(err); // never reached
            });
````

**Comment by elhigu** [comment]
There is no way to make sqlite to behave exactly like mysql or postgres. 

Unless there is really good reason using different DB for testing and real application I wouldn't do it. It just limits the feature set of the real DB that you can be using to features compatible with test database and you actually won't know if your code works against real database. 

Since this is not really knex related question, but about generally DB engines, I'm closing this now. Please leave more comments / re-open this issue if this is somehow knex related issue.

**Comment by esalter** [comment]
Thanks for your response, however I do think this is a knex issue of some kind, because if I run the same statement against the underlying driver then it correctly throws an error.  Complete example:


````node
var sqlite3 = require("sqlite3").verbose();
var file = 'error_test.sqlite';

var db = new sqlite3.Database(file);
db.serialize(function() {

  db.run("CREATE TABLE Stuff (thing TEXT)");
  db.each("SELECT * FROM Stuff where nonexist = 1", function(err, row) {
    console.log(err); // { [Error: SQLITE_ERROR: no such column: nonexist] errno: 1, code: 'SQLITE_ERROR' }
    console.log(row); // undefined
  });
});
db.close();

````

I acknowledge the futility of asking for completely uniform behavior across all databases, but the fact remains that the driver does seem to be throwing an error that knex is dropping somewhere along the way (at least, I assume that's what's happening).

If you can point me to the correct location in knex where this interaction takes place I will try my hand at fixing it or at least seeing where the disconnect is occurring.

**Comment by esalter** [comment]
Just a polite bump.  @elhigu Perhaps you know where I can begin looking at this?

**Comment by elhigu** [comment]
@esalter This is the exact query that is sent to sqlite driver:

```js
knex.select(['NonExistentColumn']).from('clients').where('nonexistant', 1).toSQL()
{ method: 'select',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [ 1 ],
  __knexQueryUid: 'fd5fdf18-115d-47ab-a2a3-e87f3c964a06',
  sql: 'select "NonExistentColumn" from "clients" where "nonexistant" = ?' }
> 
```

And here is the code, which passes sql string and bindings to driver:

https://github.com/tgriesser/knex/blob/master/src/dialects/sqlite3/index.js#L72

I would start looking into this by adding debug prints etc. `under node_modules/knex` around the code that is sending query to driver. Let me know if you need more help with this. I don't see anything in sqlite query execution code, which could cause swallowing the error...

**Comment by esalter** [comment]
This appears to have something to do with quotes in the column name.  The sql that generates the error was:

````
SELECT * FROM Stuff where nonexist = 1
````

HOWEVER, this query runs without error:
````
SELECT * FROM Stuff where "nonexist" = 1
````

I confirmed this happens at the driver as well, so you are right, this isn't a knex issue.  Sorry about that!

**Comment by esalter** [comment]
As a quick follow up though, I was reading the sqlite documentation and found they do have compatibility for supplying either backticks or brackets for identifiers.  I tested the same query against the underlying driver using backticks, and that correctly throws a "no such column" error.  Would you accept a pull request that used either [] or `` for identifiers, rather than quotes?

**Comment by elhigu** [comment]
I think we have an issue which discuss sqlite identifier quoting. I'm on mobile right now so I cannot provide a link easily.
