### ISSUE TITLE
delete migrations files

### ISSUE THREAD

**Issue by lutfor3737** [tgriesser/knex#1569]
How to delete migrations files?

**Comment by elhigu** [comment]
`rm migration_file.js`if you have already applied migration to database you need to rollback migration first to make migration to disappear from migrations table. http://knexjs.org/#Migrations-rollback

**Comment by mikeLspohn** [comment]
I accidentally deleted a migration without rolling back. Now I can't get knex to work. It keeps saying the migrations folder is corrupt because it's missing the migration files. But i've uninstalled/reinstalled knex and it's still saying that.

**Comment by rhys-vdw** [comment]
You'll have to remove the unwanted changes from your database, then delete the row corresponding to the missing migration from your migrations table.

If you want to keep the changes you could just remake the migration file and rename it to match the missing file. I think the entries are identified by the timestamp portion of the file name - should be pretty easy to work out by looking at that column.

**Comment by piousbox** [comment]
For my needs, I ended up dropping the database, re-creating the database, and then re-running the migrations and then the seed.

For production, @jensMG I agree with you and I would recommend having a file that re-creates the database schema (you can look at your existing schema and create such a file relatively easily), and removing/archiving all the migrations, and starting again with a database structure with 0 migrations, and then creating new migrations from there. NOTE! There is the database table `migrations` that is used by knex, you may want to clear it.

**Comment by AMUSF** [comment]
- Recreate manually the file with the name from the error log
- Rollback:  knex migrate:rollback --all
- Delete the file you created
