### ISSUE TITLE
using with pg-error

### ISSUE THREAD

**Issue by jamesdixon** [tgriesser/knex#1570]
Is there a way to setup Knex to use the [pg-error](https://github.com/moll/node-pg-error) package? Ultimately, I'm looking for a way to gracefully handle database errors. Open to suggestions!

Thanks!

**Comment by elhigu** [comment]
Maybe you could wire it to be set up by the pool when connection is created?

something like

```js
          pool: {
            min: 0,
            max: 10,
            afterCreate: function (conn, cb) {
              conn.parseE = PgError.parse
              conn.parseN = PgError.parse
            }
          },
```

**Comment by jamesdixon** [comment]
Gave it a try, but doesn't seem to be working. The error returned still isn't an instance of PgError.

@moll do you have any idea on how to resolve this?

Thanks!

**Comment by moll** [comment]
Almost there, @jamesdixon. One extra listener missing:

```js
connection.connection.on("PgError", emitPgError)
```

I added some instructions to https://github.com/moll/node-pg-error#using-with-knexjs. Do they help?

PS. @elhigu: I believe the connection returned by `afterCreate` is one wrapped by Knex/pool. The real `Pg.Client` lives in `connection.connection`.

**Comment by jamesdixon** [comment]
@moll those instructions work beautifully! Thank you for your quick response!

**Comment by elhigu** [comment]
@moll thanks for the infos!
