### ISSUE TITLE
oracledb connectString not possible

### ISSUE THREAD

**Issue by codyzu** [tgriesser/knex#1573]
As [documented by node-oracledb](https://github.com/oracle/node-oracledb/blob/master/doc/api.md#-81-connection-strings) the oracledb driver supports some "exotic" connection strings.

The simplest ones resemble a URL, like the knex connectionParser stuff, but the more exotic ones do not.

In particular, I need to be able to reference entries in the `tnsnames.ora` file, as [described here](https://github.com/oracle/node-oracledb/blob/master/doc/api.md#-812-net-service-names-for-connection-strings). The result is that the config passed to the oracledb driver should look like:
```
{
  user: 'dfdf',
  password: 'dfdf',
  connectString: 'nameOfConnectionInTnsNames'
}
```

The current implementation (big thanks to @atiertant for his work on this!) does not allow this. In fact, it has hardcoded the `connectString` field to be the concatination of the host and database, see [here](https://github.com/tgriesser/knex/blob/master/src/dialects/oracledb/index.js#L62)

I purpose that users should be able to define the connectString parameter in the `connection` object passed to knex. That should allow even the most exotic oracle connectStrings

I'll make a PR for this.

**Comment by atiertant** [comment]
@codyzu you are right, this could be interresting !
