### ISSUE TITLE
Querying from an SQL function

### ISSUE THREAD

**Issue by rarkins** [tgriesser/knex#1582]
I'm implementing a search function that takes a string to search for plus a limit and returns results.

I've implemented this via an SQL function that looks like this:

```sql
CREATE FUNCTION site_search (text, int) RETURNS SETOF site_search_results AS $$
```

And the JS is like this:

```javascript
  var searchFunction = knex.raw('site_search(\'' + queryString + '\', ' + queryLimit + ')');
  knex
    .select('*')
    .from(searchFunction)
    .then(function(results) {
```

A problem I've found is if the search string contains a single quote mark, e.g. `d'`. I know I can use a javascript `replace` function for this, but it worries me that the string is non-sanitized. Is there an alternative way to do this without the risk of using knex.raw on user-input?

**Comment by wubzz** [comment]
Using bindings in raw should be enough I'd think?
```javascript
knex.raw('site_search(?, ?)', [queryString, queryLimit])
```

**Comment by rarkins** [comment]
Perfect, thanks!

**Comment by msaron** [comment]
This example of selecting from a function should be in the documentation. It took me many hours trying to figure this out as all my select statements are from functions.
