### ISSUE TITLE
knex CLI doesn't work in latest release

### ISSUE THREAD

**Issue by tdboone** [tgriesser/knex#1587]
The knex CLI doesn't appear to be working since the latest release. I think the `bin` attribute in package.json was removed inadvertently: https://github.com/tgriesser/knex/pull/1578/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2L63

**Comment by elhigu** [comment]
Uh, I should have spotted that. And once again I think we need some test case for client, this is not the first time it breaks silently and it is not spotted before release. Maybe some test should read where bin is pointing in package.json and try running that... maybe

**Comment by elhigu** [comment]
I'll roll out 0.11.9 shortly

**Comment by elhigu** [comment]
@tdboone I released 0.11.9 where that change is reverted, let me know if there are still problems

**Comment by tdboone** [comment]
The CLI is working again in 0.11.9. Thank you!
