### ISSUE TITLE
Expect only data rows in knex.raw stored procedure call

### ISSUE THREAD

**Issue by lutfor3737** [tgriesser/knex#1592]
I am getting metadata from raw store procedure call. How can i get only rows? My procedure, js call, output, expected output. How can  i get expected output from raw stored procedure call.
**Procedure:**
DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `getUsers`()
BEGIN
select * from users;
END$$
DELIMITER ;

**JS call:**  var raw = await knex.raw('call getUsers()');

**Output:** 
[
  [
    [
      {
        "id": 1,
        "given_name": "Smith",
        "family_name": "Bob",
        "created_at": "2016-07-21T14:23:12.000Z",
        "updated_at": "2016-07-21T14:23:12.000Z",
        "username": "bob",
        "encrypted_password": "jahgfjak"
      },
      {
        "id": 2,
        "given_name": "Davis",
        "family_name": "Joe",
        "created_at": "2016-07-21T14:23:12.000Z",
        "updated_at": "2016-07-21T14:23:12.000Z",
        "username": "joe",
        "encrypted_password": "agdal731"
      }
    ],
    {
      "fieldCount": 0,
      "affectedRows": 0,
      "insertId": 0,
      "serverStatus": 34,
      "warningCount": 0,
      "message": "",
      "protocol41": true,
      "changedRows": 0
    }
  ],
  [
    [
      {
        "catalog": "def",
        "db": "test_api",
        "table": "users",
        "orgTable": "users",
        "name": "id",
        "orgName": "id",
        "charsetNr": 63,
        "length": 10,
        "type": 3,
        "flags": 16931,
        "decimals": 0,
        "zeroFill": false,
        "protocol41": true
      },
      {
        "catalog": "def",
        "db": "test_api",
        "table": "users",
        "orgTable": "users",
        "name": "given_name",
        "orgName": "given_name",
        "charsetNr": 33,
        "length": 765,
        "type": 253,
        "flags": 0,
        "decimals": 0,
        "zeroFill": false,
        "protocol41": true
      },
      {
        "catalog": "def",
        "db": "test_api",
        "table": "users",
        "orgTable": "users",
        "name": "family_name",
        "orgName": "family_name",
        "charsetNr": 33,
        "length": 765,
        "type": 253,
        "flags": 0,
        "decimals": 0,
        "zeroFill": false,
        "protocol41": true
      },
      {
        "catalog": "def",
        "db": "test_api",
        "table": "users",
        "orgTable": "users",
        "name": "created_at",
        "orgName": "created_at",
        "charsetNr": 63,
        "length": 19,
        "type": 7,
        "flags": 1185,
        "decimals": 0,
        "zeroFill": false,
        "protocol41": true
      },
      {
        "catalog": "def",
        "db": "test_api",
        "table": "users",
        "orgTable": "users",
        "name": "updated_at",
        "orgName": "updated_at",
        "charsetNr": 63,
        "length": 19,
        "type": 7,
        "flags": 1185,
        "decimals": 0,
        "zeroFill": false,
        "protocol41": true
      },
      {
        "catalog": "def",
        "db": "test_api",
        "table": "users",
        "orgTable": "users",
        "name": "username",
        "orgName": "username",
        "charsetNr": 33,
        "length": 765,
        "type": 253,
        "flags": 0,
        "decimals": 0,
        "zeroFill": false,
        "protocol41": true
      },
      {
        "catalog": "def",
        "db": "test_api",
        "table": "users",
        "orgTable": "users",
        "name": "encrypted_password",
        "orgName": "encrypted_password",
        "charsetNr": 33,
        "length": 765,
        "type": 253,
        "flags": 0,
        "decimals": 0,
        "zeroFill": false,
        "protocol41": true
      }
    ],
    null
  ]
]

**Expected output:** 
[
      {
        "id": 1,
        "given_name": "Smith",
        "family_name": "Bob",
        "created_at": "2016-07-21T14:23:12.000Z",
        "updated_at": "2016-07-21T14:23:12.000Z",
        "username": "bob",
        "encrypted_password": "jahgfjak"
      },
      {
        "id": 2,
        "given_name": "Davis",
        "family_name": "Joe",
        "created_at": "2016-07-21T14:23:12.000Z",
        "updated_at": "2016-07-21T14:23:12.000Z",
        "username": "joe",
        "encrypted_password": "agdal731"
      }
    ]

**Comment by wuzhipei** [comment]
i also met it but cannot solve it. Expecting solution now.

**Comment by elhigu** [comment]
You should resolve how to make stored procedure call in a way that it returns only the rows. Check out what is the output when you are running the same query on psql or mysql (which ever you are using) console. 

Knex returns those results which are returned by the driver from the database, if your query returns too much information, there is nothing that knex can do for that.

I'll reopen this if you can show that this is knex specific issue.

**Comment by tvcong0999** [comment]
var output = raw[0][0];
