### ISSUE TITLE
.timeout() seems not work as expected

### ISSUE THREAD

**Issue by xihuanhh** [tgriesser/knex#1597]
hello everyone,i use knex to connect `sqlserver`,two tables each has stored about 200,000 records，i  use sqlserver client to execute `select * from table` about 11 seconds with result.

later i just use knex execute
 `select().from(table1).timeout(60000) ` parallel with
 `select().from(table2).timeout(60000)` 
all result-->exception
`table1 Timeout: Request failed to complete in 15000ms`
`table2 Timeout: Request failed to complete in 15000ms`

then i only execute one of them,it works fine.
i am confused.
so,does somebody can help me to solve this problem,Thanks a lot!

**Comment by rhys-vdw** [comment]
@xihuanhh Looks like a bug. `sqlserver == mssql` right?

**Comment by wubzz** [comment]
@xihuanhh @rhys-vdw This is a bit of an unfortunate situation. Most likely the knex code works as intended, but calling `.timeout(ms)` with ms > 15000 on the MSSQL driver would via the default MSSQL config throw this error. See default config: https://www.npmjs.com/package/mssql

`requestTimeout - Request timeout in ms (default: 15000).`

So the error is thrown on the driver level.

**Comment by xihuanhh** [comment]
@wubzz @rhys-vdw  thanks for reply，i will try it  again.
it just  a suggestion whether  or not to add a tips on the knex doc when use knex to connect to mssql.
