### ISSUE TITLE
Option to return config asynchronously from knexfile.js

### ISSUE THREAD

**Issue by tkambler** [tgriesser/knex#1600]
I'm porting a suite of applications over to Docker. As part of that process, we're moving all of our configuration into "the cloud." In other words, we're no longer loading our config from flat files that are stored with our application's source code in production... it's all fetched via remote service calls.

I'm now having to consider how I want to handle our application's `knexfile.js` file. It seems like it would be beneficial if support were added for returning a promise for a config object from this file.

**Comment by tkambler** [comment]
In the meantime, I'm going to look into using something [like this](https://github.com/ForbesLindesay/sync-request).

**Comment by johanneslumpe** [comment]
@tkambler another way around this would be to run a `postinstall` script which fetches your configs so your application could still rely on local files.

**Comment by elhigu** [comment]
@tkambler I would say that this is not really `knex`'s responsibility to implement. Why do you need to get configuration from `knexfile.js` ? You can initialize knex like this if you need async config loading:

```js
var knex = null;
resolveConfig.then(function (config) {
  knex = require('knex')(config);
});
```

If you need also knex client I would say that fetching file to local machine would be good choice... anyways after updating configuration you need to restart application server to update run configuration to your application.

**Comment by ruzpuz** [comment]
@elhigu What about the use case when knex is used as tool for migrations. 

In example `knex migrate:latest` will use knexfile.js to get configuration. How do I inject it asynchronously?

**Comment by tkambler** [comment]
@ruzpuz In that case, don't use the `knex` CLI utility. Write your own script using the migration API.

**Comment by ruzpuz** [comment]
@tkambler sounds a bit disappointing but c'est la vie

**Comment by elhigu** [comment]
If there is lots of demand for this I suppose it could be implemented, but this is so rare use-case that one can use migration API+ own async load routines.

**Comment by ruzpuz** [comment]
I suppose this would be a 'nice to have' feature. However you are right.
