### ISSUE TITLE
Does knex support geometric Postgres types?

### ISSUE THREAD

**Issue by marclar** [tgriesser/knex#1605]
I have a table with a column of type `point`. Is this supported in knex?

[A related question (about Sequelize)](http://stackoverflow.com/questions/32059758/how-to-insert-a-postgis-geometry-point-in-sequelize-orm) uses the format:

```
var point = { type: 'Point', coordinates: [39.807222,-76.984722]};
```

**Comment by elhigu** [comment]
Could you tell me some query you are trying to write. I can try it out how does it work. There is no separate type in knex for point... I suppose that mostly it depends how pg driver is handling the point data.

**Comment by marclar** [comment]
Thanks for the reply, @elhigu -- I decided to go with Sequelize b/c I also need to use `range` types, which are supported there.

**Comment by elhigu** [comment]
👍 welcome back when you get tired of Sequelize 😉
