### ISSUE TITLE
Knex Schema: relation already exists

### ISSUE THREAD

**Issue by karatheodory** [tgriesser/knex#1608]
Dear Sirs,

considering the following case (tested on `postgres` dialect):
```js
...// Creating Knex context
.then((knex) => {
      const {schema} = knex;
      console.log('Creating tables...');

      return Promise.resolve()
      .then(() => schema
      .createTable('my_great_table', table => {
          table.uuid('id')
              .primary();
          table.string('file_name', 256)
              .notNullable();
      }))
      .then(() => schema.createTable('my_lovely_table',
        (table) => {
            table.uuid('id')
                .primary();
            table.string('name');
        }))
      .then(() => {
        console.log('Tables should be created.')
      });
    })
      .catch((error) => {
        console.error('Error creating database: ', error);
      });
```
I get `Error creating database:  { error: create table "my_great_table" ("id" uuid, "file_name" varchar(256) not null) - relation "my_great_table" already exists`

If I do the following:
```js
...// Creating Knex context
  .then((knex) => {
        const {schema} = knex;
      console.log('Creating tables...');

      return Promise.resolve()
      .then(() => schema
      .createTable('my_great_table', table => {
          table.uuid('id')
              .primary();
          table.string('file_name', 256)
              .notNullable();
      }).createTable('my_lovely_table', // Note here, now schema updates are chained.
        (table) => {
            table.uuid('id')
                .primary();
            table.string('name');
        }))
      .then(() => {
        console.log('Tables should be created.')
      });
    })
      .catch((error) => {
        console.error('Error creating database: ', error);
      });
```
everything passes seamlessly, and tables are created.

It looks like a procedure which clears current schema statements' context is missing somewhere.

**Comment by rkaw92** [comment]
See #491 - actually. knex.schema **is a getter function that creates a new SchemaBuilder instance**, and thus you are operating on the same query, mutating it. Relevant code: https://github.com/tgriesser/knex/blob/master/src/util/make-knex.js#L81

You need to refer exactly to `knex.schema` every time to get a fresh builder - don't keep references to the instance.

**Comment by karatheodory** [comment]
@rkaw92 now I see, thank you for pointing me to the proper place! I don't know why I have missed that by myself.

I have also created a pull request to include the information you have kindly provided to the docs. Hope it will help to avoid the same issues in the future.
