### ISSUE TITLE
Pluck not working for explicit column names

### ISSUE THREAD

**Issue by marudor** [tgriesser/knex#1619]
Example:
```js
knex
.pluck('foo.id')
.from('foo')
.innerJoin('bar', 'bar.foo_id', 'foo.id')
```
If foo and bar both have an ```id```field pluck will resolve to an array of false instead of the actual result.

**Comment by rolandstarke** [comment]
With this fix i get the sql error:

SQL Fehler (1052): Column 'id' in field list is ambiguous



sadly .pluck(knex.raw('id')); (https://github.com/tgriesser/knex/issues/817#issuecomment-119705834) dosn't work anymore

**Comment by elhigu** [comment]
Im surprised if it has ever worked. .select(’id’).pluck(’id’) might

**Comment by rolandstarke** [comment]
.select(’id’).pluck(’id’) results in SELECT `id`, `id`

a simple workaround is to not use pluck and instead exctract the column yourself:

.select({alias: '1 + 1'}).map((row) => row.alias);

**Comment by elhigu** [comment]
yeah, true. I now tried that out how does it actually work. Looks like pluck() indeed has been intended to combine .select() on db server side and then plucking that selected id from result 👍 

It seems to work just as expected, but yeah it really doesn't support `knex.raw`. What is the actual use case why would you need raw there? Doing some computation with column value and plucking that result? Probably it could be supported quite easily...

**Comment by rolandstarke** [comment]
yes you are right, I want the values of a computed column.

```
const language = 'en';
const questionIds = await knex
    .select({ id: knex.raw('DISTINCT COALESCE(dublicate_of, id)') })
    .from('question').where('language', language)
    .map((row) => row.id);
```



the table is like

id  | question | language | dublicate_of
------------ | -------------  | -------------  | -------------
1 | How are you? | en |  null
2 | How are u? | en |  1
3 | How are u? | de |  1

The query should give me all canonical question ids available in my language.

I first tried .pluck('id') but it did not use the alias, but selected a new column. 
With map I am fine now, its short and no new api to learn. So actually I am fine :)
