### ISSUE TITLE
Error handling in with knex.raw procedure call

### ISSUE THREAD

**Issue by lutfor3737** [tgriesser/knex#1620]
I have a procedure. If i call it from mysql workbench, i got the following error. 

`'ERROR 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`test_api`.`role_permissions`, CONSTRAINT `role_permissions_permission_id_foreign` FOREIGN KEY (`permission_id`) REFERENCES `permissions` (`id`) ON DELETE CASCADE)' `

Front end call:
`var result = await knexDb.raw('call transaction_sp_update("'+roleName+'", "'+roleOwnerId+'","'+roleOwnerType+'","'+rolePermDeletion.join().concat(',')+'","'+rolePermAddition.join().concat(',')+'","'+roleParentDeletion.join().concat(',')+'","'+roleParentAddition.join().concat(',')+'")');`

i wanted to show above error in front end. How to get that exact error in front end?

**Comment by elhigu** [comment]
Do you get some error when you call your procedure? What results are you getting from calling the procedure? If you are calling it correctly knex should throw the same DB error.

**Comment by lutfor3737** [comment]
I parsed the error message following way.
 let result = await knexDb.raw('call transaction_sp_insert(?)',[roleParams.id]);   
    if (result[0][1][0]['@SUCCESS'] == 'SUCCESS') {
      return this.findRolebyID(result[0][0][0]);
    } else if(this.getFirstWordError(result[0][1][0]['@MYSQLERROR']) == "ERROR"){
      return result[0][1][0];
    } else {
      return null;
    }
