### ISSUE TITLE
Can I translate knex('acount').where('status', 'active')  into  SQL 'status = 1' ?

### ISSUE THREAD

**Issue by k7** [tgriesser/knex#1622]
Thank you for your time.

In my project, I want to hide the plain meaningless number in SQL from higher layer module.

for example,  in my account table, `status = 1` means that the account is active.

but I want to query it in the higher layer module, just use  
```javascript
knex('acount').where('status', 'active')
```
and it should translate to SQL 
```SQL
select * from acount where status = 1;
```

How can I do this?

Thank you very much again!

**Comment by atiertant** [comment]
why don't you simply do this?
```
const active = 1
knex('acount').where('status', active)
```

**Comment by elhigu** [comment]
There is no value/enum mapping hooks like that in `knex`. To be able to do that `knex` would require knowledge about your models or db schema. To get that feature you should use some ORM. There are 2 (as far as I know) reasonable choices for `knex` based ORMs, `bookshelf` and `objection.js`.

**Comment by atiertant** [comment]
@elhigu you could add `offshore` with `offshore-sql` in your list
