### ISSUE TITLE
Add documentation for Oracle "SID"/"Service name" parameter

### ISSUE THREAD

**Issue by kibertoad** [tgriesser/knex#1623]
Current Knex connection documentation says nothing about how user is supposed to set SID connection value and this value is very important for Oracle databases.

I can make a proper PR with change if someone explains what would be a proper way to set it :).

**Comment by MoJoE3131** [comment]
I don't know if I'm asking this in the right place but is there anything new about getting a connection done using an SID?

Is it possible right now?

**Comment by kibertoad** [comment]
It is. Use "database" to specify SID. Another gotcha is that port should be specified as a part of the host parameter (go figure).
I really should submit a documentation PR one of these days.

**Comment by MoJoE3131** [comment]
Thanks for the quick answer!

I've tried putting the SID in the "database" as follow but it didn't work.  Do you see something wrong by any chance?

    localtst: {
      dialect: 'oracledb',
      connection: {
      user: "uname",
      password: "pwd",
      host: "myserver:2222",
      database: "mysid"
      }

I get the following error message : Knex:Error Pool2 - Error: ORA-12514: TNS:listener does not currently know of service requested in connect descriptor

Seems like it still thinks I'm passing a service name and not an SID....

Thanks for your help.

**Comment by kibertoad** [comment]
I'll check tomorrow against what we are using, but it might be that you are correct - you can only specify service name but not the sid with knex.

**Comment by MoJoE3131** [comment]
As a follow up.

Turns out that the database I was trying to reach also had a service name so it's now working for me.

But I still try to think that there's an issue with older database that would only use SID.

**Comment by georgemp** [comment]
Hi,

Just checking in for confirmation that SID is not supported? Thanks

**Comment by MoJoE3131** [comment]
I'm not aware that it's now supported...

**Comment by elhigu** [comment]
@atiertant might know about this.

**Comment by cmpdtp** [comment]
I can"t connect with knex using SID , is there any sollution for that probem !

**Comment by elhigu** [comment]
One should check this from oracledb driver documentation. In test setup if SID means in our case XE it is given like this  https://github.com/tgriesser/knex/blob/master/test/knexfile.js#L90

**Comment by E424065** [comment]
After following the connection string, still unable to connect with oracle DB that has SID. It is connecting only with database that has Service name.

**Comment by elhigu** [comment]
@E424065 did you try to how to do that directly with oracledb driver?
