### ISSUE TITLE
MySQL procedure migrations 

### ISSUE THREAD

**Issue by lutfor3737** [tgriesser/knex#1624]
I have a mysql procedure. I want to migrate that using knex. How i will do?

**Comment by jubairsaidi** [comment]
I'm also looking for the same in Postgres (functions not procedures), though I also am looking for a way to handle creating types as well.  Currently I simply have an sql file that I use to install the types and functions but it would be nice to have them stored with the migrations if possible.

**Comment by elhigu** [comment]
With knex raw like any other custom query.
