### ISSUE TITLE
drop table + create table= relation "xxx" already exists

### ISSUE THREAD

**Issue by alexey2baranov** [tgriesser/knex#1629]
hell0! i'm trying recreate user table and get error 

```
knex.schema.dropTableIfExists('user');
knex.schema.createTable('user', function (table) {
    table.increments();
    table.string('name');
    table.string('email', 128);
    table.integer('age');
    table.string('role').defaultTo('admin');
    table.string('password');
    table.timestamps();
})
    .then();
```

> Unhandled rejection error: create table "user" ("id" serial primary key, "name" varchar(255), "email" varchar(128), "age" integer, "role" varchar(255) default 'admin', "password" varchar(255), "created_at" timestamptz, "updated_at" timestamptz) - relation "user" already exists

**Comment by alexey2baranov** [comment]
knex.schema.dropTableIfExists('user')**.then**;
knex.schema.createTable('user', function (table) {
    table.increments();
    table.string('name');
    table.string('email', 128);
    table.integer('age');
    table.string('role').defaultTo('admin');
    table.string('password');
    table.timestamps();
})
    .then();

adding then() after dropTableIfExists goes code well. Why should I use then() after each code line and why this is not documented in documentation?

**Comment by wubzz** [comment]
@alexey2baranov Please stick to just one issue. I replied in your other issue. https://github.com/tgriesser/knex/issues/1628#issuecomment-240060001

**Comment by wubzz** [comment]
The proper way to do this would be:

```javascript
knex.schema.dropTableIfExists('user')
.then(function () {
return knex.schema.createTable('user', function(table) {
    table.increments();
    table.string('name');
    table.string('email', 128);
    table.integer('age');
    table.string('role').defaultTo('admin');
    table.string('password');
    table.timestamps();
});
})
.then(function() {
//Table created
})
.catch(function(error) {
//Error handler
});
```

Alternatively this *should* work too, I think:

```javascript
knex.schema.dropTableIfExists('user')
.createTable('user', function(table) {
table.increments();
table.string('name');
table.string('email', 128);
table.integer('age');
table.string('role').defaultTo('admin');
table.string('password');
table.timestamps();
})
.then(function() {
//Table created
})
.catch(function(error) {
//Error handler.
});
```
