### ISSUE TITLE
Database connection pool destroyed permanently after temporary network issue

### ISSUE THREAD

**Issue by jdleesmiller** [tgriesser/knex#1634]
This issue sort of sits between knex and pool2, and I opened it there as  https://github.com/myndzi/pool2/issues/28 . The maintainer of pool2 suggested that I open an issue here for comment, as well. I've pasted a summary of it here for ease of reference, but please see https://github.com/myndzi/pool2/issues/28 for more details.

Our setup: node 4.4.1, pool2 1.3.4, knex 0.10.0.

We had a failure in production today after the following series of events:

1. A web server had a temporary network issue. Attempts to open new database connections started hanging.
2. pool2 was running in its default configuration (via knex) with `bailAfter == 0`, so it destroyed itself after the first `acquire` timed out.
3. Knex logged the error but didn't crash the process (this was on 0.10, but it looks like this behaviour is still the same [on knex master](https://github.com/tgriesser/knex/blob/6fa485302b29c7e312177d94cd1eafadf882db6f/src/client.js#L165)).
4. The network came back. The server tried to process requests, but its database connection pool had been destroyed, so all requests failed with "Pool is destroyed" errors.

I think two possible solutions are:

1. Set `bailAfter` to `Infinity` by default in knex or (as a workaround) in the `knexfile`'s pool config. That way, those requests would have failed to acquire connections, but the pool would not have been destroyed, and eventually it would have been able to acquire connections again.

2. Make knex crash on pool2 errors. Had knex crashed instead of just logging the error and carrying on with a destroyed pool, the process would have been restarted, and eventually it would have come up in a working state when the network came back.

   At present, pool2 emits quite a few different types of errors, and not all of them require a crash, so knex would need some way to detect that the pool had destroyed itself and that the process either had to crash, or the pool had to be reinitialized. I don't see anything in knex that does this in 0.10.0 or on master.

Should pool2 make 'pool destroyed' a special type of event? Or should knex or pool2 set `bailAfter` to Infinity by default? Or maybe something else?

**Comment by tgriesser** [comment]
Checkout 0.12 and see if it fixes your issues
