### ISSUE TITLE
Request: support moment -> date conversion

### ISSUE THREAD

**Issue by avimar** [tgriesser/knex#1636]
Knex seems to include built-in JS native `Date` support.

The moment library is quite excellent, and it supports both an `instanceof` [operator ](http://momentjs.com/docs/#/query/is-a-moment/) and also conversion back to a native Date object by simply [calling ](http://momentjs.com/docs/#/displaying/as-javascript-date/)`toDate()`

It would be nice to automatically detect `instanceof moment` and then convert back to a native JS object, which is already supported, and does not require a dependency on moment.

I tried playing with it myself by modifying https://github.com/tgriesser/knex/blob/289f17e21bef315cc1c0839bc620dc694e6cf732/src/query/string.js#L20 but I have clue why that didn't work.

Does someone know the simple place to add this?

**Comment by wubzz** [comment]
I don't think this really belongs in knex after all. There are two ways of doing this without altering the knex code-base.

1. Use [postProcessResponse](http://knexjs.org/#Installation-post-process-response)
2. Use [pg-types](https://www.npmjs.com/package/pg-types) *(Postgres only)*
