### ISSUE TITLE
Deferring schema queries when referencing a table that's in the process of being created

### ISSUE THREAD

**Issue by joepie91** [tgriesser/knex#1645]
* __Local Knex version:__ 0.11.10
* __Knex CLI version:__ 0.11.9

(I'm reporting this bug for somebody else, as I have more information on how to potentially solve it.)

When specifying a migration that creates two (or more) new tables in a single `Promise.all`, and where one of those tables references the other, this will fail because the referenced table does not exist yet. For example, in PostgreSQL:

```
error: alter table "users_wards_map" add constraint "users_wards_map_user_id_foreign" foreign key ("user_id") references "users" ("user_id") on update CASCADE on delete CASCADE - there is no unique constraint matching given keys for referenced table "users"
```

The following is a (reduced) example of a migration where this will occur:

```javascript
exports.up = function (knex, Promise) {
    return Promise.all([
        knex.schema.raw("SET timezone = 'utc'"),
 
        knex.schema.createTableIfNotExists('users', function (table) {
            table.uuid('user_id').primary().notNullable().unique().comment("UUID generated through app");
            table.string('first_name', 255);
            table.string('last_name', 255);
        }),
        
        knex.schema.createTableIfNotExists('otps', function (table) {
            table.uuid('user_id').primary().unique().references('user_id').inTable('users').onDelete("CASCADE").onUpdate("CASCADE");
            table.string('token', 4).notNullable();
            table.text('auth_token');
            table.timestamps(false, true);
            table.boolean('verified').defaultsTo(false);
        }),
 
        knex.schema.createTableIfNotExists('children', function (table) {
            table.uuid('parent').references('user_id').inTable('users').notNullable().index().onDelete("CASCADE").onUpdate("CASCADE");
            table.uuid('child_id').primary().unique().notNullable().comment("UUID generated through app");
            table.string('first_name', 255);
            table.string('last_name', 255);
        }),
 
        knex.schema.createTableIfNotExists('users_wards_map', function (table) {
            table.uuid('user_id').references('user_id').inTable('users').onDelete("CASCADE").onUpdate("CASCADE");
            table.uuid('ward_id').references('child_id').inTable('children').onDelete("CASCADE").onUpdate("CASCADE");
        })
    ]);
};
```

While it is understandable from a technical perspective that this would fail (as the queries are run in parallel), it'll still be confusing for many developers, and it took even me a while to spot the issue, despite being familiar with it and having encountered it before.

My suggestion would be to perhaps internally defer the creation of the referencing table (`users_wards_map` in this case), if Knex is aware that a table with a matching name and column is about to be created - after all, Knex already *knows* about the table and its columns, it just hasn't executed the query yet.

For the above example, this is what the current 'internal timeline' would look like (assuming that all calls succeed, which would not be possible in this example):

```
- [1] Promise.all (in migration file)
- [2] createTable "users"
- [3] createTable "otps"
- [4] createTable "children"
- [5] createTable "users_wards_map"
- (resolve 2, 3, 4, 5), then
- (resolve 1)
```

If implementing my suggestion, this is what it would look like instead, for *the same example code, unmodified*:

```
- [1] Promise.all (in migration file)
- [2] createTable "users"
- (resolve 2), then
- [3] createTable "otps"
- [4] createTable "children"
- (resolve 3, 4), then
- [5] createTable "users_wards_map"
- (resolve 5), then
- (resolve 1)
```

... which would work correctly.

**Comment by jurko-gospodnetic** [comment]
I don't think there are any guarantees in what order the operations triggered by a `Promise.all()` call would get triggered. That means, that even if we did implement what you suggest, and knex remembered that it is in the process of *creating table X*, that it would would not already have started running a query depending on that *table X* before it even realized that the *create table X* operation existed.

This is really a typical async operation series, and I think the programmer should definitely be aware of what they are doing and what dependencies exist between such operations exist when executing them. You can always prepare a simple utility function that would, for instance, take an array of functions, each function representing a single async operation and returning a promise, and then run each of them in sequence (basically, chain them all together using `.then()` blocks), and I've seen such utility functions readily available in both `when` & `bluebird` promise libraries.

**Comment by joepie91** [comment]
When saying "Knex is aware that a table is about to be created", I just mean the synchronous calls to Knex, prior to any asynchronous execution - the actual execution order wouldn't matter there.

> You could have just as well just constructed the command to be executed later, after you do something with an already existing table and then dropping the original table.

This is a valid point, and one I had not considered. I do, however, still think that the issue described here is a footgun that's worth resolving - especially as I've seen multiple people run into this over the years.

Writing migrations is one of the things that a 'beginner' would do when starting their first project, and especially in that scenario, the intricacies of orchestrating asynchronous operations often aren't clear. I certainly know that when I started out with Node.js and Knex, my initial approach was just to shove everything into a `Promise.all` because there was no other clear path forward. The cryptic error messages don't really help with that either.

I'm not sure whether the right solution here lies in documentation or in the API, but it's definitely something that a few braincycles should be allocated to :)

**Comment by jurko-gospodnetic** [comment]
Can you try proposing a patch for the docs and people can pitch in with their thoughts there?

**Comment by elhigu** [comment]
@joepie91 Tutorials, recipes, howtos, documentation updates are always more than welcome. There is and always will be a lot of room for improvement.

One big problem has been that earlier default migration template did use `Promise.all()` which probably has been one big source of confusion over the years. 

About the feature discussion: I don't think that resolving/validating execution order of queries that user is writing is anything that `knex` should even try to validate. It is pretty much impossible to do well and it wouldn't make sense to do it just for table creation, because people don't understand how promises works.
