### ISSUE TITLE
Template tag interface

### ISSUE THREAD

**Issue by knownasilya** [tgriesser/knex#1647]
Would love to see the following API

```js
let result = await db.raw`select ${column} from ${table} where id = ${id}`;
```

Kind of what https://github.com/devTristan/simple-postgres#template-string-mode does.

**Comment by tgriesser** [comment]
Yep - this is something I'd like to add as well, added to the 1.0 api list at: https://github.com/tgriesser/knex/pull/1659

**Comment by avimar** [comment]
Related: https://github.com/tgriesser/knex/pull/1766
