### ISSUE TITLE
SQL_CALC_FOUND_ROWS and found_rows() not returning the count for MySQL

### ISSUE THREAD

**Issue by shikasta-kashti** [tgriesser/knex#1662]
Hi,

I'm trying to get the count for a query to which `LIMIT` was applied. I saw that the way to do that instead of doing another `COUNT(*)` query is to use `SQL_CALC_FOUND_ROWS` in the first query and do a another query for `found_rows()`. 

The problem is that when I try to do this from knex I always get the rows as `1`. It works fine if I try through the MySQL CLI or any GUI tool.

Here's my code:

```
var mysql = require('knex')({
    client: 'mysql',
    debug: false,
    connection: {
        host: '<here_be_host>',
        port: 3306,
        user: 'root',
        password: '<and_password>',
        database: '<and_the_db>'
    }
});

mysql
  .select(mysql.raw('SQL_CALC_FOUND_ROWS *'))
  .from('Users')
  .where('Username', 'LIKE', '%a%')
  .limit(100)
  .offset(30)
  .then((r) => { console.log('got results, getting count'); })
  .then(() => { return mysql.select(mysql.raw('found_rows()')); })
  .then((res) => { console.log(JSON.stringify(res, null, 2)); });
```

I get this in return:

```
got results, getting count
[
  {
    "found_rows()": 1
  }
]
```

Any idea what am I doing wrong here?

**Comment by HaNdTriX** [comment]
The problem with your Solution is the knex connection pool.

The  `SQL_CALC_FOUND_ROWS` - query uses a different connection than the `FOUND_ROWS()`- query. The solution is to wrap both queries in a [transaction](http://knexjs.org/#Transactions).
