### ISSUE TITLE
knex.schema is doing nothing

### ISSUE THREAD

**Issue by lvffilho** [tgriesser/knex#1667]
Im using knex.schema.createTable and nothing is doing, after sometime it gives and error.

TypeError: request.abort is not a function
    at Object.abort (file:///android_asset/www/assets/main.bundle.js:106442:18)

**Comment by tgriesser** [comment]
Can you give a gist of the code you're running?

**Comment by lvffilho** [comment]
`        AbstractDAO.knex.schema.createTableIfNotExists('Person', function (table) {
            table.integer('id').primary();
            table.string('firstName');
        `});`

**Comment by lvffilho** [comment]
Or it gives me current message

Error: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?

but i have only one connection at pool.

**Comment by lvffilho** [comment]
answer with the other issue.
