### ISSUE TITLE
MSSQL  - Could not find stored procedure 'object Object'

### ISSUE THREAD

**Issue by KromDaniel** [tgriesser/knex#1669]
Hey
`NodeJS v6.4.0`
`knex 0.12.0 `
`MSSQL (NPM) 3.3.0`
Running the next code:
```javascript
select()
 .from("dbo.brData as brd")
 .fullOuterJoin("dbo.phs as phs","brd.ph_id","phs.id")
 .fullOuterJoin("dbo.pat as pat","pat.path","phs.path")
 .where("tx_type","Small")
 .andWhere(function(){
     this.where("brd.e_id","someId")
      .orWhere("brd.t_id ","someId");
   }).then(resolve,reject);
```

Always returns the error: 

> Could not find stored procedure 'object Object'.

If I'm doing `queryBuilder.toString()` it returns good and valid query but `queryBuilder.raw(query.toString)` returns same error

Thanks

**Comment by cdmcnamara** [comment]
I'd like to make a pull request to fix it but I'm not entirely sure what the point of this block is as sql is originally a string, but then it looks like it's trying to make it an object that contains a `sql` field and an `options` field.

@tgriesser, could you shed some light?

**Comment by hitgeek** [comment]
having same issue. 
simple `select *` query returns `"Could not find stored procedure 'object Object'"`in 0.12, but works in 0.11.

MSSQL Trace shows the query `exec sp_executesql @statement=N'[object Object]'`

**Comment by tgriesser** [comment]
I think the commit I just added should fix it, will cut a release shortly

**Comment by KromDaniel** [comment]
Thanks for the real quick solution!
