### ISSUE TITLE
Proper way to determine that some object is a transaction object

### ISSUE THREAD

**Issue by StreetStrider** [tgriesser/knex#1672]
Is there a convenient way to determine that some object is a transaction object? For now I'm using this duck-typeish thing:

``` js
(tx) =>
{
    return Boolean(tx && tx.transaction && tx.savepoint)
}
```

**Comment by wubzz** [comment]
Kinda late reply, but I believe `client.txid` is the only real unique identifier.

**Comment by StreetStrider** [comment]
Ok, thak you, will know.
Both your advice and my own check rely on implementation details, though. They are stable details, but still.
