### ISSUE TITLE
Is it safe to run multiple containers in docker on knex migration?

### ISSUE THREAD

**Issue by chenweiyj** [tgriesser/knex#1677]
I use knex migrate to do migration before my application starts when my database structure changed. I use docker to deploy my application, which will run many containers in the same time. I wonder if it is safe to run knex migrate in each container concurrently. 

As expected, only one container should hold the lock and do the migration, and all others should return 'already up to date'. If not so, the database structure might be corrupted.

**Comment by elhigu** [comment]
yes, there is locking that only one instance may run migrations at once... others should get already up to date response.
