### ISSUE TITLE
API for retrieving knex config from a connection?

### ISSUE THREAD

**Issue by jtlapp** [tgriesser/knex#1684]
Is there an API I can use to retrieve the knex configuration from a connection handle?

I'm passing the connection handle around and under certain circumstances want to log the name of the database being accessed. I'd rather not also pass the configuration around or monkey-patch the connection handle with a configuration property that might ultimately conflict with knex.

**Comment by tgriesser** [comment]
> I'm passing the connection handle around

Which connection handle is this? Can you give a code example?

**Comment by jtlapp** [comment]
Distilling it down, `db` here is my connection handle:

```js
var db = knex(require('./knexfile.js'));
```

**Comment by jtlapp** [comment]
At the moment, I just need the database name. I'm looking for something like:

```js
var dbName = db.getConfig().connection.database;
```

Or:

```js
var dbName = db.getDatabase();
```

**Comment by blah238** [comment]
Does `db.client.config.connection.database` give you what you want?

**Comment by jtlapp** [comment]
Sure does! I'll give it a shot. Thank you! It would be nice to officially document a way to get the config to be sure it figures into backward-compatibility considerations.

**Comment by blah238** [comment]
@jtlapp Great to hear. I agree, if you want to open a PR for the documentation, the repo is here: https://github.com/knex/documentation

I'd probably put it after the section about reusing the knex instance: https://github.com/knex/documentation/blob/e37b968e3b584c5e3d58bf069602106053a923a6/sections/installation.js#L125

As for backwards compatibility, maybe @tgriesser could comment on whether this is expected to change in the [1.0 refactor](https://github.com/tgriesser/knex/pull/1659). I took a quick look and it looks like it should be the same.

**Comment by tgriesser** [comment]
Actually `knex.client.database()` is probably the best way to get this info, as this probably won't change. If it does, there'll be a documented upgrade path

**Comment by SephReed** [comment]
Not working for me.  Returns an object not a string.  Can't find any documentation on it.
