### ISSUE TITLE
Connections are not returned to the pool if acquireConnectionTimeout is triggered

### ISSUE THREAD

**Issue by koskimas** [tgriesser/knex#1694]
This test fails on 0.12.1

```js
const _ = require('lodash');
const Knex = require('knex');
const Promise = require('bluebird');

const knex = Knex({
  client: 'postgres',
  pool: {
    min: 0,
    max: 2
  },
  connection: {
    host: '127.0.0.1',
    database: 'test'
  },
  acquireConnectionTimeout: 100
});

// Start two transactions so that the pool is filled.
_.times(2, (idx) => {
  knex.transaction(() => {
    return Promise.delay(500);
  }).then(() => {
    console.log(`transaction ${idx} ended`);
  });
});

knex.raw('select 1').catch(() => {
  console.log('query failed as expected because of acquireConnectionTimeout');
});

setTimeout(() => {
  // By the time this is called, all the transactions should have been committed and
  // the connections returned to the pool, but the connection for which the acquireConnectionTimeout
  // was called, was never returned to the pool.
  console.log('connections in use:', knex.client.pool._inUseObjects.length, 'should be 0 right?');
}, 1500);
```

**Comment by koskimas** [comment]
Could [this line](https://github.com/tgriesser/knex/blob/master/src/client.js#L234) be the culprit? From what I understand from the pool's docs, aquire method returns a boolean, for which the line above calls `abort`.

**Comment by tgriesser** [comment]
Sounds like a bug. Thanks for the test case, will look to get this tested/patched soon... I think I must've missed the tickets where the abort stuff was added, I'll dive into it soon and see if I can figure it out.

**Comment by koskimas** [comment]
I actually looked into it already and there seems to be no good way to fix this using the generic-pool since it has no way to abort connection acquires. In addition generic-pool doesn't have a built-in acquire timeout so that timeout stuff could be moved inside the pool.

There is a issue for both of these problems in generic-pool repository, but they are not fixed. There are even pull requests for them that a have been around for quite some time. generic-pool doesn't seem to be that well maintained anymore.

Because of these reasons and the fact that our server is pretty much useless at the moment because of the pool bugs, I wrote my own pool [Tarn.js](https://github.com/Vincit/tarn.js) that only has the needed features. [Here's](https://github.com/koskimas/knex/commit/16d2683c2a128cf472375a600299b23ce6ef13f5) a commit that patches knex to use it.

I was going to create a pull request and start a discussion if Tarn.js could be used as knex's default pool. I'm committed to molding Tarn.js to serve knex.js as well as possible and writing a comprehensive test suite for Tarn and even knex so that bugs like this never surface again. Knex is the sole reason I wrote it. I'm also happy to give you push rights to the repo if you want.

What do you think?
