### ISSUE TITLE
is it possible to know wait for transaction to commit from transaction object inside callback?

### ISSUE THREAD

**Issue by helios1138** [tgriesser/knex#1705]
If I have a code like this:

``` js
transaction(trx => {
  something().transacting(trx);
})
.then(() => console.log('commited'))
```

can I use `trx` object to somehow know when transaction is finished (I need to do this inside the callback)? 

One would expect something like `trx.then()` or `trx.on('commit')` to be possible

**Comment by elhigu** [comment]
I dont know if there is an official way for that. I suppose this could work though..

```js
let transactionPromise = transaction(trx => {
  something().transacting(trx);
  transactionPromise.then(...); // register new handler to trigger when transaction is committed...
})
.then(() => console.log('commited'))
```
