### ISSUE TITLE
Wrong column name in result from sqlite join with subquery

### ISSUE THREAD

**Issue by koskimas** [tgriesser/knex#1706]
On sqlite the result of this query:

```js
knex('A')
  .select('A.id', 'B.id as r')
  .innerJoin(knex('A').as('B'), 'A.aid', 'B.id')
  .then(function (row) {
    console.log(row);
  });
```

is this:

```js
[ { A: 1, r: 2 },
  { A: 2, r: 3 },
  { A: 3, r: 4 },
  { A: 6, r: 7 } ]
```

while on postgres an mysql I get the correct:

```js
[ { id: 1, r: 2 },
  { id: 2, r: 3 },
  { id: 3, r: 4 },
  { id: 6, r: 7 } ]
```

Is there something about sqlite joins that I'm missing, or is this a bug in knex?

**Comment by koskimas** [comment]
Oh, and in my real case I need to join the subquery and cannot simply use `innerJoin('A', 'A.aid', 'B.id')`.

**Comment by tgriesser** [comment]
You probably want:

```js
knex('A')
  .select('A.id', 'B.id as r')
  .innerJoin('A as B', 'A.aid', 'B.id')
  .then(function (row) {
    console.log(row);
  });
```

not:

```js
knex('A')
  .select('A.id', 'B.id as r')
  .innerJoin(knex('A').as('B'), 'A.aid', 'B.id')
  .then(function (row) {
    console.log(row);
  });
```

The latter outputs: 
```sql
select "A"."id", "B"."id" as "r" from "A" inner join (select * from "A") as "B" on "A"."aid" = "B"."id"
```

I'm not sure why sqlite3 driver gives this binding output, however.

**Comment by koskimas** [comment]
I need to use the subquery in the join. In my actual use case the subquery is more complex. So the output is coming from the sqlite driver? Then I probably need open an issue there instead of here.

**Comment by tgriesser** [comment]
Yeah I'm not sure how the columns are mapped to the values on their end... Might be good to reproducing with the raw query against the sqlite3 lib directly without knex to confirm it's the source of the issue.
