### ISSUE TITLE
Postgres array escaping in where clause broken in 0.12

### ISSUE THREAD

**Issue by joshrickert** [tgriesser/knex#1710]
So, I just updated from 0.11.10 to 0.12.2, and it broke one of my queries. I've confirmed that this occurs on 0.12.0 and 0.12.1 as well.

This used to work:
```javascript
query.where('array_field', '&&', [7]);
```

0.11.10 output: (working)
```sql
WHERE "array_field" && '{"7"}'
```

0.12.2 output: (not working)
```sql
WHERE "array_field" && {7}
```

My workaround for now is:
```javascript
query.whereRaw(`"array_field" && '?'`, [[7]]);
```

**Comment by tgriesser** [comment]
Should be fixed in 0.12.3
