### ISSUE TITLE
Generate just expression(s)?

### ISSUE THREAD

**Issue by zam6ak** [tgriesser/knex#1719]
Can Knex query builder be used to generate just expressions?
Similarly to https://hiddentao.com/squel/#expressions

For example, something like:

```
const knex = require('knex')({client: 'pg', debug: true});
const qb = knex.queryBuilder();

const filter = qb.whereIn('f.store_id', [1,2,3,4]);

if (someCondition) {
   filter.whereBetween('votes', [1, 100]);
}

return qb.toString();
// => "f.store_id" IN (1,2,3,4) AND "votes" between 1 and 100
```

**Comment by MarkHerhold** [comment]
I think you are looking for `.toSQL()`. See http://knexjs.org/#Interfaces-Other

**Comment by zam6ak** [comment]
@MarkHerhold I don't think that helps....Again, it generates entire SQL statement with keyword and table name...I just want expressions in WHERE clause, not the entire statement....

**Comment by elhigu** [comment]
I don't think that is possible to do what you are trying to do. 

Knex doesn't have internal AST like representation of queries, where you could render just parts of the query.

**Comment by zam6ak** [comment]
I think it would be useful feature to have ....
Or at least mention this in the docs somewhere...
