### ISSUE TITLE
global leak detected: __core-js_shared__

### ISSUE THREAD

**Issue by uzysjung** [tgriesser/knex#1720]
It occurred knex version 0.12.x only  when I use hapijs/lab

this is related with this issue 
https://github.com/tgriesser/bookshelf/issues/1044

polluting namespace.

**Comment by tgriesser** [comment]
I don't think there's much we can do about this until we move to supporting exclusively node 6+, seems the best thing to do for now is ignore it: https://github.com/babel/babel-loader/issues/152

**Comment by nlemoing** [comment]
Can this be re-opened for v0.15.0 since support for node v4 and v5 is being dropped?
