### ISSUE TITLE
Can't get schema builder to execute

### ISSUE THREAD

**Issue by drekka** [tgriesser/knex#1722]
I have the following code:

    var Promise = require('bluebird');
    var Knex = require('knex');
    var merchantsDB = Knex({
        debug: true,
        client: 'sqlite3',
        connection: {
           filename: "./merchants.db"
        },
        useNullAsDefault: true
    });

    console.log("Creating database files ...");
    merchantsDB.schema.createTable('users', function (table) {
        console.log("Creating ...");
        table.increments();
        table.string('name');
        table.timestamps();
    });

My problem is that the 'Creating ...' log entry is never logged and the database and table are never created. 

I've spent hours looking at the doco and trying all sorts of things, but I cannot get it to execute.

Whats wrong?

**Comment by wubzz** [comment]
@drekka You're missing an "execution trigger". Right now it's just a query builder instance. You need to call `.then`, `.asCallback`, `.toString` or `.toSQL` after `createTable`.

```javascript
merchantsDB.schema.createTable('users', function (table) {
    console.log("Creating ...");
    table.increments();
    table.string('name');
    table.timestamps();
})
.then(() => {})
.catch((error) => {});
```

**Comment by drekka** [comment]
Thanks. That worked. I don't know why. I'm sure I tried adding .then(function(){}), but I also just realised there was a process.exit(0) running as well so I think I was actually killing the script before the code could execute. Grrr!!! :-)
