### ISSUE TITLE
Grouped chain "where" method doesn't work well with arrow function

### ISSUE THREAD

**Issue by vietthang** [tgriesser/knex#1724]
From official documentation:

```
knex('users').where(function() {
  this.where('id', 1).orWhere('id', '>', 10)
}).orWhere({name: 'Tester'})
```

When I change the code to use arrow function instead of old function style, like this:

```
knex('users').where(() => {
  this.where('id', 1).orWhere('id', '>', 10)
}).orWhere({name: 'Tester'})
```

I got ```TypeError: Cannot read property 'where' of undefined``` on the second line. Seem like knex don't pass ```this``` to the function if it is arrow function.

Beside with this behavior, I propose a new syntax:

```
knex('users').where((query) => {
  return query.where('id', 1).orWhere('id', '>', 10)
}).orWhere({name: 'Tester'})
```

which pass the old ```this``` as first parameter of the function so it feels more functional. Also we can keep ```this``` reference to keep backward compatible.

**Comment by elhigu** [comment]
It already works like that

**Comment by elhigu** [comment]
I didn't see that documented though... maybe all examples of subqueries should be changed to use the arrow function compatible way.

**Comment by vietthang** [comment]
Thanks. I just test and it actually works that way.

**Comment by chrisbroome** [comment]
Arrow functions in ES6 use lexical `this` instead of function scoped `this`. Here's the failing example with a comment as to why it is failing.

```ES6
// `this` is scoped here instead of inside the arrow function 
knex('users')
  .where(() => { this.where('id', 1).orWhere('id', '>', 10) })
  .orWhere({name: 'Tester'})
```

It's definitely better to avoid using `this` whenever we can, so I'd use the following instead:

```ES6
knex('users')
  .where(qb => qb.where('id', 1).orWhere('id', '>', 10))
  .orWhere({name: 'Tester'})
```

Just thought I'd post the exact reason it was failing in case anyone else runs into this issue.
