### ISSUE TITLE
Migrations with knexfile in different repository

### ISSUE THREAD

**Issue by niksubramanian** [tgriesser/knex#1729]
Hi there,
Amazing work on this library!

**The issue**: running a `knex.migrate.latest()` command in node always assumes that the migration files are located in `___rootdir+'/migrations'`.
**Expected behavior**: a node migration command should take into account the location of your config variable, as it does in the CLI. Alternatively, you should be able to pass a variable to specify the location of the migration folder.
# Simple way of reproducing:
## 1. Original directory structure

```
project_root/
├─package.json
├─server.js
├─config/
│        ├─knex/
│                ├─ knexfile.js
```
## 2. Running CLI

```
$ cd project_root
$ knex --knexfile=./config/knex/knexfile.js migration:make newmigration
```
## 3. New directory structure

```
project_root/
├─package.json
├─server.js
├─config/
│        ├─knex/
│                ├─ knexfile.js
│                ├─ migrations
│                        ├─ newmigration.js
```
## 4. server.js

```
const config = require('./config/knex/knexfile.js');
const env = process.env.NODE_ENV;
const knex = require('knex')(config[env)
knex.migrate.latest()
```
## 5. running server.js

```
Unhandled rejection Error: ENOENT: no such file or directory, /xx/yy/project_root/migrations
```

**Comment by niksubramanian** [comment]
In case someone is facing the same issue, and is looking for a workaround: executing migrations through the CLI seems to be the only way to make this work at the moment:
## Package.json
```
{
    "main": "server.js",
    "scripts": {
        "migrate:down":"knex --knexfile=./config/knex/knexfile.js migrate:rollback",
        "migrate:up":"knex --knexfile=./config/knex/knexfile.js migrate:latest",
  },
```
## CLI
```
$ npm run migrate:up
$ npm run migrate:down
```

If you want to programmatically manage migrations in node, you need to move your ```/migrations``` back to your project ```root_dir```.

**Comment by shadowbrush** [comment]
That is now possible with the `directory` config key. See [the default config]( https://github.com/tgriesser/knex/blob/master/src/migrate/index.js#L26) of the `Migrator`.
