### ISSUE TITLE
application name for postgresql

### ISSUE THREAD

**Issue by ryan-morris** [tgriesser/knex#1738]
I was wondering if it is possible to send the "application name" when making a connection to postgres. I'm not sure if other supported databases have this as an option.

Information on the parameter is available [in the docs](https://www.postgresql.org/docs/current/static/libpq-connect.html#LIBPQ-PARAMKEYWORDS)

If not specified the default value could be the name field from package.json. 

This would be very helpful when troubleshooting issues server side as right now the application_name field is null when running a query like below under postgres:

```
select * from pg_stat_activity;
```

**Comment by tgriesser** [comment]
Yep, in looking at PG's code, it looks like you can specify `application_name` in the connection config. Let me know if this doesn't work

**Comment by ryan-morris** [comment]
so using this format would be unsupported for setting the application_name: 

```
var knex = require('knex')({
  client: 'mysql',
  connection: {
    host : '127.0.0.1',
    user : 'your_database_user',
    password : 'your_database_password',
    database : 'myapp_test'
  }
});
```


but this should work
```
var pg = require('knex')({
  client: 'pg',
  connection: process.env.PG_CONNECTION_STRING,
  searchPath: 'knex,public'
});
```


correct?

**Comment by tgriesser** [comment]
No, the application name is probably falling off. The url parsing needs a bit of work, will try to take a look at it soon

**Comment by cklanac** [comment]
@tgriesser I'm looking to pass the `application_name` as well. Is this issue still on your radar?

**Comment by elhigu** [comment]
@cklanac didn't 

```
connection: {
    host : '127.0.0.1',
    user : 'your_database_user',
    password : 'your_database_password',
    database : 'myapp_test',
    application_name: 'app-name'
  }
```
way work?

Anyways, since this should be already possible I'm closing this one and added issue about fixing connection url parser https://github.com/tgriesser/knex/issues/2354

**Comment by brandonros** [comment]
```
    interface ConnectionConfig {
        host: string;
        user: string;
        password: string;
        database: string;
        domain?: string;
        instanceName?: string;
        debug?: boolean;
        requestTimeout?: number;
    }

```

Does somebody need to update `@types/knex` to support this?

**Comment by elhigu** [comment]
That issue should be filed to @types/knex repo, those typings are not maintained by us.

**Comment by you-fail-me** [comment]
I'm trying to specify application name like
```
connection: {
    host : '127.0.0.1',
    user : 'your_database_user',
    password : 'your_database_password',
    database : 'myapp_test',
    application_name: 'app-name'
  }
```
but it just won't work. knex 0.15.2, pg 9.6.6. Any ideas, how to pass it?

**Comment by kibertoad** [comment]
@you-fail-me See https://github.com/brianc/node-postgres/blob/master/lib/connection-parameters.js
`application_name` seems correct. Can you try debugging and see if your application_name gets set inside the driver? ('pg')

**Comment by kibertoad** [comment]
I'm reopening this since typing are now handled internally and we can fix them.

**Comment by elhigu** [comment]
New issue should be opened for that typing stuff. As I see this was about being able to pass that  `application_name` attribute to the driver in connection string and then hijacked for typing related stuff 
 :)
