### ISSUE TITLE
orderBy subquery

### ISSUE THREAD

**Issue by MarkHerhold** [tgriesser/knex#1744]
Is it possible to add a orderBy statement wrapping a subquery? I see plenty of mentions of further selects on a subquery but nothing involving orderBy.

```sql
SELECT t.*
FROM ( /* my knex query */ ) t
ORDER BY id ASC;
```

**Comment by elhigu** [comment]
do you mean like this?

```
> knex.from(builder => builder.from('foo').orderBy('create').as('t')).orderBy('t.otherCol').toSQL()
{ method: 'select',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [],
  __knexQueryUid: 'e45a8f04-ef30-4408-ab80-6ea53162b198',
  sql: 'select * from (select * from "foo" order by "create" asc) as "t" order by "t"."otherCol" asc' }
> 
```

**Comment by MarkHerhold** [comment]
@elhigu thank you!

**Comment by MarkHerhold** [comment]
@elhigu Do you know how to integrate this into a bookshelf query? When I use it in a bookshelf query, the subquery gets 'compressed' into a single flat query (e.g. the two sorts are still present and simply negate each other).

**Comment by elhigu** [comment]
No idea, maybe @rhys-vdw knows?
