### ISSUE TITLE
problematic handling of postgresql `date` types

### ISSUE THREAD

**Issue by gfarrell** [tgriesser/knex#1750]
I have a column which is of type `date` (i.e. has no time of day). The problem is that when I load a row with knex, it gives it as the previous day in UTC.

## PG: test_table

```
id | date
----------------
 1 | 2016-10-19
----------------
```

## Knex:

```
knex("test_table").where({ id: 1 }).then(([ { date } ]) => console.log(date));
// logs "2016-10-18 23:00:00Z"
```

This causes a lot of my tests to break, but surely there must be a better way of handling `date`s as opposed to `timestamptz`s.

**Comment by elhigu** [comment]
You can tell to pg driver how it should handle date type. Here is info how to do it https://github.com/brianc/node-pg-types
