### ISSUE TITLE
what does +5s mean?

### ISSUE THREAD

**Issue by ColorfulCow** [tgriesser/knex#1754]
i run knex debug and got this:

```
knex:query
      SELECT banner.id,
       banner.title,
       banner.pic_url,
       banner.action_id,
       banner.action_content
      FROM ad_banner AS banner
      WHERE  banner.location_id = ?
        AND banner.target = ?
        AND (UNIX_TIMESTAMP(current_timestamp()) between banner.online_time and banner.offline_time)
      ORDER BY banner.manual_score DESC, banner.sys_score DESC LIMIT 5 +5s
```
does this means that sql executed took 5s? why i got this? I am confused about this

**Comment by MarkHerhold** [comment]
That's output from the [debug module](https://www.npmjs.com/package/debug). I believe that it means that 5 seconds elapsed from the last line output from the debug module.

**Comment by ColorfulCow** [comment]
@MarkHerhold  i have a api using  knex(db).raw(`above sql`), while i test this api concurrently, it often took 5000+ms  then i can got the response

**Comment by ColorfulCow** [comment]
@MarkHerhold i have an api using knex(db).raw(the above sql), when i test this api concurrently, it often took 5000+ms then i can got the response

**Comment by elhigu** [comment]
AFAIK @MarkHerhold's answer is correct
