### ISSUE TITLE
returningRaw?

### ISSUE THREAD

**Issue by emrul** [tgriesser/knex#1756]
I've noticed there are a number of *raw functions but there's one I needed and haven't found: returningRaw.

(Using Postgres) I have a query like:
`knex("table").insert(sqlValues).returning(["encode(int8send(myid), 'base64') AS id"]);`
and the encode function gets escaped.

**Comment by coockoo** [comment]
@emrul Did you try using `.returning(knex.raw('raw_expression here'))`?

**Comment by emrul** [comment]
@coockoo that does the trick! Thanks
