### ISSUE TITLE
having not behaving as expected

### ISSUE THREAD

**Issue by RWOverdijk** [tgriesser/knex#1771]
I've found two things missing regarding `having`.

1. orHaving isn't documented
2. nested doesn't seem to work

```js
.having(function() {
  this.having('id', '<', 20);
  this.orHaving('id', '>', 6);
});
```

this completely ignores the two nested calls.

Are these two issues known? What can I do to help?

**Update**: I know I could chain the two methods, but in my case I can't.

**Comment by friend0** [comment]
Wondering why this hasn't been addressed yet - I'm seeing the same issue in v13

**Comment by elhigu** [comment]
@friend0 because there are too few contributors right now to take care everything, closing in favor of #2274
