### ISSUE TITLE
[Migration] Lock system?

### ISSUE THREAD

**Issue by stouf** [tgriesser/knex#1772]
I was looking for some data schema migration tools for Node.js when I found Knex.js.
Knex.js meets most of the requirements I have but there is one thing I noticed but couldn't find anywhere in the documentation: a lock system that would prevent multiple processes to run the same migration on a database. I noticed that, if I set `_migrations` as the table designed to store the migration state of my data, then a `_migrations_lock` table is implicitly created.
As I said, I could not find anything about it in the documentation; I don't know what this does and so, I don't know what to expect from it.
Could we get more information about this ?

**Comment by chadxz** [comment]
It sounds like you understand it pretty well! What would you like clarified?

**Comment by stouf** [comment]
> It sounds like you understand it pretty well!

Hehe Thanks for confirming and also thank you for your quick answer, I really appreciate :)

> What would you like clarified?

First of all, I wanted to get the confirmation that such a mechanism is implemented (what about mentioning it in the documentation by the way?)

Then, I'd like to know if I can rely on this mechanism in an architecture where the same code gets deployed on multiple servers. I'm particularly thinking about race conditions.
I took a look at the code and it seems that the algorithm is more or less:

1. Query the database to know if there is a lock
2. If no lock, then lock and start running a batch of migrations.

Is this correct? If yes, I'm worried about a scenario where we would for example have 2 server instances - let's call them A and B - with the code, doing the following:

1. Database not locked
2. A queries the database to know if it's locked
3. B queries the database to know if it's locked
4. A receives the response from the database: `is_locked = 0` and locks it with `is_locked = 1`
5. B receives the response from the database: `is_locked = 0` and locks it with `is_locked = 1`
6. Both A and B think they could acquire the lock and start running the same batch of migrations.

Is this a possible scenario or am I missing something?

**Comment by elhigu** [comment]
@stouf Mechanism does exist. 

Indeed the system only tries to get lock before running the migrations and if it cannot get lock, it waits until lock is received.

After getting lock it runs the migrations.

It is made sure that lock cannot be received by multiple clients at once by using ´select for update´ which causes database to lock the access for the row until the transcation is completed. If second client is trying to get the lock at the same time, query will hang until row lock is released by the db.

One caveat in this system is that if your migration crashes during the execution and never returns, then migration lock is left in the table and one has to clear it manually.

Documentation pull requests are always welcome!

**Comment by stouf** [comment]
@elhigu Thanks for your feedback!

> It is made sure that lock cannot be received by multiple clients at once by using select ... for update which causes database to lock the access for the row until the transcation is completed. If second client is trying to get the lock at the same time, query will hang until row lock is released by the db.

Awesome! I missed that `SELECT ... FOR UPDATE` part. Very glad to read that ! =D

> Documentation pull requests are always welcome!

I will definitely do! I wanted to get confirmation of my guesses first. Thanks a lot for being this responsive! :)

**Comment by stouf** [comment]
https://github.com/knex/documentation/pull/10 :) :) :)

**Comment by Crusader4Christ** [comment]
We use knex migrations in docker image. Our system try to start image with migrations first and applications second. Sometimes migrations don`t unlocks. Can we disable locking at all? (we can`t start migrations several times). It is very annoing to ask system admin to unlock the db

**Comment by Crusader4Christ** [comment]
docker image starts like `sails-migrations migrate && sails lift` 
Does `forceFreeMigrationsLock` can be runned from cli ?
