### ISSUE TITLE
`anonymous` result object constructor

### ISSUE THREAD

**Issue by halt-hammerzeit** [tgriesser/knex#1774]
I'm using knex with PostgreSQL.
For the results i'm getting this:

```js
anonymous {
  id: '46',
  created_at: 2016-08-27T00:37:01.209Z,
  revoked_at: 2016-10-01T17:49:40.551Z,
  user: '3' }
```

Seems that `result.constructor` is some `[Function anonymous]` which is strange.
Why is it `anonymous`?

```js
$ var a = {}
> undefined
$ a.constructor
> Object() { [native code] }
```

**Comment by rawrmaan** [comment]
I'm getting this with Postgres too. Very strange! It seems to happen when I do an `insert`.

**Comment by ricardogama** [comment]
Duplicated of brianc/node-postgres#1062

**Comment by rawrmaan** [comment]
Yep and https://github.com/brianc/node-postgres/issues/1131. This is a non-issue. Thanks guys.
