### ISSUE TITLE
countDistinct support for multiple columns

### ISSUE THREAD

**Issue by tayden** [tgriesser/knex#1776]
countDistinct currently only supports counting the distinct values in a single column, while the distinct method supports finding distinct rows using multiple attributes. It would be great if countDistinct also supported multiple attributes.

With a postgres backend, the following happens

```js
knex('customers')
  .distinct('first_name', 'last_name')
  .select();
// select distinct "first_name", "last_name" from "customers"

knex('customers')
  .countDistinct('first_name', 'last_name');
// select count(distinct "first_name") from "customers"
```

It'd be nice if instead the countDistinct query produced
`select count(distinct("first_name", "last_name")) from "customers"`

**Comment by acabrera91** [comment]
Same problem here.

**Comment by rkmax** [comment]
I have the same problem here

btw, Happy new year!!

**Comment by ikari-pl** [comment]
I would need this too...

**Comment by blackmatch** [comment]
I would need this too
