### ISSUE TITLE
Transactions/Rollbacks don't work

### ISSUE THREAD

**Issue by mxii** [tgriesser/knex#1786]
```JS
   db.transaction(function (trx) {
      return trx
         .insert({ any: 'test' })
         .into('Table1')
         .then(() => {
            throw "ERROR!";
            return trx
               .insert({ any: 'test' })
               .into('Table2');
         });
   })
   .then(() => console.log('done!'))
   .catch(err => console.log('rolled back', err));
```

I am using a `mysql` database.
knex-version: 0.12.6
mysql-version: 2.12.0

getting this on console: `rolled back ERROR!` as expected!
BUT in my `Table1` was a row inserted.

**DEBUG:**

```
  knex:tx trx7: Starting top level transaction +4s
  knex:pool INFO pool mysql:mysql:client0 - dispense() clients=1 available=2 +2ms
  knex:client acquired connection from pool: __knexUid1 +1ms
  knex:query BEGIN; +5ms
  knex:bindings undefined +1ms
  knex:query insert into `Table1` (`any`) values (?) +27ms
  knex:bindings [ 'test' ] +1ms
  knex:query ROLLBACK; +12ms
  knex:bindings undefined +1ms
  knex:tx trx7: releasing connection +3ms
  knex:client releasing connection to pool: __knexUid1 +0ms
  knex:pool INFO pool mysql:mysql:client0 - dispense() clients=0 available=2 +1ms
rolled back ERROR!
```

I would expect that there is NO row..
Am I doing something wrong?
Missing something?

Thanks.

**Comment by mxii** [comment]
Found this: `By default, MySQL runs with autocommit mode enabled. This means that as soon as you execute a statement that updates (modifies) a table, MySQL stores the update on disk to make it permanent. The change cannot be rolled back.

To disable autocommit mode implicitly for a single series of statements, use the START TRANSACTION statement:`

Here: http://dev.mysql.com/doc/refman/5.7/en/commit.html

**Comment by mxii** [comment]
Mh, tried with `START TRANSACTION` and  `SET autocommit=0` ..
No success..

Any ideas?

**Comment by mxii** [comment]
MySQL's global setting `autocommit` is `OFF`.

**Comment by mxii** [comment]
Finally got it.. damn!

Storage-engine was `MyISAM` which doesn't support transactions......... :/

**Comment by sayhicoelho** [comment]
@mxii How did you change default storage engine globally? I need to set `table.engine('InnoDB')` on every table migration?
