### ISSUE TITLE
Allow optional capitalization of SQL keywords

### ISSUE THREAD

**Issue by vjpr** [tgriesser/knex#179]
When logging SQL statements I find it easier to see whats going on if keywords are capitalized. ActiveRecord capitalizes too.

At the moment all keywords are hard-coded lowercase.

Keywords should be wrapped to allow customization.

**Comment by c0b** [comment]
:+1:

**Comment by elhigu** [comment]
IMO it would be bad idea to implement this for current knex. It would require pretty much complete rewrite for knex internals. Closing as issue is very old and hasnt been very popular and I dont see that there is a chance to implement this in a way that it would be well tested as well.
