### ISSUE TITLE
Knex.js auto escapes typecasts in postgresql

### ISSUE THREAD

**Issue by pc-magas** [tgriesser/knex#1790]
I have the following piece of code:

`````
var table='weather';
var query=db.column(table+'.id',table+'.date',table+'.temperature_max',table+'.temperature_min','city.name','city.country')
            .select()
            .withSchema('public')
            .from(table)
            .join('city',table+'.city_id','city.id')
``````

And the problem is that when I try to typecast the column date it automatically escapes in incorrectly therefore it results to execute the wrong query. I tried the following:

```
  var table='weather';
    var query=db.column(table+'.id',table+'.date::varchar',table+'.temperature_max',table+'.temperature_min','city.name','city.country')
            .select()
            .withSchema('public')
            .from(table)
            .join('city',table+'.city_id','city.id')
````
And gives me this error:

````
Unhandled rejection error: select "weather"."id", "weather"."date::varchar", "weather"."temperature_max", "weather"."temperature_min", "city"."name", "city"."country" from "public"."weather" inner join "public"."city" on "weather"."city_id" = "city"."id" where "weather"."date" = $1 order by "weather"."date" ASC - column weather.date::varchar does not exist
    at Connection.parseE (/home/pcmagas/Holy Code/src/node_modules/pg/lib/connection.js:554:11)
    at Connection.parseMessage (/home/pcmagas/Holy Code/src/node_modules/pg/lib/connection.js:381:17)
    at Socket.<anonymous> (/home/pcmagas/Holy Code/src/node_modules/pg/lib/connection.js:117:22)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)
````

I think we need somehow to tell either via a flag or something else like selectRaw(columns) or columnRaw() that will append the select statement with whatever are columns are without try any sort of escaping.

So you can do the following

```
var table='weather';
var query=db.column(table+'.id',table+'.temperature_max',table+'.temperature_min','city.name','city.country')
.columnRaw(table+'.date::text')
            .select()
            .withSchema('public')
            .from(table)
            .join('city',table+'.city_id','city.id')
````

And that will create the query:

``````
 select "weather"."id", "weather"."date"::text, "weather"."temperature_max", "weather"."temperature_min", "city"."name", "city"."country" from "public"."weather" inner join "public"."city" on "weather"."city_id" = "city"."id"
``````

**Comment by elhigu** [comment]
Knex column identifiers does not havr any support for typecasting, raw is needed. 

Im surprised that the columnRaw version of the query works... As far as i know it should output weather.date::text instead of "weather"."date"::text 

Sorry for the missing formatters etc. and being brief, responded from mobile...

**Comment by elhigu** [comment]
Closing since this is not really a bug, but knex just doesn't support casting for identifiers. That and telling if certain input should be identifier or value and what type of value are weak points in knex currently. My earlier comment why it didn't output weather.date::text is because it wasn't in knex.raw...

**Comment by elhigu** [comment]
Also one can circumvent that problem with knex.raw('??::cast', ['mytable.mycolumn'])
