### ISSUE TITLE
Knex Dialect Throwing a strange error

### ISSUE THREAD

**Issue by larquin** [tgriesser/knex#1791]
Hi there- 

Pretty new to Knex and Node, so this may be just a typo/issue on my part, but I'm a little confused about the internal workings of knex so I'm not certain if this is a real bug. 

I'm unable to run `knex migrate:latest`,  I'm getting the following error: 

```
Error: Cannot find module './dialects/[object KnexClient]/index.js'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Knex (~/Projects/homebot/api/v2/node_modules/knex/lib/index.js:55:15)
    at initKnex (~/.nvm/versions/node/v6.4.0/lib/node_modules/knex/bin/cli.js:69:10)
    at Command.<anonymous> 
```

When I dig into the source code, the error generated at `knex/lib/index.js:55:15` seems to stem from the `config` object. Is this just a naming issue, or did I find a real regression?

**Comment by elhigu** [comment]
you might have stored actual KnexClient instance reference somehow to `config.client` can you put your knexfile here? We cannot help you much without being able to reproduce the problem.

**Comment by larquin** [comment]
Yeah I think that is what happened. I re initialized my knexfile and that seemed to fix it. Closing, thanks!
