### ISSUE TITLE
Knex.js raw() method returns additional data

### ISSUE THREAD

**Issue by nicholaswmin** [tgriesser/knex#1802]
I'm running a query using the `.raw()` method, using MySQL as the DB.

Instead of returning the results of the query *only*, it also includes in the results some additional data I don't really need:

### Query

```sql
const query = SELECT idFoo AS "Foo",  DATE_FORMAT(bar, "%m/%d/%Y") AS "Bar" FROM baz
```

and then:

```javascript
db.raw(query)
.then((rows) => {
  resolve(rows)
})
.catch((err) => reject(err));
```

### Result

```javascript
[
 // actual results I need
  [ 
    {
      "Foo": "hqbmu",
      "Bar": "02/04/2002"
    }
  ],
 // unnecessary info
  [
    {
      "catalog": "def",
      "db": "mydb",
      "table": "baz",
      "orgTable": "baz",
      "name": "Foo",
      "orgName": "idFoo",
      "charsetNr": 33,
      "length": 135,
      "type": 253,
      "flags": 4097,
      "decimals": 0,
      "zeroFill": false,
      "protocol41": true
    },
    {
      "catalog": "def",
      "db": "",
      "table": "",
      "orgTable": "",
      "name": "idBar",
      "orgName": "",
      "charsetNr": 33,
      "length": 30,
      "type": 253,
      "flags": 0,
      "decimals": 0,
      "zeroFill": false,
      "protocol41": true
    }
  ]
]
```

**Note:** I've replaced some sensitive table/column names in the output I've posted here.

**Comment by wubzz** [comment]
This is driver-level stuff. Using the builder it will parse the response for you, but `raw` is exactly that: **raw**.

For example if you were to use plain `pg` module using `client.query`, you would get the same result as described in the issue. Maybe one could make an option to raw to have it send the result through the same parser as the builder, but currently that does not exist.

**Comment by nicholaswmin** [comment]
Makes sense - closing
