### ISSUE TITLE
Use knex as a query builder only

### ISSUE THREAD

**Issue by adriano-di-giovanni** [tgriesser/knex#1807]
Is it possible to use knex to generate SQL strings only?

**Comment by xxxtonixxx** [comment]
Is it possible? Or is absolutely necessary connect to a database?

**Comment by elhigu** [comment]
`toSQL()` would be safer choice, since `toString()` doesn't allow to use parameter binding in driver level.

**Comment by xxxtonixxx** [comment]
@elhigu  but if I only want to use it as query builder, do I need the sql driver (mysql, sqlite3, etc.)? Thanks for your information! 😃
