### ISSUE TITLE
Change auto increment starting number

### ISSUE THREAD

**Issue by sudo-suhas** [tgriesser/knex#1809]
Is there a better way to change the auto increment starting number other than the following:

```js
knex.schema.createTable('my_tbl', table => {
    table.increments('id').primary()
        .comment('Auto-generated id');
    // Other columns
}).then(() => {
    knex.schema.raw('ALTER TABLE my_tbl AUTO_INCREMENT = 100000')
})
```

I am working with mysql, referenced [this](http://stackoverflow.com/questions/970597/change-auto-increment-starting-number) for the alter statement.

**Comment by elhigu** [comment]
AFAIK raw is the only way for setting sequence value.

You seem to have error in that code though... you are missing `return` from the raw call so that `raw` query is only built but never executed.

Also this might work:  

```js
exports.up = function (knex) {
  return knex.schema.createTable('my_tbl', table => {
      table.increments('id').primary().comment('Auto-generated id');
      // Other columns
  }).raw('ALTER TABLE my_tbl AUTO_INCREMENT = 100000');
};
```

**Comment by sudo-suhas** [comment]
Okay. And thank you.
