### ISSUE TITLE
babel-plugin-lodash 3.2.10 dropped node 0.12 support

### ISSUE THREAD

**Issue by elhigu** [tgriesser/knex#1811]
We need to decide what do with this. For now I just hardcode version 3.2.9 to be used forever. https://github.com/lodash/babel-plugin-lodash/issues/148

**Comment by MarkHerhold** [comment]
Node.js v0.12 LTS support ends December 31st, so I recommend dropping 0.12 support at the same time.

**Comment by wubzz** [comment]
Closing, we already dropped 0.12
