### ISSUE TITLE
Stored Procedure

### ISSUE THREAD

**Issue by Drjonees** [tgriesser/knex#1820]
Hi!
I've created a stored procedure on my ms sql db that i want to execute.

Can i use knex for this?

I have tried with:
`  db().raw('EXEC STORED_PROCEDURE_NAME')
  .then(result => {
    callback(null, result);
  })
  .catch(error => {
    callback(error);
  });
`

db is knex({DATABASE_INFO})

but i'm getting "db(...).raw is not a function"

**Comment by elhigu** [comment]
you should call db.raw, not db().raw
