### ISSUE TITLE
Automatically GROUP BY fields on aggregation clauses as SQL standard suggest

### ISSUE THREAD

**Issue by calebeaires** [tgriesser/knex#1827]
As defined in the SQL standard, when grouping, you may no longer project any columns that are not a formal part of the GROUP BY clause, or aggregate functions.

I have made test on Oracle, MSSql and Mysql. All of then ask to group those fields that are not in the aggregations clauses, but Knex don`t do this by default.

on KnexJS if i do this:

```JavaScript
knex('users').select('name', 'city').avg('age').toString()
```
Result on this

```Sql
SELECT `name`, `city`, AVG(`age`) FROM `users`
```
Maybe, as SQL standard says to, the result could be

```Sql
SELECT `age`, `city`, `name`, AVG(`age`) FROM `users` GROUP BY `city`, `name`
```

Is there some workaround on KnexJS that automatically add non aggregated fields to GROUP BY when using AGGREGATIONS clauses.

**Comment by atiertant** [comment]
@calebeaires knex is a query builder not an orm...

**Comment by calebeaires** [comment]
@atiertant Mays you help me find an "function" that could check non use aggregators on fields to put then on a group by clause?

**Comment by atiertant** [comment]
@calebeaires all depend on how do you use knex, what are you doing with?

**Comment by calebeaires** [comment]
I am developing an visual builder sql that gives user power to drag and drop fields on painel, then knexJS works on backend to build sql statements. 

This app is not to call/connect on databases. It is just to build statements. This will help people nom experts to easily construct sql statements.

I will make exceptions with ``if`` and ``else if`` to find when this user user aggregations clauses. With this I will automatically pull group by when needed, as SQL Standards says to.

**Comment by atiertant** [comment]
@calebeaires if you only make select, this could work but for more complex query, some dialect will translate them in many queries... if you pass an array to groupBy(), you could keep a reference on it and then check if column is here or not

**Comment by calebeaires** [comment]
Cool!

I will walk on this way
