### ISSUE TITLE
table.unique should take an optional key-identifier as a second parameter

### ISSUE THREAD

**Issue by stringbeans** [tgriesser/knex#1829]
It would be nice to be able to do:

`table.unique(['table_id', 'secondary_id'], 'custom-key-identifier')`

currently, depending on the length of the table name already, this statement will fail due to the identifier name being too long due to how knex auto-generates the identifier

**Comment by stringbeans** [comment]
actually, this would be nice for all functions that add a key/constraint (ie. `table.foreign()`)

**Comment by dhensby** [comment]
Pretty sure this is done and can be closed

**Comment by elhigu** [comment]
I will take this in consideration while writing updated schema API
