### ISSUE TITLE
Out of date dependency causes breaking changes

### ISSUE THREAD

**Issue by wgottschalk-RMS** [tgriesser/knex#1831]
In knex v11.5 we had to take advantage of the fact that conn.client.pool was an event emitter. However, in knex v12.6 uses an out of date verison of [node-pool](https://github.com/coopernurse/node-pool/tree/master) which is not an event emitter. The new version of node-pool is implemented as an event emitter. I realize that node-pool is, for the most part, an undocumented part of the knex API but that package should be upgraded since it can cause breaking changes in an application.

**Comment by wubzz** [comment]
Closing since `generic-pool` is no longer used in this lib.
