### ISSUE TITLE
Postgres Named Bindings Issue

### ISSUE THREAD

**Issue by patrickdevivo** [tgriesser/knex#1832]
Maybe I'm misunderstanding something obvious, but I seem to be having trouble getting named bindings to work (`postgres` dialect) and if i'm not mistaken the example code in the documentation seems to be failing as well.

<img width="876" alt="knex_binding" src="https://cloud.githubusercontent.com/assets/57259/21238503/586ed690-c2d1-11e6-84e0-a23e26dfa3c1.png">

My query is rather long, so I won't paste it here, but the issue seems to be with using named bindings both as values and identifiers (perhaps?) in a query.

My query has one parameter, a table name that is sometimes used as an identifier and sometimes used as a value throughout the query, and so I would assume something like:

`.raw(QueryText, {table: tableName})` where within `QueryText` I use both `:table:` and `:table` should work fine, but I'm encountering the following error:

`Error: Undefined binding(s) detected when compiling RAW query:` which is the same as what's in the current docs.

Any thoughts?

**Comment by elhigu** [comment]
Using the same binding as value and identifier seems to work for me:

```js
knex = require('knex')({client: 'pg'});
knex.raw(':name: :name', { name: 'wat' }).toSQL();

{ method: 'raw',
  sql: '"wat" ?',
  bindings: [ 'wat' ],
  options: {},
  __knexQueryUid: 'bcd81b2c-3491-4462-8845-6fd905db5aac' }
```

Can you show me the query that fails? Sounds like you are just passing undefined value to some binding... maybe typo somewhere?
