### ISSUE TITLE
Problem in converting boolean values to 0 / 1 on select queries in sqlite3

### ISSUE THREAD

**Issue by rafakx** [tgriesser/knex#1842]
I trying do selects in sqlite3 database using boolean values, but the Knex don't transform the boolean values in 1 or 0, type that sqlite use for boolean.
What i do to solve this? There is a method that intercept the selects to change this values to 1 / 0?

Log of select: 

```
bindings:Array[1]
    0:"true"
    length:1
method:"select"
sql:"select * from "serviceType" where "active" = ? order by "description" asc"
```

Thanks!

**Comment by elhigu** [comment]
Because https://www.sqlite.org/datatype3.html sqlite3 doesn't have boolean type. It is just an integer.

**Comment by elhigu** [comment]
Ah sorry, I just read your question badly. 

Anyways knex doesn't have any mapper which would convert values / column names etc. to be something different that is passed to underlying db driver. I would say that in this case the conversion would be responsibility of sqlite3 driver.
