### ISSUE TITLE
how to debug db query durations?

### ISSUE THREAD

**Issue by brian-mann** [tgriesser/knex#1844]
I don't see any easy way to log out how long each query duration took.

Am I missing something?

I'm looking for a way to see how long the database took to return results per query.

**Comment by elhigu** [comment]
I've done that with knex.on('query' ...), .on('query-error', ...) and .on('query-response', ...) events. 

http://knexjs.org/#Interfaces-Events

**Comment by elhigu** [comment]
I added example code how to trace transaction durations https://runkit.com/embed/679qu91ylu4w
