### ISSUE TITLE
Add cordova sqlite delict 

### ISSUE THREAD

**Issue by jahead** [tgriesser/knex#1845]
Hey, conversation's from the gitter channel, people were interested in seeing cordova-sqlite-storage being integrated into knex. If this is not going to be an option, just ignore what I'm about write and close.

So there is a number of issues for this to be solved for this. 
The first of getting the delict working is done with my WIP Implementation of the cordova sqlite delict. 

Which is basically a copy of the sqlite one with minor changes due to the fact the interface of cordova-sqlite-storage does not map directly with the old Web SQL or the sqlite driver. 
see https://github.com/litehelpers/Cordova-sqlite-storage

Basically this is around initialisation of the database connection. 
I also had to introduce a connection pool to the browser because cordova is basically an app running webview and cordova-sqlite-storage does not like you opening the connection multiple times. 

The second issue is the knex's migration stuff. 
For this it's probably easier for us to ship this through a cordova plugin and using the hooks to do some stuff before the app is ran. I don't actually have a solid solution for this. And I don't know if we should bother with this until the delict is integrated?

Lastly tests.
Not sure how to run test's for this. because they will need to run in the context of a cordova app.  

If this something community wants, I'll post my implemention as a fork. I'll probably have to rebase and fix any issues :/. Sorry about the late issue creation, work's been flat out, but now I'm on holidays so I should be able to focus time on getting this integrated.

**Comment by kibertoad** [comment]
@jahead New dialects will not be added to knex, see https://github.com/tgriesser/knex/blob/master/CONTRIBUTING.md -> "https://github.com/tgriesser/knex/blob/master/CONTRIBUTING.md". Instead they should be implemented as separate npm packages. Should you create one, please let us know, we'll link to it from our documentation!
