### ISSUE TITLE
How to list tables present in a database?

### ISSUE THREAD

**Issue by elliothilt** [tgriesser/knex#1849]
I am going through documents but couldn't figure out any method which is equivalent to show tables command. Is it possible with knex.js?

**Comment by abhishekbhardwaj** [comment]
Related issue: https://github.com/tgriesser/knex/issues/360. It'll be supported in 0.13.

If you need it now, take a look at: https://www.npmjs.com/package/knex-list-db-table

**Comment by elhigu** [comment]
thanks @abhishekbhardwa for answering this!
