### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by smitt04** [tgriesser/knex#1851]
I am using knex 0.12.6 and node 6.9.1 and there seems to be a problem with where clauses and functions.

With a simple query:
```js
const query = knex('store')
  .where(function where() {
    this.where('id', 1);
  })
  .toSQL();
```

It doesn't even get in the where callback it errors before.

```
RangeError: Maximum call stack size exceeded
    at Object.containsUndefined (/srv/dp/api/current/node_modules/knex/lib/helpers.js:97:27)
    at Object.containsUndefined (/srv/dp/api/current/node_modules/knex/lib/helpers.js:115:35)
    at Object.containsUndefined (/srv/dp/api/current/node_modules/knex/lib/helpers.js:115:35)
    at Object.containsUndefined (/srv/dp/api/current/node_modules/knex/lib/helpers.js:115:35)
    at Object.containsUndefined (/srv/dp/api/current/node_modules/knex/lib/helpers.js:115:35)
    at Object.containsUndefined (/srv/dp/api/current/node_modules/knex/lib/helpers.js:115:35)
    at Object.containsUndefined (/srv/dp/api/current/node_modules/knex/lib/helpers.js:115:35)
    at Object.containsUndefined (/srv/dp/api/current/node_modules/knex/lib/helpers.js:115:35)
    at Object.containsUndefined (/srv/dp/api/current/node_modules/knex/lib/helpers.js:115:35)
    at Object.containsUndefined (/srv/dp/api/current/node_modules/knex/lib/helpers.js:115:35)
    at Object.containsUndefined (/srv/dp/api/current/node_modules/knex/lib/helpers.js:115:35)
    at Object.containsUndefined (/srv/dp/api/current/node_modules/knex/lib/helpers.js:115:35)
    at Object.containsUndefined (/srv/dp/api/current/node_modules/knex/lib/helpers.js:115:35)
    at Object.containsUndefined (/srv/dp/api/current/node_modules/knex/lib/helpers.js:115:35)
    at Object.containsUndefined (/srv/dp/api/current/node_modules/knex/lib/helpers.js:115:35)
    at Object.containsUndefined (/srv/dp/api/current/node_modules/knex/lib/helpers.js:115:35)
    at Object.containsUndefined (/srv/dp/api/current/node_modules/knex/lib/helpers.js:115:35)
    at Object.containsUndefined (/srv/dp/api/current/node_modules/knex/lib/helpers.js:115:35)
    at Object.containsUndefined (/srv/dp/api/current/node_modules/knex/lib/helpers.js:115:35)
    at Object.containsUndefined (/srv/dp/api/current/node_modules/knex/lib/helpers.js:115:35)
    at Object.containsUndefined (/srv/dp/api/current/node_modules/knex/lib/helpers.js:115:35)
    at Object.containsUndefined (/srv/dp/api/current/node_modules/knex/lib/helpers.js:115:35)
```

It may be similar to #1725 but upgrading to latest knex did not fix the issue.

**Comment by wubzz** [comment]
@smitt04 What dialect is this reproduced with? I've been running knex 12.6 and node 6 in production for months without having this issue, so thinking it could be dialect specific.

**Comment by smitt04** [comment]
this is `mysql`. Let me see if i can get a test.

**Comment by smitt04** [comment]
It took me a while but i finally was able to replicate it. I couldn't get a simple project to replicate it, so i kept on adding to it until it got closer and closer to my project structure. Unfortunately it is a little complex involving an http server and graphql. But i tried to make it as simple as possible.

Here is the simplest project i could create to replicate it.
[knexTest.zip](https://github.com/tgriesser/knex/files/686049/knexTest.zip)

Steps to test:

1. run `npm install`
2. run app `node app.js`
3. navigate to http://localhost:8000/graphql?query=%7B%0A%20%20query%0A%7D

That should execute the simple graphql query an return the error. You will also be able to see the stack trace in the terminal.

I suspect it is a problem with domains but not sure. Let me know if you have any questions or still can't reproduce.

**Comment by elhigu** [comment]
This seems to be the minimal testcase

```
npm install knex sand-http
```

```js
const knex = require('knex')({ client: 'mysql' });
const http = require('sand-http');
const query = knex('store')
  .where(function () {
    this.where('id', 1);
  })
  .toSQL();
```

**Comment by smitt04** [comment]
You are right, that is much shorter. So i looked into `sand-http` to try and figure why it was causing this issue, as it doesn't do anything by just requiring it.

It turns out it was because of 

```js
require('generator-bind').polyfill();
```

so by changing out `sand-http` for `generator-bind` causes the same issue.

```js
const knex = require('knex')({ client: 'mysql' });
require('generator-bind').polyfill();
const query = knex('store')
  .where(function () {
    this.where('id', 1);
  })
  .toSQL();
```

**Comment by smitt04** [comment]
It is weird that the `generator-bind` is causing this issue. Removing it fixes it, so i will do that for now. I will let you decide if you think this is still an issue or not.

**Comment by wubzz** [comment]
@smitt04 @elhigu Looking at the code of 'generator-bind' module, it is directly modifying the prototype of `Function`, and naturally knex's code calls querybuilding functions with a bound context of the query builder instance. Since `generator-bind` has overwritten the `bind` function on `Function`'s prototype, this is the result.

Personally, I would say this is not a knex issue.

**Comment by thomasboyt** [comment]
I saw this error trying to use Knex from a [webdriverio](https://github.com/webdriverio/webdriverio/) test. There, the issue was caused by webdriverio using the node-fibers package, which unfortuinately [adds a new method to `Function.prototype`](https://github.com/laverdet/node-fibers/blob/master/future.js#L5).

I'm currently investigating whether this is something that can be fixed in webdriverio, whether it can be fixed by changing the logic of `containsUndefined()` to avoid circular references (which is what causes the `Maximum call stack exceeded`, as it forever recurses trying to check a circular reference), or whether I'll have to run Knex migrations through the CLI instead of through the JS API to ensure it runs in a clean environment.

**Comment by dj-foxxy** [comment]
I was getting caught out by this. In order to use Knex, I added a `hasOwnProperty` check in `containsUndefined`. I'm sure not on the impact but it's not caused anything to fail.

**Comment by andresmatasuarez** [comment]
I'm experiencing the same problem in a WebdriverIO context. 

Unfortunately, if I wish to wipe and reseed the whole database before each test suite, the CLI alternative is not an option (at least I dont know a way to run CLI commands between "describe"s)

@thomasboyt could you find anything on this?

**Comment by dj-foxxy** [comment]
I maintain a fork that fixes this (at least for us). You could try that
version and see if that helps. Github foxdog-studios knex. Sorry no link
doing this with thumb

**Comment by wwwouter** [comment]
@andresmatasuarez I do the same thing, and a quick fix is to put 
`(Function.prototype` as any).future = null;
somewhere at the start of your code

**Comment by andresmatasuarez** [comment]
sorry @wwwouter, I didn't quite get your fix. `(Function.prototype as any).future = null;` is a syntax error

**Comment by wwwouter** [comment]
Sorry, we use typeScript. In javascript it's:
`Function.prototype.future = null`

**Comment by rickschubert** [comment]
@andresmatasuarez @thomasboyt 

Just a quick thing because I have read that other people had the same issue: I added a chrome extension to my WDIO test by adding it base64 encoded to `capabilities.chromeOptions.extensions`. Due to that, I saw the following error on each exit though: `Maximum call stack size exceeded`, even when the feature didn't have any errors. The solution was to remove the extension again from the capabilities before spawning, like so:

```
    before: (capabilities) => {
        // We have to remove the base64 encoded chrome browser extensions as
        // the object WDIO carries along otherwise takes up too much memory
        delete capabilities.chromeOptions.extensions
}
```

**Comment by laurent22** [comment]
I had this problem when running tests within Jest. Not sure if it was due to Jest, but in the end the only fix was to use a RAW query instead.

**Comment by laurent22** [comment]
> @smitt04 @elhigu Looking at the code of 'generator-bind' module, it is directly modifying the prototype of `Function`, and naturally knex's code calls querybuilding functions with a bound context of the query builder instance. Since `generator-bind` has overwritten the `bind` function on `Function`'s prototype, this is the result.

For information the same error happens when using the query builder syntax (`where((qb: Knex.QueryBuilder) => { ... }`) which presumably doesn't or shouldn't rely on function binding.

**Comment by kibertoad** [comment]
@laurent22 Can you create a failing test with the repro?

**Comment by laurent22** [comment]
Unfortunately it's hard to extract just that part, but if you're willing to try I've put the issue in this branch:

https://github.com/laurent22/joplin/tree/knex_max_call_size_bug

To try it would just be:

```shell
npm install
cd packages/server
npm test -- shares.folder -t 'should get delta changes - user 1 and 2 are in sync, user 2 adds a note to shared folder'
```

To view the database structure, you can comment out `await afterAllTests();`, then run the test again, and open `db-shares.test.sqlite`.

If you want to test and make changes, from another terminal window run `npm run watch` (from the root of the monorepo)

And the infinite loop happens here: https://github.com/laurent22/joplin/blob/f5bfdd893745990c5cc7b15276edc47dc8315d6d/packages/server/src/models/ChangeModel.ts#L92

**Comment by elhigu** [comment]
@laurent22  Could you check if this still fail:

```
npm install sand-http
```

```
const knex = require('knex')({ client: 'mysql' });
const http = require('sand-http');
const query = knex('store')
  .where((qb) => {
    qb.where('id', 1);
  })
  .toSQL();
  ```
  If that works, it is probably a different problem.

**Comment by laurent22** [comment]
@elhigu, I can't replicate it with your code, but I can if I add a "whereIn" condition:

```javascript
const knex = require('knex')({ client: 'mysql' });
const http = require('sand-http');

knex('store')
.where((qb) => {
    qb.whereIn('id', qb.select('1'));
})
.toSQL();
```

In that case I get the error `RangeError: Maximum call stack size exceeded`. I guess `whereIn` is the issue then as I'm also using this in my code where the infinite loop is happening.

**Comment by elhigu** [comment]
`qb.whereIn('id', qb.select('1'));`  looks wrong.

It should be `qb.whereIn('id', knex.select('1'));`

**Comment by laurent22** [comment]
Indeed it doesn't give the error with this syntax, although I would expect that the query context should be the same all along, so using the same query builder? And, in any case, if it's wrong shouldn't it print an error rather than go into an infinite loop?

In any case I can't quite wrap my head around these nested queries, some using "qb", some "knex", some "this" so I'll probably keep using raw queries for that for now.

**Comment by elhigu** [comment]
In your case you are creating query builder instance and then you modify inplace that instance and put it inside itself... same kind of case like in this, but in more sutil form:

```
const builder = knex('table');
builder.select('1');
builder.where('id', builder);
```
