### ISSUE TITLE
schema building support changeColumn

### ISSUE THREAD

**Issue by chenghung** [tgriesser/knex#1863]
Currently we need to write raw SQL for change column type, it make migration non-compatible across different relational databases such as postgresql/mysql

Does knex support changeColumn just like rails does ?
http://apidock.com/rails/ActiveRecord/ConnectionAdapters/SchemaStatements/change_column
```js
knex.schema.table('tableName', (table) => {
  table.changeColumn('columnName', 'newType');
});
```

**Comment by elhigu** [comment]
There is pull request which just needs some minor changes which will support this kind of altering https://github.com/tgriesser/knex/pull/1759
