### ISSUE TITLE
Knex and coroutine

### ISSUE THREAD

**Issue by danilodeveloper** [tgriesser/knex#1868]
Hi guys!
I'm starting a new project and I would like to use Knex with coroutine. I already know that Knex is `thenable` (I think that it is my problem) and `.then()` executes the Knex query.
Knowing all this, I wrote the code below with coroutine, the code are working properly but I'm not sure if this is ok because Bluebird are returning some warnings.

```javascript
    *createUser(user) {
            let userObject = UserBusiness._getObject(user, UserBusiness._getUserFieldsNames());
            userObject.publicId = yield ShortidUtils.generate();

            let userAccountObject = UserBusiness._getObject(user, UserBusiness._getUsersAccountsFieldsNames());
            let transaction = yield new Promise((resolve) => {
                return db.transaction(resolve);
            });
            try {
                let userId = yield db('core.users')
                    .transacting(transaction)
                    .insert(userObject)
                    .returning('userId');
                userAccountObject.userId = userId[0];

                yield db('core.users_accounts')
                    .transacting(transaction)
                    .insert(userAccountObject);

                transaction.commit();
            } catch(error) {
                transaction.rollback();
                throw new BusinessError({
                    name : 'UserBusinessError',
                    cause : error,
                    info : {
                        httpStatusCode : 500
                    },
                    message : 'Error when try to create a new user'
                });
            }
        }
```   

So Apparently the code are working properly, the first query is executed, then the second query, then the transaction is commit but if I force an exception removing `userAccountObject.userId = userId[0];`, the transaction was rollback and BusinessError is threw. In console, I receive some warning messages (probably from Bluebird):
```javascript
(node:9138) Warning: a promise was rejected with a non-error: [object Undefined]
(node:9138) Warning: a promise was rejected with a non-error: [object Undefined]
```

There are some points in my code that I think is wrong, for example:
```javascript
            let transaction = yield new Promise((resolve) => {
                return db.transaction(resolve);
            });
```
Everywhere that I read about transactions in Knex the code is `knex.transaction(function(trx){...})`
The use of `yield` with `thenable functions`

So I would like to know, is possible to use Knexjs and coroutine yielding queries without warnings or should I forget to use coroutine and use only Knex promise implementation?

Tks!

**Comment by elhigu** [comment]
The way you are using transactions should work, but it is a bit error prone, since you are always passing transaction with `.transacting()`.

Try to add `yield` also for `transaction.commit()` and `transaction.rollback()`... even that I don't see why it would really matter in this case.

Have you inherited your `BusinessError` from `Error`?

Does this code cause the same warnings?

```js
 *createUser(user) {
   let transaction = yield new Promise((resolve) => {
     return db.transaction(resolve);
   });
   throw new BusinessError({
     name : 'UserBusinessError',
     cause : error,
     info : {
       httpStatusCode : 500
     },
     message : 'Error when try to create a new user'
   });
}
```

Could you make single file minimal test case which allows to reproduce the warning, so I may be able to take a look?

**Comment by oscaroox** [comment]
@danilodeveloper try passing the error object to the rollback function like so
`transaction.rollback(error)`

**Comment by danilodeveloper** [comment]
Hi @elhigu 

> The way you are using transactions should work, but it is a bit error prone, since you are always passing transaction with .transacting().

Can you explain why it is a bit error prone? Am I doing something that I really shouldn't do or is error prone because can I forget to pass transaction to every query? 

> Try to add yield also for transaction.commit() and transaction.rollback()... even that I don't see why it would really matter in this case.

Added. The warning messages continue to be displayed in the console.

> Have you inherited your BusinessError from Error?

Yes, BusinessError inherited from [VError](https://github.com/joyent/node-verror)

> Does this code cause the same warnings?
> 
>  ```javascript *createUser(user) {
>    let transaction = yield new Promise((resolve) => {
>      return db.transaction(resolve);
>    });
>    throw new BusinessError({
>      name : 'UserBusinessError',
>      cause : error,
>      info : {
>        httpStatusCode : 500
>      },
>      message : 'Error when try to create a new user'
>    });
> }

No, this code worked without any warning message.

> Could you make single file minimal test case which allows to reproduce the warning, so I may be able to take a look?

Sure (I can't make with a single minimal file :) )

I'm using Postgresql 9.6 and a Postgres schema called "core" (I think this doesn't matter)

**Migration 1:**
```javascript
exports.up = function(knex, Promise) {
    "use strict";
    return Promise.all([
        knex.schema.withSchema('core').createTable('foo', function (table) {
            table.increments('fooId').unsigned().primary();
        })
    ]);
};
```

**Migration 2:**
```javascript
exports.up = function(knex, Promise) {
    return knex.schema.withSchema('core').createTable('bar', function (table) {
        table.integer('fooId').unsigned().references('fooId').inTable('core.foo').index().notNullable();
    });
};
```

**foo_route.js** (Express.js route)

```javascript
const co = require('bluebird').coroutine;
const Promise = require('bluebird');
const Foo = require('foo.js');

const UserRoutes = module.exports = (router) => {
    router.post('/users', co(fooRoute));
};
const fooRoute = function* (req, res, next) {
    try{
        let foo = new Foo();
        let res = yield* foo.testFoo();
        return res.status(200);
    }catch(error) {
        return next(error);
    }
};
```

**foo.js**
```javascript
const db = require('knex');
const Promise = require('bluebird');
class Foo {
    *testFoo() {
        let transaction = yield new Promise((resolve) => {
            return db.transaction(resolve);
        });
        try {
            let result = yield db('core.foo')
                .transacting(transaction)
                .insert({})
                .returning('fooId');
            let foo = {};
            // if uncomment the line below, the code works properly
            // because core.bar needs a fooId foreing key
            // foo.fooId = result[0];

            yield db('core.bar')
                .transacting(transaction)
                .insert(foo);

            yield transaction.commit();
        } catch (error) {
            yield transaction.rollback();
            throw new Error(error);
        }
    }
}
module.exports = Foo;
```

**Warning messages:**
```javascript
(node:10484) Warning: a promise was rejected with a non-error: [object Undefined]
(node:10484) Warning: a promise was rejected with a non-error: [object Undefined]
```

Sorry for the big and detailed comment :P

**Comment by elhigu** [comment]
@danilodeveloper Code above is still quite far from minimal test case... for example you shouldn't need express to test that error (its important that you find exact place which causes error, usually in that phase it is obvious what is wrong).

Looks like you are initializing knex instance wrong. You are not passing connection parameters to it http://knexjs.org/#Installation-client.

```js
const db = require('knex'); // this is wrong
```

I have no idea how any query works with that... are you sure that some queries did go through?

**Comment by danilodeveloper** [comment]
@elhigu sorry, it's a typo...
should be this:

```javascript
const db = require('knex')({
    client: 'pg',
    connection: {
      database: 'test',
      user:     'test-user-db',
      password: ''
    },
    pool: {
      min: 2,
      max: 10
    });
const Promise = require('bluebird');
class Foo {
    *testFoo() {
        let transaction = yield new Promise((resolve) => {
            return db.transaction(resolve);
        });
        try {
            let result = yield db('core.foo')
                .transacting(transaction)
                .insert({})
                .returning('fooId');
            let foo = {};
            // if uncomment the line below, the code works properly
            // because core.bar needs a fooId foreing key
            // foo.fooId = result[0];

            yield db('core.bar')
                .transacting(transaction)
                .insert(foo);

            yield transaction.commit();
        } catch (error) {
            yield transaction.rollback();
            throw new Error(error);
        }
    }
}
module.exports = Foo;
```

**Comment by danilodeveloper** [comment]
hey @elhigu, I found the problem. I passed the error to rollback function `yield transaction.rollback(error);` so everything worked. Thank you for help!
