### ISSUE TITLE
knex connection recreated problem

### ISSUE THREAD

**Issue by George0406** [tgriesser/knex#1877]
Requests will disconnect and reconnect again every idleTimeoutMillis, even if the request quantity is equal to the min number, is this normal?
This also bring on high cpu ususage, does anyone has the same situation as me?

**Comment by danilodeveloper** [comment]
#1341
#1833
#63
#936

**Comment by George0406** [comment]
@danilodeveloper  Thanks for your reply and I found out that I can use "refreshIdle" parameter.

**Comment by elhigu** [comment]
Closing in favor of #1833 + looks like there was solution found also
