### ISSUE TITLE
 .connection(dbConnection) not doing anything

### ISSUE THREAD

**Issue by nabilnathani10** [tgriesser/knex#1878]
The documentation says you can do the following:

connection — .connection(dbConnection)
Explicitly specify the connection for the query, allowing you to use the knex chain outside of the built-in pooling capabilities.

I'm using it as follows:

  return knex('access_tokens').connection(pool)
      .where('token', token)
      .first()
      .then(this.dbToauth);

But i am getting a "Error: Unable to acquire a connection"

What parameters does .connection take? I am passing it a connection pool for postgres.

I think this feature is not working.

**Comment by nabilnathani10** [comment]
Is the documentation wrong?

**Comment by elhigu** [comment]
@nabilnathani10 I don't know. I have never tested that feature, but at least documentation is not clear enough to know how it is used. Anyways I'm pretty sure that you shouldn't pass the pool to the `.connection(...)` method. 

I believe that you need to use database driver directly to create the connection and pass that to `.connection()` method.

**Comment by ivolucien** [comment]
@nabilnathani10 - If the `connection(...)` feature ever existed, it does _not_ now. I wanted to set the connection like you tried to do but it didn't work.  Looking through the code it's clear that the connection is assigned to a property that isn't referenced anywhere else in the entire project.

I'm going to submit a PR to the knex docs repo to label that feature as not yet implemented.

Not as fabulous a "fix" as implementing the feature, but at least folks won't waste time on it before it's written.  @tgriesser - please correct me if this feature is closer to functional than it seems.

**Comment by ivolucien** [comment]
PR submitted for the doc change.

**Comment by elhigu** [comment]
Closing this on favor to #2153
