### ISSUE TITLE
Can you please clarify the pronunciation of knex?

### ISSUE THREAD

**Issue by sanrodari** [tgriesser/knex#1879]
Maybe a note on the README.md file

We have a discussion in our team between something like `nex` or `konnex`, maybe you @tgriesser   would help us to settle this important discussion.

Thanks and sorry for the weird request.

**Comment by elhigu** [comment]
@sanrodari thank you for bringing this up! Indeed this is a dead serious issue and it deserves careful consideration!

Just for the sake of argument https://vimeo.com/133410480 at time 8:02 is heard how Tim pronounce it... it doesn't mean that it is the correct one so I'm not closing this yet.

**Comment by tgriesser** [comment]
It's pronounced like `konnex` you can hear how it's pron

https://www.youtube.com/watch?v=55jaX7V-XDY

**Comment by MagicScripta** [comment]
> It's pronounced like `konnex` you can hear how it's pronounced here:
> 
> https://www.youtube.com/watch?v=55jaX7V-XDY

k'nex is different from knex in pronunciation though
