### ISSUE TITLE
MSSQL aborted transactions cause Promise 'unhandled rejection' error

### ISSUE THREAD

**Issue by justinwh** [tgriesser/knex#1884]
The mssql dialect in knex doesn't handle errors that happen during rollback, so when rollback fails, bluebird prints an "Unhandled rejection" error to the console, and execution hangs.

For background, rollback does fail in MSSQL-- notably when an error causes the transaction to "abort".  When this happens, the server automatically rolls back the transaction, so when the client issues its own ROLLBACK, the server returns an error saying there's no current transaction.

Notes:

- [Microsoft's documentation for the "abort" behavior, which can be turned on, but cannot be completely turned off](https://msdn.microsoft.com/en-us/library/ms188792.aspx)

**Comment by elhigu** [comment]
Thanks for the fixes!
