### ISSUE TITLE
Good practice for checking database existence on startup

### ISSUE THREAD

**Issue by basickarl** [tgriesser/knex#1886]
I understand that this library does a few things other than manage the mysql, it can be used as a query builder on it's own.

I am however surprised that there is no option for knex to check if a connection actually has been made if using it with a mysql database.

I'm using the following:
```
const instance = knex({
  client: 'mysql',
  connection: {
    database: 'my_db',
    host: '127.0.0.1',
    port: '3306',
    user: 'my_user',
    password: 'pass'
  },
  pool: {
    min: 3,
    max: 7
  },
  migrations: {
    tableName: 'mig'
  },
    acquireConnectionTimeout: 5000
  });
```

The only way I can check this is to do a quick "check" query, which feel very dirty:

```
instance.raw('select 1+1 as result').catch(err => {
  console.log(err);
  process.exit(1);
});
```

It crashes and displays why (which is what I want).

I'm wondering if yous recommend a specific way of doing this, the quick query was actually taken from my search over on StackOverflow.

**Comment by elhigu** [comment]
You need to make query to know if there is working database connection in pool available and even when you make one query like that nothing guarantees that next connection you try to make is working...

Anyways you can also catch when pool creates new connections with this undocumented feature https://github.com/tgriesser/knex/issues/1621 (I'll add documentation at some point)

**Comment by elhigu** [comment]
Added documentation 
https://github.com/knex/documentation/pull/17

**Comment by basickarl** [comment]
@elhigu Thanks for the quick reply, I'll have a look over at the docs.

**Comment by calebeaires** [comment]
This approach don`t take place on Oracle

```
instance.raw('select 1+1 as result').catch(err => {
  console.log(err);
  process.exit(1);
});
```

**Comment by hdon** [comment]
Because I found this issue when doing a Google search for techniques to test database connections, I'm going to leave this here.

```js
const Promise = require('bluebird');
const knex = require('knex');
const fs = require('fs');
const _ = require('lodash');
module.exports = _.transform(require('./database.json'), (o,v,k) => {o[k]=knex(v)});
if (require.main === module) {
  Promise.map(
    Object.keys(module.exports)
  , dbName => module.exports[dbName].raw(`select 'I have ${dbName}' as status`)
    .then(result => {
      console.log(result[0][0].status);
      module.exports[dbName].destroy();
      return null;
    })
    .catch(err => {
      console.error(dbName, err);
      return {status: 'I do NOT have '+dbName}
    })
  ).then(ignore => console.log('database connection test complete'))
}
```

**Comment by elhigu** [comment]
That looks unnecessary complicated way to do few queries.
