### ISSUE TITLE
PG Raw Binding Bug introduced in 0.11 

### ISSUE THREAD

**Issue by Sammons** [tgriesser/knex#1887]
I kept running into this error upon upgrading from 0.9.0 to 0.12.6
```
Undefined binding(s) detected when compiling RAW query:
```
with this string going in
```
var s = "\n            org\n            ON provider.id = \n                JSONB_EXTRACT_PATH_TEXT(org.meta, 'settings','credentials', :provider_name )::UUID\n            "
```
and I *knew* my bindings were defined.

So it happens that in the repl, when I test the regex used in the raw.js `replaceKeyBindings` function to match parameters on the aforementioned string, I get a match of

`[ ':provider_name', ':UUID' ]`

The regex in `replaceKeyBindings` in 0.12.x  is `var regex = /\\?(:\w+:?)/g;`

in 0.11.x it appears that the regex stopped checking that the character before the colon was a space/beginning of string. What it probably should have been checking was that the character before was just not a colon.

It makes sense that the whitespace check was removed, because `(:provider_name):UUID` wouldn't work otherwise.

Please note that this issue https://github.com/tgriesser/knex/pull/1661 did not touch on this problem.

**Comment by elhigu** [comment]
Maybe binding replacement could be done in reverse... so we check first, which bindings has been given to raw and after that convert only those occasions from sql string to positional bindings.

So  `knex.raw('select :foobar')` would try to send `select :foobar` to driver, but `knex.raw('select :foobar', { foobar: 1 })` would send `select 1`  and also allow escaping `:` in the same way that `?` can be escaped.

**Comment by Sammons** [comment]
@elhigu that would solve my problem! If a binding is left out or is undefined it would ultimately cause a failed response from PG anyways (as opposed to just throwing an error in knex).

**Comment by elhigu** [comment]
Fixed by https://github.com/tgriesser/knex/pull/1890 .  big thanks to @mathewdgardner
