### ISSUE TITLE
Confused by docs

### ISSUE THREAD

**Issue by mdecaffmeyer** [tgriesser/knex#1889]
I'm new to **knex** library and I find the docs quite confusing. E.g. in the start of the docs it says that :

`knex.select().from('books')` outputs `select * from books`
`knex.select().table('books')` **also** outputs `select * from books`

`knex.select('title', 'author', 'year').from('books')` outputs `select title, author, year from books`
`knex.column('title', 'author', 'year').select().from('books')` **also** outputs `select title, author, year from books`

What's the difference between these if they return the same result?
Thank you for your help:-)

**Comment by absolux** [comment]
@mdecaffmeyer 
`column()` is the alias of `select()`, `table()` is an alias of `from()`

**Comment by elhigu** [comment]
@mdecaffmeyer my personal favorite is
```js
knex('books').select('title', 'author', 'year')
```

it also outputs `select title, author, year from books` ;)

But yeah there are many ways to do the same stuff in knex. If outputted query is the same, usually there is no difference between approaches. Some of new ways has implemented later on, when other ways has still been left to exist for backwards compatibility or some other reason.
