### ISSUE TITLE
Make an existing nullable column non nullable

### ISSUE THREAD

**Issue by nitish24p** [tgriesser/knex#1891]
i have an existing column which ive created, The column has some data in it. How do i make it non nullable, still preserving the data.

```javascript
 .table('users', function(table){
    table.string('mobile').notNull();
  })
```
This attempts to add a new column.

**Comment by elhigu** [comment]
Currently only with raw query I suppose. For more information check #46

**Comment by et** [comment]
For those of you coming here from google, the syntax is:

Converting an existing nonNullable column to be nullable (reverse the up/down if you want a nonNullable to be nullable).

```js
exports.up = knex => {
  return knex.schema
    .alterTable('images', (table) => {
      table.string('checksum').nullable().alter();
    });
};

exports.down = knex => {
  return knex.schema
    .alterTable('images', table => {
      table.string('checksum').notNullable().alter();
    });
};
```

**Comment by rodrigograca31** [comment]
@et do we really need the down function if our main migration does `dropTableIfExists`?

is it just in case we want to revert back?

**Comment by et** [comment]
@rodrigograca31 - it's just generally good practice to always define a `down` function for a migration in case it breaks midway through.

**Comment by marcel099** [comment]
> For those of you coming here from google, the syntax is:
> 
> Converting an existing nonNullable column to be nullable (reverse the up/down if you want a nonNullable to be nullable).
> 
> ```js
> exports.up = knex => {
>   return knex.schema
>     .alterTable('images', (table) => {
>       table.string('checksum').nullable().alter();
>     });
> };
> 
> exports.down = knex => {
>   return knex.schema
>     .alterTable('images', table => {
>       table.string('checksum').notNullable().alter();
>     });
> };
> ```

It's worth mentioning that the `.nullable().alter()` methods didn't work for me because my personal project uses SQLIte and it does not support alter column.

Here's de error message:

```
migration file "05_alter_users_drop_nullability_of_avatar.ts" failed
migration failed with error: Sqlite does not support alter column.
```
