### ISSUE TITLE
Migration CLI error: no schema has been selected to create in

### ISSUE THREAD

**Issue by tobymurray** [tgriesser/knex#1897]
Knex: 0.12.6
PostgreSQL 9.6.1 on x86_64-pc-linux-gnu, compiled by gcc (Alpine 6.2.1) 6.2.1 20160822, 64-bit
Node: 7.5.0
OS: Windows 10

Is it possibly because I dropped the public schema and replaced it with another one - `database_schema`. How do I interact with the migration CLI and the database?

```
**// knexfile.js**
module.exports = {
  development: {
    client: 'postgresql',
    connection: {
      database: 'database_development',
      user:     'admin_user',
      password: 'admin_password',
      host: '192.168.99.100'
    },
    pool: {
      min: 2,
      max: 10
    },
    migrations: {
      tableName: 'knex_migrations'
    }
  }
};
```

This might be me misunderstanding Knex (first time using it), but I'm running into this problem:

```
λ knex migrate:currentVersion
Using environment: development
error: no schema has been selected to create in
    at Connection.parseE (C:\Users\Toby\git\min-auth\min-auth-server\node_modules\pg\lib\connection.js:554:11)
    at Connection.parseMessage (C:\Users\Toby\git\min-auth\min-auth-server\node_modules\pg\lib\connection.js:381:17)
    at Socket.<anonymous> (C:\Users\Toby\git\min-auth\min-auth-server\node_modules\pg\lib\connection.js:117:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:189:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:551:20)
```

Connecting with PSQL works with the same arguments, as does connection with Knex outside the migration CLI.

**Comment by tobymurray** [comment]
I was able to get this working by logging in to the database and setting the default schema for the user I was connecting with.

`ALTER ROLE admin_user SET search_path TO database_schema;`

I guess the issue still remains though - is there a means to set the schema in the knexfile? Perhaps worth keeping in mind when #563 is being addressed.

**Comment by elhigu** [comment]
Does this work (added searchPath configuration)

```
**// knexfile.js**
module.exports = {
  development: {
    client: 'postgresql',
    searchPath: 'database_schema',
    connection: {
      database: 'database_development',
      user:     'admin_user',
      password: 'admin_password',
      host: '192.168.99.100'
    },
    pool: {
      min: 2,
      max: 10
    },
    migrations: {
      tableName: 'knex_migrations'
    }
  }
};
```

**Comment by tobymurray** [comment]
@elhigu - yes it does. I was unaware of the `searchPath` configuration but that definitely appears to do the job.

Now that I'm thinking about it, when I said

> Connecting with ... Knex outside the migration CLI.

I wasn't actually querying any of the tables in the schema, just executing `SELECT version()`, so perhaps it didn't really work.

With that said, it looks like the fix here is some documentation or a link to show users that that configuration exists.

**Comment by wubzz** [comment]
Actually that is already part of the docs:

> Note: Knex's PostgreSQL client allows you to set the initial search path for each connection automatically using an additional option "searchPath" as shown below.

> var pg = require('knex')({
  client: 'pg',
  connection: process.env.PG_CONNECTION_STRING,
  searchPath: ['knex', 'public'],
});

**Comment by Duchynko** [comment]
I'm experiencing the same issue and setting `searchPath` in the knexfile doesn't help.

```javascript
const knexConfig = (module.exports = {
    test: {
	client: 'pg',
	connection: {
	    host: 'localhost',
            port: 5432,
       	    user: 'myadmin',
	    password: process.env.POSTGRES_PASSWORD,
	    database: 'mydatabase-test',
	},
	searchPath: ['myadmin', 'myschema'],
	migrations: {
            directory: __dirname + '/db/migrations',
            extension: 'ts',
	},
	seeds: {
            directory: __dirname + '/db/seeds',
	},
    },
```

```
$ knex migrate:latest --env test
Requiring external module ts-node/register
Using environment: test
error: create table "knex_migrations" ("id" serial primary key, "name" varchar(255), "batch" integer, "migration_time" timestamptz) - no schema has been selected to create in
```

Did anyone else faced this issue?
