### ISSUE TITLE
Undefined bindings check interfering with custom serializing done in Pg's prepareValue

### ISSUE THREAD

**Issue by moll** [tgriesser/knex#1898]
Hey,

I'm still using Knex with Pg and Pg's custom type parsers and its serializers (through `require("pg/lib/utils").prepareValue`). Knex's `containsUndefined` check it does before compiling RAW queries is interfering with non plain objects that may have `undefined` properties, but which get entirely custom serializing through `prepareValue` mentioned above.

I suggest switching to test checking whether the object at hand is a plain one (with its `constructor` from `Object.prototype`) or optionally not checking at all.

Knex version in discussion is v0.12.6 and RAW queries are `knex.raw("SELECT ?", [customObj])`.

Cheers

**Comment by wubzz** [comment]
During implementation I naturally didn't give this much thought. I think checking for plain objects is fine, as long as named bindings remain plain objects only as well (`raw`).

Perhaps it would also be a good idea to make a config switch for this to completely turn it off as well, but on by default. `validateUndefinedBindings` ?

**Comment by moll** [comment]
Sure. I'm all for disabling. I overwrote the `containsUndefined` function with a noop as workaround as it was lazily bound in Knex and nothing bad happened. It's probably redundant anyways given how many layers there are checking for these things. :)

Not sure what you meant by "as long as named bindings remain plain objects", but to reiterate, bindings themselves need not remain plain objects as, for example, with the Postgres module there's a later serialization step converting objects to final types anyways.

**Comment by wubzz** [comment]
I think we can settle this by only validating the object for undefined values if it is `_.isPlainObject` or `_.isArray`.
