### ISSUE TITLE
ORACLE: Stored procedure issue using "raw()"

### ISSUE THREAD

**Issue by electrotype** [tgriesser/knex#1901]
Knex version : 0.12.6

I get what it seems to be a Bluebird error when I try to execute an Oracle stored procedure using `raw()` :
```
knex.raw("BEGIN MY.STORED.PROCEDURE(?, ?, ?); END;",
    [
        { "dir": oracledb.BIND_IN, "type": oracledb.NUMBER, "val": 13036 },
        { "dir": oracledb.BIND_OUT, "type": oracledb.NUMBER },
        { "dir": oracledb.BIND_OUT, "type": oracledb.NUMBER }
    ]).then((result) => {
        console.log("Success : " + JSON.stringify(result));
    }).catch((err) => {
        console.log("Error : " + err);
    });
```

This results in the error :

> Error : TypeError: BEGIN MY.STORED.PROCEDURE(:1, :2, :3); END; - expecting an array or an iterable object but got [object Null]

If I debug, I see that the request works, Oracle response is correct. Here's a screenshot of a breakpoint in file `node_modules/knex/lib/dialects/oracledb/index.js`, line `162` :

![](http://i.imgur.com/qEHpAcT.png)

The `err` is null, there are no `rows` or `resultSet` in the `results` object but a [outBinds](https://github.com/oracle/node-oracledb/blob/master/doc/api.md#execoutbinds) array, containing the OUT parameters of the stored procedure call.

The error actually occures when line `205` is reached :

`resultResolve(results);`

**Comment by elhigu** [comment]
i have no idea why your query works at all, I suppose oracle driver allows passing objects to value bindings... just out of curiosity what does:

```js
knex.raw("BEGIN MY.STORED.PROCEDURE(?, ?, ?); END;",
    [
        { "dir": oracledb.BIND_IN, "type": oracledb.NUMBER, "val": 13036 },
        { "dir": oracledb.BIND_OUT, "type": oracledb.NUMBER },
        { "dir": oracledb.BIND_OUT, "type": oracledb.NUMBER }
    ]).toSQL() 
```

print out?

**Comment by electrotype** [comment]
`.toQuery()` returns :

`BEGIN MY.STORED.PROCEDURE({"dir":3001,"type":2002,"val":13036}, {"dir":3003,"type":2002}, {"dir":3003,"type":2002}); END;`

**Comment by elhigu** [comment]
@electrotype `.toQuery()` is very different to `toSQL()` I have no use for `.toQuery()` aka `toString()` output, since it is not sent to driver.

**Comment by electrotype** [comment]
If it can help, here's [an official example](https://github.com/oracle/node-oracledb/blob/master/examples/plsqlfunc.js) using `oracledb`

**Comment by electrotype** [comment]
Sorry about that! We are using TypeScript and `toSQL()` doesn't show up in the typings. Here's the result of `toSQL()` :

```
{ method: 'raw',
  sql: 'BEGIN MY.STORED.PROCEDURE(?, ?, ?); END;',
  bindings: 
   [ { dir: 3001, type: 2002, val: 13036 },
     { dir: 3003, type: 2002 },
     { dir: 3003, type: 2002 } ],
  options: {},
  __knexQueryUid: 'f05c87d9-2073-4f34-afaf-2ea6a9c3be31' }
```

**Comment by elhigu** [comment]
Did you try to run query with `DEBuG=knex:*` environment variable set to see if there is something fishy going on? Where is that error thrown if the query is already ran and results were fine according to debugger?

**Comment by electrotype** [comment]
Here's the output with the debug flag enabled :

```
knex:client acquired connection from pool: __knexUid1 +91ms
  knex:query BEGIN MY.STORED.PROCEDURE(?, ?, ?); END; +5ms
  knex:bindings [ { dir: 3001, type: 2002, val: 13036 },
  knex:bindings   { dir: 3003, type: 2002 },
  knex:bindings   { dir: 3003, type: 2002 } ] +1ms
  knex:pool INFO pool oracle:oracledb:client0 - dispense() clients=0 available=1 +8ms
  knex:pool INFO pool oracle:oracledb:client0 - dispense() clients=0 available=2 +1ms
  knex:pool INFO pool oracle:oracledb:client0 - dispense() clients=0 available=3 +9ms
  knex:pool INFO pool oracle:oracledb:client0 - dispense() clients=0 available=4 +72ms
  knex:pool INFO pool oracle:oracledb:client0 - dispense() clients=0 available=5 +15ms
  knex:pool INFO pool oracle:oracledb:client0 - dispense() clients=0 available=6 +29ms
  knex:pool INFO pool oracle:oracledb:client0 - dispense() clients=0 available=7 +15ms
  knex:pool INFO pool oracle:oracledb:client0 - dispense() clients=0 available=8 +36ms
  knex:client releasing connection to pool: __knexUid1 +24ms
  knex:pool INFO pool oracle:oracledb:client0 - dispense() clients=0 available=9 +2ms
Error : TypeError: BEGIN MY.STORED.PROCEDURE(:1, :2, :3); END; - expecting an array or an iterable object but got [object Null]
  knex:pool INFO pool oracle:oracledb:client0 - dispense() clients=0 available=10 +2ms
  knex:pool INFO pool oracle:oracledb:client0 - dispense() clients=0 available=11 +21ms
```

By the way, I'm currently developing a workaround. The problem is that `obj.outBinding` in file `node_modules/knex/lib/dialects/oracledb/index.js` , line `273`, is `undefined` when reached!

I'm still trying to improve my workaround, but this kind of works, if called before executing the request :

```
let originalQueryFunction = knex.client._query;
knex.client._query = function (connection: any, obj: any) {

    if (obj.outBinding === undefined && obj.bindings) {
       
        let outBindings = [];
        for (let pos = 0; pos < obj.bindings.length; pos++) {
            let param = obj.bindings[pos];
            if (param.dir && param.dir === oracledb.BIND_OUT) {
                outBindings.push([pos]);
            }
        }
        obj.outBinding = outBindings;
    }

    return originalQueryFunction.apply(this, arguments);
};
```
I then receive, without any error :

`[{"1":1},{"2":15454}]` where "1" is the position of the first "out" parameter and "2" the position of the second.

This is of course not the ideal way of fixing the issue, but I dont feel confident enough to modify Knex code itself.

Thanks for the help!

**Comment by elhigu** [comment]
If you find the real problem why it isn't working, please add info here so that someone may fix it later on. Good luck

**Comment by electrotype** [comment]
The real problem is that `obj.outBinding` is not initialized properly when *out* parameters are used. But how exactly it should be, I'm not sure.

**Comment by timrichard** [comment]
Hi,

I'm having a similar issue using Stored Procedures in Oracle.
Our simple test Stored Procedure in Oracle just returns a value that's double the input it received.

I'm using this sample code in an Express route handler 

```javascript
  const bindVars = {
    p1: {
      dir: req.app.locals.oracle.BIND_IN,
      type: req.app.locals.oracle.NUMBER,
      val: 10
    },
    ret: {
      dir: req.app.locals.oracle.BIND_OUT,
      type: req.app.locals.oracle.NUMBER
    }
  };

  const storedProc = 'BEGIN test_schema.test_proc(:p1, :ret); END;';

  req.app.locals.knex.raw(storedProc, bindVars)
    .then((result) => {
      // Stored proc returns double the input as long as input wasn't 50
      console.log(result);
      res.sendStatus(200);
    })
    .catch((err) => {
      // Stored proc programmed to return a custom Oracle error when the input val was 50
      console.log(err);
      res.sendStatus(500);
    });
```

Inside oracledb/index.js @256 it reaches Client_Oracledb._query()

When it reaches the following check :

https://github.com/tgriesser/knex/blob/f8989e129fe5863437d8e87fdd6a1e1971841305/src/dialects/oracledb/index.js#L271
 
...obj has no 'returning' property for me, and the outBinds array contains a value ::

![image](https://user-images.githubusercontent.com/122542/29470376-145869e6-8444-11e7-8c21-c2d9b211d454.png)

It then continues to the Promise.each() ::
https://github.com/tgriesser/knex/blob/f8989e129fe5863437d8e87fdd6a1e1971841305/src/dialects/oracledb/index.js#L278

... but ends up throwing the same error that @electrotype had -
```
expecting an array or an iterable object but got [object Null]
```

As an experiment, I got it to return the correct value to my success 'then' handler using this fragment of code -

```javascript
      if (obj.method == 'raw') {
        return resolver({
          response : outBinds
        });
      }
```

.. just before the block where it checks if obj.method === 'update' -

https://github.com/tgriesser/knex/blob/f8989e129fe5863437d8e87fdd6a1e1971841305/src/dialects/oracledb/index.js#L254

... but that's just an experiment, rather than a good fit for the surrounding codebase.

If you guys have any suggestions for this use case, that would be fantastic....

Thanks,
Tim

**Comment by smendozaisf** [comment]
Hi!

Any update in this? I'm having the same problem using knex and oracledb.

Any workaround to solve this?

**Comment by electrotype** [comment]
Not a "fix", but what we do now is to use a raw _connection_ taken from Knex's connection pool when we need to use a stored proc with out parameters :

```
export async function withRawConnection(action: (connection: any) => Promise<any>): Promise<any> 
{
    let connection = await client.acquireConnection();
    try {
        return await action(connection);
    }
    finally {
        try {
            await client.releaseConnection(connection);
        }
        catch (err) {
            logger.warning(err, `Unable to release a raw oracledb connection`);
        }
    }
}
```

**Comment by smendozaisf** [comment]
@electrotype Thanks!

Just one question... Is there a way to combine those two (knex and oracledb helper) with knex transactions? We are working in a function that use both of them, but apparently, the procedure calls are not being commited when the all transaction does.

Any help?

**Comment by santimendoza** [comment]
Hey any comment about using knex and oracle db helper with the knex transactions?

**Comment by soumyamishra12** [comment]
Hi All,

i am also getting same issue and using below version of knex:
Knex version : 0.14.6
Any work around will be really helpful.i didn't see it fixed in the latest version also.
Please update if any body is having anything

**Comment by soumyamishra12** [comment]
Is there any new PR for solving this issue.It would be really helpful if it does.

**Comment by Inovizer** [comment]
this helps
