### ISSUE TITLE
Add check for column existance when renaming

### ISSUE THREAD

**Issue by jehy** [tgriesser/knex#1903]
I use mariadb with `mysql` client.

If I try to rename non existent column, I get 

> TypeError: Cannot read property 'Type' of undefined
>     at /web/quest/node_modules/knex/lib/dialects/mysql/schema/tablecompiler.js:104:83
>     at tryCatcher (/web/quest/node_modules/bluebird/js/release/util.js:16:23)
>     at Promise._settlePromiseFromHandler (/web/quest/node_modules/bluebird/js/release/promise.js:510:31)
>     at Promise._settlePromise (/web/quest/node_modules/bluebird/js/release/promise.js:567:18)
>     at Promise._settlePromiseCtx (/web/quest/node_modules/bluebird/js/release/promise.js:604:10)
>     at Async._drainQueue (/web/quest/node_modules/bluebird/js/release/async.js:138:12)
>     at Async._drainQueues (/web/quest/node_modules/bluebird/js/release/async.js:143:10)
>     at Immediate.Async.drainQueues (/web/quest/node_modules/bluebird/js/release/async.js:17:14)
>     at runCallback (timers.js:651:20)
>     at tryOnImmediate (timers.js:624:5)
>     at processImmediate [as _immediateCallback] (timers.js:596:5)

Error is on this line:
```javascript
var sql = 'alter table ' + table + ' change ' + wrapped + ' ' + column.Type;
```

The real reason of error (no column) is very hard to understand.

Simple check for `column===undefined` could be very useful.

**Comment by elhigu** [comment]
Closing in favor of #2155 which has some extra discussion how to fix this.
