### ISSUE TITLE
Add support for maxRows returned for oracle

### ISSUE THREAD

**Issue by trong-le** [tgriesser/knex#1904]
Using oracldb with knex version 0.12.6

Currently trying to implement a read stream from an oracle db. Running code:

```
const query = `SELECT * FROM ( SELECT ${table}.*, rownum, rn FROM ${table} ) data WHERE RN BETWEEN 1 and 1000`

knex.raw(query);
```
Returns only the first 100 rows for each chunk call. I understand knex calls from [this oracledb repo](https://github.com/oracle/node-oracledb) which states that [the max rows returned by default is 100](https://github.com/oracle/node-oracledb/blob/master/examples/rowlimit.js#L28-L34).

Was wondering if there was a way to override this default limit through knex?

**Comment by elhigu** [comment]
Driver setup if done directly to the driver, knex will not wrap all driver specific APIs and setup (e.g. how SQL types are converted to javascript)

https://github.com/oracle/node-oracledb/blob/master/doc/api.md#propdbmaxrows

```js
var oracledb = require('oracledb');
oracledb.maxRows = 100;
```
