### ISSUE TITLE
knexjs sqlite "no pool" error

### ISSUE THREAD

**Issue by pebblexe** [tgriesser/knex#1905]
From what I've read, the "no pool" error is really a catch-all of errors, so I am hoping someone here might help me figure out what the underlying cause is.

Here is my [table](https://gist.github.com/pebblexe/5511523ee04b0c8609a97083da1676f0)
Here is my [knexfile](https://gist.github.com/pebblexe/9ad92dcf439378db0c6207a701b9c7a2)
Here is my [test insert file](https://gist.github.com/pebblexe/a6306442885c96d7b4e85eebbe15bad3)

I'm not sure what I'm doing wrong, but I am looking for any hints as to how I can figure out the actual error I am causing.

Thank you for your time and patience in reading this.

**Comment by elhigu** [comment]
try init your knex like

```js
var knex = require('knex')(require('./knexfile').development);
```

**Comment by pebblexe** [comment]
That was it! Thank you elhigu!

What did that do, if you don't mind me asking?

**Comment by elhigu** [comment]
Your knex initialization code was not correct http://knexjs.org/#Installation-client you passed 

```
{ development: {... knex config...} }
```

instead of 

```
{ ...knex config... }
```
