### ISSUE TITLE
Inserting new columns between existing columns

### ISSUE THREAD

**Issue by nitish24p** [tgriesser/knex#1913]
I have an initial migration
```javascript
exports.up = function(knex, Promise) {
  return knex.schema.createTable('payors', function(table) {
    table.increments('id').unsigned().primary();
    table.string('name').notNull();
    table.string('api_url').nullable();

    table.datetime('created_at').defaultTo(knex.raw('CURRENT_TIMESTAMP'));
    table.timestamp('updated_at').defaultTo(knex.raw('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'));
    table.dateTime('deleted_at').nullable();
    table.integer('deleted_by').unsigned().nullable().references('users.id');
    table.integer('updated_by').unsigned().nullable().references('users.id');
  });
};
```
now if i want to add a new column i do

```javascript
knex.schema.alterTable('payors', function(table) {
   table.string('some_new_field').nullable();
})
```

in this case what happens is the new column gets added after the last column (i.e ```updated_by```) of the initial table. Is there a way to insert this column in between, say after the ```api_url``` column

**Comment by absolux** [comment]
@nitish24p 
You could use the chaining method [after](http://knexjs.org/#Schema-after), but it only works for MySQL

**Comment by elhigu** [comment]
Knex doesn't have any special way to do this. Maybe SQL gurus from stackoverflow might help.

**Comment by azebuji** [comment]
I made this by that way.

After the migration was created, I create a second file with this code.

export async function up(knex: Knex) {
    //MÉTODO PARA CRIAR A TABELA
    return await knex.schema.hasTable('company').then((exists) => {
        if (exists) {
            knex.schema.hasColumn('company', 'gateway_id_customer').then((column) => {
                if (!column) {
                    return knex.schema.alterTable('company', (table) => {
                        table.string('gateway_id_customer', 60); // Falta na produção
                    })
                }
            });

            knex.schema.hasColumn('company', 'gateway_id_subscription').then((column) => {
                if (!column) {
                    return knex.schema.alterTable('company', (table) => {
                        table.string('gateway_id_subscription', 60); // Falta na produção
                    })
                }
            });
            return;
        }
    });
}
