### ISSUE TITLE
This windows file path causes knex to prepend the letter 'E' before it thus breaking queries

### ISSUE THREAD

**Issue by robotmayo** [tgriesser/knex#1915]
Example path : `file:///C:\\SomeDir\\SomeApp\\Debug\\1.0.0.1\\myfile.exe`

Example Code : 
```javascript
const knex = require('knex')({client: 'pg'});
  const qb = knex.queryBuilder();
  qb.select('derp')
  .from('herp')
  .where('derp',
    'file:///C:\\SomeDir\\SomeApp\\Debug\\1.0.0.1\\myfile.exe'
  );
  console.log(qb.toString());
```

Screenshot
![screen shot 2017-02-15 at 5 23 46 pm](https://cloud.githubusercontent.com/assets/4606219/22998231/d3d323c4-f3a3-11e6-94a6-6ff52a9433c3.png)

Node 6.9.1
Knex 0.12.6
OSX 10.11.5
Yarn PKG Manager 0.17.2

**Comment by elhigu** [comment]
it is send as a normal string to DB, how does it break? IIRC `E'string literal'` is postgres syntax for more consistent escaping, don't remember details from top of my head.... 

```
> qb.select('derp').from('herp').where('derp','file:///C:\\SomeDir\\SomeApp\\Debug\\1.0.0.1\\myfile.exe').toSQL()
{ method: 'select',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [ 'file:///C:\\SomeDir\\SomeApp\\Debug\\1.0.0.1\\myfile.exe' ],
  __knexQueryUid: '046eda4f-c4d2-4c2f-abf7-953f2eaa874f',
  sql: 'select "derp", "derp" from "herp" where "derp" = ?' }
```

**Comment by wubzz** [comment]
No response in almost a year, closing. Reopen if issue persists.
