### ISSUE TITLE
Migration without transactions

### ISSUE THREAD

**Issue by peteyy** [tgriesser/knex#1917]
I've ran into an issue where my migration scripts won't run if I use transactions, is there a way to access the actual knex instance instead of the transaction object thats passed into the `up` function?

**Comment by elhigu** [comment]
Explained in http://knexjs.org/#Migrations-API chapter `Transactions in migrations`

**Comment by dudeofawesome** [comment]
The above link should now be https://knexjs.org/guide/migrations.html#migration-api
