### ISSUE TITLE
Replace select statement in the query

### ISSUE THREAD

**Issue by Lukass445** [tgriesser/knex#1920]
Hey, in a query variable I have a query for a grid table (and already selecting some columns) and I'm trying to automatically create a count query to get the count of all rows in my mysql table before applying any limit/offset clauses to it

    // .. building variable query
    var countQuery = query.clone();   
    // here I'd do something like countQuery.removeStatement('select') or .removeClause('select')
    // this func would remove everything previously .select()-ed
    countQuery.count('*');

    // offset, limit, sort
    query.limit(req.query.rows | 10);
    query.offset(req.query.skip | 0);
    if (req.query.sortField && req.query.sortOrder) { // if sorting is defined
      query.orderBy(req.query.sortField, req.query.sortOrder == 1 ? 'ASC' : 'DESC');
    }
    else if (sortBy) { query.orderBy(sortBy.column, sortBy.order == 1 ? 'ASC' : 'DESC'); 
    
    // .. fetching countQuery, then fetching query
is this possible ? Or is there any 'hack' to remove everything previously set to be selected ?

**Comment by absolux** [comment]
@Lukass445 
```js
// to get a count from a sub query
knex.count('*').from(query.as('t'))
```

**Comment by Lukass445** [comment]
Perfect, thank you!

**Comment by jayarjo** [comment]
@lukgri @absolux  where do you place this?

**Comment by lhenriquelpc** [comment]
Something that might be helpful is the fact that on knex you can put the select after the other parts of the query.

For exemple, you can do:

```
const query = knex.where(...).from(...);

if(conditionThatYouWant) {
   query.select('*');
} else {
   query.select('column_you_want');
}
```

Doing that, you probably don't need to feature of "removing" a select statement from the query. This issue is old, but I hope it helps someone else who stumbles upon it.
