### ISSUE TITLE
Regression in 0.12.7 for migration:make

### ISSUE THREAD

**Issue by eddieajau** [tgriesser/knex#1925]
Prior to 0.12.7 you could run `knex migrate:make` without a `config` option. It is now required so running `knex migrate:make` from the command line errors (however, it is not necessary for this function to run correctly).

**Comment by wubzz** [comment]
I'm guessing this refers to #1822 . I consider this a bug from the start, not as as current regression. Knex's documentation has always stated:

```
 The client parameter is required and determines which client adapter will be used with the library
```

The bug in reality was that the client parameter was not being validated as required.

I can see why this may be an annoyance, but technically writing any code that does not supply the `client` parameter has been coding 'agaist' the knex documentation from the start. I think it should always be validated as a required field as stated by the docs.

Your description makes it sound like knex should consider config options as required/optional depending on the function that is **going** to be called, which to me makes no sense at all.

@elhigu What's your view on this?

**Comment by elhigu** [comment]
I would say that it was a bug that it worked earlier.

**Comment by eddieajau** [comment]
> Your description makes it sound like knex should consider config options as required/optional depending on the function that is going to be called, which to me makes no sense at all.

I would consider that normal behaviour for CLI sub-functions to separate it's concerns, but I understand your decision (though it is a backward incompatibility so I would have bumped the minor version so users don't get caught out like this).

**Comment by elhigu** [comment]
@eddieajau pretty much every change we do, breaks some backwards compatibility in some degree (at least almost every item in this release's changelog).

So if we are very strict about always updating minor version when changing any functionality even when the change is bugfix, we would just end up to always bump minor version and put all changelog entries to breaking changes section...

To draw a line for not having to do always minor version update we've decided that only those changes which change documented functionality are considered as breaking changes worth of minor version update.

ps. though this change actually was changing documented functionality (there was inconsistent documentation about client attribute being required and not being required so). So it was error on my side not to spot that and update the minor.

**Comment by eddieajau** [comment]
@elhigu that's fine and that's your call, however there are developers like me that rely on other developers honouring Semver to the best of their ability. Can I suggest putting a moratorium on any more breaking changes in 0.12 so that we can just stay on this version if we want.  Thanks in advance for your consideration.

And yeah, I get it's a huge pain when you find what you know is a defect, but people think it's a feature :)
