### ISSUE TITLE
Querybuilder this vs parameter suggestion

### ISSUE THREAD

**Issue by ericeslinger** [tgriesser/knex#1927]
From the documentation about join functionality (although this is similar to complicated where / and / or stuff as well):

```
knex.select('*').from('users').join('accounts', function() {
  this.on(function() {
    this.on('accounts.id', '=', 'users.account_id')
    this.orOn('accounts.owner_id', '=', 'users.id')
  })
})
```

I've got plenty of problems in life, and keeping track of what `this` I'm using is one of them. It would be *awesome* to change the callback functionality to just add a parameter, so I could do this instead.

```
knex.select('*').from('users').join('accounts', function(qb) {
  qb.on(function(qb2) {
    qb2.on('accounts.id', '=', 'users.account_id')
    qb2.orOn('accounts.owner_id', '=', 'users.id')
  })
})
```
My specific use case is building semi-complicated joins from flat JSON arrays that parameterize a datamodel, which ends up doing stuff with `array.reduce()` over the array, and the whole thing is in an es2015 `class` object, so like I said: I don't want to mess around with `this` unless aaaabsolutely necessary.

**Comment by elhigu** [comment]
It already works the way you are asking... otherwise we couldn't use arrow functions either in query builder callbacks.

```js
> knex.select('*').from('users').join('accounts', function(qb) {
...   qb.on(function(qb2) {
.....     qb2.on('accounts.id', '=', 'users.account_id')
.....     qb2.orOn('accounts.owner_id', '=', 'users.id')
.....   })
... }).toSQL()
{ method: 'select',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [],
  __knexQueryUid: '00dc19c3-95f7-4aad-9757-edb40bb8b191',
  sql: 'select * from "users" inner join "accounts" on ("accounts"."id" = "users"."account_id" or "accounts"."owner_id" = "users"."id")' }
```
