### ISSUE TITLE
knex transaction is not working

### ISSUE THREAD

**Issue by leoxgnr93** [tgriesser/knex#1929]
Hi, 

I've been  trying to truncate a table inside a transaction trying to force the rollback just to verify if there is a problem it will rolled back in case.

Using
MySQL

I've tried 
SET autocommit = 0;
SET SQL_SAFE_UPDATES = 0;

But I got the  'Waiting for table metadata lock truncate' for obvius reasons but also tried the commit and did not work.

Please if you know what Im doing wrong, help me, Im really stucked here :S 

`
    let query: knex;
    let batchCompaniesInfoPromise = new Promise(
            (resolve, reject) => {
                query.transaction(function (trx: knex.Transaction) {
                    return query("dna_table").transacting(trx).truncate()
                        .then(trx.rollback)
                        .catch(trx.rollback)
                }).then(function (response) {
                    console.log("worked");
                    resolve("worked");
                }).catch(function (error) {
                    console.log("did not work");
                    reject("did not work");
                })
           }
        );
`

**Comment by elhigu** [comment]
Can you do what you are trying to do in mysql console? If not, then this is not knex related issue, but general mysql database question which should be asked in stackoverflow. 

If you are able to do this in myslq console, please add queries you are trying to do and I can tell how to do it with knex.
