### ISSUE TITLE
selectRaw

### ISSUE THREAD

**Issue by ozum** [tgriesser/knex#1932]
Hi,

I searched a `selectRaw` method in documentation to use operations in `select`. According to docs, there isn't.

For example selecting addition of two columns:

```sql
SELECT 
    "person"."salary" + "person"."bonus"
FROM
   "person"
```

Similar to `whereRaw`, below is my hypothetical assumption about this:

```js
knex
    .selectRaw('? + ?', ['person.salary', 'person.bonus'])
    .from('person');
```

Is there a way to generate operators in `select` using `knex`?

**Comment by elhigu** [comment]
```
knex
    .select(knex.raw('? + ?', ['person.salary', 'person.bonus']))
    .from('person');
```

should do the trick. You can pass knex.raw as parameter pretty much everywhere.

**Comment by ozum** [comment]
Thanks @elhigu, that would do what I need.

For completeness, adding `selectRaw` method is also good idea.

Kind regards,
