### ISSUE TITLE
Missing docs: Composite foreign key

### ISSUE THREAD

**Issue by adrianhelvik** [tgriesser/knex#1933]
The docs say the following:

**foreign — table.foreign(columns)**
Adds a foreign key constraint to a table for an existing column using table.foreign(column).references(column) or multiple columns using *table.foreign(columns).references(columns)*.

The italic part should say "table.foreign(columns).references(columns).on(table)". I had to look into the code to figure it out, so it would be nice if this was specified in the docs.

Thanks for a great library!

**Comment by kibertoad** [comment]
@adrianhelvik Created PR. Is the problem only for multiple columns use-case? Is the documentation for a single column correct?

**Comment by adrianhelvik** [comment]
From what I can recall, yes.
