### ISSUE TITLE
Can't create two separate knex clients

### ISSUE THREAD

**Issue by cpsubrian** [tgriesser/knex#1934]
I'm working on a helper for my test suite where I need two completely separate knex instances. I want one to actually connect to the database and I want to mock the other. Currently, the two knex instances must be sharing internal state because when I mock one, the other loses its ability to query the database. Any ideas?

Sample test case:

```js
var knex = require('knex')
var mockDb = require('mock-knex')
var config = {
  client: 'postgresql',
  connection: { database: 'ac', user: 'ac', charset: 'utf8' },
  pool: { min: 2, max: 10 },
  migrations: { tableName: 'knex_migrations' }
}

var db = knex(config)
var mocked = knex(config)

mockDb.mock(mocked)

// Can't query the 'db' instance, this hits the mocked connection.
db.raw('select * from users').then((res) => {
  console.log(res.rows)
  db.destroy()
  mocked.destroy()
})
```

**Comment by yutin1987** [comment]
maybe you cna try this sample code to mock:
```
import knex from 'knex';

export const query = jest.fn(() => Promise.resolve([]));

const client = class extends knex.Client {
  _query = query;
  acquireConnection = () => Promise.resolve({});
  processResponse = resp => resp;
  releaseConnection = () => Promise.resolve();
};

const config = {
  client: 'postgresql',
  connection: { database: 'ac', user: 'ac', charset: 'utf8' },
  pool: { min: 2, max: 10 },
  migrations: { tableName: 'knex_migrations' }
}

export db = knex(config);
export mocked = knex({ client });
```

**Comment by cpsubrian** [comment]
Thanks @yutin1987! That got me off on the right track.

For what it's worth, my use-case was a db mock I'm building for my knex/objection.js API. It provides helpers to run tests with mocked databases, real test databases (new test database create per suite), or a what I called 'query snapshot' mode.

'Query snapshot' mode uses a real test database during the first run (or specific re-runs) and saves all the query responses to disc in respective `__fixtures__/` directories. It then can use those snapshots on subsequent runs (via a mocked db) to save on the time it takes to create/teardown real databases and actually run queries.

Working now for my limited test-suite and we'll see how it evolves as the API gets bigger.

https://gist.github.com/cpsubrian/b4820b475e7262251a16fb286606e4f7

**Comment by cpsubrian** [comment]
@yutin1987 I ended up mocking the lower-level `client._query` instead, because I really just want to avoid the actual database-call but retain everything else (that may be postgres-specific).
