### ISSUE TITLE
upgrade to 0.12.x large query to string failing on memory....

### ISSUE THREAD

**Issue by jabbatico** [tgriesser/knex#1938]
just updating project to 0.12.x, and scale issues that we did not have prior to 12 are occurring. in particular. This statement:

const insert = trx.insert(batch).into('myTable').toString();

where batch is an array of objects, where some of the properties of this object are objects used to scale to very very large batch numbers. with upgrade to 12 i'm getting 

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory

with this line. I'm toString() to do an ON CONFLICT query in PG.

**Comment by elhigu** [comment]
try to run node with `node --max_old_space_size=4000` parameter to allow it to use more memory. Otherwise you need to lower the batch size you are trying to send at once. 

If there seems to be a memory leak or non-linear memory growth please reopen.

**Comment by jabbatico** [comment]
thank you very much for response. i was really looking to some insight as to why this memory limit was being pushed in .12.x and not in .11.x. we want the updated connection pooling of .12 but this limit has made us nervous about going backward on scalability in other places.
