### ISSUE TITLE
Knex:Error Pool2 - Error: ER_CON_COUNT_ERROR: Too many connections

### ISSUE THREAD

**Issue by ammar08429** [tgriesser/knex#1942]
While doing load test on the system , i started getting this error.
I have one question does knex closes the connection as soon as the query is completed?
Does it opens the connection after the query is build?

if not how can we change it to open connection only on query time and close it soon after.

**Comment by elhigu** [comment]
Looks like you are using older knex... currently generic-pool is used for connections. Try to set some timeouts to finetune pool behavior https://github.com/coopernurse/node-pool
