### ISSUE TITLE
Writing es6 code that can run with either Knex or plv8.execute()

### ISSUE THREAD

**Issue by deinspanjer** [tgriesser/knex#1944]
I'm writing some functions inside a Postgres DB using plv8.

I needed the flexibility and power of being able to develop and debug those functions outside of the DB proper, so I ported them into a small NodeJS project.  The project has a module which exports an object called "plv8" and that object has an elog() function as well as an execute() function so I can work with the code almost verbatim.  The elog() function just calls console.log, and the execute function calls `return knex.raw(query).then(result => { return result; });`

I started out fighting to find some way to get around the whole async problem, and eventually I gave up and just accepted returning a promise and modified the function code I'm writing and testing to accept a promise as follows:

```
return plv8.execute(query).then(function(result) {
  plv8.elog(DEBUG1, `Num rows: ${result.rowCount}`);
  let rows = result.rows;
  let formattedResult = {};
  // do some stuff with the rows
  return formattedResult;
});
```
The problem is that I now don't have code that can easily be put back into plv8 where the real plv8.execute() is a synchronous method that returns a raw JSON structure instead of the Knex Result class via promises.

The old code was along the lines of:
```
let rows = plv8.execute(query);
plv8.elog(DEBUG1, `Num rows: ${rows.length}`);
let formattedResult = {};
// do some stuff with the rows
return formattedResult;
```

Could anyone provide some tips or ideas on a reasonable way I could make the code work well in either world?  I'm reluctant to bring bluebird Promise into plv8 because I'm thinking since it is very synchronous, I might hit lots of problems if I start tossing promises around.  For instance, I'm not sure how I would ever actually be able to return a fully resolved result from a DB function written in plv8 if after I called plv8.execute(query), I wrapped it in a promise.

Thank you very much for your attention and help.

-Daniel

**Comment by kibertoad** [comment]
Considering that this is a year-old issue and no suggestions were provided, unfortunately, we probably should close it as stale, since even if a solution comes up, it is likely to be too late for original poster to benefit.
