### ISSUE TITLE
Unlock Table from forUpdate lock

### ISSUE THREAD

**Issue by jadslim313** [tgriesser/knex#1947]
I'm using "`for update`" to prevent race issues in my selection. You mention that The locks are saved in a table called "tableName_lock" with single column called is_locked that you need to set to 0 in order to release the lock.

My table is called requests, so I created a table called "requests_lock" and created a column called is_locked. that table never gets updated when I use for update. Is there anything I'm missing here?

```
bookshelf.knex.transaction(function(trx) {

 var query = bookshelf.knex('requests').transacting(trx).forUpdate().select('requests.id', 'requests.CreatedTime').then(function (user_roles) {
            console.log('user_friends: %j', user_roles);  
}).then(trx.commit)
  .catch(trx.rollback);
});

```

**Comment by elhigu** [comment]
You are confusing `tableName_lock` (locking system which prevents migrations from being ran multiple times)  with normal `select for update` locking which can be used if DB supports it. 

Check your database documentation how `select for update` works.

So `.forUpdate()` doesn't use any lock tables to work, but it is a feature of the database.
