### ISSUE TITLE
Executing MySQL stored functions and procedures 

### ISSUE THREAD

**Issue by SpeedyH30** [tgriesser/knex#1949]
So I may be being dumb with this one. 
I’m working on a front end and I need to execute some stored procedures and functions from and MySQL db, in node.
Im trying 
`router.get(‘/foo’, (req, res) => {`
    `db.raw(‘CALL subjobs()’).then((response) => res.json(response))`
`})` 
And this causes my api to pend and ultimately fail. And help with my understanding of how to execute both functions and procedures id greatly appreciate it

**Comment by absolux** [comment]
@SpeedyH30 
What kind of errors do you get ?

**Comment by SpeedyH30** [comment]
It just sits pending on console then eventually hits a 503 error.
Im deffinetly connected to the db as my 
`router.get(‘/foofoo’, (req, res) => {`
`db.select().from(foofoo).then((data) => res.json(data))`
`})`
works perfectly.

The function should be returning a `int`

**Comment by SpeedyH30** [comment]
I had it right was just the db Owner not giving permissions
