### ISSUE TITLE
NaN treated as column name in where('col', 'IN', [NaN])

### ISSUE THREAD

**Issue by diversario** [tgriesser/knex#1953]
This code

```js      
User.where('id', 'IN', [NaN]).fetchAll()
```

causes `ER_BAD_FIELD_ERROR: Unknown column 'NaN' in 'where clause'` error. I wasn't expecting `NaN` to be passed as a column name.

**Comment by elhigu** [comment]
Try if you get the same error with knex instead of bookshelf? 

This is the generated query though, which shows that NaN is not passed as column name in knex:

```
  bindings: [ NaN ],
  sql: 'select * from "wat" where "id" in (?)'
```

Most probably driver just doesn't understand how to handle an array with NaN inside. Doesn't seem to be related to knex.

**Comment by diversario** [comment]
Yep, it's mysql, docs say

```
NaN / Infinity are left as-is. MySQL does not support these, and trying to insert them as values will trigger MySQL errors until they implement support.
```

Sorry for bothering!
