### ISSUE TITLE
alterTable -> .alter() is not a function

### ISSUE THREAD

**Issue by mcchrish** [tgriesser/knex#1956]
```js
export function up (knex, Promise) {
  return knex.schema
    .alterTable('orders', function (table) {
      table.string('refund_id', 9).notNullable().alter()
    })
}
```

Results to
```
Knex:warning - migrations failed with error: table.string(...).notNullable(...).alter is not a function
TypeError: table.string(...).notNullable(...).alter is not a function
```

Using postgres by the way.

**Comment by elhigu** [comment]
Which knex version?

**Comment by cmodien** [comment]
just ran into this myself when trying to execute via terminal on mac os sierra… here's my version output:
22:55 $ knex --version
Knex CLI version:  0.12.8
Local Knex version:  0.10.0

Could it be picking up the local version instead of the cli version?

**Comment by toiye** [comment]
Thanks @cmodien 

I just hit this same problem.  
Knex CLI version:  0.12.9
Local Knex version:  0.12.6

Worked fine after an npm upgrade that brought my local version to 0.12.9.
