### ISSUE TITLE
.eslintrc.js file in the migration directory

### ISSUE THREAD

**Issue by kevinpeno** [tgriesser/knex#1957]
My project has an eslint rule that requires file names to follow a regex rule. However the naming scheme changes in the migrations folder and I need to put an eslintrc file into that folder to overwrite it. I cannot find an option to have knex ignore the file. Any options here?

**Comment by a-rodin** [comment]
You could rename it to just `.eslintrc`, not `.eslintrc.js`.

**Comment by elhigu** [comment]
sounds like viable solution, please comment / reopen if it doesn't work.

**Comment by kevinpeno** [comment]
Unfortunately, while still usable via eslint, this is a deprecated feature and not allowed by our coding standards. So, while that would solve the problem, I don't think it is really a solution for your users :)

**Comment by elhigu** [comment]
maybe you can add one extra directory to the path where migrations are and add the lint configuration in there...

```
src/otherlintingruleshere/migrations
```

Anyways there has been discussion about adding configuration option for migration extensions... with that you could for example set all migration files to `.migration.js` extension and lint configuration would be ignored.
