### ISSUE TITLE
What does knex do with open connections when the process is killed?

### ISSUE THREAD

**Issue by creyes52** [tgriesser/knex#1958]
I understand that knex uses a connection pool, 
given that the best practices are "Open a connection, use it and close is as soon as possible", I see no way of doing that in knex.

If the process is killed, will the opened connections be left opened on the server due to not being explicitely closed ?
What is the best practice to handle these case? It shouln't happen, but it can happen.

Environment:
client: oracle-instantclient12.1-basic-12.1.0.2.0-1
node: v6.10.0
oracle: 11g

**Comment by elhigu** [comment]
When process is killed open sockets to database will be closed automatically and if connection had transaction open it will be unrolled. 

If there is single query executing it might finish (depends on database) even after socket is closed, I don't know how oracle behaves in that case.
