### ISSUE TITLE
Knex compatibility with microservices

### ISSUE THREAD

**Issue by JeffreyCheng92** [tgriesser/knex#1961]
I'm working on a small project using microservices that all share one database. The issue is that I have migration files within each of the services and they do not all reside in one location. This results in the obvious error:

`The migration directory is corrupt, the following files are missing:`

Is there a way to ignore the `knex_migrations` table in mysql server or just migrate one migration at a time? Or do I just have to keep a separate database for each microservice? It seems to be built more for a whole application right now.

**Comment by elhigu** [comment]
Knex doesn't support having migration files spread over multiple places. 

To be honest it sounds pretty scary  to make sure that the migrations are ran in correct order if they are spread over many different places.

However as a hack you could try overriding the name of the migration table in each microservice (http://knexjs.org/#Installation-migrations) and that way each service will believe having their own DB with own migrations. In that way your database will end up with multiple migration tables.
