### ISSUE TITLE
check before alter table

### ISSUE THREAD

**Issue by igoreliasm** [tgriesser/knex#1963]
Hello everyone. I am trying to change a field on the database using alter table like this code:

```
exports.up = function(knex, Promise) {
  return Promise.all([
  	knex.schema.table('ew_user_address', function(t) {
  		t.string('session').after('id');
  	})
  ])
};

exports.down = function(knex, Promise) {
  return Promise.all([
  	knex.schema.table('ew_user_address', function(t) {
  		t.dropColumn('session');
  	})
  ])
};
```
So, when I run `migrate:latest` after the first time, the knex don't check if the field exists, then it return a erro like this:

```
varchar(255) after `id` - ER_DUP_FIELDNAME: Duplicate column name 'session'
```

There a good way to check it before like this `createTableIfNotExists`

Tks.

**Comment by absolux** [comment]
@igoreliasm According to the documentation, you can use `Schema.hasColumn()` 
```js
exports.up = (knex, Promise) => {
  return knex.schema.hasColumn('ew_user_address', 'session').then(flag => {
    return !flag && knex.schema.table('ew_user_address', t => t.string('session').after('id'))
  }
};

// will always drom the column
exports.down = (knex, Promise) => {
  return knex.schema.table('ew_user_address', t => t.dropColumn('session'))
}
```

**Comment by elhigu** [comment]
@igoreliasm I don't understand... if you run migrate:lastest twice, it should run the up script only once (and adds information about the migration already been ran to the migrations table). How are you able to get your error? 

I'll close this already, but feel free to add more comments... I'll be getting email notifications of them and answer when going through knex mails.

**Comment by igoreliasm** [comment]
Tks for your reply @elhigu but the @absolux gave me a good solutions for my problem.
;)
