### ISSUE TITLE
bailAfter in v0.12.x?

### ISSUE THREAD

**Issue by gordysc** [tgriesser/knex#1964]
This is related to #1939 .  When upgrading from 0.11 => 0.12 the connection pool manager was switched from `Pool2` to `generic-pool`.  However, not all of the previous expected options are available in the new pool management dependency, specifically: `bailAfter`.  How does one go about this with knex now?  This might be outside the intent of generic-pool, which is why I ask here.

**Comment by elhigu** [comment]
Did you read generic-pool documentation if there is same kind of option? What did bailAfter do?

**Comment by gordysc** [comment]
I did read the generic-pool documentation.  There is no option, hence why I'm asking here.  bailAfter in the latest version does nothing.  This is probably what lead to the author opening #1939 in the first place.

**Comment by elhigu** [comment]
Yep, I did understand that it was Pool2 option, that is why I asked what did it do before the change (I'm at work and didn't want to start checking Pool2 docs myself).

**Comment by gordysc** [comment]
@elhigu gotcha! In previous versions of knex w/ Pool2 it'd attempt to connect to a database for the specified amount of time.  So, in the case of #1939 as well as in our environments we use this option while a Postgres Docker container is spinning up.  This allows knex to connect to Postgres when it's available, rather than using a bash script to see if it's available.

**Comment by elhigu** [comment]
I wasn't able to find any similar functionality from generic-pool either, which would keep on trying to get connection if pool is in initial state... 

It seems that with knex > 0.12 one has to implement retrying to own startup code or to use shell scripts as you have done now.

**Comment by AlexSench** [comment]
Removing port from knex config fixed it for me.
