### ISSUE TITLE
`with` doesn't play nicely with `withSchema`

### ISSUE THREAD

**Issue by DataTables** [tgriesser/knex#1965]
Related to #1599 - I'm using Knex (awesome btw!) with Postgres and attempting to use CTEs through the `with` method, but I'm not having all that much luck.

```js
var db = knex.widthSchema('schemaName');

await db
  .with( 'tTwo', qb => {
    qb.select( '*' ).from( 'tableTwo' );
  } )
  .select( 'col1', 'col2' )
  .from( 'tableOne' )
  .leftJoin( 'tTwo', 'tableOne.id', 'tTwo.id' )
  .groupBy( 'id' )
```

Results in SQL such as:

```sql
with "tTwo" as (
  SELECT * FROM "tableTwo"
)
SELECT "col1", "col2"
FROM "schemaName"."tableOne"
LEFT JOIN "schemaName"."tTwo" ON "tableOne"."id" = "tTwo"."id"
GROUP BY "id"
```

There are two issues with the generated SQL:

1. I would have expected the table in the `with` statement to have inherited the schema name from the host. Instead it is defaulting to the public schema resulting in an error unless I add the schema name there as well.
2. The left join name should not be prefixed by the schema name - it should just be "tTwo"

I haven't looked at the code base yet, so I'm not sure what is involved in changing these, but are these two issues that I've mentioned valid and correct? If they are I'll take a look and see what I can do to implement them.

Thanks!

**Comment by absolux** [comment]
@DataTables The `withSchema()` only works for the table of the `FROM` clause. Knex cannot implicitly guess if the join table need or not to be prefixed.
IMO, you have to 
```js
await knex
  .withSchema('schema')
  .with( 'tTwo', qb => qb.select( '*' ).withSchema('schema').from( 'tableTwo' ) )
  .select( 'col1', 'col2' )
  .from( 'tableOne' )
  .leftJoin( 'tTwo', 'tableOne.id', 'tTwo.id' )
  .groupBy( 'id' )
```
or simply,
```js
await knex
  .with( 'tTwo', qb => qb.select( '*' ).from( 'schema.tableTwo' ) )
  .select( 'col1', 'col2' )
  .from( 'schema.tableOne' )
  .leftJoin( 'schema.tTwo', 'tableOne.id', 'tTwo.id' )
  .groupBy( 'id' )
```

**Comment by DataTables** [comment]
Thanks for the reply!

I agree - best way is just to write the query a little more explicitly.
