### ISSUE TITLE
Migrating every app launch.

### ISSUE THREAD

**Issue by lvandyk** [tgriesser/knex#1967]
How do you run the migrations at runtime?

I have a sqlite file that gets created at runtime and needs all migrations specified in the migrations directory to execute. What is the best way to achieve that? I see there is only a cli command.

My Scenario: Electron desktop app with nodejs + express inside. Users should be able to update their applications with ease (AKA all new migrations in DB get run automatically on next launch).

Thanks!

**Comment by absolux** [comment]
@lvandyk Please refer to the [migration API](http://knexjs.org/#Migrations-API) documentation

**Comment by lvandyk** [comment]
Thanks for the quick reply @absolux 

What I needed for anyone else struggling:
```
knex.migrate.latest();
```
