### ISSUE TITLE
Needs to install an uneeded dialects

### ISSUE THREAD

**Issue by nicklayb** [tgriesser/knex#1968]
Hi all, hope y'all doing well. I'm having an issue this morning. I tested it alone and everything works fine but in my vue-electron app, it says the followin error
```
Module not found: Error: Can't resolve 'mssql' in '/Users/nboisvert/Git/bd2app/node_modules/knex/lib/dialects/mssql'
```
The thing is, I don't use or need mssql. It asked me for mariasql before, I installed it because I thought it may be related with mysql but I don't get why I would need mssql.

I have a file `db.js` which loads my knexfile with correct envrionment :
```js
var config = require('../knexfile.js');
var env = 'development';
var knex = require('knex')(config[env]);

module.exports = knex;

knex.migrate.latest([config]);
```
And this is my knexfile
```js
module.exports = {
    development: {
        client: 'mysql',
        connection: {
            host: '127.0.0.1',
            user: 'super_username',
            password: 'super_password',
            database: 'super_database'
        }
    },
    production: {
        client: 'oracle',
        connection: {
            host: '127.0.0.1',
            user: 'super_username',
            password: 'super_password',
            database: 'super_database'
        }
    }
};
```
And I use it with vuex like that 
```js
import db from '../../../db';
db('users').select('*').then((users) => {
            _state.users = users;
        }).catch(console.error);
```

Thank you all for your help

**Comment by nicklayb** [comment]
FYI, I tried using `let db = require('../../../db');`  instead of `import db from '../../../db';` and now I have this error
`Module not found: Error: Can't resolve '../build/Debug/sqlclient' in '/Users/nboisvert/Git/bd2app/node_modules/mariasql/lib'`

**Comment by kibertoad** [comment]
@elhigu Probably can be closed due to age?

**Comment by AlrikOlson** [comment]
@kibertoad I'm actually having a similar issue. I want to create some queries for SQL Server, so I need to use ```client: 'mssql'``` when instantiating the knex object.

I've run the following commands:

```
npm i knex --save
npm i mssql --save
```

Here is my service that creates an instance of the knex object:

```javascript
import knex from 'knex';

class QueryService {
  constructor() {
    this.knex = knex({
      client: 'mssql'
    });
  }
}
```

This is the output when I try to build my application:

```
./node_modules/tedious/lib/connector.js
Module not found: Can't resolve 'dns' in '...snipped...\node_modules\tedious\lib'
```

This same output does _not_ happen when I create a standalone javascript file and execute it with ```node index.js```

All I want to use this library for is generating SQL queries from a custom JSON schema, I don't want to have any of the functionality for actually connecting to the database and executing the generated query.
