### ISSUE TITLE
generic-pool default connection reaping leaks memory running against mysql

### ISSUE THREAD

**Issue by jacobheric** [tgriesser/knex#1969]
We've noticed that ever since our upgrade to Knex 0.12.0 (which started using the generic-pool), our app leaks memory.  I've narrowed the leak down to the default connection/resource reaping behavior present in the generic-pool.  It's possible to recreate this leak very simply, you don't even need to fetch anything from the db.  You only need to start knex with a db pool.

Mysql DB setup:
```
CREATE DATABASE leak_db;
CREATE USER 'leak_user'@'localhost' IDENTIFIED BY 'leak_password';
GRANT ALL PRIVILEGES ON leak_db.* TO 'leak_user'@'localhost' WITH GRANT OPTION;
FLUSH PRIVILEGES;
```

Simple app with knex and db pool, leak.js:

```
const fs = require('fs');
var knex = require('knex');
const heapdump = require('heapdump');

var knex = require('knex')({
  client: 'mysql',
  debug: true,
  connection: {
    host : '127.0.0.1',
    user : 'leak_user',
    password : 'leak_password',
    database : 'leak_db'
  },
  pool: { min: 5, max: 15 }
});

setInterval(collectGarbage, 2000);

function collectGarbage() {
  try {
    console.info('Collecting your garbage');
    global.gc();
    var heapUsed = process.memoryUsage().heapUsed;
    console.info('Program is using ' + heapUsed + ' bytes of Heap.');
    fs.appendFile('heap.stats', heapUsed + '\n');
  } catch (e) {
    console.info('You must run program with: node --expose-gc index.js');
    process.exit();
  }
}

```

deps:

```
  "dependencies": {
    "heapdump": "^0.3.7",
    "knex": "^0.12.7",
    "mysql": "^2.13.0"
  }
```

With this the heap grows indefinitely.  If you start this with limited old gen space (max_old_space_size), it will blow the heap and die eventually:

```

    2: arguments adaptor frame: 3->2
Security context: 0x282add7c9e59 <JS Object>
    3: InnerArrayForEach(aka InnerArrayForEach) [native array.js:952] [pc=0x297bff1374d0] (this=0x282add704189 <undefined>,br=0x7a59b154331 <JS Function destroy (SharedFunctionInfo 0x7a59b1528f1)>,bs=0x30040e00ac69 <a Pool with map 0x341d4481d1d1>,w=0x3aea31483ac1 <JS Array[5]>,x=5)
    4: forEach [native array.js:~956] [pc=0x297bff1fd21c] (this=0x3aea31483a...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
[1]    40635 abort      node --expose-gc --max_old_space_size=16 leak.js
```

I've plotted the heap growth that I wrote out above: 

![vanilla-knex-with-pool-no-activity](https://cloud.githubusercontent.com/assets/191780/23916596/205557ce-08c3-11e7-9128-1c50d041a2d8.png)

With *some* initial db activity, the growth is more dramatic. 

We rolled back to Knex version 0.11.10 and this leak went away. I'm filing this here because latest Knex 0.12.7 is using generic-pool 2.4.2, which is a stale branch. I've verified that the leak still exists running Knex against generic-pool 2.5.4, which is an active branch.  I haven't tried against 3.1.* because that is not a drop in replacement.

**Comment by elhigu** [comment]
Hi, thanks for the awesome report. There might be some timers added in knex side, which may also cause the leak.

**Comment by jacobheric** [comment]
I don't *think* it's your timer.  If I turn off connection reaping on the generic-pool then the leak also appears to go away, like so:

```
  pool: {
    refreshIdle: false,
    reapIntervalMillis: 0,
    min: 5,
    max: 10
  }
```

We don't want to linger on knex 0.11.10 too long and we don't want to spend too much time vetting the reaping config tweaks against generic-pool 2.4.2 if you're going to move. What's the timeframe to move knex off the stale branch and get to 3.1.*?

**Comment by robhawkes** [comment]
Can confirm I'm seeing the same leak when connecting to a Postgres database. Can also confirm that disabling connection reaping on the pool stops the leak.

I'm using `knex@0.13.0`

**Comment by wubzz** [comment]
Closing this since knex uses tarn.js now. Reopen if issue persists.
