### ISSUE TITLE
How should I call a MySQL Stored Procedure which returns data?

### ISSUE THREAD

**Issue by cteevin** [tgriesser/knex#1975]
I really need your help with this, I'm using **_Knex version : 0.12.6_**, please be patient with the long explanation

## MySQL Side
I have this simple MySQL table:
```
CREATE TABLE Users  
(userId int(10) unsigned NOT NULL AUTO_INCREMENT,
 firstName varchar(50) COLLATE utf8_spanish_ci NOT NULL,
 lastName varchar(50) COLLATE utf8_spanish_ci NOT NULL,
 PRIMARY KEY (userId)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```
By running this query:
```
Select firstName, lastName From Users Where userId = 1;
```
I obtain this result:

firstName | lastName
------------ | -------------
John | Doe

I've created this SP:
```
CREATE DEFINER=`root`@`%` PROCEDURE `spTesting`(pUserId int(10) unsigned)
BEGIN
   Select firstName, lastName From Users Where userId = pUserId;
END
```
And, by running it like this:
```
Call spTesting(1);
```
I naturally obtain the same result:

firstName | lastName
------------ | -------------
John | Doe

## Node.js Side
When I try the query directly using Knex, like this:
```
knex.raw('Select firstName, lastName From Users Where userId = 1;').then(function(result) {
  console.log(result);
});
```
The returned info has the expected result inside **RowDataPacket**:
```
[ RowDataPacket { firstName: 'John', lastName: 'Doe' } ], 
[ FieldPacket {
    catalog: 'def',
    db: 'myDB',
    table: 'Users',
    orgTable: 'Users',
    name: 'firstName',
    orgName: 'firstName',
    ... },
  FieldPacket {
    catalog: 'def',
    db: 'myDB',
    table: 'Users',
    orgTable: 'Users',
    name: 'lastName',
    orgName: 'lastName',
    ... } ] ]
```
But when I call the SP using Knex, this way:
```javascript
knex.raw('Call spTesting(1);').then(function(result) {
  console.log(result);
});
```
I've got only this:
```javascript
[ [ [ [Object] ],
  OkPacket {
   fieldCount: 0,
   affectedRows: 0,
   insertId: 0,
   serverStatus: 2,
   warningCount: 0,
   message: '',
   protocol41: true,
   changedRows: 0 } ],
  [ [ [Object], [Object] ], undefined ] ]
```
Not even **RowDataPacket** is there... what should I add to my code, or configurate on it in order to obtain the same result in both situations?

**Comment by elhigu** [comment]
Try console.dir(result, {depth: null}) instead of console.log

**Comment by cteevin** [comment]
What a fool!, thanks man, everything is working now.
Cheers.

**Comment by yasinkya** [comment]
knex.raw('call listS();').then((rows)=>{
  console.log(rows[0][0])
})

**Comment by jrichardsz** [comment]
Before,

```
var gateways = await this.dbSession.raw('call find_user_gateways(?)', [country]);
resolve(gateways);
```

this was the result

![image](https://github.com/knex/knex/assets/3322836/67764d73-440f-42c1-b965-721a9984da29)

After this fix: gateways[0][0]

```
var gateways = await this.dbSession.raw('call find_user_gateways(?)', [country]);
resolve(gateways[0][0]);
```

![image](https://github.com/knex/knex/assets/3322836/9caeb497-97f8-4c18-accb-9d466c2687a9)
