### ISSUE TITLE
Weird behavior after del()

### ISSUE THREAD

**Issue by denkomanceski** [tgriesser/knex#1980]
UPDATE: The bug was found, check the bottom for details
Okay, this is the weirdest thing I have ever seen: 
I have these two functions:
```  
static getCourses(userId: string): Promise<Array<Course>> {
    return courseSchema.select('*').from('courses').where({user_id: userId});
  }
```
and
 ``` 
 static deleteCourse(userId: string, courseId: string): Promise<any> {
    return courseSchema.where({user_id: userId, course_id: courseId}).from('courses').del()
  }
```
The first time when I call getCourses, everything works perfect, than after that query is done, I am calling delete on the first course that is returned (there are many courses so I just delete the first one returned), and that is also fine, its deleting the course normally.. but than if I call getCourses again, I get back "0", not even an error, just a plain '0'. If I restart the server or rerun the script, it works fine.. can someone help? I really enjoy using knex.js but this is very weird to me..
Here is screenshot from the test that I am using: http://prntscr.com/ell7cm

I made this test, because before they were in express controllers, and I had no idea why after /delete, when I make /get to get the list of everything I was receiving 0.

P.S. As far as I know, knex is stateless, it doesnt really care what is happening between queries.. when I restart the script, the connection to the db gets renewed and it works fine.. until than, it doesnt work properly
P.S.S This database is test so I can send the needed scripts here and access to it if someone wants to try

This is the log for debug: true mode. The sql queries are wrong:
```
{ method: 'select',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [ '7708f64c-e363-4492-8be4-625da76ea2c6' ],
  __knexQueryUid: '5f9b6dc3-2feb-43a8-b2d7-68ced5f505b0',
  sql: 'select * from "course"."courses" where "user_id" = ?' }
2
3dd38652-1570-40a3-a28a-3c1cf50a7a80
{ method: 'del',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings:
   [ '7708f64c-e363-4492-8be4-625da76ea2c6',
     '7708f64c-e363-4492-8be4-625da76ea2c6',
     '3dd38652-1570-40a3-a28a-3c1cf50a7a80' ],
  __knexQueryUid: '2c70e1dd-e437-4de0-b591-18c2bf88891b',
  sql: 'delete from "course"."courses" where "user_id" = ? and "user_id" = ? and "course_id" = ?',
  returning: undefined }
{ method: 'del',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings:
   [ '7708f64c-e363-4492-8be4-625da76ea2c6',
     '7708f64c-e363-4492-8be4-625da76ea2c6',
     '3dd38652-1570-40a3-a28a-3c1cf50a7a80',
     '7708f64c-e363-4492-8be4-625da76ea2c6' ],
  __knexQueryUid: '20672ec6-f567-40f7-8acd-466f5e1bd35f',
  sql: 'delete from "course"."courses" where "user_id" = ? and "user_id" = ? and "course_id" = ? and "user_id" = ?',
  returning: undefined }
undefined
0 'All Courses'

```

I found the bug:

The problem was that at the beginning I was declaring ```knex.withSchema("user")``` and I was using the same instance all the time. Now I changed it to call ```knex.withSchema("user").select()`` on each query and it works fine.. I guess reusing the same instance of it is forbidden ?

**Comment by wubzz** [comment]
@denkomanceski Like you discovered it does not "spawn new instances" everytime the function is called. It also explains why the bindings in your queries kept "piling up" (so to speak) between queries. 

There are two solutions to your example:

1. Instantiate a new querybuilder each time
2. Use the `.clone()` function on an existing querybuilder.
