### ISSUE TITLE
Fails when not using a connection

### ISSUE THREAD

**Issue by markasoftware** [tgriesser/knex#1981]
Running this line from the documentation, `var knex = require('knex')({});`, gives the error `Error: knex: Required configuration option 'client' is missing.`, but as I understand it it should still work for just generating a query string like this.

**Comment by wubzz** [comment]
The documentation also states `The client parameter is required and determines which client adapter will be used with the library.`. It has been contradicting itself for quite some time. Recently we merged a change that made this quoted statement correct, by actually validating that `client` is always required.

So the documentation currently invalid - Instantiating knex without a client is not supported. See #1822 for the change and the related discussions.

There's an issue about this in knex/documentation: https://github.com/knex/documentation/issues/28
