### ISSUE TITLE
knex.with only works with select

### ISSUE THREAD

**Issue by mike-engel** [tgriesser/knex#1985]
Howdy! It seems like `knex.with` only works with `select` as the inner query. PostgreSQL, and I assume MySQL, allow other types of queries.

Here's a reduced test case: https://runkit.com/58d2db6b9ade7700135c9496/58d2db6b9ade7700135c9497

Here's how I would expect them to be output:
```sql
with "inserted" as (
  insert into "test_table" ("test") values (123456) returning *
)
```

If I'm doing something horribly wrong, please let me know. Thanks for making knex!

**Comment by absolux** [comment]
@mike-engel 

`with` clause is expected for MySQL 8+ and MariaDB 10.2, so MySQL 5.7 doesn't support it

PostgreSQL allow the other types of queries, [look at docs](https://www.postgresql.org/docs/9.5/static/queries-with.html)

A workaround for knex is possible with raw queries
```js
var insertQuery = knex.returning('*').insert({ test: 123456 }).into('test_table')

knex.with('inserted', knex.raw(insertQuery.toString()))
```
will output
```sql
with "inserted" as (insert into "test_table" ("test") values (123456) returning *) select *
```

**Comment by mike-engel** [comment]
@absolux Thanks. I understand that `knex.raw` is a workaround, but when you're inserting an object with 10-20 keys, it gets too verbose for that.

**Comment by mike-engel** [comment]
I've gotten around this by storing the call I would normally put in the callback as a variable, and then calling `.toString()` on that variable and passing that into `knex.raw`.

**Comment by elhigu** [comment]
@absolux instead of passing `.toString()` to `knex.raw()`you can pass bindings and sql separately. 

Like this:

```js
let insertQuery = knex.returning('*').insert({ test: 123456 }).into('test_table').toSQL();
knex.with('inserted', knex.raw(insertQuery.sql, insertQuery.bindings))
```

That way the code will be more protected from sql injection, because db driver will pass values as parameter bindings to DB server.

**Comment by UchihaVeha** [comment]
how i get it with knex ???
```pgsql
WITH new_tags_values (tag) as (
   VALUES ('one', 'two', 'three')
)
```

**Comment by wubzz** [comment]
Closing this as it seems to work in 0.15.1.

```javascript
var withUpdateQuery = knex.with('updated', (kq) => {
  kq.where({ id: 1 }).update({ test: 123456 }).into('test_table')
});

//with "updated" as (update "test_table" set "test" = 123456 where "id" = 1) select *
```

**Comment by elhigu** [comment]
Yep, I remember fixing this quite long ago.
