### ISSUE TITLE
Client connection hangs indefinitely

### ISSUE THREAD

**Issue by smulesoft** [tgriesser/knex#1986]
### Problem

This code from [client.js](https://github.com/tgriesser/knex/blob/master/src/client.js) is not enough to validate the connection.

```js
      // src/client.js:205-211
      validate: (connection) => {
        if (connection.__knex__disposed) {
          helpers.warn(`Connection Error: ${connection.__knex__disposed}`)
          return false
        }
        return this.validateConnection(connection)
      }
```

### Test

1. Initialize postgres

2. Initialize `knex` pool:
    ```js
    pool: {
      min:                       2,
      max:                       7,
      idleTimeoutMillis:         20 * 1000,
    }
    ```
3. Shutdown postgres

4. Reinitialize postgres

5. Create 2-5 queries (before `idleTimeoutMillis` fires a `removeIdle()` call), one of them will hang.

**Comment by smulesoft** [comment]
Do you need help reproducing this?

**Comment by elhigu** [comment]
If I recall correctly knex doesn't really support case where sql databases is closed and then started again. I cannot remember why is though and it would be nice feature though.

**Comment by elhigu** [comment]
Related to #1833 #1341 #936 #1877 and many more. Closing in favor of #1833
