### ISSUE TITLE
Update with join

### ISSUE THREAD

**Issue by RWOverdijk** [tgriesser/knex#1988]
Why is this happening?

```
> knex('foo as f').innerJoin('bar as f').toString();
'select * from "foo" as "f" inner join "bar" as "f"'
> knex('foo as f').innerJoin('bar as f').update({a: 'b'}).toString();
'update "foo" as "f" set "a" = \'b\''
```

I'd expect the join to be there. I'm prettier sure this used to work with 0.11.x

Might be related to https://github.com/tgriesser/knex/issues/557

**Comment by elhigu** [comment]
@RWOverdijk knex has never supported joins in updates (it would require also supporting FROM clause for UPDATE statement for example in postgresql).

**Comment by RWOverdijk** [comment]
So why close this issue? We can add support for it as it's a perfectly plausible use case.

**Comment by elhigu** [comment]
Duplicate / Question was answered, so I closed the issue. We discussed about this on gitter too and decided that new issue could be opened which will give proper description and discussion how update join / from support should be implemented.

**Comment by gerardolima** [comment]
hey, @elhigu, since supporting UPDATE with JOIN is/will be handled in another thread, could you, please, hefer it on this one?

**Comment by elhigu** [comment]
Maybe this one https://github.com/knex/knex/issues/2796
