### ISSUE TITLE
knex.whereIn with subqueries outputs invalid SQL

### ISSUE THREAD

**Issue by mike-engel** [tgriesser/knex#1989]
#### Description
When using an array of subqueries with `whereIn`, it improperly formats the SQL, preventing the query from being successfully run

#### Actual behavior
Reduced test case: https://runkit.com/58d54e3669bd5800151eab73/58d54e3654c1be00146c2160

The output SQL from that query is
```sql
select * from "table_two" where "tableOneId" in (select "id" from "table_one" where "value" = 'test'), (select "id" from "table_one" where "value" = 'alternate')
```
As you can see, the values passed to `in` aren't wrapped in parentheses causing the error.

#### Expected behavior
The output SQL from the query should be
```sql
select * from "table_two" where "tableOneId" in ((select "id" from "table_one" where "value" = 'test'), (select "id" from "table_one" where "value" = 'alternate'))
```

I've got a workaround manually formatting the subqueries with `knex.raw`, but it's a hack. Thanks!

**Comment by elhigu** [comment]
Thanks for great issue, it was really easy to understand the problem 👍 

You are passing array containing subqueries to whereIn which is not supported (I didn't even knew that it was possible in postgres).

If you like to add support to it we need to discuss more how arrays that are passed as values to `.where()` should be interpreted generally in knex (in sql there is at least 3 different array syntaxes and knex doesn't have currently any way how to determine which one is correct in which context)...  

For now you should be able to do your query like this:

```js
.whereIn('id', knex.raw('(?,?)', [subQuery1, subQuery2]))
```

If you like to have new feature to knex with better support for this, please open another issue where more people can discuss how arrays should be treated in knex and maybe we find some good general solution.
