### ISSUE TITLE
Connection pooling - Min and Max seem to use only default values

### ISSUE THREAD

**Issue by cteevin** [tgriesser/knex#1994]
Hello there, I am trying to understand why if I am setting the min and max values for pooling, I am not viewing the expected result, please take a look here:

### The Connection File
    'use strict';
    import conf from '../config.js';
    import bookshelfFactory from 'bookshelf';
    import knexFactory from 'knex';

    const knex = knexFactory({
      client: conf.DB.client,
      connection: {
        host: conf.DB.connection.host,
        port: conf.DB.connection.port,
        user: conf.DB.connection.user,
        password: conf.DB.connection.password,
        database: conf.DB.connection.database,
        pool: { min: 5, max: 20 }
      }
    });
    console.dir(knex.client, {depth: null})    //Output is shown at the end of this post
    const bookshelf = bookshelfFactory(knex);
    bookshelf.plugin('registry');
    bookshelf.plugin('pagination');
    export default bookshelf;

Once I run my app, I can only see two db connections, the ones with MiniSec as DB

### MySQL Result
    mysql> show processlist;
    +--------+-------------+---------------+---------+---------+------+-------+------------------+
    | Id     | User        | Host          | DB      | Command | Time | State | Info             |
    +--------+-------------+---------------+---------+---------+------+-------+------------------+
    |  12507 | development | 172.16.11.99  | None    | Query   |    0 | None  | SELECT col1, c...| 
    |  12508 | development | 172.16.11.99  | None    | Sleep   |  208 | None  | NULL             | 
    |  12797 | development | 172.16.11.99  | MiniSec | Sleep   |   15 | None  | NULL             | 
    |  12798 | development | 172.16.11.99  | MiniSec | Sleep   |   15 | None  | NULL             | 
    +--------+-------------+---------------+--- -----+---------+------+-------+------------------+
    4 rows in set (0.00 sec)

### Connection File Output
    Client_MySQL {
      config:
       { client: 'mysql',
         connection:
          { host: '172.16.11.100',
            port: '3306',
            user: 'development',
            password: 'xxxxxxxxxxxx',
            database: 'MiniSec',
            pool: { min: 10, max: 30 } } },        <<<<<------ This is what I configured
      connectionSettings:
       { host: '172.16.11.100',
         port: '3306',
         user: 'development',
         password: 'xxxxxxxxxxxx',
         database: 'MiniSec',
         pool: { min: 10, max: 30 } },        <<<<<------ This is what I configured
      driver:
       { createConnection: [Function: createConnection],
         createPool: [Function: createPool],
         createPoolCluster: [Function: createPoolCluster],
         createQuery: [Function: createQuery],
         escape: [Function: escape],
         escapeId: [Function: escapeId],
         format: [Function: format] },
      __cid: 'client0',
      pool:
       Pool {
         _factory:
          { min: 2,        <<<<<------ This is the default value
            max: 10,        <<<<<------ This is the default value
            name: 'mysql:mysql:client0',
            log: [Function: log],
            create: [Function: create],
            destroy: [Function: destroy],
            validate: [Function: validate],
            idleTimeoutMillis: 30000,
            returnToHead: false,
            refreshIdle: true,
            reapInterval: 1000,
            priorityRange: 1 },
         _inUseObjects: [],
         _draining: false,
         _waitingClients: PriorityQueue { _size: 1, _slots: [ [] ], _total: null },
         _availableObjects: [],
         _count: 2,
         _removeIdleTimer: null,
         _removeIdleScheduled: false },
      valueForUndefined:
       Raw {
         client: [Circular],
         sql: 'DEFAULT',
         bindings: undefined,
         _wrappedBefore: undefined,
         _wrappedAfter: undefined,
         _debug: undefined },
      _events:
       { start: [Function],
         query: [Function],
         'query-error': [Function],
         'query-response': [Function] },
      _eventsCount: 4,
      makeKnex: [Function: makeKnex] }

The Pool section of the previous object keeps showing the default values for min and max, and that min value is the number of connections I can see opened after running the app... what's going on?, what am I missing?

Cheers.

**Comment by wubzz** [comment]
@cteevin `pool: { min: 5, max: 20 }` should not be within the `connection` object, but rather as part of the main config object.

```javascript
const knex = knexFactory({
  client: conf.DB.client,
  connection: {
    host: conf.DB.connection.host,
    port: conf.DB.connection.port,
    user: conf.DB.connection.user,
    password: conf.DB.connection.password,
    database: conf.DB.connection.database,
  },
  pool: { min: 5, max: 20 },
});
```

**Comment by cteevin** [comment]
Thanks a lot @wubzz, no more issues now.

Cheers.
