### ISSUE TITLE
Find out if transaction is active

### ISSUE THREAD

**Issue by ivome** [tgriesser/knex#1995]
Is there an official way to find out, if a knex object currently has an active transaction? 
Something like the following: 
```javascript
console.log(knex.isTransacting());  // -> false
knex.transaction(function(trx) {
  console.log(trx.isTransacting()); // -> true
});
```

**Comment by elhigu** [comment]
There is no official way to check if the knex instance is transaction or nor, nor what is the transaction state. If you wish to implement that feature I won't object. If you decide to implement this, please open another issue with some specification how it could work to discuss about it a bit more first.

**Comment by mtlewis** [comment]
Stumbled on this recently via a Google search - for anyone else coming here the same way, knex now includes an `isCompleted` method on transactions for this purpose, cf. [transaction docs](https://knexjs.org/guide/transactions.html).
