### ISSUE TITLE
Multiple Connections with same host

### ISSUE THREAD

**Issue by orgertot** [tgriesser/knex#1996]
Hey,
When Knex has multiple connections open to the same host but in different "connection-elements"(?) it is not switching the database.

For Example: I create two connection and store the knex object in a array.
```javascript
               var knex = require('knex')({
                    client: 'mysql',
                    connection: {
                        host     : server.get("db_ip"),
                        port     : server.get("db_port"),
                        user     : server.get("db_username"),
                        password : server.get("db_password"),
                        database : server.get("db_database")
                    },
                    pool: { min: 2, max: 7 }....
                    connectionPool.push(knex);
```
So I have my variable `connectionPool` with two connections:

1. host = 127.0.0.1 , database = admin
2. host = 127.0.0.1 database = test

When I now use this:
`connectionPool[`**0**`].raw('SHOW TABLES')....`
and then
`connectionPool[`**1**`].raw('SHOW TABLES')....`

The Problem is that `connectionPool[`**1**`].raw('SHOW TABLES')....` will return the result of `connectionPool[`**0**`].raw('SHOW TABLES')....`

I hope this is a little bit understandable

**Comment by elhigu** [comment]
Could you please add complete minimized example what are you doing, what is the result and what are you expecting?

If you are connecting 2 different databases, you need to initialize 2 separate knex instances.

```
let admin Db = require('knex')({ ... admin database connection parameters ... });
let testDb = require('knex')({ ... test database connection parameters ... });

// reusing the name from OP
let connectionPool = [
  adminDb, testDb
];
```

**Comment by orgertot** [comment]
Thanks for the quick response. let me use your code:
```
let admin Db = require('knex')({ ... admin database connection parameters ... });
let testDb = require('knex')({ ... test database connection parameters ... });

// reusing the name from OP
let connectionPool = [
  adminDb, testDb
];

//now get all the tables
connectionPool[0].raw("SHOW TABLES") // <----- Returns the tables of database admin
connectionPool[1].raw("SHOW TABLES")  // <----- Returns the tables of the database admin 
```
I did expect `connectionPool[1].raw("SHOW TABLES")` to return the tables of database test obviously.

**Comment by elhigu** [comment]
You have most probably an error in your connection parameters. Make sure you hardcode both db connection parameters in your code.


```js
let adminConfig = { ..hard code paramaters here ... };
let testConfig = { ..hard code paramaters here ... };

let admin Db = require('knex')(adminConfig);
let testDb = require('knex')(testConfig);

...

```

I've been using knex all the time with multiple separate instances for different DBs without any problems.

**Comment by orgertot** [comment]
Well you are so right..
Thanks Javascript for accepting = in a if..... 
I will stick my head in sand for a bit now
