### ISSUE TITLE
node-mssql 4..0.0 incompatibility

### ISSUE THREAD

**Issue by TobiasFT** [tgriesser/knex#1999]
With the new release of node-mssql 4.0.0 knex "dialect" is no longer compatible.

" var connection = new _this.driver.Connection(_this.connectionSettings);"

Connection has been renamed ConnetionPool. Changing this stops knex from crashing but returned me no data.

**Comment by homywu** [comment]
hey guys, any idea of when this can merge? it's an easy fixed, but no one reviews it?
