### ISSUE TITLE
Slow query logging

### ISSUE THREAD

**Issue by mightyguava** [tgriesser/knex#2001]
Is there a way to log instrument slow queries and slow transactions with Knex? I know setting `DEBUG=knex` will enable detailed logging, but it'd be nice if there was something that lets me report on timings directly within the code, rather than having to parse the logs.

Does something like this exist? Like a way to hook before/after queries?

**Comment by elhigu** [comment]
Duplicate... https://github.com/tgriesser/knex/issues/1844

**Comment by elhigu** [comment]
I wrote some test/example code how to trace transaction durations https://runkit.com/embed/679qu91ylu4w
