### ISSUE TITLE
Problems with migrations

### ISSUE THREAD

**Issue by danielsalles** [tgriesser/knex#2004]
I'm having trouble understanding the migrations run with foreingkey. In the example of the [documentation](http://knexjs.org/#Schema-foreign) says the table `user` that has a `user_id` field is referencing  `Items.user_id_in_items`? I think that approach was a bit confusing.

What I'm trying to do is 1 `series` has N `categories`.
And this is the code of the migrations:
create_categories.js:

```
exports.up = function(knex, Promise) {
  return knex.schema.createTable('categories', (t) => {
    t.increments('id').unsigned().primary()
    t.dateTime('createdAt').notNull()
    t.dateTime('updatedAt').nullable()
    t.dateTime('deletedAt').nullable()

    t.string('name').notNull()
  })
};

exports.down = function(knex, Promise) {
  
};
```

create_series.js:

```
exports.up = function(knex, Promise) {
  return knex.schema.createTable('series', (t) => {
    t.increments('id').unsigned().primary()
    t.dateTime('createdAt').notNull()
    t.dateTime('updatedAt').nullable()
    t.dateTime('deletedAt').nullable()

    t.string('name').notNull()
    t.text('description').notNull()
    t.string('image').notNull()
    t.string('metaCritic').notNull()

    t.integer('category_id').unsigned()
    t.foreign('category_id'.references('Categories.category_id_in_categories'))
  })
};

exports.down = function(knex, Promise) {
  
};
```

And error:

> Using environment: development
> Knex:warning - migrations failed with error: "category_id".references is not a function
> TypeError: "category_id".references is not a function

**Comment by elhigu** [comment]
At least you have  parenthesis wrong in like 

```
 t.foreign('category_id'.references('Categories.category_id_in_categories'))
```
