### ISSUE TITLE
Is there any way I can use Knex.js for string pattern matching ?

### ISSUE THREAD

**Issue by VanessaRLewis** [tgriesser/knex#2009]
I would like to use knex.js to carry out a query similar to 
```
"SELECT FROM table_name
WHERE column ILIKE 'XXXX%"
```
Do I have to use whereRaw for this?

**Comment by elhigu** [comment]
`.where('column', 'ilike', 'XXXX%)` should do it.

**Comment by arthuranteater** [comment]
knex('users').where('columnName', 'like', '%rowlikeme%')
Outputs:
select * from `users` where `columnName` like '%rowlikeme%'

**Comment by bayardmartins** [comment]
.where('column', 'like', `${XXXX}%`)

also works with % in both sides `%${XXXX}%`

**Comment by jawadcode** [comment]
@bayardmartins Does that function auto escape malicious strings?

**Comment by elhigu** [comment]
that will compile to SQL : `WHERE "column" like ?` and ? is sent as a binding  with value `%somthing%`. So knex is not excaping it but the driver does.
