### ISSUE TITLE
Run seed only once

### ISSUE THREAD

**Issue by handmilkingsoftware** [tgriesser/knex#2010]
How to detect if the database has data on it ?

The very first time I deploy my app, I would like to conditionally run migrations and, in case this is the very first time Im deploying the app run the seeds. I can move that to the deploy script or process.

My seed files are not for testing or development, in the production version of the app I have seed files to populate the database with things like user-roles, user-privileges, system-admin-user, states, places, zip codes, etc.

The deploy script (actually chef.io) has a flag to enable run the seeds, but after the first deploy in production I had to remove that flag, it would be the same as hardcoding the knex-seed command and then remove it after the first deploy. If I didn't I would end with duplicated data as seed would run on each deploy. If there was a way to detect whether the seeds have been executed at least once to skip the knex seed comand would be great.

`knex seed:run-once --env development`

Thanks for this library, I really love knex.
cheers.

**Comment by elhigu** [comment]
Just add that logic to your seedfile. If you want to make seed to be ran just once, use migrations instead.
