### ISSUE TITLE
Inner Join and Dynamic Query on multiple tables

### ISSUE THREAD

**Issue by VanessaRLewis** [tgriesser/knex#2012]
I want to do an inner join on four tables & be able to query on any of the 4 tables columns. For example, how can I do the following query in knex:

```
select * 
from aps, switchs, wlcs, venues
where aps.switch_id = switchs.id
and aps.wlc_id = wlcs.id
and aps.venue_name = venues.name
and wlcs.name = 'w1'
and venues.name = 'v1'
and switchs.ip = '1.11.1.1';
```
I used the object syntax of .where() to store my where clauses in an object Qu.
```
Qu { 'wlcs.name': 'w1',
  'venues.name': 'v1',
  'switchs.ip': '1.11.1.1',
  'aps.wlc_id': 'wlcs.id',
  'aps.switch_id': 'switchs.id',
  'aps.venue_name': 'venues.name' }
```

I then ran the following query:

```
  Knex('aps')
        .select()
        .innerJoin('wlcs','aps.wlc_id','=','wlc.id')
        .innerJoin('switchs','aps.switch_id','=','switch.id')
        .innerJoin('venues','aps.venue_name','=','venue.name')
        .where(Qu)
        .debug(true)
        .then(function (resultCol){
             console.log("resultCol",resultCol);
        })
        .catch(function (err){
            console.log("Err",err);
        });
```

It gives me a 

> missing FROM-clause entry for table "wlc"

error. 

What is the right way to do this?

**Comment by elhigu** [comment]
You are joining `wlsc`, but you are referring it `wlc.id` instead of `wlcs.id`. Also there are some errors in your code something like this might work:
 https://runkit.com/58d3c5b9ae69180014e717c3/58f1f724dd2700001236e4e4
