### ISSUE TITLE
Pass an argument to knex.migrate.latest()

### ISSUE THREAD

**Issue by mwpastore** [tgriesser/knex#2014]
I'm running Knex migrations programmatically and I'd like to pass an argument to `knex.migrate.latest({})` at runtime. I see that the configurable object passed to `#latest()` gets merged into the migration configuration, but this configuration does not seem to be available from within an up/down function. 

- Can we pass the config as an extra argument to up/down?
- Can we bind up/down to the migration's `this` at call time to make `this.config` available?
- Is there another option I'm missing?

**Comment by amagdas** [comment]
I need this missing feature as well.

**Comment by vincenttheeten** [comment]
I'd like to see the same thing.

I was hoping to store some kind of `tenantId` on the config object, so I can run migrations for specific tenants in my multi-tenant setup; e.g. create a table under the right (postgres) schema per tenant.

I saw version 0.14.5 introduced some improvements for schema names and migrations.
Unless I'm missing something, this only uses the schema in `schemaName` to make the migrations table, not scope the `up` or `down` migration calls.

**Comment by kibertoad** [comment]
@vincenttheeten Can't you do pretty much this by using different changelog table names for different tenants and then passing different folders as migration sources?

**Comment by elhigu** [comment]
Isnt it visible in `knex.client.config` either?

**Comment by bertho-zero** [comment]
Personally I use `const { schemas } = knex.client.config` in my migrations.

**Comment by elhigu** [comment]
Fixed by #2802
