### ISSUE TITLE
New and close connection every 30 seconds

### ISSUE THREAD

**Issue by chuan137** [tgriesser/knex#2015]
Hello,

I use knex for postgresql, and notice that for every 30 seconds, two new connections open and then close. Is it expected to happen, why?

Thanks,
Chuan

**Comment by elhigu** [comment]
Check pool2 timeouts and settings and play with them. Otherwise provide minimized test code which can be used to reproduce the behavior you are experiencing.

**Comment by chuan137** [comment]
Thanks for the tip. Knex has switched back to generic-pool and the corresponding setting is idleTimeoutMillis

**Comment by elhigu** [comment]
ah yeah, generic-pool I meant 👍
