### ISSUE TITLE
knex seed:run heap OOM

### ISSUE THREAD

**Issue by Matzu89** [tgriesser/knex#2018]
I have a **huge** seed file (csv) and am using `knex-csv-transformer` to import this. Using this tool I already succeeded to import multiple other csv files, but this specific one contains `7,541,147` rows to be exact. I know, quite a lot, but also quite necessary.

It results in the OOM down below.

```==== JS stack trace =========================================

Security context: 0x16b7713266a1 <JS Object>
    2: _prepInsert [/[redacted]/api/node_modules/knex/lib/query/compiler.js:~579] [pc=0xc65c96132ea](this=0x2023fac6d3f1 <a QueryCompiler_PG with map 0xc0805c503e1>,data=0x2023fac6d459 <JS Array[7541147]>)
    3: insert [/[redacted]/api/node_modules/knex/lib/query/compiler.js:177] [pc=0xc65c96104e5](this=0x2023fac6d3f1 <a QueryCompiler_PG with map 0xc0805c503e1>)
    4: inse...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [knex]
 2: 0x12b81cc [knex]
 3: v8::Utils::ReportOOMFailure(char const*, bool) [knex]
 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [knex]
 5: v8::internal::Factory::NewUninitializedFixedArray(int) [knex]
 6: 0xe647c3 [knex]
 7: v8::internal::Runtime_GrowArrayElements(int, v8::internal::Object**, v8::internal::Isolate*) [knex]
 8: 0xc65ae4043a7
Aborted (core dumped)```

**Comment by absolux** [comment]
@Matzu89 
You can chunk it to multiple pieces then import each one, there is a module for that [csv-chunk](https://www.npmjs.com/package/csv-chunk)

**Comment by elhigu** [comment]
@Matzu89 @absolux is right, you need to start transaction and then read that csv file e.g. in batches of 1000 lines and do multiple inserts. 

Also there are probably better tools to import huge amount of csv data to sql db unless you are doing additional normalization/processing for the data in javascript side before inserting.
