### ISSUE TITLE
Add warning if one uses the createTableIfNotExist

### ISSUE THREAD

**Issue by elhigu** [tgriesser/knex#2019]
https://github.com/tgriesser/knex/issues/2016 and
https://github.com/tgriesser/knex/issues/1303

Also docs should explain why it shouldn't be used and why hasTable + createTable is better choice.

**Comment by wswoodruff** [comment]
Thanks for _this_ warning! I didn't know it was problematic at all

**Comment by jeffijoe** [comment]
The migrator itself uses this, so might want to update that as well.

https://github.com/tgriesser/knex/blob/master/src/migrate/index.js#L156-L163

**Comment by elhigu** [comment]
@jeffijoe  👍  good idea

**Comment by elhigu** [comment]
@jeffijoe https://github.com/tgriesser/knex/pull/2473
