### ISSUE TITLE
How to set timezone for transaction?

### ISSUE THREAD

**Issue by vishchiv** [tgriesser/knex#2022]
I want to apply [this](http://stackoverflow.com/questions/10797720/postgresql-how-to-render-date-in-different-time-zone") example, but seems like its not possible to implement with knex. Anybody know how to do some configuration in transaction before actual query?

**Comment by elhigu** [comment]
Maybe I didn't understand the question, but you can do that by making the query as a first query inside the transaction... just like you normally do queries inside transaction.

In the link of the OP was solution:

```sql
begin;
set local timezone to 'EST5EDT';
--- and some more queries
end;
```

You can do that in knex like this:

```js
knex.transaction(trx => {
  return trx.raw(`set local timezone to 'EST5EDT'`)
    .then(() => {
      // and some more queries...
      return trx('MyTable');
    });
}).then(() => console.log('YAY transaction complete'));
```
