### ISSUE TITLE
Is it safe to run `knex migrate:latest` concurrently? (question / feature request)

### ISSUE THREAD

**Issue by olalonde** [tgriesser/knex#2027]
I am adding the following `entrypoint.sh` to a Dockerfile and was wondering what would happen if I started multiple containers concurrently. Ideally, only one container would run the migration while others would be blocked. I was wondering if knex does that already or if I'd have to take care of this myself.

```bash
# entrypoint.sh
#!/bin/sh
set -e
# Inspiration: https://github.com/deis/controller/blob/master/rootfs/bin/boot

# make sure database exists
node ./lib/scripts/create-db.js || true

# run database migrations (todo: make sure this can be safely be run
# concurrently)
npm run knex -- migrate:latest

# passthrough
exec "$@"
```

**Comment by elhigu** [comment]
Depending on database you are using, second instance running the migrations either throw an exception or it just waits (this comes in next knex release) until the first process is ready. More info about it is found here https://github.com/tgriesser/knex/pull/1962
