### ISSUE TITLE
Calling functions on PostgreSQL

### ISSUE THREAD

**Issue by roytz** [tgriesser/knex#2044]
Hi,
Is there a way calling postgres functions without using `knex.raw()` in order to get the result parsed to an object using the knex driver?
For example, If I have a `Users` table and I have a pg function called `get_user_by_some_field` that does some work on other tables but finally returning an `User` object - how can I call the function (with parameters) and get the result parsed to an `User` object?

Thanks

**Comment by elhigu** [comment]
knex.raw is the only way, more info here: https://github.com/tgriesser/knex/issues/2021 there are also some older issues talking about calling stored procedures.

**Comment by roytz** [comment]
Thank you @elhigu , I'll comment in the issue you linked to.
