### ISSUE TITLE
0.13 released... let's think about 0.14!

### ISSUE THREAD

**Issue by cjnqt** [tgriesser/knex#2045]
(If this is the wrong format for discussing roadmaps, please feel free to close this issue.) 

I'd just like to highlight that tgriesser did [beautiful work here](https://github.com/tgriesser/knex/issues/1681#issuecomment-248921480) on improving transactions. He commented that `the transaction / context stuff is decently solid and so I'm considering releasing it sometime soon along with #1647 as a 0.14-alpha`. 

Just wanted to highlight this and see if anyone else is interested in improving transactions? Or is it just me who thinks it is very much needed?

**Comment by elhigu** [comment]
@cjnqt I think that the issue you referred is the correct place to discuss about those features. @tgriesser is the only one who knows more about their status.

They are indeed nice features, specially being able to select used connection  by yourself and creating transactions, which doesn't hog connections eagerly.
