### ISSUE TITLE
Escape characters when using knex.raw

### ISSUE THREAD

**Issue by roytz** [tgriesser/knex#2047]
I know this is probably a question that has been answered before but I was looking into old issues and still haven't found the right solution for my case.
I'm using knex.raw to call a function I created on my postgres db. The thing is that I pass some parameters with special characters which I need to escape.
Is there an easy way doing that using knex?
Thanks

**Comment by elhigu** [comment]
Which are those special characters? Probably you should check out how underlying `node-postgres` driver handles them.  

Some escaping stuff done in knex side is found here: https://github.com/tgriesser/knex/blob/2e1a459a9e740f24b9a4647bd4da427854e551dd/src/query/string.js#L4

**Comment by roytz** [comment]
Special characters such as `$`.
I know there are inner functions that deal with it but I was looking for a function I can use straight from knex API.
I was using it to pass hashed password but now I just transform the hashed password to base64 string so I don't have this problem no more.

**Comment by shai32** [comment]
I am also having the same problem, how do I store  special characters in the db with  knex.raw ?

**Comment by elhigu** [comment]
you should be able to use `$` without any tricks:

```js
> knex('$table$').select('$column$').where('$something$', '$').toSQL()
{ method: 'select',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [ '$' ],
  __knexQueryUid: '7d88f4b0-cff2-461b-a799-bf5b2fc43c29',
  sql: 'select "$column$" from "$table$" where "$something$" = ?' }
> 
```

**Comment by roytz** [comment]
When passing string the contains $ to a function in postgres using knex.raw there's a problem

**Comment by elhigu** [comment]
@roytz could you add an example code which shows the problem to check it out?

**Comment by thefoxie** [comment]
@elhigu 
Still having this issue. I'm trying to pass parameter with $. 

Works
```js
knex().raw( "select * from users where id = :_user_id", { _user_id: user?.id || null });
```
Doesn't work
```js
knex().raw( "select * from users where id = :$user_id", { $user_id: user?.id || null });
```

**Comment by elhigu** [comment]
Yeah, probably regular expression there requires that named replacement is alphanumerical or something like that.
