### ISSUE TITLE
Support conditions inside json

### ISSUE THREAD

**Issue by roytz** [tgriesser/knex#2048]
Is there a way adding search conditions that apply to json?
I mean, let's say I have `Users` table with a JSON column called `email` (the json should be 2 fields - 'address' and 'isVerified'). Now, if I want to search for a user with a specific email I would use the raw query - `select * from "Users" where email->>'address' = 'abc@gmail.com';`
Is there a way doing that using knex syntax?

**Comment by elhigu** [comment]
With knex the only way how to do jsonb queries is `knex.raw`. 

You can limit the part of raw to where it is needed like: 

```js
knex('Users').where(knex.raw(`??->>'address'`, ['email']), 'abc@gmail.com');
```

Only knex based DB library that I know which supports jsonb queries is objection.js. With that you can do:

```js
// note: this doesn't work with knex
.where('email:address', 'abc@gmail.com');
```

**Comment by roytz** [comment]
Thanks @elhigu 
It applies also to json (not jsonb), right?

**Comment by elhigu** [comment]
Yep, the same applies to json type too.

**Comment by anshulsahni** [comment]
do we have a better solution than using `raw()` now?

**Comment by elhigu** [comment]
No.
