### ISSUE TITLE
Outdated warning on SQLite's support of the DEFAULT clause

### ISSUE THREAD

**Issue by chaucerbao** [tgriesser/knex#2058]
Is this warning still accurate?

```
Knex:warning - sqlite does not support inserting default values. Set the `useNullAsDefault` flag to hide this warning. (see docs http://knexjs.org/#Builder-insert).
```

SQLite does seem to [support the DEFAULT clause](http://www.sqlite.org/lang_createtable.html#dfltval)

**Comment by elhigu** [comment]
Sqlite supports setting default for column, but it does not allow you to say that in certain part DEFAULT value should be set. Check documentation of inserting multiple rows.
