### ISSUE TITLE
Lack of documentation for withKeyName

### ISSUE THREAD

**Issue by carragom** [tgriesser/knex#2059]
Reading on the source code. The fluent API for `foreign keys` seem to have a `withKeyName` to name the specific key. Yet there is no mention of this method anywhere in the docs. Is this method beta or something?. Or should the docs be modified to actually mention it?.

**Comment by elhigu** [comment]
Probably it should be documented if it works and is tested. There are some forgotten features in `knex` which are forgotten just because of missing docs.

**Comment by fakhrul8moo** [comment]
`Knex:warning - migrations failed with error: table.integer(...).notNullable(...).unsigned(...).references(...).inTable(...).withKeyName is not a function`

It not working. I am using knex ^0.11.10

**Comment by elhigu** [comment]
it was implemented in 0.12.7 
https://github.com/tgriesser/knex/blob/master/CHANGELOG.md#0127---17-feb-2017

**Comment by elhigu** [comment]
Moved documentation issue to docs repo issues
