### ISSUE TITLE
Bug: raw `in (?)` array bindings not mapped correctly

### ISSUE THREAD

**Issue by safeerjiwan** [tgriesser/knex#2060]
We're trying to do a simple array binding that looks like:
`count(1) filter (where state in ('matched', 'scheduled', 'nurturing'))`

The binding is incorrect in the generated sql from `knex.raw`:
```
$ node
> let knex = require('knex')({ client: 'pg' });
undefined

> knex.raw('count(1) filter(where state in (?))', [['matched', 'scheduled', 'nurturing']]).toString();
'count(1) filter(where state in (\'{"matched","scheduled","nurturing"}\'))'

> knex.raw('count(1) filter(where state in (?))', ['matched', 'scheduled', 'nurturing']).toString();
Error: Expected 3 bindings, saw 1
```

This seems like a bug. The `(?)` binding, given either an array-within-array (as documented in Knex's [Raw Parameter Binding section](http://knexjs.org/#Raw-Bindings)) results in `(\{....\})`.

**Comment by wubzz** [comment]
See #1537
