### ISSUE TITLE
`first()` turns an `update` query into a `select`

### ISSUE THREAD

**Issue by jisaacstone** [tgriesser/knex#2061]
```node
> knex('pool_enterprise.test').update({'state': 'awesome'}).first().toSQL()
{ method: 'first',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [ 1 ],
  __knexQueryUid: '3698eb45-5165-46af-aa43-9376e048cb27',
  sql: 'select * from "pool_enterprise"."test" limit ?' }
```

Probably should just throw an error? I mean you can do an `UPDATE RETURNING` but I don't seen `LIMIT` clause allowed [in the postgres docs](https://www.postgresql.org/docs/9.1/static/sql-update.html)

Tested on postgres.

How it happened is I had a limit supposed to be on a subquery but I got the parens wrong. Was a bit hard to debug.

Knex version:
```node
knex@^0.12.9:
  version "0.12.9"
  resolved "https://registry.yarnpkg.com/knex/-/knex-0.12.9.tgz#aa852138c09ed46181e890fd698270bbe7761124"
```

**Comment by elhigu** [comment]
Thanks for the report. Throwing error sounds good. 

Also probably knex should throw an error in every case where calling new builder method changes some update -> plain select.

**Comment by avanarden** [comment]
Experiencing a similar issue when changing `first()` with `del()`

**Comment by moltar** [comment]
Hm, I kinda assumed `update().first()` would return a single updated row, instead of an array. Maybe a `.single()` method would be useful for such cases, if we want to avoid having a double meaning for `.first()`?

**Comment by moltar** [comment]
A note on the above, for posterity.

Since knex uses bluebird promises under the hood, it is possible to use the [`.spread` method](http://bluebirdjs.com/docs/api/spread.html), which flattens returned array into function arguments.

```js
knex('foo')
  .where('id', 1)        // match by PK, so we could only ever have one row updated
  .update({ s: 2 }, '*') // yet this normally would resolve to an array of 1 rows
  .spread((row) => {})   // .spread flattens the returned array into a single arg
```

**Comment by elhigu** [comment]
Yes. It would make sense for update().first() to try to return first updated item if possible. But that throwing error in impossible cases would still be good to have.

**Comment by wubzz** [comment]
With `.returning` not being supported by all dialects it might not be good to give `.first()` two different meanings between dialects.

I would opt for just throwing an error that update was changed to select.
