### ISSUE TITLE
Intersect statement

### ISSUE THREAD

**Issue by krutijan1** [tgriesser/knex#2064]
Hi,
sql intersect statement exists neither as part of documentation nor in source code (version 0.13.0). Are there any plans to implement this feature? Or is there reason why not to implement it? I see union statement has already been implemented.

Thx

Jan

Btw awesome library, makes my life easier

**Comment by elhigu** [comment]
No reason, nobody just hasn't implemented it. There are tons of other features of different SQL dbs which are supported only by raw queries.
