### ISSUE TITLE
Client:runner(connection)    parameter name is incorrect

### ISSUE THREAD

**Issue by helloghui** [tgriesser/knex#2067]
in method  **runner** (\src\client.js) is the parameter name should be **builder** instead of connection?
`  
  runner(connection) {
    return new Runner(this, connection)
  }
`
below is  comment  from Runner(\src\runner.js) constructor 

> The "Runner" constructor takes a "builder" (query, schema, or raw) and runs through each of the query statements

**Comment by elhigu** [comment]
True, feel free to fix 👍

**Comment by helloghui** [comment]
ok, fixed
