### ISSUE TITLE
Migration directory error 

### ISSUE THREAD

**Issue by MahmoudBakry** [tgriesser/knex#2070]
I make a migration  to create a table and i write the 2 function (up , down) and save may code with my table's schema , now i need to run this migration to Affect in my DB , but when i put that command (knex migrate:latest) , i have error (the migration directory is corrupted) . 
what can i do ?

**Comment by elhigu** [comment]
Did you change a name of some existing migration file? To fix stuff you'll probably have to change contents of migrations table manually. Please add to issue exact error that you are getting, list of files you have in migrations directory and listing what is stored in migrations table in your db.

**Comment by MahmoudBakry** [comment]
Thank you my bro , yes i have changed some of my  existing migration file , when i  drop  this tables manually , my new migration file work will without error .
