### ISSUE TITLE
Is it possible to create knex migration files from existing database?

### ISSUE THREAD

**Issue by lucaswxp** [tgriesser/knex#2073]
I already have a database, can knex read and dump the migration files to get me started? Or the only option is to create it by hand? Since it's 50+ tables, I want to avoid that.

**Comment by elhigu** [comment]
Migration system has no idea of your database state before running any migrations, so you can use your current SQL dump for starting point and then start doing future schema changes through migrations on top of that.

So there is no way for example to extract db schema and convert it automatically to knex.schema calls.

**Comment by farnetani** [comment]
I see in https://github.com/niradler/rve-knex-migration, but it's not complete!

**Comment by KhalidBhyan** [comment]
Take the SQL parts that you need to be migrated then execute them using knex.raw()
I didn't test that but you can give it a try

**Comment by hermesalvesbr** [comment]
Today exist any tool to do this?

**Comment by yudiz-bhoomit** [comment]
Yeah same question now can we do that I am using Objection + Knex in my current project currently all tables were created manually but now I want to create a migration for all the tables so is it possible that knex can generate migrations file from existing db and then I can create more migrations for future db changes.

Or still I need to create all the migrations by my self ?
