### ISSUE TITLE
returning always shows: [0]

### ISSUE THREAD

**Issue by windwww** [tgriesser/knex#2075]
Knex('users')
  .returning('id')
  .insert(users)
  .then(function(num) {
    console.log(JSON.stringify(num) + ' OK!');
  })
  .catch(function(err) {
    console.log('err', JSON.stringify(err));
  })

I always get [0] from the returning, anyone has idea.
I am using "mysql  Ver 14.14 Distrib 5.7.18, for Linux (x86_64) using  EditLine wrapper"

**Comment by elhigu** [comment]
mysql doesn't support returning.
