### ISSUE TITLE
Show warning if 'transacting' is misspelled or transacting object is empty when defined

### ISSUE THREAD

**Issue by freshsun** [tgriesser/knex#2077]
I see #1469 but my problem might be easier to fix.

Occasionally I misspelled {transacting:t} to {transaction:t}, and sometimes I pass the transacting object to event listeners with params(model, attrs, options), and I will send {transacting:options.t} to next function, which is wrong and should be {transacting:options.transacting}. It's hard to find this typo.

Don't know if anyone else made this mistake before. I guess logs an error when debugging is enabled might help.

**Comment by elhigu** [comment]
We can't be checking for typos and wont go to that route. If you are trying to use undefined variable knex can't help you with it.

However we could add check to `.transacting()` method which makes sure that passed object is valid.

**Comment by freshsun** [comment]
It might be better if I rephrase?
My question is:
Is it possible to do a strict check on options in 
bookshelf: model.save([key], [val], [attrs], [options]) 
and 
knex: transacting(transactionObj)
When:
1. user defined a key shouldn't exist in the option object, like 'transaction'
2 .user defined null for a key that shouldn't be null, like "transacting:NOTDEFINED'

Maybe i should open this issue in bookshelf repo?
I think i can get a quick dirty solution, redefine the bookshelf save/destroy/update method with proto, so i can write some code to do this check.

**Comment by elhigu** [comment]
yep, this should go to bookshelf repo. Knex cannot do the thing you are asking for.
