### ISSUE TITLE
Make .transacting(trx) method to validate that input trx is valid

### ISSUE THREAD

**Issue by elhigu** [tgriesser/knex#2079]
Currently if trx == undefined or trx == {} there are no errors thrown. 

Will be breaking change. 

Related to discussion in https://github.com/tgriesser/knex/issues/2077

**Comment by freshsun** [comment]
Thanks elhigu. If now errors are thrown, a warning is ok, even if it's controlled by a DEBUG option. I can hack this in my app but I guess this feature might save other people's time, occasionally.
