### ISSUE TITLE
MSSQL: update with limit

### ISSUE THREAD

**Issue by iw2rmb** [tgriesser/knex#2081]
knex swaps values for query:
`knex('TABLE').limit(foo).update({ FIELD: bar })` will build correct query but bindings are [bar, foo] instead of [foo, bar]

**Comment by absolux** [comment]
@iw2rmb Bindings depend on the position of the relative parameter in the query, not in the order in which they are supplied, so 
```js
knex('table').limit(5).update({ field: value })
// and 
knex('table').update({ field: value }).limit(5)
```
will always compile to 
```sql
update "table" set "field" = ? limit ?
```
and the bindings will always be [ 'foo', 5 ]

**Comment by elhigu** [comment]
Works as intended, lets reopen if this is causing building invalid queries.
