### ISSUE TITLE
Transaction rollback error behaviour went funny in #1970

### ISSUE THREAD

**Issue by morungos** [tgriesser/knex#2083]
I've found some strangely confusing new behaviour from transactions originating in 138e13b8b1, i.e. #1970. The issue is that I'm deliberately forcing rollbacks for testing, and whenever I do, I get errors: reporting "Transaction rejected with non-error", unless I am extremely careful about the way the promise resolves to a non-undefined value. This is not documented anywhere. 

This seems to be the intended behaviour of this patch, but the consequence is that any use of `trx.rollback()` forces the `.catch` handler on the overall transaction, with an explicit error "Transaction rejected with non-error". This is frankly odd and counterintuitive behaviour, since there is nothing about a rollback that is an obvious rejection. 

A close reading of #1970 seems to imply that we're expected to pass a value to `trx.rollback()`, and this does appear to work, but there is no documentation of that, or even a good reason for it. After all, SQL rollbacks don't move values around. I'm fairly sure it'd be simpler if people wanted to get a result out of a rolled back transaction, they'd be OK handling that on their own. 

Here's my minimal code:

```
const knex = require('knex')({
  client: 'sqlite3',
  connection: {
    filename: './test.sqlite3'
  },
  useNullAsDefault: true
});

return knex.transaction((trx) => {
  return trx('users').insert({email: "X1", given_name: "X1", family_name: "X1", created: Date.now()})
    .then(() => trx.rollback())
})
.catch((err) => {
  console.log("We get here", err)
})
.then(() => knex.destroy())
.catch(() => knex.destroy())
```

This throws a noisy error at "We get here". 

Changing `trx.rollback()` to `Promise.reject()` makes no difference. 

But changing it to `Promise.reject(null)`, we still get the catch, but without such a noisy error, as it isn't being logged by the patch in 138e13b8b1. I can't see a clear good reason for this strange behaviour based on the rejection value.

What is truly weird is that `trx.rollback()` doesn't reject in an intuitive way (either by throwing or rejecting) but continues the promise chain, and even if the final result is then `Promise.reject(null)`, we still get the noisy error. So if `trx.rollback()` is used, somehow the final value is forced to be undefined and the noisy error can't be inhibited. 

However, if `trx.rollback()` (and it's friendly rejection alternatives) really will always follow `.catch()` on the transaction (as a rejection of the transaction, this might make sense) this should be very clearly documented, and it isn't. 

The error message is extremely confusing (cost me a few hours upgrading code from 0.11.x), and at the least, the documentation would gain from a clear statement that any transaction that fails (or is rolled back) will be classed as rejected.

I'd also suggest reconsidering the "Transaction rejected with non-error" messages, which aren't hugely meaningful, since rejecting a transaction isn't an error. One solution might be as simple as making the default argument to `trx.rollback()` being null rather than undefined.

**Comment by elhigu** [comment]
Indeed transaction rollback / commit functions are not properly documented. I added documentation issue about it https://github.com/knex/documentation/issues/37

More background why the change was made is here: https://github.com/tgriesser/knex/issues/1966 all the reasoning is there tl;dr its easier to find accidental rollbacks / rejects when error is required, and it is pretty bad practice to reject promise without an error using throw new Error() for rejecting is nice.

> What is truly weird is that trx.rollback() doesn't reject in an intuitive way (either by throwing or rejecting) but continues the promise chain, and even if the final result is then Promise.reject(null), we still get the noisy error. So if trx.rollback() is used, somehow the final value is forced to be undefined and the noisy error can't be inhibited.

> However, if trx.rollback() (and it's friendly rejection alternatives) really will always follow .catch() on the transaction (as a rejection of the transaction, this might make sense) this should be very clearly documented, and it isn't.

You are mixing two different styles of using transactions. That is not allowed and probably causes some unexpected behavior. If you are returning promise from callback function of transaction, you should never call commit / rollback and just reject  / resolve of the returned promise and knex will implicitly commit/rollback in its internals.

Instead of this:
```js
return knex.transaction((trx) => {
  return trx('users').insert({email: "X1", given_name: "X1", family_name: "X1", created: Date.now()})
    .then(() => trx.rollback())
})
.catch((err) => {
  console.log("We get here", err)
})
```

You should do either:

```js
return knex.transaction((trx) => {
  return trx('users').insert({email: "X1", given_name: "X1", family_name: "X1", created: Date.now()})
    .then(() => {
      throw new Error('Rolling back, because I feel like it');
    }))
})
.catch((err) => {
  console.log("We get here", err)
})
```

or

```js
return knex.transaction((trx) => {
  trx('users')
    .insert({email: "X1", given_name: "X1", family_name: "X1", created: Date.now()})
    .finally(() => trx.rollback(new Error('Rolling back, because I feel like it #2')))
})
.catch((err) => {
  console.log("We get here", err)
})
```

These cases are documented in http://knexjs.org/#Transactions there could be added big disclaimer that **if you are returning promise, don't call rollback / commit** by yourself.

> I'd also suggest reconsidering the "Transaction rejected with non-error" messages, which aren't hugely meaningful, since rejecting a transaction isn't an error. One solution might be as simple as making the default argument to trx.rollback() being null rather than undefined.

Having `null` as default would be against of spirit of change discussed in https://github.com/tgriesser/knex/issues/1966

**Comment by morungos** [comment]
Hmm, I still think this could be handled better.

If either `rollback()` or `commit()` has been called and yet a promise is returned, a warning could alert people. 

But still, I don't see a rollback as an `Error`, although it's evidently true that considering the transaction as rejected is more than reasonable. However, to say:

> it is pretty bad practice to reject promise without an error 

is going a little far. (Yes, I know the Bluebird docs say that, but I don't want that forced on my, especially since it isn't in the standards.) Technically, I'd be happy if it was an `Exception` (a la Java) but since JS doesn't have them, we have to negotiate a way through. But the point stands, a rollback is not an error. Requiring everyone to make their own random error message to do a rollback is truly forcing opinionation where it isn't wanted. Maybe mask that by having a `Rollback` people can instantiate and use as a rejection reason. 

Promises aren't the same as try/catch, otherwise we'd never be bending them into transactions. So we don't have to follow the same reasoning for `throw` in promise rejections.

**Comment by elhigu** [comment]
> If either rollback() or commit() has been called and yet a promise is returned, a warning could alert people.

Yup, I wrote that to the documentation issue, that in that case throwing an error would be nice.

For the rest I just have to disagree. Rollback always causes transaction that is promise-like object to be rejected. So it is an error in `knex`. If you are familiar how async / await works with promises rejecting is pretty much the same that throwing an exception.

Also IIRC latest Node will call process exit app if there are leaked unhandled rejections (I've seen that in error messages like shown in this http://thecodebarbarian.com/unhandled-promise-rejections-in-node.js.html).

**Comment by morungos** [comment]
For future reference, this was fixable, but I've had to rewrite a bunch of tests to make it right. The problem is, for testing, I have a small fake transaction wrapper that always rolls back. That doesn't work nicely unless you can mix promises and `trx.rollback()`, because test harness suck at creating dynamic extends around tests, and I could do that with `trx.rollback()` but not (apparently) with promises alone. I hate changing code to make it testable, but this was a case where I didn't have a choice.

In the end I wrote a `withServer()` function that I can simply import into each and every test, and organized all the code to require promises everywhere, so `withServer()` could tag on an error to rollback the transaction it created. 

One of those nasty interactions between transactions and testing, I suppose.
