### ISSUE TITLE
Allow to customize how identifiers must be wrapped

### ISSUE THREAD

**Issue by koistya** [tgriesser/knex#2084]
This would unlock scenarios such as automatically converting **camelCase** to **snake_case** and vise verse. See https://medium.com/p/956357872fe4

It could look something like this (`db.js`):

```js
import knex from 'knex'

function wrapIdentifier(type, value) {
  if (type === 'as') return ....;
  if (type === 'select') return ....;
  return ...;
}

export default knex({
  client: 'pg',
  connection: process.env.DATABASE_URL,
  wrapIdentifier,
});
```

Please vote up if you're planning to use this feature, or vote down if you think it shouldn't be in the library.

Ref #929

**Comment by elhigu** [comment]
Hi, could you explain a bit more why type is necessary argument in wrapIdentifier? 

Also I suppose calling this function would be done as a hook as a first step, before  dialect specific wrapIndentifier function.

This would be nice feature to have,  since currently every knex based ORM has been struggling how to modify each queried column names.

**Comment by stevenvachon** [comment]
Or perhaps just a `transform` function. For setting, we could perform a `toSnakeCase` and for getting we could perform a `toCamelCase`. My code looks rather unpleasant having to do this manually.

**Comment by elhigu** [comment]
@stevenvachon yes something like that, I would like to have more specific name that tells to which tells to which part transformation applies. for example `transformIdentifier` and `transformReadColumnNames` (horrible like that), but something like that which tells to which part of knex the function applies :)

**Comment by stevenvachon** [comment]
perhaps a non-flat structure:
```js
transform: {
  identifier: identifier => {},
  readColumnName: name => {}
}
```

**Comment by stevenvachon** [comment]
@elhigu ?

**Comment by elhigu** [comment]
@stevenvachon I don't see anything to comment here that I didn't already say in my last comment. Those names are as good as my examples, cannot say more without reading some code.

**Comment by stevenvachon** [comment]
Ok, what are all the necessary names?

**Comment by elhigu** [comment]
I implemented + documented how to hook to the identifier wrapping part #2217  and https://github.com/knex/documentation/pull/51

**Comment by elhigu** [comment]
This will be released in knex 0.14

**Comment by sdwrage** [comment]
@elhigu Is there an estimated date for knex 0.14 to be released?

**Comment by elhigu** [comment]
before christmas, maybe this month, maybe next

**Comment by sdwrage** [comment]
@elhigu Awesome. Thanks for the update :)

**Comment by stevenvachon** [comment]
@elhigu anything happen?

**Comment by kanekotic** [comment]
can anyone share an example? seems not trivial. or i am not catching how can i make sure table names are not quoted.
thanks in advance for the help

**Comment by elhigu** [comment]
@kanekotic Those wrapper cannot distinguish if the identifier is table name or column name. So you cannot do that only for table names. However if you want to have all identifiers, without quotes that is completely possible. 

Just do something like this (https://knexjs.org/#Installation-wrap-identifier)

var knex = require('knex')({
  client: 'mysql',
  // overly simplified camelCase -> snake_case converter
  wrapIdentifier: (value, origImpl, queryContext) => value)
});

**Comment by ThePendulum** [comment]
This is probably what you'll want if you're trying to use knex with ManticoreSearch and get the error `unexpected BACKTICKED_SUBKEY, expecting SUBKEY`. That error turned up zero results on google, so I hope this comment may help someone find the solution more quickly.
