### ISSUE TITLE
Inconsistency when creating ENUM for MSSQL

### ISSUE THREAD

**Issue by neslinesli93** [tgriesser/knex#2085]
As you can see in [this line](https://github.com/tgriesser/knex/blob/master/src/dialects/mssql/schema/columncompiler.js#L61), the enums are casted to normal varchars in mssql dialect.
This should deserve at least a warning from knex itself, or an enum implementation if possible.
I've found [an elegant solution on SO](https://stackoverflow.com/a/1434338) and I've tried implementing inside knex, but I can't figure out how to put the `CHECK IN` at the very bottom of the sql string.

**Comment by elhigu** [comment]
This is how its done with postgresql https://github.com/tgriesser/knex/blob/master/src/dialects/postgres/schema/columncompiler.js#L34

**Comment by neslinesli93** [comment]
Yeah but it conflicts with possible .notNullable() calls, and possibly other chainable methods as well

**Comment by elhigu** [comment]
You might need to override https://github.com/tgriesser/knex/blob/master/src/schema/columncompiler.js#L39

in dialect which decides in which order different parts of query are constructed.

**Comment by beenotung** [comment]
This issue is not solved yet, let's re-open it.
