### ISSUE TITLE
unable to get out param in mysql stored procedure 

### ISSUE THREAD

**Issue by shanmughams** [tgriesser/knex#2086]
Hi ,
how to get out param values using  Knex in mysql ?

**Comment by elhigu** [comment]
Duplicate at least with these:
https://github.com/tgriesser/knex/issues/1949
https://github.com/tgriesser/knex/issues/1975
https://github.com/tgriesser/knex/issues/1624
https://github.com/tgriesser/knex/issues/1581
https://github.com/tgriesser/knex/issues/1592

**Comment by shanmughams** [comment]
Hi,
My mysql procedure has multiple out Params, I am looking for example to get
the value of those multiple out Params.

Thanks
Shanmugham

**Comment by elhigu** [comment]
This is same kind of issue how it is done with oracle https://github.com/tgriesser/knex/issues/1901

Basically you need to use knex.raw and figure out how output parameters are supported in node-mysql driver. There is no special handling for it in knex.
