### ISSUE TITLE
Add support for encrypt option in connection string

### ISSUE THREAD

**Issue by tmcdonnell87** [tgriesser/knex#2091]
Connections to Azure (mssql) require an `encrypt` option. 

For example: 
```
knex({
  client : 'mssql',
  connection: {
    server : 'myserver.database.windows.net',
    user : 'myuser',
    password : 'mypass',
    options: {
        port: 1433,
        database : 'mydatabase',
        encrypt: true
    }
  }
});
```

It would be great if the encryption could be all in a connection string, like: `mssql://myuser:mypass@myserver.database.windows.net:1433/scratch?encrypt=true`. 

Happy to create a PR with the consensus path forward, e.g., unpacking the querystring into a key/value options.

**Comment by elhigu** [comment]
Lets keep this discussion also in https://github.com/tgriesser/knex/issues/1528 (even that issue header is a bit misleading)
