### ISSUE TITLE
Question: Is it converting varchar to nvarchar?

### ISSUE THREAD

**Issue by HenriqueLimas** [tgriesser/knex#2092]
Working on MSSQL found that for some reason when a query is executed, it converts `varchar` to `nvarchar`. The column on the DB is `varchar` so we are losing some CPU converting `nvarchar` to `varchar`. Any reason why this happen? 
Not sure, but it seems is here that happen that conversion: https://github.com/tgriesser/knex/blob/master/src/dialects/mssql/schema/columncompiler.js#L52

**Comment by elhigu** [comment]
Code line linked there is not doing any conversion when queries are made. It just shows that when you are using knex schema building to create `.varchar()` column it actually creates `nvarchar` type of column. So no cycles are lost there. @Grimace1975 might know why it doesn't create `varchar` type.

Can you give some example code where you are experiencing varchar -> nvarchar conversion during normal queries?

Currently it seens that you can create `varchar` column only by using `.specificType` schema building method.

**Comment by HenriqueLimas** [comment]
We have that case using Bookshelf:

```
this.where({
  VARCHAR_STRING: 'My varchar string'
 }).fetch({
   columns: ['ID', 'NAME', 'VARCHAR_STRING']
 })
```

Under the hood bookshelf execute something like that `knex('TABLE_NAME').where.apply(knex('TABLE_NAME'), [{VARCHAR_STRING...}]);`

And in the database we can see that SQL executed:

```
(@p0 int, @p1 nvarchar(9))select top (@p0) [ID], [NAME], [VARCHAR_STRING] from [TABLE_NAME] where [VARCHAR_STRING] = @p1
```

**Comment by HenriqueLimas** [comment]
Pretty sure is something related to the driver, we can see it in the [data type value list](https://github.com/patriksimek/node-mssql/blob/a16180bd4253656753093de08cb50a627808b6b2/README.md#input-name-type-value):

**Comment by fortunes-technology** [comment]
@HenriqueLimas Can you explain how we can make VarChar as the default for string?

**Comment by stevesob** [comment]
Where or how can this be set in KNEX from MSSQL?
sql.map.register(String, sql.VarChar)

Can it be done in the initial config?

Since all my tables use VarChar and all parameters from Knex are NvarChar, all queries cause a table scan.

**Comment by lorefnon** [comment]
@stevesob You can use the type mapping API in node-mssql documented [here](https://github.com/tediousjs/node-mssql/blob/a16180bd4253656753093de08cb50a627808b6b2/README.md#input-name-type-value). 

Please consider opening new issues instead of commenting on issues that were closed years ago.

**Comment by WilliamStephens** [comment]
For anyone looking for how to do this:
db.client.driver.map.register(String, mssql.VarChar);

**Comment by kibertoad** [comment]
If someone is looking for a way to create a VARCHAR column in mssql, the best way is by using `specificType` - https://github.com/knex/knex/pull/4211/files
