### ISSUE TITLE
Postgresql: Timestamp without time zone not treated as UTC when the database is configured to be in UTC by default

### ISSUE THREAD

**Issue by ivosabev** [tgriesser/knex#2094]
The value in the database is `2017-06-01 10:00:00` and I would expect to get `2017-06-01T10:00:00.000Z`, but instead KNEX treats the 10:00 as an hour in my server's timezone (+3 GMT) and returns `2017-06-01T07:00:00.000Z`

**Comment by elhigu** [comment]
@ivosabev set your timestamp column type to be `timestamptz`

**Comment by elhigu** [comment]
And check this issue https://github.com/tgriesser/knex/issues/1461

**Comment by ivosabev** [comment]
Unfortunately it is not possible. I would expect when the column type is `timestamp without time zone` to get the date in the server default timezone, at least that's how Postgresql treats the `timestamp without time zone` column.

**Comment by elhigu** [comment]
@ivosabev and as told in #1461 this is actually issue of `node-postgres`. In #1461 in the end is linked solution for workaround where you can override how node-postges parses timestamp without timezone type.

**Comment by elhigu** [comment]
I'll report this to node-postgres and let's see if they are willing to change how it works.

**Comment by elhigu** [comment]
I actually investigated node-postgres issues about this and they have intentionally decided that timestamp without timezone is parsed to local date https://github.com/brianc/node-postgres/issues/1071. 

Looks like timestamp without timezone should actually be interpreted as a local time, not as a UTC time.

**Comment by pineapplemachine** [comment]
I ran into this issue also, and was able to get the behavior I expected by adding this code before creating a `knex` client object:

``` js
const types = require("pg").types;
const TIMESTAMP_OID = 1114;
types.setTypeParser(TIMESTAMP_OID, function(value) {
    // Example value string: "2018-10-04 12:30:21.199+00"
    return value && new Date(value);
});
```

**Comment by itinsley** [comment]
Thanks @pineapplemachine . This fixes my issue but feels a little unstable.

**Comment by elhigu** [comment]
Generally that is an invalid functionality, since it will make DB to treat local times as if they would be in timezone +00. For example when you cast timestamp with timezone to be in certain timezone in SQL query.
