### ISSUE TITLE
Null Characters erroring in Postgres

### ISSUE THREAD

**Issue by alikhan-io** [tgriesser/knex#2095]
Durign a routine security check we found an interesting bug where Postgres errors due to Null bytes E.g. %00 and as a result we get back an error detailing the query (we are in process now of swapping to a custom error message). 

Given this is a Postgres limitation it seems to make sense for the ORM to check for this type of character and either strip it or return an error before it even gets to the database.

https://www.postgresql.org/message-id/alpine.BSO.2.00.0906031639270.2432@leary.csoft.net

A scenario is selecting a record based on an email address e.g user@example.com%00 will return the following error message from Postgres due to the %00 being considerd a null byte.

 "select * from \"tableName\" where lower(\"email\") = $1 - invalid byte sequence for encoding \"UTF8\": 0x00"

**Comment by elhigu** [comment]
This definitely shouldn't be done in knex and that also sounds like a perfectly good error message from postgres side, that data which was sent is not good. 

It is application code's responsibility to cleanup user input if that is wanted behaviour, I would suggest using some validator library for that.  Many times 0x00 is perfectly fine value (when not used in utf8  string).
