### ISSUE TITLE
Global Knex.raw is deprecated

### ISSUE THREAD

**Issue by calebeaires** [tgriesser/knex#2096]
Somewhere on the app I am using this sintaxe ``sql.groupBy(knex.raw(g.formula));``. On console I get this message: ``Knex:warning - global Knex.raw is deprecated, use knex.raw (chain off an initialized knex object)``.

Does I made some mistake on the way I am doing that?

**Comment by rbadillap** [comment]
Take a look the `knex` object that you're using, don't load `knex` directly from node_modules, you should load the one already initialized.

This is what I mean:

```js
const knex = require('knex');

knex.raw() // Knex:warning - global Knex.raw is deprecated, use knex.raw (chain off an initialized knex object)
```

This is the proper way:

```js
const knexfile = require('{path-of-your}/knexfile.js');
const knex = require('knex')(knexfile);

knex.raw() // It works!
```
