### ISSUE TITLE
Getting nested data when using Joins

### ISSUE THREAD

**Issue by abhilash007** [tgriesser/knex#2108]
## client: 'mssql'
I have 2 Tables Students & Marks 
 Students Column Names : id,name
Marks Column Names : id, student_id(id of student),subject,mark

How to write Query . whereas i am expecting with (**total_count,LIMIT 3**)

[{
    id: 1,
    name: 'test_1',
### **_total_count:13,_**
    
**marks: [{
        subject: 'sub_1',
        mark: 10
    }, {
        subject: 'sub_2',
        mark: 9
    }, {
        subject: 'sub_3',
        mark: 8
    }]**

}, {
    id: 2,
    name: 'test_2',
 _**total_count:9,**_    

**marks: [{
        subject: 'sub_1',
        mark: 10
    }, {
        subject: 'sub_2',
        mark: 9,
        {
            subject: 'sub_3',
            mark: 8
        }
    }]**

}]

**Comment by elhigu** [comment]
There is pretty much no way to get nested data by using SQL. You should create nested representation of your rows by yourself from  flat data returned from the SQL database.
