### ISSUE TITLE
wrong 'unique' anchor in the website

### ISSUE THREAD

**Issue by PierBover** [tgriesser/knex#2114]
I've looked for the website repo but couldn't find any.

When clicking on the `unique` link from Schema and `unique` from Chainable on the left menu, they both go to the same anchor from Schema.

http://knexjs.org/#Schema-unique

**Comment by elhigu** [comment]
Yes, all chainable methods refers to the same specification. Chainable just means that you chain them in to column declaration.

What unique are you looking for? I haven't seen any other but schema builder methods for that...

**Comment by PierBover** [comment]
Well there's this unique from schema:
<img src="https://user-images.githubusercontent.com/226483/27003257-c98de6c8-4db8-11e7-87b7-faabaa7d75f7.png" width="350">

And this one from chainable:
<img src="https://user-images.githubusercontent.com/226483/27003259-d5bcaae2-4db8-11e7-8f3b-431968c2cad2.png" width="270">

These are not the same, no?

**Comment by elhigu** [comment]
I believe it is the same, but chainable doesn't require column name parameter and doesn't support multiple keys. Better documentation wouldn't hurt. Index / all other chainable methods that has also non chainable implementation seems to have the same problem.

**Comment by PierBover** [comment]
So... is there a repo we can PR to fix this?

**Comment by elhigu** [comment]
It is mentioned in https://github.com/tgriesser/knex/blob/master/CONTRIBUTING.md

https://github.com/knex/documentation
