### ISSUE TITLE
Unhandled rejection TypeError: client.driver.Client is not a constructor

### ISSUE THREAD

**Issue by Falieson** [tgriesser/knex#2121]
`Unhandled rejection TypeError: client.driver.Client is not a constructor` triggered in this knex function. 
```
  // Get a raw connection, called by the `pool` whenever a new
  // connection needs to be added to the pool.
acquireRawConnection: function acquireRawConnection() {
    var client = this;
    return new _bluebird2.default(function (resolver, rejecter) {
      var connection = new client.driver.Client(client.connectionSettings);
      connection.connect(function (err, connection) {
        if (err) {
          return rejecter(err);
        }
```

is this an issue w/ the latest version of knex?

gist: https://gist.github.com/Falieson/83593ae9b9a658441f8ab4589264ffc4

**Comment by elhigu** [comment]
Never seen this before. How can I reproduce the error?

**Comment by Falieson** [comment]
@elhigu 
clone `git@github.com:Falieson/ultimate-react-2017.git`
checkout `counters`
`npm install`
`npm run db:setupComplete` (/docs for setting up postgres)
`npm run start`

**Comment by elhigu** [comment]
Try to create reduced tests case, preferably one file for reproducing. Now it looks like some problem with build system or how knex has been used. I don't have time right now to debug whole app / build process.

**Comment by wubzz** [comment]
Given the description of the linked issue from 21 June 2017, I believe this can be closed.
>I started this issue a week ago thinking it was an issue with Knex but I've experimented doing the same code with react-router-4 and its working perfectly.
