### ISSUE TITLE
Using withSchema on DML statements such as del, insert, and update?

### ISSUE THREAD

**Issue by deinspanjer** [tgriesser/knex#2122]
I started using knex.withSchema(x).select().from(y), but I couldn't figure out a way to use it in something like an insert statement where the table name is passed via knex(tablename).
For those statements, I'm continuing to use string interpolation.  Just wondering if there is a better way.

**Comment by elhigu** [comment]
Is this what you are looking for https://runkit.com/embed/ai907osl2dzp ? Maybe I didn't get the question right?

**Comment by deinspanjer** [comment]
I didn't see the specific case I was looking for, but what I did see in there was the syntax knex.table("bar").insert()...

If this example below works, then it would be fine:
knex.withSchema("foo").table("bar").insert(stuff)

but I *think* I tried that and it didn't work.  I might be misremembering though.

**Comment by elhigu** [comment]
Seems to work https://runkit.com/mikaelle/59514b213dcf2e0012b72093
