### ISSUE TITLE
Suppressing Knex warnings

### ISSUE THREAD

**Issue by loganhuskins** [tgriesser/knex#2124]
Is there currently a way to suppress Knex warnings? We have some tests that intentionally do some wonky stuff to our migrations and it causes Knex warnings to spew out during the tests and I'm trying to avoid that if I can.

If not, is it something that could possibly be pull requested on and implemented or would it require major architectural changes?

**Comment by elhigu** [comment]
There is no way to supress warnings, it shouldn't be hard to implement. IIRC there has been already discussion about overriding loggers, but I don't want to search for them now on mobile. Could you please add link here to some previous issue discussing this?

**Comment by loganhuskins** [comment]
[This](https://github.com/tgriesser/knex/issues/1483) seems to be the best thing I have found on it.

**Comment by wubzz** [comment]
[this](https://github.com/tgriesser/knex/blob/master/src/helpers.js#L25) file is the only source. Most of these should probably be under a `DEBUG=knex:x` flag, while the `warn` in specific should probably always be displayed unless a new config option to suppress warnings is set to true.

Does that sound ok?

**Comment by elhigu** [comment]
I would prefer allowing to override logging functions in the configuration, so that one can decide to do whatever they like with messages and it would close multiple issues at once.

btw. having separate { debug: true } flag and completely differently working DEBUG  env variable is pretty confusing :)

**Comment by wubzz** [comment]
Closing as overriding log functions is now possible: https://knexjs.org/#Installation-log
