### ISSUE TITLE
knex.insert returns auto incremented id though there is no id field

### ISSUE THREAD

**Issue by thetutlage** [tgriesser/knex#2127]
I have a table which does not have `id` column in it, but whenever I make an insert statement, it returns me some auto-incremented id. I am not sure where does that comes from.

## Connection

```js
const path = require('path')
const knex = require('knex')({
  client: 'sqlite',
  connection: {
    filename: path.join(__dirname, './dev.sqlite3')
  },
  useNullAsDefault: true
})
```

## Create Table and Insert

```js
knex
  .schema
  .createTableIfNotExists('users', function (table) {
    table.integer('uuid')
    table.string('username')
  })
  .then(() => {
    return knex
      .table('users')
      .insert({ uuid: 1100, username: 'virk' })
  })
  .then(console.log)
  .catch(console.error)
```

Now `console.log` logs some auto incremented id

**Comment by elhigu** [comment]
Looks like there are no extra queries made, like getting lastrowid, so it must be this line https://github.com/tgriesser/knex/blob/master/src/dialects/sqlite3/index.js#L109

Which is some id data got from sqlite3 driver.
