### ISSUE TITLE
Unhandled rejection TypeError: _this.driver.createConnection is not a function

### ISSUE THREAD

**Issue by taiyoOzora** [tgriesser/knex#2129]
I am using the latest version of webpack, knex and mysql and so on

My database.jsx

```
var knex = require('knex')({
  client: 'mysql',
  // connection: process.env.JAWSDB_URL
  connection: {
    host : 'localhost',
    user : 'root',
    password : 'root',
    database : 'qdz4necug0zghtc5'
  }
})

export var addUserByEmail = (userInfo) =>{

  knex.insert(userInfo).into('user').then(()=>{
    console.log('yay');
    return 1;
  })
}
```

my sender:
```
var objInsert = {
          firstName: fName,
          lastName: lName,
          username: username,
          email: email,
          password: password
        };

        dispatch(startAddUserByEmail(objInsert));
      },
```

link to my git [https://github.com/taiyoOzora/Recipea](url)

the error message I get

> bluebird.js?e366:1542 Unhandled rejection TypeError: _this.driver.createConnection is not a function
>     at Runner.run (eval at <anonymous> (http://localhost:3000/bundle.js:1:9447357), <anonymous>:51:42)
>     at Builder.Target.then (eval at <anonymous> (http://localhost:3000/bundle.js:1:1949907), <anonymous>:35:43)
>     at Object.addUserByEmail (eval at <anonymous> (http://localhost:3000/bundle.js:1:5174529), <anonymous>:20:38)
>     at eval (eval at <anonymous> (http://localhost:3000/bundle.js:1:5171432), <anonymous>:30:8)
>     at Object.eval [as dispatch] (eval at <anonymous> (http://localhost:3000/bundle.js:1:12127374), <anonymous>:11:18)
>     at dispatch (<anonymous>:2:1620)
>     at HTMLFormElement.dispatch (eval at module.exports (eval at <anonymous> (http://localhost:3000/bundle.js:1:1582041)), <anonymous>:3:10316)
>     at HTMLFormElement.q.handle (eval at module.exports (eval at <anonymous> (http://localhost:3000/bundle.js:1:1582041)), <anonymous>:3:8343)

I have tried everything in my knowledge to fix it but It don't seem to work.

**Comment by absolux** [comment]
@taiyoOzora knex works only on server side not in frontend applications unless you are server rendering react applications

**Comment by taiyoOzora** [comment]
@absolux ok thanks, I think i got what you mean. I just can't seem to get any good tutorials to use it tgt. But all in all I just have to include knex in the server.js instead of my app right?

**Comment by elhigu** [comment]
This is already documented in basic examples how to use knex. Stackoverflow is better forum to ask for non-bug related user support.
