### ISSUE TITLE
problem with insert() and increments()

### ISSUE THREAD

**Issue by PierBover** [tgriesser/knex#2130]
So I have a very simple table with:
```
knex.schema.createTable('MyTable', function(table) {
	table.increments('id').primary();
});
```
And then I seed some data in it:
```
knex('MyTable').insert([
	{
		id: 1
	},
	{
		id: 2
	},
	{
		id: 3
	}
]);
```
I have to put the IDs by hand because then I need to seed other data and reference it.

But when I do:
```
knex('MyTable').insert({});
```
I get this error:
```
error: duplicate key value violates unique constraint "MyTable_pkey"
```
Because apparently Knex is trying to insert the object in the id with 1. So I do this 2 more times and finally Knex inserts the new object with the id 4. Which is now valid because there is no entry with id 4.

It seems the problem is that Knex or Postgres "doesn't know" that some items have already been inserted with the proper ID.

Is this a bug?
If not, is there a way around this problem other than inserting without ids?

I have dozens of seedings and without knowing the id beforehand for the relationships this is going to be a nightmare.

**Comment by PierBover** [comment]
So yeah, from what I've been reading I either remove the ids and then simply use Postico to know the actual id of something, or I create functions with where clauses that create the ids for me [as described here](https://medium.com/@jaeger.rob/seed-knex-postgresql-database-with-json-data-3677c6e7c9bc).

**Comment by ricardograca** [comment]
You'll have to do something like:

```js
knex.raw('SELECT setval(\'your_table_id_seq\', (SELECT MAX(id) from "your_table"));')
```

After seeding the data with the preset ids. This is just how PostgreSQL works.

**Comment by rapodaca** [comment]
The suggestion from @ricardograca worked for me. However, the quotes need to be (escaped) single as in his example. My integration tests were setting the auto-generated id, so I put the `setval` command into a seed file:

```javascript
const seed = async (sql) => {
  await sql.insert([
    { id: 1, name: 'Hello' },
    { id: 2, name: 'Goodbye' }
  ]).into('foos');

  await sql.raw('select setval(\'foos_id_seq\', max(id)) from foos');
};

exports.seed = seed;
```

Double quotes around `foos_table_id_seq` will produce an error:

> error: column "foos_id_seq" does not exist
