### ISSUE TITLE
'subquery must return only one column' error

### ISSUE THREAD

**Issue by pvinis** [tgriesser/knex#2133]
I have a simple `users` table, and a `friends` table with foreign keys `user_id_1` and `user_id_2`.

In a seed, I add some users. In another seed I want to add some friend relationships by doing that.

```
knex('friends').insert({
  user_id_1: knex('users').select('id').where({username: 'bla'}),
  user_id_2: knex('users').select('id').where({username: 'blu'}),
})
```

This gives me back an error that `subquery must return only one column`. I select just the `id` column, so what is the problem here?

**Comment by absolux** [comment]
@pvinis may be you should limit the result of the subqueries like
```js
knex('friends').insert({
  user_id_1: knex('users').select('id').where({username: 'bla'}).limit(1),
  user_id_2: knex('users').select('id').where({username: 'blu'}).limit(1),
})
```

**Comment by coockoo** [comment]
@pvinis 
Or maybe you want to use shorthand `.first()`.
```javascript
knex('friends').insert({
  user_id_1: knex('users').first('id').where({username: 'bla'}),
  user_id_2: knex('users').first('id').where({username: 'blu'}),
})
```
Which gives the same result.

Feel free to ask such questions in stackoverflow or any other community q&a place. This is kinda issue tracker and not a helpdesk.

**Comment by pvinis** [comment]
what about if the `username` is unique. isnt that making the `first` or `limit`, kinda redundant?

**Comment by coockoo** [comment]
@pvinis Can you provide schema for table users? And which db engine do you use?
`postgres` forks fine for me on unique columns (it is created with unique constraint)
`"test_table_test_key" UNIQUE CONSTRAINT, btree (test)`

**Comment by pvinis** [comment]
i dont have the scheme here but i can paste it later tonight.
i use postgres and basically its users with `id `increases`, `username` `string` `unique`, `email` `string` `unique`, `name` `string`. the friends table is `id` `increases`, `user_id_1` `string` `references('users.id')`, and `user_id_2` `string` `references('users.id')`.

**Comment by elhigu** [comment]
Looks like using .first might generate invalid query:

```js
> knex('friends').insert({
...   user_id_1: knex('users').first('id').where({username: 'bla'}),
...   user_id_2: knex('users').first('id').where({username: 'blu'}),
... }).toSQL()
{ method: 'insert',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [ 'bla', 1, 'blu', 1 ],
  __knexQueryUid: '0bf1f849-47a2-4ef2-86bc-45963557c482',
  sql: 'insert into "friends" ("user_id_1", "user_id_2") values (select "id" from "users" where "username" = ? limit ?, select "id" from "users" where "username" = ? limit ?)',
  returning: undefined }
```

but query generated by using `.limit(1)` seems to generate correct result:

```js
> knex('friends').insert({
...   user_id_1: knex('users').select('id').where({username: 'bla'}).limit(1),
...   user_id_2: knex('users').select('id').where({username: 'blu'}).limit(1),
... }).toSQL()
{ method: 'insert',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [ 'bla', 1, 'blu', 1 ],
  __knexQueryUid: '5dbdbfbf-93c1-4fa9-b7fd-95dc7689f140',
  sql: 'insert into "friends" ("user_id_1", "user_id_2") values ((select "id" from "users" where "username" = ? limit ?), (select "id" from "users" where "username" = ? limit ?))',
  returning: undefined }
```

About the unique constraint, you probably have it made wrong... since that error really seems to mean that the query returns more that one results

```sql
knex_test=# insert into accounts (id) VALUES ((select id from accounts limit 2));
ERROR:  more than one row returned by a subquery used as an expression

knex_test=# insert into accounts (id) VALUES ((select id from accounts limit 1));
ERROR:  duplicate key value violates unique constraint "test_table_one_pkey"
DETAIL:  Key (id)=(3) already exists.

knex_test=# insert into accounts (id) VALUES ((select id from accounts where id = 3));
ERROR:  duplicate key value violates unique constraint "test_table_one_pkey"
DETAIL:  Key (id)=(3) already exists.
```

Closing this for now, but please keep on discussing here if you like.

**Comment by coockoo** [comment]
Looks like using `.first` generates the same output
```
const knex = require('knex')({ client: 'pg' })
```

```javascript
knex('friends').insert({
    user_id_1: knex('users').first('id').where({username: 'bla'}),
    user_id_2: knex('users').first('id').where({username: 'blu'})
}).toSQL();
```
```
{ method: 'insert',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [ 'bla', 1, 'blu', 1 ],
  __knexQueryUid: 'd4151d94-9067-4a07-b0a9-0fabcb0420ee',
  sql: 'insert into "friends" ("user_id_1", "user_id_2") values ((select "id" from "users" where "username" = ? limit ?), (select "id" from "users" where "username" = ? limit ?))',
  returning: undefined }
```

and

```javascript
knex('friends').insert({
    user_id_1: knex('users').first('id').where({username: 'bla'}),
    user_id_2: knex('users').first('id').where({username: 'blu'})
}).toSQL().sql ===  knex('friends').insert({
    user_id_1: knex('users').select('id').where({username: 'bla'}).limit(1),
    user_id_2: knex('users').select('id').where({username: 'blu'}).limit(1)
}).toSQL().sql; // true
```

```
    "knex": "^0.13.0",
```

I actually can't tell right now why this happens.

@pvinis 
And on topic – I'd recommend you to check your table definition to make sure you have this unique constraint. Or add a `.limit(1)` or `.first()` function to be sure you are not getting "more than one row" error.

**Comment by elhigu** [comment]
@coockoo looks like you are right https://runkit.com/embed/htzh2gkncj8n I was running 0.12.6 which still generated invalid output.

**Comment by pvinis** [comment]
so this is still happening.. everyone here is writing about how to avoid multiple rows, but like i said, the error is saying that the subquery must return only one column. i do `select('id')`, tried `first('id')` too, but still get the error.

```
// user migration file

const name = 'users'

exports.up = (knex, Promise) => {
  return Promise.all([
    knex.schema.createTable(name, (table) => {
      table.increments('id').unsigned().unique().primary()
      table.string('username').unique().notNullable()
      table.string('email').unique().notNullable()
      table.string('name')
			table.timestamp('created_at').defaultTo(knex.fn.now())
    }),
  ])
}

exports.down = (knex, Promise) => {
  return Promise.all([
    knex.schema.dropTable(name),
  ])
}
```

```
// friends migration file

const name = 'friends'

exports.up = (knex, Promise) => {
  return Promise.all([
    knex.schema.createTable(name, (table) => {
      table.increments('id').unsigned().unique().primary()
      table.integer('user_id_1').unsigned().notNullable()
				.references('users.id')
      table.integer('user_id_2').unsigned().notNullable()
				.references('users.id')
    }),
  ])
}

exports.down = (knex, Promise) => {
  return Promise.all([
    knex.schema.dropTable(name),
  ])
}

```

```
// user seed file

const table = 'users'

exports.seed = (knex, Promise) => {
  // Deletes ALL existing entries
  return knex(table).del()
    .then(() => {
      // Inserts seed entries
      return knex(table).insert([
        {
          username: 'DApr1nce',
          email: 'prince@katamari.com',
          name: 'Prince of all Cosmos',
        }, {
          username: 'pinky',
          email: 'ichigo@cousin.com',
          name: 'Ichigo',
        }, {
          username: 'okedO',
          email: 'o@de.ko',
          name: 'Odeko',
        }, {
          username: '111',
          email: 'ace@one.com',
          name: 'Ace',
        }, {
          username: 'pesos',
          email: 'peso@bill.com',
          name: 'Peso',
        },
      ])
    })
}
```

```
// friends seed file

const table = 'friends'

exports.seed = (knex, Promise) => {
  // Deletes ALL existing entries
  return knex(table).del()
    .then(() => {
      // Inserts seed entries
      const users = knex('users')
    //   return users.select('id').where({username: 'DApr1nce'}).first()
        // .then((a) => console.log(a.id))
      return knex(table).insert([
        {
          user_id_1: users.first('id').where({ username: 'pinky' }).limit(1),
          user_id_2: users.first('id').where({ username: 'DApr1nce' }).limit(1),
        },
      ])
    })
}
```

**Comment by pvinis** [comment]
answering to my question, i found the problem.
i was using `const users = knex('users')` and then `users.first('id').where(..)` for the two `id`s. this was causing to have only one query to the users, with both `select`s and both `where`s on it. so the resulting query was `select "id", "id" from "users" where .. and ..`.

to correct this, i now do `const users = () => knex('users')` and `users().select('id').where(..)`.

finally, what kind of logic is this? why is `select('id').select('id')` resulting in `select "id, "id"`? is that normal? is it a bug?

**Comment by wubzz** [comment]
@pvinis I wouldn't consider it a bug. `.select` is chainable just like `.where`, should multiple `.where` statements also clear the last one?

Recently the `.clearSelect` and `.clearWhere` functions were added for this purpose.

Imo, it was faulty code to begin with as it uses the same query builder object for two different queries. Not only did the selected columns become wrong, but your query would also generate `where username = 'pinky' and username = 'DApr1nce'`.

Always use seperate querybuilders (or `.clone`) unless the query is to be the same for multiple queries.

**Comment by pvinis** [comment]
it was faulty code indeed, and thats why i answered it, for future reference :D 

good to know about `clearSelect`. well, i dont know if it should clear by default or no. i just thought i will ask, to know, if people know the reason, or to start a conversation, if people dont know the reason. i guess it makes send to have it explicitly like it is now.

thank you for your answer :)
