### ISSUE TITLE
Named bindings ignored in raw query if there are no keys in bindings object

### ISSUE THREAD

**Issue by coockoo** [tgriesser/knex#2134]
Sample code to reproduce
```javascript
	const builder = knex
		.select('t.id')
		.from('test_table as t')
		.where(knex.raw('t.id = :raw', {})) // This doesn't work
		//.where(knex.raw('c.id = :raw', { raw: undefined })) This works
	console.log(builder.toString()) // outputs:  select "t"."id" from "test_table" as "t" where t.id = :raw
	builder.then(function (res) {
		console.log('res', res) // Never executed
	})
	// Dependencies:
	//     "knex": "^0.13.0",
	//     "pg": "^6.3.1",
```
I've found source code responsible for that
https://github.com/tgriesser/knex/blob/master/src/raw.js#L165

Would it be better for consistency to throw "Undefined bindings" exception as in array bindings in this case?

**Comment by elhigu** [comment]
This is a feature to make named binding syntax to be less intrusive... beforehands there were problems e.g. when people tried to use `::text` casting operations etc. in `knex.raw`. 

It was also documented I think, but later on knex actually started to throw an error of the case that is show in example code. Docs say `Named bindings are processed so long as the value is anything other than undefined.` it should say something like `Named bindings are replaced only if there is a key with the same name found from bindings object.`

btw. from the code above I'm pretty sure that 

```
//.where(knex.raw('c.id = :raw', { raw: undefined })) This works
```

also throws an error when query is executed.
