### ISSUE TITLE
[Knex 12.6] Using clause generates syntax error

### ISSUE THREAD

**Issue by Roam-Cooper** [tgriesser/knex#2136]
When using knex 12.6
When using Postgres, calling
```js
.using('col');
```
Will produce a using clause in SQL without the brackets like
```sql
using "col"
```
It should be
```sql
using ("col")
```
Calling
```js
.using(['col', 'col2']);
```
Will produce SQL
```sql
using "col,col2"
```
It should be
```sql
using ("col", "col2")
```
Additionally, the using method is completely undocumented on knexjs.org as far as I can see.

**Comment by elhigu** [comment]
Implementation, tests + documentation would be welcome.
