### ISSUE TITLE
how to run SQL but not need builder

### ISSUE THREAD

**Issue by anhnt6626** [tgriesser/knex#2137]
I have a sql "Select * from user"
How to run this sql and return result same as knex.select().from('user')

Thanks

**Comment by elhigu** [comment]
Duplicate issue (I don't have time to dig up the last issue when this was asked). Check the result that `knex.raw()` is returning with `console.dir(res, { depth: null });`.

If I remember correctly that depends on which DB dialect you are using so you might need to have different implementation how to fetch actual rows for each dialect.

Anyways IIRC the attribute  was `res.rows` where you can find resulted rows with postgresql.
