### ISSUE TITLE
Leftjoin

### ISSUE THREAD

**Issue by GlauberF** [tgriesser/knex#2138]
Hello, I can use an alias (as) in the left join.

**Example, I have the following call:**
```js
knex.select('*')
  .from('tb_Cliente')
  .where('cli_ativo', 1)
  .andWhere('fk_saas_id', resSaasId)
  .leftJoin('tb_Endereco_Cliente', 'tb_Cliente.cli_id', 'tb_Endereco_Cliente.fk_cli_id')
  .leftJoin('tb_Email_Cliente', 'tb_Cliente.cli_id', 'tb_Email_Cliente.fk_cli_id')
  .leftJoin('tb_Social_Network_Cliente', 'tb_Cliente.cli_id', 'tb_Social_Network_Cliente.fk_cli_id')
  .leftJoin('tb_Tag_Cliente', 'tb_Cliente.cli_id', 'tb_Tag_Cliente.fk_cli_id')
  .leftJoin('tb_Atendimento_Cliente', 'tb_Cliente.cli_id', 'tb_Atendimento_Cliente.fk_cli_id')
  .then((resp) => {});
```

I need the result of this, be separated by table (tb_Endereco_Cliente, tb_Email_Cliente, tb_Social_Network_Cliente, tb_Tag_Cliente, tb_Atendimento_Cliente), example:

```js
{
    "pessoa": [{tb_Cliente}],
    "endereco": [{tb_Endereco_Cliente}],
    "lista_email": [{tb_Email_Cliente}],
    "tag": [{tb_Tag_Cliente}],
     "redes_sociais":  [{tb_Social_Network_Cliente}],
     "atendimentos" : [{tb_Atendimento_Cliente}]
```

Today you get all the mixed values

```js
{
    "pessoa": [
        {
            tb_Cliente,
            tb_Endereco_Cliente,
            tb_Email_Cliente,
            tb_Tag_Cliente,
            tb_Social_Network_Cliente,
            tb_Atendimento_Cliente
        }
    ]
}
```

**Comment by elhigu** [comment]
Knex will not return structured data for you. You need to use some ORM for the thing you are trying to do (e.g. bookshelf or objection.js are both based on knex).

You can use `.join('table as foo')`but it still will not return you structured data. Knex returns  pretty much straight results that DB gives and DB returns just flat array of columns and rows when joining tables together.

Also most of the DB drivers (at least with default settings) doesn't like that the case where you join the same column name from multiple tables, so e.g. if each table has an `id` column, result row will still have just 1 column with name `id`. This is happening already before knex even sees the result got from DB.
