### ISSUE TITLE
Unhandled rejection error on query

### ISSUE THREAD

**Issue by vpfaulkner** [tgriesser/knex#2139]
Hi,

We are having an issue with the following query:
```
DefectCount
    .query()
    .whereIn('caseId', caseIds)
    .orderBy('created_at')
    .select()
```

where `DefectCount` is a Bookshelf model. The error is:

```
Unhandled rejection error: select * from "defect_counts" where "caseId" in ($1, $2, $3
...
$81857, $81858) order by "created_at" asc - bind message supplies 16322 parameters, but prepared statement "" requires 81858

Jun 28 06:31:52 qcir-staging app/scheduler.6343:      at null.Connection.parseE (/app/node_modules/pg/lib/connection.js:567:11) 
Jun 28 06:31:52 qcir-staging app/scheduler.6343:      at null.Connection.parseMessage (/app/node_modules/pg/lib/connection.js:391:17) 
Jun 28 06:31:52 qcir-staging app/scheduler.6343:      at Socket.<anonymous> (/app/node_modules/pg/lib/connection.js:129:22) 
Jun 28 06:31:52 qcir-staging app/scheduler.6343:      at emitOne (events.js:90:13) 
Jun 28 06:31:52 qcir-staging app/scheduler.6343:      at Socket.emit (events.js:182:7) 
Jun 28 06:31:52 qcir-staging app/scheduler.6343:      at readableAddChunk (_stream_readable.js:147:16) 
Jun 28 06:31:52 qcir-staging app/scheduler.6343:      at Socket.Readable.push (_stream_readable.js:111:10) 
Jun 28 06:31:52 qcir-staging app/scheduler.6343:      at TCP.onread (net.js:525:20) 
```

As you can see the `caseIds` array is very long (~81k) which might be part of the issue. We use this same query in a different code path that includes a much smaller collection of `caseIds` and this error is not raised.

Any ideas?

Seems potentially similar to: https://github.com/tgriesser/knex/issues/1848

**Comment by elhigu** [comment]
May be because of databases maximum statement length. You should never pass tens of thousands parameters to your query. `.whereIn('id', subqueryReturningIds)` should work in most of the cases for avoiding that. Otherwise you need to split your request some other way.

**Comment by vpfaulkner** [comment]
Thanks, that was the problem and we were able to use your suggestion to fix the problem.
