### ISSUE TITLE
How do I specify table(s) with .delete() ?

### ISSUE THREAD

**Issue by stringbeans** [tgriesser/knex#2140]
Using: MySQL/MariaDB

I am trying to eventually build a query that looks like so:

`DELETE student FROM student JOIN student_tag ON .... WHERE ...`

However, looking at the documentation, it seems like I can only build a query which eventually results in:

`DELETE FROM student JOIN student_tag ON ... WHERE ...`

(notice the missing table specification after the DELETE keyword)

I've recently run into performance differences doing it one way or the other when there is a subquery in the WHERE clause of the DELETE. After doing an explain, it looks like in the 2nd way it doesnt uses indexes, whereas in the first way it does. 

Is it possible to build a query that results in a DELETE statement looking like the first way above? 

Thanks in advance!

**Comment by stringbeans** [comment]
I think ideally the .del() / .delete() would take a string (or array of strings) specifying the tables to delete from :)

**Comment by elhigu** [comment]
IIRC currently joins cannot be used in deletes nor updates. Would be great feature to implement and I'm sure there is already feature request for that.
