### ISSUE TITLE
[general] Getting ready for production - any advice?

### ISSUE THREAD

**Issue by ScaryWolfMan** [tgriesser/knex#2147]
I've been working on porting an existing REST application over to node and I'm using knex.  If anyone here is using knex in a production environment, what are some tips you can share for someone who is new to the process?

I will be using an existing database (AWS RDS - postgres) and deploying the dockerized application I've built on EB.  Is there any knex specific configuration I should do besides obviously pointing to production database? 

Thanks

**Comment by elhigu** [comment]
This question should be posted to stackoverflow. In AWS store connection details to env variables and then read them like shown in examples shown in docuementation http://knexjs.org/#Installation-client
