### ISSUE TITLE
Raw queries do not handle identifier bindings correctly

### ISSUE THREAD

**Issue by timruffles** [tgriesser/knex#2152]
If we attempt to use knex.raw to write the following type of query:

```sql
> select 'val' as "name?"
 name?
---------
 val
(1 row)
```

by writing the following...

```javascript
knex.raw('select ? as ??', ['val', 'name?'])
    .catch(e => console.error(e))
```

we get this error:

```
{ error: 'select * from (select $1 as "name$2") as t - 
     could not determine data type of parameter $1' }
```

[edited]

**Comment by elhigu** [comment]
Actually using `?` -mark in question in identifiers breaks even without nesting. You could try to replace `?` in identifier with `\?` as a workaround. 

Anyways, I like the idea of just collecting identifiers as they were given and interpolate them only in the very end of the query compilation phase. But I would actually also like it better if toSQL result query would already be in format accepted by underlying driver...

Both would be big changes though and I would like to have opinions of other collaborators before anyone would start working on these.

**Comment by timruffles** [comment]
You're quite right re ? being an issue even without nesting. Thanks!

**Comment by elhigu** [comment]
I think we can say that one should not use identifiers containing `?` or `.` characters when using knex (pretty marginal case).

**Comment by rpuls** [comment]
I'm trying to use a `REGEXP_REPLACE('column', '({{(@root\.)?app\.url}})(?!#)', '\1replace_thing')` I need the question marks in the regex, are there any solution on how to escape these ?

**Comment by elhigu** [comment]
Pass regexp as value binding and not as a static string embedded in sql.

**Comment by novito** [comment]
@elhigu escaping `?` works, but escaping `.` still gives the issue. What's your suggested workaround?

**Comment by elhigu** [comment]
Dont use periods or dont use ?? binding in that case. ?? bindings treats periods as special character and that is not going to change.

**Comment by novito** [comment]
thanks elhigu! I will find a workaround to decorate those columns after knex has been used!

**Comment by novito** [comment]
@elhigu what's the easiest way for me to find out which characters I should avoid when using `??`?

**Comment by elhigu** [comment]
safest to avoid everything that is not `a-zA-Z0-9_-.` that binding should be used for `'table.column'` type of references.
