### ISSUE TITLE
Using shared connection instead pool between requests

### ISSUE THREAD

**Issue by calebeaires** [tgriesser/knex#2153]
I have created an issue on mysql2 github page about an error that appear after many concurrently requests. The app uses knex to connection on MySQL.

The app logic needs an shared connection_id() (mysql session) between requests. It is because the app needs to create temporary tables to be used on a second request, so to make this possible, I use an singleton pattern to globally save the connection.

If I remove **pool** options from the knex connection, the lib will create many connection_id(). I need the same connection, so I use pool like this:

```node
            pool: {
                min: 0, max: 1
            }
```

The error is: `Error: Too many connections`. So, how to share the same connection (not an pooled one) between request using knexjs as the main lib. 

node-mysql2 issue: https://github.com/sidorares/node-mysql2/issues/606

**Comment by calebeaires** [comment]
I found this on documentation

**connection** (http://knexjs.org/#Builder-connection)
(incomplete) - This feature was incorrectly documented as functional. 
If implemented, the method would set the db connection to use for the **query without using the connection pool**.

How to implement it?

**Comment by elhigu** [comment]
Here is the issue talking about the connection method https://github.com/tgriesser/knex/issues/1878

Currently you might be able to reuse the same connection if you create dedicated knex instance with min: 1, max : 1 and set all timers in that way that connection will not be released when idling (not sure how pool implementation does it currently).

About the method setting connection it would need to be defined first how people would like it to work and after that it could be documented, implemented and tested.

**Comment by elhigu** [comment]
Here is also some hacky information how to set connection for query builder manually https://github.com/tgriesser/knex/issues/2090

**Comment by elhigu** [comment]
And this is probably also somewhat related https://github.com/tgriesser/knex/issues/1681

**Comment by calebeaires** [comment]
Here is the code I am using to share connection to the same session. Everything is ok except that when I call knex.destroy(), the session connection does not end, but it take 30 seconds to do so.

```node
import { Me } from './Me';
import * as knex from 'knex';

export class BucketDb {

    private static _connection: any = {}

    public static connect(databaseData) {

        if (!this._connection[Me.profile().sessionId]) {
            this._connection[Me.profile().sessionId] = knex({
                client: 'mysql2',
                connection: databaseData,
                pool: { min: 1, max: 1 }
            });
        }

        return this._connection[Me.profile().sessionId];

    }

    public static destroyBucketInstance() {
        const self = this;
        this._connection[Me.profile().sessionId].destroy();
    }

}

```

I have tried to destroy connection manually too, but this workaround does not destroy it.
```node
this._connection[Me.profile().sessionId].raw('kill (select connection_id())');
```

When listing process with the mysql command `show processlist;` after calling destroy method to close pool connection (like the 5570 pool id above), it where not closed.

<img width="611" alt="screen shot 2017-07-18 at 14 20 31" src="https://user-images.githubusercontent.com/794195/28330782-2c0da7aa-6bc5-11e7-80d6-fb1d567bb744.png">

- Does `knex.destroy()` immediately close  the connection?
- Is there an way to call directly `connection.end()` to manually close those opened pool?

**Comment by nareshsr** [comment]
You can create and destroy connection for per request

```
const config = {
    client: 'mysql2',
    connection: {
      host: process.env.DB_HOST,
      user: process.env.DB_USER,
      password: process.env.DB_PASS,
      database: process.env.DB_NAME
    },
    pool: {
      min: Number(process.env.DB_POOL_MIN),
      max: Number(process.env.DB_POOL_MAX)
    },
    acquireConnectionTimeout: Number(process.env.DB_TIMEOUT)
  }
  var Knex = require('knex')

  this.functionname = () => {
    var output = {}
    return new Promise(function (resolve) {
      var knex = new Knex(config)
      knex(tablename)
        .select()
        .then((result) => {
          if (result.length > 0) {
            output.error = false
            output.result = result
          } else {
            output.error = true
          }
          resolve(output)
        })
        .catch((err) => {
          err.error = true
          resolve(err)
        })
        .finally(() => {
          knex.destroy()
        })
    })
  }
```

**Comment by wubzz** [comment]
@nareshsr That's gonna blow up your server resources on heavy load.

**Comment by nareshsr** [comment]
> @nareshsr That's gonna blow up your server resources on heavy load.

Every connection gets created and closed after query execution.

**Comment by wubzz** [comment]
@nareshsr That doesn't matter. What eats a lot of resources is creating the connection in the first place. Multiply that resource usage with amount of requests per seconds and your server will be choking in no time.

**Comment by elhigu** [comment]
#1878 actually made it possible to pass to query builder, which connection to use to execute the query
