### ISSUE TITLE
cli - `migrate:make` cannot be used without a knexfile.js

### ISSUE THREAD

**Issue by KieronWiltshire** [tgriesser/knex#2158]
the command:
`knex migrate:make <name>` cannot be used without a knexfile.js. This is literally pointless. If I want to create a migration in the directory I am in, then I shouldn't need a knexfile.

**Comment by elhigu** [comment]
Migration directory is mentioned in knexfile, but yeah, it could fallback to default one.

Anyways I find it better to be sure that migration generation is ran in correct folder so you won't be creating additional migration directories by accident.

If PR is sent for this I suppose it could be merged in though if there are no objections to that.

**Comment by absolux** [comment]
Or an option `-d` or `--directory`, pointing by default to `cwd`, can be added to the cli instead of the knexfile.

**Comment by elhigu** [comment]
@absolux sounds reasonable, but only if -d is required when knexfile is not found. Otherwise the same problem of running knex client in wrong dir may happen.

**Comment by absolux** [comment]
@elhigu you are right.
It should be explicit, or implicit by taking the value of the folder path from the knexfile or `cwd()`

**Comment by KieronWiltshire** [comment]
All im saying is, I shouldn't need an active connection to make a migration. I don't mind if I do require a knexfile, it just shouldn't require any connection options.

**Comment by elhigu** [comment]
@KieronWiltshire Does it require connection details right now? Would be really strange if its trying to make DB connection just for copying template file... or does it perhaps require just that  `client` attribute is set?

**Comment by KieronWiltshire** [comment]
@elhigu I'm not sure, haven't really checked that far, this issue doesn't really affect me anymore as I have came up with another way around it

**Comment by KieronWiltshire** [comment]
@elhigu okay so finally found some time to test this, it requires the `client` option, and then if an empty object is provided, it goes nuts trying to find an unknown dialect.

**Comment by aurium** [comment]
It still require `client` configuration for cli `migrate:make`. Is this really necessary?
