### ISSUE TITLE
Create trigger schema builder method

### ISSUE THREAD

**Issue by stevenvachon** [tgriesser/knex#2161]
https://www.postgresql.org/docs/9.1/static/sql-createtrigger.html

would be nice to have this

**Comment by elhigu** [comment]
knex.raw is the way for now, if someone comes up nice way to do this with most of the dialects PR would be welcome. 

There are few closed issues about this feature, but looks like no one has yet created proper feature request / API proposal.

**Comment by stevenvachon** [comment]
I actually opted not to use triggers at all due to their implicit nature.

**Comment by elhigu** [comment]
Feel free to close this, if you think this is not needed after all.

**Comment by stevenvachon** [comment]
I don't need it, but others may (?).

**Comment by elhigu** [comment]
Closing this one... if someone likes to have trigger creation methods, they can open new feature request with info how to create them on all different databases + api proposal.
