### ISSUE TITLE
table.serial() ?

### ISSUE THREAD

**Issue by stevenvachon** [tgriesser/knex#2162]
Like http://knexjs.org/#Schema-integer, but different: https://www.postgresql.org/docs/9.6/static/datatype-numeric.html

**Comment by charmander** [comment]
[`table.increments(name)`](http://knexjs.org/#Schema-increments)

**Comment by stevenvachon** [comment]
That can only be used once.

**Comment by stevenvachon** [comment]
My mistake. I hadn't realized that serial will always be auto-incrementing. I was trying to enforce a "1 to 2147483647" data type.
