### ISSUE TITLE
How can copy the values of one column to another

### ISSUE THREAD

**Issue by warreee** [tgriesser/knex#2163]
Let's say I have two columns A and B. I want to copy my values of A to B.
Can this be done without raw sql?
If it is possible, what is the best practise to do this?

Cheers

**Comment by elhigu** [comment]
duplicate. somthing like `knex('Table').update({ a: knex.raw('??', ['b']) })`also usage questions should be sent to for example stackoverflow. This issue tracker is just for bugs and development related issues.

**Comment by warreee** [comment]
Alright no problem. I got confused because when I went through the issues there were some with the tag "Question".
