### ISSUE TITLE
Delete statement with alias

### ISSUE THREAD

**Issue by bemon** [tgriesser/knex#2166]
Its not possible to execute delete statement with table alias eg.

```mysql
 delete `f` from foo as `f` where `f`.`id` not in (?) and `f`.`bar` = ?
```

Even if we do this like this in knex:
```javascript
qb.from('f').table('foo as f').where(...).del();
```

**Comment by elhigu** [comment]
IIRC delete does not support `from`in knex (kind of join for update / delete statements). 

```
var knex = require("knex")({ client: 'pg' })
knex('Table as t').delete().where('t.id', 1).toSQL().sql
```

outputs: `delete from "Table" as "t" where "t"."id" = ?`

not exactly the same, but probably as near as you can get... `.with()` clause might help you to get somewhat similar functionality though.

**Comment by anonrig** [comment]
Hello from the year 2021.

![Hello general kenobi](https://media.giphy.com/media/8JTFsZmnTR1Rs1JFVP/giphy.gif)
