### ISSUE TITLE
MySQL Update Executes In Wrong Order

### ISSUE THREAD

**Issue by kurrestahlberg** [tgriesser/knex#2169]
MySQL differs from the SQL spec in update by using whatever is the current value in a field at the time of evaluating an expression. More here: https://dev.mysql.com/doc/refman/5.7/en/ansi-diff-update.html

Knex seems to always order all set statements in alphabetical order.

This causes a problem in a statement like the following for example:

```UPDATE table SET col1=col1+1, col2=col1*3;```

In this case let's assume I want col2 to be three times col1's value AFTER the update. The statement above would work correctly for MySQL as col1's new value will be used for calculating col2. Unfortunately at least MariaDB seems to follow the SQL spec and actually use the value of col1 from before the update and therefore store the wrong result.

I could fix this for both databases by doing ```UPDATE table set col2=(col1 + 1)*3,col1=col1+1;``` as then col1 would have the old value with both databases when calculating the value of col2. The problem is that Knex seems to reorder all fields to be updated to alphabetical order and therefore take away the possibility to make sure the correct result is stored with both databases.

**Comment by elhigu** [comment]
Sounds like a good idea to maintain order of keys when creating update... even that as far as I know javascript spec doesn't specify in which order they will be.

**Comment by absolux** [comment]
@kurrestahlberg it's not the fault of knex, it's `Object.keys`, used to construct the `set` clause, which returns the keys ordered in alphabetical order

**Comment by kurrestahlberg** [comment]
@absolux It is actually mostly the fault of MySQL because they deviate from the spec others follow, but Knex could be modified slightly to enable working around the issue. If Knex used a different way to store the update statements (or made sure to store ordering info alongside the other stuff) then keeping to original call order would be possible and the issue would go away.

Would a PR be accepted?

**Comment by elhigu** [comment]
@absolux I actually tried `Object.keys({ col2: 1, col1: 1 })`, `_.keys`and `Object.getOwnPropertyNames` on node 6.10.  All of them did seem to maintain order of keys. I was suspecting that some other part, maybe some object merging or so could have caused that order change in knex. 

@kurrestahlberg I would be happy to accept PR for this (ofcourse well tested one).

**Comment by absolux** [comment]
My mistake.
Actually the issue comes from `compiler._prepInsert(data)` which prepares the data and __*sorts [here](https://github.com/tgriesser/knex/blob/master/src/query/compiler.js#L565)*__ the columns names

**Comment by kurrestahlberg** [comment]
Do you know of any reason for the sorting other than nicer looking query? Could it simply be removed?

**Comment by elhigu** [comment]
I suppose it is there to make order of keys to remain stable between different js engines.

**Comment by kurrestahlberg** [comment]
Hm, obviously removing sorting breaks tests unless they are reordered as well. 

Are there any known issues with the engine reordering keys or messing up this stuff otherwise, or do you think sorting is enabled just in case?

(I feel better now that it took me full five minutes to figure out what that 20 line loop does 😄)

**Comment by elhigu** [comment]
@kurrestahlberg I don't know what has been the real motivation for sorting, so I cannot say for sure. https://stackoverflow.com/questions/5525795/does-javascript-guarantee-object-property-order there are some exceptions that V8 orders those keys that can be parsed as integers.

Looks like maybe ES2015 specify it though:

> Here is where you can count on property key order for plain Objects:
> 
> ES2015 compliant engine
> Own properties
> Object.getOwnPropertyNames(), Reflect.ownKeys(), Object.getOwnPropertySymbols(O)
>

**Comment by kurrestahlberg** [comment]
I created a PR: #2171

**Comment by elhigu** [comment]
Fixed via #2171
