### ISSUE TITLE
typeCast function not called for sqlite

### ISSUE THREAD

**Issue by GabeAtWork** [tgriesser/knex#2170]
I've tried using the `typeCast` option on sqlite databases, but it is not called on object retrieval.

I'm not sure whether or not that is intentional, as this option works very well with MySQL.

I've consulted #1240 to make sure how to use this function properly, as it doesn't seem to show up in the doc.

**Comment by wubzz** [comment]
@GabeAtWork Does the `sqlite` driver even support `typeCast` ? Pretty sure that's `mysql` specific.. `knex` is not the one calling `typeCast`.

Quick search of the `sqlite3` lib turns out zero results of `typeCast`.

**Comment by GabeAtWork** [comment]
@wubzz I don't know the internals of knex or the drivers very well, so I wasn't able to tell whether it was driver specific or not.

All I could tell was that it was called for MySQL and not for sqlite, so I thank you for the clarification :)

**Comment by wubzz** [comment]
Tried searching for a similar option for `sqlite3` but was unable to find one. Best of luck!

**Comment by GabeAtWork** [comment]
Thank you!

If anyone encounters the same problem, I solved it in tests like so:

```javascript
// "actual" has been retrieved from sqlite, and equals "0" or "1"
// If the value I'm comparing it to in the tests, I will compare the expected value to a manually cast boolean value
if(typeof expected === "boolean") {
    expect(!!actual).to.equal(expected);
}
else {
    expect(actual).to.deep.equal(expected);
}
```

This works well because the test knows the type of the value it needs to be compared to. It's a good crutch as long as you only need sqlite for tests environments.

To really solve the problem though, you'd have to transform the properties on retrieval based on some kind of config.
