### ISSUE TITLE
Updates with joins in postgres

### ISSUE THREAD

**Issue by sschick-prognos** [tgriesser/knex#2173]
when [compiling to mysql](https://github.com/tgriesser/knex/issues/191) there is a clear syntax for joining to an update. However, in postgres the syntax for doing this is `update...from`, which from what I understand knex can't really support, because there can only be one primary table. is it possible to compile this ;
```javascript
knex.from('table').update({a:knex.raw('othertable.a')}).join('othertable', 'othertable.b', 'table.b')
```
to this;
```sql
update table set a = othertable.a from othertable where othertable.b = table.b
```
particularly when the knex instance is for postgres? I understand that the syntax restricts us to inner joins, so limiting the join methods that work to innerJoin would be reasonable, but at the moment this just silently fails to add anything related to the join, and trying to add a from clause just changes the primary table.

**Comment by elhigu** [comment]
knex doesn't support `from` clause for updates / deletes etc. it works only for select.

However you can do something this (there might be some syntax errors.. didn't run the query):

```js
knex.from('table').update({
  a: knex('othertable').select('a').where('b', knex.raw('??', ['table.b'])
})
```

**Comment by sschick-prognos** [comment]
But from the issue I referenced and from [here](https://github.com/tgriesser/knex/commit/9c21af25c9bbcf11497dcd2d56c725d864f48c74), knex does support joins on updates. what I'm asking for is particularly for postgres for that join to be compiled into a from, because that is the syntax postgres expects when using secondary tables on an update. I am not asking for any changes to the `from` function in knex, just that we use the `join` functions in knex to support [postgres update from syntax](https://www.postgresql.org/docs/8.1/static/sql-update.html).

**Comment by sschick-prognos** [comment]
@elhigu  particularly what I'm worried about is if we have more than one column that is being updated;
```javascript
knex.from('table').update({
  a:knex.raw('othertable.a'),
  c:knex.raw('othertable.c')
}).join('othertable', 'othertable.b', 'table.b')
```
doing this as two subqueries would be really inefficient.

**Comment by elhigu** [comment]
Probaly both are equally efficient. You can check query plan to if there is any difference. Usually postgresql wont do multiple subqueries in that case, if subqueries are the same and only selected column is changed. Databases work mysterious ways many times it impossible to tell from query syntax how efficient it will be.

I'm pretty sure there is already feature request in knex issues to support from clause for updates for postgresql, if not please open one. I haven't heard that anyone has been planning to implement it though :(

**Comment by sschick-prognos** [comment]
looks like that is [here](https://github.com/tgriesser/knex/issues/557). Would it be unreasonable for me to try? I don't know what the culture around pushing code is for this.

**Comment by elhigu** [comment]
All pull requests are very welcome! Requirements are listed in CONTRIBUTING.md. Basically PR should have code, tests for it (including integration test that makes sure that query actually does what it is supposed to do) and link to PR to documentation repo. Then I or someone else review the code and ask for changes if there is need to do some stuff in a different way and when everything looks good reviewer merge PR to master.

**Comment by sschick-prognos** [comment]
good to know! thank you.

**Comment by duzenko** [comment]
This worked for me
```
	await knex( 'managers' ).update( {
		address: knex( 'clients' ).select( 'address' ).where( 'id', knex.raw( '??', ['managers.clientId'] ) ),
	} );
```

**Comment by JeongJuhyeon** [comment]
This works perfect:

```
const ratingsSubquery = model('rating').join('...').avg('..').as('r');

       knex('user')
        .update({ rating: model.raw('r.avg from ?', ratingsSubQuery) })
        .where('r.user_id', model.ref('user.id'));
```

Being able to substitute knex-built subqueries into raw queries is such a fantastic feature!
