### ISSUE TITLE
Is there a way to directly use a connection from Knex's connection pool?

### ISSUE THREAD

**Issue by electrotype** [tgriesser/knex#2176]
We use Knex with Oracle (oracledb). There is currently [an issue with Knex](https://github.com/tgriesser/knex/issues/1901) when stored procedures with OUT parameters are required.

What we can do is use Knex for everything except those stored procedures, and use connections from `oracledb` directly for the stored procedures. But then we have to manage _two_ connection pools... Which I'd like to avoid.

So now I'm trying to get an Oracle connection _from the Knex client_, so from Knex' connection pool! I tried something like (I'm using Typescript) :

```
let connection = await knex.client.acquireConnection();
try {
    return await connection.execute(`BEGIN SIAGDC.S35_PCK_DDS.S35_PRC_CYTR_NO_RESP(:P_DDS_ID, :P_NUMERO, :P_INT_ID); END;`,
        {
            //...
        }).then((result: any) => {
            //...
        }).catch((err: any) => {
            //...
        });
} finally {
    connection.close();
}
```
But when I do this, it seems `connection.close();` doesn't close the underlying connection properly. Let's say I create a connection pool with a maximum of 10 connections, and I make 11 requests, I then get a timeout : 

`TimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?`

Any idea how I could properly reuse Knex's connection pool to get raw connections?

**Comment by wubzz** [comment]
I don't condone these hax, but I get why you're trying it, given the issue at hand. You could try `knex.client.releaseConnection(connection)` instead of `connection.close()`. https://github.com/tgriesser/knex/blob/master/src/client.js#L258

**Comment by electrotype** [comment]
It seems to be working, thanks!
