### ISSUE TITLE
How can I get the `migrations` directory path from knex itself?

### ISSUE THREAD

**Issue by KieronWiltshire** [tgriesser/knex#2177]
I have a module that takes knex as a parameter and I wish to take retrieve the `migrations` directory path from the knex instance and publish the module's migration files into that directory.

I need the absolute path. How can I go about getting it?

```JavaScript
const path = require('path');

path.join(process.cwd(), knex.migrate.config.directory); //seems rather tedious
```

**Comment by elhigu** [comment]
or `path.join(__dirname, knex.migrate.config.directory)`, but yeah no easier way is available.
