### ISSUE TITLE
Returning 0 if AVG results are null

### ISSUE THREAD

**Issue by Ultear** [tgriesser/knex#2178]
Hello,

I'm wondering how to achieve returning object with 0 values for each key if there are no records for AVG.

Code example:
```
let service_rate = knex.raw('COALESCE(AVG(service_rate), 0) as service_rate')
  let price_rate = knex.raw('COALESCE(AVG(price_rate), 0) as price_rate')
  let attrcs_rate = knex.raw('COALESCE(AVG(attrcs_rate), 0) as attrcs_rate')
  let location_rate = knex.raw('COALESCE(AVG(location_rate), 0) as location_rate')

  let averages = await knex('reviews').select('place_id', service_rate, price_rate, attrcs_rate, locstion_rate).where({place_id}).groupBy('place_id')
```

Despite COALESCE, query always result with empty array, if there are no records for given place id. What i want to achieve is returning object with:
{
  service_rate: 0,
  price_rate: 0,
  ...and so on
}

Any help on that if COALESCE nor IFNULL doesn't work?

**Comment by absolux** [comment]
@Ultear I've tested on MySQL, MSSQL and Oracle the statement and it returns 0
```sql
select cast(coalesce(avg(area), 0) as integer) as avg from world where name = 'foo'
```

**Comment by elhigu** [comment]
@Ultear not really knex bug or related issue either... stackoverflow would be better forum to ask general questions how sql work.
