### ISSUE TITLE
debug: true  output builder.toString() instead of builder.toSql()

### ISSUE THREAD

**Issue by tnrich** [tgriesser/knex#2179]
Hey there,

I was just wondering if there is a way to get knex to output the `builder.toString()` instead of the `builder.toSql() ` when `debug:true` is set in the config. 

![image](https://user-images.githubusercontent.com/2730609/28880837-352874a4-7774-11e7-81ec-8f7471af13bb.png)

The above photo (from `knex/src/runner.js`) shows how just the `builder.toSql()` is getting passed to the debug logger. Maybe there could be some sort of option to pass the `builder.toString()` instead?

Thanks!

**Comment by elhigu** [comment]
Maybe if some better debug output hook functionality is implemented.  wouldn't like to  add this as a standalone feature. If you need this for being able to copy-paste queries, maybe you can write your own query printing callback for on `query` event.
