### ISSUE TITLE
Raw query returns decimals as strings ?

### ISSUE THREAD

**Issue by alinberce** [tgriesser/knex#2182]
I have a table with column

`table.decimal('some_column', 30,15)` which on postgres is `numeric(30,15)`
When I run a `knex.raw('select some_column from some_table') ` from node, the response I get in rows is like:

`some_column: "5.000000000000000"`
`some_column: "10.000000000000000"`

What really pointed me to this is that I do something like firstValue>lastValue I end up with a true response so that makes me think that these are returned as strings and not as numbers.

Any way to override this behavior?

**Comment by elhigu** [comment]
How data is read from DB is decided by DB driver. At least mysql and pg drivers allows to override it.
