### ISSUE TITLE
knex("group").columnInfo() resolves to Error with SQLite3

### ISSUE THREAD

**Issue by rafaelkallis** [tgriesser/knex#2184]
When using `group` as table name, `knex("group").columnInfo()` resolves to:
```
PRAGMA table_info(group) - SQLITE_ERROR: near "group": syntax error
```

When escaping the table name, all works as expected.
```js
knex("group").columnInfo(); // -> error
knex("'group'").columnInfo(); // -> ok
```

System using: latest `knex`, latest `sqlite3`, latest `node`, latest `npm`, latest `macOS`.

**Comment by elhigu** [comment]
Yep, looks like a bug:

https://runkit.com/embed/h1wibb2dk4qr
