### ISSUE TITLE
Proposal: Export Knex (the config function) as default

### ISSUE THREAD

**Issue by ericeslinger** [tgriesser/knex#2189]
I recently switched from plain old js to typescript, which has a slightly different, and at times annoying, way of dealing with import/export keywords, but is more or less similar to es6 semantics.

Knex right now uses those es6 import / export semantics in the source code, but the top-level knex.js that is flagged as main in package.json says `module.exports = require('./lib/index')`, which more or less makes that useless.

This would be a breaking change, but what I'd like to be able to do is something like:

```
import Knex, { Client } from 'knex';
```

and have that work in typescript as well. The problem appears to be that the typescript definition is using the older `export =` syntax to create namespaces and export them, instead of using a simpler `export interface Knex {}` sort of thing. In rewriting those type files, I realized this was impossible without changing knex - the resultant code *compiled* (of course, since it's all just the declarations), but wouldn't run, since the knex package has no default export. So instead I have to `import * as Knex` and muck around with namespace magic.

Anyway, I think this would probably be a breaking change for people using the `require` semantics to load up knex, so that may be a dealbreaker (I think they'd have to do `knex = require('knex').default` or something similar).

Generally, the problem is probably more about exporting a factory function as the root export (rather than treating the root export as a namespace, like `require('knex').createClient()` or something like that).

As an aside, it is possible to add a line to `knex.js` in the root directory with `module.exports.default = module.exports`, but that feels pretty hacky (and circular), and may be just a brittle fix to the more complicated problem of module / amd / require interop.

**Comment by elhigu** [comment]
I've been mainly writing typescript couple of years now and IMO `default exports` are not way to go. 

They are not so compatible with `commonjs` modules syntax which people will use years to come and I don't see much advantage to have something in module set as default compared to named exports...

With named exports one can do:

```js
import { Knex } form 'knex';         // es6 modules
const { Knex } = require('knex');  // commonjs with destructuring 
var Knex = require('knex').Knex;  // commonjs
```

which looks pretty ok on all of the platforms. 

Anyways... until node support es6 module syntax I don't see any point of changing how knex is imported so

```ts
import * as Knex from 'knex';  
```

can be used with typescript for now (this is the way how most of the current older js libs has done it) and we'll see how it should be done in the future when the world is ready.

**Comment by ericeslinger** [comment]
yeah, you're right - I had a different error that was obfuscating my issue. What I wanted to do was be able to say something like `const services: { knex: Knex } = { knex: Knex(config) };` and get type support on services.knex, and I was getting errors that indicated that the Knex type namespace was not supporting that in some way.

anyway, my bad. modules are still annoyingly in flux though.

**Comment by Sphinxs** [comment]
Any update ?
