### ISSUE TITLE
How to mark all errors with name/code property

### ISSUE THREAD

**Issue by yonatannn** [tgriesser/knex#2191]
Hi,

It's very important that every thrown error will get some classification so the app can thoutfully act on it

See bullet 3 here:
http://goldbergyoni.com/checklist-best-practices-of-node-js-error-handling/

I wonder how can I achieve that now, for example I would like wrap knex with ES6 proxy and trap the query method, catch its errors and rethrow with classification (new Error().code=query)).

Which main method can I trap that performs all queries? any other ideas?

Y

**Comment by elhigu** [comment]
Database errors are passed directly from database driver etc. to knex user... What are you trying to do exactly and why?

**Comment by yonatannn** [comment]
@elhigu within my web layer (i.e. express), I'm catching errors which might come from the DAL layer or from other places. Then I decide what to do with the error - this is the concept of operational vs developer error. Should I know that a specific error comes from the DAL/knex I could safely decide not to crash the process. But currently all errors from Knex have no classification. 

This behaviour doesn't conform to error handling best practices, In Node 8, even all the core errors are now classified with code:
https://developer.ibm.com/node/2017/07/05/node-js-errors-changes-you-need-to-know-about/

My question is, how can I tag all the errors from Knex so the one who will catch those can know that they are related to Knex? one way would be to wrap some Knex main method, catch errors, classify and rethrow

This package tried to acheive that by its oudated:
https://www.npmjs.com/package/knex-generic-errors

**Comment by elhigu** [comment]
@yonatannn knex will not wrap / map different dialect errors like generic errors is doing. What may be done in knex side is to add code information to the errors which are thrown by knex itself.

**Comment by elhigu** [comment]
As mentioned in https://github.com/tgriesser/knex/issues/522 you need to wrap  / parse etc. errors by yourself or use some external lib if available. 

I'm open to check PR which adds error codes to exceptions thrown by knex itself though. Closing as duplicate.
