### ISSUE TITLE
Wrapping the query method

### ISSUE THREAD

**Issue by i0natan** [tgriesser/knex#2196]
Hi,

Thanks for this great library. I'm tasked to "intercept" each query and inspect it. A developer is not allowed to perform all type of queries so I'd like in one place to listen to all queries and check it. For example, if there is a main method in Knex that performs queries I can wrap it (e.g. using ES6 proxy or even by changing the Knex prototype) and inspect the input before passing to the origin function.

Is there a main/single query method in Knex which I can intercept/wrap where all the queries must go through?

Best,
Yoni

**Comment by wubzz** [comment]
For just inspecting? Events
`knex.on('query', () => {...});`

For inspecting and throwing/canceling? Can overwrite
`knex.client.query`
