### ISSUE TITLE
Is encrypted DB access possible via Knex using SQLite and SQLCipher?

### ISSUE THREAD

**Issue by glogan91** [tgriesser/knex#2201]
Does anyone have any experience (hints or direction they can pass along) for encrypting and accessing an encrypted SQLite database via Knex?

From a couple different pieces of documentation, it appears I need to:
1) build a version of sqlcipher for my OS/hardware.
2) build a version of SQLite3 including the sqlcipher library.
3) ... (Knex relevant portion) figure out the specific commands to use through Knex for db connection/decryption (These would appear to be relevant when you 'connect', so not called on each db access - perhaps only once in the main/startup program (server.js)? And would probably have to be called using the 'raw()' function?

Any guidance would be appreciated  (even: "you can't get there from here") , to minimize my trial & error implementation attempts.

**Comment by elhigu** [comment]
Stackoverflow or sqlcipher forums would be better place to ask this kind of support. This doesn't have much to do directly with knex and github issues are for development issues.

If you figure out that knex requires some new feature to support this, please open a feature request for that specific thing. 

I'm closing this, but if anyone likes to comment or discuss more about this please feel free to do so.

**Comment by glogan91** [comment]
I've solved this now, and thought I would share it here in case anyone may find it useful in the future.

After you build the SQLCipher source and the npm SQLite3 package, and encrypt your DB (look elsewhere for these things), then anytime you open your database, you need to provide your encryption key using the SQL statement:

`PRAGMA KEY = 'secret'`

This PRAGMA is more completely documented in the SQLCipher site. When working with KNEX this is best done when opening the DB, via the following:
```
const myDBConfig = { client: "sqlite3",
               connection: {
                    filename: "myEncryptedSQLiteDbFile.db"},
               pool: {
                   afterCreate: function(conn, done) {
                   conn.run("PRAGMA KEY = 'secret'");
                   done();
                }  
              } 
};
const knex = require('knex')(myDBConfig);
```
Of course embedding the key value in your code is a poor security practice. More appropriate is to retrieve the 'secret' from elsewhere. 

The key KNEX thing to note here is the "**_afterCreate_**" function. This is documented in the knexjs.org site, but is not in the Table of Contents at this time, so do a browser find when on the site to get to it. It allows auto-updating DB settings when creating any new pool connections (of which there will only ever be one per file for KNEX-SQLite).

If you don't use the "afterCreate" configuration, then you will need to run a knex.raw statement with each and every SQL you execute, something like as follows:
```
    return knex.raw("PRAGMA KEY = 'secret'")
        .then(() => {
            return knex('some_table').select()
                .on('query-error', function(ex, obj) {
                    console.log("KNEX select from some_table ERR ex:", ex, "obj:", obj);
                })
        });
```
Regards, Gary.

**Comment by OneOfCats** [comment]
> I've solved this now, and thought I would share it here in case anyone may find it useful in the future (and my apologies for the minor misuse of this issue log).
> 
> After you build the SQLCipher source and the npm SQLite3 package, and encrypt your DB (look elsewhere for these things), then anytime you open your database, you need to provide your encryption key using the SQL statement:
> 
> `PRAGMA KEY = 'secret'`
> 
> This PRAGMA is more completely documented in the SQLCipher site. When working with KNEX this is best done when opening the DB, via the following:
> 
> ```
> const myDBConfig = { client: "sqlite3",
>                connection: {
>                     filename: "myEncryptedSQLiteDbFile.db"},
>                pool: {
>                    afterCreate: function(conn, done) {
>                    conn.run("PRAGMA KEY = 'secret'");
>                    done();
>                 }  
>               } 
> };
> const knex = require('knex')(myDBConfig);
> ```
> Of course embedding the key value in your code is a poor security practice. More appropriate is to retrieve the 'secret' from elsewhere.
> 
> The key KNEX thing to note here is the "**_afterCreate_**" function. This is documented in the knexjs.org site, but is not in the Table of Contents at this time, so do a browser find when on the site to get to it. It allows auto-updating DB settings when creating any new pool connections (of which there will only ever be one per file for KNEX-SQLite).
> 
> If you don't use the "afterCreate" configuration, then you will need to run a knex.raw statement with each and every SQL you execute, something like as follows:
> 
> ```
>     return knex.raw("PRAGMA KEY = 'secret'")
>         .then(() => {
>             return knex('some_table').select()
>                 .on('query-error', function(ex, obj) {
>                     console.log("KNEX select from some_table ERR ex:", ex, "obj:", obj);
>                 })
>         });
> ```
> Regards, Gary.

How did you make it work with encrypted db? It says "file is not a database"

**Comment by kibertoad** [comment]
@glogan91 I've added slightly adjusted version to recipes https://github.com/tgriesser/knex/wiki/Recipes, could you please review it?

**Comment by glogan91** [comment]
@kibertoad You bet. I'll examine & run it in my env in the next day or so.

**Comment by glogan91** [comment]
@kibertoad - It looks great to me!

@OneOfCats - If you post your problem on stack exchange, tag it with "knex.js" and include the code you've attempted, I'll look and see if I can help.

**Comment by elig0n** [comment]
this stopped working for me with:

Unhandled rejection Error: SQLITE_NOTADB: file is not a database

file is getting decrypted just fine manually via sqlcipher

**Comment by feniljariwala82** [comment]
> this stopped working for me with:
> 
> Unhandled rejection Error: SQLITE_NOTADB: file is not a database
> 
> file is getting decrypted just fine manually via sqlcipher

Not working for me too.

**Comment by feniljariwala82** [comment]
> I've solved this now, and thought I would share it here in case anyone may find it useful in the future (and my apologies for the minor misuse of this issue log).
> 
> After you build the SQLCipher source and the npm SQLite3 package, and encrypt your DB (look elsewhere for these things), then anytime you open your database, you need to provide your encryption key using the SQL statement:
> 
> `PRAGMA KEY = 'secret'`
> 
> This PRAGMA is more completely documented in the SQLCipher site. When working with KNEX this is best done when opening the DB, via the following:
> 
> ```
> const myDBConfig = { client: "sqlite3",
>                connection: {
>                     filename: "myEncryptedSQLiteDbFile.db"},
>                pool: {
>                    afterCreate: function(conn, done) {
>                    conn.run("PRAGMA KEY = 'secret'");
>                    done();
>                 }  
>               } 
> };
> const knex = require('knex')(myDBConfig);
> ```
> 
> Of course embedding the key value in your code is a poor security practice. More appropriate is to retrieve the 'secret' from elsewhere.
> 
> The key KNEX thing to note here is the "**_afterCreate_**" function. This is documented in the knexjs.org site, but is not in the Table of Contents at this time, so do a browser find when on the site to get to it. It allows auto-updating DB settings when creating any new pool connections (of which there will only ever be one per file for KNEX-SQLite).
> 
> If you don't use the "afterCreate" configuration, then you will need to run a knex.raw statement with each and every SQL you execute, something like as follows:
> 
> ```
>     return knex.raw("PRAGMA KEY = 'secret'")
>         .then(() => {
>             return knex('some_table').select()
>                 .on('query-error', function(ex, obj) {
>                     console.log("KNEX select from some_table ERR ex:", ex, "obj:", obj);
>                 })
>         });
> ```
> 
> Regards, Gary.

How did you create the SQLCipher source? I followed [this](https://www.domstamand.com/compiling-sqlcipher-sqlite-encrypted-for-windows-using-visual-studio-2022/) guide to create an SQLCipher source with a passphrase. And I tried to connect to it using **Knex.js**, but it is not working.

**Comment by Shubha9519** [comment]
Anyone found a fix for this?
