### ISSUE TITLE
what is stream?

### ISSUE THREAD

**Issue by kiodou** [tgriesser/knex#2204]
does stream get the data realtime?

I want to do a select query and get updated by an event handler when anything changes:

e.g:
1. a record get edited
2. new record was added
3. record was deleted

Can stream help me with this? Or am i wrong?

If so can someone give me an example?

**Comment by kiodou** [comment]
never mind i found what i needed

**Comment by kiodou** [comment]
Nevermind, after doing more researching i found what i needed --- Closes #2204

**Comment by kiodou** [comment]
Nevermind, after doing more researching i found what i needed, closing

**Comment by dmitriz** [comment]
Would you share what you have found?
