### ISSUE TITLE
mysql error in calling stored procedure

### ISSUE THREAD

**Issue by BhaskaranR** [tgriesser/knex#2205]
i get this error when i call the stored procedure. 

Unhandled rejection Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1. not sure if this is a bug and am i missing anything?

```
kn.raw(`call pricing.CALCULATE_PRICING('599bb2a86f6db925bda3f133', 96, '599c13ac1d8f600fcb291f90');`)
            .then((result) => {
                console.dir(result, {depth: null}) 
                resolve(result)
            });
```

**Comment by BhaskaranR** [comment]
hi is the show stopper for me. can you help me with this. i cant find a solution

Unhandled rejection Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1

**Comment by BhaskaranR** [comment]
worked with this change

```
 return new Promise((resolve, reject) => {
        console.log(`Call pricing.CALCULATE_PRICING('${person}', ${eventId}, '${id}');`);
        kn.raw(`call pricing.CALCULATE_PRICING('${person}', '${eventId}', '${id}')`)
            .then((result) => {
                console.dir(result, {depth: null}) 
                resolve(result)
            });
    }).catch((ex) => { 
        console.log(ex); 
    }
        );
```

**Comment by elhigu** [comment]
Ah, ok so the problem was that 96 had to be passed as a string '96' or was the error thrown because of extra semicolon in the end of the line? Those seems to be the only changes in the working version.
