### ISSUE TITLE
authSwitchHandler not passing through for mysql2

### ISSUE THREAD

**Issue by umarazhar** [tgriesser/knex#2206]
Hi,

I am trying to setup IAM authentication with AWS RDS from node and for that I need the authSwitchHandler option in mysql2. I think release 0.13.0 is not passing this option through, but i tested it with your master branch and it works on that. On 0.13.0 I was able to modify "knex/src/dialects/mysql2/index.js" to get it to work. The fix was simple, just add "authSwitchHandler" to the "configOptions" array.

I'm wondering when the next release (master branch) will be coming out, or if its possible to apply a patch to 0.13.0?

Thanks your help!

Cheers,
Umar

**Comment by elhigu** [comment]
0.14 is coming this year, there are some pull requests, which I would like to have ready before the jump so that 0.14 could have patch releases too with smaller updates...
