### ISSUE TITLE
return null with knex.raw(sql) in mysql

### ISSUE THREAD

**Issue by sangheestyle** [tgriesser/knex#2207]
Hi,

I use knex with [join monster](http://join-monster.readthedocs.io) for implementing GraphQL server. I implemented it with PostgreSQL and it worked well but it doesn't work with MySQL.

I found the following at [the join monster page](http://join-monster.readthedocs.io/en/latest/call-function/):

```
If you are using Knex, be careful. The raw method will return different objects depending on the knex dialect being used. The exact snippet above may not work with MySQL, MariaDB, etc.
```
And this is true.

Here is what I try on knex debug mode:

```
{ method: 'raw',
  sql: 'SELECT\n  `dashboards`.`dashboard_id` AS `dashboard_id`,\n  `dashboards`.`dashboard_id` AS `id`\nFROM dashboards `dashboards`\nWHERE `dashboards`.owner_id="xxxxx"',
  bindings: [],
  options: {},
  __knexQueryUid: '517ff79f-d2f2-499f-bf87-45c5e0340af9' }
```

And I got the following:

```
[ { dashboard_id: undefined, id: undefined } ]
```

When I copied the query from the debug log and executed it on SQLWorkbenchJ, it returned two rows which I expected.

Could anybody tell me where do I need to start to fix this problem?

p.s, I posted [similar question](https://github.com/stems/join-monster/issues/215) at join monster issue tracker.

**Comment by elhigu** [comment]
If you find some `knex` related problem, please open new issue. This issue has nothing to do with `knex` since join monster probably just generates some invalid queries in this case.

**Comment by sangheestyle** [comment]
hi @elhigu ,

I already mentioned the problem above. Same query generated by Join monster is not worked with knex.raw() but it worked on other query driver. That's why I opened this issue.

What do you think the above query?

```
'SELECT\n  `dashboards`.`dashboard_id` AS `dashboard_id`,\n  `dashboards`.`dashboard_id` AS `id`\nFROM dashboards `dashboards`\nWHERE `dashboards`.owner_id="xxxxx"'
```

Could you give me some opinion about it? I think join monster generates correct one.

**Comment by elhigu** [comment]
I can see directly from quotes that join monster does not seem to be using identifier replacement correctly, since there are some quotes missing from identifiers and also using double quotes around xxxx seems a bit weird. 

If anyone likes to look further in this please go ahead discussion, but there is no use to leave this open in knex issues, since this does not look like a bug in knex. 

For general sql related questions like this stackoverflow is better place and for join monster bugs (strange quotes) its issue tracker should work.

**Comment by sangheestyle** [comment]
@elhigu Thanks for your opinion. Double quotes for owner_id is for string but I see what you want to say. The double quote part is made by myself not the join monster. I will change it and test it later then update it for somebody who will have similar problem.

One thing I want to say is that it worked with others such as SQLWorkbenchJ that's why I asked this at here.

I think it is enough to close this issue.

p.s., Frankly speaking, quite hard to leave some issues or questions if you have to say like that.

**Comment by elhigu** [comment]
We are quite flooded with issues and there are very few people reading them through and answering. So already maybe over year ago we have started to use github issues only for development issues / feature requests and bug reports. All the general questions how to use knex and problems that cannot be reproduced we have directed to stackoverflow. 

I tried to find out if the policy was mentioned in somewhere in knex docs, but I couldn't find it, so I'll be updating knex page and readme with info about the current policy.

**Comment by sangheestyle** [comment]
@elhigu I see you point. But, please check the following code. With mysql node.js driver, it worked fine. Even it worked with double quote `owner_id="xxxxx"` or single quote `owner_id=\'xxxxx\'`.

```javascript
var mysql = require('mysql');

var con = mysql.createConnection({
  host: 'xxx',
  user: 'xxx',
  password: 'xxx',
  database: 'xxx',
});

//var sql = 'select * from dashboards;';
var sql = 'SELECT\n  `dashboards`.`dashboard_id` AS `dashboard_id`,\n  `dashboards`.`dashboard_id` AS `id`\nFROM dashboards `dashboards`\nWHERE `dashboards`.owner_id="xxxxx"';

con.connect(function(err) {
  if (err) throw err;
  console.log("Connected!");
  con.query(sql, function (err, result) {
    if (err) throw err;
    for (i = 0; i < result.length; i++) {
      console.log("Result: " + result[i].id);
    }
    con.end();
  });
});
```

Result
```
$ node main.js 
Connected!
Result: 1
Result: 2
```

I think this is not related to sql question which you mentioned but it's fine. Bye.

**Comment by elhigu** [comment]
If you believe this is a knex bug, please send a simple example code (single file, which inits DB and does the query and returns wrong results). I still don't have any means to reproduce the problem you are experiencing.

Are you sure you have initialized DB before query is executed and all that?

**Comment by sangheestyle** [comment]
OK, I want to say I don't know this is knex bug or not. I just want to know where I need to start to solve this problem that's why my comment was `Could anybody tell me where do I need to start to fix this problem?`

With the same query, mysql node.js driver works fine. Even in this case, there are many different possibilities so I don't want to say this is knex bug.

I am going to use workaround with mysql driver first then I will trace this situation(OK, I am going to use the word situation instead of problem) then I will be back.

p.s., 'Are you sure you have initialized DB before query is executed and all that?' <- works fine with other knex features without knex.raw() which works fine with sqlite, postgreSQL.

**Comment by PavleGit** [comment]
As mentioned in join-monster documentation: data from knex is different from what joinMonster expects.

For joinMonster to parse data properly, data needs to be array of rows:
```javascript
[
  { id: 1, email_address: 'andrew@stem.is', post__id: 13, post__body: 'Hello world.' },  
  { id: 2, email_address: 'matt@stem.is', post__id: 15, post__body: 'Make it less side-effecty!' }  
]
```

This means that you first need to parse and 'clean' raw data from knex and then pass it on to joinMonster.

Quick fix for your bug would therefore be something like this:
```javascript
resolve: (parent, args, context, resolveInfo) => {
    return joinMonster(resolveInfo, {}, sql => {
        // 'parse' knex data (return first item in array), before returning it to joinMonster
        // it seems knex.raw(sql) returns query promise, not actual results
        return knex.raw(sql).then(rows => rows[0]);
    }, {dialect: 'mysql'});
}
```
