### ISSUE TITLE
unknown named module ./dialects/sqlite3/index.js

### ISSUE THREAD

**Issue by dlonli** [tgriesser/knex#2209]
I'm getting an error saying `./dialects/sqlite3/index.js doesn't exist`. I checked the `knex` directory in node_modules and it does exists.

I've tried everything I tried updating the packages `npm update`.

I've tried deleting nodes_muldes directory and installing them again `npm install`
I even deleted knex and installing again, i don't know what to do

**Comment by dlonli** [comment]
I changed `Dialect = require('./dialects/' + (aliases[clientName] || clientName) + '/index.js');` to `Dialect = require('knex/lib/dialects/' + (aliases[clientName] || clientName) + '/index.js');`

in `knex/lib/index.js` and it fixed it. Not a good fixed. But looking in why it doesn't work normally

**Comment by dlonli** [comment]
Seems like it can find it originally, it just that it doesn't like put an variable in a require
`require("../path/to/something") // works`
`require("../path/to/ + var1 +"/something") // does not work`

**Comment by elhigu** [comment]
Do you have code for reproducing the issue? Sounds like you are just requiring `knex` some unsupported way.

**Comment by gpresland** [comment]
I am receiving the same error with Knex 0.13.0. This is occurring when I am attempting to compile my project with [Nexe](https://github.com/nexe/nexe/tree/master) version 1.1.3.

**Comment by elhigu** [comment]
@gpresland maybe you should ask in nexe github / stackoveflow how to use it with knex?  And try to require knex/index instead of e.g. webpack build.
