### ISSUE TITLE
Can't pass variables into where or static booleans into join in query

### ISSUE THREAD

**Issue by TriStarGod** [tgriesser/knex#2212]
I just started using knex. Seems like a good library but I can't write basic SQL queries. I've read the knex's documentation several times to no avail.
```
knex('Task')
          .join('TaskTpl', {
            'TaskTpl.userId': 'Task.userId', // works
            'TaskTpl.inactive': false, // ERROR: for some reason converted to string "false"
            'TaskTpl.id': task.childTaskTplId,
          })
          .where({
            'Task.id': task.id, // ERROR: for some reason a ?
            'Task.userId': 0, // ERROR: for some reason a ?
          })
          .first('Task.id');
```
In The above code, I have issues with the boolean in join (ie error: column "false" does not exist) and passing a variable into the where. I ran the toSQL() function to debug and it gave me the following:
`'select * from "Task" inner join "TaskTpl" on "TaskTpl"."userId" = "Task"."userId" and "TaskTpl"."inactive" = "false" and "TaskTpl"."id" = 0 where "Task"."id" = ? and "Task"."userId" = ? limit ?'`
I've tried knex.raw as well but the results are worse.

Using pg db

**Comment by absolux** [comment]
@TriStarGod try this
```js
knex('Task')
  .join('TaskTpl', 'TaskTpl.userId', 'Task.userId')
  .where({
    'TaskTpl.id': task.childTaskTplId,
    'TaskTpl.inactive': false,
    'Task.id': task.id,
    'Task.userId': 0
  })
  .first('Task.id')
```
Values in where clause will be passed as parameters and replaced with `?` in the SQL query

**Comment by TriStarGod** [comment]
Awesome, thanks. I thought the documentation said you could put variables in joins. As long as it works, I'm good.
