### ISSUE TITLE
How can I use knex.raw in transaction? 

### ISSUE THREAD

**Issue by qwang07** [tgriesser/knex#2214]
I try to update multiple rows in a transaction. I need to update some data base on its' original value. Like 
```
update aTable set something = something + 1 where id = '1'
```
or a function:
```
update aTable set something = concat_ws('|', title, otherField) where id = '1'
```
I cannot do that with .update() and I have to use knex.raw(). How can I use it within the transaction? or How can I do that within .update() method?

**Comment by elhigu** [comment]
yes you can and also you can also do:

```
  knex('aTable').update({
    something: knex.raw('?? +1', ['something'])
  }).where('id', 1)
```

to create the first query. You can check examples of all the places where you can use knex.raw in http://knexjs.org/
