### ISSUE TITLE
Oracle query generated with double quotes on table name

### ISSUE THREAD

**Issue by marcelotmagalhaes** [tgriesser/knex#2219]
Hello, I'm having an issue and couldn't find anything about in the issues here. So the problema is that this line: 

`knex('users').where('id', 1)`

produces:

`select * from "users" where "id" = 1`

This returns me an error:

`Error: ORA-00942: table or view does not exist`

But if I try the same SQL without the double quotes, it works on SQLDeveloper.
Is there any way to disable this quotation?

**Comment by elhigu** [comment]
In next release 0.14 there is support for overriding how, quoting is done. 

In this case you are probably getting the error, because you have user mixed / uppercase names in database. To get queries correct you would need to use case sensitive names for now. Closing as duplicate.

**Comment by vschoettke** [comment]
@marcelotmagalhaes you just have to convert your lowercase tablename to uppercase to make the query work. Oracle converts no quoted names to uppercase where as other dbs convert to lowercase. The same is necessary for the column names if you created them without quotes. If quoting in knex will be optional you still may have to handle the column name (e.g. querying `select id from users;` will return rows like this {"ID": <yourId>})

**Comment by marcelotmagalhaes** [comment]
@vschoettke thank you for the explanation. I converted the table name and column name to uppercase now it works.
Another doubt, I'm not a DBA guy so I don't know much about databases (I'm more a frontend guy), but I'm trying to create a migration for oracle, and a timeout error is appearing.

The migration:

`exports.up = function(knex, Promise) {
	return knex.schema.createTable('users', table => {
		table.increments();
		table.string('name').notNullable();
		table.string('email').notNullable();
		table.string('password').notNullable();
		table.timestamp('created_at').defaultTo(knex.fn.now());
		table.timestamp('updated_at').defaultTo(knex.fn.now());
	});
};`

The error:

`TimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
    at Timeout._onTimeout (/Users/marcelomagalhaes/Projects/Clientes/Internos/Comercial/server/node_modules/knex/lib/client.js:287:18)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)`

The message says the pool is full, but I can make selects and so without problems. This a test database with just a few users connected.
Am I missing something in the code or I need to talk to the DBA to grant some privilege to the connected user?

**Comment by PedroNishimura** [comment]
Olá marcelo, poderia me dar uma luz de como você fez essa query com upper, sei que essa issue é antiga mas ficaria grato com sua ajuda.
