### ISSUE TITLE
Allow a custom function for debugging output

### ISSUE THREAD

**Issue by msikma** [tgriesser/knex#2221]
Currently, setting `debug: true` in the config causes all queries to be logged through `console.log()`. See [helpers.js](https://github.com/tgriesser/knex/blob/master/src/helpers.js#L25) and [runner.js](https://github.com/tgriesser/knex/blob/master/src/runner.js#L35). It would be helpful to be able to pipe this output through to a custom function. That way I could use a logger to send them to a file, which would be useful for debugging/developing.

I'm thinking the most practical way to pass on this function is in the initialization object, probably.

**Comment by elhigu** [comment]
Duplicate https://github.com/tgriesser/knex/issues/1483
