### ISSUE TITLE
Change searchPath per query?

### ISSUE THREAD

**Issue by jimsimon** [tgriesser/knex#2223]
I wasn't able to find an answer in the docs, but is it possible to change the postgres searchPath after the connection has been created?  I'm working on a multi-tenant application that has each tenant's data in its own schema.  I'd like to grab a connection from the pool, set the search path for that connection, then query like normal.  It seems like I might be able to use `.options(...)` to do it, but it's not clear if that will work.  Is this possible?

**Comment by wubzz** [comment]
`.options()` is completely dependant on what the `pg` library supports. As far as I know they don't have an options object for `connection.query`, but I could very well be wrong.

In knex you can use `.withSchema` on the querybuilder. Alternatively running in transactions and setting search path right after transaction has been created is another way to go.

In the future please refrain from posting these kinds of questions in the repository issue list. Use stackoverflow for these types of questions.
