### ISSUE TITLE
jsonb operator treated as prepared statement placeholder

### ISSUE THREAD

**Issue by SeanCannon** [tgriesser/knex#2225]
Given this query : 

```
db.raw(`
    SELECT scores.name, scores.topics
    FROM scores
    WHERE topics::jsonb ?| (SELECT array_agg(topic_tag)
    FROM topics
    RIGHT JOIN client_topics ON topics.topic_id = client_topics.topic_id
    WHERE client_topics.client_id = 1)`);
```

I get this error `syntax error at or near \"$1\"` , because the third line becomes `WHERE topics::jsonb $1| (SELECT array_agg(topic_tag)`

In my node_modules/knex the package.json indicates the version to be `"_resolved": "https://registry.npmjs.org/knex/-/knex-0.13.0.tgz",`

I tried escaping the question mark like this, but it doesn't change the error: 
```
WHERE topics::jsonb \?| (SELECT array_agg(topic_tag)
```

**Comment by zacronos** [comment]
The documentation at http://knexjs.org/#Raw-Bindings says to use `\\?` to escape question marks in raw expressions/bindings.  Does it work when you try that?

**Comment by elhigu** [comment]
@SeanCannon remember that in javascript string you need to write `\\` to have one `\` in output string. So as @zacronos said `\\?` works and we are using it all the time in jsonb support of objection.js and that feature is also tested in knex test suite.

**Comment by SeanCannon** [comment]
Perfect, seems to work. Cheers!

**Comment by rpuls** [comment]
There seem to be some inconsistency depending on what environment you are running. At least what have worked for some does not work for other. What I did that solved my problem was this:
`INSERT INTO db."table"("id", "bodyText") VALUES (1234, '\? - \\? - \\\? - \\\\? # /? - //? - ///? - ////?');`
In my case the output was: `? - $13 - ? - $14 # /$15 - //$16 - ///$17 - ////$18` ie. I am now using single backslash for escaping the question mark which works with my environment. My knex version is 0.14.6, 
but I can't promise that I don't have any other node packages that touches my queries before they are executed.
