### ISSUE TITLE
Cannot use named or positional bindings for raw query with IN clause in Oracle

### ISSUE THREAD

**Issue by jeremija** [tgriesser/knex#2229]
I have the same problem as described in #1228, only I'm using OracleDB. It doesn't matter if named or positional bindings are used.

The example:

```javascript
import knex from '../src/oracleDataSource'

describe('where in', function suite () {
  this.timeout(20000)

  it('works with variable number of arguments', async () => {
    const results = await knex.raw(
      'select * from (select 1 as id from dual union select 2 as id from dual) where id in (?)',
      [ [1, 2] ],
    )
    console.log('results', results)
  })

})
```

results with:
```javascript
{ method: 'raw',
  sql: 'select * from (select 1 as id from dual union select 2 as id from dual) where id in (?)',
  bindings: [ [ 1, 2 ] ],
  options: {},
  __knexQueryUid: 'cfc47d05-4df3-4d58-9e88-1d3d41a76b13' }
```
```
Error: NJS-044: named JSON object is not expected in this context
```

I'd expect the results to be as described in the comment [here][1]

[1]: https://github.com/tgriesser/knex/issues/1228#issuecomment-189312598

**Comment by jeremija** [comment]
This is related to https://github.com/oracle/node-oracledb/issues/137.

A workaround is to do:

```javascript
const ids = [1, 2]
const results = await knex.raw(
  'select * from (select 1 as id from dual union select 2 as id from dual) where id in (?)',
  [ knex.raw(ids.map(() => '?').join(', '), ids) ]
)
```

But it would be much nicer if knex would do this automatically, like it is in the documentation.

**Comment by elhigu** [comment]
Raw cannot know how it should output the array you are giving to it, look for example these issues https://github.com/tgriesser/knex/issues/1537 https://github.com/tgriesser/knex/issues/791 . You should use `.whereIn()`.

Maybe like this:

```js
knex(knex.raw('select 1 as id from dual union select 2 as id from dual')).whereIn('id', [1,2]);
```

Anyways this is duplicate with  #791
