### ISSUE TITLE
Suggestion for method 'from'

### ISSUE THREAD

**Issue by qwang07** [tgriesser/knex#2232]
I try to create the following query:
```
  => UPDATE users SET password = 'new password'
  -> FROM contacts
  -> WHERE users.contactId = contact.id AND users.username = 'username'
  -> RETURNING contacts.something
  // e.g. knex.table('users').update({password: 'new password'}).from('contacts')...
```
The value in 'from' method will always replace the value in 'table' method. By now, I can only try to use knex.raw method to rewrite the whole query. Is there any better way to achieve this?

**Comment by elhigu** [comment]
Duplicate e.g. https://github.com/tgriesser/knex/issues/557
