### ISSUE TITLE
Should .first() return null on empty result set?

### ISSUE THREAD

**Issue by jtlapp** [tgriesser/knex#2240]
I'm using `.first()` to reduce the amount of code I write, so I'm not having to pull the first element out of an array. I think that's what it's for.

However, if the result set is empty, `.first()` returns an undefined value. If I weren't using the `.first()` shortcut, I'd be checking length before trying to pull a value, and I'd never intentionally end up with a variable having an undefined value.

This may simply be a bias of my Java background, but I would never want to use an undefined value to communicate information. For me, undefined means someone forgot to do something.

Given how easy Javascript makes it to test for an undefined value, I don't see that it's necessary to change this. However, I would have preferred getting `null` instead. The undefined value initially had me thinking that something was wrong; I intuitively expected `null`.

The change might break code that depends on the undefined value, though.

Regardless, it might be good to document the expected behavior.

**Comment by jtlapp** [comment]
Maybe we should just add a `.firstOrNull()` method to the query builder to satisfy stooges like me. No one's code gets broken.

**Comment by jtlapp** [comment]
Here's my stopgap solution:

```javascript

class ExtendedModel extends Objection.Model
{
    static get QueryBuilder() {
        return ExtendedQueryBuilder;
    }
}

class ExtendedQueryBuilder extends Objection.QueryBuilder
{
    firstOrNull() {
        return super.first().then((row) => {
            return (row === undefined ? null : row);
        });
    }
}

module.exports = ExtendedModel;
```

**Comment by richraid21** [comment]
Just to expand on this discussion, the logic resulting in the undefined is [located in the dialect](https://github.com/tgriesser/knex/blob/b5d93f10b1a96c47681f5e08a03d79b10a5fb226/src/dialects/postgres/index.js#L213) `processResponse` function.

**Comment by jtlapp** [comment]
I'm now thinking that because queries can return individual values, it may sometimes be important to distinguish between whether a `null` was returned or no value at all.

It seems that what I need is just a convenience method for reinterpreting undefineds as nulls.

What about just adding a `.orNull()` method for this purpose? That way my app never has to traffic in undefineds.

**Comment by jtlapp** [comment]
After [this discussion on objection.js](https://github.com/Vincit/objection.js/issues/520), I've decided to close this issue. It is necessary that `knex` return an indication that there is no result (even no `null` result), and `undefined` works well for this purpose. I just personally prefer `undefined` to mean something is wrong and can rely on an `objection.js` extension.

**Comment by hassenc** [comment]
Why doesn't knex throw an Error in this case ? (.first() query on empty result)
