### ISSUE TITLE
migrations do not run in a transaction

### ISSUE THREAD

**Issue by capaj** [tgriesser/knex#2244]
I have issues with migrations- using knex 0.13 when I have errors in my transactions, the changes are not reverted and my DB is left in wrong state. I will try to isolate this and create a reproduction repo. Just creating this issue to not forget.

**Comment by elhigu** [comment]
Which DB are you using? Remember that some of the BDs has implicit commits when schema is changed.

**Comment by capaj** [comment]
Right. Thanks. Using MySQL so yes. I need to push my boss to sanction the transition to postgre.
