### ISSUE TITLE
Transaction at lambda

### ISSUE THREAD

**Issue by holiday27** [tgriesser/knex#2245]
I have been trying to use Transactions() at serverless architecture (AWS - Lambda), the Transactions are hanging my code to continue. Testing locally it works, but when i deploy to Lambda it just BEGIN transaction and it stops.

The serverless configurations looks ok, i have other services running at the same config using same database. So maybe if someone has observe the same error or already knew about this, could please help me ?

**Comment by elhigu** [comment]
Cannot reproduce. Also there is no reason why transactions wouldn't work with lambda.

Try to minimize your code running in lambda until you can get some transactions to work, after that it should be obvious to spot why your code doesn't work there correctly.

Please also check out other issues about lambda usage from here and from stackoverflow.
