### ISSUE TITLE
Timout while acquiring connection on high traffic

### ISSUE THREAD

**Issue by ammar08429** [tgriesser/knex#2246]
Hi,

I am trying to do load test on our application, when we try to do that and when we send many users at a time, the knex with in the application fails, and keeps throwing the following error
```
Knex:warning - Pool2 - Error: ResourceRequest aborted: Knex: Timeout acquiring a connection.
Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
```
We check server side, mysql max allowed connection is 1362 and server used only 64 connections, there are still free connections yet knex throws this error.
This is my Config file
```
module.exports = {
  production: {
    client: 'mysql',
    connection: {
      host: process.env.DB_HOST,
      port: process.env.DB_PORT,
      user: process.env.DB_USER,
      password: process.env.DB_PASS,
      database: process.env.DB_NAME,
    },
    pool: {
      max: 7,
      min: 1
    }
  }
}
```

I really need help on this, that why is it failing for hight traffic and how can i solve it?

**Comment by elhigu** [comment]
Maybe you could make pool max size to bigger, since your knex pool has only 7 allowed connections. Also check that you are not opening any long running transactions, because transaction will reserve one connection to it until commit / rollback. 

Try to isolate which routes are causing pool to fill up. Since this is not really a bug / feature request I'll close this already.

**Comment by ammar08429** [comment]
We are not using transaction at all, only simple read write queries, I tried increasing max connection to 1000 and the started getting new error 
`ER_CON_COUNT_ERROR: Too many connections`

**Comment by elhigu** [comment]
That latter error is coming from database, that there are all connection slots used. Are you running multiple processes connecting to DB? Judging from latter connection counts I would have guessed something like 8-10 knex pools were connecting there. 

Maybe you are also using knex some strange way in case if you are running only 1 node process. As a adhoc solution you could try to lower pool limit to 100 connections.

Also if you are doing simple read / write queries, you shouldn't have this kind of errors unless you are referring with high traffic like 200 request / sec, or you are having very much data in your DB which causes inserts to get slow or bad indexes.

Its hard to say anything specific without knowing what we are dealing with.
