### ISSUE TITLE
Knex stopped executing query, returning builder

### ISSUE THREAD

**Issue by xiguang182** [tgriesser/knex#2248]
Returning Builder object. Any hint what causes this?

It returns a builder object like this:
`Builder {
  client:
   Client_MySQL {
     config:
      { client: 'mysql',
        connection: [Object],
        pool: [Object],
        migrations: [Object] },
     connectionSettings:
      { database: 'skeleton',
        user: 'skeleton',
        password: 'skeleton',
        port: 3306,
        host: undefined },
     driver:
      { createConnection: [Function: createConnection],
        createPool: [Function: createPool],
        createPoolCluster: [Function: createPoolCluster],
        createQuery: [Function: createQuery],
        escape: [Function: escape],
        escapeId: [Function: escapeId],
        format: [Function: format] },
     __cid: 'client0',
     pool:
      Pool {
        _factory: [Object],
        _inUseObjects: [],
        _draining: false,
        _waitingClients: [Object],
        _availableObjects: [],
        _asyncTestObjects: [],
        _count: 0,
        _removeIdleTimer: null,
        _removeIdleScheduled: false },
     valueForUndefined:
      Raw {
        client: [Circular],
        sql: 'DEFAULT',
        bindings: undefined,
        _wrappedBefore: undefined,
        _wrappedAfter: undefined,
        _debug: undefined },
     _events:
      { start: [Function],
        query: [Function],
        'query-error': [Function],
        'query-response': [Function] },
     _eventsCount: 4,
     makeKnex: [Function: makeKnex] },
  and: [Circular],
  _single: { table: 'team_registration', only: false },
  _statements: [],
  _method: 'select',
  _debug: undefined,
  _joinFlag: 'inner',
  _boolFlag: 'and',
  _notFlag: false }`

**Comment by richraid21** [comment]
Please include your code that resulted in this output.

**Comment by xiguang182** [comment]
`exports.getTeamsByTournament = (tournamentID) => {
  return global.knex('team_registration').select();
};`

**Comment by xiguang182** [comment]
Nvm, I got it. The promise has not been fulfilled when I tried to check the resolve. Please close this.
