### ISSUE TITLE
Read Write Replica Delay

### ISSUE THREAD

**Issue by ammar08429** [tgriesser/knex#2250]
Hi, 
I am trying u use mysql read write replica, i created 2 connection the knex config file, and i am using the read configuration for read queries and write configuration for write queries,
The problem is that the read replica of mysql server are updated by the master server (which handles write queries) in 20ms, so if we do read immediately after write we dont get the new data there.
I would like to know if you have a field in knex configuration where we can specify the amount of delate we need before u fire the callback of the query, this way we can add delay in our write connection and solve this problem.

```
production: {
    client: 'mysql',
//this connection is used for command line
    connection: {
      host: process.env.DB_HOST_WRITE,
      port: process.env.DB_PORT_WRITE,
      user: process.env.DB_USER_WRITE,
      password: process.env.DB_PASS_WRITE,
      database: 'dbname'
    },
//this connection is used for write queries
    write_connection: {
      host: process.env.DB_HOST_WRITE,
      port: process.env.DB_PORT_WRITE,
      user: process.env.DB_USER_WRITE,
      password: process.env.DB_PASS_WRITE,
      database: 'dbname'
//if we can add a delay here
    },
//this connection is used for read queries
    read_connection: {
      host: process.env.DB_HOST_READ,
      port: process.env.DB_PORT_READ,
      user: process.env.DB_USER_READ,
      password: process.env.DB_PASS_READ,
      database: 'dbname'
    },
    pool: {
      max: 100,
      min: 1
    }
  }
```

**Comment by elhigu** [comment]
Could you provide an example of the code using multiple pools showing the place where you would like to introduce the new delay? Or do you mean that you would like to delay all the reads after each write operation?

**Comment by ammar08429** [comment]
lets suppose i update a table and then want to read from it
So when i update using the write connection and then try to read the same table just after update it wont give me the latest data, as it will take 100ms for the master mysql server to replicate the changes over all the read replica for the same database

So what i would like to have it if we can define a delay in calling the callback after write operation , so that we call the read function after 100ms to get the latest data.

So yes i mean to delay all the reads after each write operation, so if we can have it in knex library as a support for multiple connection for read write replica of mysql it will be better.
I know we can have it in our application logic add a timeout in asCallBack function of knex library, but we have 15 microservices and changing in all of them wont be possible

**Comment by elhigu** [comment]
Without knowing more about the setup, I'm sorry that I might sound rude now, but this sounds like a really bad idea in multiple ways (trying to create pseudo sychronous replication setup with application side code). 

You will get  either non-robust functionality, when some times you get  uptodate data and sometimes not. Or you'll have to use extremely conservative delays, which blocks all the reads after every update. I would just suggest to configure replication setup to work in synchronous manner and that way DB know when to lock (it slows down writes a bit, but it sounds like a lot loss of a problem). Also this effectively limits your write speed to < 10 writes per second or those delays will block all your DB reads...

You could implement functionality you need for example with rxjs, that always before making query you'll pass them through rxjs, pipe which always waits your delay in case of write operation is being done... knex doesn't help you much with this.
