### ISSUE TITLE
? not escaped in raw queries

### ISSUE THREAD

**Issue by indianscout** [tgriesser/knex#2254]
According the docs (http://knexjs.org/#Raw):
Sometimes you may need to use a raw expression in a query. Raw query object may be injected pretty much anywhere you want, and using proper bindings can ensure your values are escaped properly, preventing SQL-injection attacks.

But:
```
knex.raw('g.title ILIKE ?', [`%${searchQuery}%`]);
```
returns a query fragment like:
```
g.title ILIKE '%http://localhost:8000/guideline/100001/edit?%'
```
Why is **_?_** not escaped properly?
I am expecting something like:
```
g.title ILIKE '%http://localhost:8000/guideline/100001/edit\?%'
```

Is it a bug or am I doing something wrong here?

**Comment by elhigu** [comment]
I suppose you are using `.toString()` to generate your fragments. You shouldn't do that, but use `.toSQL()` which keeps values and sql template separate.

**Comment by indianscout** [comment]
@elhigu: I've worked out the constelation wich fails in my case.
I've prepared a simple example which reproduces this problem:
```
db.select()
        .from('details AS d')
        .joinRaw(
            `INNER JOIN (
                ${db.raw('select * from details where title ilike ?', ['bla\?'])}
            ) AS sub
            ON d."id" = sub."id"`
        )
        .limit(10)
```

This is messing up the query:
```
SELECT *
FROM "details" AS "d"
INNER JOIN (
	SELECT *
	FROM details
	WHERE title ilike 'bla' 10 ''
) AS sub ON d."id" = sub."id" limit ?
```

I actually expect something like:
```
SELECT *
FROM "details" AS "d"
INNER JOIN (
	SELECT *
	FROM details
	WHERE itle ilike 'bla?'
) AS sub ON d."id" = sub."id" limit 10
```

**Comment by elhigu** [comment]
You are using query -> string converision in your raw call.

```
knex('details AS d')
    .joinRaw(
      'INNER JOIN (?) AS sub ON d."id" = sub."id"', 
      [ db.raw('select * from details where title ilike ?', ['bla?']) ]
    )
    .limit(10)
```

**Comment by indianscout** [comment]
Works perfect THX
