### ISSUE TITLE
Getting UTC Dates

### ISSUE THREAD

**Issue by crowecawcaw** [tgriesser/knex#2260]
I'm running some queries using knex where I'm retrieving dates as UTC epoch time. My production database is MySQL but I'm running tests in a SQLite database in memory. Currently, to get the dates in epoch seconds, I'm using knex.raw like this for MySQL:

```
knex.raw(`UNIX_TIMESTAMP(??) as 'time'`, 'table.time'),
```
Unfortunately, this doesn't also work for SQLite which needs a different raw query. Is there a way to get epoch seconds that's compatible between databases? If not, would adding a helper function to get dates as epoch seconds be appropriate?

**Comment by elhigu** [comment]
With sqlite its done with `SELECT strftime('%s', 'now');`

With mysql `SELECT UNIX_TIMESTAMP(yourfield)`

If one likes to add asEpoch() method to knex helper function in `knex.fn.*` it would be fine.

If you just like to do it locally in your repo, write your own helper function, which is configured to create different code depending, which DB are you using as backend (or use mysql also for testing to be able to use also mysql's special features, which are not available in sqlite + being able to test that transactions etc. are working as expected).

ps. Not knowing your case, but it is rarely necessary to treat datetimes as epoch timestamps.
