### ISSUE TITLE
how to update specific element in JSONB column

### ISSUE THREAD

**Issue by zerosand1s** [tgriesser/knex#2264]
hi, is there a way to update a specific element in PostgreSQL JSONB column? 
I have a jsonb column like {lat: value, lon: value}. I want to change either value at a time but I am not sure how I can do this. I tried using ```jsonb_set()``` method but could not achieve what I wanted.

**Comment by richraid21** [comment]
I looked around, it doesn't seem like there is a matching `updateRaw` like there is a `whereRaw` or `joinRaw`, etc. You will have to use a raw query I think.

**Comment by zerosand1s** [comment]
@richraid21 Could you please help me out on how I can write this raw query?

**Comment by elhigu** [comment]
AFAIK only knex based thing that supports writing to and extracting data from postgresql jsonb columns is objection.js ORM.

With plain knex you need to use raw to write references:

```
knex('table').update({
  jsonbColumn: knex.raw('jsonb_set(??, 'lat', ?)', ['jsonbColumn', newLatValue]);
})
```
You can check generated SQL here https://runkit.com/embed/44ifdhzxejf1

**Comment by markairwallex** [comment]
i just find a way to update all the data column

**Comment by elhigu** [comment]
@markairwallex in my last comment is an example how to update single value. You need to use .raw and write postgresql specific SQL code for that update.

Locking conversation to prevent answer from being lost in extra comments. If there are more problems related to this, open new issue or write a question to stackoverflow.
