### ISSUE TITLE
Trying to acquire the same connection after a timeout.

### ISSUE THREAD

**Issue by b2rsp** [tgriesser/knex#2266]
Hi,

I have the version of Knex *12.6* and i am trying to connect to MSSQL database with the *acquireConnectionTimeout* set to 2 minutes when this situation occurred. I made a query knowing that it would give me a timeout and the my general error handling caught the error. But the library kept on emiting an error every 2 minutes (the same values as *acquireConnectionTimeout*) . I have locked at the source of   and there is this code
```
acquireConnection() {
    return new Promise((resolver, rejecter) => {
      if (!this.pool) {
        return rejecter(new Error('Unable to acquire a connection'))
      }
      let wasRejected = false
      const t = setTimeout(() => {
        wasRejected = true
        rejecter(new Promise.TimeoutError(
          'Knex: Timeout acquiring a connection. The pool is probably full. ' +
          'Are you missing a .transacting(trx) call?'
        ))
      }, this.config.acquireConnectionTimeout || 60000)
      this.pool.acquire((err, connection) => {
        clearTimeout(t)
        if (err) {
          return rejecter(err)
        }
        if (wasRejected) {
          this.pool.release(connection)
        } else {
          debug('acquired connection from pool: %s', connection.__knexUid)
          resolver(connection)
        }
      })
    })
```

That created a timeout that reject the promise after 2 minutes (`acquireConnectionTimeout`) but i don't understand why keep on logging every 2 minutes. Is trying to acquire again a new connection after it fails acquire that connection?

**Comment by elhigu** [comment]
Does this happen with other databases for example postgresql? and could you provide complete test code to be able to reproduce the problem? Have you tried 0.13 (0.14 is also coming pretty soon, that is using newer version of connection pool)?

**Comment by b2rsp** [comment]
There was an application bug that was initializing the knex several times.

Thanks for the help, and i close this. :)
