### ISSUE TITLE
Pass context to wrapIdentifier and postProcessResponse hooks

### ISSUE THREAD

**Issue by joelmukuthu** [tgriesser/knex#2268]
`wrapIdentifier` will be called with a string for every identifier, be it a table-name, column-name, from a query-builder instance or even a schema-builder instance.

`postProcessReponse` will be called with any data coming from the database, be it from a `SELECT` query or queries with `RETURNING`  clauses. 

For both hooks, a little context is needed. Also, ideally the context should be able to be configurable by the user, for example something like:

```js
knex('foo')
  .hookContext({ wrapIdentifier: someObject, postProcessResponse: someOtherObject  })
  .select();

// and the hooks would be of some form like:

knex({
  client: 'pg',
  connection: /* ... */,
  wrapIdentifier(identifier, wrap, someObject) {
  },
  postProcessResponse(data, someOtherObject) {
  }
})
```

For more info check the discussion here https://github.com/tgriesser/knex/pull/2261. 

**NOTE:** These hooks are not yet released at the time of this writing.

**Comment by elhigu** [comment]
Probably single context object is enough, but yeah something like this would be good to have. The same context could be also passed to query events.

**Comment by richraid21** [comment]
So something like 
```
knex('table')
.hookContext(object)
.select();
```

that would then get propagated to `wrapIdentifier`, `postProcessResponse`, and events? 

I agree that we probably don't need keyed properties since you could just key your own.

**Comment by joelmukuthu** [comment]
I'd like to work on a PR for this, can I proceed with the strategy proposed by @richraid21? (asking because this is still tagged with the "discussion" label)

**Comment by elhigu** [comment]
I think this is good to go for PR.

Remember to test that when query is cloned / used in transaction that context will be also passed on in those cases and maybe also `.hookContext()` without parameters should act as getter that returns context of the query (so that one can actually merge more stuff to context).
