### ISSUE TITLE
Any chance of using Knex on the browser/client side? (feature question)

### ISSUE THREAD

**Issue by crumhorn** [tgriesser/knex#2270]
We're currently using Knex & Objection to load data from a MSSQL server in an Angular 2 application using GraphQL and Apollo as our transfer libraries (essentially everything is transferred as JSON). 

Everything on the Node.js side works fine, however, as GraphQL transfers everything over the wire as JSON the object itself is of course lost, and to deserialize it back on the client we would be calling the constructor of the object and then call $parseJson(...) to get it back to what it was.

The "problem" is that Knex is built for running on the client side of things, and thus when it tries to import the necessary references;

`export class OurClass extends Model {`
with the import:
`import {Model} from 'objection';`

The whole thing fails with a stack trace to ansi-styles and console coloring (hence why I ask in the Knex repo rather than Objection as the 3 steps after Objection are Knex related);

```
zone.js:392 Error: module is not defined
  Evaluating http://localhost:3000/node_modules/ansi-styles/index.js
  Evaluating http://localhost:3000/node_modules/chalk/index.js
  Evaluating http://localhost:3000/node_modules/knex/lib/helpers.js
  Evaluating http://localhost:3000/node_modules/knex/lib/raw.js
  Evaluating http://localhost:3000/node_modules/knex/lib/query/builder.js
  Evaluating http://localhost:3000/node_modules/objection/lib/utils/knexUtils.js
  Evaluating http://localhost:3000/node_modules/objection/lib/queryBuilder/QueryBuilderBase.js
  Evaluating http://localhost:3000/node_modules/objection/lib/queryBuilder/QueryBuilder.js
  Evaluating http://localhost:3000/node_modules/objection/lib/model/Model.js
  Evaluating http://localhost:3000/node_modules/objection/lib/objection.js
  Evaluating http://localhost:3000/app/app/model/entities/LegalEntity.js
  Evaluating http://localhost:3000/app/app/app.component.js
  Evaluating http://localhost:3000/app/app/app.module.js
  Evaluating http://localhost:3000/app/main.js
```

The thing I'm trying to accomplish by re-using knex/objection on the client it to avoid having to generate a whole set of database model objects that don't contain the imports to Knex/Objection (so the client & server share the same data model objects), and then having to implement our own deserializer to get it back into a Javascript class Object on the client.

Hope that wasn't too confusing a question.
Thanks in advance!

**Comment by elhigu** [comment]
This is not supported and as usual if you try to run node code in browser, you need to pack all the dependencies with the compiled lib and face those libs, which are not supported by browser (e.g. ones that tries to make tcp connection to database etc.).

Afaik no-one has ever tried to pack objection to be able to be used from browser. This is not really related to knex. Maybe in stackoverflow someone can help you to learn how to port node software so that it can be ran in browser. Also try to read knex issues which are mentioning webpack.
