### ISSUE TITLE
How can I use nextVal on knex?

### ISSUE THREAD

**Issue by slim-hmidi** [tgriesser/knex#2271]
I have a database filled with 400 rows and I want to add some more rows, when I tried to use `knex('tableName').insert({name: 'name', lastName: 'lastName', address: 'Address'}` I got an error such as `duplicated primary key constraint`.
Does Knex recognize `nextVal` to add an element at the end of the table?

**Comment by elhigu** [comment]
You have to update your databases id sequence to match the amount of data that you added to table (with hardcoded ids I suppose). This has nothing to do with knex. It depends on database how it can be done.

**Comment by slim-hmidi** [comment]
@elhigu On the seed file I hardcod the id of each row but when I want to insert a new element I got an error. I think that it can't add the new element at the end of the database.

**Comment by elhigu** [comment]
There is no such thing as "end of the database" there is only id sequence that is used to generate id's for new rows that doesn't have id field give. 

If you have hardcoded id:s in seed, it means that database will not call nextval to get the id for each row -> so table's id sequence remains in  initial value (1). So when next time you are inserting row, where you haven't given the id explicitly, DB gets the id from the id sequence and it will conflict.
