### ISSUE TITLE
Postgres arrays are retrieved as objects

### ISSUE THREAD

**Issue by roytz** [tgriesser/knex#2276]
I have a table (in Postgres) with a field of type `TEXT[]` but when I use knex (simple select query) I get that field as an object instead of an array.
I read [this](https://github.com/tgriesser/knex/issues/569) issue but it doesn't give an answer for that.

**Comment by roytz** [comment]
Thanks @richraid21 , sorry I wasn't specific enough
I'm creating my whole db using `knex.raw` and passing it a script I wrote.
I the column I referring to isn't actually a `TEXT[]` but an enum type I created.
I created a type using `CREATE TYPE some_type AS ENUM ('text1', 'text2', 'text3')` and then created a table with a column of type `some_type[]`.
When returning it using knex I get an object instead of array.

**Comment by richraid21** [comment]
Ok so I confirmed the error, but this is actually a problem with the underlying postgres driver that Knex uses, [pg](https://github.com/brianc/node-postgres). You will have to bring it up there and then Knex can upgrade when the bug gets fixed. 

Heres the reproduced example using just `pg` driver

```javascript
const { Client } = require('pg')

const config = {
    // ommitted for public post
}

/* SQL SETUP

CREATE TYPE mood AS ENUM ('sad', 'ok', 'happy');

CREATE TABLE _person (
    name text,
    current_mood mood
);

INSERT INTO person VALUES ('Rich', ARRAY['happy', 'ok']::mood[]);

*/

async function go() {
    const client = new Client(config)
    
    await client.connect()
    
    const result = await client.query('SELECT * FROM _person')
    
    console.log(result.rows)
    // Returns [ anonymous { name: 'Rich', state: '{sad,happy}' } ]

    await client.end()
}

go()
```

**Comment by shai32** [comment]
Thanks
https://github.com/brianc/node-postgres/issues/1479

**Comment by elhigu** [comment]
I suppose there is nothing to do in knex side to fix this, closing.

**Comment by roytz** [comment]
Thanks @richraid21
