### ISSUE TITLE
MySQL BIGINT

### ISSUE THREAD

**Issue by nanom1t** [tgriesser/knex#2277]
Hi,

I'm using BIGINT (64 bits) type for IDs in MySQL database. I know that JavaScript does not support 64-bit numbers, so I'm also using [Long.js](https://github.com/dcodeIO/long.js) package in my app.

Does knex support 64-bit values? How can I configure it?

For example, I have MySQL table with two fields: id (BIGINT) and name (VARCHAR). I just want to execute queries with BIGINT fields and get correct results:
```
SELECT * FROM table WHERE 1;
UPDATE table SET name='John' WHERE id = '18446744073709551615';
```
Thanks

**Comment by elhigu** [comment]
Check from your database driver documentation how to work with 64bit integers. There is no special support for it made in knex. Usually drivers sends and receives them as strings. 

```
knex('table').where(knex.raw('1'));
await knex('table').update({ name: 'John'}).where('id', '18446744073709551615');
```
