### ISSUE TITLE
Using SQLite extensions

### ISSUE THREAD

**Issue by emirotin** [tgriesser/knex#2279]
SQLite does support runtime-loadable extensions. They can add functions (like JSON support) or change the behavior of the engine.
Many of them are per-session, i.e. are unloaded when the connection is closed.

Loading extensions is supported by the sqlite3 client: https://github.com/mapbox/node-sqlite3/wiki/Extensions

Would it be possible to make knex support them?

I could use sqlite3 directly but here's my use-case where I'm not sure how to proceed:
- I'm running lots of operations inside of single transaction that fetch the data and put it into the DB
- then I'd like to drop and recreate the search index table which relies on FTS5 extension and the custom Snowball stemmer
- and then I need to populate the search index by inserting the records from the table filled in step 1

Because the per-session nature of the extensions it looks the only way for me now is to commit the transaction and then run the index-related stuff separately by using the sqlite3 client directly. This is kinda OK but can leave the DB in inconsistent state due to transaction being committed in the middle of the process.

Or am I missing something?

More info about the extensions: https://sqlite.org/loadext.html

**Comment by elhigu** [comment]
Can you setup loading extensions in afterCreate callback http://knexjs.org/#Installation-pooling ?

That is called to every DB connection just after connection has been created. Usually all the per-session related stuff is done there.

**Comment by emirotin** [comment]
Oh, didn't find it in the docs, thanks, will try and let you know how it goes. There's a slight downside of tit being called on each connection when I really only need it for the final phase, but that sounds like not that big deal, at least before I really see it slowing the things down.

**Comment by elhigu** [comment]
Yeah it would be nice to be able to get dedicated connections from knex without need to fake them with transactions. I hope I get time to implement that at some point next year...

**Comment by emirotin** [comment]
Hm, interesting enough I get segfault when using this method + transaction around the "INSERT SELECT" statement (raw query), but not when doing the same query directly on the sqlite driver myself.
It depends on the number of records being transferred, the total number of records I have is 300K+ and it doesn't fail if I limit the number of them to something like 10K.

**Comment by elhigu** [comment]
I think we cannot help more with this issue, closing. Feel free to keep on discussion though.
