### ISSUE TITLE
When is the next release?

### ISSUE THREAD

**Issue by mmiller42** [tgriesser/knex#2280]
I'm curious, as some bugs have been fixed (notably, I came here to report a bug where `NOT ILIKE` is not a supported comparison operator in `where` queries). Looks like that was fixed in August, but there haven't been any releases since April?

I understand some features may still be in development, but `master` is stable, no? Could you at least release a patch with bugfixes of this kind?

**Comment by elhigu** [comment]
I'll be doing 0.14 release in this or next month. I'm not going to  put my time to patch release, but if someone likes to do in it is ok. Currently there are so many breaking changes in that it might be difficult or might be easy...
