### ISSUE TITLE
"\u0000" in json will lead to invalid message format error for postgresql builder

### ISSUE THREAD

**Issue by ahmesaab** [tgriesser/knex#2284]
The knex query builder doesn't escape the null character. The query string generated from the builder will contain the null characters that will cause the postgresql to fire an error.

**Comment by elhigu** [comment]
Cannot reproduce https://runkit.com/embed/6v3ccxjyhj3t please add an example that demonstrate the problem.

**Comment by Param-Harrison** [comment]
@elhigu 
You can reproduce it only using null character (`\0`).
In your example, it is not a null character with length 1, instead, you used a string (`\u0000`) of length 6. That's why it isn't failing. 
cc @ahmesaab

**Comment by elhigu** [comment]
Looks like pg driver issue. That string is passed directly there.

**Comment by jan-osch** [comment]
When user input is serialized as JSON and contains `\u0000` it causes the following exception when passed to the pg driver.
`Invalid byte sequence for encoding "UTF8": 0x00`

What is your recommended way of dealing with that?  Should I sanitize all the user-inputs on application level?

**Comment by elhigu** [comment]
Maybe you should ask that in pg driver issues? Knex will not do any processing to your string inputs.
