### ISSUE TITLE
Support for sqlite3-offline

### ISSUE THREAD

**Issue by hetsch** [tgriesser/knex#2285]
Hi,

while trying to compile sqlite3 for my electron app (and miserably failing as many others ...), I stumbled over an issue where a dude provides prebuilt binaries for sqlite3 and offline app usage. The original thread can be found at https://github.com/mapbox/node-sqlite3/issues/840 and his repository is located at https://github.com/DenisCarriere/sqlite3-offline.

I wanted to ask if there is any chance to support his package or if you can think of any workaround to get it running with knex.

Thank's!

**Comment by elhigu** [comment]
You can hack it like this (in client arg one can actually give the Dialect object that knex should use):

```js
require('sqlite3-offline');

const Knex = require("knex");

const Dialect = require(`knex/lib/dialects/sqlite3/index.js`);
Dialect.prototype._driver = () => require('sqlite3-offline');

const knex = Knex({
  client: Dialect,
  connection: ':memory:'
});

console.log(
  knex.select(knex.raw(1)).toSQL()
);

await knex.schema.createTable('fooobar', (t) => {
  t.bigincrements('id');
  t.string('data');
});
await knex('fooobar').insert({ data: 'nomnom' });

console.log("Gimme all the data:", await knex('fooobar'));
```

https://runkit.com/embed/90b3cpyr4jh2

**Comment by hetsch** [comment]
Yes! Thank you for quick response. This was exactly what I needed!
