### ISSUE TITLE
MSSQL Depcreation Warning

### ISSUE THREAD

**Issue by mgarf** [tgriesser/knex#2286]
Using MSSQL with Latest Knex and Azure SQL Database. When I run knex migrate:latest i get the following error: 

(node:5416) [DEP0064] DeprecationWarning: tls.createSecurePair() is deprecated. Please use tls.Socket instead. TimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?

Still investigating if its from the connection side but is it possible the issue is this createSecurePair issue?

**Comment by maxhammad** [comment]
This is a [known issue](https://github.com/tediousjs/tedious/issues/515) relating to the `tedious` module that `mssql` uses by default. If you are on Windows, you have the option to switch the default TDS driver in the `mssql` module with the Microsoft / Contributors Node V8 Driver for Node.js for SQL Server driver, which `mssql` [now supports](https://github.com/patriksimek/node-mssql#microsoft--contributors-node-v8-driver-for-nodejs-for-sql-server).

**Comment by cbaron** [comment]
@mgarf -- what was your issue?
