### ISSUE TITLE
Possible problem with SQL generation on correlated subquery

### ISSUE THREAD

**Issue by pavoni** [tgriesser/knex#2292]
I'm trying to do a correlated subquery using `whereNotExists` and I'm seeing some surprising SQL - at least to me!

This is a simplified example
```
    return knex("table1")
    .whereNotExists(
        knex.select("*").from("table2")
        .where("table2.fid", "=", "table1.id")
    ).debug()
```
This generates:
```
{ method: 'select',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [ 'table1.id' ],
  __knexQueryUid: '13641d39-9db3-494b-8f14-fbca03b9daac',
  sql: 'select * from "table1" where not exists (select * from "table2" where "table2"."fid" = ?)' }
```
Which seems to expect a binding for `table.id` and not the subquery I was expecting.

What I was expecting is what I get from  
```
    return knex("table1")
    .whereNotExists(
        knex("table2").where(knex.raw("table2.fid = table1.id"))
    ).debug()
```
Which is 
```
{ method: 'select',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [],
  __knexQueryUid: '54dfa26b-2e98-46fb-b8ae-a0cde6a33d0c',
  sql: 'select * from "table1" where not exists (select * from "table2" where table2.fid = table1.id)' }
```

I also tried:
```
    return knex("table1")
    .whereNotExists((qb) => {
        qb.select("*").from("table2")
        .where("table2.fid", "=", "table1.id");
    })
    .debug()
```

which also gives the same SQL with a binding for `table.id`
```
{ method: 'select',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [ 'table1.id' ],
  __knexQueryUid: 'ed93d79c-4def-44e4-91aa-765a56b52c6c',
  sql: 'select * from "table1" where not exists (select * from "table2" where "table2"."fid" = ?)' }
```

This is on version `0.13.0`

Am I doing the wrong thing? Any thoughts from the experts?

**Comment by wubzz** [comment]
@pavoni You can't use the syntax "table.column" as the `value` in regular `.where*` builder functions, because knex can't possibly know if you are trying to match `"table"."column"` or the actual string `table1.id`, thus knex considers it a regular binding and it is escaped and treated as such.

This works with `raw` as you already figured out, because that is raw strings.

Using `knex("table2").where('table2.fid', '=', knex.raw("table1.id"))` should also work if I'm not mistaken.

**Comment by pavoni** [comment]
Got it - what you suggest works - thanks very much. And thanks for the super quick answer!
