### ISSUE TITLE
Why doesn't knex support all the bluebird methods?

### ISSUE THREAD

**Issue by JemiloII** [tgriesser/knex#2293]
It's been quite frustrating to run into errors or having to create bluebird wrappers around knex promises because they do not support the full set of bluebird methods. some, tap, tapCatch, etc... Why aren't these supported?

**Comment by richraid21** [comment]
I'm not really sure I understand what you mean. 

```
const Promise = require('bluebird')
const config = require('./knexfile')
const knex = require('../knex/lib')(config)

Promise.some([
    knex('_test').select('id'),
    knex('_test').first(),
    knex('_test').first('names')
], 2).spread((first, second) => {
    console.log('some-first', first)
    console.log('some-second', second)
});

knex('_test').select()
    .tap((res) => {
        console.log('tap', res)
    })
    .tapCatch((err) => {
        console.log('tapCatch', err)
    })
    .then((res) => {
        console.log('then', res)
    })

knex.destroy()
```
These all work.

**Comment by JemiloII** [comment]
I see now. I was doing ->

`knex('table').select('*').then().tapCatch();` I'll try it without the then.

**Comment by elhigu** [comment]
Because knex should migrate away from the bluebird dependency eventually.

**Comment by JemiloII** [comment]
Why should it? ES6 Promises are not as robust as bluebird...

**Comment by mattbrunetti** [comment]
@JemiloII But they are standard. And with user-land packages on npm and es-next language features, we don't really need bluebird's extra features. See this https://github.com/sindresorhus/promise-fun

**Comment by elhigu** [comment]
@JemiloII ES6 promises are robust and I would be surprised if node implementation performance, isn't already in par with bluebird. Anyways promise performance in `knex` with native promises won't be a problem.  

Also when one declares async functions, they will implicitly create standard promises to return values. So when knex is returning bluebird and async functions standard promises it might et confusing to know which methods will be available (not to mention typings problems of having multiple promise types if one uses typescript). 

Nowadays I just import Bluebird separately when I need those special methods and use it only those places where I really need those methods (not very often).

Anyways mainly its all about getting rid of unnecessary dependency and let people who still likes to use bluebird to use it explicitly.

**Comment by JemiloII** [comment]
I still find it unexpected to have to run:

```js
knex('_test').select()
    .tap((res) => {
        console.log('tap', res)
    })
    .then((res) => {
        console.log('then', res)
    })
    .map((res) => {
        console.log('map', res)
    });
```
Than to run:

```js
knex('_test').select()
    .then((res) => {
        console.log('then', res)
    })
    .map((res) => {
        console.log('map', res)
    });
```
