### ISSUE TITLE
Update the NPM package

### ISSUE THREAD

**Issue by aurium** [tgriesser/knex#2294]
Hi, the `interpret` version dependence was updated on `package.json` to load the new coffee transpiler. It will be nice to get it working on the knex package from NPM.

**Comment by elhigu** [comment]
already fixed in master

**Comment by aurium** [comment]
Hi elhigu, i'm new here on knex, what is the rule (or politics) to update the NPM package?

**Comment by elhigu** [comment]
in case if there is major version change, one should check more carefully if the new version is compatible... but mostly just send update PR and if tests pass it should be fine.
