### ISSUE TITLE
Foreign key checks question (MySQL)

### ISSUE THREAD

**Issue by Palisand** [tgriesser/knex#2296]
Why does
```javascript
knex.raw('SET foreign_key_checks = 0')
  .then(() => db.raw('SELECT @@foreign_key_checks'))
  .then(result => console.log(result));
```
output:
```
...{ '@@foreign_key_checks': 1 }...
```
while
```sql
> SET foreign_key_checks = 0;
> SELECT @@foreign_key_checks;
```
in a mysql shell outputs:
```
+----------------------+
| @@foreign_key_checks |
+----------------------+
|                    0 |
+----------------------+
```
?

Shouldn't both be `0`?

I've seen `knex.transaction` used to ensure `foreign_key_checks` remains `0` for the duration of the transaction, but I'd rather not use transactions for this particular case (I don't want a rollback to occur on failure).

**Comment by elhigu** [comment]
You are running 'SET foreign_key_checks = 0' and 'SELECT @@foreign_key_checks' in different connections. So you need transaction to make sure that those queries are executed in the same session. 

Even when you run stuff in transaction it is not obligatory to rollback if some queries are failing. Just end the transaction with `commit` anyways.
