### ISSUE TITLE
How to set DEBUG to analyze information from pool.

### ISSUE THREAD

**Issue by danilohgds** [tgriesser/knex#2299]
Hi all,

My application is having tons of troubles working with knex, I keep getting connection pool errors, despite usage being low:

export function createKnexConnector(): knex {
    return knex({
        client: 'oracledb',
        connection: {
            user: DB_USER,
            password: DB_PASSWORD,
            host: `${DB_HOST}:${DB_PORT}`,
            database: DB_NAME
        },
        fetchAsString: ['number', 'clob'],
        acquireConnectionTimeout: 120000,
        pool: { min: 2, max: 500, idleTimeoutMillis: 15000, evictionRunIntervalMillis: 300000 },
        DEBUG: true,

    } as any);
}

I have tried many settings and even DEBUG true, but I cannot see any info that would help me out.

**Comment by elhigu** [comment]
Have you tried running app with `DEBUG=knex:*` environment variable it should output information about acquiring and releasing connections.

**Comment by danilohgds** [comment]
export function createKnexConnector(): knex {
    return knex({
        client: 'oracledb',
        connection: {
            user: DB_USER,
            password: DB_PASSWORD,
            host: `${DB_HOST}:${DB_PORT}`,
            database: DB_NAME
        },
        fetchAsString: ['number', 'clob'],
        acquireConnectionTimeout: 120000,
        pool: { min: 2, max: 500, idleTimeoutMillis: 15000, evictionRunIntervalMillis: 300000 },
        DEBUG=knex:*

    } as any);
}
It doesnt validate as a correct connection opening, am I doing something wrong ?

**Comment by elhigu** [comment]
It is environment variable, not knex configuration option. You should set it before running your app.
