### ISSUE TITLE
Knex 0.11.9 is not releasing DB connection

### ISSUE THREAD

**Issue by skumar568** [tgriesser/knex#2303]
Hi,

Below is the DB connection configuration that I am using.
const db = knex({
  client: mysql2,
  debug: false,
  acquireConnectionTimeout: 10000,
  connection: {
    host: config.HOST,
    port: config.PORT,
    user: config.USER,
    password: config.PASSWORD,
    database: config.DB_NAME,
    ssl: {
      ca: fs.readFileSync(config.RDS_SSL),
    },
  },
  pool: {
    min: 5,
    max: 50,
    requestTimeout: 100,
    idleTimeout: 600000,
    syncInterval: 300000,
  },
});

After reaching MAX connection, I can see that connections are not releasing even if application is idle for 30 minutes.

Knex:warning - Pool2 - Error: ResourceRequest timed out
  pool2 ResourceRequest: clearing timeout (id=457) +1ms
  pool2 New ResourceRequest (id=458, timeout=100) +905ms
  pool2 Not growing pool: pending=1, to be available=0 +1ms
  pool2 ResourceRequest: rejectTimeout (id=458) +101ms
  pool2 ResourceRequest: reject (id=458) +0ms
  pool2 ResourceRequest: fulfilling with error: ResourceRequest timed out (id=458) +0ms
Knex:warning - Pool2 - Error: ResourceRequest timed out
  pool2 ResourceRequest: clearing timeout (id=458) +1ms
  pool2 sync +3m
  pool2 reap (cur=50, av=0) +1ms
  pool2 sync +5m
  pool2 reap (cur=50, av=0) +1ms
  pool2 sync +5m
  pool2 reap (cur=50, av=0) +0ms
  pool2 sync +5m
  pool2 reap (cur=50, av=0) +0ms
  pool2 sync +5m
  pool2 reap (cur=50, av=0) +0ms
  pool2 sync +5m
  pool2 reap (cur=50, av=0) +0ms
  pool2 sync +5m
  pool2 reap (cur=50, av=0) +0ms
  pool2 sync +5m
  pool2 reap (cur=50, av=0) +0ms

Am I missing anything?

Thanks,
Sanjeev

**Comment by elhigu** [comment]
Try if this still happens with latest knex. Also I don't see from log where connections are aquired / returned to pool.

**Comment by skumar568** [comment]
@elhigu 
I removed acquireConnectionTimeout from connection and requestTimeout, idleTimeout,syncInterval from pool configuration. Issue is still same. Attached more logs as well, 
[knexConnectionPoolLogs.txt](https://github.com/tgriesser/knex/files/1441258/knexConnectionPoolLogs.txt)

**Comment by skumar568** [comment]
@elhigu Also memory was detected in higher versions which was claimed to be fixed in 0.14 which is not available for download. Hence, not upgrading until 0.14 is not available.

**Comment by elhigu** [comment]
Did you see from logs that some connections were acquired but not returned to pool? I dont remember what kind of logs is generated for resource returning. Since you have not had this error before, I suppose that you have bug related to transactions in your app.
