### ISSUE TITLE
Question: Why does `.timestamp()` generate sql with `ON UPDATE CURRENT_TIMESTAMP`

### ISSUE THREAD

**Issue by mateuscb** [tgriesser/knex#2305]
What is the reason for automatically adding the `ON UPDATE CURRENT_TIMESTAMP` when a `table.timestamp()` column is created? It seems that at some point this was brought up (https://github.com/tgriesser/knex/issues/1928), and looks like it made into code? 

If that is the expected behavior, I think we should add it to the documentation. 

On a related note, does `table.datetime()` also add `ON UPDATE CURRENT_TIMESTAMP` ?

**Comment by elhigu** [comment]
It doesn't add automatically it to table timestamp, nor to datetime.

https://runkit.com/embed/rgzmv396whtv

var knex = require("knex")({ client: 'mysql' })

```
knex.schema.createTable('woo', t => {
  t.timestamp('foo');
  t.datetime('bar');
}).toSQL()
```

`create table `woo` (`foo` timestamp, `bar` datetime)`

**Comment by mateuscb** [comment]
@elhigu found the problem: It's expected behavior in MySQL 5.5: 

> With neither DEFAULT CURRENT_TIMESTAMP nor ON UPDATE CURRENT_TIMESTAMP, it is the same as specifying both DEFAULT CURRENT_TIMESTAMP and ON UPDATE CURRENT_TIMESTAMP.

https://dev.mysql.com/doc/refman/5.5/en/timestamp-initialization.html

Thanks for the quick response.

**Comment by elhigu** [comment]
good to know 👍
