### ISSUE TITLE
Pool object not retrievable from knexInstance itself

### ISSUE THREAD

**Issue by danilohgds** [tgriesser/knex#2306]
My app is using knex as follows: 
```

return knex({
       client: 'oracledb',
       connection: {
           user: DB_USER,
           password: DB_PASSWORD,
           host: `${DB_HOST}:${DB_PORT}`,
           database: DB_NAME
       },
       fetchAsString: ['number', 'clob'],
       acquireConnectionTimeout: 120000,
       pool: {
           min: 0,
           max: 30,
           maxRequests: 30,
           idleTimeout: 60000,
           syncInterval: 60000,
           bailAfter: 10000
       }
   } as any);


```

We ran into many issues where the pool is going crazy , creating over 50 clients right off the bat. We wanted to use the pool.stats()  from pool2 library, however I cannot find any way in the documentation to get the pool from a knex object...can you guys help?

**Comment by elhigu** [comment]
Knex uses `generic-pool`. It should be found from `knex.client.pool`. Try to find out, which parts of your app is hogging all the connection and reproduce you problem in small scale. That way you should be able to pinpoint the problem which causes it. 

If you can provide test case where just initializing knex will create many connections (they shouldn't go over pool max, which is 30 in this example though), we can figure out if there is some knex related bug here.
