### ISSUE TITLE
changing order of comparison crashes query

### ISSUE THREAD

**Issue by frsechet** [tgriesser/knex#2307]
I'm using knex 0.13.0, on node 6.11.0, with MySQL 5.6.

Using the below table:
```
CREATE TABLE `table` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `some_val` int(10) unsigned DEFAULT NULL,
  `started_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `ended_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=latin1;
```

The following request:
```
knex.raw(`
    SELECT *
    FROM table
    WHERE started_at > '2010-01-01 00:00:00' AND 'NOW()' > ended_at AND some_val = 42
`)
```
returns the following error: `ER_CANT_AGGREGATE_2COLLATIONS: Illegal mix of collations (utf8_general_ci,COERCIBLE) and (latin1_swedish_ci,NUMERIC) for operation '>'`

Now:
- The query below works in the same exact conditions (only `ended_at < 'NOW()` was switched):
```
SELECT *
FROM table
WHERE started_at > '2010-01-01 00:00:00' AND ended_at < 'NOW()' AND some_val = 42
```
- This one works as well (same as first query, without `AND some_val = 42`):
```
SELECT *
FROM table
WHERE started_at > '2010-01-01 00:00:00' AND 'NOW()' > ended_at
```
- Running the first query directly in some SQL editor (against the same database) works, which leads me to believe it's an issue with knex and not MySQL.

So, it works if I use the "good" query, but I would love to understand why this happens.

**Comment by elhigu** [comment]
That error is coming from db, raw queries are sent directly to driver, so if there is an issue it must be in mysql driver. However im pretty sure its an user error. Maybe your sql client does sanitation or something tonthe query. Try mysql shell client to se if problem shows there too.

**Comment by elhigu** [comment]
Or your sql client might set some collation configuration to opened connection...
