### ISSUE TITLE
Documentation is misleading, wrong mentions to generic-pool

### ISSUE THREAD

**Issue by danilohgds** [tgriesser/knex#2308]
Can you guys please confirm what is the current lib being used for connection pooling?

In the documentation itself we have a statement saying pool2 is now being used: 

> Upgrading 0.11 -> 0.12
> generic-pool is swapped out for Pool2 for pooling management
> 

While other pieces of the documentation mentions generic-pool... can you please address which technology is the one in place right now?

**Comment by elhigu** [comment]
in 0.13 it was changed back, because pool2 caused so many problems :|

**Comment by elhigu** [comment]
But yeah it sill is confusing and wrong that upgrade mention, since pool2 was actually taken in to use in 0.8 according to changelog. Please open an issue to docuementation repository knex/documentation.
