### ISSUE TITLE
Inconsistent types for aggregate types

### ISSUE THREAD

**Issue by markasoftware** [tgriesser/knex#2311]
It seems like `count` query results are returned as numbers, e.g: `knex('accounts').count('*')` =>

```json
[{
    "count": "15"
}]
```

But `max` as numbers: `knex('accounts').max('karma')` =>

```json
[{
    "max": 75
}]
```

Shouldn't both of these be numbers? And what about other aggregate functions?

**Comment by elhigu** [comment]
It is probably because count returns always `bigint` and max returns the same type that column 'karma' is. Not related to knex.
