### ISSUE TITLE
Timeout acquiring a connection

### ISSUE THREAD

**Issue by kenmorechalfant** [tgriesser/knex#2313]
I am having trouble getting Knex working at all. I have Postgres installed, I have made myself a user (no password) and made a database and put in a table with a couple rows and that all works fine over the psql command line tool.

Now I have an Express app, I've installed knex and pg with Yarn, and I just went into my `routes/index.js` file to try to get started and see if Knex is working. Here is my code:

```
const express = require('express');
const router = express.Router();

const knex = require('knex')({
  debug: true,
  client: 'pg',
  connection: {
    host: 'localhost',
    user: 'kenmore',
    database: 'kenmore'
  },
  acquireConnectionTimeout: 5000
});

router.get('/', (req, res, next) => {
  knex.select().from('users')
  .then(rows => {
    res.send('success');
  })
  .catch(e => {
    res.send(e.message);
  });
});

module.exports = router;
```

At first it was just hanging for a long time, then I realized that it was finally doing something after 60s, so I set the option `acquireConnectionTimeout: 5000` and in my catch() function sent the error message and I get this after 5 seconds:

`Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?`

I don't understand. Do I have to manually close connections? How is my pool full? I'm not using transactions for this simple test but I did not think it was required.

Side question: Does knex require bluebird to use promises or can I use native promises? I keep seeing `require('bluebird')` in in the code examples on the website but I see no mention of it actually being required.

**Comment by elhigu** [comment]
Please make standalone app, without express. I cannot reproduce the problem.

```
knex = require('knex')({ client: 'pg', connection: 'postgres:///knex_test', acquireConnectionTimeout: 5000 });
Array.apply(null, { length: 20}).forEach(() => { console.log('sending query'); knex.select().from('accounts').then(() => console.log('query done')).catch(err => console.log('fail', err)) });
sending query
sending query
sending query
sending query
sending query
sending query
sending query
sending query
sending query
sending query
sending query
sending query
sending query
sending query
sending query
sending query
sending query
sending query
sending query
sending query
undefined
> query done
query done
query done
query done
query done
query done
query done
query done
query done
query done
query done
query done
query done
query done
query done
query done
query done
query done
query done
query done
```

**Comment by elhigu** [comment]
Bluebird is not necessary either. Usually you can mix native promises and bluebird promises wihtout any problems.

**Comment by elhigu** [comment]
Also how did you test the connection with psql? try connecting like this `psql postgres://kenmore@localhost/kenmore` to be sure you are not using unix socket with your psql connection.

**Comment by kenmorechalfant** [comment]
@elhigu Yeah I tried doing it a half dozen different ways, but I figured it out thanks to your last comment. When I tried that it asked me for a password, however neither blank nor my account password worked. I did not think there was a password set because the psql command never asked me for one and I did not remember setting one. Anyhow, I have now set a new one and it is working.

Sorry for the dumb question. Although I found the error message to be really misleading. I figured if the credentials were wrong it would say something more along those lines.

Thanks anyway.

**Comment by elhigu** [comment]
Yeah... I think it has earlier mentioned about not being able to connect with an error. Which knex versions you were using? Does 0.13.0 give an error in your case?

**Comment by kenmorechalfant** [comment]
This is on v0.14.0.

**Comment by calebeaires** [comment]
Same here

**Comment by elhigu** [comment]
I think knex should try to recognize the case where database access doesn't work and system is failing because of it.
