### ISSUE TITLE
Updating a mediumtext field in mariadb not always working.

### ISSUE THREAD

**Issue by skywickenden** [tgriesser/knex#2318]
Running an knex update to a text field does not always update the field yet it reports success.

Before the update the column contains 'HAPPY 30TH\nBIRTHDAY\nMARGARET-CLAIRE Test\n'

The knex code:

	knex('design_text')
		.update({
			text: 'HAPPY 30TH\nBIRTHDAY\nMARGARET-CLAIRE\n',
		})
		.where({
			designId: 500127,
			areaId: 1
		})
		.debug()
		.then((repsonse) => {
			console.log('success', repsonse);
		})
		.catch((error) => {
			console.log('failure', error);
		});

The code is run and the success is consoled out. However the database has not been updated.

Running the query directly in MaraDB works fine.
Most text changes work fine, it is just a few, such as the one above that don't (It's taken a long time to find out where this problem originated!) I don't know what differentiates the successes from the failures.

**Comment by skywickenden** [comment]
This only seems to be an issue on the Linux (Ubuntu) server. It doesn't happen on my Windows setup.

**Comment by elhigu** [comment]
Cannot reproduce.  There is testcases doing update on linux with mariadb and they are not failing.
