### ISSUE TITLE
Support for standard MySQL connection strings?

### ISSUE THREAD

**Issue by affanshahid** [tgriesser/knex#2319]
I can't seem to connect to my database using the following:

`Server=myServerAddress;Port=myPort;Database=myDataBase;Uid=myUsername;Pwd=myPassword;`

but this works fine:

`mysql://<username>:<password>@<host>:<port>/<db_name>`

Is the former not supported?

**Comment by elhigu** [comment]
I don't see that being supported by node-mysql driver https://github.com/mysqljs/mysql#connection-options

Please check out if it is supported and it it is I suppose it should be doable throug knex too

**Comment by craigcosmo** [comment]
> `mysql://<username>:<password>@<host>:<port>/<db_name>`


how did you make this work ? can you show me your config ? thanks
