### ISSUE TITLE
knex.initialize() calls client.initialize() that has been renamed to client.initializePool()

### ISSUE THREAD

**Issue by ignitenet-martynas** [tgriesser/knex#2320]
Line 46 of src/util/make-knex.js:
```javascript
    // Typically never needed, initializes the pool for a knex client.
    initialize(config) {
      return client.initialize(config)
    },
```

However the corresponding method in Client has been renamed from initialize() to initializePool(). So the call should be changed to client.initializePool().

It might make sense to rename initialize() to initializePool() for Knex also as that's what it actually does? Maybe keep initialize() with a deprecation warning?

I could do a PR but would like to discuss the proper way to proceed first.

**Comment by elhigu** [comment]
I think it can be just changed to call initializePool. However I am pretty amazed that test suite didn't catch this one. Is it not called at all by any of the tests?

**Comment by pablopen** [comment]
Hi, just came across this bug while trying to reconnect the datapool when the database server is restarted in oracledb. Basically two lines of code:
in src/util/make-knex.js line 46:
```
    // Typically never needed, initializes the pool for a knex client.
    initialize(config) {
      return client.initializePool(config)
    },
```
And in 
src/client.js line 267:
```
  initializePool(config = this.config) {
````
This will allow to call
knex.destroy()
and then:
knex.initialize()
without parameters, and use the previous datapool config.

I'll try to do a PR with the fix.

**Comment by pablopen** [comment]
Just made a PR. And  @elhigu it wasn't called in any test
