### ISSUE TITLE
Pool settings confusing in 0.14 (IdleTimeout)

### ISSUE THREAD

**Issue by wubzz** [tgriesser/knex#2322]
Version 3 docs for generic-pool are extremely vague and unclear on many changes. One of these changes is a new setting called `evictionRunIntervalMillis` which essentially equals the old `reapInterval` setting. Unfortunately knex test suite did not cover this in #2208.

In short the setting is used to start a timer which checks two other settings: `idleTimeoutMillis` and `softIdleTimeoutMillis`.

In `generic-pool` v2 this timer has a default value of `1000ms`. In v3 however, it defaults to 0, which is the same as "never run any checks". This results in quite the breaking change since existing applications would expect `idleTimeoutMillis` to still work out of the box, but such is not the case anymore.

While this is not directly a knex issue, I still want to suggest that we update the docs to reflect this change, as it most likely affects a whole lot of applications that are currently using knex.

Reference: https://github.com/coopernurse/node-pool/issues/178

Will move to doc repo if agreed.

**Comment by wubzz** [comment]
CC @elhigu

**Comment by elhigu** [comment]
Awesome!
