### ISSUE TITLE
Knex insert hangs and increases CPU load considerably.

### ISSUE THREAD

**Issue by ealtamir** [tgriesser/knex#2325]
I'm trying to insert an object into my postgres database. I created the table using Knex migrations and everything worked fine, which means the connection to the DB works properly. Now I'm executing a simple insert statement in my app, it hangs and increases my notebook's temperature considerably. I'm using TypeScript. The statement is:

```javascript
knex(this.getTableName())
.insert(this, 'id')
.asCallback((err, result) => {
    console.log('got here!')
    return callback(null, null);
})
```

The SQL that the statement would produce is:
```json
{
"method":"insert",
"options":{},
"timeout":false,
"cancelOnTimeout":false,
"bindings":["6649.0","6648.4","6682.0","6649.0","5876.4","6648.7",63.82547526,6648.757407407406,6649.25,54,1.7021339386576264,9.95445248,6647.395652173914,6648.3,46,2.475089504024077,"106894.56605495"],
"__knexQueryUid":"cbce1274-955a-46b6-94aa-919ac614b58c",
"sql":"insert into \"ticker_values\" (\"ask\", \"bid\", \"high\", \"last_price\", \"low\", \"mid\", \"transactions_buy_coin_qty\", \"transactions_buy_mean_price\", \"transactions_buy_median_price\", \"transactions_buy_qty\", \"transactions_buy_stdev_price\", \"transactions_sell_coin_qty\", \"transactions_sell_mean_price\", \"transactions_sell_median_price\", \"transactions_sell_qty\", \"transactions_sell_stdev_price\", \"volume\") values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) returning \"id\"",
"returning":"id"
}
```

Any help is greatly appreciated!

**Comment by ealtamir** [comment]
After debugging for a while I realized that my problem was that I tried to establish a connection with a nonexistent database. However, I find it strange that instead of throwing an error, knex would simply increase the CPU load and hang.

**Comment by elhigu** [comment]
Maybe reconnecting or something like that goes to busyloop... will fix if I'm able to reproduce.

**Comment by elhigu** [comment]
which dialect were you using?

**Comment by elhigu** [comment]
Looks like knex needs to be less aggressive with trying to reconnect, maybe few seconds. Also some warning message is needed to tell that there was connection problem and maybe even to throw an error if db is responding, but credentials or something else is failing and connection couldn't been acquired because of that.

**Comment by elhigu** [comment]
Hard thing there is to not to fail in that case if there are just too many connections made to DB which causes acquire connection to fail.

**Comment by elhigu** [comment]
problem was that pools create callback must never reject or pool tries to get the resource until acquireConnectionTimeout is triggered.
