### ISSUE TITLE
Converting the column names to cameCase

### ISSUE THREAD

**Issue by cemremengu** [tgriesser/knex#2326]
I am using the `oracledb` dialect. The resulting responses from db are like below (as expected):

```
select * from users;

[ { ID: 'ef22d3240cfd4f7d91d80255ffb48211',
    USERNAME: 'john.doe',
    ROLE: 'admin',
    MAIL: 'john.doe',
    TICKET_ID: 32 } ]
```

How do I convert these column names to camel case so that the result would be:

```
[ { id: 'ef22d3240cfd4f7d91d80255ffb48211',
    username: 'john.doe',
    role: 'admin',
    mail: 'john.doe',
    ticketId: 32 } ]
```

I tried using `postProcessResponse` but no luck :(

**Comment by joelmukuthu** [comment]
`postProcessResponse` should work. could you post the code from your hook responsible for camel-casing the output?

**Comment by cemremengu** [comment]
Strange, I was probably doing something wrong but I was definitely getting `undefined` errors inside `postProcessResponse`  last night. This morning it worked, I guess my node was tired 😄

Thanks for the quick responses!
