### ISSUE TITLE
knex now requires me to specify the schema

### ISSUE THREAD

**Issue by fernandocanizo** [tgriesser/knex#2335]
# Environment

Knex version: knex@0.14.0
Database + version: postgres (PostgreSQL) 10.1
OS: Archlinux Kernel 4.13.12-1-ARCH #1 SMP PREEMPT

# Bug ?

Not sure if it's a bug since I just did a big upgrade on my machine and switched from Pg 9.6 to 10.1, and from PostGIS 2.3 to 2.4, at the same time, since I found several issues not presented here, I ended upgrading from knex 0.13.0 to 0.14.0.

1. Old code which was working fine with previous mentioned versions of everything involved:

```
// my knex.js module to be required from other files
'use strict';

const config = require('config');
const dbConf = config.get('dbConnection');

const knex = require('knex')({
  client: 'pg',
  debug: 'debug' === logLevel,
  searchPath: 'public,datasources',
  connection: {
    host: dbConf.host,
    port: dbConf.port,
    user: dbConf.user,
    password: dbConf.password,
    database: dbConf.db,
  },
});

knex.table = (table) => {
  return knex.withSchema(dbConf.schema).table(table);
};

module.exports = knex;
```

Then on a `users` model:
```
const knex = require('./knex');

const findByUserName = (name) => knex.select().from('users').where('name', name).first();
```

Now this was working fine before the upgrade, but now it gives me:

2. Error message

```
error: relation "users" does not exist
    at Connection.parseE (/home/flc/soft/webgis/map-server/node_modules/pg/lib/connection.js:546:11)
    at Connection.parseMessage (/home/flc/soft/webgis/map-server/node_modules/pg/lib/connection.js:371:19)
    at Socket.<anonymous> (/home/flc/soft/webgis/map-server/node_modules/pg/lib/connection.js:114:22)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:594:20)
  name: 'error',
  length: 104,
  severity: 'ERROR',
  code: '42P01',
  detail: undefined,
  hint: undefined,
  position: '13',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
  line: '1180',
  routine: 'parserOpenTable' }
```

which seems to be an error from `pg` module rather than `knex`, but still I have to ask here first.

In order to fix it I left my `knex.js` module as is, but changed the `users.js` module like this:

```
const knex = require('./knex');

const k = knex('public.users');

const findByUserName = (name) => k.select().where('name', name).first();
```

So it seems now I have to specify the schema, even the `public` one, in order to use knex.

I included a check in the users module, before defining `k`:

```
knex.raw('show search_path').then(r => console.log(r.rows));
```

which responds: 

```
[ anonymous { search_path: '"public,datasources"' } ]
```

which is fine and is as defined in my `knex.js` module.

So... What's going on?

3. I owe you a simple test case, will try to come up with a simplified version later.

**Comment by wubzz** [comment]
It's not so much that knex requires you to specify schema, but rather knex not being able to handle multiple schemas anymore, due to a bug introduced by me in #2172 .

Since postgres is case-sensitive when it comes to schema/searchpath, I intended to fix it in that issue, missing to take into account the support for multiple searchpaths.

**Solution**
For next release of knex (0.14.1?) we should change the syntax from `'public,datasources'` to `['public', 'datasources']` to support multiple schemas. This is especially crucial in case of using `,` in schemaname, was is in fact supported.

**Comment by fernandocanizo** [comment]
I believe changing `'public,datasources'` to `['public', 'datasources']` will be a breaking change, just to consider not using `0.14.1` but `0.15.0` ... (Now that I see this written I recall there was a difference between software not reaching version 1.0 yet and those still at 0.x.y, ignore my comment if that's the case)

**Comment by wubzz** [comment]
Yes, it could be considered a breaking change. However, unless the bugfix involves an Array, there is no way to ensure the case-sensitive bugfix can work. Splitting on `,` is not an option given that postgres supports using `,` in schemaname so a searchPath of `"public", "test,"` must work as well.

**Comment by fernandocanizo** [comment]
True, I didn't know schemas can have commas:

```
flc@(none):test> create SCHEMA "testing,with,commas"
CREATE SCHEMA
Time: 0.016s

flc@(none):mapserver_test> \x
Expanded display is on.
Time: 0.001s

flc@(none):mapserver_test> \dn
-[ RECORD 2 ]-------------------------
Name  | public
Owner | postgres
-[ RECORD 3 ]-------------------------
Name  | testing,with,commas
Owner | flc
```

So it cannot be split on `,`. But to avoid forcing everyone who are using multiple schemas to change their configurations, detecting if `searchPath` is an array may be the way, so it can keep supporting being configured by a single string. But then... To avoid incurring into hard to spot bugs, besides proper documentation, maybe `knex` could issue a warning if it finds a comma in a schema name set by a single string. I mean: who would use a schema name with commas anyway, right?

Does this look too convoluted?
(in replace of https://github.com/tgriesser/knex/blob/master/src/dialects/postgres/index.js#L160)

```
setSchemaSearchPath(connection, searchPath) {
  const path = (searchPath || this.searchPath);

  if (!path) return Promise.resolve(true);

  const connQueryCallback = (error) => (error) ? rejecter(error) : resolver(true);

  return new Promise(function(resolver, rejecter) {
    if (Array.isArray(path)) {
      connection.query(`set search_path to ${path.map(token => `"${token}"`).join(',')}`, connQueryCallback(error));
    } else if (typeof path === 'string' || path instanceof String) {
      if (path.match(',')) {
        // TODO I don't know which method uses knex to spit warnings
        logger.warn(`Comma found in search_path! If you're setting multiple search paths then use an array to configure it.`);
      }

      connection.query(`set search_path to "${path}"`, connQueryCallback(error));
    } else {
      // nor a string nor an array
      return Promise.resolve(true);
    }
  });
},
```

**Comment by wubzz** [comment]
Yes, enforcing `Array` for multiple schemas whilst warning of `,` usage sounds fine to me. I think you can simplify the example by reducing down to a single `connection.query` call without the `connQueryCallback` assignment:

```javascript
if(Array.isArray(path)) {
//Convert to ""
} else if(typeof path === 'string') {
  //Warn and convert to ""
} else {
    throw new TypeError();
}

//connection.query
```

**Comment by fernandocanizo** [comment]
Beautiful. Thanks. :+1:
