### ISSUE TITLE
Connection reset when idle

### ISSUE THREAD

**Issue by jingsam** [tgriesser/knex#2342]
# Environment

Knex version: 0.14.0
Database + version:   MySQL 5.5.33 mysqljs 2.15.0
OS: Ubuntu 16.04 LTS

Select applicable tempalate from below.
If issue is about oracledb support tag @ atiertant. For MSSql tag @ Grimace1975 .
Rest of dialects doesn't need tags.

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do

I use knex connect a MySQL database,  a `read ECONNRESET` after the connection idle for hours. But I connect to a MSSQL database, the connection persists.

As I know, knex will initialize a connection pool when connecting a MySQL or PG database. So, in thoery, the connection should be always available. 

2. Error message

`read ECONNRESET`

3. Reduced test code, for example in https://npm.runkit.com/knex or if it needs real
   database connection to mysql or postgresql, then single file example which initializes
   needed data and demonstrates the problem.

```
const db = knex({
  client: 'mysql',
  connection: {
    host: '*.*.*.*',
    port: 3306,
    database: '****',
    user: '****',
    password: '123456'
  }
})

db.raw('select 1').then(rows => {
  // throw read ECONNRESET when idle for hours
   ....
})
```

**Comment by NemoAlex** [comment]
https://github.com/tgriesser/knex/issues/2323
Please try 0.14.1 out.
