### ISSUE TITLE
How can I create varchar column w/o actual length? (VARCHAR instead of VARCHAR(x))

### ISSUE THREAD

**Issue by antonyarchukcodemotion** [tgriesser/knex#2347]
https://github.com/tgriesser/knex/blob/d98c0b1abc44b8090f426a3d62e0541a394142d8/lib/schemabuilder.js#L151

In the source code, it looks like I have to specify varchar length. 
If I will not do it then 255 will be used as vchar length.

I'm using PG. 
For the sake of consistency, I would like to add columns just as VARCHAR (not a VARCHAR(...)) because I already have columns with type VARCHAR. 

How can I do it using knex? Thanks

**Comment by elhigu** [comment]
with .specificType
