### ISSUE TITLE
Knex and Instance Name problem

### ISSUE THREAD

**Issue by michaelmilkov** [tgriesser/knex#2350]
# Environment

Database: MSSQL
OS: CentOS

Hello guys. I have a problem running knex to accept instance name SQLEXPRESS

I am getting Failed to connect to IP:1433 - connect ECONNREFUSED or Failed to lookup instance on server - getaddrinfo ENOTFOUND server"

I tried adding instanceName in the options. Databases without instance names are working like a charm.

Somebody experienced with named instances and knex?

Thank you!

**Comment by elhigu** [comment]
Sounds like mssql driver issue, did you check https://github.com/patriksimek/node-mssql ? 

Try to create connection first directly using the mssql driver and when you get that working try to apply the same approach with knex.
