### ISSUE TITLE
knex has the wrong exit status on bad command

### ISSUE THREAD

**Issue by P-Seebauer** [tgriesser/knex#2351]
# Environment

Knex version: 0.12.9 and 14.1
Database + version: does not matter
OS: ubuntu

# Bug
1. Explain what kind of behaviour you are getting and how you think it should do

knex (-cli) does exit with 0 if the command supplied was wrong.
It should exit with a non-zero exit code, except you state in your documentation something like 

```knex ⟨anything else⟩ print this help message and exit.```

2. Error Message
None, if you don't count the help text. This is a bug about a lack of errors.

3. Reduced test code, for example in https://npm.runkit.com/knex or if it needs real
   database connection to mysql or postgresql, then single file example which initializes
   needed data and demonstrates the problem.

just run 
```
knex foo;
echo $?;
```
It should **not** print 0

**Comment by elhigu** [comment]
Looks like this is only happening on **unknown commands**, not for example in those cases when invalid parameters are given or when command fails. 

I have hard time to believe that anyone is currently relaying on this functionality (just printing knex client help texts and passing also invalid command string in) so dropped the `breaking change` flag from this.

**Comment by P-Seebauer** [comment]
No, I'm not relying on it, I just had a typo in a CI script was looking in the wrong spot because of that. It's probably easily fixable. Maybe I'll give it a try.
