### ISSUE TITLE
batchinsert() throws error when inserting multiple rows using Oracle DB

### ISSUE THREAD

**Issue by abus120** [tgriesser/knex#2355]
# Environment

Knex version: 0.13.0
Database + version: Oracle 11g
OS: Windows 7

# Bug
@oracledb 
1. Explain what kind of behaviour you are getting and how you think it should do

- Using batchinsert() for multiple rows got error ORA-01006, but when trying to insert single row it would works fine. Using oracleDB, the tables doesn't have auto increment for PK hence I'm using db.raw() for sequences, but I'm damn sure db.raw() only causing this issue. Below is my code snippet.

```javascript
db.knex.transaction(function (trx) {
            var chunkSize = 1000;
            var rows = [{ AERR_SYSID_PK: db.knex.raw('KSN_AERR_SEQ.NEXTVAL'), FK_REQU_SYSID: 44628, FK_ORDE_SYSID: 135292, AERR_MESSAGE: 'KSM_RPRO_0059' },
            { AERR_SYSID_PK: db.knex.raw('KSN_AERR_SEQ.NEXTVAL'), FK_REQU_SYSID: 44628, FK_ORDE_SYSID: 135292, AERR_MESSAGE: 'KSM_RPRO_0060' }];  
            db.knex.batchInsert('KSN_ACTIVATE_ERROR', rows, chunkSize).returning('AERR_SYSID_PK').transacting(trx)
                .then(function (result) {
                    if (result != null && result[0] != null) {

                    }
                })
                .then(trx.commit)
                .catch(function (err) {
                    trx.rollback;
                    logger.error(err);
                });
```
2. Error message
- ORA-01006: bind variable does not exist
ORA-06512: at line 1
"

**Comment by timhuff** [comment]
I'm not too experienced with Oracle 11g but I would say that your use of sequences in this way is going to cause errors that have nothing to do with knex. If you need to use sequences this way, you might want to consider reading the current value of the sequence, then setting the `AERR_SYSID_PK` property of the nth row to something like `baseVal+n`. Then altering the sequence to `baseVal+length` afterwards. I'm assuming that there's a reason you can't just run a migration that says `table.increments('AERR_SYSID_PK')` - that would enable you to not worry about specifying `AERR_SYSID_PK` explicitly. As an aside, I believe your `trx.rollback` should be `trx.rollback(err)`.

**Comment by wubzz** [comment]
Also don't know Oracle, but I must agree with hypothesis above. 

Does the same error occur if you run the same compiled query outside of knex?

Reopen if this is still an active issue.

**Comment by juandav** [comment]
What is the current status of this issue, is this error still present, any ideas? Reopen please.
