### ISSUE TITLE
clear orderBy

### ISSUE THREAD

**Issue by jeremymarc** [tgriesser/knex#2360]
To paginate, I'm using query.clone().count('* as count'), but because the query has an ORDER BY, I'm getting an error: "must appear in the GROUP BY clause or be used in an aggregate function".

Is there a way to clear the query orderBy?

Thanks

**Comment by elhigu** [comment]
No there is not :( PR for that is always welcome.  As a workaround you may be able to clone() query builder before orderBy is added?

**Comment by roemhildtg** [comment]
I'm running into this too and would be willing to take a stab at fixing it if I could get a little bit of help on where to start.

I'm using feathers-bookshelf-service with bookshelf.

**Comment by elhigu** [comment]
@roemhildtg here is the PR where clearSelect and clearWhere was added https://github.com/tgriesser/knex/pull/1912 it should serve as a good reference how to implement more clearXXX methods

**Comment by melnikaite** [comment]
For `orderBy` you can use `queryInstance._clearGrouping('order')` to delete all `order` statements
