### ISSUE TITLE
Pooling strategy for connecting to different database based on the logged in user

### ISSUE THREAD

**Issue by anoopmd** [tgriesser/knex#2367]
I am using Knex.js for a B2B SAAS Application that wil connect to a different mysql database based on which user is logged in.

I am seeing two options
1. Create a pool for every request and destroy it once the request completes
2. Once a pool is created, Cache the pool for future connections

The disadvantage with the second option is that, over time the number of connection pools would keep inreasing. If the app has 1000 users, this would result in 1000 pools.

The disadvantage with the first one is that, there is the overhead of creating and destroying the pool for every request. If the server gets 100 requests per second, then we would have to
create and destroy the pool 1000 times in a second. 

Has anyone encountered a similar dilemma? If so what solution did you use?

**Comment by elhigu** [comment]
This kind of question should be sent to stackoverflow or some other place as mentioned in issue template.

If only database changes, but database server remains the same I suppose you can use `.withSchema` to select which schema to use. Creating pool for every  request is a bad choice. If you have multiple database server maybe you can create one pool for each server and then select which DB to use connection basis.

**Comment by anoopmd** [comment]
@elhigu Thanks  :) The database server remains same, I didn't know I could use .withSchema

**Comment by mamdi52** [comment]
I tried below but it connects the default public schema everytime. 
var dbconfig = {
        client: 'pg',
        connection: {
            host: 'localhost',
            user: 'postgres',
            password: 'mypassowrd',
            database: 'mydb',            
            charset: 'utf8',
            port: 5432,
            debug: true,
            timezone: "UTC",
            searchPath:["myschema"]
        }
    };
var knex = require('knex')(dbconfig);
var bookshelf = require('bookshelf')(knex);
bookshelf.plugin('registry');
var clients = bookshelf.Model.extend({
    tableName: 'clients',
    idAttribute: 'id'
    
});


 var ClientModel  = bookshelf.model('clients', clients);

 var client = new ClientModel();

 client.where({user_id:1}).query(function(qb){
 	qb.withSchema('myschema');
 }).fetch().then(function(result){
 	if(result)
 	console.log(result.toJSON());
 })

**Comment by wubzz** [comment]
@mamdi52 `searchPath` should be outside the `connection` object.
