### ISSUE TITLE
self.values = self.values.map(utils.prepareValue);

### ISSUE THREAD

**Issue by Dan195** [tgriesser/knex#2369]
Knex version:
PostgreSQL,  "knex": "^0.12.9",

OS:
LINUX

# Bug

When passing columns into a method for a query, I get the above error.

```
Textbook.getAllTextbooks("id")
    .then((textbooks) => {
        console.log(textbooks);
     });

```
and in my models file...

```
var Portal = {
    
    getAllPortals: function(columns) {
 return knex("Textbooks").column(columns).select();
    },
```

Yet when I run knex("Textbooks").columns("id").select(); everything returns normally. Is there something I am missing to enable this sort of functionality when the columns parameters change?

**Comment by elhigu** [comment]
Please include complete example of your problem. For example now in your current code you are calling `Textbook.getAllTextbooks` which is not included and you seem to implement somewhat similar functionality in model called `Portal`.

In runkit knex template all the knex initialization code is written already, should be easy to write runnable example to demostrate what is the problem.

**Comment by Dan195** [comment]
This is the full example less the configuration server information. I updated it to reflect exactly what I have as the previous example had incorrect variable names from copying and pasting. I am getting the same error when using runkit as well.

**Comment by elhigu** [comment]
@Dan195 https://runkit.com/embed/qiz3b94vxrb4 I don't see any error there, the query generated is `select "id" from "Portals"` which seems exactly as it should. So if you are getting an error it is elsewhere, not in the code that you have shared. Please add complete example which shows the error you are experiencing.

**Comment by Dan195** [comment]
@elhigu Thanks for the example! I missed line 2 in runkit, so that's what caused the error when trying to replicate the problem. I now see that there was old pg code from a previous version of this project that was inluencing knex's response. I have since removed that and everything is working.
