### ISSUE TITLE
Question: How do I modify the knex configuration for a single migration file?

### ISSUE THREAD

**Issue by JemiloII** [tgriesser/knex#2370]
I need to set the connection timestamp to UTC for a single migration. I am using postgres and we have the timestamps as the primary key. We are merging tables into a single table while renaming the old tables. When I go to `batchInsert`, some of the timestamps are now the same. no timestamp was the same before. So what I found out is that the date is wrong. But when I set the timezone to UTC in the main knexfile, it breaks the application. I don't want to fix every broken spot, but rather set a single migration to set `config.connection.timezone` to `'UTC'`

Below is sudo code of what I'm trying to do.

    exports.up = knex => { 
        knex.connection.add('timezone', 'utc);
        return knex.query();
    };

Only this migration file would use the custom timestamp.

**Comment by elhigu** [comment]
Use `knex.raw('...<set timezone>...')`. Migrations are ran in a transaction, so that setting should remain for all the queries at least until transaction ends.
