### ISSUE TITLE
'select ... as...' with a dot in colum name

### ISSUE THREAD

**Issue by antonyarchukcodemotion** [tgriesser/knex#2375]
Knex version: 0.13.0
Database + version: PG
OS: *nix

I have a select query with joins. It works great, but when I'm doing: 
`.select('table1.*', 'table2.name as specific.name', 'table3.*');`
I'm getting the field with name `specific_name` instead of `specific.name`, so the dot was replaced with the underscore. 
I've tried to add quotes, escape dot with `\`  etc. but the dot is replacing anyway.
At the same time I can do:
`SELECT dashboard.users.id as "blabla.id" FROM dashboard.users` 
in pg console and I will get correct `blabla.id` colum name.

Is there a way to add a dot to the 'as' block?

**Comment by elhigu** [comment]
Sorry, `period` in identifiers is not supported and there is no plan for supporting them, since knex internals are heavily using that as a separator for identifier quoting etc.

**Comment by antonyarchukcodemotion** [comment]
What else can I use instead of `period` and `underscore` to indicate nested structure in knex?

**Comment by elhigu** [comment]
semicolon, colon, magic separator string, number... any char / string that is valid identifier for your SQL dialect and that you are not using in your identifier names otherwise.

**Comment by elhigu** [comment]
Except question mark. That will mess up queries too.

**Comment by antonyarchukcodemotion** [comment]
colon/semicolon is replaced with `_` too :(

**Comment by elhigu** [comment]
by who? https://runkit.com/embed/5nu9kbrsx506

**Comment by antonyarchukcodemotion** [comment]
`.toSQL()` shows `:`, but when I'm looking at the result object it is replaced with `_`.
ver 14.2

**Comment by elhigu** [comment]
No its not. 

```js
> knex = require('knex')({ client: 'pg', connection: 'postgres://knex_test' });
> knex('accounts').select('email as foo:bar').then(res => console.log(res));
Promise {
  _bitField: 0,
  _fulfillmentHandler0: undefined,
  _rejectionHandler0: undefined,
  _promise0: undefined,
  _receiver0: undefined }
> [ anonymous { 'foo:bar': 'test3@example.com' },
  anonymous { 'foo:bar': 'test4@example.com' },
  anonymous { 'foo:bar': 'test5@example.com' },
  anonymous { 'foo:bar': 'test6@example.com' },
  anonymous { 'foo:bar': 'transaction-test1@example.com' },
  anonymous { 'foo:bar': 'transaction-test3@example.com' },
  anonymous { 'foo:bar': 'fbaz@example.com' },
  anonymous { 'foo:bar': 'email0' },
  anonymous { 'foo:bar': 'email1' },
  anonymous { 'foo:bar': 'email2' },
  anonymous { 'foo:bar': 'email3' },
  anonymous { 'foo:bar': 'email4' },
  anonymous { 'foo:bar': 'email5' },
  anonymous { 'foo:bar': 'email6' },
  anonymous { 'foo:bar': 'email7' },
  anonymous { 'foo:bar': 'email8' },
  anonymous { 'foo:bar': 'email9' },
  anonymous { 'foo:bar': 'email10' },
  anonymous { 'foo:bar': 'email11' },
  anonymous { 'foo:bar': 'email12' },
  anonymous { 'foo:bar': 'email13' },
  anonymous { 'foo:bar': 'email14' },
  anonymous { 'foo:bar': 'email15' },
  anonymous { 'foo:bar': 'email16' },
  anonymous { 'foo:bar': 'email17' },
  anonymous { 'foo:bar': 'email18' },
  anonymous { 'foo:bar': 'email19' },
  anonymous { 'foo:bar': 'email20' },
  anonymous { 'foo:bar': 'email21' },
  anonymous { 'foo:bar': 'email22' },
  anonymous { 'foo:bar': 'email23' },
  anonymous { 'foo:bar': 'email24' },
  anonymous { 'foo:bar': 'email25' },
  anonymous { 'foo:bar': 'email26' },
  anonymous { 'foo:bar': 'email27' },
  anonymous { 'foo:bar': 'email28' },
  anonymous { 'foo:bar': 'email29' },
  anonymous { 'foo:bar': 'email30' },
  anonymous { 'foo:bar': 'email31' },
  anonymous { 'foo:bar': 'email32' },
  anonymous { 'foo:bar': 'email33' },
  anonymous { 'foo:bar': 'email34' },
  anonymous { 'foo:bar': 'email35' },
  anonymous { 'foo:bar': 'email36' },
  anonymous { 'foo:bar': 'email37' },
  anonymous { 'foo:bar': 'email38' },
  anonymous { 'foo:bar': 'email39' } ]

> 
```

If in your code that is replaced, it is not the knex who is doing that replacement.

**Comment by antonyarchukcodemotion** [comment]
my bad, it was objection.js who replaced `:`
thanks again

**Comment by elhigu** [comment]
@antonyarchukcodemotion Yeah, objection uses `:`for some internal stuff and it is also part of extended identifier syntax there, which allows to refer attributes inside JSONB fields etc. And also IIRC in some other parts when declaring nested relation filters...
