### ISSUE TITLE
Knex cant recycle the connection pool

### ISSUE THREAD

**Issue by rsfernandes** [tgriesser/knex#2377]
We use Knex with generic pool as our Query Builder and Pool Manager for our Oracle 11.2 Database.

The problem we are facing is that some time Knex / generic-pool starts to accumulate connections and cant recycle them.

I tried to pass some parameters to Knex / Generic Pool to make them kill connections after some point, but looks like it did not worked out.

Packges version:

- Knex: v0.13.0
- Oracledb: v1.13.1
- Generic Pool: v2.5.4
- Knex configuration:

```
{
    client: 'oracledb',
    connection: {
        user: DB_USER,
        password: DB_PASSWORD,
        host: `${DB_HOST}:${DB_PORT}`,
        database: DB_NAME
    },
    debug: true,
    fetchAsString: ['number', 'clob'],
    acquireConnectionTimeout: 843600000,
    pool: {
        min: 2,
        max: 150,
        acquireTimeoutMillis: 100000,
        evictionRunIntervalMillis: 120000,
        maxWaitingClients: 100,
        idleTimeoutMillis: 100000
    }
}
```

Edit:

Adding a Openshift print with environment variable DEBUG="knex:*" to show the current pool state:

https://i.stack.imgur.com/DepZs.png

**Comment by elhigu** [comment]
What kind of code is it that accumulates connections. Please add complete example code to reproduce. Just a config is not enough. Does this happen with latest knex too?

**Comment by rsfernandes** [comment]
@elhigu 

Some sample code here. I will try with the latest version. 

`return rxifyPromiseFn(() => this.knexInstance.client.acquireRawConnection())
            .switchMap((connection: oracledb.IConnection) => {
                return fromPromise(connection.execute(sqlCommand, bindings))
		}).then(doSomething)
		  .catch(error)`

**Comment by rsfernandes** [comment]
Sorry for take so much time to reply.

I'm testing with Knex 0.14.2 in our homologation environment starting today.

**Comment by igor-savin-ht** [comment]
@rsfernandes 0.14.3 uses brand new connection pool, could you check if it's still an issue there?

**Comment by elhigu** [comment]
@igor-savin-ht I haven't yet stress tested oracle so it might still not be stable in 0.14.4 either at least mssql driver is still pretty unstable.

**Comment by rsfernandes** [comment]
Hi folks, I have some update to this thread.

The sessions lost by Knex were kept in Oracle as inactive, as Knex could not recycle them.
Now we're using version 0.14.6 with min pool size set to 0 and it seems to be working better, but we're changing to use node-oracledb only.

My problem is related to this issue: https://github.com/tgriesser/knex/issues/2514 so you can close this issue and we continue the conversation there.

Thks
