### ISSUE TITLE
 How to show sql?

### ISSUE THREAD

**Issue by guosenor** [tgriesser/knex#2378]
# Questions about how to use knex

How to show sql on console when application running ?

**Comment by VMBindraban** [comment]
http://knexjs.org/#Installation-debug

Run `DEBUG=knex:*` as environment variable.

**Comment by elhigu** [comment]
And toSQL().toNative() shows query in format that it is sent to sql driver. Also you can hook up printing to knex.on(’query’, ...) event

**Comment by coisnepe** [comment]
For the record, the documentation of this:
```javascript
yourQuery.toSQL().toNative()
```
is here: http://knexjs.org/#Interfaces-toSQL

**Comment by wwei-flux** [comment]
How to turn on native SQL logging for all knex queries? The `knex.on(’query’, ...)` event passes an `data` parameter which doesn't have the `toSQL` method.

**Comment by mcelotti** [comment]
@wwei-flux you could use 'start':
```
knex.on('start', (builder) => {
  // do something with builder.toQuery();
});
```
