### ISSUE TITLE
Support knex.raw in aggregates

### ISSUE THREAD

**Issue by forivall** [tgriesser/knex#238]
knex should support use of raw in aggregates

For example: `knex('table').count(knex.raw('distinct "column"')` (postgres)
Current workaround: `knex('table').select(knex.raw('count(distinct "column")')`

Fix (would pull request, but needs tests): in `clients/base/grammer.js`; in `compileAggregates`

```
- if (aggregate.columns.toLowerCase().indexOf(' as ') !== -1) {
+ if (!(aggregate.columns instanceof Raw) && aggregate.columns.toLowerCase().indexOf(' as ') !== -1) {
```

An even better fix would be to support distinct with count natively.

**Comment by absolux** [comment]
It might be closed now, since `countDistinct()` is available

**Comment by elhigu** [comment]
@absolux yep, if anyone likes to have some more features related to this, new issue should be opened.
