### ISSUE TITLE
Idea: Wrap raw `where` clauses in parentheses

### ISSUE THREAD

**Issue by dylanpyle** [tgriesser/knex#2382]
# Environment

Knex version: 0.14.2
Database + version: Postgres 9.5.1.0
OS: macOS 10.13.1

# Feature discussion / request

I'm chaining multiple queries using `andWhere` depending on arguments. One of these is a raw query which contains an `or` operator. Since this wasn't explicitly grouped, it ended up affecting other `where` clauses.

Here's some sample code:

```js
function findUsers(search, role) {
  return db('users').select('*')
    .orderBy('created_at', 'desc')
    .modify((query) => {
      if (search) {
        query.andWhere(db.raw('name ~* :search or email ~* :search', { search }));
      }

      if (role) {
        query.andWhere({ role });
      }
    })
}
```

There's undoubtedly other ways this query could be written, including `orWhere` with another raw block, but this worked and was how it was written originally.

When `role` and `search` are passed into this function, I expected it to generate a query like:

```
select * from "users" where (name ~* $1 or email ~* $2) and "role" = $3 order by "created_at" desc limit $4
```

But instead, it generates:

```
select * from "users" where name ~* $1 or email ~* $2 and "role" = $3 order by "created_at" desc limit $4
```

— which has a very different meaning / set of results.

I totally get why this is happening, and it's easy to add the `()` grouping myself. But this was confusing and took a few minutes to debug, and I feel like it could be avoided if `where(raw())` clauses were wrapped in parentheses by default. Thoughts?

**Comment by elhigu** [comment]
Kind of makes sense that single where raw could be wrapped to parenthesis, but in current way it is more versatile. To add parenthesis there is trivial to do manually in those cases when they are needed:

```js
query.andWhere(db.raw('(name ~* :search or email ~* :search)', { search }));
```

In this case I prefer to have functionality that enables more use cases.
