### ISSUE TITLE
server port

### ISSUE THREAD

**Issue by blondie63** [tgriesser/knex#2384]
Hi, looking on http://knexjs.org/ i've no found the syntax to create connections to mysql with port different from default.. i think it's:
client: 'mysql',
        connection: {

            host: '192.168.33.10',
            port: '3307',
            user: 'birdbase',
            password: 'password',

            database: 'birdbase',
            charset: 'utf8',

        }

Is it correct ? or port: 3307,

**Comment by VMBindraban** [comment]
You can define the port as a number and as a string.
The example you described is correct.

**Comment by elhigu** [comment]
look correct.

**Comment by ThisIsKeb** [comment]
Hi! I'm using a port different from the default with postgress.

 I was able to address a different port by just adding it to the initialization area. The knex documentation doesn't really state what other settings you can modify in that section, so it makes sense why you couldn't find it. Here's my code. (Note that the password and database name needs to be filled in to connect, I removed mine for security reasons.)

![image](https://user-images.githubusercontent.com/70029954/93112403-f6356880-f685-11ea-9596-32f29c4d6c7a.png)
