### ISSUE TITLE
How to use option cascade in truncate function?

### ISSUE THREAD

**Issue by slim-hmidi** [tgriesser/knex#2385]
I'm trying to use the function `truncate()` and I found that the default option was `restart identity` when I execute this query:
```
knex('estab').truncate()
```
Added to that I need to truncate mutiple table in the same query:
```
knex('estab, prov, prod').truncate()
```
But I got an error. So I changed it to this query:
```
knex.raw('truncate prov, estab, prod cascade')
```
and it works. Can I add multiple tables in the same time to the function truncate and how can I choose the option for it?

**Comment by elhigu** [comment]
I think there is no way to pass multiple tables to truncate right now. AFAIK that can be done only with knex raw.

**Comment by slim-hmidi** [comment]
@elhigu  what about the option? It's setted `restart identity` by default. Is it possible to change it or should I use `raw` ?

**Comment by elhigu** [comment]
That kind of feature would be welcome which allows to select if sequences should be reset or not. Currently I suppose `raw` is the only way to prevent that.
