### ISSUE TITLE
Error selecting constant value (could not determine data type of parameter) 

### ISSUE THREAD

**Issue by joaonice** [tgriesser/knex#2386]
# Environment

Knex version: 0.14.2
Database + version: PostgreSQL 9.4.5
OS: OSX El Capitan

Hi there, I'm trying to do this simple `select` instruction with constant values and values from one table (Later, I'll use this `select` instruction to insert values)

```js
knex
  .select(knex.raw('?, ??', ['foo', 'id']))
  .from('someTable')
```

And I'm getting the following error:

``
could not determine data type of parameter $1
``

What's the correct way to raw select constant values?

**Comment by elhigu** [comment]
Looks like postgresql does not support passing values as parameter bindings to `select` or it is just about that postgres needs explicit type cast there. So your query `select $1, "id" from "someTable"` is invalid. Or maybe this works:

```
knex
  .select(knex.raw('?::text, ??', ['foo', 'id']))
  .from('someTable')
```

If that doesn't work there are many ways to implement the thing you are trying to do. However I cannot say which is the best way without knowing more about the exact use-case what is tried to be achieved with this select.
