### ISSUE TITLE
Bug: .timestamps() is not setting default values

### ISSUE THREAD

**Issue by Jakobud** [tgriesser/knex#2387]
# Environment

Knex version: 3.10.10
Database + version: MariaDB 15.1, Distrib 10.2.8-MariaDB
OS: Ubuntu 16

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do

I have the following schema builder code:

```
return knex.schema.createTable('countries', function (table) {
        table.increments()
        table.timestamps()
        table.string('name')
        table.string('code')
      })
```

According to this line:

https://github.com/tgriesser/knex/blob/master/src/schema/tablebuilder.js#L174

`updated_at` and `created_at` should have default values (CURRENT_TIMESTAMP) applied to them. But when I insert values into the table, there are no default values. The value is NULL. I have confirmed it using describe:

```
MariaDB [photogferret]> describe countries;
+------------+------------------+------+-----+---------+----------------+
| Field      | Type             | Null | Key | Default | Extra          |
+------------+------------------+------+-----+---------+----------------+
| id         | int(10) unsigned | NO   | PRI | NULL    | auto_increment |
| created_at | datetime         | YES  |     | NULL    |                |
| updated_at | datetime         | YES  |     | NULL    |                |
| name       | varchar(255)     | YES  |     | NULL    |                |
| code       | varchar(255)     | YES  |     | NULL    |                |
+------------+------------------+------+-----+---------+----------------+
5 rows in set (0.00 sec)
```

**Comment by Jakobud** [comment]
My mistake. I should have been using `.timestamps(true, true)`. That fixed it.

**Comment by JefferyHus** [comment]
`.timestamps(true, true)` is not working for me `postgresql`

**Comment by sayhicoelho** [comment]
Thanks @Jakobud! I was facing the same issue here, but now I can't set "ON UPDATE CURRENT_TIMESTAMP" to `updated_at` field. How did you do it?

**Comment by StanleyMasinde** [comment]
> My mistake. I should have been using `.timestamps(true, true)`. That fixed it.

Sorry for spamming a closed issue but this worked for me. I was just wondering why this is not in the documentation?

**Comment by kibertoad** [comment]
@StanleyMasinde Would you be consider creating a PR for https://github.com/knex/documentation?

**Comment by StanleyMasinde** [comment]
@kibertoad sure 👍. I'll do that.

**Comment by kibertoad** [comment]
Thanks!

**Comment by cozzbie** [comment]
Was a PR ever created for this?

**Comment by StanleyMasinde** [comment]
Thanks for the reminde @cozzbie .
