### ISSUE TITLE
knex transaction not work in multiple table using mySQL database

### ISSUE THREAD

**Issue by shrimaliakash** [tgriesser/knex#2389]
I'm using knex in loopback for DB operation with mysql. My task is to update the 2 table by using the transaction. When I enter new entry in one tabe, i want to use id of that entry for 2nd query operation.

But when transaction throw the error it not rolling back the data/ removing the first table entry if second table entry throws error. but in my case transaction always do commit not rollback i put my example code in below:
``` addTest : (data) => {
 return new promise(function(resolve, reject) {
  knex.transaction(function(trx) {
    return knex.insert({
      foo_id: data.foo_id ? data.foo_id : null,
      foo_name: data.foo_name ? data.foo_name : null,
      date_entered : new Date()
    }).into('foo').transacting(trx).then(function(ids) {
      trx.rollback;
      return knex.insert({
        bar_id: data.bar_id ? data.bar_id : null,
        bar_name: data.bar_name ? data.bar_name : null
      }).into('bar').transacting(trx).then(trx.commit)
        .catch(trx.rollback)
      }).catch(function(error) {
        trx.rollback;
        reject(error);
      }) 
    }).then(function(success) {
    trx.rollback;
      resolve(success);
    }).catch(function(error) {
      reject(error);
    })
  })
}
```
please, provide me suitable suggestion. thank you

**Comment by elhigu** [comment]
Please ask this one in stackoverflow or some other forum. You are using transactions wrong in many ways. Knex issue tracker is mainly for for knex development, not for user support how to use knex.
