### ISSUE TITLE
timeout in 0.14.2

### ISSUE THREAD

**Issue by jamesdixon** [tgriesser/knex#2390]
# Environment

Knex version: 0.14.2
Database + version: Postgres 9.5.10
OS: OSX/Windows

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do

After 5 minutes or so of inactivity, subsequent requests to the database timeout. I'd expect this to not be the case. Reverting to Knex 0.13.0 resolves the issue.

2. Error message

Receiving an ETIMEDOUT message from the server.

3. Reduced test code, for example in https://npm.runkit.com/knex or if it needs real
   database connection to mysql or postgresql, then single file example which initializes
   needed data and demonstrates the problem.

 I don't have a test case at the moment. I wanted to see if anyone else is experiencing the problem. I'm curious if this is an issue with the 3.x version of generic-pool, which Knex 0.14.x uses.

**Comment by tmcdonnell87** [comment]
We also started getting transient errors immediately after upgrading to 0.14.x (with MSSQL 4.1.x). Came here looking to see if anyone has encountered it and also don't have a reproducible sample.

**Comment by elhigu** [comment]
Cannot reproduce. Please add some configuration / test code, error messages etc. to be able to get some pointers whats happening.

**Comment by tmcdonnell87** [comment]
@elhigu FWIW this does not seem to be resolved. It only appears at production scale, and we had to downgrade to 0.13 due to error volume. 

Here's the error from our logs:
```
TimeoutError: insert into [_table name_] (_...columns list_) output inserted.[id] values (@p0, @p1, @p2, @p3, @p4, @p5, @p6, @p7, @p8, @p9) - ResourceRequest timed out
at ResourceRequest._fireTimeout (/usr/src/app/node_modules/generic-pool/lib/ResourceRequest.js line 58 col 17)
this.reject(new errors.TimeoutError('ResourceRequest timed out'))
at Timeout.bound (/usr/src/app/node_modules/generic-pool/lib/ResourceRequest.js line 8 col 15)
return fn.apply(ctx, arguments)
at ontimeout (timers.js line 475 col 11)
at tryOnTimeout (timers.js line 310 col 5)
at Timer.listOnTimeout (timers.js line 270 col 5)
```

**Comment by elhigu** [comment]
@tmcdonnell87 maybe you should open separate issue for mssql one with some pointers, with which kind of configuration etc. that happen.
