### ISSUE TITLE
Set time zone in migrations

### ISSUE THREAD

**Issue by honestserpent** [tgriesser/knex#2391]
I am using knex migrations to create the database models.
The first thing I would like to do when running migrations is to explicitly set the timezone of the db (postgres in my case) to 'UTC'.

I have a migration file that does just that, as follows, but it does not work.

```
'use strict'

exports.up = function (knex, Promise) {
  return knex.schema.raw("set time zone 'UTC'");
};

exports.down = function (knex, Promise) {
  // do nothing
};
```

**Comment by elhigu** [comment]
use `afterCreate` in knex configuration. Also in what way that doesn't work? What are you trying to do?

**Comment by honestserpent** [comment]
Well, I was expecting the `set time zone 'UTC'` to work and properly set the time zone on the database. I didn't see the afterCreate method, I'll give it a try.

Thank you very much and happy new year!

**Comment by honestserpent** [comment]
@elhigu should I use `afterCreate` in my `knexfile.js`, together with the definition of the database(s) settings, like client, connection, pool sizes etc?

**Comment by honestserpent** [comment]
@elhigu any hints? Sorry to bother but I can't make it to work

**Comment by elhigu** [comment]
How do you think that setting default timezone in migrations should effect? 

Please share an example where you think that timezones are working in a wrong way. Probably there is just confusion in understanding how postgresql handles timezone information.

For example if you are inserting data to database and you pass timestamps as iso8061 strings containing timezone offset the timezone setting of postgres connection doesn't matter at all.

**Comment by honestserpent** [comment]
So, my goal is to, once I perform the migration, set the timezone to `UTC`. In postgres I can achieve this with `set time zone 'UTC'`.

I have a PostgreSQL instance hosted on ElephantSQL. By default, its timezone is `GMT`, at least for the free tier (i'm using it for testing purposes).

I want to set the timezone of postgres to `UTC`. To do so, I tried to use the `afterCreate` option as suggested both by you and the [knex docs](http://knexjs.org/#Installation-pooling-afterCreate).

I have my `knexfile.js` where I specify the development and production database information as follows:

```javascript
'use strict'

module.exports = {
  development: {
    client: 'postgresql',
    connection:     connection: postgres_development_url,,
    pool: {
      min: 2,
      max: 10,
      afterCreate: function (conn, done) {
        conn.query('SET timezone="UTC";', function (err) {
          if (err) {
            // first query failed, return error and don't try to make next query
            done(err, conn);
          }
        });
      }
    },
    migrations: {
      directory: __dirname + "/../db/migrations",
      tableName: 'knex_migrations'
    },
    seeds: {
      directory: __dirname + "/../db/seeds/development"
    }
  },

  production: {
    client: 'postgresql',
    connection: postgres_production_url,
    pool: {
      min: 2,
      max: 10,
      afterCreate: function (conn, done) {
        conn.query('SET timezone="UTC";', function (err) {
          if (err) {
            // first query failed, return error and don't try to make next query
            done(err, conn);
          }
        });
      }
    },
    migrations: {
      directory: __dirname + "/../db/migrations",
      tableName: 'knex_migrations'
    },
    seeds: {
      directory: __dirname + "/../db/seeds/production"
    }
  }
};
```

Now, I run knex migrations through `knex migrate:latest --knexfile knexfile.js`. Migrations go fine, meaning that tables are correctly created, but the timezone is not set to `UTC`.

Now, I thought that maybe the knex command-line utility doesn't use the pool information from `knexfile.js`. So, I also tried to run it the way it is used on the knex docs.

When I start the application I do the following (from my `app.js`):

```javascript
const knexConfig = require('./knexfile');
// Set according to environment: production || develepment (see knexfile.js)
const knex = require('knex')(knexConfig.development);
```

If run debug and set a breakpoint into the afterCreate function in the knexfile, I can see that the code actually gets executed without errors. Yet, if I query the database for `show time zone` after it has been run I still get `GMT` instead of `UTC`.

Hope this explains better. If you have a working example, I would be happy to look at it.

**Comment by elhigu** [comment]
> Now, I run knex migrations through knex migrate:latest --knexfile knexfile.js. Migrations go fine, meaning that tables are correctly created, but the timezone is not set to UTC.

What do you mean that timezone is not set to 'UTC'? How are you verifying it? It must be set to every connection separately. So if you connect there with `psql` at start you must first set timezone parameter correctly.

> Yet, if I query the database for show time zone after it has been run I still get GMT instead of UTC.

If you are creating new connection for that query, you need to set the timezone again to 'UTC' before making the query. If you are using knex to run that query, knex automatically call set timezone in the afterCreate, so your connections through knex always sets the timezone correctlly.

**Comment by honestserpent** [comment]
Ok, I am dumb. I was expecting to use the command and set the default timezone for postgres. I don't know why I didn't realize I was setting it just for the session.

Thank you, and sorry for making you lose time
