### ISSUE TITLE
Passing object search within object passed to knex.raw

### ISSUE THREAD

**Issue by roytz** [tgriesser/knex#2393]
Is there a way doing something like this - 
```
knex('users').where({
    age: 26,
    'email->>address': 'a@b.gmail.com'
});
```
or
```
knex('users').where({
    age: 26,
    email:
        {
            address: 'a@b.gmail.com'
        }
});
```
I know of the way doing that but using knex `raw` function but I need a way doing that by changing only the object passed to the `where` function (that's the only object I have access to).

thanks

**Comment by roytz** [comment]
@elhigu I'd appreciate your input. thanks

**Comment by elhigu** [comment]
Knex really doesn't have support for easily to refer attributes inside jsonb columns. Objection.js has extended column reference syntax to be able to do that in a somewhat similar way that you are trying to do it in the first example.

In knex probably your only choice is to do something like: 

```
.where(knex.raw('email->>address'), 'a@b.gmail.com')
```
