### ISSUE TITLE
How to handle double precision type in knex?

### ISSUE THREAD

**Issue by slim-hmidi** [tgriesser/knex#2395]
I need to use the `double precision` type in postgres database but it is not handled in knex. How can I use this in knex. I tried with `decimal(10,6)` and it did not give me the suitable results. How can I fix that?

**Comment by elhigu** [comment]
If you like to use certain datatype of your favorite DB, you can us `specificType()` to create that type of columns.

**Comment by slim-hmidi** [comment]
@elhigu thank you.

**Comment by sayhicoelho** [comment]
please add support for `double` type!

**Comment by elhigu** [comment]
There is .double() already.

**Comment by sayhicoelho** [comment]
Thanks @elhigu ! Is `.double` in the docs? I can't see.

**Comment by ctepeo** [comment]
@sayhicoelho it's not actually in documentation (or i can't find it as well there 🤷 ), but it's in code and seems like it has the same syntax as `.float()`:

https://github.com/knex/knex/blob/80355e48509857fb4941f65f4b611973a9ee99d5/lib/schema/tablebuilder.js#L111

And here you can check expected arguments: https://github.com/knex/knex/blob/61344b180e9c709322991364d786aaba05b52d26/types/index.d.ts#L1703

**Comment by mashaalmemon** [comment]
Would be great to `.double()` documented officially.
