### ISSUE TITLE
Support for mssql

### ISSUE THREAD

**Issue by tybenz** [tgriesser/knex#240]
Wondering if there are any plans to support MSSQL. Could take advantage of a MSSQL library like this one: "https://github.com/patriksimek/node-mssql".

I'd be happy to work on a pull request for this, but I might need a few pointers on how to get started.

**Comment by tjwebb** [comment]
any update on mssql? I'm building https://github.com/cnect/sails-mssql without the benefit of a real MSSQL query builder for node. Would love to use knex under the hood.

**Comment by bendrucker** [comment]
We basically need someone to take the lead on either writing and maintaining the functionality or sponsoring it. Otherwise there are a lot of higher priority items and you shouldn't count on MS SQL support.

**Comment by tjwebb** [comment]
Yea, understand. I'm already invested in the sails mssql adapter, but I'd love to circle back to a knex implementation after the immediate needs of my project are met.

**Comment by tgriesser** [comment]
Yeah absolutely, @tjwebb that'd be great if you could help out with something like this - I'm mapping out a lot of plans for how to clean up a lot of the query composition so it should be much more straightforward on adding new dialects, etc. 

Would also be cool if we could somehow get knex as a backing for sails at some point, I know from that other ticket you were looking to make that a reality - hopefully once the internals of knex are a bit more modular we can figure out something to make that happen.

**Comment by tjwebb** [comment]
@tgriesser Sounds good. If you run across any sponsored dev for mssql
support, let me know.

**Comment by emanuelhp** [comment]
Hi!

I started an implementation of mssql in https://github.com/tlsoftwares/knex, who can and want to help will be very welcome!
If you have any guidance on how to do this work would be helpful.
I started integrating the dialect "mssql" the possibilities of testing and I am already doing the database connection using https://github.com/pekim/tedious.

**Comment by whitelynx** [comment]
@emanuelhp Thanks for working on this! I'll have to check out your fork soon. I did have a question, though... would you be opposed to using https://www.npmjs.com/package/mssql instead of using tedious directly? That library wraps tedious, [the official Microsoft SQL Server client for Node](https://www.npmjs.com/package/msnodesql), and the older [node-tds](https://www.npmjs.com/package/tds) library, which means it'd be easy for users to switch between drivers. (especially since the official MS driver should outperform the rest, but isn't available on Linux)

**Comment by whitelynx** [comment]
Also, while looking up the `mssql` library, I came across [this MS SQL adapter for knex](https://github.com/CaffeinatedCode/knex-mssql), which looks like it hasn't been touched in a while... it might be useful for inspiration, though.

**Comment by mderijcke** [comment]
Has there been any progress on this? Is there maybe something we (company I work for) could do to help make this happen? (most likely financially)

I personally love Knex and would love one workflow instead having to write a separate data handler for mssql. Please let me know what could motivate you guys and I'll try make it happen!

**Comment by rhys-vdw** [comment]
@mderijcke Hm. I've never used [Bountysource](https://www.bountysource.com/) before, but it looks to me as though you could add a bounty to this issue. If you need it completed in a specific timeframe you might be better off asking any regular contributors if they would be interested in the job and hiring them directly. Good luck.

**Comment by mderijcke** [comment]
I have 0 experience with mssql, but I'm going to arrange user accounts for test databases. One of the system admins at the company I currently work for appears to have mssql experience.

I prepared a virtual machine with Windows Server 2012 R2 and Microsoft SQL Server 2014. Anyone interested in an mssql testbed can contact me or tag me in this issue.

@tgriesser - Let me know if you are interested in a permanent testing bed for mssql. If you could use help financially then we may be able to offer you some help. Please let me know what your stance on the subject is (progress, what's left to do, available time, motivation, etc)

**Comment by emanuelhp** [comment]
Unfortunately my company was restructured and I can not work on it for a while ...

**Comment by JohnHanks** [comment]
how goes the ms sql support? are there different packages to use? or is this the right one?

i am attempting to extend
http://meteor-postgres.readthedocs.org/en/latest/
but using ms sql rather than postgres

**Comment by tjwebb** [comment]
I have not that much experience with mssql, but I ended up building a Waterline adapter for it: https://github.com/cnect/sails-sqlserver. @JohnHanks perhaps the adapter APIs for Waterline and Meteor are similar enough that you could adapt some of the code? 

I also don't know much about this new meteor database adapter system. In summary: I don't know much :)

**Comment by JohnHanks** [comment]
I got the example app working with Knexjs to bridge Postgres to Meteor's Minimongo.

Does anyone know the extent of the work needed to port Knexjs to MSSQL?  We are thinking about doing it ourselves.  If we can pinpoint the changepoints in the code to get this working with any DB, maybe we can investigate and if we develop our own version of Knex for MS SQL then we can issue a pull request :octocat:  :smile:

**Comment by a-c-m** [comment]
Yet another person interested in the MSSQL support.

**Comment by raulgrell** [comment]
I am interested in the MS SQL port, and would be very happy to help in its development. I will try to keep up with discussion, but if you ever feel like you're a pair of hands short, by all means get a hold of me!

**Comment by legomind** [comment]
Is there any work being done on this at all? I would love to have this.

**Comment by rhys-vdw** [comment]
> Is there any work being done on this at all?

@bendrucker?

**Comment by JoaoCnh** [comment]
Any updates?

**Comment by Grimace1975** [comment]
Just wanted to let you know I am building a mssql provider, spent today working on it. probably have complete soon. will post and put in a pull request.

@tybenz this is still a needed feature I am assuming.

**Comment by rhys-vdw** [comment]
@Grimace1975 

Great to hear. This is one of our most regular requests. Please keep us posted. :+1:

**Comment by JoaoCnh** [comment]
@Grimace1975 Is it going well? 

I also put in some time developing for SQL Server and what stopped me was how Transactions were setup in knex source code and how Transactions were handled in the mssql node driver.

**Comment by Grimace1975** [comment]
@JoaoCnh yes it has taken a couple days, longer then i thought it would. everything is complete, all tests passing, except for transactions, and migrations working on these now.

**Comment by JoaoCnh** [comment]
@Grimace1975 nice! Pls let us know if you have gotten any far with Transaction progress

**Comment by Grimace1975** [comment]
@JoaoCnh I just finished and everything works.

@rhys-vdw I will put in a pull request. I noticed however when running babel, that other lib files where overwritten in the lib folder and are different from src. Have people been making changes in lib directly?

**Comment by mbrio** [comment]
I found a potential issue with your mssql implementation @Grimace1975. I began using it yesterday and found that your limit/offset output is based on mssql 2008 thinking. I'm not sure if this is what you were going for, but in mssql 2012 there's offset & fetch. I had to create my own branch that handled that here: https://github.com/mbrio/knex. If the tests are setup against an mssql 2012 server and you are using limit and offset together an error would occur because top and offset can not be used together.

**Comment by Grimace1975** [comment]
@mbrio yes i was trying to support mssql before 2012 as 2012 is not used as much. Top is supported tho across all platforms. The limit and offset only work when used with an order by.

Maybe as a compromise is top use limit and offset when both are used, otherwise revert to using top.

Thank you for finding this.

**Comment by Grimace1975** [comment]
@mbrio,
Do you mind trying to latest master. I have pushed up a fix. and test seem to pass.

**Comment by blitzd** [comment]
When using limit I'm now getting:

```
Unhandled rejection RequestError: select top @p0 * from [table] where [search1] = @p1 and [search2] = @p2 order by [field1] desc - Incorrect syntax near '@p0'.
```

this is with:

```
  knex
    .select()
    .from('table')
    .where(search)
    .limit(10)
    .orderBy('field1', 'desc')
    .then(function (records) {
      res.json(records);
    });
```

**Comment by Grimace1975** [comment]
@blitzd 

i removed the top (?) parens. did this work prior to pulling again.

the built in integration tests perform this action. so it passed locally.

try updating the test\knexfile.js file for mssql
set Debug=mssql
npm test

or the equivalent on your platform

**Comment by blitzd** [comment]
@Grimace1975 

The error seems to indicate that it's passing the limit(X) as a parameter, and I don't think you can do that with SQL Server, parens or no.

```
DECLARE @Top INT = 2

SELECT TOP @Top * FROM sys.tables -- Not valid

SELECT TOP (@Top) * FROM sys.tables -- Not valid

SELECT TOP 2 * FROM sys.tables -- Valid
```

I had previously hacked a bit of mssql support into knex and had implemented the limit using the following (this is just a mish-mash borrowed from other providers with very slight modifications to support top/limit):

```
  select: function select() {
    var statements = _.map(components, function (component) {
      return this[component]();
    }, this);
    var query = _.compact(statements).join(' ');
    return this._addQueryLimit(query);
  },

  limit: function limit() {
    var noLimit = !this.single.limit && this.single.limit !== 0;
    if (noLimit && !this.single.offset) return '';

    // Workaround for offset only,
    // see http://stackoverflow.com/questions/10491492/sqllite-with-skip-offset-only-not-limit
    return 'limit ' + this.formatter.parameter(noLimit ? -1 : this.single.limit);
  },

  _addQueryLimit: function _addQueryLimit(query) {
    var limit = this.single.limit;
    var hasLimit = limit || limit === 0 || limit === '0';
    limit = +limit;

    if (!hasLimit) return query;
    query = query || "";
    if(hasLimit) {
      return query.replace('select', 'select top ' + limit);
    }
  }
```

It may well pass the query builder bits of the unit tests as when I was looking through those they don't necessarily seem to get created in the same was as they get executed on the SQL Server. I.e,. you could end up with SELECT TOP 2 in your query building output - but on the SQL Server it's passing that wrapped in an execute_sql call where the parameters are split out separate (and then it's not valid).

Hope that makes sense!

**Comment by Grimace1975** [comment]
@blitzd  test tested and errors. i have corrected. pushing again.

this works with (?) as it did before.

Declare @statement nvarchar(50) = 'select top (@p0) * From Accounts';
Declare @params nvarchar(50) = '@p0 int';
Exec sp_executesql @statement, @params, 2;

**Comment by blitzd** [comment]
@Grimace1975 can confirm it does indeed work as before! Thanks!

**Comment by JoaoCnh** [comment]
I have the knex from master with the mssql dialect. Trying to migrate a simple table and getting

`TypeError: expecting an array, a promise or a thenable`

when doing knex migrate:latest

What is happening? Anyone aware of this?

**Comment by rhys-vdw** [comment]
@JoaoCnh Got a stack trace?

Send set the environment variable `BLUEBIRD_DEBUG=1` to get enhanced promise stack traces.

**Comment by denisw** [comment]
I've seen that MSSQL support has been merged into master. Any reason why this is still open?

**Comment by sphildreth** [comment]
@denisw Does this mean MSSQL is now a supported DB?
Its not listed in the README.md "A batteries-included, multi-dialect (MySQL, PostgreSQL, SQLite3, WebSQL, Oracle) query builder for Node.js and the...". This is the single roadblock preventing our implementation of knex. Thanks!

**Comment by cexafaulkner** [comment]
Any updates on this? We use KNex where I work, and are looking to add support for MS SQL.

**Comment by Grimace1975** [comment]
Andrew,

Everything should be complete. What are you finding lacking?

@tgriesser I do not believe a new build has been released, and the web content still does not show MS SQL Support.

**Comment by whitelynx** [comment]
@cexafaulkner, @Grimace1975: This was actually released as part of v0.10.0, as shown in [the changelog on the site](http://knexjs.org/#changelog); however, you are correct that the documentation has not been updated to reflect this. I'm sure a PR would be welcome to remedy this ;-)

**Comment by wubzz** [comment]
I added a PR to support MSSQL examples viewing in the docs, #1246 .

**Comment by elhigu** [comment]
mssql is already supported. closing the issue.
