### ISSUE TITLE
.returning places the OUTPUT clause in the incorrect location when updating with joins (MSSQL)

### ISSUE THREAD

**Issue by tankers746** [tgriesser/knex#2400]
# Environment
@Grimace1975 
Knex version: 0.14.2
Database + version: SQL Server 2016
OS: Windows 10 

# Bug

**1. Explain what kind of behaviour you are getting and how you think it should do**
When using .returning, with a join, the outputted query has OUTPUT after the joins.

See correct usage:
https://stackoverflow.com/questions/4170389/inner-join-within-update-output-in-one-t-sql-query

**2. Error message**
> Incorrect syntax near 'output'

**3. Reduced test code**
```
knex('matches')
      .returning(['team', 'fixture'])
      .innerJoin('teams', 'teams.teamID', 'matches.team')
      .update('opponent', 'test');
```

Outputs the query

```
update [matches] 
set [opponent] = ? 
from [matches] 
inner join [teams] on [teams].[teamID] = [matches].[team] 
output inserted.[team], inserted.[fixture]
```

When it should output:

```
update [matches] 
set [opponent] = ? 
output inserted.[team], inserted.[fixture] 
from [matches] 
inner join [teams] on [teams].[teamID] = [matches].[team]
```

I have made a pull request that fixes the bug:
https://github.com/tgriesser/knex/pull/2399

**Comment by elhigu** [comment]
#2399 was merged... is this fixed now?

**Comment by tankers746** [comment]
All good.
