### ISSUE TITLE
columnInfo is not using wrapIdentifier

### ISSUE THREAD

**Issue by seeden** [tgriesser/knex#2402]
we are using automatic camelCase transition for tableName and columns as well.
but columnInfo is not changing tableName https://github.com/tgriesser/knex/blob/7de07c966a6ab63087b31cbdd10216d3ddbf8230/src/dialects/postgres/query/compiler.js#L79

**Comment by elhigu** [comment]
Yeah, there are many places specially in schema methods, which are not using wrapIdentifier correctly. These should be fixed.

**Comment by koskimas** [comment]
I'm working on a fix for this. I'll submit a PR soon.
