### ISSUE TITLE
forUpdate() should not require a transaction if Knex is used as a query builder only

### ISSUE THREAD

**Issue by PatrLind** [tgriesser/knex#2403]
I use Knex as a query builder (not using the built in connection support) and I have problems with forUpdate() requiring a transaction.
I am using a transaction, but not via Knex. So if Knex is not connected to a database (used as a query builder only) I don't think it should require a transaction. To get around this problem I have to manually add the FOR UPDATE statement to my queries. Would it be possible to fix this?

**Comment by elhigu** [comment]
Sounds like a legit use case. I don't see any reason why this couldn't be implemented.
