### ISSUE TITLE
Not able to view the data in table

### ISSUE THREAD

**Issue by Navya-adft** [tgriesser/knex#2409]
Hi,
i am new in Psql and Knex.. 
i create the migration file and seed files..it run sucessfully..but when checking on commandline not view the values ..displaying 0 rows..
groups migration file  is,

```   
exports.up = function(knex, Promise) {
    return knex.schema.createTable('groups',function (table){
        table.increments(); 
        table.varchar('name');
        table.integer('organization_id');
        table.date('timestamp');
        table.foreign('organization_id').references('organization.id').onDelete('CASCADE');

    });
  
};

exports.down = function(knex, Promise) {
    return knex.schema.dropTable('groups');
  
};
```

and my seed file is ,
```
exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('groups').del()
    .then(function () {
      // Inserts seed entries
      return knex('groups').insert([
        {
          id: 4000, 
          name : 'webteam',
          organization_id :101,
          timestamp : '12/11/2017 04:04:20' 
        }
        
      ]);
    });
};
```
is any problem ?
 want to do any update...is i want to use commit ? but when go through the documents,when using promices no need to use commit...

**Comment by elhigu** [comment]
Please try asking if someone in stackoverflow has time to debug this. I'm sure this is just an user error and is not related to any knex bug / missing feature.
