### ISSUE TITLE
Migrate rollback - Error: Unable to acquire a connection

### ISSUE THREAD

**Issue by rkmax** [tgriesser/knex#2412]
# Environment

Knex version: 0.14.2
Database + version: Postgres 10.1
OS: Archlinux  4.14.5-1-ARCH x86_64 GNU/Linux

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do

expected: running `npx knex migrate:rollback` execute the down of each migration in the last batch
current: running `npx knex migrate:rollback` got a error message 

2. Error message
```

Error: Unable to acquire a connection
    at Client_PG.acquireConnection (/home/rkmax/Development/project/node_modules/knex/lib/client.js:346:40)
```

3. My setup it's pretty simple

    $ yarn add knex pg

the knex setup is 
```
// knexfile.js
module.exports = {
  development: {
    client: 'pg',
    connection: process.env.DATABASE_URL,
    pool: {
      min: 2,
      max: 10
    },
    migrations: {
      tableName: 'knex_migrations'
    },
    acquireConnectionTimeout: 3000
  }
}
```

DATABASE_URL environment `DATABASE_URL=pg://postgres@localhost:5432/my_app`

`postgres` user exist on my system the setup is trust on localhost so I dont need password, also the database `my_app` exists. created with `$ createdb my_app` as postgres user

I have the following two migrations

## `migrations/20180104175721_enable-uuid.js.js`

```
exports.up = knex => knex.raw('create extension if not exists "uuid-ossp"');
exports.down = knex => knex.raw('drop extension if exists "uuid-ossp"');

```

## `migrations/20180104175725_add-sites.js`

```
const tableName = 'sites';

const tableDescription = knex => table => {
    table.uuid('id').primary().defaultTo(knex.raw('uuid_generate_v4()'));
    table.string('title');
};

exports.up = knex => knex.schema.createTableIfNotExists(tableName, tableDescription(knex));
exports.down = knex => knex.schema.dropTableIfExists(tableName);

```

**Comment by rkmax** [comment]
I found the issue, it was related to my environment var DATABASE_URL under some circunstances is not defined

**Comment by rodrigograca31** [comment]
@rkmax under what circuntances? because Im having the same problem

**Comment by jonny-irving** [comment]
@rkmax any recollection of this issue?

**Comment by rkmax** [comment]
> @rkmax any recollection of this issue?

Oh boy! I can't remember the last time I used knex, this issue is too old
