### ISSUE TITLE
update() with returning("*") is returning empty array

### ISSUE THREAD

**Issue by phaddius** [tgriesser/knex#2413]
Knex version: 0.14.2
Database + version: Posgres 9.5.3.0
OS: mac, and heroku

I'm expecting my update query to return the rows affected, using the returning clause (and also tried the second parameter in the update() function).

Not sure whats going on here. The returning() function works in other parts of code when using insert() or using update() with a simple where(key,value), but not with this specific combination below, using whereIn():

```
    let entryIds = [41978500, 41978499, 41978498, 41978496]
     let updateValues = {
		updated_at : new Date(),
		status : "deleted"
	}
	let query = knex("notification")
		.whereIn("target_id", entryIds)
		.where("target_type", "entry")
		.update(updateValues)	
	return query
	})
```

The resulting logged query looks like this:  
```
update "notification" set "updated_at" = '2018-01-04 17:16:57.856', "status" = 'deleted' where "target_id" in (41978500, 41978499, 41978498, 41978496) and "target_type" = 'entry' returning * 
```

The affected rows do get updated in the db, but only an empty array is actually returned. Any help is appreciated. Thanks!

**Comment by elhigu** [comment]
Maybe there was no rows to update? I just tried this with knex_test database's accounts table and it did return all the columns of the updated rows:

```js
const knex = require('knex')({client: 'pg', connection: 'postgres:///knex_test'});
knex('accounts').update({last_name: 'wat'}).returning('*').then(console.log);

[ ...
  anonymous {
    id: '54',
    last_name: 'wat',
    email: 'email38',
    logins: 1,
    about: null,
    created_at: null,
    updated_at: null,
    phone: null },
  anonymous {
    id: '55',
    last_name: 'wat',
    email: 'email39',
    logins: 1,
    about: null,
    created_at: null,
    updated_at: null,
    phone: null } ]
```
Please add complete test case which allows to reproduce your problem.

**Comment by phaddius** [comment]
I think its specifically the whereIn() function.  Other uses of returning() using a standard where(key,value) seem to work. Would you mind retrying your test with whereIn()?

**Comment by aviyadeveloper** [comment]
I am having a similar issue, but it is using mySql, which the documentation isn't clear about in regard of support for that format and `.returning()`

**Comment by elhigu** [comment]
@aviyadeveloper you are right... documentation is not very clear about it. It kind of hints that when inserting single row, that should work... but IIRC .returning() is not supported at all with mysql.

**Comment by kibertoad** [comment]
```
The returning method is is entirely unsupported on Amazon Redshift and has no support for multiple inserts on MySQL and SQLite.
```
Is it ambiguous?..

**Comment by elhigu** [comment]
> ```
> The returning method is is entirely unsupported on Amazon Redshift and has no support for multiple inserts on MySQL and SQLite.
> ```
> Is it ambiguous?..

Yes

> ...it kind of hints that when inserting single row, that should work... but IIRC .returning() is not supported at all with mysql.

Yep, also when single row is added, returning doesn't have any effect on mysql. https://runkit.com/embed/sm0iqqrqmrux

**Comment by austinChappell** [comment]
@phaddius What about this?

```
const columns = await knex(tableName).columnInfo();
const results = await knex(tableName).where(conditions).update(changes).returning(columns);
```
