### ISSUE TITLE
knex seed:run - Error: Unable to acquire a connection

### ISSUE THREAD

**Issue by rkmax** [tgriesser/knex#2414]
# Environment

Knex version: 0.14.2
Database + version: Postgres 10.1
OS: Archlinux 4.14.5-1-ARCH x86_64 GNU/Linux

# Bug

1. I'm trying to create a seed for my database, I use the followinf knexfile.js

```
module.exports = {
  development: {
    client: 'pg',
    connection: process.env.DATABASE_URL,
    pool: {
      min: 2,
      max: 10
    },
    migrations: {
      tableName: 'knex_migrations'
    },
    acquireConnectionTimeout: 3000
  }
};
```

execute `knex seed:make my-seed` and the file `seeds/my-seed.js` was created later on I write the seed like follow

```
const tableName = 'site';

exports.seed = knex => createDummySite(knex);

async function createDummySite(knex) {
    await knex(tableName).del();
    await knex(tableName).insert([
        {
            title: 'Blahblah',
            description: 'more lorem ipsum',
        }
    ]);
}
```

2. Error message

```
Using environment: development
Error: Unable to acquire a connection
    at Client_PG.acquireConnection (/home/rkmax/Development/my_project/node_modules/knex/lib/client.js:346:40)
    at Runner.ensureConnection (/home/rkmax/Development/my_project/node_modules/knex/lib/runner.js:215:24)
    at Runner.run (/home/rkmax/Development/my_project/node_modules/knex/lib/runner.js:47:42)
    at Builder.Target.then (/home/rkmax/Development/my_project/node_modules/knex/lib/interface.js:35:43)
```

**Comment by rkmax** [comment]
I found the issue, it was related to my environment var DATABASE_URL under some circunstances is not defined

**Comment by thedevxen** [comment]
Hey, I am getting the same error. I checked the code and everything looks perfect, in face I even matched it with my previous code.
my knex file

```module.exports = {
    client: "sqlite3",
    conection: {
        filename: "./database.sqlite3"
    },
    useNullAsDefault: true
};```


database.js

```const knex = require("knex");
module.exports = knex(require("../knexfile"));```

**Comment by kibertoad** [comment]
@thedevxen is it really "conection"?

**Comment by thedevxen** [comment]
> @thedevxen is it really "conection"?

lmao

**Comment by mirajehossain** [comment]
> I found the issue, it was related to my environment var DATABASE_URL under some circunstances is not defined

Hey, I am facing same issue, but i don't know what hapen witht my db url
my url is ->  `mysql://user:pass@127.0.0.1/db`
