### ISSUE TITLE
Storing `DATETIME` in UTC in mariadb

### ISSUE THREAD

**Issue by mfbx9da4** [tgriesser/knex#2415]
# Environment

Knex version: 0.13.0
Database + version: 5.5.5-10.2.7-MariaDB-10.2.7
OS: mac os + docker

Select applicable tempalate from below.
If issue is about oracledb support tag @ atiertant. For MSSql tag @ Grimace1975 .
Rest of dialects doesn't need tags.

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do

I have the following date stored
```
mysql> select pages.scheduled_for from pages where id = 13;
+---------------------+
| scheduled_for       |
+---------------------+
| 2018-01-04 14:06:00 |
+---------------------+
1 row in set (0.00 sec)
```
When I read it, it is type cast with 
https://github.com/mfbx9da4/knex/blob/master/src/dialects/maria/index.js#L139
```
return new Date(value);
```
Except I am storing the date as UTC. I do not want knex to parse it in my local timezone.
I would expect something like 
```js
if (type === 'DATETIME' && config.timezone === 'UTC') {
  value += 'Z'
}
return new Date(value);
```
`node-mysql` for example has such a setting. See `timezone` https://github.com/mysqljs/mysql this is a common issue for many people using mysql.

2. Error message

3. Reduced test code, for example in https://npm.runkit.com/knex or if it needs real
   database connection to mysql or postgresql, then single file example which initializes
   needed data and demonstrates the problem.

# Feature discussion / request

1. Explain what is your use case

Storing `DATETIME` in utc in mariadb

2. Explain what kind of feature would support this

A config variable of `connection.timezone = 'UTC'` like that of `node-mysql`

3. Give some API proposal, how the feature should work

When parsing datetimes, check timezone config before typecasting or at least have a config for leaving dates as strings.

# Missing / erroneus documentation

Send issue to documentation repo, or fix it and send PR https://github.com/knex/documentation

# Questions about how to use knex

Github issues are for knex development. Please send questions how to use knex to
stackoverflow or ask about it in gitter chat.

**Comment by elhigu** [comment]
Duplicate https://github.com/tgriesser/knex/issues/1461
