### ISSUE TITLE
Invalid alter table statement

### ISSUE THREAD

**Issue by maxwondercorn** [tgriesser/knex#2417]
# Environment

Knex version: 0.14.2
MariaDb using mysql2 driver
OS: osx

I'm getting an unknown column error:

```
Error: Unknown column 'sitecode' in 'user'
```

from the following migration:

```
exports.up = function (knex, Promise) {
  return knex.schema.alterTable('user', function (user) {
    user.string('sitecode', 3).nullable().alter();
  })
}
```
It seems that an additional SQL fragment is being tacked on to the end of ALTER TABLE statement.  Using debug, the following SQL is being generated:

```
alter table `user` modify `sitecode` varchar(3) null, modify `sitecode` varchar(3)
```
Not sure if this a bug or I am using alter incorrectly.

**Comment by elhigu** [comment]
Your table does not have column named `sitecode` whose type / etc. you are trying to alter. If you need to add new column then you should not add `.alter()`  to end of column declaration.

```js
exports.up = function (knex, Promise) {
  return knex.schema.alterTable('user', function (user) {
    user.string('sitecode', 3).nullable();
  })
}
```

**Comment by maxwondercorn** [comment]
But it does have a 'sitecode' column.  I didn't show it for brevity, but I'm dropping a foreign key on that column before I try to alter it.  If I try the SQL generated in phpMyAdmin it fails.

If I modify it to just be:

`alter table `user` modify `sitecode` varchar(3) null`

it works.  'modify `sitecode` varchar(3)` should not be part of the generated sql statement

**Comment by elhigu** [comment]
Right I didn't see the second ```..., modify `sitecode` varchar(3)``` part.

However I'm not able to reproduce this: https://runkit.com/embed/pv2ucmwes4yx

Query generated by that alterTable is only: ```alter table `user` modify `sitecode` varchar(3) null```

Where you are getting that 

```
alter table `user` modify `sitecode` varchar(3) null, modify `sitecode` varchar(3)
```

query?

Please add complete tests case to be able to reproduce the issue.
