### ISSUE TITLE
How to add extra custome column in knex.select()

### ISSUE THREAD

**Issue by HOTTIN** [tgriesser/knex#2418]
# Environment

Knex version: v0.12.9
Database + version: mysql+5.7.19
OS: cenos7

I want to add an extra custome column in my result from knex.select(), just like: select id,'123' as type from tb, but knex return an error to me -> "ER_BAD_FIELD_ERROR: Unknown column '123' in 'field list'" ,
how can i resolve this problem?
If i commit a duplicate issues, i'm very sorry for that~~

**Comment by elhigu** [comment]
does `.select('id', knex.raw('?', ['123']))` work for you? stackoverflow is the correct place to ask for user support.

**Comment by HOTTIN** [comment]
i want to get a field in result that not exits in scheme, which i can name it and give it a value.Such as i have a table which has 3 fields: id, name, gender, when i use knex.select(),i want add a field in result named "type",and i can give it a value,

**Comment by HOTTIN** [comment]
In SQL, i write this: `select id, name, gender, "haha" as type from tb`, and i will get a result that has a field named "type",but when i use knex.select(),it return an error to me.

**Comment by HOTTIN** [comment]
i have resolve this problem,i should write like this:
knex.select('id', 'name', 'gender', knex.raw('\'123\' as type')).from('tb').
3q~

**Comment by HOTTIN** [comment]
i have resolve this problem,i should write like this:
knex.select('id', 'name', 'gender', knex.raw('\'123\' as type')).from('tb').
3q~

**Comment by HOTTIN** [comment]
i have resolve this problem,i should write like this:
knex.select('id', 'name', 'gender', knex.raw("'123' as type")).from('tb').
escape the value '123'
3q~

**Comment by HOTTIN** [comment]
i have resolve this problem,i should write like this:
knex.select('id', 'name', 'gender', knex.raw('\\'123\\' as type")).from('tb').
escape the value '123'
3q~

**Comment by elhigu** [comment]
Are you sure that this doesn't work:

```js
knex.select('id', 'name', 'gender', knex.raw('? as type', ['123'])).from('tb')
```

The way you are doing it might have sql injection vulnerability (unless you are really passing that '123' as a constant to the select).

**Comment by HOTTIN** [comment]
it works, thank u very much!
I should carefully read the document, i didn't know why .raw use "?" to accept said binging as its second parameter before, now i know,3q~~~
