### ISSUE TITLE
Using .catch clips the stack trace

### ISSUE THREAD

**Issue by pjpsoares** [tgriesser/knex#2419]
# Environment

Knex version: 0.14.0
Database: pg
OS: macOS

# Bug

I'm using Bluebird with longStackTraces enabled, to easily pinpoint eventual issues and I stumbled upon what appears to be a bug on the way knex handles the errors.
This stacktrace 
```
try {
  await knex('someTable').select();
} catch (e) {
  console.error(e);
}
``` 
is different from
```
try {
  await knex('someTable').select().catch(error => { throw error; });
} catch (e) {
  console.error(e);
}
``` 
And the only difference between them is that the second is more complete making me believe, that the chained catch from knex somehow clips the stacktrace.

**Comment by elhigu** [comment]
I just ran this with node 8.9.0:

```
knex = require('knex')({client: 'pg', connection: 'postgres:///knex_test'})

async function test1() {
  try {
    await knex('someTable').select();
  } catch (e) {
    console.error(e);
  }
}

async function test2() {
  try {
    await knex('someTable').select().catch(error => { throw error; });
  } catch (e) {
    console.error(e);
  }
}

test1();
test2();
```

Both did print out exactly the same error. Cannot reproduce and I know that catch does not do any stack trace truncating to thrown errors. Problem must be in some other part of your code.
