### ISSUE TITLE
Add a pluckFirst function

### ISSUE THREAD

**Issue by itaysabato** [tgriesser/knex#2421]
Pretty self-explanatory - `.pluck()` is great and `.first()` is great, but many times I find myself wanting to pluck a single value from the first row.

Sure, it's not a lot of code, but it would be pretty useful to have a built-in `.pluckFirst()` function IMHO.

**Comment by elhigu** [comment]
I have never heard anyone missing this before and I don't think knex should start implementing this kind of quite specialised helpers. Lets consider again if there is big demand for this.
