### ISSUE TITLE
Renaming migration file

### ISSUE THREAD

**Issue by ziyaddin** [tgriesser/knex#2423]
General question:
Let's say I created a migration file and applied migration to my database. Then I realized that I did a mistake in naming of this file. Now I want to rename this migration file. Should I take additional steps like renaming the migration name in `knex_migrations` table besides just renaming the file?

**Comment by elhigu** [comment]
Yes you need to rename file also in migrations table of every database where migration has been applied. Otherwise you'll see error about corrupted migrations directory.

**Comment by ziyaddin** [comment]
Thanks!
