### ISSUE TITLE
query working  on pgadmin but not with knex.raw. Promise appears as pending and it swallows the error

### ISSUE THREAD

**Issue by juanlet** [tgriesser/knex#2424]
# Environment

Knex version: 0.14.2
Database + version: postgresql 9.6.1
OS:  Ubuntu 16.10

Select applicable tempalate from below.
If issue is about oracledb support tag @ atiertant. For MSSql tag @ Grimace1975 .
Rest of dialects doesn't need tags.

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do
The built query works fine on pgadmin but not with not if I put it in knex.raw. I copied the query that is built and nothing. This is the logged queried after execution:

```
SELECT (SELECT count(*) FROM campaigns WHERE campaign_state_id = 1) active_campaigns_count,(SELECT json_agg(camp)
                          FROM (SELECT cmp.campaign_id,
                                CASE WHEN cmp.campaign_state_id = 1 THEN 'ACTIVE'
                                     WHEN cmp.campaign_state_id = 2 THEN 'PENDING' END as state,
                                      cmp.name,
                                      cmp.pic_url,
                                      cmp.hashtag,
                                      cmp.tweet_id,
                                      cmp.description cause_description,
                                      cmp.goal,
                                       (SELECT cr.symbol
                                        FROM currencies cr WHERE cr.currency_id=cmp.currency_id) currency_symbol,
                                        coalesce(round((SUM(cmpfb.users_reached+ cmptw.users_reached)*1)*0.5,2),0) current_contributions,
                                        campaign_ending_date,
                                        went_inactive_date,
                                        coalesce(round(goal-(SUM(cmpfb.users_reached+ cmptw.users_reached)*1*0.5),2),0) remaining_ammount_to_goal,
                                        coalesce(round(SUM(cmpfb.users_reached+ cmptw.users_reached)*1/goal*100*0.5,2),0) goal_percentage_achieved,
                                        (SELECT json_agg(founds) FROM  (SELECT fnd.user_id,fnd.twitter_username,fnd.name,fnd.logo_pic_path
                                                                        FROM foundations_data fnd
                                                                        LEFT JOIN campaigns_foundations cmpf ON  cmpf.user_id = fnd.user_id
                                                                        WHERE cmpf.campaign_id = cmp.campaign_id ) founds) foundations,
                                        (SELECT json_agg(cats)
                                         FROM (SELECT ccat.category_id, cat.description_es
                                               FROM campaign_categories ccat
                                               INNER JOIN categories cat ON cat.category_id = ccat.category_id
                                               WHERE ccat.active = true AND ccat.campaign_id=cmp.campaign_id) cats) categories,
                                        count(distinct(ccb.campaign_contribution_id)) contributors_qty,
                                                  cmp.created_at
                                        FROM campaigns cmp
                                        LEFT JOIN campaign_contributions ccb ON ccb.campaign_id = cmp.campaign_id
                                        LEFT JOIN campaign_contribution_facebook_details cmpfb ON cmpfb.campaign_contribution_id = ccb.campaign_contribution_id
                                        LEFT JOIN campaign_contribution_twitter_details cmptw ON cmptw.campaign_contribution_id = ccb.campaign_contribution_id
                                        WHERE campaign_state_id in (1)   AND cmp.campaign_id < 9223372036854776000    
                                        GROUP BY cmp.campaign_id
                                        ORDER BY cmp.campaign_id DESC
                                        LIMIT 3) camp) camp_array

```

2. Error message

No error message, it just appear as pending . I use node --inspect and when it reaches the line of knex.raw it just dies, it doesn't go through any catch block. I tried to use debug:true but it doesn't say anything. I watched the result of the request on chrome and it says pending. I'm using express js to create the route

The code of the function, when it reaches knex.raw it dies

`  async getAllCampaigns(knex, req){

    let catId = req.body.cat_id;
    let searchTerm = req.body.search_term != 'null'? req.body.search_term: null;
    // this is for the endlessScroll on the client
    let lastIdFetched = req.body.last_id_fetched? req.body.last_id_fetched: 9223372036854775807;
    let itemsPerPage = req.body.items_per_page;
    let applyFiltersByFoundationId = req.body.apply_filters_by_foundation_id;
    let states = req.body.states;
    let doPagination = req.body.do_pagination;

    let endlesScrollAndCondition = " AND cmp.campaign id = ";

    let andSearchClause ="";
    let andFoundationIdClause ="";
    let doPaginationClause ="";

    if(searchTerm){
      //TODO: SANITIZE STRING
      andSearchClause = ` AND (unaccent(cmp.name) ILIKE '%${searchTerm}%' OR cmp.hashtag ILIKE '%${searchTerm}%') `;
    }

    if(req.body.user_id && applyFiltersByFoundationId){
       andFoundationIdClause =   `AND cmp.campaign_id IN (SELECT cmpf.campaign_id
                                          FROM campaigns_foundations cmpf
                                          WHERE cmpf.user_id = '${req.body.user_id}' )`;

    }

    if(doPagination){
      doPaginationClause = ` AND cmp.campaign_id < ${lastIdFetched} `;
    }

    let andCatClause = "";
    if (catId != 0) {
      andCatClause = ` AND EXISTS (SELECT 1 from campaign_categories ccat WHERE ccat.campaign_id=cmp.campaign_id AND category_id=${catId}) `;
    }

         //TODO: check that this first column of the result (active_campaigns_count) conditions are constantly updated to what is right since it's used for paging results on client
    return  knex.raw(`SELECT (SELECT count(*) FROM campaigns WHERE campaign_state_id = 1) active_campaigns_count,(SELECT json_agg(camp)
                              FROM (SELECT cmp.campaign_id,
                                    CASE WHEN cmp.campaign_state_id = 1 THEN 'ACTIVE'
                                         WHEN cmp.campaign_state_id = 2 THEN 'PENDING' END as state,
                                          cmp.name,
                                          cmp.pic_url,
                                          cmp.hashtag,
                                          cmp.tweet_id,
                                          cmp.description cause_description,
                                          cmp.goal,
                                           (SELECT cr.symbol
                                            FROM currencies cr WHERE cr.currency_id=cmp.currency_id) currency_symbol,
                                            coalesce(round((SUM(cmpfb.users_reached+ cmptw.users_reached)*${costPerClick})*0.5,2),0) current_contributions,
                                            campaign_ending_date,
                                            went_inactive_date,
                                            coalesce(round(goal-(SUM(cmpfb.users_reached+ cmptw.users_reached)*${costPerClick}*0.5),2),0) remaining_ammount_to_goal,
                                            coalesce(round(SUM(cmpfb.users_reached+ cmptw.users_reached)*${costPerClick}/goal*100*0.5,2),0) goal_percentage_achieved,
                                            (SELECT json_agg(founds) FROM  (SELECT fnd.user_id,fnd.twitter_username,fnd.name,fnd.logo_pic_path
                                                                            FROM foundations_data fnd
                                                                            LEFT JOIN campaigns_foundations cmpf ON  cmpf.user_id = fnd.user_id
                                                                            WHERE cmpf.campaign_id = cmp.campaign_id ) founds) foundations,
                                            (SELECT json_agg(cats)
                                             FROM (SELECT ccat.category_id, cat.description_es
                                                   FROM campaign_categories ccat
                                                   INNER JOIN categories cat ON cat.category_id = ccat.category_id
                                                   WHERE ccat.active = true AND ccat.campaign_id=cmp.campaign_id) cats) categories,
                                            count(distinct(ccb.campaign_contribution_id)) contributors_qty,
                                                      cmp.created_at
                                            FROM campaigns cmp
                                            LEFT JOIN campaign_contributions ccb ON ccb.campaign_id = cmp.campaign_id
                                            LEFT JOIN campaign_contribution_facebook_details cmpfb ON cmpfb.campaign_contribution_id = ccb.campaign_contribution_id
                                            LEFT JOIN campaign_contribution_twitter_details cmptw ON cmptw.campaign_contribution_id = ccb.campaign_contribution_id
                                            WHERE campaign_state_id in (${states})  ${doPaginationClause} ${andSearchClause} ${andCatClause} ${andFoundationIdClause}
                                            GROUP BY cmp.campaign_id
                                            ORDER BY cmp.campaign_id DESC
                                            LIMIT ${itemsPerPage}) camp) camp_array`);`

If I execute the query removing some parts it works, it's like it has problems parsing the query, for example if I reduce one of the subqueries it works, so it's not a problem of the express application, any way of checking if it's a parsing issue of the query??:

```
 return  knex.raw(`SELECT (SELECT count(*) FROM campaigns WHERE campaign_state_id = 1) active_campaigns_count,(SELECT json_agg(camp)
                              FROM (SELECT cmp.campaign_id,
                                    CASE WHEN cmp.campaign_state_id = 1 THEN 'ACTIVE'
                                         WHEN cmp.campaign_state_id = 2 THEN 'PENDING' END as state,
                                          cmp.name,
                                          cmp.pic_url
                                            FROM campaigns cmp
                                            LEFT JOIN campaign_contributions ccb ON ccb.campaign_id = cmp.campaign_id
                                            LEFT JOIN campaign_contribution_facebook_details cmpfb ON cmpfb.campaign_contribution_id = ccb.campaign_contribution_id
                                            LEFT JOIN campaign_contribution_twitter_details cmptw ON cmptw.campaign_contribution_id = ccb.campaign_contribution_id
                                            WHERE campaign_state_id in (${states})  ${doPaginationClause} ${andSearchClause} ${andCatClause} ${andFoundationIdClause}
                                            GROUP BY cmp.campaign_id
                                            ORDER BY cmp.campaign_id DESC
                                            LIMIT ${itemsPerPage}) camp) camp_array`);`

```

I'm calling this function from a route:

`router.post('/get/all',(req,res,next)=>{

    Promise.try(() => {
     return Campaign.getAllCampaigns(knex,req);
     })
     .then((result)=>{
      // console.log(result.rows[0].camp_array[0]);
        return res.send(result.rows[0]);
     })
     .catch((err)=>{
      console.log(err);
       next(500);
     });

});`

I 
3. Reduced test code, for example in https://npm.runkit.com/knex or if it needs real
   database connection to mysql or postgresql, then single file example which initializes
   needed data and demonstrates the problem.

debug true  output for the query shows nothing

`{ method: 'raw',
  sql: 'SELECT (SELECT count(*) FROM campaigns WHERE campaign_state_id = 1) active_campaigns_count,(SELECT json_agg(camp)\n                              FROM (SELECT cmp.campaign_id,\n                                    CASE WHEN cmp.campaign_state_id = 1 THEN \'ACTIVE\'\n                                         WHEN cmp.campaign_state_id = 2 THEN \'PENDING\' END as state,\n                                          cmp.name,\n                                          cmp.pic_url,\n                                          cmp.hashtag,\n                                          cmp.tweet_id,\n                                          cmp.description cause_description,\n                                          cmp.goal,\n                                           (SELECT cr.symbol\n                                            FROM currencies cr WHERE cr.currency_id=cmp.currency_id) currency_symbol,\n                                            coalesce(round((SUM(cmpfb.users_reached+ cmptw.users_reached)*1)*0.5,2),0) current_contributions,\n                                            campaign_ending_date,\n                                            went_inactive_date,\n                                            coalesce(round(goal-(SUM(cmpfb.users_reached+ cmptw.users_reached)*1*0.5),2),0) remaining_ammount_to_goal,\n                                            coalesce(round(SUM(cmpfb.users_reached+ cmptw.users_reached)*1/goal*100*0.5,2),0) goal_percentage_achieved,\n                                            (SELECT json_agg(founds) FROM  (SELECT fnd.user_id,fnd.twitter_username,fnd.name,fnd.logo_pic_path\n                                                                            FROM foundations_data fnd\n                                                                            LEFT JOIN campaigns_foundations cmpf ON  cmpf.user_id = fnd.user_id\n                                                                            WHERE cmpf.campaign_id = cmp.campaign_id ) founds) foundations,\n                                            (SELECT json_agg(cats)\n                                             FROM (SELECT ccat.category_id, cat.description_es\n                                                   FROM campaign_categories ccat\n                                                   INNER JOIN categories cat ON cat.category_id = ccat.category_id\n                                                   WHERE ccat.active = true AND ccat.campaign_id=cmp.campaign_id) cats) categories,\n                                            count(distinct(ccb.campaign_contribution_id)) contributors_qty,\n                                                      cmp.created_at\n                                            FROM campaigns cmp\n                                            LEFT JOIN campaign_contributions ccb ON ccb.campaign_id = cmp.campaign_id\n                                            LEFT JOIN campaign_contribution_facebook_details cmpfb ON cmpfb.campaign_contribution_id = ccb.campaign_contribution_id\n                                            LEFT JOIN campaign_contribution_twitter_details cmptw ON cmptw.campaign_contribution_id = ccb.campaign_contribution_id\n                                            WHERE campaign_state_id in (1)   AND cmp.campaign_id < 9223372036854776000    \n                                            GROUP BY cmp.campaign_id\n                                            ORDER BY cmp.campaign_id DESC\n                                            LIMIT 3) camp) camp_array',
  bindings: [],
  options: {},
  __knexQueryUid: 'f6c37a3d-b034-49c2-bf80-281c6e8839e9' }
`

**Comment by elhigu** [comment]
Please add some minimal test case reproducing the error. At least I'm not going to start debugging that (would take at least half an hour to setup DB and get it run somehow... probably more). 

For example try to reproduce your problem with trivial queries like `select 1` etc. and remove all the code that is not needed for reproducing the problem. 

Also make the reproduction code to be in single runnable file.

**Comment by juanlet** [comment]
I'm quite a noob, it will be quicker to try to rewrite the query without using raw. There's some serious bug with raw parsing. It's the 4th time I have to rewrite queries that works perfectly on pg admin to non-raw format in order to get the query executed.

**Comment by juanlet** [comment]
Hey @elhigu...for some reason I changed to another faster wifi connection and it worked...I don't know if the broadband made the server produce a timeout or something since it took more than 5 seconds to complete the query...I'll kkep you posted if it happens again
