### ISSUE TITLE
A quicker, lighter, less stressful version 1

### ISSUE THREAD

**Issue by martinheidegger** [tgriesser/knex#2425]
# Feature discussion / request

There have been a few of issues _(#1659 most recently)_ about a 1.0 release of knex. And it feels to me like there is a lot of effort about this going on for something that could easily give value with a quick solution: Set the semver to 1.0.

Knex as-is is (widely) used in production. Every API change will have some impact to users and being forthcoming about the fact that the API changed - i believe - is the right thing to do. I understand the hesitation to get into a 1.0 release - one of my first multi-year project years back died in 0.9. From my experience: releasing 1.0 is liberating as well as using semver all the way. You stress less about version numbers and are quicker to communicate the impact of your work.

Please don't repeat my mistake and let knex reach the 1.0

**Comment by martinheidegger** [comment]
> indicates that a project is ready for production use according to maintainers

While I generally agree I think this specifies the case that the **API** is ready for production use - not necessarily every implementation - There are always going to be bugs popping up that need to be fixed (already found ones and not found ones).

**Comment by elhigu** [comment]
Fact that thousands of people is using knex in production slightly hints that knex actually is production ready. 

> A quicker, lighter, less stressful version 1

But I'm not understanding how just changing semver to 1 will make knex any quicker / lighter. Or you just meant that this would be one way to get 1.0 without doing one more rewrite?

Closing as duplicate https://github.com/tgriesser/knex/issues/1331

**Comment by martinheidegger** [comment]
" meant that this would be one way to get 1.0 without doing one more rewrite?" < exactly.

**Comment by elhigu** [comment]
yes
