### ISSUE TITLE
badly formatted debug output for knex:bindings when I use "%" in my string

### ISSUE THREAD

**Issue by capaj** [tgriesser/knex#2430]
# Environment

Knex version: 0.14.2
Database + version: postgre 9.6.2
OS: ubuntu

I have this query:
```javascript
GroupModel.query()
      .where('name', 'like', '%' + searchQuery + '%')
      .andWhere('organisation_id', organisationId)
```

this produces this debug output:
```
  knex:query select "groups".* from "groups" where "name" like $1 and "organisation_id" = $2 +6ms
  knex:bindings [ '+6msales%', 1 ]
```

I believe that `+6ms` should be placed on the end of that line, not inside the array as it is.

**Comment by elhigu** [comment]
Could you give also some knex based example to test this? I suppose that happens when running code with DEBUG=knex:* ?

**Comment by wubzz** [comment]
Not able to reproduce this in local tests. Please reopen if it's still an issue. (With knex example as requested above)
