### ISSUE TITLE
Dynamic createTable

### ISSUE THREAD

**Issue by cjloong** [tgriesser/knex#2431]
# Environment

Knex version:0.14.2
# Bug
We are trying to dynamically create table using the TableBuilder. Code sample is as follows:
```js
const name = "User"
const extraColumns = ["name","description"]

    await pool.schema.createTable(name, function(table){

        // Part 1. Create built in columns
        table.increments("id")

        // Part 2. Dynamic part
        (columns).forEach(name=>{
                table.string(name)
         })
    })
```

2. Error message
table.increments is not a function

However, it is observed that switching part 1 and part 2 around works.

**Comment by elhigu** [comment]
You don't have variable called columns. Cannot reproduce.

**Comment by elhigu** [comment]
And also when obvious bugs are fixed the code works https://runkit.com/embed/isgbqjiyix72, please use runkit to create runnable example next time.
