### ISSUE TITLE
Question/request: Coerce to promise to use with async/await without explicit .then()

### ISSUE THREAD

**Issue by jacobmischka** [tgriesser/knex#2434]
Forgive me if there's a way to do this that I couldn't find, but it would be great if there were a way to coerce the call to a promise without calling `.then()` explicitly, so results could be used with `await` directly.

I'm currently doing the following, which works fine, but it would be nice if there were just a _little_ bit of sugar for it:

```js
const account = await db.first().from('accounts').where({ id }).then(a => a);
```

Thank you!

**Comment by elhigu** [comment]
Query builder is thenable, so you don't have to call `.then()` when using await to resolve it (await value is pretty much the same that when you call `Promise.resolve(value)`, but nicer syntax). 

Just do:

```js
const account = await db.first().from('accounts').where({ id });
```

it works.

**Comment by jacobmischka** [comment]
Interesting, I swore I tried that and it complained about it not actually being a promise. I wonder if it might have been a problem with babel or async-to-generator mangling it, hm.

Thanks for clearing that up!
