### ISSUE TITLE
.returning doesn't work with boolean values

### ISSUE THREAD

**Issue by osdiab** [tgriesser/knex#2438]
# Environment

Knex version: 0.14.2
Database + version: Postgres
OS: Mac OSX

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do

Returning doesn't really work for booleans properly. I expect that if I want an insert to return `true`, that it just returns a boolean. But that's not the behavior:

```
> knex('users').insert([{ id: 1, name: 'hello'}], true).toSQL().sql
'insert into "users" ("id", "name") values (?, ?)'

SHOULD BE: 'insert into "users" ("id", "name") values (?, ?) returning true'

> knex('users').insert([{ id: 1, name: 'hello'}]).returning(true).toSQL().sql
'insert into "users" ("id", "name") values (?, ?) returning "true"'

SHOULD BE: 'insert into "users" ("id", "name") values (?, ?) returning true'

The above will fail because "true" isn't a column.

> knex('users').insert([{ id: 1, name: 'hello'}], false).toSQL().sql
'insert into "users" ("id", "name") values (?, ?)'

SHOULD BE: 'insert into "users" ("id", "name") values (?, ?) returning false'

> knex('users').insert([{ id: 1, name: 'hello'}]).returning(false).toSQL().sql
'insert into "users" ("id", "name") values (?, ?)'

SHOULD BE: 'insert into "users" ("id", "name") values (?, ?) returning false'

This is just inconsistent with the behavior for `true` 
```

2. Error message

N/A

3. Reduced test code, for example in https://npm.runkit.com/knex or if it needs real
   database connection to mysql or postgresql, then single file example which initializes
   needed data and demonstrates the problem.

See above

**Comment by elhigu** [comment]
You can use runkit to do the same that you just did above https://runkit.com/embed/9u0cmf59dyyx . Anyways your examples were good and easy to understand what is the problem.

Only column names are valid parameters to `.returning` http://knexjs.org/#Builder-returning. So your code should have actually thrown an error if knex would validate call parameters better.

However as a workaround you can use knex.raw (it can be passed to pretty much anywhere even that it is not explicitly stated everywhere in documentation):

```js
const rawTrue = knex.raw('?', [true]);
const rawFalse = knex.raw('?', [false]);

knex('users').insert([{ id: 1, name: 'hello'}]).returning(rawTrue)
```
