### ISSUE TITLE
MSSQL Insert into table with Trigger fails

### ISSUE THREAD

**Issue by roemhildtg** [tgriesser/knex#2446]
# Environment

Knex version: 0.14.2
Database + version: MS SQL Server 2017
OS: Windows Server 2012/Windows 7

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do

I am inserting a record into a table. The table has a Trigger with DML in it to do some updates to the record after its inserted.

2. Error message

The target table 'workorder_tasks' of the DML statement cannot have any enabled triggers if the statement contains an OUTPUT clause without INTO clause

3. Reduced test code, for example in https://npm.runkit.com/knex or if it needs real
   database connection to mysql or postgresql, then single file example which initializes
   needed data and demonstrates the problem.

```
    return db(params).insert(data, this.id).then(rows => {
      const id = typeof data[this.id] !== 'undefined' ? data[this.id] : rows[0];
      return this._get(id, params);
    }).catch(errorHandler);
```

**Comment by elhigu** [comment]
cannot reproduce, please add complete runnable code to reproduce the problem.

**Comment by elhigu** [comment]
@Grimace1975 do you have any idea if it is possible to usw triggers with mssql dialect in a way OP describes?

**Comment by roemhildtg** [comment]
The code above inserts a record into a table that has an "INSERT" trigger on the table. It doesn't matter what the cursor does, it immediately throws an error if registered.

**Comment by elhigu** [comment]
@roemhildtg the point of runnable code to reproduce the problem is to easily verify that there is actually a problem and that the one who did the report did nothing wrong (surprisingly often problem is in the user code). So instead of just description what to do the complete code encourages devs to actually test out that problem exists and start solving it and it saves lots of time.

Test case in this case would be something like that

```js
const knex = require('knex')({...});

async function main() {
  await knex.schema.createTable(...);
  await knex.raw('code to create trigger I suppose');
  await knex('table').insert({foo: 'bar});
}

main(); 
```

Anyways need to wait up for someone who know mssql.

**Comment by roemhildtg** [comment]
I see. Yeah I hadn't thought about that. 

Anyways, I have a workaround for this issue...as an alternative to using triggers, I'm just executing the function as a stored procedure at the service.
