### ISSUE TITLE
Accessing queryBuilder.not property changes the query.

### ISSUE THREAD

**Issue by sparebytes** [tgriesser/knex#2447]
# Environment

Knex version: 0.14.2 and 0.13.0
Database + version: Postgres
OS: Windows

# Bug

When accessing the queryBuilder.not property, such as when inspecting the object during a debugging, the query is altered and includes a not clause.

No error is given but the query generated is flawed.

Program:
```javascript
const Knex = require('knex');
const knex = Knex({ client: 'pg' });

let queryBuilder = knex("ABC").select("EFG");

let tmp = queryBuilder["not"];

queryBuilder = queryBuilder.where("HIJ", 123);

if (/\bnot\b/ig.test(queryBuilder.toQuery())) {
    console.error("Why is there a not clause? \n", queryBuilder.toQuery());
}
```

Output:
```
Why is there a not clause?
 select "EFG" from "ABC" where not "HIJ" = 123
```

**Comment by elhigu** [comment]
Query builder's public API doesn't have `.not` method according to knex documentation. Lets reopen if this causes problems in real world. It might be some old undocumented feature, which was meant to be used like: queryBuilder.where().not.where('HIJ', 123); note that query builder is not immutable, so you don't have to do `queryBuilder = queryBuilder.where("HIJ", 123);` just `queryBuilder.where("HIJ", 123);` does the same thing.
