### ISSUE TITLE
Stored procedure call with Out Parameter

### ISSUE THREAD

**Issue by sai070cm118** [tgriesser/knex#2452]
# Questions about how to use knex

Hi!
I've created a stored procedure on my ms sql db that i want to execute with out parameter.

Can i use knex for this?

I have tried with the following.

var rawSql = 'call CreateUser(?,@out_value)';
knex.raw(rawSql,['MyName']);

How to capture the out value here.

**Comment by elhigu** [comment]
There was one older issue about this, please try to look for it.

**Comment by elhigu** [comment]
Actually now I remember. It was about oracles output bindings. How are they used in mssql? This was the oracle's issue https://github.com/tgriesser/knex/issues/1901

**Comment by elhigu** [comment]
You need to checkout mssql driver documentation how to pass output parameters to stored procedures.
