### ISSUE TITLE
Error when composite primary key with a collumn that auto_increments

### ISSUE THREAD

**Issue by Espina2** [tgriesser/knex#2454]
# Environment

Knex version: 0.14.2
Database + version: Mysql 5.7 docker official image
OS: MAC OS High Sierra 

Select applicable tempalate from below.
If issue is about oracledb support tag @ atiertant. For MSSql tag @ Grimace1975 .
Rest of dialects doesn't need tags.

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do**
I want to create a table that have composite primary key, and one of the columns is the id that auto_increments. When I define the that an increments I cannot define an composite primary key.

2. Error message
ER_MULTIPLE_PRI_KEY: Multiple primary key defined

3. Reduced test code, for example in https://npm.runkit.com/knex or if it needs real
   database connection to mysql or postgresql, then single file example which initializes
   needed data and demonstrates the problem.

**Comment by elhigu** [comment]
@Espina2 please provide mysql code that you are trying to generate with knex. Also You have not provided code example causing the error you just listed please read  https://github.com/tgriesser/knex/blob/master/CONTRIBUTING.md#what-is-minimal-code-to-reproduce-bug-and-why-i-have-to-provide-that-when-i-can-just-tell-whats-the-problem-is
