### ISSUE TITLE
Get query builder object on query event

### ISSUE THREAD

**Issue by Gregroam** [tgriesser/knex#2456]
Would be nice to expose the original query builder object on the "query" event. I'd like to add support to my codebase to automatically set some special "updatedAt" and "createdAt" fields whenever the method is "update" or "insert", the method I can get from the "query" event, but altering the query isn't possible.
I can see the reason why the query builder object isn't available here, it's meant to be the last stage before the query executes, perhaps a new event like .on("query-builder") that exposes the query builder object and runs before .on("query")

**Comment by elhigu** [comment]
@Gregroam you might like to look into `objection.js` or some other higher level ORM -like library built on top of `knex`, which provides this kind of hooks and a lot of more functionality commonly needed in application development. 

If someone is interested of implementing this though, I don't see any reason why this couldn't be added to knex. Event would trigger just before compiling builder to a query.

**Comment by wubzz** [comment]
The builder is already technically exposed to the eventhandler via `this`, but that of course becomes a problem when using arrow functions. So I agree we should append the builder as part of [the object](https://github.com/tgriesser/knex/blob/master/src/runner.js#L124) that is sent as first argument to the eventhandler.

However, for the feature that is described, I don't think this is enough. Exposing the builder alone simply means you have to hack into the builder's state - specifically `_single` - to alter the rows to be inserted, something like this:

```javascript
knex(table)
.insert({test: 123})
.on('query', function() {
    //Or for-each if multi-insert
    this._single.insert.createdAt = new Date();
});
```

To me that is not really optimal. I think for this feature it would make a lot more sense to build something similar to a recent addition to knex: `postProcessResponse` - but maybe like `preProcessInsert`, `preProcessUpdate`, etc.

**Comment by Gregroam** [comment]
I figured if you could intercept the query builder in an event, you could just check if `query._method` is `insert` or `update` and then just chain another method on it like
```
knex.on("query-builder", (queryBuilder) => {
  if (queryBuilder._method === "insert") {
    queryBuilder.insert({createdAt: new Date(), updatedAt: new Date()});
  }
})
```

**Comment by wubzz** [comment]
Just realized my comment above only applies to the `query` event emitted on the actual query builder, so `knex.on('query')` has no way of accessing the builder, and I don't think it's a good idea to send this from the [runner](https://github.com/tgriesser/knex/blob/master/src/runner.js#L126) to the [client](https://github.com/tgriesser/knex/blob/master/src/client.js#L127).

So a new event [here](https://github.com/tgriesser/knex/blob/master/src/runner.js#L124) is probably best if we want to support this.

**Comment by elhigu** [comment]
@wubzz I think that event should be emitted just before query compiling starts so that one will still have time to modify it before execution.

But I just saw some events which might already be there, but are just not documented https://github.com/tgriesser/knex/blob/master/src/runner.js#L31 and https://github.com/tgriesser/knex/blob/master/src/util/make-knex.js#L126

Though compilation probably starts right away after emitting 'start' so event handler still might not have time to modify the query.

**Comment by wubzz** [comment]
@elhigu You're absolutely right. This should definitely be documented.

Using that event to do final changes to the builder should be possible as long as asynchronus operations aren't required, which I'm not sure if there's any use case for..

**Comment by elhigu** [comment]
I couldn't find any tests for that either so those needs to be added to prevent regression.

**Comment by wubzz** [comment]
@Gregroam For now you can use the `start` event as described above. [Example usage](https://github.com/tgriesser/knex/pull/2488/files#diff-bfeb3d958a56cecbae4f5f8983fdf195)

**Comment by Gregroam** [comment]
I'm sure people would have use cases for async operations, but for now this would work since I'm just setting the current date on columns

**Comment by Gregroam** [comment]
Update: Got this working exactly how I wanted it to by using the `start` event. Thanks guys

**Comment by Gregroam** [comment]
Coming back to this. The start event doesn't seem to fire for insert/update queries that are transacting a transaction

**Comment by elhigu** [comment]
@Gregroam please open separate issue for that.
