### ISSUE TITLE
alter still sent as part of createTableIfNotExists even if table already exists

### ISSUE THREAD

**Issue by dwightkelly** [tgriesser/knex#2457]
# Environment

Knex version: 0.14.2
Database + version: MariaDB 10.2
OS: Linux

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do

Have the following code to create a table if it doesn't already exist. It has a foreign key in users table that references the auto-incrementing id in accounts table. 

```
        await db
                .schema
                .createTableIfNotExists('accounts', table => {
                        table.increments('id').primary();
                        table.string('name').notNullable();
                })
                .createTableIfNotExists('users', table => {
                        table.increments('id')
                                .primary();
                        table.string('email').notNullable();
                        table.integer('accountID').unsigned()
                                .references('id').inTable('accounts') .notNullable();
                });
```

This generates the following SQL commands

```
  knex:query create table if not exists `accounts` (`id` int unsigned not null auto_increment primary key, `name` varchar(255) not null, `emailDomain` varchar(255), `status` varchar(255) not null, `created_at` timestamp not null default CURRENT_TIMESTAMP, `updated_at` timestamp not null default CURRENT_TIMESTAMP) default character set utf8 +0ms
  knex:query create table if not exists `users` (`id` int unsigned not null auto_increment primary key, `firstName` varchar(255), `lastName` varchar(255), `email` varchar(255) not null, `accountID` int unsigned not null, `ucfUserID` int, `role` varchar(255), `status` varchar(255) not null, `created_at` timestamp not null default CURRENT_TIMESTAMP, `updated_at` timestamp not null default CURRENT_TIMESTAMP) default character set utf8 +27ms
  knex:query alter table `users` add constraint `users_accountid_foreign` foreign key (`accountID`) references `accounts` (`id`) +29ms
```
If the table already exists, 'create table' is a NOP; however, the 'alter' causes the following error message.

2. Error message

{ Error: ER_CANT_CREATE_TABLE: Can't create table `ordb`.`#sql-e9c_e0` (errno: 121 "Duplicate key on write or update")

**Comment by MihaelIsaev** [comment]
The same for me 😞 Please fix it asap

> Knex version: 0.14.2
> Database + version: Postgres v10.1
> OS: macOS

**Comment by elhigu** [comment]
Duplicate https://github.com/tgriesser/knex/issues/1303 I'll add warning to the createTableIfNotExist schema method.

**Comment by MihaelIsaev** [comment]
It's not rude, I just asked for urgent bugfix, because it's a huge bug and people like me want to use your lib in production. but suggestion to use `.hasTable()` (in #1303) before `.createTableIfNotExist()` - it's not the solution, it's really strange IMHO.

**Comment by elhigu** [comment]
Deprecating that method is a solution so that people will stop using it wrong. Using `.hasTable` + `.createTable` is the correct fix for you.

**Comment by koskimas** [comment]
@MihaelIsaev People develop this library on their free time for free. You are in no position to require them to do more free work for you. You accepted these things when you chose to use an open source product.

**Comment by koskimas** [comment]
@MihaelIsaev You appear to be a total fucking asshole 😄

**Comment by elhigu** [comment]
> It's not rude, I just asked for urgent bugfix, because it's a huge bug and people like me want to use your lib in production.

It just implies that in your opinion your use of this lib is more important than the others and that contributors doesn't know which are the most important things to fix.
