### ISSUE TITLE
Array as tableName causes addition of 'as `0`' to query (0.14)

### ISSUE THREAD

**Issue by DataTables** [tgriesser/knex#2459]
# Environment

Knex version: 0.14.2
Database + version: MySQL Ver 14.14 Distrib 5.7.20
OS: Fedora 27

# Bug

> 1) Explain what kind of behaviour you are getting and how you think it should do

As of 0.14 if an array is passed in as a tablename (in the constructor or `from()`) the query adds `as 0` to the `from` statement, causing issues with joins:

```
await db(['app_user']).select('user_id');
```

> 2) Error message

```
select `user_id` from `app_user` as `0`
```

That's not a problem in this specific case, but when you introduce a left join, the table alias is an issue.

> 3) Reduced test code

https://runkit.com/embed/gl5tzy0nw00h

I'm not honestly sure if this is a bug or not. 0.13 didn't as the alias and there is no mention of it in the upgrade notes, but equally there is no mention of using the tableName as an array, so it might just be a mistake on my part of how I'm using the API, but I thought I'd open this just in case an array should be allowed (something is happening with it after all).

**Comment by elhigu** [comment]
This is side effect of supporting object syntax for aliases https://github.com/tgriesser/knex/pull/2227 which is documented here: http://knexjs.org/#Builder-identifier-syntax 

As far as I know passing array there has never been officially supported.

**Comment by DataTables** [comment]
Thanks!
