### ISSUE TITLE
Nested transactions

### ISSUE THREAD

**Issue by electrotype** [tgriesser/knex#2462]
Let's say I have a `delete` function which uses a transaction. Something like : 

```
public async delete(topicCode: string): Promise<void> {
    await client.transaction(async trx => {
      await trx('topics_channels_join').delete().where('topic_code', topicCode);
      await trx('topics').delete().where('code', topicCode);
    });
}
``` 

Then I have a `replace` function  which needs to use that `delete` function. But a transaction is also started in the `replace` function. For example:
```
public async replace(topic: Topic): Promise<void> {
    await client.transaction(async trx => {
      await delete(topic.code);
      await create(topic);
    });
}
```
I guess this code _doesn't work_ because the transaction object in the parent `replace` function is not the same as the one in the called `delete` function!

So what would be the recommended pattern to deal with such nested transactions?

I guess the `replace` function needs to pass its own transaction object to the `delete` function. But remember that the `delete` function can also be called _directly_. So how should I implement this?

Thanks in advance.

**Comment by joelmukuthu** [comment]
I would pass the transaction as an optional argument to both `replace` and `delete`. If passed, use it, else create a new transaction in each method. For example with `delete`: 

```js
const _delete = async (topicCode, trx) => {
  await trx('topics_channels_join').delete().where('topic_code', topicCode);
  await trx('topics').delete().where('code', topicCode);
};

public async delete(topicCode: string, trx: any): Promise<void> {
    if (trx) {
      return _delete(topicCode, trx);
    }
    return client.transaction(async trx => _delete(topicCode, trx));
}
``` 

FYI, these types of questions should be asked in stackoverflow to lessen the workload the knex maintainers have to do, since there are a lot of other issues created daily that have to do with actual knex development (bugs, features etc).

**Comment by joelmukuthu** [comment]
Hehe, this might be a question for the maintainers after all then :)

But if you're willing to push on with this idea and are working with classes and have a similar api with all your methods (that's a lot of and's), you could add a method `withTransation(method, ...args)` that does the `if..else` for any method you give it

**Comment by elhigu** [comment]
I believe you need to pass transaction object to all the functions that needs to be ran in the same transaction. Sounds like your approach is coming from hibernate/java world, where that context/transaction can be saved in thread local storage and passed automatically to every query made in the same thread. In node that is not possible, because all the code is running in the same thread. So maybe you should initialize completely new instance of your class and pass transaction /connection that queries should use in constructor (or similar) so when you need to do multiple queries they can be sent automatically to the same connection... This is app design issue that cannot be helped in knex side.

**Comment by electrotype** [comment]
Exactly, I'm trying to get some sort of thread local functionality for the transaction.

I'm trying this library: 
https://github.com/othiym23/node-continuation-local-storage

It's a little bit scary, but who knows?

**Comment by electrotype** [comment]
Wow, it _does_ work. 

I guess I'll have to write lots of tests, but my first ones all pass...

I use this as a base class for my repositories : 

```typescript
import * as continuationLocalStorage from 'continuation-local-storage';
import * as knex from 'knex';
import { getDciPostgreSQLKnexClient } from '../clients/dciPostgreSQLClient';

export class PostgreSQLBaseRepository {
  private CLS_KNEX_CLIENT_KEY = 'PostgreSQLBaseRepository_knexClient';

  private knexClientStore: continuationLocalStorage.Namespace = continuationLocalStorage.createNamespace(
    'PostgreSQLBaseRepository_knexClientStore'
  );

  protected isTransactionClient = (client: knex): client is knex.Transaction => {
    return client && 'commit' in client && 'rollback' in client;
  };

  protected runInCLSContext = async <T>(client: knex, fnt: (client: knex) => Promise<T>): Promise<T> => {
    return await this.knexClientStore.runAndReturn<Promise<T>>(async (): Promise<T> => {
      this.knexClientStore.set(this.CLS_KNEX_CLIENT_KEY, client);
      const result = await fnt(client);
      return result;
    });
  };

  protected async withTransaction<T>(fnt: (client: knex) => Promise<T>): Promise<T> {
    return await this.withClient(fnt, true);
  }

  protected async withClient<T>(fnt: (client: knex) => Promise<T>, transactional: boolean = false): Promise<T> {

    const existingClient = this.knexClientStore.get(this.CLS_KNEX_CLIENT_KEY);

    if (existingClient && (!transactional || this.isTransactionClient(existingClient))) {
      return await fnt(existingClient);
    }

    const client = getDciPostgreSQLKnexClient();

    if (transactional) {
      return await client.transaction(async trx => {
        return await this.runInCLSContext<T>(trx, fnt);
      });
    }

    return await this.runInCLSContext<T>(client, fnt);
  }
}

```
And then something like : 

```typescript
public async delete(topicCode: string): Promise<void> {
    return await this.withTransaction<Topic>(async (client: knex) => {
      await client('topics_channels_join').delete().where('topic_code', topicCode);
      await client('topics').delete().where('code', topicCode);
    });
}

public async replace(topic: Topic): Promise<void> {
    return await this.withTransaction(async (client: knex) => {
        await delete(topic.code);
        await create(topic);
    });
}
```

So in case it can help someone, one day!
Use at your own risks! 
I'll try to update this issue if there are new developments on my side...

**Comment by electrotype** [comment]
To investigate : https://github.com/TimBeyer/cls-bluebird
Would that help or even be required since Knex uses Bluebird?

**Comment by elhigu** [comment]
@electrotype when you have multiple requests going on at the same time I still don't see how this thread local store emulation work. You still need to pass context / client to class instance to  be able to separate different queries to different transactions.

**Comment by electrotype** [comment]
@elhigu This is the black magic of "continuation-local-storage'". Everything that is ran inside that part :

```
return await this.knexClientStore.runAndReturn<Promise<T>>(async (): Promise<T> => {
  // ...
});
```
... will have access to the same CLS context and be able to share common object instances. Even when things are called _asynchronously_.

As I said, this is black magic and I'm not even sure it will work with Knex. I don't know if errors would be handled properly, if a context cleanup must be done or even if manual `commits`/`rollbacks` would sometimes be required!

But the "continuation-local-storage" library _does_ work. It is like thread local. Where I work, we already use this library to be able to access the same `correlation id` (a string), wherever we are in the code, and it works well. But dealing with database connections and transactions is way more scary.

**Comment by electrotype** [comment]
Well, forget it for now :
https://github.com/othiym23/node-continuation-local-storage/issues/124
https://github.com/othiym23/node-continuation-local-storage/issues/98

It seems there is some work done to provide a stable solution, but it's here yet.

**Comment by urbandroid** [comment]
Asking about java world concept to js people, lol classic. They are not that advanced. i will keep tracking this issue to witness origin of a new cargo cult.

**Comment by gustavonecore** [comment]
@electrotype I came across with the same solution as you, using ObjectionJs, with a custom transaction manager, but then the concurrency hiting me design, since I can't ensure the isolation of every transaction.

Did you find any other solution for this knex stuff?

**Comment by electrotype** [comment]
What we do now (it sucks but works), is to pass a "context" parameter (as the first parameter) in _each and every_ methods of our system which is part of a service or a repository. In that context object, we have logic that creates, stores and reuses a Knex transactional client, when required. In other words, this object manages the transactional scopes. 

Sadly I can't share our code... Hope it helps a little.

**Comment by gustavonecore** [comment]
Alright, sounds good.
But, I'm curious how you are handling multiple connections and the isolation level for those transactions...
Are you using CLS somehow for that?
I'm thinking to attach every request into my transaction manager and then pass it to the command/handlers (hexagonal apporach).

Have you tried that solution with concurrent clients?

Thanks for youw answer!!!
