### ISSUE TITLE
Is there a way to get migration file to go into specified schema ?

### ISSUE THREAD

**Issue by walshe** [tgriesser/knex#2465]
it seems to put the knex migrations file just outside the schemas that i put my tables in 

```

var config = require("../../config")


exports.up = function (knex, Promise) {
  return knex.schema.withSchema(config.get('/db/postgresSchema')).createTable('inventoryStats', function (t) {
    t.string('inventoryId').primary()
    t.string('vin').notNull()
    t.integer('version').notNull()
    t.dateTime('inventoryFirstFoundDate').notNull()
    t.string('currentStatus').notNull()
    t.dateTime('currentStatusFirstDate').notNull()
    t.integer('currentStatusConsecutiveDays').notNull()
    t.dateTime('forSaleFirstDate').nullable()
    t.string('firstListedPrice').nullable()
    t.string('currentListedPrice').nullable()
    t.string('currentListedPriceFirstDate').nullable()
    t.integer('currentListedPriceConsecutiveDays').nullable()
    t.dateTime('inventoryServiceLastFoundDate').notNull()
    t.timestamps(true)
  })
}

exports.down = function (knex, Promise) {
  return knex.schema.withSchema('aggregated-inventory-svc').dropTable('inventoryStats')
}
```

**Comment by elhigu** [comment]
I'm not really sure about the question here... Do you mean: "Is there a way to tell knex to store migrations and migrations_lock table to a certain schema?" And if so do you mean that you would like to tell that schema in migration file or should that be described in knex configuration or how?

**Comment by walshe** [comment]
yes, when I run the migration..

`knex migrate:latest --knexfile './db/knexfile.js' --cwd .`

it creates my table inside the specified schema, but the knex_migrations and knex_migrations_lock tables are stored OUTSIDE the schema. Is there a way to have these also in the schema to keep things contained.. ?
thanks

**Comment by elhigu** [comment]
Currently, no there is not, unless db driver allows somehow to set it up. In that case it could be controlled e.g. with environment variable.

**Comment by elhigu** [comment]
I believe this is reasonable feature to have, but needs proper feature request issue for that.
