### ISSUE TITLE
limit is not applied when used with patch

### ISSUE THREAD

**Issue by capaj** [tgriesser/knex#2466]
# Environment

Knex version: 0.14.3
Database + version: pg 6.4.2
OS: ubuntu 17.10

# Bug

I was trying to make objection.js model to update 10 items with couple of conditions:
```javascript
await NotificationQueueModel.query()
    .patch({
      state: 'PROCESSING',
      pid: batchId
    })
    .whereNull('state')
    .andWhere(builder => {
      builder.where('scheduled', '<=', timestamp).orWhereNull('scheduled')
    })
    .orderBy('created_at', 'asc')
    .limit(10)
```

The resulting query looks like this:
```
  knex:query update "notification_queue" set "state" = $1, "pid" = $2, "updated_at" = $3 where "state" is null and ("scheduled" <= $4 or "scheduled" is null) +1s
  knex:bindings [ 'PROCESSING',
  knex:bindings   'f34e0a43ec33901c',
  knex:bindings   2018-02-12T17:58:22.964Z,
  knex:bindings   moment("2018-02-12T18:58:22.964") ] +1s
```

Is this correct? I think postgreSQL does allow to use the `LIMIT` with update query so why did knex ignore it?

I did resolve my issue by doing a select instead of `UPDATE`. There `LIMIT` is applied correctly, but I really wonder where the problem is.

**Comment by elhigu** [comment]
Why do you think postgresql supports limit in update?

```
knex_test=# update accounts set last_name = 'foo';
UPDATE 47
knex_test=# update accounts set last_name = 'foo' where last_name = 'bar';
UPDATE 0
knex_test=# update accounts set last_name = 'foo' where last_name = 'bar' limit 1;
ERROR:  syntax error at or near "limit"
LINE 1: ...ounts set last_name = 'foo' where last_name = 'bar' limit 1;
                                                               ^
knex_test=# 
```

**Comment by capaj** [comment]
@elhigu thanks, should have tried it in postgre console before posting.

Just one more question-wouldn't we want to throw an error in the query builder when limit is used with update? It's rather and edgecase, but it appears on stackoverflow for example here:

https://stackoverflow.com/questions/6289729/mysql-update-query-with-limit
https://stackoverflow.com/questions/11432155/limiting-postgresql-update-command

currently knex just ignores it which can badly suprise you if you're like me and you don't know that limit cannot appear in `UPDATE` query.  There should be a condition which checks this already and skips the limit. Wouldn't it make more sense to throw instead of just skipping?

**Comment by elhigu** [comment]
I would be happy to accept pull requests, which are throwing errors when knex are used in a wrong way... to me silently ignoring stuff from builder is worse that actually building invalid SQL. At least from invalid SQL we get error from server side.

Though many times it is hard work to investigate if certain combination actually is allowed in some SQL dialects, so adding those errors and testing them is not always trivial.

**Comment by capaj** [comment]
@elhigu good to hear. 
Quickly searching for dialects it seems no other dialect supports it.
SQLite supports it only with a special compile flag(https://stackoverflow.com/a/29074519/671457), so I'd ignore that.
MsSQL has it's special `top`: https://stackoverflow.com/a/1198404/671457 which is unsopported by knex
Postgre and Mysql doesn't support it like we've already established. So I'd say it would be best to throw when limit is used with `UPDATE` query. I will try to pull together some PR when I get some time.
