### ISSUE TITLE
Knex in browser security

### ISSUE THREAD

**Issue by richbai90** [tgriesser/knex#2467]
# Environment

Knex version: 0.14.3
Database + version: mysql 5.x
OS: Windows

I'm building an in browser reporting engine, and using knex to generate the queries. I'd like to send the sql object to the server to be executed on the database, but I want to know if that is secure. I cannot use prepared queries because I want the end user to be able to report on whatever is available.

What I have done is added a layer to knex that checks what is being submitted and prevents malicious sql from being submitted in the first place, but this is far from perfect.

I just want to know if what I am doing is considered a safe or good practice.

Ideally I would like to be able to submit a sql object to the server and use knex to submit it, and knex would have some way of preventing me from doing anything dangerous assuming a malicious individual got through whatever browser defenses I may have put in place, something that wouldn't be very hard for even the slightest devoted hacker.

**Comment by elhigu** [comment]
No it will not be safe and cannot be considered good practice. Also if you have not designed indexing to work well with your reporting queries (which might be impossible or inefficient if user can choose to query what ever he likes), reporting queries can be awfully slow. 

What is your strategy to be able to decide if query is safe to run or not?

Also this is just general question about sql and app design, so stackoverflow would be the correct place to ask this.

If you give only read access to user to DB and don't worry that user can make query, which eats up all the memory and runs forever and there is only data that can be accessed that one user... maybe it could be considered as a  reasonable solution. As a general case no.
