### ISSUE TITLE
hasColumn inside .table() causes column creation to fail

### ISSUE THREAD

**Issue by blackbetty** [tgriesser/knex#2470]
# Environment

Knex version:
Database + version: Postgres 9.6
OS: MacOS High Sierra 10.13.3

Select applicable tempalate from below.

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do
I am trying to migrate a table, and trying to be safe about applying the actual column creation. When I nest a call to table.text() inside hasColumn() inside a table() call, the column never gets created. Subsequent migrations which look for that column never find it, and cause defaults I set to never get applied.
2. Error message
 None
3. Reduced test code, for example in https://npm.runkit.com/knex or if it needs real
   database connection to mysql or postgresql, then single file example which initializes
   needed data and demonstrates the problem.
```
const tableName = 'tableName';
const columnName = 'columnName';

exports.up = function (knex, Promise) {
  return knex.schema.table(tableName, (t) => {
    return knex.schema.hasColumn(tableName, columnName).then((exists) => {
      if (exists == false) {
        try {
        t.text(columnName); 
      }
        catch (e) {
          console.log(e);
        }
      } 
    });
  });
};
```

Nothing seems to happen, the catch doesn't get triggered, I have been pulling my hair.  When I remove the hasColumn() call, it all works as expected.

**Comment by elhigu** [comment]
you should not do async code inside alter table handler. Something like this should work:

```js
exports.up = function (knex, Promise) {
  return knex.schema.hasColumn(tableName, columnName).then((exists) => {
    // exist might be 0/1 not necessarily false thougs probably with == operator 
    //it would work anyways
    if (!exist) { 
      return knex.schema.table(tableName, t => {
        t.text(columnName); 
      });
    }
  });
};
```

**Comment by blackbetty** [comment]
@elhigu I saw this last week but forgot to respond. Thanks for answering so quickly, sorry to plug up your issues.

**Comment by jhammond2012** [comment]
> you should not do async code inside alter table handler. Something like this should work:
> 
> ```js
> exports.up = function (knex, Promise) {
>   return knex.schema.hasColumn(tableName, columnName).then((exists) => {
>     // exist might be 0/1 not necessarily false thougs probably with == operator 
>     //it would work anyways
>     if (!exist) { 
>       return knex.schema.table(tableName, t => {
>         t.text(columnName); 
>       });
>     }
>   });
> };
> ```

Just in case someone stumbles across this and doesn't pay attention as I do 😆... The second call of `exists` is missing a 's'. It should be `if (!exists) { `
