### ISSUE TITLE
Raw Knex Binding Error : "Undefined binding(s) detected when compiling RAW query"

### ISSUE THREAD

**Issue by CamShft** [tgriesser/knex#2478]
# Environment

Knex version: 0.0.53
Oracle
# Bug

1. try to bind value to SQL command 
2. Undefined binding(s) detected when compiling RAW query

3. 
SLQ command : 
V_TRX_NUMBER                 :=     :trxNumber;
   V_AMOUNT                     :=     :amount;
   V_AMOUNT_APPLIED             :=     :amountApplied;
   V_AMOUNT_APPLIED_FROM        :=     :amountAppliedFrom;
   V_TRANS_TO_RECEIPT_RATE      :=     :transToReceiptRate;
   V_APPLY_DATE                 :=     TO_DATE( :applyDate , v_date_format);
   V_CURRENCY_CODE              :=     :currencyCode;
   V_EXCHANGE_RATE_TYPE         :=     :exchangeRateType;
   V_EXCHANGE_RATE              :=     :exchangeRate;
   V_DEPOSIT_DATE               :=     TO_DATE( :depositDate , v_date_format);
   V_GL_DATE                    :=     TO_DATE( :glDate , v_date_format);
   V_RECEIPT_DATE               :=     TO_DATE( :receiptDate , v_date_format);
   V_RECEIPT_COMMENTS           :=     :receiptComments;
   V_RECEIPT_NUMBER             :=     :receiptNumber;
   V_CUSTOMER_NUMBER            :=     :customerNumber;
   V_CUSTOMER_RECEIPT_REFERENCE :=     :customerReceiptReference;
   V_RECEIPT_METHOD_ID          :=     :receiptMethodId;
....

function kenw.raw : 
let result = await client.raw(createReceipt, {
                "trxNumber": receipt.transactionNumber,
                "amount": receipt.amount,
                "amountApplied": receipt.amountApplied,
                "amountAppliedFrom": receipt.amountAppliedFrom,
                "transToReceiptRate": zero, // To validate
                "applyDate": applyDate,    // To validate
                "currencyCode": receipt.currencyCode,
                "exchangeRateType": receipt.exchangeRateType,
                "exchangeRate": receipt.exchangeRate,
                "depositDate": depositDate,
                "glDate": glDate,   // To validate
                "receiptDate": receipt.dateCreated,
                "receiptComments": receipt.comments,
                "receiptNumber": receipt.referenceNumber,
                "customerNumber": receipt.customerNumber,
                "customerReceiptReference": receipt.customerReceiptNumber,
                "receiptMethodId": receiptMethodId
            });

Why i got this error each time i try to launch my function.

It seems good, like the Knex doc.

Thank for your help !

**Comment by wubzz** [comment]
@CamShft This error is thrown when one or more values of the bindings is undefined, as the error describes. There are examples of this in the docs.

The reason we have added this error is because knex cannot possibly know what to do when a value is missing - should it set the column to default value? should it set it to null? etc.

This also acts as a safeguard against developer error. It's highly unlikely you as a developer actually intended to run a query with undefined values.

In your case one or more of the properties is undefined when you run your query.
