### ISSUE TITLE
Missing wrapIdentifier for typescript :(

### ISSUE THREAD

**Issue by d30jeff** [tgriesser/knex#2482]
# Environment
Node v8.9.0 + Typescript

Knex version: **"^0.14.3"**,
Database + version: **psql (PostgreSQL) 9.6.3**
OS: **Mac OS High Sierra**

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do
Unable to use wrapIdentifier in connection definition.

2. Error message
```
src/models/Database.ts(18,9): error TS2345: Argument of type '{ client: string; connection: string; wrapIdentifier: (result: any, queryContext: any) => void; }' is not assignable to parameter of type 'Config'.
  Object literal may only specify known properties, and 'wrapIdentifier' does not exist in type 'Config'.
```
3. Reduced test code, for example in https://npm.runkit.com/knex or if it needs real
   database connection to mysql or postgresql, then single file example which initializes
   needed data and demonstrates the problem.

**Comment by elhigu** [comment]
knex typings are not maintained by us, please report issue to https://github.com/DefinitelyTyped/DefinitelyTyped
