### ISSUE TITLE
Migrations warning - demands usage of `hasTable` before `createTable`

### ISSUE THREAD

**Issue by Kid-Binary** [tgriesser/knex#2489]
# Environment

Knex version: 0.14.3
Database + version: sqlite3, 3.1.13
OS: Ubuntu 16.04.3 LTS

# Bug

1. Behaviour

Writing simplest migration `up/down` functions with appropriate `createTable/dropTable` statements and then running it via `knex migrate:latest` causing library to spit warnings, apart from that, everything works fine. Following proposed solution, `hasTable` was integrated into the migration operation, but the warning remains.

2. Warning message

> Knex:warning - Use async .hasTable to check if table exists and then use plain .createTable. Since .createTableIfNotExists actually just generates plain "CREATE TABLE IF NOT EXIST..." query it will not work correctly if there are any alter table queries generated for columns afterwards. To not break old migrations this function is left untouched for now, but it should not be used when writing new code and it is removed from documentation.

Nevertheless, final output is optimistic:

> Batch 1 run: 1 migrations
/home/dvovk/Code/knex-probe/migrations/migrations/20180219121713_initial.js

3. Test code:

```javascript
exports.up = function (knex) {
  return knex.schema.hasTable('users', (exists) => {
    if (!exists) {
      knex.schema.createTable('users', (table) => {
        table.increments('id');
        table.string('username');
        table.string('password');
      });
    }
  });
};

exports.down = function (knex) {
  return knex.schema.dropTable('users');
};
```

**Comment by elhigu** [comment]
Duplicate. That warning is coming from mirgration APIs internal code and is fixed in 0.14.4

**Comment by falcon-lin-development** [comment]
@Damaged-Organic  In knex version 0.20.8
you code will not create a table as expected. An additional 'return' is required.
`
```
return knex.schema.hasTable('users', (exists) => {

    if (!exists) {

      return knex.schema.createTable('users', (table) => ...
`

**Comment by jonny-irving** [comment]
Has something changed since this was being looked at as the `hasTable` method only accepts one argument now. The table name.
