### ISSUE TITLE
Returning Data from SQL script Binding

### ISSUE THREAD

**Issue by CamShft** [tgriesser/knex#2490]
Hi, want know how it's possible to return a result from a file PSQL to knex, 
for i can use it in code.

I tried knex.returning('message'); 
knex.raw(code here) 
and in my SQL FILE where my parameter are binded : 
returning variable into {"Msg": "message"}

But i hurt an error.

Thanks for your help.

**Comment by elhigu** [comment]
Hi, I'm sorry, but I couldn't understand the question. 

Could you write more complete example code what are you trying to do and what error are you getting?

**Comment by CamShft** [comment]
ok by example i need communique to a PSQL With knex.

I create my request via a SqlFile.

and i call RAW.

Like this : 
let result = await client.raw(createMultipleInvoices /** <-- In this is the contain of the SQL file. **/, {
                "p_batch_source_json": JSON.stringify(simonBatchSource),
                "p_invoice_headers_json": JSON.stringify(simonInvoiceHeaders),
                "p_invoice_lines_json": JSON.stringify(simonInvoiceLines)
            });

All this work fine, but now i would like to get some values from SQL like the status, msg_data and msg_count.

but i search in doc for get value from PSQL with knex and i don't found exactly want i need.

Can you help me please.

**Comment by elhigu** [comment]
As far as I know knex does not support sending multiple queries in single knex.raw command with postgresql.

By PSQL do you mean postgresql server or psql commandline client? I'm pretty sure that the thing you are trying to do is not possible with knex.

**Comment by CamShft** [comment]
it's PostgresSQL,

if i have understand, when we use raw, we can't get parameter from the result of SQL ? 

Because i had transform the old code that use a connexion and bindvars.
after the transaction we can get, in the result, the outbind.

`resolve(connexion.execute(sqlTemplateCreateInvoice, bindvars, { autoCommit: false }).then((result: any) => {
        const apiInfo = 'AR_INVOICE_API_PUB.create_invoice';
        const responseUndefined = 'undefined';
        let responseJSON: any = responseUndefined;
        if (result && result.outBinds && result.outBinds.reponseJSON) {
          context.LogDebug(`${logPreffix}result.outBinds.reponseJSON: ${result.outBinds.reponseJSON} .`);

          const reponseJSON = JSON.parse(result.outBinds.reponseJSON);`

**Comment by elhigu** [comment]
I would suggest checking out node-oracledb driver and use that directly for this use case. If you are able to make it work there, I may come up with some way how to do it with knex too.

Or maybe if someone else is able to understand the problem can help.

**Comment by CamShft** [comment]
OK but is it possible to bind variables to a transaction file sql, and fill it with the result of the execute store proc. 

Exemple : 
```
//SQL file
Begin;
// Store proc
storproc.function(
       ...                             => ...
       x_return_status        => l_return_status,
       x_msg_count            => l_msg_count,
       x_msg_data             => l_msg_data);

 :reponseJSON :=l_return_status;
End;
```

The call : 
```
let response =  ' ';
            let result = await client.raw(createMultipleInvoices, {
                "p_batch_source_json": JSON.stringify(simonBatchSource),
                "p_invoice_headers_json": JSON.stringify(simonInvoiceHeaders),
                "p_invoice_lines_json": JSON.stringify(simonInvoiceLines),
                "reponseJSON": response
            });
```
what i expect : 

in result i want have the l_return_status, l_msg_count and l_msg_data  value.


is it what i tried to do. 

Thanks

**Comment by elhigu** [comment]
Have you checked out this issue https://github.com/tgriesser/knex/issues/1901

**Comment by CamShft** [comment]
@elhigu  i seen that issue but i don't think we try to do the same thing.
Can you provide me a example where you use a sql with a store procedure.
But it need return some value after the result of the commit of the store proc with Knex raw ? 

May be the documentation need to have an example for a BIND_OUT parameter and BIND_IN ?  


```
let result = await client.raw(createMultipleInvoices, {
           "json1": JSON.stringify(json), <-- here all be right
           "json2": JSON.stringify(json2), <-- here too
           "json3": JSON.stringify(json3), <-- here too
            "responseJSON" : { type: oracledb.NUMBER, dir: oracledb.BIND_OUT, maxSize: 50000 } but here is the test where i want to get some result in this variable.
 });
```

or if you have an idea how we can return some value in the result variable.
Because the SQL file contain a begin and End, and the last command that i doing is call store proc.
And i pass json in string for loop on this, and fill some table for we can call the store proc with the table filled.
SQL File : 
   StoreProc(
       table create with json1=> here,
        table create with json2=> here,
        table create with json3=> here,
       x_return_status        => l_return_status,
       x_msg_count            => l_msg_count,
       x_msg_data             => l_msg_data);
     

and i know all work fine but after this i want to return the tree last variables and i got nothing in result.

May be you can hepl me with that.

**Comment by elhigu** [comment]
@CamShft try it directly with `oracledb` driver. It might be that knex just doesn't support setting binding type to `oracledb.BIND_OUT` knex documentation should not have any information about that, because it is feature of certain driver, which is actually sending queries to the database.
