### ISSUE TITLE
create-react-app + knex package: yarn test fails 

### ISSUE THREAD

**Issue by giona69** [tgriesser/knex#2497]
# Environment
MacOSX
React app
create-react-app template

Knex version: 0.14.4
Database + version: N/A
OS: N/A

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do
used together with react, yarn test is failing
packages knex and react-scripts cannot work together
launching yarn test is failing
removing knex package is working

2. Error message
this is the error message launching yarn test:

2018-02-20 10:15 node[4772] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
2018-02-20 10:15 node[4772] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
events.js:137
      throw er; // Unhandled 'error' event
      ^

Error: Error watching file for changes: EMFILE
    at _errnoException (util.js:1003:13)
    at FSEvent.FSWatcher._handle.onchange (fs.js:1382:9)
error Command failed with exit code 1.

3. files to reproduce bug
this is the pckage json that fails, to reproduce the bug:

{
  "name": "template-react-app",
  "version": "0.1.0",
  "private": true,
  "engines": {
    "node": ">=6.1.1"
  },
  "dependencies": {
    "express": "~4.15.2",
    "knex": "^0.14.4",
    "prop-types": "^15.6.0",
    "react": "^16.2.0",
    "react-dom": "^16.2.0",
    "react-redux": "^5.0.6",
    "react-router-dom": "^4.2.2",
    "react-router-redux": "^5.0.0-alpha.9",
    "react-scripts": "1.1.1",
    "redux": "^3.7.2",
    "redux-logger": "^3.0.6",
    "redux-thunk": "^2.2.0",
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test --env=jsdom",
    "lint": "eslint . --ext js --ignore-path .gitignore",
    "eject": "react-scripts eject"
  },
  "devDependencies": {
    "babel-eslint": "^8.2.1",
    "enzyme": "^3.3.0",
    "enzyme-adapter-react-16": "^1.1.1",
    "eslint": "^4.17.0",
    "eslint-config-google": "^0.9.1",
    "eslint-plugin-babel": "^4.1.2",
    "eslint-plugin-node": "^6.0.0",
    "eslint-plugin-react": "^7.6.1",
    "eslint-watch": "^3.1.3",
    "fetch-mock": "^6.0.0",
    "react-test-renderer": "^16.2.0",
    "redux-devtools": "^3.4.1",
    "redux-mock-store": "^1.5.1"
  }
}

**Comment by elhigu** [comment]
I think you should first check out what create react app people can help about this. Has any knex version worked like this?

**Comment by giona69** [comment]
no minimal code needed, just include the knex library in create-react-app repo, will cause tests to crash. I'll post the same there, thanks.

**Comment by elhigu** [comment]
minimal code in this case would be then shell commands showing fast way to reproduce the problem + output of that command.
