### ISSUE TITLE
Choosing enconding at PostgreSql

### ISSUE THREAD

**Issue by woj1965** [tgriesser/knex#2498]
# Environment

Knex version: 0.14.4
Database + version: PostgreSql 9.4
OS: Windows/Ubuntu

# Feature discussion / request

1. Explain what is your use case
Unfortunately I need access a postgresql database (hosted in a windows server) using a **SQL_ASCII** encoding. When I use the Knex I got the message: `Unhandled rejection error: invalid byte sequence for encoding "UTF8": 0xc1 0x52`. 

2. Explain what kind of feature would support this
This feature will allow choose the postgresql database encoding

3. Give some API proposal, how the feature should work
A feature at database connection like **encoding**, or a function to use this in querys (select, insert, update, etc.)

**Comment by elhigu** [comment]
How is this implemented with pg driver? Does PG driver support different encodings? I don't think this should be handled in any ways in knex level.

**Comment by elhigu** [comment]
Lets reopen if there is something that needs to be done in knex side.
