### ISSUE TITLE
Ability to hide warnings

### ISSUE THREAD

**Issue by faustbrian** [tgriesser/knex#2512]
As already mentioned a week ago in this PR https://github.com/tgriesser/knex/pull/2471 the warning that was added with that PR makes it impossible to use knex in a pure CLI environment if you are using an ORM like Bookshelf or Objection as your terminal with get spammed with the warning even though you yourself are not calling the `returning` method, the ORMs do.

As @elhigu mentioned in the comments a feature request is to make it possible to plug in your own logging implementation in the future but until that comes would something like `(returning && process.env.SUPPRESS_WARNINGS)` be an option?

It would be awkward to be forced to fork purely to hide this 1 warning message https://github.com/tgriesser/knex/pull/2471/files#diff-9e1276d680a5451020b184cb3f7fa802R15 in a CLI environment.

**Comment by wubzz** [comment]
Seems [something](https://github.com/tgriesser/knex/commit/5b6601d1d709d676691dacb2502619ba0f3887ee) is in the works already

**Comment by faustbrian** [comment]
This was marked in some issue as `Planned for 1.0` which I guess is still quite some time away based on the current version number or did that plan change?

My current issue is that I was using knex just fine in a production CLI application with `0.14.3` but `0.14.4` introduced a bug fix I also need but the same version also introduced the warning message for sqlite returning so I am currently locked at `0.14.3` without the bug fix because of the warning message.

**Comment by wubzz** [comment]
Closing this as overriding log functions is now possible: https://knexjs.org/#Installation-log

If this doesn't cover the issue let's reopen.
