### ISSUE TITLE
Pass querybuilder as argument of nested where clauses

### ISSUE THREAD

**Issue by rohannair** [tgriesser/knex#2517]
# Feature discussion / request
Given this use case:
```javascript
knex('foos').where(function () {
  this.where('x', 3).orWhere('x', 4)
}).andWhere(function () {
  this.where('y', 2).orWhere('y', 4)
})
```

There's a lot of reliance on `this` and adding arrow functions binds the functions to a different context. If the querybuilder wax passed in as an argument to the where callback it could be a lot cleaner and more straight forward:

```javascript
knex('foos')
  .where(q => q.where('x', 3).orWhere('x', 4))
  .andWhere(q => q.where('y', 2).orWhere('y', 4))
```

**Comment by wubzz** [comment]
While unfortunately not documented, that is actually exactly how it works already.

```javascript
const knex = require('knex')({
	client: 'pg',
});

console.log(
	knex('foos')
  .where(q => q.where('x', 3).orWhere('x', 4))
  .andWhere(q => q.where('y', 2).orWhere('y', 4))
	.toString()
);
```

> select * from "foos" where ("x" = 3 or "x" = 4) and ("y" = 2 or "y" = 4)

Will create an issue in docs repo instead.

**Comment by rohannair** [comment]
Awesome!

**Comment by elhigu** [comment]
Except for `.where('x = 3')` that is not correct knex syntax.
