### ISSUE TITLE
using knex.raw to update jsonb attribute to an array

### ISSUE THREAD

**Issue by roytz** [tgriesser/knex#2521]
Hi,
I want to update a jsonb column with an array for a specific key.
I used `knex.raw` and `jsonb_set` like this-
`knex.raw('jsonb_set(column_name, '{??}', '?', true)', [key, arrayOfValues]);`
but it doesn't work because the array transforms to `{"val1", "val2", ...}`.
Any suggestions?

writing it manually like this `knex.raw('jsonb_set(column_name, '{??}', '["val1", "val2", ...]', true)', [key]);` would work.

Thanks

**Comment by elhigu** [comment]
This should be asked in stackoverflow or gitter. 

You need to write it something like:

```
knex.raw('jsonb_set(column_name, '{??}',  ?, true)', [key, JSON.stringify(arrayOfValues)]);
```

Raw cannot know you are trying to pass json data in and javascript array != json

**Comment by benoitv-code** [comment]
> You need to write it something like:
> 
> ```
> knex.raw(`jsonb_set(column_name, '{??}',  ?, true)`, [key, JSON.stringify(arrayOfValues)]);
> ```

_Replying to this as Google points to this answer, which might lead to a vulnerability_

I think this code would allow a SQL Injection, as ```knex('table').update({ column_name:knex.raw(`jsonb_set(column_name, '{??}',  ?, true)`, ["myColumn' --", JSON.stringify([])]) }).toSQL()``` produces `update "table" set "column_name" = jsonb_set(column_name, '{"myColumn' --"}',  ?, true)`

This would be better:  ```knex('table').update({ column_name:knex.raw(`jsonb_set(column_name, ??,  ?, true)`, [`{${key}}`, JSON.stringify([])]) }).toSQL()```
