### ISSUE TITLE
How to create unique index with 'where' clause?

### ISSUE THREAD

**Issue by qwang07** [tgriesser/knex#2525]
# Environment

Knex version: 0.14.4
Database + version: Postgres v9.6
OS: Debian

# Feature discussion / request

I'd like to create a unique index for my table with WHERE clause:
```
db.schema.createTable('newTable', function(t) {
  t.increments()
  t.string('col1').defaultTo(null)
  t.string('col2').notNullable()
  t.integer('col3').notNullable()
  t.unique(['col1', 'col2', 'col3']).whereNotNull('col1')
  t.unique(['col2', 'col3']).whereNull('col1')
})
```
I try to create two partial indexes for the table. However, whereNotNull is not chainable with unique function. Is there any other way to achieve the same function?

**Comment by elhigu** [comment]
Not yet. There is PR which is not ready yet though for support for partial indices https://github.com/tgriesser/knex/pull/2401

For now you need to use knex.schema.raw for it.
