### ISSUE TITLE
back-pressure issue with MS-SQL 

### ISSUE THREAD

**Issue by ChrisZ1** [tgriesser/knex#2530]
# Environment

Knex version: 0.14.4
Microsoft SQL Server 2014 (SP1-CU3) (KB3094221) - 12.0.4427.24 (X64)   Oct 10 2015 17:18:26   Copyright (c) Microsoft Corporation  Enterprise Edition (64-bit) on Windows NT 6.3 <X64> (Build 9600: ) (Hypervisor) :
OS: MS Windows NT 6.3(9600)

@ Grimace1975 .

hi, I am debugging an run out of memory issue when running large report. To debug the issue, created code like this:
```
var dbstream = knex.select("column1").table("mytable").stream({highWaterMark: 5});
dbstream.on("data", row => {
if(! httpResponse.write(JSON.stringify(row)))        
    readStream.pause();
});
httpResponse.on("drain", () => {
   dbstream.resume();
});
```
Notice that even when dbstream is in paused state, the node VM still keep growing in size. Debug into code notice that even when dbstream  is paused, data still keep pushing into the dbstream.
\node_modules\readable-stream\lib\_stream_readable.js   ln 228 Readable.prototype.push() is invoked regardless of the pause state of the dbstream.
In addition, node_modules\knex\lib\dialects\mssql\index.js  ln 178, options with highwatermark is ignored?

error message: FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory

Should knex stop more data flowing from  DB until resume() is invoked? 

Advice appreciated!

**Comment by elhigu** [comment]
Does using the mssql driver directly has the same problem?

**Comment by jylzj** [comment]
Did some more digging. Found that from the tedious level, the [resume/pause is supported](https://github.com/tediousjs/tedious/pull/518). But from the node-mssql level, not using these new features yet. So this is not an issue with knex. Thanks!
