### ISSUE TITLE
Installs of commander dependency with date 1st Jan 1970 and breaks ZIP

### ISSUE THREAD

**Issue by AdrieanKhisbe** [tgriesser/knex#2531]
# Environment

Knex version: 0.14.0
Database + version: irrelevant
OS: ubuntu + macOs

# Bug
An installed version of knex cannot be zipped and then deployed. (aws lambda)

This is due to the following problem on commander dependency: https://github.com/tj/commander.js/issues/777 (caused by [npm bug](https://github.com/npm/npm/issues/19968)), the files in package installed having a too old timestamp.

**Comment by elhigu** [comment]
0.14.0 - 0.14.2 versions of knex should not be used... Is master broken with this too?

**Comment by AdrieanKhisbe** [comment]
My Bad, in fact we were using 0.14.4 
(I mixed up 0.13.0 and 0.14.4)

**Comment by AdrieanKhisbe** [comment]
A fix on commander was release, that solved the problem! :)
cf https://github.com/tj/commander.js/issues/777#issuecomment-374444804
