### ISSUE TITLE
Add Primary Key to Migration Lock Table

### ISSUE THREAD

**Issue by herloct** [tgriesser/knex#2534]
# Environment

Knex version: 0.14.4
Database + version: Percona Server for MySQL 5.7.21 using Percona XtraDB Cluster 5.7.21
OS: CentOS 7

# Bug

I'm trying to run knex migrations on Percona Server for MySQL running inside Percona XtraDB Cluster, it throws error like this:

```
Error: ER_UNKNOWN_ERROR: Percona-XtraDB-Cluster prohibits use of DML command on a table (my_database.migrations_lock) without an explicit primary key with pxc_strict_mode = ENFORCING or MASTER
```

It seems that Percona XtraDB Cluster requests that every table MUST have primary key, yet knex's `migrations_lock` doesn't have any.

Maybe we could add primary key on knex's `migrations_lock`, something like this maybe:
https://github.com/tgriesser/knex/blob/master/src/migrate/index.js#L164-L168

```javascript
_createMigrationLockTable(tableName, trx = this.knex) {
  return trx.schema.createTable(tableName, function(t) {
    t.integer('is_locked').primary();
  });
}
```

**Comment by elhigu** [comment]
It is cleaner to add separate id column with primary key  for the row. PRs are welcome.

**Comment by k00p** [comment]
PR Created #2569

**Comment by rmothilal** [comment]
Hi, Is this fix in 0.14.6?

**Comment by elhigu** [comment]
next knex version will be 0.15.0, and this will be included.

**Comment by rmothilal** [comment]
Hi, thanks for getting back to me. When can we expect the next version? Also is there a current work around for this?

**Comment by elhigu** [comment]
I don't know yet when its to be released, but surely in a month or so at most.

**Comment by rmothilal** [comment]
Thanks very much for the responses
