### ISSUE TITLE
Cannot find module './dialects/mssql/index.js'  - Using Browserify

### ISSUE THREAD

**Issue by ChavaSobreyra** [tgriesser/knex#2537]
# Environment

Knex version: ^0.14.4
Database + version: mssql
OS: mac

Select applicable template from below.
For MSSql tag  @Grimace1975

# Bug

**1. Explain what kind of behavior you are getting and how you think it should do**
I'm writing and e2e test in cypress, which is a browserify environment.

**2. Error message**
`Cannot find module './dialects/mssql/index.js' `

**3. Reduced test code**

```javascript
require('dotenv').config()
const knex = require('knex')({
  client: 'mssql',
  connection: {
    host: process.env.DB_HOST,
    user: process.env.DB_USER,
    password: process.env.DB_PASSWORD,
    database: 'MyDatabase'
  }
})
```

**Comment by elhigu** [comment]
Did you check these issues already https://github.com/tgriesser/knex/search?q=browserify&type=Issues&utf8=%E2%9C%93

**Comment by elhigu** [comment]
Can be opened again if more info is added showing that something needs to be changed in knex to support this case. So far this does not seem like a knex problem.
