### ISSUE TITLE
Source is not transpiled to lib/ when running tests

### ISSUE THREAD

**Issue by ricardograca** [tgriesser/knex#2541]
# Environment

Knex version: 0.14.4
Database + version: Not relevant
OS: Ubuntu 16.04.4

# Bug

Running the test suite doesn't automatically transpile `src/` to `lib/` even though the Contributing document says that it should:

> Make changes in the /src directory and run npm run babel (runs once and then quits) or npm run dev (runs once and then watches for changes) to update the files in /lib. **npm test will also do this.**

Looking at the `test` script in `package.json` it looks like it just calls the `pre-test` script which simply runs the linter and not the babel compiler. 

### Steps to reproduce

1. Clone the repo
2. `npm install`
3. Change some file in `src` so that a test would fail
3. `npm test`

### Expected results

The changes made to the file in `src` make the test suite fail.

### Actual results

The test suite completes successfully because the changes are not being transpiled to `lib`.

# Missing / erroneus documentation

This could also be a case of incorrect documentation.

**Comment by elhigu** [comment]
Yes, this is bug or incorrect docs. I always run npm run build && npm test when developing.

**Comment by ricardograca** [comment]
Is there any problem with updating the script in `package.json` to run the build process before testing?

**Comment by elhigu** [comment]
I think that should be eay to go. Running tests without build should separated to own script. Probably test is not doing build because some people are using build-watch for the code and then just running tests without building vode separately.

**Comment by elhigu** [comment]
And I really cant write properly with touch screen 😅

**Comment by ricardograca** [comment]
:smile: No problem. I'll get this fixed after the timestamps thing.

**Comment by ricardograca** [comment]
So, with all that back and forth I got lost. This isn't actually fixed is it?

**Comment by wubzz** [comment]
@ricardograca No, it's not. Seems the revert decided closed it again.. Reverted due to [this](https://github.com/tgriesser/knex/commit/3aa811fa9d686515fb5b374f2c86d707425f62b4)
