### ISSUE TITLE
What is the best way to approach this situation (schema builder)

### ISSUE THREAD

**Issue by javascrewpt** [tgriesser/knex#2546]
I was using **knex migrations** for an app with this schema (give or take) representing my database:

```
exports.up = function (knex, Promise) {
    return knex.schema
        .createTable('servers', function (table) {
            table.increments('id').primary();
            table.string('serverName', 50);
            table.integer('fault_id').references('faults.id');
        })
        .createTable('faults', function (table) {
            table.increments('id').primary();
            table.text('faultDescription', 'longtext');
        });
};

exports.down = function (knex, Promise) {
    return knex.schema
        .dropTable('servers')
        .dropTable('faults');
};
```

I've been using this database for a while now and I have lots of data already in the database. Now I want to add another column to the `servers` table, using knex migrations. 

If I run `knex migrate:rollback` I've lost all the data.
If I change the schema and run `knex migrate:latest` I get an error that it's already up to date.
If I create a new schema with `alterTable`, I've lost reference to the schema above.
I literally don't see a way of using `schema migrate` to solve this issue. 

What is the correct approach?

**Comment by elhigu** [comment]
This kind of application design questions should be asked in stacckoverflow or in sone other forums.

Knex github issues are for library development related use only.

That being said. You should create new migration file with alter table statement that adds new column. Once migration file is ran on db it should not be changed afterwards.
