### ISSUE TITLE
Return inserted data

### ISSUE THREAD

**Issue by thelegend5** [tgriesser/knex#2547]
sometimes after insertion of data, i need to process the data inserted into some other functions, but i can't get the data inserted, you as well say that why would you use the data after insertion when you already had them before insertion, well, that's the idea of a promise, i want to process the data in the `then` function after they're successfully inserted, but my issue is that i only get the id back, can i get any help, anything i forgot ??

i'm using mysql database

```sh
>knex('users').returning('username').insert({username:'kaggfsd',password:'fgkgfdfd',email:'ngfgfla'}).then((data)=>{console.log(data)})
Promise {
  _bitField: 0,
  _fulfillmentHandler0: undefined,
  _rejectionHandler0: undefined,
  _promise0: undefined,
  _receiver0: undefined }
> [ 7 ]
```

**Comment by elhigu** [comment]
Knex returns the same thing that db server returns from insert query. I suppose you are using some database like mysql that does not support returning statement. To get inserted data with mysql you need to select the row with inserted id. Or you need to return the same object you inserted by explicitly returning it from promise.

**Comment by AMUSF** [comment]
Maybe this helps 
`router.post('/todos', (req, res) => {
	knex('todos')
		.insert(req.body)
		.then(insertedTodo => {
			console.log('insertedTodo:', insertedTodo)
			knex('todos')
				.where('id', insertedTodo[0])
				.then(selectedTodo => {
					return res.json(selectedTodo)
				})
		})
		.catch(err => res.json(err))
})`

**Comment by dsomel21** [comment]
Is this still the only solution?!
