### ISSUE TITLE
Invoking Stored Procedure and get OUTPUT

### ISSUE THREAD

**Issue by blackout1208** [tgriesser/knex#2548]
Hi guys,

Perhaps this is not a bug and you may have a trick for it.

I have a stored procedure on mysql database where I have IN and OUT arguments.
I am invoking that stored procedure with knex.raw() but how do I get the OUT arguments?

**Comment by elhigu** [comment]
There is older issue about this. I cannot remember if there was some problems in knex side with this. Passibg out arguments depends on database driver. Have you looked driver’s docs?

**Comment by blackout1208** [comment]
@elhigu yes. That is why I am using the raw() method. But may be there something more specific that I didn't see.

```
CALL StoreProcedure('value1', 'value2', @a);
SELECT @a;
```
If I would run the query directly on my Workbench the code above works. I am trying to check how I can create the @a and get its value in one call to raw().

I am using this:

`const a = knex.raw("call StoreProcedure('value1', 'value2');");`
But this way makes MySQL complain about the number of my arguments. Naturally.

**Comment by blackout1208** [comment]
I found the solution:

```
const val = await knex
    .raw("call insertCompetition('value1', 'value2', @a)")
    .then(val => return JSON.stringify(val)))
    .catch(err => console.log(err));
```
