### ISSUE TITLE
Number is geting rounded when being read by knex

### ISSUE THREAD

**Issue by AstroGD** [tgriesser/knex#2555]
#Environment

Knex version: 0.14.4
Database + version: Mysql 2.15
OS: Linux Debian
@Grimace1975

#Bug

**1. Explain what kind of behaviour you are getting and how you think it should do**
I am reading all Entrys of a table using this code:
`await knex.select("*").from(table);`
The Entry for the column "channelid" is 361543889154473984 (Bigint(20))
But instead of 361543889154473984, knex is returning 361543889154474000.

**2. Error message**
There is no Error Message being provided

**Comment by raijinsetsu** [comment]
There is no way to safely represent that number in Javascript (see: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER; your number is 2 orders of magnitude larger). According to the Knex doc, it shouldn't even be a number: it should be a string (see: http://knexjs.org/#Schema-bigInteger).

Are you casting the string to a number or is the row returned by knex actually a number? Hint: use "typeof" on the column.

**Comment by elhigu** [comment]
I suppose mysql driver should return that number as string instead of number. Anyways, not knex issue. Knex does not decide how values are returned from db.

**Comment by raijinsetsu** [comment]
@elhigu The documentation clearly states that KNEX (not the driver) will return strings for BIGINT columns. Is that not incorrect?

**Comment by elhigu** [comment]
@raijinsetsu documentation is correct, unless mysql driver has changed how it behaves. 

If you can add complete example how to reproduce this problem (single file, which initializes/populates db and shows that query actually is not returning bigints as string) this issue can be reopened. With current info all looks like user error (in https://github.com/tgriesser/knex/blob/master/CONTRIBUTING.md#what-is-minimal-code-to-reproduce-bug-and-why-i-have-to-provide-that-when-i-can-just-tell-whats-the-problem-is is more info why so detailed reproduction is needed).

**Comment by AstroGD** [comment]
Ah I see. Thanks for the quick answer. I didn't know there was a limit. Sorry for wasting your time.

**Comment by ryanrouleau** [comment]
For anyone that stumbles across this, you can add 
```
    supportBigNumbers: true,
    bigNumberStrings: true,
```
to the connection field in the knex config which will not cast the bigint to a js number but instead return it as a string.

So something like this:

```javascript
const knexConfig = {
  client: 'mysql2',
  connection: {
    host: env.DB_HOST,
    user: env.DB_USER,
    password: env.DB_PASSWORD,
    database: env.DB_DATABASE,
    supportBigNumbers: true,
    bigNumberStrings: true,
  },
};

```

**Comment by AstroGD** [comment]
thanks. I will definitely put that into my code
