### ISSUE TITLE
Query builder should respect valueOf for objects in bindings

### ISSUE THREAD

**Issue by Gregroam** [tgriesser/knex#2558]
Using the POSTGRES driver

Setup. A class that takes a string and validates it's a v4 uuid. Set it's valueOf method to return the inputted uuid string.
```
class UUIDV4 {
    constructor(_uuid) {
        if (!UUIDV4.reg.test(_uuid)) {
            throw new Error("Invalid UUID");
        }
        this.uuid = _uuid;
    }
    valueOf(){
        return this.uuid;
    }
}
UUIDV4.reg = /^[0-9A-F]{8}-[0-9A-F]{4}-4[0-9A-F]{3}-[89AB][0-9A-F]{3}-[0-9A-F]{12}$/;
```

Initialize the knex client and construct a query
```
const knex = require("knex");
const client = knex(/**connection**/);

let q = client("table").select().where({column: new UUIDV4("107E85E0-4BCD-4B61-BF60-FF7E50F0F9C0")});

console.log("Unbinded sql:", q.toSQL());
console.log("Compiled sql:", q.toString());
```

Expected sql output
```
select * from "table" where "column" = '107E85E0-4BCD-4B61-BF60-FF7E50F0F9C0'
```

Actual sql output
```
select * from "table" where "column" = '{"uuid":"107E85E0-4BCD-4B61-BF60-FF7E50F0F9C0"}'
```

**Comment by Gregroam** [comment]
I did try using `toJSON` instead of `valueOf`, which almost worked but knex expects the text value in the database column to be wrapped in quotes to successfully select it.

**Comment by elhigu** [comment]
I think this should be handled by sql driver. Knex should not modify values that one is passing to driver as bindings. IIRC postgres driver supports a method called `.toPostgres` for converting object to binding value.
