### ISSUE TITLE
Knex fails to automatically serialise/deserialise JSON in SQLite

### ISSUE THREAD

**Issue by alexborisov** [tgriesser/knex#2575]
# Environment

Knex version:0.14.4
Database + version: SQLite 3.1.13
OS: MacOS/Debian

# Bug

1. Knex supports JSON schema type. This falls back to string for databases that don't support JSON. The expected behaviour is that migrations will create a TEXT type column for SQLite. Inserting a record with JSON data for that column should automatically stringify the data. Reading the record back should automatically parse the JSON.

2. Migrations produce the correct table structure. However if you try to insert a row with JSON it fails to do this (the column is `NULL`). If I `JSON.stringify()` my data first this works as expected. The documentation only mentions having to stringify array data and in my case it's an object.

**Comment by elhigu** [comment]
@alexborisov sadly, knex does not know that your string column should contain json data, so it is impossible to implement. Serialization / deserialization is job of the db driver. To me knex's choice to emulate non-existing column types with text type etc. was not really good choice, more info about it was  articulated quite throughly here: https://github.com/tgriesser/knex/issues/2368#issuecomment-349362295 

1., 2.  Closing as impossible.

**Comment by elhigu** [comment]
You might like to try some knex based ORM like objection.js, which actually can keep information about column types described in Model.
