### ISSUE TITLE
Silently ignoring rollback timeout swallows transaction error

### ISSUE THREAD

**Issue by magnusjt** [tgriesser/knex#2582]
Knex version: 0.14.3

# Bug

See old pull request where I believe this was added: https://github.com/tgriesser/knex/pull/1296

The issue is that if a rollback times out, the original transaction error will be swallowed. I believe this is the code:

````js
// src/transaction.js
rollback(conn, error) {
    return this.query(conn, 'ROLLBACK;', 2, error)
      .timeout(5000)
      .catch(Promise.TimeoutError, () => {
        this._resolver();
      });
  }
````

As you can see the original transaction error is forwarded to query, but since the rollback times out the original error is not thrown. There is no harm in swallowing the error from the rollback itself, but that's not what is happening here.

**Comment by wubzz** [comment]
I believe this is not really related to #1296 since the issue you describe must have existed long since before that PR. Before that PR it would just hang indefinitely, also without throwing error, I'm pretty sure.

I do understand how this can be an issue, tho. Perhaps the correct solution is to reject with the original error `this._rejecter(error)` instead of calling `this._resolver()`

**Comment by magnusjt** [comment]
It's almost the same, but actually worse because in this case we were lead to believe that the transaction was successful. Better to hang indefinitely than report success in the case of failure. 

The proposed solution is probably good enough in this case, but there are still more issues with the code. For example, if the rollback throws another type of error, we get that error out instead of the original transaction error. I could maybe have a look at it if it's interesting, otherwise your solution is probably good enough for most.

**Comment by magnusjt** [comment]
@wubzz I see you made PR with a fix. Thanks! And thanks for all the great work with knex. It's a wonderful library.
