### ISSUE TITLE
Can't migrate with sqlite3: SQLITE_ERROR: no such table: knex_migrations_lock

### ISSUE THREAD

**Issue by poohitan** [tgriesser/knex#2583]
# Environment

Knex version: 0.14.6
Database + version: sqlite3 (tried 3.11.0 and 3.19.3)
OS: OS X, Ubuntu
Node.js version: 8.9.3

# Bug

I have a problem with running the migrations. I'm trying to use knex with sqlite3 driver. The `knex migrate:latest` command fails with an error `SQLITE_ERROR: no such table: knex_migrations_lock`;

Here is my knexfile.js:
```javascript
module.exports = {
  client: 'sqlite3',
  connection: {
    filename: './test.db',
  },
  useNullAsDefault: true,
};
```

This issue reproduces for me both on OS X and Ubuntu with different sqlite3 versions.

As far as I understand, both `knex_migrations` and `knex_migrations_lock` tables should be created automatically, whilte it seems they are not.
Will appreciate your help.

**Comment by elhigu** [comment]
You are initializing knex in a wrong way in your code (which you haven't included here).

**Comment by poohitan** [comment]
Now I guess the problem is the `NODE_ENV=development` in my environment which makes knex CLI think that it should read the config from `development` section when I run the migration, and at the same time when I initialize knex, I don't pass any environment, so it reads it from the root of the config object. Am I right?

**Comment by elhigu** [comment]
I dont use knex commanline client myself. I'm not sure if it accepts configuration without that internal property.

If it is necessary, then having few extra chars in your app code shouldn't be too much boilerplate to add:

```
const knex = require('knex');
const knexConf require('../knexfile').development;

module.exports = knex(knexConf);
```

**Comment by poohitan** [comment]
Sure, but I don't want to have `.development` in my production code. Also in this case I don't need different configs for development and production environments. So I tried to achieve this.

**Comment by elhigu** [comment]
How about:

```js
const knex = require('knex');
const knexfile = require('../knexfile');
const knexConf = knexfile[Object.keys(knexfile)[0])];
module.exports = knex(knexConf);
```

or 

```js
const knex = require('knex');
const knexfile = require('../knexfile');
const knexConf = knexfile[process.env.NODE_ENV];
module.exports = knex(knexConf);
```

or in knexfile:
 
```js
const conf = {
  client: 'sqlite3',
  connection: {
    filename: './test.db',
  }
};

const knexFile = {};
knexFile[process.env.NODE_ENV || 'development'] = knexFile;

module.exports = knexFIle;
```
or having separate knex-config.js and knexfile.js and require('knex-config') in your app and let commandline client to use knexfile which require knex-config.js.

Anyways what you are trying to achieve is pretty trivial to implement and there are many ways to do it. Main restriction being that if you are using knex commandline client and NODE_ENV variable then it seems that you need to have correct property for environment in your knexfile.

**Comment by elhigu** [comment]
PRs to documentation are always welcome.

Your migrations have probably failed before being able to cleanup migration lock table, just delete all rows in that table.

**Comment by poohitan** [comment]
Migrations table weren't even created. Neither `knex_migrations` nor `knex_migrations_lock`.

BTW I was able to reproduce the same error using PostgreSQL driver. I got `error: relation "knex_migrations_lock" does not exist`, fixed it the same way as for sqlite3.
