### ISSUE TITLE
jsonb data type fails on MySQL migration

### ISSUE THREAD

**Issue by sebmor** [tgriesser/knex#2584]
# Environment

Knex version: 0.14.6
Database + version: Mysql 5.7.21
OS: Mac

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do
Creating a migration with jsonb http://knexjs.org/#Schema-jsonb on a MySQL db

2. Error message
```
exports.up = function(knex, Promise) {
  return Promise.all([
    knex.schema.createTable('column', (t) => {
      t.increments('id').primary()
      t.json('json_column').notNullable()
    })
  ])
};
``` 
```
Knex:warning - migration file "20180425000654_create_bets.js" failed
Knex:warning - migration failed with error: create table `column` (`id` int unsigned not null auto_increment primary key, `json_column` undefined not null) - ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'undefined not null)' at line 1
```

The documentation; 
(`Adds a jsonb column. Works similar to table.json(), but uses native jsonb type if possible.`) 
suggests that if jsonb is not supported it will revert to the most appropiate data type for your database. However it plainly errors as undefined in MySQL.

**Comment by elhigu** [comment]
There is no jsonb type in mysql. There is no appropriate datatype to replace json types. If you need DB agnostic way to store json data, just create text column and serialize JSON to strings. More reasoning found for example here: https://github.com/tgriesser/knex/issues/2368

**Comment by sebmor** [comment]
fwiw, there is also currently not a json type for MySQL (at least not current stable version). And the current .json() makes it a TEXT type.
Using .json() doesn't error in MySQL while .jsonb() does was my point.
