### ISSUE TITLE
"binary" datatype very different when using different drivers

### ISSUE THREAD

**Issue by raijinsetsu** [tgriesser/knex#2585]
# Environment

Knex version: 0.12.9 (but reproducible in 0.14.6)
Database + version: MariaDB or MySQL, any version
OS: any

# Bug
.binary(columnName) creates a column with the "BLOB" type -or- "VARBINARY" (when providing a hidden second argument) for the mysql and mariadb drivers. Those types are limited to 64KB. The mssql driver uses type "VARBINARY(max)" and the pg driver uses type "BYTEA", both of which can store at least 1GB.

.binary should work like .text and allow a second argument so that "longblob", etc. could be specified.

The work-around is an abstraction like this:

``` typescript
export function binaryColumn<T extends Knex.TableBuilder>(columnName: string, knex: Knex, table: T) {

    switch (knex.client.config.client) {
        case 'mysql':
        case 'mysql2':
        case 'mariasql':
            return table.specificType(columnName, 'LONGBLOB');
        default:
            return table.binary(columnName);
    }
}
```

**Comment by elhigu** [comment]
I failed to see bug in this. If you would like to propose feature for some better DB agnostic binary column, please open feature request where is investigated, how it can be supported in postgres/mysql/sqlite/oracle and mssql and propose an API.
