### ISSUE TITLE
support currentSchema in db connection string?

### ISSUE THREAD

**Issue by xiechao06** [tgriesser/knex#2590]
# Environment

Knex version:
Database + version: postgresql 9.5
OS: ubuntu 16.04

Select applicable tempalate from below.
If issue is about oracledb support tag @ atiertant. For MSSql tag @ smorey2 .
Rest of dialects doesn't need tags.

# Feature discussion / request

1. Explain what is your use case

I've used one database, which contains many schemas 

2. Explain what kind of feature would support this

I hope the db connection string could support currentSchema like:

`postgres://localhost/foo_db?currentSchema=foo_schema`

I've found a similar discussion here: https://stackoverflow.com/questions/4168689/is-it-possible-to-specify-the-schema-when-connecting-to-postgres-with-jdbc

so I could just use `db(tableName).select` instead of `db.withSchema('foo_schema').from(tableName).select`, which is very tedious  

# Missing / erroneus documentation

Send issue to documentation repo, or fix it and send PR https://github.com/knex/documentation

# Questions about how to use knex

Github issues are for knex development. Please send questions how to use knex to
stackoverflow or ask about it in gitter chat.

**Comment by elhigu** [comment]
I think this should be implemented by driver. Here is already feature request done for node-postgres https://github.com/brianc/node-postgres/issues/1123 about it
