### ISSUE TITLE
hasTable does not work with schema in MSSQL

### ISSUE THREAD

**Issue by Fabi2607** [tgriesser/knex#2591]
# Environment

Knex version: 0.14.4
Database + version: MSSQL Express 2012 @smorey2 
OS: Windows 7

# Bug

After creating a schema "test" in MSSQL a table can be created with:
```
knex.schema.withSchema("test").createTable("tableName", ...)
```

afterwards the table exists in the database, but
```
knex.schema.withSchema("test").hasTable("tableName")
```
returns false.

The generated SQL also omits the schema name.

## Expected behaviour
`knex.schema.withSchema("test").hasTable("tableName")` returns true.

**Comment by Fabi2607** [comment]
I think the following should work:

```sql
SELECT t.name 
  FROM sys.tables AS t
  INNER JOIN sys.schemas AS s
  ON t.[schema_id] = s.[schema_id]
  WHERE s.name = N'schemaName' AND t.name = N'tableName';
```
I am not really experienced in MSSQL, but this seems to cover my use case.

I did some more testing, this also affects OracleDB, which generates

```sql
select TABLE_NAME from USER_TABLES where TABLE_NAME = 'tableName'
```

 i think the proper query for OracleDB is

```sql
SELECT table_name, owner
  FROM all_tables
  WHERE owner='schemaName' AND table_name = 'tableName'
```

But this is more or less guesswork and some searching on the internet, so do not take my word for it...

**Comment by Fabi2607** [comment]
Any updates on this? If the above sounds reasonable I could also create a pull request with these changes.

**Comment by elhigu** [comment]
no updates, nobody has fixed / implemented this yet. PRs are welcome of course.

**Comment by Fabi2607** [comment]
Our problems are solved with the merged PR, should I close it? Or do you want an issue to document the potential issues with Oracle?

**Comment by elhigu** [comment]
Documentation wouldn't hurt, but that is a bit of a special case, which the person working on oracle with that like of tableownership scheme should know about. So this is good like this.
