### ISSUE TITLE
Knex best practices

### ISSUE THREAD

**Issue by i0natan** [tgriesser/knex#2596]
Hey friends, we want to add to our "node best practices" repo (link below) a section about data-access practices, will you kindly contribute some ideas based on your vast experience?

For example, the following might be best practices when working with ORMs: (a) Instantiating the ORM object only once per process (b) never do automatic sync in production (c) your ideas?

Thanks for your help!

https://github.com/i0natan/nodebestpractices

**Comment by elhigu** [comment]
I think knex is a bit too low level library for most of the stuff for being used without some ORM on top of it. Anyways this doesn't seem like any real issue. Closing. Hopefully someone takes time to help writing that page.
