### ISSUE TITLE
console.log in knex object displays password properties - security issue.

### ISSUE THREAD

**Issue by danilohgds** [tgriesser/knex#2597]
Hello all,

So far I have been able to reproduce this with oracle client. Create a knex instance object and then perform the log method on it, it will print with readable password....which is a major security issue imo.

```js
return knex({
  client: 'oracledb',
  connection: {
    user: DB_USER,
    password: DB_PASSWORD,
    host: `${DB_HOST}:${DB_PORT}`,
    database: DB_NAME
})
```

logs will show: 

```
connectionSettings:
--
  | { user: 'READABLEUSER',
  | password: 'READABLEPASSWORD',
  | host: 'READABLEHOST',
  | database: 'REDABLEDB' },
```

**Comment by elhigu** [comment]
If you are doing:

```js
console.log(knex); 
```

You shouldn't log blindly objects containing sensitive information.

I don't think it is necessary to handle this on knex side. You can always for example log your knexfile.js or environment variable or some other place that contains DB password.
