### ISSUE TITLE
Custom connection on schema building

### ISSUE THREAD

**Issue by Taggotty** [tgriesser/knex#2599]
# Feature discussion / request

1. Explain what is your use case
I´d like to build a schema with a custom connection, this way I can for example disable the foreign_keys of a sqlite database in a migration. Furthermore it just seems consistent to me, as you can run a query with a custom connection. Of course this feature would need be used with caution, as the custom connection is not bound to outer transactions.

2. Explain what kind of feature would support this

3. Give some API proposal, how the feature should work
Maybe add `connection(connection: Connection)` to the schema builder.

**Comment by kibertoad** [comment]
@Taggotty Can't you just call migrations on an alternate knex instance?..

**Comment by elhigu** [comment]
This should be done by running schema through separate knex instance as @kibertoad mentioned.
