### ISSUE TITLE
Cannot set foreign key and primary key on same column

### ISSUE THREAD

**Issue by dehypnosis** [tgriesser/knex#2604]
# Environment

Knex version:
Database + version: mysql 8
OS: alpine linux

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do

```js
await db.schema.createTable('user_profiles', (table) => {
    table.integer('user_id').unsigned().primary()
      .references('users.id')
      .onUpdate('CASCADE')
      .onDelete('CASCADE');
...
```

Above statement ignore foreign key generation. I think It should generate FK and PK both on user_id column, isn't it right?

**Comment by elhigu** [comment]
According to this it seems to create primary and foreign key https://runkit.com/embed/lgvrgqhvior2

Cannot reproduce.
