### ISSUE TITLE
GROUP_CONCAT; knexjs way or must do it raw.

### ISSUE THREAD

**Issue by cunundrummer** [tgriesser/knex#2615]
# Environment

Knex version: 0.14.6 
Database + version: mysql 8.0
OS: OSX 10.11.6 (El Capitan)

Select applicable tempalate from below.
If issue is about oracledb support tag @ atiertant. For MSSql tag @ smorey2 .
Rest of dialects doesn't need tags.

# Questions about how to use knex

Github issues are for knex development. Please send questions how to use knex to
stackoverflow or ask about it in gitter chat.

Is there no way without using knex.raw to convert this mySql query:

`SELECT  CATEGORIES.name AS Category, 
        GROUP_CONCAT(SUBCAT.name  ORDER BY SUBCAT.name ) AS Subcat, 
        COUNT(*)  
FROM Categories AS CATEGORIES 
  INNER JOIN Categories SUBCAT ON  CATEGORIES.id = SUBCAT.parentCatId
GROUP BY Category;`

into a knexjs 'format' without getting 

> code: 'ER_BAD_FIELD_ERROR',
  errno: 1054,
  sqlState: '42S22',
  sqlMessage: 'Unknown column \'GROUP_CONCAT(SUBCAT.name ORDER BY SUBCAT.name)\' in \'field list\'' }

I seem to have the correct statement created by knexjs with my code (excuse the formatting, it doesn't render well when used in 'code brackets'):

knex
      .select(
        { Category: 'CATEGORIES.name' },
        { Subcat: `GROUP_CONCAT`+'(' + 'SUBCAT.name' + ' ' + `ORDER BY` + ' ' + `SUBCAT.name` + ')'},
        'count(*)'
      )
      .from('Categories').as('CATEGORIES')
      .join('Categories as SUBCAT', function() {
        this.on('CATEGORIES.id', '=', 'SUBCAT.parentCatId')
      })
      .groupBy('Category')
      .then(rows => {
        console.log(rows);
        res.status(200).json(rows);
      })
      .catch(error => {
        res.status(500);
        console.error(error);

      })
      .finally(() => {
        console.log(`knex promise completed. Shutting connection...`);
        knex.destroy();
      })

**TERMINAL RESULT**:

> { method: 'select',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [],
  __knexQueryUid: 'ae397343-f0a9-4df0-8016-cb9a934b8b80',
  sql: 'select `CATEGORIES`.`name` as `Category`, `GROUP_CONCAT(SUBCAT`.`name ORDER BY SUBCAT`.`name)` as `Subcat`, `count(*)` from `Categories` inner join `Categories` as `SUBCAT` on `CATEGORIES`.`id` = `SUBCAT`.`parentCatId` group by `Category`',
  as: 'CATEGORIES' }

* again it seems formatting is not the same as what I see in terminal.  Anything in grey is surrounded by "`".

The statement looks correct and equivalent to my sql statement. I have searched for GROUP_CONCAT and found reference  #1140 and #465.  But the solution was to use .raw or multiple statements and variables and calls.  And that was in 2016.  Is there no way to do it using something similar to what I coded in js? Or is it a bug?

**Comment by elhigu** [comment]
This question should not be done here as it was already mentioned in issue template:

> Github issues are for knex development. Please send questions how to use knex to stackoverflow or ask about it in gitter chat.

So please send future questions about knex usage to stackoverflow.

Knexy way to convert

```sql
SELECT 
  CATEGORIES.name AS Category, 
  GROUP_CONCAT(SUBCAT.name ORDER BY SUBCAT.name ) AS Subcat, 
  COUNT(*) 
FROM Categories AS CATEGORIES 
INNER JOIN Categories SUBCAT ON CATEGORIES.id = SUBCAT.parentCatId 
GROUP BY Category;
```

is indeed by using `knex.raw`

```js
knex('Categories as CATEGORY')
  .select(
    'CATEGORY.name as Category', 
    knex.raw('GROUP_CONCAT(? ORDER BY ?) as ?', ['SUBCAT.name', ' SUBCAT.name', 'Subcat'])),
    knex.raw('COUNT(*)')
  )
  .innerJoin('Categories as SUBCAT', 'CATEGORIES.id', 'SUBCAT.parentCatId')
  .groupBy('Category')
```

Which outputs (https://runkit.com/embed/pjdve0xqc4an): 

```sql
select 
  `CATEGORY`.`name` as `Category`, 
  GROUP_CONCAT(? ORDER BY ?) as ?, 
  COUNT(*) 
from `Categories` as `CATEGORY` 
inner join `Categories` as `SUBCAT` on `CATEGORIES`.`id` = `SUBCAT`.`parentCatId` 
group by `Category`
```
