### ISSUE TITLE
returning('*') not working with my sql database

### ISSUE THREAD

**Issue by Jay427** [tgriesser/knex#2616]
# Environment

Knex version: 0.14.6
Database: mysql v2.15.0 :
OS:Windows 8

# Bug
-This update module
-I want return updated document but  returning('*') not working for me.
-returning(['id' , 'email']) not working for me.
-this issue occurred in insert query also.(`const data = await knex.insert(workspace).into(tableName).returning('*');`)
-Is there any solutions? Advanced Thanks.
```
exports.updateByEmail = async (email, updateData) => {
    let obj = {
        error: null,
        data: null
    };
    try {
        const data = await knex(tableName).where('email', email).update(updateData).returning('*');
        obj.data = data;
        return (obj);
    } catch (error) {
        obj.error = error;
        return (obj);
    }
}

```

**Comment by wubzz** [comment]
From the docs:

> Utilized by **PostgreSQL**, **MSSQL**, and **Oracle** databases, the returning method specifies which column should be returned by the insert and update methods

**Comment by Jay427** [comment]
`const data = await knex(tableName).returning('*').where('id', id).update(updateData).returning(['id',''name']);`
Not working for me.

**Comment by wubzz** [comment]
@Jay427 Because `.returning` is not supported by MySQL.

**Comment by hbole** [comment]
@wubzz  if knex .returning is not supported by MySQL Why is it in its documentation?

**Comment by wubzz** [comment]
@hbole Because the documentation isn't strictly for MySQL. As described above, this is described in the first text of the `returning` section:

> Utilized by **PostgreSQL**, **MSSQL**, and **Oracle** databases, the returning method specifies which column should be returned by the insert and update methods

**Comment by Duarte007** [comment]
if knex returning is not supported by MySQL, how method i can use for this?

**Comment by kibertoad** [comment]
@Duarte007 Check LAST_INSERT_ID for MySQL. Overall MySQL is not a well-supported DB in Node.js ecosystem, consider using PostgreSQL instead.

**Comment by MohamedLamineAllal** [comment]
Why not add the support of returning within knex fror mysql. Using LAST_INSERT_ID. And let it as an option for when the id is auto increment. Which is too helpful. And so in such a system (id's auto increment) we can have cross compatibility with the same code.

**Comment by elhigu** [comment]
@MohamedLamineAllal  because that does not return everything, only ids of the inserted rows in the best scenario... 

With postgresql `returning()` can be used even with update or delete.

Crossdb compatible insert is a different issue https://github.com/tgriesser/knex/issues/2682

**Comment by pazfelipe** [comment]
I got the same warning when I try to insert some data into database returning its id. But even when I get this warning/error, knex keeps returning data id from mysql db.

**Comment by elhigu** [comment]
> I got the same warning when I try to insert some data into database returning its id. But even when I get this warning/error, knex keeps returning data id from mysql db.

Yup you get the id, but it does not happen because you are having `.returning('id')` in your code. Mysql would return id and give warning even if you add `.returning('notId')` in your query. 

There is no way for knex to know, which is the name of your mysql auto incrementing column...

**Comment by bossman-codex** [comment]
so what can be done????

**Comment by elhigu** [comment]
@bossman-codex You can use postgresql, mssql or oracle, which supports `.returning()` or not to use it.
