### ISSUE TITLE
returning('*')  not woking with mysql database

### ISSUE THREAD

**Issue by Jay427** [tgriesser/knex#2617]
# Environment

Knex version: 0.14.6
Database: mysql v2.15.0 :
OS:Windows 8

# Bug
-Update module
-I want return updated document but  returning('*') not working for me.
-returning(['id' , 'email']) not working for me.
-this issue occurred in insert query also.(`const data = await knex.insert(workspace).into(tableName).returning('*');`)
-Is there any solutions? Advanced Thanks.
```
exports.updateByEmail = async (email, updateData) => {
    let obj = {
        error: null,
        data: null
    };
    try {
        const data = await knex(tableName).where('email', email).update(updateData).returning('*');
        obj.data = data;
        return (obj);
    } catch (error) {
        obj.error = error;
        return (obj);
    }
}

```

**Comment by wubzz** [comment]
See reply in your previous issue: https://github.com/tgriesser/knex/issues/2616
