### ISSUE TITLE
how to use when i required to apply date_format() for the column of first table, where join also appying

### ISSUE THREAD

**Issue by amarnathjena** [tgriesser/knex#2618]
# Environment

Knex version:
Database + version:
OS:

Select applicable tempalate from below.
If issue is about oracledb support tag @ atiertant. For MSSql tag @ smorey2 .
Rest of dialects doesn't need tags.

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do

2. Error message

3. Reduced test code, for example in https://npm.runkit.com/knex or if it needs real
   database connection to mysql or postgresql, then single file example which initializes
   needed data and demonstrates the problem.

# Feature discussion / request

1. Explain what is your use case

2. Explain what kind of feature would support this

3. Give some API proposal, how the feature should work

# Missing / erroneus documentation

Send issue to documentation repo, or fix it and send PR https://github.com/knex/documentation

# Questions about how to use knex

Github issues are for knex development. Please send questions how to use knex to
stackoverflow or ask about it in gitter chat.

**Comment by elhigu** [comment]
Stackoverflow is for usage questions.  Also one should actually put some time to properly present the questions, so that people can understand what is the problem.

**Comment by amarnathjena** [comment]
Hi Mikael Lepistö, i have changed the issue title. Hope this time it understandable the actual issue for what want answer if any body have.

**Comment by elhigu** [comment]
Maybe `knex('TableName').select(knex.raw('date_format(?)', ['TableName.columnName]))`, I'm sorry but I still have pretty much no idea what is this question about.

**Comment by amarnathjena** [comment]
**My NodeJS querybuilder is like below:**. And i want to extract dates with specific format.

return knex.select('id', 'name', 'code', 'start_date', 'end_date', 'table1.process_id as pid', 'table2.process_name as pname', 'table3.name as cname', 'table3.id as cid')
                .from('table1')
                .leftJoin('table2', function(){
                    this.on('table.process_id', '=', 'table1.id')
                })
                .leftJoin('table3', function(){
                    this.on('table3.id', '=', 'table1.id')
                });

Hope this time no confusions you will get and thanks for your help.

**Comment by elhigu** [comment]
Looks like join parts are irrelevant in this case, because you are actually just selecting dates from table1. Also my previous comment actually did answer to your question how to call sql data formatter functions for selected columns.
