### ISSUE TITLE
how use USE INDEX (....) and IGNORE INDEX (....) with MySQL

### ISSUE THREAD

**Issue by simonjcarr** [tgriesser/knex#2620]
MySQL supports the use of USE INDEX and IGNORE INDEX (known as index hints)

See link here https://dev.mysql.com/doc/refman/8.0/en/index-hints.html

Example here. 
```
SELECT * FROM table1 t1 USE INDEX (col1_index,col2_index)
  WHERE t1.col1=1 AND t1.col2=2 AND t1.col3=3;
```

How do I do this with KnexJS

**Comment by elhigu** [comment]
Usage questions should go to stackoverflow (as it is mentioned in issue template).

Anyways I don't think there is any other way to achieve this, but putting the whole query to knex.raw.

```js
knex.raw('SELECT * FROM ?? USE INDEX (??,??) WHERE ??=? AND ??=? AND ??=?', ['table1 as t1', 'col1_index', 'col2_index','t1.col1',1,'t1.col2',2,'t1.col3',3])
```
