### ISSUE TITLE
andWhereRaw is missing in the documentation

### ISSUE THREAD

**Issue by capaj** [tgriesser/knex#2623]
I know the docs don't list all the or/and methods. but it would be nice to at least mention the method at least once somewhere. For example `andWhere` is not explicitly listed on the left, but it is mentioned couple of times.

Could I have a question regarding this method-why does it even exists if it's just aliased `whereRaw` method?

**Comment by elhigu** [comment]
I suppose they were originally added to be able to write more natural looking queries.  

I have never really used them and they have seemed to cause more confusion during the years than been helpful. I would love to deprecate all of them, but I don't think that is good idea to do right now (also other maintainers might disagree with me on deprecating them). 

I suppose this is documentation issue. Did you have any specifics in mind how documentation could be better for these?

**Comment by capaj** [comment]
Imho best would be to list all the and/or variants under the original. So for example:
current `whereRaw` is just:
![image](https://user-images.githubusercontent.com/1305378/40419225-f1a522d8-5e84-11e8-8a94-cb4994d672cd.png)

and I propse we add there 
```
you can also call with these prefixes:
 * andWhereRaw - just an alias of `whereRaw`
 * orWhereRaw - calls `whereRaw` but uses `OR` logic symbol to add the condition
```

maybe we can drop the descriptions and just list them.
And this for all methods which have these prefixed versions. I can open a documentation PR over the weekend if you agree.

**Comment by capaj** [comment]
@elhigu I presonally don't see a problem deprecating them. They certainly caused me some confusion.
On the other hand- I remember I ran into a usecase where I needed specificaly use `andWhere` as opposed to `where` so it might be quite challenging to deprecate them and still cover all the usecases.

**Comment by capaj** [comment]
@wubzz you are right-it's just sugar. I probably had some other problem with my query at the time.

**Comment by elhigu** [comment]
Moved issue to documenatation repo.
