### ISSUE TITLE
knexfile.js does not read Dotenv variables

### ISSUE THREAD

**Issue by bartbuurman** [tgriesser/knex#2624]
So I am trying out knexjs and the first setup works like a charm. I've set up my connection, created a datastructure and in my terminal i ran `knex migrate:latest`. 
It all worked fine... the migrated tables showed up in my database ran the migrate again and got `Already up to date`.

Now here is where I get an issue: Using Dotenv... Here is my code:
```js
require('dotenv').config();

module.exports = {

    development: {

        client: process.env.DB_CLIENT,
        connection: {
            
            host: process.env.DB_HOST,

            user: process.env.DB_ROOT,
            password: process.env.DB_PASS,

            database: process.env.DB_NAME,
            charset: process.env.DB_CHARSET

        }
    }
};
``` 

As far as i can see nothing wrong with it and when i run the script through node no errors show up.
Then I wanted to check if I still could do a migrate and i get the following error:

> Error: ER_ACCESS_DENIED_ERROR: Access denied for user ''@'[MY IP]' (using password: YES)

I am using the same vars only this time from my `.env` file. But when i look at the error nothing is loaded from it, and yes both the `knexfile.js` and `.env` are in the root of my project :) Among the things i tried is setting the path in different ways within `require('dotenv').config();` but then it would throw an error from dotenv meaning the file was already correctly loaded.

Can anyone help me figuring this out?

## Environment
Knex CLI version:  0.14.6
Local Knex version:  0.14.6
Database: Remote (works without using dotenv)
OS: Windows

**Comment by elhigu** [comment]
This should go to stackoverflow. Knex doesn't have anything which would break `dotenv`. Try to add console log to you knexfile to see if it is even read correctly in. Also try if setting NODE_ENV=development in your environment helps.

require('dotenv').config();

console.dir(process.env);

module.exports = {

    development: {

        client: process.env.DB_CLIENT,
        connection: {
            
            host: process.env.DB_HOST,

            user: process.env.DB_ROOT,
            password: process.env.DB_PASS,

            database: process.env.DB_NAME,
            charset: process.env.DB_CHARSET

        }
    }
};

**Comment by JoaoRabelo98** [comment]
Thanks @elhigu 
It's works perfectly!!

**Comment by edugrip** [comment]
Yes. It works. @bartbuurman , Thankyou for creating this issue. I learnt how to use dotenv here.

**Comment by KrisLau** [comment]
I'm still having trouble with this it seems like whenever I try to run commands from the terminal the environment values get wiped out

**Comment by avardag** [comment]
1) This issue has to be closed.
2) I had the same issue today, when i tried to set scripts in package.json of my project. Env variables weren't loading. When i tried to log them, it returned `undefined`. Only worked when I did this below:
`scripts:{
    "db:migrate": "node -r dotenv/config ./node_modules/knex/bin/cli.js migrate:latest --knexfile server/db/knexfile.js"
  }`

**Comment by ayoubaayoub** [comment]
i was have the same issue and i solve like this :
in your Knexfile.js
require('dotenv').config({path:path.join(__dirname,'../.env')});
i hope this solution can helped someone.

**Comment by obomheire** [comment]
I had the same issue, require('dotenv').config({path:path.join(__dirname,'../.env')}); works for me all thanks to @ayoubaayoub
