### ISSUE TITLE
returning and wrapIdentifier don't seem to work well together

### ISSUE THREAD

**Issue by koskimas** [tgriesser/knex#2630]
# Environment

Knex version: 0.14.6
Database + version: postgresql 10
OS: arch linux

# Bug

Hi,

I believe `wrapIdentifier` and/or `postProcessResponse` hooks are not called correctly for identifiers passed to `returning` function on postgresql. Here's a piece of code that reproduces the problem:

```js
const knex = require('knex')({
  client: 'postgres',

  connection: {
    host: '127.0.0.1',
    database: 'test'
  },

  wrapIdentifier: (id, oldImpl) => {
    return oldImpl(id + '_foo');
  },

  postProcessResponse: (result) => {
    // This is never called with the return value of the insert query.
    return result;
  }
});

const main = async () => {
  await knex.schema.dropTableIfExists('t');
  await knex.schema.createTable('t', table => {
    table.increments('id');
    table.string('value');
  });

  const retVal = await knex('t')
    .insert({ value: 'hello' })
    .returning('value')
    .debug();

  console.log(`should return ['hello'] but returns`, retVal);
  await knex.destroy();
};

main().catch(console.error);
```

In the example, `retVal` should be `['hello']` (right?) but it is `[undefined]` instead. `wrapIdentifier` seems to be called correctly for the binding, but the `returning` property is not mapped and a wrong column is picked from the return value (maybe, just quessing here).

Or am I missing something obvious?

**Comment by elhigu** [comment]
Looks like wrapIdentifier is called correclty:

https://runkit.com/embed/9i57f0h6k4te

```js
const knex = require('knex')({
  client: 'postgres',

  wrapIdentifier: (id, oldImpl) => {
    return oldImpl(id + '_foo');
  },
});

knex('t')
  .insert({ value: 'hello' })
  .returning('value').toSQL().sql;

// outputs: insert into "t_foo" ("value_foo") values (?) returning "value_foo"
```
So it may be that postProcess is not called in this case... sounds strange. Btw. shouldn't that insert returning return `[{value_foo: 'hello'}]` instead of `['hello']`?

**Comment by koskimas** [comment]
Yeah, `wrapIdentifier` is called for the actual binding, but the query has the "special" `returning` property shown in the `debug()` output, and it holds an unmapped value `value`. Could that be the reason?

> So it may be that postProcess is not called in this case

`postProcessResponse` is indeed not called.

**Comment by linkenneth** [comment]
For some additional context, the original issue was found through: https://github.com/Vincit/objection.js/issues/937

**Comment by wubzz** [comment]
This is quite definitely due to `processResponse` which afaik goes directly on `this.returning` when assembling the returning response. It needs to call `wrapIdentifier` there as well. Same issue should occur for `.pluck(fieldName)` as well.

For example postgres handler:
https://github.com/tgriesser/knex/blob/master/src/dialects/postgres/index.js#L243

**Comment by koskimas** [comment]
I'll create a PR for this. This is blocking a feature in objection.

**Comment by elhigu** [comment]
should be fixed in next release
