### ISSUE TITLE
[DEP0096] DeprecationWarning: timers.unenroll() is deprecated. Please use clearTimeout instead.

### ISSUE THREAD

**Issue by mendrinos** [tgriesser/knex#2631]
# Environment

AdonisJS version: 4.1
Knex version: 0.14.5
Database + version: MySQL 5.7.21
OS: MacOS 10.13.4 (17E202)

# Deprication logs

Using the AdonisJS framework and when I run:

`await Database.raw('use ' + subdomainDbName).get()`

I am getting this deprication logs:

`(node:8013) [DEP0096] DeprecationWarning: timers.unenroll() is deprecated. Please use clearTimeout instead.`

Not a bit issue; but my log files are getting bloated with this Warning, and wondering if it is related to Knex.js?

**Comment by elhigu** [comment]
Did you ask from adonis first? AFAIK it has its own ORM. Please check out with @tutlage first (if I remember correctly he is the author of adonis). If he thinks it really is knex problem please report back and I’ll reopen this.

I dont have laptop with me so I cannot check the facts right now.

**Comment by mendrinos** [comment]
Sure, I have raised it with AdonisJS framework too, and will update here if needed.

https://github.com/adonisjs/adonis-framework/issues/868
