### ISSUE TITLE
groupByRaw does not get passed through correctly

### ISSUE THREAD

**Issue by MartinMuzatko** [tgriesser/knex#2633]
# Environment

Knex version: 0.14.4
Database + version: SQLLite 3.11.0 2016-02-15
OS: Windows 10 / Debian

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do

We get the right SQL statement and bindings when we call knex with `.toSQL()` at the end.
But the execution of the sql statement looks like the `groupByRaw` is getting lost.

2. Error message

Unfortunately - no error message.

3. Reduced test code, for example in https://npm.runkit.com/knex or if it needs real
   database connection to mysql or postgresql, then single file example which initializes
   needed data and demonstrates the problem.

**This is how the DB looks like: **

![image](https://user-images.githubusercontent.com/2950505/40622364-7d5a3050-62a1-11e8-9934-bce5b8dbb9f5.png)

**This is the Knex implementation (variables replaced with values):**

What this SQL Statement does, is to get the average of a number of samples.
If we have 10 rows, and we want 5 samples, we average through 2 rows per sample and return those.

``` js
await knex
    .select('Timestamp', 'GlobalCycles', 'PartCycles', 'PartText', 'PartNumber', 'Source', 
        function() {
            this.count()
            .as('DevRowID')
            .from('EPC as A')
            .where({DevID: dev_id})
            .andWhere('GlobalCycles', '>=', 32900)
            .andWhere('GlobalCycles', '<=', 34000)
            .andWhere('A.rowid','<=','B.rowid')
        })
    .avg('V_1 as '+ (mqtt_names[0] ? mqtt_names[0] : 'V_1'))
    .avg('V_2 as '+ (mqtt_names[1] ? mqtt_names[1] : 'V_2'))
    .avg('V_3 as '+ (mqtt_names[2] ? mqtt_names[2] : 'V_3'))
    .avg('V_4 as '+ (mqtt_names[3] ? mqtt_names[3] : 'V_4'))
    .avg('V_5 as '+ (mqtt_names[4] ? mqtt_names[4] : 'V_5'))
    .avg('V_6 as '+ (mqtt_names[5] ? mqtt_names[5] : 'V_6'))
    .avg('V_7 as '+ (mqtt_names[6] ? mqtt_names[6] : 'V_7'))
    .avg('V_8 as '+ (mqtt_names[7] ? mqtt_names[7] : 'V_8'))
    .avg('V_9 as '+ (mqtt_names[8] ? mqtt_names[8] : 'V_9'))
    .avg('V_10 as '+ (mqtt_names[9] ? mqtt_names[9] : 'V_10'))
    .avg('V_11 as '+ (mqtt_names[10] ? mqtt_names[10] : 'V_11'))
    .avg('V_12 as '+ (mqtt_names[11] ? mqtt_names[11] : 'V_12'))
    .avg('V_13 as '+ (mqtt_names[12] ? mqtt_names[12] : 'V_13'))
    .avg('V_14 as '+ (mqtt_names[13] ? mqtt_names[13] : 'V_14'))
    .avg('V_15 as '+ (mqtt_names[14] ? mqtt_names[14] : 'V_15'))
    .avg('V_16 as '+ (mqtt_names[15] ? mqtt_names[15] : 'V_16'))
    .avg('V_17 as '+ (mqtt_names[16] ? mqtt_names[16] : 'V_17'))
    .avg('V_18 as '+ (mqtt_names[17] ? mqtt_names[17] : 'V_18'))
    .avg('V_19 as '+ (mqtt_names[18] ? mqtt_names[18] : 'V_19'))
    .avg('V_20 as '+ (mqtt_names[19] ? mqtt_names[19] : 'V_20'))
    .from('EPC as B')
    .where({DevID: dev_id})
    .andWhere('GlobalCycles', '>=', 32900)
    .andWhere('GlobalCycles', '<=', 34000)
    .groupByRaw('DevRowID * '+ (number_of_samples-1) + ' / ' + number_of_records[0].nor);
```

**This is how the sql statement looks like:**
```sql
SELECT Timestamp,
       GlobalCycles,
       PartCycles,
       PartText,
       PartNumber,
       Source,
       (
           SELECT count( * ) 
             FROM EPC AS A
            WHERE DevID = 1 AND 
                  GlobalCycles >= 32900 AND 
                  GlobalCycles <= 34000 AND 
                  A.rowid <= B.rowid
       )
       AS DevRowID,
       avg(V_1) AS EnergyConsumptionPerCycle,
       avg(V_2) AS AirConsumptionOfLastSuctionCycle,
       avg(V_3) AS Quality,
       avg(V_4) AS Performance,
       avg(V_5) AS EvacuationTimeT1,
       avg(V_6) AS LeackageOfLastSuctionCycle,
       avg(V_7) AS LastMeasuredFreeFlowVacuum,
       avg(V_8) AS PrimarySupplyVoltage,
       avg(V_9) AS SystemVacuum,
       avg(V_10) AS InputPressure,
       avg(V_11) AS V_11,
       avg(V_12) AS V_12,
       avg(V_13) AS V_13,
       avg(V_14) AS V_14,
       avg(V_15) AS V_15,
       avg(V_16) AS V_16,
       avg(V_17) AS V_17,
       avg(V_18) AS V_18,
       avg(V_19) AS V_19,
       avg(V_20) AS V_20
  FROM EPC AS B
 WHERE DevID = 1 AND 
       GlobalCycles >= 32900 AND 
       GlobalCycles <= 34000
 GROUP BY DevRowID * 2 / 8;
```

**Knex `.toSQL()`:**

``` js
{
bindings: ["1", "32900", "34000", "B.rowid", "1", "32900", "34000"],
Objectsql: "select `Timestamp`, `GlobalCycles`, `PartCycles`, `PartText`, `PartNumber`, `Source`, (select count(*) from `EPC` as `A` where `DevID` = ? and `GlobalCycles` >= ? and `GlobalCycles` <= ? and `A`.`rowid` <= ?) as `DevRowID`, avg(`V_1`) as `EnergyConsumptionPerCycle`, avg(`V_2`) as `AirConsumptionOfLastSuctionCycle`, avg(`V_3`) as `Quality`, avg(`V_4`) as `Performance`, avg(`V_5`) as `EvacuationTimeT1`, avg(`V_6`) as `LeackageOfLastSuctionCycle`, avg(`V_7`) as `LastMeasuredFreeFlowVacuum`, avg(`V_8`) as `PrimarySupplyVoltage`, avg(`V_9`) as `SystemVacuum`, avg(`V_10`) as `InputPressure`, avg(`V_11`) as `V_11`, avg(`V_12`) as `V_12`, avg(`V_13`) as `V_13`, avg(`V_14`) as `V_14`, avg(`V_15`) as `V_15`, avg(`V_16`) as `V_16`, avg(`V_17`) as `V_17`, avg(`V_18`) as `V_18`, avg(`V_19`) as `V_19`, avg(`V_20`) as `V_20` from `EPC` as `B` where `DevID` = ? and `GlobalCycles` >= ? and `GlobalCycles` <= ? group by DevRowID * 2 / 8"
}
```

But when we execute that. We only get ONE row. As if `GROUP BY` would not exist.

In our sql editor, the same query yields 3 results:

![image](https://user-images.githubusercontent.com/2950505/40622756-58a14ee0-62a3-11e8-9a8c-03ca3b2392a9.png)

**Comment by elhigu** [comment]
What does toSQL().toNative() return give you? That is the query which is passed ultimately to the DB driver. If group by clause exist there, the problem is not in knex, but your query is not doing what it is supposed to do. 

This is hardly reduced minimal test case btw. Try to narrow down the problem you are having by dropping all the extra parts from the query which are not necessary to show the strange behavior.

**Comment by MartinMuzatko** [comment]
Thanks a lot, we will try that :)

**Comment by KlausTaeger** [comment]
@elhigu Thanks for the tips. 

The `...toSQL().toNative()` export did not remove the 'group by' operation from the query string.

I created a stripped test at https://runkit.com/huck/my-first-playground with the same result: three aggreations rows when entering the select statement manually. Only one entry in the array returned by knex. 

(The test accesses a table a remote DB with the following content: 
![grafik](https://user-images.githubusercontent.com/39734813/40661969-56802818-6355-11e8-9615-43a2897d1ad0.png)

**Comment by elhigu** [comment]
Ah, yeah. From your playground example the problem is obvious. You are passing column reference as string literal.

```js
.andWhere('A.ID', '<=', 'B.ID')
```

should be:

```js
.andWhere('A.ID', '<=', knex.raw('??', ['B.ID'])) // in future also .andWhere('A.ID', '<=', knex.ref('B.ID')) will work
```

So in your playground this returns correct results:

```js
let query = knex.select('ID',
  function() {
    this.count()
        .as('ROW_ID')
        .from('grouping_test as A')
        .where({GroupID: 1})
        .andWhere('A.ID', '<=', knex.raw('??', ['B.ID']))
    }
    )
    .avg('Value as AVG')
    .from('grouping_test as B')
    .where({GroupID: 1})
  .groupByRaw('FLOOR(??*2/6)', ['ROW_ID']);
```

**Comment by elhigu** [comment]
btw, thanks for good reproduction. it was easy to spot the problem from that one 🎉

**Comment by KlausTaeger** [comment]
@elhigu : Thanks a lot! That helped. I still have to meditate over **why** it worked, though...
