### ISSUE TITLE
Can I use withSchema and batchInsert?

### ISSUE THREAD

**Issue by chriseaton** [tgriesser/knex#2641]
Currently an exception will be thrown if i do something like:

`knex.withSchema('rpt').batchInsert('UserAccounts'...)`

is there a way to use this? Alternatively is is safe to just do a string concat and do:
`knex.batchInsert('rpt.UserAccounts'...)`
?

**Comment by elhigu** [comment]
No, batchInsert is an utility function, which actually not part on query builder chain (this should be mentioned in docs better, or whole batch insert should be moved to separate npm package).

It might break in future, but if it works right now I suppose it works. Thats undefined behaviour currently.

Safest would be to make those batch inserts with normal insert and to use lodash `_.chunk` to make batches.
