### ISSUE TITLE
Undefined max_batch when using knexSnakeCaseWrappers (Objection)

### ISSUE THREAD

**Issue by heisian** [tgriesser/knex#2644]
# Bug
When running `knex` migrations configured with Objection's `knexSnakeCaseWrappers`, the promise handler for the `_latestBatchNumber` query **always** returns a default value of `0`:
```node
// knex/src/migrate/index.js, lines 329-332

_latestBatchNumber(trx = this.knex) {
    return trx.from(getTableName(this.config.tableName, this.config.schemaName))
      .max('batch as max_batch').then(obj => obj[0].max_batch || 0);
  }

```

This is because `max_batch` does not exist in `obj`. The actual structure of `obj`, due to `knexSnakeCaseWrappers` is:
```node
obj = {
  maxBatch: 2
}
```

Defaulting to `0` results in a batch number of `1` always being inserted into the `knex_migrations` table when using `knexSnakeCaseWrappers`.

In effect, this makes all of your migrations only use a single batch, which is potentially **_catastrophic_** when performing a rollback.

# Environment

Knex version: 0.14.6
Database + version: Postgres 10.1
OS: macOS/Linux

Select applicable template from below.
If issue is about oracledb support tag @ atiertant. For MSSql tag @ smorey2 .
Rest of dialects doesn't need tags.

**Comment by koskimas** [comment]
@heisian This is a knex issue. The `postProcessResponse` doesn't receive information whether the query is an "internal" one or not. objection's `posProcessResponse` always maps the response and there is nothing we could do here. Knex should probably not use `wrapIdentifier` and `postProcessResponse` in these kind of internal queries.

**Comment by heisian** [comment]
OK, sounds like a slightly deep-rooted issue.. will think this over - am using my own patched branch for the moment.

Would it be prudent to warn about using `knexSnakeCaseWrappers` in Objection, since the use of such will cause only a single batch to be created and thereby roll back the entire db if a rollback is performed?

**Comment by koskimas** [comment]
We should probably add a warning about using `knexSnakeCaseWrappers` in **migrations**. You can safely use it in the actual code.

**Comment by heisian** [comment]
Ok. Do you think it sounds feasible to adjust Knex to use `wrapIdentifier` when running migrations, i.e., `knex.withSchema('mySchema').table('myTable', (t) => { t.increments('myId') }) but **not** when interacting with the metatable `knex_migrations`? Will be looking into it..

**Comment by kibertoad** [comment]
@heisian Any chance you could create a failing test for reproduction of the issue? I want to try implementing overriding config within single query scope and would appreciate easy repro for the issue to play with.

**Comment by kibertoad** [comment]
@heisian Actually, no need, I've succesfully reproduced everything that I needed and finalizing solution now :)

**Comment by kibertoad** [comment]
@heisian Please review! https://github.com/tgriesser/knex/pull/2914

**Comment by heisian** [comment]
This is great! I still have much more to learn about the Knex internals. @ekeric13 and I will check it out on Monday

**Comment by kibertoad** [comment]
@heisian ahahaha, yeah, Knex internals are fun :D

**Comment by kibertoad** [comment]
@heisian Anything else before you can return upstream :-P?

**Comment by heisian** [comment]
I could use some Grey Poupon....

**Comment by kibertoad** [comment]
:D

**Comment by kibertoad** [comment]
@heisian 0.16.0-next4 is available now! Please let me know how testing it goes :)

**Comment by heisian** [comment]
woooooo!

**Comment by heisian** [comment]
@kibertoad It seems that specifying a `knexfile` doesn't work:
`knex/bin/cli.js:296` - `console.log(argv.knexfile) // outputs path correctly`
`knex/bin/cli.js:58` - `console.log(env.pathToKnexFile) // undefined`

**Comment by kibertoad** [comment]
ouch. thanks for bug report. let me do a hotfix and update our testsuite

**Comment by kibertoad** [comment]
@heisian Please review! https://github.com/tgriesser/knex/pull/2923

**Comment by kibertoad** [comment]
@heisian Can we do the take 2? `0.16.0-next5` with fix is already out.

**Comment by heisian** [comment]
@kibertoad sorry, we were on short week here last week, will be sure to test it out again today!

**Comment by heisian** [comment]
@kibertoad It seems that the `--cwd` flag no longer applies to the `--knexfile` flag. With `0.16.0-next5` I need to specify my `knexfile` path relative to `node_modules/knex/lib/index.js`.

**Comment by heisian** [comment]
One thing I've noticed is that table names in migrations are no longer case insensitive, i.e.:
```node
knex.schema.withSchema('my_schema').table('Table_name', (t) => { ... })
```
and
```node
knex.schema.withSchema('my_schema').table('table_name', (t) => { ... })
```
are not the same, though I see this as a good thing.

**Comment by heisian** [comment]
Ah okay, I've found a big issue - `knexSnakeCaseMappers` no longer seem to get applied to migrations. here is my knexfile, which is the same as when using knex `0.15.x`:

```node
module.exports = Object.assign({
      client: 'pg',
      connection: {
        host: PSQL_HOST,
        port: PSQL_PORT,
        database: PSQL_DATABASE,
        user: PSQL_USERNAME,
        password: PSQL_PASSWORD,
      },
      pool: {
        min: 1,
        max: poolMax,
        afterCreate(conn, cb) {
          const queryString = 'SET timezone="UTC";'
          conn.query(queryString, (err) => {
            cb(err, conn)
          })
        },
      },
      migrations: {
        directory: `${__dirname}/../migrations`,
        stub: `${__dirname}/stubMigrations.js`,
      },
      seeds: {
        directory: process.env.PSQL_SEED_DIR || `${__dirname}/../seeds`,
        stub: `${__dirname}/stubSeeds.js`,
      },
      debug: ['debug'].includes(process.env.DEBUG),
    },
    knexSnakeCaseMappers()
})
```

When running migrations with `0.16.0-next5`:
```node
exports.up = (knex) =>
  knex.schema.withSchema('auth').createTable('emails', (t) => {
    t.increments()
    t.integer('userId').notNullable().index()
    t.foreign('userId').references('id').inTable('auth.users')
    t.string('email').notNullable()
    t.boolean('primary')
    t.boolean('verified').defaultTo(false)
    t.timestamp('createdAt').notNullable()
    t.timestamp('updatedAt').notNullable()
    t.timestamp('deletedAt')
  })

exports.down = (knex) => knex.schema.withSchema('auth').dropTable('emails')
```

```SQL
SELECT column_name FROM information_schema.columns WHERE table_name = 'emails';
/*
Returns:
id
userId
email
primary
verified
createdAt
updatedAt
deletedAt
*/

**Comment by elhigu** [comment]
Ouch... that is really bad, and I just released 0.16.0... we need to fix that and release 0.16.1 asap.

**Comment by kibertoad** [comment]
@heisian 0.16.1-next1 should have addressed CWD and query execution processing regressions, could you take a look? (and sorry for needing so many iterations to get it exactly right)

**Comment by heisian** [comment]
no worries, thank you all for the efforts. I will test it out today. thanks for the update

**Comment by heisian** [comment]
okay, we always explicitly specify the knexfile, so will give it a shot, ty for the heads up

**Comment by heisian** [comment]
oh got it ok will start using it in CI, and will report any discrepancies. I've manually verified that batches are handled correctly. thank you!

**Comment by kibertoad** [comment]
Woohoo! Glad to hear that!
