### ISSUE TITLE
knexjs.raw sending proper bindings but getting results for some bindings

### ISSUE THREAD

**Issue by cunundrummer** [tgriesser/knex#2646]
# Environment
Angular 6 (typescript) frontend -> expressjs (javascript) backend -> mysql

Knex version:
Database + version: MySql 5.7.17
OS: OSX 10.11.6 (15G20015)

Select applicable tempalate from below.
If issue is about oracledb support tag @ atiertant. For MSSql tag @ smorey2 .
Rest of dialects doesn't need tags.

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do

I am calling a knex.raw() to call a stored procedure on mysql.  Tested and working from mysql.
The call is `knex.raw('call getPosts(?)', category)`.  It works with some but not other strings.
I test with

    .then(rows => {

      console.log(rows[0]);
      console.log(rows.length);
      return rows[0][0];
    })
No error messages.  Either the proper results (when returning `rows[0][0]`:

req:
{ name: 'computers' }
Getting posts for category computers
{ method: 'raw',
  sql: 'call getPosts(?)',
  bindings: [ 'computers' ],
  options: {},
  __knexQueryUid: 'be99971d-0db3-4157-80f2-ff5b45ced06f' }
[ [ TextRow {
      id: 3,
      catId: 3,
      userId: 1,
      createdOn: 2018-06-05T17:00:32.000Z,
      editedOn: null,
      expiresOn: 2018-06-05T17:00:32.000Z,
      title: 'Nvidia Graphics card',
      body: 'Graphics card thing $0.' } ],
  ResultSetHeader {
    fieldCount: 0,
    affectedRows: 0,
    insertId: 0,
    info: '',
    serverStatus: 34,
    warningStatus: 0 } ]
2
Closing knex connection for retrieving posts for cat: computers
GET /posts/computers 304 32.089 ms - -

*OR*

an empty response set ([]) (but tested and working in mysql):

req:
{ name: 'jobs' }
Getting posts for category jobs
{ method: 'raw',
  sql: 'call getPosts(?)',
  bindings: [ 'jobs' ],
  options: {},
  __knexQueryUid: 'a7162f00-1103-4b2d-b517-c9f41218adc4' }
[ [],
  ResultSetHeader {
    fieldCount: 0,
    affectedRows: 0,
    insertId: 0,
    info: '',
    serverStatus: 34,
    warningStatus: 0 } ]
2
Closing knex connection for retrieving posts for cat: jobs
GET /posts/jobs 200 22.992 ms - 2

2. Error message

None

3. Reduced test code, for example in https://npm.runkit.com/knex or if it needs real
   database connection to mysql or postgresql, then single file example which initializes
   needed data and demonstrates the problem.

Here is the test script statements from my sql:

    set @bs := 'Buying and Selling'; #Jobs works too
    set @f := 'free';
    call getPosts(@f);
    call getPosts('Buying and Selling');

My stored_procedure:

    CREATE DEFINER=`me`@`host` PROCEDURE `getPosts`(IN categoryName VARCHAR(50))
    BEGIN
	DECLARE categoryId INT;
	DECLARE RESULT_SET VARCHAR(50);
    
    #get Id
    set categoryId = (SELECT id from Categories where name = lower(trim(categoryName)));
    
    #find if isroot
    IF  ( (select isRootCat from Categories c where c.id = categoryId) = TRUE) THEN
        #it is root get all the subcategories... i.e (2,3,4)
		set RESULT_SET = ((select GROUP_CONCAT(c.id SEPARATOR ',') from Categories c where c.parentCatId = categoryId));
		SELECT * from Posts WHERE find_in_set(catId, @RESULT_SET);
        
	ELSE
		#not a root, get all post pertaining to categoryId i.e.'free' = 2
		select * from Posts where catId = categoryId;
    END IF;
    END

**Comment by elhigu** [comment]
Complete (single file) reproduction example with database initialization code for being able to reproduce the results is missing. Maybe reopened if  complete code for reproduction is provided.

**Comment by cunundrummer** [comment]
Cleared all cache, restarted system.  Works now.  Sorry for bothering.
