### ISSUE TITLE
PG dialects throw error while connecting with CockroachDB 2.0

### ISSUE THREAD

**Issue by leopku** [tgriesser/knex#2656]
# Environment

Knex version: ^0.14.2
Database + version: CockroachDB 2.0.2
OS: macOS 10.13.2

Select applicable tempalate from below.
If issue is about oracledb support tag @ atiertant. For MSSql tag @ smorey2 .
Rest of dialects doesn't need tags.

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do

knex config
```
const knex = require('knex')({
    client: 'pg',
    debug: true,
    ssl: false,
    connection: {
        host     : conf.host,
        user     : conf.username,
        password : conf.password,
        database : conf.database,
        port     : conf.port,
        charset  : 'utf8'
    }
});
```

db config
```
{
        'host': '127.0.0.1',
        'username': 'cockroach',
        'password': '',
        'database': 'd',
        port: 26257
    }
```

2. Error message

when connect to database, exception comes `Unexpected exception: TypeError: Cannot read property '1' of null`

3.  By code tracing, the error came from `checkVersion` function in `dialects/postgres/index.js`.
In [line 149](/tgriesser/knex/blob/master/src/dialects/postgres/index.js#L149), 
```
resolver(/^PostgreSQL (.*?)( |$)/.exec(resp.rows[0].version)[1]);
```
the actual result of `select version();` of cockroach is:
```
+--------------------------------------------------------------------------+
|                                 version                                  |
+--------------------------------------------------------------------------+
| CockroachDB CCL v2.0.2 (x86_64-unknown-linux-gnu, built 2018/05/21       |
| 14:55:20, go1.10)                                                        |
+--------------------------------------------------------------------------+
```

4. Simplify fix step is adding 'CockroachDB',
```
resolver(/^(PostgreSQL|CockroachDB) (.*?)( |$)/.exec(resp.rows[0].version)[1]);
```

**Comment by leopku** [comment]
If needed, I will be glad to submit a PR for this issue.

**Comment by elhigu** [comment]
You need to pass version configuration parameter for postgres compatible databases telling with which postgres version they are compatible with. Please check docs section `Initializing the Library` for an example.
