### ISSUE TITLE
memory leak on pool connections

### ISSUE THREAD

**Issue by sre-dev** [tgriesser/knex#2657]
# Environment

Knex version: 0.14.6
Database + version: pg 9.6.1
OS: macos high sierra

# Bug

```
var knex = exports.knex = require('knex')({
  debug: process.env.KNEX_DEFAULT_DEBUG,
  client: 'pg',
  connection: process.env.DATABASE_URL,
  pool: {
    min: 2,
    max: process.env.DB_CONNECTION_POOL_MAX || 10
  }
});
```

I'm getting a memory leak that seems to scale with the number of pool connections I allow. If I set the max connections to 10, then I leak what seems to be all of the data that I load with knex between iterations of my code; however, if I set it to 2, then my heapsize stays within a generally consistent and tolerable range between GCs.

I'm not entirely sure how exactly to go about creating a reproducible snippet since the application is a little unwieldy (though I'll be happy to try if someone can point me in the right direction) and so I can't be entirely sure that it's not my own application logic that's at fault, but the reason I think it might be a knex issue is because the heap dump seems to point to a Promise as being the primary leak, and the error handler for the is a knex client object. Also the fact that the leak scales with pool connections which I don't directly control with my own logic seems a little strange.

<img width="751" alt="screen shot 2018-06-13 at 6 12 02 pm" src="https://user-images.githubusercontent.com/34924774/41386399-1b5b4848-6f36-11e8-9851-ab73d6416359.png">

No clue if this is related to #2573, as I do use a transaction but the the data that I am leaking is being loaded outside it. I should also mention that I was previously using knex 0.12.5, and the leak was also occurring there before I upgraded to 0.14.6.

**Comment by elhigu** [comment]
Needs complete code for reproduction. You need to isolate the code which is actually causing the leak. There is no way to help with this otherwise. 

Can be reopened if minimal reproduction code is provided.
