### ISSUE TITLE
Disable auto commit of knex

### ISSUE THREAD

**Issue by dinhanhhuy** [tgriesser/knex#2659]
# Environment

Knex version: 0.14.6
Database: MySQL
OS: MacOS

# Feature discussion / request: disable auto commit of knex;

1. Explain what is your use case
- i need `BaseDao.syncCache` call after `await callback({trx, caches})` commit
- Im buiding a model transaction that auto sync data after knex transaction finish.

```javascript
//base_model.js
static async transaction(callback) {
        await this._database.primary.transaction(async function(trx) {
            const caches = [];
            await callback({trx, caches}) //do many transactions and assign caching task for `caches`
            trx.commit();
            trx.commit = () => {
                console.log('we disable auto commit of knex'); 
            }
            if (caches.length > 0) {
                await BaseDao.syncCache(caches); //execute `caches` task to sync elastic
            }
        })
    }
```
My sample use of custom transaction:
- update database with knex then auto sync that data to elastic
```javascript
await BaseDao.transaction(async function({trx, caches}) {
            await UserDao.init({trx, caches}).update({id: 1, change: {email: 'update1@gmail.com'}})
            await UserDao.init({trx, caches}).update({id: 2, change: {email: 'update2@gmail.com'}})
            await UserDao.init({trx, caches}).update({id: 3, change: {email: 'update3@gmail.com'}})
            await UserDao.init({trx})
        });
```
By assign empty function to `trx.commit` i already have what i want, but i'm asking are there any better way to do this?

**Comment by elhigu** [comment]
By not returning promise from transaction (async functions does that implicitly). Sorry I don't have right now time to explain more than that.

**Comment by dinhanhhuy** [comment]
Thank you, I have a misunderstanding in my code. Move `BaseDao.syncCache(caches);` outside the `primary.transaction` does the trick.
