### ISSUE TITLE
Access to private types in index.d.ts

### ISSUE THREAD

**Issue by jwhitmarsh** [tgriesser/knex#2664]
Apologies if this is the wrong place to raise this, but I raised it in https://github.com/DefinitelyTyped with no luck. 

Is there a reason the types below aren't exported? My use case is to extend Knex and so access to those types would be useful. 

```typescript
type Callback = Function;
type Client = Function;
type Value = string | number | boolean | Date | Array<string> | Array<number> | Array<Date> | Array<boolean> | Buffer | Knex.Raw;
type ValueMap = { [key: string]: Value | Knex.QueryBuilder };
type ColumnName = string | Knex.Raw | Knex.QueryBuilder | {[key: string]: string };
type TableName = string | Knex.Raw | Knex.QueryBuilder;
```

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/1254d58f4afc5e2d361656aecc3c7a51e1bc10db/types/knex/index.d.ts#L17-L21

**Comment by elhigu** [comment]
I have no idea. Closing since not knex issue. If someone has a clue, please feel free to answer to this thread anyways.

**Comment by pupudu** [comment]
I had the same issue. Ended up just copy pasting the types to my own module.

**Comment by kibertoad** [comment]
@pupudu Types are now included in knex repository. Please let us know if some of the ones you need are still private in 0.17.x

**Comment by pupudu** [comment]
@kibertoad That's good news indeed. I tried to grab `Partial`, `SafePartial` and `MaybeArray` and failed. Maybe the way I was trying to do is wrong? 

Here's what I tried:
```
import {Partial} from 'knex'; // Doesn't seem to export it
```
Please advise the right way to do it.
