### ISSUE TITLE
Generate .sql files with CREATE TABLE syntax

### ISSUE THREAD

**Issue by mikeerickson** [tgriesser/knex#2667]
I am not sure where to go to ask this, so I am trying here.  I have perused the documentation and the internet trying to find a place where I can extract CREATE TABLE syntax for each table in a database.

My desired end results is to procedural generate migrations, so I don't have to create table migration by hand?   Does knex have the ability to do this?

I have reviewed `mysqldump` and it looks like it will generate the individual .sql files which is fine, but it has a lot of extra "stuff" that I would like to minimize.

Further, if anybody has a recommendation for a tool that could be used to manage `mysql` migrations, I would appreciate any recommendations

**Comment by elhigu** [comment]
Not a knex issue. mysqldump is way to go. Try stackoverflow maybe.

**Comment by mikeerickson** [comment]
@elhigu Ah, sorry I kept this issue open.  I was able to do exactly as I wanted using `mysqldump`My apologies for not circling back and closing this accordingly.
