### ISSUE TITLE
SAP HANA connection

### ISSUE THREAD

**Issue by dmi2012** [tgriesser/knex#2671]
Hi all,

I am interested in having the knex connector to link to my SAP HANA database through knex.
There is a 'hdb' connector that can be installed through npm.

Is there any interest in the community to support this type of database?
I've been trying to make it work - but don't have the right technical skills to do it...

**Comment by elhigu** [comment]
It should be done as a separate npm module. Check contributing.md https://github.com/tgriesser/knex/blob/master/CONTRIBUTING.md#i-would-like-to-add-support-for-new-dialect-to-knex-is-it-possible

**Comment by elhigu** [comment]
Anyone interested of implementing that package can discuss about it here in this issue commentsthough.

**Comment by var-kar** [comment]
If you are still looking for this please find this repo. https://github.com/jasny/knex-hdb. Although I am not sure why custom client class in not working for him(jasny).
