### ISSUE TITLE
Support default return values for the function `first` or return `null`.

### ISSUE THREAD

**Issue by roytz** [tgriesser/knex#2672]
# Environment

Knex version: 0.14.6
Database + version: Postgresql 10.4
OS: MacOS Sierra

# Feature discussion / request

Support default return values for the function `first` or return `null`.
The current behavior of `first` when no row found is to return `undefined` and when having a function that returns a promise with `knex` query that ends with `.first()` it means that this function might return `undefined`.
This causes a problem if you use `Hapi` as your server.

**Comment by elhigu** [comment]
I don't think this is a good idea. 

Null and undefined means different things. If null is returned, it might mean that row was found and certain  column was selected, but there was NULL stored in that column.

If there would be added new builder method `.returnNullInsteadOfUndefinedWhenRowNotFound()` it would be as easy to just add `.then(val => _.isUndefined(val) ? null : val)` to that query (of course you would write some helper function for that).

**Comment by roytz** [comment]
Thanks @elhigu but that's not accurate... If the column value is null, knex will return an object with the column name as key and the value will be null.
By definition, if the row wasn't found we should get null - http://www.ecma-international.org/ecma-262/6.0/#sec-terms-and-definitions-undefined-type

```
4.3.10 undefined value

primitive value used when a variable has not been assigned a value

4.3.12 null value

primitive value that represents the intentional absence of any object value
```

**Comment by elhigu** [comment]
> If the column value is null, knex will return an object with the column name as key and the value will be null

In most of the cases yes, but in some cases it doesn't (IIRC if you use pick() or update with returning definition with single column given to returning part.

```
4.3.10 undefined value

primitive value used when a variable has not been assigned a value

4.3.12 null value

primitive value that represents the intentional absence of any object value
```

That is basically just talking about when you have variables. Real world doesn't really work like that. For example lodash returns undefined when value was not found and so does pretty much every other library when it is convenient to make distinction between value being null and undefined. Even `Array.find` and other javascript's "standard library" methods uses `undefined` to represent that something was not found.

Anyways that doesn't mean that this feature would be out of the question, it just means that it will never be default behaviour in knex.

Is it possible to extend hapi to prevent problems with this?

What is the proposed API for this feature?

**Comment by roytz** [comment]
So maybe we can do it not as default behavior but pass a 2nd argument which is the default in case the row wasn't found? like lodash `get`.
About hapi - that's its behavior.. Changing that changes the lifecycle - https://hapijs.com/api#lifecycle-methods

**Comment by wubzz** [comment]
`.first()` currently supports both `.first([column1, column2])` and `.first(column1, column2)` if I'm not mistaken. So applying a second argument there could be breaking, just pointing that out.

According to docs in that link it supports async functions, so shouldn't a simple `||` solve this?

Before
```javascript
return knex(table).first()
```

After
```javascript
return await knex(table).first() || null;
```

Maybe I'm wrong, I've never used Hapi myself before.

**Comment by roytz** [comment]
Thanks @wubzz , I think you're right regarding the 2nd (and rest) parameter.
I prefer not using the `||` operator for many reason - https://www.codereadability.com/javascript-default-parameters-with-or-operator/
I can use lodash `get` but it's not as nice as if I was able to use knex functionality...

**Comment by wubzz** [comment]
Agreed, closing for now.
