### ISSUE TITLE
Oracle Database Continuous Query Notification

### ISSUE THREAD

**Issue by jremerich** [tgriesser/knex#2677]
Hi, guys!

There is a way that allow me to use de CQN (Continuous Query Notification)?

I'm following this [tutorial](https://blogs.oracle.com/opal/demo-oracle-database-continuous-query-notification-in-nodejs) but I have an error telling that 'subscribe is not a function'

I'm using AdonisJS Framework. My code follows:
```
Database.connection('oracle')
    .subscribe('mysub', {
        sql: "SELECT sysdate FROM dual",
        callback: function (message) {
            console.log('message subscribe: ', message);
        }
    })
    .then(function (ret) {
        console('retorno then: ', ret)
    })
    .catch(function (ret) {
        console.error('retorno catch: ', ret)
    })
```

**Comment by elhigu** [comment]
No. you need to use oracle db driver directly I suppose if it is even possible with that.
