### ISSUE TITLE
select oralce sequence nextval  not working well

### ISSUE THREAD

**Issue by KAIXIE** [tgriesser/knex#2680]
knex.select(`S_t_role_info.NEXTVAL`).from('dual') run result is 
the following picture

![a](https://user-images.githubusercontent.com/11786672/42135027-0bf51316-7d78-11e8-915d-f9fd01a8a454.png)

**Comment by ricardograca** [comment]
Clearly that's not the complete code that is running. Can you share the complete query code and the results in text form instead of a picture?

**Comment by elhigu** [comment]
That works as expected. To write query that you are trying to do you need to use .raw

```js
knex.select(knex.raw('??.NEXTVAL', ['S_t_role_info'])).from('dual').timeout(1000)...
```

**Comment by KAIXIE** [comment]
```
knex.select(knex.raw('S_t_role_info.NEXTVAL')).from(knex.raw('dual')).first().timeout(1000).then(id => {
                console.log({ id: id.NEXTVAL });
                let insertId = id.NEXTVAL;
})
```
debug sql query is: 
`select * from (select S_t_role_info.NEXTVAL from dual) where rownum <= ?`

in oracle the **first()** function call will results error: **Error: ORA-02287: sequence number not allowed here**

**Comment by elhigu** [comment]
@KAIXIE so what kind of query you would like knex to generate? Btw. the one you wrote is not none of those that has been mentioned earlier in this thread.

**Comment by KAIXIE** [comment]
Thank you for your patience, my logic wrong, this condition can not use **first()** function
