### ISSUE TITLE
ClickHouse support

### ISSUE THREAD

**Issue by darky** [tgriesser/knex#2684]
# Feature discussion / request

It gain popularity as column oriented db for big data.
Would be cool to support ClickHouse via knex.

**Comment by elhigu** [comment]
If its a new dialect, check contributingg.md

**Comment by santiagochen** [comment]
> If its a new dialect, check contributingg.md

did you find the solution for clickhouse with knex  ?

**Comment by shahsank3t** [comment]
@darky @santiagochen did you guys find any wrapper or Knex support for ClickHouse?

**Comment by imtiaz101325** [comment]
Was this ever discussed further. Would be cool if knex had fist class support. 
If it's something that would be appreciated then more than happy to look into contributing.
