### ISSUE TITLE
Support EnterpriseDB as part of  PostgreSQL dialect

### ISSUE THREAD

**Issue by hulmgulm-at-work** [tgriesser/knex#2685]
# Environment

Knex version: 0.15.0
Database + version: EnterpriseDB 9.6.2.7
OS: Windows

# Feature discussion / request

1. Explain what is your use case

I need to support EnterpriseDB, which is the commercial version of PostgreSQL. The SQL dialect is the same as for PostgreSQL but with additional features. Staying with the corresponding PostgreSQL dialect is fine for me but choosing postgresql as dialect fails as Knex cannot get the version number. Knex fails with an "Cannot read property '1' of null" error in the function
```JavaScript
checkVersion: function checkVersion(connection) {
    return new _bluebird2.default(function (resolver, rejecter) {
      connection.query('select version();', function (err, resp) {
        if (err) return rejecter(err);
        resolver(/^PostgreSQL (.*?)( |$)/.exec(resp.rows[0].version)[1]);
      });
    });
  },
```
as EnterpriseDB returns a different version format. It will return e.g.
EnterpriseDB 9.6.2.7, compiled by Visual C++ build 1800, 64-bit
as compared to PostgreSQL
PostgreSQL 10.4 on x86_64-pc-linux-musl, compiled by gcc (Alpine 6.4.0) 6.4.0, 64-bit

2. Explain what kind of feature would support this
Allow the use of EnterpriseDB as part of the PostgreSQL dialect.

3. Give some API proposal, how the feature should work
Change the version check, so that it accepts both, PostgreSQL and EnterpriseDB.

**Comment by kibertoad** [comment]
@hulmgulm-at-work If you could create a failing test that would replicate behaviour of EnterpriseDB in this particular scenario, I could take a shot at fixing this.

**Comment by elhigu** [comment]
You need to pass dialect version that is used for knex manually. We decided long ago to not keep up with version strings of every postgres compatible databases.

So something like this should do:
```js
{
  client: 'pg',
  version: '9.6',
  ...
}
```

**Comment by elhigu** [comment]
same works for mysql compatible databases.

**Comment by hulmgulm-at-work** [comment]
Thank you, that solved my issue. Is this documented somewhere? I cannot find it in the documentation.

**Comment by elhigu** [comment]
Yep, in "Initializing the Library" section.

**Comment by jmoral1943** [comment]
It doesn't work with EnterpriseDB timestamps I get null

**Comment by kibertoad** [comment]
@jmoral1943 Could you please submit reproduction code?
