### ISSUE TITLE
Circular dependencies (prevents proper `rollup`)

### ISSUE THREAD

**Issue by danielgindi** [tgriesser/knex#2716]
# Environment

Knex version: 0.15.1
Database + version: Unrelated
OS: Unrelated

# Bug

Rollup spits those out:
```
Circular dependency: node_modules\knex\lib\raw.js -> node_modules\knex\lib\formatter.js -> node_modules\knex\lib\query\builder.js -> node_modules\knex\lib\raw.js
Circular dependency: node_modules\knex\lib\raw.js -> node_modules\knex\lib\formatter.js -> node_modules\knex\lib\query\builder.js ->  commonjs-proxy:C:\Users\Daniel.SILVERBOLT\Desktop\git\endpoint-analyzer\node_modules\knex\lib\raw.js -> node_modules\knex\lib\r
aw.js
Circular dependency: node_modules\knex\lib\raw.js -> node_modules\knex\lib\formatter.js -> node_modules\knex\lib\raw.js
Circular dependency: node_modules\knex\lib\schema\helpers.js -> node_modules\knex\lib\schema\columncompiler.js -> node_modules\knex\lib\schema\helpers.js
Circular dependency: node_modules\knex\lib\schema\helpers.js -> node_modules\knex\lib\schema\columncompiler.js ->  commonjs-proxy:C:\Users\Daniel.SILVERBOLT\Desktop\git\endpoint-analyzer\node_modules\knex\lib\schema\helpers.js -> node_modules\knex\lib\schema\he
lpers.js
Circular dependency: node_modules\knex\lib\schema\helpers.js -> node_modules\knex\lib\schema\tablecompiler.js -> node_modules\knex\lib\schema\helpers.js
Circular dependency: node_modules\knex\lib\schema\compiler.js -> node_modules\knex\lib\schema\helpers.js -> node_modules\knex\lib\schema\compiler.js
Circular dependency: node_modules\knex\lib\schema\compiler.js -> node_modules\knex\lib\schema\helpers.js ->  commonjs-proxy:C:\Users\Daniel.SILVERBOLT\Desktop\git\endpoint-analyzer\node_modules\knex\lib\schema\compiler.js -> node_modules\knex\lib\schema\compile
r.js
```

It is a huge problem, and will make code unexecutable after "rolling up".
The rollup process will convert commonjs deps into "static imports", which do not support circular dependencies.
Then it will end up with a flat hierarchy where there's a reference to a (yet) undefined variable.

Circular dependencies are a design flaw anyway, and could produce unexpected bugs, and should be avoided. Note that ES imports do not support circular deps.

3. Reduced test code, for example in https://npm.runkit.com/knex or if it needs real
   database connection to mysql or postgresql, then single file example which initializes
   needed data and demonstrates the problem.
```
rollup({
            plugins: [
                require('rollup-plugin-node-resolve')({
                    preferBuiltins: true,
                }), 
                require('rollup-plugin-commonjs')({
                    ignoreGlobal: false,
                }), // To convert CommonJS modules to ES2015
            ],
            input: 'index.js',
        });
```

# Feature discussion / request

1. Explain what is your use case
Using *rollup* for packing a module or a project.

2. Explain what kind of feature would support this
Removing circular dependencies by lifting common functions/data to a separate js file.

3. Give some API proposal, how the feature should work
Should really be simple to implement. It's not a change in API or in implementation - but a minor change in structure, where common features that required circular dependencies will be lifted to separate files.

**Comment by ziyaddin** [comment]
Knex version: `0.5.1` or `0.15.1`?

**Comment by danielgindi** [comment]
0.15.1, sorry :-)

**Comment by elhigu** [comment]
> Should really be simple to implement. It's not a change in API or in implementation - but a minor change in structure, where common features that required circular dependencies will be lifted to separate files.

You clearly have not read knex's internal implementation, dialect implementation/formatter etc. are very tightly coupled calling base and dialect implementation back and forth :) So no really easy task to get rid of, but would be nice though. 

Knex contributors knows very well that those parts of knex should be rewritten in a cleaner way and at some point it will be rewritten. 

Anyways I'm closing this report since this is not really a bug, but just a compatibility issue with rollup. This might start working at some point in future.

**Comment by danielgindi** [comment]
No problem :-)

Also some libraries have solved it in a neat and simple way:
https://github.com/Marak/colors.js/commit/f35d715e046cf07c41f7d31eb57d6c16ed4d0f4d

Just putting it here as a reference...

**Comment by yeya** [comment]
I used to include mysql and mysql2 packages - even though I'm using only mysql2 - just to allow rollup.
After updating from 0.95. to 2.4.0 and trying to `rollup` it looks like I need to add
 `better-sqlite3`, 
`sqlite3`, 
`tedious`, 
`pg`, 
`pg-query-stream`, 
and `oracledb` .
😒
