### ISSUE TITLE
defaultTo with uuid_generate_v4() fails due to syntax error

### ISSUE THREAD

**Issue by EIrwin** [tgriesser/knex#2722]
# Environment

Knex version: `0.15.1`
Database + version: Postgres 9.4+
OS: osx

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do

For migrations, when creating tables, we are using the following

```
exports.up = async function(knex) {
	await knex.schema.raw('CREATE EXTENSION IF NOT EXISTS "uuid-ossp"');
	return knex.schema.createTable('apps', table => {
		table
			.uuid('id')
			.primary()
			.defaultTo(knex.schema.raw('uuid_generate_v4()'));
		table.string('name');

	});
};
```
The expected SQL for this should be 

```create table "apps" ("id" uuid default uuid_generate_v4(),  "name" varchar(255))```

But the output is the following

```create table "apps" ("id" uuid default 'uuid_generate_v4()',  "name" varchar(255))```

Notice the quotations around the `uuid_generator_v4()`.

This is causing the following error to occur:

`invalid input syntax for type uuid: "uuid_generate_v4()"`

2. Error message

`invalid input syntax for type uuid: "uuid_generate_v4()"`

3. Reduced test code, for example in https://npm.runkit.com/knex or if it needs real
   database connection to mysql or postgresql, then single file example which initializes
   needed data and demonstrates the problem.

```
// knexfile.js
{
  development: {
  		client: 'pg',
  		version: '7.2',
  		connection: {
  			host: process.env.PGHOST,
  			user: process.env.PGUSER,
  			password: process.env.PGPASSWORD,
  			database: process.env.PGDATABASE,
  		},
  		pool: { min: 0, max: 10 }, //TODO need to look further into this.
  		migrations: {
  			tableName: 'migrations',
  		},
  },
}

// migration file in /migrations directory
exports.up = async function(knex) {
	await knex.schema.raw('CREATE EXTENSION IF NOT EXISTS "uuid-ossp"');
	return knex.schema.createTable('apps', table => {
		table
			.uuid('id')
			.primary()
			.defaultTo(knex.schema.raw('uuid_generate_v4()'));
		table.string('name');

	});
};
```

**Comment by adiospace** [comment]
Use `knex.raw` instead of `knex.schema .raw`

**Comment by elhigu** [comment]
yup, knex .schema.raw is for adding complete raw queries to schema builder, not for creating parts of query builder.

**Comment by EIrwin** [comment]
Looks like this worked. Thanks!
