### ISSUE TITLE
Fatal error when running a migration with knex CLI which returns `undefined` instead of a Promise

### ISSUE THREAD

**Issue by leontastic** [tgriesser/knex#2725]
# Environment

Knex version:
Database + version: PostgreSQL 10.4 + Knex 0.15.2
OS: Mac OS

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do

Fatal error when running a migration with knex CLI which returns `undefined` instead of a Promise

2. Error message

`TypeError: Cannot read property 'knex' of undefined`
This originates from this line https://github.com/tgriesser/knex/blame/f55140f4f6684730d8e2cdca5b351b30a99afc81/src/migrate/index.js#L413

I believe this line is a bug.

3. Reduced test code, for example in https://npm.runkit.com/knex or if it needs real
   database connection to mysql or postgresql, then single file example which initializes
   needed data and demonstrates the problem.

Example migration run with `knex migrate:latest` or `knex migrate:rollback`:

```node
exports.up = () => {}
exports.down = () => {}
```

**Comment by sshaw** [comment]
Just ran into this with 0.15.2 😢

**Comment by sshaw** [comment]
Though in my case I'd consider it a user error as [the docs](https://knexjs.org/#Migrations) are not clear that a promise must be returned...

**Comment by phdowling** [comment]
I'm seeing this issue following a tutorial here: https://mherman.org/blog/2016/09/25/node-passport-and-postgres/
I am trying to run the following migration against postgres:
```
exports.up = (knex, Promise) => {
  return knex.schema.createTable('users', (table) => {
    table.increments();
    table.string('first_name').notNullable();
    table.string('last_name').notNullable();
    table.string('email').unique().notNullable();
    table.string('password').notNullable();
    table.boolean('admin').notNullable().defaultTo(false);
    table.boolean('active').notNullable().defaultTo(false);
    table.timestamp('created_at').notNullable().defaultTo(knex.raw('now()'));
  });
};

exports.down = (knex, Promise) => {
  return knex.schema.dropTable('users');
};

```

**Comment by davidfurlong** [comment]
Getting this issue despite returning Promise.resolve(). Any ideas on how to run an empty migration?

**Comment by stefanmaretic** [comment]
> Though in my case I'd consider it a user error as [the docs](https://knexjs.org/#Migrations) are not clear that a promise must be returned...

What value do I need to resolve?
