### ISSUE TITLE
CTE queries binding wrong values

### ISSUE THREAD

**Issue by eliascodes** [tgriesser/knex#2727]
# Environment

Knex version: 0.15.2
Database + version: PostgreSQL 10.4
OS: macOS 10.13.6

# Bug
When using the `with` method to generate data-modifying CTEs, there seems to be a problem with the value binding; the values passed into the query builders are being bound to the wrong placeholders.

I've got a minimal example:
```js
const knex = require('knex')({
  client: 'pg',
  connection: 'psql://postgres@localhost:5432/<DB_NAME>'
});

const q1 = knex
  .table('user')
  .update({ name: 'foo' })
  .where({ group_id: 1 })

const q2 = knex
  .with('updated_group', (qb) => 
    qb
      .table('group')
      .update({ group_name: 'bar' })
      .where({ group_id: 1 })
      .returning('group_id')
  )
  .table('user')
  .update({ name: 'foo' })
  .where({ group_id: 1 })

console.log('WITHOUT CTE')
console.log(q1.toString())

console.log('WITH CTE')
console.log(q2.toString())
```
This gives me the output:
```
WITHOUT CTE
update "user" set "name" = 'foo' where "group_id" = 1

WITH CTE
with "updated_group" as (update "group" set "group_name" = 'foo' where "group_id" = 1 returning "group_id") update "user" set "name" = 'bar' where "group_id" = 1
```

You can see that in the second example (`WITH CTE`), the bindings of `foo` and `bar` are the wrong way round.

If I use `toSQL` to inspect these queries, the following is the `bindings` array for the second query:
```
bindings: [ 'foo', 1, 'bar', 1 ],
```
So seems like these are being substituted into the query sequentially, and since the `WITH` clause will always come first, the bindings are in the wrong order (should be `[ 'bar', 1, 'foo', 1 ]`). Obviously changing the order of the method chain doesn't affect the final query.

Am I just misunderstanding the `with` API, or is this actually an issue? Thanks.

**Comment by wubzz** [comment]
Seems to be an issue where knex prepares bindings for `.update` prior to [compiling](https://github.com/tgriesser/knex/blob/master/src/query/compiler.js#L167) the `.with` statement which results in reverse order of bindings.

Compiling the `.with` call first seems to fix the issue. Wonder if its the same for select and insert..

Marking as bug.
