### ISSUE TITLE
Async credentials while running migrations

### ISSUE THREAD

**Issue by kurthopfer** [tgriesser/knex#2732]
# Feature discussion / request
I would like to be able to run migrations as part of AWS codepipline through the buildspec process.
Basically a buildspec file issues some commands (node, python, ruby, etc...) after a build has completed.
I want to be able to run `knex migrate:latest --env dev` which works fine if I have my database connection object hard-coded, either in the knexfile.js or a config file. But since I am storing all of the connection information in AWS Secrets manager I have to make an async call to secrets manger before I can populate the knexfile.

I am not sure how in-demand this feature would be but I believe it should be somewhat simple to implement.

**Comment by elhigu** [comment]
I think this would be good feature to have. I've also stumbled on this and have helped few times someone else to work around this.

**Comment by elhigu** [comment]
Implementation could be as easy as just allow to return promise from knexfile.js instead of synchronous configuration object.

**Comment by mkiddTempus** [comment]
I'm having this exact issue as well. Does anyone have suggestions for a work around?

**Comment by elhigu** [comment]
@mkiddTempus dont use knex commandline client for running migrations and that way you can decide to first fetch all secrets before trying to create DB connection

**Comment by mkiddTempus** [comment]
How do you not use the CLI for running migrations? 

I did just create a second cli-specific knexfile with hard coded values and passed it in via --knexfile and  while that worked locally I don't think my devops team will go for it.

**Comment by elhigu** [comment]
By calling migration API in your app code https://knexjs.org/#Migrations-latest

**Comment by mkiddTempus** [comment]
In the mean time since I posted I did some searching and also found this solution: https://york.io/2016/05/04/knex-reset-migrations.html

This still would be a nice feature to have.

**Comment by jyrkiput** [comment]
I had the almost similar issue with AWS Lambdas, where I wanted to get secrets from Secret Manager. My solution was to write custom client, where most the code comes from Postgres client and AWS examples

```
var lodash = require('lodash')
var Client_PG = require('knex/lib/dialects/postgres/')
var inherits = require('inherits');
var Promise = require('bluebird').Promise;

function SecretsManagerClient(config) {
    Client_PG.apply(this, arguments)
}

inherits(SecretsManagerClient, Client_PG)

function createConnectionSettings(connectionSettings) {
    return new Promise(function(resolve, reject) {
        var AWS = require('aws-sdk'),
            region = connectionSettings.region,
            secretName = connectionSettings.secretName,
            secret;

        var client = new AWS.SecretsManager({
            region: region
        });

        client.getSecretValue({SecretId: secretName}, function(err, data) {
            if (err) {
                reject(err);
            }
            else {
                if ('SecretString' in data) {
                    secret = data.SecretString;
                } else {
                    let buff = new Buffer(data.SecretBinary, 'base64');
                    decodedBinarySecret = buff.toString('ascii');
                }
            }

            var connection = JSON.parse(secret);

            var settings = {
                host: connectionSettings.host || connection.host,
                user: connection.username,
                password: connection.password,
                database: connection.dbname,
                charset: "utf8",
                debug: connectionSettings.debug
            }
            resolve(settings)
        })
    })
}

lodash.assign(SecretsManagerClient.prototype, {
    acquireRawConnection() {
        const client = this;
        return createConnectionSettings(this.connectionSettings).then(function(connectionSettings) {
            return new Promise(function(resolver, rejecter) {
                const connection = new client.driver.Client(connectionSettings);
                connection.connect(function(err, connection) {
                    if (err) {
                        return rejecter(err);
                    }
                    connection.on('error', (err) => {
                        connection.__knex__disposed = err;
                    });
                    connection.on('end', (err) => {
                        connection.__knex__disposed = err || 'Connection ended unexpectedly';
                    });
                    if (!client.version) {
                        return client.checkVersion(connection).then(function(version) {
                            client.version = version;
                            resolver(connection);
                        });
                    }
                    resolver(connection);
                });
            }).tap(function setSearchPath(connection) {
                return client.setSchemaSearchPath(connection);
            });
        });
    }
});
```
Then my configuration is
```
{
        client: SecretsManagerClient,
        driver: "pg",
        connection: {
            region: "eu-west-1",
            secretName: "<secretname>"
        }
}
```

Now I'm able to run migrations from CLI if needed, and lambdas also have access to credentials in Secrets Manager.

Btw, I'm not too familiar with Node, so code is pretty rough and there probably is better way to achieve this :)

**Comment by Ali-Dalal** [comment]
@jyrkiput I tried to run the code you provide to load config from secret manager for example, the config loaded successfully but I am not getting any response of Knex. nothing shown in console either. can you please help?

**Comment by elhigu** [comment]
Closing in favor of #3340
