### ISSUE TITLE
knex.raw does not support case-sensitive strings

### ISSUE THREAD

**Issue by ziyaddin** [tgriesser/knex#2734]
# Environment

Knex version: 0.15.0
Database + version: PostgreSQL
OS: Linux

# Bug

When I try to run a raw query similarly below:

```return knex.raw('select sum(personalLikes) from users').then(...)```

I get the following error:

```Unhandled rejection error: column "personallikes" does not exist```

Seems that knex does not support case-sensitive strings and converts `personalLikes` into `personallikes`.

**Comment by ricardograca** [comment]
It's not knex, it's Postgresql. Try with:

```
return knex.raw('select sum("personalLikes") from users').then(...)
```
