### ISSUE TITLE
Knex doesn't retrieve full number when it starts with 0

### ISSUE THREAD

**Issue by Zaseth** [tgriesser/knex#2736]
Hello.

I have a value in my table that is this number: `057`.

I select the row using:

```javascript
getPlayer (username) {
	return this.knex("users").first("*").where({username)
}
```
This returns:
```
{ id: 100,
  red: 249,
  green: 210,
  blue: 57 }
```

`blue` is actually `057`, but why is Knex giving me `57`?

**Comment by kibertoad** [comment]
Numerics in javascript (and in all other languages that I know) can't have zero padding (since it bears no meaning). Are you sure you need it? If yes, use strings.

**Comment by Zaseth** [comment]
Fixed.
