### ISSUE TITLE
Enabling SSL for Connection?

### ISSUE THREAD

**Issue by mets11rap** [tgriesser/knex#2741]
No formatting because it's just a question: How do I enable SSL for PostgreSQL connection?

**Comment by ricardograca** [comment]
```js
require('knex')({
  client: 'pg',
  connection: {
    // ...
    ssl: true
}
```

**Comment by mets11rap** [comment]
Thank you!

**Comment by kibertoad** [comment]
Would be cool if someone made a PR to knex documentation repo with this, as this doesn't seem to be covered  by documentation.

**Comment by mets11rap** [comment]
@ricardograca What key do I use for the actual connection string?

**Comment by mets11rap** [comment]
To clarify what Alex said: You don't need to make the connection key an object. Just put in the URL as a string and add `?ssl=true` to the end.

**Comment by jmrossy** [comment]
+1 to @kibertoad's suggestion of adding this to the docs. Enabling SSL is an important addition for production services and the docs currently don't mention this option.
