### ISSUE TITLE
Oracle Driver missing - Avoid Application Crash 

### ISSUE THREAD

**Issue by Velmuruganms12** [tgriesser/knex#2743]
**# Environment**
@atiertant 

Knex version: 0.15.2
Database + version: Oracle 11g/12g
OS: Centos

**Current Scenario:**
When Oracle client library is not installed Application is getting crashed with error message. Unable to handle exception at connection creation using knex.  It works good when oracle client library when installed.

**Expected :**
We should able to capture the driver missing error in catch block and continue with application.

**# Feature discussion / request :**
we use knex for connecting to oracle, when install oracle client on the machine we dont have issues.

But when we dont have oracle client we are not able to catch exeception application is getting crashed.

Suggest us how we can handle exception better for this scenario.

**Client Connection Code:**

           ```
     client = require('knex')({
                    client: 'oracledb',
                    connection: {
                        user: details.user,
                        database: details.database,
                        host: details.host,
                        port: details.port,
                        password: details.password,
                    }
                });

```

**Error Message :**

0|npm      | Knex: run
0|npm      | $ npm install oracledb --save
0|npm      | Error: NJS-045: cannot load the oracledb add-on binary for Node.js 6.11.4 (linux, x64)
0|npm      | Node.js require() error was:
0|npm      |   DPI-1047: 64-bit Oracle Client library cannot be loaded: "libclntsh.so: cannot open shared object file: No such file or directory". See https://oracle.github.io/odpi/doc/installation.html#linux for help
0|npm      | Node.js require() mapped to /home/XXXXX/node_modules/oracledb/build/Release/oracledb.node
0|npm      | Node-oracledb installation instructions: https://oracle.github.io/node-oracledb/INSTALL.html
0|npm      | You must have 64-bit Oracle client libraries in LD_LIBRARY_PATH, or configured with ldconfig.
0|npm      | If you do not have Oracle Database on this computer, then install the Instant Client Basic or Basic Light package from
0|npm      | http://www.oracle.com/technetwork/topics/linuxx86-64soft-092277.html

**Comment by elhigu** [comment]
Every dialect crashes the same way because of missing require. What would it help if you would be able to catch that error? At least migrator client would still crash anyways... 

I'm failing to see the actual use case here.

**Comment by Velmuruganms12** [comment]
My use case here is application should not crash because of driver issue, instead it should throw error saying oralce client missing by catching the error message.

**Comment by wubzz** [comment]
Can you explain how you would handle this error while keeping the application running? 

All subsequent calls to knex would simply not work, so I'm not sure what you would gain from trying to keep the app running.

It's not fair to consider this a "driver issue" really. Bottom line it's essentially the same thing as trying to start an express app without first installing express - should the app keep running?

**Comment by elhigu** [comment]
if you really want to prevent process from exitting to that you can already override global error handler. That is an error that you really cannot recover from unless you install more stuff and restart app, so I'm still failing to see the benefit in just showing an error (except for preventing restart loop).

**Comment by danderson00** [comment]
I hit this issue, and it took me a little while debugging to figure out what's happening. I have logging suppressed (passing log object with empty log functions - any error logging is done on promise rejection - I'm not interested in "warnings") to avoid console spamming, and the process exiting without any explanation is not ideal.

While I agree with your statement that a missing require is almost certainly a fatal exception and the process should exit, it should not be the responsibility of a library to make the decision of when and whether to exit the process. Consumers should still be able to wrap the initialisation call in a try catch block (or have a rejected promise returned) and handle the error appropriately to the application.

**Comment by wubzz** [comment]
Hm, I missinterpreted this issue. I thought the crash was simply due to not installing the driver module, but we actually end the process explicitly in knex.. I can understand why that isn't optimal.

While I don't see a use-case keeping the application alive with broken knex, I guess I can agree that the lib shouldn't close the application completely on its own accord..

[This](https://github.com/tgriesser/knex/blob/master/src/client.js#L221) line should be changed into `throw new Error(message)`

**Comment by danderson00** [comment]
So I was going to submit a PR with a simple test, but after thinking about it, I'm not convinced the try..catch block here is actually necessary. It's hard to see a scenario where passing the error to the logger gives additional value over just allowing the exception to bubble, and rethrowing the error has the disadvantage of obscuring the original stack trace. I dunno, your call.

Thanks for maintaining an awesome product!

**Comment by danderson00** [comment]
Sorry, this is not right - it adds the instructions to install the module to the message. I'll do a PR next week.

**Comment by elhigu** [comment]
That error print is pretty useful there so that people knows why that require can fail. Error message could always be more extensive. In this case I dont think that loosing original stacktace matters at all. At least I cannot think of any other reason for failing, but missing npm package... hmm or actually also missing depent native library maybe. Anyways if the original error is thrown it should be clear enough I suppose...

**Comment by kibertoad** [comment]
@elhigu Probably this can be closed now?
