### ISSUE TITLE
Decimal support for sqlite

### ISSUE THREAD

**Issue by kornel-kedzierski** [tgriesser/knex#2748]
# Environment

Knex version: 0.15.2
sqlite3: 4.0.1
OS: MacOS 10.13.5

# Feature discussion / request

1. Explain what is your use case
We need support for sqlite's decimal column

2. Explain what kind of feature would support this
Is it necessary to map decimal or double to float?
@ knex/lib/dialects/sqlite3/schema/columncompiler.js

**Comment by elhigu** [comment]
https://www.sqlite.org/datatype3.html

What is sqlite's decimal column type? I can see only float and integer number types there.

**Comment by kamote** [comment]
@kornel-kedzierski knex support decimal however it maps to float internally. https://github.com/tgriesser/knex/blob/master/src/dialects/sqlite3/schema/columncompiler.js#L16-L17

**Comment by elhigu** [comment]
Closing until someone shows that sqlite3 has a decimal type.
