### ISSUE TITLE
Allow returning queryBuilder and not promise

### ISSUE THREAD

**Issue by twiggy** [tgriesser/knex#2751]
Simple feature request, sorry if i missed it in the docs.

It would be nice to say

var snippet = knex.select('id').from('table').toSnippet().join('table2', 'table2.id', '=', 'table.id'); 
query = await knex.where('1', '=', '1');

I see .toString and .toSQL, and then there are things like modify and clone, but it requires wrapping functions it seems. makes more sense in our code to build half the query, then plop on where statements as various conditions are met etc.

Thanks in advance and thanks for the awesome library!

**Comment by elhigu** [comment]
Your code example doesn't make sense at all.

```js
// here you create snippet (or rather preinitialized query builder called snippet)
var snippet = knex.select('id').from('table').toSnippet().join('table2', 'table2.id', '=', 'table.id');

// here you try to do query `select where 1 = 1`, execute it and return the same query that was executed?
query = await knex.where('1', '=', '1');
```

All the things you listed what you would like to be able with knex, you can already do...

Probably there was just an error in your example and you wanted to clone that query and execute it with an additional where clause like this:

```js
const builderSnippet = knex('table').join('table2', 'table2.id', 'table.table2_id');
let rows = await builderSnippet.clone().where('table2.name', 'foobarista');
```

**Comment by twiggy** [comment]
the real issue was the use of "await". it basically like saying knex.from('table').then() without really realizing it. I had it before my call so i kept getting a result set vs a queryBuilder object. was wondering what was actually causing the execution of the sql to trigger with in the chain, must have been tired. Without "await" you get a snippet as you would expect. i think i use await enough my brain just hid it.

1 =1 is just a common sql expression meant as a noop, but not a real code.

thanks @elhigu
