### ISSUE TITLE
Multiple .returning

### ISSUE THREAD

**Issue by Minh42** [tgriesser/knex#2759]
```
return knex('users')
.returning('user_id')
 .insert({
    ...data
  })
.then(function(id) { 
    for (var i = 0; i < 5; i++) {
      knex.transaction(trx => {
        return trx('user_photos')
        .returning('user_id')
        .insert({
          ...data
        })
      })
    }
  })
.then(function(id) {
    for (var i = 0; i < 5; i++) {
      knex.transaction(trx => {
        return trx('user_tags')
          .returning('user_id')
          .insert({
            ...data
        })
      })
    }
  })
```

Hi all, I'm encountering some issues with the .returning function in knex. I want to populate my users table first, my user_photos table and then my user_tags table.  The first .returning works fine and I'm able to get it and use it to populate my user_photos table but for the last table I'm unable to get the user_id (I get null populated). Do you have any ideas? 

Thanks for your help.

# Environment

Knex version: latest
Database + version: mysql/latest
OS: mac

**Comment by elhigu** [comment]
you are not returning anything from your two latter then's. Try stackoveflow for support how to use knex.
