### ISSUE TITLE
knex returning problems: The below code should return the value of 'entries' column but instead return the no of rows/columns affected. Can't figure out the problem

### ISSUE THREAD

**Issue by hbole** [tgriesser/knex#2760]
const knex=require('knex');
const db=knex({
  client: 'mysql',
  connection: {
    host : '127.0.0.1',
    user : 'root',
    password : 'root',
    database : 'facerecognitionapp'
  }
});

app.put('/image',(req,res)=>{
	const { name } = req.body;
	db('users')
	.returning('entries')
	.where('name', '=', name)
	.increment('entries', 1)
	.then(entries => {
		console.log(entries);
	})
	.catch(err=> res.status(400).json('Unable to find entries'));
})

**Comment by hbole** [comment]
After searching a lot i got the info that returning is not supported in mysql.
Please provide an alternative way so that i can use knex with sql and get the same results.
Thank You.

**Comment by wubzz** [comment]
As you already learned from #2616 `returning` is not supported for MySQL, which makes this question more of a StackOverflow question imo.

Nevertheless, I suppose you could just run a second query to fetch updated rows.

```javascript
const where = {name};

await db('users').where(where).increment('entries');

const updatedRows = await db('users').where(where).select();
```

Or use `Raw` if MySQL does indeed support a way of returning full rows, I wouldn't know as I don't use MySQL..
