### ISSUE TITLE
Can't set the default value of a date to `knex.fn.now()`

### ISSUE THREAD

**Issue by maximedupre** [tgriesser/knex#2761]
# Environment

Knex version: `v0.15.2`
Database + version: MySQL `v5.7.18 `
OS: macOS `v10.13.6`

# Bug

Code: 

    table.date('date').notNullable().defaultTo(knex.fn.now())

Error:

    create table `notifications` (`id` int unsigned not null auto_increment primary key, `userId` int unsigned not null, `text` varchar(255) not null, `opened` boolean not null default '0', `date` date not null default CURRENT_TIMESTAMP) - Invalid default value for 'date'
    Error: Invalid default value for 'date'

It should be working because:

 > As of MySQL 5.6.5, TIMESTAMP and DATETIME columns can be automatically initializated and updated to the current date and time (that is, the current timestamp). Before 5.6.5, this is true only for TIMESTAMP, and for at most one TIMESTAMP column per table.

**Comment by elhigu** [comment]
That error you pasted is coming from the database. What is the correct SQL query to achieve what you are trying to do?

**Comment by kibertoad** [comment]
Interesting. Syntax appears to be correct, here is official example:

```
CREATE TABLE t1 (
  ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
```

I wonder if it needs to be CURRENT_DATE to work with Date column. I'll check with MySQL database, it could be that we need fn.nowDate() equivalent for dates; also we definitely could improve our documentation for knex.fn.now()

**Comment by builtbyproxy** [comment]
I used your code @maximedupre 
However instead of table.date i used, table.timestamp

`table.date('date').notNullable().defaultTo(knex.fn.now())`
>
`table.timestamp('date').notNullable().defaultTo(knex.fn.now())`

**Comment by maximedupre** [comment]
I think this ticket is invalid, since I'm creating a "date" column, not a "datetime" column and the quote specifically talks about DATETIME:

> As of MySQL 5.6.5, TIMESTAMP and DATETIME columns can be automatically initializated and updated to the current date and time (that is, the current timestamp). Before 5.6.5, this is true only for TIMESTAMP, and for at most one TIMESTAMP column per table.
