### ISSUE TITLE
Feature: Add return values to the Docs

### ISSUE THREAD

**Issue by LBWright** [tgriesser/knex#2765]
# Environment

Knex version:
Database + version:
OS:

Select applicable tempalate from below.
If issue is about oracledb support tag @ atiertant. For MSSql tag @ smorey2 .
Rest of dialects doesn't need tags.

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do

2. Error message

3. Reduced test code, for example in https://npm.runkit.com/knex or if it needs real
   database connection to mysql or postgresql, then single file example which initializes
   needed data and demonstrates the problem.

# Feature discussion / request

1. Explain what is your use case
There are some cases in which it would be nice to know the return values of a given method. For example, when updated a given record, the update returns the count of records updated. This either isn't documented, or is hidden in the documentation. Delete is another good example. It would be nice to know what the return value of the delete is, according to the docs. I do believe that Knex has excellent documentation and that the maintainers have taken care of most use cases. This would be a useful addition.

2. Explain what kind of feature would support this
All that would need to happen is to add the return values to the docs.

3. Give some API proposal, how the feature should work
Just simply going through the documentation and adding the return values of unspecified functions. I wouldn't mind making the edits and PR myself.

# Missing / erroneus documentation

Send issue to documentation repo, or fix it and send PR https://github.com/knex/documentation

# Questions about how to use knex

Github issues are for knex development. Please send questions how to use knex to
stackoverflow or ask about it in gitter chat.

**Comment by LBWright** [comment]
As I said in the issue, if you have no plans for the feature. I wouldn't mind pulling down the docs and adding to the documentation.

**Comment by ricardograca** [comment]
This would be a great addition, but take a look at the section titled "Missing / erroneus documentation" in the very issue you posted.

**Comment by LBWright** [comment]
Oh hey cool. @ricardograca Really sorry for polluting the issues! I'll make the issue and PR there. Sorry about that.
