### ISSUE TITLE
Firebird

### ISSUE THREAD

**Issue by kerwynrg** [tgriesser/knex#2766]
# Environment

Knex version:
Database + version: Firebird 2.5/3
OS: Linux
I work constantly with firebird databases and I'd like to use knex as I've been doing is awesome.
There is an existing but old fork supporting firebird. https://www.npmjs.com/package/knex-node-firebird
Could it be possible to add firebird as a supported RDBMS in this repo? If that's in your plans it'll be great not to have duplicated code and old dependencies when forking.

### EDIT [08/16/2018]
I'm working on a firebird implementation, is not completed yet but is currently functional with basic behavior.

It's based from [knex-node-firebird](https://www.npmjs.com/package/knex-node-firebird)

This is the repo [Knex(0.15.2) with Firebird](https://github.com/kerwynrg/knex) FWIW.

I'd like to send a pull request to include firebird support in this repo but i don't know if this is functional to someone else.

**Comment by kerwynrg** [comment]
I'm working on a firebird implementation, is not completed yet but is currently functional with basic behavior.

It's based from [knex-node-firebird](https://www.npmjs.com/package/knex-node-firebird)

This is the repo [Knex(0.15.2) with Firebird](https://github.com/kerwynrg/knex) FWIW.

I'd like to send a pull request to include firebird support in this repo but i don't know if this is functional to someone else.

**Comment by elhigu** [comment]
Info about setting up new dialects is found from CONTRIBUTING.md

**Comment by Level0r0s** [comment]
@kerwynrg  not found dialect firebird in

This is the repo Knex(0.15.2) with Firebird FWIW.

please send

**Comment by Tomas2D** [comment]
I did an updated version of knex firebird dialect, check out my package [knex-firebird-dialect](https://github.com/Tomas2D/knex-firebird-dialect)

**Comment by kibertoad** [comment]
@Tomas2D Would you like to send a PR, adding dialect to ECOSYSTEM.md doc?

**Comment by Tomas2D** [comment]
Sure, PR #5003 created.
