### ISSUE TITLE
Inconsistent property name - The most minor issue ever.

### ISSUE THREAD

**Issue by chriseaton** [tgriesser/knex#2771]
# Environment

Knex version: 0.15.2
Database + version: sqlite
OS: linux

# Bug
1. Explain what kind of behaviour you are getting and how you think it should do
The connection setting for sqlite utilizes the property "filename". This property has inconsistent casing with the rest of the project (not camel-case). It should be "fileName". The text "filename" is not one word, but two, or at best, two connected by a hyphen, but in either case should be "fileName" in camel-case.

In fact, you can see you're already using the same text properly in `src/migrate/index.js`:
https://github.com/tgriesser/knex/blob/26dfeb8805bb11b63d76065d244c78c7b380b41b/src/migrate/index.js#L56

**Comment by kibertoad** [comment]
You do realize that this is a breaking change that would require a major version change, right?

**Comment by kibertoad** [comment]
Considering that "filename" is a part of public API, and fileName in migrate/index.js is part of private implementation that users need not be aware of, I would say that public API is currently not inconsistent, and I don't think that fileName is a very frequent casing in config options.

**Comment by chriseaton** [comment]
Doesn't necessary need to be a breaking change if you create a simple fallback in the connection config parsing, something like:
```
connection.filename = connection.filename || connection.fileName;
```
I's just a minor casing issue. If you're following a naming convention, then it's an issue, if you're not, then obviously it doesn't matter. It is inconsistent because the public API uses camel-case for all other config properties, just not this one for some reason (oversight maybe).

**Comment by kibertoad** [comment]
That's true, it may be kept a non-breaking change.

https://en.wikipedia.org/wiki/Filename
Writing filename as one or as two words is equally correct, so casing is not necessarily required.
In the end it boils down to a matter of preference, so I guess it is to be decided by the gods of Knex :)

**Comment by chriseaton** [comment]
Fair enough, I guess it is technically a word, but knex is the only project in the js eco-system I've ever seen it shown in this format. Food for thought.

**Comment by elhigu** [comment]
Those connection parameters are usually passed directly to db driver and reflects naming convention of the driver: 

https://github.com/mapbox/node-sqlite3/wiki/API#new-sqlite3databasefilename-mode-callback

Sqlite3 node driver calls it `filename`.

**Comment by ricardograca** [comment]
@chriseaton I think I've seen way more cases of `filename` than `fileName` being used in javascript or other languages, so I guess the change you proposed was a bit subjective.
