### ISSUE TITLE
increment method Cannot self-increment floating point

### ISSUE THREAD

**Issue by gensir** [tgriesser/knex#2777]
increment method Cannot self-increment floating point

**Comment by gensir** [comment]
have access to ：
knex('users')
                .update({ money: knex.raw('money + ?', money) })
                .where('id', id)

**Comment by elhigu** [comment]
With latest knex plain increment should work too https://runkit.com/embed/0k32ahg9x3mo .. but looks like that method is actually not using parameter bindings correctly. 

Better to do it your way for now.
