### ISSUE TITLE
Limit number of migrations shown in rollback/latest list

### ISSUE THREAD

**Issue by mattishaden** [tgriesser/knex#2779]
# Feature discussion / request

1. Our migrations count are nearing 200 and we're starting to be fed up with scrolling through this long list of migrations that's been run after every test. We want to limit the displayed migrations on both migrate:latest and migrate:rollback.

2. Configuration option, something like:

> migrations: {
>     tableName: 'migrations',
>     limitShown: 10
> }

3. Provide the config attribute to appropriate function and limit the list there? Taking pointers! :)

**Comment by elhigu** [comment]
You don't need to run / rollback migrations after every test.

**Comment by elhigu** [comment]
or knex-db-manager's truncate method write simple truncate helper by hand...

**Comment by mattishaden** [comment]
We already use knex-cleaner, truncating is not the issue. We just don't want the clutter if we run a single test with .only and see 200 migrations before/after.

**Comment by elhigu** [comment]
where are you getting those prints? are you calling knex command line client for running and rolling back migrations? You could call it also directly with migration API which doesn't print any info about ran migrations if you don't want to.

If its knex command line client who is creating those prints --silent switch for that could be reasonable feature to have.

**Comment by ricardograca** [comment]
If you really must run migrations each time the test suite runs (is it a CI service?) and it bothers you that much just turn off output temporarily before running migrations.

Alternatively, if you must re-create the schema each time from scratch (like you seem to be doing) you could thumbs up #1086.
