### ISSUE TITLE
Callback before query is executed

### ISSUE THREAD

**Issue by taybin** [tgriesser/knex#2789]
# Feature discussion / request

I'd like to add query annotations to my postgresql queries for better tracking/integration with database monitoring tools (https://github.com/ankane/shorts/blob/master/The-Origin-of-SQL-Queries.md)

In python tools like sqlalchemy, it's easy to have a function called on the query right before execution, allowing you to modify the query.  It'd be nice to have a similar feature for knex so I could setup the same thing.

The API for such a thing could look similar to the `postProcessResponse` config:

```
var knex = require('knex')({
  client: 'postgresql',
  globalPreExecuteQuery: (statement) => `${statement}/*application:MyApp*/,
});
```

Another idea is to be able to set it in middleware, so we can pass the request object to it:
```
app.use(function (req, res, next) {
    knex.annotateQueries((statement) => `${statement}/*application:MyApp,endpoint:${req.requestUrl}*/`);
    next();
});
```
And then all of the queries made on that knex connection would include that annotation.

**Comment by elhigu** [comment]
You may be able to use https://knexjs.org/#Interfaces-Events `start` event for this.

**Comment by elhigu** [comment]
Let me know if your use case cannot be implemented with `start` event and in that case we need to reopen and discuss more about this.

**Comment by taybin** [comment]
That's a good place to start.  Thanks.

**Comment by aj070** [comment]
@elhigu It will be nice to have this feature. If I want to do some validations for all the queries that are being executed, for example, JOOQ has [this](https://www.jooq.org/doc/latest/manual/sql-execution/execute-listeners/#example-bad-query-execution-executelistener) to check for bad queries (throw exception on `delete` and `update` queries without a predicate). Please let me know if there is a way to implement this in knex
