### ISSUE TITLE
Multicolumn foreign constraint does nothing

### ISSUE THREAD

**Issue by asafigan** [tgriesser/knex#2791]
# Environment

Knex version:0.15.0
Database + version: postgres

# Bug

`references(columns)` does nothing. I am trying to build a foreign key from multiple columns. But when I run the migration with debug I noticed that the foreign constraint was never built and it throw no error. When I look at the source code it looks like knex does nothing when the input to references is an array.

example: `table.foreign(['role_id', 'tenant_id']).references(['roles.id', 'roles.tenant_id'])`

**Comment by elhigu** [comment]
duplicate https://github.com/tgriesser/knex/issues/1933

**Comment by asafigan** [comment]
Thank you
