### ISSUE TITLE
Data stored in `timestamptz` column not being correctly returned

### ISSUE THREAD

**Issue by mk-nickyang** [tgriesser/knex#2792]
# Environment

Knex version: 0.14.6
PostgreSQL 9.6.2 on x86_64-pc-linux-gnu, compiled by gcc (Debian 4.9.2-10) 4.9.2, 64-bit

# Bug

I have a column named `post_date` in `timestamptz` type, example date: `2018-08-10 17:05:07+00`

When I run
`knex.raw('SET timezone="Australia/Brisbane"; select post_date from TABLE_NAME')`
Result is `2018-08-10T17:05:00.000Z`, which is wrong, no offset.

However, if I run
`knex.raw('SET timezone="Australia/Brisbane"; select post_date::timestamp from TABLE_NAME')`
Result is `2018-08-11T03:05:00.000Z`. which is correct, it has 10 hours offset. 

Why do we still need cast `timestamp` type to it when the column is already in `timestamptz` type? Is this the only way to get the correct date?

**Comment by elhigu** [comment]
You cannot put multiple queries separated with semicolon in single `raw` call. You don't have to cast timestampz to timestamp...

Its easier if you handle your timestamps always in UTC and only cast them to certain timezone when you really need to do it (for example when showing in UI to the end user). You can do timezone conversions for example with luxon on JS side https://moment.github.io/luxon/ 

Anyways, the behavior you are experiencing is not bug in knex. If you need more help how to use  knex + timestamps + timezones you could try stackoverflow.

**Comment by elhigu** [comment]
And if you like to setup your DB to always return timestamps in `Australia/Brisbane` timezone, you should use pool's `afterCreate` attribute to set timezone to where you want when new connection / session is created.
