### ISSUE TITLE
Update to Babel 7

### ISSUE THREAD

**Issue by kibertoad** [tgriesser/knex#2793]
Babel 7 just got released, bringing bags of goodies, among them faster transpilation. Probably it's a good idea for us to upgrade as well.

**Comment by kibertoad** [comment]
@elhigu If you approve, I could work on this.

**Comment by elhigu** [comment]
I suppose it can be updated. I would like more if we could drop it completely, but I don't think that is going to happen at least this year.

**Comment by kibertoad** [comment]
Well, if we migrate to Typescript we could drop it immediately, but since that isn't likely to be completed anytime soon either, April 2019 sounds realistic for when we could drop Babel directly (I don't think we really need any Node 10 features such as async iterators).

**Comment by kibertoad** [comment]
Blocked by https://github.com/59naga/babel-plugin-add-module-exports/issues/65

**Comment by pgebheim** [comment]
Well, this means that knex will break other projects which try to use Babel 7.

Would love to see this upgraded, but also -- why do you require babel-runtime as a non-dev-dep?

**Comment by kibertoad** [comment]
@pgebheim Why would it break them? Other projects consume already transpiled sources so they do not depend on how knex uses Babel.
Babel-runtime is an interesting topic, though. @elhigu Could you comment on why we need it if we transpile anyway?

**Comment by pgebheim** [comment]
@kibertoad Right now its breaking projects because babel-runtime is specified as a dependency, so it gets tracked into every project that includes Babel.

The end result is that there are multiple babel-runtime versions in the project and babel will break.

**Comment by pgebheim** [comment]
Upon further investigation I think the error is a bit of a red herring. Knex definitely shouldn't be exporting babel-runtime as a real dependency, but the issue I am seeing is because electron-compile needs babel6.

It just so happens that since knex provided a real dep for babel-runtime and its version is newer than specified in electron-compile, the loading of the dep resolves to the version specified in Knex.

**Comment by ricardograca** [comment]
Fixed with #2813.
