### ISSUE TITLE
Insert to multiple tables

### ISSUE THREAD

**Issue by c0debreaker** [tgriesser/knex#2795]
I have two tables(users, userdata) that I'd like to insert data when I make a single call to my Express api endpoint. `http://www.example.com/signup`

And the payload that I submit via post is
```
name: 'Scott Denver'
webBrowser: 'Chrome'
```

I'd like to insert name into `users` table. The webBrowser should be inserted to `userdata` data.

What will be the knex insert code for this?

**Comment by elhigu** [comment]
Try stackoverflow.
