### ISSUE TITLE
PostgreSQL - Authentication success with pg, but fail with knex?

### ISSUE THREAD

**Issue by qwang07** [tgriesser/knex#2798]
# Environment

Knex version: v0.15.2
Database + version: PostgreSQL v10
OS: Mac OSX

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do
As my title said authentication fail in knex, but works in pg with the same connection config. It seems like knex do accept the config but does not pass it to driver.

2. Error message
error: password authentication failed for user "qwang"

3. Reduced test code, for example in https://npm.runkit.com/knex or if it needs real
   database connection to mysql or postgresql, then single file example which initializes
   needed data and demonstrates the problem.

```
// db.js
const dbConfig = require('config').dbConfig
//  dbConfig: {
//    client: 'pg',
//    connection: {
//      host: process.env.PG_HOST,  -> '127.0.0.1'
//      port: process.env.PG_PORT, -> '5432'
//      user: process.env.PG_USER, -> 'owner'
//      password: process.env.PG_PASSWORD, -> 'MyStore12345'
//      database: process.env.PG_DATABASE, -> 'mystore'
//    },
//    pool: {
//      min: 3,
//      max: 7,
//    },
//    acquireConnectionTimeout: 5000
//  }

const knex = require('knex')(dbConfig)
const client = new knex.client.driver.Client()

console.error(knex.client)


client.connect(err => {
  if (err) {
    console.error('Error with connecting database: \n', err)
    process.exit(-1)
  }
  console.log('Postgres is ready to use')
  client.end()
})

module.exports = knex

```
Part of output:
```
...
Client_PG {
  config:
   { client: 'pg',
     connection:
      { host: '127.0.0.1',
        port: '5432',
        user: 'owner',
        password: 'MyStore12345',
        database: 'mystore' },
     pool: { min: 3, max: 7 },
     acquireConnectionTimeout: 5000 },
  logger:
   Logger {
     _debug: undefined,
     _warn: undefined,
     _error: undefined,
     _deprecate: undefined },
  connectionSettings:
   { host: '127.0.0.1',
     port: '5432',
     user: 'owner',
     password: 'MyStore12345',
     database: 'mystore' },
  driver:
   PG {
     defaults:
      { host: 'localhost',
        user: 'qwang',
        database: 'qwang',
        password: null,
        connectionString: undefined,
        port: 5432,
...
```
In output, the client accept correct config as its' `config` and `connectionSettings`. However, in the driver, the defaults values ('qwang' which is my username in OS) are wrong and they were used in real connections. It causes authentication error.

**Comment by elhigu** [comment]
Try to use directly `pg` driver to connect it will fail the same way that knex does when you are trying to make query. I don't see anything here which would suggest there is bug in knex causing this.

If you still think this is bug in knex please create single file test with DB initialization etc. to make it possible for others to verify that it doesn't work.
