### ISSUE TITLE
Does knex support peer authentication?

### ISSUE THREAD

**Issue by ashbc** [tgriesser/knex#2801]
# Environment

Knex version: 0.15.2
Database + version: PostgreSQL 10 (pg module@7.4.3)
OS: Ubuntu 18.04

Use case: running postgres and Node app on the same VM, intending to connect via peer authentication

The only information I could find online was #227, which was closed without being resolved.

Current knexfile:
```
module.exports = {
  // ...
  production: {
    client: 'postgresql',
    // ...
    connection: 'postgresql://user@localhost:5432/dbname'
  },
};
```

Output on running `knex migrate:latest`:
`error: password authentication failed for user "user"`

**Comment by kibertoad** [comment]
@ashbc Can you make it work using pure Postgres driver?

**Comment by ashbc** [comment]
Using `pg` with the same connection string gives the same error. Sorry for not trying this out first :P

**Comment by kibertoad** [comment]
np :)

**Comment by ashbc** [comment]
It appears at some point `pg` may have dropped support for connection strings.
https://github.com/brianc/node-postgres/issues/613#issuecomment-285454310

Changing the options to `connection: { host: '/var/run/postgresql', database: 'dbname' }` works fine.

**Comment by kibertoad** [comment]
@ashbc Thank you for posting the solution!
