### ISSUE TITLE
Using .with and .update with some raw objects mixes up bindings

### ISSUE THREAD

**Issue by Gregroam** [tgriesser/knex#2803]
# Environment

Knex version: 0.15.2
Database + version: Postgres 9.6.9
OS: Mac High Sierra

# Bug

Setup:
```
const knex = require("knex")({...});

var t = knex.raw(`(SELECT 1)`);

var query = knex.with("foo", w => {
    w.select(knex.raw(`?, ?, ?, ?`, [1,2,3,4]))
}).from("bar").update("foo", knex.raw(`CASE
    WHEN ? = ? THEN ?
    WHEN ? = ? THEN ?
END`, [
    t, 2, 'a',
    t, 1, 'b'
]));
```

Expected SQL Output:
```
with "foo" as (select 1, 2, 3, 4)
update "bar" set "foo" = CASE
    WHEN (SELECT 1) = 2 THEN 'a'
    WHEN (SELECT 1) = 1 THEN 'b'
END
```

Actual SQL Output:
```
with "foo" as (select 2, 'a', 1, 'b')
update "bar" set "foo" = CASE
    WHEN (SELECT 1) = 1 THEN 2
    WHEN (SELECT 1) = 3 THEN 4
END
```

As you can see, it's mixed up some of the bindings between 2 different raw objects. 
In this example, the "foo" with table has nothing to do with the update part, it was just a quick simple example to show the problem.

**Comment by Gregroam** [comment]
Furthermore, if we separate the raw objects into their own variables and log them

```
var t = knex.raw(`(SELECT 1)`);

var raw1 = knex.raw(`?, ?, ?, ?`, [1,2,3,4]);

var raw2 = knex.raw(`CASE
    WHEN ? = ? THEN ?
    WHEN ? = ? THEN ?
END`, [
    t, 2, 'a',
    t, 1, 'b'
]);

var query = knex.with("foo", w => {
    w.select(raw1)
}).from("bar").update("foo", raw2);
```

console.log(raw1.toString());
```
1, 2, 3, 4
```

console.log(raw2.toString());
```
CASE
    WHEN (SELECT 1) = 2 THEN 'a'
    WHEN (SELECT 1) = 1 THEN 'b'
END
```

Then these 2 show the correct sql pieces,

console.log(query.toString());
```
with "foo" as (select 2, 'a', 1, 'b') update "bar" set "foo" = CASE
    WHEN (SELECT 1) = 1 THEN 2
    WHEN (SELECT 1) = 3 THEN 4
END
```
this still mixes them up

**Comment by elhigu** [comment]
Reopen if this doesn't work with master or with 0.16.0 release... maybe we really should start doing @ next releases to npm to make it easier to verify these.

**Comment by kibertoad** [comment]
"@next" releases would definitely be appreciated greatly :)

**Comment by elhigu** [comment]
I'll try to do one and document the process so that others can do it too afterwards.

**Comment by kibertoad** [comment]
@elhigu I could contribute some time to do releases if that would speed up the process

**Comment by elhigu** [comment]
I dont think we are ready yet to release 0.16.0, but updating those ’next’ releases would be helpful so that I wouldnt have to think about them (thats the main reason I havent done them so far)
