### ISSUE TITLE
Field with more fields

### ISSUE THREAD

**Issue by AncaElena10** [tgriesser/knex#2805]
Which would be the equivalent of

```
const blog = new Schema({
  title: { type: String, required: true },
  body: { type: String, required: true },
  comments: [{
    reply: { type: String, validate: commentValidators },
  }]
});
```

from Mongo do Knex-MySql? How do I create a field with more fields? (like comments)

**Comment by elhigu** [comment]
Sorry, this is not user support channel, try stackoverflow / gitter chat. 

Knex doesn't support this kind of functionality well either (there are no convenience APIs for handling json column types. Also the code pasted does not have anything to do with knex.

Maybe you should start by reading about SQL databases and relations to understand how things work in SQL world.
