### ISSUE TITLE
Process not exit

### ISSUE THREAD

**Issue by nanom1t** [tgriesser/knex#2807]
Hi,

I'm using knex.js in my project and it work well. But I've faced with the next problem. I want to execute some script with cron and it works, but the process not exiting. I know about knex.destroy() method, but it does not help.

Worker.js:
```
var module1 = require('./module1');

module1.doWork().then(function (results) {
    console.log(results);
    module1.disconnect();
}).catch(function (err) {
    module1.disconnect();
});
```
Module1.js:
```
var database = require('./database');
var module2 = require('./module2');

module.exports = {
    doWork: function() {
        module2.doWork2();
    }, 

    disconnect: function () {
        database.disconnect();
    }
};
```
Module2.js:
```
var database = require('./database');

module.exports = {
    doWork2: function() {
        
    }, 

    disconnect: function () {
        database.disconnect();
    }
};
```
database.js:
```
var knex = require('knex')({
    host: configs.DATABASE_HOST,
    port: configs.DATABASE_PORT,
    database: configs.DATABASE_NAME,
    user: configs.DATABASE_USER,
    password: configs.DATABASE_PASSWORD,
    supportBigNumbers: true,
    bigNumberStrings: true
});

module.exports = {
   ....
   disconnect: function() {
       knex.destroy();
   }
};
```
Module1 and Module2 use database.js to work with database as separate units and it works well. The problems happens when I require module2, which uses database.js inside module1. Module1 also uses database. So it looks like knex creates two database connections and I close only one of them. Because of that the process does not exit after execution.

Please help to resolve this issue or tell me what I'm doing wrong.

Thanks

**Comment by nanom1t** [comment]
This issue also happens with next case:
worker.js
```
var module1 = require('./module1');
var module2 = require('./module2');

module1.doWork1().then(function() {
  return module2.doWork2();
}).then(function() {
  module1.disconnect();
  module2.disconnect();
}).catch(function() {});
...

```
module1.js:
```
var database = require('./database');

module.exports = {
    doWork1: function() {...}, 

    disconnect: function () {
        database.disconnect();
    }
};
```
module2.js:
```
var database = require('./database');

module.exports = {
    doWork2: function() {...}, 

    disconnect: function () {
        database.disconnect();
    }
};
```
database.js is the same as in previous example.

**Comment by elhigu** [comment]
Try to use stackoverflow for help for knex usage. If you can create runnable singlefile test code showing that knex.destroy is not working this can be reopened. 

If anyone likes to take better look on this please feel free to keep on discussing also here.

Closing as knex usage issue.
