### ISSUE TITLE
Syntax Error in disposeTimeout

### ISSUE THREAD

**Issue by lmoralejo** [tgriesser/knex#2811]
```js
knex = require('knex')({
  client: 'sqlite3', 
  connection: ':memory:', 
  pool: { 
    min: 1, 
    max: 1, 
    disposeTiemout: 360000*1000, 
    idleTimeoutMillis: 360000*1000 
}});
```

_Originally posted by @elhigu in https://github.com/tgriesser/knex/issues/1871#issuecomment-273721116_

Sorry guys, but there is a syntax error in these lines. It says disposeTiemout, instead of disposeTimeout

**Comment by ricardograca** [comment]
I'm pretty sure that's just a typing mistake on that example.

**Comment by elhigu** [comment]
:D I went ans fixed my old comment. Now it says disposeTimeout.

**Comment by lmoralejo** [comment]
> I'm pretty sure that's just a typing mistake on that example.

The error I took from the botpress code, in version 10.24.4.

**Comment by lmoralejo** [comment]
> > The error I took from the botpress code, in version 10.24.4.
> 
> Sounds like botpress should test their code better and do less copypasting from github comments ;) Thanks for the anecdote though, it was interesting.

The anecdotal thing is that this bug, should not be in this forum, but in the botpress !! haha, I was wrong, thanks guys!
