### ISSUE TITLE
Create migrations with the CLI without knexfile

### ISSUE THREAD

**Issue by bertho-zero** [tgriesser/knex#2819]
### Feature discussion / request

It would be convenient to be able to create migrations without knexfile, one could pass the required arguments to the CLI.

In my case only `client` or `dialect` is necessary but one can also imagine passing the directory of the migrations or other by the arguments.

```
knex migrate:make create_rule_table --client mysql --directory ./migrations
```

**Comment by elhigu** [comment]
Why do you need that? 

Currently big problem with command line client is that it really doesn't have any tests. So until someone writes some test setup for running tests for it we have not been accepting any additions to that part of knex.

**Comment by kibertoad** [comment]
Some projects don't have knexfile in the first place and only pass config to knex instance programmatically. I've seen projects with fictitious knexfile just for generating migrations.
So if someone volunteers to make a solution for testing CLI, this feature request could proceed?

**Comment by elhigu** [comment]
Sure, this is not the first time that something like this has been requested.
