### ISSUE TITLE
Nullable References

### ISSUE THREAD

**Issue by jgomes94** [tgriesser/knex#2822]
# Environment node.js

# Questions about how to use knex

Hello I have the following migration:

```
exports.up = function (knex, Promise) {
    return knex.schema.withSchema('public')
        .createTable('activity', function (t) {
            t.increments();
            t.timestamps(true, true);
            t.string('sfid', 18).unique();
            t.string('account__c', 18).references('sfid').inTable('account');
            t.string('application__c', 18).references('sfid').inTable('application__c').nullable();
            t.specificType('amount__c', 'double precision');
            t.string('document_link__c', 1000);
            t.string('message__c', 255);
            t.string('process_type__c', 255);
        })
};

exports.down = function (knex, Promise) {
    return knex.schema.raw('DROP TABLE public.activity');
};
```

However when i try to create a null reference in application field 

it gives me error.. **insert or update on table "activity" violates foreign key constraint "activity_application__c_foreign"**

**PS:** I didn't show the model because i think it seems like this is a problem with the migration itself however if its relevant i can show the code too

**Comment by elhigu** [comment]
Usage questions should go to stackoverflow, github issues are for development usage (as mentioned is issue template). Closin, but if anyone likes to help, feel free to keep on discussion here. IIRC those should be nullable by default.
