### ISSUE TITLE
TimeoutError: Knex: Timeout acquiring a connection. error using Pool.afterCreate property

### ISSUE THREAD

**Issue by Miteshdv** [tgriesser/knex#2824]
# Environment

Knex version:0.15.2
Database + version:Sqlite3
OS:Linux Mint Sarah 18

Select applicable tempalate from below.
If issue is about oracledb support tag @ atiertant. For MSSql tag @ smorey2 .
Rest of dialects doesn't need tags.

# Bug
By Adding Pool Property , i am getting Connection Timeout error. Even there is just one client, even if i specify max and min pool i get error
TimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?

1. Explain what kind of behaviour you are getting and how you think it should do
Timeout error shouldnt appear by adding pool.afterCreate property
2. Error message
TimeoutError: Knex: Timeout acquiring a connection.

3. Reduced test code, for example in https://npm.runkit.com/knex or if it needs real
   database connection to mysql or postgresql, then single file example which initializes
   needed data and demonstrates the problem.

var knex = require("knex")({
  client: "sqlite3",
  connection: {
    filename: "./db/chinook.sqlite3"
  },
  pool: {
    afterCreate: (conn, done) => {
    
    }
  })
# Feature discussion / request

1. Explain what is your use case

2. Explain what kind of feature would support this

3. Give some API proposal, how the feature should work

# Missing / erroneus documentation

Send issue to documentation repo, or fix it and send PR https://github.com/knex/documentation

# Questions about how to use knex

Github issues are for knex development. Please send questions how to use knex to
stackoverflow or ask about it in gitter chat.

**Comment by elhigu** [comment]
Looks like you are not calling done() callback to tell that `afterCreate`  hook is ready. 

Try:

```
afterCreate: (conn, done) => {
  done();
}
```

**Comment by Miteshdv** [comment]
Thank you , I apologize for bothering you .
It seems i missed this part in docs
