### ISSUE TITLE
SQL to Knex style

### ISSUE THREAD

**Issue by mixkungz** [tgriesser/knex#2828]
Database: MySQL
If I have a where clause 
`where user_id=? and status = ? (month(column1) = ? and year(column1) = ?) or (month(column2) = ? and year(column2) = ?`

How can I write with knex style?

**Comment by k-j-kleist** [comment]
Why do you ignore this part of the issue template?

`# Questions about how to use knex
Github issues are for knex development. Please send questions how to use knex to
stackoverflow or ask about it in gitter chat.`

**Comment by ricardograca** [comment]
Closing this for the reasons @k-j-kleist listed.

**Comment by mixkungz** [comment]
sorry for mistake.
