### ISSUE TITLE
Inserting/saving object with timestamps saving as localtime without timezone instead of UTC with timezone. 

### ISSUE THREAD

**Issue by IsaaX** [tgriesser/knex#2830]
# Environment

Knex version: ^0.15.2
Database + version: postgres 10.5
OS: mac osx 

# Bug
Hello! Really love this package! Am having some issues with postgres db and I've referred to all previous issues with this and have not been able to come to the desired result. 

1. Explain what kind of behaviour you are getting and how you think it should do
So I've been trying to get my timestamps in my database when an object is created to auto populate (
```
table.timestamp('createdAt').notNullable().defaultTo(knex.fn.now())
table.timestamp('updatedAt').notNullable().defaultTo(knex.fn.now())
```

This works but the time stored in the database is local datetime and not UTC timezone. So next thing I attempted to try is setting the timezone correctly, and it does when I do print statements on my node server to the correct utc time. But when I go to save/insert an object, the date gets reconverted back into a local datetime and not UTC time with a timezone attached to it. 

```
pool: afterCreate: (conn, cb) => {
      conn.query(`SET timezone = 'UTC'`, err => {
        cb(err, conn);
      });
    }
```
Then I've tried a variety of `pg.types.setTypeParser` functions that people have suggested in multiple issues. From my understanding this function is called when it's database -> node. I don't think this works for the otherway around. So now I've exhausted all the other options and am wondering if anyone had some insight on this? 

Example of timestamp:
Expected: 2018-09-30T19:55:42Z
Actual: 2018-09-30 14:55:42

**Comment by elhigu** [comment]
Check what type of columns are you having in your DB for your timestamps. They should be `timestamptz` and check from database directly what is stored there. This issue needs complete testcase for reproduction, check CONTRIBUTING.md for details. 

Currently what is described in this issue there are many places where you just might have an user error so actual code for all the stuff you are listing is needed.

**Comment by elhigu** [comment]
Here is maybe the best explanation, that I could find from knex issues... it starts about mysql, but in the end also postgresql is discussed https://github.com/tgriesser/knex/issues/1461#issuecomment-304671676 and the thing mentioned in that comment could be the one you are facing.

**Comment by elhigu** [comment]
> https://github.com/IsaaX/knex-timezone

ps. It seemed that you didn't read the https://github.com/tgriesser/knex/blob/master/CONTRIBUTING.md#what-is-minimal-code-to-reproduce-bug-and-why-i-have-to-provide-that-when-i-can-just-tell-whats-the-problem-is

**Comment by IsaaX** [comment]
I don't believe I follow. I saw the various explanations that you've put out and have followed the suggested recommended solutions `pg-types` in which all lead to the same result of storing the timestamp in my localtime instead of UTC time. Looking at that comment https://github.com/tgriesser/knex/issues/1461#issuecomment-304671676 (which I saw many times before reporting), not sure how that applies in the current situation. That discussion si talking about the value being stored as UTC, while I'm saying that in my case, the values aren't being stored as UTC.

Example:
if my current time is 12:45, then utc time is 5:45 since im in central timezone T-6

So to clarify what I'm concerned about is, I'd assume that the timestamptz value in the database to be stored with timezone, or the value of UTC time which is currently not. 

Example of timestamp stored in the database row:
Actual (Central Time): 2018-09-30 12:45:42
Expected (UTC Time): 2018-09-30T18:45:42Z


Sorry, I did read the guide and added steps and instructions on reproduction but I should have followed it to a tee. Was hoping that would be helpful to you. Didn't mean to agitate.

**Comment by tgriesser** [comment]
@IsaaX is the [timezone of your node app](https://stackoverflow.com/questions/8083410/how-can-i-set-the-default-timezone-in-node-js) set to UTC?

```
TZ='Etc/UTC' node app.js
```

**Comment by IsaaX** [comment]
@tgriesser correct, I tried both `TZ` and `PGTZ`. I also tried the `afterCreate` hook in the pool settings.

```
pool: {
      afterCreate: (conn, cb) => {
        conn.query(`SET timezone = 'UTC'`, err => {
          cb(err, conn);
        });
      }
    },
```

When I do print statements inside of the node server, it prints out the expected UTC time. What I find odd is why isn't that value being stored in the database instead?

**Comment by elhigu** [comment]
> You have probably understood wrongly what timestamp with timezone means in postgresql. 

This was the most important point in the other message. Timestamptz in postgres is stored as utc and values returned for those columns are returned in that timezone which is set for the session (for example in afterCreate). So actual timezone in which data was inserted is never stored to database. It is just converted to UTC.

> Sorry, I did read the guide and added steps and instructions on reproduction but I should have followed it to a tee. Was hoping that would be helpful to you. Didn't mean to agitate.

I know it is not meant to, but without complete single file test-case reproducing your problem it is impossible (or unnecessarily time consuming) to spot which is the user error in this case.

For example this one is completely unclear of the method that you are using to get these values:

```
Example of timestamp stored in the database row:
Actual (Central Time): 2018-09-30 12:45:42
Expected (UTC Time): 2018-09-30T18:45:42Z
```

Complete test case as told in contributing to reproduce your findings eliminates all confusion and I could probably tell right away just from seeing the code, why it behaves like that.

**Comment by IsaaX** [comment]
That's exactly what I'm saying, the timestamps in my database are not UTC time, they are my current time without the timezone. I'd be more than happy to have a UTC time without a timezone but that's not what my issue is. Once again I want to show my appreciation for taking the time to chat it out with me, I've seen how active you are so keep up the work! 

Ill use the current time right now to draw out what is happening. 
It's currently 14:43 (2:43pm) my current time (Central timezone), and if you look up the UTC time now, it says its 19:43 (7:41pm). So I'd expect a timestamp of 19:43 in the database but that isn't the case for myself. 


That makes perfect sense and appreciate the push back! I'll do so in the future as well 👍 
```

const knex = require('knex')({
  client: 'pg',
  
  connection:
    {
      host: 'localhost',
      user: 'postgres',
      socketPath: '',
      password: '',
      database: 'test_timezone',
    },
  pool: {
    afterCreate: (conn, cb) => {
      conn.query(`SET timezone = 'UTC'`, err => {
        cb(err, conn);
      });
    }
  },
  useNullAsDefault: true
});

async function main() {
  await knex.schema.dropTableIfExists('counter')
  await knex.schema.createTable('counter', table => {
    table.increments();
    table.integer('amount').notNull();
    
    
    table
      .datetime('createdAt')
      .notNullable()
      .defaultTo(knex.fn.now());
    table
      .datetime('updatedAt')
      .notNullable()
      .defaultTo(knex.fn.now());
  });
  
  await knex('counter').returning('id').insert({ amount: 5 });
  knex.destroy();
}


main();
```

**Comment by IsaaX** [comment]
I've figured out the issue and it was a user error on my end. The data is correct in the database and the visualizer tool that I use auto casts it into my localtime since there was not timezone stamp on it. Sorry for all the confusion and appreciate the help you gave me @elhigu Keep up the good work guys!
