### ISSUE TITLE
Allow createTable callbacks to be asynchronous

### ISSUE THREAD

**Issue by jaredLunde** [tgriesser/knex#2836]
# Feature discussion / request

1. *Explain what is your use case*
So far as I can tell there isn't a way to asynchronously build columns inside the createTable callback. I came across this use case while creating some helper functions for creating special column types. As it stands, one would have to create extensions, functions, etc. outside of the createTable scope but that seems superfluous (though I can see that same argument being made against this).

2. *Explain what kind of feature would support this*
Allowing createTable callbacks to be asynchronous or return Promises.

3. *Give some API proposal, how the feature should work*
```js
return knex.schema.createTable('accounts', table => {
    table.timestamp('created_at').defaultTo(knex.fn.now()).notNullable()
    return Promise.all([
      // creates a UID function + column
      column(table, 'uid').primary(),
      // creates an extension for citext + column
      column(table, 'username'),
      // creates an extension for citext + column
      column(table, 'email').unique().notNullable(),
      // creates pgcrytpo extension + column
      column(table, 'key')
    ])
  })
```

```js
return knex.schema.createTable('accounts', async table => {
    table.timestamp('created_at').defaultTo(knex.fn.now()).notNullable()
    await column(table, 'uid').primary()
    await column(table, 'username')
  })
```

I do have an escape hatch in the following but it'd still be nice to have this feature IMO
```js
return Promise.all([
  column(knex, 'uid').primary(),
  ...
]).then(
  columns => knex.schema.createTable('accounts', table => {
      columns.forEach(bindCol => bindCol(table))
      table.timestamp('created_at').defaultTo(knex.fn.now()).notNullable()
  })
)
```

Thoughts/concerns?

**Comment by tgriesser** [comment]
`createTable` isn't going to become async as that would break a ton of the internals. I've been working on a rewrite of the internals for the past two weeks that will allow for better conventions for extension with custom behavior. Hopefully going to get a repo up later this week so people can take a look, though it probably won't be ready for awhile. 

I'm not sure what `column` is doing there and why it would need to be async, but I would keep it as it is with the async stuff happening before the `createTable` call.

**Comment by jaredLunde** [comment]
Cool, figured something like that was the case. Thanks!
