### ISSUE TITLE
Remove Node.js 7 from Travis configuration

### ISSUE THREAD

**Issue by kibertoad** [tgriesser/knex#2841]
Are there any reasons why we are running tests against Node.js 7? As is the case with all odd development releases, it's not officially supported.

**Comment by wubzz** [comment]
I think we should remove it. Node 7's 'End-of-life' was 2017-06-30.

I don't see a problem adding the 'inbetween' versions of Node to Travis so long as their enddate has not passed.

**Comment by kibertoad** [comment]
@wubzz Gotcha. Made a PR for that. And yeah, we should add the Node 11 when it lands :).
