### ISSUE TITLE
Migrate rollback all, similar to Laravel

### ISSUE THREAD

**Issue by Jakobud** [tgriesser/knex#2844]
# Environment

Knex version: 0.15.2
Database + version: MariaDB
OS: Linux (Ubuntu)

# Feature discussion / request

1. Ability to rollback all migrations in a single CLI command. Something like `#knex migrate:reset`, very similar to Laravel (https://laravel.com/docs/5.7/migrations#rolling-back-migrations).

2. The CLI would be where the command would be supported

3. I don't know if an API is necessary for it or not. I'm just looking for a CLI command

**Comment by kibertoad** [comment]
Sounds pretty straightforward. Would you be willing to contribute PR for that? (note that there are currently no tests for CLI, so you would also have to come up with a way to test it).

**Comment by Jakobud** [comment]
I'm working on trying to get this thing to build. Running into the following npm install issue:

```
/node_modules/nyc/node_modules/window-size/package.json.1389188851' -> '/vagrant/sandbox/knex/node_modules/nyc                                                                      /node_modules/window-size/package.json'

npm ERR! path /vagrant/sandbox/knex/node_modules/nyc/node_modules/yargs/node_modules/p-locate/package.json.359                                                                      0117351
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open
npm ERR! enoent ENOENT: no such file or directory, open '/vagrant/sandbox/knex/node_modules/nyc/node_modules/y                                                                      args/node_modules/p-locate/package.json.3590117351'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2018-10-09T01_53_33_879Z-debug.log
```

**Comment by damusix** [comment]
Would this be acceptable for MariaDB / Mysql?

``` js

async function resetDb () {
    const result = await db.raw("SELECT table_name FROM information_schema.tables WHERE table_schema = 'mydb';")

    await db.raw("SET FOREIGN_KEY_CHECKS = 0");

    results[0].forEach(async ({ table_name }) => {

        await db.raw("DROP TABLE IF EXISTS '" + table_name + "';");
    })

    await db.raw("SET FOREIGN_KEY_CHECKS = 1");
};

```

This is what I'm currently doing.

**Comment by kibertoad** [comment]
@damusix This is just straightforward deletion of everything. Migrations might be much more granular than that and potentially exist on top of some preexisting DB structure that should remain after all the migrations are torn down.

**Comment by kibertoad** [comment]
Also this probably is going to leave some garbage behind, e. g. table-level functions?..

**Comment by elhigu** [comment]
I don't see how this could work except by just running `.down` function for every migration (that is what laravel reset seems to do).

**Comment by kibertoad** [comment]
> I don't see how this could work except by just running .down function for every migration 

Yep, and this doesn't look too complicated to implement.

**Comment by edevil** [comment]
I'm using this code:
```
async function doRollback(migrate) {
  await migrate.forceFreeMigrationsLock();
  while ((await migrate.currentVersion()) !== "none") {
    await migrate.rollback();
  }
}
```

which works. However, I started obtaining a `MaxListenersExceededWarning` on Knex 0.16. https://github.com/tgriesser/knex/issues/2967

**Comment by zefexdeveloper** [comment]
How is the progress to merge this PR @kibertoad ?

**Comment by kibertoad** [comment]
@zefexdeveloper See #2968. It was already merged.

**Comment by zefexdeveloper** [comment]
Thank you @kibertoad

**Comment by elhigu** [comment]
Sounds like this was done. Closing.
