### ISSUE TITLE
.returning() method not working with MariaDB.

### ISSUE THREAD

**Issue by Willian-Girao** [tgriesser/knex#2851]
# Environment

Knex version: 0.15.2
Database + version: MariaDB 10.0 
OS: Windows

Select applicable tempalate from below.
If issue is about oracledb support tag @ atiertant. For MSSql tag @ smorey2 .
Rest of dialects doesn't need tags.

# Bug
 The .returning() method, according to the documentation, "specifies which column should be returned by the insert and update methods.". When I use this method to return the 'id' column of the inserted/updated row, it actually returns the 'id' value, but when I change the column to be returned it keeps returning the 'id' value. Also, for tables without an 'id' column (as primary key & auto_incremente) it always returns '[0]', even tho the column was successfully inserted/updated.

2. Error message

There are no error messages, but the I only get the behavior described above .

3. The query code:
let test = await this.db('referall_codes').insert({
            code: 'code',
            type_id: 3,
            discount: 3,
            pharmacy_id: 3
          }).returning('code')
 
And if I console.log(test) i get [0], even tho the row is successfully inserted into the database.

Now, if I create a column (id) that is primary key and try the above piece of code with .returning('id), I in fact get the newly created row id, but if I change the .returning() method argument to any other column, it still returns me the 'id' column value for the newly inserted row.

**Comment by elhigu** [comment]
Mariadb / msyql doesn't support that DB feature.

**Comment by Willian-Girao** [comment]
I see. Thx for the reply. I guess MySQL is only able to return auto-incremented values generated by the DBMS.

**Comment by ivanandriollo** [comment]
MariaDB supports insert returning since version 10.5.0 Can we reopen this, or is there another issue open already?

`https://mariadb.com/kb/en/insertreturning/`
