### ISSUE TITLE
Ability to chain forUpdate and forShare to the transaction object

### ISSUE THREAD

**Issue by maximedupre** [tgriesser/knex#2852]
# Environment

Knex version: `v0.15.2`
Database + version: MySQL `v5.7.18`
OS: macOS `v10.13.6`

# Feature discussion / request

I think we should be able to do:

	let transactionStarted = async (trx) => {
         await trx.forUpdate().select('p.*').from('projects as p')
	}

	await knex.transaction(transactionStarted);

Instead we have to do this:

	let transactionStarted = async (trx) => {
         await knex.transacting(trx).forUpdate().select('p.*').from('projects as p')
	}

	await knex.transaction(transactionStarted);

We can already use `trx` as a query builder and chain everything else to it, so I think that the API should be consistant with `forShare` and `forUpdate`

**Comment by elhigu** [comment]
I'm surprised if that doesn't work. I'm sure I have used select for update with trasactions without .transcating syntax. Please add single file reproduction case. 

There is actually test case for this: https://github.com/tgriesser/knex/blob/1c782cf2c89969695301307f52fe55b8452ba07b/test/integration/builder/selects.js#L1082

Does 
```
let transactionStarted = async (trx) => {
     await trx('projects as p').forUpdate().select('p.*');
}

await knex.transaction(transactionStarted);

```

work?

**Comment by maximedupre** [comment]
Oh it does work when use trx as a function.

√ `await trx('projects as p').forUpdate().select('p.*');`
X `await trx.forUpdate().select('p.*').from('projects as p')`
