### ISSUE TITLE
Selecting a null dateTime

### ISSUE THREAD

**Issue by dealercontrolrachel** [tgriesser/knex#2863]
# Environment

Knex version: 0.15.2
Database + version: Mysql 8.0 Ubuntu docker container
OS: macOs High Sierra 10.13.6

# Bug

Okay I don't think this has been asked before, I can't find anything else about it. If it has or if it is supposed to function this way, I apologize. Also I am new to knex so please bear with me.

I have a table with a nullable dateTime column. When I insert a null value and then go select the row in mysql, the value is NULL. 

However, in my application when I do a knex.select for this table and immediately dump the results, the null values come back as 'Invalid Date'. I would expect them to be null. 

Not sure if this is a bug or intended functionality but if anyone has any way around it that would be great. My plan at the moment is to loop through all my results and if I see 'Invalid date' for that column, change it to null but this seems sub-optimal.

**Comment by wubzz** [comment]
Potentially same as #1276

**Comment by kibertoad** [comment]
@dealercontrolrachel This looks easy enough, I'll try to address it today.

**Comment by dealercontrolrachel** [comment]
@wubzz I saw that post and I think this is a similar issue but not the same. Also the solution you linked there is not applicable anymore (that parseType function does not exist in the current build at all) so there is currently no fix to this problem there.

**Comment by dealercontrolrachel** [comment]
Looks like the problem was actually being caused by moment.js in my own files.... Sorry guys!

**Comment by wubzz** [comment]
Yes, looks like the other issue has been resolved since 2016, one way or another.
