### ISSUE TITLE
count with multiple aliased columns

### ISSUE THREAD

**Issue by ricardograca** [tgriesser/knex#2871]
# Environment

Knex version: 0.15.2

# Feature discussion / request

It would be nice to be able to use a single `.count()` call with an object to set multiple aliased count columns instead of having to call it multiple times.

It seems most of the work for this was already done in #2449 so it should be very simple to add support for this. I can provide a PR if there's any interest in having this feature.

Currently if one tries to use this notation only the first key is being used, and the rest is just ignored. 

Instead of:

```js
// ...
.count({ something: 'something.id' })
.count({ somethingElse: 'something_else.id' })
// ...
```

we could just:

```js
// ...
.count({
  something: 'something.id',
  somethingElse: 'something_else.id'
})
// ...
```

**Comment by kibertoad** [comment]
Released in 0.19.1
