### ISSUE TITLE
multiple columns in .orderBy()

### ISSUE THREAD

**Issue by HurSungYun** [tgriesser/knex#2874]
# Environment

Knex version: 0.15.2

# Feature discussion / request

It would be really great to be able to use a single `.orderBy()` when setting order with multiple columns.

For now, I should write code like
```
.select()
.from('table')
.orderBy('a')
.orderBy('b', 'desc')
.orderBy('c', 'desc')
```

It can be simplified like
```
.select()
.from('table')
.orderBy('a', 'asc', 'b', 'desc', 'c', 'desc')
```

or like this
```
.select()
.from('table')
.orderBy(['a', 'asc'], ['b', 'desc'], ['c','desc'])
```

or some other forms better than this would also be okay.

I can work on this if this feature request is accepted.

**Comment by HurSungYun** [comment]
https://github.com/tgriesser/knex/blob/66acbe7719470d22d4aa65fdc9709f2717e1bca7/src/query/builder.js#L542-L550

This code implies a single `.orderBy()` can only handle one column. So for now, I think there is no way to do it.

Another interface suggestions:
```
.select()
.from('table')
.orderBy(['a','b','c'], ['asc', 'desc', 'desc'])
```

```
.select()
.from('table')
.orderBy({
  a: 'asc',
  b: 'desc',
  c: 'desc',
});
```

In implementation level, I wanna suggest two solutions.

* multiple `_statements.push()` in builder

```
for (const column in columns) {
   this._statements.push({
      grouping: 'order',
      type: 'orderByBasic',
      value: column,
      directions[column],
    });
}
```

* add add `type` in `_statements`

```
this._statements.push({
    grouping: 'order',
    type: 'orderByMultiple',
    value: columns,
    directions,
});
```

**Comment by sgoll** [comment]
My two cents: I find the suggested syntax `orderBy('a', 'asc', 'b', 'desc', 'c', 'desc')` very confusing: at first glance it is not clear at all that every other argument has a special meaning (`asc`/`desc` for direction) and is not just another column name. This becomes more problematic when using a variable for the arguments, e.g. `orderBy(...columnsWithDirections)`.

The same goes for `orderBy(['a','b','c'], ['asc', 'desc', 'desc'])`—it is not clear which of the two arrays is the column names and which is the direction (although, arguably, the same could be said for the regular `orderBy(column, direction)` syntax as well, so …

The problem with `orderBy({ a: 'asc', b: 'desc', c: 'desc' })` is that technically no JavaScript engine _guarantees_ the preservation of the order of object attributes (although, all do it).

I'd suggest making the syntax explicit by using objects for each entry in the `orderBy` list—and explicitly using a list as single argument to make the implementation be able to distinguish the multi-column variant from the regular call variant:
```
orderBy([
  { column: 'a', direction: 'asc' },
  { column: 'b', direction: 'desc' },
  { column: 'c', direction: 'desc' },
])
```

In this case, the `direction` attribute would be optional (just as `orderBy(column)` is valid without specifying direction). In that case, we could also make the array items be simple strings that only specify the column name, e.g. `orderBy(['a', 'b', { column: 'c', direction: 'desc' }])`.

The type definition for the multi-column variant of `orderBy()` would then be:
```
orderBy(columns: Array<string | {
  column: string;
  direction?: string; // or: 'asc' | 'desc' ?
}>)
```

**Comment by HurSungYun** [comment]
@sgoll thanks for kind reply and suggestion. I totally agree with you and I like your suggested form of type definition. It would be more clear.

In addition, I believe it would be great to provide single-column and multi-column `.orderBy()` in a single function. So the extended type definition of `.orderBy()` can be like this.

```
function orderBy(column: string | Array<string | {
    column: string;
    direction?: string;
}>, direction? : string)

/*
typeof column === 'string' -> single-column
Array.isArray(column) -> multi-column
*/ 
```

and how about use `order` instead of `direction`?

**Comment by kibertoad** [comment]
@HurSungYun Yeah, I think SQL documentation everywhere uses `order` term to describe asc/desc and not `direction`

**Comment by HurSungYun** [comment]
@kibertoad thanks for comments. I changed my description above. :)

**Comment by sgoll** [comment]
@HurSungYun Yes, that looks good. Depending on whether the first argument to `.orderBy()` is an array (via `Array.isArray()`) we can branch into old-style single-column or new-style multi-column.

Please use `order` since this is in fact the preferred term—though PostgreSQL, MySQL, and MSSQL docs seem to use both terms somewhat interchangeably, "order" is used significantly more often.

Your type definition can be clarified even more (in TypeScript syntax) using overloads to list both call variants separately (thus disallowing the optional `direction` argument from single-column when the first argument is an array):
```
interface OrderBy {
  (columnName: string, order?: string): QueryBuilder;
  (columnDefs: Array<string | { column: string; order?: string }>): QueryBuilder;
}
```
(The `OrderBy` interface is the one from https://github.com/tgriesser/knex/blob/master/types/knex.d.ts)

**Comment by HurSungYun** [comment]
@sgoll it seems to be excellent. 👍 

@elhigu Is there any other stuff to consider before starting to implement this issue?

**Comment by elhigu** [comment]
Sounds good to me 👍

**Comment by HurSungYun** [comment]
Maybe now this issue can be closed. 👍

**Comment by camlegleiter** [comment]
Should the documentation be updated to indicate that this interface change is supported? Currently it still shows the original single column order by functionality. I only discovered this change digging through to see if `orderBy` supported something else.

**Comment by kibertoad** [comment]
@camlegleiter It will be updated after 0.16.0 is out, which, hopefully, should be rather soon.

**Comment by kibertoad** [comment]
There is already https://github.com/knex/documentation/pull/143 which we'll merge before release and rebuild the doc.
