### ISSUE TITLE
bluebird warning

### ISSUE THREAD

**Issue by maikelmclauflin** [tgriesser/knex#2878]
# Environment

Knex version:
Database + version:
OS: mac osx 10.14 (18A391)

Select applicable tempalate from below.
If issue is about oracledb support tag @ atiertant. For MSSql tag @ smorey2 .
Rest of dialects doesn't need tags.

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do
warning from bluebird package
2. Error message
```
(node:67680) Warning: a promise was created in a handler at /characterastronomy/react-auth-server/node_modules/express/lib/router/index.js:317:13 but was not returned from it, see http://goo.gl/rRqMUw
    at Function.Promise.attempt.Promise.try (/characterastronomy/react-auth-server/node_modules/bluebird/js/release/method.js:29:9)
```
3. Reduced test code, for example in https://npm.runkit.com/knex or if it needs real
   database connection to mysql or postgresql, then single file example which initializes
   needed data and demonstrates the problem.
will do this if needed but basically I have traced it to the following warning is encountered when authing for this project: 
https://github.com/characterastronomy/backend
front end is here: https://github.com/characterastronomy/web-ui

but basically, when you unlink, and just call this function the warning occurs from this function. Not sure which function call is causing it tried deleting line by line, but was not able to get rid of it without getting rid of the query: 
```

function setProviders(id, providers) {
  return connection
    .from('users')
    .where('id', id)
    .update('providers', providers)
    .returning('*')
    .then(([user]) => user)
}

```

**Comment by wubzz** [comment]
Based on the information [here](https://github.com/petkaantonov/bluebird/blob/master/docs/docs/warning-explanations.md#warning-a-promise-was-created-in-a-handler-but-was-not-returned-from-it) I'd take a gander and say that it might occur when the update matches 0 rows meaning `user` would be undefined, and is returned, whereas the attached link states:

> // return a non-undefined value to signal that we didn't forget to return

Just a guess without deep investigation.

**Comment by maikelmclauflin** [comment]
If anyone else is seeing this and would prefer not to, i found this in the documentation for now: http://bluebirdjs.com/docs/api/promise.config.html
```

try {
  const bluebird = require('bluebird')
  bluebird.config({
    warnings: false
  })
} catch (e) {
  console.log(e)
}
```

**Comment by wubzz** [comment]
Based on the response I guess I was right, in which case this is not a knex issue. Closing.

**Comment by maikelmclauflin** [comment]
not necessarily. i looked into this and found that a length of 0 users was never found during the query. happy to make a project if nothing pops out as the cause of this

**Comment by ricardograca** [comment]
If you can create a reproducible test case we can take a look.

**Comment by wubzz** [comment]
Feel free to reopen if you discover this to be a knex issue.
