### ISSUE TITLE
Custom cast feature

### ISSUE THREAD

**Issue by jnst** [tgriesser/knex#2880]
# Feature discussion / request

## 1. Explain what is your use case

* https://knexjs.org/#Schema-bigInteger

>Note that bigint data is returned as a string in queries because JavaScript may be unable to parse them without loss of precision.

Basically JavaScript will treat `bigint` as string.
In my case, I using [long.js](https://github.com/dcodeIO/long.js#utility) on the application logic side.

```javascript
const long = Long.fromString('9007199254740992');
```

But it is annoying to convert it to `Long` type after receiving it with `string` type (from `bigint`) each time.
Please define customization function for convert types.

Also, I use TypeScript. It is useful if we can convert `tinyint` to` enum` with customization function.

## 2. Explain what kind of feature would support this

🤔

## 3. Give some API proposal, how the feature should work

On the knex.js side, define customization function for column.
And the developer himself makes the convert code as a function and passes it as an argument to the customization function.

**Comment by jnst** [comment]
I'm sorry, my poor English was broken.
The text was corrected. (maybe)

**Comment by elhigu** [comment]
Each database driver has hooks to tell how different column types read from database should be converted to javascript types. Knex doesn't even have the information of column types so it really cannot be done on knex side.

**Comment by elhigu** [comment]
If you know which columns should be converted you can use https://knexjs.org/#Installation-post-process-response to modify data returned from query.

**Comment by jnst** [comment]
I understood. Thank you. 😀
