### ISSUE TITLE
Knex migrations for multi schema

### ISSUE THREAD

**Issue by xyluet** [tgriesser/knex#2882]
# Environment

Knex version: 0.15.2
Database + version: MySQL 5.6
OS: Windows 7

I have 2 schemas for my database, for example
```
product_en
├── item
product_cn
├── item
```

They exactly same table, but with different language. But how to make knex, make the knex_migrations table to both schema ?

**Comment by kibertoad** [comment]
@xyluet If I understand your use-case correctly, you need to execute knex.migration with two different schemaName values (see https://knexjs.org/#Migrations-API);

In case migrations have to be executed somewhat differently based on which schema you are writing for, take a look at this new feature available in knex NEXT release: https://github.com/knex/documentation/pull/135/files

Please don't hesitate to ask if you have any more questions!

**Comment by xyluet** [comment]
@kibertoad Thank you for quick response. But i have more problem.

My DB:
```
product_en
├── item
├── vendor

product_cn
├── item
├── vendor

sales_en
├── employee

sales_cn
├── employee
```

and if in the future there is new language, it should
```
product_th
├── item
├── vendor

sales_th
├── employee
```

which I need to make 3 migration files
```
item.v1.js
vendor.v1.js
employee.v1.js
```

I quite don't understand how to execute knex.migrate with n schemaName, can you give example?

**Comment by kibertoad** [comment]
Something along the lines of 

```
const migrationConfigs = [
{
    directory: ['db/commonMigrations', 'db/schema1Migrations'],
    tableName: 'schema1_migrations',
    schemaName: 'schema1',
},

{
    directory: ['db/commonMigrations', 'db/schema2Migrations'],
    tableName: 'schema2_migrations',
    schemaName: 'schema2',
}
]

    for (let config of migrationConfigs) {
      await knex.raw(`CREATE SCHEMA IF NOT EXISTS ${config.schemaName}`)
      await knex.migrate.latest(config)
}
```

Are you confident about approach you are taking, though? Duplicating entire table structure just for localization purposes sounds weird; or dataset are actually different based on locale?

**Comment by xyluet** [comment]
Yeah, my team want to use that approach :( Duplicating entire table with same datasets.

Anyway thanks @kibertoad , I finally found workaround for my 'awesome' case.

```js
// TODO
// using env for connection
const dbConnection = require(`./knexfile`).development;

const Knex = require(`knex`);

const LANGUAGE = [`en`, `id`];

const SCHEMAS = [`travel`, `car`, `master`];


SCHEMAS.forEach((schema) => {
  const migrationConfigs = [];

  LANGUAGE.forEach((language) => {
    migrationConfigs.push({
      directory: `./migrates/${schema}`,
      schemaName: `${schema}_${language}`,
    });
  });

  migrationConfigs.forEach(async (config) => {
    // Deep copy without reference
    const knexConnection = JSON.parse(JSON.stringify(dbConnection));

    // create decoy connection just to check schema if exists
    const knexSchema = Knex(knexConnection);
    await knexSchema.raw(`CREATE DATABASE IF NOT EXISTS ${config.schemaName}`);
    knexSchema.destroy();

    // create actual connection for migrations
    knexConnection.connection.database = config.schemaName;
    const knex = Knex(knexConnection);

    try {
      await knex.migrate.latest(config);
      // await knex.migrate.rollback(config);
    } catch (error) {
      console.warn(error);
    } finally {
      // Dont forget to destroy
      knex.destroy();
    }
  });
});
```
