### ISSUE TITLE
@types/knex interface enum not same on doc for Postgres

### ISSUE THREAD

**Issue by deelienardy** [tgriesser/knex#2886]
# Environment

Knex version: 0.15.2
Database + version: Postgres v 10
OS: Linux Ubuntu

# Missing / erroneus documentation

I am using typescript for my project and postgres for db
when i looking on document for enum, its says

> 
> For Postgres, an additional options argument can be provided to specify whether or not to use Postgres's native TYPE:
> 
> table.enu('column', ['value1', 'value2'], { useNative: true, enumName: 'foo_type' })

but on @types/knex, it did not have options for it

> enum(columnName: string, values: Value[]): ColumnBuilder;
> enu(columnName: string, values: Value[]): ColumnBuilder;

It make me can't make enum type, so what is the correct way to make enum type for postgres on typescript?

sorry if this is wrong place for asking this, i don't know where to ask about this.

**Comment by pushplay** [comment]
@deelienardy 
The project you're looking for is https://github.com/DefinitelyTyped/DefinitelyTyped (with knex stuff in https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/knex).

**Comment by kibertoad** [comment]
@pushplay Actually, typings were moved inside knex recently: https://github.com/tgriesser/knex/commit/b2450a94dce9e9bdba9e9fd2cc6107539b72967f

**Comment by pushplay** [comment]
Oh sweet!

**Comment by deelienardy** [comment]
so, i can't use @types/knex right now for postgres enum ?

**Comment by tulios** [comment]
Can you add the new definition? I'm currently doing:

```typescript
import { ColumnBuilder, TableBuilder, Raw } from 'knex'

type Value =
  | string
  | number
  | boolean
  | Date
  | string[]
  | number[]
  | Date[]
  | boolean[]
  | Buffer
  | Raw

export interface IExtendedTableBuilder {
  enum(columnName: string, values: Value[], opts?: object): ColumnBuilder
}
```

and then

```typescript
const extendedTable = table as IExtendedTableBuilder
extendedTable.enum('type', ['MyType'], { useNative: true, enumName: 'my_type' })
```

https://github.com/tgriesser/knex/blob/ff75f1d2bda11ddb8d9679d23364b52dcfa8f268/types/knex.d.ts#L570-L571

**Comment by NRauh** [comment]
I also ran into this issue.

You lose some type checking, but if you can't (or don't want to) do the solution above, this works.

```ts
(t.enu as any)('room', ['optionA', 'optionB'], {
  useNative: true,
  enumName: 'room_name',
});
```

**Comment by davidspiess** [comment]
This was merged a few days ago, see https://github.com/tgriesser/knex/pull/3043.

**Comment by emahnovets** [comment]
HI, @davidspiess . May be you know, when this changes will be released?

**Comment by kibertoad** [comment]
@emahnovets Updating to latest knex version is not an option? That would remove your dependency on external typings.

**Comment by davidspiess** [comment]
@emahnovets sorry i'm not part of the core team, but waiting as well. 
@kibertoad the types are updated in master but there is no official release yet.

**Comment by kibertoad** [comment]
@davidspiess Sorry for inconvenience. I'll try to cleanup changelog and release official version tonight.

**Comment by kibertoad** [comment]
@davidspiess 0.16.4 was just released. Please give it a try and let us know if something is wrong!

**Comment by dipanjanpanja6** [comment]
In doc its says you can use null `table.enu('column', null, { useNative: true, existingType: true, enumName: 'foo_type' })` but it give type error ``Type 'null' is not assignable to type 'readonly Value[]``
