### ISSUE TITLE
Create multiple tables safely in a single migration

### ISSUE THREAD

**Issue by eliranlevi** [tgriesser/knex#2888]
# Environment

Knex version: 0.15.2

# Feature discussion / request

#### 1. Explain what is your use case:

When migration for creating multiple tables fails, you can't really rollback. The situation is that you're stuck with just a half of your migration fully migrated to the database, running `knex migrate:rollback` either throws an error or logs `Already at the base migration` (because when error is thrown the migration isn't added to the `migrations` table) and everything gets unresponsive. You'll eventually have to tweak your way into getting stability again and sometimes it can have serious consequences if you're not sure what you're doing.

#### 2. Explain what kind of feature would support this

Introducing a helper function to clean the DB when not all tables created.

#### 3. Give some API proposal, how the feature should work

I tried the following code snippet on my project and it worked nicely (I made it quickly, there might be place for improvement it but that's the core of the idea):

```JavaScript
const createTablesSafely = knex => tables => {
    const createTables = tables.map(({ name, schema }) => {
      return knex.schema.createTable(name, schema)
    });

    return Promise.all(createTables)
      .catch(e => {
        const dropTables = tables.map(({ name }) => {
          return knex.schema.dropTableIfExists(name);
        });

        return Promise.all(dropTables).then(() => Promise.reject(e));
      });
  }
```

and basic usage example:

```JavaScript
exports.up = function(knex, Promise) {
  return createTablesSafely(knex)([
    {
      name: "users",
      schema(usersTable) {
        usersTable.increments("id").unsigned().primary();
        usersTable.string("username");
        usersTable.string("password");
      },
    },
    {
      name: "cities",
      schema(citesTable) {
        citiesTable.increments("id").unsigned().primary();
        citiesTable.string("name");
      },
    },
    // rest of tables...
  ]);
}
```

So it might be nice if this can somehow be part of knex.

**Comment by elhigu** [comment]
This is too specific functionality to certain edgecase to be added to knex and it will still fail if for example db is disconnected during migration or if process is killed or if it hangs. 

However would be good if we would add runstatus for migration table to see if running some migration has failed. Then we could just run separately down handler of migration to clean it up (separate feature request should be done for that). It would be robust and general solution to clean up failed migrations.
