### ISSUE TITLE
Postgres checkVersion issue

### ISSUE THREAD

**Issue by antoniuslin** [tgriesser/knex#2892]
Hello.

I'm using CockroachDB when I encountered an error, specifically having to do with the source line citation below.

```
Error:
node_modules/knex/lib/dialects/postgres/index.js:186
        resolver(/^PostgreSQL (.*?)( |$)/.exec(resp.rows[0].version)[1]);
                                                                    ^

TypeError: Cannot read property '1' of null
```

https://github.com/tgriesser/knex/blob/932fa4b683812781b5f7ade96e4e26aafe9f7268/src/dialects/postgres/index.js#L145

Instead of the original current line:
`/^/^PostgreSQL (.*?)( |$)/`
I fixed it to be the following:
`/^(PostgreSQL |CockroachDB CCL v)(.*?)( |$)/`

(I'm not opening a PR yet unless invited to do so). The reason I'm raising this as an issue/discussion topic, although understandably, this is not **directly** related to PostgreSQL (why I'm not creating a PR) is to find-out if `knex` team would consider CockroachDB within the same Postgres family of dialect, especially since CockroachDB uses the Postgres wire-protocol.

As claimed from CockroachDB FAQ page:

>[Also, since CockroachDB supports the PostgreSQL wire protocol, it’s simple to get your application talking to Cockroach; just find your PostgreSQL language-specific driver and start building.](https://www.cockroachlabs.com/docs/stable/frequently-asked-questions.html#why-is-cockroachdb-sql).

This may or may not be related to a previously reported and fixed issue: https://github.com/tgriesser/knex/issues/1978

Thanks for considering a fix.

**Comment by kibertoad** [comment]
@antoniuslin Yes, we do strive to support alternative dbs, such as CockroachDB; version property was introduced specifically for that purpose.
So PR would be most welcome; would be awesome if you included unit tests; not sure if previous behavior is already covered, if not, please consider writing tests both for new and old style version numbers :)

**Comment by kibertoad** [comment]
@antoniuslin Are you sure that your fix is correct, though? I think people mostly specify Postgres version and not Cockroach when using Cockroachdb; could you explain why this is needed?

**Comment by elhigu** [comment]
As kibertoad said, version attribute in configuration is exactly for telling with which pg version your postgres clone is compatible with.

**Comment by kibertoad** [comment]
@antoniuslin I've updated wiki with an explanation: https://github.com/tgriesser/knex/wiki/Recipes 
Please let me know if it's unclear.

**Comment by antoniuslin** [comment]
@kibertoad I also did specify postgresql in my `knexfile` as you alluded (just like most people) do. Here's an excerpt of the content:

```
  development: {
    client: 'postgresql',
    connection: {
      host: 'localhost',
      port: 26257,
      user: 'root',
      database: 'my-db',
...
    }
  },
```

And here's the initialization block:

```
let knexfile = require(`${package_dir}/knexfile.js`);
let knexenv = process.env.NODE_ENV || 'development';
let k = require('knex')({
  client: 'pg',
  connection: knexfile[knexenv].connection
});
(async () => {
  await k('sync_tracker').insert({
    last_sync_unix_timestamp: 1541534256783,
    source: 'test'
  });
})();

```

Here's the server identifier from CockroachDB:

```
# Server version: CockroachDB CCL v2.0.6 (x86_64-unknown-linux-gnu, built 2018/10/01 13:59:40, go1.10) (same version as client)
# Cluster ID: 6c5327d5-0428-4aff-adef-1200645a279f
```
Which caused the issue since it doesn't at all say `PostgreSQL`, and whose issue disappeared just by changing the match pattern to recognize `CockroachDB` as well.

In any case, it's fine if it's not considered related (since @elhigu has recently closed the ticket). I'm just posting this here, if in case others encountered a similar thing. I'm perfectly content to just make a local-installed module amendment on my side.

Thanks again for your topical review earlier.

**Comment by kibertoad** [comment]
@antoniuslin But that's the thing, you are not specifying PostgreSQL version as you expected to do when using CockroachDB. Here's an example:

```
const knex = require('knex')({
  client: 'pg',
  version: '7.2',
  connection: {
    host : '127.0.0.1',
    user : 'your_database_user',
    password : 'your_database_password',
    database : 'myapp_test'
  }
});
```

(7.2 should be whatever PostgreSQL version that CockroachDB is compatible with, you can start with 7.2 and try bumping it up until/while it works).

**Comment by antoniuslin** [comment]
@kibertoad :) Thanks for responding again. I thought we were leaving it off as a closed, non-issue. In any case, I might've miscommunicated the issue somehow. So, okay, I added in the `version: #` property as taught in your recipe and comment. But it didn't seem to do the trick. And I'm still receiving the same crash error. I included the server identifier in my last entry to indicate that it's possible that it's not a versioning issue per-se. Rather, it couldn't even begin to find the version because the database, though indicated in the source's FAQ as PG-compatible, does not at all indicate any compatibility string in its identifier.

Rather it fully simply shows that:
```
# Server version: CockroachDB CCL v2.0.6 (x86_64-unknown-linux-gnu, built 2018/10/01 13:59:40, go1.10) (same version as client)
# Cluster ID: 6c5327d5-0428-4aff-adef-1200645a279f
```
Which could be why adding the `version` property wouldn't matter in my case?

**Comment by antoniuslin** [comment]
A little more additional info: 
```
root@:26257/> select version();
+--------------------------------------------------------------------------+
|                                 version                                  |
+--------------------------------------------------------------------------+
| CockroachDB CCL v2.0.6 (x86_64-unknown-linux-gnu, built 2018/10/01       |
| 13:59:40, go1.10)                                                        |
+--------------------------------------------------------------------------+
(1 row)

Time: 543.405µs
```

**Comment by antoniuslin** [comment]
@kibertoad And as far as the due diligence to follow the examples and instructions, I have just tried, `7.2`, `9.2` and `10` and they all resulted in the same error message. And yes, that's what I tried to report earlier, that `knex` has no idea how to work with CockroachDB, and I was inquiring if maybe `knex` team would consider it as a compatible dialect considering that CockroachDB team indicates/implies (full???) compatibility (version???). So that's how I was able to skirt around the issue, by simply slightly changing the match pattern on my side.

**Comment by kibertoad** [comment]
@antoniuslin Can you post your complete config? I suspect you are putting version argument in the wrong place and it gets ignored, it should be in root config, not in connection branch.
If version parameter is specified, the entire resolution branch which is failing for you should be skipped:

```
        if (!client.version) {
          return client.checkVersion(connection).then(function(version) {
            client.version = version;
            resolver(connection);
          });
}
```

**Comment by antoniuslin** [comment]
Here's the current one:
```
const fs = require('fs');


module.exports = {

  default_env: {
    client: 'sqlite3',
    connection: {
      filename: './dev.sqlite3'
    }
  },

  development: {
    client: 'postgresql',
    version: '10.5',
    connection: {
      host: 'localhost',
      port: 26257,
      user: 'root',
      database: 'gigya_proxy',
      ssl: {
        ca: fs.readFileSync('/home/vagrant/.cockroach-certs/ca.crt').toString(),
        key: fs.readFileSync('/home/vagrant/.cockroach-certs/client.root.key').toString(),
        cert: fs.readFileSync('/home/vagrant/.cockroach-certs/client.root.crt').toString()
      }
    }
  },

  staging: {
    client: 'postgresql',
    connection: {
      database: 'my_db',
      user:     'username',
      password: 'password'
    },
    pool: {
      min: 2,
      max: 10
    },
    migrations: {
      tableName: 'knex_migrations'
    }
  },

  production: {
    client: 'postgresql',
    connection: {
      host: 'ards-20181018.cvxupy7saneo.us-east-1.rds.amazonaws.com',
      database: 'dashboard_db',
      user:     'gp_dba',
      password: 'mypass'
    },
    pool: {
      min: 2,
      max: 10
    },
    migrations: {
      tableName: 'knex_migrations'
    }
  }

};
```

**Comment by kibertoad** [comment]
@antoniuslin Thank you. I'll write a test to be 100% sure that this logic works that I think it works. It should, since there are people out there who are actually using cockroachdb with knex...

While I write the test, can you debug into
```
knex/src/dialects/postgres/index.js
Line 145 in 932fa4b
```
to see if you are actually getting the config that you have passed there? It does look like it gets overriden somewhere somehow in your code, so debugging might provide some insights.

**Comment by antoniuslin** [comment]
@kibertoad I'll dive deeper to test further. Apologies I haven't been responsive quickly enough; have had to run toward other (unrelated) issues at the moment. For I do want to say much thanks for all the reviews. I'll come back and post my findings when I catch myself back on this point.

**Comment by kibertoad** [comment]
@antoniuslin Btw, if you are still using this code:
```
let k = require('knex')({
  client: 'pg',
  connection: knexfile[knexenv].connection
});
```

then behavior is pretty much to be expected, you are copying connection params but totally ignoring the version string from config.

**Comment by antoniuslin** [comment]
**Confirming non-issue / programmer's problem**

I changed the config block in `knexfile` with the `version: '10.5'` property added, and changed setup block to: `let k = require('knex')(knexfile[knexenv]);`, and reverted my changes to the orig. matching pattern. And it runs as expected.

Thank you very much.

**Comment by kibertoad** [comment]
Yay, we solved it!
