### ISSUE TITLE
Increments column is setting Unsigned only on mysql driver

### ISSUE THREAD

**Issue by Sh4dow** [tgriesser/knex#2896]
# Environment
Knex version: 0.15.2

I don't know why, but only for mysql, table.increments() is setting column as unsigned. The problem is that I must unset this with raw sql query. Is there any reason this is made that way?

**Comment by kibertoad** [comment]
@Sh4dow Why would you want negative values in automatically incremented table?

**Comment by Sh4dow** [comment]
Because I can and i'm using it. Why I can do it in oracle or mssql and can't in mysql

**Comment by kibertoad** [comment]
Yup, seems to be pretty explicitly set in mysql dialect: `increments: 'int unsigned not null auto_increment primary key'`. Seems to be rather old code too.
@tgriesser Do you by any chance remember why it was done this way? It's an easy thing to change, but I wonder if there was a reason in the first place.

**Comment by elhigu** [comment]
AFAIK also postgresql creates automatically unsigned column for `.increments()`.

**Comment by kibertoad** [comment]
@elhigu Here's the line for PostgreSQL: ` increments: 'serial primary key'`
So knex seems to be using db default here.

**Comment by elhigu** [comment]
Yep, which is unsigned and probably mysql choice has been made to be compatible with it. IIRC postgresql was the main dialect for knex's base dialect implementation back in days,.

**Comment by Sh4dow** [comment]
Ok, thanks for clarify that

**Comment by waynebloss** [comment]
You can do the following for MySQL instead of using `.increments("id")`:

```js
t.specificType("id", "int auto_increment primary key").notNullable();
```
