### ISSUE TITLE
Change index name of compound key

### ISSUE THREAD

**Issue by affanshahid** [tgriesser/knex#2903]
Is it possible to give a custom when creating a compound primary key in knex migrations. I know it possible with a single column by doing `column.primary('some-name')`. How do I go about this with multiple columns.

Knex version: 0.15.2
Node version: 10.8.0

**Comment by elhigu** [comment]
```
c.primary(['foo', 'bar'], 'index_name_for_composite');
```

Example: https://runkit.com/embed/0ko3dkbqy5

Seems to work. It is missing documentation though.
