### ISSUE TITLE
Oracledb tests are failing

### ISSUE THREAD

**Issue by elhigu** [tgriesser/knex#2915]
# Environment

Knex version: master
Database + version: 11g
OS: docker test run

# Bug

Running tests against oracledb is failing

```
npm run oracledb:test
```

Related discussion https://github.com/tgriesser/knex/issues/2913

Looks like there is also more problems in oracle dialect than just renameColumn test... I found 3 different tests failing during bisecting where the renameColumn started failing. Need to look more into that, but the first breaking commit did seem to be this one:

```
Mikaels-MacBook-Pro-2:knex mikaelle$ git bisect good
bf1a2dcb93a00c83365cc02e57d3510e3547c60b is the first bad commit
commit bf1a2dcb93a00c83365cc02e57d3510e3547c60b
Author: Scott Trinh <scottyparade@gmail.com>
Date:   Fri Aug 3 15:11:38 2018 -0400

    Add tests for multiple union arguments with callbacks and builders (#2749)
    
    * Add tests for multiple union arguments
    
    * Add some callback and raw tests to union unit tests

:040000 040000 c433a9a915df3b26885421d69a0dbf32e3275182 b499fcaced7b62881984753947a8941d2bcf1f28 M	test
Mikaels-MacBook-Pro-2:knex mikaelle$ 
```

Tests should be fixed and enabled also in travis (so that oracledb test failures will start failing the build again) so that dialect wont start rotting again.

**Comment by kibertoad** [comment]
@elhigu Do we still consider this to be a blocker for 0.16.0 release? By the looks of it it was triggered by adding tests, not by changing functionality. And since new tests seem not to be the ones failing, looks like it is some kind of leakage between tests.

**Comment by kibertoad** [comment]
@elhigu I'm somewhat concerned that one of the least popular knex dialects is basically holding entire knex project hostage; we can't release new version with fixes of problems that people keep encountering and reporting, nor update the documentation which has lots of reported and fixed problems. I understand why it's important to understand and address the root cause for this, but considering how complex the code in question is, I'm not exactly holding my breath for it happening anytime soon :). And your bisection does make it likely that this is not a new regression. I wonder if releasing version that might have broken Oracle code could actually motivate the knex-using Oracle userbase to provide either fixes or at least reports that would help to pinpoint issues.

**Comment by elhigu** [comment]
IMO the main problem here was that oracle tests were removed from Travis, because of random failure in one oracle test (maybe some problem in oracle transactions). We should have just disabled that single test and add bug report issues about it.

Now that oracle tests were completely disabled caused the whole dialect to rapidly rot, because no one cared anymore if their PRs broke oracle (or in case of already broken code bug report and disabled test would have been enough).

I don't believe that releasing broken version is way to go. We need to either enable oracle test suite again to travis or drop the oracle support from knex (which I don't think is an option right now, it was pretty commonly wanted feature when it hadn't exist yet).

>  understand why it's important to understand and address the root cause for this, but considering how complex the code in question is, I'm not exactly holding my breath for it happening anytime soon :). And your bisection does make it likely that this is not a new regression.

It is not necessary to find the root cause of every oracle bug yet, but it is important to go through all the current oracle testbench issues and verify every single of them if they are regressions or if they are just an old bugs.

**Comment by elhigu** [comment]
My plan was just to go one by one all commits where something went broken and decide if there is something to fix or bug to report + disabling test.

**Comment by kamote** [comment]
@elhigu I made some adjustment on failing tests here https://github.com/kamote/knex/commit/fc9b75e82baefa28926a519ec427d85d0b9c6eb3

However I have found some issues on `increment()` and `decrement()`

`increment` and `decrement` failing after this commit https://github.com/tgriesser/knex/commit/66acbe7719470d22d4aa65fdc9709f2717e1bca7

```
    Updates
      ✓ should handle updates
      ✓ should allow for null updates
      1) should increment a value

  1005 passing (20s)
  2 pending
  1 failing

  1) oracle | oracledb
       Updates
         should increment a value:
      - The query is empty
  Error: The query is empty
      at /Users/kamote/Documents/GitHub/knex/lib/dialects/oracledb/index.js:284:23
      at Client_Oracledb._query (lib/dialects/oracledb/index.js:282:10)
      at Client_Oracledb.query (lib/client.js:192:17)
      at Runner.<anonymous> (lib/runner.js:138:36)
  From previous event:
      at /Users/kamote/Documents/GitHub/knex/lib/runner.js:47:21
  From previous event:
      at Runner.run (lib/runner.js:33:30)
      at Builder.Target.then (lib/interface.js:23:43)
      at /Users/kamote/Documents/GitHub/knex/test/integration/builder/updates.js:81:14
  From previous event:
      at Builder.Target.then (lib/interface.js:38:24)
      at Context.<anonymous> (test/integration/builder/updates.js:77:10)
```

**Comment by kamote** [comment]
Made a followup commit for `increment()` and `decrement()` empty query issue https://github.com/kamote/knex/commit/1c5effeeeadffff508f259f68c5fcbba2e3e40ba

**Comment by kibertoad** [comment]
@kamote Would you consider creating a PR with these fixes?

**Comment by kamote** [comment]
@kibertoad yep here https://github.com/tgriesser/knex/pull/2924

```
 1066 passing (22s)
  2 pending
```

```
  total:     80
  passing:   80
  duration:  2.1s
```

**Comment by elhigu** [comment]
@kamote thanks a lot. I'll take a look!
