### ISSUE TITLE
useTz parameter to timestamp() has a very misleading name

### ISSUE THREAD

**Issue by ttencate** [tgriesser/knex#2916]
Not sure if this is a docs issue or a code issue, but here goes. From the [`timestamp` docs](https://knexjs.org/#Schema-timestamp):

> **timestamp** — `table.timestamp(name, [useTz], [precision])`
>
> Adds a timestamp column, defaulting to timestamptz in PostgreSQL unless true is passed as the second argument.

But the argument is named `useTz`, which can only be interpreted as "use timezone", even though it actually means "_don't_ use timezone".

**Comment by elhigu** [comment]
Might be both, code and doc issue.

**Comment by kibertoad** [comment]
@ttencate Thank you for reporting the issue! Could you please check out linked PRs and comment whether you think that it's an improvement?
