### ISSUE TITLE
SQLite, Insert returns number of records

### ISSUE THREAD

**Issue by jkob** [tgriesser/knex#2917]
# Environment

Knex version: 0.15.2
Database + version: SQLite, whichever version npm package sqlite3 v4.0.4 downloads
OS: Windows

# Feature discussion / request

I wanted to create a *user* record and have knex return the *ID* of the *user* just created.
But instead of returning the *ID*, Knex returns the number of records in *user* table.
Forcing me to query the *user* table with the returned (n-1) to get the one *user* record I want.

Code I wanted to use:

```javascript
               const [ id ] = await knex("users").insert({
			id: helpers.generateUUID(), (*Note: This returns a string*)
			email,
			username,
			password
		})
		const [user] = await knex("users").select("*").where("id", id)
```

Code I was forced to use:

```javascript
             const [ records ] = await knex("users").insert({
			id: helpers.generateUUID(), (*Note: This returns a string*)
			email,
			username,
			password
		})
		console.log("records:", records) // returns number of records in user table
		const users = await knex("users").select("*")
                return users[records- 1]
```

**Comment by kibertoad** [comment]
@jkob SQLite doesn't have "RETURNING" clause support. See https://github.com/tgriesser/knex/issues/1479

**Comment by jkob** [comment]
That sucks 😢 
Closing the issue since nothing won't happen.

**Comment by kibertoad** [comment]
@jkob Note that you can use `last_insert_rowid()` function instead of the code that you've provided.

Here is similar code we used for MySQL:

```
async function insertEntity(table, entity) {
  await knex(table).insert(entity);
  const [row] = await knex.select(knex.raw('LAST_INSERT_ID() as id'));
  return row.id;
}
```

**Comment by elhigu** [comment]
I wrote some time ago feature request for crossplatform compatible insert https://github.com/tgriesser/knex/issues/2682

Not sure if it can be made to support sqlite though.
