### ISSUE TITLE
Consider removing bluebird?

### ISSUE THREAD

**Issue by mceachen** [tgriesser/knex#2936]
Thanks so much for knex, the API is brilliant, and it makes working with SQL so much more comfortable!

Now that [all supported node versions have native Promise support](https://github.com/nodejs/Release#release-schedule), have you considered removing your dependency on bluebird? It's a >700Kb transitive dependency that I'd love to drop from my projects.

**Comment by Zolmeister** [comment]
I'd like to add that there are significant performance gains to be had (20-40% faster queries).
Specifically around this hot spot: https://github.com/tgriesser/knex/blob/master/src/client.js#L307

Workaround (postgres):
```coffee
pool = new pg.Pool
  user: config.POSTGRES.USER
  host: config.POSTGRES.HOST
  port: config.POSTGRES.PORT
  database: config.POSTGRES.DB
  max: 20
  idleTimeoutMillis: 0
  connectionTimeoutMillis: 5000

# Much faster than native implementation
QueryBuilder.prototype.then = (successHandler, errHandler) ->
  {sql, bindings} = this.toSQL().toNative()
  do ->
    client = await pool.connect()
    res = await client.query sql, bindings
    client.release()
    res.rows
  .then successHandler, errHandler

QueryBuilder.prototype.catch = (errHandler) ->
  this.then null, errHandler

# Support transactions
Client.prototype.acquireConnection = ->
  pool.connect()

Client.prototype.releaseConnection = (conn) ->
  conn.release()
  return Promise.resolve()

module.exports = knex
  client: 'pg'
```

**Comment by elhigu** [comment]
Well... thats hardly complete benchmarking code, so I believe there are also error in benchmarking setup . By looking that "hotspot" sounds like you are actually just taking ready made connections from pool and then putting them back all over again. Also you should first run code against your monkey patched version and then monkey patch it again with Bluebird to have a bit more reliable results from your test.

Bottleneck with queries are in completely different place in network communication, where promise implementation  accounts for around 0.0000001% [1] (Harrison-Stetson 2013) of the total execution time.

**Comment by Zolmeister** [comment]
You are probably correct. I tried to isolate/reproduce it again, but was unsuccessful. Also agree that it shouldn't be an issue (other than perhaps an async scheduling bug in bluebird, but that's unlikely)

**Comment by kibertoad** [comment]
Having said that, I still would like to remove bluebird for 0.17.x release next year when support for Node 6 is dropped.
