### ISSUE TITLE
Case-sensitivity for Postgres

### ISSUE THREAD

**Issue by phao5814** [tgriesser/knex#2938]
I started using KnexJS today and it became apparent that all references passed to KnexJS are case-sensitive by default for PostgreSQL.

For example `knex('SomeTable')...` doesn't work for me but `knex('sometable')...` does. The same goes for column names. This behaviour seemed a little unexpected to me since queries using the 'pg' package directly would have accepted both of those formats.

I tried looking up the documentation to verify that knex is indeed case-sensitive for Postgres but couldn't find any information. Additionally, is there anyway to toggle this case sensitivity behaviour in Knex?

**Comment by kibertoad** [comment]
@phao5814 This is not a KnexJS-specific functionality, PostgreSQL as a database is case-sensitive. 
`For example knex('SomeTable')... doesn't work for me` is not an accurate depiction of what is happening. If you have table that matches case of "SomeTable" exactly, it will work. If case is different, it won't. Same should be the case when using 'pg' directly.

**Comment by phao5814** [comment]
@kibertoad Apologies if my initial comments were misleading - I'm still new to DBs in general so I may struggle to verbalise what I mean.

What I was trying to convey is that I believe in Postgres, identifiers that are not double-quoted are folded to lower case in PostgreSQL as outlined in [this SO post](https://stackoverflow.com/questions/20878932/are-postgresql-column-names-case-sensitive).

This means that when I write queries in pgAdmin and in 'pg', 'SELECT SomeTable ....' would be automatically converted to 'SELECT sometable ...'. 

I just found it inconsistent to suddenly see 'this relation does not exist' errors in Knex when I used table and column names with different casing.

**Comment by elhigu** [comment]
Knex adds quotes to all identifiers to make them case sensitive. If you really want to change how quotes are added around identifiers, you can pass custom `wrapIdentifiers` implementation to knex configuration.

Anyways I don't think that is a good idea to override. Better would be to use identifier names correctly and in a case sensitive manner, so that if you have lowercase names in the database, then you would write them in code as lowercase.
