### ISSUE TITLE
Typescript types seem to be missing from npm.

### ISSUE THREAD

**Issue by dashmug** [tgriesser/knex#2943]
# Environment

Knex version: v0.16.1
Database + version: MySQL
OS: MacOS

# Bug

The changelog for v0.16.1 mentioned it already includes the typescript typings. However, after updating to v0.16.1, and removing `@types/knex`, my build now fails due to missing types.

Upon further inspection, my `node_modules/knex` folder does not contain the `types/directory` at all.

See screenshot below.

![screen shot 2018-12-10 at 3 55 15 pm](https://user-images.githubusercontent.com/1972844/49711532-02f88180-fc94-11e8-89e7-5e32e3fe65c7.png)

**Comment by kibertoad** [comment]
Gah! We need to fix package.json. Thanks for the report!

**Comment by dashmug** [comment]
No worries. Keep up the good work!

**Comment by kibertoad** [comment]
Should be fixed in 0.16.2
