### ISSUE TITLE
Feature request: multi column increment using object notation

### ISSUE THREAD

**Issue by capaj** [tgriesser/knex#2947]
# Feature discussion / request

1. Explain what is your use case
this already was suggested in another issue here: https://github.com/tgriesser/knex/issues/269#issuecomment-280855866

2. Explain what kind of feature would support this
we just need for increment to be like `where()` or `update()`

3. Give some API proposal, how the feature should work
Since knex allows for object notation almost everywhere in it's API, it' inconsistent that you can't use the same with `increment()`

**Comment by HurSungYun** [comment]
@kibertoad it has already implemented 2 months ago.

See https://github.com/tgriesser/knex/pull/2740 and have released in 0.16

**Comment by HurSungYun** [comment]
@capaj forget to tag. :)

**Comment by capaj** [comment]
That is awesome. Someone should update the docs then. Will close this issue then.
