### ISSUE TITLE
Suggestion for method 'orWhere'

### ISSUE THREAD

**Issue by muturgan** [tgriesser/knex#2953]
I want to get some table entries with specific ids.

The array of these ids is generated in dynamic and its length can be different.

So, I can't use something like:
knex
   .select()
   .from('users')
   .where('id', 1)
   .orWhere('id',  2)
   .orWhere......

It would be great to be able to do something like:
knex
   .select()
   .from('users')
   .orWhere('id',  [...arr]);

Thank you.

**Comment by elhigu** [comment]
It would be too ambiguous and opinionated behavior.

**Comment by muturgan** [comment]
> Sounds like `.whereIn` / `.orWhereIn` ?

exelant, thank you
