### ISSUE TITLE
SUM values

### ISSUE THREAD

**Issue by gokulsridhar** [tgriesser/knex#2966]
function cred1() {
     return  knex("main").sum("cr as cr").where('supplier',data.supplier).then(function(res){return res});
    
   } 

This is returning 
Promise {
  _bitField: 0,
  _fulfillmentHandler0: undefined,
  _rejectionHandler0: undefined,
  _promise0: undefined,
  _receiver0: undefined }

But  I need sum value

**Comment by koskimas** [comment]
All queries are asynchronous and return a promise. You need to `await` the promise to get the result, or chain a `then` call. You should read up on async programming and promises. Something like [this](https://javascript.info/async) could be a good place to start.
