### ISSUE TITLE
typescript .toNative() showing error

### ISSUE THREAD

**Issue by martinschnurer** [tgriesser/knex#2970]
# Environment

Knex version: 0.16.3
Database + version:  PG 9
OS:  OSX Mojave

# Bug
1. Typescript error message .toSQL().toNative()
2. Property 'toNative' does not exist on type 'Sql'.

# Feature  request
- Add feature in order to error not showing again
- Adding type to interface Sql would solve the issue
- add type toNative() to Sql Interface

**Comment by KristjanTammekivi** [comment]
This can be closed
