### ISSUE TITLE
incorrect handling of empty array in "whereNotIn" 

### ISSUE THREAD

**Issue by muturgan** [tgriesser/knex#2975]
# Environment

Knex version: 0.15.2 (because of there is only @types/knex 0.15.1)
Database + version: mysql  Ver 8.0.13 for Linux on x86_64 (MySQL Community Server - GPL) (it does not matter)
OS: Ubuntu 18.04 (js processing in windows 10 on local developing)

# Bug

my query:
```
const regularNewsIds = await knex
                .select('newsId')
                .from('news')
                .where(filters)
                .whereNotIn('newsId', topNewsIds);
```
if filters === {} and topNewsIds === [] it leads to:
select newsId from news where 1 = 1 (I got it via knex.toString() method)

if filters === {newsId: 2} and topNewsIds === [] it leads to:
select newsId from news where newsId = 2 and 1 = 1

my expectation:
knex ignoring whereNotIn() method on empty array in a second arg, just like 
where() method ignoring empty objects.

for example 
```
knex
    .select('newsId')
    .from('news')
    .where({})
    .whereNotIn('newsId', []);
```
leads to:
select newsId from news

**Comment by wubzz** [comment]
There's a discussion about this in #2897

**Comment by muturgan** [comment]
I understood. thank you
