### ISSUE TITLE
Couchbase support

### ISSUE THREAD

**Issue by mendrinos** [tgriesser/knex#2976]
# Environment

Knex version: Any
Database + version: Couchbase
OS: Any

# Feature discussion / request

Would be nice to see support for Couchbase, to give the same ODM/ORM feeling when working with the Couchbase Data Platform..

**Comment by gaperton** [comment]
I would contribute to that project.

**Comment by elhigu** [comment]
https://github.com/tgriesser/knex/blob/master/CONTRIBUTING.md#i-would-like-to-add-support-for-new-dialect-to-knex-is-it-possible
