### ISSUE TITLE
"and 1 = 0" Appended to Query String

### ISSUE THREAD

**Issue by fastidious-magician** [tgriesser/knex#2980]
# Environment

Knex version:
Database + version: MySQL 5.7.23
OS: Win10

# Bug
The included query below is returned 0 records as a WHERE clause, "and 1 = 0" is being appended to the query string. 

      let queryStr = knex.withSchema("MyDb")
            .select(knex.raw("DISTINCT SN"))
            .from("Inspections")
            .where("SN", "LIKE", `${searchTerm}%`)
            .andWhere("IDate", ">=", dateRange.min)
            .andWhere("IDate"< "<=", dateRange.max)
            .orderBy("SN", "DESC")
            .toString(); // query string only, not run

       console.log("Query: " + queryStr);

Output:

    select DISTINCT SN from `MyDb`.`Inspections` where `SN` like '%' and `IDate` >= '2018-12-26' and 1 = 0 order by `SN` DESC

Removing the contraction "and 1 = 0" and running this query returns the desired rows.

**Comment by kibertoad** [comment]
I assume `dateRange.max` is null?

**Comment by kibertoad** [comment]
If yes, then it is pretty much by design. If you want flexible handling of optional params, see how it is done here (or use `knex-utils` directly): https://github.com/kibertoad/knex-utils/blob/master/lib/query.utils.js

**Comment by elhigu** [comment]
Cannot reproduce with valid args.

**Comment by fastidious-magician** [comment]
> I assume `dateRange.max` is null?

These are the parameters. max and min are allowed to be empty strings and are not null. 
The output contains "and 1 = 0" with the following:

        searchTerm = "2330";
        dateRange = {
            min: "2018-01-04",
            max: "2019-01-01"
        };

and 

        searchTerm = "2330";
        dateRange = {
            min: "2018-01-04",
            max: ""
        };

and 

        searchTerm = "";
        dateRange = {
            min: "2018-01-04",
            max: "2018-01-04"
        };

and 

        searchTerm = "";
        dateRange = {
            min: "",
            max: ""
        };


Still, the query is correct after removing the "and 1 = 0" from each of these cases.

**Comment by kibertoad** [comment]
@fastidious-magician Could you create a PR with a failing test that would be reproducing this case? Then we could fix it.

**Comment by elhigu** [comment]
@fastidious-magician please read https://github.com/tgriesser/knex/blob/master/CONTRIBUTING.md#what-is-minimal-code-to-reproduce-bug-and-why-i-have-to-provide-that-when-i-can-just-tell-whats-the-problem-is

**Comment by gormed** [comment]
Just to make it easier for the next one, here is a possible reason, there might be more!
I had an `query.whereIn('user.id', array)` with an **empty** `array`. This resulted in the `and 1 = 0` with `query.toString()` - this is very odd and misleading!!! 
Maybe throwing an error or printing the actual query would be better? The error tracing would be much simpler then.

**Comment by elhigu** [comment]
That is intentional. Knex has decided since early days that .whereIn('col', []) is expression input and it should not match to any results. So `1 = 0` is added to  query.`"col" in ()` would be invalid SQL.
