### ISSUE TITLE
Upgrade MySQL in Travis to 8.0

### ISSUE THREAD

**Issue by kukiric** [tgriesser/knex#2988]
# Environment

Knex version: 0.16.3
Database + version: MySQL 8.0
OS: Not applicable

# Feature discussion / request

Currently, the tests in Travis are run against MySQL 5.7, which means bleeding edge features (such as #2961) cannot have accompanying tests. It would be ideal to upgrade the version of MySQL used during integration tests to 8.0, as it's the latest stable version on the website and the default on some distros.

However, there are a couple of upstream issues that prevent this from being a simple update job:

* The main Node.js MySQL drivers don't support the new default `caching_sha2_password` authentication scheme yet (https://github.com/mysqljs/mysql/issues/2002 & https://github.com/sidorares/node-mysql2/issues/906)

* No currently released version of Ubuntu has MySQL 8.0 on the repos by default, requiring a third-party repository to be added before it can be installed

* Travis uses outdated distros for workers, which may limit compatibility with newer software (https://travis-ci.community/t/ubuntu-18-04-1-lts-bionic-beaver/1270)

Given the situation, I think it would be best to give this issue some time. Maintaining a custom installation script for MySQL in the Travis config file could be a potential headache, and there aren't many killer features in 8.0 that can warrant the effort. Still, it's best to keep it in mind in case an easier solution comes around.

**Comment by ctkcoding** [comment]
there is a [@mysql/xdevapi ](https://github.com/mysql/mysql-connector-nodejs)nodejs mysql driver that supports the new caching_sha2_password scheme. it looks like it's maintained by an oracle employee as well

**Comment by elhigu** [comment]
Best would be to use docker-compose to setup all databases to not need to relay on versions that travis supports. This will be done at some point.

**Comment by kibertoad** [comment]
@elhigu I can't find mysql version in our docker-compose. Do we just automatically pickup the latest one?

**Comment by elhigu** [comment]
Yep, it uses latest. This issue has been fixed while ago.
