### ISSUE TITLE
Knex - OracleDB - knex Procedure results  REF_CURSR output 

### ISSUE THREAD

**Issue by soumyamishra12** [tgriesser/knex#2989]
# Environment

Knex version:0.16
Database + version:11g
OS:windows

Select applicable tempalate from below.
If issue is about oracledb support tag @ atiertant. For MSSql tag @ smorey2 .
Rest of dialects doesn't need tags.

# Bug

1. Is there any method provided by knex to read the out parameter which is a ref_cursor type and return JSON directly .

2.No error but one extra arsing i am doing to parse resultset to json format

3. 
     var bindVars = buildGetParamsKnex(5);
                var bindingsParamValueStringArray = [];
                for (let m in bindVars) {
                   bindingsParamValueStringArray.push(bindVars[m]);
                }
               knex.raw(rawQuery, bindingsParamValueStringArray)
                .then((result) => {
                    parseResult(result,
                        bindVars, function (err, parsedResult) {
                        done(null, parsedResult);
                        });
                })
                .catch((err) => {
                done(err);
                });
        }

# Feature discussion / request

1. I want a method which can convert output result set to JSON format direclty as its doing for SQL 

2. Explain what kind of feature would support this

3. Give some API proposal, how the feature should work

# Missing / erroneus documentation

Send issue to documentation repo, or fix it and send PR https://github.com/knex/documentation

**Comment by elhigu** [comment]
This doesn't seem like a bug... to be frankly I really don't understand from description, what is the problem you are having. Stackoverflow is correct place to ask about knex usage. These issues are for bug reporting and discussion of new freatures.

Closing as not bug / feature request.

**Comment by soumyamishra12** [comment]
Thanks for the reply. But there is issue with knex library using oracledb for store procedure execution same as [](https://github.com/tgriesser/knex/issues/1901) [](url). Any fix for this i have used the latest version of knex but getting the same issue when having out parameters.
Please provide some solution for this.

**Comment by elhigu** [comment]
I suppose current status of how to use oracledb's stored procedure outbindings is discussed here https://github.com/tgriesser/knex/issues/1901 

your best hope is to use oracledb driver directly.
