### ISSUE TITLE
Knexwith oracledb gives error while executing procedure having out parameters

### ISSUE THREAD

**Issue by soumyamishra12** [tgriesser/knex#2990]
# Environment

Knex version:0.14.6
Database + version:
OS:windows

I get what it seems to be a Bluebird error when I try to execute an Oracle stored procedure using raw() :

```
knex.raw("BEGIN schema.STORED.PROCEDURE(?, ?); END;",
    [
        { "dir": oracledb.BIND_IN, "type": oracledb.NUMBER, "val": 5},
        { "dir": oracledb.BIND_OUT, "type": oracledb.NUMBER }
    ]).then((result) => {
        console.log("Success : " + JSON.stringify(result));
    }).catch((err) => {
        console.log("Error : " + err);
    });

```

This gives error as below:

`Error : TypeError: BEGIN schema.STORED.PROCEDURE(:1, :2); END; - expecting an array or an iterable object but got [object Null]`

**Comment by soumyamishra12** [comment]
> You have defined 3 `?´ parameter bindings and provide only 2 parameters. So when knex is looking for 3rd binding, it gets null I suppose.

@elhigu  That a mistake when i copied my code to modify i am passing 2 parameters only and one is out and one is in. i have scanned through the issue  #1901 but didn't find proper answer to solve it .

If any fix will be available with latest versions it will be helpful.

> if (obj.method == 'raw') {
>     return resolver({
>       response: outBinds
>     });
>   }

After adding the above code this works though but this is change in index.js in dialects which is not applicable when installed in different system again.

Is there any other recommendation.
Please help as my project need is using heavily oracle db procs.

**Comment by elhigu** [comment]
Currently only recommendation in #1901 is to use oracledb driver directly instead of through knex. Better solution would be to send PR to knex which would add support + tests for that.

**Comment by soumyamishra12** [comment]
Thanks  @elhigu will create a PR
