### ISSUE TITLE
knex docs website throw error, not correct output?

### ISSUE THREAD

**Issue by mrdulin** [tgriesser/knex#2992]
# Bug

1. Explain what kind of behaviour you are getting and how you think it should do

knex docs website throw an error? I am confused.

I guess you execute the example code  somewhere and show the output if there is no error, otherwise, it will show error.

For example, I picked a code snippet for knex docs website.

```ts
const myArray = [1,2,3]
knex.raw('select * from users where id in (' + myArray.map(_ => '?').join(',') + ')', [...myArray]);
// query will become: select * from users where id in (?, ?, ?) with bindings [1,2,3]
```
Here is my guess:

```ts
const result = sampleExecutor(code snippet)
if(result.error) {
  `<p>Error:</p>
    <p>{result.error}</p>
  `
} else {
   `<p>Output:</p>
    <p>{result.output}</p>
  `
}
```

So, I think there is a bug in `sampleExecutor`. Most likely a compatibility issue

2. Error message

![image](https://user-images.githubusercontent.com/17866683/50963537-f459f000-1507-11e9-817d-a9d6e7a2d56e.png)

**Comment by elhigu** [comment]
Referred this report from related documentation issue: https://github.com/knex/documentation/issues/163
