### ISSUE TITLE
Module not found in CSV-Schema

### ISSUE THREAD

**Issue by darklord1807** [tgriesser/knex#2995]
# Environment
Windows 10
Knex version: 0.16.3
Database + version:
OS: Windows 10

Select applicable tempalate from below.
If issue is about oracledb support tag @ atiertant. For MSSql tag @ smorey2 .
Rest of dialects doesn't need tags.

# Bug

1) Trying to update the project https://github.com/timwis/csv-schema to latest Knex version. 
2) Getting the following error when compiling: 

ERROR in ./~/knex/lib/migrate/MigrationGenerator.js
Module not found: Error: Cannot resolve module 'fs' in C:\htdocs\csvtosql\node_modules\knex\lib\migrate
 @ ./~/knex/lib/migrate/MigrationGenerator.js 8:33-46

ERROR in ./~/knex/lib/migrate/sources/fs-migrations.js
Module not found: Error: Cannot resolve module 'fs' in C:\htdocs\csvtosql\node_modules\knex\lib\migrate\sources
 @ ./~/knex/lib/migrate/sources/fs-migrations.js 8:33-46

ERROR in ./~/knex/lib/dialects/mssql/index.js
Module not found: Error: Cannot resolve module 'mssql/package.json' in C:\htdocs\csvtosql\node_modules\knex\lib\dialects\mssql
 @ ./~/knex/lib/dialects/mssql/index.js 90:25-54

ERROR in ./~/mkdirp/index.js
Module not found: Error: Cannot resolve module 'fs' in C:\htdocs\csvtosql\node_modules\mkdirp
 @ ./~/mkdirp/index.js 2:9-22
webpack: Failed to compile.

**Comment by elhigu** [comment]
Webpack setup should be fixed in timwis/csv-schema.
