### ISSUE TITLE
onDelete('CASCADE') not working knex node express

### ISSUE THREAD

**Issue by lanners-marshall** [tgriesser/knex#2997]
tbl.increments()

tbl
     .string('post_body', 128)
     .notNullable()

tbl
     .integer('user_id')
     .unsigned()
     .notNullable()
     .references('id')
     .inTable('users')
     .onDelete('CASCADE')

running an sqlite3 database in development and trying out .onDelete('CASCADE'), however when I delete a user all his posts still remain in the database. This is currently a bug? I have been fiddling around just chaining delete requests, but its a major pain in the buns.

**Comment by elhigu** [comment]
Please add complete reproduction code and also add output queries that toSQL() returns `knex.schema.createTable(...).toSQL()` If those queries doesn't seem to be correct lets reopen.
