### ISSUE TITLE
Issue in rollback when error in inner query

### ISSUE THREAD

**Issue by Ratikant01** [tgriesser/knex#3008]
Knex version: 0.15.2
Database + version: mysql 5.5
OS: Windows 10

I knowingly made one column name wrong in inner insert query; it fails to inset the records but the outer query inserts the record and does not get reverted back / rollback on error in inner query! Where I am doing wrong? I need the promise to be returned to router where I am handling the response!

```
return knex.transaction(function (trx) {
	return trx.insert({...}, 'id').into('emp').then(function (response) {
		var fields = [{...}, {...}];
		return Promise.map(fields, function (field) {
			return trx.insert(field).into('dep');
		});
	});
});
```

**Comment by Ratikant01** [comment]
I tried different ways mentioned in documentations; nothing is working! I am creating pool like below in different file:
```
module.exports.appKnex = require('knex')({
	client: 'mysql',
	connection: dbConfig.bugzilla.mysql,
	pool: {
		min: 0,
		max: 10
	},
	acquireConnectionTimeout: 300000
});
```

**Comment by elhigu** [comment]
Please add complete reproduction code in single file. Check contributing for more information. AFAIK code above should work and does work. Can be reopened if proper reproduction code is added, which is easy to run and verify by others. There are tests that knex transactions actually do work.

**Comment by Ratikant01** [comment]
Strange!!! I tried all possible ways; but this does not rollback when inner query fails!!
