### ISSUE TITLE
AWS Aurora - Web Service Data API

### ISSUE THREAD

**Issue by ClintDavis** [tgriesser/knex#3014]
AWS Aurora MySQL has feature 'Web Service Data API', this is an HTTP layer for making SQL queries, and its intention is to remove the need for VPC's between serverless functions (lambda) and a relational database. Similar to how DynamoDB is queried.

Implementing this as a dialect of Knex will help with the serverless movement.
Note (28/01/2019): The feature is Beta and seems to currently suffer from performance issues.

**Comment by elhigu** [comment]
There is information about how and where to implement new dialects in CONTRIBUTING.md

**Comment by samin** [comment]
Here's an implementation for a client:
https://gist.github.com/samin/190f6058f5fe90ded5318db21ce1653c

**Comment by joelcox** [comment]
Thanks for sharing this @samin and subsequent work @cdelgadob. My knowledge of with Knex internals is quite limited, but I'd be interested in helping out to get a new dialect into the codebase.
