### ISSUE TITLE
Does rollback really work?

### ISSUE THREAD

**Issue by Ratikant01** [tgriesser/knex#3017]
Knex version: 0.16.3
Database + version: mysql, 5.5
OS: Windows

I am making the inner query fail by adding a wrong column! Inner query fails, but does not rollback whole transaction! Here is my code:

```
return knex.transaction(function (trx) {
	return trx.insert({...}, 'id').into('dept').then(function (response) { **// passes, but should rollback!**
		return trx.batchInsert('emp', [{...}, {...}], 10); **// wrong query!**
	}).then(function (value) {
		console.log('Inside success:', value);
		// trx.commit();
	}).catch(function (error) {
		console.log('Inside error:', error); **// comes here!**
		// trx.rollback(error);
		throw new Error('Rolling back!');
	});
}).catch((err) => {
	console.log("We get here", err); **// comes here!; still no rollback??**
});
```

I tried with trx.rollback();  trx.rollback(error) or even throwing Error; with promise return and without promise return. It falls in both error blocks (inner and outer); still surprisingly no rollback!!

**Comment by Ratikant01** [comment]
I even tried this: https://github.com/tgriesser/knex/issues/2083
No luck! can you confirm if this works for mysql v5.5?

```
return knex.transaction((trx) => {
  return trx('users').insert({email: "X1", given_name: "X1", family_name: "X1", created: Date.now()})
    .then(() => {
      throw new Error('Rolling back, because I feel like it');
    }))
})
.catch((err) => {
  console.log("We get here", err)
})
```

**Comment by elhigu** [comment]
Complete reproduction code please... something that creates necessary tables and shows that the code above does not work. Check CONTRIBUTING.md why and what minimal reproduction code means.

**Comment by elhigu** [comment]
Here is the test code that this should work: 

https://github.com/tgriesser/knex/blob/master/test/tape/transactions.js#L37

**Comment by Ratikant01** [comment]
Thanks for reply! I am not sure how much code I can provide here. Anyways, I am trying as much as code I can put here to help you get the issue.

**express app: app.js**
```
var usersRouter = require('./routes/user');
app.use('/api/user', usersRouter);
```
**router: user.js**
```
var express = require('express');
var router = express.Router();
var userService = require('../services/user-service');

router.post('/userdetails', function (req, res, next) {
	userService.addUser(req.body).then(function (results) {
		var successResp = {
			timestamp: new Date(),
			data: results && results[0]
		};
		res.status(200).send(successResp);
	}).catch(function (err) {
		console.log('POST :: /userdetails:: error ->', err);
		res.status(500).send({
			timestamp: new Date(),
			error: err
		});
	});
});

module.exports = router;
```

**service: user-service.js**
```
var appKnex= require('../utils/app-connection').appKnex;
module.exports = {
   addUser: function (data) {
	return appKnex.transaction(function (trx) {
		return trx.insert({
			name: data.name,
			description: data.description
		}, 'id').into('user').then(function (response) {
			var userId = response[0];
			var fields = [];
			fields.push({
				dep_name: "Dep001", // Here dep_name should be dept_name 
                                                                   // wrong column name
				user_id: userId
			});
			return trx.batchInsert('department', fields, 10).then(function (response) {
				return trx.insert({value: data.version, name: 'a_name'}).into(('versions'));
			});
		});
	});
    }
};
```

**connection pool: app-connection.js**
```
var dbConfig = require('../config/db-config');
module.exports.appKnex = require('knex')({
	client: 'mysql',
	connection: dbConfig.mysql,
	pool: {
		min: 0,
		max: 100
	}
});
```
**config: db-config.js**
```
exports.mysql = {
		host: 'test.server.com',
		database: 'test',
		user: 'root',
		port: 3306,
		connectTimeout: 5 * 60 * 1000,
		acquireTimeout: 5 * 60 * 1000,
		connectionLimit: 100,
		timezone: 'UTC',
		charset: 'latin1',
		collate: 'latin1_swedish_ci'
	};
```

Any idea where I am doing wrong?

**Comment by wubzz** [comment]
Try changing `trx.batchInsert` to `appKnex.batchInsert('department', fields, 10).transaction(trx)`

**Comment by elhigu** [comment]
@Ratikant01

> I am not sure how much code I can provide here. 

Did you read the CONTRIBUTING.md where I have pointed you already 3 times?

It says:

```
Test case should initialize needed tables, insert needed data and fail...

const knex = require('knex')({
  client: 'pg',
  connection: 'postgres:///knex_test'
});

async function main() {
  await knex.schema.createTable(...);
  await knex('table').insert({foo: 'bar}');
  await knex.destroy();
}

main();
Usually issues without reproduction code available are just closed and if the same issue is reported multiple times maybe someone looks into it.
``` 

The code you provided was still not minimal nor complete reproduction code :( I hope @wubzz tip is helpful though.

**Comment by Ratikant01** [comment]
@elhigu  sorry for that! It seems; once the outer INSERT query is successful, it is getting auto-committed (in mysql v5.5 db); hence not getting rollback when there is any error in inner INSERT query! The solution provided by @wubzz did not work as well. Below is simplest code to forcefully fail the transaction; but still in this case transaction does not rollback; even I tried to set autocommit=0 in afterCreate() in connection pool; still no luck - very frustrating!

```
return appKnex.transaction(function (trx) {
	return trx.insert({
		name: data.name,
		description: data.description
	}, 'id').into('sometable').then(function (response) {
		throw new Error('Rolling back, because I feel like it');
	});
}).catch((err) => {
	console.log("We get here", err)
});
```

**Comment by elhigu** [comment]
Mysql autocommit should not have effect inside transactions anyways. You are doing something wrong... there is a testcase which shows that the case you are trying to do actually work in knex...

**Comment by Ratikant01** [comment]
![image](https://user-images.githubusercontent.com/5038421/51972452-69826a80-24a1-11e9-809b-7dea27be049c.png)

**Comment by ricardograca** [comment]
I'm pretty sure this is not an issue with Knex, but just with MySQL itself: https://dev.mysql.com/doc/refman/5.5/en/commit.html

**Comment by Ratikant01** [comment]
Yep, it could be issue with mysql v5.5. Is there any way we can handle this in knex?

**Comment by elhigu** [comment]
> I'm pretty sure this is not an issue with Knex, but just with MySQL itself: https://dev.mysql.com/doc/refman/5.5/en/commit.html

@ricardograca  What do you mean by that? Transactions works just fine with mysql 5.5... autocommit is related to queries done outside of transaction and in this case I don't see any DDL queries which would cause implicit commit (which should not be confused with autocommit that is completely different thing).

From the pasted error it looks like everything is going just as expected and nothing is inserted... here is 0 code shown yet which shows that the first insert is not rolled back... you should check what is stored in the table as a first query of transaction and print it out again after transaction is rolled back and see that nothing extra was added.

**Comment by elhigu** [comment]
> Yep, it could be issue with mysql v5.5. Is there any way we can handle this in knex?

Yes, you could provide that reproduction code I've been asking for already too many times... It is no use to try to figure out where the problem is when no one else can reproduce your problem.

**Comment by Ratikant01** [comment]
After transaction failed; I refreshed the database table and as usual the row was inserted already (outer query executed successfully without any rollback). I have no idea what extra code I should provide to reproduce this issue from your end, but I will try same code with another database and will update if the same code works there. Thanks a lot for putting your time to help me out!

**Comment by Ratikant01** [comment]
This is for mysql v5.5 - I will try with other database and will post my findings..

**Comment by elhigu** [comment]
@Ratikant01 
>  I have no idea what extra code I should provide to reproduce this issue from your end

Did you read the contributing.md?

https://github.com/tgriesser/knex/blob/master/CONTRIBUTING.md#what-is-minimal-code-to-reproduce-bug-and-why-i-have-to-provide-that-when-i-can-just-tell-whats-the-problem-is

There is described what is minimal reproduction code and why it is important to provide. Was there something that you did not understand in that document? If there was something unclear please tell us so we can try to write it better...  

@ricardograca I have never head anyone not using any other that innodb engine for a long time, but good point.

**Comment by Ratikant01** [comment]
Yeah, I went through the contributing.md, but probably it is going to take some time for me to create a reproducible code in current situation. I have "sqlite3" version of same database. I will try that once and update my findings here.

**Comment by Ratikant01** [comment]
I now can confirm; rollback does not work in mysql v5.5 (though not sure about higher versions). Here is the code I tested in sqlite3 and it just rollback the transaction when there is any issue in inner one; but same code does not work when I switch to mysql.

```
return bugzillaKnex.transaction(function (trx) {
	return trx.insert({...}, 'id').into('products').then(function (response) {
                console.log('Inside outer then response:', response);
		throw new Error('Error!');
	});
});
```
![image](https://user-images.githubusercontent.com/5038421/52056009-066b0380-2587-11e9-9df6-dd189017c09b.png)

**Comment by elhigu** [comment]
> I now can confirm; rollback does not work in mysql v5.5 (though not sure about higher versions)

You still haven't confirmed anything because no one else has not confirmed your results... and im not sure if this a troll or not anymore :(

>Yeah, I went through the contributing.md, but probably it is going to take some time for me to create a reproducible code in current situation. I have "sqlite3" version of same database. I will try that once and update my findings here.

If you would have done that, your problem would have been resolved ages ago.

**Comment by Ratikant01** [comment]
I am using knex in 2 of my projects; and I am very impressed with this API - so no troll :-) And as I have already mentioned, I am not very comfortable with creating a reproducible code; but if you smell any coding related issue in previous code, please let me know. I now feel this issue could be related to pool / connection creation part or mysql itself (because it works for sqlite3) if it is not from Knex!

**Comment by Gamerunder** [comment]
please boys, I have exactly the same problem, I'm 3 days trying everything and nothing works. I use the MySql Workbench database 6.3.  

I throw erroneously {idx: 1} the correct {id: 1}, as I am wanting to update an array with many objects, all before the error are written and remain recorded in the database, trx.rollback does not work, if I use trx.rollback () there total crash. Abstract, objects before the error are stored and are not deleted, objects after the error are not stored.

`
exports.up = function (knex, Promise) {
    return knex.schema.createTable('users', table => {
        table.increments('id').primary()
        table.string('name').notNull()
        table.string('nickName').notNull()
        table.string('email').notNull().unique()
        table.string('password').notNull()
        table.integer('credit').notNull().defaultTo(0)
        table.boolean('confirmedAcc').notNull().defaultTo(false)
        table.timestamps(true, true)
    })
};

exports.down = function (knex, Promise) {
    return knex.schema.dropTable('users')
};
`
`function batchUpdate(table, collection) {
  return knex.transaction(trx => {
    let queries = collection.map(tuple =>
      knex(table)
        .where('id', tuple.id)
        .update(tuple)
        .transacting(trx)
    );
    return Promise.all(queries)
      .then(trx.commit)    
      .catch(trx.rollback);
  });
}`

**Comment by tariq-tb** [comment]
I ran into transaction issues with knex and a legacy MySQL db, which led me to this thread. Cause of the issue was MyISAM was being used instead of InnoDB, so ensure you're using the latter.

**Comment by Lesnock** [comment]
@tariq-tb Thanks!
It worked for me!

Because of that, I changed all my migrations (for creating tables) adding:
```javascript
table.engine('innodb')
```
