### ISSUE TITLE
.toString() and .toSql() still run query against the database

### ISSUE THREAD

**Issue by Osuriel** [tgriesser/knex#3018]
# Environment

"knex": "^0.16.3",
"mysql": "^2.16.0"

I'm trying to do a lot of things and test out stuff and I keep polluting my test database with random data. ideally, I'd just like to do things and see what the output query would be instead of running it against the actual database to see if it actually worked.

I was told I need to add .toString() .toSql() at the end of my query builder. but this does not work, 

1. .toString() returns an object instead of a string like the documentation says it should. which does not help me see what will actually be ran in the database.

2. .toString() still queries the database which means that I have to pollute the database just to test stuff which in my case is really difficult because I can't just put random data.

```
const addNewChain = async ({ displayName, address, phoneNumbers }) => {
  const result = await db().transaction(trx =>
    trx.insert(mapToSnakeCase(address), 'id').into('addresses')
      .then(addressId =>
        trx.insert({ addresses_id: addressId, display_name: displayName }, 'id')
          .into('chains'))
      .then((chainId) => {
        const phoneNumbersMapped = phoneNumbers
          .map(pn => ({ ...mapToSnakeCase(pn), chains_id: chainId }));
        return trx.insert(phoneNumbersMapped, 'phone_number').into('chains_phones');
      })).toString();
  return result;
};

```

# Feature discussion / request

1. Explain what is your use case

2. Explain what kind of feature would support this

3. Give some API proposal, how the feature should work

# Missing / erroneus documentation

Send issue to documentation repo, or fix it and send PR https://github.com/knex/documentation

# Questions about how to use knex

Github issues are for knex development. Please send questions how to use knex to
stackoverflow or ask about it in gitter chat.

**Comment by tgriesser** [comment]
You have the entire query in one statement. Try breaking it up: 

```ts
const addNewChain = async ({ displayName, address, phoneNumbers }) => {
  return db().transaction(async (trx) => {
    const insertAddressQb = trx.insert(mapToSnakeCase(address)).into('addresses')
    console.log(insertAddressQb.toString())
    const [addressId] = await insertAddressQb
    const chainsInsertQb = trx.insert({ addresses_id: addressId, display_name: displayName }).into('chains')
    console.log(chainsInsertQb.toString())
    const [chainId] = await chainsInsertQb
    const phoneNumbersMapped = phoneNumbers.map(pn => ({ ...mapToSnakeCase(pn), chains_id: chainId }));
    const chainsPhonesInsert = trx.insert(phoneNumbersMapped, 'phone_number').into('chains_phones');
    console.log(chainsPhonesInsert.toString())
    return await chainsPhonesInsert
  }
};
```
The queries don't get executed until they're awaited and/or `.then()` is called. Also if you need more debugging start your app with [DEBUG](https://knexjs.org/#faq) `DEBUG=knex* node index.js` from the terminal
