### ISSUE TITLE
[BUG] loadExtensions works unright way

### ISSUE THREAD

**Issue by dmytropanontko** [tgriesser/knex#3019]
# Environment

Knex version: `0.16.3`
DB: `Postgres 10.6`
OS: `Ubuntu 18.04`

I tried to run migration

```js
this.knex.migrate.latest({
      directory: './core/database/migrations',
      tableName: 'knex_core_migrations',
      loadExtensions: ['.js']
    })
```

I use TypeScript and create source map for all my fiels with extensions `.d.ts`. When I was running migration I got following error message:

![image](https://user-images.githubusercontent.com/37536815/51985897-aea99b00-24a7-11e9-842b-c64694e1b944.png)

After that I go to `/node_modules/knex/lib/migrate/sources/fs-migrations.js` and added `console.log(...)` to `filterMigrations`. Result of `console.log(...)` you can see on the photo. If I understand right for some reasons `loadExtensions` works unright. I did one more thing. I cloned your repo and run `knex` on local machine. When I run `knex` on local all works fine.

**Comment by kibertoad** [comment]
It was fixed in unreleased version: https://github.com/tgriesser/knex/pull/2969

Hopefully we release 0.16.4 with a fix soon (@elhigu wink-wink)

**Comment by dmytropanontko** [comment]
@kibertoad I need this fix ASAP. Could you release some beta version?

**Comment by kibertoad** [comment]
Unfortunately, I can't, but @elhigu can.

**Comment by dmytropanontko** [comment]
Hi @elhigu , please release beta version of `0.16.4`. Thanks
@kibertoad Thanks and have a nice day.

**Comment by elhigu** [comment]
0.16.4-next1 is now in npm
