### ISSUE TITLE
mssql: `TypeError: The "config.server" property is required and must be of type string.`

### ISSUE THREAD

**Issue by vjpr** [tgriesser/knex#3020]
`This knex version only supports mssql driver versions 4.1.0 and 5.0.0+`

# Environment

Knex version: knex@0.16.3
Database + version: mssql
OS: macos
mssql version: 5.0.0-alpha.5

**Comment by elhigu** [comment]
Error tells you that 5.0.0-alpha.5 is less than 5.0.0. You need to update your mssql driver.

**Comment by elhigu** [comment]
hmm.. sounds like alpha should work, since I just did ran all the tests suite against it a minute ago. So I cannot reproduce this error.

**Comment by elhigu** [comment]
Is this about  missing typings or what...? Will re-open if clarifications are added.
