### ISSUE TITLE
Knex not passing client connection settings to database driver (Postgres)

### ISSUE THREAD

**Issue by reediculous456** [tgriesser/knex#3030]
# Environment

- Knex version: have used 0.13.0, 0.14.X, 0.15.0, 0.16.3 (currently using 0.15.0 because that is the highest bookshelf is compatible with)
- pg version: 7.8.0
- Database + version: Postgres 8.4.20
- OS: MacOS

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do
Knex does not pass the connection configuration to the Postgres Database Driver (pg). If I initialize the pg driver myself using the same connection details I am passing to knex, it connects successfully and works as intended

2. Error message
```
Unhandled rejection error: missing FROM-clause entry for table "undefined"
    at Connection.parseE (/Users/Wesley/Desktop/VendorSearch/node_modules/pg/lib/connection.js:555:11)
    at Connection.parseMessage (/Users/Wesley/Desktop/VendorSearch/node_modules/pg/lib/connection.js:380:19)
    at Socket.<anonymous> (/Users/Wesley/Desktop/VendorSearch/node_modules/pg/lib/connection.js:120:22)
    at Socket.emit (events.js:189:13)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
    at Socket.Readable.push (_stream_readable.js:220:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
```

3. Test Code
## Database.js
```
const config = require(`../../utils/Config`);

const knex = require(`knex`)({
  client: config.database.dialect,
  version: config.database.version,
  connection: {
    host: config.database.host,
    user: config.database.username,
    password: config.database.password,
    database: config.database.name,
    port: config.database.port
  }
});

const bookshelf = require(`bookshelf`)(knex);

const Role = bookshelf.Model.extend({
  tablename: `roles`
});

const User = bookshelf.Model.extend({
  tablename: `users`,
  role: function () {
    return this.belongsTo(Role);
  }
});

exports.Role = Role;
exports.User = User;

exports.__bookshelf = bookshelf;
exports.knex = knex;
```
## User.js
```
const User = require(`../../Database`).User;
const jsonify = require(`../../Database`).jsonify;
const knex = require(`../../Database`).knex;

exports.getAll = () => {
  console.log(knex.client);
  return User.fetchAll()
    .then(jsonify);
};
```
## knex.log(client) result
```
Client_PG {
  config:
   { client: 'pg',
     version: '8.4.20',
     connection:
      { host: '(www.myhost.com)',
        user: '(my username)',
        password: '(my password)',
        database: '(my database)',
        port: '5432' } },
  logger:
   Logger {
     _debug: undefined,
     _warn: undefined,
     _error: undefined,
     _deprecate: undefined },
  version: '8.4.20',
  connectionSettings:
   { host: '(www.myhost.com)',
     user: '(my username)',
     password: '(my password)',
     database: '(my database)',
     port: '5432' },
  driver:
   PG {
     defaults:
      { host: 'localhost',
        user: 'Wesley',
        database: 'Wesley',
        password: null,
        connectionString: undefined,
        port: 5432,
        rows: 0,
        binary: false,
        max: 10,
        idleTimeoutMillis: 30000 ...
```

**Comment by ricardograca** [comment]
I'm not seeing any evidence of Knex not passing client connection settings to database driver. Also, if Bookshelf is irrelevant in your case there is no need to include that information. If you think it is relevant, then you should move this to the Bookshelf repo, but I'm pretty sure the connection settings are being passed correctly, considering both Knex's and Bookshelf's test suites are currently green.

**Comment by reediculous456** [comment]
Looking at the console output, it looks like maybe i'm only seeing the default config of pg and not the one knex is passing it. either way, something is wrong with the combination of knex, pg, and Postgres 8.4.20
What other documentation would you like given the error output i'm receiving?

**Comment by ricardograca** [comment]
PostgreSQL 8.4 is approaching 10 years old. It predates Knex by several years. I'm not sure (if?) when was the last time someone tested Knex with such an old version.

**Comment by reediculous456** [comment]
```
   console.log(knex.select().from('users').toString());
   console.log(knex.select().from('users').then(function(users){
    console.log(users);
}));
```
gave result
`select * from "users"`
with correct response so this seems to be a bookshelf error

**Comment by ricardograca** [comment]
Closing this as invalid then.
