### ISSUE TITLE
Returning doesn't work with insert on MySQL

### ISSUE THREAD

**Issue by michaelh-mg** [tgriesser/knex#3031]
# Environment

Knex version: `0.16.2`
Database + version: MySQL 5.6.42
OS: Node Docker container running on MacOS Mojave 10.14.2

Select applicable tempalate from below.
If issue is about oracledb support tag @ atiertant. For MSSql tag @ smorey2 .
Rest of dialects doesn't need tags.

# Bug

When doing an `insert` with `returning`, the fields specified in `returning` are not returned. Instead, just the `id` is returned.

## Example
```typescript
return this.db
      .transaction(trx =>
        trx
          .withSchema("schema_name")
          .into("installation")
          .insert(inst, ["id", "app_version"])
      )
```
**OR**
```typescript
return this.db
      .transaction(trx =>
        trx
          .withSchema("schema_name")
          .into("installation")
          .insert(inst)
          .returning(["id", "app_version"])
      )
```
Both of those examples will only return an array with the generated `id` in it. It won't return the `app_version`.

### Actual Return Value
```typescript
[ 0 ]
```

### Expected Return Value
```typescript
[ { id: 0, app_version: "1.0.1" } ]
```

_NOTE: I'm aware that `.returning` will not work for multiple inserts with MySQL. I was only attempting single inserts when this bug manifested._

**Comment by elhigu** [comment]
Duplicate + docs say that mysql db does not support `returning` statement. So this is limitation of the mysql database, not knex.

**Comment by michaelh-mg** [comment]
@elhigu Actually, the docs do not say that MySQL doesn't support the `returning` statement. The docs say that MySQL does not support _multiple inserts_ with `returning`. Also, can you please post the issue number to which this ticket is a duplicate? I searched the issues before creating this ticket and didn't see any existing ticket for this issue.

https://knexjs.org/#Builder-returning

> The returning method is ... and has no support for multiple inserts on MySQL and SQLite.

**Comment by elhigu** [comment]
There are many issues to which this is duplicate, I’ll add references when I have time.

**Comment by elhigu** [comment]
Looks like docs were fixed in https://github.com/tgriesser/knex/commit/5c77ee2acd6fe7747b08ade84abb22818e7f6e31 and then contradicting info was added in https://github.com/knex/documentation/pull/141 . Latter change should be reverted.

The first line of description has the correct info https://knexjs.org/#Builder-returning

> Utilized by PostgreSQL, MSSQL, and Oracle databases, the "returning" method specifies which column should be returned by the insert and update methods. 

Duplicates / related issues:

https://github.com/tgriesser/knex/issues/2851 
https://github.com/tgriesser/knex/issues/2785
https://github.com/tgriesser/knex/issues/2760
https://github.com/tgriesser/knex/issues/2616
https://github.com/tgriesser/knex/issues/2075

Probably more questions about it are found from stackoverflow...

**Comment by skunca** [comment]
Hi,

Could you please revisit this? While MySQL doesn't support returning the ID, the libraries that knex uses to execute the queries do:

https://github.com/mysqljs/mysql#getting-the-id-of-an-inserted-row

Is it possible to surface these values in knex results? Wouldn't mind to do a PR for this.

**Comment by elhigu** [comment]
@skunca that has nothing to do with this issue. You can open new feature request about it where to discuss it further. Afaik getting id of single inserted row has never been a problem even with mysql.

**Comment by dsomel21** [comment]
Any update on this?
