### ISSUE TITLE
Migration fails for dynamic schema name

### ISSUE THREAD

**Issue by hbarcelos** [tgriesser/knex#3034]
# Environment

Knex version: knex@0.16.3
Database + version: MySQL 5.7.24
OS: Linux (Manjaro)

# Bug

I'm trying to setup an integration test suite using [`ava`](https://github.com/avajs/ava). As known, `ava` spawns different Node processes for each test file.

In order to make the tests isolated, I need to re-create my database and run the migrations in all test files. I started bootstrapping and got the following script:

```javascript
import test from 'ava';
import cuid from 'cuid';
import knexFactory from 'knex';
import knexFile from './knexfile';

const knex = knexFactory(knexFile.development);

test.before(async t => {
  const schemaName = `foo_${cuid()}`;

  await knex.raw(`CREATE SCHEMA ${schemaName}`);

  try {
    await knex.migrate.latest({ schemaName });;
  } catch (err) {

  }

  Object.assign(t.context, { schemaName });
});

test.after.always(async t => {
  const { schemaName } = t.context;
  await knex.raw(`DROP SCHEMA ${schemaName}`);
});

test('foo', () => {})
```

However, I'm running into the following error:

> migration file "20190205110315_create_users_table.js" failed
> migration failed with error: create table `users` (`id` int unsigned not null auto_increment primary key, `email` varchar(255), `password` text) - Table 'users' already exists

What is happening is that the `.migrate.latest()` call is ignoring its `schemaName` parameter and it's running against the configuration defined in the `knexfile.js` file, that is, the actual database.

The migration file is pretty straightforward:

```javascript
exports.up = function(knex, Promise) {
  return knex.schema.createTable('users', table => {
    table.increments();
    table.string('email');
    table.text('password');
  })
};

exports.down = function(knex, Promise) {
  return knex.schema.dropTable('users');
};
```

**Comment by kibertoad** [comment]
@hbarcelos Migrator `schemaName` does not affect schema of migrations themselves, it is only to specify what schema to use for internal migration tables (lock and changelog). If you want to parametrize your migrations based on knex instances, use this:

```
Getting parametrized instance

You can call method withUserParams on a Knex instance if you want to get a copy (with same connections) with custom parameters (e. g. to execute same migrations with different parameters)

var knex = require('knex')({
  // Params
};

var knexWithParams = knex.withUserParams({customUserParam: 'table1'});
var customUserParam = knexWithParams.userParams.customUserParam;
```

Then you can get schema from e. g. `knex.userParams.schema` inside the migration.

**Comment by elhigu** [comment]
Closing as this doesnt seem like a bug, but expected behaviour.
