### ISSUE TITLE
Query chain is failed ?

### ISSUE THREAD

**Issue by acharotariya** [tgriesser/knex#3035]
# Environment

Knex version:0.16.3
Database + version: mysql  Ver 8.0.13 for macos10.14 on x86_64 (MySQL Community Server - GPL)
OS:macos

# Bug

1. here i'm use this query to get items & passing  dynamic value (columnname,sort) but if value is not passed than query is failed.please help me.
let items = await knex.select().table('items').orderBy(`items.${columnname}`,sort).limit(limit).offset(page).catch((err) => { console.log("err >>>>>>", err) })

**Comment by elhigu** [comment]
Cannot reproduce. Knex usage questions should be done in stackoverflow or gitter chat.
