### ISSUE TITLE
Error: Connection lost: The server closed the connection.

### ISSUE THREAD

**Issue by mengzhen94** [tgriesser/knex#3037]
# Environment

Knex version: 0.16.3
Database + version: MariaDB
OS: ubuntu

# Description
Hi, after my app running for several hours, there is a connection lost issue `Error: Connection lost: The server closed the connection.`. 
My Knex connection is:
```
const knex: Knex = Knex({
  client: 'mysql',
  useNullAsDefault: true,
  connection: {
      host: 'mysql',
      port: 
      user: 
      password:
      database: 
    },
  ...knexSnakeCaseMappers()
});
```
Does anyone have any idea how to keep connection?

**Comment by elhigu** [comment]
When connection if cut by the server, knex's pool discards that connection and automatically creates new one when needed.

**Comment by probitaille** [comment]
Apparently, Knex may fail to creates new one when needed. I got the exact same problem. If my application is idle for serveral hours, the server closed the connection and Knex doesn't create a new one. Need to restart the whole application to create a new connection. 
![image](https://user-images.githubusercontent.com/2374739/64872279-e8817900-d614-11e9-9922-d235c85459bd.png)

**Comment by elhigu** [comment]
If it happens with latest knex, you should create separate bug report. Iirc for example with oracle drivers there are still bugs when trying to recognize broken connections.

**Comment by radiumrasheed** [comment]
@elhigu are you saying it just logs this as a warning, and that it can be ignored ?

**Comment by elhigu** [comment]
@radiumrasheed no. I'm not saying that. Try to read my comment again.

**Comment by jordy-k** [comment]
For me, just add pool in knex configuration:
```
const knex: Knex = Knex({
  client: 'mysql',
  useNullAsDefault: true,
  connection: {
      host: 'mysql',
      port: 
      user: 
      password:
      database: 
    },
    pool: { min: 0, max: 7 }
  ...knexSnakeCaseMappers()
});
```
