### ISSUE TITLE
Querying w/o a transaction always times-out after use of transaction on same table 

### ISSUE THREAD

**Issue by CodisRedding** [tgriesser/knex#3049]
# Environment

Knex version: 0.16.3
Database + version: mssql:4.1.0
OS: macos:10.14.1
@smorey2 

# Bug
Querying w/o a transaction always times-out after use of transaction on same table 

1. _Explain what kind of behaviour you are getting and how you think it should do_
If I query a table within a transaction I cannot query that table again without a transaction (see `Request time` below in the `route.js` file.

2. _Error message_
`{
  "message": "select [ID] from [tableName] where [DeactivatedDate] is null and [Something] = @p0 - Timeout: Request failed to complete in 15000ms",
  "stack": "RequestError: Timeout: Request failed to complete in 15000ms\n    at Request.tds.Request.err [as userCallback] (/Users/rocky/Code/extract-explorer-api/node_modules/mssql/lib/tedious.js:578:19)\n    at Request._this.callback (/Users/rocky/Code/extract-explorer-api/node_modules/tedious/lib/request.js:60:27)\n    at Connection.message (/Users/rocky/Code/extract-explorer-api/node_modules/tedious/lib/connection.js:1807:24)\n    at Connection.dispatchEvent (/Users/rocky/Code/extract-explorer-api/node_modules/tedious/lib/connection.js:863:38)\n    at MessageIO.<anonymous> (/Users/rocky/Code/extract-explorer-api/node_modules/tedious/lib/connection.js:757:18)\n    at emitNone (events.js:106:13)\n    at MessageIO.emit (events.js:208:7)\n    at ReadablePacketStream.<anonymous> (/Users/rocky/Code/extract-explorer-api/node_modules/tedious/lib/message-io.js:102:16)\n    at emitOne (events.js:116:13)\n    at ReadablePacketStream.emit (events.js:211:7)\n    at addChunk (/Users/rocky/Code/extract-explorer-api/node_modules/readable-stream/lib/_stream_readable.js:291:12)\n    at readableAddChunk (/Users/rocky/Code/extract-explorer-api/node_modules/readable-stream/lib/_stream_readable.js:278:11)\n    at ReadablePacketStream.Readable.push (/Users/rocky/Code/extract-explorer-api/node_modules/readable-stream/lib/_stream_readable.js:245:10)\n    at ReadablePacketStream.Transform.push (/Users/rocky/Code/extract-explorer-api/node_modules/readable-stream/lib/_stream_transform.js:148:32)\n    at ReadablePacketStream._transform (/Users/rocky/Code/extract-explorer-api/node_modules/tedious/lib/message-io.js:70:16)\n    at ReadablePacketStream.Transform._read (/Users/rocky/Code/extract-explorer-api/node_modules/readable-stream/lib/_stream_transform.js:184:10)\n    at ReadablePacketStream.Transform._write (/Users/rocky/Code/extract-explorer-api/node_modules/readable-stream/lib/_stream_transform.js:172:83)\n    at doWrite (/Users/rocky/Code/extract-explorer-api/node_modules/readable-stream/lib/_stream_writable.js:428:64)\n    at writeOrBuffer (/Users/rocky/Code/extract-explorer-api/node_modules/readable-stream/lib/_stream_writable.js:417:5)\n    at ReadablePacketStream.Writable.write (/Users/rocky/Code/extract-explorer-api/node_modules/readable-stream/lib/_stream_writable.js:334:11)\n    at Socket.ondata (_stream_readable.js:639:20)\n    at emitOne (events.js:116:13)\nFrom previous event:\n    at Client_MSSQL._query (/Users/rocky/Code/extract-explorer-api/node_modules/knex/lib/dialects/mssql/index.js:311:12)\n    at Client_MSSQL.query (/Users/rocky/Code/extract-explorer-api/node_modules/knex/lib/client.js:192:17)\n    at Runner.<anonymous> (/Users/rocky/Code/extract-explorer-api/node_modules/knex/lib/runner.js:138:36)\nFrom previous event:\n    at /Users/rocky/Code/extract-explorer-api/node_modules/knex/lib/runner.js:47:21\n    at runCallback (timers.js:810:20)\n    at tryOnImmediate (timers.js:768:5)\n    at processImmediate [as _immediateCallback] (timers.js:745:5)\nFrom previous event:\n    at Runner.run (/Users/rocky/Code/extract-explorer-api/node_modules/knex/lib/runner.js:33:30)\n    at Builder.Target.then (/Users/rocky/Code/extract-explorer-api/node_modules/knex/lib/interface.js:23:43)\n    at Object.getByName (/Users/rocky/Code/extract-explorer-api/src/models/extract-delimiter.js:42:8)\n    at database.transaction (/Users/rocky/Code/extract-explorer-api/src/routes/extract-import.js:88:30)\n    at <anonymous>",
  "code": "ETIMEOUT",
  "number": "ETIMEOUT",
  "originalError": {
    "message": "Timeout: Request failed to complete in 15000ms",
    "code": "ETIMEOUT"
  },
  "name": "RequestError",
  "precedingErrors": [],
  "__stackCleaned__": true,
  "user": "rocky@thatsme.com",
  "date": "2019-02-13 09:54:19",
  "level": "error"
}`

3. _Code_
> database.js

```javascript
"use strict";

const config = require("./config");

const knex = require("knex")({
  client: "mssql",
  connection: {
    port: config("DB_PORT"),
    host: config("DB_HOST"),
    user: config("DB_USER"),
    password: config("DB_PASSWORD"),
    database: config("DB_NAME"),
    charset: "utf8"
  },
  pool: {
    min: 1,
    max: 20
  }
});

module.exports = knex;
```

> vendor.js

```javascript
"use strict";

const database = require("../database");

module.exports = {
  get: () => {
    return database("tblVendor")
      .select("Name")
      .where({ DeactivatedDate: null });
  },
  
  insert: (name, trx) => {
    // use transaction if supplied
    const db = trx ? trx : database;
    return db
      .returning(["id"])
      .insert({ Name: name })
      .into("tblVendor");
  }
};
```

> route.js

```javascript
"use strict";

const database = require("database");
const vendor = require("vendor");

await database.transaction(async (trx) => {
  // works
  const vendors1 = await vendor.get();

  // works
  const id = await vendor.insert("some-name", trx);

  // Request time
  const vendors2 = await vendor.get();
});
```

**Comment by CodisRedding** [comment]
I know what is happening and it's def not a bug. I will leave incase others run across it (delete if you want). I didn't realize that the entire table would lock until the transaction committed. The solution is to query within the same transaction (which kind of sucks).

**Comment by elhigu** [comment]
You mean that mssql locks the whole table when it inserts a row to it?

**Comment by CodisRedding** [comment]
Well, I cannot query that table without the use of the transaction.

**Comment by CodisRedding** [comment]
I checked what kind of lock it puts on a table when it's not committed.

request_mode = IX

IX (Intent Exclusive). Indicates the intention to place X locks on some subordinate resource in the lock hierarchy

X (Exclusive). The holding session is granted exclusive access to the resource.
