### ISSUE TITLE
Knexjs with sphinxql (mysql driver)

### ISSUE THREAD

**Issue by denfm** [tgriesser/knex#3051]
# Environment

Knex version: 0.16.3
Database + version: Mysql (sphinxql)
OS: Windows 10

# Questions about how to use knex

Could you please tell how to use knexjs (builder) in order to add facet tags at the end of the request?

**Comment by elhigu** [comment]
Usage questions should go to stackoverflow. Also would be helpful if you can tell what kind of query you are trying to write. you should be able to add stuff to the end of query with:

```
const originalQueryBuilder = knex('table').where('id', 1);
knex.raw('? STUFF AFTER QUERY', [originalQueryBuilder]);
```

This would be easier if we would have https://github.com/tgriesser/knex/issues/3032 feature implemented, which would allow to add `.raw` pass to be a last phase in the query building.
