### ISSUE TITLE
How to lock database tables in Oracle database?

### ISSUE THREAD

**Issue by apurvshah** [tgriesser/knex#3053]
# Environment

node: v8.9.2
Knex version: 0.16.2
oracledb: 3.0.1
Database + version: Oracle 11g/12C
OS: Windows8.1 Pro

Select applicable tempalate from below.
If issue is about knex,  oracledb
Rest of dialects doesn't need tags.

How to lock database tables in Oracle using knex?

My application is using both MSSQL and Oracle database. I would like to keep the code common for both of them. I am able to lock the database tables during any CRUD operation in MSSQL database using 1. 'knex.transaction(trx)' and then subsequent calls to transacting(trx)/trx.commit. 

I understand that Transaction itself should not lock any tables. But then how to lock tables using knex in both MSSQL and Oracle database by keeping code base same?

@atiertant

**Comment by elhigu** [comment]
Depends what kind of locking is needed. `select for update` can be used for locking rows otherwise you must write a helper, which recognized if knex client is oracle or mssql and then do different knex.raw call depending on dialect.

Knex usage questions should go to stackoverflow.
