### ISSUE TITLE
Single whereIn clause to retrieve records having a certain value or null

### ISSUE THREAD

**Issue by sthnaqvi** [tgriesser/knex#3057]
# Environment

Knex version:0.15.2
Database + version: 5.6.34-log - MySQL Community Server (GPL)
OS: Ubuntu

# Bug
I am not receiving any data where location is null in below query

# Query
db('users').whereIn('location', [null, 0, 'Delhi'])

1. Explain what kind of behavior you are getting and how you think it should do?

Actual result that I am getting is an empty array ([ ]). 
While I expect to get records of all users having locations as either 0, null, or 'Delhi'

**Comment by elhigu** [comment]
Not knex issue. Try stackoverflow for usage questions.

**Comment by sthnaqvi** [comment]
@elhigu This is not a usage question nor is this a bug, this is just a feature enhancement proposal
Scenario:
When I use this query `db('users').whereIn('location', ['Mumbai', 'Delhi'])`  I got users who have location Mumbai , Delhi .
But when I use `db('users').whereIn('location', [null, 'Delhi'])` , I only got only Delhi location users, ideally i should get null as well as Delhi based users.

**Comment by elhigu** [comment]
https://runkit.com/embed/uqqk6szx9z3o

It seems to generate correct type of query. What kind os SQL you are trying to build? Are you sure that mysql supports passing null to where in clause?

**Comment by elhigu** [comment]
That being said if you write a proper feature request issue about it and investigate how null values works with where in different dialects and what should be made to make it work consistently between databases engines it could be left open and reconsidered (there are also potential performance drawbacks in some cases what changing this may cause).
