### ISSUE TITLE
Using DELIMITER in MySQL knex raw query

### ISSUE THREAD

**Issue by victorbadila** [tgriesser/knex#3058]
# Environment

Knex version: 0.16.3
Database + version: MySQL 8
OS: Ubuntu 18.04

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do

I'm trying to run a raw MySQL query that involves the DELIMITER keyword. While the query works if ran with the SQL console or workbench it throws an error with knex.

2. Error message
```
 DELIMITER $$ - ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'DELIMITER $$' at line 1
```

3. Reduced test code, for example in https://npm.runkit.com/knex or if it needs real
   database connection to mysql or postgresql, then single file example which initializes
   needed data and demonstrates the problem.

`await knex.raw('DELIMITER $$')`

**Comment by elhigu** [comment]
seems to work as it should:

```
> knex.raw('DELIMETER $$').toSQL()
{ method: 'raw',
  sql: 'DELIMETER $$',
  bindings: [],
  options: {},
  __knexQueryUid: 'ee5322ef-de28-43b2-8089-531827ab5413' }
```

Sounds like you are trying to run invalid query that is not supported by mysql server or node mysql driver. You can check out from mysql driver developers if that should work.

**Comment by dealercontrolrachel** [comment]
I am having the same issue. 

At the bottom of my migration file I have 
`.then(() => knex.raw('DELIMITER |'))`

and I get 

```
migration failed with error: DELIMITER | - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'DELIMITER |' at line 1```

If I paste DELIMITER | into mysql manually it works fine of course. 

Please address this issue.

**Comment by victorbadila** [comment]
@dealercontrolrachel I debugged this issue further and it seems that `DELIMITER` is not a SQL token but more of a sql client prop that lets it do certain magic, i.e. change how certain code blocks are interpreted without ending the script / query. The problem is that `node-mysql` that this repo uses as a dependency doesn't fully implement a sql client, more info here: https://github.com/mysqljs/mysql/issues/1683

I was able to get around this by reverting to bash inside my node code and calling mysql manually from there, and did so wrapping everything in promises where needed so that my migrations goes smoothly.

**Comment by dealercontrolrachel** [comment]
@victorbadila yeah I realized it was a command line thing late last night. Thank you for looking into it anyways. I also opened this issue if you are interested #3091

**Comment by codingstill** [comment]
I had a similar issue when trying to update a stored procedure with `knex.raw()`. Turns out that the sql passed in `raw('')` does not need to set/change the delimiter at all. 

For example the following fails via `knex.raw()`
```
DROP PROCEDURE IF EXISTS `sp_name`;
DELIMITER $$
CREATE PROCEDURE `sp_name` ()
BEGIN
-- sp_name implementation
END$$

DELIMITER ;
```

The following though runs via `knex.raw()`
```
DROP PROCEDURE IF EXISTS `sp_name`;

CREATE PROCEDURE `sp_name` ()
BEGIN
-- sp_name implementation
END;
```
knex: 0.14.6, MySQL: 8.0.18
