### ISSUE TITLE
Consider bumping major version to be fully semver compliant.

### ISSUE THREAD

**Issue by bradobro** [tgriesser/knex#3062]
# Environment

Knex version: 0.16.3
Database + version: not applicable
OS: not applicable.

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do

I expect to be able to use package auditing tools, such as `npm-check`, to audit my `package.json`. I expect core dependencies, such as my database libraries, to adhere to the semver spec, including the use of major version `0`. (See https://semver.org/#spec-item-4 and https://semver.org/#spec-item-5).

2. Error message

Instead, I get a warning because `knex` still uses major version `0`:

``` Non-Semver Versions less than 1.0.0, caution.
 ◯ adm-zip  0.4.7   ❯  0.4.13  https://github.com/cthackers/adm-zip
 ◯ knex     0.12.9  ❯  0.16.3  https://knexjs.org
```

**Comment by elhigu** [comment]
That has been considered various times. Will be bumped when ready. Look for issues about version 1.0 for more info and add related issue links if you feel like it.

**Comment by bradobro** [comment]
Thanks @elhigu
