### ISSUE TITLE
exists a way to define the charset for the connection?

### ISSUE THREAD

**Issue by IsCruz** [tgriesser/knex#3064]
Actually i'm using db2 as dat base, i'm looking if exists how to define the charset; 
some special chars in spanish are changing once are inserted in the database

**Comment by elhigu** [comment]
Check db drivers docs if it can be set in connection parameters or it might be set during db creation maybe or set separately when new connection is created with afterCreate callback that can be given in knex config.

**Comment by elhigu** [comment]
Knex doesnt have any separate mechanish just for it.

**Comment by IsCruz** [comment]
> Check db drivers docs if it can be set in connection parameters or it might be set during db creation maybe or set separately when new connection is created with afterCreate callback that can be given in knex config.

That's why i'm asking. I'm not found info about the charset.
thanks
