### ISSUE TITLE
Typescript - Allow more strict typings for insertion/update type and return type

### ISSUE THREAD

**Issue by mmarvick** [tgriesser/knex#3065]
# Environment

Knex version: 0.14.2
Database + version: postgres 9.6.3
OS: MacOS 10.14.2

# Feature discussion / request

1. Explain what is your use case

When using typescript, having stronger typing for updates and insertions would be useful, in addition to return types.

2. Explain what kind of feature would support this

I'm probably missing out on tons of complexity here, but being able to constrain the params that go into certain methods (`where`, `select`, `insert`, `update`), and the return value of a sql call, would be super useful.

I think getting this right for anything more complex than just inserting / selecting straight from a table could be very tricky, but even just for typing for those simple queries could be super useful. And the model for the table could be decoupled from the model for what's being returned from SQL, in case the user is only returning certain columns or is using window functions, etc.

3. Give some API proposal, how the feature should work

I'm probably overlooking a lot, but here's a couple of thoughts

```ts
type Book = {
  id: number;
  title: string;
  author: string;
  pages: number;
}

// In this example, we're inserting books, and returning a single row for all columns in the inserted book
// Returns: Array<Book>
let insertion = await
  knex<Book, Array<Book>>('book')
    // expects Book
    .insert({
      id: 1
      title: 'Fahrenheit 451',
      author: 'Ray Bradbury',
      pages: 208
    })
    .returning('*');

// The below would _FAIL_, both because you're missing a non-optional parameter, and because you're trying to
// insert with a param that doesn't exist
let insertion = await
  knex<Book, Array<Book>>('book')
    // expects Book
    .insert({
      id: 1
      author: 'Ray Bradbury',
      pages: 208,
      // ☠️☠️☠️☠️☠️ this will cause an typescript compile error
      genre: 'Fiction'
    })
    .returning('*');

// In this case, we're specifically inserting into a table with the Book model, but not specifying the return type.
// Returns: any (because return object type is not specified)
let insertion = await
  knex<Book>('book')
    // expects Book
    .insert({
      id: 1
      title: 'Fahrenheit 451',
      author: 'Ray Bradbury',
      pages: 208
    })
    .returning('*');

// In this example, we use no typing at all
// Returns: any (because return object type is not specified)
let insertion = await
  knex('book')
    // expects any (because update object type is not specified)
    .insert({
      id: 1
      title: 'Fahrenheit 451',
      author: 'Ray Bradbury',
      pages: 208
    })
    .returning('*');

// In this example, we can specify that the return type only has one of the columns
// Returns: Array<Pick<Book, 'author'>>
let update = await
  knex<Book, Array<Pick<Book, 'author'>>('book')
    // expects first arg to be `keyof<Book>`, _maybe_ with typesafety on second param as number
    .where('id', 3)
    .update({
      pages: 382
    })
    // expect this to be a string or Array<keyof Pick<Book, 'author'>>, which is just Array<'author'>
    .returning(['author']);
```

**Comment by elhigu** [comment]
You could try using objection with typescript. It already supports this kind of return types for queries that are made to table of certain model etc. I believe ORM level is much more appropriate to do this kind of checks that DB level, where actually resulted data can be pretty much anything. 

Adding this feature is probably not be as useful as you think.

Anyhow... if this doesn't break old typings I don't see any reason why this couldn't be added if someone is willing to do it. I'm personally not taking part to any of knex + typescript issues. 

Leaving open for future discussion for people who would be interested about this.

**Comment by mmarvick** [comment]
You're probably right that this makes more sense at an ORM level. I agree with you that (at least for a return type), this might not add that much value anyways -- what's the point of declaring it with generics when I can just cast it from `any` anyways.

I think inserts/updates are probably the clearest use case that adds some tangible value - partially for the typesafety, but mostly for the autocomplete. It's also a little more straightforward (a lot of the complexity I was worried about with joins and subqueries and windowing functions only really matters if you're trying to type the return type / where clauses / join clauses / etc.)

I constantly find myself doing things like this:

```
let bookUpdates: Partial<Book> = {
  pages: 400
};
return knex('book')
  .update(bookUpdates);
```

Where something like this would be a bit cleaner / simpler:

```
return knex<Book>('book')
  .update({
    pages: 400
  });
```

I am in agreement with the general sentiment though that, at best, this is a nice to have.

**Comment by davidspiess** [comment]
I feel you @mmarvick, i too find myself constantly defining partial interfaces similar to your `book` example.

**Comment by lorefnon** [comment]
I didn't see the discussion here before, but I believe this has been addressed by https://github.com/tgriesser/knex/pull/3168

**Comment by mmarvick** [comment]
I would agree - nice work! Thanks @lorefnon
