### ISSUE TITLE
PgBouncer transaction pooling vs. Knex pooling?

### ISSUE THREAD

**Issue by booboothefool** [tgriesser/knex#3069]
I am running a minimal PostgreSQL instance that allows `max_connections = 25`.

This number is very small, so I noticed that as a single user clicking through my app, I reach this limit very easily. When running `select count(*) from pg_stat_activity` after every query, the number steadily climbs and holds onto the connection long after the query is finished. As a result, I get an error `remaining connection slots are reserved for non-replication superuser connections`, and the database fails to return the query result.

I tried putting PgBouncer in front of my PostgreSQL with transaction pooling mode, and noticed much more reliable performance. The connection count stays low and queries return consistently quick. It also just seems faster in general, perhaps with how it auto-optimizes connects/disconnects. I wasn't able to hit the max connection limit with transaction pooling mode, but when testing session pooling mode and the connection limit is reached, it will seemingly queue up the connection and make it wait a bit to return the request, which is much better than erroring out/crashing like it did without PgBouncer.

I read Knex had built-in connection pooling, but the results are dramatically much better after I added PgBouncer, so I was wondering what the difference was in their pooling mechanisms?

**Comment by wubzz** [comment]
How are you creating the knex instance/object in your app? And at what scope level?

It sounds to me like you are either:

A) Using pool settings that exceed that of your postgres config

B) Creating a knex object per request _(thus creating a new connection)_

Using correct pool settings on a single knex instance should never generate these issues. It would wait for a connection to be available from the pool once it has exceeded the max of 25 and if no connection is available for (default) 60 seconds, it would throw a timeout error.

**Comment by booboothefool** [comment]
Thanks for your insight!

At the top scope in one of my files I create the knex like:
```
const knex = require('knex')(_.pick(require('../knexfile')[env], ['client', 'connection']));
const { Model } = require('objection');
Model.knex(knex);
```
and export it to use throughout the rest of my application (Objection.js uses knex under the hood). A typical request would run a function that looks something like this:

```
    profile: async (root, { id }, context) => {
      try {
        const res =
          await Profile
            .query()
            .findById(id)
        return res;
      } catch (err) {
        throw err;
      }
```

^ so if I click on a bunch of profiles, I seemingly get a bunch of new connections that get held onto for a while (without PgBouncer).

I didn't set any knex pool settings, so it's using whatever the defaults are. I guess that's `min: 2, max: 10`.

>especially when running an app in cluster mode

Yes! So I have a Kubernetes cluster and when I try 1 pod (Node.js app worker) I see 4 connections at rest. When I increase the replicas to 3 pods, it gets multiplied to 12 idle connections. With the 3 pods, I very quickly hit the max connection limit after clicking only a few profiles.

With PgBouncer in front of the 3 pods, it starts with 3-4 connections and caps it at ~10 connections no matter how much I spam click profiles, so I never hit the max connection limit, and everything is much smoother!

The way you describe is how I'd expect Knex to work, but I'm not seeing that kind of behavior. If I hit the max connections limit without PgBouncer, I simply get the error `remaining connection slots are reserved for non-replication superuser connections` and get nothing from the database, until after I wait a long while (like 20 seconds) and try to run the same query again.

**Comment by wubzz** [comment]
Ok, so a cluster resulting in multiple knex instances with default pool settings. Makes sense it would eventually exceed the limit. This setup would be a total of max 40 clients and each connection has an idle timeout of 30 seconds by default.

What worries me is that the pool seems to create a new connection for each request. It should re-use idle connections as much as possible. That however is an issue to be placed in https://github.com/vincit/tarn.js/ rather than Knex if that's really the case.

Using PgBouncer the Knex pool settings shouldn't really matter anyway, since PgBouncer keeps track of the connections. So limitation there is kinda pointless I think? Running cluster without PgBouncer however definitely requires adjusting the default pool settings.

**Comment by elhigu** [comment]
Closing as knex usage issue, please keep on discussing here if you like to. 

Using pg-pool for handling pooling when running knex in multiple processes sounds like nice idea. I have usually just set databases connection limit to (knex instance count * knex pool size), but having external shared connection pool might be a better choice in some cases, for example where you are not able to tune database settings to allow huge connection counts.

**Comment by persunde** [comment]
Setup:

- Postgres DB
- Nodejs backend applications that each have multiple instances/processes running in a Cloud cluster setup
- Knex handling the DB connections and uses Knex as query builder and with the Objection ORM

Please help me **with configuring Knex for a scaled out system** where we have lots of processes using Knex to connect to our DB. I am unable to find any good answer for this online.
I found this thread on SO, but I dont think it answers my problem.
https://stackoverflow.com/questions/63263087/whats-the-difference-between-orm-query-builder-library-connection-pool-size-and?noredirect=1&lq=1

I want to scale out my system using something like Kubernetes or Docker Swarm. So I will run multiple instances of my application. I want to scale out more, and it seems that the amount of connections to the DB will be too high with my current Knex configuration that we use.

Maybe @elhigu can help me answer my questions?
How should I configure Knex for this usecase? It seems that using Knex pooling, will create too many open connections to the database once I scale out to a handful of instances? Or is this not a problem?

I tested out a PgBouncer setup with our current system that is scaled out minimally. The processes use Knex. The system hit the PgBouncer pool limit very quickly and started throwing errors. I was using the standard transaction pooling PgBouncer configuration.
```
max_client_conn = 100
default_pool_size = 20
pool_mode = transaction
```

So how should I configure a system with multiple applications and multiple instances that use Knex as a query builder and as the underlying connection handler for Objection ORM. How can I configure Knex (and maybe the DB and/or PgBouncer) to work well with a system with lots of scaled out processes that uses Knex? How should this be done?

@wubzz says:
> Using correct pool settings on a single knex instance should never generate these issues

but I dont know what the "correct pool setting" would be. So please help me here.

My understanding is that having lots of open connections directly to the DB is bad and can impact the DB performance. My understanding is that with Knex pools, each application will always have at least the minimum pool size of connections open to the DB at all times. So if you scale out this will increase the number of open connections with each new instance. So if you scale out enough it will either slow down the DB with the excessive amounts of open connections or hit the connection limit.
Is my understanding correct?
What do I need to do to fix this problem?

I have read somewhere else that you can take the max number of connections allowed to the DB and divide it by the number of processes running, and that should be your Knex pool size.
But the processes we run have a varied amount of traffic, and I would prefer it if an process that experience heavy traffic can use the full pool/connection size, and release or give it up to other processes when the traffic goes down again.

Note: I do not fully understand the difference between an open connection and a session(?) in a pool, so some terminology might be mixed or used incorrectly.
