### ISSUE TITLE
Upgrading Knex & MSSQL Break Schema Routing

### ISSUE THREAD

**Issue by mgarf** [tgriesser/knex#3070]
# Environment

Knex version: 0.13.0 > 0.16.3
Database + version: Azure MSSQL
OS: Windows

@smorey2 

# Bug

When upgrading from any version higher than 13, KnexJS can no longer find the tables anymore. 

`Invalid object name 'users'`

Adding the schema into the object still causes the same issue

`Invalid object name 'dbo.users'`

Connection settings are setup as:

module.exports = {
  client: process.env.DB_CLIENT, // mssql
  connection: {
    host: process.env.DB_HOST,
    user: process.env.DB_USER,
    password: process.env.DB_PASSWORD,
    options: {
        port: process.env.DB_PORT,
        database: process.env.DB_NAME,
        encrypt: true
    }
  }
};

**Comment by elhigu** [comment]
Please add complete but minimal reproduction code, which sets up database for this and creates a query causing the error. There are integration tests already which verifies that mssql is generally working. Closing until reproduction code provided.
