### ISSUE TITLE
Date-fields have time appended when retrieved

### ISSUE THREAD

**Issue by bockelie93** [tgriesser/knex#3071]
# Environment

Knex version: 0.16.3
Database + version: PostgresSQL + 11.1
OS: Windows 10

# Bug

1. I have a date field created by a migration script (table.date(foo)). When I check the database, the dates are stored on the format YYYY-MM-DD (i.e. 2019-02-26). 

2. When I retrieve that field through knex, I get: { foo: "2019-02-25T23:00:00.000Z" }. I expect to get { foo: "2019-02-25" }.

**Comment by elhigu** [comment]
Use pg-types to set driver to parse date column values differently. I am a bit surprised if you are really getting ISO8061 datetime strings instead of Date() objects from the driver.

**Comment by bockelie93** [comment]
You end up with a date object, which then defaults to a ISO8061 datestime string when sent. 

Ended up just having to return the string when 'parsing' it.
```
import { types } from 'pg';

const DATE_OID = 1082;
const parseDate = (value) => value;

types.setTypeParser(DATE_OID, parseDate);
```

This would result in an ISO8601 string
`const parseDate = (value) => new Date(value);
`

Thanks for the quick reply and solution. 🥇

**Comment by arcollector** [comment]
I will leave my grain of sand to help anyone strugging with postgres, its timestamp format and knex

you need the libraries before nothing, althoug you have installed knex, `import { types } from 'pg'` will fail

```bash
npm install pg pg-types
```

then after calling `Knex(config)` you need to set the parsers, like this

```js
import moment from 'moment';
import { types } from 'pg';
import { builtins } from 'pg-types';
const parseFn = (val) => {
  return val === null ? null : moment(val).format('YYYY-MM-DD HH:mm:ss');
};
types.setTypeParser(builtins.TIMESTAMPTZ, parseFn);
types.setTypeParser(builtins.TIMESTAMP, parseFn);
```

and then initialize your Knex instance, and you are done

**Comment by elhigu** [comment]
Better is to convert those to ISO8601 timestamps to be able to read them correctly for example in browser which is in different timezone than server.

Also using moment for parsing is really slow if you are returning for example 5 timestamps per row and then reading 2000 rows from db can cause spending easily hundreds of milliseconds CPU time thus slowing down server (though I'm pretty sure node-postgres does parsing rows in async way that hopefully it doesn't block event loop at least).

This is quite ugly, but its pretty fast and returns dates in a format which can be then parsed in frontend correctly with `new Date()` or with `moment()` on any timezone. 

```
function pgToISO8601(val) {
    if (val === null) {
      return null;
    }
    
    // supports following formats:
    //
    // 2014-09-23 15:29:18.37788+03
    // 2014-09-23 15:29:18-03
    // 2014-09-23 15:29:18.38+03:30
    // 2014-09-23 15:29:18+00
    // 2014-09-23 15:29:18.38
    // 2014-09-23 15:29:18

    val = val.replace(' ', 'T');
    const positiveTimezoneOffset = val.lastIndexOf('+');
    const negativeTimezoneOffset = val.lastIndexOf('-');
    const subSecondOffset = val.lastIndexOf('.');
    let firstPartLength = val.length;    

    let timezone = '';
    if (positiveTimezoneOffset > 18 || negativeTimezoneOffset > 18) {
      const offset = Math.max(positiveTimezoneOffset, negativeTimezoneOffset);
      const sign = positiveTimezoneOffset > -1 ? '+' : '-';
      const normalizedTz = val.substr(offset+1).replace(':', '');
      const hours = normalizedTz.substr(0,2);
      const minutes = normalizedTz.substr(2,2);
      timezone = sign + hours + ':' + (minutes || '00');
      firstPartLength = offset;
    }

    let milliseconds = '.000';
    if (subSecondOffset != -1) {
      // parseFloat ignores offset part of string
      milliseconds = parseFloat(val.substr(subSecondOffset)).toFixed(3).substr(1);
      firstPartLength = subSecondOffset;
    }
    
    const dateHoursMinutesSeconds = val.substr(0, firstPartLength);

    return dateHoursMinutesSeconds + milliseconds + timezone;
  }
  // Don't parse timestamps to js Date() objects, but just ISO8601 strings
  pgTypes.setTypeParser(builtins.TIMESTAMPTZ, pgToISO8601);
  pgTypes.setTypeParser(builtins.TIMESTAMPT, pgToISO8601);
```

Execution time difference between moment parsing and this one for 100k conversions was:

moment: ~2400ms
adhocparser: ~ 130ms

```
start = new Date().getTime(); for (let i = 0; i < 100000; i++) { moment(`2014-02-27 10:00:00.${i}+0200`).format('DD-MM-YYYY HH:MM:ss'); }; end = new Date().getTime(); console.log(end - start)
03:46:27.877 VM353:1 2484

start = new Date().getTime(); for (let i = 0; i < 100000; i++) { pgToISO8601(`2014-02-27 10:00:00.${i}+0200`); }; end = new Date().getTime(); console.log(end - start)
03:47:24.840 VM431:1 127
```

**Comment by PascalUlor** [comment]
@arcollector thanks, your approach works

**Comment by sebastianpikand** [comment]
To all future readers of this post – I had a similar scenario where I had an users table with created_at and update_at columns. These columns created date timestamps with http://knexjs.org/#Schema-timestamps

When displaying admins the users table in frontend, I also retrieved date string from the database and could not find an easy way to format the date to just DD-MM-YYYY.

Ultimately I decided to append .select(knex.raw(...)) to my query, so everything looked like this in the end:

`knex('table_name')
      .select([
       //all "regular" columns
      ])
      .select(knex.raw("to_char(created_at, 'DD-MM-YYYY') as created_at"))`

**Comment by FaresKi** [comment]
> You end up with a date object, which then defaults to a ISO8061 datestime string when sent.
> 
> Ended up just having to return the string when 'parsing' it.
> 
> ```
> import { types } from 'pg';
> 
> const DATE_OID = 1082;
> const parseDate = (value) => value;
> 
> types.setTypeParser(DATE_OID, parseDate);
> ```
> 
> This would result in an ISO8601 string
> `const parseDate = (value) => new Date(value); `
> 
> Thanks for the quick reply and solution. 🥇

Thanks a lot! You're the real hero

**Comment by Narayana53** [comment]
With using this 1901 year is returning as 2001 year. Knex always reading date records with yy format only. How to get yyyy format.
