### ISSUE TITLE
How to perform row level security on prostgreSQL with knex? and bookshelf?

### ISSUE THREAD

**Issue by akdj** [tgriesser/knex#3075]
Hello!

I am trying to secure the access control of my service server, with an authentication by user, and also by setting a [row level security]( https://www.postgresql.org/docs/9.5/ddl-rowsecurity.html) on my database postgreSQL. 

However I don't know how to perform it with knex and bookshelf. how to set the user identity to one specific user in the query to the db? 

Are there someone who already try this? 

thank you

**Comment by elhigu** [comment]
With knex.raw queries. No special support for this in knex.

**Comment by akdj** [comment]
Thank you.  I will try it!
