### ISSUE TITLE
Feature request: allow call .select() with an object

### ISSUE THREAD

**Issue by grundiss** [tgriesser/knex#3076]
# Feature discussion / request
Hi,
It would be nice to be able to call `.select` like this:
```javascript
const query = knex('books').select({
  "bid": "books.id",
  "aid": "authors.id",
}).join(/* ... */)
```
and see it as a synonym to:
```javascript
const query = knex('books').select([
  "books.id as bid",
  "authors.id as aid",
]).join(/* ... */)
```

**Comment by elhigu** [comment]
It already works like that https://runkit.com/embed/astdig72bjnx

**Comment by grundiss** [comment]
Oh, great!

May be add it into the documentation then?

**Comment by elhigu** [comment]
Docs would be nice 👍 I'll add issue to knex/documnetation issue tracker.
