### ISSUE TITLE
MySQL 8.0.13^ Default value as expression support.

### ISSUE THREAD

**Issue by joziahg** [tgriesser/knex#3089]
My first issue, let me know if I messed something up.

# Environment

Knex version: 0.16.3
Database + version: MySQL 8.0.13
OS: Windows 10 / AWS RDS MySQL

# Feature discussion / request

1. Explain what is your use case
MySQL 8.0.13^ comes with the ability to set the default value of a field to an expression. More information from the MySQL docs [here](https://dev.mysql.com/doc/refman/8.0/en/data-type-defaults.html). Knex has the defaultTo() method which is used to set the default value of a field. I am proposing adding support for expressions as a default value via defaultTo() in migrations.
My specific use case is for storing UUID's as VARBINARY(16) and using new UUID functions in 8.0.13.
Additionally knex could use the VARBINARY() type but that is for another issue.
Sample schema builder table method example: 
```javascript
    table.specificType('id', 'VARBINARY(16)').primary().defaultTo(`(UUID_TO_BIN(UUID()))`, true) // this boolean argument could be used to escape the quotes that comes with passing the expression as a string.
```

2. Explain what kind of feature would support this
defaultTo() should be able to do this fairly easily I believe.
3. Give some API proposal, how the feature should work
Perhaps defaultTo() could get a boolean argument to escape the quotes at migration execution.

**Comment by wubzz** [comment]
If I understand the issue correctly then you should be able to solve this by doing

```javascript
    table.specificType('id', 'VARBINARY(16)').primary().defaultTo(knex.raw('(UUID_TO_BIN(UUID()))'))
```

**Comment by joziahg** [comment]
> 
> 
> If I understand the issue correctly then you should be able to solve this by doing
> 
> ```js
>     table.specificType('id', 'VARBINARY(16)').primary().defaultTo(knex.raw('(UUID_TO_BIN(UUID()))'))
> ```

You do understand the issue correctly. My first thought was to use knex.raw() but I wasn't aware you could use it anywhere. I can confirm your solution does work. I think it would be valuable to add a small snippet on the docs for defaultTo() that describes how to use 8.0 default expressions. Thanks!

**Comment by wubzz** [comment]
I agree we should make a note of this in the docs, but maybe not specifically under `defaultTo`. Thing is knex is very flexible, even more so than is described in the API. Whether that is by design or accident, that's just how it is. Things like `Raw`, `Ref`, `Builder` etc can be used as an argument _almost_ anywhere in the API.
