### ISSUE TITLE
Triggers that Perform Inserts

### ISSUE THREAD

**Issue by dealercontrolrachel** [tgriesser/knex#3091]
# Environment

Knex version: 0.16.3
Database + version: Mysql8
OS: Ubuntu

# Feature discussion / request

Apparently setting delimiters does not work. Therefore, as far as I can tell there is no way to execute a trigger that does an insert

I want to run this through knex raw: 
```
DELIMITER |
CREATE TRIGGER `audit_user_update` 
  BEFORE UPDATE ON `users`
  FOR EACH ROW
BEGIN
  INSERT INTO `audit_users` (...) VALUES (...);
END|
DELIMITER ;
```

Currently I see no way to do so. 

One way to fix this that I have seen with other frameworks would be to provide a way to **escape  a semicolon** so for example, I could change my query to this:
```
CREATE TRIGGER `audit_user_update` 
  BEFORE UPDATE ON `users`
  FOR EACH ROW
BEGIN
  INSERT INTO `audit_users` (...) VALUES (...);;
END;
```

Edit: Here's a link to where I saw the escaped semicolon idea
https://stackoverflow.com/a/27282282

**Comment by elhigu** [comment]
You need to setup mysql driver to allow multiple statements in single query. IIRC there is an option for it in mysql client configuration. Escaping will not help anything `knex` doesn't really care if there are semicolons in those strings or not.
