### ISSUE TITLE
Upgrade mssql lib

### ISSUE THREAD

**Issue by dhensby** [tgriesser/knex#3093]
The `mssql` package is now stable v5.0.0 and v6.0.0 is in alpha.

v5 mitigates some issues around `generic-pool` and it's *interesting* `acquire` logic.

v6 removes the `generic-pool` dependency and replaces it with `tarn.js`. v6 also upgrades the underlying `tedious` library to v6.

Both deal a lot better with lost connections.

I don't believe either introduce and breaking changes that would affect this library.

I'm happy to author the upgrade PR (most likely just an upgrade to the package.json) but wanted thoughts on what you'd prefer the baseline to test against?

**Comment by kibertoad** [comment]
Personally I think we should be testing against "recommended" version, so I would say whatever version you personally would encourage people to use in production today.

**Comment by dhensby** [comment]
Well, v5 is going to be a very short lived version as v6 is under development with a view to release it soon™️ 

But I wouldn't ever recommend anyone uses our alpha in production...

As I don't think we'll see any issues with v5, lets bump it to that for now?

**Comment by kibertoad** [comment]
Makes sense!
