### ISSUE TITLE
Rollback Knex do not work !!!?

### ISSUE THREAD

**Issue by Gamerunder** [tgriesser/knex#3094]
# Environment

Knex version: 0.61.3
Database + version: MySql Server 8.0.15 + Worbench 8.0.15
OS: Windows 10 ultimate

I'm 3 days trying everything and nothing works. I use the MySql Workbench database 6.3.

I throw erroneously {idx: 1} the correct {id: 1}, as I am wanting to update an array with many objects, all before the error are written and remain recorded in the database, trx.rollback does not work, if I use trx.rollback () there total crash.  Objects before the error are stored and are not deleted, objects after the error are not stored.

```
exports.up = function (knex, Promise) {
    return knex.schema.createTable('users', table => {
        table.increments('id').primary()
        table.string('name').notNull()
        table.string('nickName').notNull()
        table.string('email').notNull().unique()
        table.string('password').notNull()
        table.integer('credit').notNull().defaultTo(0)
        table.boolean('confirmedAcc').notNull().defaultTo(false)
        table.timestamps(true, true)
    })
};

exports.down = function (knex, Promise) {
    return knex.schema.dropTable('users')
};
```

```
function batchUpdate(table, collection) {
  return knex.transaction(trx => {
    let queries = collection.map(tuple =>
      knex(table)
        .where('id', tuple.id)
        .update(tuple)
        .transacting(trx)
    );
    return Promise.all(queries)
      .then(trx.commit)    
      .catch(trx.rollback);
  });
}

```

Something wrong?

**Comment by elhigu** [comment]
Yes. You should not return promise from transaction handler if you are calling commit/rollback explicitly.

**Comment by Gamerunder** [comment]
Finally after 4 days looking for a solution, I discovered the problem. I used only WorkBench doing an instance simulating MySql Server. This way Rollback does not work.
I installed Mysql Server, I did the Migrations again and now the 'commit' / 'rollback' is running 100%.

Thank you for your help.
