### ISSUE TITLE
Transactions as a promise

### ISSUE THREAD

**Issue by cthurston** [tgriesser/knex#3095]
# Feature discussion / request

Is there a specific design choice in transaction requiring a callback?

I would love to write my transactions with async/await like below.  And I'm not sure if the trx.commit() should be outside or inside the try/catch.

```js
  const trx = await client.transaction()

  try {
    await client
      .transacting(trx)
      .from('OtherItems')
      .whereIn('itemId', itemIds)
      .del()

    await client
      .transacting(trx)
      .from('Items')
      .whereIn('itemId', itemIds)
      .del()

    await trx.commit()
  } catch (err) {
    await trx.rollback()
    throw err
  }
```

As a work-around I made a utility function that I can await.  Is this going to cause me problems down the road?
```js
function getTransaction (client) {
  return new Promise(res => {
    client.transaction(trx => {
      res(trx)
    })
  })
}

const trx = await getTransaction(client)
```

**Comment by kibertoad** [comment]
@cthurston It's funny that you mention it, I've got a thought to implement exactly that last night. I'll give it a shot this weekend.
And no, there shouldn't be a problem with your approach, if you are not returning a promise within your transaction initialization callback, it expects you to handle it manually.

**Comment by elhigu** [comment]
That is actually pretty easy way to leak connections, when forgetting to call commit/rollback for transaction in weird error cases. That being said it is really useful many times to just get that transaction like that 👍

**Comment by elhigu** [comment]
I'm also pretty sure that there has been discussion about this earlier somewhere in the issues...

**Comment by wubzz** [comment]
Yeah there's been multiple discussions around this, and even an implementation or two. Previously it was always halted with reasoning *"for 1.0"* or *"for rewrite"*. But definitely always been of interest.

**Comment by kibertoad** [comment]
@cthurston There was a further improvement in master: now you can access executionPromise that gets resolved or rejected after transaction commit/rollback, in case you need it. See https://github.com/knex/documentation/pull/205 for details.
