### ISSUE TITLE
Confirming that a transaction can be rolled back multiple times

### ISSUE THREAD

**Issue by voidcenter** [tgriesser/knex#3102]
# Environment

Knex version: 0.14.0
Database + version: Postgres 10
OS: 

Hi I have a pretty general question on if the "rollback" function of a transaction can be called with no errors after the transaction has already been committed/rolled-back. I saw this in our use case that we can call the `rollback` function without any errors even after commit. I was expecting some errors. Wonder if this is expected?

Context: we create transaction and then send to a group of engineers to let them use it. They are responsible for commit/rollback. To stay on the safe side and to avoid having lingering DB connections, we also rollback the transaction afterwards in case anyone forgot to commit/rollback their transactions. We expect such cautionary rollback to fail most of them time. However we see it succeed (no error thrown) consistently even transactions was successfully committed already. 

The behavior seems counterintuitive, just want to confirm if it's expected.

**Comment by elhigu** [comment]
Looks like additional commits / rollbacks actually fails, but error is silenced somehow (but still logged to debug):

```
Mikaels-MacBook-Pro-2 mikaelle$ DEBUG=knex:* node
> knex = require('knex')({client: 'pg', connection: 'postgres:///knex_test'})
> let trx = null; new Promise((resolve, reject) => knex.transaction(tRex => resolve(tRex))).then(res => trx = res);
  knex:tx trx1: Starting top level transaction +0ms
Promise { <pending> }
>   knex:client acquired connection from pool: __knexUid2 +0ms
  knex:query BEGIN; trx1 +0ms
  knex:bindings undefined trx1 +0ms
> trx('accounts').limit(1).then(console.log)
Promise {
  _bitField: 0,
  _fulfillmentHandler0: undefined,
  _rejectionHandler0: undefined,
  _promise0: undefined,
  _receiver0: undefined }
>   knex:query select * from "accounts" limit ? trx1 +6s
  knex:bindings [ 1 ] trx1 +6s
[ { id: '3',
    last_name: 'User',
    email: 'test3@example.com',
    logins: 2,
    balance: 0,
    about: 'Lorem ipsum Dolore labore incididunt enim.',
    created_at: 2019-01-31T02:56:22.067Z,
    updated_at: 2019-01-31T02:56:22.067Z,
    phone: null } ]
> trx.commit()
  knex:query COMMIT; trx1 +4s
  knex:bindings undefined trx1 +4s
Promise {
  _bitField: 0,
  _fulfillmentHandler0: undefined,
  _rejectionHandler0: undefined,
  _promise0: undefined,
  _receiver0: undefined }
>   knex:tx trx1: releasing connection +11s
  knex:client releasing connection to pool: __knexUid2 +11s
> trx.commit()
  knex:tx trx1: Transaction completed: COMMIT; +2s
Promise {
  _bitField: 0,
  _fulfillmentHandler0: undefined,
  _rejectionHandler0: undefined,
  _promise0: undefined,
  _receiver0: undefined }
>   knex:tx trx1 error running transaction query +3ms
> trx.commit().catch(console.log)
  knex:tx trx1: Transaction completed: COMMIT; +17s
Promise {
  _bitField: 0,
  _fulfillmentHandler0: undefined,
  _rejectionHandler0: undefined,
  _promise0: undefined,
  _receiver0: undefined }
>   knex:tx trx1 error running transaction query +2ms
> trx.commit().catch(console.log)
  knex:tx trx1: Transaction completed: COMMIT; +9s
Promise {
  _bitField: 0,
  _fulfillmentHandler0: undefined,
  _rejectionHandler0: undefined,
  _promise0: undefined,
  _receiver0: undefined }
>   knex:tx trx1 error running transaction query +1ms
> trx.rollback().catch(console.log)
  knex:tx trx1: Transaction completed: ROLLBACK +12s
Promise {
  _bitField: 0,
  _fulfillmentHandler0: undefined,
  _rejectionHandler0: undefined,
  _promise0: undefined,
  _receiver0: undefined }
>   knex:tx trx1 error running transaction query +1ms
```

I don't know if that is intentional or not. However if transaction is ended, then no more queries can be sent in, so extra rollbacks / commits not failing actually sounds pretty harmless. 

Also some times transaction is rolled back directly by DB driver. In that case client cannot even know that transaction was rolled back behind the scenes (except from rejected promise returned from knex.transaction() call).

This could be also officially decided documented and implemented, but for that we need feature request + more discussion with other contributors and users.
