### ISSUE TITLE
affectedRows on raw query

### ISSUE THREAD

**Issue by justvinz** [tgriesser/knex#3106]
# Environment

Knex version: 0.16.3
Database + version: MySql 5.7.25
OS: ubuntu

@smorey2 

# Bug

I'm executing a raw query:

```js
const sql = `INSERT INTO my_table (topic_id, id, text)
    VALUES ('abc', 'def', 'test')
    ON DUPLICATE KEY UPDATE text = 'foo';`;
  const res = await knex.raw(sql);
  console.log(res);
```

As stated in [MySql documentation](https://dev.mysql.com/doc/refman/5.7/en/insert-on-duplicate.html):
> With ON DUPLICATE KEY UPDATE, the affected-rows value per row is 1 if the row is inserted as a new row, 2 if an existing row is updated, and 0 if an existing row is set to its current values.

**1. First execution**

```js
{
    fieldCount: 0,
    affectedRows: 1,
    insertId: 0,
    serverStatus: 2,
    warningCount: 0,
    message: '',
    protocol41: true,
    changedRows: 0 }
```

✔️ affectedRows: 1 (insert)

**2. Second execution:**

```js
{
    fieldCount: 0,
    affectedRows: 2,
    insertId: 0,
    serverStatus: 2,
    warningCount: 0,
    message: '',
    protocol41: true,
    changedRows: 0 }
```

✔️ affectedRows: 2 (existing row updated)

**3. Third (and following) execution:**

```js
{
    fieldCount: 0,
    affectedRows: 1,
    insertId: 0,
    serverStatus: 2,
    warningCount: 0,
    message: '',
    protocol41: true,
    changedRows: 0 }
```

❗️ affectedRows: **1** => **I was expecting 0 instead**: existing row is set to its current values

--

If I execute the same query directly on mysql, it works as expected.

Any suggestion?
Also, what is serverStatus? Can't find it in the documentation.

Thanks

**Comment by wubzz** [comment]
AFAIK this isn't a knex question since this response comes straight from the driver, in your case `mysql` or `mysql2`.

**Comment by justvinz** [comment]
@wubzz 

Thank you.
Yes, I realized it's definitely a problem of the driver, I've tested it directly without knex.

[Opened issue on mysqljs/mysql](https://github.com/mysqljs/mysql/issues/2194), I'm closing here.
