### ISSUE TITLE
queryContext not passed to wrapIdentifier when `raw` is used

### ISSUE THREAD

**Issue by koskimas** [tgriesser/knex#3110]
# Environment

Knex version: 0.16.3
Database + version: Any
OS: Any

# Bug

Hi!

So I noticed that, at least in some cases, `queryContext` is not passed to `wrapIdentifier` called by raw instances inside queries. Here's a reproduction:

```js
const Knex = require('knex');

const knex = Knex({
  client: 'sqlite3',
  useNullAsDefault: true,
  debug: false,
  connection: {
    filename: ':memory:'
  },

  wrapIdentifier(str, origImpl, queryContext) {
    if (str === 'iAmGoingToBeConvertedToId') {
      str = 'id'

      if (!queryContext) {
        throw Error('We should have queryContext here right?')
      }
    }

    return origImpl(str)
  }
});

async function main() {
  await knex.schema.dropTableIfExists('test')
  await knex.schema.createTable('test', table => {
    table.increments('id')
    table.string('text')
  })

  await knex('test')
    .queryContext({ someStuff: true })
    .select('id')
    .where('id', knex.raw('??', 'iAmGoingToBeConvertedToId'))
}

main()
  .then(() => {
    return knex.destroy()
  })
  .catch(err => {
    console.error(err)
    return knex.destroy()
  })
```

**Comment by koskimas** [comment]
Same thing with subqueries by the way, but one might argue that this is not a bug:

```js
  await knex('test')
    .queryContext({ someStuff: true })
    .select('id')
    .whereIn('id', knex('test').select('iAmGoingToBeConvertedToId'))
```

**Comment by koskimas** [comment]
Ok, I found that you can call `queryContext` for the `raw` instance, but that's not documented anywhere (is it?). If documented, I could live with that feature.

This however, should just work:

```js
  await knex('test')
    .queryContext({ someStuff: true })
    .select('id')
    .whereRaw('id = ??', 'iAmGoingToBeConvertedToId')
```

but it also throws.

**Comment by kibertoad** [comment]
I'll take a look when I'm hime, thanks for reporting!

**Comment by kibertoad** [comment]
@koskimas Do you think any part of documentation should be improved?

**Comment by koskimas** [comment]
If calling `queryContext({ something })` for a `raw` instance is part of the public API, I think it should be documented somewhere.

**Comment by elhigu** [comment]
> If calling queryContext({ something }) for a raw instance is part of the public API, I think it should be documented somewhere.

From implementation I got an impression that queryContext was not added to public api of raw, but just patched in when used as a part of queries with .whereRaw etc.
