### ISSUE TITLE
Can not create MySQL longblob type

### ISSUE THREAD

**Issue by begueradj** [tgriesser/knex#3120]
Knex version: current
Database + version: mysql  Ver 14.14 Distrib 5.7.25, for Linux (x86_64) using  EditLine wrapper
OS: Ubuntu !8.04 LTS

Knex.js has only [binary][1] field type to store images.

I want to use the MySQL BLOB type which Knex.js does not have.
But Knex.js says you can create it (if I understand well) using the [`table.specificType()`][2] method:

> specificType — table.specificType(name, type)
> 
> Sets a specific type for the column creation, if you'd like to add a
> column type that isn't supported here.

I am not sure how to use this.

I tried:

    table.specificType('photo', longblob)
    table.specificType('photo', "longblob")

But I am getting weird errors:

1. For the first syntax, I get this error message: ReferenceError: longblog is not defined      
2. For second syntax, I get this error message:

```
errno: 1064,                                                                                                                                   
  sqlMessage:                                                                                                                                    

```

Any help?

  [1]: https://knexjs.org/#Schema-binary
  [2]: https://knexjs.org/#Schema-specificType

**Comment by begueradj** [comment]
I just had a typo, sorry this is not a bug.

**Comment by jimmykt** [comment]
heyyy what was your fix to your solution?
