### ISSUE TITLE
knex seed primary keys don't start at 1

### ISSUE THREAD

**Issue by juliancoleman** [tgriesser/knex#3122]
# Environment

Knex version: `^0.15.2`
Database + version: Postgres@9.6
OS: MacOS / Docker (CentOS)

# Questions about how to use knex

When running a seed without specifying the PK field, it seems that my id's start at 9 instead of 1, every time I rerun the seeds. Even when using Truncate+Cascade. I don't feel like I should have to specify a pk in each seed as I'm expecting my `increments` to start at 1 with every rerun of the seeds. Or am I wrong?

<img width="74" alt="Screen Shot 2019-03-29 at 10 38 29 AM" src="https://user-images.githubusercontent.com/11545939/55252017-1281e300-520f-11e9-9103-ba0af33b7a81.png">

**Comment by juliancoleman** [comment]
<img width="97" alt="Screen Shot 2019-03-29 at 10 46 25 AM" src="https://user-images.githubusercontent.com/11545939/55252378-08acaf80-5210-11e9-8972-e8619036a39a.png">

**Comment by juliancoleman** [comment]
Why is this expected behavior? This is actually incorrect

**Comment by elhigu** [comment]
Show me your database truncate code.

**Comment by elhigu** [comment]
Also questions how to use knex doesn't belong here, as issue template also states.

**Comment by juliancoleman** [comment]
Using Postico, right click on the table name, click `Truncate...`, and rerun the seed is how I currently do it. I'm sorry about the formatting. I didn't really understand the issue template.

**Comment by juliancoleman** [comment]
However, in my unit tests, I use `knex-db-manager` with the following in my `afterAll` block

```ts
dbManager.truncateDb( ['knex_migrations', 'knex_migrations_lock'] );
```

**Comment by elhigu** [comment]
thats strange, since I've written that truncate code for knex-db-manager and I know that it gives an option to query, which truncates also id sequences of corresponding table. 

Please check from your database after truncate that those sequences are also set to 0.

**Comment by elhigu** [comment]
also knex truncate with postgresql seems to work just fine 

```
> knex('accounts').then(console.log)
Promise {
  _bitField: 0,
  _fulfillmentHandler0: undefined,
  _rejectionHandler0: undefined,
  _promise0: undefined,
  _receiver0: undefined }
>   knex:client acquired connection from pool: __knexUid2 +2s
  knex:query select * from "accounts" trx1 +2s
  knex:bindings [] trx1 +2s
  knex:client releasing connection to pool: __knexUid2 +2ms
[ { id: '1',
    last_name: null,
    email: null,
    logins: 1,
    balance: 0,
    about: null,
    created_at: null,
    updated_at: null,
    phone: null },
  { id: '2',
    last_name: null,
    email: null,
    logins: 1,
    balance: 0,
    about: null,
    created_at: null,
    updated_at: null,
    phone: null },
  { id: '3',
    last_name: null,
    email: null,
    logins: 1,
    balance: 0,
    about: null,
    created_at: null,
    updated_at: null,
    phone: null } ]
> knex('accounts').truncate().then(console.log)
Promise {
  _bitField: 0,
  _fulfillmentHandler0: undefined,
  _rejectionHandler0: undefined,
  _promise0: undefined,
  _receiver0: undefined }
>   knex:client acquired connection from pool: __knexUid2 +14s
  knex:query truncate "accounts" restart identity trx1 +14s
  knex:bindings [] trx1 +14s
  knex:client releasing connection to pool: __knexUid2 +9ms
Result {
  command: 'TRUNCATE',
  rowCount: null,
  oid: null,
  rows: [],
  fields: [],
  _parsers: [],
  RowCtor: null,
  rowAsArray: false,
  _getTypeParser: [Function: bound ] }
> knex('accounts').insert({}).then(console.log)
Promise {
  _bitField: 0,
  _fulfillmentHandler0: undefined,
  _rejectionHandler0: undefined,
  _promise0: undefined,
  _receiver0: undefined }
>   knex:client acquired connection from pool: __knexUid2 +3s
  knex:query insert into "accounts" default values trx1 +3s
  knex:bindings [] trx1 +3s
  knex:client releasing connection to pool: __knexUid2 +6ms
Result {
  command: 'INSERT',
  rowCount: 1,
  oid: 0,
  rows: [],
  fields: [],
  _parsers: [],
  RowCtor: null,
  rowAsArray: false,
  _getTypeParser: [Function: bound ] }
> knex('accounts').then(console.log)
Promise {
  _bitField: 0,
  _fulfillmentHandler0: undefined,
  _rejectionHandler0: undefined,
  _promise0: undefined,
  _receiver0: undefined }
>   knex:client acquired connection from pool: __knexUid2 +3s
  knex:query select * from "accounts" trx1 +3s
  knex:bindings [] trx1 +3s
  knex:client releasing connection to pool: __knexUid2 +1ms
[ { id: '1',
    last_name: null,
    email: null,
    logins: 1,
    balance: 0,
    about: null,
    created_at: null,
    updated_at: null,
    phone: null } ]

```

**Comment by elhigu** [comment]
Try to come up reproduction case for this one and I'm sure you will find what is the problem in your code.

**Comment by juliancoleman** [comment]
## Steps taken

1. Truncated database (restarting identity and cascading)
2. Ran migrations using `npm run knex migrate:latest`
3. Ran seeds using `npm run seed:run`

Issue seems to have resolved itself. This doesn't quite make sense to me, though. Is there some way you might be able to explain it to me? Why on a fresh database would this happen?

**Comment by juliancoleman** [comment]
Could I run `dbManager` in my seed file to ensure proper indexing?

**Comment by elhigu** [comment]
knex(tableName).del() doesn't reset sequence, so that might have been a problem

**Comment by juliancoleman** [comment]
I don't doubt that might have been the issue. And I was certain it was an issue with how I'd written it, not an issue with the library itself. Would it be bad practice to truncate instead of `.del()`?

**Comment by elhigu** [comment]
Truncate and del creates different queries. .truncate() does restart identities and does TRUNCATE query and del() does just DELETE table without where statement, so everything gets deleted. Neither one is a bad practice, just different queries.

Documentation of truncate could be better 😐 I don't know if it restarts sequences on every dialect, but with postgres it does.

**Comment by juliancoleman** [comment]
So calling `knex.truncate` restarts identities. Does it also cascade?

**Comment by juliancoleman** [comment]
If worst comes to worst, I'll just use `raw` to accomplish this, but it would be much better to have it in the library

**Comment by elhigu** [comment]
i don't think it cascades. Yea, I think there is open issue about truncate and cascade somewhere here.

**Comment by juliancoleman** [comment]
Ah, lemme find it because this may just end up being a duplicate of that issue

**Comment by juliancoleman** [comment]
https://github.com/tgriesser/knex/issues/1506#issuecomment-446975889
