### ISSUE TITLE
PostgreSQL Composite Types

### ISSUE THREAD

**Issue by dgadelha** [tgriesser/knex#3123]
It would be nice if Knex was able to handle Javascript objects during insert/updates and treat them as *composite type* representations.

```sql
CREATE TYPE cash AS (
    currency TEXT,
    amount INTEGER
);

CREATE TABLE recharges (
    id SERIAL PRIMARY KEY,
    value cash NOT NULL
);
```
```js
await knex("recharges").insert({
    value: {
        currency: "USD",
        amount: 200
    }
});
```

Related documentation: [PostgreSQL Composite Types](https://www.postgresql.org/docs/current/rowtypes.html)

**Comment by kibertoad** [comment]
Isn't ORM solution like Objection.js or Bookshelf a better library to implement that kind of logic?

**Comment by elhigu** [comment]
If pg driver supports them, I don’t see any problem why knex would not. This is out of scope of knex.

**Comment by dgadelha** [comment]
Hi,

The problem is how Knex deal with them (https://runkit.com/embed/x8oyg5l7xre3):

```js
knex("recharges").insert({
    value: {
        currency: "USD",
        amount: 200
    }
}).toQuery();
```

Results in:
```sql
insert into "recharges" ("value") values ({"currency":"USD","amount":200})
```

And the expected would be:

```sql
insert into "recharges" ("value") values ('("USD",200)')
-- or
insert into "recharges" ("value") values (ROW('USD',200))
```

**Comment by elhigu** [comment]
You cannot use .toQuery() or toString() when you are figuring out how knex deals with stuff. toSQL() and toSQL().toNative() will show you what is sent to db driver (more or less). 

(because of this I've been many times hoping to completely remove toQuery() and toString() methods from knex)

**Comment by elhigu** [comment]
So please check if pg driver supports those.

**Comment by dgadelha** [comment]
Hello,

Now I was able to understand your point about why pg driver should support it, not Knex.

I'm really sorry for my lack of knowledge about which function to use to detail how Knex would deal with stuff.

Kind of agree with you about toQuery, maybe start with a depreciation?

Thanks a lot!

**Comment by elhigu** [comment]
toString is kind of useful in some cases when one needs to copy paste queties to sql IDE or command line client. In most of the cases it works just fine, but one still has to remember that it is not the same thing that knex does internally. That was the reson why I havent pushed deprecating it forwards.
