### ISSUE TITLE
Set charset and collation for the connection

### ISSUE THREAD

**Issue by Buzut** [tgriesser/knex#3124]
# Environment

Knex version: 0.16.3
Database + version: MariaDB 10.1.38
OS: Ubuntu 18.04

# Bug

There is apparently no way to set the connection charset and collation. For instance, with the mysql driver, `charset: 'utf8mb4_unicode_ci'` allows to define what needs to be used.

Adding this in the `connection` object has no impact. I've also tried `knex.raw('SET NAMES utf8mb4')` but it doesn't seem to have any effect either.

Hence, all emojis end up like "?" in the database and selecting the rows that contain them renders the same.

I've tried with the mysql driver and it works well. There's just a missing param.

**Comment by kibertoad** [comment]
@Buzut Shouldn't be happening. You can in the sourcecode the following:

```
  this.connectionSettings = cloneDeep(config.connection || {});
<...>
    return new Promise((resolver, rejecter) => {
      const connection = this.driver.createConnection(this.connectionSettings);
```

So knex literally is passing entire `connection` object to the driver when establishing connection. Please investigate further or provide a complete reproduction.

**Comment by Buzut** [comment]
Indeed, my bad. I had set the DB to the old utf8 charset 🤦🏻‍♂️
