### ISSUE TITLE
How to perform batch updates with INSERT IGNORE?

### ISSUE THREAD

**Issue by twigs67** [tgriesser/knex#3126]
This isn't a bug, but a question. I'm trying to perform a bulk insert, but use INSERT IGNORE, which means I have to do a raw query. I have the following:

```
 let values = [[1,2,3],[4,5,6]]; 
  let stm = 'INSERT IGNORE INTO pm_reviews ' +
            `(${inserts}) VALUES${valueStatement};`;
          console.log(stm)
          await db.raw(stm, values);
```

The SQL statement comes out as:
```
INSERT IGNORE INTO pm_reviews (col1, col2, col3) VALUES(?,?,?),(?,?,?),(?,?,?);
```

I keep getting the error: "Expected 8 bindings, saw 96".

I'm guessing I'm not inserting the bindings (values) correctly, but I've tried a number of different ways. 

Any help would be appreciated.

**Comment by tuananh** [comment]
@twigs67 are you generating the `(?,?,?), (?,?,?)....` in the raw query ?

**Comment by twigs67** [comment]
> @twigs67 are you generating the `(?,?,?), (?,?,?)....` in the raw query ?

Yes, that’s what I did. I first identified the size of the insert and chunked it in order to be mindful of mysqls size limit. Although this worked well, was a pain. 

I’ve moved to TypeOrm since then for future projects. It’s much better and more efficient imo.

**Comment by elhigu** [comment]
> I’ve moved to TypeOrm since then for future projects. It’s much better and more efficient imo.

Good move (well I have no idea if type ORM is any good), IMO knex is too low level tool for application development. It is better suited as a base layer for higher level libraries that can handle DB references etc. better.

**Comment by tuananh** [comment]
> > @twigs67 are you generating the `(?,?,?), (?,?,?)....` in the raw query ?
> 
> Yes, that’s what I did. I first identified the size of the insert and chunked it in order to be mindful of mysqls size limit. Although this worked well, was a pain.
> 
> I’ve moved to TypeOrm since then for future projects. It’s much better and more efficient imo.

I see. Thanks.
