### ISSUE TITLE
Missing typeCast documentation

### ISSUE THREAD

**Issue by FabianTe** [tgriesser/knex#3127]
# Missing / erroneus documentation

I am missing documentation on the property `Config.typeCast` that is being mentioned here: https://github.com/tgriesser/knex/issues/1240#issuecomment-195534490

Am I simply not finding it or does it not exist?

Is this feature production ready or shouldn't I use it since it is not well documented?

**Comment by elhigu** [comment]
It is mysql driver's option, doesn't have anything to do with knex. Connection object is passed pretty much directly to underlying driver, so knex will not document those options.
