### ISSUE TITLE
rollback all running in wrong order

### ISSUE THREAD

**Issue by ctrimble** [tgriesser/knex#3131]
# Environment

Knex version: 0.16.4-next2
Database + version: Aurora PostgreSQL
OS:

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do

We ran `knex.migrate.rollback(migrationsConfig, true)` in an effort to rollback a set of legacy migration files.  We expected this to execute the scripts in reverse chronological order, so that it would have the same effect as repeated calls to `knex.migrate.rollback(migrationsConfig)`.  Instead, it appears to be calling down on the migration files in chronological order.  This caused our rollback to fail.  As a workaround, we made repeated calls to rollback, without the `all` flag, and this worked.

2. Error message

migration failed with error: drop table if exists "client" - cannot drop table client because other objects depend on it

**Comment by filbertteo** [comment]
I encountered the same issue too.

**Comment by kibertoad** [comment]
0.16.6 is out which should address this problem. Please reopen the issue if you are still experiencing the problem after update.
