### ISSUE TITLE
oracledb returning numbers as strings

### ISSUE THREAD

**Issue by wickedest** [tgriesser/knex#3134]
# Environment

Knex version: 0.15.2
Database + version: Oracle 12
Driver: oracledb 
OS: Linux

tag: @atiertant 

# Bug

1. I would expect that values returned from an insert would broadly reflect the schema.  E.g. if my table has an integer field ID, then when returning "ID", I would expect an integer value.

2. There is no error message.

3. Sample code demonstrating the problem

```js
const connection = require('knex')({
	client: 'oracledb',
	connection: {
		user: process.env.DBIT_ORACLE_USER,
		password: process.env.DBIT_ORACLE_PASSWORD,
		connectString: process.env.DBIT_ORACLE_CONNECTION
	}
});

(async () => {
	await connection.schema.dropTableIfExists('DBIT_USER');

	await connection.schema.createTable('DBIT_USER', (table) => {
		table.integer('ID').primary().notNullable();
		table.string('NAME', 30);
	});

	await connection('DBIT_USER')
		.insert([{ ID: 1, NAME: 'tom' }])
		.returning([ 'ID', 'NAME' ])
		.then((results) => {
			// Note that results is: [ { ID: '1', NAME: 'tom' } ]
			// expected: [ { ID: 1, NAME: 'tom' } ]
			console.log(results);
			process.exit(0);
		})
		.catch(console.error);
})();
```

It might be in [this code](https://github.com/tgriesser/knex/blob/master/src/dialects/oracledb/index.js#L64-L72).  But, I'm not sure what `ReturningHelper` is supposed to do (not much afaik).  The issue appears to be that the return type is always `this.driver.STRING`, regardless of type.  The same code works for mssql.

**Comment by atiertant** [comment]
the problem is knex don't know the row type and oracledb driver need a type, string is the default value.... 
see https://oracle.github.io/node-oracledb/doc/api.html#executebindParams
you can try ask oracle for a `this.driver.AUTO` feature or use `parseInt()`

**Comment by elhigu** [comment]
Not knex’s responsibility.
