### ISSUE TITLE
"Incorrect string value" when adding a row, but can easily add the same row manually

### ISSUE THREAD

**Issue by maximedupre** [tgriesser/knex#3135]
# Environment

Knex version: `0.16.3`
Database + version: MySQL `5.7.18`
OS: macOS Mojave `10.14.2`

@smorey2 

# Bug

I'm trying to insert a row with the string "kické-accent.wav".

My table uses the "latin1_swedish_ci" collation and that seems juste fine, as I am able to insert the row without a problem using the MySQL Workbench.

However, when attempting to create the row with `knex`, I get the following error: 

    Error: Incorrect string value: '\xCC\x81-acc...' for column 'name' at row 1
          at Function.raw (.../node_modules/knex/lib/util/make-knex.js:46:30

The code that inserts the row looks like this:

    await trx.raw('INSERT INTO files SET ?', [{ extension: 'wav', name: 'kické-accent.wav', user_id: 3706 }]);

What is going on under the hood that prevents me from inserting a row just like I would do manually using the MySQL Workbench?

Cheers!

**Comment by kibertoad** [comment]
@maximedupre Could you try doing same insert by using Node.js MySQL driver directly without knex? I suspect that driver is converting UTF to ASCII behind the scenes and that generates incorrect values, but would be nice to exclude knex as a suspect.

**Comment by elhigu** [comment]
You cannot pass row like that to RAW. Knex cannot know what to do to that javascript object.

I suppose you are trying to do
```
await trx('files').insert({ extension: 'wav', name: 'kické-accent.wav', user_id: 3706 });
```

**Comment by maximedupre** [comment]
@kibertoad You are right, the problem occurs directly with the MySQL driver. I'll file an issue over there.

@elhigu Well it might be a coincidence that it's working, but I have this code at many places in my app and have no problems. I think that Knex does not know what to do to that js object, but the mysql driver does.

Thanks for both of your answers.

**Comment by elhigu** [comment]
@maximedupre yep, ypu are right looks like it happens because mysql escaping actually escapes object to `key1 = value1, key2 = value2` type of string. https://runkit.com/embed/2r5t4a4pu6i0

If we change mysql2 driver to use prepared statements instead of escaped strings, that code might break though (it has been requested while ago and should be more efficient and secure).

**Comment by kibertoad** [comment]
@elhigu Considering that Node 6 deprecation is right near the corner and we should start thinking about 0.17 already, I would suggest going for it.

**Comment by elhigu** [comment]
Are we in hurry with that? Is there some breaking changes in queue that we would really like to get out? We can just naturally drop node 6 support when we release first breaking changes after 6 reached end of line. I don't think we need to create 0.17 just for dropping node 6.

**Comment by kibertoad** [comment]
@elhigu Main reason why I'm eager to drop Node 6 ASAP is because it would allow us to start usiong async/await in tests :D
