### ISSUE TITLE
shielded slashes

### ISSUE THREAD

**Issue by Trahtenberg** [tgriesser/knex#3150]
Hello! 
I have JSON in the cell. I request data selection and get shielded slashes. How to disable shielding? I need to get the data in the form in which they are stored in the table.

```
let result = new Promise(function (getRes,getErr) {
            knex.from('configs')
            .select('*')
            .where({id:id_config})
                .then((ans) => {
                    getRes(ans);
                }).catch((err) => { getErr(err) })
                .finally(() => {
                    knex.destroy();
                });
        });

        return await result;
```

**Comment by elhigu** [comment]
I have no idea what are shielded slashes, but anyways you should check your db driver docs how to get the data out. Knex doesn’t modify values that driver returns. 

Closing as this seems to be knex usage issue and should be asked in gitter or stackoverflow.

**Comment by Trahtenberg** [comment]
query return this:

`{"selector":"a[class=\\"xf-product-title__link js-product__title\\"]","site":"https:\\/\\/www.ya.ru\\/catalog\\/kartinki\\/nasha/"}`

but need:

`{"selector":"a[class=\"xf-product-title__link js-product__title\"]","site":"https://www.ya.ru/catalog/kartinki/nasha/"}`

**Comment by elhigu** [comment]
Happens because js strings always require double backslashes for representing backslash. So for example is string literal ’\\foo\\’ is written to file or printed with console.log it will output just \foo\ without any doubles.
