### ISSUE TITLE
unable to alias in update

### ISSUE THREAD

**Issue by ctkcoding** [tgriesser/knex#3151]
I am unable to find a way to alias a column name. I want to do this
```
db('user'+user_id).where({list_id: list_id}).update(column, new_value)
```
where column is a passed in value. However knex thinks I want to update a column named "column" and while I saw a similar issue (#83) from 2013, the "solution" is crazy unwieldy

**Comment by pupudu** [comment]
Hi @ctkcoding 
I am doing something similar in a project I am working on. If I understand your question correctly, you can do this:
```js
const columnName = "my_table_column";
const newValue = 123;
db('user'+user_id).where({list_id: list_id}).update({
   [columnName]: newValue
})
```
The trick is to use `[]` brackets around the object property name.

**Comment by elhigu** [comment]
I have no idea what either of you are trying to do. Please tell what kind of SQL you are trying to make knex to generate. 

Issue #83 refers to SQL languages alias feature, which allows one to have different names for SQL identifiers... If you are just tying to pass column name in javascript variable, it works just like this:

```

// looks like you have separate table for each user, which is SQL antipattern
const userTableName = 'user'+user_id;
const updateColumnName = 'first_name';
db(userTableName).where({list_id: list_id}).update({updateColumnName: new_value}).then(res => {
  console.log('Update was success!');
});
```

> The trick is to use [] brackets around the object property name.

Having brackets around property name just does make string conversion from array to column name string, which sounds like some kind of hack to make something to work by accident when using knex with mssql server (mssql uses brackets instead of quotes).

**Comment by pupudu** [comment]
@elhigu The [] brackets have nothing to do with knex or any sql adapters. That's plain javascript, allowing us to use dynamic values as object property keys.  Not sure why you call it as some hack.

The question is about how to use aliases(probably not the most correct terminology) dynamically. And that is what I answered. 

```js
const dynamicColumnName = "streetAddress"
// then inside update...
.update({
  [dynamicColumnName]: "Bristol Road" // gives { streetAddress: "Bristol Road" }
})
```
Being a maintainer, you surely know that the same can be achived using named parameters. `:columnName: = :columnValue`

**Comment by elhigu** [comment]
>@elhigu The [] brackets have nothing to do with knex or any sql adapters. That's plain javascript, allowing us to use dynamic values as object property keys. Not sure why you call it as some hack.

@pupudu wow, sorry about that. I cannot believe that how I've been able to code javascript over 10 years without knowing that :D 

And looks like I had another brainfart there in my post mixing object syntax, when I was supposed to use the update syntax of the OP...

**Comment by pupudu** [comment]
> I cannot believe that how I've been able to code javascript over 10 years without knowing that :D

@elhigu hahaha not sure if you are trolling or not. Anyways I was just trying to help the person who asked this question. All hail knexJs

**Comment by elhigu** [comment]
> @elhigu hahaha not sure if you are trolling or not. Anyways I was just trying to help the person who asked this question.

Sadly no trolling 🙈
