### ISSUE TITLE
How to use knex.js and integrate functionalities of model tree structures with nested sets

### ISSUE THREAD

**Issue by jpsepulvedaf** [tgriesser/knex#3152]
How to use knex.js and integrate functionalities of model tree structures with nested sets, like for example "Sequelize" with its library "[sequelize-nested-set](https://www.npmjs.com/package/sequelize-nested-set)". Maybe there is a library that solves this problem of records tree, and that it is used together with "knex.js",
Any suggestions?

**Comment by elhigu** [comment]
As far as I know there is no tool like that, if anyone know feel free to comment here. This seems to be out of scope for knex issue tracker so closing.
