### ISSUE TITLE
Print query with bindings

### ISSUE THREAD

**Issue by petermilan** [tgriesser/knex#3153]
# Feature discussion / request
From time to time, when debugging bigger complex queries, I am grabbing output from knex and using it in adminer directly. The debug output will print the query without rendered bindings.
it would be nice to see the output of query directly.

**Comment by petermilan** [comment]
For a workarround I tried to do update the toSQL function in 
`knex/lib/query/compiler.js`

where before the query is returned I am injecting just quickly built query into the response:
```
    let builtSql = query.sql;
    query.bindings.forEach((binding) => {
      const bindingAsInt = parseInt(binding, 10);
      if (!bindingAsInt) {
        binding = '\'' + binding + '\'';
      }
      builtSql = builtSql.replace('?', binding);
    });
    query['>>> BUILT_SQL >>>'] = builtSql;
````

which will generate output like this : 
```
{ method: 'select',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [ 46341 ],
  __knexQueryUid: '5c0edec3-2619-49b2-a6f2-158699c43f8f',
  sql: 'select "users".* from "users" where "users"."id" in (?)',
  '>>> BUILT_SQL >>>': 'select "users".* from "users" where "users"."id" in (46341)' }
```
which can be easily used for debugging of query.

Would something like this make sense to be built in knex?

**Comment by elhigu** [comment]
.toQuery() and .toString() does interpolate queries to string with bindings in string format. However those doesn't work perfectly in some special cases.
