### ISSUE TITLE
Migration did not return a promise

### ISSUE THREAD

**Issue by DanrwAU** [tgriesser/knex#3165]
# Environment

Knex version: 0.16.5
Database + version: SQLite 3
OS: Ubuntu 18.04

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do
    
Migration file needs to be run on both new databses and databases where tables may already exist, using the example from the documentation results in an error about not returning a promise. 

Is this a use case for knex.createTableIfNotExists (if this still exists?)

This issue has been raised previous in #924 but the original posted never seemed to solve it and it wasn't answered

2. Error message

    migration 20190322204646_create_capcodes_table.js did not return a promise

3. Reduced test code, for example in https://npm.runkit.com/knex or if it needs real
   database connection to mysql or postgresql, then single file example which initializes
   needed data and demonstrates the problem.

Example Migration file:

```
exports.up = function(db, Promise) {
   db.schema.hasTable('capcodes').then(function(exists) {
    if (!exists) {
     return db.schema.createTable('capcodes', table => {
            table.integer('id').primary().notNullable();
            table.string('address', [255]).notNullable();
            table.text('alias').notNullable();
            table.text('agency');
            table.text('icon');
            table.text('color');
            table.text('pluginconf')
            table.integer('ignore').defaultTo(0);
            table.unique(['id', 'address'], 'cc_pk_idx');
      })
      .then((result) =>{

      })
      .catch((err) => {
          
      })
    } else {
      return
    }
  })
}

exports.down = function(db, Promise) {
  
};
```

**Comment by elhigu** [comment]
Your up/down methods are not returning promises.

**Comment by DanrwAU** [comment]
I may be being thick here, would you mind spending 30 seconds with an example of how to handle this? removing the .then and .catch resulting in this hard failing. 
As it is now it does work, just throws an error at the console. 

Thanks :)

**Comment by elhigu** [comment]
exports.up = function(db, Promise) {
  return db.schema...
}

Like that. Sorry i dont like coding with mobile phone so im not gonna write longer example :)

**Comment by kibertoad** [comment]
Or, a much simpler solution - make both functions async.

**Comment by kenmorechalfant** [comment]
> Your up/down methods are not returning promises. They should, otherwise knex doesnt know when your migration finishes or if it fails

Am I crazy or does the docs not mention this? I feel like I'm missing something because the docs don't really explain things well.

**Comment by yumindeckard** [comment]
@elhigu if we use `knex migrate:make create_users_table`, the generated code does NOT have `Promise` as a second parameter.

It cost me 3 hours to figure it out that there should be a second parameter, `Promise`.

**Comment by kibertoad** [comment]
@yumindeckard That second parameter shouldn't be there, it is always going to be undefined. And not sure if returning promise is still needed, I think that was fixed. Which knex version are you using?

**Comment by elhigu** [comment]
> It cost me 3 hours to figure it out that there should be a second parameter, Promise and that I should return a Promise.

Good learning experience, in future debugging things like that gets a lot faster to be a matter of minutes. Though there is no reason to ever put that `Promise` parameter there if you are using >= node 6. 

If code generator didn't generate the second parameter, you are probably using new enough knex, that it is never even passed to the migration... At least you are not using it in your up function for anything.

I'll be hiding this discussion as off topic.

**Comment by yumindeckard** [comment]
@elhigu It's `NOT` documented.

And if you use `knex migrate:make migration_name`, the generated code is like this:

```javascript
exports.up = function(knex) {
  
};

exports.down = function(knex) {
  
};

```

**Comment by elhigu** [comment]
Yep AFAIK it is not documented that migration should return promise / thenable. I don't know how you would be supposed to know that. I'll be happy to merge PR for updating those docs with better descriptions how to write migration files.

Also you don't have to use async. It just makes writing migrations easier since async functions implicitly returns a promise. You can also just return schema builder instance from it and it will work as well.

**Comment by TodorTotev** [comment]
Update @ the documentation would be great. Had this problem today and if it wasn't for this issue being posted here I would have spent even more time solving it.

If @elhigu didn't already update the docs, I can do it.

**Comment by newhouse** [comment]
> It cost me 3 hours to figure it out that there should be a second parameter, Promise and that I should return a Promise.

That 2nd parameter that's commonly named `Promise` is definitely not required in any not-really-old version of Node, and its absence from your `up`/`down` method signatures would not have any impact. The requirement is/was just that you return a `Promise` so that the code can wait until it's resolved to know that the work of the migration you wrote is complete.

 > How did I know I need to use `async` ???

You don't _have_ to use `async`, but it was suggested here because: if you do, then the function will implicitly return a `Promise`-like ("then-able") thing, no matter what you actually write your code to be inside said function.

`Promises`, and `async` functions can be a little tough to grasp, but this is simply "how javascript works"™️.

**Comment by elhigu** [comment]
@todortotev PRs for making documentation more clear are always welcome.
