### ISSUE TITLE
Possible SQL Injection issue when using strings with periods as parameter binding.

### ISSUE THREAD

**Issue by ulysset** [tgriesser/knex#3175]
Hi!
First, thanks a lot for this library, it is very useful.
# Environment
Knex version: 0.16.3
Database + version: PSQL 10.4
OS: MacOS 10.14.4

# Bug
1. I'm trying to use knex.raw to bind parameters to the raw query.
I would expect the parameter `"Russian Federation & U.S.S.R."` to be used in the final query as `"Russian Federation & U.S.S.R."` but the final query is rendered like this : `"Russian Federation & U"."S"."S"."R".""`

2. Error message:
```bash
{ method: 'select',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings:
   [ 'Russian Federation & U.S.S.R.',
     1000000,
     'Russian Federation & U.S.S.R.' ],
  __knexQueryUid: 'a7039b67-d1e9-4835-addc-f32e7fedbbd7',
  sql:
   'select "year", ROUND(AVG(CASE WHEN "group_name" = ? THEN "co2_per_capita" ELSE 0 END * ?)::numeric, 4)  "Russian Federation & U"."S"."S"."R"."" from "table_name" where "group_name" in (?) group by "year" order by "year" asc' }
{ error: syntax error at or near "."
.........
```

My code :
```javascript
knex.raw(
  'ROUND(AVG(CASE WHEN "group_name" = :groupName THEN "co2_per_capita" ELSE 0 END * :coef)::numeric, 4)  :groupName:',
    {
        groupName,
         coef: unit ? cO2Multiplier("MtCO2", unit) : 1
         // ^^^ Ignore this line ^^^
    }
)
```

**Comment by elhigu** [comment]
You are using it as identifier, `:groupName:` notice colons on both sides of the replacement. So naturally it is rendered as identifier and not as value binding.

**Comment by ulysset** [comment]
Thanks for the quick answer @elhigu !
Actually, I want it to be an identifier and not as value binding. 
The `:groupName:` is an `AS` clause and requires double quotes in psql.
```SQL
select
    "year",
    ROUND(AVG(CASE WHEN "group_name" = 'Russian Federation & U.S.S.R.' THEN "co2_per_capita" ELSE 0 END * 100000)::numeric, 4)
    /* Here is the alias with the identifier */
    AS "Russian Federation & U.S.S.R."
from "table_name"
where "group_name" in ('Russian Federation & U.S.S.R.')
group by "year"
order by "year" asc
```
This query work when I run it manually :
![image](https://user-images.githubusercontent.com/13087992/56979480-391e9b00-6b7a-11e9-9a73-533fb75c437e.png)

I added the AS clause word to the knex.raw. Here is the rendered SQL from Knex (basically the same) :
```bash
{ method: 'select',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings:
   [ 'Russian Federation & U.S.S.R.',
     1000000,
     'Russian Federation & U.S.S.R.' ],
  __knexQueryUid: 'd0f15243-b038-46e9-a3ba-4040f540697d',
  sql:
   'select "year", ROUND(AVG(CASE WHEN "group_name" = ? THEN "co2_per_capita" ELSE 0 END * ? )::numeric, 4) AS "Russian Federation & U"."S"."S"."R"."" from "HISTORICAL_CO2_EMISSIONS_PER_CAPITA_co2_per_capita_prod" where "group_name" in (?) group by "year" order by "year" asc' }
```
I guess it's a bad practice practice to use spaces and periods in a column name ¯\_(ツ)_/¯

**Comment by elhigu** [comment]
Yep identifiers with periods are not supported by knex (because of identifier parsing and automatic quoting) and spaces... I'm not sure, but I wouldn't try it :)

**Comment by elhigu** [comment]
And passing user defined value as identifier without special validation is an sql injection hole indeed.

**Comment by ulysset** [comment]
Thanks @elhigu, it wasn't user-defined so I'll just remove the periods!
