### ISSUE TITLE
Fix the typescript definition for table.timestamps() (and maybe also update the docs)

### ISSUE THREAD

**Issue by CodyEakins** [tgriesser/knex#3179]
# Environment

Knex version: 0.16.5
Database + version: Postgres 11.2
OS: Windows 10, WSL and VSCode

# Bug

**Current Behavior:**
If you try to use the `options` argument of `table.timestamp()` in TypeScript, it raises a type error with the following message:
`Argument of type '{ useTz: boolean; }' is not assignable to parameter of type 'boolean | undefined'.`

**What is should do:**
According to the documentation for `table.timestamp()`, this function should allow a second argument to be passed to it called `options`, which is an `object` of configuration properties ([Reference 1: Knex.js Website](https://knexjs.org/#Schema-timestamp), [Reference 2: Knex Website Github](https://github.com/knex/documentation/blob/c903f99b8bb19d25f1714be7232d2a6ddcbe6a3d/sections/schema.js#L305)).

However, TypeScript currently thinks that the second argument should be a `boolean` called `standard` ([Reference: Knex Github](https://github.com/tgriesser/knex/blob/6a4fecfe7822442ee5c43d924958eadfe6e17a93/types/index.d.ts#L1062)). This is strange and undocumented.

**Test Code:**
```ts
const knex = require('knex')({
  client: 'pg',
  connection: 'postgres:///knex_test'
});

async function main() {
  await knex.schema.createTable(
    'example',
    (table): void => {
      table.timestamp('created_at', { useTz: true }); // raises typescript error
    },
  );
  await knex.destroy();
}

main();
```
# Possible Fixes
This bug could be the result of a few things, but here is some recommended next steps:
- Check out `table.timestamp()`'s original function declaration; make sure there is support for the second argument
- Update the typescript definition to better match the function signature
- Update the docs to better match the function signature

This could also be a legacy feature, so in that case, update the docs to reflect the current function signature, explaining the `standard` argument.

**Comment by lorefnon** [comment]
Seems like the type-definitions are dialect agnostic, where as the signature of timestamp function varies across dialects [<sup>[1]</sup> ](https://github.com/tgriesser/knex/blob/0115f933ca09b20bf457d1e47e3e06a9e26b0ae1/src/dialects/mysql/schema/columncompiler.js#L86) [<sup>[2]</sup>](https://github.com/tgriesser/knex/blob/0115f933ca09b20bf457d1e47e3e06a9e26b0ae1/src/dialects/postgres/schema/columncompiler.js#L77). 

What is the ideal thing to do here ? Are there many cases where signatures differ across dialects ?

**Comment by elhigu** [comment]
Object format is official way to go. Old parameter is left there only to not brake backwards compatibility (and all old migration files using the parameter).

**Comment by lorefnon** [comment]
This issue can be closed as it was addressed by https://github.com/tgriesser/knex/pull/3181.
