### ISSUE TITLE
Fix the name value in the knex_migrations table when using custom migration sources

### ISSUE THREAD

**Issue by CodyEakins** [tgriesser/knex#3184]
# Environment

Knex version: 0.16.5
Database + version: Postgres 11.2
OS: Windows 10, with WSL and VSCode

# Bug

**Current Behavior:**
When using a custom migration source in `knex.migrate.latest()`, migration names are incorrectly saved to the database with their relative path to the migrations directory. 

For example, if I have migration named `20190503112250_initial.ts`, it should be saved to the `knex_migrations` table's `name` column as `20190503112250_initial.ts`. However, in this case, it saves the name as `./20190503112250_initial.ts` (note the extra `./`).

**Error Message:**
Because of the difference in names, this leads to errors when running future migrations:
`Error: The migration directory is corrupt, the following files are missing: ./20190503112250_initial.ts`

Knex thinks the file is missing in my environment because the name is being resolved incorrectly.

**Test Code:**
Here is the custom migration source (very common for webpack bundling):
```ts
class WebpackMigrationSource {
  public migrationContext: __WebpackModuleApi.RequireContext;

  public constructor(migrationContext: __WebpackModuleApi.RequireContext) {
    this.migrationContext = migrationContext;
  }

  public getMigrations(): Promise<string[]> {
    return Promise.resolve(this.migrationContext.keys().sort());
  }

  /* eslint-disable-next-line class-methods-use-this */
  public getMigrationName(migration: string): string {
    return migration;
  }

  public getMigration(migration: string): object {
    return this.migrationContext(migration);
  }
}

export default WebpackMigrationSource;
```
And here is the call-site/test: 
```ts
import knex from 'knex';

import WebpackMigrationSource from './WebpackMigrationSource';

// write your proper test environment's config here
const config = {
  client: 'pg',
  connection: 'postgres:///knex_test',
};

const knexInstance = knex(config);

const main = async (): Promise<void> => {
  await knexInstance.migrate.latest({
    // @ts-ignore: this type error is fixed in knex's master branch
    migrationSource: new WebpackMigrationSource(require.context(
      './migrations',
      false,
      /.ts$/,
    )),
  });
};

main();
```

Then check out the name values in your `knex_migrations` table; they should have the `./`.

---

There is a possibility that this issue could also be caused by how my `WebpackMigrationSource.ts` file is structured. Let me know if that is the case, and I'll close the issue.

**Comment by CodyEakins** [comment]
It turns out that this was an issue with the `WebpackMigrationSource.ts`; here is the updated, working custom migration:
```ts
import path from 'path';

class WebpackMigrationSource {
  public migrationContext: __WebpackModuleApi.RequireContext;

  public constructor(migrationContext: __WebpackModuleApi.RequireContext) {
    this.migrationContext = migrationContext;
  }

  public getMigrations(): Promise<string[]> {
    return Promise.resolve(this.migrationContext.keys().sort());
  }

  /* eslint-disable-next-line class-methods-use-this */
  public getMigrationName(migration: string): string {
    return path.parse(migration).base;
  }

  public getMigration(migration: string): object {
    return this.migrationContext(migration);
  }
}

export default WebpackMigrationSource;
```
Note the added `path.parse()` to `getNigrationName()`...

@elhigu or @lorefnon - Maybe you can update the custom migration example in the docs to account for this difference in name resolution? I don't want others running into the same problem by following the original example.

**Comment by elhigu** [comment]
@CodyEakins thanks for the info!

**Comment by elhigu** [comment]
Added issue to documentation repo
