### ISSUE TITLE
Breaking change in 0.16.6 (when used with typescript)

### ISSUE THREAD

**Issue by Xiphe** [tgriesser/knex#3193]
# Environment

Knex version: 0.16.5
Database + version: sqlite3@
OS: macos

# Bug

1. After moving to `v0.16.6` when compiling my application with typescript I get the following error

2. `Generic type 'Knex<TRecord, TResult>' requires 2 type argument(s)`

3. 
```ts
// client.ts
import knex from 'knex';

export default class Client {
  db: knex;
  constructor(db: knex) {
    this.db = db;
  }
}
```

---

I understand that the typescript definitions might not be your primary API. But  https://github.com/tgriesser/knex/pull/3168 is probably causing ts-errors in any project that uses typescript and knex. And I therefore would consider it to be a breaking change.

I would really like to either see this change become optional or to have a migration guideline so that I can continue to use the lastest version of knex.

Thanks a lot for your work, also on #3168. Really appreciated!

**Comment by loxs** [comment]
I will also reference my comment on the pull request itself: https://github.com/tgriesser/knex/pull/3168#issuecomment-491749022

**Comment by felixmosh** [comment]
and mine :]
https://github.com/tgriesser/knex/pull/3168#issuecomment-491756537

**Comment by kibertoad** [comment]
Can you try 0.16.7?

**Comment by Xiphe** [comment]
Hey @kibertoad 
Thanks for the fast response.
In my case using `v0.16.7` does not compile in TS without problems.

```
[...]/KnexContent.ts (560,37): Property 'id' does not exist on type 'any[]'.
[...]/KnexContent.ts (560,71): Property 'data' does not exist on type 'any[]'.
[...]/KnexContent.ts (563,9): Property 'listVersions' in type 'KnexContent' is not assignable to the same property in base type 'ContentAdapter'.
  Type '(model: Model, id: string) => Promise<any[] | null>' is not assignable to type '(model: Model, id: string) => Promise<(Item & { rev: number; latest: boolean; published_rev: boolean; latest_rev: number; author_name: string; date: string; } & { published: boolean; })[]>'.
    Type 'Promise<any[] | null>' is not assignable to type 'Promise<(Item & { rev: number; latest: boolean; published_rev: boolean; latest_rev: number; author_name: string; date: string; } & { published: boolean; })[]>'.
      Type 'any[] | null' is not assignable to type '(Item & { rev: number; latest: boolean; published_rev: boolean; latest_rev: number; author_name: string; date: string; } & { published: boolean; })[]'.
        Type 'null' is not assignable to type '(Item & { rev: number; latest: boolean; published_rev: boolean; latest_rev: number; author_name: string; date: string; } & { published: boolean; })[]'.
```

This is not the same error as in `v0.16.6` but still does not allow "just installing the new version"

**Comment by Xiphe** [comment]
I suspect that the idea behind #3168 is pretty cool in regards of type-safety. And would really like to understand how to use it but was not able to wrap my head around it.

**Comment by kibertoad** [comment]
@Xiphe I think you are trying to use array as a non-array, hence the problem. Are you on gitter? We could try grilling into problem together. And yeah, looks like it should be 0.17 instead, will republish.

**Comment by felixmosh** [comment]
> Can you try 0.16.7?

I used this version, and all of Knex related stuff were broken.

**Comment by kibertoad** [comment]
@felixmosh Will unpublish ASAP.

**Comment by kibertoad** [comment]
0.16.6 and 0.16.7 were unpublished. I will rerelease current master as 0.17.0-next so that we could investigate incompatibilities and prepare migration guide.

**Comment by loxs** [comment]
I am also willing to experiment with @next when I have some time.

**Comment by felixmosh** [comment]
> @felixmosh Will unpublish ASAP.

Thank you!

**Comment by felixmosh** [comment]
> 0.17.0-next

`npm i knex@next` installs knex@0.16.4-next2, this version not includes this PR.

**Comment by kibertoad** [comment]
It wasn't released yet, give me an hour or so :)

**Comment by kibertoad** [comment]
0.17.0-next is now out. Suggestions, problem reproductions and PRs most welcome!

**Comment by kibertoad** [comment]
0.17.0-next* releases seem to have solved the problem.

**Comment by kibertoad** [comment]
Final version of 0.17.0 is out.

**Comment by felixmosh** [comment]
@kibertoad , @Xiphe Thank you for this feature, this is awesome and it works perfectly !! 🙏🏼

**Comment by kibertoad** [comment]
@lorefnon is the hero here :)

**Comment by lorefnon** [comment]
Thanks a lot for your patience and helping out with your feedback. :)

**Comment by Xiphe** [comment]
I only wrote the issue and then stopped being involved. Thanks everyone for the awesome work, can't wait to try it out!

**Comment by felixmosh** [comment]
With knex v-0.17.5 there is an issue with `.first` operator.

```typescript
const prettyUrl = await db('seo')
  .columns('contentId', 'type', 'url', 'prevUrl')
  .where({ url })
  .orWhere({ prevUrl: url });
  .first();

prettyUrl.shouldRedirect = url === prettyUrl.prevUrl;
delete prettyUrl.prevUrl;
```
![image](https://user-images.githubusercontent.com/9304194/59178690-617dba00-8b68-11e9-9078-daa9dd532b72.png)

**Comment by kibertoad** [comment]
@felixmosh Is it any better in 0.18.0-next1?

**Comment by felixmosh** [comment]
@kibertoad yes it still happens but now with different error, 
![image](https://user-images.githubusercontent.com/9304194/59743765-b365c480-9279-11e9-92a9-a07305f09a32.png)

**Comment by kibertoad** [comment]
@lorefnon Any ideas?

**Comment by lorefnon** [comment]
I am unable to reproduce this. Can you please post your tsconfig.json and the full error that tsc gives you ?

**Comment by felixmosh** [comment]
Actually `knex@0.18.0-next2` do solves the issue.

Did you removed blueBird promises from knex? at this version all `.map`/ `.reduce` statements are red
```
Error:(118, 6) TS2339: Property 'map' does not exist on type 'QueryBuilder<any, any>'.
```

**Comment by lorefnon** [comment]
Yeah, there is a parallel ongoing effort to remove bluebird.

**Comment by kibertoad** [comment]
@felixmosh Can't you just call map on result array after awaiting the results?

**Comment by felixmosh** [comment]
Yeah I can, but this will be breaking changes :]

**Comment by loxs** [comment]
@felixmosh  Where is the discussion about this ongoing effort? I'd like to at least help with testing (and ensure my systems don't fail). Please keep me in the loop if possible.
