### ISSUE TITLE
npm showing version 0.16.5

### ISSUE THREAD

**Issue by capaj** [tgriesser/knex#3196]
https://www.npmjs.com/package/knex

shows 0.16.5 as latest version

![image](https://user-images.githubusercontent.com/1305378/57682429-2011f180-7632-11e9-8e37-92a7de410008.png)

Seems like NPM lost the 0.16.7 version that was published 2 days ago.
Not sure how, but it happened. Can someone republish it please? We can downgrade back 0.16.5 in the meantime, but it would be nice to have the latest on NPM.

**Comment by kibertoad** [comment]
It was unpublished due to breaking changes. You can use 0.17.0-next if you don't use TS or if current versionof typings work fine for you

**Comment by capaj** [comment]
thanks for the explainer. Will close this and use 0.17.0-next  for now.
