### ISSUE TITLE
0.16.7 not appearing on npm

### ISSUE THREAD

**Issue by kanolato** [tgriesser/knex#3198]
# Environment

Knex version:
Database + version:
OS:

Select applicable tempalate from below.
If issue is about oracledb support tag @ atiertant. For MSSql tag @ smorey2 .
Rest of dialects doesn't need tags.

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do
Yesterday I installed the version 0.16.7, and today one of my colleagues tried to do the same and the package does not exist anymore :(. 
It also doesnt show up on the version tab in npm: https://www.npmjs.com/package/knex?activeTab=versions
2. Error message
```
npm ERR! code E404
npm ERR! 404 Not Found: knex@0.16.7
```

3. Reduced test code, for example in https://npm.runkit.com/knex or if it needs real
   database connection to mysql or postgresql, then single file example which initializes
   needed data and demonstrates the problem.

# Feature discussion / request

1. Explain what is your use case

2. Explain what kind of feature would support this

3. Give some API proposal, how the feature should work

# Missing / erroneus documentation

Send issue to documentation repo, or fix it and send PR https://github.com/knex/documentation

# Questions about how to use knex

Github issues are for knex development. Please send questions how to use knex to
stackoverflow or ask about it in gitter chat.

**Comment by kibertoad** [comment]
0.16.6 and 0.16.7 were unpublished due to breaking changes in typings. If you are brave or don't use Typescript, you can switch to 0.17.0-next, which is the same as 0.16.7.

**Comment by kibertoad** [comment]
Final version of 0.17.0 is out.
