### ISSUE TITLE
Does Knex support Cloud SQL connection with node.js

### ISSUE THREAD

**Issue by jigneshk5** [tgriesser/knex#3199]
I'm getting error on the following line:
```
if (process.env.INSTANCE_CONNECTION_NAME && process.env.NODE_ENV === 'production') {
  config.socketPath = `/cloudsql/${process.env.INSTANCE_CONNECTION_NAME}`;
}
```
which is a part of documentation provided by Google for making Cloud sql connection to node JS as attached below:
```
const config = {
  user: process.env.SQL_USER,
  password: process.env.SQL_PASSWORD,
  database: process.env.SQL_DATABASE
};

if (process.env.INSTANCE_CONNECTION_NAME && process.env.NODE_ENV === 'production') {
  config.socketPath = `/cloudsql/${process.env.INSTANCE_CONNECTION_NAME}`;
}

// Connect to the database
const knex = Knex({
  client: 'mysql',
  connection: config
});
```
I want to confirm if knex supported config objects with socket path given above. It's in alpha-version mentioned by google so I want to know if knex can make sql connection with this database or not?

**Comment by kibertoad** [comment]
It's not a knex parameter per se. All knex is doing with it is passing to a driver, so if the driver that you are using supports it, it will work.

**Comment by derhuerst** [comment]
FYI: The `pg` (PostgreSQL) driver *does not* support it, as of knex `0.18.1`. You have to pass the the socket path as `host`. More info: https://github.com/brianc/node-postgres/issues/1617

**Comment by kibertoad** [comment]
@derhuerst Are you sure this is a `knex` and not `pg` issue? I remember we managed to get it working with Google Cloud SQL back in the day (I think we had to pass connection explicitly, though), so unless something got broken, should work.

**Comment by derhuerst** [comment]
I just tried to get it working in a Cloud Run instance. It dug into the Knex code base and logged the options passed to `pg`, and AFAIR they we wrong.
