### ISSUE TITLE
Feature Request - Join inside Where clause

### ISSUE THREAD

**Issue by MiOnim** [tgriesser/knex#3202]
Hey guys,

I am using Knex to generate SQL query from an expression tree. For example, if a tree looks like the following:
```
     AND
    /   \
  X     OR
        / \
      Y    Z
```
The query I need to generate should have the following in WHERE clause:
`WHERE (X) AND (Y OR Z)`

I wrote a recursive function to achieve this:
```
function parseTree(tree, query) {
  if (tree.item is Node) {
    buildQuery(query, tree.item);
  } else if (tree.item === 'AND') {
    query.andWhere(builder => {
      parseTree(tree.left, builder);
    }
    query.andWhere(builder => {
      parseTree(tree.right, builder);
    }
  } else if (tree.item === 'OR') {
    query.orWhere(builder => {
      parseTree(tree.left, builder);
    }
    query.orWhere(builder => {
      parseTree(tree.right, builder);
    }
  }
}
```
Inside the `buildQuery(...)` function, I have a JOIN statement.

Knex is removing the JOIN statements from the final query (probably because it is inside `andWhere`).

Is it possible to allow this behavior of adding JOINs to a query from inside `andWhere` and `orWhere`? This would be very helpful in situations like this.

**Comment by elhigu** [comment]
Please add simple sample sql of the query you are trying to build. Im sure it is possible to build with knex. I have no idea how you could have join inside of where unless you are using subqueries.

**Comment by elhigu** [comment]
Closes as usage question
