### ISSUE TITLE
npm does not reference 0.16.7 anymore (had to roll back to 0.16.5)

### ISSUE THREAD

**Issue by jeremychone** [tgriesser/knex#3203]
# Environment

Knex version: 0.16.7
Database + version: - 
OS: OSX

# Bug

There is an npm issue which it cannot find the 0.16.7 as of today at least. Few days ago, I updated to it, but now it says not found. I check the npm site, and the last version seems to have rolled back to 0.16.5. 
![image](https://user-images.githubusercontent.com/74671/57861445-76ef0680-77ab-11e9-8f25-b2c490de7b84.png)

**Comment by kibertoad** [comment]
See https://github.com/tgriesser/knex/issues/3198 :)
tl:dr -> breaking TypeScript changes, hence rereleased as 0.17.0-next

**Comment by jeremychone** [comment]
Thanks, 0.17.0-next worked.

**Comment by kibertoad** [comment]
Final version of 0.17.0 is out.
