### ISSUE TITLE
MySql decimal returns Number instead of String

### ISSUE THREAD

**Issue by olgeorge** [tgriesser/knex#3204]
# Environment

Knex version: 0.14.6
Database + version: MySql 5.7.12
OS: OSX

# Feature discussion / request

Don't convert decimal to Number automatically.

I have a decimal column with precision 8 and scale 8
```
await knex.schema.createTable("myTable", t => {
    t.engine("InnoDB");
    t.charset("utf8mb4");
    t.collate("utf8mb4_unicode_ci");
    t.bigIncrements();
    t.decimal('decimal', 8, 8);
});  
```

When I fetch the records decimal is converted to Number:

```
await knex("myTable").select(knex.raw('*'));
// returns {"id":1, "decimal":0.01}
```

I expect knex to return string, so that I can use Decimal.js to avoid floating-point operations. Converting decimal to Number automatically defeats the purpose of using decimal in the database layer, and it seems to me this should be the default behavior.

What's the reasoning behind this? Is there any way to turn this conversion off?

**Comment by wubzz** [comment]
Unlikely a knex issue. Knex returns response from driver. So the issue is probably in `mysql` / `mysql2` which ever driver you are using. They both seems to have config flags you can use to return strings instead of Numbers.

https://github.com/mysqljs/mysql
https://github.com/sidorares/node-mysql2/tree/master/documentation

`Knex({config})` passes config to the driver.

**Comment by elhigu** [comment]
Knex doesn't touch values that are returned from DB driver (except in some rare cases), so you need to setup mysql driver in a way that you get the data in wanted format.

**Comment by olgeorge** [comment]
Yes, thanks. To change that I had to either switch to `mysql2` or add:
```
const config = {
    client: 'mysql',
    connection: {
        database: process.env.DB_NAME,
        host: process.env.DB_HOST,
        user: process.env.DB_USER,
        password: process.env.DB_PASSWORD,
        timezone: "UTC",
        charset: 'utf8',
        supportBigNumbers: true, // this fixes it
        bigNumberStrings: true, // this fixes it
    },
    pool: {
        min: 0,
        max: 1,
    }
};
```

**Comment by transtone** [comment]
> Yes, thanks. To change that I had to either switch to `mysql2` or add:
> 
> ```
> const config = {
>     client: 'mysql',
>     connection: {
>         //...
>         supportBigNumbers: true, // this fixes it
>         bigNumberStrings: true, // this fixes it
>     },
> };
> ```

    `decimalNumbers: true,`
