### ISSUE TITLE
"colorette" dependency breaks browserify builds.

### ISSUE THREAD

**Issue by barissenkal** [tgriesser/knex#3216]
# Environment

Knex version: 0.16.5
Database + version: Not relevant for this issue.
OS: macOS, Safari (14607.2.6.1.1) and Chrome (76.0.3800.0)
**Edit:** Browserify version: 16.2.3

# Bug

**1. Explain what kind of behaviour you are getting and how you think it should do**

Having `colorette` as dependency breaks browserify builds. This includes your website at the moment. ![Screenshot](https://i.imgur.com/IhojfZG.png)

**2. Error message**

Error Message on your website:
`index.js:6 Uncaught TypeError: Cannot read property 'isTTY' of undefined`

~~Error message when using browserify:~~
**Edit:** Error message when browserify bundle runs inside a browser-like environment.
`Uncaught TypeError: Cannot read property 'isTTY' of undefined`

**3. Reduced test code, for example in https://npm.runkit.com/knex or if it needs real
   database connection to mysql or postgresql, then single file example which initializes
   needed data and demonstrates the problem.**

Not relevant for this issue.

**Comment by kibertoad** [comment]
Can you raise issue with colorette as well?

**Comment by barissenkal** [comment]
Sure. Created a [pull request](https://github.com/jorgebucaran/colorette/pull/36) on the colorette repo.

**Comment by kibertoad** [comment]
Fix released in 0.17.2.
