### ISSUE TITLE
How can I use UUID as a primary key in MySQL

### ISSUE THREAD

**Issue by MacgyverMartins** [tgriesser/knex#3217]
# Environment

Knex version: 0.16.5
Database + version: MySQL 5.7.19
OS: Mac OS

I create this migration:
```javascript
exports.up = function(knex, Promise) {
  return knex.schema.createTable('users', t => {
    t.uuid('id').primary()
    t.string('name');
};
```
But when insert a new user, I got this error message
`Field 'id' doesn't have a default value`
I think, it happens because I use MySQL instead of PostgreSQL. So I should put some `.defaultTo()`, but what value I put inside the function? Or, can I use uuid as primary keys in MySQL ?

**Comment by elhigu** [comment]
Closing as usage question. 

I don't know if it is possible to do with mysql, but if it is you need to give default value for 'id' column, like incremental is always adding sequential value to it. Maybe this works:

```
t.uuid('id').primary().defaultTo(knex.raw('UUID()'));
```

**Comment by MacgyverMartins** [comment]
@elhigu, Really, it is not possible to enter a default value for the UUID in Mysql. Even with `knex.raw('UUID()')`.

So I create these :
So, I created this "workaround" based on [this answer](https://stackoverflow.com/questions/36728899/knex-js-auto-update-trigger/48028011#48028011)
```javascript
exports.up = function(knex, Promise) {
  return knex.schema.createTable('users', t => {
    t.uuid('id').primary()
    t.string('name');
})
.then(() => knex.raw(onInsertTrigger('users')));
```
and into kinexfile I add this:
```javascript
  onInsertTrigger: table => `
  CREATE TRIGGER before_insert_${table}
  BEFORE INSERT ON ${table}
  FOR EACH ROW
  SET new.id = uuid();
  `
```
I don't know if it's a good solution, but it works.
Maybe can help other people

**Comment by DHFW** [comment]
`knex.raw('UUID()')` should be: `knex.raw('(UUID())')` (notice that `UUID()` is wrapped with `()`!

See this [article](https://mydevjourney.net/2020/03/14/knex-how-to-use-an-uuid-as-a-field-default-value-in-mysql/)

**Comment by erikshestopal** [comment]
@DHFW  Only possible on MySQL > 8.0.
