### ISSUE TITLE
.first() Doesn't Work on Insert

### ISSUE THREAD

**Issue by candyapplecorn** [tgriesser/knex#3218]
# Environment

Knex version: 0.16.5
Database + version: PostgreSQL 10.5 on x86_64-apple-darwin17.7.0, compiled by Apple LLVM version 9.1.0 (clang-902.0.39.2), 64-bit
OS: Mac/Apple

# Feature discussion / request
.first() returns the 1st item from a list of results. However it doesn't work on insert statements, _even though insert statements also return a list_

> 1. Explain what is your use case
calling .first() on insert statements

> 2. Explain what kind of feature would support this
making .first() work on insert statements

> 3. Give some API proposal, how the feature should work
making .first() work on insert statements

**Comment by elhigu** [comment]
It is not that straightforward... Inserts returns different things on different dialects. Also with select .first() also adds limit 1 to the query, which is not possible to do with insert. 

Please add more details proposal how it is expected to work in different cases, for example with databases that doesn't support `returning()` statements.

Also if we start expanding places where `.first()` is ok, is there any other type of queries which should support `.first()`.

To be honest from my point of view just adding an error if someone is trying to use `first()` with non-select statement would add the most value with least work. Just getting first item of result array is pretty trivial to do outside of knex.
