### ISSUE TITLE
Client does not support authentication MYSQL 8

### ISSUE THREAD

**Issue by victorgois07** [tgriesser/knex#3233]
ER_NOT_SUPPORTED_AUTH_MODE: Client does not support authentication protocol requested by server; consider upgrading MySQL client

**Comment by elhigu** [comment]
Not knex issue. Please report to mysql driver maintainers.

**Comment by elhigu** [comment]
But you can see from knex’s docker-compose.yaml how to setup mysql 8 in a way to get pass through that error. There was some switch that should be given to server in startup.

**Comment by hscstudio** [comment]
> But you can see from knex’s docker-compose.yaml how to setup mysql 8 in a way to get pass through that error. There was some switch that should be given to server in startup.

Can You show me working example of docker compose mysql ?

**Comment by elhigu** [comment]
> Can You show me working example of docker compose mysql ?

Did you check knex's docker-compose.yml?

**Comment by hscstudio** [comment]
> > Can You show me working example of docker compose mysql ?
> 
> Did you check knex's docker-compose.yml?

Yes, but this [docker-compose.yaml](https://github.com/knex/knex/blob/master/scripts/docker-compose.yml) do hack via `command: --default-authentication-plugin=mysql_native_password`, and this is not default authetication plugin in MySQL version 8

**Comment by elhigu** [comment]
> Yes, but this docker-compose.yaml do hack via command: --default-authentication-plugin=mysql_native_password, and this is not default authetication plugin in MySQL version 8

Did you check the first comment? If there something that knex can do to make mysql driver to support new mysql authentication? Driver is the part that connects to the server, knex doesn't have much to do with that part.

Also for starting server in docker with new authentication just drop the `--default-authentication-plugin=mysql_native_password`  parameter from docker-compose.yml. Then look help from here https://stackoverflow.com/a/56509065/360060 if you are able to connect to it somehow.

**Comment by gianpaj** [comment]
install the [mysql2](https://www.npmjs.com/package/mysql2) npm package and set `mysql2` as `client` in your knexfile.js  - that worked for me


```
  production: {
    client: 'mysql2',
    connection: DB_CONNECTION,
    pool: {
      min: 2,
      max: 10,
    },
    migrations: {
      tableName: 'knex_migrations',
    },
  },
```

**Comment by ViktorTsekov** [comment]
Thank you @gianpaj!
