### ISSUE TITLE
decimalNumbers is missing in MySqlConnectionConfig interface

### ISSUE THREAD

**Issue by 3mini** [tgriesser/knex#3236]
# Environment

Knex version: 0.16.4
Database + version: MySQL 5.7.22
OS: OSX 10.14.5

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do

Because we're using [MySQL2](https://www.npmjs.com/package/mysql2), we need `decimalNumbers`  as connection option.

I think that `MySqlConnectionConfig` interface have to add an optional key as below.

```
interface MySqlConnectionConfig {
  ...
  decimalNumbers?: boolean;
  ...
}
```

2. Error message
```
Types of property 'connection' are incompatible.
  Type '{ host: any; port: any; user: any; password: any; database: any; decimalNumbers: boolean; }' is not assignable to type 'string | ConnectionConfig | MariaSqlConnectionConfig | MySqlConnectionConfig | MsSqlConnectionConfig | Sqlite3ConnectionConfig | SocketConnectionConfig'.
    Object literal may only specify known properties, and 'decimalNumbers' does not exist in type 'ConnectionConfig | MariaSqlConnectionConfig | MySqlConnectionConfig | MsSqlConnectionConfig | Sqlite3ConnectionConfig | SocketConnectionConfig'.

decimalNumbers: true,
```

**Comment by kibertoad** [comment]
PR would be most appreciated! Should be an easy change.

**Comment by 3mini** [comment]
@kibertoad
I made a PR for this issue (#3244).

**Comment by kibertoad** [comment]
0.17.3 with this improvement was released!
