### ISSUE TITLE
KnexJS How to create multiple inner join

### ISSUE THREAD

**Issue by Bouncue** [tgriesser/knex#3241]
I need to transform this SQL query to KnexJS query

```
SELECT
    Book.Title,
    Book.Number,
    Author.Name,
    Author_1.Name,
    Author_2.Name,
    Author_3.Name
FROM
    ((((Book)
INNER JOIN Author ON Book.AuthName = Author.Name)
INNER JOIN Author AS Author_1 ON Book.AuthName = Author_1.Name)
INNER JOIN Author AS Author_2 ON Book.AuthName = Author_2.Name)
INNER JOIN Author AS Author_3 ON Book.AuthName = Author_3.Name
WHERE Book.Title = "HelpMe" ORDER BY Book.Number;
```

I have read the doc here [https://knexjs.org/#Builder-join](https://knexjs.org/#Builder-join) but I barely understood how to use the given example to meet my need because there is no example for such multiple inner join.

Help me please

**Comment by elhigu** [comment]
By adding multiple `.innerJoin(...)` parts to the query builder. Also knex issues is not correct place for usage questions. StackOverflow or gitter are for those.
