### ISSUE TITLE
Error: Connection terminated unexpectedly

### ISSUE THREAD

**Issue by JulesAU** [tgriesser/knex#3258]
# Environment

Knex version: 0.16.5
Database + version: pg lib ver 7.11.0. connecting to Postgres 9
OS: Alpine linux in docker

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do

Still getting regular `Error: Connection terminated unexpectedly` errors in production log. 

Downgrading to `0.13.0` avoids this - I stayed on that version for a long time because this issue remains. I tried upgrading recently and note that this issue still exists.

2. Error message

`Error: Connection terminated unexpectedly`

**Comment by elhigu** [comment]
Cannot reproduce
