### ISSUE TITLE
Weird type error with 'DeferredKeySelection'

### ISSUE THREAD

**Issue by jpike88** [tgriesser/knex#3259]
Knex 0.17.3

```
export function getBaseTagQuery() {
	return sql.knex('tag')
		.leftJoin('tag_group', 'tag_group.id', 'tag.tagGroupID')
		.select('tag_group.label as groupLabel', 'tag.*')
		.where('tag.active', 1);
}
```

Gives me a TS error:

```Return type of exported function has or is using name 'DeferredKeySelection' from external module "/Users/joshpike/Projects/aquipa/server/node_modules/knex/types/index" but cannot be named```

**Comment by kibertoad** [comment]
@jpike88 0.17.4 with all the latest typing improvement was released, please give it a try!
