### ISSUE TITLE
Missing types/result.d.ts in v0.17.4 package, typecscript can't compile app code.

### ISSUE THREAD

**Issue by jeremychone** [tgriesser/knex#3271]
# Environment

Knex version: 0.17.4
Database + version: postgresql 11
OS: mac

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do

After upgrading to v0.17.4 (from v0.17.3), we get a typescript error

![image](https://user-images.githubusercontent.com/74671/59152867-aaffc500-8a01-11e9-8a6d-1cc46d92a654.png)

in `v0.17.4` the new `types/result.d.ts` seems to be missing from the npm package. 
 
![image](https://user-images.githubusercontent.com/74671/59152851-68d68380-8a01-11e9-818e-85542933fa91.png)

# Workaround

`npm install knex@0.17.3`

**Comment by kibertoad** [comment]
ouch. lemme fix it real quick

**Comment by kibertoad** [comment]
@jeremychone Could you please try 0.17.5?

**Comment by jeremychone** [comment]
@kibertoad Just did, works. Thank you!

**Comment by kibertoad** [comment]
np, thanks for reporting it quickly!
