### ISSUE TITLE
type issue, getting first item of any[] doesn't give me any type

### ISSUE THREAD

**Issue by jpike88** [tgriesser/knex#3276]
# Environment

Knex version: latest on master
```
let nextChild = await knex('file')
			.where('parentFolderID', 3)
			.where('name', 'test')
			.where('deleted', 0);

		if (nextChild.length > 0) {
			nextChild = nextChild[0];
			if (nextChild.isFolder) {
				return recursiveLook(nextChild, parsedUrl);
			} else {
				return nextChild;
			}
		} else {
			throw new Error('Invalid child specified!');
		}
```

![Screen Shot 2019-06-10 at 9 24 23 am](https://user-images.githubusercontent.com/9585787/59168802-8cb0db00-8b61-11e9-8afa-66c45548da50.png)

**Comment by lorefnon** [comment]
Type of variable gets inferred from first assignment and doesn't change later. This is general typescript behavior and not knex specific. 

You can either use `let nextChild: any = await knex('file').where(...)`
or assign te result of `nextChild[0]` to a new variable (whose type will be inferred as any).

**Comment by jpike88** [comment]
Ah yep, been getting so much type drama I thought this was Knex's fault!
