### ISSUE TITLE
Thank You ♥️

### ISSUE THREAD

**Issue by itsjzt** [tgriesser/knex#3278]
🏆🏆🏆

Thank you guys for making this kind of thing which provides a very clean abstraction over SQL with just the most required features. I always find SQL better than using any kind of ORM but writing raw SQL has some of its own problems like not having database like independence, migrations.

I actually never knew this kind of clean abstraction  can exists which don't provide very high level API so that it creates a learning curve. 

You can close this issue after reading this. Just wanted to let you know someone, somewhere loves this project. 🎉

**Comment by kibertoad** [comment]
Much appreciated!
