### ISSUE TITLE
Rollback in wrong order

### ISSUE THREAD

**Issue by boutdemousse** [tgriesser/knex#3281]
**What I want to do** 

Rollback my migration that has a lot of table creation in the same batch, using `knex migrate:rollback`

I suppose this is what happened here too : https://github.com/tgriesser/knex/issues/2832#issue-365698120

**What should happen**

The rollback should happen. 

**The problem**

If I have two migration files with table A and table B, with a foreign key to A.id in B, then the rollback will fail when trying to remove A before B (!). 

Rollback order is reversed by batch number, but when sharing the same batch number it seems that the original migration order is kept for some reason ?

So basically all foreign key constraints are failing and you can't rollback the batch in this case.
Foreign key constraints are therefore not respected and the rollback fails when `--all` is not used.

You can check that it is the case looking at this part of the code starting line 150 :
https://github.com/tgriesser/knex/blob/5eaac66ea54c9d75a93a7a0b08be3fdc43785aca/src/migrate/Migrator.js#L150
```javascript
          return all
            ? allMigrations
                .filter((migration) => {
                  return completedMigrations.includes(migration.file);
                })
                .reverse()
            : this._getLastBatch(val);
```

The `_getLastBatch()` is as follow : 
https://github.com/tgriesser/knex/blob/5eaac66ea54c9d75a93a7a0b08be3fdc43785aca/src/migrate/Migrator.js#L370
```javascript
  // Get the last batch of migrations, by name, ordered by insert id in reverse
  // order.
  _getLastBatch([allMigrations]) {
    const { tableName, schemaName } = this.config;
    return getTable(this.knex, tableName, schemaName)
      .where('batch', function(qb) {
        qb.max('batch').from(getTableName(tableName, schemaName));
      })
      .orderBy('id', 'desc')
      .map((migration) => {
        return allMigrations.find((entry) => {
          return (
            this.config.migrationSource.getMigrationName(entry) ===
            migration.name
          );
        });
      });
  }
```

**Alternative solution**

Using `knex migrate:rollback --all` works fine.

**Comment by elhigu** [comment]
Please add reproduction code.

**Comment by boutdemousse** [comment]
While I was trying to reuse my work project on the computer at home to isolate the error and share the repo, I actually encountered another bug that I don't have at work.

I guess it's not my day with knex ? 

```
migration file "20190130134225_create_products.js" failed
migration failed with error: alter table `productsAttributes` add unique `productsattributes_productid_name_unique`(`productId`, `name`) - ER_TOO_LONG_KEY: Specified key was too long; max key length is 767 bytes
```

**Comment by kibertoad** [comment]
@boutdemousse Try using explicit name for constraint, autogenerated one does not satisfy DB requirements.
Which knex version are you using? Rollback order bug was fixed in latest ones.

**Comment by elhigu** [comment]
closing until there is reproduction... that limit should not be hit easily. Please open separate bug report with reproduction code for that.

**Comment by kibertoad** [comment]
Should work fine in 0.18.0
