### ISSUE TITLE
Performance solution UUID in MySQL and/or MariaDB

### ISSUE THREAD

**Issue by jonathansilva** [tgriesser/knex#3283]
# Feature discussion / request

Please implement the functions:
UUID_TO_BIN
BIN_TO_UUID
IS_UUID (would be cool too)

This will solve 3 problems:
- increased storage: 36 characters
- more difficult to debug
- performance issues: mainly because of the size and not being ordered

link: https://mysqlserverteam.com/mysql-8-0-uuid-support/

**Comment by elhigu** [comment]
Please add API proposal how you thing those should be supported. Like this you should be able to use them easily with for example `knex.raw('UUID_TO_BIN(??)', ['column_name'])`.

Usually we don't implement special APIs for stuff that is used just one dialect, closing for now until there is some kind of proposal how this feature should work. This is too unclear like this.
