### ISSUE TITLE
question: knex query as json format and json format to knex query

### ISSUE THREAD

**Issue by gopalakrishnan-subramani** [tgriesser/knex#3284]
We have a requirement where as the SQL select query is build on a visual tools in the browser,
then store the query as JSON format into DB at the  backend, then execute the query on the node.js on need basics.

I have few questions, please help to validate.

1. Will knex work on browser?
2. Can I convert knex query into JSON format so that the JSON shall be stored into DB record as it is.
3. Can I take JSON generated on item 2 above, get back knex query for execution .

If we could not do item 1 to 3,  can you please recommend alternative library if that exists. Right now, we use loopback, it has options for queries in JSON format, but we are exploring other options which has strong community support.

**Comment by kibertoad** [comment]
1) Unlikely. Which DB are you using?
2) I don't think query serialization is a feature that we currently support. However, are are definitely open for PRs that would implement something along these lines.

Unfortunately, I'm not aware of other solutions that support this use-case.

**Comment by elhigu** [comment]
Knex can be used in a browser for query building purposes. In your case closest thing probably would be to build queries in browser and then send toSQL() or toSQL().toNative() result to backend and execute those as raw queries.

Knex builders doesn't support any inspection / serialization capabilities so if you want to create query builder instance from serialized form, there is no way to do it.
