### ISSUE TITLE
(postgres) knex.raw INSERT INTO wrapping string values in double quotes instead of single

### ISSUE THREAD

**Issue by joemillervi** [tgriesser/knex#3288]
# Environment

Knex version: 0.17.6
Database + version: postgres (PostgreSQL) 9.5.3
OS: mac os el capitan 10.11.6

# Bug

1. When a raw query is made using kenx.raw and values are passed in as an object, it wraps the strings with double quotes by default. PostgreSQL interprets " as being quotes for identifiers, ' as being quotes for strings, so this creates an error.

2. Error message: error: column "bob" does not exist
(when inserting a username)

3. Assume a platform_user table exists with a username row. 
This code: 
```
knex('platform_user').insert({username: 'bob'})
```

Works fine and creates this log:

```
{ method: 'insert',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings:
   ['bob' ],
  __knexQueryUid: '74a9d5d8-e6de-4320-ae3c-03f969240528',
  sql:
   'insert into "platform_user" ("username") values (?)',
  returning: undefined }
```

However if you use a raw query:
```
    const platformUser = await knex.schema.raw('
            INSERT INTO platform_user (
            username,
    )   
    VALUES (
      :username:
    );  
  ',  
  {username: 'bob'}) 
```
Then it generates this sql:
`'\n    INSERT INTO platform_user (username)\n    VALUES ("bob");\n  '`
That causes error: column "bob" does not exist

Is there a way to configure this in settings? If not, I think single quotes around strings should be used (in postgres) do you know if this change would be in the pg package or in knex?

**Comment by elhigu** [comment]
You are using identifier binding for `:username:` instead of value binding `:username` so it will be quoted as identifier instead of passing it as value.

**Comment by joemillervi** [comment]
Ah ok thanks. Will look into this.
