### ISSUE TITLE
timestamps not working

### ISSUE THREAD

**Issue by stoplion** [tgriesser/knex#3289]
# Environment

Knex version: ^0.17.3
Database + version: Postgress 9.6
OS: OS X

# Bug

1. According to the docs, `timestamps` 'Adds created_at and updated_at columns on the database, setting each to datetime types.'  But this is not working.

```
`exports.up = async function(knex) {
  knex.schema.alterTable('posts', (t) => {
    t.timestamps(true, true)
  })
}

exports.down = async function(knex) {
  knex.schema.alterTable('posts', (t) => {
    t.dropTimestamps()
  })
}
```

No created_at and updated_at columns are created.

Are the docs giving the complete steps needed to make this work?

**Comment by elhigu** [comment]
You are not executing your schema builder. Add await or return your schema builder from migration handler.

**Comment by kibertoad** [comment]
@elhigu Our documentation doesn't mention that part, though: https://knexjs.org/#Schema

Probably we should make that part more explicit.

**Comment by elhigu** [comment]
> The knex.schema is a getter function, which returns a stateful object containing the query. Therefore be sure to obtain a new instance of the knex.schema for every query. These methods return promises.

Also that seems to be wrong... since they doesn't return promises, but schema builder instance that is thenable and needs to be executed separately.

Anyways, saying that it returns promise would imply that one has to wait until promise is resolved before continuing. But true, it could be made more explicit.
