### ISSUE TITLE
Passing the type of database row as a type parameter is not working as documented

### ISSUE THREAD

**Issue by nmummau** [tgriesser/knex#3295]
### Environment

Knex version: knex 0.16.5
Database + version: pg 7.11.0
OS: Ubuntu 18.04.2 LTS
Node: 10.16.0
Typescript: 3.1.6

I'm reading the [TypeScript Support docs](https://knexjs.org/#typescript-support), specifically the section that describes:
> If using TypeScript, you can pass the type of database row as a type parameter to get better autocompletion support down the chain. 

I'm just trying to select a row from a table and get a typed output row. The Knex documentation makes it look so simple, but I cannot get it to work as described. 

I have a `config.ts` file (not shown) that is responsible to setup the knex connection information. That file is imported into the `database.ts` file where Knex is imported and then exported for use throughout my project. I am able to use it without issue, but I recently noticed that I'm missing out on the typed features of Knex so I looked into doing some refactoring... but I'm having issues.

It's clear that **`database<ILogin>`** is where my issue lies, but nothing is pointing me into a direction to head so I'm hoping someone on here will help.

Here is example code:
#### database.ts
```
import Knex from 'knex';
import config from '@/config';

const knex = Knex({
	client: 'pg',
	connection: config.database
});
export default knex;
```

#### user.ts
```
import database from '@/database'  //the above database.ts file

interface ILogin {
  loginId: number;
  loginName: string;
}

var loginName = 'foo';
var outputRow = {} as ILogin;


//Does not work
var outputRow = database<ILogin>('base.login')
  .select({ loginId: 'login.login_id', loginName: 'login.login_name' })
  .where({ 'login.login_name': loginName })
  .first();


//Does work but is inconvenient and doesn't match the documenation
database('base.login')
  .select({ loginId: 'login.login_id', loginName: 'login.login_name' })
  .where({ 'login.login_name': loginName })
  .first()
  .then((row) => {
    outputRow = {
      loginId: parseInt(row.loginId)
    }
  })
```

VS Code gives me this error when highlighting the <ILogin> type parameter.
>Expected 0 type arguments but got 1. ts(2558)

Thanks in advance.

@lorefnon

**Comment by lorefnon** [comment]
Can you please give me the result of `npm ls knex`, `npm ls @types/knex` and `npm ls typescript`.

**Comment by nmummau** [comment]
`npm ls knex`
knex@0.16.5

`npm ls @types/knex`
(empty)

`npm ls typescript`
typescript@3.1.6

PS: During troubleshooting, I did `npm install @types/knex`, but I had the same results. I have since removed @types/knex since I read it was deprecated.

**Comment by lorefnon** [comment]
That feature didn't exist in knex@0.16.5. please consider updating to
latest stable and let us know if you continue facing this issue.

**Comment by nmummau** [comment]
That'll do it... I'm new to npm and assumed `npm install` would get me the lastest. I ran `npm install knex@latest` and am now on knex@0.17.6 and it appears to be working. Thank your you help, I really appreciate it. Sorry for the trouble.
