### ISSUE TITLE
Returning date from MySQL database as ISO format only

### ISSUE THREAD

**Issue by ShanChathusanda93** [tgriesser/knex#3299]
# Environment

Knex version: 0.15.2
Database + version: MySQL 5.7.26
OS: Ubunut 18.04.1

# Feature discussion / request

Currently I am trying to get some data from a table in a MySQL database. Here I tried to get the **date** only from a **Datetime** column. The data in this column is stored as the local time. But when I get the result by using knex, I only received the date with the format of ISO. But I need to get these dates from local format. I have searched for the documents for this feature but I was unable to get a solution from using knex. I really appreciate if you can provide some guidance to this.

**Comment by ricardograca** [comment]
This is the underlying mysql driver doing the formatting. Knex isn't involved in that. You can probably use the `timezone` and/or `dateStrings` options to achieve what you want: https://github.com/mysqljs/mysql#connection-options

**Comment by elhigu** [comment]
Knex doesn't decide how data is returned from database. Its responsibility of DB driver as @ricardograca said..

**Comment by ShanChathusanda93** [comment]
Thank you for the quick response.
