### ISSUE TITLE
Joining tables with same underlying column name causes conflict

### ISSUE THREAD

**Issue by bj-bg** [tgriesser/knex#3300]
# Environment

Knex version: 0.17.6
Database + version: PostgreSQL 11.3
OS: macOS 10.14.5

# Bug

The query:
```
db('users')
    .select({ user_id: 'users.id' }, { otp_id: 'otps.id' }, 'otps.*')
    .leftJoin('otps', 'users.id', 'otps.user_id')
    .where('users.phone_number', formattedPhoneNumber).first();
```
produces the sql:
```
select "users"."id" as "user_id", "otps"."id" as "otp_id", "otps".* from "users" left join "otps" on "users"."id" = "otps"."user_id" where "users"."phone_number" = ? limit ?
```
as expected. Everything works fine when the user has an OTP entry. However, if there is no OTP associated with some user then knex returns:
```
{
  user_id: null,
  otp_id: null,
  id: null,
  created_at: null,
  updated_at: null,
  otp: null,
  verified_at: null,
  expires_at: null
}
```
i.e. the `user_id` is `null` even though a user entry exists. Running the sql query directly on the DB (via psql) returns the expected results.

If I change the query to:

```
db('users')
    .select({ user_id: 'users.id' }, { otp_id: 'otps.id' }, 'otps.otp', 'otps.verified_at', 'otps.expires_at')
    .leftJoin('otps', 'users.id', 'otps.user_id')
    .where('users.phone_number', formattedPhoneNumber).first()
```
then everything works as expected so I suspect the issue is some sort of conflict when parsing the db response given that there are two columns with the same underlying name ('id').
In fact, if I swap the ordering of the select from:
```
select({ user_id: 'users.id' }, { otp_id: 'otps.id' }, 'otps.*')
```
to
```
select('otps.*', { user_id: 'users.id' }, { otp_id: 'otps.id' })
```
then the user_id has the expected result; which does strongly suggest that the user_id is getting overwritten by the otps id (this wouldn't happen in the second case because I assume the fields are being processed in the order that they're passed to the select).

Not sure why this isn't an issue when there's a entry in both the users and otps field.

**Comment by elhigu** [comment]
Doesn't look like knex issue, but just how database / pg driver behaves in this particular case. If complete reproduction code is provided allowing other to verify the issues, this can be reopened.

**Comment by bj-bg** [comment]
Relevant code is:
```
const db = Knex({
    client: 'pg',
    connection: CONFIG.DB_CONNECTION_URL,
    pool: { min: 2, max: 10 }
});

db('users')
    .select({ user_id: 'users.id' }, { otp_id: 'otps.id' }, 'otps.*')
    .leftJoin('otps', 'users.id', 'otps.user_id')
    .where('users.phone_number', formattedPhoneNumber).first();
```
and for reference, the DB schema:
```
CREATE TABLE users (
    id uuid PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    first_name TEXT NOT NULL,
    family_name TEXT NOT NULL,
    phone_number VARCHAR(255) UNIQUE NOT NULL,  -- VARCHAR(255) can be indexed (unlike TEXT)
    email CITEXT,
    token_updated_at TIMESTAMPTZ,
    num_token_requests INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE otps (
    id uuid PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    user_id uuid UNIQUE NOT NULL REFERENCES users(id),
    otp VARCHAR(255) NOT NULL,
    verified_at TIMESTAMPTZ,
    expires_at TIMESTAMPTZ NOT NULL
);
```

**Comment by elhigu** [comment]
As I said, DB init data is important and thats not complete example, that will still require maybe 10 minutes to run it and still wouldn't be sure if it even works as is...

https://github.com/tgriesser/knex/blob/master/CONTRIBUTING.md#what-is-minimal-code-to-reproduce-bug-and-why-i-have-to-provide-that-when-i-can-just-tell-whats-the-problem-is

> as expected. Everything works fine when the user has an OTP entry. However, if there is no OTP associated with some user then knex returns:

Queries for both of the cases would be needed

> Running the sql query directly on the DB (via psql) returns the expected results.

And the plain query which was used to get expected results (bacause it couldn't have been the one produced by query builder or it wouldn't have worked).
