### ISSUE TITLE
Issues in last changes to transactions

### ISSUE THREAD

**Issue by vonagam** [tgriesser/knex#3309]
@kibertoad, i see two issues with pull requests #3235 and #3297 which were published in 0.18:

In first one, you check sql equality to `"ROLLBACK"` string, but what about nested transactions which use `"ROLLBACK TO SAVEPOINT ..."` for rollback?

In second one, you did not just expose `executionPromise`, you created it. It means that now everybody should handle this new promise (especially people who use a container function), otherwise you will get unhandled rejections for previously fine working code. So now there are two separate promises that behave the same but are handled separately, i don't think that really what you wanted.

**Comment by kibertoad** [comment]
thanks for raising the issue! I will take a look

**Comment by fruuf** [comment]
having a similar error here, if you throw an exception within the knex.transaction handler an unhandled rejection bubbles up all the way to process.on

**Comment by elhigu** [comment]
@fruuf AFAIK it is normal behavior and has always been like if transaction handler throws an exception, it is leaked... you should handle those exceptions by your handler. However if you make handler to be async function, then it implicitly return a promise, which triggers knex's implicit commit / rollback functionality.

I would suggest always using `knex.transaction(asyc (trx) => {...})` type of handlers.

If you think you are experiencing regression, open new issue with reproduction code to verify the issue.

**Comment by optii** [comment]
I seem to be having similar problems since the 0.18 update with transactions. I will try and open an issue with reproduction code if I get time

**Comment by vonagam** [comment]
Just to be clear, you can find reproduction code for this issue in knex tests. For example [second one for transaction](https://github.com/tgriesser/knex/blob/ae6bb64cbe7787e6ddfe883b3b2a4fc6c27d653e/test/integration/builder/transaction.js#L25), you can see unhandled rejection warning in [travis log for second PR](https://travis-ci.org/tgriesser/knex/jobs/547885316#L2266).

To not get any warnings you need to write code like this with double catch:
```js
await knex.transaction(async (trx) => {
  trx.executionPromise.catch(() => {} /* catch new */);
  throw undefined;
})
.catch(() => {} /* catch old */);
```

Ideally you should add this snippet to knex mocha setup to treat unhandled rejections as tests failure and not just warnings:
```js
process.on('unhandledRejection', (reason) => {
  console.error('Unhandled Rejection:', reason);
  process.exit(1);
});
```

(But i see that you have other unrelated unhandled rejections, so that may wait.)

**Comment by kibertoad** [comment]
Created #3320 for test improvement.

**Comment by kibertoad** [comment]
0.18.1 was released, please report back if it works properly now.
Will take a look at first part of this issue later today. Wonder if using plain `.startsWith` is a safe choice.

**Comment by TD092854** [comment]
When I use:
```javascript
const trx = await knex.transaction();
```
I still get an unhandled promise rejection warning whenever the transaction is rolled back.
If I use the code following code I'm now able to catch the rejection.
```javascript
const trx = await new Promise((resolve) => {
    knex.transaction((trx) => {
        resolve(trx);
    }).catch((err) => {
        console.error(err);
    });
});
```

Shouldn't the rollback only throw an error if it actually fails to roll back?

**Comment by kibertoad** [comment]
@TD092854 You are using 0.18.1?

**Comment by TD092854** [comment]
@kibertoad Yes I am.

**Comment by vonagam** [comment]
@TD092854 Do you pass an argument to `rollback()`?

**Comment by TD092854** [comment]
I am calling rollback with an argument as stated in the documentation.

> Calling trx.rollback will return a rejected Promise. If you don't pass any argument to trx.rollback, a generic Error object will be created and passed in to ensure the Promise always rejects with something.

But even without an argument it throws an error that I cannot catch when awaiting the rollback.

```javascript
try {
     // Do queries in the transaction
    await trx.commit();
} catch (ex) {
    await trx.rollback(ex);
}
```
Putting a try/catch around that block does nothing.
The error that is always thrown from the rollback (with or without argument) bubbles up to the catch on the transaction as defined in my first comment.

**Comment by vonagam** [comment]
Putting `try ... catch` around does nothing because `trx.commit()` or `trx.rollback()` never reject, instead they may reject a transaction promise. You can access this promise in two ways:

- If you use `knex.transaction()` with a container function then the return value is this promise. (so second snippet from your first comment works)

- If you use `knex.transaction()` without a container function (like in first snippet) to get transactor use `trx.executionPromise` to get that promise and add handlers to it.

If you use a container function and call `trx.rollback()` with or without argument a transaction promise will always get rejected.

If you do not use a container function then a transaction promise will be rejected in two cases: either you passed argument to `trx.rollback()` or a rollback failed.

So to fix first snippet do:
```js
const trx = await knex.transaction();

trx.executionPromise.catch((error) => {
  // you get here only if a commit or a rollback fails
  console.error(error);
});

try {
  // stuff
  await trx.commit();
} catch (error) {
  // something failed inside try block
  console.error(error);
  await trx.rollback(); // do not pass an argument
}
```

**Comment by TD092854** [comment]
It still fails in the same way as before with your snippet.
The catch on the executionPromise is called but, I still end up getting an unhandled rejection (with or without argument to trx.rollback()).

```javascript
const trx= await knex.transaction();

trx.executionPromise.catch((err) => {
    console.error(err);
});

try {
    // Do queries in the transaction
    await trx.commit();
} catch (ex) {
    await trx.rollback();
}
```

**Comment by 2color** [comment]
I'm experiencing the same thing as @TD092854 with version `0.18.1`

For example, just to test rolling back a transaction I did the following

```js
const trx = await knex.transaction();

trx.executionPromise.catch((err) => {
    console.error('other exception', error)
});

try {
    // insert stuff
    await trx.rollback();
} catch (ex) {
    console.error('exception: ', ex)
}

```

I get the following when running the code:
 `other exception Error: Transaction rejected with non-error: undefined`

**Comment by vonagam** [comment]
@TD092854 @2color 

Ok, i might have reproduced an unhandled rejection (but only when rollback has an argument).

Can you try to replace [those lines](https://github.com/tgriesser/knex/blob/56c3af8512a84d6eff77fe33c5105fe2b6f55436/src/transaction.js#L110-L113) in your `node_modules/knex/src/transaction.js` with:

```js
if (this.initRejectFn) {
  this.initRejectFn(err);
} else {
  throw err;
}
```

And then run your code and check if any cases will stop to produce unhandled rejections.

**Comment by kibertoad** [comment]
@TD092854 @2color Could you please try the freshly released 0.18.2?

**Comment by 2color** [comment]
@vonagam That fixed the problem. 

@kibertoad Thanks for the quick release of `0.18.2`

Question regarding the docs, is there any reason to use the callback style transactions?
I personally prefer to do async/await all over but perhaps I'm missing something?

**Comment by kibertoad** [comment]
If you don't want to have unhandled rejection on transaction rollback after insertion error, then yes, I think that you need that catch block.
Callbacks might result in simpler code when all transaction operations happen in same place, it would do automatic transaction management for you based on returning promise or throwing inside of it. If you need to pass transaction around, await version is definitely the way to go.

**Comment by 2color** [comment]
I understand. 

What about catching an error creating the transaction, is this perhaps a better way to handle it?


```js
let trx
try {
    trx = await knex.transaction();

    trx.executionPromise.catch((err) => {
        console.error('other exception', error)
    });

    await trx('users').insert({ name: 'James' });
    await trx('orders').insert({ item: 'Chocolate' });
} catch (ex) {
    await trx.rollback();
    console.error('exception: ', ex);
}
```

**Comment by elhigu** [comment]
I aways prefer callback style with aync / await if I don't have any reason why I would like to have explicit commit / rollback.

```
try {
    const result = await knex.transaction(async trx => {
       let rows = trx('table').where(...).forUpdate();
       // update rows
       return 'what ever you like to get out';
    });
} catch (err) {
  // transaction failed
}
```

Explicit commit / rollback is mostly needed when you need to pass transaction around to different functions in your app and for example commit / rollback in the end in some frameworks middleware.

**Comment by kibertoad** [comment]
@2color 
> What about catching an error creating the transaction, is this perhaps a better way to handle it?

If this is a frequent use-case in your codebase and you don't do anything on transaction rollbacks, what I personally would do is introduce method getNewTransaction in some abstraction like db.js and have there a method of
```
function getNewTransaction() {
 const trx = await knex.transaction();
trx.executionPromise.catch((err) => {
        console.error('other exception', error)
    });
return trx;
}
```

**Comment by 2color** [comment]
Perhaps I should be more precise with my question. 

When exactly does the `executionPromise` fail and how does it relate to calling `await trx.rollback();`?

**Comment by TD092854** [comment]
Thanks!

I'm now able to use the following code without any unhandled rejections (with or without argument to rollback) and without a catch handler on executionPromise.

```javascript
const trx = await knex.transaction();

try {
    // Do queries in the transaction
    await trx.commit();
} catch (ex) {
    await trx.rollback();
}
```

Will the rollback throw an error if it fails? Or will that still result in an unhandled rejection or an error in the catch handler of executionPromise?

**Comment by vonagam** [comment]
Opened #3328 to fix absence of unhandled rejections warnings when they are valid.

Here current expected behaviour of standalone transactions based on code:

`trx.commit()` and `trx.rollback()` return a promise which never rejects. But they resolve or reject  `trx.executionPromise` based on their success, so you must add catch handler to it to be notified about failed commits or rollbacks. (Also you should not pass non-undefined value as an argument to `rollback()` as it will reject a transaction promise).

Personally i would have preferred if `commit` and `rollback` would reject themselves on failure and not `executionPromise` (so there would be no need for `executionPromise` and it will be easier to work with `async`/`await`). But as i understand this is work in progress stuff.

**Comment by vonagam** [comment]
Also for now you can achieve easier usage with `async`/`await` with helpers like this:

```js
const commit = async (trx) => {
  await trx.commit();
  await trx.executionPromise;
};

const rollback = async (trx) => {
  await trx.rollback();
  await trx.executionPromise;
};
```

**Comment by kibertoad** [comment]
0.18.3 with latest fixes on this subject was released. Please report back what your experiences with it are!

**Comment by 2color** [comment]
Thanks @vonagam and @kibertoad.

Do the docs need updating:
https://github.com/knex/documentation/blob/e783ab528c5a09a5f1601f5df3c3af6d77f7d968/sections/transactions.js#L102-L119

**Comment by TD092854** [comment]
Thanks for all the work! :)

So with the latest changes I would be able to do the following and handle all errors?

```javascript
const trx = await knex.transaction();

try {
    // Do queries in the transaction
    await trx.commit();
} catch (ex) {
    await trx.rollback();
}

await trx.executionPromise;
```

**Comment by vonagam** [comment]
Yes.
