### ISSUE TITLE
add MariaDB dialect

### ISSUE THREAD

**Issue by knoxcard** [tgriesser/knex#3325]
Currently, only `mysql` and `mysql2` drivers are being promoted.

`mariadb` should be added as well, linking to this library...
https://www.npmjs.com/package/mariadb

_This is already working with Sequelize_

**Comment by elhigu** [comment]
Mariadb driver didn't work so well, so the whole dialect was dropped and mysql should be used instead.

**Comment by elhigu** [comment]
I did some stress testing with that driver and there were crashes, leaking and hanging in error cases etc. I don't remember all the details from top of my head.

**Comment by knoxcard** [comment]
okay, no problem. @rusher - Got it all working with Sequelize, have to discuss with him what it would take to get it 100% with Knex.

**Comment by elhigu** [comment]
maybe they have fixed some of those driver bugs or sequelize hasn't done proper stress testing for drivers (I did find bugs from most of node db drivers when I did my tests and at most of them were fixed fast by driver maintainers) ... dunno. Anyways new dialects should be done as seaprate npm packages. (checkout contributing.md)

**Comment by wirekang** [comment]
There some differences between mysql and mariadb, and mysql driver blocks mariadb-only features.


https://github.com/knex/knex/issues/5173
