### ISSUE TITLE
whereRaw query unable to work with parameter or array binding

### ISSUE THREAD

**Issue by isocroft** [tgriesser/knex#3330]
# Environment

Knex version: 0.17.3
Database + version: MySQL 5.7.3
OS: linux/amd64

# Bug
>I am getting an error on knex *'src/raw.js'* line 138 when trying to use the whereRaw

The bug here is that the **expectedBindings** are not counted properly as well as the **index** leading to the error 

2. Error message: **"Expected 1 bindings, saw 0"**

3. Reduced test code:

```js

knex.table('rides').whereRaw('user_id = ? AND completed = ? AND YEAR(created_at) >= ? AND YEAR(created_at) <= ? AND total_cost <=> deposit', ["30fb73d0-9e3d-11e9-bd80-3741ce1df8fb", 1, 2018, 2019]).select('id', 'total_cost', 'driver_id')
.then(function (rows) {
    // code here...
});

```
# Missing / erroneus documentation

Send issue to documentation repo, or fix it and send PR https://github.com/knex/documentation

**Comment by elhigu** [comment]
Cannot reproduce: https://runkit.com/embed/gmfkad4x2ec0

Here is a way how to get that error https://runkit.com/embed/gmfkad4x2ec0

**Comment by isocroft** [comment]
I know i specified that the **knex** version was 0.17.3 however your *runkit setup* uses the latest (v0.18.2) version.

**Comment by elhigu** [comment]
So its working for you with 0.18 🤔 Im pretty sure there has not been any changes to bindings code since 0.14 or ecen earlier...
