### ISSUE TITLE
Custom migration stubs are not used

### ISSUE THREAD

**Issue by Enitoni** [tgriesser/knex#3333]
I'm trying to define my own migration stubs, to avoid having to create the same boilerplate code manually.

This is the stub file (project/migration.stub.js):
```js
//@ts-check

/**
 * @param {import("knex")} knex
 */
exports.up = async knex => {}

/**
 * @param {import("knex")} knex
 */
exports.down = async knex => {}
```
And this is my knexfile (project/knexfile.js):
```js
// Update with your config settings.
require("dotenv/config")
const { DB_HOST, DB_NAME, DB_USER, DB_PASS } = process.env

module.exports = {
  development: {
    client: "sqlite3",
    connection: {
      filename: "./dev.sqlite3"
    },
    migrations: {
      tableName: "knex_migrations",
      stub: "migration.stub.js"
    }
  },

  production: {
    client: "pg",
    connection: {
      host: DB_HOST,
      user: DB_USER,
      password: DB_PASS,
      database: DB_NAME
    },
    migrations: {
      tableName: "knex_migrations"
    }
  }
}
```

However, when I run `knex migrate:make something` it gives me this:
```js
exports.up = function(knex) {
  
};

exports.down = function(knex) {
  
};
```

According to the documentation, this is correctly configured. Am I missing something?
Knex version: 0.18.3

**Comment by kibertoad** [comment]
@Enitoni This behaviour seems not to be covered by tests, so could very well be broken. I'll take a look today, thank you for reporting!

**Comment by bohdan-shulha** [comment]
@kibertoad , it is absolutely broken. The issue lies in the merger algorithm and/or argv parsing, and it happens at this line https://github.com/tgriesser/knex/blob/master/bin/cli.js#L159 

```.make(name, { extension: ext, stub })```

When the `stub` is `null` (one didn't pass `--stub` option) - it replaces the value given in knexfile.

**Comment by kibertoad** [comment]
No need to setup everything :). If you take a look at existing cli tests, they use sqlite3, so work out-of-the-box.

**Comment by kibertoad** [comment]
Released in 0.18.4

**Comment by nfantone** [comment]
@kibertoad I know this is a somewhat old (and closed) issue - but I just needed to say that the stub file that @Enitoni was looking to set up should be the **default for `.js` extensions**.

I find myself doing _exactly this_ every time I start a new `knex` project with SQL migrations.

**Comment by kibertoad** [comment]
@nfantone To make sure that I understand you correctly - you suggest knex to treat `"migration.stub.js"` as default if no stub is specified?

**Comment by kibertoad** [comment]
Isn't it a default already?

**Comment by nfantone** [comment]
@kibertoad I meant a version of the default stub closer to what @Enitoni suggested. Something like:

```js
//@ts-check

/**
 * @param {import("knex")} knex
 */
async function up(knex) {
  // TODO
}

/**
 * @param {import("knex")} knex
 */
async function down(knex) {
  // TODO
}

module.exports = { up, down };
```

If you feel like the `@ts-check` directive is _too_ opinionated, it could be left out altogether.
