### ISSUE TITLE
Version mismatch between NPM and github releases

### ISSUE THREAD

**Issue by gDelgado14** [tgriesser/knex#3342]
Noticed that `knex` on NPM is set to version 0.18.3 while the latest release of knex as per this repo is 0.17.2

Can someone please explain if and how these two versions are related? Not sure if we should be updating to version 0.18.3 since there's no mention of it in this repo other than in the package.json

**Comment by kibertoad** [comment]
@gDelgado14 You are reading too much into it, I'm just really terrible at remembering to tag versions on GitHub 😅. That said, there is a known regression in 0.18.x currently: https://github.com/tgriesser/knex/issues/3333

If it doesn't concern you, and breaking changes in 0.18 typings are not a problem for you, then by all means 0.18 is superior to 0.17 and update is recommended.

**Comment by kibertoad** [comment]
0.18.4 with correct tag has just landed.
