### ISSUE TITLE
Fix vulnerabilities

### ISSUE THREAD

**Issue by kostenko** [tgriesser/knex#3348]
# Environment

Knex version: 0.19.0
Database + version: postgres 11
OS: linux/

# Fix vulnerabilities
There are a couple of high vulnerabilities in the dependencies. I managed to workaround the mixin-deep by updating micromatch in package-lock.json to 4.0.1 but set-value remains vulnerable.
https://npmjs.com/advisories/1012
https://npmjs.com/advisories/1013

```
$ npm ls mixin-deep
service@1.0.0 service
└─┬ knex@0.19.0
  └─┬ liftoff@3.1.0
    └─┬ findup-sync@3.0.0
      └─┬ micromatch@3.1.10
        └─┬ snapdragon@0.8.2
          └─┬ base@0.11.2
            └── mixin-deep@1.3.2 

$ npm ls set-value
service@1.0.0 service
└─┬ knex@0.19.0
  └─┬ liftoff@3.1.0
    └─┬ findup-sync@3.0.0
      └─┬ micromatch@3.1.10
        └─┬ snapdragon@0.8.2
          └─┬ base@0.11.2
            └─┬ cache-base@1.0.1
              ├── set-value@2.0.1 
              └─┬ union-value@1.0.1
                └── set-value@2.0.1  deduped
```

**Comment by AstroGD** [comment]
Please provide a fix asap as I am highly depending on your package and the entire software Im using your package for is currently offline and needs to get back online

**Comment by kibertoad** [comment]
@kostenko @AstroGD Unfortunately, this is not as simple, since, as you can see, this is a deeply nested dependency that we have no control over. As you can see here https://github.com/jonschlinkert/cache-base/pull/13 - community is already making efforts to address the problem. However, until this is addressed upstream, we can't do anything about it.
Good news is that `liftoff` is only used by knex-cli, so there is no real attack vector based on this for knex itself being run in production.

**Comment by kibertoad** [comment]
@kostenko OK, according to https://github.com/jonschlinkert/cache-base/pull/13#event-2480332075, npm "has fixed the version reported to be vulnerable", whatever that means. Could you try deleting node_modules locally and re-resolving them from a clean slate now, and check if you still get warnings?

**Comment by kostenko** [comment]
@kibertoad Yeah, only after they (cache-base) fixed their [package.json](https://github.com/jonschlinkert/cache-base/pull/13/commits/1ff79f8cd5c88231f98ca80faf092e6fb78c2bc7) — seems like they expected `^` to lead to an upgrade when a patch version of a npm packages is released, which is a wrong expectation as `^` would do it for a minor version.

**Comment by AstroGD** [comment]
I changed the micromatch version to 4.0.2 as it does not require the vulnerable dependencies any longer. Seems to work fine with knex. Tested it for 1 hour now and I dont seem to have issues with this change

**Comment by kibertoad** [comment]
@kostenko Can this issue be considered resolved then? Is there anything left to do?

**Comment by kostenko** [comment]
@kibertoad Sure, I'm closing it, thanks.
