### ISSUE TITLE
EBUSY ERROR

### ISSUE THREAD

**Issue by khanhnvbap** [tgriesser/knex#3353]
# Environment

Knex version: ^0.16.5
Database + version: mysql version ^2.17.1
OS: centos

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do
- I have cronjob run 30s per time. I connect to mysql with knexjs for get data and update it. 
Every things seem ok until cronjob run 200 times then knexjs throw error: **getaddrinfo EBUSY**
2. Error message
`Error: getaddrinfo EBUSY database_host_name database_host_name:3306`
When I restart server it is ok.

**Comment by ricardograca** [comment]
Doesn't seem to be related to Knex specifically at all: https://github.com/npm/npm/issues/13461

**Comment by khanhnvbap** [comment]
> Doesn't seem to be related to Knex specifically at all: [npm/npm#13461](https://github.com/npm/npm/issues/13461)

I don't run npm install. I run my code and my server throw error of knexjs package.

**Comment by elhigu** [comment]
cannot reproduce, also 99.9% sure that this is nothing specific to knex.
