### ISSUE TITLE
.toSQL() for renameColumn doesn't return sql statements.

### ISSUE THREAD

**Issue by pyudroi** [tgriesser/knex#3358]
# Environment
Knex version: 0.19.0
Database + version: MySql + 8.0
OS: macos

# Bug
.toSQL() for renaming column doesn't provide right SQL statements back.

```
(async () => {
  try {
    var knex = require('knex')({
      client: 'mysql',
      connection: {
        host: '127.0.0.1',
        user: 'root',
        password: 'secret',
        database: 'project'
      }
    });

    knex.schema.createTable('users', function (table) {
      table.increments();
      table.string('name');
      table.timestamps();
    })

    let val = knex.schema.alterTable('users', function (t) {
      t.renameColumn('name','title')
    }).toSQL()

    console.log(val);

  } catch (e) {
    console.log(e);
  }

})().catch(err => {
  console.error(err);
});
```

Prints
```
[ { sql: 'show fields from `users` where field = ?',
    output: [Function: output],
    bindings: [ 'name' ] } ]
```

**Comment by lorefnon** [comment]
It appears that this has been broken for DDL operations that require schema introspection since inception. 

@kibertoad @elhigu Do you think we can simply add a provision to identify scenarios where the query pushed in the sequence is not the primary query and throw in such cases ?

**Comment by elhigu** [comment]
I don't think that knex even should support so complicated query generation, which first needs to get data from database to be able to decide how to continue.  Hopefully there wont be any other cases like that. Usually with schema builder .toSQL() should return just all the queries in an array that were added.

**Comment by elhigu** [comment]
The best solution would be to change that `renameColumn` to work in a way that it would work in a way that it would not need to fetch data from DB for building the queries. Maybe in a way that API user provides enough information to it (the same way that is done for example when user likes to modify already created native enum).

**Comment by pyudroi** [comment]
@lorefnon @elhigu : Thanks for your inputs. 

In below code of 'mysql:rename' -  I see there is push of initial query (show fields..) mentioned in my example. I can't seem to understand enough on why other queries are not going in the array.

This has become a bit of an issue in our migrations - can anybody help fix it.


```
// Renames a column on the table.
  renameColumn(from, to) {
    const compiler = this;
    const table = this.tableName();
    const wrapped = this.formatter.wrap(from) + ' ' + this.formatter.wrap(to);

    this.pushQuery({
      sql:
        `show fields from ${table} where field = ` +
        this.formatter.parameter(from),
      output(resp) {
        const column = resp[0];
        const runner = this;
        return compiler.getFKRefs(runner).then(([refs]) =>
          new Promise((resolve, reject) => {
            try {
              if (!refs.length) {
                resolve();
              }
              resolve(compiler.dropFKRefs(runner, refs));
            } catch (e) {
              reject(e);
            }
          })
            .then(function() {
              let sql = `alter table ${table} change ${wrapped} ${column.Type}`;

              if (String(column.Null).toUpperCase() !== 'YES') {
                sql += ` NOT NULL`;
              } else {
                // This doesn't matter for most cases except Timestamp, where this is important
                sql += ` NULL`;
              }
              if (column.Default !== void 0 && column.Default !== null) {
                sql += ` DEFAULT '${column.Default}'`;
              }

              return runner.query({
                sql,
              });
            })
            .then(function() {
              if (!refs.length) {
                return;
              }
              return compiler.createFKRefs(
                runner,
                refs.map(function(ref) {
                  if (ref.REFERENCED_COLUMN_NAME === from) {
                    ref.REFERENCED_COLUMN_NAME = to;
                  }
                  if (ref.COLUMN_NAME === from) {
                    ref.COLUMN_NAME = to;
                  }
                  return ref;
                })
              );
            })
        );
      },
    });
  },
```

**Comment by elhigu** [comment]
Looks like extra queries are made to automatically fix also foreign keys... so other queries are not going to the array because they are not know until first query has been ran.

IMO correct fix for this would be to change API to require that user also tells knex, which foreign key references must be fixed after renaming the column. Then if someone wants more automated process of inspecting data from schema automatically... 

Following that guideline `knex` would get simpler and more robust library which would be safer for people to use to make more complex and automated functionality on top of it.

**Comment by elhigu** [comment]
@pyudroi as a workaround you may write renaming and foreign key fixing as `.raw` queries.

**Comment by pyudroi** [comment]
> IMO correct fix for this would be to change API to require that user also tells knex, which foreign key references must be fixed after renaming the column. Then if someone wants more automated process of inspecting data from schema automatically...

I believe knex should fix foreign key references while renaming columns. This is since user would not want to like to leave a dangling foreign key reference to to old column name - also I guess that underlying database would not allow for it.

> Looks like extra queries are made to automatically fix also foreign keys... so other queries are not going to the array because they are not know until first query has been ran.

From the renameColumn code (although I do not completely understand it) - looks like foreign keys are looked up. If you know the solution - could you please make a fix for it.

**Comment by o1lab** [comment]
@elhigu : would you be able to get a fix for this please ?

**Comment by elhigu** [comment]
I cannot. My opinion is that `renameColumn` is too high level function that knex should not even provide it. It seems to require too much inspecting database schema, before being able to do it so that it is too complex to implement in many databases. Especially with sqlite which requires copying data to temporary table etc.

**Comment by pyudroi** [comment]
@elhigu : appreciate your reply. It can be seen that renameColumn requires multiple statements in some cases. But a easier fix for renameColumn in my case would be to return the simple alter statement  - that would be great solution. Because, it will be user's responsibility to handle cases where it has a foreignKey reference or constraints etc. Then migrations (pseudo code) would like below

```
.dropForeignKey() 
.renameColumn() 
.foreign() 
```

For sqlite's case : sqlite doesn't support renameColumn - so an appropriate error should be thrown instead.
