### ISSUE TITLE
Make a Select distinct with innerJoins 

### ISSUE THREAD

**Issue by gardheamsantos00** [tgriesser/knex#3374]
o try make one select distinct with knex:

my SQL

`SELECT DISTINCT Q.ID_FASE,Q.ID_PROPRIEDADE,R.ID_PERGUNTA,R.RESULTADO, R.JUSTIFICATIVA FROM QUE_RESPOSTA R 
INNER JOIN QUE_ATENDIMENTO Q ON Q.ID_ATENDIMENTO = R.ID_ATENDIMENTO
INNER JOIN PROPRIEDADE PROP ON PROP.ID_PROPRIEDADE = Q.ID_PROPRIEDADE
INNER JOIN PESSOA P ON P.ID_PESSOA = Q.ID_CONSULTOR 
INNER JOIN USUARIO U ON U.ID_PESSOA = P.ID_PESSOA
INNER JOIN USUARIO_PRODUTOR UP ON UP.ID_USUARIO = U.ID_USUARIO
WHERE U.ID_USUARIO = 24 AND ID_FASE = 1 ORDER BY Q.ID_PROPRIEDADE`

My knex query 

`const data = await db.distinct('Q.id_fase','Q.id_propriedade'
                              ,'R.id_pergunta','R.resultado','R.justificativa')
                      .from('que_resposta AS R')
                      .innerJoin('que_atendimento AS Q', 'Q.que_atendimento','R.que_atendimento')
                      .innerJoin('propriedade AS PROP', 'PROP.id_propriedade','Q.id_propriedade')
                      .innerJoin('pessoa AS P', 'P.id_pessoa','Q.id_consultor')
                      .innerJoin('usuario AS U', 'U.id_pessoa','P.id_pessoa')
                      .innerJoin('usuario_produtor AS UP', 'UP.id_usuario','U.id_usuario')
                      .where('U.id_usuario', req.params.id ).and('id_fase', 1)
                      .orderBy('Q.id_propriedade')`

the return is { }, why ?

**Comment by elhigu** [comment]
Check differences in your generated SQL and the original query and check especially that all identifiers are written correctly in case-sensitive manner.
