### ISSUE TITLE
Raw bindings for json property names

### ISSUE THREAD

**Issue by alechirsch** [tgriesser/knex#3381]
I am developing a dynamic and generic way to filter on jsonb properties in postgresql. I am running into a problem with providing json properties as bindings when generating the queries. 
Using `??` to define a column name and `?` to define the value I am testing against.

Here is an example of a raw query:
`qb.distinct().select(knex.raw('??->??->>?? as ??')).orderByRaw('??->??->>?? asc')`

This generates a query that looks like this:

`select distinct "pet"."style"->"looks"->>"color" as "color" from "pet" order by "pet"."style"->"looks"->>"color" asc`

This is a syntax error in postgres, it expects that all property names for the json column to be surrounded by single quotes instead of double quotes. The correct version of the query is this:

`select distinct "pet"."style"->'looks'->>'color' as "color" from "pet" order by "pet"."style"->'looks'->>'color' asc`

I thought I might be able to use single question marks instead to achieve the single quotes, however that generates the following:

`qb.distinct().select(knex.raw('??->?->>? as ??')).orderByRaw('??->?->>? asc')`

`select distinct "pet"."style"->?->>? as "color" from "pet" order by "pet"."style"->?->>? asc`

This query produces the following error, and It probably would not work anyways for passing in json column names as bindings

`SELECT DISTINCT, ORDER BY expressions must appear in select list`

There needs to be a way to provide a json column name as a binding to a raw knex query, since I cannot allow for SQL injection. Perhaps using three question marks to indicate that the quotes should be single instead of double depending on the database being used would solve this problem.

**Comment by elhigu** [comment]
You can use the #> operator instead of ->. Check for example what kind of jsonb references objection generates. There is no reason why knex should implement special ??? for different quoting in this case. It would mean that knex should implement safe escaping for those which is out of scope of knex (like knex doesnt provide safe escaping for values either)

**Comment by alechirsch** [comment]
@elhigu Thanks for the suggestion, I will look into implementing with that other syntax. From the looks of it, this should work.
