### ISSUE TITLE
`this.dialect` is useful

### ISSUE THREAD

**Issue by mytototo** [tgriesser/knex#3384]
Hi,

I know you want to deprecate `this.dialect` so we can use `config.client` instead. Here is the warning:
```
Using 'this.dialect' to identify the client is deprecated and support for it will be removed in the future. Please use configuration option 'client' instead.
```

Looks logical.

However, `new Dialect()` is still useful when we want to use node modules that don't allow dynamic requiring, such as `pkg`.

Dynamic `require` is at https://github.com/tgriesser/knex/blob/master/lib/knex.js#L43

Instead of passing a `client` string, I'd like to keep doing this:
```js
const Dialect = require('knex/src/dialects/postgres/index');
const db = new Dialect({});
```

This way, I can continue using third-party module that don't support dynamic requiring.

What do you think ?
Thank you.

**Comment by elhigu** [comment]
`dialect` and `client` configuration attributes are aliases for the same thing. So deprecating `dialect` will not affect to anything. 

Support for third party dialects will work as described in here: https://github.com/tgriesser/knex/blob/master/CONTRIBUTING.md#i-would-like-to-add-support-for-new-dialect-to-knex-is-it-possible

**Comment by mytototo** [comment]
Got it, I didn't know this way of using existing dialect.
Thank you!
