### ISSUE TITLE
Portable Oracle Client Library

### ISSUE THREAD

**Issue by Gerodork** [tgriesser/knex#3385]
# Environment

Knex version: 0.19.1
Database + version: Oracle 11.2
OS: Windows 10

@atiertant 
# Questions about how to use knex
I’m trying to use Knex to connect to different databases which are either MSSQL or Oracle.
When I try to use the oracle connector, it asks for the Oracle Client Library.
While I can very well install it on my computer and make it work, the app’s goal is to be fully portable. My users will not be able to install it by themselves. 
Is there any way to wrap the Oracle Client into knex, the oracleDb dependency, or into my app so that it won’t go look for it in the PATH, but locally in any directory I may point it to.

Thanks for your help.

**Comment by kibertoad** [comment]
Unfortunately, it is not possible. First of all, knex does not implement drivers on its own, but relies on existing ones. Second, even if it did, Oracle client is proprietary closed software that is likely to be illegal to reverse engineer for reimplementation.
That said, Oracle client resolution is not part of knex, but of oracle node driver. You might want to check with it regarding how possible it is to use bindled client. 
All in all Oracle is painful to use in Node. js ecosystem, I recommend against it if by any means possible

**Comment by Gerodork** [comment]
Thank you for your quick response. Have a good day.

________________________________
De : Igor Savin <notifications@github.com>
Envoyé : Monday, August 5, 2019 4:04:52 PM
À : tgriesser/knex <knex@noreply.github.com>
Cc : NISIO Thibault <thibault.nisio@epsi.fr>; Author <author@noreply.github.com>
Objet : Re: [tgriesser/knex] Portable Oracle Client Library (#3385)


Unfortunately, it is not possible. First of all, knex does not implement drivers on its own, but relies on existing ones. Second, even if it did, Oracle client is proprietary closed software that is likely to be illegal to reverse engineer for reimplementation.
That said, Oracle client resolution is not part of knex, but of oracle node driver. You might want to check with it regarding how possible it is to use bindled client.
All in all Oracle is painful to use in Node. js ecosystem, I recommend against it if by any means possible
