### ISSUE TITLE
jsonb function in schema builder appears to be broken in mysql

### ISSUE THREAD

**Issue by lorefnon** [tgriesser/knex#3386]
# Environment

Knex version: 0.19.0
Database + version: mysql 8.0.17
OS: [debian](https://github.com/docker-library/mysql/blob/master/8.0/Dockerfile#L1)

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do

   `jsonb` column builder in mysql should fallback to json: 

   As per the docs: 

   > jsonb — table.jsonb(name)
   > Adds a jsonb column. Works similar to table.json(), but uses native jsonb type if possible.

2. Error message

   `ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'undefined)' at line 1`

3. Reduced test code, for example in https://npm.runkit.com/knex or if it needs real
   database connection to MySQL or PostgreSQL, then single file example which initializes
   needed data and demonstrates the problem.

```
const config = { client: 'mysql', connection: process.env.DB_CONNECTION_STRING }
const knex =  require('knex')(config);
> knex.schema.createTable('users', t => { t.increments('id'); t.jsonb('metadata') }).toSQL()
[ { sql:
     'create table `users` (`id` int unsigned not null auto_increment primary key, `metadata` undefined)',
    bindings: [] } ]
```

*Note:* `undefined` is used as type of `metadata`.

**Comment by kibertoad** [comment]
@lorefnon Released in 0.19.2
