### ISSUE TITLE
ERROR: Request Error: {query} - Connection Lost - Read ECONNRESET [mssql]

### ISSUE THREAD

**Issue by andrew-caines** [tgriesser/knex#3387]
# Environment

Knex version: **"knex": "^0.19.1",**
Database + version: **MSSQL (Azure)**
OS: **Unbuntu**

Select applicable template from below.
@smorey2 

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do

**I have a base64 image which i store, when i was developing on windows, this worked without issue, now what I am running it on Unbuntu (re-installing from package.json) i get this error on only 1 route, and only 1 query.  All of my other writes/reads to the DB work without issue. It is also the largest insert by far.**

2. Error message
``
[/saveDelivery] ERROR: RequestError: insert into [driver_CompletedDeliveries] ([amtItems], [bins_recovered], [deliveryTime], [driverID], [imgDataBase64], [moneyCollected], [signeeName], [targetID], [type]) values (@p0, @p1, @p2, @p3, @p4, DEFAULT, @p5, @p6, @p7) - Connection lost - read ECONNRESET
``
3. Reduced test code, for example in https://npm.runkit.com/knex or if it needs real
   database connection to MySQL or PostgreSQL, then single file example which initializes
   needed data and demonstrates the problem.
``

router.post('/saveDelivery', async (req, res) => {
   
    const knex = req.app.locals.knex; //This is my knex instance.
    const { clientID, Image, Amount, Signee, Time, Type, Money, PickedUp } = req.body;
    if (!req.session.driverID) {
        res.send({ success: false, message: 'You must be logged in, and a driver to save deliveries.' });
    }
    const dt = new Date(Time).toISOString().slice(0, 19).replace('T', ' ');
    try {
        await knex('driver_CompletedDeliveries')
            .insert({
                type: Type,
                targetID: clientID,
                bins_recovered: PickedUp,
                amtItems: Amount,
                imgDataBase64: Image,
                signeeName: Signee,
                deliveryTime: dt,
                driverID: req.session.driverID,
                moneyCollected: Money
            });
        res.send({ success: true, message: 'Delivery Saved successfully!' });
    } catch (err) {
        console.error('[/saveDelivery] ERROR: ${err}');
        res.send({ success: false, message: '[/saveDelivery] Error Saving: ${err}' });
    }
});
``
Ultimately:  When i do this request on my dev-station (windows 10, with same package.json) it works without issue.  When I moved it to production it started having this issue, in this one route, there are about 30 other routes which use all the CRUD features to the same database, and tables.  This is the only one that has the issue.  If i console log the req,body it does have the fields (i suspected it may have been a post payload size issue, it wasnt). 

Has anybody seen this before?  This is my connection string 
```
const knex = require('knex')({
    client: 'mssql',
    connection: {
        server: 'THEDATABASE.database.windows.net',
        user: 'USER',
        password: 'PASSWORD',
        database: 'da',
        options: {
            port: 1433,
            encrypt: true  // mandatory for microsoft azure sql server
        }
    },
    pool: { min: 2, max: 10 }
});
app.locals.knex = knex; //Put Knex on req.app.locals.knex
```
Any ideas?!  Anything more you would require to see? 
Package.json
```

"knex": "^0.19.1",
    "mssql": "^5.1.0",

```

**Comment by andrew-caines** [comment]
Oh, also for clarification, the payload size of the base64 Image is about 8k  (only)

**Comment by andrew-caines** [comment]
![image](https://user-images.githubusercontent.com/12756948/62659846-bbf98380-b929-11e9-9d3b-a7df0603cb6e.png)

When I run the same code in RunKit, it generates the same error!

**Comment by andrew-caines** [comment]
Further update, I re-installed on two new servers. 1 Windows Server 2019. Installs and runs 100%. Installed on Unbuntu 18.04 Fresh, gives same error.
This is now making me suspicious it may be a low level driver or library that is used by Knex, as the windows binary/library/whatever works and the Linux one does not. Side by Side, the win32 works, the Linux does not.
Could this be a issue with Tedious or mssql in general?!

**Comment by kibertoad** [comment]
@andrew-caines Are you positive that there are no network/connectivity issues that prevent Ubuntu from connecting? Error itself looks like something that you would get when server itself is refusing connection, before DB itself kicks in. Can you try connecting to DB directly using Linux mssql cmdline client from Ubuntu in question and see if that works?

**Comment by kibertoad** [comment]
If it does work, and problem is only on that one query, it does sound like a low-level issue, as knex delegates pretty much all the down-to-metal stuff to driver in question, so node-mssql might be a good place to start investigation.

**Comment by andrew-caines** [comment]
All queries work, until the size of the payload is over 4096 bytes, the moment it hits 4k, it breaks.  Basically, when i have some Base64 (varchar(MAX)) data to the server it breaks, i know its 4096, because if i send 4097 it gives the error, 4096 it doesn't.

Like i said, wierdly, on Windows it doesn't throw this error. Something about the base library that knex uses on linux?

**Comment by elhigu** [comment]
You should try to reproduce your problem using mssql (or tedious) driver directly and ask help from their forums. This is certainly not caused by knex.

**Comment by MuhammadZaidSE** [comment]
@andrew-caines did you solve this issue? If yes! what was the solution?
