### ISSUE TITLE
Suggest rephrase some words in README.md

### ISSUE THREAD

**Issue by Nomia** [tgriesser/knex#3388]
In the README.md file of this repo, it says: `Node.js versions 8+ are supported.`

But what's the `requirement`? 
Does that mean: versions below 8 are `not supported`, if that's so, I suggest rephrase that `requirement` to:
```
Node.js version below 8 are not supported
``` 
or 
```
To use knex, make sure your node.js version is 8+
```

Sorry, my mother language is not English. That sentence really confused me.

-------------------------------  the problem  --------------------------------
some code in the file `knex/lib/client.js` are not supported in node.js v7.x:
```
const tarnPoolConfig = {
      ...this.getPoolSettings(config.pool),
};
```
the code above will cause an error in node.js 7.x:
```
SyntaxError: Unexpected token ...
```

**Comment by elhigu** [comment]
Currently node versions 8,10 and 12 are supported. IIRC 8 will be deprecated after few months.

**Comment by elhigu** [comment]
`Node.js versions 8+ are supported.`sounds clear enough to me.  If you want to send PR to make it more clear I will merge it though.
