### ISSUE TITLE
How to use ’partition by‘ with knex?

### ISSUE THREAD

**Issue by yeongjet** [tgriesser/knex#3391]
How to generate sql like 
`with a as (select ROW_NUMBER() over (partition by activity_id order by activity_id desc, count desc, updated_at asc) rank, * from "activity_ranklist" where company_id = ${companyId} and openid like '%b%')
select * from a`
Is it support ’partition by‘ in knex?
#2289

**Comment by elhigu** [comment]
This can be done only with help of knex.raw. You need to pass raw query to `.with`.

**Comment by acro5piano** [comment]
Seems that `partition by` with order is not supported by Knex.

**Comment by eugenelet** [comment]
Is there any update on this issue? Is there an alternative for this? E.g. a mixture of Knex functions with raw db query to create table with partitions using Knex migration?

**Comment by MauriDalga** [comment]
There is an example that has worked for me.
```javascript
knex('table').select(knex.raw('column1, column2, count(*) over(...) as something')).where(...);
```
