### ISSUE TITLE
Using Knex on js arrays (for unit testing)

### ISSUE THREAD

**Issue by TimUntersberger** [tgriesser/knex#3392]
I have recently thought about how to test my knex queries and came to the random idea that being able to use the knex queries on js arrays for testing purposes would be really convenient.

Is there already a way to do this and if no how could someone implement something like that (Maybe as a driver)?

**Comment by thetutlage** [comment]
Why not run actual queries?

**Comment by kibertoad** [comment]
@TimUntersberger Why not just use an in-memory SQLite as a DB? Then you don't need any actual infrastructure and can still test your queries.

**Comment by kibertoad** [comment]
That said, I highly recommend having proper integration tests for your queries. Otherwise you are likely to overlook problems with your migrations, foreign keys, misspellings etc

**Comment by TimUntersberger** [comment]
@thetutlage I actually forgot what the specific reason was for opening this issue compared to just running actual queries. Closing the issue.
