### ISSUE TITLE
Oracle: inserting of multiple rows fails when one of the fields is oracle.raw()

### ISSUE THREAD

**Issue by Kano098** [tgriesser/knex#3404]
# Environment

Knex version: 0.19.0
Database + version: Oracle 11g
OS: Ubuntu 16.04

# Bug

The next code:
```
const values = [
    { field: 'value1', updateDateTime: knex.raw('CURRENT_TIMESTAMP') },
    { field: 'value2', updateDateTime: knex.raw('CURRENT_TIMESTAMP') }
  ];
knex.insert(values).into('table');
```

will generate the next sql:
```
BEGIN 
  EXECUTE IMMEDIATE 
    'insert into "table" ("field", "updateDateTime") values (:1, CURRENT_TIMESTAMP)' 
    USING 'value1', current_timestamp; 

  EXECUTE IMMEDIATE 
    'insert into "table" ("field", "updateDateTime") values (:1, CURRENT_TIMESTAMP)' 
    USING 'value2', current_timestamp; 
END; 
```

Oracle throws the `ORA-01006: bind variable does not exist` error after executing it.

In case of inserting 1 row it works fine cause knex doesn't wrap queries into `EXECUTE IMMEDIATE`

I would appreciate any help.
@atiertant

**Comment by elhigu** [comment]
Sounds like oracle doesn't support inserting multiple lines well. I  would suggest inserting rows one by one in this case. If you have solution how to implement inserting multiple rows in single query without wrapping them to execute immediate lets reopen and request PR which would implement that solution.
