### ISSUE TITLE
[Question] joining 2 queries using transaction

### ISSUE THREAD

**Issue by felixmosh** [tgriesser/knex#3408]
I'm implementing `.paginate` query builder extend method.
It looks something like that:
```javascript
const users = await knex('users').paginate({perPage: 20});
```
This query should look like (MySQL): 
```sql
Select * from `users` limit 0, 20;
```
And the bonus is that it should attach to the return value `total` property.
In order to get the **total** number of users I need to make an additional Query, I've managed to "combine 2 query result" by using a transaction.

This code is inside the implementation of `.paginate`

```javascript
function paginate({ perPage }) {
  // ... validations
  const offset = //offset calc;
  const limit = perPage;

  // This will paginate the data itself
  this.offset(offset).limit(limit);

  return this.client.transaction(async trx => {
    const result = await this.transacting(trx);
    const countQuery = await this.clone()
      .clearSelect()
      .clearOrder()
      .count("* as total")
      .offset(0)
      .first()
      .transacting(trx);

    return { data: result, total: countQuery.total };
  });
}

```

WDYT about this implementation? is it OK to use transaction this way? Do you have any other method?

**Comment by elhigu** [comment]
Knex doesn't really support building multiple queries for single builder... this implementation actually breaks knex's normal behaviour where query is first built and then executed separately with then.

Probably this could be done as single query too, but would require certain DB or multiple implementations for different dialects. At least with postgres this could be done by returning subquery rows as array or jsonb.

This might work, but I'm not sure at all what will happen in case when you have already started transaction and you are going to do paging query inside external transaction.

**Comment by felixmosh** [comment]
@elhigu thanx for your response.
