### ISSUE TITLE
Detecting whether `knex` is a transaction

### ISSUE THREAD

**Issue by olalonde** [tgriesser/knex#3424]
I have a few functions that looks like this:

```javascript
export const create = async ({ userId }, { knex }) => {
   // do something
})
```

where `knex` can either be a transaction object returned by knex.transaction() e.g.: `knex.transaction(tx => create({ userId }, { knex: tx }))`.

However in some functions, I want to ensure that the `knex` is actually a transaction object (and otherwise start a new transaction). Is there a public API to find that out? e.g. `knex.isTransaction`

**Comment by kibertoad** [comment]
@olalonde I think you can use `isTransaction` field that is set on transactors. If it works out for you, please consider submitting a PR for documentation on it, as I see no reason why it couldn't be public API.

**Comment by elhigu** [comment]
created issue to docs repo.

**Comment by olalonde** [comment]
Oh thanks, I didn't realize there was already such a prop, would indeed be a good idea to document.
