### ISSUE TITLE
afterConnect - "conn.query is not a function"

### ISSUE THREAD

**Issue by gotdan** [tgriesser/knex#3430]
# Environment

Knex version: 19.3
Database + version: Sqlite3
OS: OSX

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do:
Following the afterCreate example in docs, I'm trying to add a second db to a sqlite connection after the connection is created:
	```
	...
	pool: {
		afterCreate: (conn, done) => {
			conn.query("ATTACH DATABASE './db2.db' AS db2", (err) => {
				done(err, conn);
			});
	}
	```

2. Error message:
Unhandled rejection TypeError: conn.query is not a function

**Comment by elhigu** [comment]
`conn` is database driver's connection object. You need to check from sqlite3 drivers documentation how to run queries with it. That example is for node-pg driver.
