### ISSUE TITLE
How do I create a query that utilises 'use index'

### ISSUE THREAD

**Issue by olsw** [tgriesser/knex#3433]
The current query I have

`db.connection
    .count('un.id AS notesCount')
    .from('user_notes AS un')
  query.where('un.user_id', userId)
  query.join('user_note_types AS unt', 'un.type_id', 'unt.id')`

This would create sql similar to:
`select count(un.id) as notesCount from user_notes as un inner join user_note_types as unt `
what I would like to achieve is that the final sql includes a 'use index':
`select count(un.id) as notesCount from user_notes as un use index (idx_user_id) inner join user_note_types as unt`

I cant seem to get the 'use index' syntax correct. Any suggestions?

**Comment by elhigu** [comment]
It seems to work like this:

```
knex
  .select(knex.raw('count(??) as notesCount', ['un.id']))
  .from(knex.raw('user_notes as un use index (idx_user_id)'))
  ...
```

https://runkit.com/embed/rjwoanhuza7k
