### ISSUE TITLE
Cannot access faker.js from Knex seed file

### ISSUE THREAD

**Issue by reinvanimschoot** [tgriesser/knex#3453]
# Environment

Knex version: 0.19.3
Database + version: Postgres 11.5
OS: MacOS Mojave

Select applicable template from below.
If issue is about oracledb support, tag @ atiertant. For MSSql tag @ smorey2.
Rest of dialects don't need tags.
If issue is about TypeScript definitions, tag @ lorefnon.

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do

I am trying to use faker to generate some random data to populate my database after creation.
I am using TypeScript. 
The import statement I use in my knex generated seed file is:

`import * as faker from 'faker';`

2. Error message

I get `TS2307: Cannot find module 'faker'`.

3 Other info

I tried using `require` but I got the same problem. 

I have the latest version of Faker installed including the typings.

My tsconfig is as follows:

```
{
  "compilerOptions": {
    "sourceMap": true,
    "outDir": "dist",
    "lib": [
      "esnext",
      "dom"
    ],
    "noImplicitAny": true,
    "noImplicitThis": true,
    "alwaysStrict": true,
    "strictBindCallApply": true,
    "strictFunctionTypes": true,
    "skipLibCheck": true,
    "strict": true,
    "esModuleInterop": true,
    "strictPropertyInitialization": false
  },
  "exclude": [
    "node_modules"
  ]
}
```

Cheers!

**Comment by elhigu** [comment]
doesnt' seem like a knex bug.
