### ISSUE TITLE
how to use the formatter?

### ISSUE THREAD

**Issue by deadlyicon** [tgriesser/knex#3454]
# Quick Question:

I am doing this to convert an array of strings into the sql values list i need in a query I am constructing in the raw. Is there a way to use the internal formatter instead of doing this:

`return knex.whereIn('x',values).toString().split('select * where "x" in ')[1];`

thanks!

**Comment by elhigu** [comment]
Looks like you are doing something really sketchy and I have no idea why would you like to do that and you probably should not be doing that unless you are really writing some hack just for yourself to use.

That being saind. You could maybe use `knex.raw('?', [values]).toString()`. Note that toString() should not be used for anything else except helping to debug with knex. Resulting string is not guaranteed to be sql injection proof and it might have even wrong values, depending on parameters you are passing.

**Comment by deadlyicon** [comment]
I know this is really weird. That is why I am looking for a better solution. The task of taking an array of strings like `['a','b','c']` and converting them to `"('a','b','c')"` is not a weird task. It's something knex has a formatter helper for. For example it's done (eventually) inside of `.whereIn('x',['a','b','c'])`. 

This seems like a pretty standard feature of a library like knex. That feature being turning an array of strings into a sql-injection-proof set of values in proper sql format. 

Does anyone else have any suggestions on how I might use the formatter that knex uses internally to accomplish this? I think this is it: https://github.com/tgriesser/knex/blob/0.14.6/src/formatter.js#L67

**Comment by deadlyicon** [comment]
@elhigu would you mind re-opening this issue?

**Comment by elhigu** [comment]
There is no plan to expose formatter outside of knex. IIRC There are some other feature requests for example for array literals, which could help in your use case.

This issue is not going to be reopened, because this is not a bug report neither proper feature request.

> This seems like a pretty standard feature of a library like knex. That feature being turning an array of strings into a sql-injection-proof set of values in proper sql format.

One should pass those strings as value bindings to the driver which takes care of properly handling sql injection protection. It is not goal for knex to implement that functionality.

**Comment by deadlyicon** [comment]
@elhigu thank you so much for your help.
