### ISSUE TITLE
How to run only new seeds using knex().seed.run() like knex().migrate.latest()?

### ISSUE THREAD

**Issue by saurabhsinghhauhan** [tgriesser/knex#3456]
# Environment

Knex version:0.19.2
Database + version: Mysql , 14.14 Distrib 5.7.27, for Linux (x86_64) using  EditLine wrapper
OS: Linux

# Feature discussion / request

Hello @smorey2,  I'm using knex and in my use case when I started a project there are some seeds which I run using below code snippet.

```
module.exports.runSeed = async () => {

    // run seed
    await db().seed.run()
        .then(m => console.log('db seeded', m))
        .catch(err => {
            throw err;
        });
}
```

After some time I need to create more seeds but now I'm facing an issue that every time I have to pass the seed name to my function in config. 

```
 // seed configuration
    const config = {
        extension: '.js',
        specific: '05_ips.js'
    }
```

Is there any way so knex can autodetect which seeds are new and only run those seeds, as same happens in migration.

**Comment by elhigu** [comment]
if you need to keep track of already ran seeds you should be using migration scripts instead.
