### ISSUE TITLE
chainable conjunctions 

### ISSUE THREAD

**Issue by calvinmetcalf** [tgriesser/knex#346]
taking a page from [chai's](http://chaijs.com/api/bdd/) book, instead of

```js
knex('users').where(function() {
  this.where('id', 1).orWhere('id', '>', 10)
}).orWhere({name: 'Tester'})
```

something like 

```js
knex('users').where(function() {
  this.where('id', 1).or.where('id', '>', 10)
}).or.where({name: 'Tester'})
```

one's that could be helpful:

- not
- in
- exists
- null (though reserved word issues?)
- raw

**Comment by elhigu** [comment]
Kind of nice, but really doesn't add much to current syntax. Also it would make API / testing more complex when we need to support multiple ways of doing the same queries.
