### ISSUE TITLE
Upsert with Postgres not working

### ISSUE THREAD

**Issue by grahamjenson** [tgriesser/knex#365]
I was attempting to define an upsert (update or insert) function as described [here](http://www.the-art-of-web.com/sql/upsert/), with code like:

```
action = 'view'
weight = 10
insert = @knex('actions').insert({action: action, weight: weight}).toString()
update = @knex('actions').where(action: action).update({weight: weight}).toString()

query = "BEGIN; LOCK TABLE actions IN SHARE ROW EXCLUSIVE MODE; WITH upsert AS (#{update} RETURNING *) #{insert} WHERE NOT EXISTS (SELECT * FROM upsert); COMMIT;"
@knex.raw(query)
```

This will cause a "error: syntax error at or near "WHERE"" because of the insert statements use of ```values```.
A workaround for this is to change the values statement to a ```select``` statement as described [here](http://stackoverflow.com/questions/15840922/where-not-exists-in-postgresql-gives-syntax-error). This can be done with the code ```insert = insert.replace(/\svalues\s\(/, " select ")[..-2] ``` 

Graham

**Comment by elhigu** [comment]
knex doesn't support upsert yet, there are other issues about feature request
