### ISSUE TITLE
It's not possible to create complex PK because of too long name

### ISSUE THREAD

**Issue by hsz** [tgriesser/knex#388]
I am creating a table:

    knex.schema.createTable('tblscheduletypes', function (table) {
        table.primary(['deviceId', 'channelNumber', 'schedTypeId']);
        // ...
    })

`.primary()` metods creates following `SQL`:

    alter table `tbldevicescheduleconfig` add primary key tbldevicescheduleconfig_deviceid_channelnumber_schedtypeid_primary(`deviceId`, `channelNumber`, `schedTypeId`)

So the name of PK is 66 characters long.

It would be nice to allow to change the naming policy or set specific name.

**Comment by wubzz** [comment]
I'm closing this in favor of #1430 where I will be going through this more in-depth.

**Comment by elhigu** [comment]
@wubzz are you sure about that issue number? Doesn't sound the same with this.

**Comment by elhigu** [comment]
Ah... ok it is about the documentation part 👍  Yep agreed that no need to have any better fix for this, but just document that primary() takes index name as a parameter.
