### ISSUE TITLE
Shortcut for foreign key definitions

### ISSUE THREAD

**Issue by StephanHoyer** [tgriesser/knex#389]
instead of 

    table.integer('booking_id').unsigned().references('booking.id')

maybe it would make sense to do

    table.reference('booking', 'id', 'booking_id')

the last two args even can be defaulted to the values. If this is a good idea, I might be creating a pull request.

BTW: Awesome stuf you build here and with bookshelf! The ORM/Query-Builder I always wanted ;)

**Comment by elhigu** [comment]
There hasn't been much support for this. Closing for  now (cleaning up / tagging old issues).
