### ISSUE TITLE
when knex is installed globally this line causes a failure

### ISSUE THREAD

**Issue by samccone** [tgriesser/knex#395]
https://github.com/tkellen/node-liftoff/blob/a5f0f1b0dce78bc37a5ad1ae0ea374437bb4efe8/index.js#L81

Since the modulePath is empty thus it thinks it is not installed, however since the module is installed globally the reported path is valid.

-------------

As a side note why is this even here, since how can you even invoke the CLI command without even having knex installed? 

Perhaps the root of the problem is due to `node-liftoff` not resolving symlinks, meh just a thought

**Comment by elhigu** [comment]
Can't reproduce.
