### ISSUE TITLE
Paging in different databases like MS SQL Server or Oracle

### ISSUE THREAD

**Issue by gpetrov** [tgriesser/knex#41]
Hi,

Are your database adapters flexible enough so that you can generate sql select statements that have a complete different sql for paging like MS SQL Server and Oracle? I see your current adapters are only for very similar databases that support the LIMIT statement.

http://www.sqlteam.com/article/server-side-paging-using-sql-server-2005
http://weblogs.asp.net/fbouma/archive/2007/05/21/api-s-and-production-code-shouldn-t-be-designed-by-scientists.aspx

Maybe you can post an MS SQL Server 2005+ adapter as well?

That will be awesome!

**Comment by JoaoCnh** [comment]
Any word on the MSSQL Server? It's a deal breaker for me. I was really liking knex but I must connect to SQL Server otherwise I'll have to look to another place :|

**Comment by elhigu** [comment]
There are now oracle and mssql dialects implemented. New issues about them may be added to new issues :)
