### ISSUE TITLE
Icons for Knex

### ISSUE THREAD

**Issue by joepie91** [tgriesser/knex#449]
@Thibaut over at Thibaut/devdocs#117 has offered to add Bookshelf and Knex documentation to DevDocs (given that there is no DocSet support yet), but is in need of a 16x16 and 32x32 icon for both. I can provide a downscaled version of the Bookshelf page header for now, but Knex doesn't seem to have any kind of square logo or favicon readily available.

My idea was to perhaps just have the white piece of Knex (perhaps in a different color?) as it would easily fit a square logo, but I don't have the source files for the current Knex page header. Could you provide a 32x32 and 16x16 icon for Knex?

**Comment by tgriesser** [comment]
Hey @isaacdurazo I was thinking it might be simple to just use http://commons.wikimedia.org/wiki/File:Knex-Connect-White.svg combined with the same font as the Bookshelf logo - what do you think?

**Comment by isaacdurazo** [comment]
Hey @tgriesser Thats a great idea! maybe something like this?
![oqvxwr5bzqk9kqsnb-dyuloqthmfo46buyvh-mdknse](https://cloud.githubusercontent.com/assets/1379244/7433603/f78c6d00-efe7-11e4-86c1-d899036d3b1d.png)

**Comment by tgriesser** [comment]
Yeah that's what I was thinking, though that specific piece (the connector) is white in K'Nex - not sure if it makes sense to change the color (the image is public domain too so it should be good to use)

Other available pieces:

http://en.wikipedia.org/wiki/K%27Nex_pieces#Photo_Gallery

**Comment by isaacdurazo** [comment]
@tgriesser I personally think it's fine to use a different color than white. Another thing if we use white, we would need to keep the black outline, which doesn't work when the icon is in small sizes

**Comment by tgriesser** [comment]
Sounds good, let's do it

**Comment by isaacdurazo** [comment]
Greay @tgriesser I'll prepare the files and send them to you later today.  Do you want me to email them?

**Comment by tgriesser** [comment]
Email is great, or you can just add them here - https://github.com/bookshelf/assets whichever is easiest for you

Thanks again!

**Comment by wubzz** [comment]
Seeing as the suggested icon is now on [knexjs.org](http://knexjs.org) and the latest activity in given repository is roughly one year ago, i'm going to assume this is resolved.
