### ISSUE TITLE
Dialect-agnostic helpers and expressions

### ISSUE THREAD

**Issue by myndzi** [tgriesser/knex#465]
Per our conversation on IRC, opening a ticket.

I've been using knex a lot lately, and one thing that has been unwieldy for me is when I want or need to perform an SQL expression, particularly using certain kinds of functions, e.g. a random value, the current date, group concat, and so on. These things may vary by the DB in use ('rand()' vs 'random()', 'current_date' vs 'date()', 'array_agg()' vs 'group_concat'**)

** I understand these are not exactly the same thing

Secondly, making use of expressions at all is a bit unwieldy too. If I want to select anything other than a plain column name, I have to use knex.raw, which is a bit bulky, and contextually ambiguous - it's hard to tell how exactly the 'raw' text you specify will be combined with the query at large, when it's available, etc.

Both of these things could be addressed at the same time by beginning an expression API of some sort to let you build query expressions; for example, `knex.select(knex.random().raw('* 2'), 'foo')` or something like that. Mixing in mathematical stuff seems difficult to do elegantly, unfortunately, but anything that presents as a function is a candidate. (I just remembered a really 'fun' one -- CONCAT() exists in many DBs as an alias for the unintuitive '||' for concatenation, which is what you must use in sqlite)

This would help greatly in writing database-agnostic queries, which is what I'm using knex for. (Specifically, postgres in production and sqlite in testing)

There's a secondary thing presented by the group_concat problem. In postgres, you can do some pretty useful things, such as 'array_agg()' to return in a particular row an array of aggregated items (the 'pg' module returns this as an array, conveniently). This is a function that can fundamentally change how you structure certain bits of code if you want to take advantage of it, but there's no analog in the other DBs; group_concat comes close, however, and can be used to simulate it. For example, I am switching on the dialect, and if not postgres, I use `GROUP_CONCAT(col, '\n')` to concatenate the items with a newline, then after the query I process the data to split that back out.

This kind of thing can't be handled just on the query side of things, and it's messy to require the user to handle the splitting. One possibility is to extend knex with the ability to add data handlers that execute on the query results and take advantage of that to implement an array aggregation helper. This seems pretty doable since we're dealing with promise chains anyway.

One problem with the array aggregation bit is the group by clause, though. PG conveniently lets you group by an entire table name (9.3+, I think?), but in others you are stuck iterating the columns, so something like 'select foo.*, group_concat(bar.thing)' may become problematic. I've been handling this by explicitly listing the columns in a variable which I use in the select statement, then appending another select statement if/when I want to do the array aggregation. I then group by the same variable as the first select. (By the way, kudos on the ability to define your query in an arbitrary order - that's done some really fantastic things for code elegance for me!)

So, in the best case you might do something like parse the query, retrieve the relevant columns, and construct the 'correct' query in sql, but that's a bit complex and certainly not required for a first attempt.

In general, even the functions that ARE the same between databases are still messy to use because you must perform string concatenation and use knex.raw, so in the very basic case, even an expression API that doesn't handle these discrepancies would be useful.

**Comment by elhigu** [comment]
Good starting point would be to add one specific feature request to get these things started. This is way too big to go anywhere in its current form. Closing this now while cleaning up abandoned issues.
