### ISSUE TITLE
Transaction API misleading

### ISSUE THREAD

**Issue by timruffles** [tgriesser/knex#470]
First off thanks for Knex! :)

The transaction API has a promise-like API (`then()`, `catch()`) that suggests it's exposing a promise for the eventual committal or rollback of the transaction. Instead, however, it's a stateful API with nothing to do with promises - every time you call it [something happens](https://github.com/tgriesser/knex/blob/master/lib/transaction.js#L77) and a different promise is returned!

If you consider the root idea of promises it is that they represent a future value, or a failure to provide that value. Calls to `then()` are _entirely divorced from time_ - e.g you should be able to call `then()` any number of times, before, after, and during the asynchronous operation it represents, and get the same result every time.

I'd be happy to contribute to fix up this aspect of the API. I just wasted a heap of time because something that looked like a promise wasn't one.

**Comment by timruffles** [comment]
@tgriesser yes - that's precisely where I'd see it being a problem. e.g:

```javascript
var active = knex('users').where('deleted_at IS NULL');

exports.active = function() { return active.then() };
exports.online = function() { return active.where('online', true).then() };
```
Also, thinking about it, you'd need a `exec()` to allow reuse of queries via the promise API.  `now` and `later` will be the same value if promises are cached, and no `exec()` API exists.

```javascript
var recentEvents = knex("projects").where("created_at > NOW() - 1000");

var now = recentEvents.then();
var later = timeout(2000).then(function() { return recentEvents.then() });
```

Another option to give builder/result distinction and retain the inline style: change `Result#then()` so if it is resolved with a query builder it will run the query and return a promise for its result.

**Comment by bruun** [comment]
> I just wasted a heap of time because something that looked like a promise wasn't one.

You are not alone. A `.then` in promise-land shouldn't have side-effects, but the knex API does.

**Comment by baltar** [comment]
What's the take on this now? I'm all for an explicit run() method. I use bookshelfjs and avoid direct use of knex, but I just stumbled across a a case where that non-promise then() hit me. I really don't think that preventing a minimal amount of verbosity is enough justification to allow such confusing and in some cases dangerous behaviour.

**Comment by elhigu** [comment]
@baltar  As far as I know consensus was that `QueryBuilder` could be changed to not be `thenable` and has separate method to convert it to promise. 

But this will be really big change so probably not coming any time soon. 

It will be nice to be able to return `QueryBuilder` instances from promise without triggering them in the process :) Bad side is that it adds a bit more boilerplate to tell everywhere when query should be triggered (sounds fair enough drawback to increased control).

@bruun I couldn't find anything from spec saying that calling then multiple times for `thenable` should be immutable, but yeah it would be nice :+1:
