### ISSUE TITLE
Document index, constraint, timestamp col drop methods

### ISSUE THREAD

**Issue by danschumann** [tgriesser/knex#483]
I'm looking to put a remove index command on a `down` migration, but not seeing one in the docs, is there a removeIndex?

**Comment by djmadcat** [comment]
+1

**Comment by blah238** [comment]
FYI `dropIndex` is now documented: https://github.com/tgriesser/knex/blob/05ffb457a885c9a2d27a0684b57cbcf45cbb0456/index.html#L1908

**Comment by techniq** [comment]
Also need to document `foreign()` to create foreign key references after a column already exists.  I just replaced some existing foreign key references so I could add cadcade deletions using:

```js
exports.up = function(knex, Promise) {
  return knex.schema
    .table('review', function (table) {
      table.dropForeign('event_id')
      table.foreign('event_id')
        .references('event.id')
        .onDelete('CASCADE')
        
      table.dropForeign('user_id')
      table.foreign('user_id')
        .references('user.id')
        .onDelete('CASCADE')
    })
})
```

**Comment by rhys-vdw** [comment]
Thanks @techniq, updated Ben's post.

**Comment by rhys-vdw** [comment]
Would you be interested in supplying a PR, @techniq?

**Comment by techniq** [comment]
@rhys-vdw See PR #1156

**Comment by rhys-vdw** [comment]
Thanks @techniq.

**Comment by techniq** [comment]
Welcome @rhys-vdw. You can check those off of @bendrucker's list ;)

**Comment by rhys-vdw** [comment]
Already done.

**Comment by techniq** [comment]
Thanks.  My page needed a hard refresh to see.  Guess just comments are websocket streamed in.

**Comment by rhys-vdw** [comment]
I figured something like that. I'll update `gh-pages` later when I'm back from work.
