### ISSUE TITLE
scheme.table callback called multiple times?

### ISSUE THREAD

**Issue by danschumann** [tgriesser/knex#491]
It seems like calling 

```
schema.table('tablename', function(t) {
  t.integer('id');
});
schema.table('somethignelse', function(t) {
  t.integer('fart');
});
```

this will `alter table tablename add id(int)` TWICE.

This seems to be the case when using what is in trunk, but not uploaded to npm

At least this appears to be the case I am running into, as if it was using the old callback or something

**Comment by rkaw92** [comment]
Got bitten by this almost 2 years after the initial report. I suppose that making `schema` a function that generates a new schema builder, and only leaving the methods as that function's properties is one solution that would leave programmers with the following outcome:
```js
knex.schema // works
knex.schema() // works
schema.createTable() => does not work; re-uses single instance
schema().createTable() => works
```

This, however, would require an API change and apparently some internal refactoring, so it might just be best to update the README with information that `knex.schema` is a getter and leave it visible right below http://knexjs.org/#Schema .

**Comment by wubzz** [comment]
Closing as docs has been updated to reflect this nature of the schema builder. API re-design should be in a seperate issue, if such a change is still requested.
