### ISSUE TITLE
Idle connections thrash when pool min > 0 (i.e. by default)

### ISSUE THREAD

**Issue by ErisDS** [tgriesser/knex#503]
I was going to raise this against [generic-pool-redux](https://github.com/bookshelf/generic-pool-redux), but I'm not sure if it's not perhaps an issue with a missing config option here in knex.

The default minimum pool size in knex is 2, so by default 2 connections are kept active at all times.
At the same time, there is an idle timeout set to 30 seconds in generic-pool-redux, which cleans away idle connections.

The result is that by default connections are opened and closed every 30 seconds whenever a client is idle. This isn't much of an issue, until you start scaling the number of clients talking to a database. Then the thrashing LOGN & QUIT requests activating and deactivating idle connections starts blocking real requests from being able to access the database.

Setting `min:0` stops the thrashing, but I don't think this behaviour is correct, especially not as the default behaviour for the library.

Perhaps there is or should be a way to stop idle connections from being cleaned away when there is a min > 0, or perhaps the default min should be 0?

**Comment by ErisDS** [comment]
@tgriesser I don't think this ever got looked into - should it perhaps have an issue on generic-pool-redux?

**Comment by ErisDS** [comment]
@wubzz is this considered fixed, or has it moved?

**Comment by ErisDS** [comment]
Hi @wubzz you closed this issue but I'm not able to find any reference to what the solution was, could you please let me know?

**Comment by wubzz** [comment]
@ErisDS  Sorry, was sure I put a comment here.. I closed this because of a few reasons:

1. Default `min` has been 0 for a long time
2. `generic-pool-redux` [hasn't been a dependency of knex since 2015](https://github.com/tgriesser/knex/commit/dff5a1409ac23679c8af2bd13c7cb807eb375974)
3. There's been a lot of pool related changes since 0.7.0

Knex uses [pool2](https://github.com/myndzi/pool2) for pooling now.

If there's still an issue here, you're free to reopen it.

**Comment by ErisDS** [comment]
Ok cool, so the default changed - that's a good start. I also went and read the [pool2 docs]() and they say this:

> idleTimeout

> An integer, in milliseconds, to specify how long a resource must be idle before it may be disposed of. Resources are periodically checked (see syncInterval below) for idleness, and idle resources are disposed of **unless they would bring the pool below the configured min value**.

This sounds like the logic in pool2 will result in much better behaviour. Thanks for the info!

**Comment by xxx** [comment]
I think this has become an issue again with the switch to generic-pool for pooling as of 0.12.0. We definitely see it with 0.12.9.
