### ISSUE TITLE
Adding upsert type capability

### ISSUE THREAD

**Issue by tgriesser** [tgriesser/knex#54]
Brought up by @adamscybot in tgriesser/bookshelf#55 - this could be a nice feature to add.

**Comment by clark800** [comment]
:+1:

**Comment by diegoitaliait** [comment]
Hi, 
there are news about this new feature?

Or can someone recommend examples, that show how to simulate this functionality for mysql?

thx

**Comment by tgriesser** [comment]
Right now I'm doing it with `raw`, but I'm working hard on getting this available in here soon.

**Comment by olalonde** [comment]
Postgres just implemented upsert support by the way :+1: 

http://git.postgresql.org/gitweb/?p=postgresql.git;a=commit;h=168d5805e4c08bed7b95d351bf097cff7c07dd65

https://news.ycombinator.com/item?id=9509870

**Comment by julianlloyd** [comment]
I think this would make a great addition to Knex. :+1:

**Comment by hotaru355** [comment]
I was looking for a way to do a `REPLACE INTO` in MySql and found this feature request. Since `REPLACE` and `INSERT` have exactly the same syntax in MySql I would imagine it to be easier to implement than a `ON DUPLICATE KEY UPDATE`. Are there any plans to implement a `REPLACE` ? Would a PR be something of value?

**Comment by bradsimantel** [comment]
Any updates on this, especially with PostreSQL 9.5?

**Comment by RubenCordeiro** [comment]
I think one important question is whether or not to expose the same ```upsert``` method signature for different dialects, such as PostgreSQL and MySQL. In Sequelize, a issue has been raised regarding the return value of ```upsert``: https://github.com/sequelize/sequelize/issues/3354. 

I realise that some of KnexJS library methods have distinctions regarding the return values in the context of different dialects (such as ```insert```, where an array of the first inserted id is returned for Sqlite and MySQL, while an array of **all** the inserted id's is returned with PostgreSQL).

According to the documentation, the ```INSERT ... ON DUPLICATE KEY UPDATE``` syntax in MySQL has the following behaviour (http://dev.mysql.com/doc/refman/5.7/en/insert-on-duplicate.html):

> With ON DUPLICATE KEY UPDATE, the affected-rows value per row is 1 if the row is inserted as a new row, 2 if an existing row is updated, and 0 if an existing row is set to its current values.

While in PostgreSQL (http://www.postgresql.org/docs/9.5/static/sql-insert.html):

> On successful completion, an INSERT command returns a command tag of the form

> `INSERT oid count`

> The count is the number of rows inserted or updated. If count is exactly one, and the target table has OIDs, then oid is the OID assigned to the inserted row. The single row must have been inserted rather than updated. Otherwise oid is zero.

> If the INSERT command contains a RETURNING clause, the result will be similar to that of a SELECT statement containing the columns and values defined in the RETURNING list, computed over the row(s) inserted or updated by the command.

Thoughts?

**Comment by hayeah** [comment]
I monkey patched Client_PG to add the "onConflict" method for insert. Suppose we want to upsert github oauth credentials, we can write the query like this:

```js
const profile = {
    access_token: "blah blah",
    username: "foobar",
    // ... etc
  }

  const oauth = {
    uid: "13344398",
    provider: "github",
    created_at: new Date(),
    updated_at: new Date(),
    info: profile,
  };

  // todo: add a "timestamp" method

const insert = knex("oauths").insert(oauth).onConflict(["provider", "uid"],{
  info: profile,
  updated_at: new Date(),
});

console.log(insert.toString())
```

The array of column names specifies the uniquessness constraint.

```
insert into "authentications" ("created_at", "info", "provider", "uid", "updated_at") values ('2016-02-14T14:42:18.342+08:00', '{\"access_token\":\"blah blah\",\"username\":\"foobar\"}', 'github', '13344398', '2016-02-14T14:42:18.342+08:00') on conflict ("provider", "uid")  do update set "info" = '{\"access_token\":\"blah blah\",\"username\":\"foobar\"}', "updated_at" = '2016-02-14T14:42:18.343+08:00'
```

See gist: https://gist.github.com/hayeah/1c8d642df5cfeabc2a5b for the monkey patch.

This is a super hacky experiment... so don't exactly copy & paste the monkey patch into your production code : p

Known problems:

+ The monkey patch is on QueryBuilder affects all dialects, because Client_PG doesn't specialize the builder.
+ The `returning` clause is at the wrong place.
+ Doesn't support raw update like `count = count + 1`
+ onConflict should probably throw if query method is not insert.

Feedback?

**Comment by RubenCordeiro** [comment]
@hayeah I like your approach and it suits Postgres. I am going to try your monkey patch in a project to see if I can empirically detect any issues other than the ones you pointed out.

**Comment by willfarrell** [comment]
Syntax Suggestion: `knex('table').upsert(['col1','col2']).insert({...}).update({...});` where `upsert` would take in the condition statement. This way it's not db specific.

Summary of the different implementations of upserts can be found at https://en.wikipedia.org/wiki/Merge_(SQL)

**Comment by tthyer** [comment]
I'm interested in having this capability too. Use case: building a system that is reliant on lots of outside data from an outside service; I periodically poll it for data that I save to a local MySQL db. Will probably be using knex.raw for now.

**Comment by haywirez** [comment]
Also interested, but in my use case would need to have it work in a way that isn't based on conflicts, as the columns don't always have 'unique' constraints - simply update entries matching the query if they exist, otherwise insert new rows.

**Comment by hayeah** [comment]
@haywirez I am curious as to why there are no unique constraints? Wouldn't you be exposed to race conditions?

**Comment by haywirez** [comment]
@hayeah I have a specific use case with time-windowed data, storing entries that have a value tied to a given day. Therefore I'm inserting and updating entries that have a "combined key" of a matching (day) timestamp, and two other IDs corresponding to PK's in other tables. Within a 24-hour window, I have to either insert them if the correct data couldn't yet be fetched, or update them with the latest counts.

**Comment by slavafomin** [comment]
That would be a great feature to have!

**Comment by lendi-au-glen** [comment]
^ Agreed.

**Comment by rhys-vdw** [comment]
Hi everyone who's ever commented here. I'm adding a PR Please label.

Happy to take a PR adding this functionality, but I'd like to see a discussion of the desired API here first.

PS.

> ^ Agreed.

I'm going to delete comments like this, if you want to add a +1 do so with the little emoji reaction thing.

**Comment by reggi** [comment]
I have a bit of an issue with the array of column restraints as in @willfarrell and @hayeah's examples.  Not sure if these examples can support `json` properties. 

> api proposal 1

```js
knex('table')
  .where('id', '=', data.id)
  .upsert(data)
```

> api proposal 2

```js
knex('table')
  .upsertQuery(knex => {
    return knex('table')
      .where('id', '=', data.id)
  })
  .upsertUpdate(knex => {
    return knex('table')
      .insert(data)
  })
```

> api proposal 3

```js
knex('table')
  .where('id', '=', data.id)
  .insert(data)
  .upsert() // or .onConflictDoUpdate()
```

I'm leaning most toward something like 3. Is there a reason none of these proposals don't include where statements / proper "queries" to match the record?

Just to add in [here's how mongodb does it](https://docs.mongodb.com/manual/reference/method/db.collection.update/#definition).

```js
db.collection.update(
   <query>,
   <update>,
   {
     upsert: <boolean>,
     multi: <boolean>,
     writeConcern: <document>
   }
)
```

**Comment by hayeah** [comment]
@reggi I believe my monkey patch is compatible with `where`...

**Comment by halt-hammerzeit** [comment]
@reggi I don't see your point.
Can you elaborate more on which functionality is missing from the approach proposed in @willfarrell and @hayeah's examples.
Why do you need `where` at all?
It's just an `insert` opertation.

**Comment by halt-hammerzeit** [comment]
@reggi The MongoDB example you provided reads "First try to UPDATE WHERE ... then do an INSERT if no document matches the query" whereas SQL UPSERT reads "INSERT INTO ... UPDATING in case a row with this primary key already exists".
So, I guess, you're talking about a whole different "upsert" than it's implemented in SQL databases.

**Comment by halt-hammerzeit** [comment]
I would propose this API:

```js
knex.createTable('test')
   .bigserial('id')
   .varchar('whatever')

knex.table('test').insert(object, { upsert: ['id'] })
```

`.insert()` function would analyse the second parameter.
If it's a string, then it's the old `returning` parameter.
If it's an object, then it's an `options` parameter having `options.returning` and `options.upsert`, where `options.upsert` is a list of the primary keys (can be > 1 in case of a compound unique key constraint).
Then a SQL query is generated which simply excludes `options.upsert` keys from the `object` JSON (via `clone(data) && delete cloned_data.id`) and then uses that `cloned_data` stripped of the primary keys to construct the second part: `ON CONFLICT UPDATE SET ...`.

I guess that would be the most simple and unambiguous solution.

**Comment by slavafomin** [comment]
Are there any news regarding this feature?

**Comment by ScionOfBytes** [comment]
Well? Any news?

**Comment by elhigu** [comment]
@slavafomin @ScionOfBytes Looks like even the API has not yet been agreed on. That would be the next step and then someone who likes to implement it may do so. So no news.

**Comment by MentalBrake** [comment]
was hoping to see some progress in 3 years as I was scrolling down here, guess I'll have to go with raw

**Comment by amir-s** [comment]
I just wrote a monkey patch so I can use `replace` for mysql and sqlite. 
https://gist.github.com/amir-s/2e40f1b72bc89e505e0f695fb10cecd0

**Comment by absolux** [comment]
@amir-s `replace` is not an `upsert`

**Comment by amir-s** [comment]
@absolux I didn't say anything about `upsert`. what I have posted is what I wrote for `replace`. one could modify it to fit his/her needs.

**Comment by absolux** [comment]
@amir-s I agree, but the subject of this issue is the upsert capability.

In the other hand, MySQL (ON DUPLICATE KEY UPDATE) and PostgreSQL 9.5+ (ON CONFLICT UPDATE) support upsert by default.

MSSQL and Oracle can support it with a merge clause, but knex should know the names of conflict columns to be able to construct the query.
```sql
-- in this case the conflict column is 'a'
merge into target
using (select key from target) as t
on (t.a = target.a)
when matched then
  update set b = ?
when not matched then
  insert (a, b) values (?, ?);
```

But SQLite did not. We need two queries to simulate the upsert
```sql
-- 'a' is the conflict column
insert or ignore into target (a, b) values (?, ?);
update target set b = ?2 where changes() = 0 and a = ?1;
```
The other solution is using `INSERT OR REPLACE`, or simply `REPLACE`. 
```sql
-- replace will delete the matched row then add a new one with the given data
replace into target (a, b) values (?, ?);
```
unfortunately, if the target table has more columns than a and b, their values will be replaced by defaults
```sql
insert or replace into target (a, b, c) values(?, ?, (select c from target where a = ?1))
```
Another solution using CTE, look this [stackoverflow answer](http://stackoverflow.com/a/7511635)

**Comment by timhuff** [comment]
I've come to this issue several times in search of a knex-based Postgres upsert. If anyone else needs this, here's how to do it. I've tested this against both single and composite unique keys. I would test before usage because I'm not sure if `knex().update(obj)` compiling to `UPDATE  SET...` is defined behavior. Warning: CoffeeScript ahead - if that's not your jam (seems the crowd has turned on it lately), I've provided some compiled javascript below.

### The Setup
Create a unique key constraint on the table using. I needed a composite key constraint:
```coffeescript
table.unique ['a','b']
```

### The Function
```coffeescript
upsert = (params)->
	{table, object, constraint} = params
	insert = knex(table).insert(object)
	update = knex().update(object)
	knex.raw "#{insert} ON CONFLICT (#{constraint}) DO #{update} returning *"
```

### Usage
```coffeescript
objToUpsert = {a:1, b:2, c:3}

upsert({
	table: 'test',
	object: objToUpsert,
	constraint: 'a, b'
})
```
If your constraint isn't composite then, naturally, that one line would just be `constraint: 'a'`.

This will return either the updated object or the inserted object.

### Compiled JavaScript
```javascript
var objToUpsert, upsert;

upsert = function(params) {
  var constraint, insert, object, table, update;
  table = params.table, object = params.object, constraint = params.constraint;
  insert = knex(table).insert(object);
  update = knex().update(object);
  return knex.raw(insert + " ON CONFLICT (" + constraint + ") DO " + update + " returning *");
};

objToUpsert = {
  a: 1,
  b: 2,
  c: 3
};

upsert({
  table: 'test',
  object: objToUpsert,
  constraint: 'a, b'
});
```

Hope someone finds this useful. @elhigu Any comment on the usage of `knex().update(object)`?

**Comment by elhigu** [comment]
@timhuff looks nice, one thing to change would be to pass each query to raw, using value binding. Otherwise `query.toString()` is used to render each part of the query and it opens up possible dependency injection hole (queryBuilder.toString() is not as safe as passing parameters to driver as bindings)..

**Comment by timhuff** [comment]
@elhigu Wait... `query.toString()` doesn't use bindings? Could you give me a rough example of the modification you're recommending? I... might have a lot of code to update.

**Comment by timhuff** [comment]
Found the part of the documentation labeled [Raw bindings](http://knexjs.org/#Raw-Bindings). I thought `query.toString` was safe. It'd be good to have a section of the documentation labeled something like "How to make unsafe queries". There's only a handful of no-nos and that way people can use the library knowing "as long as I don't do these things, I'm safe".

**Comment by adnanoner** [comment]
I've created the following upsert: https://gist.github.com/adnanoner/b6c53482243b9d5d5da4e29e109af9bd
It handles single and batch upserts. I adapted it a bit from @plurch . Improvements are always appreciated :)

**Comment by NicolajKN** [comment]
For what it's worth I've been using this format:

```
const query = knex( 'account' ).insert( accounts );
const safeQuery = knex.raw( query.toString() + ' ON CONFLICT DO NOTHING' );
```

**Comment by elhigu** [comment]
@NicolajKN You shouldn't use toString(), it might cause many kind of problems and won't pass values through bindings to DB (potential SQL injection security hole).

Same this done properly would be like this:

```js
const query = knex( 'account' ).insert( accounts );
const safeQuery = knex.raw( '? ON CONFLICT DO NOTHING', [query]);
```

**Comment by abus120** [comment]
Hi, Can anyone help me to fix batchinsert() using knex for Oracle DB. I'm facing following error during batchinsert for multiple rows.

begin execute immediate 'insert into "KSN_ACTIVATE_ERROR" ("AERR_MESSAGE", "AERR_SYSID_PK", "FK_ORDE_SYSID", "FK_REQU_SYSID") values (:1, KSN_AERR_SEQ.NEXTVAL, :2, :3) returning "AERR_SYSID_PK" into :4' using :1, KSN_AERR_SEQ.NEXTVAL, :2, :3, out :4; execute immediate 'insert into "KSN_ACTIVATE_ERROR" ("AERR_MESSAGE", "AERR_SYSID_PK", "FK_ORDE_SYSID", "FK_REQU_SYSID") values (:1, KSN_AERR_SEQ.NEXTVAL, :2, :3) returning "AERR_SYSID_PK" into :4' using :5, KSN_AERR_SEQ.NEXTVAL, :6, :7, out :8;end; 
- ORA-01006: bind variable does not exist
ORA-06512: at line 1
"
Please assist to fix this issue.

**Comment by timhuff** [comment]
@abus120 Can you provide the code that's causing this error?

**Comment by abus120** [comment]
Hi,

Really appreciate your quick response and thanks in advance to assist to fix this issue.
Hang-up with this error since 2 days but can’t able to resolve.


db.knex.transaction(function (trx) {
            var chunkSize = 1000;
            var rows = [{ AERR_SYSID_PK: db.knex.raw('KSN_AERR_SEQ.NEXTVAL'), FK_REQU_SYSID: 44628, FK_ORDE_SYSID: 135292, AERR_MESSAGE: 'KSM_RPRO_0059' },
            { AERR_SYSID_PK: db.knex.raw('KSN_AERR_SEQ.NEXTVAL'), FK_REQU_SYSID: 44628, FK_ORDE_SYSID: 135292, AERR_MESSAGE: 'KSM_RPRO_0060' }];
            db.knex.batchInsert('KSN_ACTIVATE_ERROR', rows, chunkSize).returning('AERR_SYSID_PK').transacting(trx)
                .then(function (result) {
                    if (result != null && result[0] != null) {

                    }
                })
                .then(trx.commit)
                .catch(function (err) {
                    trx.rollback;
                    logger.error(err);
                });
        }).then(function (resp) {
            logger.info('Transaction completed - Insert into KSN_ECOM_STAGING_DETAIL,KSN_ECOM_STAGING_NOTE,KSN_ECOM_BRANCH_STG_ADDRS');
        }).catch(function (err) {
            logger.error(err);
        });

Thanks
Siddik

**Comment by timhuff** [comment]
I'm currently wrapping up some work, myself, but I took a quick look at your code. I would suspect that the cause of your issue is `db.knex.raw('KSN_AERR_SEQ.NEXTVAL')`. If you have an auto-incrementing primary key on this table (via `.increments()`), you don't need to specify it explicitly like this. It'll populate automatically. Either way, I would create a separate issue for this. It's not really related to upserting.

**Comment by abus120** [comment]
FYI, DB tables doesn’t have an auto increment for PK.  However I try to insert for single record then it would works fine without error, but got error when inserting multiple records.
I’ve suspected too db.raw() only cause this error, but I don’t found any other way to achieve this spend lot of time.

It might be so helpful, if you provide any solutions to fix this issue.


Thanks
Siddik

**Comment by elhigu** [comment]
@timhuff @abus120 how is this discussion related to upsert feature? Please move discussion to elsewhere.

**Comment by abus120** [comment]
@timhuff any possibilities to fix this issue? otherwise would you please suggest me some alternatives for batchinsert() my DB tables doesn't have auto increments for PK.

**Comment by timhuff** [comment]
@abus120 As @elhigu said, create a new issue and mention me and we can discuss further if you'd like. The long and short of it: I don't know why this is erroring and I'd need to reconstruct your db and reproduce the error to investigate further but the need to use sequences in this way is puzzling and seems to indicate a deeper issue.

**Comment by abus120** [comment]
@timhuff this is my new case# 2355

**Comment by elhigu** [comment]
Deleted discussion of unrelated issue.

**Comment by cloutiertyler** [comment]
@elhigu Hold on doesn't that insert query get executed immediately after being created? Doesn't that create a race condition?

**Comment by timhuff** [comment]
@cloutiertyler You weren't talking to me but maybe I can save @elhigu some time here. None of these queries should be executed. The statement `knex('account').insert(accounts)` does not execute a query. It's not executed until the data is actually called upon (e.g. via a `.then`). He sends that into `knex.raw('? ON CONFLICT DO NOTHING', [query])` which will call `query.toString()`, which only converts the query into the SQL statement that *would* be executed.

**Comment by cloutiertyler** [comment]
@timhuff Thanks Tim, I assumed it had to be something like that, but that's not normal behavior for a promise. Promises are usually executed upon creation. The reason I ask is that I was getting errors saying "Connection Terminated" every so often when I tried to run this upsert. Once I switched over to removing the insert and creating an entirely raw query they went away. Am I missing something here?

**Comment by timhuff** [comment]
knex `QueryBuilder`s aren't `Promise`s, though. When you start writing a knex query, you stay in "knexland". Everything you do is more or less just configuring a JSON spec of the query that you want to build. If you run `.toString`, it builds it and outputs it. It doesn't become a (`bluebird`) Promise until until you run [one of these](http://knexjs.org/#Interfaces-Promises) on it. You might be interested in using [`.return`](http://knexjs.org/#Interfaces-return) if you want to execute the statement immediately.

**Comment by cloutiertyler** [comment]
Ah, I see, well that clears up my confusion. Thanks for the clarification and pointers! My issue must exist elsewhere then.

**Comment by timhuff** [comment]
As an aside, the fact that it *doesn't* run immediately is often useful. Sometimes you wanna pass the thing around, configuring it, before executing. There's also situations where you can do stuff like...

```javascript
const medicalBuildings = knex.select('building_id').from('buildings').where({type: 'medical'})
const medicalWorkers = knex.select().from('workers').whereIn('building', medicalBuildings)
```
(super contrived example but let's run with it)

I don't actually want to run that first statement - it's just part of my 2nd one.

**Comment by elhigu** [comment]
Not to mention that if all query builders would execute on creation the builder pattern it is using would not work at all without having some terminator method (that executes the query).

**Comment by timhuff** [comment]
@elhigu I mean... I guess you could just always run it on the next tick, right? I'm not suggesting that would by any means be a good idea but how many queries are actually created and executed on different ticks?

**Comment by elhigu** [comment]
@timhuff I hadn't thought about that. Yeah I think that would be possible too. I find case quite common where one starts building query, then fetch some async data and keep on building more. I don't do that very often though.

**Comment by lukewlms** [comment]
I do find this probably the most unintuitive part of Knex - I don't know of anywhere else that these two lines actually create different objects and run different code paths in this way:

    a();

or

    await a();

I love Knex but after several months I still stumble occasionally over forgetting to call `await` because I'm on an operation that does not require awaiting.  Needing to add `.then()` in order for it to run seems to run counter to how promises work everywhere else.

Is there a function that always simply executes and returns the promise, something like "`.execute()`"?  If so we would use that every time to eliminate coding errors in forgetting to `.then()` the query so that it doesn't execute.

**Comment by timhuff** [comment]
@lukewlms The important thing to keep in mind here is that *`knex`'s query builder is not a promise*. It's a query builder. It's a big factory that constructs complicated SQL statements and when you're done you tell the factory "alright, this one's ready to go. Please execute that for me" and then, *only at that point*, do promises even come into the picture. Everything before then is synchronous. I mean, the fact that it talks to the database for you at all is a convenience. It could just as well hand you the SQL statement and say "run it yourself. the `pg` package is that way".

I think what confuses people is that `.then` is the way you tell the factory "alright, now execute it and hand me the promise". I can see why this might be confusing but the alternative would be writing `.execute()` every time you want to execute a query.

**Comment by timhuff** [comment]
I really don't think it'd be a terrible idea to make a `.execute()` function part of the API, if for no other reason than to make it more intuitive to newcomers. I mean, in practice, you could use something like `.then(_.identity)` to emulate `.execute()` but what we're after here is the syntactic sugar.

**Comment by timhuff** [comment]
@lukewlms If this is a serious concern for your team, just modify your knex instance. I know some people frown upon modifying libraries but I think tacking on little util methods isn't terrible. If you pass your `knex` instance to this function, a `.execute` will become part of your API.

```javascript
const _ = require('lodash')
const QueryBuilder = require('knex/lib/query/builder')

const methods = {
  execute: function() {
    return this.then(_.identity)
  },
}

const augmentKnex = knex => {
  _.assign(QueryBuilder.prototype, methods)
  _.assign(knex, methods)
  _.bindAll(knex, _.functions(methods))
  return knex
}
```

**Comment by elhigu** [comment]
@lukewlms that ’execute()’ -like method is called ’.then()’ you can call always it when you like to execute query and get promise. It is just how ’thenable’ works and it is explained in promise spec. It is one important and widely used concept in javascript when dealing with promises and async/await (which are pretty much just glorified shortcuts for Promise.resolve and .then). Also if you are executing queries without handling results you are looking for problems like app crashing.

**Comment by elhigu** [comment]
But again please move discussion to some related issue I’ll delete these in few days

**Comment by lukewlms** [comment]
@elhigu .then() doesn't actually run different code on promises in the spec - that is unique to Knex.

@timhuff the issue there is that we can't use it fluently in either `.then()` or `await` cases.  `await knex...then();` wouldn't work.

It's not a huge issue for us as we're fairly experienced now, but I expect a lot of newbies to be staring at their code and trying to figure out why their values aren't saved to the DB - b/c they didn't prepend "await" or append "then()", which most similar code does not require.  Ofc Knex works differently but in a way that no other lib I've seen works.

I'd like Knex to have wide adoption so I do think it's a real concern.

**Comment by lukewlms** [comment]
@elhigu I hear you though, I'll consider what code might look like and perhaps put it in a different thread.

**Comment by timhuff** [comment]
@lukewlms I'm not positive (don't think I've ever done this) but I'm pretty sure `await knex...then();` should work. The `.then` would return a promise and then the `await` would... await its resolution.

**Comment by elhigu** [comment]
Actually its better to just follow this PR about the upsert feature implementation https://github.com/tgriesser/knex/pull/2197 it has already API designed how it should work. In this thread is not really any useful information that is not already mentioned in comments of that PR. If needed (PR is closed and never completed) lets open new issue for this one with additional API description.

**Comment by timhuff** [comment]
@elhigu Thanks for the heads up! I was unaware of that thread. Good to hear we're making progress on an upsert coming to the API. Looks like 6 months ago it failed 1 of the 802 tests and so it never passed travis-ci. Is that 1 failing test case the only thing keeping this from becoming a part of the knex API?

**Comment by elhigu** [comment]
@timhuff there was only initial implementation done, it must be completely rewritten. Most important part of that PR is the common API design, which can be supported by most of the dialects. So it comes when someone just decides to implement it if no-one else does that and some day I have some extra time or need it badly, I'll do it myself.

**Comment by timhuff** [comment]
@elhigu Thanks for filling me in. I'll have to read up on the progress here when I get a little more time.

**Comment by lukewlms** [comment]
@timhuff @elhigu Ah I see, I didn't realize .then() and await could be used together.  Looks like that's a solution for us then, thanks!

**Comment by timhuff** [comment]
Ah. It looks like that might've been a big part of the confusion. `async`/`await` are largely just syntactic sugar for promises. `knex` didn't have to change at all to go from "promise-compatible" to "await/async compatible". The fact that it's then-able is all that's required for both cases.

**Comment by ashconnell** [comment]
I'm not sure if this helps anyone or if i'm just a noob, but I had to wrap my constraint in quotes because i was getting a query syntax error.

```js
const contraint = '("a", "b")'
```

> I've come to this issue several times in search of a knex-based Postgres upsert. If anyone else needs this, here's how to do it. I've tested this against both single and composite unique keys.
> 
> ### The Setup
> Create a unique key constraint on the table using the below. I needed a composite key constraint:
> 
> ```js
> table.unique(['a', 'b'])
> ```
> 
> ### The Function
> (edit: updated to use raw parameter bindings)
> 
> ```js
> const upsert = (params)=> {
>   const {table, object, constraint} = params;
>   const insert = knex(table).insert(object);
>   const update = knex.queryBuilder().update(object);
>   return knex.raw(`? ON CONFLICT ${constraint} DO ? returning *`, [insert, update]).get('rows').get(0);
> };
> ```
> 
> ### Usage
> ```js
> const objToUpsert = {a:1, b:2, c:3}
> 
> upsert({
> 	table: 'test',
> 	object: objToUpsert,
> 	constraint: '(a, b)',
> })
> ```
> 
> If your constraint isn't composite then, naturally, that one line would just be `constraint: '(a)'`.
> 
> This will return either the updated object or the inserted object.
> 
> > #### A note about composite nullable indices
> > If you have a composite index `(a,b)` and `b` is nullable, then values `(1, NULL)` and `(1, NULL)` are considered mutually unique by Postgres (I don't get it either). If this is your use case, you'll need make a partial unique index and then test for null before upsert to determine which constraint to use. Here's how to make the partial unique index: `CREATE UNIQUE INDEX unique_index_name ON table (a) WHERE b IS NULL`. If your test determines that `b` is null, then you'll need to use this constraint in your upsert: `constraint: '(a) WHERE b IS NULL'`. If `a` is also nullable, I would guess you'd need 3 unique indices and 4 `if/else` branches (though this is not my use case, so I'm not sure).
> 
> Here's the [compiled javascript](https://gist.github.com/timhuff/f4f0814b0eb048784e44e744aa8e41f5).
> 
> Hope someone finds this useful. @elhigu ~Any comment on the usage of `knex().update(object)`?~ (edit: nevermind - saw the warning - using `knex.queryBuilder()` now)

**Comment by elhigu** [comment]
Removed some unrelated discussions  (about how promises/thenables work).

**Comment by designalchemy** [comment]
Did this get added ?

**Comment by elhigu** [comment]
There is feature request and spec in https://github.com/knex/knex/issues/3186
