### ISSUE TITLE
Nested objects in query builder

### ISSUE THREAD

**Issue by johnbrett** [tgriesser/knex#543]
Hey guys, I've noticed some odd behaviour with the query builder's handling of nested objects. It tries to JSON.stringify them as opposed to toString().

Following code example:

``` javascript
var obj = {
    email: {
        nested_key: 'value'
    }
}

knex.insert(obj).into('account').toString(); //produces 'insert into `account` (`email`) values (\'[object Object]\')'

knex.insert(obj).into('account').exec(); //produces 'insert into `account` (`email`) values (`nested_key` = \'value\')' }
```

Which of course throws a `ER_BAD_FIELD_ERROR: Unknown column 'nested_key' in 'field list'`

Is this expected behaviour? as it's different to how the `Mysql` module would handle objects which would handle them like the first case, proves very hard to debug when toString() doesn't produce the same query as what's being run also!

I created a gist if you want to replicate: https://gist.github.com/johnbrett/174a77c8a20752031682

Thanks for time on this!

**Comment by wubzz** [comment]
Closing this, seems fixed:

```javascript
var obj = {
    email: {
        nested_key: 'value'
    }
}

console.log(knex.insert(obj).into('account').toString()); 
//insert into `account` (`email`) values ({"nested_key":"value"})
```
