### ISSUE TITLE
String interpolation with objects rather than arrays

### ISSUE THREAD

**Issue by bblack** [tgriesser/knex#549]
Feature request:

Rather than having a query like `select * from users limit ? offset ?` and supplying an array `[10, 20]`, it would be nice to supply an object with descriptive key names, as in `select * from users limit :count offset :offset` and supplying an object `{count: 10, offset: 20}`. This can help code readability especially for long queries with many interpolations.

**Comment by wubzz** [comment]
Knex has named-bindings support now so I'm going to consider this resolved.

**Comment by bblack** [comment]
sweet, thanks!
