### ISSUE TITLE
Migrations should be wrapped in a transaction automatically

### ISSUE THREAD

**Issue by ricardograca** [tgriesser/knex#567]
Whenever a migration fails it may leave the database in an inconsistent state, and a rollback won't be possible since the migration wasn't finished. I've looked through some of the closed issues and it seems some people already had problems due to this behavior. At least #312 and #148, but I didn't look very far back.

From my point of view a migration should always be wrapped inside a transaction that rolls back any changes in case of failure, if possible. It shouldn't be up to the user to do this manually, or is there a reason this can't be done automatically?

**Comment by tgriesser** [comment]
This was handled by #622 and will be released soon.
