### ISSUE TITLE
Store seed state in database like migrations

### ISSUE THREAD

**Issue by jbrumwell** [tgriesser/knex#579]
Hi,

It seems that seed:run will run all of the seed files, is there a benefit to adding a seed:latest method that works in the same fashion as the migrate:latest. The implementation of seed files wouldn't change but it would allow for test data to be passed around branches, and would ease testing and qa.

Cheers,

Jason

**Comment by jpdesigndev** [comment]
:+1: Would love to see something like this as well. Not sure why the current seeds are alphabetical?? I'm not saying it was a bad idea. I just don't understand the significance of alphabetical seeds. Especially when dealing with relations, etc.

**Comment by jocull** [comment]
+1

**Comment by kibertoad** [comment]
@elhigu Is this issue still relevant? From my understanding this is kinda redundant, since versioned seeds are basically migrations.

**Comment by elhigu** [comment]
Thanks @kibertoad. Definitely not needed or wanted. Indeed migrations works just fine for this.
