### ISSUE TITLE
Are self-joins possible?

### ISSUE THREAD

**Issue by alkawryk** [tgriesser/knex#582]
I'm trying to alias my tables while joining so that I can perform a self-join. For example:

select \* from offers o1, offers o2 where ...

Is this possible?

**Comment by ivan-kleshnin** [comment]
Is this still no supported?

**Comment by demisx** [comment]
+1 This would be a real plus.

**Comment by rhys-vdw** [comment]
Yeah, I see cause for this being supported. Actually I think that it would be nice to first support aliasing tables in the `FROM` clause.

Perhaps something like:

```js
knex({ a: 'table', b; 'table' }).whereRaw('?? = ??', 'a.column_1', 'b.column_2');
```

```sql
select * from table a, table b where "a"."column_1" = "b"."column_2"
```

In the meantime the self join above can be achieved with `raw`:

```js
knex(knex.raw('table a, table b')).whereRaw('?? = ??', ['a.column_1', 'b.column_2']);
```

**Comment by demisx** [comment]
@rhys-vdw Ditto. Aliasing tables will help us to get rid of the `knex.raw` calls at least. We are  currently doing exactly what you've shown.

**Comment by serprex** [comment]
I've begun working on an implementation at https://github.com/serprex/knex however I'm not currently working on a system capable of running tests. May see if I can fit in debugging & test development after hours at the office

**Comment by elhigu** [comment]
This just might start working if this is finished https://github.com/tgriesser/knex/pull/2227

**Comment by elhigu** [comment]
In next release this can be done with syntax introduced in #2227, like @rhys-vdw suggested in https://github.com/tgriesser/knex/issues/582#issuecomment-202266489

**Comment by OlivierCavadenti** [comment]
It's supported with raw syntax, but could be useful to support more concise syntax with more options ?

```sql
knex.from("table").selfInnerJoin('column_1', 'column_2');
```
```sql
select * from table a inner join "table" b on "a"."column_1" = "b"."column_2"```

(with automatic generated aliases)
