### ISSUE TITLE
Postgres options don't appear to work for raw queries.

### ISSUE THREAD

**Issue by perfectsquircle** [tgriesser/knex#605]
I want to run a raw query and use options as well (rowMode: "array" in postgres, specifically). 

    knex.raw("select 'foo', 'bar';").options({ rowMode: "array" }).then(function(result) {
        console.dir(result);
    });

It seems that the options don't make it to the pg driver because the rows come back in the regular format. I have not tried this in MySQL or SQLite.

**Comment by olalonde** [comment]
:+1:

**Comment by whitelynx** [comment]
This seems to be fixed, at least in v0.10.0.

@tgriesser Should this be closed?

**Comment by wubzz** [comment]
Closing this as it is working in the latest version.
