### ISSUE TITLE
Multiple Migrations directory

### ISSUE THREAD

**Issue by marcoschicote** [tgriesser/knex#607]
Hi
I was wondering if it was possible to pass multiple migrations directories in the knexfile.js.

Thanks

**Comment by sebgie** [comment]
I would also be interested in using this feature :). Has there been any progress yet? What would be a good starting point for making this work?

**Comment by rhys-vdw** [comment]
Hi @sebgie, doesn't look like anybody has tackled this yet. You're welcome to have a crack. Should be as simple as specifying a directory in the knexfile and specifying the correct knexfile via CLI. The CLI is not documented well presently, unfortunately, but the code is quite simple IIRC.

**Comment by confuser** [comment]
Has any work been done on this? Just came across a use case that would benefit from this. A couple of questions before I open a PR, if one is still welcome?

Would adding the option to use an array for the directory property within ones knex config suffice? If so, which directory would `make` default to? The first element?

**Comment by medv** [comment]
Really interested in this.

Using feathers and react-apollo, my major components can be tied to models and packaged in private NPM repos for re-use. In this case, each service would want to have not only its own graphql schema, redux reducers/actions, tests, but also its own knex migrations that would then somehow funnel up to the top-level migration using the CLI.

**Comment by devinivy** [comment]
We have an approach to do this with the current version of knex, and are using it to tie knex migrations to hapi plugins (for use with objection ORM).  This code isn't quite published, but here's the approach,
which is fully tested
https://github.com/BigRoomStudios/schwifty/blob/master/lib/migrator.js#L45

In short, we symlink all migrations into a temp directory then hand that directory to knex.

**Comment by unhawkable** [comment]
Would be great if a simple glob pattern for migrations directory is handled in migrations/directory config option.

**Comment by bruno-sartori** [comment]
any progress on this?? +1

**Comment by elhigu** [comment]
If there are no new comments in the issue, there has not been any progress. I will remove any future status update requests / +1 comments to prevent those from spamming issues. (it's been a bit of problem that issues in knex has been flooded with unrelated discussion / status update requests)

**Comment by devinivy** [comment]
It would be great to have support in knex, but it really wasn't so bad to code around.  One year later since https://github.com/tgriesser/knex/issues/607#issuecomment-276647062 and we're successfully still using the same approach.  Just a few days ago I refactored this routine to be totally agnostic to the package that it's a part of— it takes a knex instance, a list of migrations directories, and an indication whether to migrate to latest or rollback: https://github.com/BigRoomStudios/schwifty/blob/a3800b2294424060540afada4d2de70f145243bc/lib/migrator.js#L19

**Comment by elhigu** [comment]
I think that the #2690 will actually add support for these usecases too so closing this one in favor or #2690
