### ISSUE TITLE
Postgres function table source quoted by .from()

### ISSUE THREAD

**Issue by turnerhayes** [tgriesser/knex#613]
Hi,

I have a function , `my_table_source_function()`, that returns a SETOF one of my tables in Postgresql 9.3.5. I'm trying to construct a query that uses this function as a table source, the way I can do in the pg CLI or pgadmin3. However, when I pass it to `.from()`, it gets quoted, as though it were a table name:

```sql
select "id" from "my_table_source_function(\'{1}\'::bigint[])" as "source"
```

Is there a "raw from" sort of option (like `.whereRaw`), or is there already a solution for this that I'm missing? I looked in the docs and the source, and didn't see anything obvious.

Thanks,

Turner

**Comment by bendrucker** [comment]
Pass the string for your function call to `knex.raw` and then pass that to `from`

**Comment by turnerhayes** [comment]
Ah, I didn't realize `knex.raw()` could be used for only part of a query. I thought it was only for complete queries. Thanks!
