### ISSUE TITLE
Where with subquery

### ISSUE THREAD

**Issue by ekulabuhov** [tgriesser/knex#614]
Hi!

In your examples you have:
`knex('accounts').where('id', 'in', subquery)`

If you replace 'in' with any other operator (i.e. >, <, =, etc.) the subquery won't be wrapped in parenthesis anymore. Testing this with PG produces invalid query.

Thanks!

**Comment by sandro-csimas** [comment]
Here is how solve:
````
return UserEvent.collection().query(function(qb) {
  qb.where('circle_id', circle.id)
  qb.whereIn('user_id', entities.getIds(users))
  qb.whereIn('type', ['user_leaves', 'user_arrives'])
  qb.where('id', function() {
    this.select('last_user_event.id')
    .from('user_event as last_user_event')
    .whereRaw('last_user_event.user_id = user_event.user_id')
    .orderBy('last_user_event.occurrence_date', 'desc')
    .limit(1);
  });
})
````
Will be better if knex support subqueries as you said for the other operators.

**Comment by elhigu** [comment]
This seems to work in 0.9
