### ISSUE TITLE
Notify people that using stream() will keep a hanging sql connection which never closes if the http request is canceled

### ISSUE THREAD

**Issue by ZeusTheTrueGod** [tgriesser/knex#615]
Say you have a code which allows a user to export data from a big table

``` javascript
app.use('/', function(req, res) {
    var inputStream = knex('items').orderBy('updated_at', 'asc').select('*').stream();
    res.attachment('items.csv');
    var transformStream = csv.createWriteStream({
        headers: true
    });
    inputStream.pipe(transformStream).pipe(res);
   //WITHOUT LINES BELOW YOU GET A NEVER FINISHING REQUEST 
   req.on('close', function() {
        inputStream.end();
        console.info('input stream canceled');
    }); //if someone cancels download
});
```

If you comment req.on('close', ...) code and curl this request handler and cancel it during the downloading process, you will see one extra request in postgres:
```
SELECT datname,procpid,current_query FROM pg_stat_activity;
```

When you reach connection pool max value - no new database request can be made and they will be queued

The solution is inside the example, close the pg-stream when req emits a close event. I've tested that 'close' events happens only when someone cancels the request, during the normal request all goes well.

It would be nice to notify knexjs users about a side effect of using a request stream, spotting that bug was not trivial for me.

**Comment by bendrucker** [comment]
Where is that sql query being fired? Not sure we need to document every caveat about using streams in Node.

**Comment by ZeusTheTrueGod** [comment]
Sorry, I was wrong in explaining the case.

That sql is how I checked what are active queries in my psql database.
On every canceled download you get one more active query 'select * from items ordered by updated_at asc'  which is never released, even in an hour.

If you have connection pool set to max 5 queries, then 5 canceled downloads will hang up the whole connection pool and all other sql request will be ignored.

Why you still may have to document this is because it is a pretty reasonable idea to use the 'stream' method for exporting data for knexjs users, look at the code what I shown for csv export, or people may use a stream method for json export / fetching data via api. 

Downloading csv file is not the only case, say you have api for fetching items, and if there are like 100 000 items and a user closes the browser while app fetches data - knexjs loses one connection from the pool. 

Warning in the documentation like 'if you use stream() inside http server handler - ensure that you close your stream via'
''' javascript
req.on('close', function() {
        inputStream.end();
        console.info('input stream canceled');
}); 
'''
may help to avoid this issue.

I don't see whom else should I address this issue.

**Comment by ZeusTheTrueGod** [comment]
Thank you!

**Comment by stepankuzmin** [comment]
Hi there, @ZeusTheTrueGod! 

I've tried your solution with koa2, but I'm getting empty reply from server after I cancel a bunch of requests. Did you ever run with this issue?

P.S. btw, if I do not close stream on `req.on('close', stream.end.bind(stream))`, I'm getting:

```js
Unhandled rejection TimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
```
