### ISSUE TITLE
How to get the full SQL query ?

### ISSUE THREAD

**Issue by gchauvet** [tgriesser/knex#619]
Hi,

How can I get the full SQL query, with included parameters ?
(I need to add before SELECT statement some Postgresql options  e.g : 
SET join_collapse_limit to 1;
SET enable_nestloop = off;
)

**Comment by tgriesser** [comment]
Calling `builder.toSQL()` should give you the sql/bindings, but you'd need to then call the query yourself with `knex.raw` or something. I've got plans to overhaul the entire query construction process so it'd be possible to tap into the construction at any point for cases like this. I'll keep this open and close it once that's done with a demonstration of how that'll work.

**Comment by gchauvet** [comment]
Super :)
ATM, I create 2 raw requests  + my normal request in a transaction to do the job (because PG query options are valids in the same session only).

**Comment by tgriesser** [comment]
If it's something you're using globally, you might want to look into the `afterCreate` hook on the pool which allows you to run statements after the connection has been added to the pool but before its first use for things like that... see [this example](https://github.com/tgriesser/knex/issues/14#issuecomment-19170597).

**Comment by skout90** [comment]
i edited https://github.com/wbyoung/knex-logger, like below.
- index.js File
`'use strict';

var chalk = require('chalk');

var colored = function(fn) {
  return function() {
    var enabled = chalk.enabled;
    chalk.enabled = true;
    fn.apply(this, arguments);
    chalk.enabled = enabled;
  }
};

module.exports = function(knex, options) {
  var opts = options || {};

  return function(req, res, next) {

    // TODO: improve color support with levels for info/warn/error
    // TODO: add an option to only log if a certain number of queries occur per
    // request

    var queries = [];
    var captureQueries = function(builder) {
      var startTime = process.hrtime();
      var group = []; // captured for this builder

      builder.on('query', function(query) {
        group.push(query);
        queries.push(query);
      });
      builder.on('end', function() {
        // all queries are completed at this point.
        // in the future, it'd be good to separate out each individual query,
        // but for now, this isn't something that knex supports. see the
        // discussion here for details:
        // https://github.com/tgriesser/knex/pull/335#issuecomment-46787879
        var diff = process.hrtime(startTime);
        var ms = diff[0] * 1e3 + diff[1] * 1e-6;
        group.forEach(function(query) {
          query.duration = ms.toFixed(3);
        });
      });
    };

    var logQueries = colored(function() {
      res.removeListener('finish', logQueries);
      res.removeListener('close', logQueries);
      knex.client.removeListener('start', captureQueries);

      queries.forEach(function(query) {
        // merge binding
        for(let bind of query.bindings) {
          query.sql = query.sql.replace('?', bind);
        }

        var color = chalk.cyan;

        console.log('%s %s %s %s',
          chalk.gray('SQL'),
          color(query.sql),
          chalk.gray('{' + query.bindings.join(', ') + '}'),
          chalk.magenta(query.duration + 'ms'));
      });
    });

    knex.client.on('start', captureQueries);
    res.on('finish', logQueries);
    res.on('close', logQueries);

    next();
  };
};
`
