### ISSUE TITLE
Join or clause can't compare to constants

### ISSUE THREAD

**Issue by morungos** [tgriesser/knex#626]
Currently, it doesn't seem to be possible to generate a query like the following (in MySQL):

```
select * from `users` inner join `contacts` on `users`.`id` = `contacts`.`id` and `users`.`name` = 'mungo'
```

My test looks approximately like this. Basically, the on clause doesn't work with the richness of the where clause, and it probably should. Of course, with integer values JS can tell the difference between strings and identifiers, but not for strings, so it's escaping a string value as an identifier in all cases. 

This is needed because for left and right joins, you can't move the on clause to the where clause. 

```
    it("complex join with string value", function() {
      testsql(qb().select('*').from('users').join('contacts', function(qb) {
        qb.on('users.id', '=', 'contacts.id').andOn('users.name', 'mungo');
      }), {
        mysql: {
          sql: 'select * from `users` inner join `contacts` on `users`.`id` = `contacts`.`id` or `users`.`name` = \'mungo\'',
          bindings: []
        },
        default: {
          sql: 'select * from "users" inner join "contacts" on "users"."id" = "contacts"."id" or "users"."name" = \'mungo\'',
          bindings: []
        }
      });
    });
```

I'll probably work on a patch/pull request later.

**Comment by bendrucker** [comment]
I encountered a variant of this before. I have a join somewhere like this:

```js
this.on('pledges.id', 'payments.pledge_id')
      .on('payments.paid', knex.raw(true));
````

The solution here is to use `knex.raw`. To close this, I'd like to get a docs update and a test for that. Tackling that now.

**Comment by bendrucker** [comment]
Important change I realized was needed while testing. `knex.raw(true)` is fine, but you can't do the same for a string since it won't be escaped. So the documented recommendation is to use a binding:

```js
this.on('pledges.id', 'payments.pledge_id')
      .on('payments.paid', knex.raw('?', [true]));
```

I know this looks gross but I can't think of a better way to address it.

**Comment by morungos** [comment]
Thanks for this, and it certainly resolves my immediate problem. That makes me happy, as it was a blocker. 

I'm happy to consider this closed, but I'd suggest that .on and .where should handle cases consistently as far as possible, just to make the API as clean as possible. I tried the object argument style with .on, and that certainly didn't behave. I'd like to be able to do this without .raw if I can, because my app works with personal health information, and every .raw needs to be audited as a security vulnerability for SQL injection, although I can see the bindings style should make that trivially easy in this case. 

If you don't mind, I'm going to look into it some more and see if I can find a way to make this easier. I'd suggest by adding the object argument style allowed by .where, because that's already broken and so can't break existing code.

**Comment by bendrucker** [comment]
Happy to take a proposal or PR for a better API

**Comment by cedw032** [comment]
I solved this problem with the following code

```
.innerJoin('fixtures', (builder) => {
        builder.on('fixtures.competition_id', 'competitions.id').andOnIn('sport_id', [sportId]);
      })
```

**Comment by OlivierCavadenti** [comment]
As I can read, we always need to make something, maybe I can reopen it if anyone want to make a PR ?
