### ISSUE TITLE
Subqueries in insert statements

### ISSUE THREAD

**Issue by whitelynx** [tgriesser/knex#627]
Using a subquery inside `.insert()` without wrapping it in a function yields an incorrect query.

Is there a reason for the requirement of wrapping the subquery in a function? I can't think of any use case where a user passing a subquery `QueryBuilder` instance to one of the functions would _not_ want it wrapped with parenthesis.

As far as implementation, we could change [Formatter#parameter()](https://github.com/tgriesser/knex/blob/master/lib/formatter.js#L33) to check for subqueries by checking if `value instanceof QueryBuilder` like [Formatter#checkRaw()](https://github.com/tgriesser/knex/blob/master/lib/formatter.js#L40) does.

----

Test cases
----------

### Case 1: A literal value

This query works as expected:
```javascript
db('geom_text').insert({description: 'a point!', geom: 'POINT(-71.064544 42.28787)'}).toString();
```
...this results in:
```
insert into "geom_text" ("description", "geom") values ('a point!', 'POINT(-71.064544 42.28787)')
```

### Case 2: A direct subquery

This one, however, fails:
```javascript
var subquery = db().select(db.raw('?', ['POINT(-71.064544 42.28787)']));
db('geom_text').insert({description: 'a point!', geom: subquery}).toString();
```
...resulting in:
```
insert into "geom_text" ("description", "geom") values ('a point!', select 'POINT(-71.064544 42.28787)')
```

### Case 3: A subquery returned by a function

This query, works as expected again:
```javascript
db('geom_text').insert({description: 'a point!', geom: function()
{
    return this.select(db.raw('?', ['POINT(-71.064544 42.28787)']));
}}).toString();
```
...resulting in:
```
insert into "geom_text" ("description", "geom") values ('a point!', (select 'POINT(-71.064544 42.28787)'))
```

**Comment by bendrucker** [comment]
So this is more an omission than anything. Knex is calling `toString` implicitly and that's why the value isn't wrapped. Your solution sounds fine to me.

**Comment by whitelynx** [comment]
Actually, looking at it again, `Formatter#parameter()` calls `Formatter#checkRaw()`, which does the check for a `QueryBuilder` instance... the problem seems to be simply that the `parameter` isn't passed through to `Formatter#outputQuery()`'s `alwaysWrapped` flag, which it probably should be.

I'll get that in a PR.
