### ISSUE TITLE
Oracle Formatter and ORA-00904

### ISSUE THREAD

**Issue by jthomm** [tgriesser/knex#632]
Since Oracle interprets quoted and non-quoted identifiers differently, the database throws ORA-00904 ("invalid identifier") when Knex's formatter wraps my identifiers in quotes.

For example:

``` js
var tableName = 'employees';
var predicate = {name: 'Johnson'};

knex.select('*').from(tableName).where(predicate); // throws ORA-00904

var newTableName = tableName.toUpperCase();
var newPredicate = {};
for (property in predicate) {
  if (predicate.hasOwnProperty(property)) {
    newPredicate[property.toUpperCase()] = predicate[property];
  }
}

knex.select('*').from(newTableName).where(newPredicate); // works fine
```

In order to avoid this error, I either find myself `.toUpperCase()`-ing all my variables containing identifiers before passing them to Knex or rewriting `Formatter_Oracle.prototype.wrapValue` in lib/dialects/oracle/formatter.js to do it for me:

``` js
// Wraps a value (column, tableName) with the correct ticks.
Formatter_Oracle.prototype.wrapValue = function(value) {
  // jthomm adding `.toUpperCase()`
  return (value !== '*' ? '"' + value.toUpperCase() + '"' : '*');
};
```

I'm not suggesting you guys implement it this way but I was wondering if there is an idiomatic way for me override `Formatter_Oracle.prototype.wrapValue` with my own function when I instantiate the client or something.  Right now I'm literally changing the code in my local Knex installation every time I want to connect to an Oracle database.

**Comment by jthomm** [comment]
Just realized I can replace `wrapValue` after I instantiate my client:

```js
var knex = require('knex')({client: 'oracle'});

knex.client.Formatter.prototype.wrapValue = function (value) {
  return (value !== '*' ? '"' + value.toUpperCase() + '"' : '*');
};
```

This is better than what I was doing before but I wonder if this could be streamlined for Oracle users with a config option:

```js
var knex = require('knex')({
  client: 'oracle',
  caseSensitive: false // uses the version of `wrapValue` above to coerce all identifiers to uppercase
});
```

Something to consider, anyway...

**Comment by bendrucker** [comment]
Can you please post a query as it appears now and then what your modifications would output for the same query?

**Comment by jthomm** [comment]
Sure.  Using the example from above:

```js
var selectCols = ['department', 'age', 'manager'];
var tableName = 'employees';
var predicate = {name: 'Johnson'};

var query = knex.select(selectCols).from(tableName).where(predicate);
```

`query` will execute the below SQL:

```sql
select "department", "age", "manager" from "employees" where "name" = 'Johnson'
```

However, unless the table was created using all lowercase, quoted identifiers (not a common practice in Oracle), the database will store table and column identifiers in all caps internally.

Therefore, with the modified `wrapValue`, you get the following SQL (which does not result in ORA-00904):

```sql
select "DEPARTMENT", "AGE", "MANAGER" from "EMPLOYEES" where "NAME" = 'Johnson'
```

**Comment by bendrucker** [comment]
I'm not an Oracle user and am still not clear on the issue here. It sounds to me like your columns are uppercased but you're supplying them as lowercase to knex. Unless there's a setting in Oracle that uppercases identifiers regardless of the case provided when they were created, I don't think this merits an option right now. 

Overriding the formatter allow you to get exactly what you want for your convention without adding a documentation burden for a special option.

I'm not actively using this stuff though, so I'm interested to at least hear some evidence for why this should be included.

If you can get some other Oracle users to weigh in on case sensitivity and there's a strong interest in an option, we'll certainly add it.

**Comment by tgriesser** [comment]
I'm pretty sure this is related to #473 and is part of the reason I'm looking to rewrite the query generation to be able to tap into this stuff more elegantly than the proposed change in that PR. 

So @jthomm you might want to take a look at that patch/ticket for the time being, but other than that there will be a more idiomatic way of being able to customize a lot of things like this coming sometime soon.

**Comment by jthomm** [comment]
> Unless there's a setting in Oracle that uppercases identifiers regardless of the case provided when they were created

That is exactly what Oracle does.  Unless you create your object using quoted identifiers with specific casing (which Oracle strenuously discourages), the database will uppercase all table and column identifiers before executing the statement.  So when Knex wraps identifiers in quotes, it more than likely represents a break from how the database stores the object internally.

> Overriding the formatter allow you to get exactly what you want for your convention without adding a documentation burden for a special option.

I agree for the most part.  My issue was more an FYI to other Oracle users saying "Hey, this is what you have to do to make Knex usable for you" than a bug or a feature request.

> I'm pretty sure this is related to #473

@tgriesser Yes, that's exactly the issue, although I don't have the stones to send non-quoted text from the web to the database.  I think, at least for Oracle, uppercasing identifiers and then wrapping them in quotes is just as effective, and probably safer.  But that's my opinion!

Thanks guys.

**Comment by bendrucker** [comment]
Got it. Definitely sounds like a situation where 99% of users would expect things to work the way you have it set up.

**Comment by hosred** [comment]
I wish also if we could return column names in lowercase
as option

this should done by building the query like this

select id as "id",name as "name" from wfd where id = ?


so the return JSON has properties in lowercase.

oracle by default return column names in UPPER case


I'm testing knex with strong-oracle on oracle 11g

Regards.

**Comment by vschoettke** [comment]
@jthomm No stones required. If you look at the pull request you will see that only column/table names matching `/^([a-z_])+([a-z0-9_]*)$/` that are non-reserved keywords where not quoted.

I didn't kept that pull-request up to date because I switched away from using the column/table directly in the query as string to using variables instead. 

@hosred Your proposal does not work for queries where the columns are not known (e.g. `select *`). Therefore I chose the more universal/hacky approach to lowercase all uppercase result column names.

**Comment by smendozaisf** [comment]
Any update on this? Is there a way for oracle devs to add something like caseSensitive false?

**Comment by kgeis** [comment]
@smendozaisf, Oracle does not have that option.

**Comment by smendozaisf** [comment]
@kgeis Did you read the thread?

**Comment by kgeis** [comment]
@smendozaisf, yes, I have read the thread. I probably misunderstood your initial comment though.

**Comment by elhigu** [comment]
In knex 0.14 one will be able to override formatters for identifiers https://github.com/tgriesser/knex/pull/2217

**Comment by destiny117** [comment]
For anyone finding this issue on google. Here's the solution using [wrapIdentifier](http://knexjs.org/#Installation-wrap-identifier) with the latest release (0.14.4):

```
var knex = require("knex")({
  "client"     : "oracledb",
  "connection" : { your connection string },
  // convert all identifiers to uppercase (Oracle standard)
  "wrapIdentifier": (value, origImpl, queryContext) => origImpl(value.toUpperCase())
});
```
