### ISSUE TITLE
Wrong Where Criteria

### ISSUE THREAD

**Issue by ozum** [tgriesser/knex#633]
Hello,

I want to build a query in a loop based on given parameters, but not to execute it. Actual queries are more complex, which I need to use parentheses and functions in "where" method. I simplified the example to make it easy and small.

Suppose I want to build the query below:

    select * from "account"
    where "city" = '23'
    and ("account_owner" = '1' or "account_team" = '2')
    and ("contact_owner" = '1' or "contact_team" = '2')

The code below produces wrong query by executing callback of "where" method at the execution of toString() method and "contact_owner" and "contact_team" added twice:

    // This code produces:
    //
    // select * from "account"
    // where "city" = '23'
    // and ("contact_owner" = '1' or "contact_team" = '2')
    // and ("contact_owner" = '1' or "contact_team" = '2')

    var knex        = require('knex')({ debug: false, client: 'pg' });
    var query       = knex.select('*').from('account').where('city', '23');
    var tables      = {
        'account': { 'level': 'N' },
        'contact': { 'level': 'N' }
    };

    for (tableName in tables) {
        if (tables.hasOwnProperty(tableName)) {
            console.log('A: ' + tableName);

            query.where(function() {
                console.log('B: ' + tableName);
                this.where(tableName + '_owner', 1)
                    .orWhere(tableName + '_team', 2);
            })
        }
    }

    console.log(query.toString());

I know I need to use function to generate parentheses. For testing, the code below produces correct table names, but without parentheses:

    // This code produces:
    //
    // select * from "account"
    // where "city" = '23'
    // and "account_owner" = '1' or "account_team" = '2'
    // and "contact_owner" = '1' or "contact_team" = '2'

    var knex        = require('knex')({ debug: false, client: 'pg' });
    var query       = knex.select('*').from('account').where('city', '23');
    var tables      = {
        'account': { 'level': 'N' },
        'contact': { 'level': 'N' }
    };

    for (tableName in tables) {
        if (tables.hasOwnProperty(tableName)) {
            console.log('A: ' + tableName);

            query.where(tableName + '_owner', 1)
                 .orWhere(tableName + '_team', 2);
        }
    }

    console.log(query.toString());

I'm not sure if this is a bug, or I use Knex wrong. If this is not a bug, could you please suggest a method for generating parentheses in a loop.

Thank you,

**Comment by johanneslumpe** [comment]
Your issue has nothing to do with `knex`, but rather with the fact that you are trying to use block scope in javascript, something that will only be available in es6 using the `let` statement. In order to use a variable in a loop, you need to close-over it, for it to be preserved. This is an issue a lot of beginners run into.

I would suggest the following version, where you do not need to close over anything, and also can skip your `hasOwnProperty` check:

````javascript
var query       = knex.select('*').from('account').where('city', '23');
var tables      = {
    'account': { 'level': 'N' },
    'contact': { 'level': 'N' }
};

Object.keys(tables).forEach(function (tableName) {
        query.where(function() {
            console.log('B: ' + tableName);
            this.where(tableName + '_owner', 1)
                .orWhere(tableName + '_team', 2);
        })
});

console.log(query.toString());
// logs:
// select * from "account"
// where "city" = '23'
// and ("account_owner" = 1 or "account_team" = 2)
// and ("contact_owner" = 1 or "contact_team" = 2)
````

Antalya sana selam söylüyor ;)

**Comment by ozum** [comment]
Dear @johanneslumpe,

Your example solves my problem in this particular scenario with extra added scope. However, please examine execution order of code below. (I think knex "where" method is a snyc method not an async one. Correct me if I'm wrong, I'll change my code according to it.).

    var knex        = require('knex')({ debug: false, client: 'pg' });
    var query       = knex.select('*').from('account');
    var tables      = {
        'account': { 'level': 'N' },
        'contact': { 'level': 'N' }
    };

    Object.keys(tables).forEach(function (tableName) {
        console.log('A');
        query.where(function() {
            console.log('B');
        })
    });

    console.log(query.toString());
    // logs:
    // A
    // A
    // B
    // B
    // select * from "account" where (true) and (true)

If "where" method is a sync method, one expects this log:

    // logs:
    // A
    // B
    // A
    // B
    // select * from "account" where (true) and (true).

Although I solved my particular problem, I'll be happy, if you clarify this one for me to understand working of knex.

Best Regards,

You should visit Antalya again between late May - late June for optimum weather for sea and sun :) But instead, I'll suggest you visiting Bodrum or Cesme in July. Drop me a message for suggestions :)

**Comment by johanneslumpe** [comment]
@ozum The callback you're passing to `where` is lazily executed, meaning that as long as you do not use the query, the callback will never be called. You can easily see this, if you remove the call to `toString`. You will only get a log of `A` twice. Only after calling `toString` you will see the logs from your callback.

I assume that this type of lazy execution is what threw you off track. 

Just to clarify: I live in Antalya ;)

**Comment by ozum** [comment]
@johanneslumpe
Oh, I see. This lazy behaviour causes me to scratch my face. Is it possible to add this behaviour into methods' documentation please?

Thank you for your help. It solved my current problems and prevented possible future problems.

Antalya is a great city to live in ;) I hope other readers enjoy my suggestions.

**Comment by johanneslumpe** [comment]
@tgriesser Should this be mentioned in the docs?
