### ISSUE TITLE
ER_CANT_CREATE_TABLE: Can't create table 'test.#sql-1_2' (errno: 150)

### ISSUE THREAD

**Issue by nathasm** [tgriesser/knex#634]
I have a migration that I use to set up the initial schema. For my tests, I start up a Docker mysql instance and another for my tests to run and link them together through fig. Then I use the migration API to initialize my MySQL tables prior to running my tests.

    before(function (done) {
      bookshelf.knex.migrate.latest().then(function() {
        done();
      });
    });

    after(function(done) {
      bookshelf.knex.migrate.rollback().then(function() {
        done();
      });
    });

Migration for tables:

    exports.up = function(knex, Promise) {
      return knex.schema.createTable('users', function(t) {

        t.increments('id').primary();
        t.string('username').unique().notNull();
        t.string('email').unique().notNull();
        t.string('password').notNull();
        t.timestamps();
      }).createTable('companies', function(t) {

        t.increments('id').primary();
        t.string('name').unique().notNull();
        t.timestamps();

      });
    };

    exports.down = function(knex, Promise) {
      return knex.schema.dropTable('companies').dropTable('users');
    };

The error I am getting only happens on my Docker instances run from Ubuntu. When I am using boot2docker on my mac, everything works as it should (e.g. tables created, tests run, rollback occurs):

    ER_CANT_CREATE_TABLE: Can't create table 'test.#sql-1_2' (errno: 150)
    web_1 |     at Query.Sequence._packetToError (/src/node_modules/mysql/lib/protocol/sequences/Sequence.js:48:14)
    web_1 |     at Query.ErrorPacket (/src/node_modules/mysql/lib/protocol/sequences/Query.js:82:18)
    web_1 |     at Protocol._parsePacket (/src/node_modules/mysql/lib/protocol/Protocol.js:271:23)
    web_1 |     at Parser.write (/src/node_modules/mysql/lib/protocol/Parser.js:77:12)
    web_1 |     at Protocol.write (/src/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    web_1 |     at Socket.<anonymous> (/src/node_modules/mysql/lib/Connection.js:82:28)
    web_1 |     at Socket.emit (events.js:95:17)
    web_1 |     at Socket.<anonymous> (_stream_readable.js:765:14)
    web_1 |     at Socket.emit (events.js:92:17)
    web_1 |     at emitReadable_ (_stream_readable.js:427:10)
    web_1 |     at emitReadable (_stream_readable.js:423:5)
    web_1 |     at readableAddChunk (_stream_readable.js:166:9)
    web_1 |     at Socket.Readable.push (_stream_readable.js:128:10)
    web_1 |     at TCP.onread (net.js:529:21)
    ....

Does this error make sense? What would be causing it to try and create that sql table? Any insight on what is happening under the hood would be appreciated? It may be a docker issue but right now I'm thinking it may be something with knex?

**Comment by bendrucker** [comment]
First, return the promises in your `before` and `after` hooks if you're using Mocha. What you're doing right now won't catch errors properly and will just time out if something goes wrong. 

As for that particular error, I can't see how knex would be involved. If you turn on `debug` and share the queries, happy to help you debug further.

**Comment by tgriesser** [comment]
From looking at the MySQL [error codes](http://dev.mysql.com/doc/refman/5.0/en/innodb-error-codes.html), it looks as though that code/message is referring to a foreign key constraint issue?
