### ISSUE TITLE
Running seed files in particular order

### ISSUE THREAD

**Issue by demisx** [tgriesser/knex#637]
I have a few  seed files with inter dependencies. What are the best practices to make seed files run in a specific order, so I don't get errors about failed foreign key constraints? Should I prefix them with numbers, i.e. `01_`, `02_`... or is there a better way? Thank you.

**Comment by bendrucker** [comment]
That's one option. Seeds are sorted by `Array.prototype.sort` so you can rely on alphabetical order. Your other option is to run seeds that have dependencies in a single file so you have full control over the control flow. Keep in mind that you can always `require` stuff from another folder (including json) to keep organized.

**Comment by orlando** [comment]
In case someone is looking for a solution, I'm using the code in migrations to generate the timestamp to prepend it to the seed file. https://github.com/tgriesser/knex/blob/f66b524af71adf434cddc1830fd9b369d2f48a32/src/migrate/index.js#L411-L426

I think is a good idea to have it that way by default @bendrucker, if that's the case I can send a PR

**Comment by orlando** [comment]
Adding @tgriesser for input

**Comment by xdevnull** [comment]
@orlando what about
```knex seed:make $(date +%s)_UsersTableSeeder```

**Comment by quyle92** [comment]
I use `_runSeeds` prototype to run seeding files in custom order:[(https://github.com/knex/knex/blob/f66b524af71adf434cddc1830fd9b369d2f48a32/src/seed/index.js#L19).](https://github.com/knex/knex/blob/f66b524af71adf434cddc1830fd9b369d2f48a32/src/seed/index.js#L19)
- First, creating database.seeder.js and use the following script:
```
const environment = process.env.ENVIRONMENT || 'development'
const config = require('./knexfile')[environment];
const knexInstance = require('knex')(config);
(async () => {
    let seeding_list = [
        '/usr/local/var/www/got-to-goal-nodejs-sql/src/db/seeds/teams.seeder.js',
        '/usr/local/var/www/got-to-goal-nodejs-sql/src/db/seeds/players.seeder.js',
        '/usr/local/var/www/got-to-goal-nodejs-sql/src/db/seeds/superpowers.seeder.js',
        '/usr/local/var/www/got-to-goal-nodejs-sql/src/db/seeds/characters.seeder.js',
        '/usr/local/var/www/got-to-goal-nodejs-sql/src/db/seeds/characters_players.seeder.js',
        '/usr/local/var/www/got-to-goal-nodejs-sql/src/db/seeds/games.seeder.js',
        '/usr/local/var/www/got-to-goal-nodejs-sql/src/db/seeds/games_players.seeder.js',
    ] // => here is a list of seeding files that you want to run in specific order.
    await knexInstance.seed._runSeeds(seeding_list)
})()
```
- then run the database.seeder.js: `$ node /path/to/database.seeder.js`
