### ISSUE TITLE
The operator "in" is not permitted

### ISSUE THREAD

**Issue by ozum** [tgriesser/knex#638]
I need to use "in" operator inside leftJoin.

```
knex.select('*').from('users').leftJoin('accounts', function() {
    this.on('accounts.id', 'in', '(1,2,3,4,5,6)');
});
```

I got error: 'The operator "in" is not permitted'

For inner joins, as a workaround I may move conditions to "where" conditions. However for left joins it is difficult and error prone to move it to where condition.

Of course my actual queries are much more complex than this.

Is there a way to use "in" operator on "on"?

**Comment by tgriesser** [comment]
For now you might want to do it with a raw query in the on statement, but I'll look into adding support for this.

**Comment by Rush** [comment]
I second the request.

**Comment by absolux** [comment]
@Rush 
Use `onIn`
```js
knex.select('*').from('users').leftJoin('accounts', () => this.onIn('accounts.id', [1, 2, 3]))
```

**Comment by wubzz** [comment]
Closing, resolved by using `onIn`
