### ISSUE TITLE
strong-oracle support not installed with npm install knex

### ISSUE THREAD

**Issue by hosred** [tgriesser/knex#640]
Hi

strong-oracle support is not found in the latest version when installed by npm
npm install knex

the downloaded version is 0.7.3 not include the strong-oracle

**Comment by bendrucker** [comment]
There has not been a release since that was added. You can use a git dependency to pin your knex version to a particular commit instead.

**Comment by tgriesser** [comment]
I'll get a release out with this and other fixes soon

**Comment by llambda** [comment]
FYI, Oracle just published its own Oracle-maintained nodejs driver at https://github.com/oracle/node-oracledb. I wanted to bring this up because it is new and people may not be aware of it yet. I intend to make some time to try it and out and get it working with Knex.

**Comment by firrae** [comment]
@llambda did you get the official driver working? I haven't tried it yet with knex but it's what the prototype used in my project.

**Comment by elhigu** [comment]
@firrae official driver is now used in travis CI tests and all tests are currently passing with it.
