### ISSUE TITLE
Allow SQL functions in #defaultTo

### ISSUE THREAD

**Issue by anthonator** [tgriesser/knex#643]
In Postgres I'm trying to create a table with a UUID primary key that defaults to ```uuid_generate_v1mc()```. This currently doesn't seem possible although I would expect it to be a common use case.

Is this possible and I'm not seeing it? If not, is this something Knex wants to support?

**Comment by bendrucker** [comment]
`col.defaultTo(knex.raw('uuid_generate_v1mc()'));`

**Comment by tkellen** [comment]
defaultsTo(knex.raw('....'))
