### ISSUE TITLE
Configure CLI with .knexrc

### ISSUE THREAD

**Issue by anthonator** [tgriesser/knex#644]
It would be great if we could configure the CLI with a ```.knexrc``` file. This way we could set defaults for options like ```--knexfile``` and ```--cwd```. This would provide some convenience and prevent us from having to specify these options each time we run a ```knex``` command.

**Comment by anthonator** [comment]
Is there still interest in a PR for this?

**Comment by tkellen** [comment]
This would need to happen in Liftoff (the cli tool knex uses), and yes, there is a desire: see tkellen/js-liftoff#8

**Comment by tkellen** [comment]
Happy to discuss this further over there!
