### ISSUE TITLE
TypeError: Object #<ColumnBuilder_PG> has no method 'inTable'

### ISSUE THREAD

**Issue by anthonator** [tgriesser/knex#645]
This could be a possible documentation problem.

I get this error:

```TypeError: Object #<ColumnBuilder_PG> has no method 'inTable'```

when I run this command:

```js
t.uuid('order_id').inTable('orders').references('id');
```

However, when I run:

```js
t.uuid('order_id').references('id').inTable('orders');
```

it seems to work fine.

The documentation doesn't specify that ```inTable``` relies on ```references```. It communicates that ```inTable``` can be called directly on ```column```.

So either there's a bug in ```inTable``` or the documentation needs to be updated.

**Comment by anthonator** [comment]
```inTable``` documentation

http://knexjs.org/#Chainable-inTable

**Comment by bendrucker** [comment]
Ideally should work anyway but for now got some docs against this
