### ISSUE TITLE
when chaining update calls, only the last takes effect

### ISSUE THREAD

**Issue by bblack** [tgriesser/knex#647]
Whereas `where` calls can be chained like so:

```
> knex('foo').where('a', 1).where('b', 2).toString()
'select * from "foo" where "a" = \'1\' and "b" = \'2\''
```

`update` calls cannot:

```
> knex('foo').update('a', 1).update('b', 2).toString()
'update "foo" set "b" = \'2\''
```

May not exactly be a bug, but the difference has me wondering whether this is by design.

**Comment by bendrucker** [comment]
Not sure why anyone would want this but it can't hurt to have consistent behavior

**Comment by rooftopsparrow** [comment]
Also same for issue #653

**Comment by bendrucker** [comment]
As @rooftopsparrow mentioned in #653, this applies in a similar way to incrementing. These should build up rather than assuming a single call.

**Comment by wubzz** [comment]
Chaining `.update` in 0.11 seems to work

>console.log(knex('test').update('a', 2).update('b', 3).toString())
>update "test" set "a" = '2', "b" = '3'

Chaining `increment` is still not implemented.

>console.log(knex('test').increment('a', 2).increment('b', 3).toString())`
>update "test" set "b" = "b" + 3

TODO
- [ ] Chaining increment

**Comment by joaonice** [comment]
@rhys-vdw @wubzz Any update on this?

**Comment by simonecogno** [comment]
Seems like in PR #1437 there is problem to implement the chaining `insert` but it seems that there is no problem with the chaining `increment`. Any chance to add at least the chaining  `increment`? Or is there a workaroud that avoid to make X separate queries for incrementing x fields?

**Comment by wubzz** [comment]
A new PR relating to increment has been created here: 2740

Closing this issue as it originally was about `.update()` which can already be chained.
