### ISSUE TITLE
Function to escape "like" strings?

### ISSUE THREAD

**Issue by danielgindi** [tgriesser/knex#648]
It would be nice to have something like this:

``` js
...orWhere('name', 'like', '%' + knex.escapeLike(incomingArgument))...
```

I tried to find something similar in the code but haven't found one.

**Comment by vschoettke** [comment]
A simple replace would be easy, however the like generation has to be also modified to add the ESCAPE character because of DB differences.

MySQL: 
>To test for literal instances of a wildcard character, precede it by the escape character. If you do not specify the ESCAPE character, “\” is assumed.

Oracle:
LIKE ... ESCAPE esc_char
> If esc_char is not specified, then there is no default escape character.

PostgresSQL:
> To match a literal underscore or percent sign without matching other characters, the respective character in pattern must be preceded by the escape character. The default escape character is the backslash but a different one can be selected by using the ESCAPE clause.

**Comment by danielgindi** [comment]
I think that for all of the escape method we should actually query the db for escaping configuration.
I do not know about Postgres but in MySql there are different modes possible.
I have done that in a similar library for .Net and it works wonderfully.

נשלח מה-iPhone שלי

‫ב-28 בינו׳ 2015, בשעה 12:05, ‏‏Vincent Schoettke ‏<notifications@github.com> כתב/ה:‬

**Comment by killercup** [comment]
FYI, I'm currently using this in Postgres: `whereRaw("name ILIKE '%' || ? || '%'", [param]);`

**Comment by danielgindi** [comment]
Well then you are not taking care of special characters.

‏בתאריך יום שבת, 14 במרץ 2015, Pascal Hertleif <notifications@github.com>
כתב:

**Comment by killercup** [comment]
You are right. For some reason I thought this worked earlier today… I'll look into making this work with Postgres.

**Comment by esatterwhite** [comment]
I basically want to all for a case in/sensitive string match, but there doesn't seem to be a way to do this 

knex.whereRaw( 'FIELD LIKE BINARY %?%', ['term'] ). always fails. It doesn't It always escapes the term.

YOU also can't Use the bianry, or collate clause in the where function.
is there anyway to do that is semi portable?

**Comment by elhigu** [comment]
Can be added to knex.fn if someone likes to implement it for different databases and sends PR. Closing since there hasn't been much interest for this one.

**Comment by jayarjo** [comment]
Still not implemented? How can there be a lack of interest for such a common use case?

**Comment by elhigu** [comment]
Maybe it is not so common use case. Also this issue doesn't describe what that escaping should exactly do.  Remove `%` chars or something else? It is pretty opinionated functionality. If you like to implement or specify how it should work exactly, please open new feature request.
