### ISSUE TITLE
Add a gentle shutdown API

### ISSUE THREAD

**Issue by mk-pmb** [tgriesser/knex#649]
Thank you for knex!

Could you add an API call to indicate, also reflected in its name, knex should try to reduce its pool and abandon it as soon as all currently active work is done, and refuse to begin new work?

I found `.destroy()` in #55 but it would confuse maintenance programmers, as it sounds like it might interrupt work already in progress.

I'm totally fine if `.shutdownPoolSoon()` (first idea, not best) internally would just call `.destroy()`, as this would still alleviate the mismatch of intent. By shifting the burden to you, the lib maintainer, to decide whether the lib should do anything else before `.destroy()`, you free the lib consumers (programmers) of caring for yet another low-level detail that might change in future versions.

Update: Probably a no-brainer, but just to be sure: Feedback about success or failure of the shutdown request should be about whether knex will be going to abandon its pool. It should not be about whether shutdown had been requested earlier or whether the pool is abandoned yet. (An event for notification of the latter probably is somewhere in the docs, haven't read enough of them yet.)

**Comment by joaosoares** [comment]
Is there a way to do this yet?

**Comment by elhigu** [comment]
@joaosoares One can do this manually using knex events, pool.status() and knex.destroy()... Sounds pretty easy to implement and hard to test well.

There is no helpers for this in knex side. 

Not sure how your code should respond if you try to send more queries to knex instance which is trying to shutdown. Probably you just shouldnt send more queries to it to avoid need for extra error-handling 🙃

**Comment by mk-pmb** [comment]
I think you're missing the point. The main request is to shift the burden of possible future cleanup tasks. You cannot account for them manually (well, unless you're clairvoyant) as you can't yet know what kinds of cleanup tasks might be recommended in future versions.

**Comment by elhigu** [comment]
@mk-pmb I wasn't missing the point, but only answering to @joaosoares's question and provided info how to implement work around.

**Comment by mk-pmb** [comment]
Then I probably confused what he meant with "do this", I'm sorry.

**Comment by joaosoares** [comment]
Thank you @elhigu. The reason I needed a gentle shutdown API is that I'm trying to execute a one-off query on the database without the need for a persistent connection, and I wanted to call the API on a promise chain after I'm done, for example:
```javascript
const knex = Knex(dbConfig)
const oneOffQuery = knex.raw('query goes here').then((resp) => {
    console.log(resp);
    knex.gentleShutdown();
});
```

If I don't destroy the Knex instance afterwards it seems that the MySql database I'm trying to connect to doesn't close the connection, keeping a needless connection alive on the DB.

Is there an alternative way to use Knex for this use case? If so, that's what I am interested in.

**Comment by tgriesser** [comment]
As of 0.12, `knex.destroy` should now work by draining unused connections in the pool, rejecting any new connections to the pool, and waiting for all active to complete before calling the callback or returning a promise.
