### ISSUE TITLE
No mock connection available for unit testing

### ISSUE THREAD

**Issue by trevorallred** [tgriesser/knex#651]
I'm trying to unit test my application but I can't find any docs or examples of how to do this. Here's what I'm trying on my config.

```
    Knex.knex = Knex.initialize({
        debug: true,
        client: 'mysql',
        connection: {
            host     : 'FAKE_SERVER',
            user     : 'root',
            password : '',
            database : 'integration_tests',
            charset  : 'utf8'
        }
    });
```

Then I overwrite the client query:

```
    client.query = BluebirdPromise.method(function (builder) {
        var sql = builder.toSql(builder);
        var expectedSql = 'insert into `test_unit` (`id`, `name`) values (?, ?)';
        chai.assert.equal(sql, expectedSql);
        return null;
    });
```

I posted this on SO http://stackoverflow.com/questions/28165063/how-can-i-mock-a-fake-database-for-when-unit-testing-against-knex
Later I got it to work on Knex v0.5.0 but when I upgrade to 0.7.3 my unit tests now fail with the following error:

```
 Error: getaddrinfo ENOTFOUND
  at errnoException (dns.js:37:11)
  at Object.onanswer [as oncomplete] (dns.js:124:16)
  at Protocol._enqueue (/Users/trevorallred/projects/tantalim/server/node_modules/mysql/lib/protocol/Protocol.js:135:48)
  at Protocol.handshake (/Users/trevorallred/projects/tantalim/server/node_modules/mysql/lib/protocol/Protocol.js:52:41)
  at Connection.connect (/Users/trevorallred/projects/tantalim/server/node_modules/mysql/lib/Connection.js:111:18)
  at /Users/trevorallred/projects/tantalim/server/node_modules/knex/lib/dialects/mysql/index.js:105:16
  at new Promise (/Users/trevorallred/projects/tantalim/server/node_modules/bluebird/js/main/promise.js:82:37)
  at Client_MySQL.acquireRawConnection (/Users/trevorallred/projects/tantalim/server/node_modules/knex/lib/dialects/mysql/index.js:104:10)
  at Object.create (/Users/trevorallred/projects/tantalim/server/node_modules/knex/lib/pool.js:33:19)
  at Object.Pool.createResource (/Users/trevorallred/projects/tantalim/server/node_modules/knex/node_modules/generic-pool-redux/pool.js:288:12)
```

Any better suggestions?

**Comment by vschoettke** [comment]
It looks like you don't mock the driver initialization (acquireRawConnection).

knex will require and use the driver if `connection` is specified (not undefined). If you only want to verify that your query is built correctly that would be sufficient I guess. Please note that you must call `.toSQL()` directly the query builder.
e.g.:
```
var knex = require('knex')({client: 'mysql'});
var query = knex.select('test').from('testtable');
console.log(query.toSQL());
console.log(query.toString());
```

If you want to mock the whole database, mocking the mysql driver is probably easier.

**Comment by trevorallred** [comment]
I need to do more than check the syntax. I'm trying to unit test the actual query and how it reacts inside my application. How would I mock the entire database? I found this line:
https://github.com/tgriesser/knex/blob/master/knex.js#L98

```javascript
if (config.__client__) {
    client = config.__client__;
}
```
And I tried this:

```javascript
require('knex')({
    __client__: function() {
        query: function() {},
        acquireConnection: function() {},
        ...
    }
})
```

Now when I call `var sql = knex('person')` I get this error:

    TypeError: undefined is not a function

I'm pretty sure it's not able to find `function knex(tableName) {`
https://github.com/tgriesser/knex/blob/master/knex.js#L66

Any pointers?

**Comment by gchauvet** [comment]
take a look on this project : 
https://github.com/colonyamerican/mock-knex

**Comment by nmccready** [comment]
mock-knex seems ok, but not really a solid solution. This should be included in this project.

**Comment by thebearingedge** [comment]
I just started playing with `mock-knex` and like it so far. I can see how separate codebases are causing compat problems though.

**Comment by elhigu** [comment]
@nmccready I don't see much of a point for having other client just to use it as a mock for testing. It does not add a lot of value in comparison to e.g. sqlite in-memory database. Or one can use a generic mock library if just some functions needs to be mocked.

I'm not saying that mocking is useless / this would be bad feature to have in knex, but to me benefits are not worth the extra maintenance overhead it would add.

@trevorallred hope you get your mocks working though :+1:

**Comment by cbrunnkvist** [comment]
Perhaps there could be some note in the documentation summarizing different current approaches. 

I ran into this snag of wanting to mock some too, and I haven't decided how I'm going to handle it yet. At the moment it looks like I might get away with `proxyquire`:ing my DbConnection and trying to combine that with some `sinon` stub and/or mock.

**Comment by nmccready** [comment]
At realty maps we came up with a decent mocking library. We need to open
source it still. But it should help.

**Comment by oguimbal** [comment]
FYI: This is not an actual mock, but I added support of knex to [pg-mem](https://github.com/oguimbal/pg-mem).
