### ISSUE TITLE
.limit(0) not limiting to empty array

### ISSUE THREAD

**Issue by leore** [tgriesser/knex#655]
When I do .limit(0) I end up getting the entire dataset back. 0.6.* did not have this behaviour

**Comment by vschoettke** [comment]
Duplicate of #585. This is already fixed in the repo but yet not published to npm.

Just out of curiosity, why do you want to execute limit(0) query?

**Comment by leore** [comment]
We have an API that takes count and offset as query parameters. Our users and apps that consume this api have corner cases where they pass in count=0 and expect to get an empty array not the full data set.

**Comment by leore** [comment]
When do you think #585 will be published to npm?

**Comment by tgriesser** [comment]
Ah sorry abt. that... I'll do a quick pass through and try and get a release out today
