### ISSUE TITLE
query builder union ignores wrap

### ISSUE THREAD

**Issue by werkt** [tgriesser/knex#661]
The implementation of union in query builder cannot currently accept a value for 'wrap' which results in individually parenthesized union components.  The obvious intended behavior is to allow numerous union components to be specified as arguments, which requires a solution that allows wrap to be the last argument (if it is boolean), but I've implemented it as much in tgriesser/knex#660.

**Comment by bendrucker** [comment]
@werkt In the future you can pop a "Closes #661" at the end of your PR body (or in the commit) and it'll auto close when merged. Thanks again!
