### ISSUE TITLE
DELETE RETURNING support

### ISSUE THREAD

**Issue by whitelynx** [tgriesser/knex#667]
The `RETURNING` clause is supported in a `DELETE` statement by the following:
- [PostgreSQL version 8.2 and newer](http://www.postgresql.org/docs/8.2/static/sql-delete.html)
- [MariaDB version 10.0.5 and newer](https://mariadb.com/kb/en/mariadb/delete/)

Could support for it be added?

**Comment by whitelynx** [comment]
Looking more closely at the code, it looks like [QueryCompiler_PG#del](https://github.com/tgriesser/knex/blob/master/lib/dialects/postgres/query.js#L98) _is_ utilizing the `returning` clause correctly in `delete` statements. It seems that the results are incorrect, though. (I get `[ {} ]` back from the query)

I'll open a more correct issue for this. (might still make sense to implement `returning` for MariaDB, though)

**Comment by wubzz** [comment]
@whitelynx Tested this in 0.11 just now, and it seems to be supported. If you're still having issues, please re-open the issue.
