### ISSUE TITLE
Apply multiple column filters to a join?

### ISSUE THREAD

**Issue by TehNrd** [tgriesser/knex#668]
I have the requirement to perform a left outer join on a table using multiple column filters but all of the examples only show performing a join with one field from each table:

For example, joining on one field:
`knex.select('*').from('users').leftOuterJoin('accounts', 'users.id', 'accounts.user_id')`

Outputs:
`select * from 'users' left outer join 'accounts' on 'users'.'id' = 'accounts'.'user_id'`

I need to add another condition to the join but I can't seem to figure this out. Something like:
`knex.select('*').from('users').leftOuterJoin('accounts', 'users.id', 'accounts.user_id','users.state','accounts.state')`

Which needs to output:
`select * from 'users' left outer join 'accounts' on 'users'.'id' = 'accounts'.'user_id' AND 'users'.'state' = 'accounts'.'state'`

Is this possible using the standard api or will I need to build this myself with `.joinRaw()`?

**Comment by bendrucker** [comment]
Complex and/or joins are 100% supported via the callback syntax:

```js
knex
  .select('*')
  .from('users')
  .leftOuterJoin('accounts', function () {
    this
      .on('users.id', 'account.user_id')
      .on('users.state', 'accounts.state');
  });
```

I think there are ways to make this clearer and proposed and will implement in #670.

**Comment by TehNrd** [comment]
Perfect, thank you so much!

Thanks for creating a issue to update the docs as well.

**Comment by gchauvet** [comment]
hmmm, and If I want to implement this request with Knex : 
```sql
SELECT *
FROM 'users'
LEFT JOIN 'accounts'
   ON 'users'.'id' = 'accounts'.'user_id'
   AND ('users'.'state' IS NULL OR 'users'.'state' = 'accounts'.'state')
```

would be : 
```javascript
knex
  .select('*')
  .from('users')
  .leftOuterJoin('accounts', function () {
    this
      .on('users.id', 'account.user_id')
      .andOn(function () {
         this.on('users.state', '=', 'NULL');
         this.orOn('users.state', 'accounts.state');
      });
  });
```

?

**Comment by bendrucker** [comment]
You can't pass a callback to `this.on` inside a join. Not sure if this is actually possible right now. @tgriesser?

**Comment by tgriesser** [comment]
No it's not but it should be... seems currently it tries to create a subquery rather than a wrapped on clause.

**Comment by bendrucker** [comment]
Yup the above example will throw because `on` will be `EventEmitter.prototype.on` inside the deepest callback (i.e. it's a query)

**Comment by bendrucker** [comment]
Tracking this in #690

**Comment by mact200590** [comment]
and when you need to use 3 diffent tables and use join. how can i do that

**Comment by pleymor** [comment]
Another way to write it with builders:

`
knex
  .select('*')
  .from('users')
  .leftOuterJoin('accounts', (b1) => b1
      .on('users.id', 'account.user_id')
      .andOn((b2) => b2
         .on('users.state', 'NULL')
         .orOn('users.state', 'accounts.state')
      )
  });
`
