### ISSUE TITLE
Document "andOn" method in joins

### ISSUE THREAD

**Issue by bendrucker** [tgriesser/knex#670]
While responding to #668 I realized that the docs on joins could be confusing because `where` is aliased as `andWhere`. Joins have or/and semantics too and for consistency there should be an `andOn` method with an example showing it.

**Comment by bendrucker** [comment]
Never mind, it exists, just needs a mention in the docs. Also it proxies the call needlessly when it could just be a straight up alias.

**Comment by whitelynx** [comment]
:+1:

**Comment by wubzz** [comment]
Closing as these are mentioned in docs now.
