### ISSUE TITLE
describe was not found when I was running the test migration 

### ISSUE THREAD

**Issue by 3rcok** [tgriesser/knex#671]
I am new to knex and node. I didn't find step by step instruction on how to run the test.
I did 'npm install' under knex after I forked and cloned to local'
I added the following in test/knexfile.js 
client: 'mysql',

    connection: {
      host     : '127.0.0.1',
      database: 'knex_test',
      user:     'test',
      password: 'test'
    },
and running the following 

knex --debug --knexfile ./test migrate:latest

/Users/lwang/javascript/knex/test/index.js:48
describe('Unit tests', function() {
^
ReferenceError: describe is not defined
    at Object.<anonymous> (/Users/lwang/javascript/knex/test/index.js:48:1)
    at Module._compile (module.js:456:26)
Any help would be appreciated.

**Comment by bendrucker** [comment]
That's not how requires in node work. If you pass the path as `./test` the file is assumed to be `index.js` and that's the test runner. Mocha normal sets up the globals, thus the errors.
