### ISSUE TITLE
Timestamp format in a seed file

### ISSUE THREAD

**Issue by demisx** [tgriesser/knex#674]
My `created_at` column defined in migration as this:

```js
table.timestamp('created_at').notNullable().index().defaultTo(knex.raw('now()'));
```

It works fine if my seed file object doesn't have `created_at` property. I need to initialize some records with particular created date. I've tried providing the timestamp in this format and a few others,

```js
created_at: '2013-11-28 23:09:11.761166+03'
```

 but the seeding fails each time with this error:

```
 Error: Command failed: error: null value in column "created_at" violates not-null constraint
```

What is the right format to specify the timestamp in a seed file? Thank you.

**Comment by bendrucker** [comment]
You should just be able to send `Date` objects and let the DB driver figure out how to translate.

**Comment by demisx** [comment]
Yes, providing js Data object like this `created_at: new Date(98, 1)` works as long as I do this in every single seed object. If some of my seeds skip the `created_at` property, the `defaultTo` doesn't kick in and I run into ` Error: Command failed: error: null value in column "created_at" violates not-null constraint` Error as in #673. 

Looks like this issue is also related to #662. I'll initialize with explicit values until it's fixed. Thank you.

**Comment by bendrucker** [comment]
Yup, same issue. Need to consult with Tim #662 because it's a breaking change as documented. Will probably require a minor version.
