### ISSUE TITLE
Feature Idea: Helper for schema builder to create columns for storing 53-bit JavaScript integers 

### ISSUE THREAD

**Issue by elhigu** [tgriesser/knex#676]
Hi,

Since knex.js is JavaScript, would it be reasonable to add helper to schema builder to create ~53bit jsInteger type?  

Type jsInteger would be like bigInteger, except there would be automatically added check constraints for those columns to make sure, that too big values cannot be added.

**Comment by bendrucker** [comment]
Interesting idea. Right now I don't see this as a common enough need to make this a priority, although we'd certainly review a PR if you wanted to take a stab at an API.
