### ISSUE TITLE
How to alter a column using the schema builder?

### ISSUE THREAD

**Issue by myndzi** [tgriesser/knex#677]
Is there an equivalent of knex.schema.table() such as table.column('foo') ? I'm trying to change the default of an existing column in a migration file.

**Comment by bendrucker** [comment]
Right now you have to do that with `knex.raw`. Hardly ideal but updating the schema API allowing stuff like this is going to be a big undertaking.

**Comment by myndzi** [comment]
How exactly would you use knex.raw in such a case?

knex.schema.table('foo', function (table) {
// ...??
});

**Comment by tgriesser** [comment]
I think that:

```js
knex.schema.raw('alter table foo modify column bar varchar(255)')
```

should do it (you chan chain `.raw` off schema and it will run in order). But yeah this is something that I plan to add better support for soon.

**Comment by myndzi** [comment]
Okay, thanks.

**Comment by andrewaarestad** [comment]
Here's the syntax I ended up using for altering a column type:

`knex.raw('ALTER TABLE "' + table + '" ALTER COLUMN "' + column + '" TYPE ' + newType + '')`

**Comment by elhigu** [comment]
there is nowadays `.alter()`which can be used to change column type. http://knexjs.org/#Schema-alter
