### ISSUE TITLE
Mongo support

### ISSUE THREAD

**Issue by Globegitter** [tgriesser/knex#679]
Surprised I have not found any other issue about that yet, but I am just curios what knex's stance is on NoSQL dbs such as Mongo or CouchDB?

Is there any support planned at any point? Or have some kind of adapter system that others can write it easier?

Otherwise looks like a really great project.

**Comment by bendrucker** [comment]
Hey there,

Supporting NoSQL DBs has always been a wish item for [Bookshelf](http://bookshelfjs.org/). Knex specifically deals with SQL databases. I don't really see any piece of knex as it stands now that would lend itself to NoSQL. 

If you can think of anything I'd love to hear.
