### ISSUE TITLE
Can Knex do "distinct on"?

### ISSUE THREAD

**Issue by kvslee** [tgriesser/knex#681]
Can anyone explain how to build a following "distinct on" in knex? I cannot find any example in docs and forums. Thanks.

SELECT DISTINCT ON (column_1), column_2
FROM tbl_name
ORDER BY column_1, column_2;

**Comment by bendrucker** [comment]
```js
knex.select(knex.raw('distinct on ("column1")'), 'column2').from('tbl_name')
```

produces

```sql
select distinct on ("column1"), "column2" from "tbl_name"
```

**Comment by omeid** [comment]
Everything could be done through `knex.raw`, but that means it won't be portable, necessarily.

Any reason `.distinct()` couldn't be `distinct on` by default?

**Comment by serprex** [comment]
We've run into this issue, workaround:
````
> b = db('test').select('a').distinct(db.raw('on a'));b.toString()
'select distinct "a", on a from "test"'
> b._statements
[ { grouping: 'columns', value: [ 'a' ] },
  { grouping: 'columns', value: [ [Object] ], distinct: true } ]
> b._statements.unshift(b._statements.pop())
2
> b.toString()
'select distinct on a, "a" from "test"'
````

**Comment by barroudjo** [comment]
> ```js
> knex.select(knex.raw('distinct on ("column1")'), 'column2').from('tbl_name')
> ```
> 
> produces
> 
> ```sql
> select distinct on ("column1"), "column2" from "tbl_name"
> ```

If I may, for this to be valid in PostgreSQL, there should be no comma between the 

```sql
distinct on ("column1")
``` 
and

```sql
"column2"
```
In short the valid sentence in PostgreSQL is:
```sql
distinct on ("column1") "column2"
``` 
which can obviously be obtained by:
```js
knex.select(knex.raw('distinct on ("column1") "column2"').from('tbl_name')
```

**Comment by HamadaBrest** [comment]
I'm using **"knex": "0.21.2"** with **PostgreSQL**

This works form me : 
```js
knex.select('column1', 'column2').distinctOn('column1').from('tbl_name').orderBy(['column1', 'column2']);
```
You should try it 🐎
