### ISSUE TITLE
Better connection pool

### ISSUE THREAD

**Issue by myndzi** [tgriesser/knex#683]
Just creating an issue to track status/discussion of this. I spoke to tgriesser on IRC about this some days ago.

generic-pool doesn't track "checked out" objects, and it doesn't validate released objects; in short, it leaves some things to be desired. I pointed at the "advanced-pool" module, which I just tried to integrate in, but it has a problem too that doesn't address knex's needs: there doesn't appear to be a way to remove an idle object from the queue, so things like the pg error event from calling pg_terminate_backend can't readily be made to clean the object from the pool.

I am currently encountering an issue in production that I got more detail on just today, and it appears that part of the problem is generic-pool thinking it has more available objects than it does (which makes sense, production app isn't using my patched up version yet). I don't believe my patch will necessarily solve that problem, though, since it can only remove objects that HAVE been released to the pool. Either way, NOT tracking checked-out objects is a big roadblock in terms of doing this stuff cleanly.

Looking for options other than "write a new connection pooler". Any thoughts?

**Comment by bendrucker** [comment]
When Tim and I spoke earlier this week the conclusion was that a new pooling implementation was needed but we'd defer to the driver's pool if it provided one. node-mysql has a pretty good implementation. It's on the roadmap doc I've been working on, soon to be public.

No thoughts on what can be done to deal with this for the presrnt.

**Comment by myndzi** [comment]
I decided to just suck it up and write something. What do you think; should a pooler ever throw an error? I'm leaning towards a synchronous throw in the case of an erroneous release (this is definitely a code error), but silently ignoring calls to destroy ("clean up this thing that's in an uncertain state"). Release doesn't actually need to be async, it's a fire-and-forget. A resource requested by the calling code should not return an error from the underlying resource allocator; these things are separated anyway, even though they're loosely correlated. There are configurable options for timing out on requesting a resource as well as idle duration and reap interval. The raw resource allocation/destruction calls are asynchronous, though any errors returned by the destroy call will not be propagated up past the pooler.

**Comment by myndzi** [comment]
I'm sore tempted to make it promise-based, if only for the potential to know when an acquire or destroy call is sync or async (return a promise for an async call, otherwise sync)

**Comment by bendrucker** [comment]
Can't hurt to hack on this. I'd really like to get node-postgres and node-mysql on a common interface so Knex can just consume their pooling interface with minimal code. That way each db can be responsible for handling its own errors at the driver level.

And if you're gonna return a promise, always return one.

**Comment by myndzi** [comment]
What I meant was, since the pooler doesn't know about the resources it's allocating / destroying, the function for doing that work could be synchronous or asynchronous. Expecting a promise for async is a way that the pooler can know that information.

Tim mentioned that node-postgres uses generic-pool, so I'm not sure whether I'd actually want to use its own pooling mechanism for the same reasons I want to improve knex's. node-mysql's does indeed look solid, and I was considering ripping it out, but it's written to be pretty specific to databases. I'm not entirely sure what extra information the database drivers would have to act on that's useful as far as preferring their own poolers that we wouldn't also be able to make use of.

For the sake of consistency across databases, then, and also detailed understanding of connection handling, it seems desirable to use a single pooler even if it's reproducing some work in the case of mysql. This is kind of the same reasoning as using a query builder at all - minimizing the differences between databases from the user's perspective.

I did think of one other error case, which is that on initialization, the pooler should attempt to claim a resource and throw if it fails. This would primarily be to help show networking / configuration problems up front. On the other hand, once it's been proven that the resource IS available, the pooler should probably just silently keep trying if it fails when attempting to allocate a resource later, on the assumption that the failure is temporary. It's actually pretty complex to provide error logic past that, but one possibility is to throw after being unable to provide a resource for over X time...?

I can of course emit events for failed resource allocations, but that then puts some work on the consumer of the pool to get involved in managing the state of the pool's connections, which doesn't seem right.

Any thoughts on how to proactively do something about the application potentially entering an error state where it can no longer allocate resources?

**Comment by bendrucker** [comment]
> Expecting a promise for async is a way that the pooler can know that information.

Normally there's some perf concerns and you might want to do a return + callback API. Bluebird's pretty good at optimizing immediately available values and I'd rather let it do its thing and expose a single API.

> Tim mentioned that node-postgres uses generic-pool, so I'm not sure whether I'd actually want to use its own pooling mechanism for the same reasons I want to improve knex's.

Correct 

> node-mysql's does indeed look solid, and I was considering ripping it out, but it's written to be pretty specific to databases.

It's actually mostly general, with a big fat `query` method that could be removed.

The idea here would be to create and then drive adoption around a standard DB pooling module that would support things like clustering be smart about authentication (versus attempting to create a truly generic pooler). The ideal scenario would be that mysql and postgres would adopt it.

**Comment by myndzi** [comment]
Hm, I suppose there's no need for ultimate genericism, though having such a module available is beneficial still. Can you elaborate on what you mean by being smart about authentication and clustering support?

**Comment by bendrucker** [comment]
Tim and my shared conclusion from the other day was that the value of nailing the DB-specific concerns was way higher than trying to be truly generic.

**Comment by tkellen** [comment]
:+1: the whole reason you choose a database is to use the features it provides, not some generic subset that will allow you to change to another black box.

**Comment by bendrucker** [comment]
And so the ideal version is a generic interface that something like Knex can consume, but leaving it to the database to actually hook up the right listeners on its connections to make sure they're managed within the pool properly.

**Comment by myndzi** [comment]
tkellen: by that logic, you wouldn't want to use knex :) Knex does kind of prevent you from using db-specific features effectively, after all.

Ben: if we use the database driver native pools, then knex wouldn't want or need a pool at all. Are there databases that knex supports that do not have a pooling implementation?

**Comment by bendrucker** [comment]
> then knex wouldn't want or need a pool at all

Correct. Maria and SQLite don't ship with pools.

**Comment by myndzi** [comment]
Well, I've had success rewriting dialects/postgres/pool.js to use node-pg's pool, will do mysql too; I managed to get a test setup where I can run the appropriate integration tests finally. Problem: upstream/master is bombing a mysql integration test for me, and I'm not sure why.

I am just gonna hope that node-pg does the appropriate bookkeeping to avoid the production problem I'm dealing with; this seems a better shot than the other approach. If there are still problems I can run them down as best I can and submit a patch to node-postgres itself. My enthusiasm for solving the more general "make a good pool module" problem is waning fast :P

**Comment by myndzi** [comment]
1) Integration Tests Dialect: mysql Schema createTable accepts the table name, and a "container" function:

      AssertionError: expected [ Array(4) ] to deeply equal [ Array(4) ]
      + expected - actual

       [
      +  "create table `test_table_one` (`id` bigint unsigned not null auto_increment primary key, `first_name` varchar(255), `last_name` varchar(255), `email` varchar(255) null, `logins` int default '1', `about` text comment 'A comment.', `created_at` datetime, `updated_at` datetime) default character set utf8 engine = InnoDB comment = 'A table comment.'"
      -  "create table `test_table_one` (`id` bigint unsigned not null auto_increment primary key, `first_name` varchar(255), `last_name` varchar(255), `email` varchar(255) null, `logins` int default '1', `about` text comment 'A comment.', `created_at` datetime, `updated_at` datetime) engine = InnoDB comment = 'A table comment.'"
         "alter table `test_table_one` add index test_table_one_first_name_index(`first_name`)"
         "alter table `test_table_one` add unique test_table_one_email_unique(`email`)"
         "alter table `test_table_one` add index test_table_one_logins_index(`logins`)"
       ]

**Comment by myndzi** [comment]
Well, I wanted to be helpful and do mysql too, but pg is really the one that affects us with a very real problem in production so I figured I'd at least do that one. Yet, even after making the changes and passing the tests, Travis is complaining:

https://github.com/tgriesser/knex/pull/687

I don't really know what to do.

**Comment by tgriesser** [comment]
@myndzi so a heads up, node-pg uses essentially the same underlying pool as knex (generic-pool), which is why it seemed like it'd be better to just create a better one with more features like clustering out of the box based on node-mysql's implementation.

See the open issues:

https://github.com/brianc/node-postgres/issues?q=is%3Aissue+is%3Aopen+pool

**Comment by myndzi** [comment]
Yeah, I was hoping its implementation would be at least more proactive about tracking the connection stuff, and lay the groundwork for eliminating knex's pooling in favor of the db-driver pools. I also figured at least we'd get mysql's pool out of the pull, but it had problems as noted.

The more we discuss it, the less convinced I am for making a new pooler for knex's use; I think you're right about instead pushing to improve the db drivers' poolers.

I had a look through mysql's code and I'm not sure how I feel about my ability to rip it out yet.

**Comment by bendrucker** [comment]
@myndzi I'm happy to help if you're interested in working on it. But this is also a priority for me, and there's both code issues and a coordination problem here. The roadmap I'm writing up (will be public by Monday) includes a new pooler. I'd really like to get a design doc written and then get preliminary buy-in from mysql and postgres to use it. There is really no sense in duplicating effort solving this problem and hopefully a shared implementation would result in more users and therefore faster bug fixes.

**Comment by myndzi** [comment]
I am interested in working on it, and I'm definitely in favor of this approach. Perhaps we should just submit an issue to mysql requesting the separation of the pool module from the library at large; we could focus our efforts there, and also maybe gain support from people familiar with the code in question

**Comment by bendrucker** [comment]
Great. Please hold off on taking this discussion out of this thread for now. But of course by all means continue hacking on this. Really appreciate your help.

**Comment by myndzi** [comment]
I keep wavering back and forth between rip mysql's and write my own. node-mysql's tests, for example, are kind of inconvenient. The pooler is fairly intertwined with the connection methods, which are specific to node-mysql. I'm having trouble running down what happens with a network error on an underlying connection. Stuff like that. Using mysql's gives us a big advantage in trying to get people to adopt something else, but even if we wrote something different, we wouldn't have to be like "yo, mysql, use our stuff now pls" -- what they have in place seems quite robust.

I feel like it's going to be as much work to disentagle the pool from the connection and get all the tests matching up and so on as it will be to just finish up and add a few features to the one I wrote. Unless you have any objections, I think I'll do just that. I'll peruse mysql's code for ideas on what functionality to support and call it a day...?

**Comment by myndzi** [comment]
See: https://github.com/myndzi/pool2

I plan to expand on this with a clustered pool implementation that will make use of the 'capabilities' array to return a subset of the available pool resources -- for example, a database connection with write capabilities.

Comments?

**Comment by bendrucker** [comment]
I don't have the time to spend right now to think carefully about this. You're welcome to go ahead but I can't give you a firm thumbs up on anything you're proposing yet.

**Comment by myndzi** [comment]
Clustering is in now too :) Will put together a patch to utilize this instead of generic-pool.
