### ISSUE TITLE
current_date syntax in knex

### ISSUE THREAD

**Issue by kvslee** [tgriesser/knex#688]
Can anyone help to find a right syntax? I got a complaint on an syntax error near "30 days".  

Where(knex.raw('date > (CURRENT_DATE - INTERVAL "30 days")'))

Thanks.

**Comment by bendrucker** [comment]
From the [MySQL docs on dates/times](http://dev.mysql.com/doc/refman/5.5/en/date-and-time-functions.html) it looks like quotes are a no go, so `INTERVAL 30 DAY` should work.
