### ISSUE TITLE
Warning for createTableIfNotExists on sqlite3 dialect

### ISSUE THREAD

**Issue by Kagami** [tgriesser/knex#689]
Hi. I get warning:
```
SQLite3 Foreign & Primary keys may only be added on create
```
when trying to create table with `createTableIfNotExists` using sqlite3 dialect. Probably because of this line:
https://github.com/tgriesser/knex/blob/master/lib/dialects/sqlite3/schema/table.js#L84

**Comment by bendrucker** [comment]
Thanks for tracking this down!

**Comment by Kagami** [comment]
Thanks!
