### ISSUE TITLE
Allow joins to nest conditional statements

### ISSUE THREAD

**Issue by bendrucker** [tgriesser/knex#690]
Raised in https://github.com/tgriesser/knex/issues/668#issuecomment-74277245

This should be possible:

```js
.leftOuterJoin('accounts', function () {
    this
      .on('users.id', 'account.user_id')
      .andOn(function () {
         this.on('users.state', '=', 'NULL');
         this.orOn('users.state', 'accounts.state');
      });
  });
```

**Comment by gchauvet** [comment]
:+1:

**Comment by danielgindi** [comment]
It's weird that this still isn't implemented...

**Comment by tgriesser** [comment]
@danielgindi feel free to send a PR or failing tests. Otherwise it's still on my todo list

**Comment by mdaparte** [comment]
thumbs up!

**Comment by smithb1994** [comment]
Ran into the same problem... Is there a solution that exists?

**Comment by hotaru355** [comment]
:+1:

**Comment by kof3r** [comment]
Is there a chance this will get implemented any time soon? Would help me avoid a raw query... :smile:

**Comment by nkint** [comment]
any news on this?

**Comment by shinux** [comment]
very helpful feature
