### ISSUE TITLE
Add Firebird as supported platforms

### ISSUE THREAD

**Issue by ludydoo** [tgriesser/knex#691]
Hi! Just wanted to see, is anyone interested by Knex supporting Firebird?

**Comment by bendrucker** [comment]
Hey there,

We haven't heard anyone ask about this yet. We can leave it open for a few days to see if anyone wants to chime in. Otherwise we'd really need someone to take the lead on implementing this since there are a ton of priorities that come before this.

**Comment by ludydoo** [comment]
Alright let's see!

**Comment by FraGoTe** [comment]
It would be great, any other initiative to implement firebird?

**Comment by FraGoTe** [comment]
I am starting to develop the driver:

https://github.com/FraGoTe/knex/tree/testing/src/dialects/firebird


Help would be appreciated.

**Comment by RWOverdijk** [comment]
It's very much appreciated by me, even though this issue is really really old.

What's the progress on this?

**Comment by kibertoad** [comment]
@RWOverdijk Considering that last commit on that branch was 3 years ago, looks like that's about it. Probably your best shot would be forking what was done so far and finishing a PR on your own :)

**Comment by RWOverdijk** [comment]
I was hoping someone else made progress on this... Ah well. Thanks.

**Comment by elhigu** [comment]
Nowadays new dialects should be implemented as separate npm modules, more info about it in conteibuting.md

**Comment by RWOverdijk** [comment]
All right, thanks.
