### ISSUE TITLE
ON CONFLICT REPLACE

### ISSUE THREAD

**Issue by Kagami** [tgriesser/knex#694]
Hi. Simple question.

Is it possible to add `ON CONFLICT REPLACE` to the `CREATE TABLE` command? Haven't found it in the docs.

**Comment by bendrucker** [comment]
No, you'd have to go with `knex.schema.raw` for that.

**Comment by Kagami** [comment]
Any plans to support it? Raw SQL is too incompatible across databases...

**Comment by bendrucker** [comment]
Not a high priority. We'd appreciate a PR if it is one for you.

**Comment by tgriesser** [comment]
Let's tag these as closed with feature/pr so that once it becomes easier to add clauses with a more standardized query building we can find and reopen / fix pretty quickly

**Comment by zone117x** [comment]
Would be really helpful if this was supported, or "INSERT ... ON DUPLICATE KEY.. ", or any other upsert technique.
