### ISSUE TITLE
Can't create in-memory SQLite3 database

### ISSUE THREAD

**Issue by ricardograca** [tgriesser/knex#695]
Passing `:memory:` as the `filename` property will actually create a sqlite file named `:memory` in the directory where the script is run.

    var knex = require('knex')({
      client: 'sqlite3',
      connection: {filename: ':memory:'}
    })

Ubuntu 14.04 x86_64
sqlite3@3.0.5
knex@0.7.3

**Comment by ricardograca** [comment]
Nevermind. Developer stupidity...

**Comment by sidazhang** [comment]
@ricardograca Do you mind sharing your solution? I am running into the same developer stupidity here :)

**Comment by ricardograca** [comment]
Ha! It was just that I was passing `':memory'` instead of actually `':memory:'`<- Notice the lack of a colon at the end in the first case ;)
