### ISSUE TITLE
Knex 2015 Roadmap

### ISSUE THREAD

**Issue by bendrucker** [tgriesser/knex#696]
Very pleased to share the [Knex 2015 Roadmap](https://docs.google.com/document/d/1DriKNaSjg0P0MBxc1wwvWUc763j6sjKrLoTXW0lrZH8/edit?usp=sharing) with everyone!

I wrote this up with Tim over the last week or two to wrap up what we're thinking about. There are genuinely some low level changes that need to be made to support certain enhancements. Others improvements will be driven less by technical changes and more by organizational changes, chiefly breaking Knex up into smaller packages and instituting a governance policy across all the pieces of Knex. 

The [roadmap](https://docs.google.com/document/d/1DriKNaSjg0P0MBxc1wwvWUc763j6sjKrLoTXW0lrZH8/edit?usp=sharing) is a Google doc which is open for comments. We intend to update this document over the next week or two based on your feedback and then move towards implementing a lot of the proposed changes. There are no timelines (yet) for any of the described changes.

Please tweet, email, or [woof](https://www.youtube.com/watch?v=8wfG8ngFvPk) this to anyone you know who's using Knex!

If you're also a Bookshelf user, this is the first step towards addressing some of the biggest shortcomings of Bookshelf. I'm going to be drafting a very similar document in a few weeks focusing on Bookshelf—stay tuned on that!

**Comment by jonathandelgado** [comment]
Phenomenal, really looking forward to it!

**Comment by llambda** [comment]
Nice guys you rock.

**Comment by MayhemYDG** [comment]
Can't wait to use knex's query builder as a standalone module.

**Comment by gchauvet** [comment]
:+1:
A modular design will be a must have feature !

**Comment by ozum** [comment]
Please don't forget #624 for 2015. (Inspectable objects).

**Comment by ricardograca** [comment]
Looking forward to the separation of migrations and seeds. I'd like to make some improvements to that, but like mentioned in the Roadmap, I was put off by the steep learning curve and complexity of the current code base.

**Comment by Kagami** [comment]
It would be nice to have some sort of official extension API so the end-users can easily add new SQL commands to their specific needs. Probably this is already possible by extending the `QueryBuilder`/`QueryCompiler` classes but it will be good to have some documentation for this.

**Comment by jtwebman** [comment]
@bendrucker Is there anything I could get started and help you out with? I built the bookshelf-scopes plugin and would love to help out on the library. We use it here at PK4 Media so I am sure I could get some work time for it as well.

**Comment by dantman** [comment]
How much progress has been made on the 2015 roadmap?

**Comment by tgriesser** [comment]
Not a ton - closing in favor of https://github.com/tgriesser/knex/pull/1659 which will serve as a central place for progress in getting api additions / modifications for getting a 1.0 out the door
