### ISSUE TITLE
Return hierachical json data from relational database tables

### ISSUE THREAD

**Issue by kvslee** [tgriesser/knex#698]
Someone may point me a right direction to accomplish the task to return a hierarchical json data from relational database tables (see an example below). Can knex itself do this? I will appreciate if you can specify some helpful guides or examples which I can start with. Thanks much.   

Two related tables (employee and project)
employee
--------------------------------
 employee_id |       name
-------------+------------------
           1 | Jon Snow
           2 | Thoren Smallwood
           3 | Samwell Tarley

 project
-----------------------------------------------------------
 project_id | employee_id |              name
------------+-------------+--------------------------------
          1 |           1 | Infiltrate Mance Rayder's Camp
          2 |           3 | Research the Wights

Expected Json file 
[
  {
    "project_id": 1,
    "employee_id": 1,
    "name": "Infiltrate Mance Rayder's Camp",
    "employee": {
      "employee_id": 1,
      "name": "Jon Snow"
    }
  },
  {
    "project_id": 2,
    "employee_id": 3,
    "name": "Research the Wights",
    "employee": {
      "employee_id": 3,
      "name": "Samwell Tarley"
    }
  }
]

**Comment by bendrucker** [comment]
Sure, so you're basically asking for an ORM. [Bookshelf.js](http://bookshelfjs.org/) is powered by Knex and will do this sort of mapping for you.

If you don't want to use Bookshelf, you need to write light ORM code yourself. Knex isn't going to do this for you — it just executes queries and gives you back results. If you need to do mapping that's on you to implement.

**Comment by tgriesser** [comment]
Check out https://www.npmjs.com/package/french-toast or https://www.npmjs.com/package/treeize
