### ISSUE TITLE
Update default timestamp creation docs

### ISSUE THREAD

**Issue by ricardograca** [tgriesser/knex#699]
Knex now has `knex.fn.now()` which should be documented [here](http://knexjs.org/#Schema-timestamp). This was addressed in #310.

Somehow it seems that the documented solution for SQLite there doesn't work anymore. Using knex.raw("date('now')") produces a syntax error with the latest version of the npm sqlite3 package, which ships libsqlite 3.8.x.

**Comment by tkambler** [comment]
:+1:
