### ISSUE TITLE
ON DUPLICATE KEY UPDATE ?

### ISSUE THREAD

**Issue by sgarbesi** [tgriesser/knex#701]
Anyway to pull off an `on duplicate key update` for an insert statement with MySQL ?

Couldn't find anything documentation or search wise.

**Comment by bendrucker** [comment]
Right now you need to do this with raw queries.

**Comment by sgarbesi** [comment]
@bendrucker Can you supply a simple example?

**Comment by bendrucker** [comment]
From: http://dev.mysql.com/doc/refman/5.1/en/insert-on-duplicate.html

Output:
```sql
INSERT INTO table (a,b,c) VALUES (1,2,3)
  ON DUPLICATE KEY UPDATE c=c+1;
```

Input:
```js
knex.raw('INSERT INTO table (a,b,c) values (?, ?, ?) ON DUPLICATE KEY UPDATE c=c+1', [1, 2, 3]);
```

**Comment by bendrucker** [comment]
#696 outlines how we want to make edge features like this easier to support in the various databases. No timeline and it won't be in the very near future, but we're interesting in making it easier to use the query builder for creating things like this.

**Comment by avimar** [comment]
Thought this might help someone:


	var data= {
		uuid: req.params.uuid
		,accountcode: req.params.account
		, comment: req.params.feedback || null
		,createdAt : new Date()
		,updatedAt : new Date()
		};
	var query = knex('callfeedback').insert(data).toString();
	query += ' on duplicate key update ' + knex.raw('updatedAt= ?, comment = ?',[new Date(),req.params.feedback]);

	knex.raw(query).then()...

**Comment by dotnil** [comment]
```js
let insert = knex(table).insert(data)
delete data.id 
let update = knex(table).update(data)
let query = util.format('%s on duplicate key update %s', insert.toString(), update.toString().replace(/^update `[^`]+` set /i, '')
return knex.raw(query)
```

**Comment by adnanoner** [comment]
@dotnil what does this do differently than the code from @avimar ?

**Comment by dotnil** [comment]
mine is more generic.

**Comment by mwahidje** [comment]
@dotnil is the code correct? for me it produces two update keywords after `on duplicate key`. 

Example: `insert into "Users" (...) values (...) on duplicate key update update "Users" set ...`

**Comment by dotnil** [comment]
@shikasta-kashti Ah, that's because in your query the table name is wrapped with `"` instead of ```. Give the regex a try `/^update ([`"])[^\1]+\1 set/i`

**Comment by Prozi** [comment]
@dotnil thx for the code. arent u missing ) closing util.format? anyways it works with it

**Comment by dotnil** [comment]
Yes, thanks :-). It's fixed now.

**Comment by scull7** [comment]
How would one accomplish a multiple record `insert...on duplicate key update` using parameter substitution?

```sql
-- example from: https://dev.mysql.com/doc/refman/5.7/en/insert-on-duplicate.html
INSERT INTO table (a,b,c) VALUES (1,2,3),(4,5,6)
  ON DUPLICATE KEY UPDATE c=VALUES(a)+VALUES(b);
```

**Comment by woudsma** [comment]
I'm using this to insert-or-update in knex (ES6):
```js
updatePage(page) {
  const noop = () => undefined

  const { id } = page
  const content = { id, content: page }

  const result = await client('pages')
    .where({ id })
    .update(content)
    .catch(noop)
  || await client('pages')
    .insert(content)
    .catch(::console.error)

  console.log(result)
}
```

**Comment by NathanJPhillips** [comment]
```ts
function insertOrUpdate(knex: Knex, tableName: string, data: any) {
  return knex.raw(knex(tableName).insert(data).toQuery() + " ON DUPLICATE KEY UPDATE " +
    Object.getOwnPropertyNames(data).map((field) => `${field}=VALUES(${field})`).join(", "));
}
```

**Comment by dcbasso** [comment]
@NathanJPhillips it´s possible to make similar code with "batchInsert"?

**Comment by dcbasso** [comment]
I test and does not work with "batchInsert" method. 
There is a way to make INSERT OR UPDATE with BATCH of items (array of data)?

**Comment by adnanoner** [comment]
@dcbasso I've made one for postgress but perhaps you could adapt it for mysql: https://gist.github.com/adnanoner/b6c53482243b9d5d5da4e29e109af9bd

**Comment by dcbasso** [comment]
The best way for me, at my point of view is: INSERT OR UPDATE.

**Comment by dcbasso** [comment]
**ON DUPLICATE KEY UPDATE** It´s not supported by SQLITE.

**Comment by elhigu** [comment]
If someone could collect info how each database does this, maybe it could be specified what kind of API would be good for knex. If support is very different on every dialect, it might be better to have different API for each dialect.

This is pretty common request, so in this case separate implementations could be valid solution compared to unusable abstraction which works well only on one platform.

**Comment by dcbasso** [comment]
@elhigu could be one method (insertOrReplace and insertOrReplaceBatch) only and if the K'NEX knows the information about the database (connection) he can use the correct implementation... abstraction itself!

**Comment by dcbasso** [comment]
Guys in this code: https://github.com/tgriesser/knex/blob/master/src/util/batchInsert.js we have the method "insert".
Where I can find this method to take a look on the code?

**Comment by elhigu** [comment]
@dcbasso it is spread in multiple places in different dialects and in base implementation. Also builder part and compiling part of the query are two separate things... So... It is not easy to point out where the code is found.

Anyways for this issue it is not relevant either. Relevant thing is to figure out how each database engine support upsert things (as I tried to point out in my last comment). 

Then its up to community to decide what kind of support is wanted, add builder method(s) which creates internal representation of the thing and write compiler implementations to have it supported in different dialects (and obviously add docs + tests at the same time).

**Comment by dcbasso** [comment]
I wish to make my own changes here, that´s why I ask for.

**Comment by afbruno** [comment]
I did a resume that works:
/**
 * Returns an INSERT/UPDATE MYSQL command.
 * Requires knex, lodash libs.
 * @param{string} table - Table Name
 * @param{Array} data - Data Array
 * @param{Array} pks - Primary Keys
 * @return an INSERT/UPDATE Mysql command
 */

function insertUpdate(table, data, pks) {
	var firstData = data[0] ? data[0] : data;
	if (typeof pks === "undefined") {
		pks = ["id"];
	}
	var fields = _.difference(_.keys(firstData), pks);
	var str = _.map(fields, function(o) {
		return ('`%s` = VALUES(`%s`)').replace(/%s/gi, o);
	})
	return knex.raw(knex(table).insert(data).toQuery() + " ON DUPLICATE KEY UPDATE " + str.join(", ")).toString();
}

**Comment by elhigu** [comment]
There is design for this feature in https://github.com/tgriesser/knex/pull/2197 which I would like to see implemented at some point. Closing as duplicate.

**Comment by abdulkaderjeelani** [comment]
Utility funciton to generate upsert query
Usage:  ``` upsert(data, 'tableName', [], ['colName']); ```
```
exports.upsert = (t, tableName, columnsToRetain, conflictOn) => {
    const insert = knex(tableName)
        .insert(t)
        .toString();
    const update = knex(tableName)
        .update(t)
        .toString();
    const keepValues = columnsToRetain.map((c) => `"${c}"=EXCLUDED."${c}"`).join(',');
    const conflictColumns = conflictOn.map((c) => `"${c.toString()}"`).join(',');
    let insertOrUpdateQuery = `${insert} ON CONFLICT( ${conflictColumns}) DO ${update}`;
    insertOrUpdateQuery = keepValues ? `${insertOrUpdateQuery}, ${keepValues}` : insertOrUpdateQuery;
    insertOrUpdateQuery = insertOrUpdateQuery.replace(`update "${tableName}"`, 'update');
    insertOrUpdateQuery = insertOrUpdateQuery.replace(`"${tableName}"`, tableName);
    return Promise.resolve(knex.raw(insertOrUpdateQuery));
};

```

**Comment by elhigu** [comment]
@abdulkaderjeelani which is filled with SQL injection security threats...

**Comment by j0h** [comment]
Most of these solutions seems to be filled with potential SQL injection threats. Here is a simple generic function for anyone looking to do this on Postgres.

```javascript
/**
 * Knex Postgres INSERT or UPDATE
 * @param {string} knex - knex instance
 * @param {string} table - table name
 * @param {string} constraint - constraint name
 * @param {Object} keys - constraint key/value object (insert)
 * @param {Object} payload - row data values (insert and/or update)
 * @returns {Promise} - knex raw response
 */
async function insertOrUpdate(knex, table, constraint, keys, payload) {

  const update = Object.entries(payload)
    .map(([key, value]) => {
      return knex.raw('?? = ?', [key, value]);
    })
    .join(', ');

  return await knex.raw(`? ON CONFLICT ON CONSTRAINT ?? DO ${update && 'UPDATE SET ' + update || 'NOTHING'};`,
    [knex.insert({
      ...keys,
      ...payload
    }).into(table), constraint]);
}
```

Usage: If you have a **foo_bar** table with a unique key on **foo_id** and **bar_id** named **foo_bar_uk** with **data_number**, **data_string** and **data_json** columns, use the function as follows:

```javascript
const res = await insertOrUpdate(knex, 'foo_bar', 'foo_bar_uk',
  {
    foo_id: '1',
    bar_id: '2'
  },
  {
    data_number: 10,
    data_string: 'twenty',
    data_json: JSON.stringify({ a: 'b' })
  });
```
This will create an entry with all data from the **keys** and **payload** parameter, if there is a unique constraint error, the row will be updated using the values supplied in the **payload** parameter.

**Comment by felixmosh** [comment]
I've wrote tiny lib, that adds `onDuplicateUpdate` function to Knex QueryBuilder.
https://github.com/felixmosh/knex-on-duplicate-update

**Comment by leventov** [comment]
Here's an improvement of @j0h's version from https://github.com/knex/knex/issues/701#issuecomment-488075856 for **Postgres**. It doesn't require bothering with the constraint name, and re-uses inserted values via the special `excluded` table, that appears to work (unlike the original version) e. g. when an integer is inserted as JSONB.

```node
/**
 * Knex Postgres INSERT or UPDATE
 * @param {string} table - table name
 * @param {Object} keys - constraint key/value object (insert)
 * @param {Object} payload - row data values (insert and/or update)
 * @returns {Promise} - knex raw response
 */
async function insertOrUpdateQuery(table, keys, payload) {
  const update = Object.keys(payload)
    .map(key => knex.raw("?? = EXCLUDED.??", [key, key]))
    .join(", ")

  const constraint = Object.keys(keys)
    .map(key => knex.raw("??", key))
    .join(", ")

  const sql = `? ON CONFLICT (${constraint}) 
               DO ${(update && `UPDATE SET ${update}`) || "NOTHING"};`
  return knex.raw(sql, [
    knex
      .insert({
        ...keys,
        ...payload,
      })
      .into(table),
  ])
}
```

**Comment by JeffSpies** [comment]
@leventov do you happen to have an example of how one might use your function? Having difficulties using it here. Thanks in advance!

**Comment by ivoneijr** [comment]
> @NathanJPhillips it´s possible to make similar code with "batchInsert"?

Here a quick example about how to insert batch data or update few fields.

```
const query = `${knex('users')
      .insert(users)
      .toQuery()} ON CONFLICT (email) DO UPDATE SET active = EXCLUDED.active, name = EXCLUDED.name;`;

knex.raw(query);
```

**Comment by felixmosh** [comment]
> > @NathanJPhillips it´s possible to make similar code with "batchInsert"?
> 
> Here a quick example about how to insert batch data or update few fields.
> 
> ```js
> const { knex } = require('../../config/db');
> const { error } = require('../../helpers/logger');
> 
> const batchUpsert = async (users) => {
>   try {
>     const query = `${knex('users')
>       .insert(users)
>       .toQuery()} ON CONFLICT (email) DO UPDATE SET active = EXCLUDED.active, name = EXCLUDED.name;`;
> 
>     await knex.raw(query);
>   } catch (err) {
>     error(err);
>   }
> };
> 
> module.exports = {
>   upsertBatch,
> };
> ```

Knew has now a [built in support](http://knexjs.org/#Builder-onConflict) for this, no more query concats 🎉

**Comment by ivoneijr** [comment]
I know @felixmosh , but unfortunately, it didn't work.

**Comment by kibertoad** [comment]
@ivoneijr Could you please share more details, what exactly is not working?

**Comment by jardelgoncalves** [comment]
@ivoneijr, if it is `.onConflict('column').merge()`, it is probably the version of knex

**Comment by ivoneijr** [comment]
@kibertoad @jardelgoncalves I tried to use `.onConflict('colum').merge()` on postgres 13, knex version `"knex": "^0.21.1"` and it just didn't work.

**Comment by kibertoad** [comment]
@ivoneijr Please try version `^0.21.14`, and if that still doesn't work, please share the code you are using and the error that you are getting.

**Comment by ivoneijr** [comment]
@kibertoad version `0.21.14` working perfectly. Thks.

Sorry about that.

**Comment by samhess** [comment]
let url = new URL('https://pro-api.coinmarketcap.com/v1/cryptocurrency/listings/latest')
  url.search = new URLSearchParams({start:1, limit:100, convert:'USD'})
  let response = await fetch(url, {headers:{'X-CMC_PRO_API_KEY':'xxxxxxxxxxxxxxxxxxxx'}})
  let data = await response.json()
  let coins = data.data.map(coin => {
    return {
      'id' : coin.id,
      'symbol' : coin.symbol,
      'name' : coin.name,
      'slug' : coin.slug,
      'ranking': coin.cmc_rank,
      'price': coin.quote.USD.price,
      'volume24h': coin.quote.USD.volume_24h,
      'change1h': coin.quote.USD.percent_change_1h,
      'change24h': coin.quote.USD.percent_change_24h,
      'change7d': coin.quote.USD.percent_change_7d,
      'marketCap': coin.quote.USD.market_cap,
    }
  })
  let columns = Object.keys(coins[0]).join(',')
  let values = coins.reduce((acc, current) => {
    let values = Object.values(current).map(x => `'${x}'`).join(',')
    return acc + `(${values}),`
  }, '')
  values = values.slice(0,-1)
  knex.raw(`
    INSERT INTO coins (${columns})
    VALUES ${values} ON DUPLICATE KEY UPDATE 
    name=VALUES(name),
    slug=VALUES(slug),
    ranking=VALUES(ranking),
    price=VALUES(price),
    volume24h=VALUES(volume24h),
    change1h=VALUES(change1h),
    change24h=VALUES(change24h),
    change7d=VALUES(change7d),
    marketCap=VALUES(marketCap)
  `)
  .catch((err) => {
    console.log('UPSERT error:', err.message);
  })
  .then(() => console.log('UPSERT done'))

**Comment by felixmosh** [comment]
@samhess Or use my small util https://github.com/felixmosh/knex-on-duplicate-update#readme which does something similar :)

**Comment by Kostanos** [comment]
I've inspired by @NathanJPhillips and created the Gist for PostgresQL - https://gist.github.com/Kostanos/2c12029a3d917d26c2333463016a62bc

**Comment by elhigu** [comment]
Knex already supports `.onConflict()` https://knexjs.org/#Builder-onConflict
