### ISSUE TITLE
whereNot

### ISSUE THREAD

**Issue by ozum** [tgriesser/knex#713]
Hi,

How could I generate grouped negated queries without whereRaw?

For example:

    SELECT * FROM entity WHERE NOT (a = 1 OR b = 2)

Please note: The example is for the sake of simplicity, I know I can generate an equivalent query above as:

    SELECT * FROM entity WHERE (a <> 1 AND b <> 2)

However more complex queries are hard to convert and sometimes input is given as it is.

Thanks,

**Comment by bendrucker** [comment]
That's not supported at the moment but also wouldn't be terribly difficult to add

**Comment by ozum** [comment]
I sent a pull request for this. Please see #715.
