### ISSUE TITLE
Can Knex support more features on where()?

### ISSUE THREAD

**Issue by jchbh-duplicate** [tgriesser/knex#719]
Can Knex support following features in where()

1. where("id", undefined)
  Can it same as "id is null", currently it will return "id = NULL" and cause sql fail.
2. where({id: 1, name: undefined})
  Can it same as "andWhere("id", 1)"? and ignore name is undefined? 
3. where(id, [1,2,3])
  Can it same as "WhereIn"?

Write 2-3 lines code will support such features. I want to know why Knex not support them but choose to cause the generated SQL fail.

**Comment by bendrucker** [comment]
2 and 3 have both been discussed in recent issues and declined. You can use the issue search and probably dig those up without too much difficulty. 

Gonna say no on 1 as well. You expect it to work a certain way, but there's an immediate contradiction between 1 and 2. `undefined` can't be stripped sometimes and null other times with different syntaxes. 

We're going to keep everything explicit for know but are happy to entertain proposals if they can maintain clear and predictable behavior.

**Comment by jchbh-duplicate** [comment]
Thanks, I got it.
