### ISSUE TITLE
Quick Migrations Q  // 

### ISSUE THREAD

**Issue by cdaringe** [tgriesser/knex#720]
Hi all:

I'm following the CLI instructions to do a demo on migrations.  I have a brand new, empty db setup, `migrationdemo_dev`, and my knexjs file is conf'd for it.  Using the CLI, i do:

1. `knex migrate:make some-migration`
1. edit up that migration file (see bottom of this post)
1. execute the migration via `knex migrate:latest`.  It outputs a successful looking msg (Batch 1 run: 2 migrations ... /migrations/20150303111223_some-migration.js)

Per inspecting the DB, the knex-migrations table is built, and shows the migration timestamp/etc.  However, the `knex.createTable` didn't actually build the users table.  The `console.log` fired, so the function is being executed.  Just curious what I'm missing.

Thanks!

```js
// some-migration file
'use strict';

exports.up = function(knex, Promise) {
    knex.schema.createTable('users', function (table) {
      table.increments();
      table.string('name');
      table.timestamps();
    });
    console.log("BANANANANANANAS!!!");
};

exports.down = function(knex, Promise) {
  knex.schema.dropTable('users');
};
```

**Comment by cdaringe** [comment]
Ah, missing return statement.  Looks like the promise needs to be returned!

**Comment by bendrucker** [comment]
It's a common mistake and in master that triggers a warning. Should be in the latest release.
