### ISSUE TITLE
Can Knex quote an column and export a String for generate raw string?

### ISSUE THREAD

**Issue by jchbh-duplicate** [tgriesser/knex#723]
I want to generate an raw query string with correct quote the column in order to support function in sql.

How to do column name with correct quote and return string?

Example:
update t1 set a = b + c. => knex("t1").update(a, knex.raw("b+c")). 
"b+c" will not be quoted because it is an raw sql. 
can some function like 
knex.quote("b") + "+" + knex.quote("c") to return correct `b`+`c` in mysql and "b"+"c" in pg?

Thanks a lot!

**Comment by ozum** [comment]
I had same issue and here is my workaround:
WARNING: Considering it is just a workaround which uses internal methods not publicly available, it is not reliable to work in future versions.

    var knex = require('knex')({ debug: false, client: 'pg' });
    var query = knex.select('*');
    var formatter = new query.client.Formatter(); // Also this works too: new.knex.client.Formatter()
    var columnName = formatter.columnize('member.name');
    console.log(columnName);  // ---> "member"."name"

**Comment by whitelynx** [comment]
I'd like to suggest adding `knex.identifier()` and `knex.literal()`, for quoting/wrapping identifiers and literals, respectively. (I had suggested `knex.identifier()` in [this knex-postgis issue](https://github.com/jfgodoy/knex-postgis/issues/3#issuecomment-79114156)) Adding those would fix this, as well as giving us an explicit way to control how values are interpreted by knex.

**Comment by whitelynx** [comment]
To be clear, though, `knex.identifier()` and `knex.literal()` would be functions that would return `knex.Raw` instances (or some other knex object type); we would still want something like `knex.quoteIdentifier()` (returning a string instead) exposed for building raw queries.

**Comment by ozum** [comment]
@whitelynx +1

**Comment by absolux** [comment]
Maybe it's too late to answer but a simple solution could be
```js
knex("t1").update('a', knex.raw("?? + ??", ['b', 'c']))
```

**Comment by elhigu** [comment]
@absolux way is currently the official way to do it. Closing.
