### ISSUE TITLE
The genericPool is not initialized.

### ISSUE THREAD

**Issue by dcrockwell** [tgriesser/knex#724]
I seem to be getting this error randomly without changes to my code. Can anybody shed some light on which conditions can cause this error?

**Comment by scottpersinger** [comment]
I'm seeing this also. There doesn't seem to be any callback or promise on `knex()`, yet it appears that the connection pool is not actually initialized immediately when this returns...

**Comment by scottpersinger** [comment]
Ok, I think my problem was just closing the pool prematurely. Unfortunately the error message is a little obscure in that case.

**Comment by bendrucker** [comment]
Can you show/describe what you mean by closing the pool prematurely?

**Comment by scottpersinger** [comment]
Ya, I was calling 'knex.destroy()` prematurely, and then getting that error when I tried to run another query later. The issue was staring me in the face, but the 'pool not initialized' message was throwing me off.
 https://github.com/tgriesser/knex/blob/master/lib/pool.js#L57

**Comment by wreckah** [comment]
I have the same problem in my tests. I drop and create a new test database (pg) before each test suite. And my model classes which inherit knex object from the base class start producing "The genericPool is not initialized" error.

I've solved this by patching all my model classes by new knex object:
```js
// Disconnect from the test database to be able drop it.
Model.knex.destroy();

// Connect to dev database to be able to drop a test database.
var knex = Knex(knexfile.development)

knex.raw(DROP_SQL).then(function() {
  knex.raw(CREATE_SQL).then(function() {
    // Disconnect from dev database.
    knex.destroy();

    // Connect to a new test database and patch all model classes by a new knex object.
    Model.knex = Knex(knexfile.test);
    for (var model in models) {
      model.knex = Model.knex;
    }
    Model.knex.migrate.latest(knexfile.test).then(cb);
  });
});
```
I don't like this workaround. Is there any way to re-initialize the pool on existing knex object?

**Comment by tgriesser** [comment]
I believe you should now be able to call `knex.initialize` in 0.8 if you wish to re-initialize a connection pool after `knex.destroy`

**Comment by blah238** [comment]
Getting `Object [object KnexClient] has no method 'initialize' at `knex@0.8.6`.

**Comment by blah238** [comment]
Here is a Gist demonstrating my issue: https://gist.github.com/blah238/3292ef7881b3dd3c7269

It seems knex.initialize tries to call a non-existent initialize function on the client object.
