### ISSUE TITLE
using knex.raw() inside knex.andWhere() ignores arguments

### ISSUE THREAD

**Issue by hotaru355** [tgriesser/knex#726]
I am adding a `WHERE` clause the following way and it seems that the last 2 arguments are getting ignored. Is there something I am doing wrong?

    var sql = knex.andWhere(
      knex.raw('DATE_ADD(UTC_TIMESTAMP(), INTERVAL ? DAY)', [7]), '>=', 'mytable.mydate');
    console.log(sql.toString()); // SELECT * WHERE DATE_ADD(UTC_TIMESTAMP(), INTERVAL ? DAY)', 7)
    // what happened to the rest of the WHERE clause ?

**Comment by jeremiahrhall** [comment]
I am also running in to this.

**Comment by jeremiahrhall** [comment]
I'm not sure this is the cleanest fix for this bug but, I have been using this in my app for a few weeks without issue: https://github.com/jeremiahrhall/knex/commit/7bdfd352b49dd8f066643c7db41c26071004eec3

**Comment by tgriesser** [comment]
I believe this is fixed in 0.8 - let me know if you're still having issues.
