### ISSUE TITLE
knex.raw() is not a function

### ISSUE THREAD

**Issue by ozum** [tgriesser/knex#727]
I get 'raw is not a function' error when using knex raw as below:

    var knex = require('knex')({ debug: false, client: 'pg' });
    var query = knex.select('*').where('a', '=', 4);
    query = query.where('b', '=', 4);
    query = query.where(query.raw('c < 3'));  // <--- query.raw is not a function
    console.log(query.toString());

The error I get is:

    query = query.where(query.raw('c < 3'));
                              ^
    TypeError: undefined is not a function

When I change my code as below, it seems fine:

    var knex = require('knex')({ debug: false, client: 'pg' });
    var query = knex.select('*').where('a', '=', 4);
    query = query.where('b', '=', 4);
    query = query.where(knex.raw('c < 3')); // <--- knex.raw is OK.
    console.log(query.toString());

The problem is, I'm writing a utility library which I don't have knex variable available, I have just query.

Thank you,

**Comment by bendrucker** [comment]
Not sure what to tell you here. Doesn't make sense to put a `raw` method on a query. It's only available on `knex`.

**Comment by ozum** [comment]
I would like to add some custom query which may not available via knex methods.

A simplified example:

    // select * from account where "a" = '4' and "b" = '4' and "c" > "account"."balance"

    var knex = require('knex')({ debug: false, client: 'pg' });
    var query = knex.select('*').from('account').where('a', '=', 4);
    query = query.where('b', '=', 4);
    query = query.where(query.raw('"c" > "account"."balance"'));

This example may be achievable some other way, but I think it would clear my intention.

**Comment by bendrucker** [comment]
No, we're not going to add a `query.raw` method. All the query methods always add to the query and having one that just returns a value without any affect on the query would be consistent. In your example above you can just use `whereRaw` anyway.

**Comment by ozum** [comment]
@bendrucker. I was trying to add column names to standard query methods. I will try to find another way. Related to this, could you please suggest a way for #730. Thank you.
