### ISSUE TITLE
Indexes inside createTableIfNotExists

### ISSUE THREAD

**Issue by Kagami** [tgriesser/knex#729]
Hi. I've already mentioned this problem in https://github.com/tgriesser/knex/issues/322#issuecomment-74895279 but haven't got response so I've decided to create separate issue to track it down.

My use case is simple: I want to create table with an index and I'm using `createTableIfNotExists` for that. The problem is: knex run `createTableIfNotExists` callback even if table already exists so it tries to create index second time and fails.

Example to reproduce this:
```js
var knex = require("knex")({
  client: "sqlite3",
  debug: true,
  connection: {
    filename: "test.db",
  },
});

knex.schema.createTableIfNotExists("test", function(table) {
  console.log("Inside createTableIfNotExists cb");
  table.string("name").unique();
}).then(function(res) {
  console.log("OK:", res);
}).catch(function(err) {
  console.log("ERR:", err.message);
}).finally(function() {
  process.exit(1);
});
```

Output:
```bash
$ node test.js
Inside createTableIfNotExists cb
{ __cid: '__cid1',
  sql: 'create table if not exists "test" ("name" varchar(255))',
  bindings: [] }
{ __cid: '__cid1',
  sql: 'create unique index test_name_unique on "test" ("name")',
  bindings: [] }
OK: [ [], [] ]

$ node test.js
Inside createTableIfNotExists cb
{ __cid: '__cid1',
  sql: 'create table if not exists "test" ("name" varchar(255))',
  bindings: [] }
{ __cid: '__cid1',
  sql: 'create unique index test_name_unique on "test" ("name")',
  bindings: [] }
ERR: SQLITE_ERROR: index test_name_unique already exists
```

So, is there any better way to create a table only on first run other than manually check its existense with `hasTable & createTable`? Should `createTableIfNotExists` run the callback even if table already exists or is it a bug?

**Comment by chrisbroome** [comment]
I just ran into this issue today. I also think that the table definition callback shouldn't be called if the table already exists.

**Comment by bendulum** [comment]
+1

**Comment by brandonros** [comment]
I too experienced this. I as a user (without looking at the library code) wouldn't expect the inners of the createTableIfNotExists call to execute if the table exists.

**Comment by RubenCordeiro** [comment]
I agree with @chrisbroome, I don't think that the callback should be called. It is an unexpected behaviour. I would like to confirm if there is a consensus within the community.

**Comment by lintiwen** [comment]
Just to confirm, the callback IS CALLED even if the table exists right?

I'm experiencing the same confusion and I think it's counter-intuitive to call the callback in this case.

**Comment by zacronos** [comment]
I agree, the example code shows a case where the current behavior causes an error, and intuitively shouldn't be a problem.

**Comment by NerdPad** [comment]
+1

any solutions?

**Comment by jalieven** [comment]
+1

**Comment by elhigu** [comment]
There are more discussion about the topic in #1303. Closing this as duplicate.
