### ISSUE TITLE
Knex and Lodash

### ISSUE THREAD

**Issue by leore** [tgriesser/knex#731]
Knex is incompatible when using Lodash 3 is installed. Specifically migrations won't work because the diff function has been changed.

**Comment by bendrucker** [comment]
The changelog doesn't mention breaking changes to `_.difference`. Any idea what's causing the issue?

https://github.com/lodash/lodash/wiki/Changelog

**Comment by leore** [comment]
Sorry I meant "_.isEmpty()" has changed.

https://github.com/tgriesser/knex/blob/1411f2310aa6efb3242ff313038d67da3c0a347f/lib/migrate/index.js#L17

Is causing the issues

**Comment by leore** [comment]
@bendrucker let me know when there is a fix. I need to upgrade lodash.

**Comment by bendrucker** [comment]
No docs on a change there either. Are you sure it's related to lodash?

**Comment by pon** [comment]
I tried it as well - getting the same error. `validateMigrationList` is getting called with `all` as an array of arrays and `completed` is `undefined`

**Comment by bendrucker** [comment]
Ah. I'm almost sure this is fixed in #697. Prior to that `validateMigrationList` had 2 args where in reality it was getting `[all, completed]` as the only arg. 

@tgriesser this needs to go out in a patch release

**Comment by tgriesser** [comment]
Patched, let me know if it's still an issue

**Comment by leore** [comment]
@tgriesser looks like its working now. thanks
