### ISSUE TITLE
Rollback bad migrations

### ISSUE THREAD

**Issue by mgartner** [tgriesser/knex#733]
It would be great if migrations that fail automatically rollback the database to the state before the migration. It's really tough to work with writing new migrations, have them fail, then having to recreate the entire database because it's left in a funky state where it fails to rollback a step or reapply the migration.

**Comment by bendrucker** [comment]
Yup, that would be #622. The issue there is that some people may already be using transactions in their migrations and so implicitly passing one would break their code. The extracted migrations and schema packages, which I'm starting on this coming weekend, will probably merit a version bump.

**Comment by handonam** [comment]
hey @bendrucker, did you have a reference to the schema package update you were talking about?  I'm looking to transactionalize migrations, so I'm hoping you might have created a new implementation that allows me to use it.

**Comment by bendrucker** [comment]
https://github.com/knex/arctic

Haven't had time to work on it recently but it's a full API-compatible rewrite of the current migrations system. Transactions will be initially disabled and configurable via `config.migrations.transaction`. Eventually in a future breaking release it will be enabled by default.

**Comment by kimmobrunfeldt** [comment]
When starting a project now, should I use transactions in my migrations or start using arctic? The latter seems to be in quite early dev phase.

**Comment by tgriesser** [comment]
@kimmobrunfeldt the latest knex 0.8.x wraps migrations in transactions, so you can just use that
