### ISSUE TITLE
Error: The migration directory is corrupt, the following files are missing: drop-table.coffee

### ISSUE THREAD

**Issue by dariospadoni** [tgriesser/knex#734]
Hello

After updating from 0.7.2 to 0.7.5 I got this error when I run migration script. I have not changed any script and actually there's nothing to migrate but I got the error. Is it something related to the folders configuration?

**Comment by bendrucker** [comment]
Presumably related to #731. Can you edit knex in `./node_modules/knex` and log out `all` and `completed` from https://github.com/tgriesser/knex/blob/3296ba3fc0cb459c53a73264de93fbccc3e97a43/lib/migrate/index.js#L13-L14?

**Comment by dariospadoni** [comment]
Sure, this is what I get:
```
[ 'create-orders-table.coffee' ]
[ 'create-orders-table.coffee', 'drop-table.coffee' ]
```

**Comment by bendrucker** [comment]
Can you post those two scripts? This looks like it may have been a bug with your migrations that wasn't being properly raised by knex in the past.

**Comment by dariospadoni** [comment]
The point is that I have only 'create-orders-table.coffee' which inside has exports.up and exports.down; the other file ('drop-table.coffee' ) is missing

**Comment by bendrucker** [comment]
Ah, right. So you had that `drop-table.coffee` file in there at some point when you ran migrations. Knex was supposed to throw because you deleted it, but until recently the validator wasn't being called correctly. A migrations directory that no longer includes all migrations run to date is considered corrupt. You'll need to dig into the migrations table and manually delete that entry to resolve the corruption.

**Comment by dariospadoni** [comment]
That fixed the issue, thanks!

**Comment by invernizzie** [comment]
@bendrucker I'm sorry, I think I'm missing something, maybe you have a chance to clarify.

In development, I would like to go back and forth between branches that use different DB schema versions (imagine a development branch with some newer migrations, and a master branch pointing to the latest stable version). 

Before checking out an "outdated" branch, I expect to be able to rollback to a specific migration version (the latest supported by the said branch, which I still don't know exactly how to track with knex...). If I then try to run any migrations, I thought knex would only run those whose files are present and ignore the missing ones.

Of course, if knex assumes a migrations directory with missing files is "corrupted", I can't achieve this workflow. Is there any other way to do this? Or other approaches that would serve the same purpose?

**Comment by invernizzie** [comment]
Hmm I found my use case actually works, I must have done something wrong... sorry to bother.

To find out the migrations that a version included, I'm sticking with `git diff --name-only migrations/` for now.

**Comment by qw4n7y** [comment]
Actually @invernizzie had raised a reasonable question. It would be nice to have an option to skip those migrations which are in knex_migrations table but not exists on file system. that would make switching between branches much easier. please correct me if i am wrong

**Comment by kibertoad** [comment]
@qw4n7y Recommended approach is using this: https://github.com/tgriesser/knex/pull/2968 (CLI option coming soon). Then you can return to clean slate before switching to another branch without completely messing up your db.

**Comment by jayunit100** [comment]
@qw4n7y  can you provide some details on how we can use #2968 to solve the general problem of having a different knex directory ? it seems like for my app what i need is like a `-f` option that will make it so that when i do an update, it ignores missing files.

**Comment by Muhammad-Bilal-7896** [comment]
> Ah, right. So you had that `drop-table.coffee` file in there at some point when you ran migrations. Knex was supposed to throw because you deleted it, but until recently the validator wasn't being called correctly. A migrations directory that no longer includes all migrations run to date is considered corrupt. You'll need to dig into the migrations table and manually delete that entry to resolve the corruption.

Works 100% Fine For me I navigated to PGAdmin and deleted the latest row from the knex_migrations table(means the row of which table I had deleted after creating previously) and the command migration script runs perfectly. Thank you so much for your answer.

**Comment by saurabh-singh07** [comment]
> > Ah, right. So you had that `drop-table.coffee` file in there at some point when you ran migrations. Knex was supposed to throw because you deleted it, but until recently the validator wasn't being called correctly. A migrations directory that no longer includes all migrations run to date is considered corrupt. You'll need to dig into the migrations table and manually delete that entry to resolve the corruption.
> 
> Works 100% Fine For me I navigated to PGAdmin and deleted the latest row from the knex_migrations table(means the row of which table I had deleted after creating previously) and the command migration script runs perfectly. Thank you so much for your answer.

i did not get that. can you help me???
