### ISSUE TITLE
Column names are not being properly escaped in the postgreSQL dialect

### ISSUE THREAD

**Issue by jfgodoy** [tgriesser/knex#737]
Column names are not being properly escaped in the postgreSQL dialect. This allow SQL Injection.
If I do:
```
var query = knex.select('id","name').from('test')
console.log(query.toSQL())
```
I get
```
{ method: 'select',
  options: undefined,
  bindings: [],
  sql: 'select "id","name" from "test"' }
```

**Comment by tgriesser** [comment]
Thanks for finding this, patched and released in 0.6.23 and 0.7.6 - also if you see any other injection issues feel free to ping me at the email on my github so the info is a little less public.
