### ISSUE TITLE
Reference underlying bluebird promise library

### ISSUE THREAD

**Issue by thebinarypenguin** [tgriesser/knex#742]
Is there a good/supported way to access the underlying promise library (bluebird)?

I need to use `Promise.reduce()` on an array. Can I use knex's underlying promise lib or should I just `require()` my own version of bluebird?

**Comment by bendrucker** [comment]
Just use your own version of Bluebird. You'd even be fine with multiple promise libraries.

**Comment by thebinarypenguin** [comment]
Thanks
