### ISSUE TITLE
Populating foreign keys in a seed

### ISSUE THREAD

**Issue by robwilkerson** [tgriesser/knex#744]
While in the early stages of development, I'm using fake data to populate my tables. To create this data quickly, I'm using the faker module to load some dummy data. I'm currently working on a `Property` seed file that belongs to a `Landlord` and a `Neighborhood`. The latter 2 tables have been populated.

What I'm currently doing is retrieving all available neighborhood ids, then retrieving all available landlord ids, then creating _n_ property records using a random neighborhood id and a random landlord id. I have something functional, but it's not pretty. I'm no craftsman with promises, but I'd like to get there and I can't shake the feeling that there _must_ be a better way than this:

    knex.select('id').from('neighborhoods')
        .then(function(neighborhoodIds) {
            _.pluck(neighborhoodIds, 'id');

            knex.select('id').from('landlords')
                .then(function(landlordIds) {
                    landlordIds = _.pluck(landlordIds, 'id');

                    var maxRecords = 250;
                    for (var i = 0; i < maxRecords; i++) {
                        var iNeighborhood = _.random(neighborhoodIds.length - 1);
                        var iLandlord = _.random(landlordIds.length - 1);

                        promises.push(
                            createNewRecord(knex, {
                                neighborhood_id: neighborhoodIds[iNeighborhood],
                                landlord_id: landlordIds[iLandlord]
                            })
                        );
                    }
                })
            ;
        })
    ;

Would really appreciate input from folks with more experience working with Knex & promises. What can I do to clean this up?

Thanks.

**Comment by bendrucker** [comment]
Did this pretty quickly and it's late but it should work:

```js
var records = 250;

Promise.resolve([
  'neighborhoods',
  'landlords'
])
.map(function (table) {
  return knex.select('id').from(resource).pluck('id')
})
.spread(function (neighborhoods, landlords) {
  return new Array(records).map(function () {
    return {
      neighborhood_id: random(neighborhoods),
      landlord_id: random(landlords)
    };
  });
})
.then(function (properties) {
  return knex.into('properties').insert(properties);
});

function random (array) {
  return array[_.random(array.length - 1)];
}
```

**Comment by robwilkerson** [comment]
Wow. This was incredibly helpful. Thanks for taking the time.

One note for anyone that may search this later, the `new Array(records).map(...)` line doesn't work as-is because the array is filled with empty elements. As a workaround, I used `_.range(records).map(...)`. This initializes the array with actual values. A nuance in the context of the larger solution, of course, but it may save someone a few minutes down the road.

Thanks again.

**Comment by bendrucker** [comment]
No problem! The idea of `new Array(records).map(fn)` is for `fn` to run `records` times. So the intent is to have empty elements and then just map them to randomly generated records. Just a functional equivalent to:

```js
var data = [];
for (var i = 0; i < records; i++) {
  data.push(randomRecord());
}
```
