### ISSUE TITLE
Using the knexfile.js alongside bookshelf

### ISSUE THREAD

**Issue by mrozbarry** [tgriesser/knex#747]
I've noticed that bookshelf doesn't really understand the notion of knex's environment.  For instance, knexfile.js uses development, staging, and production, but there is no real method of bridging that to bookshelf unless the intention is to let the developer figure that out.

I'm building an app where it is very beneficial to use migrations and various database adaptors, but I'm not finding a good way of understanding how knex sets it's internal environment, and how to use that with bookshelf.

The reason I'm mostly confused is because knex on it's own seems to "just know" which environment to do migrations on, but I don't have a way in code to determine which.  There isn't much documentation regarding both bookshelf with a knexfile and knex migrations.

**Comment by mrozbarry** [comment]
Never mind, I just noticed the `knex --help` output.

**Comment by Wtower** [comment]
In any case, the knexfile can be used directly in bookshelf configuration:

    var knexFile = require('../knexfile.js');
    var knex = require('knex')(knexFile.development);
    var bookshelf = module.exports = require('bookshelf')(knex);

Detect if running on dev with `app.get('env')`.
