### ISSUE TITLE
No way to batch commands

### ISSUE THREAD

**Issue by jtwebman** [tgriesser/knex#748]
It would be nice if we could batch commands as they would run much faster if batched verses each one running. Would anyone be interested in a batch method that you could pass an array of knex commands and it would batch them up into a single SQL statement set to the database? If so add a +1 comment below and if the owner @tgriesser likes the idea I'll send a pull request.

**Comment by tgriesser** [comment]
Yeah this would be great, except I'm pretty sure that there'd be a lot of internals that'd need changing to get this working - it's something I'm taking a look into refactoring/provide support for, I'll make sure to reference this ticket when I get anywhere with it.

**Comment by epicmonkey** [comment]
JFYI: there is another library that might be useful to parse and batch commands: https://github.com/substack/minimist vs commander.

**Comment by wubzz** [comment]
This can technically be done already by concatenating `.toString()` on multiple querybuilders into a single large string sent to `raw`.

If the feature is still requested, please create a new issue with use case examples.

**Comment by elhigu** [comment]
This is also limitation of pg driver, which does not support sending multiple queries to DB without waiting earlier query to be executed first. With mysql driver it can be done the way @wubzz mentioned. Probably parameter bindings cannot be used in that case though making code more vulnerable to sql injection.

**Comment by gustavosizilio** [comment]
Actually, you cant. As @elhigu commented on the other issue (https://github.com/knex/knex/issues/4349) you cant do as @wubzz  suggested. So, this is not a proper answer.

**Comment by gustavosizilio** [comment]
> This can technically be done already by concatenating `.toString()` on multiple querybuilders into a single large string sent to `raw`.
> 
> If the feature is still requested, please create a new issue with use case examples.

We have a bug if we follow this approach @wubzz. Please, look at the closed issue (https://github.com/knex/knex/issues/4349)

**Comment by elhigu** [comment]
@gustavosizilio im sure @wubzz knows all about that. If you want something like this, please open proper feature request and it can be discussed there. This thread is really outdated.

**Comment by elhigu** [comment]
...and you might be able to use .toSQL() and combine sql strings + bindings to a single raw query, but I have no idea which drivers supports it.
