### ISSUE TITLE
Seed fails due to foreign key constraint

### ISSUE THREAD

**Issue by robwilkerson** [tgriesser/knex#750]
I have a number of seed files, but some depend on others having already populated their data. For example, I have a `buildings` table that has a foreign key (`neighborhood_id`) referencing the `neighborhoods` table. For the seeds to work correctly, neighborhood data must be populated before the buildings seed runs.

Surely I'm not the only one that's encountered this, but I haven't been able to turn up any solutions. I tried setting the pool to `{ min: 1, max: 1}` based on a suggestion, but that didn't change anything. What's the recommended means of ensuring data gets populated in a particular order?

**Comment by bendrucker** [comment]
If particular seeds need to run in a certain order, it's best to include them in a single file for clarity:

```js
insertSeed1().then(insertSeed2)
```
