### ISSUE TITLE
MySQL column and table names containing backticks not escaped properly

### ISSUE THREAD

**Issue by cspotcode** [tgriesser/knex#753]
Apparently MySQL table and column names are allowed to contain backticks.  Not that I would ever do that on purpose, but anyway...

http://dev.mysql.com/doc/refman/5.0/en/identifiers.html

> Permitted characters in quoted identifiers include the full Unicode Basic Multilingual Plane (BMP), except U+0000:
> * ASCII: U+0001 .. U+007F
> * Extended: U+0080 .. U+FFFF

...and...

> The following statement creates a table named a`b that contains a column named c"d:
>
>     mysql> CREATE TABLE `a``b` (`c"d` INT);

So the proper way to escape them is with a double-backtick, just like how PGSQL escapes `"` with `""`.

I've updated the tests to check that backticks in identifiers are being properly escaped.  It's in PR #752.

Related to issue #737.

**Comment by elhigu** [comment]
This seems to work correctly already:

```js
> knex('tab`le').select('d`oh').where('i`d', 'm´e').toString()
'select `d``oh` from `tab``le` where `i``d` = \'m´e\''
```
