### ISSUE TITLE
How to use same binding multiple times in query

### ISSUE THREAD

**Issue by kesavkolla** [tgriesser/knex#755]
I want to make a query like following:

select * from users where createddt > ? and accessed < ? and updated > ?

For all three where conditions the value is same.  How can I pass binding array for this?  I'm using raw to test out the query.  Currently I've to pass the same value 3 times in the binding array which I want to avoid.  

Is there any mechanism to support named bindings?

Thanks in advance

**Comment by bendrucker** [comment]
No named binding mechanism, but you can do this:

```js
knex.raw('theRawQuery', new Array(3).map(() => 'value'));

**Comment by tgriesser** [comment]
Eh this has come up enough times I'll add it.

**Comment by kesavkolla** [comment]
I think it's an useful feature either named binding or positional binding ($1,$2 etc...). Thanks for considering. 

Regards,
-Kesav

**Comment by wilmoore** [comment]
Should this be closed given https://github.com/tgriesser/knex/issues/824#issuecomment-102105163?

**Comment by wubzz** [comment]
Closing this as [named bindings](http://knexjs.org/#Raw) has been a part of knex for quite a while now.
