### ISSUE TITLE
Any hooks for to modify the connection?

### ISSUE THREAD

**Issue by memelet** [tgriesser/knex#763]
We have a set of legacy databases we need to access, where each database has the same schema but each for a different tenant. We would like to be abled to intercept the the connection acquire and perform "use tenantdb" on teh connection before it gets to the runner. I'm not seeing any hooks, but thought I would ask.

**Comment by akras14** [comment]
+1

**Comment by akras14** [comment]
@memelet check out https://github.com/tgriesser/knex/issues/14#issuecomment-19170597 and https://github.com/tgriesser/knex/issues/619. I am still testing by afterCreate might work for my use case.

**Comment by memelet** [comment]
@akras14 I don't think this will work for us. We need to 'use database' for every query, not just when the connection is added to the pool. 

More featured connection pools (in JVM land: http://brettwooldridge.github.io/HikariCP/) typically provide hooks for checkout/checkin for just this purpose.

**Comment by tgriesser** [comment]
I'm planning on adding something in for this

**Comment by akras14** [comment]
After some review, we would also need a custom hook to run on every query. 

The use case is as follows: 

- We have 20 different users in 1 database, all separated by schema. 
- We only want to maintain 10 connections to that database and pool those connections between 20 users. 
- We want to make sure every user can only access their schema, so we need a hook to set user role and schema before every request.

@tgriesser  I would appreciate if you could let me know if there is a way to do this already. Or if it will be possible using the change that you are planning to work on.

If you need help, I'd be happy to contribute with your guidance.

**Comment by myndzi** [comment]
This actually answers my question about whether there's a use case for having hooks in the pool as we were discussing before, Tim. However, since the user-facing interface to this functionality will be Knex in this case, I'm not sure whether it needs to be implemented at the pool level or not. I'm guessing it might help?

I'm also guessing with all the changes happening that my old hooks patch won't be sufficient here, and we should probably just close that pull request.

Let me know if you need support from the pool2 side of things and I'll try and put something in ASAP.

**Comment by akras14** [comment]
For our use case, we would need it at a Knex level. Obviously it would need to run for each pooled connection, but I think configuration belongs at a higher level.

Something like this

```javascript
function createConnection(SOME_CLOSURE_VALUE){
  connection = knex.initialize({
    client: 'pg',
    connection: CONNECTION_STRING,
    beforeEachCall: function(conn, done) {
      conn.query("SET search_path to " + SOME_CLOSURE_VALUE + ";", function() {
        done();
      });
    }
  });
}
```

**Comment by memelet** [comment]
I'm looking for hooks that would allow modifying the query or use db based
on values from a restapi invocation.  That is, only at that time would the
values be available.  So a pre hook defined at connection create time seems
it would not work.

**Comment by akras14** [comment]
@memelet but you could define your api call from within the hook method, and then update the query accordingly based on the result? The query won't go through until the done() is called, so it's up to you to determine when that is?

**Comment by myndzi** [comment]
It seems like it would be more straightforward to simply create a function that calls the REST api and then calls the database. Is there some reason you wouldn't just do that?

**Comment by akras14** [comment]
+1 ^ Thought of that after leaving my original comment.

But I think our use case is still valid for such hook.

**Comment by memelet** [comment]
The api call is incoming, the database (or query restricted) is derived
from parameters.  The express middleware could set state that the knex
callback would later use.

**Comment by premchelliah** [comment]
@akras14 were you able solve your 'use database' scenario? I have a similar need to do 'set session' every time a connection is acquired from the pool. Thanks!

**Comment by elhigu** [comment]
@premchelliah afterCreate is called every time after new connection is created. For this issue `.withSchema` may work? If that doesn't work and the number of tenants is not too high you might want to create separate knex instance for each tenant with some small pool setup. 

Feature which would provide work around for all of this kind of problems, would be the one, which allows user to choose using the same connection for separate queries.

**Comment by premchelliah** [comment]
@elhigu appreciate your quick response. '.afterCreate' will not work bcoz, we need to set the session (in postgres, [set session var = 'value'])  value every time the connection is acquired from the pool and not just the first time after connection creation. '.withSchema' also will not work as we have only one schema for our use case. The last solution (separate knex instance) could work; but unfortunately, we have a large user base, and this could exhaust the resources on the db. Is there a way to achieve what you mentioned 'allows user to choose using the same connection for separate queries'? Thanks again. 

BTW, this article outlines the solution we are implementing. https://blog.2ndquadrant.com/application-users-vs-row-level-security

**Comment by elhigu** [comment]
@premchelliah there is no support for such use case currently in any public APIs. Pretty much the only way to achieve that is by overriding some `knex` internal implementation...

**Comment by premchelliah** [comment]
Thank you @elhigu for clarifying.
