### ISSUE TITLE
Auto-increment based on multi-column unique constraint?

### ISSUE THREAD

**Issue by olalonde** [tgriesser/knex#764]
I have a transactions table that looks like this:

```
user_id, transaction_id, amount
```

Instead of having a global auto increment for transaction_id, I would like each unique user to have their transaction_id start at 0 and increment from there. This means that `transaction_id` wouldn't be unique but `user_id, transaction_id` would. E.g.

```
1,0,20
1,1,70
1,2,70
2,0,5
2,1,20
2,2,2
2,3,45
etc.
```

Would this be possible to do with Knex / Bookshelf or is this something database specific that I would have to handle manually in my application code? (I'm using PostgreSQL)

**Comment by kibertoad** [comment]
Closing this as a stale issue. If it's still relevant now, please consider opening a feature request with API proposal.
