### ISSUE TITLE
Issue where knex config is lost in scope of a migration

### ISSUE THREAD

**Issue by arnold-almeida** [tgriesser/knex#765]
Had a weird issue where knex lost its config from the knexfile.

A sample of what i had to do to get it working is located below.

https://gist.github.com/arnold-almeida/abc74d260d1d71098563

**Comment by bendrucker** [comment]
No idea what's going on here. If you can reproduce it in a repo we can clone and run, we can help. Otherwise it's impossible to say what you're doing wrong.
