### ISSUE TITLE
Debug

### ISSUE THREAD

**Issue by shawnwhinnery** [tgriesser/knex#769]
Is there a debug mode? Something that simply logs queries and errors?

**Comment by shawnwhinnery** [comment]
Ignore this. I don't even remember submitting the issue lol.

**Comment by tgriesser** [comment]
In 0.8 we'll be using the debug module with comprehensive debugging across the various pieces (transactions, sql, pool, etc.) - just need to get some docs written up

**Comment by tuhoojabotti** [comment]
How is it going with this? I used to override `knex.client.Runner.prototype.debug` to use our logging system (bunyan), but it seems that the latest version just calls `console.log` inline, which is not very nice.

Is there a way to listen to the query event globally for logging purposes?

**Comment by doubliez** [comment]
I was also overriding `knex.client.Runner.prototype.debug` to use our own logging system in Knex 0.7 and noticed this has been removed in version 0.8.

Do you have any plans on reintroducing this possibility? Or as @tuhoojabotti asked, is there another way to do that?
