### ISSUE TITLE
Support for FROM ONLY and UPDATE ONLY

### ISSUE THREAD

**Issue by aexmachina** [tgriesser/knex#771]
There are cases with PostgreSQL table inheritance where you need to `SELECT * FROM ONLY foo` and `UPDATE ONLY foo` because queries to the parent table operate on the parent table and all child tables. knex doesn't seem to provide any support for this.

Is this something you would consider adding? If I were to submit a PR, how would you like this exposed in the API?

**Comment by tomaspinho** [comment]
Hey, @aexmachina 

I've done a crude implementation of this feature [here](https://github.com/tgriesser/knex/pull/1874). Could you and @tgriesser take a look? Thanks.

**Comment by elhigu** [comment]
Here is link added in a way that github creates reference between issues https://github.com/tgriesser/knex/pull/1874

**Comment by elhigu** [comment]
This was implemented while ago
