### ISSUE TITLE
Does Knex offer insert/update validation? 

### ISSUE THREAD

**Issue by bluejamesbond** [tgriesser/knex#772]

**Comment by bluejamesbond** [comment]
Any details regarding this would be much appreciated

**Comment by tkellen** [comment]
Nope. If you want lifecycle functionality like that, check out [Bookshelf](http://bookshelfjs.org)!

**Comment by bluejamesbond** [comment]
I am trying to switch from NonSQL to Sql. So I'm making the transfer from mongoose to your bookshelf and Knex library. However,  I can't seem to find a parallel feature to the validation  I referred to earlier. Something like thishttp://mongoosejs.com/docs/validation.html
with bookshelf?

**Comment by tkellen** [comment]
Check out http://bookshelfjs.org/#Model-save and hook it up to whatever validation library suits your fancy.

**Comment by bendrucker** [comment]
And for validators, look at:

https://github.com/hapijs/joi

**Comment by bluejamesbond** [comment]
So we can override the save method?

**Comment by bendrucker** [comment]
No, don't do that. Use the `on('saving')` event. There are examples in the Bookshelf docs. If you're still having trouble please open an issue there.
