### ISSUE TITLE
Connection timeout / cleanup causing open connection count to grow exponentially

### ISSUE THREAD

**Issue by flakmonkey** [tgriesser/knex#773]
I noticed some strange behavior in knex that caused my node server to become unresponsive. Whenever a DB connection reaches its "idleTimeoutMillis," knex would cleanup that connection and then open two more in its place. This continues until the max connection count is reached on the DB server. This causes the node server to hang while it attempts to manage an increasing number of connections.

I experienced this issue on node v0.12.1, but the issue does not appear in v0.10.38.

Here is a sample script I used to reproduce the issue. Executing it once causes this behavior to occur.

```
var knex = require('knex')({
    "client": "mysql",
    "connection": {
      "host": "[uri-for-rds-instance]",
      "port": 3306,
      "user": "[user]",
      "password": "[pass]",
      "database": "[dbname]",
      "ssl": "Amazon RDS"
    }
  });

knex.select('id').from('user').then(function (rows) {
  console.log(rows);
}).catch(function (err) {
  console.log(err);
});
```

**Comment by tgriesser** [comment]
Yeah this is fixed in master - I'm going to go through tickets now and get an 0.8.0 published by the end of today.

**Comment by flakmonkey** [comment]
Thanks for the quick response. Do you know which commit fixed the issue? I'd like to check it out but I'm not seeing any relevant commit messages.

**Comment by tgriesser** [comment]
It was changing the connection pool implementation: https://github.com/tgriesser/knex/pull/693
