### ISSUE TITLE
web sql is broken

### ISSUE THREAD

**Issue by calvinmetcalf** [tgriesser/knex#776]
specifically `query` is undefined [here](https://github.com/tgriesser/knex/blob/4c7417af088b93c35c1bf9531d5c2efe2bfecb7a/lib/runner.js#L203) because the short circuits in [these 2 functions](https://github.com/tgriesser/knex/blob/4c7417af088b93c35c1bf9531d5c2efe2bfecb7a/lib/runner.js#L233-L238) will always trip.

**Comment by tgriesser** [comment]
Ah shoot - i'm going through the tickets now and cutting a new 0.8 release by the end of the day, I'll look to get this working

**Comment by calvinmetcalf** [comment]
not a super high priority especially as safari (sorta) supports indexedDB
