### ISSUE TITLE
Using migrations in app with multiple databases?

### ISSUE THREAD

**Issue by TehNrd** [tgriesser/knex#778]
In our app we have the need for two different databases. This could theoretically be n number of databases for an app.

I'm a bit lost as to how, and if, knex migrations will work with this type of architecture as migrations depended on the knexfile.js to declare one database for each environment. I also understand the issue with there being mutliple knex_migration tables. I suppose one of the database would contain the master knex_migration table but the migrations themselves could be run against any number of different databases.

Does anyone have any thoughts or insights on how this could be accomplished? Thanks.

**Comment by bendrucker** [comment]
I've been working on a more robust migrations API: https://github.com/knex/arctic

Even so, I don't see how the API can get involved in this. You can just create separate knex instances for each databases and run the migrations in parallel. If there's something I'm missing that knex could be doing to make this easier without doing all the work for you please elaborate.

**Comment by TehNrd** [comment]
I think I may have have completely overlooked the `--knexfile` CLI option. I could simply have two knexfile.js files that point to different databases, right?

**Comment by bendrucker** [comment]
Yeah but the better way to handle something like this if you need to automatically migrate multiple databases is using the API

**Comment by TehNrd** [comment]
Ah, yes, the migration API does seem a bit more flexible but documentation on the optional `config` object is a bit sparse. Are there examples anywhere? Does it use a standard knex config object like the following. 

```
{
  client: 'pg',
  connection: postgres://databaseUrl,
  migrations: {
    tableName: 'migrations'
  },
  directory: /somefolder/path
```
Docs currently state the properties supported are `database`, `directory`, `extension`, and `tableName` for the migrations API so should the optional config object actually look like this...?

```
{
  client: 'pg',
  database: postgres://databaseUrl,
  tableName: 'migrations',
  directory: /somefolder/path
},
  
```

I can submit a pull request to clarify the docs if you can point me in the right direction on this object.

**Comment by bendrucker** [comment]
It's not another knex config. Since the API methods sit on an existing knex instance you can only configure the things you mentioned: directory, extension, and tableName. database shouldn't even be there because that can't be set dynamically. A PR to amend that would be much appreciated.

You really shouldn't be using the config properties of the migration methods. I've implemented configuration with decorators in arctic (https://github.com/knex/arctic/blob/c847f0d55a05f94efee2102873de62135e4bd360/src/index.js#L34) so it'll be easy to eventually remove it in a future major release. 

There's rarely a good reason to mutate your migration during config for a particular call. The directory, extension, and tableName are really not ever going to change and therefore can be provided at initialization.

**Comment by TehNrd** [comment]
Got it. We essentially have two databases, a standard and performance tier. Here is what I ended up doing should anyone else come across this need.

In my main project I have a folder called `migrations` in this folder there are two sub folders named `standard` and `performance`. I still create migrations with the knex command line 'knex migrate:make --cwd './migrations/standard' migration_name' and this creates another migrations folder in each that contains all of the migrations files.

In the main top level migration folder I created a simple runMigrations.js file that uses the knex migration api to invoke migrations for both the "standard" and "performance" database. Below is what it looks like. To run the migrations it's a simple `node ./migrations/runMigrations` command.

```javascript
var async = require('async');
var standardDatabaseSettings = require('../databaseSettings')({databaseName: 'standard'});
var performanceDatabaseSettings = require('../databaseSettings')({databaseName: 'performance'});

//Run the migrations for the two databases
async.parallel([

    //Standard database migrations
    function(callback){
        //Only proceed if there is a database url provided
        if(standardDatabaseSettings.url){
			var knexStd = require('knex')({client: 'pg', connection: standardDatabaseSettings.url, migrations: {tableName: 'knex_migrations'}});
			knexStd.migrate.latest({directory: './migrations/standard/migrations'}).exec(function(err,rows){
				console.log('Standard Database Migrations completed:');
				console.log(rows);
				callback();
			}); 
		}else{
			callback();
		}
    },

    //Performance database migrations
    function(callback){
    	//Only proceed if there is a database url provided
        if(performanceDatabaseSettings.url){
			var knexPerf = require('knex')({client: 'pg', connection: performanceDatabaseSettings.url, migrations: {tableName: 'knex_migrations'}});
			knexPerf.migrate.latest({directory: './migrations/performance/migrations'}).exec(function(err,rows){
				console.log('Performance Database Migrations completed:');
				console.log(rows);
				callback();
			}); 
		}else{
			callback();
		}
    }
],
// On complete callback
function(err, results){
    if(err) throw err;
    console.log('Migrations complete.')
    process.exit();
});
```

Thanks @bendrucker for being on point with feedback and help! 

Feel free to close this issues as I am good to go now.

**Comment by bendrucker** [comment]
The way I understood the original problem is that you have two databases that need to have migrations run on them, but the database schemas are the same. If so, here's a much better way to accomplish the same thing with proper error handling:

```js
'use strict'

const Knex = require('knex')
const Promise = require('bluebird')
const extend = require('xtend')
const format = require('util').format
const settings = require('../databaseSettings')
const databases = ['standard', 'performance']

Promise.map(databases, function (database) {
  return {
    name: database,
    settings: settings[database]
  }
})
.filter(function (database) {
  return database.settings.url;
})
.bind({
  clients: []
})
.map(function (database) {
  const client = Knex({
    client: 'pg',
    connection: database.settings.url
  })
  this.clients.push(client)
  return extend(database, {
    knex: client
  })
})
.map(function (database) {
  return database.knex.migrate.latest()
    .then(function () {
      console.log('%s database migrations complete', database.name)
    })
})
.then(function () {
  console.log('All migrations complete')
})
.finally(function () {
  return Promise.map(this.clients, function (knex) {
    return knex.destroy()
  })
})
.catch(function (err) {
  console.err(err)
  process.exit(1)
})
```

If you really needed to have entirely separate migrations for both databases, just pass a config object to `migrate.latest` that uses `format` and `database.name`.

**Comment by TehNrd** [comment]
Nope, we actually have two different database with totally separate schemas.

`format`? Not seeing that in the docs.

**Comment by bendrucker** [comment]
Ok, make one small change then:

```js
return database.knex.migrate.latest({
    directory: format('./migrations/%s', database.name)
  })
```

https://nodejs.org/api/util.html#util_util_format_format

**Comment by TehNrd** [comment]
Ahh, got it. Thanks.

**Comment by bendrucker** [comment]
Do yourself a favor and stick to promises instead of trying to use async. You'll have a much better experience using knex/bookshelf.

**Comment by TehNrd** [comment]
Old habits die hard. :-/ I know I need to get on the promise train. :-)

**Comment by 4rchico** [comment]
How could I rollback the migrations when they are made in this way ?

**Comment by 4chirinos** [comment]
How could I rollback the migrations when they are made in this way ?

**Comment by weihsth** [comment]
I had the same issues and reworked / extended the version of @bendrucker ... hope someone could find it useful:

We have one "master" database and 1+n tenant_* databases.

The script is called via npm script, like `npm run db:migrate:latest` while the script in package.json looks like this:

`{
  "db:migrate:latest": "node db/migrate.js latest"
}`

db/migrate.js
`'use strict'

const Promise = require('bluebird');
const dotEnvExtended = require("dotenv-extended");
const {decrypt} = require("../callables/crypt");
const {knex} = require("knex");
const {existsSync, mkdirSync} = require("fs");

dotEnvExtended.load();

const myArgs = process.argv.slice(2);

const knownMigrationTypes = ["latest", "rollback", "up", "down", "list",]
const migrationType = myArgs[0];

if (!knownMigrationTypes.includes(migrationType)) {
    console.error('Please add migrations command (latest, rollback, up, down, list)');
    process.exit(1);
}

const masterMigrationsPath = __dirname + "/migrations/master";
const masterSeedsPath = __dirname + "/seeds/master";

const tenantsMigrationsPath = __dirname + "/migrations/tenants";
const tenantsSeedsPath = __dirname + "/seeds/tenants";

if (!existsSync(masterMigrationsPath)) {
    mkdirSync(masterMigrationsPath, {recursive: true});
}

if (!existsSync(masterSeedsPath)) {
    mkdirSync(masterSeedsPath, {recursive: true});
}

if (!existsSync(tenantsMigrationsPath)) {
    mkdirSync(tenantsMigrationsPath, {recursive: true});
}

if (!existsSync(tenantsSeedsPath)) {
    mkdirSync(tenantsSeedsPath, {recursive: true});
}

const knexConnectionMaster = knex({
    client: process.env.DB_CLIENT,
    multipleStatements: true,
    connection: {
        user: process.env.DB_USER,
        host: process.env.DB_HOST,
        port: process.env.DB_PORT,
        password: process.env.DB_PASSWORD,
        database: 'master',
        multipleStatements: true,
        // timezone: '+00:00',
        dateStrings: ['DATE', 'DATETIME', 'TIMESTAMP'],
        typeCast: (field, next) => {
            if (['DATE', 'DATETIME', 'TIMESTAMP'].includes(field.type)) {
                return new Date(field.string());
            }
            return next();
        }
    },
    migrations: {
        directory: masterMigrationsPath,
        schemaName: "master",
    },
    seeds: {
        directory: masterSeedsPath,
    },
    pool: {
        min: 2,
        max: 20,
        propagateCreateError: false
    }
});
console.log('Migrations started...');

const connections = [];

Promise
    .resolve(knexConnectionMaster.raw('update tenant set isUpdating = 1 where id > 0;'))
    .then(() => console.log('Set all tenants to updating mode.'))
    .then(() => {
        console.log(`master migrations (${migrationType}) started...`);
        let promise;
        switch (migrationType) {
            case "latest":
                promise = knexConnectionMaster.migrate.latest();
                break;
            case "rollback":
                promise = knexConnectionMaster.migrate.rollback();
                break;
            case "up":
                promise = knexConnectionMaster.migrate.up();
                break;
            case "down":
                promise = knexConnectionMaster.migrate.down();
                break;
            case "list":
                promise = knexConnectionMaster.migrate.list();
                break;
        }
        return promise.then(() => {
            console.log(`master migrations (${migrationType}) completed!`);
        })
    })
    .then(() => {
        console.log(`tenant_* migrations (${migrationType}) started...`);
        return knexConnectionMaster
            .select()
            .from('tenant_database_connection');
    })
    .map(tenantDatabaseConnection => {
        const connection = knex(getConnectionConfig(tenantDatabaseConnection, 'migration'));
        connections.push(connection);
        return {
            name: tenantDatabaseConnection.dbName,
            knex: connection
        }
    })
    .map((database) => {
        console.log(tenantsMigrationsPath);
        const config = {
            directory: tenantsMigrationsPath
        };
        let promise;
        switch (migrationType) {
            case "latest":
                promise = database.knex.migrate.latest(config);
                break;
            case "rollback":
                promise = database.knex.migrate.rollback(config);
                break;
            case "up":
                promise = database.knex.migrate.up(config);
                break;
            case "down":
                promise = database.knex.migrate.down(config);
                break;
            case "list":
                promise = database.knex.migrate.list(config);
                break;
        }
        return promise.then(() => {
            console.log(`%s database migrations (${migrationType}) completed!`, database.name);
        })
    })
    .then(() => {
        knexConnectionMaster.raw('update tenant set isUpdating = null where id > 0;')
        console.log('Set all tenants to default mode.');
    })
    .then(() => knexConnectionMaster.destroy())
    .then(() => Promise.map(connections, (knex) => knex.destroy()))
    .catch((err) => {
        // todo: rollback needed?!
        console.error(err);
        process.exit(1);
    })
    .finally(() => {
        console.log('Closed migration database connections.');
        console.log(`Migrations (${migrationType}) completed!`);
        process.exit(0);
    });

function getConnectionConfig(tenantDbData, userId) {
    let value;
    return {
        client: process.env.DB_CLIENT,
        connection: {
            host: tenantDbData.dbHost,
            port: tenantDbData.dbPort,
            user: tenantDbData.dbUsername,
            database: tenantDbData.dbName,
            password: decrypt({ // if u hav plain text PW in database, use tenantDbData.dbPassword without decrypting
                salt: tenantDbData.dbPasswordSalt,
                encryptedValue: tenantDbData.dbPassword
            }),
            multipleStatements: true,
            dateStrings: ['DATE', 'DATETIME', 'TIMESTAMP'],
            typeCast: (field, next) => {
                try {
                    if (['DATE', 'DATETIME', 'TIMESTAMP'].includes(field.type)) {
                        value = field.string();
                        return value ? new Date(value) : null;
                    }

                    return next();
                } catch (e) {
                    return next();
                }
            }
        },
        migrations: {
            directory: tenantsMigrationsPath,
        },
        seeds: {
            directory: tenantsSeedsPath,
        },
        pool: {
            min: 1,
            max: 20,
            propagateCreateError: false,
            afterCreate: function (conn, done) {
                conn.query(`SET @user_id="${userId}";`, function (err) {

                    if (err) {
                        done(err, conn);
                        return;
                    }

                    done();
                });
            },
        }
    };
}`
