### ISSUE TITLE
Allow connection strings without specifying a client

### ISSUE THREAD

**Issue by joeyespo** [tgriesser/knex#780]
I'm using an environment variable to specify the full connection string to run in different environments.

Some examples:
- `sqlite:///path/database.db`
- `postgres://user:pass@host:port/db`

This is also what I do when using Sqlalchemy. Is it possible to specify just the connection string in the config without having to manually parse out the client? If not, is this planned?

**Comment by bendrucker** [comment]
Can you collect as many connection string examples as you can find? I'll whip up a module to parse them out and then we can add this.

**Comment by tgriesser** [comment]
Yeah this seems really logical, there's no good reason for not doing this already... and I'm fairly sure `url.parse` would cover all of the cases.

**Comment by bendrucker** [comment]
`url.parse` will do a lot of the work:

```js
url.parse('postgres://user:pass@host:port/db')
```

```js
{
  protocol: 'postgres:',
  slashes: true,
  auth: 'user:pass',
  host: 'host',
  port: null,
  hostname: 'host',
  hash: null,
  search: null,
  query: null,
  pathname: '/:port/db',
  path: '/:port/db',
  href: 'postgres://user:pass@host/:port/db'
}
```

SQLite might have some edge cases

**Comment by myndzi** [comment]
That appears to be parsing the URI incorrectly. I am a bit disappointed. You might try the 'url-parse' module, it appears to do it correctly, though it seems not to give you the plain data, instead including the ':' in protocol (scheme), and the '#' and '?' in hash and query respectively.

**Comment by KaKi87** [comment]
Hello,

Using `{ connection: 'sqlite:///:memory:' }` returns a `Required configuration option 'client' is missing` error.

Thanks
