### ISSUE TITLE
Migration scripts not working for sqlite3

### ISSUE THREAD

**Issue by arnoldpistorius** [tgriesser/knex#781]
Hi,

I'm trying to create a migration script for sqlite3, but no luck;

```
npm install knex -g
mkdir testdb
cd testdb
npm install knex --save
npm install sqlite3 --save
knex init
```

My `knexfile.js`:

```
// Update with your config settings.

module.exports = {

development: {
    client: 'sqlite3',
    connection: {
      filename: './database.db'
    },
    migrations: {
      tableName: "knexmig"
    }
}

};
```

```
knex migrate:make init
```

My `migrations/20150418095606_init.js` file:

```
'use strict';

exports.up = function(knex, Promise) {
  knex.schema.createTable("testtable", function(t) {
      t.string("hello");
  })
};

exports.down = function(knex, Promise) {

};
```

```
knex migrate:latest
```

Now a database.db file is created, but only contains `knexmig` and `sqlite_sequence` tables. The `testtable` is never created.

edit: I created a public cloud9 workspace containing these files; https://ide.c9.io/arnoldpistorius/knexbug

**Comment by bendrucker** [comment]
You need to return the promise in your `up` and `down` methods:


```js
exports.up = function(knex, Promise) {
  knex.schema.createTable("testtable", function(t) {
      t.string("hello");
  })
};
```

Otherwise the connection may be destroyed before the queries actually have a chance to run.

**Comment by myndzi** [comment]
I think he means like this:
    exports.up = function(knex, Promise) {
      return knex.schema.createTable("testtable", function(t) {
          t.string("hello");
      })
    };

**Comment by bendrucker** [comment]
Oops, yes. Edited.

**Comment by arnoldpistorius** [comment]
Sorry for my late reply, but thanks, it is working now :) couldn't find an example in the documentation.
