### ISSUE TITLE
Adding foreign key constraint after table is created?

### ISSUE THREAD

**Issue by olalonde** [tgriesser/knex#782]
I have an existing table and would like to add foreign keys to it. What would be the syntax to do this?

For example:

```javascript
table.column('author').references('author_id').inTable('authors')
```

**Comment by bendrucker** [comment]
Right now that has to be done entirely with `knex.schema.raw`. The query builder only supports dropping and renaming existing columns at the moment.

**Comment by olalonde** [comment]
Ok thanks. Does it support composite foreign key constraints?

**Comment by bendrucker** [comment]
You can do whatever you'd like via raw. If it's valid SQL raw will take it.

**Comment by olalonde** [comment]
Ok, thanks.
