### ISSUE TITLE
Is there any chance of using SQL_CALC_FOUND_ROWS in MYSQL

### ISSUE THREAD

**Issue by grzegorzgolec** [tgriesser/knex#784]
Hi Iam using query with limit on large dataset and i need get the overal row count, I wanted to use **SQL_CALC_FOUND_ROWS** and **found_rows()** function. How to do that or maybe there is a built in method for that ?

**Comment by tgriesser** [comment]
You can wrap in `knex.raw` and pass as a parameter wherever you need and it should work.

**Comment by grzegorzgolec** [comment]
to which method should I pass this param ?

**Comment by tgriesser** [comment]
What's the query you're looking to make?

**Comment by grzegorzgolec** [comment]
I want to integrate into this bookshelf collection

```javascript
    new Model.PartCollection().query(function(qb){
	        
	        qb.where(_this.getHelper(userSession)).limit(limit).offset(off).orderBy("part_id",order);
	        
	        if (date) qb.where("part_stamp",">=",date);
	        if (category) qb.where({ part_pc_id: category });
	        if (status) qb.where({ part_status: status });  
	        
	    }).fetch({
	    
	    	columns:PartBase.COLUMNS,
	    	withRelated: ["detail","shipment","files","fits"]
	    
	    }).then(...
```

**Comment by mnpenner** [comment]
+1. You can't just wrap it in `knex.raw` and pass it to `.select` -- there can't be a comma after it. e.g.

```
let query = knex
    .from('emr_client')
    .select(knex.raw('SQL_CALC_FOUND_ROWS'))
    .select(mapColumns(columns))
    .limit(limit)
    .offset(offset);
```

Gives:

> `select SQL_CALC_FOUND_ROWS, `emr_client_id` as `id`, `ecl_first_name` as `firstName`, `ecl_last_name` as `lastName` from `emr_client` limit 1000` - ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ' `emr_client_id` as `id`, `ecl_first_name` as `firstName`, `ecl_last_name` as `l' at line 1

**Comment by joaomvfsantos** [comment]
Any updates on this?

**Comment by elhigu** [comment]
@joaomvfsantos Looks like tim asked for information about SQL query which one is trying to do and so far there has been no response... there are no plans to write custom knex API method for this.

**Comment by joaomvfsantos** [comment]
I guess the type of query is something on the sorts. Imagine you have a table user with a column named first_name. You want to retrieve all users that have the name 'Tim'. Imagine there are 1000 results, and you want to limit it in sets of 30, you would normally use LIMIT. Now you need to know the total number of elements. The combination of SQL_CALC_FOUND_ROWS with found_rows() provides a simple way to achieve this:

```
SELECT SQL_CALC_FOUND_ROWS * FROM user WHERE user.first_name LIKE 'Tim%' LIMIT 30;
SELECT found_rows();
```

The second select returns the total number of rows that match the query without the LIMIT. This is a very useful method to efficiently provide pagination (for example). Please note that this cannot be made with the knex.raw method as this adds a comma after SQL_CALC_FOUND_ROWS which is invalid SQL as @mnpenner mentioned. Afaik, this would be good to add as the knex API should not limit the way you interact with SQL.

**Comment by elhigu** [comment]
Those queries can be done like this:

```js
knex = require('knex')({client: 'mysql' })
knex('user').select(knex.raw('SQL_CALC_FOUND_ROWS *')).where('user.first_name', 'like', 'Tim%').limit('30').toSQL();
/*
{ method: 'select',
  options: {},
  timeout: false,
  bindings: [ 'Tim%', 30 ],
  sql: 'select SQL_CALC_FOUND_ROWS * from `user` where `user`.`first_name` like ? limit ?' }
*/

knex.select(knex.raw('found_rows()')).toSQL()
/*
{ method: 'select',
  options: {},
  timeout: false,
  bindings: [],
  sql: 'select found_rows()' }
*/
```

What is correct syntax for query which doesn't do `SQL_CALC_FOUND_ROWS *`, but have list of columns like @mnpenner is trying to do. I can give an example how to do that too.

**Comment by joaomvfsantos** [comment]
@elhigu That would be the most useful case scenario yes, If you can give an example on that list of columns would be great. Will try this out. Thanks.

**Comment by mnpenner** [comment]
@elhigu The correct MySQL syntax is simply to drop the `,` after `SQL_CALC_FOUND_ROWS`. Specifically,

```mysql
select SQL_CALC_FOUND_ROWS `emr_client_id` as `id`, `ecl_first_name` as `firstName`, `ecl_last_name` as `lastName` from `emr_client` limit 1000 
```

An example of how to write that with knex would be much appreciated.

**Comment by elhigu** [comment]
@mpenner this should work

```js
knex('emr_client').select(
  knex.raw('SQL_CALC_FOUND_ROWS ??', [[
    'emr_client_id as id', 'ecl_first_name as firstName', 'ecl_last_name as lastName'
  ]])
).limit(1000).toSQL();
/*
{ method: 'select',
  options: {},
  bindings: [ 1000 ],
  sql: 'select SQL_CALC_FOUND_ROWS `emr_client_id` as `id`, `ecl_first_name` as `firstName`, `ecl_last_name` as `lastName` from `emr_client` limit ?' }
*/
```

Note that it is important to have double `[[ ]]` or knex doesn't understand that `??` should be replaced with an array of identifiers.

Please leave comment if there are still problems with this and I'll reopen the issue.
