### ISSUE TITLE
createTable() generates "drop table"

### ISSUE THREAD

**Issue by mfrost66** [tgriesser/knex#787]
Calling createTable() after a dropTable() results in two "drop table" statements being executed

```
return schema.dropTable('users')
   .then(function(){ return schema.createTable('users',function(t){
       t.string('login').primary();
       t.json('data',true)})
   })
```

**Comment by tgriesser** [comment]
So `schema` is a ES5 getter on `knex`, so calling it like that will break things. I'll add a way to warn against this occurrence.

Changing code to:

```js
return knex.schema.dropTable('users')
   .then(function(){ return knex.schema.createTable('users',function(t){
       t.string('login').primary();
       t.json('data',true)})
   })
```

will work.

**Comment by joepie91** [comment]
Hmm, this feels like an API smell. It seems like bad practice to me to have a non-idempotent getter - why not just make it a method at that point, so that it is more obvious that it (apparently) instantiates an object?

**Comment by wubzz** [comment]
This is now part of the docs, closing.

An API-redesign should be given its own detailed issue if such a change is still requested.
