### ISSUE TITLE
Knex migration not rolling back when aborpt or failed

### ISSUE THREAD

**Issue by olalonde** [tgriesser/knex#790]
My knex migration isn't rollback if it fails in the middle. For example if it creates a table `table1` and fails to create table `table2`, the database will have `table1` but not `table2` after being run. Do I have to explicitly do this in my migration or is it a bug?

**Comment by bendrucker** [comment]
Should be resolved by #788

**Comment by tgriesser** [comment]
Yeah this will be fixed in the upcoming 0.8
