### ISSUE TITLE
Using prepared statement with `WHERE somecol IN (?)` and array argument?

### ISSUE THREAD

**Issue by olalonde** [tgriesser/knex#791]
Is it possible to use prepared statement to do something like:

``` javascript
knex.raw('SELECT id FROM users WHERE id IN (?)', [ [1, 2, 3] ])
```

**Comment by tgriesser** [comment]
No, though I'm looking into expanding the capabilities of argument interpolation. I'll consider this case.

**Comment by olalonde** [comment]
Ok thanks.

**Comment by tgriesser** [comment]
just curious, why not just do `select('id').from('users').whereIn('id', val)`?

**Comment by olalonde** [comment]
I think my statement was a bit more complex than that and didn't have time to figure out the right knex methods Thanks for pointing this out though.

**Comment by tgriesser** [comment]
Actually - so prepared statements don't convert arrays as you'd want there. Instead what I'm going to look at is creating a standard convention of interpolating values (potentially anything with a toSQL fn), so you could have some helper function on knex wrap the array so it knows to expand into the `(?, ?, ?)` format.

**Comment by smithb1994** [comment]
@tgrlesser Any progress on this? I've run into this problem too.
Is there a temporary work around in the mean time?

**Comment by smithb1994** [comment]
@tgriesser 
This feature is much needed for postgres functions array_append(), array_replace(), ect.
Is there a work around for passing arrays into knex.raw() ?

**Comment by smithb1994** [comment]
Nevermind, you can already do what I wanted... I was just stupid enough to be executing my queries by doing .toString first.... I'm an idiot.

**Comment by rhyek** [comment]
Any news on this? Or is this already possible?

**Comment by elhigu** [comment]
Ops, wrong button. Anyways this could be probably considered duplicate since there are other issues about how array values are interpreted.

**Comment by edorivai** [comment]
Usecase (Postgres):

```js
const countries = ['NL', 'BE', 'DE'];
knex('destination').select(
    knex.raw(`(CASE
        WHEN "countryCode" IN :countries THEN 'EU'
        ELSE 'WORLD'
    END) AS "region"`, { countries })
).toString();
```

Result:
```sql
select (CASE
        WHEN "countryCode" IN '{"NL","BE","DE"}' THEN 'EU'
        ELSE 'WORLD'
END) AS "region" from "destination"
```

Expected:
```sql
select (CASE
        WHEN "countryCode" IN ('NL','BE','DE') THEN 'EU'
        ELSE 'WORLD'
END) AS "region" from "destination"
```

Current workaround:

```js
const countries = ['NL', 'BE', 'DE'];
knex('destination').select(
    knex.raw(`(CASE
        WHEN "countryCode" IN (${countries.map(code => `'${code}'`).join(', ')}) THEN 'EU'
        ELSE 'WORLD'
    END) AS "region"`)
).toString();
```

**Comment by elhigu** [comment]
@edorivai postgres has at least 4 different syntaxes for arrays, so it cannot possibly guess which one you mean.

I think this issue should have proper feature request filed. One way to support this would be to have some wrappers for arrays, which tells to knex how that array should be rendered in query. 

Something like:

```
knex.raw("where in ?", [asList([1,2,3,4])]) 
```

would output: 

```
where in (1,2,3,4)
```

Maybe in your case ANY could work like mentioned here: https://github.com/tgriesser/knex/issues/1537
