### ISSUE TITLE
Cannot find module '../knex' @ knex for browser

### ISSUE THREAD

**Issue by 3h3c** [tgriesser/knex#792]
hi,

please fix this issue.

On line 7565 change from

module.exports = Transaction;

},{"../knex":undefined,"./interface":73,"./promise":75,"events":267,"inherits":275}],90:[function(require,module,exports){
.
.
.

to

module.exports = Transaction;

},{"../knex":1,"./interface":73,"./promise":75,"events":267,"inherits":275}],90:[function(require,module,exports){
.
.
.

thx.

**Comment by tgriesser** [comment]
Should be fixed by 0.8
