### ISSUE TITLE
ON DUPLICATE KEY UPDATE ? 

### ISSUE THREAD

**Issue by ashrafk786** [tgriesser/knex#793]
Hello,

I'm using "knex": "^0.7.3", lab, and promises, mysql data store. My schema looks like this: 

``` javascript
user: {
    id: {type: 'increments', nullable: false, primary: true},
    username: {type: 'string', maxlength: 30, nullable: false, unique: true},
    email: {type: 'string', maxlength: 60, nullable: true, unique: true},
    password: {type: 'text', maxlength: 60, nullable: true},
},
profile: {
      id: {type: 'increments', nullable: false, primary: true},
      user_id: {type: 'integer', nullable: true, unsigned: true, references: 'user.id', unique: true},
      bodytype_id: {type: 'integer', nullable: true, unsigned: true, references: 'bodytype.id'},
      },
```

The issue that I'm facing is that I've written a test that calls out to my api's to do a PUT which updates the user's profile. If the profile does not exists, it creates one. Unfortunately, I keep seeing this in the logs: 

> message: 'Duplicate entry \'77\' for key \'profile_user_id_unique\'' }

Can I use ON DUPLICATE KEY UPDATE in knex to resolve the above matter? Thank you.

**Comment by scmorse** [comment]
I was also recently seeking this feature. Will knex support this?

**Comment by toreader** [comment]
+1

I'd recommend the same chaining as for unionAll.

**Comment by herlon214** [comment]
+1

**Comment by avimar** [comment]
duplicate #701

**Comment by lambrojos** [comment]
+1

**Comment by mgmorcos** [comment]
+1

**Comment by elhigu** [comment]
Follow this up in here https://github.com/tgriesser/knex/pull/2197

**Comment by felixmosh** [comment]
I've wrote tiny lib, that adds onDuplicateUpdate function to Knex QueryBuilder.
https://github.com/felixmosh/knex-on-duplicate-update
