### ISSUE TITLE
Oracle Fatal Error Assertion `handle->InternalFieldCount() > 0' failed.

### ISSUE THREAD

**Issue by khalilTN** [tgriesser/knex#796]
I'm using Knex with oracle, I'm trying : 
````
client('userTable').insert(data).returning('id');
````
The generated log is :
````
{ __cid: '__cid1',
  method: 'insert',
  options: undefined,
  bindings: 
   [ <Buffer 74 65 73 74 20 74 68 65 20 74 68 69 6e 67 73>,
     Mon Apr 27 2015 11:50:06 GMT+0200 (CEST),
     'blueberry',
     0,
     Mon Apr 27 2015 11:50:06 GMT+0200 (CEST),
     {} ],
  sql: 'insert into "userTable" ("avatar", "createdAt", "favoriteFruit", "status", "updatedAt") values (:1, :2, :3, :4, :5) returning ROWID into :6',
  returningSql: 'select "id" from "userTable" where ROWID = :1',
  outParams: [ { columnName: 'id' } ],
  returning: [ 'id' ] }
````
An undebuggable fatal error occurs :
````
node: /usr/include/node/node_object_wrap.h:61: static T* node::ObjectWrap::Unwrap(v8::Handle<v8::Object>) [with T = OutParam]: Assertion `handle->InternalFieldCount() > 0' failed.
````
What could be the cause ?
Thank you !

**Comment by tgriesser** [comment]
@khalilTN can you try it with the [`strong-oracle`](https://github.com/strongloop/strong-oracle) driver (which should have the same api) and see if you have the same issue?

**Comment by vschoettke** [comment]
I think it's related to the Buffer parameter if other queries work fine.

**Comment by tgriesser** [comment]
Ah interesting, I guess we should cast that to string

**Comment by khalilTN** [comment]
@vschoettke other queries contains buffers too, i think it's not related to the buffer.

**Comment by khalilTN** [comment]
@tgriesser  Oracle blob hexadecimal strings.

**Comment by tgriesser** [comment]
Should be handled in 0.8 - let me know if you're still seeing issues
