### ISSUE TITLE
API for creating partially applied query chain

### ISSUE THREAD

**Issue by tgriesser** [tgriesser/knex#798]
Referenced in #797 - creating a more powerful version of `.clone`, creating a new knex constructor with partially applied values from a knex chain:

Potential API:

``` js
knex = knex.select('*').from('account').asPartial()
```

**Comment by StreetStrider** [comment]
This would be awesome. It's the part of my workflow. In my models I create basic knex factory, which pick table name and common conditions.
```javascript
function selectPublic ()
{
  return db('table_name')
  .select()
  .where(/* ... common condtions */)
  .clone();
}
/* then */
function pickSome (...)
{
  return selectPublis()
  .where(...);
}
```
This helps keep things like table name and conditions DRY and evade knex mutability issues.

**Comment by tgriesser** [comment]
What would you imagine as the best API for something like this:

```js
var selectPublis = db('table_name')
  .select()
  .where(/* ... common condtions */)
  .toFactory();
```

Some naming ideas: `.partial()`, `.toPartial()`, `.asFactory()`, `.toFactory()`, `.makeBuilder()`

I guess it'd be making something along the lines of a new builder factory, so `.toFactory()` seems like a potentially decent name for it.

/cc @tkellen @myndzi @bendrucker

**Comment by bendrucker** [comment]
I assume the existing naming convention around new methods (e.g. `fromJS`) was borrowed from immutable and I think it makes sense to maintain to/from for this as well (`toPartial`).

**Comment by tgriesser** [comment]
Yeah I haven't been entirely sold on `fromJS` yet - any other ideas there.

**Comment by bendrucker** [comment]
I think it's fine. Nothing better comes to mind and there's the advantage of mimicking a package with 6k+ stars that's growing in popularity.

**Comment by myndzi** [comment]
As mentioned on IRC, I am having a hard time coming up with solid use cases for this, but I like it anyway. It might enable some things under the hood if nothing else, and immutability can be its own reward.

I think issuing a warning about misuse as in https://github.com/tgriesser/knex/issues/797 should be sufficient for the short term, and the code examples I've considered so far can be rearranged easily enough.

StreetStrider: In your example, you have no need to clone the query since a new one is built every time you call your function. IMO at least, I would rather do it that way (as a function) than assigning a partial query object that you would subsequently be calling like `selectPublic.where(...)` since the semantics of functions help clarify what's going on (new partial query being returned).

**Comment by StreetStrider** [comment]
imo, `partial` is a good start, since it describes the nature of this feature, and it is already has analogue in FP («partial» for partially applied functions). `to` particle is not required here, as it is most often used in context of *types* (`toString`, `toJSON`, `toBuffer`), so partial is not a type, but a state of knex builder.

**Comment by StreetStrider** [comment]
@myndzi, yes, you're right. Usually, I save `var _table = db('table_name');` then `selectPublic` uses it, so, in this case, `.clone` is required. I've just mistaken in example (tryed to simplify it). Thanks for this note.

**Comment by myndzi** [comment]
It still leaves me wondering why you would bother with something like `var _table = db('table_name')` at all

**Comment by StreetStrider** [comment]
@myndzi, to prevent duplicating of table name, basic conditions etc. To keep things dry. To create metamodels.

**Comment by myndzi** [comment]
Why wouldn't you simply assign the table name as the variable, instead of the knex instance?

**Comment by StreetStrider** [comment]
@myndzi, because knex instance is composable. The practical goal here is to define model from common functions to specialized. At the top we define basic entity: table, all other are derived from it, by adding `column`, `where`, `limit` etc.
```js
function table ()
{
  return db('table_name'); // this is the root for all: selects, inserts, updates…
}
function add (/* … */)
{
  /* here check for domain-specific conditions */
  /* transform & prepare input data for inserting */
  return table() /* use `table` */
  .insert(data);
}
function selectPublic ()
{
  return table() /* use `table` */
  .select('title', 'content', 'author', 'published' /* public fields we expose in API */)
  .where('is_moderated', true /* basic checks for public API */)
}
function byAuthor (author) /* more specialized stuff built upon `selectPublic` */
{
  return selectPublic()
  .where('author', author);
}
// …
```
These functions-factories used for achieving knex-builder immutability, required to build such hierarchical model. The other way is to use `.clone`. `partial` may become even better way.

**Comment by tgriesser** [comment]
Yeah, I've actually always wanted to make the knex builder immutable internally but it's just impractical overhead for most cases. A partial API would actually make it feasible (and more powerful than clone).

**Comment by StreetStrider** [comment]
@tgriesser, yes, I'm thinking the very same way. Immutability is too expensive to turn it on for all by default. Things like `clone`, `partial` is a good way to turn immatability exactly where developer will really need it.

**Comment by myndzi** [comment]
By making a slight change, that all works as-is without need for an entire new feature/approach on knex's side:

```javascript
function table ()
{
  return 'table_name'; // this is the root for all: selects, inserts, updates…
}
function add (/* … */)
{
  /* here check for domain-specific conditions */
  /* transform & prepare input data for inserting */
  return db(table()) /* use `table` */
  .insert(data);
}
function selectPublic ()
{
  return db(table()) /* use `table` */
  .select('title', 'content', 'author', 'published' /* public fields we expose in API */)
  .where('is_moderated', true /* basic checks for public API */)
}
function byAuthor (author) /* more specialized stuff built upon `selectPublic` */
{
  return selectPublic()
  .where('author', author);
}
// …
```

Please note, I'm not trying to attack you, just trying to dig in and find a real use case that can't be solved cleanly otherwise.

**Comment by tgriesser** [comment]
As mentioned in #803, this could actually be very useful for applying default options on every query.

**Comment by myndzi** [comment]
Yeah, like I was saying on IRC, I think it (partials) just opens the way to a cleaner API. Didn't know about the query options thing in node-mysql (#803), but it's certainly another thing this would make nice :)

**Comment by tkellen** [comment]
Huge +1 to this. [Sequel](http://sequel.jeremyevans.com) has something similar called "datasets" and I use it everywhere.

**Comment by KeKs0r** [comment]
I just started using knex, so I might not yet fully comprehend all capabilities. I started using it to construct a quite complicated query dynamically which I could not with string concatenation. I did the exact same thing with a string that I could easily concatenate. I found quite the performance loss on the simple query, which I guess stems from building the complex query with knex with several callbacks etc. 

I think somehow complex prepared statements could make up for this performance loss.

If someone is interested in some load tests +  how I build my queries, I would be more than happy to supply them.

**Comment by moll** [comment]
What exactly is slow with a fully immutable query object? Aren't we talking about fairly tiny objects with a property or two and an array or two? Surely that can't be noticeable compared to the expense of doing an actual query.

**Comment by elhigu** [comment]
@KeKs0r if you have some hard data / example benchmark code please open new issue with them... the performance discussion is a bit off-topic here.

**Comment by elhigu** [comment]
Closing old issue. New feature request with proper API proposal should be added if this is still wanted. 

Though I'm having a hard time to see how this would prevent the misuse of forgetting to use `.clone()`,  also this kind of factory functions are trivial to write and are easier to understand (for people new to knex) with plain JS and not having to read through docs trying to figure out what is the difference between clone and toFactory.
