### ISSUE TITLE
Knex node-mysql timeout support

### ISSUE THREAD

**Issue by danielzurawski** [tgriesser/knex#803]
Hi,

I've noticed that node-mysql supports a 'timeout' property in the object you pass to .query and I was wondering if there is a way to pass that in through knex? If not, would that be a welcomed contribution or does that require a lot of re-wiring in generic-pool-redux etc.?

https://github.com/felixge/node-mysql/#timeouts

Thanks.

**Comment by tgriesser** [comment]
I think you can pass it by chaining `.options({timeout: 60000})` somewhere in the query. Don't have a way yet to enable it globally, though this might be a very good case of something #798 would be good for (/cc @myndzi)

**Comment by tgriesser** [comment]
Closing in favor of discussion in #798

**Comment by diversario** [comment]
@tgriesser: is there a way to tap somewhere in knex to call `.options()` on every query before it's executed?
