### ISSUE TITLE
Custom seeds directory

### ISSUE THREAD

**Issue by nathasm** [tgriesser/knex#804]
I may be off base here, so maybe someone can help clear this up:

Docs state that the knexfile.js can define a custom seeds directory:

<pre>
  development: {
    client: 'mysql',
    connection: {
    },
    migrations: {
      tableName: 'knex_migrations',
      directory: '../db/migrations'
    },
    seeds: {
      directory: '../db/seeds'
    }
}
</pre>

And then try to seed my project, it looks like it's picking up the default directory.
<pre>
knex --knexfile config/knexfile.js seed:run
Error: ENOENT, readdir 'MYPATH/config/seeds'
</pre>

In lib/seed/index.js L17 it looks like it's trying to pull the value from knex.client.seedConfig.

If I change that reference to knex.client.config.seeds everything seems to work

Am I missing something?

**Comment by tgriesser** [comment]
Nope, sounds like a regression - I'll get it fixed/tested tomorrow am
