### ISSUE TITLE
Migration directory gets overwritten in 0.8.X

### ISSUE THREAD

**Issue by nathasm** [tgriesser/knex#812]
I've spent some time but haven't had much luck tracking down this bug, maybe if I punt it over the wall someone might have better luck.

The problem is that my teardown/after works if there is a failed test case, but if all the tests pass, then the teardown fails with the error below.

All of this worked in 0.7.X but fails in 0.8.X.

<pre>
# This 
var config = require('../../server/config/index')
var knex = require('knex')(config.db);
before(function (done) {
  knex.migrate.latest().then(function() {
    knex.seed.run().then(function() {
      done();
    });
  });
});

after(function(done) {
  knex.migrate.rollback().then(function() {
    done();
  });
});
</pre>

In the cases where all the tests, pass, the rollback fails because the knex.client.config.migrations.directory is over-written _somewhere_

<pre>
Unhandled rejection Error: ENOENT, readdir '/Users/nsmith/project/server/config/Users/nsmith/project/server/db/migrations'
</pre>

Note, that the configuration file resides in 'server/config' but the migrations reside in 'server/db/migrations'. So it seems like some path resolution didn't happen a join was issued mistakenly.

**Comment by myndzi** [comment]
Do you have any other 'before' or 'after' handlers, in other files, etc.?

Note that you can return a promise in Mocha, if that's what this is, which makes this sort of thing much more pleasant to write.

**Comment by kibertoad** [comment]
@elhigu I suggest closing this due to age.
