### ISSUE TITLE
Knex won't create SQLite files in nonexistent directories at 0.8.x

### ISSUE THREAD

**Issue by blah238** [tgriesser/knex#813]
Not sure if this was documented but figured I'd post about it.

My connection object is:
```js
{
    client: 'sqlite3',
    connection: {
      filename: '.tmp/localDiskDb.sqlite'
    }
}
```

In 0.7.8 it didn't matter if the `.tmp` directory existed or not, but in 0.8.x it must exist or else the following error occurs:

`Knex:Error Pool2 - Error: Error allocating resources: SQLITE_CANTOPEN: unable to open database file`

If I do a `mkdir .tmp` it is then able to create the file.

**Comment by tgriesser** [comment]
I'm not seeing this behavior in 0.7.8 - it just deferred the error until you first queried

**Comment by tgriesser** [comment]
Not that I'd be opposed to mkdirp'ing this one, I just want to confirm it's not a regression

**Comment by blah238** [comment]
You are correct, I must just have been misremembering the old behavior. mkdirp would be nice!
