### ISSUE TITLE
knex on npm throws error in migrate/index.js ?

### ISSUE THREAD

**Issue by anyong** [tgriesser/knex#816]
https://bpaste.net/show/e2becf43585e

Seems like there is no such thing as `this.conf`, so I'm not sure why it's being referenced. The same file in this repo does not have any `this.conf`.

Edit: Really strange because my project's local node_modules has (had) `this.conf` (on lines 92 & 140), but the globally installed version does not (it's `this.config`). But it seems that `npm uninstall` and reinstalling fixed the issue, but how did it happen in the first place, I wonder?

**Comment by kibertoad** [comment]
Linked snipped no longer exists and issue is really old, if it is still relevant, hopefully someone would raise it again.
