### ISSUE TITLE
Pluck doesn't work with count

### ISSUE THREAD

**Issue by wreckah** [tgriesser/knex#817]
At the moment knex code:
```js
knex('table').first().count().pluck('count');
```
produces SQL:
```sql
select count(*), "count" from "table"
```
And
```js
knex('table').first().count('* AS count').pluck('count');
```
doesn't help:
```sql
select count(*) as "count", "count" from "table"
```

It would be great to be able to use pluck with count. Wouldn't it?

**Comment by koskimas** [comment]
`pluck` selects a property from an array of objects. You call the `first` method here which selects the first object and converts the array into an object. Pluck doesn't work with objects. This is how `pluck` works in lodash. If you use lodash you can always do this:

```
knex('table').count('* AS count').pluck('count').then(_.first)
```

Maybe this works?

```
knex('table').count('* AS count').pluck('count').first()
```

**Comment by wreckah** [comment]
Unfortunately doesn't.

`First` works perfectly, it returns the first row as object:
```js
knex('table').count('* AS count').first().then((cnt) -> console.log(cnt))
```
outputs:
```js
{ count: '1' }
```

The problem is in the `pluck` method. It adds an additional `"count"` to selected fields and causes  SQL error:
```
knex('table').count('* AS count').pluck('count').first().then((cnt) -> console.log(cnt))

Unhandled rejection error: select count(*) as "count", "count" from "admins" limit $1 - column "count" does not exist
  at [object Object].Connection.parseE (project/node_modules/pg/lib/connection.js:534:11)
  at [object Object].Connection.parseMessage (project/node_modules/pg/lib/connection.js:361:17)
  at Socket.<anonymous> (project/node_modules/pg/lib/connection.js:105:22)
  at Socket.emit (events.js:107:17)
  at readableAddChunk (_stream_readable.js:163:16)
  at Socket.Readable.push (_stream_readable.js:126:10)
  at TCP.onread (net.js:538:20)
```

**Comment by StreetStrider** [comment]
@wreckah, looks like `pluck` does not work properly with aliased fields. Let's just wait for maintainers, I hope, Tim will help with this issue.

@koskimas, the things what you say is technically correct but don't help topicstarter.

**Comment by splash21** [comment]
it works with an aliased field using ;
.pluck(db.raw('total'))

**Comment by wreckah** [comment]
Thanks @splash21! It's enough for me.

**Comment by ivan-kleshnin** [comment]
5 years of this bug soon :)

**Comment by koskimas** [comment]
keen observation

**Comment by elhigu** [comment]
We could always remove the .pluck method to really fix it once and for all 😌

**Comment by kemp12322** [comment]
umm anyone has an alternate solution for this?
