### ISSUE TITLE
Seed slowdown with Express

### ISSUE THREAD

**Issue by tbranyen** [tgriesser/knex#819]
I've been able to consistently reproduce behavior that is baffling me.  If I run:

``` javascript
knex.seed.run({ directory: local('./api/seeds') })
```

While running an Express app, I get huge (seconds) of latency for every single request, even static files.  I read through the Knex code for seeds and nothing there seems to jump out at me as a reason.

I figured I'd open this issue in case others have hit similar behavior or if @tgriesser has any leads on how to remedy this.

**Comment by tgriesser** [comment]
What is `local`?

**Comment by tbranyen** [comment]
Oh sorry, `local` is just: `path.join.bind(path, __dirname)`.  I did more debugging, and turns out it's not seed related, but `withRelated` related and Passport.  I had Passport running on all assets, but shouldn't have as it's causing a huge slowdown.

This was my mistake, I was convinced it was the seeds action though.  Glad it's not!

**Comment by tbranyen** [comment]
My fix ended up being very trivial.  I rearranged my static file handling (development obviously) to be higher up in the middleware parsing, skipping all session deserialization.  Since I'm working locally with sqlite3, I bet it was just too much pressure on the db and static assets will be handled by nginx in production anyways.

**Comment by StreetStrider** [comment]
@tbranyen, speaking of `local`. I have package called [rootpath](https://github.com/StreetStrider/rootpath) for the same purpose(s). This might be interesting for you.
