### ISSUE TITLE
pool max

### ISSUE THREAD

**Issue by knownasilya** [tgriesser/knex#822]
> RangeError: Pool2: max cannot be 0.

When I set `pool: { max: 0 }` because I'm managing my connections myself. Previously this was allowed, but it looks like you're using a new pooling lib..

**Comment by tgriesser** [comment]
Oops, see if 0.8.4 handles it for you

**Comment by knownasilya** [comment]
Almost, but no cigar '[Error: There is no pool defined on the current client]'
