### ISSUE TITLE
knex.raw does not treat $N params as binding anymore

### ISSUE THREAD

**Issue by neemah** [tgriesser/knex#824]
```
db.raw('select * from card where a = $1 and b = $2', [1, 2]);
```

knex 0.7.5 - works
knex 0.8.5 - do not

I would like to keep "$N" placeholders instead of "?" :)

**Comment by grahamjenson** [comment]
I need this as well, especially when I need to refer to the same binding multiple times e.g. `db.raw('select * from card where a = $1 and b = $1', [1]);`

**Comment by tgriesser** [comment]
@grahamjenson I don't know if I've documented it yet, but you can now instead do:

```js
db.raw('select * from card where a = :val and b = :val', {val: 1});
```

@neemah I'll take a look into adding support back in for this one

**Comment by myndzi** [comment]
I was surprised to learn, when writing some non-knex code, that lack of $N has to do with the postgres database driver. This means that even in a "raw" query, knex was (and apparently still is) doing some processing/manipulation of the contents; I'm not sure that seems like a great idea to me, but damned if I don't also want parameter interpolation of this kind in drivers that don't support it. Perhaps it would be good to give a different method name or some kind of option to allow for substitutions while still allowing "unfiltered" queries via `.raw`?

**Comment by JoshRagem** [comment]
I also need this.

**Comment by jure** [comment]
Just discovered the same thing. What's the reasoning? I would also expect `knew.raw` to work similarly to `node-postgres`'s `.query`.

**Comment by elhigu** [comment]
This is by design.

**Comment by elhigu** [comment]
@jure please check from documentation how it works to not have to expect it working in certain database specific manner.

**Comment by jure** [comment]
I’ve read a fair bit of issues and documentation, and I now see how this works, but it took a mental switch from: “`raw` just passes arguments to the underlying client library” to ”`raw` is an opinionated interface to the underlying client libray with additional safety checks”. Now things are clear, but my initial model was more like a fictional `rawUnsafe`. :)
