### ISSUE TITLE
Bulk inserts have an awkward behaviour

### ISSUE THREAD

**Issue by Dynom** [tgriesser/knex#826]
Hi,

For testing purposes I need to provision databases with sets of data. The sets are generally a bit larger, starting at around 10.000 items. However with inserts above 1.000 items I get weird results. Either Knex is losing connection to the database or other V8 weirdness. So I've wrote something that inserts in chunks.

However the following implementation has weird results:

```js
    let amount = 10000;
    let provisioning = knex.table("items").truncate();
    let data = [];
    for (let i = 0; i < amount; i++) {

      data.push({...}); // Some data is pushed here

      // We chunk at a maximum of 500 items, if we add more, things go boom.
      if (data.length >= 500 && i < (amount - 1)) {
        (function (chunk) {
          provisioning.then(function() {
            return provisioning.insert(chunk);
          });
        }(data));

        // Resetting data so we can generate the next chunk
        data = [];
      }
    }

    // Insert the (remaining) data
    return provisioning.then(function() {
      return provisioning.insert(data);
    });
```

Result in PostgreSQL:
```
 count
-------
 17000
(1 row)
```

When I construct the Knex client with a much larger (than default=10) pool-size, things work as expected: `knex({pool:{max:1000}});`

I'm sure I must be doing something wrong, but I'm not sure what.

I've had this problem with 0.7.5 and also with 0.8.5 (now using Pool2, according to your documentation).

**Comment by Dynom** [comment]
Now that I'm tinkering with it more, I'm not sure if this actually "solves" the problem. There seems to be a timing issue somewhere. When the server I run this on is "busy" I still get strange results, having a large pool size only reduces the severity of the symptoms. 

Something is afoot.

**Comment by Dynom** [comment]
I believe the problem to be with my inexperience with Promises in general. I've come up with something that works, based on the previous bulkInsert work by @tgriesser here: https://github.com/tgriesser/knex/blob/batch-insert/lib/util/batch-insert.js

```js
import knex = require("knex");
(function (items) {
  let db = knex.table("items");

  // This is the basic operation to add a promise to the chain.
  chain = chain.then(function() { return db.truncate(); });

  let foo = [];
  items.forEach(function(item) {

    // Add db.insert() promises to our promise chain
    // This can easily be changed to include chunks and/or streams
    chain = chain.then(function () {
        return db.insert(item);
    });
  });

  // Start resolving the promises once our db.then() is invoked.
  return db.then(function(){
    chain.then();
  });

}(items));
```

An implementation that works in chunks of say ~500 items:
```js
let amount = 10000;
let db = knex.table("items");

// Start the chain    
let chain = Promise.then({});
chain = chain.then(function() { return db.truncate(); });

let data = [];
for (let i = 0; i < amount; i++) {

  data.push({...}); // Some data is pushed here

  // Make sure we insert when we reach our sanity limit of 500, or if we're in our last iteration
  if (data.length >= 500 && i === (amount - 1)) {

    // Here we wrap our data in a closure, to protect against scoping and reference problems
    chain = (function(records) {
      return chain.then(
        function () { return db.insert(records); }
      );
    }(data));

    // Resetting data so we can generate the next chunk
    data = [];
  }
}

// Return our chain and start resolving.
return db.then(function() {
  return chain.then();
});
```

This might also work directly with Knex, by for example doing:
```js
db = db.then(function() { /*...*/});
```

But I kept it like this because I think this reads a bit more clear.

**Comment by myndzi** [comment]
I think this is the same mistake as here: https://github.com/tgriesser/knex/issues/797

Namely, you've instantiated a knex query and are reusing it, but you shouldn't be doing that. I think what you actually want to do is something like this:

    var data = /* your array of things to insert */;
    return (function next(chunk) {
        if (chunk.length === 0) { return; }
        return knex(table).insert(chunk).then(function () {
            return next(data.splice(0, 500));
        });
    })(data.splice(0, 500));

**Comment by Dynom** [comment]
Hi @myndzi,

Thanks for the feedback!

**Comment by wubzz** [comment]
Marking this as solved based on comments above. In addition, Knex 0.10 now has a built-in utility for this called `.batchInsert` to handle these scenarios. [Reference](http://knexjs.org/#Utility-BatchInsert)

**Comment by shakvaal** [comment]
As a newbie I'm confused: so `knex(table).insert(/*a really big array*/)` would always fail?
What if I don't know exactly how much rows I'll need to insert?
Do I have to always use batchInsert then?

**Comment by Dynom** [comment]
You could always wonder if that would be a good idea, depending on how large your array is. Following some sort of chunked/paginated insert strategy for larger data-sets is probably a good idea.

The `batchInsert()` is a nice addition for this, although I'd use it sooner then recommended by Knex (starting from a couple of hundred inserts instead of >= 1000).

**Comment by elhigu** [comment]
@shakvaal If I recall correctly the limit comes from a fact that database engines has limited maximum SQL statement size. So if your insert statement is 10MB probably at least sqlite will fail with that.
