### ISSUE TITLE
apostrophes not properly escaped with pg

### ISSUE THREAD

**Issue by bblack** [tgriesser/knex#828]
on 0.8.5. apostrophes are escaped with backslashes, rather than the proper double-apostrophe. probably related to https://github.com/tgriesser/knex/issues/658 .

```
knex = require('knex')({client: 'pg'})
q = knex('Beer').where('name', 'ilike', "Mama's Little Yella Pils")
q2 = knex('Beer').where('name', "Mama's Little Yella Pils")
console.log(q.toString())
console.log(q2.toString())
```

> ```
select * from "Beer" where "name" ilike 'Mama\'s Little Yella Pils'
select * from "Beer" where "name" = 'Mama\'s Little Yella Pils'
```

**Comment by kayoub5** [comment]
for anyone have same issue, a temporary solution would be to do this
```sql
ALTER SYSTEM SET standard_conforming_strings=false
```
this will force PG to accept escaping with backslashes.
details:
http://www.postgresql.org/docs/current/static/config-setting.html
http://www.postgresql.org/docs/current/static/sql-altersystem.html
http://www.postgresql.org/docs/current/static/runtime-config-compatible.html#GUC-STANDARD-CONFORMING-STRINGS

**Comment by victorquinn** [comment]
Any status update here? We're having the same problem.

Seems like a rather big problem that a query in Postgres can't contain an apostrophe so I'm surprised there hasn't been much movement here!

**Comment by bblack** [comment]
I've just rebased #886 on master. I'd love to get some comments on it so we can get this fixed.

**Comment by victorquinn** [comment]
I have a fork but would love ring in from @tgriesser -- I wasn't sure on the ideal approach here as the \' is in the sanitizer which has no knowledge of the type of db (Postgres v. other) so I felt like this belonged as a find/replace in the dialect (which would find/replace \' with '' for Postgres queries). Any thoughts?

Cheers,
Victor

**Comment by bblack** [comment]
The escaping takes place in a function exposed by the `src/query/string` module, which is referred to in code as `SqlString`. The approach I took in #886 was to give each dialect its own `SqlString` property, which points to either a dialect-specific module (which I did for postgres), or the existing generic one (all other dialects).

**Comment by victorquinn** [comment]
Nice, that makes sense but I didn't want to make that call because it's not my library and that adds additional complexity.

**Comment by parkan** [comment]
+1 for this, please. This is a very serious bug, especially in a managed environment where the user can't `ALTER SYSTEM`

**Comment by tgriesser** [comment]
Closing in favor of #1661
