### ISSUE TITLE
Change `.first` behaviour

### ISSUE THREAD

**Issue by nkt** [tgriesser/knex#830]
For now this wouldn't work:
```js
let id = knex('users').insert(user, 'id').first();
```
So I have to right something like:
```js
let id = knex('users').insert(user, 'id').spread((id) => id);
```
Would you change this behaviour?
Or maybe add `insertOne` method?

**Comment by tgriesser** [comment]
I'm actually considering altering the insert behavior so the shape of what is passed in matches the shape of the result ->

```js
knex('users').insert({firstName: 'User'}, 'id') -> returns an id
```

while:

```js
knex('users').insert([{firstName: 'User'}], 'id') -> returns an array of ids
```

This'd be a breaking change but it seems more consistent.

**Comment by nkt** [comment]
@tgriesser I think this would be inconsistent, and also breaks a lot of code. Return type shouldn't depends on incoming args.
I guess it would be better add `insertOne` method.
For example, mongodb deprecated same api in new driver, and introduces `insertOne` and `insertMany`, instead of `insert`. http://mongodb.github.io/node-mongodb-native/2.0/api/Collection.html#insert

**Comment by myndzi** [comment]
Note that Bluebird has a .get() method, so you could do .get(0) to get the first element of an array from a promised value. I'm not 100% certain that knex proxies this method though. At one point I remember submitting a patch to flesh out the proxied Promise methods, but ideally we'd iterate over the prototype or something to keep up to date with any changes to Bluebird's API.

**Comment by tuhoojabotti** [comment]
`.get(0)` works, I have used it.

**Comment by scarlac** [comment]
For future reference of anyone coming from Google, using ES6 array destructuring with `.returning()` is similar to `first()`. E.g.:
```
(async () => {
  const [firstRow] = await knex('mytable').insert({field: 1}).returning('*');
})()
```
