### ISSUE TITLE
Error object in catch() of promise

### ISSUE THREAD

**Issue by sourabhv** [tgriesser/knex#846]
Error in `catch` prints something like this

    { [<error message>]
        <key>: <value>,
        ...
    }

It took me 5 mins to finally figure out that its not a `JSON` but `Error` object with `toString` function changed (correct me if I'm wrong).

I suggest change that `toString` to print something which doesn't look like a deformed JSON

**Comment by myndzi** [comment]
This is actually standard; try the following code:

    var fn = function () { };
    fn.foo = 'foo';
    console.log(fn);

    var err = new Error('msg');
    err.bar = 'bar';
    console.log(err);

You can see that this is the way Node prints certain classes of objects when properties are assigned to them. Presumably all knex is doing is adding some additional properties to give context and information about the error. If you're looking for a stack trace, try logging `err.stack`

**Comment by myndzi** [comment]
Gonna close this, go ahead and post a comment if you think it should remain open...

**Comment by sourabhv** [comment]
Ah! It seems like it is, but I asked this on `#javascript@freenode` and no one was able to explain this behavior and until someone asked me to try `err.message` saying that Error objects sometimes behave this way. Maybe adding something about how to use the returned error somewhere in knex documentation would be helpful?

**Comment by myndzi** [comment]
I don't feel like this has anything to do with knex, to be honest. It behaves like any Error object, and there's nothing special in knex about it. It's just part of learning about javascript like anything else; Knex's docs aren't the place to explain function expressions, promises, or any number of other concepts; I feel like this falls in that category.

P.S. There's a #node.js on freenode, as well as #bookshelf (which includes knex discussion) :)
