### ISSUE TITLE
Print database schema 

### ISSUE THREAD

**Issue by cj3kim** [tgriesser/knex#847]
Hi! Love the work you do and it has made my life alot easier. 

Would love the feature of  being able to print out the entire schema of the database I'm working with into my config/db directory  - a la schema.txt . Do you have this feature in the works?

**Comment by wubzz** [comment]
I feel this is a bit out of scope for knex. It could however maybe be implemented somewhat easily with existing helper functions such as `columnInfo`. Maybe in a seperate package?

What do you think @elhigu ?

**Comment by elhigu** [comment]
Yeah, it will be pretty extensive and custom job for every dialect to be able to print schema and also there are so many different things not supported by knex in schema that it will be pretty impossible to show schemas of different DBs in a crossdb compatible form.

I would say that this is a job for external library, e.g. knex-db-manager could take in such feature.
