### ISSUE TITLE
Migrations: Can't "CREATE INDEX CONCURRENTLY" anymore

### ISSUE THREAD

**Issue by torarvid** [tgriesser/knex#848]
Hi. Not sure if this is a regression, but with knex 0.7.x I could have a migration where I added a raw command to do "CREATE INDEX CONCURRENTLY".

Now I get `CREATE INDEX CONCURRENTLY cannot run inside a transaction block`. Is this not possible at all anymore, or is there a trick to make it work? :)

**Comment by bendrucker** [comment]
For the moment you'll need to follow #834 and disable migration transactions entirely. At some point you'll be able to set this on a per-migration basis.

**Comment by rhys-vdw** [comment]
This has been address by #957.
