### ISSUE TITLE
Require lodash in knexfile.js fails

### ISSUE THREAD

**Issue by kimmobrunfeldt** [tgriesser/knex#850]
My knexfile.js is defined as:

```javascript
var _ = require('lodash');
var dbConfig = require('./src/database').config;

module.exports = _.merge(dbConfig, {
    migrations: {
        directory: __dirname + '/migrations',
        tableName: 'migrations'
    }
});
```

But running any migration command fails, e.g. `knex migrate:currentVersion --debug`:
```
/Users/kimmo/code/project/node_modules/lodash/index.js:692
  function runInContext(context) {
                       ^
illegal access
```

Is this lodash specific problem?

**Comment by kimmobrunfeldt** [comment]
Lodash author responded: "It doesn't look like directly a lodash problem though. Maybe the Knex folks can help." Do you know what's happening?

**Comment by tgriesser** [comment]
I have no idea what that would be caused by. What version of node are you running? Did you try a fresh npm install: 
```
rm -rf ./node_modules

npm install
```

**Comment by kimmobrunfeldt** [comment]
Hmm weird.. Now it worked normally. I'll close this.
