### ISSUE TITLE
SSL Query Parameter for Postgres

### ISSUE THREAD

**Issue by gregbty** [tgriesser/knex#852]
It seems like #516 has surfaced again. When I use a config object it seems to work fine with the `ssl` option, however this doesn't work with a connection string:

Works:

``` node
connection: {
  host: "host",
  port: "port",
  user: "user",
  password: "password",
  database: "database",
  ssl: true
 }
```

Does not work:

``` node
connection: "postgres://user:password@host:port/database?ssl=true"
```

**Comment by kimmobrunfeldt** [comment]
I'm experiencing this issue too:

```javascript
Using following config:
{ client: 'pg',
  connection: 'postgres://<gibberish>:<gibberish>@<hostgibberish>.eu-west-1.compute.amazonaws.com:5432/<gibberish>?charset=utf-8&ssl=true',
  pool: { min: 2, max: 10 },
  debug: false,
  migrations:
   { directory: '/tmp/build_7902ce01745a86676a8158ae8b05c065/migrations',
     tableName: 'migrations' } }
Using environment: production
Knex:Error Pool2 - error: no pg_hba.conf entry for host "50.147.231.214", user "<user>", database "<database>", SSL off
Error: Pool was destroyed
    at Pool._destroyPool (/tmp/build_7902ce01745a86676a8158ae8b05c065/node_modules/knex/node_modules/pool2/lib/pool.js:485:16)
    at Pool.<anonymous> (/tmp/build_7902ce01745a86676a8158ae8b05c065/node_modules/knex/node_modules/pool2/lib/pool.js:408:18)
    at Pool.<anonymous> (/tmp/build_7902ce01745a86676a8158ae8b05c065/node_modules/knex/node_modules/pool2/lib/pool.js:442:17)
    at tryCatcher (/tmp/build_7902ce01745a86676a8158ae8b05c065/node_modules/bluebird/js/main/util.js:24:31)
    at Promise.errorAdapter (/tmp/build_7902ce01745a86676a8158ae8b05c065/node_modules/bluebird/js/main/nodeify.js:35:34)
    at Promise._settlePromiseAt (/tmp/build_7902ce01745a86676a8158ae8b05c065/node_modules/bluebird/js/main/promise.js:528:21)
    at Promise._settlePromises (/tmp/build_7902ce01745a86676a8158ae8b05c065/node_modules/bluebird/js/main/promise.js:646:14)
    at Async._drainQueue (/tmp/build_7902ce01745a86676a8158ae8b05c065/node_modules/bluebird/js/main/async.js:177:16)
    at Async._drainQueues (/tmp/build_7902ce01745a86676a8158ae8b05c065/node_modules/bluebird/js/main/async.js:187:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/tmp/build_7902ce01745a86676a8158ae8b05c065/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:358:17)
```

**Comment by nickpoorman** [comment]
I'm having this issue as well on `v0.8.6`.

**Comment by idan** [comment]
I'm experiencing this on `v0.8.6` as well.

**Comment by nmccready** [comment]
I see this is fixed here on master. https://github.com/tgriesser/knex/blob/master/test/tape/parse-connection.js#L47-L56

When is 0.8.7 being cut?

**Comment by tjwebb** [comment]
@tgriesser please release a patch version for this. knex is currently unusable with Postgres over SSL.

**Comment by tgriesser** [comment]
Sorry abt that. Been MIA for quite a bit, I'll cut one tomorrow and start jumping into a lot of the backlogged tickets.

**Comment by tgriesser** [comment]
> This also happens to be a blocking issue for the Waterline PostgreSQL adapter, which we migrated over to use knex.js: https://github.com/waterlinejs/postgresql-adapter

Oh wow that's awesome!

**Comment by tjwebb** [comment]
> Been MIA for quite a bit, I'll cut one tomorrow and start jumping into a lot of the backlogged tickets.

@tgriesser sweet, thanks man.

**Comment by kimmobrunfeldt** [comment]
Workaround which worked for me: set environment variable `PGSSLMODE=require`. It forces postgres driver to use SSL and it resolved the issue at least in my case. Still waiting for the official patch though.

**Comment by nickpoorman** [comment]
Is anyone ever going to fix this???????

**Comment by rhys-vdw** [comment]
> Is anyone ever going to fix this???????

@nickpoorman You're welcome to provide a fix.

**Comment by codeclown** [comment]
I assume this is because Knex parses connection strings instead of passing them to the underlying library untouched, no?

[src/util-parse-connection.js](https://github.com/tgriesser/knex/blob/775d6c2af7106b38d53083bd5185c189f2fcd01f/src/util/parse-connection.js)
[src/index.js](https://github.com/tgriesser/knex/blob/775d6c2af7106b38d53083bd5185c189f2fcd01f/src/index.js)

Just bumped into this issue when using a valid connection string with charset option for mysql. I tested it and confirmed that the query parameters never arrived to `node-mysql`.

**Comment by zacharynevin** [comment]
I'm having this issue as well

**Comment by bennmapes** [comment]
I had the same issue, it appears the knex doesn't set the ssl default in `pg`.

I was able to fix this by adding 
`var pg = require('pg');
pg.defaults.ssl = true;`

before using knex.

**Comment by mindeavor** [comment]
The workaround by @bennmapes works great. The best place to put it is in your `knexfile.js`, since knex requires that file before migrating, etc.

**Comment by robinvdvleuten** [comment]
Is this still an issue? It seems to be working with a parameter string

**Comment by elhigu** [comment]
@robinvdvleuten does it work also with connection object by passing `{ ..., ssl: true }` ?

**Comment by whalelephant** [comment]
> @robinvdvleuten does it work also with connection object by passing `{ ..., ssl: true }` ?

yes but also required in the URL
 

 `{connection:url...?ssl=true, ssl=true}`

**Comment by elhigu** [comment]
@whalelephant you cannot give connection string and the object at the same time...

**Comment by whalelephant** [comment]
> @whalelephant you cannot give connection string and the object at the same time...

yes, sorry that was a typo, to be clear I meant
```
{
    connection:url...?ssl=true, 
    ssl:true
}

```

**Comment by elhigu** [comment]
> > @whalelephant you cannot give connection string and the object at the same time...
> 
> yes, sorry that was a typo, to be clear I meant

I didn't mean the typo.  Your { ssl : true } in your example is not in the connection object. You added it as a knex configuration object's top level attribute and it does not do anything in that level. 

In pseudo typescript knex configuration object looks like:

```
{
    client: DialectString,
    connection : ConnectionObject | ConnectionString, // this is passed directly to DB driver
    pool: PoolConfiguration,
    ... some additional custom knex configs, but no attribute called ssl ...
} 

```

I'll remove this and other messages about the confusion, to prevent them from polluting this issue. Hope this answer reaches your mail though.

**Comment by elhigu** [comment]
removed some a bit off-topic  discussion

**Comment by trubachev** [comment]
my workaround is to parse connections string to object and add/override `sss` option. NPM package to parse [pg-connection-string](https://www.npmjs.com/package/pg-connection-string)

```JavaScript
const dbConfig = {
  client: "postgresql",
  connection: {
    ssl: isProduction || isStaging,
    ...parse(CONFIG.DATABASE_URL),
  },
}
```

**Comment by Duchynko** [comment]
> @robinvdvleuten does it work also with connection object by passing `{ ..., ssl: true }` ?

This still doesn't work

**Comment by jayarjo** [comment]
What about passing in paths to custom certificates?

**Comment by akay0214** [comment]
> > @robinvdvleuten does it work also with connection object by passing `{ ..., ssl: true }` ?
> 
> This still doesn't work

works for me
