### ISSUE TITLE
Select/Column overriding old columns

### ISSUE THREAD

**Issue by tuhoojabotti** [tgriesser/knex#854]
From reading the docs this seems to be the documented behavior, but updating from 0.7.3 to 0.8.6 the behavior changed and broke my tests (thankfully).

Before calling qb.select(col) appended the column, now it replaces the old ones. I couldn't find a way to append a column without overriding the old ones.

Is there a way to append columns?

**Comment by tgriesser** [comment]
Would you be able to provide a simple test case to make sure I match the behavior you're expecting?

**Comment by tuhoojabotti** [comment]
Here's an example:

```javascript
return Model.query(function (qb) {
	// This used to append column, not overwrite.
	// Could be changed to qb.columns(..., { append: true }) or something.
	qb.select(knex.raw('COUNT(*) OVER() AS total_count'));
	if (limit) qb.limit(limit);
	if (offset) qb.offset(offset);
}).fetchAll(options)
	.tap(function (m) {
		if (m.length) res.header('X-Total-Count', m.at(0).get('total_count'));
		else res.header('X-Total-Count', 0); // You went too far.
		m.invoke('set', 'total_count', undefined);
	});
```

Also if you have a better idea for counting all results before limit, that would be nice too. ;)

**Comment by sjuvonen** [comment]
I cannot confirm this. The behaviour seems completely the opposite to me: calling select() will NOT overwrite anything; instead it will APPEND to the old list of columns up for select. According to the documentation, method column() should OVERWRITE the selected columns but it is actually only an alias to select(), hence it doesn't work. 

This is evident by looking at the code lib/query/builder.js#782, as the same method is set for column() as is used with select().

**Comment by tuhoojabotti** [comment]
I think the original problem is fixed now. It was just one broken version after the big internal refactorings. I will close this issue now. @sjuvonen if you think this issue should still be open for discussion, let me know and I'll re-open it. I think that being able to clear selected columns is another issue altogether.
