### ISSUE TITLE
.connection(dbConnection) works well?

### ISSUE THREAD

**Issue by hidetaka-f-matsumoto** [tgriesser/knex#858]
Hello.
I tried to use ".connection(dbConnection)" for bellow.
- I want to query for tow or more databases in one connection.

In brief code as bellow, I expect _some_queries_ to be applied each DB in same connection.
But doesn't. I found that each connection have different threadId at [lib/client.js](https://github.com/tgriesser/knex/blob/master/lib/client.js#L207)

```
var knex = require('knex')(conf); // DB1
var knex2 = require('knex')(conf2); // DB2
var con = require('mysql').createConnection({host: '127.0.0.1', user: 'knex_user', password : 'knex_pass'});
con.connect();
Promise.reduce([knex, knex2], function(promise, k) {
    return k.connection(con)._some_queries_;
}, 0);
con.end();
```

To be precise, I need XA Transaction. [This vote](http://stackoverflow.com/questions/30570922/xa-transaction-with-knex-node-js) is the detail of my question.

I am new at javascript, so maybe I wrote wrong code...
I hope somebody kindly aid me.
Thanks.

**Comment by kibertoad** [comment]
@hidetaka-f-matsumoto Sorry, this took forever, but I think what you are asking for was finally implemented in https://github.com/tgriesser/knex/pull/2817 and is available in 0.16.x "@next" branch.
