### ISSUE TITLE
.where() with function should probably pass an argument

### ISSUE THREAD

**Issue by rstacruz** [tgriesser/knex#863]
saw this example on the website:

``` js
knex('users').where(function() {
  this.where('id', 1).orWhere('id', '>', 10)
}).orWhere({name: 'Tester'})
```

...and thought that the use of `this` is probably better off done as an object passed onto that function. that is:

``` js
knex('users')
  .where(w => w.where('id', 1).orWhere('id', '>', 10))
  .orWhere({name: 'Tester'})
```

**Comment by tgriesser** [comment]
Yep, it actually works like that currently, I should update the docs to reflect this.

**Comment by wubzz** [comment]
Closing, this is documented now.
