### ISSUE TITLE
Postgres JSON operators are not considered valid.

### ISSUE THREAD

**Issue by rhys-vdw** [tgriesser/knex#867]
The following are not included [here](https://github.com/tgriesser/knex/blob/5e65678b32fa639843902d39603ab2050d84f10f/lib/formatter.js#L169-L171):

- ->
- ->
- ->>
- ->>
- #>
- #>>

[PostgreSQL reference](http://www.postgresql.org/docs/9.3/static/functions-json.html).

**Comment by Dynom** [comment]
I have a related problem. I want to perform a query like this:

```SQL
SELECT * FROM table WHERE slob::jsonb ? 'foo' AND ...
```

And I'm unable to get it to work, because the question mark `?` is treated magically. I'm working around it by doing:

```SQL
SELECT * FROM table WHERE (slob->'rating') IS NOT NULL
```

**Comment by rhys-vdw** [comment]
@Dynom Can you show the JavaScript you're using to generate these queries?

**Comment by Dynom** [comment]
Certainly, but it's not that complex. Simply using the questionmark results in undesired behaviour

The desired:
```TS
      .select(this.db.raw("distinct on (item_id) *"))
      // ..
      .where("slob::jsonb ? 'rating'")
      .andWhere({
        user_id: userId,
        action: Actions.SOME_ACTION
      })
      .whereIn("item_id", itemIds)
      .orderByRaw("item_id, date DESC")
      // ..
```

The workaround:
```TS
      .select(this.db.raw("distinct on (item_id) *"))
      // ..
      .whereRaw("(slob->'rating') IS NOT NULL")
      .andWhere({
        user_id: userId,
        action: Actions.SOME_ACTION
      })
      .whereIn("item_id", itemIds)
      .orderByRaw("item_id, date DESC")
      // ..
```

**Comment by elhigu** [comment]
@rhys-vdw The operators `->`, `#>` etc. to access fields inside json columns are not usually used the same way that the operators listed in https://github.com/tgriesser/knex/blob/master/src/formatter.js#L165. 

So I'm not sure if they should be in that list at all. To me those operators belongs together with `table.column` identifier part of the query. 

I mean that to me it sounds natural that one could  refer specific json field in those places where one can now put table/column reference.

e.g. `.where('Table.Column:jsonField.nestedField', '=', 'matchMe');` I've written pegjs parser for that syntax for our ORM based on knex.

Anyways what the operator list is missing for postgres is at least `%` operator for trigram string matching from `pg_trgm` extension and `@@` which used for postgres full text search queries. 

Looks like there are so many custom operators that this list could be dialect specific to be useful... or the list could be maybe removed and allow people to use any operators they want?

**Comment by jadams74** [comment]
Has any progress been made on this issue?

**Comment by elhigu** [comment]
I think this issue is invalid. One shouldn't be using those operators the same way how one would use e.g. `?`or `@>` operators. 

@jadams74 which operators were you looking for?

**Comment by jadams74** [comment]
Oh, I am agnostic as far as 'same way' is concerned. I just need the syntax to make this work:

select * from table where jsonbColumn->>'property' = 'true';

jsonbColumn
------------------
{
    "property": true
}

**Comment by elhigu** [comment]
I would like to do it in that way that I interpret string literal as jonb boolean than casting jsonb property to string... 

```js
knex('table').whereRaw("??->'property' = 'true'::jsonb", ['jsonbColumn']);
```

Your version would be

```js
knex('table').whereRaw("??->>'property' = 'true'", ['jsonbColumn']);
```
