### ISSUE TITLE
Increment rounds to integer when incrementing decimal or float field

### ISSUE THREAD

**Issue by light24bulbs** [tgriesser/knex#868]
If I say  

`bookshelfModelInstance.query().increment('ADecimalField', 1.28)`

the resulting SQL is 

`update "meals" set "subtracted" = "subtracted" + 1`

**Comment by olalonde** [comment]
+1

**Comment by elhigu** [comment]
There is almost ready branch implementing this if someone feels like finishing it https://github.com/tgriesser/knex/pull/1069

**Comment by skarbovskiy** [comment]
+1. also found, that calling several increment/decrement in one query results in only the last been added to resulting query
```
knex('balances')
  .increment('hold_amount', data.amount)
  .decrement('amount', data.amount)
```
`update "balances" set "amount" = "amount" - 9`

**Comment by shimmy568** [comment]
If you need to increment by a float you can still do it with something like this (until this is fixed eventually)


```
knex.raw('UPDATE users SET points = points + :score WHERE id = :username', {
	score: scores[i],
	groupID: userInfo[i].userID
}).catch(function(err){
	throw err;
});
```

In this case it allows score to be a float. Hope this helps.
