### ISSUE TITLE
It seems StringEscape for postgres is incorrect.

### ISSUE THREAD

**Issue by jchbh-duplicate** [tgriesser/knex#869]
According to the document of [String constant in postgres](http://www.postgresql.org/docs/8.3/interactive/sql-syntax-lexical.html#SQL-SYNTAX-STRINGS), 
Unlike Mysql, the "(double quote) does not need to be escape to \", which cause the compare return null if anything match this inputs.

**Comment by smithb1994** [comment]
+1

**Comment by smithb1994** [comment]
@jchbh-duplicate  @tgriesser 
this bug has been causing me so much hassle, I make a hacky work around but it always keeps coming back up in different parts of my code. 
simple statements like `.where('col', '@>', [val])` don't work, because its querying for the `\`

**Comment by tgriesser** [comment]
Closing in favor of #1661
