### ISSUE TITLE
Postgres: no whereNotExists with .insert?

### ISSUE THREAD

**Issue by myndzi** [tgriesser/knex#871]
Recently was testing code like this:

```
knex('history')
    .insert(rows)
    .whereNotExists(
        knex.select('ad_id')
            .from('history AS check')
            .whereRaw('history.ad_id = check.ad_id')
    );
```

but when I call .toString() on the output, the 'where not exists' clause does not appear to be included.

**Comment by marianomerlo** [comment]
This is an example on how to do it:
https://github.com/tgriesser/knex/commit/e74f43cfe57ab27b02250948f8706d16c5d821b8

**Comment by myndzi** [comment]
`knex.raw` does let you do things that knex itself doesn't support directly, but this issue is more to point out that this case should succeed as written than complain about it being impossible :) Thank you for the example, however; hopefully it will be useful to anyone stumbling on this by searching for same until such time as I or someone else can run it down and fix or add it.

**Comment by bhoriuchi** [comment]
i second this. i am trying to update a join table w/o using attach and check that a foreignKey exists on a belongsToMany relationship and the whereIn is not added to the query

```js
var rel = model.related(relatedField);
var dat = rel.relatedData;
return rel.detach(null, {transacting: t}).then(function() {

    var inserts = _.map(ids, function(id) {
        var row = {};
        row[dat.foreignKey] = dat.parentId;
        row[dat.otherKey]   = id;
        return row;
    });

    return knex(dat.joinTableName).debug().transacting(t)
    .whereIn(dat.otherKey, function() {
        this.transacting(t).select(dat.targetIdAttribute)
        .from(dat.targetTableName);
    })
    .insert(inserts);
    //return rel.attach(ids, {transacting: t});
});
```

debug output
```
{ method: 'insert',
  options: {},
  bindings: [ 1, 15, 200, 15 ],
  sql: 'insert into `group_user` (`group_id`, `user_id`) values (?, ?), (?, ?)' }
```

maybe i am doing this incorrectly?

**Comment by wubzz** [comment]
@myndzi The compiler for insert does not take the `where` satements into consideration, see [here](https://github.com/tgriesser/knex/blob/master/src/query/compiler.js#L73).

Replacing `return sql;` with
```javascript
let wheres = this.where();

return sql + (wheres ? ' ' + wheres : '');
```

Properly includes your where-statement in the query. But I'm not entirely sure why you'd want this, since the query *(at least from my understanding)* will fail regardless as the syntax is not supported.

```sql
insert into "test" ("test") values ('123') where not exists (select * from "test" where "test" = '123')
```

The only way that is supported, at least in postgres, is via this instead:

```javascript
insert into "test" ("test") SELECT '123' where not exists (select * from "test" where "test" = '123')
```

And even then it would only support insert of *one* row, no?

**Comment by elhigu** [comment]
Closing since SQL doesn't support inserts + where statements. Upsert/merge is how databases supports this usecase. About that there has been quite a lot discussion in https://github.com/tgriesser/knex/pull/2197 and currently tracked feature equest is https://github.com/tgriesser/knex/pull/3186

**Comment by kohenkatz** [comment]
@elhigu said:

> SQL doesn't support inserts + where statements

PostgreSQL does. See e74f43cfe57ab27b02250948f8706d16c5d821b8

**Comment by elhigu** [comment]
@kohenkatz no it doesn't did you read the SQL that trick genreates. There is zero where statement given for insert.

**Comment by kohenkatz** [comment]
@elhigu I don't think you are reading it correctly - there is clearly a `WHERE` statement in this:

```
insert into "recipients" (recipient_id, email) select \'user\', \'user@foo.com\' where not exists (select 1 from "recipients" where "recipient_id" = ?)
```

This is a trick that we have been using in PostgreSQL for many years.

Here is another example (from [here](https://www.the-art-of-web.com/sql/upsert/#section_4)):

```
INSERT INTO mailing_list (email)
SELECT 'email@example.org'
WHERE NOT EXISTS (SELECT * FROM mailing_list WHERE email='email@example.org');
```

I would give you a query from an application I wrote, but it has become more complex over time and now actually needs the newer `UPDATE ... ON CONFLICT` syntax for UPSERTs, and it's not worth my time to dig through the git history.

**Comment by elhigu** [comment]
In that query that `where` is part of `select` which a different thing. You should be able to achieve same thing also by combining CTEs (with query) and `insert` and knex already supports that.

**Comment by elhigu** [comment]
though one could add feature request to for supporting insterting data from select. I cannot remember from top of my head if that was somehow already possible. 

OP was not about that though.

**Comment by TSiege** [comment]
If anyone else has stumbled here trying to do this with a `whereNotExists` clause here's an example I have working with my own code.
```js
knex(
  // insert values clause
  knex.raw('?? (??, ??, ??)', ['posts_authors', 'author_id', 'post_id', 'sort_order'])
).insert(
  // select where not exists clause
  knex.select(
    knex.raw('?, ?, ?', [author_id, post_id, sort_order])
  ).whereNotExists(
    knex('posts_authors').select('id').where({ author_id, post_id: id })
  )
)
```
This is the query it generates:
```sql
insert into "posts_authors" ("author_id", "post_id", "sort_order") select '1', '123', 10 where not exists (select "id" from "posts_authors" where "author_id" = '1' and "post_id" = '123');
```
