### ISSUE TITLE
Execute query via all connections in pool.

### ISSUE THREAD

**Issue by khalilTN** [tgriesser/knex#875]
Hi,
I'm using a connection pool and I'm trying to execute oracle alter session queries.

```
var client = Knex({client: 'oracle', connection: connection,
      pool: {
             min: 0,
             max: 10
      }, debug: LOG_QUERIES
});
var query = "ALTER SESSION SET ...";
client.raw(query).then(function(resp){
    next();
 }).catch(function(e){
     next(e);
});
```

The problem is that query is executed via only one connection from the pool, so if the pool returns another instance, this instance session is not affected with the query .
Is there a way to browse all connections in pool and do some initialization queries ?
Thanks.

**Comment by wubzz** [comment]
No, there is not, since the connections do not exist until they are required. In order to do what you're suggesting you would need to use `afterCreate` in pool configs. See documentation for details.
