### ISSUE TITLE
WebSQL broken since bluebird@2.9.28

### ISSUE THREAD

**Issue by LoicMahieu** [tgriesser/knex#877]
In latest install of `knex`, WebSQL is broken.

If `bluebird@2.9.28` is installed, we got exception:
`Failed to execute 'executeSql' on 'SQLTransaction': SQL execution is disallowed.`
#### Why ?

I think bluebird defers the execution of `executeSql`. Sample demo:

``` js
// WORKS
var db = createDatabase(...)
db.transaction(function (t) {
  t.executeSql('..', [], function () { ... })
});

// DONT WORKS
var db = createDatabase(...)
db.transaction(function (t) {
  setTimeout(function () {
    t.executeSql('..', [], function () { ... })
  }, 0);
});
```

**`t.executeSql()` must be called sync.**
#### Demonstration

https://travis-ci.org/LoicMahieu/websql-tests/jobs/68164864
Error which is thrown is not `Failed to execute 'executeSql'...` but `Cannot set property message of [object Object] which has only a getter`. This is because knex want to rewrite message property of the error, not support when this is a SQLError, see: https://github.com/tgriesser/knex/blob/master/src/client.js#L125
This would be the subject for another issue ;)
#### Rapid Workaround

Overwrite knex's bluebird version. Example:

```
rm -rf node_modules/knex/node_modules/bluebird
npm install bluebird@2.9.27
```
#### Knex Workaround

Move `transaction()` closer to `executeSql()`:
https://github.com/LoicMahieu/knex/commit/22e3918db82a7c8d77db709e19285769d430b175

**Comment by kibertoad** [comment]
@elhigu Do we still support websql?

**Comment by elhigu** [comment]
nope and there has been discussion about dropping bluebird too
