### ISSUE TITLE
Postgres array_append

### ISSUE THREAD

**Issue by greens231** [tgriesser/knex#879]
Is there a way to array_append? I use array_append a lot and having to make a raw query every time i need is a deal breaker. help please.

**Comment by smithb1994** [comment]
+1
I've been looking for a good solution to this for arrays. You can do it with most query instances though, doing something like this:

```javascript
knex('userModels').select(
    knex.raw('array_append(colName, ?)', [2])
);
```
`select array_append(colName, '2') from "userModels"`

As soon as you try passing in arrays though, it doesn't work. See reference to feature request #791

**Comment by smithb1994** [comment]
@greens231 
Here's how you probably want to use it.
```javascript
knex('userModels')
    .update({
        colName: knex.raw('array_append(colName, ?)', ['cats'])
    });
```
`update "userModels" set "colName" = array_append(colName, 'cats')`

**Comment by elhigu** [comment]
closing as solved
