### ISSUE TITLE
SSL Query Parameter for Postgres, again

### ISSUE THREAD

**Issue by idan** [tgriesser/knex#893]
Seems like #852, #516 are still lingering.

As per #852:

Works:

```
connection: {
  host: "host",
  port: "port",
  user: "user",
  password: "password",
  database: "database",
  ssl: true
 }
```

Does not work:

```
connection: "postgres://user:password@host:port/database?ssl=true"
```

**Comment by holic** [comment]
Also ran into this. I worked around it by manually parsing the connection string with the same library used in Knex and passing the resulting config into Knex:

```js
var parse = require('pg-connection-string').parse

module.exports = {
	client: 'pg',
	connection: parse(process.env.DATABASE_URL)
}
```

**Comment by rhys-vdw** [comment]
Hey people. Thanks for the report. Any chance we could get a PR with a fix for this one?

**Comment by rhys-vdw** [comment]
Also with some test coverage since it seems this keeps coming up.

**Comment by harriha** [comment]
Seems that this is fixed in master already https://github.com/tgriesser/knex/commit/90105e064fc1de032df15f73530f0640528b920a

**Comment by wubzz** [comment]
```javascript
const knex = require('knex')({
	client: 'pg',
	connection: "postgres://user:password@host:port/database?ssl=true"
});


console.log('sslEnabled', knex.client.config.connection.ssl);
```

>sslEnabled true
