### ISSUE TITLE
semver

### ISSUE THREAD

**Issue by iofjuupasli** [tgriesser/knex#912]
Please use semver

> Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable
> 
> How do I know when to release 1.0.0?
> 
> If your software is being used in production, it should probably already be 1.0.0. If you have a stable API on which users have come to depend, you should be 1.0.0. If you're worrying a lot about backwards compatibility, you should probably already be 1.0.0.

**Comment by maxcnunes** [comment]
Yes. Apparently there were breaking changes from 0.7.* to 0.8.* . For example in 0.7.* was possible pass a client to knex ([here](https://github.com/tgriesser/knex/blob/0.7/knex.js#L96)) and this is not possible anymore. So the knex should have moved to 1.0.0

Semver really makes clearer when the changes are breaking changes, new features or just bug fixings.

**Comment by martinheidegger** [comment]
Knex is quite mature now. What is keeping you from adopting semver? It would be really quite a relief to have that!

**Comment by elhigu** [comment]
@martinheidegger  knex is following semver + this is duplicate https://github.com/tgriesser/knex/issues/1331
