### ISSUE TITLE
knex('tablename').where({ a: 1 }).where({ b: 2 }) unexpected behavior.

### ISSUE THREAD

**Issue by olalonde** [tgriesser/knex#914]
Doing 

```
knex('tablename').where({ a: 1 }).where({ b: 2 });
```

seems to be the equivalent of

```
knex('tablename').where({ a: 1, b: 2 });
```

This looks like unexpected behaviour to me. Shouldn't the second `.where()` undo the previous where clause?

**Comment by olalonde** [comment]
Is there any method to reset the where clause?

**Comment by olalonde** [comment]
That seems to break what knex uses to parse query results.

**Comment by razvanz** [comment]
Not a contributor, but since I'm here, I'm going to answer.

A query is composable hence the 2 query examples you provided are equivalent. However, you care reset a query's where clause with `.clearWhere` ([docs](http://knexjs.org/#Builder-clearWhere)).

**Comment by elhigu** [comment]
Thanks @razvanz I'm always happy to see that more people are answering these issues. And to add some more info to the answer: `.andWhere` is just an alias of `.where` method so if you chain multiple `.where` one after another they will be combined with `and` to the final query.
