### ISSUE TITLE
Feature request: `join table as alias`

### ISSUE THREAD

**Issue by olalonde** [tgriesser/knex#915]
Would be nice if the `.join` api exposed an `.as` method to alias the table being joined. Would be useful for queries like `knex('users').join('users', function () { this.as('referrer'); })`.

**Comment by olalonde** [comment]
Sending a PR soon.

**Comment by olalonde** [comment]
Ok so I implemented the feature but when executing the query, the rows don't parse correctly into an object.

**Comment by olalonde** [comment]
Oh ok, the problem was that both table had same column names and were "shadowing" each others. Fixed by "manually" prefixing all joined columns with `.select()`. Ready to send PR.

**Comment by elhigu** [comment]
@olalonde  I was just going through old PRs looks like the one you sent didn't work so I'm closing it for now. This would be nice addition to have. 

In addition to code and test PR should also have `index.html` update with documentation.

**Comment by absolux** [comment]
Something like below does not work ?
```js
 knex('users').join('users as second', 'users.id', 'second.other_id') 
```

**Comment by elhigu** [comment]
@absolux yeah it works, I suppose this can be closed...
