### ISSUE TITLE
using hasTable - ERROR: migration did not return a promise

### ISSUE THREAD

**Issue by ashleygwilliams** [tgriesser/knex#924]
https://gist.github.com/ashleygwilliams/64fa852f58c07dcddf58 <- code and error here

full PR here: https://github.com/mozilla/api.webmaker.org/pull/141
travis here: https://travis-ci.org/mozilla/api.webmaker.org/builds/73473870

basically am using `hasTable` because the project did not originally start using knex. it just used sql. we are now converting all the migrations to knex. new local instances will need to run all the migrations, but old instances (like production), will only need to run new ones.

i investigated editing the migrations table. if that's better than this checking i'm doing, i'd love some direction on doing that.

either way would really love some help. this is an open source educational project for mozilla foundation- so it's for a good cause :) thanks in advance!

**Comment by wubzz** [comment]
I'm guessing this is long since resolved, and I apologize that no response was given here.

Presumably it was due to a missing `return` statement before `knex.schema` in `exports.up`.

**Comment by DanrwAU** [comment]
I'm having the same issue with this, i need to do an if (!exists) as per the original poster to not try and run on existing tables, how should we handle this to prevent the below errors? 

migration 20190322204706_create_messages_table.js did not return a promise

My Migration file is: 
```
exports.up = function(db, Promise) {
    db.schema.hasTable('messages').then(function(exists) {
        if (!exists) {
            return db.schema.createTable('messages', table => {
                    table.increments('id').primary().unique();
                    table.string('address', [255]).notNullable();
                    table.text('message').notNullable();
                    table.text('source').notNullable();
                    table.integer('timestamp');
                    table.integer('alias_id');
                    table.foreign('alias_id').references('capcodes.id');
                    table.index(['address', 'id'], 'msg_index');
                    table.index(['id', 'alias_id'], 'msg_alias');
                    table.index(['timestamp', 'alias_id'], 'msg_timestamp');
            })
            .then((result) =>{

            })
            .catch((err) => {
                
            })
        } else {
            return
        }
    })
}


exports.down = function(db, Promise) {
  
};
```
