### ISSUE TITLE
Paging

### ISSUE THREAD

**Issue by 58bits** [tgriesser/knex#925]
I was wondering what the current common practice is for paging with knex, and returning totals, before offset and limit?

For small datasets in pg, I was considering using `knex.raw` and a windowing function so that this can be done in a single request. e.g...

```
SELECT COUNT(table.id) OVER () AS total_entries_count, a,b,c
FROM table
WHERE clauses
OFFSET x LIMIT y;
```

Thoughts?

**Comment by andrejkaurin** [comment]
I am interested too

**Comment by arenddeboer** [comment]
(for future reference)
You should be able to do something like this:
```
knex('User')
.select(['id', 'displayName', knex.raw('count(*) OVER() AS full_count')])
.limit(10)
.offset(20)
.then(function (rows) {
  console.log(rows)
})
```

I tried this until I realized the total count is meaningless for me as I do a lot of joins which get parsed into a hierarchical JSON response using treeize, reducing the number of final rows.

**Comment by elhigu** [comment]
Common practise is to do count query and separately and only after that query the page. AFAIK that is also how ORMs usually does it.
