### ISSUE TITLE
Add link to Knex Query lab in readme

### ISSUE THREAD

**Issue by iansinnott** [tgriesser/knex#926]
It would be great if there was a link to [Knex Query lab][lab] in the readme. It's a good resource for people who want to use Knex that are also relatively new to SQL. I think I first found out about this in @tgriesser's [JSCONF talk][talk], which is worth a watch for anyone interested in this lib.

[lab]: http://michaelavila.com/knex-querylab/
[talk]: https://www.youtube.com/watch?v=19Av0Lxml-I

**Comment by rhys-vdw** [comment]
Hey, that is helpful. I'll accept a PR against the README. It could also be mentioned under the "Debugging" section of the website.

**Comment by iansinnott** [comment]
Sure, happy to make a pull request. I was just about to head to work when I wrote that earlier.

**Comment by iansinnott** [comment]
Opened PR #930
