### ISSUE TITLE
Decimal types fetching as strings, not numbers

### ISSUE THREAD

**Issue by light24bulbs** [tgriesser/knex#927]
I have a migration which creates the field
``` coffeescript
t.decimal('balance', undefined, 2)
```

But when fetching from the database, the model returns with 

```coffeescript 
balance: '12.00'
```

Am I doing something wrong?  Could this be a property of Postgres and not Knex?

**Comment by rhys-vdw** [comment]
See #387.

**Comment by light24bulbs** [comment]
Thanks.  That's too bad.  I worked around it by overriding bookshelf's ```model.parse```

```coffeescript
parse: (attrs) ->
	attrs.balance = Number(attrs.balance)
	return attrs
```

I'll open an issue with the postgres plugin.

**Comment by tukkajukka** [comment]
Here's a slightly improved version that returns both the integer part and the fractional part:

```es6
const pg = require('pg');
const PG_DECIMAL_OID = 1700;
pg.types.setTypeParser(PG_DECIMAL_OID, parseFloat);
```

**Comment by abhyuditjain** [comment]
This is awesome. But can I use moment(<value_from_db>).format("YYYY-MM-DD") for date type? I don't know ho to do that as knex returns date as datetime string.

**Comment by elhigu** [comment]
@abhyuditjain check documentation of your DB driver how to set custom type parsing. The question has been answered many times already here in knex issues and IIRC also in stackoverflow.

**Comment by IlyaSemenov** [comment]
The modern alternative without hardcoding internal IDs:

```ts
pg.types.setTypeParser(pg.types.builtins.NUMERIC, Number)
```
