### ISSUE TITLE
How to deal with interrupted connections?  Query hangs when connection is lost.

### ISSUE THREAD

**Issue by tilleps** [tgriesser/knex#936]
I wondering how to deal with interrupted connections in the following scenario:

Sequence of events:
1. Start database
2. Start app and create connections/pool
3. Stop database
4. Execute query (issue:  query hangs).

Is there a way to prevent the query from hanging?  Is there an client/pool event that I can listen to that will notify that the database connection(s) is no longer available?

**Comment by marwanhilmi** [comment]
Running into this issue - seems like a pretty big oversight. It appears there's not even a way to listen to errors from the connection - the queries just hang (no errors returned at all). Would it be possible to implement something like `pool.on('error', function(){})` event so we can at least manually restart or reconnect?

**Comment by emadd** [comment]
+1  Really needs a graceful way to recover from lost connections

**Comment by woubuc** [comment]
I'm running into this issue now in testing. Has this been addressed yet?

**Comment by digipigeon** [comment]
+1 Fixing this would be a big bonus for me.

**Comment by elhigu** [comment]
@tilleps could you try this again after 0.10.0 is released (or with 0.10.0-rc1 which is currently out)? This might cause connection acquire timeout after 60 seconds in `knex@0.10`

**Comment by dnfrolov** [comment]
@tilleps try to set `requestTimeout` on pool configuration object to some time less then acquireTimeout

**Comment by emadd** [comment]
@elhigu I was able to update to 9.0 and it definitely handles loss off connection better than before.  Nice!

**Comment by newls** [comment]
I don't know if this can help, but I achieved to find where to hook some event listener.

```javascript
var knex = require('knex')(configuration)
_knex.client.pool.on('error', function() {
    console.log(arguments);
  }
```

This achived to give me some result

```
{ '0': 
   { Error: connect ENOENT /var/run/postgresq/.s.PGSQL.5432
       at Object.exports._errnoException (util.js:1012:11)
       at exports._exceptionWithHostPort (util.js:1035:20)
       at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
     code: 'ENOENT',
     errno: 'ENOENT',
     syscall: 'connect',
     address: '/var/run/postgresq/.s.PGSQL.5432' } }

```

In this example, I tried to use host as '/var/run/postgresq', the real unix socket is at '/var/run/postgresql'.
This is the only way I found to get connection error.

I know this issue is more specific to "lost" connection, but I'm quite certain it works for that case too.

**Comment by tilleps** [comment]
@elhigu Updated to Knex version 0.12.6.  Appears to reconnect automatically.  Thank you!

(Tested with default knex connection config settings)
