### ISSUE TITLE
create view

### ISSUE THREAD

**Issue by sombriks** [tgriesser/knex#939]
Hello all,

is there by chance support to the creation of views?

something like:

`return knex.schema.createView('vw_user_accounts')//`
` .asSelect('*').from('users').leftJoin('accounts', function() {`
` this.on('accounts.id', '=', 'users.account_id').orOn('accounts.owner_id', '=', 'users.id')`
`});`

**Comment by chrisbroome** [comment]
I've resorted to doing something like the following:

```javascript
function createOrReplaceView(viewName) {
  var viewDefinition = knex.from('users').leftJoin('accounts', function() {
    this.on('accounts.id', '=', 'users.account_id').orOn('accounts.owner_id', '=', 'users.id')
  });
  return knex.schema.raw('CREATE OR REPLACE VIEW ?? AS (\n' + viewDefinition + '\n)', [viewName]);
}
```

**Comment by sombriks** [comment]
Hi @chrisbroome ,

i'm solving it with pure knex.raw  queries.

Also i'm modelling the database as close as possible to the [relational algebra](https://en.wikipedia.org/wiki/Relational_algebra) approach.

That way even raw sql gets a bit cleaner.

Im closing the issue, now i think that knex can live quite happy without it.

If anyone thinks it should have special builder helper for view creation, just file an new issue.

**Comment by revolunet** [comment]
where would you put the view creation code ? in a knex migration ?

**Comment by sombriks** [comment]
@revolunet pretty much there, in the migrations folder.

actually they are already there, but disguised as knex.raw statements.

we could debate there a good enough idiom and add it under knex.schema umbrella.

for now, migrations with knex.raw are saving well all my databases evolutions.

**Comment by honestserpent** [comment]
@sombriks could you please add more info on where and how you are using them in your migrations? Possibly, could you put an example migration file where you use it?

**Comment by sombriks** [comment]
Hi @honestserpent , i have a sample project on that: https://github.com/sombriks/sample-knex-cookbook

**Comment by honestserpent** [comment]
Thank you! Have you ever used [objection ](http://vincit.github.io/objection.js/#introduction) with that?

**Comment by acodercat** [comment]
i need createView ,thanks !!1

**Comment by elhigu** [comment]
@acodercat create proper feature request and propose how it should work exactly. Then - if everything is clear how it should work - send PR with tests and documentation and then you'll get what you need 👍
