### ISSUE TITLE
Ability to override getter/setter for specific model properties?

### ISSUE THREAD

**Issue by jamesdixon** [tgriesser/knex#940]
Hi,

Is there a way to override a getter/setter for specific properties on a model? My use case is that for a property like email address, I want to ensure that when it is set or retrieved, it always sets/retrieves the email in lowercase so I can do a valid comparison.

Is this possible?

Thanks!
James

**Comment by rhys-vdw** [comment]
I think you meant to post this to Bookshelf, not Knex right?

**Comment by jamesdixon** [comment]
@rhys-vdw apologies. That was the intention. I was flipping back and forth between Bookshelf and Knex tabs and mistakenly posted this here. I'll close it now.
