### ISSUE TITLE
Catching stream errors

### ISSUE THREAD

**Issue by danielgindi** [tgriesser/knex#948]
I'm trying to use `stream()`, and catch sql errors, but it seems that there's no way to do that.

Say that:

``` javascript
db.select('*').from('unknown_table').stream(function (stream) {

    console.log('This line is reached'); /// <--- Stream is received

    stream.on('error', function (err) {
        console.log('This line is not reached'); /// <--- Seems as a natural place to handle stream errors
    });

}).catch(function (err) {
    console.log('This line is also not reached'); /// <--- Seems as a natural place to handle sql errors
});
```

I do not receive any callback with the error. Instead this is the log:

``` cli
> This line is reached
> Error: ER_NO_SUCH_TABLE: Table 'unknown_table' doesn't exist
```

**Comment by danielgindi** [comment]
@tgriesser any ideas on how to catch these errors?

**Comment by id0Sch** [comment]
so this is still happening, im using mysql syntax.
any idea how to catch these errors?

**Comment by bertho-zero** [comment]
I have the same issue, I have an uncaughtError but my .on('error') isn't triggered.

**Comment by novemberborn** [comment]
I think the problem is in this snippet:

https://github.com/tgriesser/knex/blob/f8989e129fe5863437d8e87fdd6a1e1971841305/src/runner.js#L81:L105

If `ensureConnection()` fails, and no `handler` was provided, the promise rejection is swallowed. Instead it should be emitted on `stream`.

For now, a workaround might look something like this:

```js
let stream
const streamDone = knex()
  // query code
  .stream(streamValue => {
    stream = streamValue
  })

streamDone.catch(err => stream.emit('error', err))

// Now use `stream`
```

**Comment by novemberborn** [comment]
Here's a PR: https://github.com/tgriesser/knex/pull/2199
