### ISSUE TITLE
How to construct `SELECT (EXISTS ...))`?

### ISSUE THREAD

**Issue by sorawit** [tgriesser/knex#949]
Hi. Is it possible to construct query like this with knex?

`SELECT id
  ,name
  ,EXISTS (SELECT 1
   FROM options
   WHERE customer_id = customers.id
   AND option_name = 'Editor') AS isEditor
FROM customers`

Thanks!

**Comment by rhys-vdw** [comment]
Kind of:

```js
var inner = knex('options').whereRaw('customer_id = customer.id').limit(1);
var isEditor = knex.raw(isEditor).wrap('exists (', ') as isEditor');

knex('customers').select('id', 'name', isEditor).then( //...
```

output:
```
select "id", "name", exists (select * from "options" where customer_id = customers.id limit 1) as isEditor from "customers"
```

**Comment by sorawit** [comment]
I assume you mean  `knex.raw(inner).wrap('exists (', ') as isEditor');` and it works! Thanks a lot.

**Comment by maxbogue** [comment]
Why is there not a .exists() method like .count() for this?

**Comment by elhigu** [comment]
@maxbogue because we cannot make wrapper to every function of every dialect.

```js
const subQuery = knex('options').where('customer_id', knex.raw('??', ['customer.id']).limit(1);
knex('customers').select('id', 'name',  knex.raw('exist(?) as ??', [subQuery, 'isEditor'])).this(...
```

is currently nicest syntax for  this.

**Comment by towc** [comment]
can I argue this is a fairly common usecase, and I'd be fine if it actually just limited to 1 and turned to a boolean for every implementation? It could then use optimizations, but the main point is that it helps keep your code semantic

**Comment by nfantone** [comment]
For everyone out there that reaches this issue looking for a way to create a simple `SELECT EXISTS(...)` statement, here's the gist:

```js
knex.first(
  knex.raw('exists ? as present', knexSubQuery.limit(1))
);
```

Example:

```js
async function exists(alias) {
  const res = await knex.first(
    knex.raw(
      'exists ? as present',
      knex('email_mx_alias')
        .select('id')
        .where('alias', '=', alias)
        .limit(1)
    )
  );

  return res.present === 1;
}
```

**Comment by Gameghostify** [comment]
This should be another way, right?

```js
const selectQuery = knex.select("1").from("myTable").where({ myColumn: 12345 }).toSQL();

const result = await knex.raw(`SELECT EXISTS (${selectQuery.sql})`, selectQuery.bindings);

const exists = result.exists;
```

**Comment by nfantone** [comment]
@Gameghostify I think that one has a couple of issues.

- You can't select an unknown column from a `.select()` call - like you did with `1` there. You'll en up with a `ER_BAD_FIELD_ERROR: Unknown column '1' in 'field list'` exception.
- If you fix the above (by, say, changing `1` to some known column, like `id`), then there would be no `.exists` property anywhere on your result set. You get back `RowDataPacket` and `FieldPacket` arrays.

Other than that, it should work.

**Comment by Gameghostify** [comment]
I haven't tested it yet but I'm pretty sure
```sql
SELECT EXISTS(SELECT 1 FROM myTable WHERE myColumn = 12345)
```

gets generated here.

With most rdbms (e.g. mysql, mariadb, ...) this should be exactly the same as
```sql
SELECT EXISTS(SELECT * FROM myTable WHERE myColumn = 12345)
```

**Comment by nfantone** [comment]
Well - I _did_ test it and it has the problems outlined above. The concept works, it just needs some implementation tweaks to make valid for `knex`.

**Comment by Gameghostify** [comment]
Oh, sorry, I misunderstood

Tested it now and it works with `knex.select(1)` (notice, not a string)!

It seems that knex treats strings as column names here  (whereas numbers are treated as literals)

**Comment by naveen1337** [comment]
I am doing like this for my unique constraint check logic using Knex raw

```ts

type payloadType = {
    name: string,
    colname: string,
    colvalue: string
}
export async function uniqueConstrintCheck(knex: any, tableName: string, payload: payloadType[]) {
    try {
        for (const task of payload) {
            const response = await knex.raw('SELECT  EXISTS (SELECT from ?? WHERE ??= ?)', [tableName, task.colname, task.colvalue])
            if (response.rows[0].exists === true) {
                return `${task.name} already exists`
            }
        }
        return null
    } catch (err) {
        console.error(err)
        return `something went wrong`
    }
}
```
