### ISSUE TITLE
Add a 'single' function just like the 'first' function

### ISSUE THREAD

**Issue by rightaway** [tgriesser/knex#950]
There's a 'first' function http://knexjs.org/#Builder-first to get just the first row in the results, but in cases where your 'where' clause should only be returning a single row, you should be able to call a function like `single()` to throw an error if 0 or 2+ rows are returned. Kind of like a sanity check on your query, and returning only a single object so that you don't need to do r`esults[0]`.

**Comment by rhys-vdw** [comment]
This proposed `single()` method would be unique to Knex in that it fires an error after generating a valid query. I don't think this kind of validation is a good fit for Knex, which is billed as a "query builder". This kind of logic, in my opinion, is better suited as a layer above Knex.

For instance, you could use Bookshelf's [`Model#fetch({require: true})`](http://bookshelfjs.org/#Model-fetch) for this kind of behaviour, and it makes sense in the context of an ORM.

However, you if you really want this, it should be fairly trivial to make a plugin:

```js
// knex-plugins/single.js
function ensureSingle(rows) {
  if (rows.length !== 1) throw new Error(
    '`.single` received result set with ' + rows.length + ' rows!'
  );
}

function single() {
  return this.tap(ensureSingle);
}

module.exports = function(Knex) {
  Knex.Client.prototype.QueryBuilder.prototype.single = single;
};
```

```js
// knex-instance.js
var Knex = require('knex');
require('./knex-plugins/single')(Knex);

var config = // ...

module.exports = Knex(config);
```

**Comment by rightaway** [comment]
> This proposed single() method would be unique to Knex in that it fires an error after generating a valid query. I don't think this kind of validation is a good fit for Knex, which is billed as a "query builder". This kind of logic, in my opinion, is better suited as a layer above Knex.

Very well put, and I agree. And thanks for the details on how to make a plugin. Marking as closed.

**Comment by acro5piano** [comment]
I created a package for this. Just import them to extend Knex query builder.

https://github.com/acro5piano/knex-first-or-fail

Note that it doesn't throw error if there are two or more rows in the result set.

**Comment by elhigu** [comment]
I think we have now ecosystem document somewhere where this can be added 👍
