### ISSUE TITLE
Unhandled rejection Error: There is no pool defined on the current client

### ISSUE THREAD

**Issue by AhmadZuhdi** [tgriesser/knex#954]
knex@0.8.6

with config
```
client : 'sqlite3',
connections : {
				
	filename : `${pathConfig.app}/database/db.sqlite`
},
pool: {
				
    min:0,
	max:1
}
```

![](https://www.dropbox.com/s/lif0ubnmq843qrl/Screenshot%202015-08-30%2010.14.35.png?dl=1)
![](https://www.dropbox.com/s/2pm7k4rzw3ru7mg/Screenshot%202015-08-30%2010.14.49.png?dl=1)

**Comment by blah238** [comment]
I think `connections` should be `connection`. I agree that the error messaging here is very unhelpful.

**Comment by AhmadZuhdi** [comment]
it work now, 
thanks a lot.
