### ISSUE TITLE
undefined attributes are not handled properly

### ISSUE THREAD

**Issue by b3njamin** [tgriesser/knex#961]
When saving to the database values that are undefined should not be saved currently they art set to NULL.  See tgriesser/bookshelf#891

**Comment by rhys-vdw** [comment]
Thanks @b3njamin.

Related: #332.

**Comment by b3njamin** [comment]
@rhys-vdw Have created a pull request man :facepunch:

**Comment by elhigu** [comment]
Fixed in #1174
