### ISSUE TITLE
Trouble running an array of promises sequentially

### ISSUE THREAD

**Issue by Turmoil** [tgriesser/knex#971]
Hi,

I am trying to run an array of promises sequentially. I am new to javascript and promises and haven't got the hang of promises quite yet. So basically I iterate though an array of JSON objects called `organisationStructure` and add the promise sequence (generated by `createNode`) to the `nodes` array. When I reduce the `nodes` array of promises it seems to run concurrently. I realise the promises run straight away but how do I get them into the reduce sequentially. Below is my code:
```javascript
return headNode.then(function(nodeId) {

    var nodes = [];
    var parentId = nodeId[0];

    for (var i = 0; i < organisationStructure.length; ++i) {
        var orgNode = organisationStructure[i];

        nodes.push(
            createNode(accId, orgNode.Country, Tags.Country, parentId)
            .then(function(countryNodeId) {
                return createNode(accId, orgNode.City, Tags.City, countryNodeId[0]);
            }).then(function(cityNodeId) {
                return createNode(accId, orgNode.Branch, Tags.Branch, cityNodeId[0]);
            }).then(function(branchNodeId) {
                return createNode(accId, orgNode.Department, Tags.Department, branchNodeId[0]);
            })
        );
    }

    return Promise.reduce(nodes, function(_, task) {
        console.log(task);
        return task;
    }, null);
});
```

**Comment by tkellen** [comment]
Assuming your promise is a bluebird process, just do this:

```js
Promise.each(['foo', 'bar', 'baz'], function (item) {
  console.log('processing', item);
  // if a promise is returned here, iteration will suspend until it clears
});
```

**Comment by Turmoil** [comment]
Thanks tkellen. I just re-read the Bluebird documentation and it says what you suggested. That the `each` method also takes an array of values. I assumed it only took an array of promises and was confused abut how it would do that sequentially. I modified my code to this and it now works. Thank you.
```javascript
return Promise.each(organisationStructure, function(orgNode){
    return createNode(accId, orgNode.Country, Tags.Country, parentId)
    .then(function(countryNodeId) {
        console.log(countryNodeId[0]);
        return createNode(accId, orgNode.City, Tags.City, countryNodeId[0]);
    }).then(function(cityNodeId) {
        return createNode(accId, orgNode.Branch, Tags.Branch, cityNodeId[0]);
    }).then(function(branchNodeId) {
        return createNode(accId, orgNode.Department, Tags.Department, branchNodeId[0]);
    });
});
```

**Comment by tkellen** [comment]
Sure thing! You might wanna do all of that in a transaction, too.

**Comment by Turmoil** [comment]
Yeah next step is to understand error handling in promises and then transactions. I'm guessing exceptions bubble up and I can handle it in one spot and probably handle all exceptions from the transaction scope.
