### ISSUE TITLE
Default pool2 configuration often leads to ECONNRESET errors

### ISSUE THREAD

**Issue by acgourley** [tgriesser/knex#975]
I recently ran into hair-pulling errors using knex with google cloud SQL. The issue was that GCS was closing idle connections in the pool, however by default pool2 was not testing the connections effectively before trying to use them. 

There are two possible solutions, and I would suggest the default config does one of the following: 

### Option 1 - don't keep idle connections around. 
```
  client: 'mysql',
  pool: {
    min: 0
  }
  ...
}
```
###  Option 2 - effectively test connections (may be database specific)
```
  client: 'mysql',
  pool: {
    min: 2,
    max: 10,
    ping: function (conn, cb) { conn.query('SELECT 1', cb); }  }
  ...
}
```

**Comment by smlynch** [comment]
@acgourley I was also pulling my hair out over this issue but luckily I found this issue.  Thanks for the tips (and hopefully knex can provide better defaults to handle this).

**Comment by ErisDS** [comment]
Would be great if you could include the errors you were getting on this issue so that other people with the same problem can find this easily by searching for the error message :grin:

**Comment by vivekduddempudi** [comment]
@acgourley  Thank you very much

**Comment by acgourley** [comment]
The main reason I didn't include errors is that they are vague - basically node complains about ECONNRESET but that could have many other causes. I'll add it to the title, though!

**Comment by jamesdixon** [comment]
Thanks for posting this. Very helpful! Curious if you've had any issues with the first request being slow? I tried both of the configurations above and while I'm not seeing the ECONNRESET anymore, after an idle period, the first request to the server is slow -- subsequent requests are fast.

**Comment by techniq** [comment]
@jamesdixon - are you using a first generation on demand  instance?  If so the instance might be shutting down so the slowness is in it starting back up.

**Comment by jamesdixon** [comment]
@seansullivan I'm actually on Azure. The application runs on an Azure App Service (formerly Azure Websites) and the database sits on an Azure VM. The App Service is set to "Always On," which should prevent it from being suspended and then having to initialize when a request comes in. However, I experienced the same issue when using Amazon RDS, so I'm not sure if there is something I need to configure within Postgres itself.

**Comment by acgourley** [comment]
I haven't really noticed it being slow at first. I'm not sure why that would even be the case, once you set the pooling to 0 it should be making a new connection every time and so the client should be doing the same thing on call 1 as call 2. If you quickly bounce your client app, is the first request still slow? If not, it's probably the server.

**Comment by jamesdixon** [comment]
@acgourley I switched pooling back to 0 and the issue is still there, but further investigation reveals that it's something to do with Azure. 

On another note, are you successfully able to use pooling or do you have it off as well? If the latter, has it affected your application performance at all?

**Comment by acgourley** [comment]
If pooling works for you, and if your host allows you to keep connections
open a while, great. The concern would be if your host closes connections
quickly anyway which effectively turns makes queries even more expensive as
they first test the connection, realize it's down, and then have to make a
new connection anyway. If you have control over your database server, you
can probably set things up to support this well. If you're using a hosted
SQL solution with minimum control, maybe a pool of zero is better. I
personally am using Google Cloud SQL and have kept the pool at 0.

**Comment by jamesdixon** [comment]
Thanks for the feedback, @acgourley. I'm actually using my own Postgres instance hosted on an Azure VM. That said, it seems that whenever I attempt to use pooling, I run into the `ECONNRESET` error. I believe I'll be sticking with a pool of 0 until I can get that resolved.

**Comment by tgriesser** [comment]
I think the fixes in 0.12 should help with this, please open another ticket if you have any errors.

**Comment by jimmanu** [comment]
@jamesdixon did you ever resolve this? I'm having a similar issue "too many connections" with knex in azure

**Comment by jeffijoe** [comment]
I'm on 0.14.6 and am experiencing this issue on Google Cloud SQL (Postgres).

Here's a screenshot from my error logs.

![image](https://user-images.githubusercontent.com/2505474/42123077-12971df4-7c4c-11e8-95cb-0791dedd5ec7.png)

I'm curious if the `Transaction query already complete` error is related? I can't reproduce locally, no matter how long I run it.
