### ISSUE TITLE
0.8.6 with sqlite3 - there is no connection pool defined on the current client

### ISSUE THREAD

**Issue by cdelaorden** [tgriesser/knex#979]
Tested with node 0.10.x and node 0.12.x, with and without pool setting in knexfile, every combination.
sqlite3 version is 3.1.0

I'm using babel but I also tried from node REPL with no success.

Funny thing is: knex migrate:latest _does_ work, with the same knexfile.

Any hints or advice?

**Comment by blah238** [comment]
@cdelaorden is this still an issue for you? If so please post your Knexfile and the code you are using to initialize Knex.

**Comment by rstacruz** [comment]
this is happening to me with postgres. migrations run fine.

```
// knexfile.js
var config = {
  client: 'pg',
  connection: process.env.DATABASE_URL /*its blank*/ ||
    'pg://rsc:@127.0.0.1/hello_development'
}

module.exports = {
  development: config,
  production: config
}
```

**Comment by rstacruz** [comment]
```
const knex = Knex(require('../knexfile'))

const bookshelf = Bookshelf(knex)

const Snapshot = bookshelf.Model.extend({
  tableName: 'snapshots'
})

var snap = new Snapshot({
  created_at: new Date(),
  data: 'hello'
})

return snap.save()
```

**Comment by rstacruz** [comment]
nevermind, i see where i went wrong! it should be:

```js
const env = process.env.NODE_ENV || 'development'
const knex = Knex(require('../knexfile')[env])
```

**Comment by cdelaorden** [comment]
Sorry @blah238 forgot to answer to this. I didn't retry but probably my mistake was in knex initialization also, probably forgot to extract the correct environment config.

I think however, the error should read something like 'Invalid configuration file' instead of just trying to connect to non-sense data and fail.
