### ISSUE TITLE
Is it possible to use knex without an actual connection?

### ISSUE THREAD

**Issue by juanjoLenero** [tgriesser/knex#983]
Would it be possible to use knex just for the query building features i.e. just to generate sql strings?

**Comment by rhys-vdw** [comment]
Yes. It is possible. Either give an empty object for the config options, or provide a `client` for a dialect.

```js
knex = require('knex')({});
pg = require('knex')({});

knex('table').insert({a: 'b'}).returning('*').toString();
// "insert into "table" ("a") values ('b')"
pg('table').insert({a: 'b'}).returning('*').toString();
// "insert into "table" ("a") values ('b') returning *"
```

This should really be noted in the [Initializing the Client](http://knexjs.org/#Installation-client) section of the docs. I'd appreciate a PR updating index.html if you're up for it.

**Comment by juanjoLenero** [comment]
@rhys-vdw Sure thing. #986

**Comment by nrl240** [comment]
Hello!

I am trying to simply build a SQL query string as illustrated earlier in this issue; however, I am getting the following error:

> ./node_modules/knex/lib/dialects/mssql/index.js
> Module not found: Can't resolve 'mssql/package.json' in '/Users/noelle/PorterAndSail/segmentation-tool/node_modules/knex/lib/dialects/mssql'

As soon as I add `const knex = require('knex')({});`, I get the error.

Thanks in advance.

**Comment by Davorak** [comment]
Heads up,
```.js
var knex = require('knex')({});
```
Stopped working after 0.12.6 as far as I can tell.  After that version you get an error like:
```.bash
> var knex = require('knex')({})
Error: knex: Required configuration option 'client' is missing.
    at new Client (/Users/pjw/node_modules/knex/lib/client.js:108:11)
    at Knex (/Users/pjw/node_modules/knex/lib/index.js:60:34)
```

Similar issue https://github.com/tgriesser/knex/issues/2090 suggests:
```.js
const knex = require('knex')({ client: 'pg' });
```
but warns its likely not future proof.

**Comment by elhigu** [comment]
> const knex = require('knex')({ client: 'pg' });

That is supported... no need for passing connection details and that is a feature which is planned to be kept.

**Comment by jgoux** [comment]
Hi, sorry for bumping into this old issue. 😅 

Why is `knex.connection()` not available using this initialization approach? It would be handy to be able to create a knex instance with only an external connection.

My use-case is to use knex in my postgraphile environment. Postgraphile provides an instance of pg's connection with an open transaction, so if I could pass this to knex and have my client that would be awesome!
Right now I can use it as a query builder only and pass the compiled sql to the pg client.

**Comment by elhigu** [comment]
> Why is knex.connection() not available using this initialization approach? 

Is it not? Did you try?
