### ISSUE TITLE
`table.unique(columns)` is undocumented.

### ISSUE THREAD

**Issue by jsumners** [tgriesser/knex#988]
In the following migration, an error will be thrown: "Knex:warning - migrations failed with error: Cannot read property 'length' of undefined". This error occurs when it tries to build the column list in `Formatter.prototype.columnize`.

``` javascript
exports.up = function up(knex) {
  return knex.schema
    .createTable('roles', function createRoles(table) {
      table.increments('id');
      table.string('name').unique().notNullable();
      table.timestamp('created_at', true).defaultTo(knex.raw('now()')).notNullable();
      table.timestamp('updated_at', true).defaultTo(knex.raw('now()')).notNullable();

      return table.comment('Roles that can be used for permissions');
    })
    .createTable('people', function createPeople(table) {
      table.increments('id');
      table.string('given_name').notNullable();
      table.string('surname').notNullable();
      table.string('email').unique().notNullable();
      table.string('username').unique().notNullable();
      table.timestamp('created_at', true).defaultTo(knex.raw('now()')).notNullable();
      table.timestamp('updated_at', true).defaultTo(knex.raw('now()')).notNullable();

      return table.comment('Every user with authenticated access to the CMS');
    })
    .createTable('person_roles', function createPersonRoles(table) {
      table.integer('person_id').references('id').inTable('people');
      table.integer('role_id').references('id').inTable('roles');

      // this causes the error
      table.primary(['person_id', 'role_id']).unique();

      // this will "resolve" the error
      // table.primary(['person_id', 'role_id']).unique(['person_id', 'role_id']);

      return table.comment('Joins people to their roles');
    });
};
```

Sure, it's probably silly to add the unique characteristic on that key. But the docs don't even indicate that columns can be passed in to the unique function, and the error should really be trapped.

**Comment by rhys-vdw** [comment]
API wise: the only issue I see here is that you shouldn't be able to chain `unique` off `primary`. As I understand there are two uses of `unique` - the documented one (that adds a unique constraint to a column declaration). And using it on its own and passing columns to enforce a unique constraint.

> Sure, it's probably silly to add the unique characteristic on that key.

Primary keys are always unique, but I assume you know that.

> But the docs don't even indicate that columns can be passed in to the unique function

This is a problem. I'm leaving this issue open in the hopes that we get a PR on this one.

>  ...the error should really be trapped.

Trapped how? With default settings migrations now run in a transaction, which should have been rolled back.

**Comment by jsumners** [comment]
> Trapped how? With default settings migrations now run in a transaction, which should have been rolled back.

It should throw a decent error message so that users of the API aren't forced to step through it with a debugger to figure where the bad array access is happening (and why). It's as simple as:

```javascript
if (!columns) {
  throw new Error('Missing columns when building SQL statement. Did you forget to pass columns to a column method?');
}
```

**Comment by rhys-vdw** [comment]
Ah, @jsumners, true. Better yet, something like this:

```js
if (!_.isArray(columns)) {
  throw TypeError(`expected an array, got "${columns}"`);
} 
```

I'll accept a PR for that too. :+1:

**Comment by jsumners** [comment]
I've done as much as I have time for by reporting what I discovered.

**Comment by rhys-vdw** [comment]
Sure, I'll leave the issue open.

**Comment by jocull** [comment]
I just used this today off `table` without any problems, so it'd be nice to see it in the docs.

**Comment by rhys-vdw** [comment]
If you feel the documentation is lacking, please open a PR with suggested
changes.

**Comment by kapouer** [comment]
The documentation is still a bit being, the actual signature being
`table.unique(columns, constraintName)`

**Comment by kibertoad** [comment]
Documentation was updated to state `unique — table.unique(columns, [indexName])`, so this seems to have been resolved.
