### ISSUE TITLE
Knex use Prepare Statements?

### ISSUE THREAD

**Issue by dschinkel** [tgriesser/knex#989]
Does Knex allow Prepare statements for postgreSQL?

**Comment by pasupulaphani** [comment]
Looks like it is in the roadmap. Couldn't find anything in Knex docs on this yet.

**Comment by elhigu** [comment]
Basically it does not support them. Postgre dialect sends every query as a prepared statement to DB, but it does not re-use them either even the same query is sent multiple times in the same connection.
