### ISSUE TITLE
JSON vs JSONB - type default in schema builder

### ISSUE THREAD

**Issue by light24bulbs** [tgriesser/knex#991]
Should JSONB be changed to the default type in the JSON schema builder?  I'm having some truly wacky results with JSON and realized I should have been using JSONB.  Postgres docs recommends it as the default choice for most applications.  

In the interest of abstracting away from weird database quirks wherever possible, do you think JSONB should be the default?

**Comment by light24bulbs** [comment]
Hm actually this is probably left in as legacy support for everyone still running postgres 9.3 huh?  It makes sense that the new type would be an opt in feature if it isn't widely supported.

**Comment by rhys-vdw** [comment]
I think it's reasonable to leave the responsibility of this decision to the users of knex, much as Postgres does for its users. Also what would you call the `json` type? `legacyJson`? Could cause more confusion.

**Comment by elhigu** [comment]
Could it be more clear to use if knex would have separate `json` and `jsonb` column types? They are quite different types with different behaviour and operators.

Current way of having to create `jsonb` column by setting it with boolean parameter is a bit awkward. It is like making `biginteger` column by creating `integer` column with extra boolean flag that says "this is actually biginteger column".

**Comment by light24bulbs** [comment]
Hmm, I agree.  That's a small thing (no big deal) but it would make it more
explicit.  Especially for people maintaining the migrations later on.

On Tue, Sep 29, 2015 at 12:57 PM, Mikael Lepistö <notifications@github.com>
wrote:

> Could it be more clear to use if knex would have separate json and jsonb
> column types? They are quite different types with different behaviour and
> operators.
>
> Current way of having to create jsonb column by setting it with boolean
> parameter is a bit awkward. It is like making biginteger column by
> creating integer column with extra boolean flag that says "this is
> actually biginteger column".
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tgriesser/knex/issues/991#issuecomment-144171091>.
>



-- 
-Forrest

**Comment by rhys-vdw** [comment]
@elhigu, @light24bulbs: I also agree, will accept a PR adding `jsonb` column type to schema builder and adding deprecation message to `schema.json` when using boolean flag.

**Comment by elhigu** [comment]
Fix didn't include deprecation message since it was most straight forward implementation which just calls `this.json(name, true)`
