### ISSUE TITLE
Update / Where clause, Column default value

### ISSUE THREAD

**Issue by wubzz** [tgriesser/knex#996]
I don't know about mysql, oracledb, maria, etc, but in Postgres you can run:

```sql
CREATE TABLE accounts(
id serial,
name NOT NULL DEFAULT ''
);

INSERT INTO accounts(name) VALUE('Test');

UPDATE accounts SET name = DEFAULT;
```

And it will set "Name" from "Test" -> "''".

The idea came up in relation to a new feature for an API, where you should be able to send "API_SET_BLANK" in order to blank (or set default) of a field in the database. Example:
```javascript
{
		"Accounts": [
			{
				"id": 1,
				"name": "API_SET_BLANK"
			}
		]
	}
```

Is there currently anyway to utilize this behaviour in knex? Preferably without using a knex.raw instance. If not, would you consider accepting a PR for this?

**Comment by elhigu** [comment]
How about 
```js
knex('accounts').update({ name: knex.raw('DEFAULT') }).where('id',1)
``` 
it outputs 
```sql
update "accounts" set "name" = DEFAULT where "id" = 1
```` 

It has `knex.raw()`, but really small one :)
