### ISSUE TITLE
using ES7 async/await in migrations

### ISSUE THREAD

**Issue by indeyets** [tgriesser/knex#997]
I wonder if it is possible to use babel in "knex" cli-tool. some kind of optional dependency, maybe? or just ability to specify custom init-file, which would be run before migrations are imported

this would allow using ES7 await/async instead of raw promises in migrations. readability of await-code is much better than of then-chains :)

**Comment by indeyets** [comment]
ok, nevermind. I did it with adding `require("babel/register")();` to knexfile

**Comment by CreepGin** [comment]
Thanks for the pointer on `knexfile.js`. I'm now using the following for taking care of both typescript and babel.

```js
require('ts-node/register');
require('babel-core/register');
require("babel-polyfill");
```
